### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#1007]
I was looking for any documentation on how to create custom reports?

**Comment by eeintech** [comment]
@lookme2 Which type of reports? There is a bit of documentation on `Test Reports` on here: https://inventree.readthedocs.io/en/latest/report/test/

But I have to concede I've never used those kind of reports before. What's your use-case?

**Comment by lookme2** [comment]
@eeintech sorry for the late reply.  I don't really have a use-case at this time.  I was just poking around and saw this and was wondering how it worked.  I will close this.
