### ISSUE TITLE
Update failing. 

### ISSUE THREAD

**Issue by WeredPerson** [inventree/InvenTree#1012]
When running invoke update I get the error below. I'm not sure what additional arguments its looking for and I couldn't find anything in the docs for this. 

https://inventree.readthedocs.io/en/latest/start/update/

root@server:/var/www/html/inventree# invoke update     
'update' did not receive all required positional arguments!

**Comment by SchrodingersGat** [comment]
That's a weird one. There should be no positional arguments required.

Are you up to date with the latest code? 

Running `invoke update` works for me on latest master (checked just now)

**Comment by WeredPerson** [comment]
All up to date. I think Il try a clean install and see what happens.

**Comment by WeredPerson** [comment]
Installing a fresh copy didn't work on that server, it was running Ubuntu 18.04. I spun up a new Ubuntu 20.04 container copied over the original install and it worked fine there, so it was something with that container.

**Comment by SchrodingersGat** [comment]
Might have been a weird version of invoke? Glad you got it working anyhow
