### ISSUE TITLE
Additional tool - PartKeepr to InvenTree

### ISSUE THREAD

**Issue by rgilham** [inventree/InvenTree#1032]
I've been using PartKeepr for a number of years and did not want to repopulate the database in InvenTree, 
So I created a script to migrate parts and categories to InvenTree.
It uses the PartKeepr REST API and the InvenTree python interface

I tried to generate the locations from the PK information but the Location requires a parent which is not always the case.
It also transfers over the stock number but not the pricing from PK.
I wanted to delete the parts in the Inventree database but this can't be done using the python interface because it is not possible to make the park inactive. I had to modify the sqlite database.

The script is here:
https://github.com/rgilham/PK2InvenTree
You are welcome to add it to the 3rd party tools.

**Comment by eeintech** [comment]
> I wanted to delete the parts in the Inventree database but this can't be done using the python interface because it is not possible to make the park inactive.

You can actually do it this way:
```
api = InvenTreeAPI('http://127.0.0.1:8000/', username='username', password='password')
part = Part(api, 10) # Replace 10 with part pk/id
if part:
	part._data['active'] = False
	part.save()
	part.delete()
```

**Comment by rgilham** [comment]
Great to know, I almost had it. I tried to do part.active = False


I have updated to script.


Robin

**Comment by eeintech** [comment]
> I tried to generate the locations from the PK information but the Location requires a parent which is not always the case.

I don't think this should be the case, can you open an issue here with your code snippet: https://github.com/inventree/inventree-python/issues

**Comment by SchrodingersGat** [comment]
@rgilham what a great tool! As @eeintech says above both the issues you are having with the scripts should be addressable.

**Comment by SchrodingersGat** [comment]
https://inventree.readthedocs.io/en/latest/extend/integrate/#pk2inventree

**Comment by eeintech** [comment]
@rgilham Thanks again for sharing the tool, it was added to InvenTree third-party tools.
Could you do me a favor and close this issue?

If you have any other suggestion/question regarding the python interface, you can post them here:
https://github.com/inventree/inventree-python/issues
