### ISSUE TITLE
Staff status role

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1034]
Been wondering how to consider the "Staff" status role:
- should Staff status provide user with automatic add/change/delete permissions on all objects?
- is the Staff status to control only access to the Admin views/interface?

**Comment by SchrodingersGat** [comment]
In django terms, a "staff" user is a user that has permissions to access the admin interface. I think there could definitely be a reason to allow "staff" users who can administrate certain tables but not others, or edit (but not create or delete) others..

I do not think that it makes sense to artificially limit this be enforcing that a staff user has all permissions granted automatically.

**Comment by eeintech** [comment]
@SchrodingersGat I understand the original idea but in practice and in InvenTree's scope, I find it a bit confusing.

As a "staff" user, when I scroll though the Admin interface, it's nice to be able to see things like `Users` and `Groups` which otherwise don't show in the main interface. But for any other model, I don't see much value of doing operations in the admin when the main interface already has that functionality, maybe except for mass import of data.

My feeling is that the "staff" status is a weird middle child, stuck between the super user and normal InvenTree users associated to roles with most write capabilities. However, there might be useful use-cases of the "staff" status I'm not seeing.
