### ISSUE TITLE
server time issue

### ISSUE THREAD

**Issue by bgrant85** [inventree/InvenTree#1035]
As a newbie, I know this is a lack of knowledge on my part but some guidance would be appreciated.
I've setup Inventree using Postgresql and its working well so far, except that on certain pages such as "Add Purchase Order" in the date/time field it shows this little note that says "Note: You are 5 hours behind server time".  This seems like its something I need to fix but I have no idea what it means or  how to fix.
When I installed Postgresql and created the database, originally I did not issue a command to set timezone to UTC.  In attempt to fix this problem, I went back and issued a command ALTER ROLE db_user SET timezone TO 'UTC'; and restarted the service, but nothing seemed to change.
Can someone explain the problem and/or suggest a fix?
Thanks.

**Comment by SchrodingersGat** [comment]
Hey @bgrant85 can you please provide a screenshot of where you are seeing this message?

**Comment by SchrodingersGat** [comment]
Ah, I've worked out why you are seeing that.

I've just [added timezone support](https://github.com/inventree/InvenTree/pull/1037)

1. Update InvenTree - https://inventree.readthedocs.io/en/latest/start/update/
2. Edit `config.yaml` add the following lines:

```
# System time-zone (default is UTC)
# Reference: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Select an option from the "TZ database name" column
timezone: your/timezone
```

3. Restart the server

Then you should no longer see the message!

**Comment by bgrant85** [comment]
seems to have fixed it.  Thanks.
