### ISSUE TITLE
Method to extract Default Location from API?

### ISSUE THREAD

**Issue by rco3** [inventree/InvenTree#1039]
Either in the Part creation or in Category creation through the Django interface, a Default Location can be set.  Through the API, I know how to neither query nor set that default location. When adding new Parts or StockItems through the API, it would be nice to set the location to the Default for the Category or Part automatically.

Is there a method via API for finding this Default Location that I'm missing?

This is, for me, the last piece of the puzzle for scanning a bag barcode from existing inventory to new StockItem (and SupplierPart, MFG, Part as necessary).  It's working without Location for now - I've added several already. Thanks again, @SchrodingersGat.

**Comment by eeintech** [comment]
@rco3 The Default Location field was missing in the API, I just added it. Once it is merge you will be able to query/edit it like other Part fields using the API.

**Comment by rco3** [comment]
Perfect.  Thanks, @eeintech.

**Comment by rco3** [comment]
Hey, shouldn't the same thing be done to the Category serializer?

**Comment by eeintech** [comment]
@rco3 Good catch, I'll add it 👍

**Comment by rco3** [comment]
Thanks, @eeintech .  I've added that in both places in my existing installation, works fine.

**Comment by SchrodingersGat** [comment]
@rco3 I have also added an additional feature here - https://github.com/inventree/InvenTree/pull/1049

**Comment by rco3** [comment]
Handy.  Had that been in place, I might not have looked for Location in the API response.

Thanks, @SchrodingersGat.

**Comment by SchrodingersGat** [comment]
I think both solutions here are useful in their own right 👍
