### ISSUE TITLE
Improve api authentication documentation

### ISSUE THREAD

**Issue by amishHammer** [inventree/InvenTree#1042]
There are many methods to do 'token based authentication'  it would be good if it was documented that you want an authorization header based token.  I had to work this out by reading the python client code as it's not spelled out in the documentation here:  https://inventree.readthedocs.io/en/latest/extend/api/#authentication

```
        if self.use_token_auth and self.token:
            headers['AUTHORIZATION'] = 'Token {t}'.format(t=self.token)
            auth = None
```

**Comment by eeintech** [comment]
@amishHammer Please open an issue in the documentation repo: https://github.com/inventree/inventree-docs/issues

**Comment by amishHammer** [comment]
Done
