### ISSUE TITLE
FreeBSD Install Method

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#1046]
Hey, I just installed a clean version on my FreeBSD system in a jail. I ran into some issues since it has switched to invoke over make. Here is what I needed to do in addition to what was in the installation instructions. Incase anyone else is trying.

```
pkg install python
pkg install py37-pip
pkg install py37-wheel
```
Then in order to get `invoke install` to work I `ln -s /usr/local/bin/bash /bin/bash` and `ln -s /usr/local/bin/pip /usr/local/bin/pip3`

After that it all seems to be running just fine.

If you people know more about freeBSD then I do and have a better/easier was to achieve an install let me know.

Thanks!

**Comment by SchrodingersGat** [comment]
@a7hybnj2 thanks for relaying this information. I'll add this information to the installation instructions. I have no experience on FreeBSD. Cheers
