### ISSUE TITLE
Sort by Column in Stock screen?

### ISSUE THREAD

**Issue by watarat** [inventree/InvenTree#1057]
Have installed Inventree in VM in Ubuntu 20, under Win10.
Fabulous!! - Have entered about 50 parts and finding the logic fantastic - thanks!
When I view _**Stock**_ - and click header row to sort by IPN or Part or Description, nothing changes.
(I'm preparing labels for stock containers)
Its strange - because the Stock (qty) column does sort..
In the **_Part_** screen, all headers are functional.
django is all new to me, and I've dug down to ../inventree/InvenTree/templates/js/stock.html but nothing leaps out at me.
Perhaps there is something in my setup that I'm missing?

**Comment by SchrodingersGat** [comment]
That's an odd one - I've just checked on my install and all of the columns in the **Stock** table are sorting properly. Can you provide a screenshot or similar to demonstrate exactly what you are seeing?

**Comment by watarat** [comment]
Yep- find it hard to believe this wouldnt have been caught already.. :)
After sorting on Stock Qty up, attempt at sort down on IPN (purple arrow on IPN header)
![Clipboard03](https://user-images.githubusercontent.com/8358937/96525324-1fb76480-12c2-11eb-9dff-a9c92829eb03.jpg)
Attempt at sort up on IPN - no change
![Clipboard02](https://user-images.githubusercontent.com/8358937/96524726-95bacc00-12c0-11eb-9884-941b51040f9c.jpg)
Then sorting on Stock Qty down changes order (works)
![Clipboard01](https://user-images.githubusercontent.com/8358937/96524571-3361cb80-12c0-11eb-8f74-0741881ea4de.jpg)

Behaves the same on firefox within hosting VM, and via Chrome from external Win 10

**Comment by rco3** [comment]
I see similar behavior in Safari and Firefox under Mojave.  Odd bit: any Parts with multiple StockItems sort together when I sort by Part, and the rest in no discernable order. Same for sort by IPN, Description, whatever.  If I sort by Stock, those are no longer together, but the sort order is still not correct.

**Comment by SchrodingersGat** [comment]
Fixed it! This was a really weird one, to do with how javascript objects are accessed by name. It was a two-part problem.

Firstly, the field names did not match the data delivered via the API

Secondly, multi-level object lookup is tricky if the lookup string contains a `.` character.

The linked fix should make the sorting much better all round.

**Comment by watarat** [comment]
So to update to latest - I followed 
$ git pull origin master
$ invoke update
Which failed as per below.
I can see some changes in the file ../inventree/InvenTree/common/migrations/0008_remove_inventreesetting_description.py which I suspect are relevant - but not up to speed on why.
(I'm running on a dev sqlite3 database as per the getting stared path:)  )

![Clipboard01](https://user-images.githubusercontent.com/8358937/96529183-04e9ed80-12cc-11eb-802b-48aa217d5880.jpg)

**Comment by eeintech** [comment]
@watarat Can you open a new issue and we can debug this? (If you haven't solved it already)

**Comment by SchrodingersGat** [comment]
@eeintech this has actually already been fixed in https://github.com/inventree/InvenTree/pull/1061 👍
