### ISSUE TITLE
BOM Showing Two Prices When Only One Price Has Any Quantity

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#1059]
I have a BOM with a sub-part that has three items but two of the items have a quantity of zero (0). Here is the BOM:
![image](https://user-images.githubusercontent.com/18520951/96531014-b77f6900-1256-11eb-8531-0ed2ff6b9e6f.png)
The item in question is the last line of the BOM screenshot.
And here is the sub-part:
![image](https://user-images.githubusercontent.com/18520951/96530580-bb5ebb80-1255-11eb-895d-7a60b5d661f3.png)
How do I fix this so there is only one price showing?
--Larry

**Comment by LarryJoy** [comment]
The BOM of the original post shows the wrong sub-part. Here is the same BOM with the correct sub-part item, again the last line of the screen shot:
![image](https://user-images.githubusercontent.com/18520951/96531793-696b6500-1258-11eb-8d0f-fde1ef6d68c8.png)
--Larry

**Comment by SchrodingersGat** [comment]
@LarryJoy under the part detail view for **10049-104**, what is in the *Suppliers* tab?

I suspect that there multiple prices from different suppliers...

**Comment by LarryJoy** [comment]
Here is the Suppliers tab:
![image](https://user-images.githubusercontent.com/18520951/96600698-34dec400-12bf-11eb-99f7-65cb0ede917d.png)
Yes, there are three suppliers with each having a price breakdown of 1 @ whatever $ price per each USD. However, see my original post that shows the Stock tab wherein the first two items have a quantity of zero (0) and a notation of "Depleted". Why is InvenTree picking up the price for the zero quantity items and what do I need to do to make it work correctly? I would say that this is a bug in the program.
--Larry

**Comment by eeintech** [comment]
@LarryJoy The price breaks still apply regardless of the quantity you have in stock (eg. one may still want to use the cheaper part in the BOM, and be aware about it). With a single supplier part, you would get one single price. It is not a bug, it's by design.

**Comment by LarryJoy** [comment]
Okay, I understand your reasoning. However, by the time I would go back to purchasing from supplier(s) with present zero stock in inventory, the price is most likely to be different, and most likely would be an increase in price. As I see it I would have to keep a separate spreadsheet of the BOM to figure single prices for the sub-parts for figuring the cost of materials (COGS) to credit the Inventory account. How does your company handle this accounting?
--Larry

**Comment by eeintech** [comment]
> However, by the time I would go back to purchasing from supplier(s) with present zero stock in inventory, the price is most likely to be different, and most likely would be an increase in price.

This would be the case for **any** supplier part, not only part with no stock.

One way to always have up-to-date price breaks would be to pull those from your supplier (API / web scrapping) and push them to InvenTree via the API or [Python interface](https://github.com/inventree/inventree-python).

For [Ki-nTree](https://github.com/sparkmicro/Ki-nTree/) I am actually planning on pulling price breaks from Digi-Key and adding them to the supplier part. As for keeping those synced to Digi-Key, I have not put too much thoughts on that yet.

**Comment by LarryJoy** [comment]
Okay, you didn't answer the question of how your company keeps track, so it looks like it would be a bunch of manual calculations using a separate spreadsheet.
--Larry

**Comment by eeintech** [comment]
> you didn't answer the question of how your company keeps track

I work with different companies and processed are done differently. For the one that use InvenTree, we don't have pricing with our setup yet.

**Comment by SchrodingersGat** [comment]
Pragmatically, the only way to keep the prices of supplier parts synced is to periodically change the prices in the SupplierPart objects to match the *actual* price.

This *could* be done programatically with access to an API for an external supplier (e.g. DigiKey)

You could have a script which periodically queries the external supplier for pricing information on each part supplied by that supplier. This would vary from supplier to supplier, and would be a lot of work to implement (but would certainly be possible!)

Obviously you could also manually update pricing, but this gets very tedious.

If there's a third option I'm not considering, please let me know.

**Comment by LarryJoy** [comment]
@SchrodingersGat I don't understand why you would want to sync the price in the SupplierPart object as the current pricing would only be used when issuing a purchase order and does not affect the cost of the part presently in stock/inventory. Let's go through an initial cycle:
•You set up an engineering/design BOM in a spreadsheet and then produce a manufacturing/purchasing spreadsheet.
•You look at suppliers and pricing and enter this information in the purchasing spreadsheet.
•You order the parts.
•When the parts come in you take the cost of the parts and add the cost of shipping, handling, taxes, tariffs, etc., as applicable, for each part. (I have a small spreadsheet program that I enter the costs in and it does the math.)
•You take the revised, increased, cost of each part and enter it into the InvenTree Stock information.
•When you do an InvenTree BOM the total cost calculated for the part/assembly becomes the cost of the material or Cost of Goods Sold (COGS) and this amount would be a credit to the Inventory account, which lowers the value of the Inventory.
•I use the First In First Out accounting method and so the cost/price of each part stays the same until depleted.
When it comes to reorder time:
•You don't use the InvenTree Source pricing because it pertains to what you have in stock. Your Purchase Order has to be the supplier's current pricing.
•And again, when the parts come in you have to figure the total cost for the part and enter the information as a separate line item in the SupplierPart object.
Anyway, that is how I see it.
@LarryJoy

**Comment by SchrodingersGat** [comment]
@LarryJoy I think you have outlined a shortcoming of what the InvenTree system currently does.

Prices are tracked against each `SupplierPart` which should track how much a certain part costs at a given quantity. However, when you actually buy the parts (with a purchase order) the system **does not** track how much you actually paid for that particular StockItem.

I think this would be a very important thing to do, then you can actually know the cost of stock-on-hand

I have [opened a new issue](https://github.com/inventree/InvenTree/issues/1075) to implement this feature.

**Comment by SchrodingersGat** [comment]
@LarryJoy InvenTree can now track the purchase price of individual stock items as outlined in the linked issue above.

Has this issue been addressed to your satisfaction?

**Comment by LarryJoy** [comment]
@SchrodingersGat Just wanted to acknowledge that you have revised the program and that it will take me a few days to work through the update to see how it is working. I'll report back later.
--@LarryJoy

**Comment by LarryJoy** [comment]
@SchrodingersGat I updated my InvenTree and it is now at V 0.1.5 pre. I have several questions on how this works now.
>All of my parts I entered previously with a price break of one at a total cost per each (listed cost plus shipping, handling, taxes, tariffs, etc. as applicable). Is this the proper way to do it? There are other price breaks. To see the total cost of a BOM you go to the $ icon, which has Part Pricing and then Unit Cost with a Min and Max amount. Okay, I understand that comes from multiple suppliers with different costs.
•You build an assembly and put it in Finished Goods. Where do you go to find or enter the cost of the assembly? For me it is just the cost of the parts but for others they are going to want to add the allocated cost of manufacturing.
•For a BOM that I have there is the price column that shows one price "to" a second price. If I only want one price how do I do that? For instance if I have an assembly that uses a qty of 4 of an item (sub-part) and I have a qty of 2 at one price and a qty of 10 at another price I would figure the price per each for 4 parts that would be equal to 2 times the first price plus 2 times the 2nd price. Leaving a qty of 8 at the 2nd price.
>Where do I go or what do I do to find the total cost of inventory?
--@LarryJoy

**Comment by eeintech** [comment]
> You build an assembly and put it in Finished Goods. Where do you go to find or enter the cost of the assembly? For me it is just the cost of the parts but for others they are going to want to add the allocated cost of manufacturing.

@SchrodingersGat I don't think there is a way to merge parts price tag during purchase order to build order and automatically associate a final price tag to assembly when created as a stock item?

> For a BOM that I have there is the price column that shows one price "to" a second price. If I only want one price how do I do that? For instance if I have an assembly that uses a qty of 4 of an item (sub-part) and I have a qty of 2 at one price and a qty of 10 at another price I would figure the price per each for 4 parts that would be equal to 2 times the first price plus 2 times the 2nd price. Leaving a qty of 8 at the 2nd price.

@LarryJoy I'm not quite sure what is that you are trying to see/solve here... Oliver implemented BOM inheritance recently, have you had a look?

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat I don't think there is a way to merge parts price tag during purchase order to build order and automatically associate a final price tag to assembly when created as a stock item?

I'm having trouble understanding what you are asking here - can you expand on this a bit for me?

**Comment by eeintech** [comment]
Sure sorry I just re-read myself and indeed it's confusing.

I was trying to say is:
* Part A and B price is set from purchase order
* Part C (assembly) BOM uses both Part A & B and gets built/stocked using a build order
* Can we get the price of part C be linked to Part A & B from the original purchase order?

That would basically be considered a costed BOM, but from purchase order price data instead of supplier part data.
And it would be for the stock of Part C, not the part itself.

**Comment by SchrodingersGat** [comment]
Ah, the "cost of manufacture" of that stock item, or the "sum of component costs". That makes sense.

Will be pretty complex to implement, I think. But I think it would be a good thing to implement.

**Comment by eeintech** [comment]
Those are the right words, yup.

However I think this goes out of the scope of this issue, I would request @LarryJoy to open a new one if still interested in this feature.

**Comment by matmair** [comment]
@LarryJoy does this error still occur with the current stable/master?
