### ISSUE TITLE
Windows installation venv

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [inventree/InvenTree#1062]
Hi, on windows, python venv should be activated using these commands:

py -m venv inventree-env
.\inventree-env\Scripts\activate

You could update manual in order to ease installation on windows (regarding to https://inventree.readthedocs.io/en/latest/start/install/)

source is here https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/

**Comment by eeintech** [comment]
@WhiteChairFromIkea Thanks, added!
