### ISSUE TITLE
Large Example Data for first time users

### ISSUE THREAD

**Issue by cdplayer** [inventree/InvenTree#1067]
I have successfully installed but have no example data. As a new user testing I would very much like (my) first install to have an extremely large parts and user database. Something akin to 12000+ parts and other data as if 20-50 users were using it for at least 18 months. Definitely not after small data set. Apologies if i've overlooked this in the documentation. I have lots of questions and suggestions, is there a discord server?

**Comment by SchrodingersGat** [comment]
Hey @cdplayer it would be great indeed to have a large test dataset for new users to play around with. It would however be a lot of effort to set this up, and other development priorities have taken precedence. At this stage, no such data set exists.

> I have lots of questions and suggestions, is there a discord server?

The best place to raise issues and discussions is here on GitHub - we do not have a discord or other discussion channel. At this stage there's only really a couple of developers at the moment (with limited time available)

**Comment by SchrodingersGat** [comment]
This has now been addressed, see here - https://inventree.readthedocs.io/en/latest/start/demo/
