### ISSUE TITLE
Code formatting style guide

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1068]
Look at options for checking (and enforcing) coding style guide

- UPPERCASE_FOR_SOME_STUFF
- e.g. camel case (or other options) for variables / functions / classes
- tools for automated checking of code
- Add "contributing.md" file

**Comment by jnewlands** [comment]
Popular formatters

- [black](https://github.com/psf/black)
- [yapf](https://github.com/google/yapf)

**Comment by eeintech** [comment]
https://github.com/inventree/InvenTree/pull/651

I'm not a big fan of black, too opinionated IMO.
yapf seems more flexible, have to give it a shot!

**Comment by eeintech** [comment]
@SchrodingersGat @jnewlands I played a bit with `yapf` over on my fork: https://github.com/eeintech/InvenTree/tree/yapf_test

I've ran the yapf formatter with standard settings on all Python files in the `part/` folder and `flake8` only reported 3 issues.
The concern is that among those 3 issues, 2 of them are conflicts between `flake8` rules and `yapf` formatting (the last one was a  `flake8` internal conflict). But I guess this will be the case with any code formatter out there, unless there is a formatter out there is developed by the same team as `flake8`, not sure...

I do like the [flexible settings](https://github.com/google/yapf#knobs) of `yapf` and would prefer it over `black`.

I think with with a couple hours, InvenTree's entire code base could be formatted using `yapf` and passing CI.
What do you think, worth the push into this direction?
