### ISSUE TITLE
Add "multiple BOM" option

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1078]
Under certain circumstances there are reasons for a buildable part to have multiple BOMs.

So when a BuildOrder is created, the user can select from multiple available BOMs (if provided for that part)

**Comment by eeintech** [comment]
> Under certain circumstances

I'm curious to know which are the circumstances driving this idea.

I'm really attached to the **one BOM per part relationship**, it's easy enough to make a part variant and replace some BOM items then use the variant for the build instead.

On the other hand, InvenTree is lacking a revision system (hasn't been implemented yet). It would be nice to be able to store one BOM per revision for the same part and be able to switch between those revisions and BOMs directly from the part detail page and when creating the build. This would make the "multiple BOM" per part available in a sleek manner.

**Comment by eeintech** [comment]
Isn't it what "variant" parts are for? It seems like the perfect use-case to me, at least that's how I planned on using them.

I still don't see the appeal and I feel like it's adding complexity to solve a problem which can already be solved with the current features, maybe at the expense of little more setup (eg. create Part variant vs create BOM variant).

**Comment by eeintech** [comment]
@SchrodingersGat Coming back to this discussion, I backtracked on my previous comment and think it would be great if we introduced a **variant** management system to part's BOM, in addition to part variants (which have use cases in certain type of inventories).

I changed my mind after seeing more complexity introduced into my company database, the term "BOM variant" makes a lot of sense now.

**Comment by eeintech** [comment]
@matmair Ha that's old, in our company we can function without it.

**Comment by SchrodingersGat** [comment]
The "multiple BOM" concept is probably not something worth pursuing any longer.
