### ISSUE TITLE
Define metadata fields in part, edit them in stock items

### ISSUE THREAD

**Issue by jnewlands** [inventree/InvenTree#1079]
Further improving my issue to contribution ratio:

Similar to how there are parameter template fields in the InvenTree wide settings (for example, defining 'resistance' as a parameter globally then makes it available in), it would be useful to do the same for the relationship between parts and stock items (my specific use case is to track anodised parts).

Further it would be useful to be able to add arbitrary requirements to BOM lines (e.g. part=X, anodised=True).

Even better is if changes to these parameters were also traceable.

**Comment by matmair** [comment]
@SchrodingersGat this sounds a bit like #3108 -should we merge them?

**Comment by SchrodingersGat** [comment]
@matmair this is distinct, I actually worked with @jnewlands on this concept back in 2020 but this approach ended up getting replaced by the "test results" concept. I think this issue can be closed out now.
