### ISSUE TITLE
Assign default Parameter Templates by Category

### ISSUE THREAD

**Issue by rco3** [inventree/InvenTree#1083]
For example, Category: Capacitors might be assigned (e.g.) Capacitance in Farads, Voltage in Volts, etc. When a new Part is created in that Category, it would be lovely to either 

a) automatically add a new Parameter for each Default Template assigned to Parts in this Category, with value = NULL unless otherwise assigned, or

b) at Part creation, offer to add aforementioned Parameters but only do so for those Parameters for which the user supplies a value. (probably the most flexible method)

From the API, a method might be added to report all of the default Parameter Templates assigned to a Category, so that they may be added programmatically, and another to assign a default Parameter Template to a new or existing Category.  When creating a Part and assigning a Category, the remote system can then retrieve all of the expected Parameters for that Category and assign values (or not) as appropriate.

**Comment by eeintech** [comment]
@rco3 I agree with you, this would be a sweet setup.

With [Ki-nTree](https://github.com/sparkmicro/Ki-nTree/), I'm doing this:
1. load a [configuration file](https://github.com/sparkmicro/Ki-nTree/blob/master/config/digikey/digikey_parameters.yaml) (YAML) which contains all parameters related to each category (and their mapping to Digi-Key parameter naming)
2. create all parameters found in the list under the defined category
3. fill out all the parameters values using parsed Digi-Key API response.

Off-loading step 2 to InvenTree would make sense, the list of parameters for each category could be added to the InvenTree part settings.

**Comment by SchrodingersGat** [comment]
Agreed this would be a great feature to add.

**Comment by rco3** [comment]
I'm impressed with Ki-nTree, BTW.  I have been doing a lot of barcode decoding work, if you think there's some value in adding that capacity to Ki-nTree and would like some good examples of bad ways to do it. There's a few places I can't figure out how to eliminate some ambiguities, but... well, anyway.

I was going to skip #1 by simply using the same names for my Parameters as the Digi-Key Parameter names, and look for matches when I add a new Part.

It does bring up a question of sorting, though.  How do we handle sorting values for, e.g., capacitors in the Parametric table? Value in decimal Farads? Decimal µF? Integer pF?  Or is Inventree units/suffixes-aware and I didn't realize it?  I was thinking about using the [engineering-notation](https://pypi.org/project/engineering-notation/) module for converting to a common base unit (e.g., µF) when I populate a given Parameter, but that's still a LOT of zeros somewhere for caps.  Or multiple columns for the same Parameter in the table...

I've added a bunch of parts already without Parameters, so I'll probably end up banging a quick script to sweep through those and pull Parameters from DK.  I can hardcode the Parameters I want and just do one Category at a time, my taxonomy isn't that complex. 

I would really love to be able to offer a pull request with this feature working, but I've no idea where to start.

**Comment by eeintech** [comment]
Digi-Key has **tons of** categories and subcategories, and subcategories' parameters naming differ greatly in my experience.
To avoid creating huge and heterogeneous parametric tables in the category view, my preferred way was to "communize" all parameters for each category under pre-defined names and fill in the parameter values using a lookup table for Digi-Key's parameters for each subcategories. That way the maximum number of parameters you'd get across an entire category would be 10 to 15, instead of maybe the double amount without the common names.

Sometimes they are just named different for a similar spec, for instance "Connector" parts use both:
```
Number of Contacts:
  - Number of Contacts
  - Number of Positions
```
To define the number of available numbers of connections.

Another even more obvious example is the numerous namings of ICs' VCC:
```
Rated Voltage:
  - Voltage - VCCA
  - Voltage - VCCB
  - Voltage - Supply
  - Voltage - Supply (Vcc/Vdd)
  - Voltage - Supply, Digital
```
In this case, you'll loose ability to efficiently compare VCC between two ICs (eg. they would not be in the same column).

Now for the filtering and interpretation of scientific notation, it's a little bit more tricky and I have not put so much thoughts into it. I would love to see Digi-Key's own filtering system on InvenTree, to me that's how good it gets.  
But unfortunately I think that's too much to reach for, and I actually been quite please how the current filter works:
1. put in a value in the search bar (for instance to search for a capacitor value containing 1)
2. sort by value (all parts won't probably be _correctly_ sorted by value, but at least _grouped together_ by value)
3. check what's in the database.

And that makes my job easy enough for retrieving parts 😃

**Comment by rco3** [comment]
I certainly agree that DK has the search thing DOWN, and handle sorting correctly unlike some software I could name whose initials are ALTIUM (grumble, grr). That search engine earns them a LOT of small-order business. I freely admit that I have not seen enough DK Parameter responses to realize what variety of parameter names they use.  That will inevitably affect my strategy; thank you.

Agree that sorting the value alphabetically  instead of numerically presents only minor barriers / minimal opportunity for error for a human reader. (Altium) Probably not worth the effort to try to integrate directly into Inventree, then. I'm happy enough with using the [engineering-notation](https://pypi.org/project/engineering-notation/) module externally to select over a range of actual values if necessary, it's probably not going to be often enough to worry about how efficient it is.

**Comment by rco3** [comment]
OK, I'm watching these commits to try to understand how I can contribute... how the hell are you producing this much usable code this fast?  Is some of it autogenerated?  Admittedly it looks harder because I still don't understand all that's going on, but wow.

**Comment by eeintech** [comment]
@rco3 Ha no auto-generated code! There is a good part of re-use of the current tools and hooks implemented by @SchrodingersGat. I'm no full-time software dev (at least not yet) but I picked up Django less than a year ago, started the hard way with a somewhat complex project and now able to navigate my way around InvenTree's code base so I thought of giving a hand as my team is starting to use it. Still learning on everyday basis so I'm happy to help :smiley:

**Comment by eeintech** [comment]
@rco3 The PR is now in review stage! I'm happy with the current state, mind having a look too?

```
$ git remote add eeintech https://github.com/eeintech/InvenTree.git
$ git fetch eeintech
$ git checkout -b categories_parameters
$ git pull eeintech categories_parameters
```

Make sure to call `invoke update` as it needs to apply the new migration.

**Comment by rco3** [comment]
OK, let me spin up a test install.

**Comment by rco3** [comment]
Seems like the only Categories I can select are those on the top level.  I can't assign Parameters to sub-categories.

**Comment by eeintech** [comment]
That's right, I've limited to top-level categories to simplify the process and unify part parameters in each category. Subcategories inherit from their parent categories, you can try it and it should work fine 👍

**Comment by rco3** [comment]
I don't understand.  I have Electronic and Mechanical at my top level.  I don't understand why I would make Capacitance in Farads a default parameter for all Electronic parts.

**Comment by eeintech** [comment]
Umm, I made an assumption that categories will be defined as "part type" (capacitors, resistors, etc.) starting from the top-level. However you brought a fair point, now I think it should let user decide at which level parameter templates should start to apply.

My original concern for including subcategories was that each time part parameters are created, it needed to let the users decide:
* if they wanted to gather all parent categories (higher-levels) parameters and add it to the part
* or simply add the parameter templates for the subcategory only

I took a shortcut not taking into account your (and probably many more) implementation of categories.
I should have an improved version shortly :+1:

**Comment by SchrodingersGat** [comment]
Looks like @rco3 has raised the same idea that I have over in #1096 :)

**Comment by eeintech** [comment]
@rco3 Please pull my branch (`eeintech/categories_parameters`) and update InvenTree.
Let me know what you think of the new implementation.

**Comment by rco3** [comment]
I used to work (30 years ago? egad.) with a local jingle studio when they brought in full bands to record, and one repeat client was a local violinist ("fiddle player") of some national repute. Well-deserved, I might add - I mean, he did have a gold record on his wall.  The studio owner and I were both reasonably experienced musicians as well, though not at that level.  After the third completely different, brilliant, and (to our ears) flawless take at the same solo, the owner leaned toward me and quietly asked, "Have you ever tried to play the violin?"  We both looked at Tom blazing away on a fourth take, and back at each other.  I shook my head.  He said, "Can't be done."

I'm kinda amazed sometimes at some of the places that my device firmware has ended up, but every time I try to figure out how you've just made this feature work I just think, "Can't be done."  Maybe I should stick to solder.  

Thanks for all this, @eeintech and @SchrodingersGat .  I know thanks aren't as good as commitable code, but I'm trying.

==============

Back to Inventree: when installing the categories_parameters branch a migration failed, so I wiped clean and started over.  Still tried to trip me up by throwing a vi session at me, but I dodged and kept moving.

That worked nicely - I created a rudimentary taxonomy of Categories, created some Parameter Templates, assigned Part Category Parameter Templates through Settings, and created a new Part.  Bang! It had the Parameters with the default values.  I love it.

I did notice that the Admin pages still only allow for Top-level Categories to be assigned. (I think I know where to look for a thread to pull on that one!). I'm assuming that's TBD.

As @SchrodingersGat suggested over in #1096, I agree that Categories should inherit their parents' Parameters by default, e.g. Package. Those checkboxes should (IMHO) default to TRUE - or is that a setting that I've missed?

I also agree that Parts created via API should have the default Parameters automagically added, and immediately progress to realizing that API access to the list of Parameter Templates assigned to a given Category will be needed ... Oh, look - there it is!  Except that it only reports those categories assigned at that level, but not those inherited from its parents - at least, that's what happens when I use the interactive API-doc page.  I assume we would want that to report the same list of Parameters as will be assigned to a new Part of that Category?

**Comment by eeintech** [comment]
@rco3 Thanks for good words, I'm terrible at music myself but can appreciate hard work and talent, it's always inspiring!

1. Yes those checkboxes can be enabled by default, to do so you just need to enable the following part setting in the InvenTree settings:

![image](https://user-images.githubusercontent.com/4020546/98131027-e3226600-1e88-11eb-8296-bbc9ff3fd981.png)

2. I fixed the admin section too, thanks for pointing this out.

3. I also added a hook for adding a parameter template to all categories with the same level only.
Let's say you have setup InvenTree the following way:
* `Electronics` is level=0
* `Mechanical` is level=0
* `Capacitors` is level=1 (under "Electronics")
* `Resistors` is level=1 (under "Electronics")
* `Ceramic_0402` is level=2 (under "Capacitors")

And that you want to add the `symbol` parameter template with a **blank** default value to all categories from level=1, then you would check the following box:

![image](https://user-images.githubusercontent.com/4020546/98146518-9b580a80-1e99-11eb-92f6-3b977e3fcfd0.png)

That way you guarantee that all "Electronics" part have the `symbol` parameter loaded when they are created and you don't force this template into the "Mechanical" category.

Then you can "subclass" the `symbol` parameter template in the "Ceramic_0402" category with default value set to `Capacitors:0402`, adding it to that category only!

I'm pretty happy with the current state, if you have the chance to do more testing let me know if you find anything

**Comment by SchrodingersGat** [comment]
Looking very promising @eeintech - I'm away for a few days so won't be able to have an in-depth look for a while.

@rco3 as someone who plays the violin (a bit) I'm pretty sure it can't be done either ;)
