### ISSUE TITLE
Barcode validation strategy... shift?

### ISSUE THREAD

**Issue by rco3** [inventree/InvenTree#1086]
@SchrodingersGat , @eeintech ,  I'd really love to be able to complete the validate() method in Inventree's digikey_barcode.py, but I can't find a way to unambiguously KNOW that it's not a Newark barcode.  I can validate Format06 barcodes as 'Mouser' (with great confidence) or 'Digi-Key/other' because Mouser violates the standard in a minor but specific way, and I can pull a whole bunch of useful data from either... but I don't really see how to fit that into the strategy as currently instantiated.

I think I have a reasonably robust strategy for validating the variety of extended character codes coming from wedges; there may be some field errors in a statistically miniscule number of cases, but that should be a minority.  I think we'll have more oddball bags without SKU or MPN than bags with actual field decoding errors.

I have methods for validate_Format06() and decode_Format06() that I think are readily adaptable.  From there, what's next?  It's easy enough to extract MPN from Format06 (with some exceptions) and feed that to Ki-nTree (server-side?); extract Invoice#, SalesOrder#, etc for tracking incoming stock, etc.  But I'm lost when it comes to trying to Django-ify it all, and integrate this data pipeline directly into Inventree.  Right now I'm building tkinter monstrosities instead. Yucky.  QT is starting to not look so scary after all.

Some of these things I guess really are specific to me (although I'm interested in the anodizing discussion as well), and aren't things I'm going to have to do over and over, so maybe it does make the most sense for me to just FrankenUI some single-use tools instead of adding it to Inventree. I can handle the former on my own; the latter, not so much.

Thoughts?

**Comment by eeintech** [comment]
@rco3 Thanks for sharing thoughts. I honestly have little to no idea about current barcode workflow, I want to use them in the future but haven't gotten there yet.

My general idea of building a GUI outside of InvenTree is that you can keep and manage it independently, it's especially useful when you want to interact with other systems than InvenTree (spreadsheet for instance, or another CAD/PLM/Inventory system).
I have built Ki-nTree using [PySimpleGUI](https://github.com/PySimpleGUI/PySimpleGUI)'s Tkinter flavor and I have to admit, this project makes the GUI building exercise as "simple" as advertised! I highly recommend it :smile:

**Comment by rco3** [comment]
Yeah, CAD. That. I've started the ball rolling to start getting some Fusion360<-->Inventree communication going. Been using a cloud service for getting BOM data out of F360, but it's worthless for keeping actual track of actual things.  I've gotten a basic script working to extract all the Parts (Name, IPN, Desc) in an open design, next to connect to Inventree and search for a Part from that IPN.  I think I can just make some menu entries / toolbar buttons to handle most of what I need interface-wise from within F360.

I will check into PySimpleGUI, thanks for the tip!

**Comment by ArakniD** [comment]
I’ve gotten zxing/browser to work in the barcode entry form, and filled out th e digikey barcode class. It auto adds u known items and creates a stock entry if not imported before , or looks it up and goes to it..

it needs much refinement. I’ll put a merge request through when I’m done :)

**Comment by matmair** [comment]
@SchrodingersGat do you see something actionable here - I suggest to close it if not.

**Comment by SchrodingersGat** [comment]
@rco3 our barcode support has advanced quite significantly now. If there is anything in particular you want to see, please open a new issue :)
