### ISSUE TITLE
Validation of PDF generation library

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1090]
The current "report generation" framework is *very* underdeveloped, but the plan is to expand it to include

- Stock reports
- Purchase order
- Sales order
- Packing list
- Test report

(others?)

## Weasyprint 

- Currently the [Weasyprint](https://weasyprint.readthedocs.io) library is being used to generate simple PDF test reports.
- Based on reportlab
- Seems reasonably feature packet
- Requires non-python system libraries to be installed (so, not *fully* cross platform)

## [xhtml2pdf](https://github.com/xhtml2pdf/django-xhtml2pdf)

- Another option?
- Just python packages, no system packages

Need to look at the capabilities of both packages and decide on one before continuing and PDF development.

**Comment by rco3** [comment]
Build report: serial/batch for tracked items in Build, perhaps test results for individual items and for overall build.

**Comment by SchrodingersGat** [comment]
Closing - WeasyPrint is soon going to not require cairo lib, so that makes it much more palatable.
