### ISSUE TITLE
Increase Code Coverage

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1098]
At least 80% coverage for 0.7.0 release

Code coverage is pretty low, especially in areas which are more complex to test and require more work!

Specifically, the API and modal forms!

**Comment by eeintech** [comment]
That's pretty important indeed!

I've noticed the builds have been missing the coveralls hook since a while now, it looks like it disconnected in August?
https://coveralls.io/github/inventree/InvenTree

**Comment by SchrodingersGat** [comment]
Huh, I hadn't noticed that. I will have to investigate why that's not working at the moment.

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/98047812-b5392380-1e80-11eb-9dea-4fc64272530e.png)

This is the output at the end of the Travis CI step.. Weird that it isn't throwing an error

**Comment by eeintech** [comment]
FYI I switched from `python-coveralls` to `coveralls` package for Ki-nTree, I had issue with `python-coveralls` in Travis CI.

**Comment by matmair** [comment]
@SchrodingersGat is this still relevant?

**Comment by SchrodingersGat** [comment]
I've added a specific coverage level goal for the next release

**Comment by matmair** [comment]
@SchrodingersGat kind of overshot the goal :-)
