### ISSUE TITLE
Can't disable "Delete on deplete" function while creating new Stock Item 

### ISSUE THREAD

**Issue by rrakso** [inventree/InvenTree#1100]
Hi! Why I can't disable it as before? :disappointed: Now this field is disabled and I can't disable it (switch) hahahah. 
![image](https://user-images.githubusercontent.com/23143274/98023453-4075d300-1e07-11eb-8776-efd0c63f5fba.png)

My all stock items are not automatically deleted because I use stock item pk in many places to identify stock and parts.

**Comment by eeintech** [comment]
@rrakso Your part probably has the "trackable" setting disable:

![image](https://user-images.githubusercontent.com/4020546/98034904-b5381580-1de5-11eb-8ef0-e936b5797eea.png)

Mind checking? What if you enable it?

**Comment by SchrodingersGat** [comment]
Fixed in #1101 - pretty simple bug is causing this

**Comment by eeintech** [comment]
Ouch! Nice fix :+1:
