### ISSUE TITLE
New Build System Issues

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1104]
I "played" a bit with the new build system, here are my findings:
#### 1. `Build Quantity` field is set to partial build output after the later is created:
a. Fresh new build

![image](https://user-images.githubusercontent.com/4020546/98152277-76669600-1e9f-11eb-8681-7fbc25b875c1.png)

b. After partial build of quantity=3 is created 

![image](https://user-images.githubusercontent.com/4020546/98152441-bb8ac800-1e9f-11eb-99fd-661b62e4e9b5.png)

#### 2. Build Outputs shows `1` tag **before** any partial build is completed

![image](https://user-images.githubusercontent.com/4020546/98152564-f12fb100-1e9f-11eb-8c9b-db08facdaa44.png)

#### 3. `Create New Output` button (under "Allocated Parts" tab) stops working after partial build output is created

This sounds like a consequence of issue 1 (system thinks the build is complete).

#### 4. If `Destination Location` is not set, partial build output shows "No stock location set" under `Location` column even though the `location` was set during the partial build completion process.

![image](https://user-images.githubusercontent.com/4020546/98152741-2fc56b80-1ea0-11eb-912e-b1cee38716d2.png)

![image](https://user-images.githubusercontent.com/4020546/98152777-3bb12d80-1ea0-11eb-8e40-0ceb1cd8939b.png)

I will report here if I find any other issues.

**Comment by SchrodingersGat** [comment]
> 4. If Destination Location is not set, partial build output shows "No stock location set" under Location column even though the location was set during the partial build completion process.

Ok this one has been fixed in #1105

**Comment by SchrodingersGat** [comment]
> 1. Build Quantity field is set to partial build output after the later is created:

Fixed this now too. Field name was being shadowed by the form. A very subtle one!

**Comment by SchrodingersGat** [comment]
> Create New Output button (under "Allocated Parts" tab) stops working after partial build output is created

Subtle issue in the template - now fixed!

**Comment by SchrodingersGat** [comment]
> Build Outputs shows 1 tag before any partial build is completed

This is the design intent. When a new build output is created, the "StockItem" output is immediately created, but marked as *in_production*. 

This means that you can immediately see how many units are currently in production, and also you can allocate serial numbers to the output items before they are "finished".

**Comment by SchrodingersGat** [comment]
@eeintech please feel free to reopen this issue if you find any more problems with the new build system. Thanks for pointing out these ones!

**Comment by eeintech** [comment]
Nice, thanks for the quick fixes 👍 

Yes I will do another round to see if I find anything else.

**Comment by eeintech** [comment]
> This is the design intent. When a new build output is created, the "StockItem" output is immediately created, but marked as _in_production_.
> 
> This means that you can immediately see how many units are currently in production, and also you can allocate serial numbers to the output items before they are "finished".

Oh I found why I couldn't see the "In Production" batch, the `In Stock = True` filter is set by default :grimacing: 
Now it makes more sense, I can see all outputs and the number of rows matches the tab marker.
