### ISSUE TITLE
Allow parts to be 'saleable' by default

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#1108]
For how we are using InvenTree, most everything that gets purchased can be resold to the customer, so it would be very handy to be able to (optionally) have Parts marked as saleable by default.

**Comment by eeintech** [comment]
Hello @nwns and welcome to InvenTree!

This is certainly doable, makes me think that InvenTree settings, in addition to have "system" wide settings, should also have per-user preferences for part creation.
For instance:
* John mostly creates "Component/Purchasable" parts, he wants to have the defaults set as such
* Sally mostly creates "Assembly/Salable" parts, she want to have the defaults set as such

**Comment by SchrodingersGat** [comment]
This sounds like a perfect use case for the existing "global settings" framework.

And I really like the idea of having "user settings" also - there would be room for both.

**Comment by SchrodingersGat** [comment]
@nwns check out the fixes implemented in #1114 

To configure the "default" values for various part parameters, navigate to the settings view and change the highlighted options below

![image](https://user-images.githubusercontent.com/10080325/98538567-0f057780-22df-11eb-8960-3cd73cfe52a0.png)
