### ISSUE TITLE
Prepopulate supplier parts with the information from the Part

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#1109]
Because a lot of the parts that we use are unique and only orderable from a single vendor we end up just using the suppliers part number for our internal part number and thus end up entering each part twice into the system:  Once for to create the Part, and a second time to create the SupplierPart so that we can create the PO to receive the parts.

I see two ways of making this process easier:
1) If both could be created at the same time
2) if the New Supplier Part dialog would populate all matching fields from the Part it is being created from.

**Comment by eeintech** [comment]
@nwns One immediate option/hook that you have is the [API](https://inventree.readthedocs.io/en/latest/extend/api/) or the [Python interface](https://inventree.readthedocs.io/en/latest/extend/python/).
With few lines of codes, you could pull information from an existing database part and copy it to create a new supplier part.

That said, I could see why you would want a few items in the New Supplier Part form to be auto-loaded, like:

| Part Field | Supplier Part Field |
| ----- | ----- |
| IPN | SKU |
| Description | Description |
| Link | Link |

The auto-loading could be set in the InvenTree settings, for users who would want to have it enabled (in reference to #1108).
 
Would that be helpful?

**Comment by SchrodingersGat** [comment]
Creating supplier information at the time of part creation would be extremely handy to me also. I have a slightly different suggestion for how this could be implemented..

In the [PartCreate](https://github.com/inventree/InvenTree/blob/826c4711799bb4e8f4b59cd1db889514426d522c/InvenTree/part/views.py#L578) view, we could add a new group of inputs to the form, labelled **Supplier Details** or something like that..

This form group could contain the following fields:

- Supplier
- SKU
- Manufacturer
- MPN
- External link

If any of these fields are completed by the user (and subsequently validated) then a new matching SupplierPart object is created after the Part object is created, and linked to the Part.

**Comment by nwns** [comment]
@eeintech Just importing the suppliers catalog would be an interesting idea but the suppliers have many more parts that we would ever use.

Those three fields would be the most useful.

@SchrodingersGat That could also work, though I think it would best if the IPN was automatically copied to the SKU and MPN with the SupplierPart object being created only if the Supplier is set.

**Comment by eeintech** [comment]
> In the [PartCreate](https://github.com/inventree/InvenTree/blob/826c4711799bb4e8f4b59cd1db889514426d522c/InvenTree/part/views.py#L578) view, we could add a new group of inputs to the form, labelled **Supplier Details** or something like that..
> 
> This form group could contain the following fields:
> 
> * Supplier
> * SKU
> * Manufacturer
> * MPN
> * External link

@SchrodingersGat Is it possible to only display a "section" of a form through a user toggle? If so, how would you do it?
Can the fields for this section of the form be mirroring the Part fields with possible modification by user before submitting form?

**Comment by SchrodingersGat** [comment]
See #1956

**Comment by eeintech** [comment]
Wow looks awesome! :rocket:
