### ISSUE TITLE
IPN not unique

### ISSUE THREAD

**Issue by amishHammer** [inventree/InvenTree#1112]
Currently it seems like it is possible to have 2 parts with the same IPN, I think like email this should be made to be a unique field with null when not present.  It should not be possible to give the same IPN to 2 parts.

**Comment by eeintech** [comment]
@amishHammer See https://github.com/inventree/InvenTree/pull/962#issuecomment-687719365

There was one case where I needed to have 2 parts with the same IPN: when I wanted to create 2 different revisions of the same part. Currently there is no revision control system in place so that's only possible if IPN can be re-used.

I'm not sure what the other use-cases are.

**Comment by amishHammer** [comment]
In practice the revision part numbers seem to mostly be taken care of with suffixes like '-4' for the 4th revision. There is a revision field on the part so maybe make it a combined unique with the revision field.

**Comment by eeintech** [comment]
Appending the revision to make the IPN unique could work, I do like the idea. But still I don't know if this was in the original design philosophy to add the uniqueness constraint and if some users have some good use-cases against it (unlike mine which could be solved as you mentioned).

**Comment by SchrodingersGat** [comment]
@amishHammer this was designed to accommodate the situation where multiple revisions of the same 'internal part' are in the database. If there is no revision specified then the IPN has to be unique.

Is the current setup causing you issues with your installation?

**Comment by amishHammer** [comment]
As of right now if revision is blank you can have multiple parts with the same IPN.  This might be a good candidate for a global option.

**Comment by eeintech** [comment]
> If there is no revision specified then the IPN has to be unique.

I don't think that logic is there yet. Validation only checks that the `name`, `IPN` and `revision` combination is unique.

**Comment by SchrodingersGat** [comment]
I've added a user-configurable option to allow or prohibit duplicate IPN values.
