### ISSUE TITLE
Server CPU Usage

### ISSUE THREAD

**Issue by watarat** [inventree/InvenTree#1121]
This is just an observation. but maybe of interest, or have some significance.

I'm running Inventree in a minimum cost Amazon AWS Server (Lightsail) USD$3.50/month.
Being cheap - you don't get much - and its actually really only 5% of a server on a continuous basis.
AWS have the terminology "Burst" - and you accumulate burst performance by averaging <5% CPU usage over time.
If your base load is >5% - then you eventually end up with no burst performance (to handle burst cpu load) and presumably your server becomes throttled.

Anyway - running Inventree seems to use approx **6%** of the CPU capacity.
This is continuous and largely unaffected by actual part operations on the database.
I also have a Mosquitto MQTT broker, and a Node-Red service running - which together only contributes about 0.1% of server load.

I'm wondering if the CPU usage is 'normal' and expected - or if there is some process spinning its wheels when not intended to be.

Here is a pic from their dashboard of me starting up Inventree at about 9:25. 
This is the Dev version, with sqlite3 database.
![image](https://user-images.githubusercontent.com/8358937/98875788-d75c2280-24cc-11eb-9b4b-48353432b15d.png)

You can see the 'Burst' capacity slowly rising, until Inventree starts - then it begins to actually slowly decrease (bit hard to see)
I'm reasonably happy to just manually fire up the server as needed - or to maybe figure out a crontab to shut it down overnight - afterall - its just me being a cheapskate - and it might in fact not be an issue at all, but just figured i'd report it 😀

**Comment by SchrodingersGat** [comment]
It's a good question. The backend should not really be doing much of anything at all unless it is servicing a user request.

There is [work in progress](https://github.com/inventree/InvenTree/pull/1113) to implement background / scheduled tasks but this also should only be periodic spikes that don't represent much baseload.

Continuous CPU usage of 5% seems pretty high to me. CPU usage is not actually something I've looked at particularly closely before.

Currently running a dev install on my laptop, it says that the python process is taking up ~10% of my CPU! However this is using the inbuilt python dev server which is pretty inefficient.

What are you using to serve the data?

I have just done some very crude testing on my AWS install and it looks like the baseload CPU usage of InvenTree is ~0.0% - I am using gunicorn to act as the server process: https://inventree.readthedocs.io/en/latest/start/deploy/#gunicorn

When I perform some web actions CPU jumps up to ~10% temporarily.

**Comment by SchrodingersGat** [comment]
If you are just using the default python server (i.e. running `invoke server`) then this is most likely the culprit.

For reference, here's the CPU usage running this on my laptop through WSL:

![image](https://user-images.githubusercontent.com/10080325/98879799-73d8f180-24da-11eb-9e3a-37bbc50945ca.png)

**Comment by SchrodingersGat** [comment]
And on AWS running under gunicorn:

![image](https://user-images.githubusercontent.com/10080325/98880456-e26a7f00-24db-11eb-8779-8247fb179e47.png)

**Comment by watarat** [comment]
Yes - my figures are similar
![image](https://user-images.githubusercontent.com/8358937/98880092-e5af3c00-24d6-11eb-97eb-a7f368b0fec0.png)
![image](https://user-images.githubusercontent.com/8358937/98880103-eba51d00-24d6-11eb-8e2a-4b33c0e2d730.png)
Yes I'm simply running **invoke server -a 172.xx.xx.xx:8000**

I'll work through gnuicorn and report back
(Thanks!!)

**Comment by SchrodingersGat** [comment]
That'll be it! The python dev server is useful for testing but that's about it.

**Comment by watarat** [comment]
Dang - seem to have something amiss..
```
(inventree-env) ubuntu@ip-172-26-11-16:~/inventree/InvenTree$ gunicorn -c gunicorn.conf.py InvenTree.wsgi
[2020-11-12 01:24:33 +0000] [184735] [INFO] Starting gunicorn 20.0.4
[2020-11-12 01:24:33 +0000] [184735] [INFO] Listening at: http://172.26.11.16:8000 (184735)
[2020-11-12 01:24:33 +0000] [184735] [INFO] Using worker: sync
[2020-11-12 01:24:33 +0000] [184737] [INFO] Booting worker with pid: 184737
[2020-11-12 01:24:33 +0000] [184737] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/inventree/InvenTree/InvenTree/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[2020-11-12 01:24:33 +0000] [184737] [INFO] Worker exiting (pid: 184737)
[2020-11-12 01:24:33 +0000] [184735] [INFO] Shutting down: Master
[2020-11-12 01:24:33 +0000] [184735] [INFO] Reason: Worker failed to boot.
``` 
Looking for path error.. Seems /inventree/Inventree should be OK?
```
(inventree-env) ubuntu@ip-172-26-11-16:~/inventree/InvenTree$ python -m site
sys.path = [
    '/home/ubuntu/inventree/InvenTree',
    '/usr/lib/python38.zip',
    '/usr/lib/python3.8',
    '/usr/lib/python3.8/lib-dynload',
    '/home/ubuntu/inventree-env/lib/python3.8/site-packages',
]
USER_BASE: '/home/ubuntu/.local' (exists)
USER_SITE: '/home/ubuntu/.local/lib/python3.8/site-packages' (exists)
ENABLE_USER_SITE: False
(inventree-env) ubuntu@ip-172-26-11-16:~/inventree/InvenTree$
```
Anything obvious I could have messed up??

**Comment by SchrodingersGat** [comment]
I reckon that whatever context the gunicorn process is running in is not running under the same python virtual environment, and so  it does not have access to the correct set of python libraries.

In particular with your error message, it cannot import django as django is not "installed" for that context.

Did you install gunicorn from within the local virtual-env context, or system-wide?

From the error trace it looks like it's installed system-wide

**Comment by watarat** [comment]
UM - suspect that I had installed gunicorn (probably system wide) in a rush of blood reading the guide early on, then today I activated environment first and installed (again??)
After lots of mucking around, eventually believed I had uninstalled gunicorn completely, and reinstalled within environment but it still failed. A server reboot seemed to fix it up 😀

**Running very nicely now - thanks!!**
![image](https://user-images.githubusercontent.com/8358937/98891936-26b34a80-24ef-11eb-9803-af08a8bc96c7.png)

**Comment by SchrodingersGat** [comment]
Awesome, glad to hear! This was an interesting learning exercise if nothing else. Now you just have to work out what you're going to spend all that burst allowance on ;)

**Comment by watarat** [comment]
Indeed - not happy with it being used - not happy with it not being used 😂
