### ISSUE TITLE
Full List of Allocated Parts

### ISSUE THREAD

**Issue by Tormentum-creator** [inventree/InvenTree#1132]
Hi, 

I just started using InvenTree. Cool Software!

I had a question about the allocated parts for a build. My inventory consists of quite a few levels of sub-assemblies. A build for my final product will have at least 4 levels of sub-assemblies. Is there a way to quickly get a list of all of the allocated parts for a final product build? Right now it seems that I have to go into each build for each sub-assembly to get to the list of allocated parts. I'd like to be able to quickly get an overview of all of the allocated parts for the entire build of my final product.

Thanks!

**Comment by SchrodingersGat** [comment]
> I just started using InvenTree. Cool Software!

Glad you like it!

Currently there is no way to see the complete "tree" of required parts to make a final product. I think it would be a very useful feature to have. However it might be hard to visualize / display this data?

Happy to take suggestions on how you would want to use this feature, what data you'd like to see (and how it is rendered)...

**Comment by Tormentum-creator** [comment]
> > I just started using InvenTree. Cool Software!
> 
> Glad you like it!
> 
> Currently there is no way to see the complete "tree" of required parts to make a final product. I think it would be a very useful feature to have. However, it might be hard to visualize/display this data?
> 
> Happy to take suggestions on how you would want to use this feature, what data you'd like to see (and how it is rendered)...

Ok, all good! I figured out that I can get the full "tree" with all of the details of stock, supplier etc. by going to the BOM of my final product. 

I do think it would be a great feature if there was an option to build an assembly and all sub-assemblies with one step. Also allowing you to see all of the parts and allocate all of the parts on the same page. That would allow one to quickly see exactly what they need for the complete build from one page.

Thanks for working on developing this software!
