### ISSUE TITLE
Cannot access outside localhost

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [inventree/InvenTree#1138]
Hi, I tried to access inventree vie my PC address 192.168.xx.xx:PORT, instead of 127.0.0.1:PORT without success.

Steps to reproduce:
1. Edit InvenTree/config.yaml file:
from 
`allowed_hosts:`
`  - '*'`
to 
`allowed_hosts: ['*']`

2. Toggle line
`debug: True / False` several times between server restarts;
3. Start the server, try to connect via 192.168.xx.xx:PORT -> no success;

I was always able to connect via 127.0.0.1:PORT.

The solution was to edit tasks.py line:
`def server(c, address="127.0.0.1:8000"):`
to
`def server(c, address="0.0.0.0:PORT"):`

After that, I was able to connect via 192.168.xx.xx:PORT. This is contradictory to https://inventree.readthedocs.io/en/latest/start/config/

**Comment by eeintech** [comment]
You don't need to edit the `tasks.py` file, you can run the server passing the address with the `-a` argument:
```
$ invoke server --help
Usage: inv[oke] [--core-opts] server [--options] [other tasks here ...]

Docstring:
  Launch a (deveopment) server using Django's in-built webserver.

  Note: This is *not* sufficient for a production installation.

Options:
  -a STRING, --address=STRING   Server address:port (default=127.0.0.1:8000)


$ invoke server -a 127.0.0.1:8000
...
Starting development server at http://127.0.0.1:8000/
```

Which part of the documentation do you think is incorrect?

**Comment by SchrodingersGat** [comment]
Starting the development server with the command `invoke server -a 0.0.0.0:8000` (for example) should definitely allow you to access the server from a local network.

Ref: https://inventree.readthedocs.io/en/latest/start/deploy/#running-on-a-local-network

**Comment by WhiteChairFromIkea** [comment]
Thanks. I was stuck at line `allowed_hosts` in the middle of installation manual, never reached wiki you referenced here 👍 
Sorry for the noise :)
