### ISSUE TITLE
Component part cannot be added to multiple BOMs

### ISSUE THREAD

**Issue by wolffam** [inventree/InvenTree#1141]
I am seeing an issue where once I add a component part to a BOM of an assembly, I cannot add that component to another assembly's BOM (or at least it's inconsistent).

Below are screenshots demonstrating the issue.  What's interesting is that if I click "Add Item" a couple of times within the 2nd assembly's BOM, the component will sometimes show up.

![Screen Shot 2020-11-23 at 9 46 31 AM](https://user-images.githubusercontent.com/11801197/99996779-144bd300-2d71-11eb-808d-2afdf29c4707.png)

![Screen Shot 2020-11-23 at 9 46 55 AM](https://user-images.githubusercontent.com/11801197/99996776-13b33c80-2d71-11eb-9dfd-a0abdf8acdbc.png)

![Screen Shot 2020-11-23 at 9 47 12 AM](https://user-images.githubusercontent.com/11801197/99996771-11e97900-2d71-11eb-83a8-1dd227162d31.png)

InvenTree Version | 0.1.5 pre
Django Version | 3.0.7
Commit Hash | 73259c0
Commit Date | 2020-11-20

**Comment by SchrodingersGat** [comment]
Very strange that you say the part appears (sometimes) but not all the time..

There is some logic in place to prevent circular BOM references.  e.g. `A -> B -> C -> A`

However based on your screenshots I don't think this is kicking in here.

Can you add a few dummy parts and see if you can spot a pattern of when the parts appear and when they do not?

**Comment by wolffam** [comment]
Hi @SchrodingersGat , 
The two similar screenshots were taken without any change in the parts.  I just click "Close" and then "Add Item" again.  It seems to be random (which is strange) whether or not it shows the component.  I only get the issue by closing and adding item.  The issue does not occur if I just select the drop down again within the "Create BOM item" view.

**Comment by SchrodingersGat** [comment]
I *think* I have worked this out, I was able to get the same seemingly random behaviour. It is very odd.

Can you test out #1142 and see if it works?

**Comment by wolffam** [comment]
That seems to fix it!  Nicely done!
