### ISSUE TITLE
BOM list stuck

### ISSUE THREAD

**Issue by elmo2k3** [inventree/InvenTree#1143]
Hey!

Started with InvenTree just yesterday and got stuck when playing around with parts and bom.
BOM list seems to hang in an infinite loop. None of the connected parts includes another part.
![Screenshot_20201124_093158](https://user-images.githubusercontent.com/20565/100069138-ad91ec80-2e38-11eb-9bdb-612b66c55022.png)
Edit is still possible
![Screenshot_20201124_093646](https://user-images.githubusercontent.com/20565/100069166-b4b8fa80-2e38-11eb-8931-6983dd0d65e6.png)
Using latest version 3ff0759.
Many thanks for this awesome project!!

**Comment by SchrodingersGat** [comment]
Huh, this one was pretty subtle - I was actually very lucky to be able to replicate it at all!

See fixed notes in #1144 

Once that's merged your issue should be fixed 👍 

Glad you are enjoying the software :)

**Comment by elmo2k3** [comment]
Great, works!! :smile:  :+1:
