### ISSUE TITLE
Order Stock from Build Order

### ISSUE THREAD

**Issue by elmo2k3** [inventree/InvenTree#1145]
Hey,

I would like to order a part from within a build order but the buttons are disabled (can't be realyy seen in the screenshot).
![Unbenannt](https://user-images.githubusercontent.com/20565/100330503-52dec900-2fcf-11eb-9195-7ef532e6b986.JPG)
Am I doing it wrong or isn't it implemented yet?

Cheers
Bjoern

**Comment by eeintech** [comment]
@elmo2k3 It wasn't yet implemented 😞
