### ISSUE TITLE
Error when deleting BuildOrder

### ISSUE THREAD

**Issue by Tormentum-creator** [inventree/InvenTree#1153]
Hi,

I get this error when I try to delete a cancelled build order.
![image](https://user-images.githubusercontent.com/74629382/100674003-1215e580-332a-11eb-8d50-fa8fd70a6a9c.png)

Thanks

**Comment by SchrodingersGat** [comment]
Hey @Tormentum-creator please click on the "Show Error Information" and include that in the screenshot so we can see what is going on :)

**Comment by Tormentum-creator** [comment]
> Hey @Tormentum-creator please click on the "Show Error Information" and include that in the screenshot so we can see what is going on :)

Sorry, here is the error information:

IntegrityError at /build/7/delete/ update or delete on table "build_build" violates foreign key constraint "build_build_parent_id_9a1ef723_fk_build_build_id" on table "build_build" DETAIL: Key (id)=(7) is still referenced from table "build_build". Request Method: POST Request URL: http://10.144.22.71:8000/build/7/delete/ Django Version: 3.0.7 Python Executable: /usr/bin/python3 Python Version: 3.8.5 Python Path: ['/home/gi/inventree/InvenTree', '/usr/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/gi/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/home/gi/.local/lib/python3.8/site-packages/odf', '/home/gi/.local/lib/python3.8/site-packages/odf', '/home/gi/.local/lib/python3.8/site-packages/odf', '/home/gi/.local/lib/python3.8/site-packages/odf', '/home/gi/.local/lib/python3.8/site-packages/odf', '/home/gi/.local/lib/python3.8/site-packages/odf', '/home/gi/.local/lib/python3.8/site-packages/odf'] Server time: Mon, 30 Nov 2020 22:47:43 +0000 Installed Applications: ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'build.apps.BuildConfig', 'common.apps.CommonConfig', 'company.apps.CompanyConfig', 'label.apps.LabelConfig', 'order.apps.OrderConfig', 'part.apps.PartConfig', 'report.apps.ReportConfig', 'stock.apps.StockConfig', 'users.apps.UsersConfig', 'django_filters', 'dbbackup', 'rest_framework', 'rest_framework.authtoken', 'corsheaders', 'crispy_forms', 'import_export', 'django_cleanup', 'qr_code', 'mptt', 'markdownx', 'markdownify', 'django_tex', 'django_admin_shell', 'djmoney', 'djmoney.contrib.exchange', 'error_report'] Installed Middleware: ['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'corsheaders.middleware.CorsMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'InvenTree.middleware.AuthRequiredMiddleware', 'error_report.middleware.ExceptionProcessor'] Traceback (most recent call last): File "/home/gi/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 243, in _commit return self.connection.commit() The above exception (update or delete on table "build_build" violates foreign key constraint "build_build_parent_id_9a1ef723_fk_build_build_id" on table "build_build" DETAIL: Key (id)=(7) is still referenced from table "build_build". ) was the direct cause of the following exception: File "/home/gi/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner response = get_response(request) File "/home/gi/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response response = self.process_exception_by_middleware(e, request) File "/home/gi/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/home/gi/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view return self.dispatch(request, *args, **kwargs) File "/home/gi/.local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch return super().dispatch(request, *args, **kwargs) File "/home/gi/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch return handler(request, *args, **kwargs) File "/home/gi/inventree/InvenTree/InvenTree/views.py", line 542, in post obj.delete() File "/home/gi/.local/lib/python3.8/site-packages/mptt/models.py", line 1053, in delete return super(MPTTModel, self).delete(*args, **kwargs) File "/home/gi/.local/lib/python3.8/site-packages/django/db/models/base.py", line 938, in delete return collector.delete() File "/home/gi/.local/lib/python3.8/site-packages/django/db/models/deletion.py", line 337, in delete signals.post_delete.send( File "/home/gi/.local/lib/python3.8/site-packages/django/db/transaction.py", line 232, in __exit__ connection.commit() File "/home/gi/.local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner return func(*args, **kwargs) File "/home/gi/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 267, in commit self._commit() File "/home/gi/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 243, in _commit return self.connection.commit() File "/home/gi/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/home/gi/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 243, in _commit return self.connection.commit() Exception Type: IntegrityError at /build/7/delete/ Exception Value: update or delete on table "build_build" violates foreign key constraint "build_build_parent_id_9a1ef723_fk_build_build_id" on table "build_build" DETAIL: Key (id)=(7) is still referenced from table "build_build". Request information: USER: joel GET: No GET data POST: csrfmiddlewaretoken = 'QXgSuRdn8XtUHSDSV9MOZpQ93Tw8LU0e8wToUdySgrsq0bAQaVv027UGcDLfzjc2' confirm_delete = 'on' FILES: No FILES data COOKIES: csrftoken = 'TOYr8yKLC23yRFKrTo7Z12sEYB3CgrlGbnBXyU5gKw24aYHp8aQb4Kwb7liJ4Qxu' sessionid = 'c8kgchpcf6o1epbxplvucnojy6b9bvnv' META: CONTENT_LENGTH = '487' CONTENT_TYPE = 'multipart/form-data; boundary=----WebKitFormBoundaryapsvDZH673BvJ1Qy' CSRF_COOKIE = 'TOYr8yKLC23yRFKrTo7Z12sEYB3CgrlGbnBXyU5gKw24aYHp8aQb4Kwb7liJ4Qxu' HTTP_ACCEPT = '*/*' HTTP_ACCEPT_ENCODING = 'gzip, deflate' HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.9' HTTP_CONNECTION = 'keep-alive' HTTP_COOKIE = 'csrftoken=TOYr8yKLC23yRFKrTo7Z12sEYB3CgrlGbnBXyU5gKw24aYHp8aQb4Kwb7liJ4Qxu; sessionid=c8kgchpcf6o1epbxplvucnojy6b9bvnv' HTTP_DNT = '1' HTTP_HOST = '10.144.22.71:8000' HTTP_ORIGIN = 'http://10.144.22.71:8000' HTTP_REFERER = 'http://10.144.22.71:8000/build/7/' HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36' HTTP_X_REQUESTED_WITH = 'XMLHttpRequest' PATH_INFO = '/build/7/delete/' QUERY_STRING = '' RAW_URI = '/build/7/delete/' REMOTE_ADDR = '10.144.22.65' REMOTE_PORT = '51691' REQUEST_METHOD = 'POST' SCRIPT_NAME = '' SERVER_NAME = '10.144.22.71' SERVER_PORT = '8000' SERVER_PROTOCOL = 'HTTP/1.1' SERVER_SOFTWARE = 'gunicorn/20.0.4' gunicorn.socket = wsgi.errors = wsgi.file_wrapper = '' wsgi.input = wsgi.input_terminated = True wsgi.multiprocess = True wsgi.multithread = False wsgi.run_once = False wsgi.url_scheme = 'http' wsgi.version = '(1, 0)' Settings: Using settings module InvenTree.settings ABSOLUTE_URL_OVERRIDES = {} ADMINS = [] ALLOWED_HOSTS = ['*'] APPEND_SLASH = True AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend'] AUTH_PASSWORD_VALIDATORS = '********************' AUTH_USER_MODEL = 'auth.User' BASE_DIR = '/home/gi/inventree/InvenTree' CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}, 'qr-code': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 'LOCATION': 'qr-code-cache', 'TIMEOUT': 3600}} CACHE_MIDDLEWARE_ALIAS = 'default' CACHE_MIDDLEWARE_KEY_PREFIX = '********************' CACHE_MIDDLEWARE_SECONDS = 600 CONFIG = {'database': {'ENGINE': 'django.db.backends.postgresql', 'NAME': 'inventree_db', 'USER': 'inventree', 'PASSWORD': '********************', 'HOST': '0.0.0.0', 'PORT': 5432, 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'OPTIONS': {}, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'NAME': None, 'MIRROR': None}}, 'language': 'en-us', 'timezone': 'UTC', 'currencies': ['AUD', 'CAD', 'EUR', 'GBP', 'JPY', 'NZD', 'USD'], 'debug': True, 'debug_toolbar': False, 'log_level': 'WARNING', 'allowed_hosts': ['*'], 'cors': {'allow_all': True}, 'media_root': '../inventree_media', 'static_root': '/home/gi/static/', 'sentry': {'enabled': False}, 'latex': {'enabled': False, 'interpreter': 'pdflatex', 'options': ''}} CORS_ORIGIN_ALLOW_ALL = True CORS_URLS_REGEX = '^/api/.*$' CRISPY_TEMPLATE_PACK = 'bootstrap3' CSRF_COOKIE_AGE = 31449600 CSRF_COOKIE_DOMAIN = None CSRF_COOKIE_HTTPONLY = False CSRF_COOKIE_NAME = 'csrftoken' CSRF_COOKIE_PATH = '/' CSRF_COOKIE_SAMESITE = 'Lax' CSRF_COOKIE_SECURE = False CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure' CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN' CSRF_TRUSTED_ORIGINS = [] CSRF_USE_SESSIONS = False CURRENCIES = ['AUD', 'CAD', 'EUR', 'GBP', 'JPY', 'NZD', 'USD'] DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql', 'NAME': 'inventree_db', 'USER': 'inventree', 'PASSWORD': '********************', 'HOST': '0.0.0.0', 'PORT': 5432, 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'OPTIONS': {}, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'NAME': None, 'MIRROR': None}}} DATABASE_ROUTERS = [] DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440 DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000 DATETIME_FORMAT = 'N j, Y, P' DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%Y', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M', '%m/%d/%y'] DATE_FORMAT = 'N j, Y' DATE_INPUT_FORMATS = ['%Y-%m-%d'] DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage' DBBACKUP_STORAGE_OPTIONS = {'location': '/tmp'} DEBUG = True DEBUG_PROPAGATE_EXCEPTIONS = False DECIMAL_SEPARATOR = '.' DEFAULT_CHARSET = 'utf-8' DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter' DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage' DEFAULT_FROM_EMAIL = 'webmaster@localhost' DEFAULT_INDEX_TABLESPACE = '' DEFAULT_TABLESPACE = '' DISALLOWED_USER_AGENTS = [] EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' EMAIL_HOST = 'localhost' EMAIL_HOST_PASSWORD = '********************' EMAIL_HOST_USER = '' EMAIL_PORT = 25 EMAIL_SSL_CERTFILE = None EMAIL_SSL_KEYFILE = '********************' EMAIL_SUBJECT_PREFIX = '[Django] ' EMAIL_TIMEOUT = None EMAIL_USE_LOCALTIME = False EMAIL_USE_SSL = False EMAIL_USE_TLS = False EXCHANGE_BACKEND = 'InvenTree.exchange.InvenTreeManualExchangeBackend' EXTRA_URL_SCHEMES = [] FILE_CHARSET = 'utf-8' FILE_UPLOAD_DIRECTORY_PERMISSIONS = None FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler'] FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440 FILE_UPLOAD_PERMISSIONS = 420 FILE_UPLOAD_TEMP_DIR = None FIRST_DAY_OF_WEEK = 0 FIXTURE_DIRS = [] FORCE_SCRIPT_NAME = None FORMAT_MODULE_PATH = None FORM_RENDERER = 'django.forms.renderers.DjangoTemplates' IGNORABLE_404_URLS = [] IMPORT_EXPORT_USE_TRANSACTIONS = True INSTALLED_APPS = ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'build.apps.BuildConfig', 'common.apps.CommonConfig', 'company.apps.CompanyConfig', 'label.apps.LabelConfig', 'order.apps.OrderConfig', 'part.apps.PartConfig', 'report.apps.ReportConfig', 'stock.apps.StockConfig', 'users.apps.UsersConfig', 'django_filters', 'dbbackup', 'rest_framework', 'rest_framework.authtoken', 'corsheaders', 'crispy_forms', 'import_export', 'django_cleanup', 'qr_code', 'mptt', 'markdownx', 'markdownify', 'django_tex', 'django_admin_shell', 'djmoney', 'djmoney.contrib.exchange', 'error_report'] INTERNAL_IPS = ['127.0.0.1'] LANGUAGES = [('en', 'English'), ('de', 'German'), ('fr', 'French'), ('pk', 'Polish')] LANGUAGES_BIDI = ['he', 'ar', 'fa', 'ur'] LANGUAGE_CODE = 'en-us' LANGUAGE_COOKIE_AGE = None LANGUAGE_COOKIE_DOMAIN = None LANGUAGE_COOKIE_HTTPONLY = False LANGUAGE_COOKIE_NAME = 'django_language' LANGUAGE_COOKIE_PATH = '/' LANGUAGE_COOKIE_SAMESITE = None LANGUAGE_COOKIE_SECURE = False LATEX_ENABLED = False LATEX_GRAPHICSPATH = ['/home/gi/inventree/inventree_media/report/assets'] LATEX_INTERPRETER = 'pdflatex' LATEX_INTERPRETER_OPTIONS = '' LATEX_SETTINGS = {'enabled': False, 'interpreter': 'pdflatex', 'options': ''} LOCALE_PATHS = "('/home/gi/inventree/InvenTree/locale/',)" LOGGING = {'version': 1, 'disable_existing_loggers': False, 'handlers': {'console': {'class': 'logging.StreamHandler'}}, 'root': {'handlers': ['console'], 'level': 'WARNING'}} LOGGING_CONFIG = 'logging.config.dictConfig' LOGIN_REDIRECT_URL = '/accounts/profile/' LOGIN_URL = '/accounts/login/' LOGOUT_REDIRECT_URL = None MANAGERS = [] MARKDOWNIFY_BLEACH = False MARKDOWNIFY_WHITELIST_ATTRS = ['href', 'src', 'alt'] MARKDOWNIFY_WHITELIST_TAGS = ['a', 'abbr', 'b', 'blockquote', 'em', 'h1', 'h2', 'h3', 'i', 'img', 'li', 'ol', 'p', 'strong', 'ul'] MARKDOWNX_MEDIA_PATH = 'markdownx/2020/11/30' MEDIA_ROOT = '/home/gi/inventree/inventree_media' MEDIA_URL = '/media/' MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage' MIDDLEWARE = ['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'corsheaders.middleware.CorsMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'InvenTree.middleware.AuthRequiredMiddleware', 'error_report.middleware.ExceptionProcessor'] MIGRATION_MODULES = {} MONTH_DAY_FORMAT = 'F j' NUMBER_GROUPING = 0 PASSWORD_HASHERS = '********************' PASSWORD_RESET_TIMEOUT_DAYS = '********************' PREPEND_WWW = False QR_CODE_CACHE_ALIAS = 'qr-code' REST_FRAMEWORK = {'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler', 'DATETIME_FORMAT': '%Y-%m-%d %H:%M', 'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.BasicAuthentication', 'rest_framework.authentication.SessionAuthentication', 'rest_framework.authentication.TokenAuthentication'), 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated', 'rest_framework.permissions.DjangoModelPermissions'), 'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'} ROOT_URLCONF = 'InvenTree.urls' SECRET_KEY = '********************' SECURE_BROWSER_XSS_FILTER = False SECURE_CONTENT_TYPE_NOSNIFF = True SECURE_HSTS_INCLUDE_SUBDOMAINS = False SECURE_HSTS_PRELOAD = False SECURE_HSTS_SECONDS = 0 SECURE_PROXY_SSL_HEADER = None SECURE_REDIRECT_EXEMPT = [] SECURE_REFERRER_POLICY = None SECURE_SSL_HOST = None SECURE_SSL_REDIRECT = False SERVER_EMAIL = 'root@localhost' SESSION_CACHE_ALIAS = 'default' SESSION_COOKIE_AGE = 1209600 SESSION_COOKIE_DOMAIN = None SESSION_COOKIE_HTTPONLY = True SESSION_COOKIE_NAME = 'sessionid' SESSION_COOKIE_PATH = '/' SESSION_COOKIE_SAMESITE = 'Lax' SESSION_COOKIE_SECURE = False SESSION_ENGINE = 'django.contrib.sessions.backends.db' SESSION_EXPIRE_AT_BROWSER_CLOSE = False SESSION_FILE_PATH = None SESSION_SAVE_EVERY_REQUEST = False SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer' SETTINGS_MODULE = 'InvenTree.settings' SHORT_DATETIME_FORMAT = 'm/d/Y P' SHORT_DATE_FORMAT = 'm/d/Y' SIGNING_BACKEND = 'django.core.signing.TimestampSigner' SILENCED_SYSTEM_CHECKS = [] STATICFILES_DIRS = ['/home/gi/inventree/InvenTree/InvenTree/static'] STATICFILES_FINDERS = ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder'] STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage' STATIC_COLOR_THEMES_DIR = '/home/gi/static/css/color-themes' STATIC_ROOT = '/home/gi/static' STATIC_URL = '/home/gi/static/' TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': ['/home/gi/inventree/InvenTree/templates', '/home/gi/inventree/inventree_media/report'], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.template.context_processors.i18n', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages', 'InvenTree.context.health_status', 'InvenTree.context.status_codes', 'InvenTree.context.user_roles']}}, {'NAME': 'tex', 'BACKEND': 'django_tex.engine.TeXEngine', 'DIRS': ['/home/gi/inventree/inventree_media/report']}] TEST_NON_SERIALIZED_APPS = [] TEST_RUNNER = 'django.test.runner.DiscoverRunner' THOUSAND_SEPARATOR = ',' TIME_FORMAT = 'P' TIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M'] TIME_ZONE = 'UTC' USE_I18N = True USE_L10N = True USE_THOUSAND_SEPARATOR = False USE_TZ = True USE_X_FORWARDED_HOST = False USE_X_FORWARDED_PORT = False WSGI_APPLICATION = 'InvenTree.wsgi.application' X_FRAME_OPTIONS = 'DENY' YEAR_MONTH_FORMAT = 'F Y' You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by SchrodingersGat** [comment]
A potential fix for this issue - https://github.com/inventree/InvenTree/pull/1154

Once this is merged in, please update and see if the issue persists.
