### ISSUE TITLE
Separate "container" from "content" in permission rule sets?

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1176]
@SchrodingersGat Starting a discussion here before going heads down into the implementation.

For our team, we need more flexibility into the permission system.
I start seeing some users creating **Categories** and **Stock Locations** ("containers") instead of **Parts** and **Stock Items** ("content").
I would like to prevent this to happen as I'm the one cleaning-up the mess afterwards...

The problem is that both "containers" and "content" models permissions are bundled together:
- **Category** permissions are tied to the **Part** permission rule set
- **Stock Location** permissions are tied to the **Stock** permission rule set

Would you be on-board for splitting those two rule sets, giving **Category** and **Stock Location** their own rule sets?
Any other ideas?

**Comment by SchrodingersGat** [comment]
I think this makes a lot of sense. So the new permission groups would be 

- `stock item`
- `stock location`
- `part`
- `part category`

This is going to require a careful consideration of all the places that the current `part` and `stock` permissions are used. Also, we will need to migrate the existing permissions across!

**Comment by eeintech** [comment]
Yes it is definitely not a "drop-in" change, will try to be very careful in that regard.
Glad you agree, thanks for chiming in so quickly!

**Comment by SchrodingersGat** [comment]
No worries. Might be difficult to respond in a timely manner over the holidays :)
