### ISSUE TITLE
No Pricing information found when fractional amount is used

### ISSUE THREAD

**Issue by atoav** [inventree/InvenTree#1178]
I have a part which uses a cable as a sub-part. The cable comes in rolls of 3 meters, so I created a supplier part where 1 unit costs a third of the manual prize. 

If I use a fractional amount of 0.25 (representing a 25 cm piece of ribbon cable in my case) I get a hint that says there is no pricing information available:  
![2020-12-20 14_08_59-Window](https://user-images.githubusercontent.com/6620266/102714243-9cb88780-42cd-11eb-9909-2bbce786ea89.png)  

If I use anything bigger than 1 it works as expected, even with 1.5:  
![2020-12-20 14_11_22-Window](https://user-images.githubusercontent.com/6620266/102714254-afcb5780-42cd-11eb-8824-4f742105ee9c.png)  
![2020-12-20 14_12_29-Window](https://user-images.githubusercontent.com/6620266/102714266-b659cf00-42cd-11eb-801a-dd54a71e3565.png)  

I also tried to enter a Prize-break for an amount <1, but this is not allowed. Expected behaviour would be that fractional amounts <1 cost a fraction of the prize.

**Comment by eeintech** [comment]
@atoav This is an interesting use-case which isn't supported yet. I also think that price for fractional quantity should be allowed 👍 

If you are comfortable with Django/Python you can submit a PR 😃
