### ISSUE TITLE
Match part global settings to individual properties

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1180]
## Part properties
![image](https://user-images.githubusercontent.com/4020546/102928009-0370a900-4466-11eb-97eb-8d36cd1cba76.png)

## Global Part settings
![image](https://user-images.githubusercontent.com/4020546/102928038-108d9800-4466-11eb-999d-89efdf1fd485.png)

(see the missing properties? :nerd_face: )

This should be straightforward but have to put it on backburner (lack of time).

**Comment by SchrodingersGat** [comment]
Implemented in #1201 :)

**Comment by eeintech** [comment]
@SchrodingersGat Sweet, thanks!
