### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1182]
Request Method: | GET
-- | --
http://127.0.0.1:8000/index/
3.0.7
CalledProcessError
Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py in run, line 512
/Users/macbookair/Dev/InvenTree-master/venv/bin/python

Hello
When I try to open program I got this error what can be solution?

Thank you in advance.
3.8.0

**Comment by SchrodingersGat** [comment]
Hi @neco1982 did you close this issue because you got it working?

**Comment by neco1982** [comment]
Yes working

2 Oca 2021 Cmt, saat 12:18 tarihinde Oliver <notifications@github.com> şunu
yazdı:
