### ISSUE TITLE
BOM erros

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1183]
Hello
I created BOM and build order when i tryed to complete build i got the below errors.
what was wrong in my process thank you
Form errors exist
Build cannot be completed
Required build quantity has not been completed
Build order cannot be completed

**Comment by SchrodingersGat** [comment]
Hi @neco1982 did you get this working?

**Comment by neco1982** [comment]
Hi yes working thank you

2 Oca 2021 Cmt, saat 12:17 tarihinde Oliver <notifications@github.com> şunu
yazdı:
