### ISSUE TITLE
Creating new build and BOM

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1184]
Hello 
I tryed to create new build and new BOM for it and use it metarials which is on stok but used for other builds and BOM I couldnt chose them for new BOM. What can be solution?

**Comment by SchrodingersGat** [comment]
It sounds like this might be the same issue as https://github.com/inventree/InvenTree/issues/1160

Do you think that https://github.com/inventree/InvenTree/issues/1160 describes the same problem you are seeing?

**Comment by neco1982** [comment]
Solved

2 Oca 2021 Cmt, saat 12:23 tarihinde Oliver <notifications@github.com> şunu
yazdı:
