### ISSUE TITLE
"inv install" is missing arguments

### ISSUE THREAD

**Issue by do9xe** [inventree/InvenTree#1189]
Hello everyone,

while installing InvenTree on debian 10 and following the setup guide in the documentation the `inv install` command errors with `'install' did not receive all required positional arguments!`.
After copying `InvenTree/config_template.yaml` to `config.yaml` and running the pip install command manually I get the same error for the `inv migrate` command. As far as I can see in `tasks.py` the required argument is called `c` for the command line context.
So far I have no clue what this argument should be. To unexperienced users this is very confusing and it might stop them to install this tool.
I would like to ask to update the documentation accordingly with the full command that is required here.
(Used version: v0.1.4)

**Comment by eeintech** [comment]
@do9xe Sorry you ran into this issue.

You seem to have a problem calling the `invoke` tool, have you tried to run `invoke install` instead?
How did you install `invoke`?

**Comment by do9xe** [comment]
@eeintech Thanks for your help!
After a lot of debugging it seems like my version of invoke was quite old, because I wasn't using a venv to install it. Debian 10 currently delivers v0.11.1 and if one installs it into a venv it has version 1.4.1.
Sorry for opening this issue as it was clearly my fault.

**Comment by eeintech** [comment]
@do9xe Glad it is fixed! Enjoy!
