### ISSUE TITLE
BOM Will Not Load

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#1190]
![image](https://user-images.githubusercontent.com/18520951/103303521-2d7d1a80-49d4-11eb-9bda-a7b82f01820c.png)
The "Loading, please wait..." just keeps going on and on and on. What's going on?
--Larry

**Comment by eeintech** [comment]
@LarryJoy Your issue looks related to #1143 which was fixed by PR #1144 

Are you sure you are running the latest version of InvenTree?
(click on your username then click on "About InvenTree" to check the current version you are running)

**Comment by LarryJoy** [comment]
Version is "0.1.5 pre". I don't see anything about what version is the latest. I went to GitHub and tried to find item #1143 but didn't see anything about searching by item number.
--@LarryJoy

**Comment by LarryJoy** [comment]
I ran through the Update InvenTree procedure. When I ran 'git pull origin master' the system came back with "program up to date". I went ahead and ran 'invoke update' and when that finished I logged back in to InvenTree and went to the 10076-1KIT IPN. From there I went to the BOM tab and this time it loaded right away. I don't know what the problem was but it is working now.
--@LarryJoy

**Comment by eeintech** [comment]
@LarryJoy Good to know it's fixed 👍

**Comment by SchrodingersGat** [comment]
This is most likely the same issue reported here - https://github.com/inventree/InvenTree/issues/1143 (which has been fixed).

Glad to hear that you got it working with the latest code.
