### ISSUE TITLE
Where Did BOM Pricing Column Go?

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#1191]
When I did the update to V 0.1.5 pre the pricing column disappeared. Where did it go? How to get it added back in? The price for the assembly is as before by clicking on the "$" icon.
--Larry

**Comment by eeintech** [comment]
@LarryJoy BOM pricing was hidden in #1144 by @SchrodingersGat, it looks like it was broken and Oliver intends to fix it.

**Comment by LarryJoy** [comment]
I tried to find issue #1144 for an explanation, but I couldn't find any search mechanism.
--@LarryJoy

**Comment by eeintech** [comment]
@LarryJoy If you're looking for the issue, the number itself is the link 😉
