### ISSUE TITLE
Stock Form Errors?

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#1193]
![image](https://user-images.githubusercontent.com/18520951/103381829-ea49a700-4aba-11eb-98e3-98e9a47a6a7f.png)
I entered the stock quantity as zero and got this. I then returned the quantity to one and got the same thing. What is the problem?
--Larry

**Comment by eeintech** [comment]
Hi @LarryJoy This is a known bug I've encountered myself.

See PR #1179
