### ISSUE TITLE
'install' did not receive all required positional arguments!

### ISSUE THREAD

**Issue by h0m3us3r** [inventree/InvenTree#1194]
While following the installation guide (https://inventree.readthedocs.io/en/latest/start/install/), the `inv install` step fails with `'install' did not receive all required positional arguments!`.

**Comment by SchrodingersGat** [comment]
Hi @h0m3us3r have you installed the `invoke` tool? This sounds very similar to this other recent issue (please check proposed resolution there):

https://github.com/inventree/InvenTree/issues/1189
