### ISSUE TITLE
Create stock item fails with "Form errors exist" when initiated from part page

### ISSUE THREAD

**Issue by svdasein** [inventree/InvenTree#1199]
When attempting to add stock for a part, if I attempt to add the stock by clicking "New Stock Item" from the individual part page, when submitting the "Create new Stock Item" form I'm getting a "Form errors exist" message with no further elaboration and no highlighting on the "errant" form.

![image](https://user-images.githubusercontent.com/511777/103471169-63a6fb00-4d42-11eb-998a-b72cb149a9ab.png)

I have no problem adding stock for parts if I go first to the Stock tab and create the new stock item from there (referencing the same part)

This seems very consistent - it works fine if I come at it via stock but not if I come at it via the part. 

There's either some hidden field that's missing or wrong or there needs to be a better error message.

![image](https://user-images.githubusercontent.com/511777/103471242-77069600-4d43-11eb-8830-b04f60ec1f06.png)

**Comment by svdasein** [comment]
You've already fixed it - thanks

**Comment by eeintech** [comment]
Yes, fixed in #1198
