### ISSUE TITLE
Python Interface with inventree

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#1209]
Has anyone used this?  I am trying to retrieve the stock location of a part.  I have been able to use Part.list(search=<part#>) to find the part but unable to get the human readable location of the part.

**Comment by eeintech** [comment]
@lookme2 Please open a new issue here: https://github.com/inventree/inventree-python/issues
The documentation is here: https://inventree.readthedocs.io/en/latest/extend/python/

The API call `part = Part(api, <part#>)` should be able to get you the `part.default_location`.

**Comment by lookme2** [comment]
Will do.  Thanks.
