### ISSUE TITLE
Investigate DRF Forms

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1213]
DRF is already used extensively for the API.

And it appears that it also supports form management:

https://www.django-rest-framework.org/topics/html-and-forms/

If this is the case, then the existing form framework could be ported to using the API, which would *significantly* reduce existing code duplication.

**Comment by eeintech** [comment]
Would you lose the crispy form layer?

**Comment by SchrodingersGat** [comment]
Good question! I'm not sure.. I was just reading through the DRF documentation and saw they supported web forms. Not something I plan on tackling for quite some time anyway.

**Comment by rcludwick** [comment]
Most people these days develop an api layer and then develop a front end based upon that.  So you could write an alternative front end for IOS, Android, or integrate it internally with your own applications.  Your auth layer would likely need to change though.

**Comment by SchrodingersGat** [comment]
@rcludwick absolutely. A lot of the web interface currently makes use of the API. For example, all the dynamic tables are loaded using AJAX
