### ISSUE TITLE
Can settings.py use environment variables instead of a config.yaml?

### ISSUE THREAD

**Issue by rcludwick** [inventree/InvenTree#1214]
So I wanted to dockerize inventree for my docker cluster, ideally using it on postgresql.  

See here for my efforts:  https://github.com/rcludwick/inventree-docker 
I forked this off a mariaDB docker implementation.

It works, but it's painful.

1.  I have to create a config.yaml
https://github.com/rcludwick/inventree-docker/blob/master/start_gunicorn.sh

2. The config.yaml is a template so I have to update config.yaml when the config.yaml template changes.
3. The config.yaml is not configurable for people wanting to use this outside of a small company.  (logging is hardcoded, eg.) 
4. So I have to use environment variables to construct the config.yaml which then is turned loaded by settings.py or fork inventree to change the settings.py to what I need them to be.

So in my professional life when I write a configurable application setting, I just expect people to pass in the value in a environment variable, while providing a reasonable default in the settings.py

So... eg.  
``` python
LOGGING_DEFAULT = {...}
LOGGING = json.loads(os.getenv("INVENTREE_LOG_CFG","")) if os.getenv("INVENTREE_LOG_CFG") else LOGGING_DEFAULT
```

Then instead of creating the config.yaml which gets parsed by the settings.py file, it's all just handled simply by the settings.py.  

JSON is similar enough to python data structures that it's not a big deal typically.  

It's not just logging say, but also:

DRF AUTHN/AUTHZ configuration.  
STATIC_URL
MEDIA_URL
AUTH_PASSWORD_VALIDATORS
etc.

**Comment by SchrodingersGat** [comment]
Sure, this all seems pretty sensible and goes along with https://github.com/inventree/InvenTree/issues/1214
