### ISSUE TITLE
Secrets file should be configurable.

### ISSUE THREAD

**Issue by rcludwick** [inventree/InvenTree#1215]
For docker config and other secrets systems, the secrets come into a file inside the docker container.  

This would be nice to be configured.  Right now it has to be copied, but it could just be done in the following manner.

NOTE:  Whether you do it based upon the config.yaml or the envvars, is up to you, but if you want to scale it out past 1 docker container, this will make it easier for people to deploy it in docker.

``` python
if os.getenv("INVENTREE_SECRET_KEY",""):
    # The secret key is passed in as an envvar directly
    SECRET_KEY = os.getenv("INVENTREE_SECRET_KEY")
elif os.getenv("INVENTREE_SECRET_KEY_FILE",""):
    # Docker compose secrets come in as a file to the container
    SECRET_KEY = open(os.getenv("INVENTREE_SECRET_KEY_FILE", "r")).read().strip()
else:
    # Works only for one docker instance which is probably okay.  
    SECRET_KEY = generate_secret_key()
```

The docker compose config would then look like this:

``` docker-compose
inventree:
    build: ./inventree-docker
    container_name: inventree
    expose:
      - 9767/tcp
    networks:
      - proxy
      - db
    depends_on:
      - db
    volumes:
      - /mnt/dockerdata/inventree/static:/usr/src/static
      - /mnt/dockerdata/inventree/media:/usr/src/media
    secrets:
      - postgres_password
      - postgres_user
      - django_secret_key
    environment:
      - SECRET_KEY_FILE=/run/secrets/django_secret_key
      - DATABASE_USER_FILE=/run/secrets/postgres_user
      - DATABASE_PASSWORD_FILE=/run/secrets/postgres_password
      [...]
```

**Comment by SchrodingersGat** [comment]
@rcludwick I am happy with this suggestion - I have little (to none) experience with docker but I can 100% see the utility of such a feature.

**Comment by rcludwick** [comment]
It's worth while checking out the linuxserver.io collection of projects.  It also makes it easier to get a development environment.
