### ISSUE TITLE
admin static files doesnt loaded

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1216]
Hello I loaded project in production with gunicorn and ngnix on digitalocean by using postgresql. Everything is good and working well there is one problem that admin page static files doesnt loaded. There is some photos would you please tell me where is mistake i tryed several path to get static files but fails
![Ekran Resmi 2021-01-12 23 34 50](https://user-images.githubusercontent.com/31635566/104369780-0a537e80-552f-11eb-98b4-767c09d375de.png)
![Ekran Resmi 2021-01-12 23 37 12](https://user-images.githubusercontent.com/31635566/104369930-353dd280-552f-11eb-913f-abde6740802a.png)
![Ekran Resmi 2021-01-12 23 38 18](https://user-images.githubusercontent.com/31635566/104370023-51da0a80-552f-11eb-9359-dfcb2336cb62.png)

**Comment by neco1982** [comment]
solved

**Comment by SchrodingersGat** [comment]
@neco1982 what was your solution?

**Comment by neco1982** [comment]
I added on path the file inventree_static which is created by inv static
instead of static which is created by manage.py collectstatic it worked for
me

13 Oca 2021 Çar, saat 01:07 tarihinde Oliver <notifications@github.com>
şunu yazdı:
