### ISSUE TITLE
Shortcut to add a batch of build parts to a purchase order

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1220]
@SchrodingersGat How dfficult do you think it would be to add the "order stock" button to a build output, with this button triggering a new form with **all the parts** in the build output to be added to a purchase order?
Bonus point would be to automatically fill in the quantity field for each part in this form with the missing stock (delta between full allocation quantity and available stock).

![image](https://user-images.githubusercontent.com/4020546/104485617-bda48d80-5598-11eb-9604-af3ace9ab2d8.png)

**Comment by SchrodingersGat** [comment]
Not super difficult at all, I think. The "order parts" form is in *desperate need* of an overhaul, it has been probably 2 years since I implemented that, and a lot has been learned since then.

**Comment by eeintech** [comment]
@SchrodingersGat Was going to take a stab at this but realized that the build system has changed quite a bit... Also looks like allocation ignores the build outputs and does it for the full build quantity.
