### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1238]
Hello
I want to use the program with my native language i translated all field from templates it is working but i have problem with modals i couldnt find the sources to translate them. Would you please help me i found the source from the locale/django.po file i go there translated to my language but it is not changed on view. I also changed status_codes.py they appear sometimes with my native language sometimes with default language us-en. There is any solution to solve this?
Thanks in advance.

**Comment by neco1982** [comment]
I checked changes on local server appear but on ngnix doesnt appear. 
![Ekran Resmi 2021-01-17 23 01 02](https://user-images.githubusercontent.com/31635566/104855551-76165c80-591e-11eb-837d-6ac64b541b56.png)
![Ekran Resmi 2021-01-17 23 01 00](https://user-images.githubusercontent.com/31635566/104855554-79114d00-591e-11eb-9e97-7c4aeed1f6f2.png)
![Ekran Resmi 2021-01-17 23 50 39](https://user-images.githubusercontent.com/31635566/104855637-e7eea600-591e-11eb-8840-01f915565577.png)

**Comment by SchrodingersGat** [comment]
It is probably caused by some particular files missing the translation "hook". You can read about how translation hooks work here:

https://docs.djangoproject.com/en/3.1/topics/i18n/translation/

It would be simplest to start with a single example of a string you would like to see translated, and work from there.

Briefly, there are two ways to mark strings as translatable. 

### Strings in Templates

Template files (e.g. `.html` and `.js`) use the `{% trans "String" %}` approach:

```html
{% load i18n %}

This is not a translated string.
{% trans "This string WILL be translated" %}
```

### Strings in Python

```python
from django.utils.translation import gettext_lazy as _

untranslated_text = "This string will not be translated"

translated_text = _("This string will be translated")
```

It is likely that there are a lot of existing strings which are not hooked into the translation engine - these will need to be updated.

There has not been much work recently on any translation. I'd love your help on adding translation hooks if you are willing to offer it!

It looks like you are translating to Turkish? Would you be willing to contribution your translation back to the project?

**Comment by neco1982** [comment]
> It is probably caused by some particular files missing the translation "hook". You can read about how translation hooks work here:
> 
> https://docs.djangoproject.com/en/3.1/topics/i18n/translation/
> 
> **It would be simplest to start with a single example of a string you would like to see translated, and work from there.**
> 
> Briefly, there are two ways to mark strings as translatable.
> 
> ### Strings in Templates
> Template files (e.g. `.html` and `.js`) use the `{% trans "String" %}` approach:
> 
> ```
> {% load i18n %}
> 
> This is not a translated string.
> {% trans "This string WILL be translated" %}
> ```
> 
> ### Strings in Python
> ```python
> from django.utils.translation import gettext_lazy as _
> 
> untranslated_text = "This string will not be translated"
> 
> translated_text = _("This string will be translated")
> ```
> 
> It is likely that there are a lot of existing strings which are not hooked into the translation engine - these will need to be updated.
> 
> There has not been much work recently on any translation. I'd love your help on adding translation hooks if you are willing to offer it!
> 
> It looks like you are translating to Turkish? Would you be willing to contribution your translation back to the project?

I almost translated all project  in Turkish so I can support for this

**Comment by neco1982** [comment]
> It is probably caused by some particular files missing the translation "hook". You can read about how translation hooks work here:
> 
> https://docs.djangoproject.com/en/3.1/topics/i18n/translation/
> 
> **It would be simplest to start with a single example of a string you would like to see translated, and work from there.**
> 
> Briefly, there are two ways to mark strings as translatable.
> 
> ### Strings in Templates
> Template files (e.g. `.html` and `.js`) use the `{% trans "String" %}` approach:
> 
> ```
> {% load i18n %}
> 
> This is not a translated string.
> {% trans "This string WILL be translated" %}
> ```
> 
> ### Strings in Python
> ```python
> from django.utils.translation import gettext_lazy as _
> 
> untranslated_text = "This string will not be translated"
> 
> translated_text = _("This string will be translated")
> ```
> 
> It is likely that there are a lot of existing strings which are not hooked into the translation engine - these will need to be updated.
> 
> There has not been much work recently on any translation. I'd love your help on adding translation hooks if you are willing to offer it!
> 
> It looks like you are translating to Turkish? Would you be willing to contribution your translation back to the project?

By the way i made all translations according to hooks. Here I realized something and made some researches about it bootstrap modal have some translation problem for example in this photo i translated all part of modal but submit button doesnt change the language. If i change id name then it is translated but in this case it lose function. Another problem is project which i published with gunicorn and ngnix on digitalocean doesnt updated any translation from modal form as it is accept from other fields. Please check here is http://167.99.220.1/ it is life everything is translated except modal forms. Here is photo from local server working there is modal translation
![Ekran Resmi 2021-01-18 03 30 44](https://user-images.githubusercontent.com/31635566/104860757-bdf8ac00-593d-11eb-9f41-ff1e7c1c7cac.png)

**Comment by neco1982** [comment]
Solved after sitting till 5 am

**Comment by SchrodingersGat** [comment]
@neco1982  glad you solved it. If there are any particular strings that you are unable to translate please let me know.

Otherwise if you have completed a Turkish translation (fantastic!) please submit a pull request with the changes :)

**Comment by SchrodingersGat** [comment]
Hey @neco1982 - just letting you know that language translation for InvenTree is now provided via crowdin - https://crowdin.com/project/inventree

If you are interested, this would be a fantastic place to help out other Turkish users by contributing to the translation effort!

Hope you are still making good use of InvenTree :)
