### ISSUE TITLE
Add "depleted stock" to homepage

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1245]
Add display of stock items which are "depleted" (in stock but quantity = 0)

**Comment by SchrodingersGat** [comment]
Additionally add settings or which items are displayed on the home page

**Comment by matmair** [comment]
@SchrodingersGat how did you imagine the settings? One per item? And per user or global?

**Comment by SchrodingersGat** [comment]
This was a while ago, I think I was imagining that each item on the home page could be configurable (simple boolean setting).
