### ISSUE TITLE
Update installation documentation - F-strings on Debian Stretch

### ISSUE THREAD

**Issue by Shimrockx** [inventree/InvenTree#1251]
Hi,

On Debian Stretch the default python version installed is Python 3.5.2. which does not support F-string syntax.

So the `inv install` command returning an invalid syntax error as followed :

```
File "/var/opt/inventree/tasks.py", line 191
    c.run(f'python {path}')
                         ^
SyntaxError: invalid syntax
```

**I think you must edit the documentation to add a warning or prevent for supported debian versions.**

Something like that :)

For those to whom the problem happens here is a [link](https://unix.stackexchange.com/questions/332641/how-to-install-python-3-6) to install a newer version of Python on Debian Stretch  (I suggest to follow the 2nd answer)

Some issues can happen when running Python newer versions on Debian Stretch, this [link](https://stackoverflow.com/questions/43333207/python-error-while-loading-shared-libraries-libpython3-4m-so-1-0-cannot-open) is useful.

**Comment by eeintech** [comment]
I agree that the supported Python versions (3.6, 3.7) should be mentioned somewhere, in the Readme or the doc.

**Comment by SchrodingersGat** [comment]
I've made the "minimum python version" more obvious on the documentation page.
