### ISSUE TITLE
Document printing

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1252]
Hello I want to print document from the Build details It is posible to print directly or pdf document which must contain. 
Date,
Customer name,
BOM items with consuming quantities,
Part details(Name)
Variant details(Name, description, unit, keywords)-Seperate line or coloumns
Some explanations from Buid notes,-Seperate lines
Look likes this
![PHOTO-2021-01-19-16-36-28](https://user-images.githubusercontent.com/31635566/105232259-2ed7d800-5b79-11eb-947d-71ecb063ba20.jpg)
I couldnt collect the datas from program. Do I need to use weasyprint or xhtml2pdf?
Thanks in advance

**Comment by SchrodingersGat** [comment]
Currently the reporting functionality does not extend to the `BuildOrder` model - although this would be a great addition.

InvenTree uses weasyprint for reporting, so it would be a matter of creating a report model for `BuildOrder`, and passing the particular build context to the reporting engine.

**Comment by neco1982** [comment]
I tried several ways to get pdf report I always got same error.(Error:PDF document couldnt load. Try again) I used some weasyprint documentation and made some changes on build views and created a templates but it is not working. When I do those steps with new project it is working but on InvenTree doesnt work.
![Ekran Resmi 2021-01-22 00 50 34 1](https://user-images.githubusercontent.com/31635566/105417750-1b963c80-5c4d-11eb-8870-03c252f13578.png)
![Ekran Resmi 2021-01-22 00 50 59](https://user-images.githubusercontent.com/31635566/105417759-1df89680-5c4d-11eb-832f-eda912f7bc12.png)
![Ekran Resmi 2021-01-22 00 54 40](https://user-images.githubusercontent.com/31635566/105417767-218c1d80-5c4d-11eb-8999-1af4cc711cd8.png)
![Ekran Resmi 2021-01-22 00 53 25](https://user-images.githubusercontent.com/31635566/105417776-251fa480-5c4d-11eb-890c-5156f8ac1364.png)

**Comment by SchrodingersGat** [comment]
Have you had a look at how the `TestReport` model works?

https://github.com/inventree/InvenTree/blob/b90311acea2e407cefb2141d0577c778430e374c/InvenTree/report/models.py#L180

This is an example of a PDF export from HTML template that is currently implemented - it would be a good starting point.

**Comment by neco1982** [comment]
Solved
![Ekran Resmi 2021-01-28 21 20 37](https://user-images.githubusercontent.com/31635566/106182156-84326b80-61af-11eb-8d54-08750987088c.png)

**Comment by SchrodingersGat** [comment]
That looks great @neco1982 - can you send me the template file and python code used to generate this? I would like to roll it into the main InvenTree code.

**Comment by SchrodingersGat** [comment]
@neco1982 check out the latest version of InvenTree - you can now print build reports directly from the build view.

The "default" build report template can be found here:

https://github.com/inventree/InvenTree/blob/master/InvenTree/report/templates/report/inventree_build_order_base.html

But you can always override with your own template!
