### ISSUE TITLE
Critical: PDF report generation is now broken

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1256]
![image](https://user-images.githubusercontent.com/10080325/105430764-62655000-5ca8-11eb-866d-5aeef2402c05.png)

- Report generation recently moved to the API
- Now is BAD
- Fix!!

**Comment by SchrodingersGat** [comment]
Seems like it might only be an issue when generating LaTeX reports?

**Comment by neco1982** [comment]
Hello I made some PDF report 
![Ekran Resmi 2021-01-28 21 20 37](https://user-images.githubusercontent.com/31635566/106181803-16863f80-61af-11eb-8d49-34d73f10960c.png)

**Comment by SchrodingersGat** [comment]
@neco1982 that looks great - could you share the .html template you used to generate this report?

**Comment by neco1982** [comment]
Here is codes
1.urls.py
url(r'^print/', views.BuildPrint, name='build-print'),
2. views.py
from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile

def BuildPrint(request, **kwargs):     

    items = Build.objects.filter(**kwargs).values('reference','quantity','notes','creation_date','target_date', 'part__name', 'part__description','part__variant_of__name', 'title','allocated_stock__stock_item__part__name', 'allocated_stock__quantity').distinct()
    

    html_string = render_to_string('build/build_print.html', {'items': items, 'time':datetime.now()})
    html = HTML(string=html_string)
    result = html.write_pdf()
        
    response = HttpResponse(content_type='application/pdf;')    
    response['Content-Dispositon'] = 'inline; attachment; filename=İşEmri.pdf' 
    response['Content-Transfer-Encoding'] = 'binary'    
    with tempfile.NamedTemporaryFile(delete=True) as output:
            output.write(result)
            output.flush()
            output = open(output.name, 'rb')
            response.write(output.read())
     
    
    return response

3. build_base.html for link pdf
<a href="{% url 'build-print' build.id %}" type='button' class='btn btn-default btn-glyph' id='build-print' title='{% trans "Yazdır" %}'>
            <span class='fas fa-clipboard-list'/>
        </a>
4. build_print.html
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    

    <title>İşEmri</title>
    
    <style>
        table {
          font-family: arial, sans-serif;
          table-collapse: collapse;
         
        }
        td, th {
          border: 1px solid #cccccc;
          padding: 8px;
        }
        th {
          font-weight: bold;
          text-transform: uppercase;
        }
        @page {
            size: Letter; /* Change from the default size of A4 */
            margin: 2.5cm; /* Set margin on each page */
        }

            @top-center {
                content: "İŞEMRİ";

            }
        }
    
    </style>
    
  </head>
  <body>
    <h1>İşEmri</h1>
    <hr/>
    <table style="width: 100%">
      <colgroup>
        <col span="1" style="width: 80%">
        <col span="1" style="width: 20%">
        
      </colgroup>   
    <tr>
    <div>
        <th>Tarih</th> 
        <th>İşEmri No</th>  
    </div>   

    </tr>
    </thead>
        {% for item in items %}
        <tbody>
          <tr>
            <td>{% ifchanged item.creation_date%}{{item.creation_date|date:'d-m-Y'}}{% endifchanged %}</td>
            <td>{% ifchanged item.reference%}BO{{item.reference}}{% endifchanged %}</td>
            
        {% endfor %}
        </tr>
        </tbody>
      
    
    </table>
   
    <table style="width: 100%">
      <colgroup>
        <col span="1" style="width: 40%">
        <col span="1" style="width: 40%">
        <col span="1" style="width: 20%">
      </colgroup>
    <div>  
    <thead>    
    <tr>
    
          <th>Desen</th> 
        
        
          <th>Varyant</th> 
          
          <th>Metre</th>      
       
    </tr>
    </thead>
        {% for item in items %}
        <tbody>
          <tr>
            <td>{% ifchanged item.part__variant_of__name%}{{item.part__variant_of__name}}{% endifchanged %}</td>
            <td>{% ifchanged item.part__name%}{{item.part__name}}{% endifchanged %}</td>
            <td>{% ifchanged item.quantity%}{{item.quantity}} MT{% endifchanged %}</td>
        {% endfor %}
        </tr>
        </tbody>
        <thead>
    </div> 
    </table>
    <table style="width: 100%">
      <colgroup>
        <col span="1" style="width: 40%">
        <col span="1" style="width: 40%">
        <col span="1" style="width: 20%">
      </colgroup>
    <div>  
    <thead>    
    <tr>
    
          <th>Müşteri</th> 
        
        
          <th>İşlem</th> 
          
          <th>Termin</th>      
       
    </tr>
    </thead>
        {% for item in items %}
        <tbody>
          <tr>
            <td>{% ifchanged item.title%}{{item.title}}{% endifchanged %}</td>
            <td>{% ifchanged item.notes%}{{item.notes}} İŞLEMİ{% endifchanged %}</td>
            <td>{% ifchanged item.target_date%}{{item.target_date|date:'d-m-Y'}}{% endifchanged %}</td>
        {% endfor %}
        </tr>
        </tbody>
        <thead>
    </div> 
    </table>

    <table style="width: 100%">
      <colgroup>
        <col span="1" style="width: 100%">        
      </colgroup>   
    <tr>
    <div>
        <th>Alt Çözgü</th>   
    </tr>
    </thead>
        {% for item in items %}
        <tbody>
          <tr>
            <td>{% ifchanged item.part__description%}{{item.part__description}}{% endifchanged %}</td>           
        {% endfor %}
        </tr>
        </tbody>
      </div>
    
    </table>
    <table style="width: 100%">
      <colgroup>
        <col span="1" style="width: 80%">
        <col span="1" style="width: 20%">
        
      </colgroup>   
    <tr>
    <div>
        <th>Atkılar</th> 
        <th>Miktar</th>  
    </div>   

    </tr>
    </thead>
        {% for item in items %}
        <tbody>
          <tr>
            <td>{{item.allocated_stock__stock_item__part__name}}</td>
            <td>{{item.allocated_stock__quantity}} KG</td>
            
        {% endfor %}
        </tr>
        </tbody>
      
    
    </table>
    
  </body>
</html>

**Comment by SchrodingersGat** [comment]
Fixed by https://github.com/inventree/InvenTree/pull/1270

**Comment by SchrodingersGat** [comment]
Thanks for sharing that @neco1982 

I'll look at integration of Build reports as a first-class InvenTree feature.
