### ISSUE TITLE
Do not delete part image that is still in use

### ISSUE THREAD

**Issue by Kedarius** [inventree/InvenTree#1257]
My part pictures do sometimes disappear and it seems that I have found the reason.
It seems that Inventree deletes part image when changing it and it does not check whether the image is still in use on another part.

So for example I've duplicated part, changed image on the duplicate and the original's image gets deleted...

**Comment by SchrodingersGat** [comment]
Thanks for spotting this @Kedarius

**Comment by Kedarius** [comment]
Well, it was easy to spot  under the right circumstances :-) I've entered cca 20 resistors and all of them but the last had missing pictures :-) At that point I realized that I've been doing duplicate part, change parameters, change picture, duplicate,....
