### ISSUE TITLE
Source for translation

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1261]
Hello I translated program except some section. Would you please help me where comes from those (split and removed received ) I want to change them also but I couldnt find the source. Also bottom pagination explanation showing ...of .. rows?
![Ekran Resmi 2021-01-28 21 27 39](https://user-images.githubusercontent.com/31635566/106183115-e049bf80-61b0-11eb-856a-13c95b092cc9.png)

**Comment by SchrodingersGat** [comment]
These translation hooks should now be implemented in #1263 

Once your translation is done please submit a PR with the translation files! :)

**Comment by SchrodingersGat** [comment]
@neco1982 did #1263 expose those translations for you?

**Comment by SchrodingersGat** [comment]
Hey @neco1982 did you complete the Turkish translation? Are you able to submit the translation files as a pull request?

**Comment by SchrodingersGat** [comment]
I'm going to close this issue out now - please do contribute back your translation data when you have a chance.
