### ISSUE TITLE
New section 

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1264]
Hello I want to create new section called quality ( like parts, stock, built) the users which allowed to reach this section will be able to reach bulids orders with built order numbers (will reach built output stock with built order number) but wont be able to change build orders they will be able to see only built output section inside built order and will be able  change stock location and count it. And the base of this section i want to see details built order number part number quantity and date of stock which had counted or changed location by this section users. Is this possible the structure of program if yes Would you please help me from where i must start? 
Thank you in advance

**Comment by SchrodingersGat** [comment]
Hi @neco1982 I think you will need to provide some further information here, I'm not able to follow what you are suggesting. Perhaps some mock-up images of what you would expect to see?

**Comment by neco1982** [comment]
![0ACB0168-971D-44E0-BBC6-4C2D6202218D](https://user-images.githubusercontent.com/31635566/106455064-bdfbbe80-649c-11eb-8483-a3ff6bc9ee32.jpeg)

**Comment by SchrodingersGat** [comment]
@neco1982 are you looking to have this new information displayed on the InvenTree webpage, or in a generated PDF report?

**Comment by SchrodingersGat** [comment]
@neco1982 I am closing this issue for now, but if you have anything further to add, please feel free to open it again. Thanks
