### ISSUE TITLE
Remove cairo dependency

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1273]
Next WeasyPrint release will [not require cairo](https://www.courtbouillon.org/blog/00004-weasyprint-without-cairo-what-s-different)

**Comment by wengtad** [comment]
Seems like WeasyPrint was removed the cairo dependency. Based on their comment [here](https://github.com/Kozea/WeasyPrint/issues/841#issuecomment-773941914).

**Comment by SchrodingersGat** [comment]
@wengtad yes promising progress! Hopefully the remaining non-python deps will be dealt with soon too :)

**Comment by SchrodingersGat** [comment]
Beta version is out - https://www.courtbouillon.org/blog/00008-weasyprint-53-beta

**Comment by liZe** [comment]
> Hopefully the remaining non-python deps will be dealt with soon too :)

I hope so, but you’ll probably have to wait a little bit more! :wink:

**Comment by rcludwick** [comment]
Don't forget to pull this out of the DockerFile.

**Comment by SchrodingersGat** [comment]
Currently waiting for v2.0 of django-weasyprint to be released : https://github.com/fdemmer/django-weasyprint/issues/53#issuecomment-896122557

**Comment by 42CrMo4** [comment]
@SchrodingersGat fyi [django-weasyprint 2.1.0](https://github.com/fdemmer/django-weasyprint/releases) is released.

**Comment by SchrodingersGat** [comment]
@42CrMo4 thanks for the update, was not aware that v2.x was out yet!
