### ISSUE TITLE
About purchasing a part of the BOM components only

### ISSUE THREAD

**Issue by dsalychev** [inventree/InvenTree#1277]
Hi,

I tried, but didn't find a way to contact you about a little of support except this issue.

I'm looking for an inventory management system which allows not only to track inventory of electronic components,
but also to upload BOM in order to understand how much additional (or missing) components should be bought in order
to build N devices. Does InvenTree allow to do so?

Thanks in advance!

**Comment by SchrodingersGat** [comment]
Yes InvenTree absolutely supports Bills of Material.

https://inventree.readthedocs.io/en/latest/build/bom/

If there is anything not covered in the docs please let me know

**Comment by dsalychev** [comment]
That's good. I'm trying to run a debug version of InvenTree on FreeBSD at the moment. I'm not familiar with Django and its deployment procedure, but it doesn't look that complex for Apache web server though. Thanks for a good alternative to PartKeepr and Part-DB!

**Comment by SchrodingersGat** [comment]
There are a lot of good docs out there on deployment of a Django app - it is very customisable. 

I originally started this project as PartKeepr did not quite meet my needs. Feel free to suggest (or contribute!) features. Hope you find it useful.

**Comment by dsalychev** [comment]
I'm going to spend this weekend preparing software for my own inventory, so, I'll try to provide any kind of feedback. Btw, I just had to tinker with my package manager locally to run `inv install` and `inv migrate` without any troubles. Do you accept patches for documentation?

**Comment by SchrodingersGat** [comment]
Absolutely - if you had to add some custom steps, you can raise a PR on the docs here - https://github.com/inventree/inventree-docs

**Comment by SchrodingersGat** [comment]
Closing stale issue
