### ISSUE TITLE
Restore backup

### ISSUE THREAD

**Issue by ivladz** [inventree/InvenTree#1281]
I have found several mentions of doing a backup in the documentation but no mention of how to perform the restore.
In my test instance I've configured "backup_dir" in config.yaml and performed a backup with "inv backup". Could not find a "restore" method defined in tasks.py

Is there something I'm missing?

**Comment by eeintech** [comment]
@ivladz Yes it is missing. Given `inv backup` is a shortcut for `./manage.py dbbackup` and `./manage.py mediabackup` command, to restore you could try to run:
```
$ ./manage.py dbrestore
$ ./manage.py mediarestore
```
Reference: https://github.com/django-dbbackup/django-dbbackup

Should be fixed with #1284

**Comment by eeintech** [comment]
@SchrodingersGat Should this be in the official doc?

**Comment by SchrodingersGat** [comment]
Yes we should add a guide for backup / restore

**Comment by eeintech** [comment]
Done, see inventree/inventree-docs#55
