### ISSUE TITLE
Modal size scaling

### ISSUE THREAD

**Issue by pawcio0928** [inventree/InvenTree#1282]
Hello, 

when the error occurred modal size is not properly scaled to the window size and the save button is out of the screen. The page is longer of a height of the alert and to I must srcoll down the page. 
Please find that issue on the screenshot below. 
<img width="761" alt="Screenshot 2021-02-08 at 22 09 11" src="https://user-images.githubusercontent.com/5786244/107284218-b9677500-6a5d-11eb-909a-7b9f30920669.png">

My suggestion is to change alert to [toast](https://getbootstrap.com/docs/4.2/components/toasts/) notification in the corner which will be disappear after a while.

**Comment by SchrodingersGat** [comment]
Hi @pawcio0928 I have not been able to replicate this. issue. 

For example I made a really long modal and it did *not* overflow the screen

![image](https://user-images.githubusercontent.com/10080325/107492921-16d7ff00-6be1-11eb-9289-aa7d4ff6b72a.png)

What browser and InvenTree version are you using?

**Comment by pawcio0928** [comment]
@SchrodingersGat  You are right when you add alert in modal-form-content. But from error alert is between header and content. The same location of this alert I found in sources. 

I use the latest version of Inventree. Problem occurred in Safari and Google Chrome. 
<img width="1052" alt="Screenshot 2021-02-10 at 13 15 28" src="https://user-images.githubusercontent.com/5786244/107509016-1f5d1500-6ba2-11eb-927a-d48f2bfbcc5d.png">
