### ISSUE TITLE
Failed to send PO in mail 

### ISSUE THREAD

**Issue by PrashantSangal01** [inventree/InvenTree#1285]
Hi, 

I am running a debug version on my network machine. Things are running OK so far except that the PO mail is not sent to supplier ( a working test mail ID in our case) when order is placed. I think somehow, either it should be connected to existing mail client or its own mail client has to be configured. In both cases, the steps are not found anywhere. May you help in this regard?? 

Thanks and Regards, 
Prashant Sangal

**Comment by SchrodingersGat** [comment]
Hi Prashsant - InvenTree is not currently setup to send emails. The "email" field for a supplier is only for your reference.

However, having the ability to send emails out to suppliers might be a great idea in the future!

**Comment by PrashantSangal01** [comment]
Hello Oliver, 

Thanks for quick response. I am evaluating InvenTree for Electronics / Embedded Lab Inventory Management. Everything else seems to be in place from user point of view ( considering only order placement), except that the mail is not received at other end, which is, as you mentions, due to feature unavailability. The "Place Order" button appears as soon as line items are added to the PO. The mail should be sent to supplier mail ID and cced to the user as soon as "place Order" is completed. 

When do you think this feature may be available? 

Regards, 
Prashant Sangal

**Comment by SchrodingersGat** [comment]
This feature is not on the current development path - there are other much more pressing features. There would need to be a lot of effort to get an email server setup, etc.

No plans at this stage, but if someone was willing to look into it I would be willing to provide some direction.

**Comment by PrashantSangal01** [comment]
Thanks a lot. Closing this issue now.
