### ISSUE TITLE
The meaning of stock status

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1301]
I have a question about stock status field. 
Does it have some special meaning in inventree business logic, i.e. stock items handled differently depending on status?

I have a use case of separation between new and used/salvaged parts.
So for example I would like to track new and used kinds of the same part in the same (or different) storage locations.
If it makes sense I propose to create new status: "Used" or "Salvaged".

**Comment by eeintech** [comment]
That's good point. [Statuses are hard-coded in InvenTree](https://github.com/inventree/InvenTree/blob/4431082440b9db565541d0ec111f07bbbf47616c/InvenTree/InvenTree/status_codes.py#L161) but maybe it should be more flexible, like option for adding user-defined statuses to the logic.

**Comment by sintech** [comment]
I think at this point new status: Used/Not New/Salvaged with color: green and available+receiving will be enough.

**Comment by SchrodingersGat** [comment]
I've added a note to update the docs with some info on how the stock "status" impacts the business logic.

Very short version - some stock status code will remove the stock from certain operations - e.g. you can't add "destroyed" or "lost" stock to a sales order, etc.

Adding a "Used" status flag would be pretty straight forward. It would require manually marking each stock item as "used"

**Comment by rnilssen** [comment]
Perhaps this should be dynamically configureable?

We run a small ISP and is looking to convert our stock system to InvenTree. We primarily have two types of stock, first is consumeables in different variants, like fiber patches and similar. And then there is unique components like fiberoptic transcievers and disk drives which we want to track through their life. What we have run into is that we havent found any way to mark a tracked item as "in use". For example an SSD should be "in use" when its used, yet if its returned to storage we should mark it OK or used or whatever is appropriate. Meaning that "in use" items isnt made available in the stock list.

Does this make any sense to any of you?

Considering the above usecase in comparison to the original usecase in the thread, maybe the status field would benefit from beeing dynamically configurable with custom statuses with their relevant attributes setable?

**Comment by matmair** [comment]
@milssen I do not mean to intrude but have you thought about using a more traditional asset- and inventory-management solution?
I like to recommend a great FOSS called [snipe-it](https://github.com/snipe/snipe-it). I use it for IT-tracking in a company with around 300 Endpoints, a several hundred licenses and a lot of shared assets with a lot of changing users (in an AD). The usecase you describe is covered by it.
