### ISSUE TITLE
Stock status has no tracking history

### ISSUE THREAD

**Issue by jnewlands** [inventree/InvenTree#1303]
It would be nice to track when a stock item is destroyed and add a note (much like how a location transfer is tracked at the moment).

This is part of a broader issue (#1056) where one might wish to track _any_ changes to a stock item. @eeintech 
 and @SchrodingersGat mention [django-simple-history](https://github.com/jazzband/django-simple-history) as a potential solution.

**Comment by eeintech** [comment]
@jnewlands There is also [django-reversion](https://django-reversion.readthedocs.io/en/stable/) as an alternative to django-simple-history, it gives the ability to "roll-back" any instance in a previous state.

I actually don't know that those packages are needed for stock, the current "home-made" history seems fine to me, as long as destroyed stocks can still be accessed through a filter on the Stock page (and filtered out by default).

**Comment by matmair** [comment]
@SchrodingersGat the package(django-simple-history) itself is great but I have had problems when people **restore** data. Used as a fancy log it worked fine.
Some stuff to consider: 
- values in unique fields might be taken again - creating conflicts
- if you have a lot of signals in your model restores might start a lot of tasks - in one case that led to data-continuity problems in a multi-user environment, which are hard to debug if your dataflows were not designed to be rolled back in the first place
- foreign keys might have changed too, that can lead to very strange problems and tends to be hard to figure out afterwards

**Comment by SchrodingersGat** [comment]
All very reasonable points. A good is example is if stock was moved from a location which has now been deleted - there's no way to "undo" that in a single action!

Maybe this is a case of "asking the wrong question". What I am looking to do is refactor the current "stock history" implementation to solve a number of outstanding issues:

- Stock "status" changes are not tracked - https://github.com/inventree/InvenTree/issues/1303
- Stock history items are not properly translated (you know this one)
- Stock history items are not "hyperlinked" - e.g. if you change location, I'd like to be able to click on that location (if that location still exists)

I *think* that the django-simple-history solution is a fine one here, but maybe it is overkill. Hooking into the signals might also be overbearing, we could potentially extend the current functionality of stock-tracking table to include location foreign keys, and status information...

**Comment by matmair** [comment]
I mean if you do not plan to restore anything I do not see a problem, then it might be a great + fast solution.

Stock history items would be translated now 👼. How one would implement that with an automatically generated record/table I would have to check. But passing through custom change-messages will be necessary anyway because the defaults do not mean anything to users.

**Comment by matmair** [comment]
1) this feature was implemented in #1572 
2) do not @ me in closed issues

**Comment by MrShippeR** [comment]
I can't get to know from request Stock Item History how to get it working. Could you navigate me how to get into location where overview is? Should I enable any setting to see it? My account is Admin and Superuser, but didn't see.

Sorry for mentioning. I used it because old discusion...

**Comment by MrShippeR** [comment]
I founded page in Admin->Stock->Stock->Stock item trackings
![inventree3](https://github.com/inventree/InvenTree/assets/12204070/759b8a89-0293-4dfe-8ab4-3bafbbc2629d)

Is it what you refered? Is there any frontend interface?

**Comment by SchrodingersGat** [comment]
@MrShippeR I believe that what you are asking for is already implemented - literally in the screenshot that you shared above. If you think that it is not sufficient, please open a new issue for that.
