### ISSUE TITLE
Part image/attachment from URL

### ISSUE THREAD

**Issue by ivladz** [inventree/InvenTree#1306]
It would be great to be able to add a part image and/or part attachment directly from an URL. Right now you have to download the image/document locally and then upload via GUI.
This together with #623 would make for a great usability improvement.

**Comment by SchrodingersGat** [comment]
Agreed it would be a great productivity increase. I am just unsure on exactly how to best implement it:

- Technical requirements
- Support for browsers
- Security issues?

**Comment by eeintech** [comment]
I think a simple wget (or any other web scrapping Python library) should work to grab the image from the URL and set it as main picture?

**Comment by SchrodingersGat** [comment]
Getting the image from the web is pretty straight-forward, but how to tell the server which image to download?

A) Copy and paste the URL?
B) Drag and drop the image from the browser? (Preferred)

if B) then I am not yet aware of a good way to extract the URL from a drag-and-dropped image

**Comment by ivladz** [comment]
I was thinking of method A, have a URL box in the Image upload form:
![image](https://user-images.githubusercontent.com/2379634/108223867-f52bca00-7142-11eb-86ef-be64d92eaa83.png)
Where you would paste an image link from the web (for example https://inventree.readthedocs.io/en/latest/assets/images/api/api_doc.png).

This would make a 2-step process (download the file locally, then uploading it via the existent functionality) into 1-step fast process. I guess the only "drawback" on this method is that the Inventree server requires internet access (don't know if right now it really needs it for something).

**Comment by eeintech** [comment]
I was also thinking A) because it's easy enough to right-click on the image and directly get the URL.

A check for internet access would be needed indeed.

**Comment by SchrodingersGat** [comment]
It should not be too hard to implement it this way. However there is a level of "user trust" here, exposing the server directly to the internet!

**Comment by eeintech** [comment]
@SchrodingersGat Agree but I think it comes down to the same level of trust for user to download the image on their local machine then upload it to InvenTree. Whatever is embedded in the "image" file will persist. This would just cut the middle man (eg. local machine). What do you think?

**Comment by SchrodingersGat** [comment]
Sure, it's the same on the "client side" of user trust. 

I guess that on the server side, we could ensure that the code to actually download the image performs a bunch of checks:

- The URL looks like an image
- Only download a certain maximum file size
- Sanitize the image after download 
- Handle plethora error cases

**Comment by eeintech** [comment]
This sounds like a fun little project :smile:

**Comment by SchrodingersGat** [comment]
Work in progress here - https://github.com/inventree/InvenTree/pull/1410
