### ISSUE TITLE
Unified attachments/images/links system

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1312]
In current version of inventree we have three different entities for a part:
- attachment: multiple (uploaded file + comment)
- image: single
- link: single

Which is pretty limiting if you have a lot of pictures of item and links to datasheets or manufacturer website.

What do you think about creation of new unified attachment model with above mentioned entities as members?
New attributes:
- 'type' - define the type of entity: 'attachment, picture, link'.
- 'link' - could have url of remote document (pdf, picture, etc.) or local file for uploaded media.
- 'comment' - name or description of the document (

If one wants to make a local copy of document during adding, it could be done by 'download' checkbox.

**Comment by SchrodingersGat** [comment]
I like the idea - although isn't an "image" just a particular type of "attachment"? Currently you can add any amount of images under the "attachments" field?

**Comment by sintech** [comment]
> isn't an "image" just a particular type of "attachment"?

Yes your are right, but it is not very convenient from UX point of view. Even the current implementation of part image does not allow to open it in full size (without involvement of right mouse button). It would be great if click on part image could open modal window with enlarged image, thumbnails and Carousel style controls.
About the links. I know it good to have your own copy of every datasheet pdf or part image, but why limit yourself to everything local if we can just add a link to manufacturer or distributor website. In my current inventory system I mostly use links to various documents related to specific part including images. Only exceptions are my own projects and rare parts.
