### ISSUE TITLE
[demo site] - missing buttons on Allocation page ?

### ISSUE THREAD

**Issue by fenugrec** [inventree/InvenTree#1317]
Is it too early to file bugs against the demo site ? (I'm testing a few things before I commit to setting up my own instance)

Following the docs and trying to allocate parts for a build on the demo site, for example this part https://inventree.polarize.xyz/part/25/allocation . I made + validated a simple BOM for it; but when looking at the "Allocated" page, I'm not sure what to do. I was expecting maybe some buttons to auto-allocate ? Or did I miss a step ? 

![demo_alloc-crop](https://user-images.githubusercontent.com/10098613/108251271-185c7680-714f-11eb-9248-22440ea97797.png)

**Comment by SchrodingersGat** [comment]
That tab simply shows where the part is currently allocated.

To actually allocate the parts to a build, you will need to navigate to the particular "Build" page

**Comment by eeintech** [comment]
When a "Widget" is allocated in build, this is how it would look like:

![image](https://user-images.githubusercontent.com/4020546/108274049-628b2b00-7142-11eb-8162-fdeb35cf0169.png)

However I have to agree this "Allocated" tab tend to be confusing...

@SchrodingersGat What about hiding it when the part is not allocated in any build?

**Comment by SchrodingersGat** [comment]
Good idea re: hiding - the "tabs" interface desperately needs improving - see https://github.com/inventree/InvenTree/issues/1171

**Comment by fenugrec** [comment]
> When a "Widget" is allocated in build, this is how it would look like:

! How did you do that ? Spent 10 minutes trying to figure it out. Went in the build order, the part page, tried making a new build order...

**Comment by eeintech** [comment]
@fenugrec It is not admittedly not straight forward but here are the basic steps:
1. the "Widget" part needs to be used in a new assembly (as a BOM item)
2. you need to create a build order for that assembly
3. you need to allocate parts for the build of that assembly (eg. referencing the "Widget" part)

**Comment by fenugrec** [comment]
Thanks @eeintech  . I didn't think of checking "Create output" on the "Incomplete" tab.
