### ISSUE TITLE
Specific Unit Testing

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1322]
- [ ] Algorithm for generating next build number
- [ ] Algorithm for generating next serial number
- [ ] Algorithm for generating next PO number
- [ ] Algorithm for generating next SO number
- [ ] Change a Part from "non-trackable" to "trackable" (check that "upstream" parts are now trackable)
- [ ] BOM item deletion via API
- [ ] BOM item creation via API
- [ ] BOM item editing via API
- [ ] Test form / view for allocating items to a sales order by serial number (ref: https://github.com/inventree/InvenTree/pull/1426)

**Comment by matmair** [comment]
@SchrodingersGat aren't the first few items covered by your new validation PR?

**Comment by SchrodingersGat** [comment]
Yes most of this is either fixed or outdated. I'll close it out
