### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by maxsimongt3** [inventree/InvenTree#1328]
Hello 

I'd like to know if there is an issue with importing overall or if its just on my end
or maybe I'm just doing something wrong.
<img width="1912" alt="Screen Shot 2021-02-18 at 5 40 55 PM" src="https://user-images.githubusercontent.com/78984540/108433976-e01f6b80-7214-11eb-99aa-f39189ee9bee.png">

**Comment by SchrodingersGat** [comment]
You need to make sure that the **id** field is empty for any new records.

If the **id** field is non-empty, then it will attempt to find an *existing* Part matching that **id** - and it returns an error if it does not match

**Comment by maxsimongt3** [comment]
Thank you so much Oliver
<img width="1046" alt="Screen Shot 2021-02-18 at 7 04 15 PM" src="https://user-images.githubusercontent.com/78984540/108438021-68edd580-721c-11eb-96a1-6cc1a1dcf448.png">

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/inventree-docs/pull/65
