### ISSUE TITLE
Android APP - This app is not available for any of your devices

### ISSUE THREAD

**Issue by ivladz** [inventree/InvenTree#1337]
First of all, NICE! the first release of the mobile app
Don't know if this is the right place for app related issues but here I go.

When I check the app in the google store it says it's unavailable for my device (OnePlus 7 Pro - Android 10, country Romania). Any idea why?

**Comment by SchrodingersGat** [comment]
Hi @ivladz !

> Don't know if this is the right place for app related issues but here I go.

Yes this is definitely the right place. I want to keep all the issues in a central location :)

> When I check the app in the google store it says it's unavailable for my device (OnePlus 7 Pro - Android 10, country Romania). Any idea why?

The initial app release (`0.1.0`) was mostly an exercise in figuring out the Play Store requirements - it was quite complicated! For this release I only selected a small subset of countries to release to.

I will very soon be releasing `0.1.1` which will be available to a wider range of countries and also fix a few bugs.

Should be out in the next couple of days. I'll leave this issue open until then, and let you know when it is available for you!

Tell all your Romanian friends :)

**Comment by SchrodingersGat** [comment]
Ok, update 0.1.1 is now online, it should be available to you now! Best of luck :)

**Comment by eeintech** [comment]
@SchrodingersGat Just curious... given you decided to monetize the app, is InvenTree going to have to same treatment at some point in the future? Can you please communicate on your intentions a bit?

**Comment by eeintech** [comment]
Also, any chance you can offer a trial? Would be nice to have a way to evaluate it.

**Comment by SchrodingersGat** [comment]
The main InvenTree web app will always remain free, and open source. I made the decision to monetize the app to support ongoing development.

Rest assured that InvenTree at large will not follow this path.

**Comment by ivladz** [comment]
Glad to hear that the web app will remain free!
I'm also ok with paying a one time fee for the mobile app, as long as it doesn't get to a subscription based model.. (there are too many of those these days)

Back on topic, it is now available on the google play store for me. So I guess this can be closed.

**Comment by SchrodingersGat** [comment]
Yeah I don't want to lock people into a subscription payment or anything like that! Please let me know (by raising another issue here) if you have any problems with the app at all.

Also as it is very early version, if you have any suggestions for features or functionality, let me know too!

**Comment by eeintech** [comment]
Awesome, glad to hear I will still be able to push whenever I get time for that :smile:
