### ISSUE TITLE
Side Tree Error

### ISSUE THREAD

**Issue by Tabarane** [inventree/InvenTree#1345]
when assigning category item with long name the tree view get broken in view

InvenTree Version | 0.1.7 pre

![image](https://user-images.githubusercontent.com/28815281/108713796-297ffb80-7532-11eb-86d1-10946bbf0d8f.png)

**Comment by SchrodingersGat** [comment]
Thanks for reporting @Tabarane 

Looks like this also applies for the *Part Category* tree display.
