### ISSUE TITLE
APP - scan barcode blank screen

### ISSUE THREAD

**Issue by ivladz** [inventree/InvenTree#1357]
When I use the "Scan barcode" functionality on the mobile app I get the following blank screen:
![Screenshot_20210224-153938](https://user-images.githubusercontent.com/2379634/109009470-40038f80-76b7-11eb-92a2-fa876286903e.jpg)

Phone: OnePlus 7 PRO
Android: 10

What is the camera it tries to use?
I ask because my phones selfie camera is a pop-up camera.

**Comment by SchrodingersGat** [comment]
1. Are you presented with any error message?
2. If you "activate" the pop-up camera does it do anything different?

**Comment by ivladz** [comment]
1. No message, just the blank screen.
2. Don't know of a manual way to pop the camera.. normally the camera app does it when it is switched to selfie mode

**Comment by SchrodingersGat** [comment]
@ivladz ok thanks for the feedback. I'll have to look into this one.

There are a few different ways to enter "scan barcode" mode - either from the home screen, just for general scanning, or from a stock item or stock location actions context. Does the same issue occur if you open the scanner view from the stock item "actions" tab?

**Comment by ivladz** [comment]
I've tried "scan barcode" from multiple locations, same thing.
An interesting thing: I would have expected to be asked for camera permission, but that did not happen. When I went into the permission settings per app I saw that InvenTree had no permission granted. Then I manually enable camera permission but this still didn't change anything.

**Comment by SchrodingersGat** [comment]
Huh, it definitely should have asked for camera permissions (this is what it does on my devices).

I think I will have to update the barcode library I am using and push out an update - *hopefully* that will fix it? Should have something for you in the next couple of days :)

**Comment by SchrodingersGat** [comment]
Try updating to 0.1.2 and see if the issue is resolved :)

**Comment by ivladz** [comment]
Updated and tested, works great! First impression: it's fast!
And it also asks for permission for Camera on first use now.
Will come back if other issues pop up, after doing some more intensive testing :)
