### ISSUE TITLE
Landing Part view does not display part list

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1365]
I think I have the right filter enabled?

![image](https://user-images.githubusercontent.com/4020546/109319528-f46af600-781c-11eb-9a79-f60ce501db67.png)

It works at category level:

![image](https://user-images.githubusercontent.com/4020546/109319655-18c6d280-781d-11eb-867b-5c6ee9f295e5.png)

**Comment by ivladz** [comment]
I'm also seeing the same thing after updating my InvenTree with the latest code.

**Comment by SchrodingersGat** [comment]
oops, fixed in https://github.com/inventree/InvenTree/pull/1363
