### ISSUE TITLE
buttons not responding

### ISSUE THREAD

**Issue by maxsimongt3** [inventree/InvenTree#1369]
https://user-images.githubusercontent.com/78984540/109355596-7246f580-784d-11eb-8540-31f73cb0ce14.mov

I updated the repository on my computer and this started happening
can any one help

**Comment by ivladz** [comment]
Can you try after doing a force refresh of the page? (CTRL+F5)

**Comment by maxsimongt3** [comment]
that worked 
thank you

**Comment by SchrodingersGat** [comment]
https://inventree.readthedocs.io/en/latest/faq/ ;)

After updates where the CSS or JS files are changed, you need to make sure your browser grabs the latest copy, rather than using the cached files!

Thanks for helping out @ivladz
