### ISSUE TITLE
lost function call initSideNav() in item_base.html

### ISSUE THREAD

**Issue by mosenturm** [inventree/InvenTree#1375]
Hi,

there is a lost function call `initSideNav()` in `item_base.html` whith a lot of side effects (stock entry info table not showing, **+New Entry** button not working, ...) If I remove the function call, everything is working fine.

**Comment by SchrodingersGat** [comment]
Have you tried doing a hard-refresh of the page (`Ctrl`+`F5`) - the JS files may be out of date in your browser cache

**Comment by mosenturm** [comment]
Yes, I have doing and hard reload with clearing the cache. I've cloned the repo from github yesterday. Also the function declaration `initSideNav()` is not to find in the sources - only the function call.

**Comment by SchrodingersGat** [comment]
Merged in now. LMK how you go.
