### ISSUE TITLE
Part views are extremely slow

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1378]
Ref: https://github.com/inventree/InvenTree/pull/1373#issuecomment-788305898

This is *not* related to the API - the actual HTTP request is delayed for ~10 seconds before returning anything at all

**Comment by SchrodingersGat** [comment]
Serving the page itself is taking over 10 seconds...

![image](https://user-images.githubusercontent.com/10080325/109563627-21c4e600-7b34-11eb-86b7-20f319ec5c4c.png)

**Comment by SchrodingersGat** [comment]
Ah dang, false alarm. I had django-debug-toolbar turned on and the introspection required to service that is what was taking ages.

Turning the toolbar off reduced response time to 600ms

**Comment by SchrodingersGat** [comment]
@eeintech you don't happen to have the debug toolbar enabled do you?

**Comment by eeintech** [comment]
@SchrodingersGat Only on my local instance, not on our server. I will enable it right now to see what I get and keep you posted

**Comment by SchrodingersGat** [comment]
For reference my test BOM (with 60 parts) takes ~200ms to load

**Comment by eeintech** [comment]
So apparently with `debug = True` all part details page take much longer to load. But regardless, the BOM takes the same time as before (15-20s) and I can't find any relevant telemetry data in the debug toolbar:

![Screenshot from 2021-03-01 17-18-59](https://user-images.githubusercontent.com/4020546/109566839-7162cd80-7ab2-11eb-9d3c-d27d8d8c48e6.png)

What do you think?

**Comment by SchrodingersGat** [comment]
Can you post a screenshot of how long the various ajax requests are taking once the page is loaded?

**Comment by eeintech** [comment]
@SchrodingersGat 

![image](https://user-images.githubusercontent.com/4020546/109569129-f00d3a00-7ab5-11eb-9cc5-6894ce7e073d.png)

I've noticed that the loading time is drastically improved whenever I only select "25" items displayed vs "100".

I've also tried Firefox instead of Chrome and it seems slightly faster... could it be my computer?

I asked a colleague of mine to load it on his local machine (using Chrome) and it takes about 6-7s, much faster than on mine.
A little confused what's happening here and no idea how to debug it...

**Comment by SchrodingersGat** [comment]
> I've noticed that the loading time is drastically (20s becomes 5-6s) improved whenever I only select "25" items displayed vs "100".

Interesting. Selecting how many items to display is a client-side issue, as all the BOM items are pre-loaded before display.

I wonder if it *is* your computer. 

Do you see a significant lag when switching between displayed pages of BOM items?

**Comment by eeintech** [comment]
No lag no, the switching is instant.

**Comment by SchrodingersGat** [comment]
That would indicate that the "lag" is caused by the initial client-side javascript processing code... very strange indeed
