### ISSUE TITLE
Add custom stock status labels

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1386]
Add the ability to customize existing stock item labels, and also add new ones.

Care needs to be taken to ensure that the existing business logic works...

- [ ] Import existing hard-coded status labels
- [ ] Customize name of status labels
- [ ] Customize "in_stock" status of each label (does the label mean the item can be used as 'stock'?)
- [ ] Customize label color
- [ ] Ensure label names are passed through the translation engine
- [ ] Prevent duplicate labels
- [ ] Pass all label info through to the client-side javascript framework
- [ ] How does the app know what the labels are (and how to display them?)

Ref: https://github.com/inventree/InvenTree/issues/1301

**Comment by matmair** [comment]
@SchrodingersGat would this be a roadmap item?

**Comment by SchrodingersGat** [comment]
I think that given how integral the 'stock status' label is to the business logic, I'm not keen to pursue this any further. Thanks for pinging this one.

**Comment by matmair** [comment]
I think it would be cool to customise this but there is a ton of more important things to go around.
