### ISSUE TITLE
"Form errors exist" in Part Pricing modal

### ISSUE THREAD

**Issue by cdwilson** [inventree/InvenTree#1399]
I was testing out the Part Pricing modal, and when I click on the "Calculate" button, I get an error saying "Form errors exist".

This was tested on ed028aed629113855a3982d5b013a94fc749aa7f

![image](https://user-images.githubusercontent.com/14631/110897075-9ecd2980-82b1-11eb-8d4a-7d2040046961.png)

**Comment by SchrodingersGat** [comment]
@cdwilson this looks like a visual bug only - that "form errors" div should normally be hidden.
