### ISSUE TITLE
[FR] Cannot set Responsible User for a Part during creation or API

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#1416]
The responsible user can be set in the administrator interface. I found no way to set it during normal part creation. I also found no way to set it via API and python extension. Do I miss something?

**Comment by SchrodingersGat** [comment]
Do you have **Stock Ownership Control** enabled?

![image](https://user-images.githubusercontent.com/10080325/112747597-1d400000-9002-11eb-9767-a140fa450903.png)

**Comment by SergeoLacruz** [comment]
Yes, that is on. But I think this enables a responsible user for the stock. A was talking about the responsible for the part.

![responsible_user](https://user-images.githubusercontent.com/10836099/112955786-14554880-9140-11eb-8273-eee21c0dd8e0.png)

**Comment by SchrodingersGat** [comment]
Ah, I see. The `responsible user` field for the `part` model doesn't actually *do* anything yet, so it is only available via the admin interface!

**Comment by SergeoLacruz** [comment]
OK. So I assume it is an unfinished feature. 
I am working on migrating a database with about 2000 components from a legacy system. We have such a field that tells who originally asked for that part to be added to the database. No further function.

**Comment by SchrodingersGat** [comment]
Sounds like that the field would be a good place to put that data, then. How are you importing the records across? Using the admin import tools?

**Comment by SergeoLacruz** [comment]
I use the python interface based on the example with the couch. This allows the required flexibility to shuffle all parameters around.

**Comment by SergeoLacruz** [comment]
Hi,
Let me come back to this question. I there anything to bring this forward? 
Michael

**Comment by matmair** [comment]
@SergeoLacruz the field does not really do anything so while it could be added to ui and API I am not sure what benefit it would bring. What would you like to use it for? Any specific functionality in mind or more for just keeping that info?

**Comment by SergeoLacruz** [comment]
Hi,
I do not any functionality in mind. In our old system we store which designer originally requested that part. This guy usually has additional info on how to use it and if there where problems. Thats why we store this info.

**Comment by matmair** [comment]
@SergeoLacruz wo bds straight forward to implement

**Comment by SergeoLacruz** [comment]
I think so. But honestly, I have no clue on where to start. I did not dig into the code so deep.

**Comment by matmair** [comment]
@SergeoLacruz looking into adding this. Would you imagine this as a freeform text field or a owner field (user / group)?

**Comment by SergeoLacruz** [comment]
An owner field would be better.
