### ISSUE TITLE
Upgrading From 0.1.5 To 0.1.7

### ISSUE THREAD

**Issue by Junky24** [inventree/InvenTree#1420]
I have been trying to upgrade inventree from 0.1.5 to 0.1.7 using postgresql as the database. And the problem that I am running into is that fact the database model for inventree has like five extra rows in it and the source code gives me errors saying that is does not have permission to add the necessary rows. So I was wondering if there is an easy way to get inventree to add those rows without changing the data.

Thanks

**Comment by SchrodingersGat** [comment]
@Junky24 can you please provide the exact commands you are using to upgrade, and the full error message?

**Comment by Junky24** [comment]
I first used the move command to move the entire old inventree folder to a second drive so that I can keep a working inventree available to help me get the update working, then I downloaded the tar ball for version 0.1.7 and expanded it into the path where 0.1.5 used to be. After that I went into the new inventree folder and ran inv install to get all the needed libraries installed then I did inv postgresql to install the libary that allows me to use the postgresql data base from the old inventree, next I edited the config.yaml to comment out the sqlite database setting, and setup the postgresql engine with the database name, username, password, and host and port numbers. Then I did inv migrate and I got an error about not having permission matching some report.view something or other.
If I leave the config.yaml unchanged, it works ok, with the sqlite database.
If I create a new postgresql and point the config.yaml to that one instead of the old existing, it works ok.
But when I try to use my old database, I get errors.  When I examine the differences between the old and new postgresql databases, I notice some new tables/rows added.  (I'm not very database literate).  So I assume that the new additions are the source of the problem.  Any suggestions?
Thanks.

**Comment by eeintech** [comment]
@Junky24 I thought you may have ran into the same issue as me, see #1427. But given your initial comment of table data mismatch, I created a new issue.
See if you can comment out line 349 of `InvenTree/users/models.py` file and re-run `inv migrate`, maybe that'd fix your issue.

**Comment by eeintech** [comment]
@Junky24 You should re-try now as Oliver has fixed the issue I mentioned in #1430

**Comment by eeintech** [comment]
@Junky24 Any chance you could re-try with the latest version of InvenTree?

**Comment by SchrodingersGat** [comment]
@Junky24 I'm closing this issue for now, but if you come back here and need further assistance please feel free to open it again.
