### ISSUE TITLE
Support different unit of measure (UoM) for each supplier

### ISSUE THREAD

**Issue by cdwilson** [inventree/InvenTree#1435]
I'm not exactly sure the correct term for this, but I'm wondering if InvenTree supports different unit of measure (UoM) for each `SupplierPart`.  For example, when buying screws from McMaster-Carr, the UoM can be specified in "packs", where the a quantity of "1 pack" equals 100 screws:

![image](https://user-images.githubusercontent.com/14631/113455184-dc0f6d80-93be-11eb-92f1-a1ccd4ddf0fd.png)

If I'm building an assembly that requires 4 screws per assembly, and I'm building 25 assemblies in total, I would need to generate a PO for McMaster for qty 1 (pack) of screws.  However, if have multiple suppliers for the same `Part`, each supplier may have a different UoM for their SKU which will determine the Qty to be used on the PO.  Another supplier for the same part may sell the screws in "bags" where "1 bag" equals 25 screws (and the PO for this other supplier would require Qty 4).

I'm curious if InvenTree has any way to handle this?

**Comment by SchrodingersGat** [comment]
Sounds like this is a very similar issue to:

- https://github.com/inventree/InvenTree/issues/1126
- https://github.com/inventree/InvenTree/issues/1192

Currently InvenTree does not support this, other than adding quantity "100" to the order..

I'd be interested in suggestions as to how to best handle this...

**Comment by matmair** [comment]
@SchrodingersGat @cdwilson I would like to implement this:
- each SupplierPart can be assigned a number of contained parts (one part-definition per SupplierPart - either Part, ManufacturerPart or SupplierPart)
- on receiving the item it gets split automatically in the screen - so if 100 are in the SKU then you can assign 20 to location A and 80 to location B in this step
- multi-part SKUs should be done as a separate FR I think (see #1192)

Let me know what you think - I am thinking about imlementing it in a few weeks, should be more contained then other things.

**Comment by SchrodingersGat** [comment]
I also think it makes sense to implement these things separately. Please let me know when you've got space to implement this and we can discuss!

**Comment by cdwilson** [comment]
@matmair FYI for when you start looking into this, I ran across these articles which give a good overview of UoM and some additional examples:

- https://www.aligni.com/doc/guides/units-of-measure/
- https://www.aligni.com/doc/basics/units/

> each SupplierPart can be assigned a number of contained parts (one part-definition per SupplierPart - either Part, ManufacturerPart or SupplierPart)

If I'm understanding you correctly, it sounds like what you're proposing is a solution that addresses the specific use case I mentioned above, i.e. the supplier SKU is simply an integer multiple of the inventory quantity (which currently has an implicit UoM in InvenTree of "each").  However, it doesn't sound like this will actually introduce real unit of measure support in InvenTree, which is probably fine if you don't want to actually introduce an explicit UoM system.

In the Aligni articles I linked above, it appears that they have implemented a more full-featured UoM system which allows an explicit UoM ("each", "inch", "ounce", etc) to be assigned to each inventory item.  It also appears that their system automatically performs unit conversions between the "buy unit of measure" and the "inventory unit of measure" which seems really nice.  While this kind of system can handle more use cases (e.g. purchasing spools of wire in meters), it is also more complicated to implement and requires up-front setup of the conversion rules.  

I'm not sure if something like this makes sense in InvenTree, but I figured I'd mention it in case it might inform how you were thinking about implementing this.

**Comment by matmair** [comment]
@cdwilson thanks for the links. That is how basically all PLMs work so my approach will be in the same general direction.
The user will def. have to do the conversion in their head as I am not about to try to understand them imperial system of measurements. I can code - I am not a wizard 😂

## Implementation plans:

It's just a float input (with enforcement for integer if the part is tracked) and field in the database and business rules to ensure you do not try to split a tracked part on receiving - because what sense does it make to track 0,25 of a unique part.

Full UoM is quite hefty for hobby users - I see engineers struggling with the concept all the time. That could come later although it should only be done in a way that it needs to be enabled.

This is in a 2-8 weeks horizont for me - 0.6.1 or 0.6.2

**Comment by SchrodingersGat** [comment]
@matmair sorry can you clarify? Not sure exactly what you are suggesting.

**Comment by matmair** [comment]
@SchrodingersGat I would add a float field to the supplier part model with how many of the part/manufacturer part are contained by the supplier part. So on receiving the part would be split into that many parts. Also, there needs to be a check so that trackable parts are only split into full units.

**Comment by SchrodingersGat** [comment]
@matmair right, I think that makes sense.. We'd need to consider this very carefully.

**Comment by miggland** [comment]
This sounds like a feature I want :)

**Comment by SchrodingersGat** [comment]
> This is in a 2-8 weeks horizont for me - 0.6.1 or 0.6.2

@matmair how did that work out for you ;)

**Comment by SchrodingersGat** [comment]
@cdwilson long time coming but check out https://github.com/inventree/InvenTree/pull/3644

**Comment by matmair** [comment]
> > This is in a 2-8 weeks horizont for me - 0.6.1 or 0.6.2
> 
> 
> 
> @matmair how did that work out for you ;)

Been using a backend-only solution for a few months ;-) . I just really hate building frontends.

**Comment by SchrodingersGat** [comment]
:O holding out on us?
