### ISSUE TITLE
Why is company description a required field?

### ISSUE THREAD

**Issue by cdwilson** [inventree/InvenTree#1436]
Just curious if there is a reason why company description is a required field.  I'm usually not really sure what to put in the description field, so I typically just put the company name again.  As a result, all my suppliers and manufacturers show up with an awkward name where it's duplicated twice...

1. Is it possible to make the description field optional?
2. I'm curious how other people use this field.  Can you give some examples of what you typically put in the description for companies like Digi-Key, Mouser, etc?

![image](https://user-images.githubusercontent.com/14631/113456145-52ad6a80-93c1-11eb-8a54-b8c15f745fc6.png)

**Comment by SchrodingersGat** [comment]
Fair question, it could be made an optional field without detriment. 

I do find it useful as while the engineering dept knows all about suppliers like Digi-Key etc, other depts might need some context info e.g. "supplier of electronic components."

But sure, can make this field optional

**Comment by SchrodingersGat** [comment]
I'm away on holiday for a week but feel free to submit a PR to make this field optional :)
