### ISSUE TITLE
Error ['git', 'rev-parse', '--short', 'HEAD'] after updating for first time

### ISSUE THREAD

**Issue by Marioheld** [inventree/InvenTree#1439]
I encountered the following problem after updating InvenTree for the first time. 

I installed InvenTree 0.1.5 following the installation instructions but using zip download of the source instead of the git command. Everything worked flawlessly until I tried to upgrade to 0.1.7. 
Trying to download the new release zip files and overwrite the old files did not work well. 
The login page still worked but the index page crashed with error: 
```
CalledProcessError at /index/
Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.
```

Seems like the about.html can not generate a hyperlink to Github because it is missing the commit hash, probably due to the install method of using the zip releases and not using git pull. 

Switched to using git clone and git pull to work with the InvenTree files works better. 

Maybe add a hint in the docs that using git is the recommended way or adding more update information for Installations which used zip files and add an exception for the git rev-parse command?

![Issue](https://user-images.githubusercontent.com/4212288/113759968-fe362200-9715-11eb-9c95-98e700209fa3.PNG)

**Comment by eeintech** [comment]
@SchrodingersGat About this, shouldn't users be warned that, as InvenTree is updated so frequently, the zip install is **not** recommended?
