### ISSUE TITLE
Cache translated javascript as "static" files

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1440]
-Serve js files under the "static" directory
- e.g. allows serving separately
- Improved performance
- Create various translations using the "invoke translate" command
- Follow the "traditional" approach of separating js files into different languages.

Ref: https://github.com/inventree/InvenTree/pull/1437

**Comment by matmair** [comment]
So I tried this and there a few problems:

- in some js-files there is other template data than translations
- a long ttl on the static dir could cause issues when updating
- the performance gain compared with a good oiled gunicorn instance is insignificant

@SchrodingersGat the gain from doing this seems to be miniscule, there is so much more to gain from other issues I would leave this as-is.

**Comment by SchrodingersGat** [comment]
Fair points. If we ever get to the point where we're seeing a performance hit we can readdress.

Another consideration is that the client mostly caches these files anyway!
