### ISSUE TITLE
Remove duplicate columns from part tables

### ISSUE THREAD

**Issue by cdwilson** [inventree/InvenTree#1442]
(Adding this as a separate issue per request in https://github.com/inventree/InvenTree/pull/1417#issuecomment-815024403 from @eeintech)

There are a couple places (e.g. part stock pages) where the tables include info that is duplicated from the page header.  This info is identical for each line in the table, and it causes the table to be crowded on smaller screens.  Would it be OK to remove these duplicate columns?

![image](https://user-images.githubusercontent.com/14631/113967552-0bbadd00-97e6-11eb-8e89-b5144079e582.png)

![image](https://user-images.githubusercontent.com/14631/113967562-0f4e6400-97e6-11eb-9728-79b7f551a43c.png)

**Comment by eeintech** [comment]
@cdwilson Checkout master :wink:
