### ISSUE TITLE
API: Updating PartParameters

### ISSUE THREAD

**Issue by Novakov** [inventree/InvenTree#1451]
I'm playing a bit with InvenTree and trying to build scripts that will allow me to import a lot of parts into database (like Ki-nTree but different data source and a lot of parts at once). My idea was to build scripts incrementaly but I might hit issue with part parameters API: it is not possible to edit existing part parameter.

I'm using Python with `inventree` package and following function for creating or updating paramater for given part:

```python
def set_param(part: Part, param: ParameterTemplate, value: Any):
    existing_params = part.getParameters()

    matching = list(filter(lambda x: x.template == param.pk, existing_params))

    if not matching:
        Parameter.create(db, {'part': part.pk, 'template': param.pk, 'data': value})
    else:
        matching[0]['data'] = value
        matching[0].save()
```

Function works fine when parameter does not yet exist (parameter is visible in UI, value is correct and I can modify it by hand), however editing fails with:

```
WARNING:root:Bad response (405) - PUT 'http://host:8000/api/part/parameter/2/' - {"detail":"Method \"PUT\" not allowed."}
ERROR:root:PUT request failed at 'part/parameter/2/' - 405
```

InvenTree version: 0.1.8 pre (53c9475e)

**Comment by SchrodingersGat** [comment]
Fix incoming - https://github.com/inventree/InvenTree/pull/1453

Turns out the `PartParameter` model did not have a detail endpoint allowing for update / delete operations.

**Comment by Novakov** [comment]
That was quick, thanks a lot :)
