### ISSUE TITLE
Creating variant from template doesn't copy paramaters if invoked from "create new part"

### ISSUE THREAD

**Issue by laaber** [inventree/InvenTree#1454]
Hi,
I've just started evaluating/testing InvenTree, so maybe I'm just doing it wrong :)
I'm using commit-ID 72f83771f127f15f64251d3eec8b01999efaec90

That said...
I've created a Part and set "Template" to true. I've added a parameter to it. Now I'm creating a variant of this template part by opening the template part, click "variants" (URL: /part/3/variants) and "new variant". "Copy Parameters" is enabled, "variant of" shows my template part. The new part inherits the parameters from the template.

Now I create another new part from the categories page, select my category and choose my template in the "variant of" field. The interface only allows to copy the category's and its parent's parameters (didn't find out where these are defined). The parameters from the template part aren't copied to the new item and there's no option to enable this.

Expected behaviour:
Both interfaces allow to use the parameters from the template part or parameters from the template are always used (= remove the options and just copy the parameters).

The ability to copy parameters was introduced with https://github.com/inventree/InvenTree/issues/955, I think.
I didn't test it with BOMs, maybe they behave the same way.

**Comment by SchrodingersGat** [comment]
@laaber I see what you are saying here, and it is a discrepancy for sure.

I'll have to have a think about how to best handle this, it's a subtle different to the user but potentially difficult to implement.

Your suggestion of simply *always* copying the parameters downstream might be the best, certainly the simplest, approach.

**Comment by eeintech** [comment]
@laaber Good catch indeed.



> The interface only allows to copy the category's and its parent's parameters (didn't find out where these are defined).

Those parameters are defined in the Settings menu, under the "Categories" tab.
Select a category then define the parameters for this category.
Every time a part is created inside this category, you'll have the option to automatically create parameters from the templates attached to that category and/or the parent categories.

**Comment by SchrodingersGat** [comment]
Fixed in https://github.com/inventree/InvenTree/pull/1904
