### ISSUE TITLE
Django Q and Django secret key documentation fixes.

### ISSUE THREAD

**Issue by rcludwick** [inventree/InvenTree#1455]
Excellent work on the docker file.  

I would add the following in the documentation of the workers.  

All workers and servers need the same DJANGO_SECRET_KEY, otherwise the workers will not work correctly.  Hit that in development a ways back.  It's a subtle bug that will trip people up.  (especially if they decide to run 2 servers for high availability)

Also I would add documentation on docker hub so that people understand exactly what their docker compose needs to look like.  

See the following as an example:  

https://hub.docker.com/r/linuxserver/plex

You don't probably have to be that detailed, but a good docker compose file there would be nice.

**Comment by SchrodingersGat** [comment]
This has now been fixed in the docs - thanks for pointing this out.
