### ISSUE TITLE
advanced translation pipeline

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1459]
Hi @SchrodingersGat I thought a bit about how one could streamline the translation pipeline - especially for people who are not familiar with Djangos language system. An OS-project I love and use ([Snipe-It](https://github.com/snipe/snipe-it)) uses crowdin. I setup a test [check it out here](https://crwd.in/inventree) which watches the django.po file in my [master](https://github.com/matmair/InvenTree/tree/master) and pushes all changed translation into [a translation branch](https://github.com/matmair/InvenTree/tree/l10n_master). Coupled with an action that regenerates the .po with each commit that could greatly automate the whole translation system and maybe enable more languages.
Crowdin is free with advanced features for [OS](https://crowdin.com/page/open-source-project-setup-request).

**Comment by matmair** [comment]
I found a flow diagram I made for another thing, shows how the process / dataflow could work.
![flow_diagramm_crowdin](https://user-images.githubusercontent.com/66015116/114789127-e51b1a00-9d82-11eb-9565-ae72f727d99e.png)

**Comment by SchrodingersGat** [comment]
Interesting, I had not heard of this before. I've been wondering for a while how to make the translation process easier for anyone to contribute.

Are there any examples of using crowdin with a django project in particular? I'm trying to find some django specific examples without much luck so far.

**Comment by matmair** [comment]
I do not know of any examples with Django but I configured the shown configuration to try it out in my fork.

**Comment by matmair** [comment]
@SchrodingersGat the crowdin project with CI enabled is hosted [here](https://crowdin.com/project/inventree1).
The [github action](.github/workflows/translations.yml) creates the current po files and pushes them to the [base branch](https://github.com/matmair/InvenTree/blob/l10_base/InvenTree/locale/en/LC_MESSAGES/django.po).
The crowdin translations are pushed every 10 minutes to [this branch](https://github.com/matmair/InvenTree/tree/l10n_trans/InvenTree/locale)

**Comment by SchrodingersGat** [comment]
@matmair I've had a look at the crowdin page, it looks **really** good - I'd like to make this the "official" way to do translations :)

How do we proceed from here?

FYI the github action link you posted doesn't work

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/pull/1498 adds some more locale entrypoints too

**Comment by SchrodingersGat** [comment]
And looks like crowdin supports translation status badges we can include in README.md

https://store.crowdin.com/products/bds

**Comment by matmair** [comment]
> 
> 
> @matmair I've had a look at the crowdin page, it looks **really** good - I'd like to make this the "official" way to do translations :)
> 
> How do we proceed from here?
> 
> FYI the github action link you posted doesn't work

@SchrodingersGat  Cool ;-) I restructured the action and everything else a few days ago to have a CI - example.

I deleted the example-project so the 'inventree' name and URL are free now. I have a full and working CI-example [here](https://crowdin.com/project/inventree1), if you provide me an e-mail (twitter DM for example) I can make you a manager to have a look around and see how I configured everything.

**Comment by matmair** [comment]
I just checked out bds, seems to be cool - I added an exampe [here](https://github.com/matmair/InvenTree/tree/sample/badges#readme)

**Comment by SchrodingersGat** [comment]
@matmair can you add me as a maintainer on your example project? My crowdin username is @SchrodingersGat 

Cheers

**Comment by matmair** [comment]
@SchrodingersGat I am trying for a few minutes now, seems like a free user (without open source project) can only have one manager.

**Comment by matmair** [comment]
Interesting that I could be made manager on your project.
I just looked how the 'official' project is set up now, will submit PR to crowdin-file to fix the multiple files showing up. It is all controlled by the file.

**Comment by matmair** [comment]
@SchrodingersGat I see you fixed it already 👍

**Comment by SchrodingersGat** [comment]
Trail and error :p

**Comment by matmair** [comment]
I think I can happily close this now ;-) thank you @SchrodingersGat for picking this up, will reduce the manual work for translating a lot.

**Comment by eeintech** [comment]
@matmair So if I understand correctly, every new PR will create a push to Crowdin to process the translation, then create new GitHub PR with the updated translation files? No need to run `inv translate` anymore?

**Comment by matmair** [comment]
@eeintech at the moment yes. If it works, I will create a PR to only run when pushed to master - to reduce unnecessary work for ppl. translating.
Short version: no more `inv translate` + semi-automated translations -> better quality.

**Comment by eeintech** [comment]
Cool, I'm trying out Crowdin's editor but I don't know how to push suggested translations... Do you need write access to the project? Where is the "send for review" button or similar?

**Comment by matmair** [comment]
There are 2 steps: 
- you translate the string and the indicator switches from red to green
- you approve or get aproved the string (with the checkmark-symbol)

crowdin checks every few minutes for new aproved strings or changes in the source-translation-files and pushes or pulls them.

**Comment by eeintech** [comment]
Oh I see the server is polling the suggestion is you go, I thought you would have to push yourself.

I started playing with it, it seems that I cannot approve but only suggest, so I don't have a checkmark symbol.
The only indicator is the item turns green:

![image](https://user-images.githubusercontent.com/4020546/115567427-3f3b4400-a289-11eb-81d0-6a73c22c3e0d.png)

**Comment by eeintech** [comment]
It's a neat system overall! Well done with that implementation!

My french (native language) is so rusty haha

**Comment by matmair** [comment]
@eeintech if you start translating to french I would suggest to translate the core-name like below. You can insert them on the right sight of the translator view. Those entries are used in the suggestions so you can make translating much faster.
![grafik](https://user-images.githubusercontent.com/66015116/115567714-d8834e00-a2bb-11eb-87ca-54e267b6ce6d.png)


| Englisch | Deutsch |
|-|-|
| allocation | <del>Zuweisung</del> |
|  | Zuordnung |
| Barcode | Barcode |
|  | <del>Strichcode</del> |
| batch code | Losnummer |
|  | <del>Chargennummer</del> |
| BOM | <del>BOM</del> |
|  | Stückliste |
| BOM Item | <del>BOM-Eintrag</del> |
|  | Stücklistenposition |
|  | <del>BOM-Position</del> |
| build order | Bauauftrag |
|  | <del>Bau</del> |
| build output | <del>Bau</del> |
|  | Bau-Ausgabe |
|  | <del>Endprodukt</del> |
| IPN | IPN |
| location | <del>Standort</del> |
|  | Lagerort |
| overage | Überschuss |
| parameter | Parameter |
| part | Teil |
| purchase order | Bestellung |
|  | <del>EK-Bestellung</del> |
| report | <del>Report</del> |
|  | Bericht |
| revision | Revision |
| sales order | <del>Bestellung</del> |
|  | Auftrag |
|  | <del>VK-Auftrag</del> |
| serial number | Seriennummer |
| stock | <del>Lagerbestand</del> |
|  | Bestand |
|  | <del>Lager</del> |
| stock expiry  | Lager Ablaufdatum |
| stock item | <del>Lagerobjekt</del> |
|  | Bestandsobjekte |
| stocktake | Inventur |
|  | <del>Bestandsaufnahme</del> |
|  | <del>Bestandsänderung</del> |
| supplier | Zulieferer |

**Comment by matmair** [comment]
> 
> 
> Oh I see the server is polling the suggestion as you go, I thought you would have to push yourself.
> 
> I started playing with it, it seems that I cannot approve but only suggest, so I don't have a checkmark symbol.
> The only indicator is the item turns green:
> 
> ![image](https://user-images.githubusercontent.com/4020546/115567427-3f3b4400-a289-11eb-81d0-6a73c22c3e0d.png)

I just checked; you are right. I gave you permissions to approve French.



> 
> 
> It is a neat system overall! Well done with that implementation!


Another project in which I submit a lot of translations uses this system, it opens up translating to non-programmers as it lowers the bar.

> 
> My french (native language) is so rusty haha

I know that feeling. Sometimes I wonder if my German or English is worse. But to be fair there is quite a dialect in my area so most Germans do not understand me either.

**Comment by eeintech** [comment]
@matmair Ummm I see, it is less intuitive to start there because the editor is pulling random (?) phrases in the left panel, it would be nice if it started with those "core" translation at the top of the list. Any way those words can be marked as "core" and Crowdin picked them up first?

**Comment by eeintech** [comment]
This is seriously addictive and takes me at least 2 min per word to be certain that's the way it would be used in French :sweat_smile: 

Question: is it case sensitive?
For instance if I translate "Part" with "composant", will it automatically make the first letter uppercase?

**Comment by matmair** [comment]
> 
> 
> > if you start translating to french I would suggest to translate the core-name like below. You can insert them on the right sight of the translator view. Those entries are used in the suggestions so you can make translating much faster.
> 
> @matmair Ummm I see, it is less intuitive to start there because the editor is pulling random (?) phrases in the left panel, it would be nice if it started with those "core" translation at the top of the list. Any way those words can be marked as "core" and Crowdin picked them up first?

Well the phrases it shows you are somewhat sorted - it shows you stuff it can use for suggestions later. I do not know how one could highlight translations but I will look into it.



> 
> Question: is it case sensitive?
> For instance if I translate "Part" with "composant", will it automatically make the first letter uppercase?
> 
> EDIT: I am actually looking for the correct translation of "Part" because there is no generic word in french that I know of...

It uses the strings the way you input them. The QA looks out if the first and last letter match the source string.

Finding good translations is hard.

**Comment by eeintech** [comment]
Understood.

Other few questions:
- what does Crowdin do with "suggested" translation? Where can I review and approve of all it at once?
- what does it do with "approved" translation (push to InvenTree branch `l10n`)?

**Comment by matmair** [comment]
1. On the project-site you can select a language and then 'Proofread' to approve suggested strings
![grafik](https://user-images.githubusercontent.com/66015116/115574540-02d80a00-a2c2-11eb-9fe2-5b48c502d09c.png)
2. Approved translations are pushed to l10n, from where they then will need to be manually pulled. That can be done for all languages in one operation.
