### ISSUE TITLE
use instance name in title and views?

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1463]
@SchrodingersGat this is just a suggestion - close this if you disagree, no hard feelings.

There are a few views and (meta) titles where 'InvenTree' is used where it could make sense to use the instance name. I currently have a few instances deployed in places where English is not widely used or known. A few users, especially in manufacturing, are confused by the 'InvenTree' as they are used to only use the internal system names (for exampel 'TeilDB').

I would make a PR replacing 'InvenTree' with the instance name in all end-user facing parts. About, version and setting-views should keep 'InvenTree' in my opinion as to show what system is used.

**Comment by SchrodingersGat** [comment]
I'm not opposed to this, feel free to submit a PR showing how you would like to see it implemented

**Comment by matmair** [comment]
@SchrodingersGat I threw together how I would do it.
It am missing:
- unittests
- UI-tests
- documentation

the feature branch is in [my github](https://github.com/matmair/InvenTree/tree/instance-name-in-title)
