### ISSUE TITLE
See or select the default location when receiving stock

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#1467]
When receiving parts on a PO, unless you happen to have the correct location of the part memorised, you have no idea what the correct location of received part is.

There are a couple of ways that this could be solved satisfactorily:
1) When receiving a single line item, automatically select the default location as the location destination.  I looked at the code and as far as I can tell, this is not going to be easy to accomplish as the table of line items to receive is filtered separately from the selection of locations to put the line items; so short of creating a purpose specific modal this probably not a great way forward.
2) Add the default location as a column to the table of parts to receive.  This should be fairly straight forward as the table seems to be populated the same way as all other tables.  

Rejected ideas:
1) Receive the items to "Desk" or something and then transfer them to the correct location.  This doesn't work because it is more unnecessary work, and more crucially, the transfer dialog has the same problem, it also doesn't show the default location and additionally requires a note to be added.

I think 2 is probably the expedient way forward, but would the project accept a change like that?

**Comment by SchrodingersGat** [comment]
Seems like this is a similar issue to https://github.com/inventree/InvenTree/issues/551

I think that 2) is going to be the best approach here. Each "location" can be filled with the "default location" for that part (if it exists)

Going a little bit further, I think that each `PurchaseOrderLIneItem` object should have a `destination` field. This can be set even before the items are received. For example the person making the order could specify where the items should be received into, and then the receiving person can follow this request.

Then, when creating the "receive items" dialog, (with the new "location" column as described in option 2) the "location" column has already been determined. It can also then be edited by the receiver if required.

Does this all make sense?

**Comment by nwns** [comment]
That makes sense.

For the next sprint (on Thursday), I will start with 2), and if time remains expand upon it further as outlined.
