### ISSUE TITLE
Migrating Data on docker

### ISSUE THREAD

**Issue by irameez** [inventree/InvenTree#1473]
Hello,
I am trying to import data in InvenTree using docker. But it gives me the error:
`docker-compose run inventree invoke import-records -f data_170420.json`
`Creating inventree_inventree_run ... done`
`Error: File '/home/inventree/src/data_170420.json' does not exist`
`ERROR: 1`

Where exactly do  I need to put my json file, I have tried putting it in the place it where creates the json file when using the export command and also in the local system path where InvenTree data is stored, but it always give me the same error.
Can someone please help me with this issue.

Thanks
Rameez.

PS: Using `invoke backup` also doesn't, it gives me this error: https://pastebin.com/Tb57tvnt

**Comment by rcludwick** [comment]
So if you look at the static data mount point it should look like something like this right?

```
    volumes:
      - data:/home/inventree/data
```

So that maps the local directory data to /home/inventree/data inside the container.  So if you copy the file to ```data/data_170420.json```, it should be visible inside the container with the following command:

```docker-compose run inventree invoke import-records -f /home/inventree/data/data_170420.json```

**Comment by rcludwick** [comment]
Oh also make sure the directory and file is 777 permissions so it's readable by inventree.

```chmod -R 777 data```

**Comment by rcludwick** [comment]
So this is his other error, and it looks like pg_dump is not in the docker container, or it has the wrong pathing.


```
Traceback (most recent call last):
  File "/home/inventree/src/InvenTree/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/dbbackup/utils.py", line 118, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbbackup/management/commands/dbbackup.py", line 61, in handle
    self._save_new_backup(database)
  File "/usr/local/lib/python3.9/site-packages/dbbackup/management/commands/dbbackup.py", line 74, in _save_new_backup
    outputfile = self.connector.create_dump()
  File "/usr/local/lib/python3.9/site-packages/dbbackup/db/base.py", line 78, in create_dump
    dump = self._create_dump()
  File "/usr/local/lib/python3.9/site-packages/dbbackup/db/postgresql.py", line 38, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
  File "/usr/local/lib/python3.9/site-packages/dbbackup/db/postgresql.py", line 21, in run_command
    return super(PgDumpConnector, self).run_command(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbbackup/db/base.py", line 156, in run_command
    raise exceptions.CommandConnectorError(
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump  --host=db --port=5432 --username=pguser --no-password --clean inventree [Errno 2] No such file or directory: 'pg_dump'
```

**Comment by SchrodingersGat** [comment]
Looks like I need to include `pg_dump` binary in the docker container!

**Comment by SchrodingersGat** [comment]
@irameez I have updated the docker image such that you should no longer see the `pg_dump` related errors.

If you can update your docker image, and try again?

**Comment by irameez** [comment]
> Oh also make sure the directory and file is 777 permissions so it's readable by inventree.
> 
> `chmod -R 777 data`

That fixed the issue but now I am getting this error:
[import_error.txt](https://github.com/inventree/InvenTree/files/6334995/import_error.txt)

**Comment by irameez** [comment]
> @irameez I have updated the docker image such that you should no longer see the `pg_dump` related errors.
> 
> If you can update your docker image, and try again?

thanks backup is working now.

**Comment by SchrodingersGat** [comment]
Fantastic! Can I close out this issue?

**Comment by irameez** [comment]
> 
> 
> Fantastic! Can I close out this issue?

actually I am still having a problem importing the data file. I am getting this error now
[import_error.txt](https://github.com/inventree/InvenTree/files/6335310/import_error.txt)

**Comment by SchrodingersGat** [comment]
That error message is saying that there are duplicate settings values with the key `PART_ASSEMBLY`. 

You already have settings configured in the database, and are trying to re-import them - but the import process is failing because the key already exists.

If you prune the `PART_ASSEMBLY` entry out of the data you are importing, it will progress (but mostly likely hit the next issue).

Importing data into a database from a file is a pretty tricky problem!

**Comment by irameez** [comment]
> 
> 
> That error message is saying that there are duplicate settings values with the key `PART_ASSEMBLY`.
> 
> You already have settings configured in the database, and are trying to re-import them - but the import process is failing because the key already exists.
> 
> If you prune the `PART_ASSEMBLY` entry out of the data you are importing, it will progress (but mostly likely hit the next issue).
> 
> Importing data into a database from a file is a pretty tricky problem!

I see, but what I don't understand is that I am trying to import data on a fresh install of InvenTree, why is it showing this entry where the database is fresh and empty

**Comment by rcludwick** [comment]
@SchrodingersGat If you use pg_dump to dump the db, can he possibly use pg_restore to restore it?

**Comment by irameez** [comment]
> 
> 
> That's odd, then. Data migrations are performed as part of the testing framework, so it is strange that it's erroring out for you here.
> 
>     1. How far through the docker install instructions were you when you tried to import the data?
> 
>     2. I'm assuming that you are importing data from a previous InvenTree setup?

I have tried importing data at different steps; after data migration, before and after creating super user.
Actually I have inventree running on mysql/ubuntu without docker, I installed docker and since it uses PostgreSQL I was trying to import data.

**Comment by irameez** [comment]
Just wondering, so there is no fool proof way of transfering data from MySQL to PostgreSQL

**Comment by SchrodingersGat** [comment]
@irameez the data import/export process should not care what database you are using - the file format is JSON and InvenTree should take care of properly importing and exporting the data.

I have spent some now looking into the data import/export process. There were definitely some (very subtle) issues with it. 

PR is here - https://github.com/inventree/InvenTree/pull/1517

Once that PR is merged (and the docker image is updated) I would suggest you try again. Hopefully the issues have resolved, if not then we can dive in and work out exactly what is going wrong - I would like to solve this issue too as it most likely will impact anyone wanting to use the import feature...

**Comment by irameez** [comment]
> 
> 
> @irameez the data import/export process should not care what database you are using - the file format is JSON and InvenTree should take care of properly importing and exporting the data.
> 
> I have spent some now looking into the data import/export process. There were definitely some (very subtle) issues with it.
> 
> PR is here - #1517
> 
> Once that PR is merged (and the docker image is updated) I would suggest you try again. Hopefully the issues have resolved, if not then we can dive in and work out exactly what is going wrong - I would like to solve this issue too as it most likely will impact anyone wanting to use the import feature...

Thank you, on latest version import is working fine now. You can close this issue.
