### ISSUE TITLE
stock level graph

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1484]
> @SchrodingersGat is there a reason why there are no graphs in InvenTree? 

Yes - to date there has been no historical data to "graph". However I would love to support charts.

If you are going to add graph support here (and chart.js looks great) then I would like to implement a 'stock level history' graph - and I'm sure there are other areas it could be used too!

Excited to see what you come up with here :)

_Originally posted by @SchrodingersGat in https://github.com/inventree/InvenTree/issues/1482#issuecomment-821979111_

**Comment by matmair** [comment]
@SchrodingersGat I would love to implement a stock level history graph.
One problem I see is that one can have multiple stock items of the same part in the same location-> should those be summed up or should we keep it per stock item?

**Comment by SchrodingersGat** [comment]
I think there would be a case for a "two-level" stock history:

### Stock Item History

Currently we already have stock item history (although this is in *serious* need of rework). So we could have a graph of "stock level" for a single StockItem

### Part History

Individual stock items come and go, and may well be entirely deleted from the system. So I think that each time a stock item quantity is adjusted, the parent "Part" object also should create a new `PartStockHistory` database entry. That way, independent of what happens to the actual stock items, we have a historical stock level record for the `Part` itself.

**Comment by matmair** [comment]
@SchrodingersGat I just sketched the *Stock Item History Graph* out and realised something: the way Stock Items work they will (al)most never get restocked. That is because every time you buy new stock a new stock item will be created.
I think it does not make sense to implement it. I already have a rough outline in my fork because I realised to late so if you think it still makes sense, I can finish it.

**Comment by SchrodingersGat** [comment]
I think you are probably right. The effort required to track and graph stock level for each individual stock *item* is probably not worth it, given how ephemeral the individual stock items can be.

Instead, I think that "stock level history" should be calculated against each *Part*.

Each time a stock item is updated (here "updated" means "created", "edited", "deleted"), we should run `part.calculate_stock_level()` which enters a new row into the "stock_history" table for that part.

Some considerations:

- If the stock level remains unchanged then no need to add a new row
- Bulk stock actions (e.g. competing a build and updating 100x stock items) will make a *lot* of these calls! We can offload these to the background worker
- Will need to add "signals" to the StockItem model to handle the cases where stock items are created / deleted

**Comment by SchrodingersGat** [comment]
Actually @matmair the individual stock item history already is present, look at the `StockItemTracking` model. This stores a "quantity" for each time the StockItem is updated.

**Comment by matmair** [comment]
@SchrodingersGat I saw that, my question was more of 'do we need it' than an 'could we do it'.
I will implement the suggested model and try hooking a signal to `addTransactionNote`.

**Comment by matmair** [comment]
Will be put on hold till #1303 is implemented https://github.com/inventree/InvenTree/pull/1520#issuecomment-828000341

**Comment by matmair** [comment]
@SchrodingersGat Now that #1548 is resolved, can I go ahead on this and #1482?

**Comment by SchrodingersGat** [comment]
Yep, happy for you to proceed

**Comment by matmair** [comment]
@SchrodingersGat should I add a whole new model for tracking the stock levels for a part over time (persisting the deletion of stock items) or do you think that would be overkill (I am not sure if that is really needed)?

**Comment by SchrodingersGat** [comment]
I think that tracking the on-hand quantity of a particular part over time would be pretty useful. More useful even than the current "per item" history.

As each StockItem can be deleted from the database once consumed, then its quantity history also goes with it (which is fine).

A quantity history for the Part itself would be more useful for many users I would imagine. Essentially each time a stock operation is performed, then the parent Part "in stock" quantity would need to be calculated, and a new row added to some `PartQuantityHistory` table...

What do you think about this potential approach?

**Comment by matmair** [comment]
Sounds good. I will make a PR for it.
I think using hooks and delayed actions is unnecessary for this action as it shouldn't be too expensive but will measure anyway.

**Comment by matmair** [comment]
I do not think this will go anywhere without central part history tracking. Will close this for now as I do not see a real need.

**Comment by SchrodingersGat** [comment]
Agreed. There are many actual function changes that take priority over a change like this.

**Comment by matmair** [comment]
> Agreed. There are many actual function changes that take priority over a change like this.

I thought maybe it could be a 'help_wanted' thing but it would probably be better if a core contributor / somebody with a deep understanding of InvenTrees innerworkings does this. Could be pretty bad for performance / maintainance.
