### ISSUE TITLE
performance optimisation

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1485]
## How I noticed
I am currently transitioning from testing InvenTree in small academic / teaching environments (max. 10 concurrent users) to a larger pool before deployment to est. 100 concurrent users.

With that came a switch to quite powerful production webservers and bare-metal configs instead of docker. Out of curiosity I measured the performance of the new docker-image and the performance is more than 2x slower than an apache2 + mod_wsgi / postgres bare-metal config on the same server.

I found that no kind of expiry or cache control is set for the static content in docker. Also, the reloading of all the 'dynamic' JS-files seems to cause quite a lot of blocking-time.

# Ideas - RFC
@SchrodingersGat @eeintech
My understanding of the layout of InvenTree is limited so I would ask you to weigh in on these ideas to make InvenTree quicker:
- [x] enabling [manifest storage](https://docs.djangoproject.com/en/3.2/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage) and enable long-time caching in the docker config (I already do that on my bear-metal config and it makes everything considerable faster)
- [x] only load needed JS-files per view (not really needed with caching enabled)
- [x] rendering the 'dynamic' JS stuff once while updating the app with the translations backed and adding it to the static content

**Comment by SchrodingersGat** [comment]
@matmair thanks for starting this conversation! Performance has been a core design criterion for me, so I'm very happy to support improvements in this area.

> only load needed JS-files per view (not really needed with caching enabled)

This is a good idea, and a pretty low barrier to implementation. Currently all the JS files are loaded via the "base.html" template as it's simpler 

> enabling manifest storage and enable long-time caching in the docker config (I already do that on my bear-metal config and it makes everything considerable faster)

I have not looked into this before, but it looks like a great idea. Approximately how much of a speed improvement would you typically expect?

> rendering the 'dynamic' JS stuff once while updating the app with the translations backed and adding it to the static content

This I think is a key improvement. Currently the server has to render each javascript file each time it is requested! So somehow we'll need to split these out into separate locale files, something like:

- part.en.js
- part.de.js

and then serve these files statically (which means Gunicorn does not even need to touch them).

The "conversion" process could be handled in the current `invoke static` script - translate the files before copying them over to the static directory.

----------------------

In general terms, where are you seeing the main performance hits currently? And what are the major points of difference between a docker setup and a bare-metal setup?

**Comment by matmair** [comment]
@SchrodingersGat regarding expiry: [nginx-headers](https://serverfault.com/a/334871) that would reduce the amount of loaded data by half (on the /part/ -site) on each reload, that is the lowest hanging fruit.

I will look at the rendering of the JS-files this week, I find that the most interesting. Also, it could make - with a fast static file-server - quite a lot of difference. The /dynamic/ content is the bigger part of the 'blocking' time on site-load.
![these are the loading sizes and times with basic caching enabled](https://user-images.githubusercontent.com/66015116/115269952-1e190d00-a13c-11eb-9526-a330e1d6135d.png)

The main difference between docker and bare-metal are the response times and more specialised builds of the applications. Our webservers for example are optimised builds with only the functionality we need compiled. There are memory-based proxies between the static file-servers and the network, also there is load-balancing between multiple instances for the dynamic content and dedicated database-servers. Bare-metal is generally more hardened and striped down (if done right).

**Comment by matmair** [comment]
The first suggestion -> only loading needed JS-files is unnecessary with caching enabled / the new translation mechanism.
I will work on manifest storage this evening, than the new stuff should work.

**Comment by matmair** [comment]
@SchrodingersGat next ideas for performance:

- [ ] reduce the amount of small API-calls (esp. on index)
- [ ] optimise SQL-lookups
- [ ] optimise form-rendering - I do not know right now what is causing it but the pop-up forms take a lot of time to load

**Comment by SchrodingersGat** [comment]
Regarding optimization of SQL queries and form rendering - InvenTree currently supports [django-debug-toolbar](https://django-debug-toolbar.readthedocs.io/en/latest/) which you can activate via the configuration options. This can show you where the inefficiencies are.

Note that the toolbar itself slows down rendering considerably!

I have used this in the past to narrow down some SQL issues, and take certain query calls from ~30s down to < 1s
