### ISSUE TITLE
Part - get_price

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1512]
@SchrodingersGat  get_price currently just returns None when called with a quantity lower than the lowest pricebreak.
2 questions:
- intentional?
- should the automatic calculation when a part is added warn if there if that results in no price added?

**Comment by SchrodingersGat** [comment]
Not "intentional", perhaps it should just return the lowest quantity price break in this situation?

**Comment by matmair** [comment]
Changing the default behaviour creates a lot of problems, I will not poke this hornets-nest further.

**Comment by eeintech** [comment]
@matmair What kind of problems? Would be nice to have it return the lowest quantity unit price and calculate for the requested quantity.

**Comment by eeintech** [comment]
#1178 was related. I think we should find a solution to this problem

**Comment by matmair** [comment]
@eeintech stuff broke in a lot of places and I could not find out why everywhere.
I think it makes sense that you can set a minimum order quantity just by starting the price-breaks at the minimum quantity. But correct me if you think otherwise.

**Comment by eeintech** [comment]
@matmair Does #1535 implementation works for you?

**Comment by matmair** [comment]
In the core functions (purchase-orders, pricing information) it does but I get a wired error when deleting stock - which hinders me from getting rid of stock. Will investigate further and submit my findings.

**Comment by eeintech** [comment]
Weird indeed, I just checked and I don't have this kind of error. Have you tried the same thing with `master` on your setup?

**Comment by matmair** [comment]
I have reset the deployment in which I got the error, seems to run fine now.
