### ISSUE TITLE
Support more currency

### ISSUE THREAD

**Issue by wengtad** [inventree/InvenTree#1515]
May I know how to add more currency in the list? Are there any setting to do it?
![image](https://user-images.githubusercontent.com/12437747/115865051-5dac6580-a46a-11eb-9d23-d7aa6f266d5e.png)

**Comment by SchrodingersGat** [comment]
Edit the `config.yaml` configuration file :)

**Comment by wengtad** [comment]
Ah okay, I found it, thanks.
