### ISSUE TITLE
More syntax for adding serial numbers

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1519]
I will add the following two options to serial number-recognition:
\<start>+ :add expected number of serials after \<start>
\<start>+\<length> :add \<length> numbers starting at \<start>

I am thinking of also including a character for filling a pattern with all missing serials (to get the expected number of serial numbers).
What do you think @SchrodingersGat ?

**Comment by SchrodingersGat** [comment]
I like it! Both suggestions I would support.

**Comment by eeintech** [comment]
Sweet! Nice job!
