### ISSUE TITLE
[BUG] no attribute MPN 

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1524]
# System

Version: 0.2.2 pre
Commit-Date: 2021-04-27
Commit-Hash: 4d2e23f
Plattform: Win H2 - WSL2 Debian Buster
Deployment Method: runserver

# Steps to reproduce
- open supplier part
- add price break (button)
- enter data (does not matter, in my case: number 1, price 1)
-> results in 'Internal Server Error' Error Code 500

# Message
AttributeError at /price-break/new/
'SupplierPart' object has no attribute 'MPN'

**Comment by matmair** [comment]
@SchrodingersGat @eeintech
to be fair I already made a patch, I am just not sure how I am the first do discover that. The last code-change on this line is 6 months old. Is it my system/setup maybe?

**Comment by eeintech** [comment]
@matmair This is happening because of #1417, sorry about that. It should be `supplier_part.manufacturer_part.MPN` or similar.

**Comment by eeintech** [comment]
Oh I didn't see #1525 yes it is correct! Good catch!
