### ISSUE TITLE
Embed information on 3rd-party libraries

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1533]
I would like to create a place (I suggest the "about" modal) where all the great used libraries get mentioned and their licenses linked. The legal depts. in bigger organisations like to see something like that to be sure there is nothing bad going on licensing wise ([like this](https://www.theregister.com/2021/03/25/ruby_rails_code/)).

@SchrodingersGat 
Thoughts / did I oversee that there already is something like that? I made a tech-demo (not polished) how it could look in [my public repo](https://github.com/matmair/InvenTree/tree/3rdparty-info).

**Comment by SchrodingersGat** [comment]
I like this idea. I would suggest that we add it to the inventree documentation (https://inventree.readthedocs.io) and then add:

- A link from the "about" modal in InvenTree
- A link from README.md

**Comment by matmair** [comment]
👍That is a way better way than my tech-demo. Will submit a PR today.

**Comment by SchrodingersGat** [comment]
https://inventree.readthedocs.io/en/latest/credits/
