### ISSUE TITLE
BOM Template

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#1540]
I am looking for a BOM Template.  Does one exist?

**Comment by eeintech** [comment]
@lookme2 You don't really need a BOM template, you'll need to match your headers with InvenTree's fields.
Take a look at this part of the doc: https://inventree.readthedocs.io/en/latest/build/bom/#select-fields

**Comment by lookme2** [comment]
@eeintech I don't think I made myself clear.  I am look into how to print a BOM report.  Is this still the doc that I should be looking at?

**Comment by SchrodingersGat** [comment]
@lookme2 while the BOM report generation functionality exists, there are currently no base templates which have been written.

The templates which do exist are here: https://github.com/inventree/InvenTree/tree/master/InvenTree/report/templates/report if you want to use these as a starting point.

**Comment by lookme2** [comment]
@SchrodingersGat thanks.  I'll mess around with those today.
