### ISSUE TITLE
Stock with Status of 120

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#1549]
I have a part in my inventory with a status of 120.  What does that mean?   I cant seem to count that stock.

**Comment by SchrodingersGat** [comment]
The code `120` used to mean "ASSIGNED_TO_BUILD" however InvenTree now manages order assignments in a better way.

For some reason the InvenTree updates have not fixed this outdated code automatically...

You should manually edit this stock item to "OK" (or whatever other status you need) using the admin interface.

**Comment by lookme2** [comment]
@SchrodingersGat I have over 1100 parts in my DB.  Is there a way to batch fix this?  Looking from the admin page it looks like I have hundreds of them with a status of 120

**Comment by eeintech** [comment]
@lookme2 After #1559 is merged, here's how to mass update the stock status:
1. Go to "Admin" section, click on "Stock items"
2. Click on "Export" button on top right, save it as `.xls`
3. In the XLS file, change the rows in the `status` column from `120` to `10`. Save it
4. Go back to the "Admin" section, under "Stock items", click on "Import" button on top right
5. Select the XLS file you just edited, select the formal to `.xls`, click on "Submit"
6. Verify the `status` and `status_label` (if it was not set to "OK") have been updated
7. Complete import clicking on "Confirm import" button

Let me know if you have any issue with those steps :smiley:

**Comment by lookme2** [comment]
@SchrodingersGat I performed the step suggested by @eeintech and that worked great!  Thanks!

**Comment by eeintech** [comment]
Sweet! Enjoy!
