### ISSUE TITLE
Version 0.2.1 in Firefox looks like garbage

### ISSUE THREAD

**Issue by Acvarium** [inventree/InvenTree#1562]
Updated server to 0.2.1. Now in Firefox it looks messed up and unusable, in some cases

![screenshot-2021-05-08_23:15:17](https://user-images.githubusercontent.com/463177/117552362-8c723080-b053-11eb-8171-a9509d5029c1.png)

![screenshot-2021-05-08_23:18:34](https://user-images.githubusercontent.com/463177/117552414-c6dbcd80-b053-11eb-94a1-cce63707d350.png)

**Comment by matmair** [comment]
@Acvarium sorry to read that; for triage some information might help:
-	your browser version + special addons you have (if you want to share that)
-	underlying OS
-	commit-hash (can be found in 'About InvenTree' modal in the top right corner)

Please force-reload the site again with Strg+f5 (on win) and if the error persists try in a private session with all addons turned off. Might be an old stylesheet cached by the browser - is a common problem.

**Comment by SchrodingersGat** [comment]
It does look like a stylesheet caching issue. Try a hard refresh as suggested

**Comment by Acvarium** [comment]
It helped. Thank you very much. Love this tool. It has improved the quality of my life.

**Comment by SchrodingersGat** [comment]
High praise @Acvarium glad you find it useful :)
