### ISSUE TITLE
Use stock item "purchase_price" in Part Pricing calculation

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1577]
The `PartPricing` view does not seem to take into account the price of stock items (stored in the `purchase_price` field) but only supplier price breaks.

https://github.com/inventree/InvenTree/blob/07c7af1f2e1bb577aa92709d0055d70a9d02ffed/InvenTree/part/views.py#L1950

My proposal is to have a separate calculation for supplier pricing (from supplier price break) and purchased pricing (from stock items), to not overwrite the pricing of one or the other in the BOM calculation for example.

Any thoughts?

**Comment by matmair** [comment]
@eeintech sounds great. And that is basically what I implemented in #1482. It shows all the prices of all stock items and quantities. Just in a chart.
I am considering also adding a break-even chart with its own permission.

**Comment by eeintech** [comment]
@matmair Sorry I guess I missed the intention of #1482 which is more about price history tracking?

I'm looking into straight forward way to see purchase price directly into a BOM calculation, and maybe also indicated for every single item in a BOM. Will that #1482 cover it?

**Comment by matmair** [comment]
@eeintech I made a few screenshots for reference
![grafik](https://user-images.githubusercontent.com/66015116/118177545-21e63980-b433-11eb-9185-3374eee0c7fc.png)
![grafik](https://user-images.githubusercontent.com/66015116/118177633-3aeeea80-b433-11eb-88ed-e8ff6b89e491.png)

The modal shows the total price range for the BOM calculated over all items and quantities, a column in the BOM table might indeed be more fitting.

**Comment by eeintech** [comment]
Wow yeah that's way more fancy than what we need :smile: 

I just pushed those missing BOM columns in #1581

**Comment by matmair** [comment]
I am not really happy with the Part Pricing view, it is quite inefficient (space wise) in my mind.

**Comment by eeintech** [comment]
How do you imagine it? If it were to be improved?

**Comment by matmair** [comment]
I am currently experimenting a bit internally what people think and suggest.
Merging the alert on top and the first table.
I am A/B testing just that and a matrix instead of a lot of headings.

**Comment by matmair** [comment]
@eeintech have you seen the new pricing page? Anything I should add? Will work on this next, including #1592 and maybe #1539

**Comment by eeintech** [comment]
@matmair I'm sorry I missed it. Is it in master already? I'll check it out soon!

**Comment by eeintech** [comment]
I was trying to check out the new pricing page and ran into #1641

**Comment by eeintech** [comment]
@matmair I'm trying to find out what is new... That's my part pricing view on master:

![image](https://user-images.githubusercontent.com/4020546/121051512-858c2a00-c787-11eb-8112-54092a9dfad7.png)

I don't see anything about the purchased price (which is different than the price break).

Also, where do one see the stock pricing graph?

**Comment by matmair** [comment]
@eeintech the new stuff is all in the pricing view (/part/<pk>/order-prices/), not the modal. It was made this way to keep the modal clean and small.

**Comment by eeintech** [comment]
@matmair Thanks, I missed that part :grimacing: 

I don't know if this is the right place for my review now that it is merged but here it is:
1. I found it confusing there is no "Calculate" button... After changing the quantity, I was quite confused how to update the "Pricing Ranges" information. Now I understand I just need to hit Enter but still think it would be more obvious to have the "Calculate" button under the quantity. What do you think?
2. The "Info" token phrasing is also quite confusing:

![image](https://user-images.githubusercontent.com/4020546/121086222-e1b77400-c7b0-11eb-9046-8cb633868ae5.png)

Also does it really help understanding the graph? Right now I don't think so so either I would just remove it or make it a nicer explanation how to decipher the pricing graph.

3. If I understand correctly the graph:
- "Single Price" = Stock Item Single Price
- "Part Single Price" = Supplier Price Break Single Price
Is that correct? The graph is a little confusing to be honest :sweat_smile: 

![image](https://user-images.githubusercontent.com/4020546/121086447-280cd300-c7b1-11eb-843a-3359482adeb3.png)

Also this graph is labelled as "Stock Pricing" so shouldn't it only refer to stock prices, not supplier parts price breaks?

**Comment by eeintech** [comment]
One more thing, can't a graph be generated when only one stock/purchase price is found? I only get this message:

![image](https://user-images.githubusercontent.com/4020546/121087559-a027c880-c7b2-11eb-9686-19a484a64b33.png)

**Comment by matmair** [comment]
> 
> 
> @matmair Thanks, I missed that part 😬
> 
> I don't know if this is the right place for my review now that it is merged but here it is:

Feedback is always welcome!


>     1. I found it confusing there is no "Calculate" button... After changing the quantity, I was quite confused how to update the "Pricing Ranges" information. Now I understand I just need to hit Enter but still think it would be more obvious to have the "Calculate" button under the quantity. What do you think?
> 
I found it cleaner that way but that is easy to change.
>
>     2. The "Info" token phrasing is also quite confusing:
> 
> 
> ![image](https://user-images.githubusercontent.com/4020546/121086222-e1b77400-c7b0-11eb-9046-8cb633868ae5.png)
> 
> Also does it really help understanding the graph? Right now I don't think so so either I would just remove it or make it a nicer explanation how to decipher the pricing graph.
> 
Do you have an idea for a better text?
>
>     1. If I understand correctly the graph:
> 
> 
>     * "Single Price" = Stock Item Single Price
> 
>     * "Part Single Price" = Supplier Price Break Single Price
>       Is that correct? The graph is a little confusing to be honest 😅
> 
That is the way I meant it.
> 
> ![image](https://user-images.githubusercontent.com/4020546/121086447-280cd300-c7b1-11eb-843a-3359482adeb3.png)
> 
> Also this graph is labelled as "Stock Pricing" so shouldn't it only refer to stock prices, not supplier parts price breaks?
>
Stock prices alone are not very informative. the quantity serves to help the user to get a feel how much (in total) they paid for the stock while the difference helps to show how much prices differ from the calling price for that supplier price - some manufacturers differ a lot from others - which should be considered if you are not sure if one supplier is enough.

We could turn a lot of those values off by default - the user just needs to click on the label and the graphs appears.

**Comment by matmair** [comment]
@eeintech is this fulfilled by #1712 or do you imagine a different implementation?

**Comment by eeintech** [comment]
I have yet to check it out (so busy those days...) but from the screenshot I saw it looks like it!

Thanks @matmair
