### ISSUE TITLE
Search is case sensitive for Cyrillic letters

### ISSUE THREAD

**Issue by Acvarium** [inventree/InvenTree#1585]
Version 0.2.1
I just noticed, that I can't find some items using search bar. And, as my testing show, if I mane item with uppercase letter in Cyrillic, I have to search the same way.
That is not the case with Latin letters 

https://youtu.be/XJRTfYEDWDU

**Comment by SchrodingersGat** [comment]
What database backend (e.g. mysql / postgresql / etc) are you using?

**Comment by Acvarium** [comment]
I don't remember. How to check this?

**Comment by Acvarium** [comment]
I think it is sqlite3

**Comment by SchrodingersGat** [comment]
If you're using sqlite, this is a known limitation (although I only just found out about it).

https://docs.djangoproject.com/en/dev/ref/databases/#substring-matching-and-case-sensitivity

You might need to migrate to either MySQL or postgresql database

**Comment by SchrodingersGat** [comment]
@Acvarium I've added a note about this to the docs.
