### ISSUE TITLE
Purchase price not available when adding stock from a part page

### ISSUE THREAD

**Issue by G-Pereira** [inventree/InvenTree#1589]
![Screenshot from 2021-05-15 14-35-48](https://user-images.githubusercontent.com/15521303/118363179-1148d700-b58b-11eb-85d5-76e675a285ef.png)
![Screenshot from 2021-05-15 14-36-14](https://user-images.githubusercontent.com/15521303/118363180-127a0400-b58b-11eb-9589-5cbbdd390a32.png)

**Comment by matmair** [comment]
@G-Pereira is 'Purchasable' enabled for that part? Part pricing only shows up when that is enabled.

**Comment by G-Pereira** [comment]
No, i am most interested in knowing how much the part (assembly) costs to know what is my profit margin. How can I do that?

**Comment by G-Pereira** [comment]
Keep in mind that the original topic of this issue is the price of a stock item, not a part. Please answer my question anyway

**Comment by G-Pereira** [comment]
That makes sense, my bad. I think it shouldn't show in the other case as well then.
There's another issue which the subject as moved to this question so i will close this one.
