### ISSUE TITLE
Purchase price not being recorded

### ISSUE THREAD

**Issue by G-Pereira** [inventree/InvenTree#1590]
When adding stock manually by "Creating a Stock Item" (not from a purchase order) the purchase price it is not being recorded. When checking Django's admin panel the field is blank.

**Comment by G-Pereira** [comment]
Now that I've added the price manually in the Admin panel it still isn't able to calculate prices:
![image](https://user-images.githubusercontent.com/15521303/118380921-b42a4100-b5dd-11eb-9e67-a2a9c29019f5.png)
![image](https://user-images.githubusercontent.com/15521303/118380932-c906d480-b5dd-11eb-8510-14d858dec438.png)

**Comment by matmair** [comment]
@G-Pereira the pricing is calculated based on the price-breaks in the part and the BOMs parts. Showing price-history from stock is currently not released and part of #1482.

**Comment by G-Pereira** [comment]
Ok, but this is still a bug because the price field is not submitted to the stock order in the database. I had to manually set it in the admin panel

**Comment by SchrodingersGat** [comment]
@G-Pereira the `purchase_price` will not be saved if the part being referenced is not marked as "purchaseable"

Look at the "details" tab for `XH-3A` and check that the "purchaseable" flag is set:

![image](https://user-images.githubusercontent.com/10080325/118415332-09a14380-b6ed-11eb-8812-d285acbcb224.png)

**Comment by G-Pereira** [comment]
I confirm that! Thank you!
It makes sense not storing the value in that case but shouldn't the field be hidden if a not purchase able part is selected?
