### ISSUE TITLE
Internal prices

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1606]
@SchrodingersGat what do you think of internal prices for parts?
The use case would be for calculations in assemblies as the sale-price normally includes a profit margin and only using the sub-part prices does not include the work-time.

**Comment by SchrodingersGat** [comment]
I think this makes sense. What extra fields / information do you think would be added?

**Comment by matmair** [comment]
@SchrodingersGat I would add a price range just like the sale-price and add tools for calculating / fitting those into the 'new' pricing view.
