### ISSUE TITLE
Support for diffrent views eg. gallery view

### ISSUE THREAD

**Issue by Marioheld** [inventree/InvenTree#1615]
Sometimes it is really handy to browse the parts by pictures. 
Generally the support for viewing the data in diffrent ways (list, gallery, map/locations) would be a nice feature. 
While changing the CSS for a gallery view seems to be easy at first, I think there is more underlaying work needed so that InvenTree is aware of the types of views and the currently selected view of the user. 
The possibility for plugins to provide own views could also bring a big potential.

**Comment by SchrodingersGat** [comment]
@Marioheld would you be able to provide a simple visual mock-up of what you are thinking here?

In general I'm on board with supporting this concept, if it is useful in the general case :)

**Comment by Marioheld** [comment]
The green arrow shows the new view switcher. 
L stands for list mode. This is the currently used view. 
![list view](https://user-images.githubusercontent.com/4212288/120063552-f33da500-c067-11eb-9da1-2192979aaff3.jpg)
G stands for gallery mode. Here you have much larger images and can spot the difference between parts, which have similar naming. 
For example the two types of speaker are very similar but the left type is physically bigger. 
![gallerie view](https://user-images.githubusercontent.com/4212288/120063554-f5076880-c067-11eb-8ad7-b9020b0113f3.jpg)

**Comment by SchrodingersGat** [comment]
That seems more than reasonable.

The current table view is handled using the bootstrap-table library

It appears there is already an extension which might support this feature:

https://examples.bootstrap-table.com/#extensions/custom-view.html

**Comment by Marioheld** [comment]
Taked a look on the custom view extension. 
Looks promising. 
Can I provide you anything else?

**Comment by SchrodingersGat** [comment]
refer to https://github.com/inventree/InvenTree/pull/1622 and let me know what you think
