### ISSUE TITLE
Documentation is failing

### ISSUE THREAD

**Issue by NamasteJasutin** [inventree/InvenTree#162]
Hi,

On https://inventree.readthedocs.io/en/latest/ I'm seeing the following message:
This is an autogenerated index file.

Please create an index.rst or README.rst file with your own content under the root (or /docs) directory in your repository.

**Comment by SchrodingersGat** [comment]
Hi, there's currently nothing in the docs but I am hoping to get started on that soon. This project is still in early stages. Please feel free to help contribute if it is something you are interested in :)

**Comment by SchrodingersGat** [comment]
Documentation is now automatically building - https://inventree.readthedocs.io/en/latest/index.html

It is pretty sparse as I need to go and re-format the doc strings properly.
