### ISSUE TITLE
Regex in part search

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1623]
What do you think about regex support in part table search box?
It is already supported by django and REST framwork, you just have to prepend field name with '$' to enable it.
I tried it with part name and it worked fine even without regexes.
The question is how it affect performance and on what fields it should be enabled.
```
     search_fields = [
-        'name',
+        '$name',
         'description',
         'IPN',
         'revision',
```

https://github.com/inventree/InvenTree/blob/c08ad467bebbda79b9f0f0fe5b97f306d55d8843/InvenTree/part/api.py#L697

**Comment by SchrodingersGat** [comment]
Interesting question. If I was to add support I'd want to see it be a user configurable option. Regex is pretty confusing to the non developer (and even for many developers) and if it was default behaviour it would probably turn off a lot of users.

**Comment by sintech** [comment]
Configurable option sounds nice.
But if you don't use regex special chars in search string it works pretty much the same as with regex disabled.

**Comment by rcludwick** [comment]
1.2.3.4 will regex match 11223344 say.  

So I don't expect a REST api to automatically regex search my query parameter.  I would probably find it surprising if it did and not in a happy way, frankly.

This would be better off handled with a custom query param, like ?name__regex=...  or something.

**Comment by SchrodingersGat** [comment]
I agree that results would be unexpected (and unwanted) if regex search was the default.

What about when you enter a search term into the search bar, a drop-down options menu lets you enable / disable regex search?

**Comment by sintech** [comment]
> a drop-down options menu lets you enable / disable regex search?
Sound good for me. 
As an alternative it could be some special char surrounding regex for ex. `/regex/`. But it is more obscure.

**Comment by matmair** [comment]
@SchrodingersGat are we still interested in this?

**Comment by SchrodingersGat** [comment]
This can be closed. Some parameters support regex search in the manner that @rcludwick suggested above (e.g. `part__name__regex=<xxx>` but I don't think we should support it for general use in the search bar.
