### ISSUE TITLE
[BUG] Bootstrap pagination: NaN to NaN of undefined rows

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1628]
To reproduce:

1. Navigate to a part list under a category
2. Select "All" for the number of items displayed
3. Refresh the page, it will show as:

![image](https://user-images.githubusercontent.com/4020546/120483251-eda1d100-c37f-11eb-82fb-bceeaa7a43b4.png)

**Comment by SchrodingersGat** [comment]
Seems to be happening for all of the tables... but not all the time? This is a very strange one.

**Comment by eeintech** [comment]
@SchrodingersGat It's weird indeed. The number of items shown default to "25" or "ALL" and the pagination also disappears...

## Normal
![image](https://user-images.githubusercontent.com/4020546/120652188-86525280-c44d-11eb-9124-bc0bb760f9c6.png)


## Pagination problem and bad item size
![image](https://user-images.githubusercontent.com/4020546/120652111-720e5580-c44d-11eb-88da-dba61e7832b8.png)

**Comment by eeintech** [comment]
As soon as "25" is selected, everything goes back to normal.

In my testing, only the "ALL" selection is causing this problem, and it is persistent until switched back to "25".

**Comment by matmair** [comment]
Will try to investigate; js is not my strongsuit

**Comment by matmair** [comment]
I think I found the solution for the problem in a [blog post](https://www.programmersought.com/article/47294916291/).
I submitted a PR #1655

@eeintech @SchrodingersGat could you test this please? It seems to kill the nightly version of firefox but all current stable versions of edge, chrome, chromium, firefox and safari seem to work.

**Comment by matmair** [comment]
@SchrodingersGat might I suggest the `bug` label?

**Comment by alfrede** [comment]
could this be helpful? https://github.com/wenzhixin/bootstrap-table/issues/2681 i think it is almost the same.

**Comment by matmair** [comment]
@alfrede as far as I remember this bug was fixed years ago in upstream but we still can't get it to run
