### ISSUE TITLE
Error 505 when viewing part pricing information

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1641]
@matmair I think this one belongs to you :smile: 

![image](https://user-images.githubusercontent.com/4020546/121025315-068cf680-c773-11eb-9224-293b5d5256a2.png)

I get this error on all our parts. Do you know what may cause it?

**Comment by matmair** [comment]
@eeintech could be. On which modal / from which view?

**Comment by eeintech** [comment]
I think I was on a wrong branch, it is working now sorry!

**Comment by matmair** [comment]
@eeintech please also include the version information (found in the about modal in the upper right corner of the page) and the error traceback. Thanks!
