### ISSUE TITLE
Documentation is broken on any page that is not the main index

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#1650]
Going to https://inventree.readthedocs.io/en/latest/ and clicking on any link results in a 404 and broken styling.  Screenshot below is of the "Installation" instructions.

![image](https://user-images.githubusercontent.com/10690911/121387539-fc503100-c907-11eb-9f52-80999db3b5cf.png)

**Comment by SchrodingersGat** [comment]
Can you check again? Does not appear broken to me right now.

**Comment by SchrodingersGat** [comment]
The links from README.md are definitely broken. They can be "fixed" by appending `.html`

I wonder if the readthedocs build has changed something recently

**Comment by SchrodingersGat** [comment]
So looks like the menu links work correctly, but any hard coded embedded links fail.

Definitely looks like the `.html` requirement must have been added?

@eeintech you've had some experience with the mkdocs setup - any idea what might be going on here?

**Comment by SchrodingersGat** [comment]
Ok, I think I've worked it out. Had to re-work most of the links and change some settings in the `mkdocs.yml` file. Probably some config on the readthedocs server has changed recently. At least it has forced me to look under the hood and format the links "correctly" ;)

**Comment by eeintech** [comment]
@SchrodingersGat Glad you fixed it, I just looked into their release notes and indeed we were missing the `site_url` config option which is now required since their 1.2 release (June 4th 2021): https://www.mkdocs.org/about/release-notes/#backward-incompatible-changes-in-12

I guess it forced the path to refer to the `site_url` now.
I don't see why the `.md` extension needed to be added though...

**Comment by SchrodingersGat** [comment]
I enabled the "strict" option which throws an error if there is a broken link (i.e. linking to an internal page that does not exist).

However the broken link detection only works if the .md suffix is used in the link URL

**Comment by eeintech** [comment]
Ok makes sense, thanks!
