### ISSUE TITLE
Add Total row/col to Purchase Order table

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1660]
Enhance "Purchase Order Items" table by adding:

- [ ] "Total" column with quantity * unit price
- [ ] "Grand Total" row with sum of all rows quantity and prices.

**Comment by matmair** [comment]
@sintech / @SchrodingersGat I think this can be closed

**Comment by SchrodingersGat** [comment]
@sintech check out latest version and let us know if this addresses your requests

**Comment by sintech** [comment]
This is exactly what i needed, thanks @matmair , @SchrodingersGat
