### ISSUE TITLE
Label printing 

### ISSUE THREAD

**Issue by watarat** [inventree/InvenTree#1665]
I've just bought a label printer - and am having heaps fun creating decently labelled bags of 'stuff' :)
(And then scanning with the Android App - awesome!!)
I'm trying to use my internal part number as a major textual header for my label - and it doesn't seem to be populated as expected.
As a workaround - I'm printing "item.part" - As it prints the whole shebang starting with the IPN. (1131 in sample below)
If I try and just print item.ipn - I get no data.
e.g. relevant bit of the html I've used

```
<div class='partt'>
  <b>TI IPN  : {{ item.ipn }} </b>
  <hr>
  TI Part : {{ item.part }}
  <hr>
</div>
```

and pic of output .pdf - you can see the upper right corner doesn't print the ipn (in bold).
I'm really just groping in the dark - based on the hints in the 'readthedocs' - so may well have the code wrong :)
(Is there a reference (or maybe a bit of code I can read) that tells what the available fields are for pulling out data)
( I have gotten as far as inferring stuff like printing "item.location.parent.name " which works just fine :)

![Clipboard02](https://user-images.githubusercontent.com/8358937/122198767-9a2f9700-ced8-11eb-860d-a73da4bb0489.jpg)

Whole code in case it makes life easier :)

```
{% extends "label/label_base.html" %}

{% load barcode %}

{% block style %}


.qr {
    position: fixed;
    left: 1mm;
    top: 0mm;
    height: 14mm;
    width:  14mm;
}

.partt {
    font-family: Arial, Helvetica, sans-serif;
    font-size:10px;
    display: inline;
    position: absolute;
    left: 18mm;
    top: 2mm;
}

.locat {
    font-family: Arial, Helvetica, sans-serif;
    font-size:10px;
    display: inline;
    position: absolute;
    left: 2mm;
    top: 18mm;
}

{% endblock %}

{% block content %}

<img class='qr' src='{% qrcode qr_data %}'>

<div class='partt'>
  <b>TI IPN  : {{ item.ipn }} </b>
  <hr>
  TI Part : {{ item.part }}
  <hr>
</div>

<div class='locat'>
  Location:<br>
  {{ item.location.parent.name }}<hr>
  {{ item.location.name }}<hr>
  {# (Qty: {{ item.quantity }} ) #}
</div>

{% endblock %}
```

**Comment by SchrodingersGat** [comment]
Hey @watarat first let me say I am **super** excited that you're making use of both the label printing functionality and the barcode scanning in the app. I would be *very* interested in any feedback you have for these features, as I have felt like it was only me that was using them :D

Regarding printing the IPN- please note that the field names are case-sensitive. Try `{{ part.IPN }}` and see if that works for you :)

**Comment by watarat** [comment]
Dang - Smacked self in head !!
Yep- that sorted it!  Fully qualified to item.part.IPN (I had item.ipn - but had tried all combos with wrong case :)  )
```
<div class='partt'>
  <b>TI IPN  : {{ item.part.IPN }} XY</b>
  <hr>
  TI Part : {{ item.part }}
  <hr>
</div>
```

XY is there just to prove change made it through!!
![Clipboard01](https://user-images.githubusercontent.com/8358937/122220253-51370d00-ceef-11eb-8a80-d0a9c8a50589.jpg)

The combo of dedicated printed labels and the App are just incredible.
I guess my experience is: Dont try and understand it from a technical point of view - its just so natural to use, you need to play with it!
I am experimenting with a little app called Barcode2Win which is a funky pair of apps that connect your android camera as a barcode reader , to a matching app on Windows (Over WiFi). It can paste the barcode to what is effectively a 'wedged' keyboard input.
Thus I can use the App (which is great) - or by jamming the barcode into the desktop ("scan barcode" part of the browser) - I can do all the desktop stuff just as easily.
Its a no cost option to explore just how powerful it can be.  (Go buy a real scanner for <$50 on ebay when you're convinced :)  )

I'll try and put together something as a review on Google Play -as its a bit sparse at the mo! :)

Thanks for prompt reply - its soo good (refreshing) to use software that really "just works"  :)

**Comment by SchrodingersGat** [comment]
Happy to help! Let me know if you come across any other issues, or (even better) if you have any ideas on how we can make the software better!
