### ISSUE TITLE
Stock part with price zero

### ISSUE THREAD

**Issue by G-Pereira** [inventree/InvenTree#1671]
Stock with purchase price zero doesn't show the price (zero) this is useful when part came from a sample order.

**Comment by SchrodingersGat** [comment]
To clarify - do you mean the price has been manually entered as zero, or the price has been left blank?

Can you share a screenshot of where you are seeing the issue?

**Comment by G-Pereira** [comment]
I mean setting the part with explicitly zero cost doesn't get the price to show up as zero it is instead hidden.
![image](https://user-images.githubusercontent.com/15521303/122682102-737ea280-d1ef-11eb-9739-e359a3c1bca7.png)
![image](https://user-images.githubusercontent.com/15521303/122682120-87c29f80-d1ef-11eb-9ea4-4773c3e1b099.png)
