### ISSUE TITLE
Redesign of Part main page

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1673]
I propose to reduce the number of clicks needed to get all part info by changing the contents of Part page.
Current `Part Details` pane have info and elements rarely used during part lifetime, so it could be moved to one of the secondary pages. While the other info, such as: stock, parameters, notes and attachments should be available right on the main page.
Tables could be limited to display only N rows with link to corresponding pane to get everything else. Or vertical scroll-bar could be used instead.
Please find attached a mockups of main page for wide and narrow browser windows.
What do you think?

![part_details_wide](https://user-images.githubusercontent.com/10057327/122350997-61ce9e00-cf56-11eb-8046-6644ed2c218f.png)
![part_details_narrow](https://user-images.githubusercontent.com/10057327/122350995-61360780-cf56-11eb-98e4-4da45c4a80be.png)

**Comment by SchrodingersGat** [comment]
In general I agree that the part detail page could be more "information dense"

I'd like to see a "simplified" version of the stock table here, with the existing stock table kept on a separate tab - otherwise i think it would look too cluttered.

**Comment by eeintech** [comment]
It's a fair asking, the difficulty relies on which information to display first, each and every InvenTree user would have their own preference...

**Comment by sintech** [comment]
> "simplified" version

Entirely agree with this, all tables could be just static html tables with minimum necessary information. 

![part_details_lite](https://user-images.githubusercontent.com/10057327/122400694-9fe2b680-cf84-11eb-8d93-a796b8de0cbb.png)

**Comment by SchrodingersGat** [comment]
I certainly don't want to have to support "configurable" displays, unless someone puts up their hand to manage the template / javascript coding for that!

Any changes here would have to be more than simple aesthetic preferences, otherwise we'd have to manage multiple stylistic changes all the time!

@sintech I like the simplified version you've outlined above. Not very intrusive at all. And most of the "important" information is front and center.

**Comment by matmair** [comment]
@SchrodingersGat sounds like a nightmare with the current frontend-stack 👼

@sintech proposal makes sense, maybe keep the current info-header for the more detailed views and just change `/part/<pk>`?

**Comment by eeintech** [comment]
I like the proposal too. One warning is about the size of the front tables, it should be limited to 2-3 elements max, preferably filter in "last updated" fashion. If you have 10-15 parameters per parts (like we do), tons of attachments and stock items, it will make it worse!

**Comment by sintech** [comment]
> size of the front tables

Let's make it configurable. Or make tables partially visible with button to show all (via css/js).

**Comment by sintech** [comment]
Thank you @SchrodingersGat, part page is definitely better now.
But it still has duplicates of part info and rarely used property switches right in the middle of the page.
Maybe it makes sense to move switches to "edit part" modal?
Screenshot of my part page:
![part_main_new](https://user-images.githubusercontent.com/10057327/125406755-d9f77a80-e3c1-11eb-8d6f-709c1c75ac46.png)

**Comment by SchrodingersGat** [comment]
@sintech good point, will be addressed as part of https://github.com/inventree/InvenTree/pull/1811
