### ISSUE TITLE
ModuleNotFoundError: No module named 'postgres', in  docker production server

### ISSUE THREAD

**Issue by carlosmatthews** [inventree/InvenTree#1685]
hi, i am trying to implement inventree with DOCKER production server, on VM with centos7.
I follow the steps of the documentation but in the step.

> docker-compose run inventree-server invoke migrate

I get an error that seems to be related to the default database, and to the python posgres module:

Starting inventree-db ... done
Running InvenTree database migrations...

InvenTree Database Configuration

ENGINE: postgres
NAME: inventree
HOST: inventree-db
2021-06-18 13:35:08,715 INFO Loading SECRET_KEY from '/home/inventree/data/secret_key.txt'
2021-06-18 13:35:08,716 INFO InvenTree running in DEBUG mode
2021-06-18 13:35:08,716 INFO MEDIA_ROOT: '/home/inventree/data/media'
2021-06-18 13:35:08,716 INFO STATIC_ROOT: '/home/inventree/static'
2021-06-18 13:35:08,716 INFO Configuring database backend:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'postgres'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inventree/src/InvenTree/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/usr/local/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 122, in load_backend
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'postgres' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
[root@localhost admin]#

**Comment by SchrodingersGat** [comment]
> ENGINE: postgres
> NAME: inventree
> HOST: inventree-db

`ENGINE` should be set to `postgresql`, not `postgres` in your configuration. Please adjust that and see if the issue is resolved.

**Comment by matmair** [comment]
@carlosmatthews does the error still occur with the proposed changes?

**Comment by carlosmatthews** [comment]
> 
> 
> @carlosmatthews does the error still occur with the proposed changes?

**Comment by carlosmatthews** [comment]
@matmair 
hello I made the suggested change in the variable ENGINE = posgresql and the installation could be completed.
Now, what you cannot enter is the web interface through:
You should now be able to view the InvenTree login screen at http: // localhost: 1337
I'm deploying on a remote machine through vpv and ssh

**Comment by matmair** [comment]
@carlosmatthews If you deploy on a remote machine over a VPN (?) your InvenTree-site will be served under the IP-address of that server. To get that use the following command in bash (on linux)
``` bash
ifconfig -a.
```
On a personal note: It might be more user-friendly to use a domain / subdomain for InvenTree because people tend to remember words easier.

**Comment by carlosmatthews** [comment]
> 
> 
> @carlosmatthews does the error still occur with the proposed changes?
With the proposed changes you can do the installation correctly

**Comment by matmair** [comment]
@carlosmatthews so is it working? Does the server answer on its IP-address?

**Comment by carlosmatthews** [comment]
> 
> 
> @carlosmatthews so is it working? Does the server answer on its IP-address?

no I have no response from the server on port 1337 where the interface is in theory, I could finish the installation but I cannot connect to the interface, scanned the ports of the server it only shows me 22 and 49159 of posgresql

**Comment by carlosmatthews** [comment]
> 
> 
> @carlosmatthews so is it working? Does the server answer on its IP-address? 
I made a scan with nmap to the ip of the virtual machine and I only see ports 22 ssh and 491 59 of postgesql.
I have already manually opened port 1337 in the virtual machine.
probe from the VM to curl localhost: 1337 and reject the connection, instead, port 49159 returns an empty response.
If I run the command docker container ls it shows that the containers are running:
`CONTAINER ID   IMAGE                        COMMAND                  CREATED        STATUS                         PORTS                                         NAMES
b658f56ce542   inventree/inventree:latest   "./start_worker.sh"      25 hours ago   Up 25 hours                                                                  inventree-worker
674ae71089e8   nginx                        "/docker-entrypoint.…"   25 hours ago   Restarting (1) 3 seconds ago                                                 inventree-proxy
e26949398828   inventree/inventree:latest   "bash ./start_prod_s…"   25 hours ago   Up 25 hours                    8000/tcp                                      inventree-server
d6ac5f1e1c19   inventree/inventree:latest   "invoke superuser"       25 hours ago   Up 25 hours                    8000/tcp                                      admin_inventree-server_run_1b7eca191e2f
af552b2affa3   inventree/inventree:latest   "invoke static"          26 hours ago   Up 4 seconds                   8000/tcp                                      admin_inventree-server_run_1041784f8457
e3377bffd7fb   inventree/inventree:latest   "invoke migrate"         26 hours ago   Up 7 seconds                   8000/tcp                                      admin_inventree-server_run_3fa79392c749
e7d42b3431ed   inventree/inventree:latest   "pgcli -h inventree-…"   26 hours ago   Up 26 hours                    8000/tcp                                      admin_inventree-server_run_5a660ff64746
19ba2f11bd9a   postgres                     "docker-entrypoint.s…"   26 hours ago   Up 26 hours                    0.0.0.0:49159->5432/tcp, :::49159->5432/tcp   inventree-db`

**Comment by carlosmatthews** [comment]
> 
> 
> @carlosmatthews are you using a `docker-compose.yml` file? If so can you share that here?

version: "3.3"

# Docker compose recipe for InvenTree
# - Runs PostgreSQL as the database backend
# - Runs Gunicorn as the InvenTree web server
# - Runs the InvenTree background worker process
# - Runs nginx as a reverse proxy

# ---------------------------------
# IMPORTANT - READ BEFORE STARTING!
# ---------------------------------
# Before running, ensure that you change the "/path/to/data" directory,
# specified in the "volumes" section at the end of this file.
# This path determines where the InvenTree data will be stored!
#

services:
    # Database service
    # Use PostgreSQL as the database backend
    # Note: this can be changed to a different backend,
    # just make sure that you change the INVENTREE_DB_xxx vars below
    inventree-db:
        container_name: inventree-db
        image: postgres
        ports:
            - 5432/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            # The pguser and pgpassword values must be the same in the other containers
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=pgpassword
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - data:/var/lib/postgresql/data/
        restart: unless-stopped

    # InvenTree web server services
    # Uses gunicorn as the web server
    inventree-server:
        container_name: inventree-server
        image: inventree/inventree:latest
        expose:
            - 8000
        depends_on:
            - inventree-db
        volumes:
            # Data volume must map to /home/inventree/data
            - data:/home/inventree/data
        environment:
            # Default environment variables are configured to match the 'db' container
            # Note: If you change the database image, these will need to be adjusted
            # Note: INVENTREE_DB_HOST should match the container name of the database
            - INVENTREE_DB_USER=pguser
            - INVENTREE_DB_PASSWORD=pgpassword
            - INVENTREE_DB_ENGINE=postgresql
            - INVENTREE_DB_NAME=inventree
            - INVENTREE_DB_HOST=inventree-db
            - INVENTREE_DB_PORT=5432
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        container_name: inventree-worker

**Comment by carlosmatthews** [comment]
> 
> 
> @carlosmatthews are you using a `docker-compose.yml` file? If so can you share that here?

`version: "3.3"

# Docker compose recipe for InvenTree
# - Runs PostgreSQL as the database backend
# - Runs Gunicorn as the InvenTree web server
# - Runs the InvenTree background worker process
# - Runs nginx as a reverse proxy

# ---------------------------------
# IMPORTANT - READ BEFORE STARTING!
# ---------------------------------
# Before running, ensure that you change the "/path/to/data" directory,
# specified in the "volumes" section at the end of this file.
# This path determines where the InvenTree data will be stored!
#

services:
    # Database service
    # Use PostgreSQL as the database backend
    # Note: this can be changed to a different backend,
    # just make sure that you change the INVENTREE_DB_xxx vars below
    inventree-db:
        container_name: inventree-db
        image: postgres
        ports:
            - 5432/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            # The pguser and pgpassword values must be the same in the other containers
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=pgpassword
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - data:/var/lib/postgresql/data/
        restart: unless-stopped

    # InvenTree web server services
    # Uses gunicorn as the web server
    inventree-server:
        container_name: inventree-server
        image: inventree/inventree:latest
        expose:
            - 8000
        depends_on:
            - inventree-db
        volumes:
            # Data volume must map to /home/inventree/data
            - data:/home/inventree/data
        environment:
            # Default environment variables are configured to match the 'db' container
            # Note: If you change the database image, these will need to be adjusted
            # Note: INVENTREE_DB_HOST should match the container name of the database
            - INVENTREE_DB_USER=pguser
            - INVENTREE_DB_PASSWORD=pgpassword
            - INVENTREE_DB_ENGINE=postgresql
            - INVENTREE_DB_NAME=inventree
            - INVENTREE_DB_HOST=inventree-db
            - INVENTREE_DB_PORT=5432
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        container_name: inventree-worker`

**Comment by carlosmatthews** [comment]
@SchrodingersGat
here is the yml docker-compose file, it was copied and pasted from:
https://inventree.readthedocs.io/en/latest/start/docker_prod/

```
version: "3.3"


# Docker compose recipe for InvenTree

# - Runs PostgreSQL as the database backend
# - Runs Gunicorn as the InvenTree web server
# - Runs the InvenTree background worker process
# - Runs nginx as a reverse proxy

# ---------------------------------
# IMPORTANT - READ BEFORE STARTING!
# ---------------------------------

# Before running, ensure that you change the "/path/to/data" directory,
# specified in the "volumes" section at the end of this file.
# This path determines where the InvenTree data will be stored!
#


services:
    # Database service
    # Use PostgreSQL as the database backend
    # Note: this can be changed to a different backend,
    # just make sure that you change the INVENTREE_DB_xxx vars below
    inventree-db:
        container_name: inventree-db
        image: postgres
        ports:
            - 5432/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            # The pguser and pgpassword values must be the same in the other containers
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=pgpassword
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - data:/var/lib/postgresql/data/
        restart: unless-stopped

    # InvenTree web server services
    # Uses gunicorn as the web server
    inventree-server:
        container_name: inventree-server
        image: inventree/inventree:latest
        expose:
            - 8000
        depends_on:
            - inventree-db
        volumes:
            # Data volume must map to /home/inventree/data
            - data:/home/inventree/data
        environment:
            # Default environment variables are configured to match the 'db' container
            # Note: If you change the database image, these will need to be adjusted
            # Note: INVENTREE_DB_HOST should match the container name of the database
            - INVENTREE_DB_USER=pguser
            - INVENTREE_DB_PASSWORD=pgpassword
            - INVENTREE_DB_ENGINE=postgresql
            - INVENTREE_DB_NAME=inventree
            - INVENTREE_DB_HOST=inventree-db
            - INVENTREE_DB_PORT=5432
        restart: unless-stopped

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        container_name: inventree-worker
 inventree-worker:
        container_name: inventree-worker
        image: inventree/inventree:latest
        entrypoint: ./start_worker.sh
        depends_on:
            - inventree-db
            - inventree-server
        volumes:
            # Data volume must map to /home/inventree/data
            - data:/home/inventree/data
        environment:
            # Default environment variables are configured to match the 'db' container
            # Note: If you change the database image, these will need to be adjusted
            # Note: INVENTREE_DB_HOST should match the container name of the database
            - INVENTREE_DB_USER=pguser
            - INVENTREE_DB_PASSWORD=pgpassword
            - INVENTREE_DB_ENGINE=postgresql
            - INVENTREE_DB_NAME=inventree
            - INVENTREE_DB_HOST=inventree-db
            - INVENTREE_DB_PORT=5432
        restart: unless-stopped

    # nginx acts as a reverse proxy
    # static files are served directly by nginx
    # media files are served by nginx, although authentication is redirected to inventree-server
    # web requests are redirected to gunicorn
    # NOTE: You will need to provide a working nginx.conf file!
    inventree-proxy:
        container_name: inventree-proxy
        image: nginx
        depends_on:
            - inventree-server
        ports:
            # Change "1337" to the port that you want InvenTree web server to be available on
            - 1337:80
        volumes:
            # Provide ./nginx.conf file to the container
            # Refer to the provided example file as a starting point
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            # nginx proxy needs access to static and media files
            - data:/var/www
        restart: unless-stopped


volumes:
    # NOTE: Change /path/to/data to a directory on your local machine
    # Persistent data, stored external to the container(s)
    data:
        driver: local
        driver_opts:
            type: none
            o: bind
            # This directory specified where InvenTree data are stored "outside" the docker containers
            # Change this path to a local system path where you want InvenTree data stored
            device: /home/admin/datos

```

**Comment by SchrodingersGat** [comment]
Do you have the `nginx.conf` file located in the same path as your `docker-compose.yml` file?

**Comment by carlosmatthews** [comment]
> 
> 
> Do you have the `nginx.conf` file located in the same path as your `docker-compose.yml` file?

yes

**Comment by SchrodingersGat** [comment]
What does the log of the `inventree-proxy` container show? Are any requests making it to the proxy?

**Comment by carlosmatthews** [comment]
> 
> 
> What does the log of the `inventree-proxy` container show? Are any requests making it to the proxy?

I think that now the proxy is working, there was an error in the nginx.conf file, I am trying to make an ssh tunnel to enter the remote VM and the interface from my local browser


[root@localhost admin]# docker logs inventree-proxy
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/06/24 14:22:26 [notice] 1#1: using the "epoll" event method
2021/06/24 14:22:26 [notice] 1#1: nginx/1.21.0
2021/06/24 14:22:26 [notice] 1#1: built by gcc 8.3.0 (Debian 8.3.0-6)
2021/06/24 14:22:26 [notice] 1#1: OS: Linux 3.10.0-1127.18.2.el7.x86_64
2021/06/24 14:22:26 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/06/24 14:22:26 [notice] 1#1: start worker processes
2021/06/24 14:22:26 [notice] 1#1: start worker process 24
2021/06/24 14:22:26 [notice] 1#1: start worker process 25
172.21.0.1 - - [24/Jun/2021:14:24:59 +0000] "GET / HTTP/1.1" 302 0 "-" "curl/7.29.0" "-"

**Comment by carlosmatthews** [comment]
its work...thanks
