### ISSUE TITLE
Observe "default" values for blank fields when creating objects via API

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1687]
It appears that when creating objects via the API (e.g. with the python interface), then any fields not explicitly specified will have the value set to "blank" or "false", rather than the value specified as "default" for that field in the model..

Needs to be investigated!

**Comment by SchrodingersGat** [comment]
After research, it appears that the behaviour I "expected" to work is not yet supported in DRF:

Ref: https://github.com/encode/django-rest-framework/pull/8002

Hopefully this is merged soon

**Comment by eeintech** [comment]
Good catch @SchrodingersGat, hope the feature request gets in soon!
