### ISSUE TITLE
Table ordering not working for any parameter

### ISSUE THREAD

**Issue by G-Pereira** [inventree/InvenTree#1689]
![image](https://user-images.githubusercontent.com/15521303/122682048-35817e80-d1ef-11eb-92d5-8b41370cd088.png)

**Comment by SchrodingersGat** [comment]
@G-Pereira please confirm that the fix by @matmair has addressed the issue for you

**Comment by G-Pereira** [comment]
Yes! I forgot to check existing ones!

**Comment by SchrodingersGat** [comment]
I think @matmair was just very quick to respond ;)

**Comment by G-Pereira** [comment]
Yes, you two are incredible!

**Comment by matmair** [comment]
I tend to do some simple issues when I can't crack a harder problem 👼
