### ISSUE TITLE
Docker: inventree worker doesn't start.

### ISSUE THREAD

**Issue by rcludwick** [inventree/InvenTree#1702]
As of today I see this when trying to start inventree-worker in the docker format.

```
ERROR: for inventree-worker  Cannot start service inventree-worker: OCI runtime create failed: 
container_linux.go:380: starting container process caused: exec: "./start_worker.sh": stat ./start_worker.sh: 
no such file or directory: unknown
```

Looks like the start_worker.sh script maybe moved perhaps or didn't get added to the docker container.

I double checked my config against the docker production docs and it looks good, and the inventree-server side works for me. 

https://inventree.readthedocs.io/en/latest/start/docker_prod/

**Comment by wengtad** [comment]
Yup I'm was hitting this previously. You will need to use `./start_prod_worker.sh` instead of  `./start_worker.sh` . The docs seems to be outdated.

**Comment by SchrodingersGat** [comment]
@rcludwick I've updated the docs, should work if you change to `start_prod_worker`

Thanks
