### ISSUE TITLE
the web interface does not appear correctly

### ISSUE THREAD

**Issue by carlosmatthews** [inventree/InvenTree#1720]
inventree is running (installation with docker production), only the web interface looks plain and without images.

![imagen](https://user-images.githubusercontent.com/68878024/123296722-4848cb80-d4ed-11eb-85c1-b1c0b49d5bec.png)

**Comment by SchrodingersGat** [comment]
Have a look at your nginx logs and see what is happening for any request to `/static/`

It appears that the static files (which includes css files) are not being served properly.

**Comment by carlosmatthews** [comment]
Yes , itseems that the Log shows erros whith static files. How can I fix it?.
I paste a part of the Log, down here..

`2021/06/24 15:59:22 [error] 24#24: *11 open() "/var/www/static/img/inventree.png" failed (2: No such file or directory), client: 10.68.18.20, server: , request: "GET /static/img/inventree.png HTTP/1.1", host: "10.68.19.203:1337", referrer: "http://10.68.19.203:1337/build/"
10.68.18.20 - - [24/Jun/2021:15:59:22 +0000] "GET /static/img/inventree.png HTTP/1.1" 404 153 "http://10.68.19.203:1337/build/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" "-"
2021/06/24 15:59:22 [error] 24#24: *29 open() "/var/www/static/script/bootstrap/bootstrap-treeview.js" failed (2: No such file or directory), client: 10.68.18.20, server: , request: "GET /static/script/bootstrap/bootstrap-treeview.js HTTP/1.1", host: "10.68.19.203:1337", referrer: "http://10.68.19.203:1337/build/"
10.68.18.20 - - [24/Jun/2021:15:59:22 +0000] "GET /static/script/bootstrap/bootstrap-treeview.js HTTP/1.1" 404 153 "http://10.68.19.203:1337/build/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" "-"
2021/06/24 15:59:22 [error] 24#24: *11 open() "/var/www/static/script/bootstrap/bootstrap-toggle.js" failed (2: No such file or directory), client: 10.68.18.20, server: , request: "GET /static/script/bootstrap/bootstrap-toggle.js HTTP/1.1", host: "10.68.19.203:1337", referrer: "http://10.68.19.203:1337/build/"
10.68.18.20 - - [24/Jun/2021:15:59:22 +0000] "GET /static/script/bootstrap/bootstrap-toggle.js HTTP/1.1" 404 153 "http://10.68.19.203:1337/build/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" "-"
10.68.18.20 - - [24/Jun/2021:15:59:22 +0000] "GET /static/bootstrap-table/bootstrap-table.js HTTP/1.1" 404 153 "http://10.68.19.203:1337/build/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" "-"
2021/06/24 15:59:22 [error] 24#24: *11 open() "/var/www/static/bootstrap-table/bootstrap-table.js" failed (2: No such file or directory), client: 10.68.18.20, server: , request: "GET /static/bootstrap-table/bootstrap-table.js HTTP/1.1", host: "10.68.19.203:1337", referrer: "http://10.68.19.203:1337/build/"
2021/06/24 15:59:22 [error] 24#24: *11 open() "/var/www/static/bootstrap-table/bootstrap-table-en-US.min.js" failed (2: No such file or directory), client: 10.68.18.20, server: , request: "GET /static/bootstrap-table/bootstrap-table-en-US.min.js HTTP/1.1", host: "10.68.19.203:1337", referrer: "http://10.68.19.203:1337/build/"
10.68.18.20 - - [24/Jun/2021:15:59:22 +0000] "GET /static/bootstrap-table/bootstrap-table-en-US.min.js HTTP/1.1" 404 153 "http://10.68.19.203:1337/build/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" "-"
2021/06/24 15:59:22 [error] 24#24: *11 open() "/var/www/static/treegrid/js/jquery.treegrid.js" failed (2: No such file or directory), client: 10.68.18.20, server: , request: "GET /static/treegrid/js/jquery.treegrid.js HTTP/1.1", host: "10.68.19.203:1337", referrer: "http://10.68.19.203:1337/build/"
10.68.18.20 - - [24/Jun/2021:15:59:22 +0000] "GET /static/treegrid/js/jquery.treegrid.js HTTP/1.1" 404 153 "http://10.68.19.203:1337/build/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" "-"
2021/06/24 15:59:22 [error] 24#24: *11 open() "/var/www/static/treegrid/js/jquery.treegrid.bootstrap3.js" failed (2: No such file or directory), client: 10.68.18.20, server: , request: "GET /static/treegrid/js/jquery.treegrid.bootstrap3.js HTTP/1.1", host: "10.68.19.203:1337", referrer: "http://10.68.19.203:1337/build/"`

**Comment by carlosmatthews** [comment]
@SchrodingersGat 
if indeed it seems that there was a problem with the static files, as you indicate.
perform the update of the inventree docker image, as specified in the docker production server guide.
`docker-compose down`
`docker-compose pull
docker-compose up -d`
Now the interface is working. but I got the following error:
```
ERROR: for inventree-worker  Cannot start service inventree-worker: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./start_worker.sh": stat ./start_worker.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```
I understand that the Background Worker is not running but I don't know how I could start it correctly. Thanks

**Comment by carlosmatthews** [comment]
edit the docker-compose file, change:
`entrypoint: ./start__worker.sh    >>>>>  entrypoint: ./start_prod_worker.sh`
and the worker started

**Comment by SchrodingersGat** [comment]
So all working OK now?

**Comment by carlosmatthews** [comment]
> 
> 
> So all working OK now?
HI, the program is runing, seems good.
The only strange thing that I see is this indication in the program options:
of an issues detected in the server.
I don't know exactly what it means, or if I should pay attention to it or not. Thanks.

![imagen](https://user-images.githubusercontent.com/68878024/123635366-fb693b80-d7f1-11eb-80c1-a8ab1b717989.png)

**Comment by SchrodingersGat** [comment]
@carlosmatthews this error message is OK, it just means that you have not configured an email account for outgoing mail. This would be used (for example) to allow users to receive a password reset email.
