### ISSUE TITLE
reintroduce BOM price?

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1721]
https://github.com/inventree/InvenTree/blob/be85de4a7b5dc6d328fe1d519dd592fdba76b76e/InvenTree/templates/js/bom.js#L264-L281

Hey @SchrodingersGat do you thin pricing has been fixed / what was meant by that?

**Comment by SchrodingersGat** [comment]
I think this has been addressed by now. I should have left more detail. I think that I disabled the pricing column as the pricing needed a huge overhaul and was very expensive (slow) to calculate. That comment can safely be removed now.
