### ISSUE TITLE
Server V6 

### ISSUE THREAD

**Issue by watarat** [inventree/InvenTree#1728]
Busting to try new mobile functionality, having trouble getting server to Version 6 however.
Think I've updated to latest code (complete git klutz here!!)
```
(env) inventree@richard-VirtualBox:~/inventree/InvenTree$ git pull origin master
From https://github.com/inventree/inventree
 * branch              master     -> FETCH_HEAD
Already up to date.
(env) inventree@richard-VirtualBox:~/inventree/InvenTree$ 
```
Restarting server gives

> InvenTree Version	0.2.4 pre &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Up to Date]
> API Version	5
> Python Version	3.8.5
> Django Version	3.2.4
> Commit Hash	061a120a
> Commit Date	2021-06-22
> 

And of course the app isnt happy - requiring API V6.

**Comment by SchrodingersGat** [comment]
That commit hash is from a few days ago...

Strange that the server is reporting old code if you are pulling down from git.

Can you run this command from the command line and post the results?

```
git rev-parse --short HEAD
```

**Comment by watarat** [comment]
```
(env) inventree@richard-VirtualBox:~/inventree/InvenTree$ git rev-parse --short HEAD
b5086ab7
(env) inventree@richard-VirtualBox:~/inventree/InvenTree$ 
```

**Comment by SchrodingersGat** [comment]
Yeah so that code does not match what the server is actually running. Is it possible you have download 2 copies?

What is the server configuration you are running? Is it running in docker, or a custom setup?

**Comment by watarat** [comment]
Yes - quite possible I've stuffed up the install :(
Server is running in an Ubuntu Desktop VM under VirtualBox - PostGreSQL backend.
I'm running it from 
```
cd /home/inventree/
source ./env/bin/activate
cd src/
invoke server -a 192.168.31.112:8000
```

and the git commands are issued from here
```
(env) inventree@richard-VirtualBox:~/inventree/InvenTree$ pwd
/home/inventree/inventree/InvenTree

(env) inventree@richard-VirtualBox:~/inventree/InvenTree$ ls
barcodes  common   config_template.yaml  img_source  label   manage.py  part     report  stock      users
build     company  gunicorn.conf.py      InvenTree   locale  order      plugins  script  templates
(env) inventree@richard-VirtualBox:~/inventree/InvenTree$
```

**Comment by SchrodingersGat** [comment]
Did you run `invoke update` after pulling down the new source code?

**Comment by watarat** [comment]
Sent self to naughty corner - because I hadnt, but that doesnt seem to change things?

**Comment by SchrodingersGat** [comment]
It should not change *this* particular issue, but I thought it was worth checking.

The strange part is that the git hash values are different...

Can you show the log messages when you start the server?

**Comment by watarat** [comment]
Log messages?? , not sure where from, Log subdir is empty
```
(env) inventree@richard-VirtualBox:~/log$ pwd
/home/inventree/log
(env) inventree@richard-VirtualBox:~/log$ ls
(env) inventree@richard-VirtualBox:~/log$

```
- Terminal output
```
- InvenTree Database Configuration
================================
ENGINE: django.db.backends.postgresql
NAME: inventreeti
HOST: localhost
InvenTree Database Configuration
================================
ENGINE: django.db.backends.postgresql
NAME: inventreeti
HOST: localhost
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 28, 2021 - 04:10:08
Django version 3.2.4, using settings 'InvenTree.settings'
Starting development server at http://192.168.31.112:8000/
Quit the server with CONTROL-C.

```

**Comment by SchrodingersGat** [comment]
Thanks, it was the terminal output I was interested in...

```
cd /home/inventree/
source ./env/bin/activate
cd src/
invoke server -a 192.168.31.112:8000
```

It looks like maybe you've duplicated the code under `~/inventree/src` ?

**Comment by watarat** [comment]
Yep - looks that way - its the one I've configured - but guess its the one in /inventree that I'm 'git updating'.
I'll have a crack at sorting that out (Not quite sure how I got that to be..)
Thanks so much - sorry for annoying!

**Comment by watarat** [comment]
YUP!!
Re configured the one under /inventree/Inventree - tada!!
```
# Version Information:
InvenTree-Version: 0.2.5 pre
Django Version: 3.2.4
Commit Hash: b5086ab7
Commit Date: 2021-06-28
Database: postgresql
Debug-Mode: True
Deployed using Docker: False
```
ahh - The "Copy Version" button on the page doesnt copy the API Version (shown above) - but it's 6 👍 
(or python version)

```
InvenTree Version	0.2.5 pre            [Up to Date]
API Version	6
Python Version	3.8.5
```
Thanks again!!

**Comment by SchrodingersGat** [comment]
Nice work :) Happy to close this out then?

**Comment by watarat** [comment]
Definitely close it - just uploaded a part picture - fabulous!! 
Awesome - thanks again.
Richard.

Trivial - but noticed that the action of deleting the last parts in stock (via App), - that are set as delete when depleted...
Causes a red Error bar at bottom of screen, and then puts up Bad Request 400 Error message box.
It does however do exactly what you'd expect!!
Suspect it is just failing on refreshing the data for non existent part.
Cheers
Rich

**Comment by SchrodingersGat** [comment]
Thanks for that feedback @watarat - I'll have to have a look into that.

Please let me know if you find any other issues using the app, or want to suggest some features.

Cheers
