### ISSUE TITLE
Errors with Dockerfile apk add --no-cache fontconfig

### ISSUE THREAD

**Issue by BansheePrime** [inventree/InvenTree#1735]
Probably my misunderstanding but I keep getting following error when I use required python:alpine image:
```
ERROR: unable to select packages:
  ttf-ubuntu-font-family (no such package):
    required by: world[ttf-ubuntu-font-family]
```

If I use alpine:3.13 image there is no errors with line 57 in Dockerfile:
``
RUN apk add --no-cache fontconfig ttf-droid ttf-liberation ttf-dejavu ttf-opensans ttf-ubuntu-font-family font-croscore font-noto
``

In this case pip should be properly installed with something like:
`apk add --update py-pip`

**Comment by BansheePrime** [comment]
Looks like in Alpine 3.14 we have no package ttf-ubuntu-font-family:
 https://alpine.pkgs.org/3.14/alpine-main-x86_64/5/

**Comment by SchrodingersGat** [comment]
Are you downloading the inventree docker image pre-built from dockerhub, or building yourself from source?

**Comment by BansheePrime** [comment]
> Are you downloading the inventree docker image pre-built from dockerhub, or building yourself from source?

I'm working with cloned git.

**Comment by SchrodingersGat** [comment]
Looks like the alpine base image has been changed and the `ttf-ubuntu-font-family` package is no longer valid. Will have to look into this some more.
