### ISSUE TITLE
changing base currency

### ISSUE THREAD

**Issue by irameez** [inventree/InvenTree#1756]
default and base currency is set to USD, is there a way to change this so that it shows a different currency in part details and sales orders.
Thanks.

**Comment by matmair** [comment]
@irameez if you run the latest version from master (which I generally do not recommend, I always deploy the latest release) there is setting in settings->currencies for that. Previously this was set in the config.yml

**Comment by irameez** [comment]
I am running the latest version but for some reason I can't seem to find the option, can you please share a screenshot.

**Comment by matmair** [comment]
![grafik](https://user-images.githubusercontent.com/66015116/124363483-c159c880-dc3b-11eb-8db4-e9bfa4f930e7.png)

**Comment by irameez** [comment]
thank you so much, I somehow missed that small button :)
