### ISSUE TITLE
Label printing limitations and Manufacturer’s part number (MPN) issues

### ISSUE THREAD

**Issue by Oakman-Dev** [inventree/InvenTree#1762]
Below are some small suggestions that I found when using Ki-nTree to sort my Digi-Key components (not just SMD parts but fans etc.)

- **Suggestion**: Make manufacturer’s part number (MPN) a property of Parts/Part Details columns for easier navigation and searching
- **Suggestion**: Enable Part Parameters to be used for labels. It would be great to be able to call Part Parameters, value for example when creating labels. That way we can include more than just Part Details. (Found this to be an issue when using Ki-nTree and wanting to use manufacturer’s part number)
- **Suggestion**: Enable to Print labels directly to a network-attached label printer for faster inventory management. (Maybe with something like https://github.com/mbello/ezprinting)
- **Suggestion**: Add a page to the documentation of all the variables that can be called for example on a label (or throughout the entire system).

PS: Do you have a Patreon or similar for the project?
PPS: If you ever make an iOS app, I'd buy it in a heartbeat!

**Comment by eeintech** [comment]
> * **Suggestion**: Make manufacturer’s part number (MPN) a property of Parts/Part Details columns for easier navigation and searching

Using the search function, you can look up Manufacturer part numbers:
![image](https://user-images.githubusercontent.com/4020546/124645472-77522c00-de61-11eb-8b00-455edb5681d6.png)

Manufacturer details are abstracted from the "Part" it belongs too because you can have multiple Manufacturers for one "part" (common example: 1uF X5R 0603 6.3V capacitor)

> * **Suggestion**: Enable Part Parameters to be used for labels. It would be great to be able to call Part Parameters, value for example when creating labels. That way we can include more than just Part Details. (Found this to be an issue when using Ki-nTree and wanting to use manufacturer’s part number)

That sounds like a good suggestion, @SchrodingersGat is that doable?

> * **Suggestion**: Enable to Print labels directly to a network-attached label printer for faster inventory management. (Maybe with something like https://github.com/mbello/ezprinting)

I'm curious, what label printer do you use? I have a Dymo LabelWriter 450 but it is only connected through USB which means the label needs to be downloaded before printed. I guess what you're suggesting is to remove the "downloading" step?

> * **Suggestion**: Add a page to the documentation of all the variables that can be called for example on a label (or throughout the entire system).

Have you already read [the doc for labels](https://inventree.readthedocs.io/en/latest/report/labels/)?

> PS: Do you have a Patreon or similar for the project?

I think @SchrodingersGat still receives Paypal donation? https://inventree.readthedocs.io/en/latest/contribute/#donate

**Comment by SchrodingersGat** [comment]
@Oakman-Dev thanks for your suggestions here! Adding parameters to the parts (with "name" lookup e.g. `part.parameters.length`) should be pretty simple to do!

No patreon at the moment, but the link @eeintech shared above does allow donations via PayPal (which are very gratefully accepted!)

**Comment by Oakman-Dev** [comment]
That's great @SchrodingersGat , thank you! I'd love the be able to print labels with saved barcodes, manufacturer part numbers etc, to make "offline" searching and also make it cross-system compatible. 

@eeintech I'm using the same Dymo LabelWriter 450 as you with a small Pi Zero W as a CUPS server. The reason for wanting it on the interface would be that I could trigger a print from my phone or tablet browser and maybe in the future as part of the mobile app without having to deal with system dialogs and drivers etc.

Regarding the parameters for labels, I can't find any documentation that points to how I can use any of the Item parameters (not details), when printing a label. When using your amazing Ki-nTree plug-in, it would be great to for example be able to print a QR or EAN code that matches what the manufacturer has and/or their part number for say an MCU.

**Comment by SchrodingersGat** [comment]
@Oakman-Dev iOS app is now available! :)

**Comment by Oakman-Dev** [comment]
@SchrodingersGat Is there a way for me to use if if I've already bought the Android version?

**Comment by SchrodingersGat** [comment]
No sorry, the two apps are completely separate

**Comment by Oakman-Dev** [comment]
@SchrodingersGat No worries, I'll make sure to get the iOS version then as well. :) Btw, any news on printing labels directly from the app/platform (to a networked label printer) without having to go through a printing menu etc?

**Comment by eeintech** [comment]
@Oakman-Dev You may want to open a "feature request" issue for this :wink:

**Comment by SchrodingersGat** [comment]
@Oakman-Dev definitely open a new issue for this feature :)
