### ISSUE TITLE
`Uncaught TypeError: row.supplier_part_detail is undefined`

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#1764]
Hi,

Recently I fell in love with this project because it is so well updated and seemed the perfect solution to my troubles. Recently I got some more parts and I'm now trying to get InvenTree in the middle of my workflow. 

Adding parts works perfectly and adding suppliers for the parts works amazingly too. However, when I'm adding stock and a part has an assigned supplier, the whole stock list doesn't load. It keeps saying `Loading data...`. 

Steps to reproduce:
1. I import a lot of parts from a CSV that I hand crafted to fit this project.
2. After importing, I go to suppliers and add a part to the specified supplier.
3. (Maybe of importance) I supply all parts with SKU '0' because I'm currently unable to supply all SKU's for the parts.
4. The parts show up in the Parts tab and in the list of Supplier Parts.
5. When I browse to the stock tab and add stock to the specific part, it reloads the page but is unable to stop `Loading the data...`

After some investigation I found an error in the JavaScript console. This is the log:
```
Uncaught TypeError: row.supplier_part_detail is undefined
    formatter http://127.0.0.1:8000/dynamic/stock.js:721
    calculateObjectValue http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:3558
    initRow http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:5498
    initRow http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:5409
    initRow http://127.0.0.1:8000/static/bootstrap-table/extensions/treegrid/bootstrap-table-treegrid.js:1171
    initBody http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:5597
    initBody http://127.0.0.1:8000/static/bootstrap-table/extensions/group-by-v2/bootstrap-table-group-by.js:1405
    initBody http://127.0.0.1:8000/static/bootstrap-table/extensions/filter-control/bootstrap-table-filter-control.js:2819
    initBody http://127.0.0.1:8000/static/bootstrap-table/extensions/treegrid/bootstrap-table-treegrid.js:1107
    initBody http://127.0.0.1:8000/static/bootstrap-table/extensions/custom-view/bootstrap-table-custom-view.js:1217
    load http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:6372
    success http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:5850
    jQuery 6
    initServer http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:5886
    init http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:3977
    init http://127.0.0.1:8000/static/bootstrap-table/extensions/filter-control/bootstrap-table-filter-control.js:2803
    init http://127.0.0.1:8000/static/bootstrap-table/extensions/treegrid/bootstrap-table-treegrid.js:1059
    init http://127.0.0.1:8000/static/bootstrap-table/extensions/custom-view/bootstrap-table-custom-view.js:1187
    bootstrapTable http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:7386
    jQuery 2
    bootstrapTable http://127.0.0.1:8000/static/bootstrap-table/bootstrap-table.js:7361
    inventreeTable http://127.0.0.1:8000/dynamic/tables.js:215
    loadStockTable http://127.0.0.1:8000/dynamic/stock.js:366
    <anonymous> http://127.0.0.1:8000/stock/:791
    jQuery 13
```

To me it seems that it's trying to read a row from the database but the field does not exist. 
`row.supplier_part_detail is undefined` says to me that maybe you previously used a different name for the variable or it changed across versions. 

Is there a way for me to make it work? **The item stock does show up in the Admin panel when I browse to the admin page and click on Stock Items -> Change**

I'm running Linux Mint 20.04 with Firefox updated to the latest version. InvenTree's `version.py` reports: 
```
INVENTREE_SW_VERSION = "0.2.5 pre"
INVENTREE_API_VERSION = 7
```

Any additional information requested will be provided as I'm not sure which is relevant at the moment. I'm a developer too but the source code is currently too big for me to look into this seemingly small issue.

Thanks a lot for the project, I'm really enjoying it anyway. It's just this issue makes it currently unusable to me.

**Comment by Guusggg** [comment]
My bad, I just updated to the latest source code after seeing the pull request and everything is functional again.

Thanks a lot for maintaining this project so decently!

**Comment by eeintech** [comment]
@Guusggg No problem, I noticed this issue yesterday :smile:
