### ISSUE TITLE
Importing with part parameters

### ISSUE THREAD

**Issue by stijnloeys** [inventree/InvenTree#1765]
Dear,

Is it possible to import a datasheet from excel, with the right headers as said in the documentation of inventree, but also with their part parameters? 
And if this is possible, is it also possible to do this as a normal user, and not as an admin?

Kind regards

**Comment by eeintech** [comment]
Hi @stijnloeys 

It is **only** currently possible to import part parameters using the Admin section or the [InvenTree Python API](https://github.com/inventree/inventree-python).

This could be a good feature, the little tricky side is to decide if from this import the part parameters templates are created automatically or not.

**Comment by eeintech** [comment]
@stijnloeys Forgot to mention that you can also use the part import feature directy in the UI :+1: 

1. Enable it in settings:

![image](https://user-images.githubusercontent.com/4020546/129577054-6ceabbd5-78e2-419e-b111-7ab560c17e24.png)

2. Use it directly in part view, see "Import Parts" tab:

![image](https://user-images.githubusercontent.com/4020546/129577223-e9e72b9c-3868-469b-9c4a-f0870fd4128a.png)

**Comment by eeintech** [comment]
Closing for now, let us know if you encounter any issue with the options mentioned above
