### ISSUE TITLE
Problems linking with Digikey-API

### ISSUE THREAD

**Issue by Randomtyper23** [inventree/InvenTree#1766]
Hey all,

Are there any known problems with the linking of the program with the digikey-API? The installation succeeded on my PC, but when i enter the client and secret i get from following the video posted about the digikey API, i get an error (401) saying the clientID is invalid...
Does anyone know how to fix this? 

Kind regards

**Comment by eeintech** [comment]
@Randomtyper23 Are you referring to this API: https://github.com/peeter123/digikey-api

If yes, you'd be better opening an issue on this repository instead of here :)

**Comment by Randomtyper23** [comment]
Ah no sorry, I was referring to the ki-ntree application :) I followed their tutorial but keep getting an invalid error with the clientKey.. But I'll ask there thanks :)

**Comment by eeintech** [comment]
@Randomtyper23 Ok please close this issue and open an issue here: https://github.com/sparkmicro/Ki-nTree/issues
And I'll respond :smiley:
