### ISSUE TITLE
Docker:  select2 doesn't make it into static

### ISSUE THREAD

**Issue by rcludwick** [inventree/InvenTree#1767]
Not sure why, but select2 exists in InvenTree/InvenTree/static, but isn't copied over to /home/inventree/static.

This appears to prevent submitting via form, and makes various errors in the developers console.

Manually copying it over seems to make it work okay.

**Comment by SchrodingersGat** [comment]
The entire /select2 directory?

**Comment by SchrodingersGat** [comment]
I just tried this on a "fresh" docker build (had to clean out the docker image cache a few times to get it to work properly).

Running from inside the docker image:

![image](https://user-images.githubusercontent.com/10080325/124941679-56026300-e04e-11eb-8c52-6110e6f30470.png)

![image](https://user-images.githubusercontent.com/10080325/124941791-6a466000-e04e-11eb-8c23-df615b0e7343.png)

**Comment by rcludwick** [comment]
Yeah.  Collectstatic doesn't appear to be working.... Not sure why.

**Comment by SchrodingersGat** [comment]
What do you get in the "collected" static directory?

**Comment by rcludwick** [comment]
Ahhh..... my fault.  Thanks for helping anyway.  It's working as expected.
