### ISSUE TITLE
Feature Request - Part Label

### ISSUE THREAD

**Issue by watarat** [inventree/InvenTree#1769]
I would find it very useful to be able to print labels for a PART (as distinct from STOCK).
I can see that there is partial support for that - the option to print a part label is in the GUI but there doesn't seem to be a back end for it ??

Use case for me - is that if I don't have any stock of an item - I am unable to utilise the App scan function.
So - typically for me - when I receive new parts - or am simply replenishing parts I've run out of - it would be useful to have a barcode to scan. (This could be either on an empty bag, or placeholder card - in the appropriate stock location.)
(Guess I am sort of thinking of the PART as being the parent of STOCK, and in the event of no stock - I can use the parent as an identifier)

So then when an order comes in - I can just scan the bag/card and add stock.
(Not sure if that functionality is within the App yet - given there are no stock labels to scan).

Rationale for this goes along the line of..
If I run out of something - say 1k resistors - if I go looking in the logical place (Resistor Box) - then there is nothing there - oops - maybe they are somewhere else - or put back out of order - better rifle through the whole box, look elsewhere. etc.
So I prefer to have something to mark that they are supposed to be there. i.e. I prefer to find an empty bag (with a label)- rather than find nothing ;)

R

**Comment by SchrodingersGat** [comment]
A "part label" mechanism makes sense and is not very difficult to implement with the current framework. The additional functionality that you mention (e.g. automatically re-ordering stock) would be a bit more difficult.

For now I'm happy to implement a "part label" feature and go from there.

**Comment by watarat** [comment]
Must admit to being a pretty basic user, and for a lot of parts I don't do full tracking of supplier/order etc - my envisaged usage would be something like.
1. Notice Stock low (or use last part)
2. Order in more without any Inventree input.
3. When part arrives, scan the new PART LABEL and simply do an " Add Stock".
At present - that works fine so long as there is existing stock - I can get to Add Stock, via the App by doing
Part -> Stock -> (Select Stock) -> Actions -> Add Stock.
If there is no stock - I cant get past Stock -> No Stock Found.

**Upon reflection** - perhaps my problem can be addressed by not selecting "Delete on Deplete" when creating the original part.
- that way the item will remain when qty goes to zero.  (Simples really!!)
Probably have answered my own question 😂

Thus the printed Stock Label is perhaps not needed?
(Just did a quick test - and above solves my problem)
Thanks awefully for your willing response !!

**Comment by SchrodingersGat** [comment]
Part labels have been implemented in https://github.com/inventree/InvenTree/pull/1776

**Comment by watarat** [comment]
Hi Oliver,  Feedback:
Thanks for implementing this - works a treat!!
Have implemented own format labels for parts (no issues) and are actually very handy! 😛
Rich.
