### ISSUE TITLE
Feature: Add installed stock items after build creation

### ISSUE THREAD

**Issue by reilly-callaway** [inventree/InvenTree#1770]
Include an "Add stock item" button to the install stock items tab for a stock item.

Currently installed stock items can only be added whilst in production through a build order. Would be beneficial to be added after production as well.

**Comment by wolffam** [comment]
@SchrodingersGat , 
Wasn't this a feature in the past? https://github.com/inventree/InvenTree/issues/977
Did it removed purposefully and/or can it be added back?

**Comment by eeintech** [comment]
@reilly-callaway Your original question is a bit confusing, do you expect a "Add Stock Item" button somewhere on the build order page? Where exactly?

@wolffam Are you saying you would like to link a stock item to a build order, using the "Build Outputs" tab of the build order page?

**Comment by wolffam** [comment]
Ideally (and I am pretty sure this feature existed at one point) we would be able to take an assembly stock item that is the result of a build and "uninstall" a stock item component from that assembly and "install" a replacement stock item component.  Let me know if that can use any further clarification.  I'd prefer not to fall back to an older version of the software if I can avoid it

**Comment by eeintech** [comment]
@wolffam No need to fallback, this was unintentionally skipped during the build order revamp @SchrodingersGat did a few months back, it will be added again.

I'm still not quite sure to grab your feature request, neither the one from the OP...

If you could add screenshots to what you expect that'd be better, or if @SchrodingersGat or @matmair know what are you referring to, then nevermind!

**Comment by wolffam** [comment]
@eeintech , are you asking me for some further clarification? If so, I'd be happy to provide it.
I can also make a new issue if you feel this is separate from the OP's request.

**Comment by matmair** [comment]
@wolffam I think this issue is fine.
So TLDR: You want the button to add /edit the stock items installed in a stock item? Technically I do not see problems, as far as I remember this was lost during a refactor as @eeintech said.
Do you fell confident enough to implement it yourself? Please be advised we got a new forms API (for example see the sales order forms) which generates builds client-side - implementing the new function this way would be preferred.

**Comment by wolffam** [comment]
That is correct @matmair (in terms of the feature).  We have finished assemblies that we sometimes need to replace a specific part in and therefore need the feature for "hotswapping" stock items in an assembly stock item.

I will not be able to implement it myself without a fair bit of hand holding unfortunately. I had done some poking around in the codebase last year but haven't looked at it in a long while and am a django newbie to top it off

**Comment by SchrodingersGat** [comment]
@wolffam yes this feature did exist, and has been lost! It will be restored soon...

The idea of swapping out particular installed items is definitely a feature I wish to keep supporting.

**Comment by wolffam** [comment]
@SchrodingersGat , can I aid in helping fix this bug in any way?  Our workflow is dead in the water without it so I would be happy to dig into something if it helps.

**Comment by matmair** [comment]
@wolffam maybe try implementing it and submit a PR; often is the fastest way. If you get stuck just submit what you have as a draft PR so others can help.

**Comment by SchrodingersGat** [comment]
@wolffam happy for you to submit a PR - I'm too busy to look at it myself right now.

**Comment by eeintech** [comment]
@wolffam Check out #1892 and let me know if it's missing something :wink:
