### ISSUE TITLE
Error attempting to delete stock item

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1784]
![image](https://user-images.githubusercontent.com/10080325/125014839-b8d91600-e0b1-11eb-95ab-4f0676ff881b.png)

**Comment by eeintech** [comment]
@SchrodingersGat I cannot reproduce it, any special condition for this to happen?

**Comment by SchrodingersGat** [comment]
I have not yet managed to replicate - this error screenshot was sent to me by a coworker

**Comment by eeintech** [comment]
@SchrodingersGat Ever found out the condition?

**Comment by SchrodingersGat** [comment]
Not precisely - it was something to do with the "notes" field being improperly applied. In any case it was good motivation to finally consolidate the stock adjustment functionality.
