### ISSUE TITLE
select2-bootstrap.css filled with html code

### ISSUE THREAD

**Issue by chrisnoisel** [inventree/InvenTree#1803]
My css knowledge is out of touch by today's standard but it seems [select2-bootstrap.css](https://github.com/inventree/InvenTree/blob/master/InvenTree/InvenTree/static/select2/css/select2-bootstrap.css) content got erased with something else.

**Comment by SchrodingersGat** [comment]
Uhhh. yeah.. Thanks for picking this up @chrisnoisel  that's a very strange one!
