### ISSUE TITLE
Admin interface can be super slow

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1809]
Some pages on the admin interface takes ages (like, 10 seconds) to render.. 

Need to profile them to work out where the inefficiencies are.

**Comment by SchrodingersGat** [comment]
For example the admin page for a "purchase order" is extremely slow to load.

**Comment by eeintech** [comment]
I've noticed that too, thought it was my setup 😬

**Comment by SchrodingersGat** [comment]
Might be something that the django-debug-toolbar plugin can help us debug..

**Comment by eeintech** [comment]
:thinking: Umm what?

![image](https://user-images.githubusercontent.com/4020546/125469676-658800ca-bbd0-4873-9fd9-f72038ff9e33.png)

**Comment by eeintech** [comment]
Removed the inline items:

![image](https://user-images.githubusercontent.com/4020546/125476155-3eab8d9c-1d49-4354-8a0d-6506e7312714.png)

**Comment by eeintech** [comment]
@SchrodingersGat The bottleneck was in the `SupplierPart` model related queries, this boy is a very expensive database hit if not prefetched. I think #1812 alleviates this problem, at least for purchase order details (works nicely for me now).
