### ISSUE TITLE
Too much CPU usage of inventree-server docker container

### ISSUE THREAD

**Issue by Nobodi99** [inventree/InvenTree#1814]
Hello,

I tried to set up an inventree instance with docker on my Raspberry Pi 3b.
After following the guide for the production deployment I got it to run once.

Now whenever I try to start it the container starts to hog a lot of CPU power.
At some points up to 350%...
![grafik](https://user-images.githubusercontent.com/39123731/125620660-1fc94ae3-7743-4418-98ee-96f07758f43e.png)

When looking at the logs at that time it seems to start a lot of workers at that moment.

![grafik](https://user-images.githubusercontent.com/39123731/125620649-4badc982-0273-4262-b3ff-5a935f23cbad.png)

The usage will fluctuate between 80% and 350% and never really going down at all.

Also this is repeating a lot in the docker log:
![grafik](https://user-images.githubusercontent.com/39123731/125621116-d7438e58-cea9-4ee9-9beb-fc7c24f74c3d.png)

Is there anything I'm missing?

My docker-compose file looks nearly identical to the one in the docs.

The only changes I made are user/password for the db and using the macvlan network I use for all my containers to give each container a unique network IP.

It basically just looks liked this:
`networks:
      home_net:
        ipv4_address: 192.168.178.XXX
`

Did anybody have similar problems and fixed them?
I can't really see any reason why the CPU usage should be that high at all. 

Would really appreciate some help in this case...

**Comment by SchrodingersGat** [comment]
Both the server and background-worker processes will spawn multiple worker threads -> this is expected!

Not sure why it's taking so much CPU though. I'll try to spin up a docker instance and see if I can reproduce.

What is the CPU usage when the process is running well after boot-up?

**Comment by Nobodi99** [comment]
Thanks for the reply.
Sadly I can't even get it to run properly on the pi.

Today I decided to just set up an instance of inventree on my ubuntu notebook to test some things.
Here I found the cause of my problems.
The high CPU usage is probably because it uses multiple cores. So that is fine.
The real problem I have is the RAM usage.
A fully working, newly deployed container (server) uses about 1.1 - 1.2 GB of memory.
The worker needs araound 150-200 MB.
My pi only has 1GB so that's why it doesn't work for me.

In that regard I do question that amount. For a "simple" web application >1GB of memory usage is quite a lot.

**Comment by eeintech** [comment]
It seems weird to me that there are 9 workers spun out, a couple should be enough.

We're not even using workers in our team instances and everything works great, you may want to try it out without them too.

**Comment by lookme2** [comment]
@eeintech I hate to say this but I can't even figure out how to start the workers.

**Comment by SchrodingersGat** [comment]
@Nobodi99 the CPU and RAM resource consumption does seem wrong. Is the server actually working, can you access the webpage?

**Comment by Nobodi99** [comment]
@SchrodingersGat  Yes I can access the webpage when I host it on my laptop. The only problem I have there is that I can't seem to load any of the static ressources. I get a lot of MIME-type errors for them.

![grafik](https://user-images.githubusercontent.com/39123731/126301385-c979463f-4b52-4c4c-aa70-1caff4141a7b.png)


@eeintech WHat do you mean without the workers? I don't see any possibillity to control the number of workers the container starts internaly. They just start on their own inside the server container.

**Comment by eeintech** [comment]
@Nobodi99 Did you install using docker? I was referring to manual install sorry.

**Comment by Nobodi99** [comment]
@eeintech Yes. Because I have a few other things hosted on a raspberry pi docker is the easiest and most organized way for me to host everything. 

@SchrodingersGat Maybe you can implement an environment variable which limits the number of workers in the container? [This inventree container](https://github.com/Zeigren/inventree-docker) by Zeigren imlements that. With that it saves a ton of memory depending on the number of workers.

**Comment by SchrodingersGat** [comment]
@Nobodi99 good idea - see https://github.com/inventree/InvenTree/pull/1879

**Comment by Nobodi99** [comment]
@SchrodingersGat That's a really good addition and I believe it fixes this issue. At least during the startup process of the container it uses way less ressources now when I limit the number of workers.

There is just one tiny problem. The container can't start completely because the logging function in the gunicorf.conf.py is broken.

![grafik](https://user-images.githubusercontent.com/39123731/127490189-b817cddd-3fcc-44d7-8b9f-002cb4ce2fb9.png)

This happens because raspbian uses an older version instead of python 3.8.
So maybe have a look if that line is actually necessary? I'm not that good with python tbh.

Regarding the MIME thing I posted about, I will create a new issue for that.

**Comment by SchrodingersGat** [comment]
@Nobodi99 silly typo on my part - see fix here: https://github.com/inventree/InvenTree/pull/1884
