### ISSUE TITLE
Uploading BOM's 

### ISSUE THREAD

**Issue by stijnloeys** [inventree/InvenTree#1816]
Hey all, 

I tried to upload a BOM list for a product in my inventory list, but i keep getting the "wrong dimension" error. Does anyone know how to solve this? I followed your template and also made a BOM list via the site itself, then downloaded it, removed it and then reuploaded it, but it kept saying "wrong dimension".

Thanks in advance

**Comment by SchrodingersGat** [comment]
Can you please provide the full error message?

**Comment by stijnloeys** [comment]
![error](https://user-images.githubusercontent.com/42654949/125789933-eab8ac7d-d264-4ce1-8136-842531abcd3c.PNG)

I upload this (as a csv):
[BOM1.xlsx](https://github.com/inventree/InvenTree/files/6823135/BOM1.xlsx)

**Comment by eeintech** [comment]
@stijnloeys I don't have any problem with your file:

![image](https://user-images.githubusercontent.com/4020546/125807122-484660eb-1f52-42d9-a65b-a495f3992e37.png)

What do you mean by `I upload this (as a csv)`? This is a Excel worksheet (not CSV) and the extension is automatically processed when picking up the file.

**Comment by StijnLoeys1999** [comment]
Sorry, there were some errors in the uploading, For some reason Inventree did not want to accept the "#" part in the name, such that the part was not in the database, when i fixed that it was ok
