### ISSUE TITLE
Category / Stock location selector usability

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1827]
I can't say for everyone but for me new double-line selector is inferior to the previous one.
New one is just name sorted while previous was tree based which is more logical and suitable for tree structures.
At the same time it looks very nice for plain tables like suppliers or manufacturers (tiny logos are cute).

Please consider returning to the old selector in parts and stock items.

**Comment by SchrodingersGat** [comment]
@sintech can you please share a screenshot of the particular form you're talking about?

**Comment by sintech** [comment]
My bad, that's what I'm talking about:

- New, only three rows at once:
![category_new](https://user-images.githubusercontent.com/10057327/126059452-491f7a60-3e10-4f57-9b81-a96042cc0b72.png)

- Old (from admin, but it looked the same on site):
![category_old](https://user-images.githubusercontent.com/10057327/126059463-8f7e689a-7d49-446c-a44e-b5ad607f8a33.png)
I would add some space around '/' but anyway it is better than new one.

**Comment by SchrodingersGat** [comment]
Ah I see. I've made an improvement in #1833, certainly ordering the results in a "tree" fashion makes a lot of sense.
