### ISSUE TITLE
Can't create supplier/manufacturer from "Create new Supplier Part" dialog

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1830]
Steps to reproduce:
- Open any part
- Switch to "Suppliers" tab
- Click "New Supplier Part"
- Click "New Supplier" or "New Manufacturer"
ER: Create new supplier modal is opened
AR: `Error requesting form data`

![изображение](https://user-images.githubusercontent.com/10057327/126060067-f26746b6-fa1a-4e94-af13-78b81e3d6e29.png)

**Comment by SchrodingersGat** [comment]
@sintech thanks for reporting this. Looks like a bug related to the new method of dealing with forms, which has not been carried across to *all* forms (yet).
