### ISSUE TITLE
Part BOM is not displayed

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1837]
I have an "Assembly" part with BOM items.
After the last couple of inventree updates I noticed that BOM table is empty.
BOM is still there according to database, I even see part images are loaded in browser dev tools but it is not displayed.
I see BOM items in Prices tab.

![изображение](https://user-images.githubusercontent.com/10057327/126070177-817e858c-ac92-448c-be7d-3d6d31710fc4.png)

**Comment by SchrodingersGat** [comment]
It looks like the bom table is not loading. Can you look in the "console" tab of the browser tools to see if there is an error?

![image](https://user-images.githubusercontent.com/10080325/126070442-67a4c774-634b-4de5-9a3c-4852fd1c0b19.png)

**Comment by sintech** [comment]
![изображение](https://user-images.githubusercontent.com/10057327/126071320-31622d1a-91df-48d2-b81e-04e971fa2c52.png)
Sorry for error in russian, I don't know how to switch it to english.

**Comment by murych** [comment]
got the same issue today:
```
unreachable code after return statement forms.js:1095:16
```

my inventree instance version info:
```
# Version Information:
InvenTree-Version: 0.3.0
Django Version: 3.2.4
Commit Hash: 5ce6dd3
Commit Date: 2021-07-16
Database: postgresql
Debug-Mode: True
Deployed using Docker: True
```

![image](https://user-images.githubusercontent.com/3063817/126071626-1187d859-4edc-4972-a217-238c729700f3.png)

**Comment by SchrodingersGat** [comment]
The part menus recently got updated - can you try doing a hard refresh of the browser? `Ctrl`+`Shift`+`R` or `Ctrl`+`F5`.

I'm not seeing the same issue here on top of latest master.

**Comment by murych** [comment]
Updated to `master` branch, now BOM parts are displayed. Thanks for quick fix!
