### ISSUE TITLE
[BUG] Alignment issues in part grid view

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1848]
When displaying parts in grid view, the grid cell height does not expand to fill the available space:

Someone with more advanced CSS knowledge would be able to fix this in a jiffy, I'm sure.

![image](https://user-images.githubusercontent.com/10080325/126236973-203001ad-7a22-4762-9232-366194896e84.png)

**Comment by matmair** [comment]
This was closed with #2068
