### ISSUE TITLE
Stock table is not updated when stock item is deleted

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1865]
Steps to reproduce:
1. Open part stock
2. Select stock item in table
3. Click `Delete stock` in dropdown menu
4. Switch `Confirm stock adjustment`, press `Submit`

ER: Table with updated list of items
AR: Table contents stays the same

WA: Reload page.

**Comment by eeintech** [comment]
That sounds right, it's funny that "Remove Stock" actually refreshes the page correctly :confused: 

Unrelated but that's what removing the full stock on a stock item marked as "delete on deplete" :grimacing: 

![image](https://user-images.githubusercontent.com/4020546/127060303-ded604ba-65cf-4515-915d-1dd8c635d80b.png)

Hopefully will be fixed soon!

**Comment by SchrodingersGat** [comment]
@sintech should be fixed now.

@eeintech can you please raise an issue for the separate error?

**Comment by eeintech** [comment]
@SchrodingersGat Sure, or I'll fix it myself 😉
