### ISSUE TITLE
Sidebar menu in Part view is not working anymore

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#1881]
Hi, 

Today I updated to v0.4.0 which brings features that I really like, nice work guys!
After updating however, the Part view's sidebar does not work anymore.

I click on Bill of Materials, and the URL changes to `/part/105/`**#**`/` and jumps to the top, but the view does not switch.
It's not a big problem at all, as the whole information is still possible to access by scrolling down.

Thank you for the great work!

**Comment by matmair** [comment]
Hi @Guusggg did you force-refresh your browser-window after updating? A lot JS changed so old cached files might be a problem.

**Comment by Guusggg** [comment]
Oh my... Thank you, you solved it! I always refresh with CTRL+R thinking it automatically clears the cache but after some trying I found CTRL+SHIFT+R to be clearing the cache and refreshing.
