### ISSUE TITLE
Android Application pull requests

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#1882]
Hi,

I thank you a lot for this project. It is truly awesome already at such a fast pace. I also really like the mobile App.

I'm a software engineer that uses this software for a company of a friend of mine and I chose it specifically because it's open source so I can edit things that make sense for him. However, as you guys are working so hard on it, I want to spend company time on the project. However I think the website is already very well made, but the app is lacking features. 

I have experience in Android development so I would like to create pull requests for some simple stuff (All components of the functionality is there, I just need to send a few API calls probably) like adding new items to storage and taking pictures of the products.

Is there any way for me to contribute to the app? I'm also considering a bounty for some features.

**Comment by matmair** [comment]
@Guusggg the app is a closed source project by @SchrodingersGat (who is the maintainer of this project) so you have to consult with him on this topic.
There are a lot tasks open for the core app though :-)

**Comment by Guusggg** [comment]
I understand, and I can imagine why. I'll try to consult with him on this matter!

**Comment by SchrodingersGat** [comment]
@Guusggg I'm guessing it was you who submitted this feature request via the app earlier today? The app has had a major overhaul (to the internals) recently, mostly after https://github.com/inventree/InvenTree/pull/1716 was implemented. The API now is pretty much fully "self defined" so integration of new forms / fields into the app is a breeze.

I'm open to accepting contributions or bounties for new app features. I think that the app is (or will be) a feature which really sets InvenTree apart from other similar projects! Let me know if you do want to contribute or sponsor a particular feature!

Oh and I'm super excited that you like the project so much!

**Comment by Guusggg** [comment]
@SchrodingersGat I prefer to contribute my time over contributing money as I assume you are pretty busy, looking at all the commits and issue responses. 

I'm just in love with this project because it allows me to see the strength of Open Source, especially in an industry that is dominated by closed source, proprietary software that is way too expensive for what it really is. To me, its simple enough to understand to just get started (once you have someone with the technical know-how on how to deploy) and its already pretty powerful so I'm really curious to see what will be next year!

Just let me know what you think works for you in regards to contributing. 
At first I would just look at expanding the barcode scanning feature (When an unknown barcode gets scanned, I want to add options to add it to storage or assign it to a product or do nothing, so a little choice menu pops up instead of an error) and I want to look into uploading images by taking a picture (I think taking a picture is already pretty easy using Android API's and uploading them to the server is probably also a fixed issue as you can do it in web already now)

**Comment by SchrodingersGat** [comment]
> and I want to look into uploading images by taking a picture (I think taking a picture is already pretty easy using Android API's and uploading them to the server is probably also a fixed issue as you can do it in web already now)

This feature was actually recently added - you can long-press on the image of a part to upload a new image either from the gallery or camera.  It just hasn't made it into the docs yet  ;)

The app is developed using flutter - I'm assuming you're familiar?

**Comment by Guusggg** [comment]
Damn, that camera feature is amazing! Just tested it out, works perfect. 

I'm not super familiar with Flutter, I have to admit, but I'm not really too scared. I'm reading a bit about it in the docs and it seems straight forward. I haven't programmed in Dart before but I have experience in all kinds of languages ranging from JavaScript to Java along with Python, C, C++ and Rust. Even a small bit of Haskell. I just read with the language docs in hand and will figure it out
