### ISSUE TITLE
MIME conflict with static files when changing Debug to "False" in config

### ISSUE THREAD

**Issue by Nobodi99** [inventree/InvenTree#1883]
So when I run inventree in a container I get following errors in the console of my browser.

![grafik](https://user-images.githubusercontent.com/39123731/127495328-2a20ddc8-8491-4aab-a31c-fc8dedd00b1a.png)

This happens because I changed the config file to Debug=false instead of true and this will prevent Django from serving the static files by itself.

See [the offical documentation](https://docs.djangoproject.com/en/3.2/howto/static-files/) for that. There is also a link on there to the documentation about serving static fiels in Production.

I believe it makes sense to tackle this issue. Running a production instance with a potentially insecure way of serving files may not be optimal.

**Comment by Nobodi99** [comment]
Just saw it being mentioned in the documentation. Should probably just be referenced on the docker production setup page tbh

**Comment by SchrodingersGat** [comment]
Good point @Nobodi99 I've added a note in the docs
