### ISSUE TITLE
Unable to print labels after Docker version 0.4.1

### ISSUE THREAD

**Issue by lettore** [inventree/InvenTree#1903]
Using the image inventree/inventree:0.4.2 I get the following error when I try to print a label.

<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AttributeError at /api/label/stock/1/print/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">module 'weasyprint' has no attribute 'fonts'</pre>

Request Method: | GET
-- | --
http://example.com/api/label/stock/1/print/?items[]=1&
3.2.4
AttributeError
module 'weasyprint' has no attribute 'fonts'
/usr/lib/python3.8/site-packages/django_weasyprint/views.py, line 52, in get_font_config
/usr/bin/python3
3.8.10
['/home/inventree/InvenTree',  '/usr/bin',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/usr/lib/python3.8/site-packages',  '/usr/lib/python3.8/site-packages/odf',  '/usr/lib/python3.8/site-packages/odf',  '/usr/lib/python3.8/site-packages/odf',  '/usr/lib/python3.8/site-packages/odf',  '/usr/lib/python3.8/site-packages/odf',  '/usr/lib/python3.8/site-packages/odf',  '/usr/lib/python3.8/site-packages/odf']
Wed, 04 Aug 2021 11:37:01 +0000

</body>
</html>

**Comment by SchrodingersGat** [comment]
@lettore can you confirm that printing *does* work for docker image `inventree:0.4.1`?

**Comment by lettore** [comment]
Yes I'm using that image now and print is working.

Il Mer 4 Ago 2021, 13:54 Oliver ***@***.***> ha scritto:

**Comment by SchrodingersGat** [comment]
Can you please run a test for me: 

In your `0.4.1` instance, open a CLI and run `pip list` and provide the output here

Then, do the same for `0.4.2`

I cannot at this point reproduce the error on my end. Might be related to installed packages?

**Comment by SchrodingersGat** [comment]
Ah, looks like new version of weasyprint was released that breaks compatibility.
