### ISSUE TITLE
Print label command prompt to save PDF instead of directly open Print dialog

### ISSUE THREAD

**Issue by lettore** [inventree/InvenTree#1910]
Hi,
this is a feature request, at the moment when I want to print a label I'm prompted to save the PDF file, and the files build up in the download folder.
Instead it should be open the print dialog for directly print the label, or at least open the PDF file in another tab.

**Comment by SchrodingersGat** [comment]
Unless I'm misunderstanding your question - isn't this covered by your internet browser settings? You should be able to specify whether the PDF file is opened by the browser or downloaded to your PC.

**Comment by lettore** [comment]
The default behaviour in Chrome is to display PDF files in the browser.
This works unless your code explicitly wants to save the file, and I think this is the case.
If this is a feature then there should be 2 buttons, one for print and one for download.
Are you able to print the label without saving the PDF on disk?

**Comment by sintech** [comment]
Looks like this behavior is controlled by "Content-Disposition" header.
If it set to "attachment", browser asks to save file, if set to "inline", browser displays pdf in the same tab.

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/128438929-8db1f6f3-da53-4c1a-88fe-6e6c8552fe5e.png)

![image](https://user-images.githubusercontent.com/10080325/128438946-bb786bc2-0568-4c3f-8143-af8f5918904a.png)

This is the behaviour I am seeing.

**Comment by lettore** [comment]
> Looks like this behavior is controlled by "Content-Disposition" header.
> If it set to "attachment", browser asks to save file, if set to "inline", browser displays pdf in the same tab.

It's true, to check if this is the case I added this extension https://chrome.google.com/webstore/detail/undisposition-racle-fork/bbppejejjfancffmhncgkhjdaikdgagc/related?hl=en to Chrome and magically the PDF now open in the browser without prompt for save.
For now it's a good workaround but it should be fixed in code, there's no need to have a prompt to save because the button is print label, and saving can be done from the PDF view page if needed.

**Comment by SchrodingersGat** [comment]
I have implemented this as a user-configurable option - https://github.com/inventree/InvenTree/pull/1920
