### ISSUE TITLE
Error:  Not showing Part table for one Category

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#1914]
Hey

I just updated to 4.3, which in the about still shows 4.3.  Anyway I have a Category that will not show the parts table.  I have attached a picture of the error.  Any ideas?
![Screenshot 2021-08-06 104950](https://user-images.githubusercontent.com/11365211/128537578-4de5ab5b-3d1e-41c8-9d1e-90c351657ce1.png)

**Comment by lookme2** [comment]
I found the problem.  I had a part parameter with the label "CCA#"  that was giving me the error.  I deleted that parameter and it now seems to work fine.  This might be a bug.

**Comment by matmair** [comment]
@lookme2 we need a bit more information to reproduce this:
- You can copy the version information in the about section
- Please provide us a text-version of that JS-error
- Please check the error logs in the admin-section - if there is an error also post it here

I can not reproduce the error, that why I am asking

**Comment by SchrodingersGat** [comment]
@lookme2 looks like there is a limitation in bootstrap-table filter extension. Simplest fix is to disallow special characters in template names - see https://github.com/inventree/InvenTree/pull/1917

**Comment by SchrodingersGat** [comment]
I'll deal with the version number mismatch too, thanks for pointing that out.
