### ISSUE TITLE
Internal price is not filtered by part

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1915]
Is this a normal behavior?
It looks like API call is missing `part` filter. So all parts have the same `Internal Cost` table.
![image](https://user-images.githubusercontent.com/10057327/128554895-e260548a-72fc-4b72-bbc9-6bb20f68cbd0.png)

![image](https://user-images.githubusercontent.com/10057327/128555122-911201c7-8a8a-415b-a2c2-324c7fc8cdcc.png)

**Comment by SchrodingersGat** [comment]
@matmair do you have time to have a look at this one?

**Comment by matmair** [comment]
@SchrodingersGat will do
