### ISSUE TITLE
Uncaught TypeError: selections.forEach is not a function

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1929]
When trying to print labels to multiple stock items at once, this is the JS error:

![image](https://user-images.githubusercontent.com/4020546/128777795-485fa05a-0ee7-494d-889b-4133e97c9641.png)

![image](https://user-images.githubusercontent.com/4020546/128777822-63b9a0cb-8439-4908-94af-e2c4f9316194.png)

EDIT: printing single label on each stock item works

**Comment by SchrodingersGat** [comment]
Are you running off the latest version? I can't seem to reproduce this.

**Comment by eeintech** [comment]
Oh it looks like it only happens on the parent stock item page, not on the part page.

@SchrodingersGat if you go on the parent stock item of your serialized item, can you reproduce?
I'm on master.

**Comment by SchrodingersGat** [comment]
Thanks @eeintech - fix provided in #1940

**Comment by eeintech** [comment]
Yup, looks good now. Thanks @SchrodingersGat
