### ISSUE TITLE
Link to external URL - Handle File URL

### ISSUE THREAD

**Issue by vk2avw** [inventree/InvenTree#1936]
Link to external URL doesn't accept a file based URL, for example:

file:///electronics/Data/RF_Transistors/BFG591.pdf

Gets a "Enter a valid URL." error.

Parts can be obsolete or their OEM is no longer in existence it can be necessary to store whatever materials that are associated with the part locally. It shouldn't be necessary to stand up a local webserver to access "local" files.

This is with a InvenTree docker container pulled at around 00:00 UTC Aug 10 2021.

**Comment by SchrodingersGat** [comment]
Interesting problem... As InvenTree is designed to be accessible separately to the server instance (and by multiple users) then pointing to "local" files would soon prevent issues.

I would suggest that you upload these files as attachments against a particular part. That way they do not get "lost" and any users can access them.

However if you *really* want to do this, you could allow the `file` URL scheme in your settings file:

https://github.com/inventree/InvenTree/blob/b92ec751effa579103a5cac02c7fb7ed12d0aea8/InvenTree/config_template.yaml#L139

**Comment by vk2avw** [comment]
Thanks for the prompt response and the suggestion, re: config_template.yaml. I will investigate how I get to it via the "docker" container. The system concerned is a "CentOS 6" system that will remain as it is for the moment. That is why the use of the docker container was the obvious "painless" choice for assessing InventTree.

Attachments may be useful, but I already have the files stashed in the local file system and it is useful to organise them that way
(e.g. to refer to them in "documents" and other ways).

Yes, understood that "local" files may not be available to all users in a system. But:

1. I am the only user of the instance of InvenTree as I intend it to use to organise my extensive hobbyists collection of electronic parts, and
2. If I was to using InvenTree in a production environment I would either: stand up a web server or use NFS/SMB "mounts/shares" to make the files available within the organisation.

Choice 2 is unlikely as I have retired from my position as a Systems Engineer and setting up a such a system is too much like work....

Thanks,
Stephen.

**Comment by SchrodingersGat** [comment]
No worries Stephen. Regarding docker - if you follow the [docker setup guide]https://inventree.readthedocs.io/en/latest/start/docker/) you will see how to expose the "data" directory to a volume on your OS. The config template file will be created in this directory and you can edit it there. Just make sure to restart the docker container after you edit the file.
