### ISSUE TITLE
Token authentication doesn't work for media files behind nginx proxy

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1937]
- nginx proxy redirects auth requests to `/auth/`
- when using token auth (e.g. python interface or app) server returns either `302` or `403`
- token is being checked, but *user information not being added to the request*
- also request is serviced *before* token is checked

**Comment by SchrodingersGat** [comment]
@lettore it took some doing but I have managed to reproduce your issue. I'm assuming you're running behind a nginx proxy, which is forwarding auth requests for media files to the inventree server.

There was a silly bug which prevented token-based auth from working. See #1938 for a fix which should be merged soon.

**Comment by lettore** [comment]
> @lettore it took some doing but I have managed to reproduce your issue. I'm assuming you're running behind a nginx proxy, which is forwarding auth requests for media files to the inventree server.
> 
> There was a silly bug which prevented token-based auth from working. See #1938 for a fix which should be merged soon.

Well I'm using the Ngnix proxy container as your docker compose file, in front of that I use Traefik as https proxy.
Not sure if this can be the problem.

**Comment by SchrodingersGat** [comment]
The issue is (I believe) on the server side - the token auth for `/media/` files is currently not working correctly

**Comment by SchrodingersGat** [comment]
Please pull down latest master and see if the problem is resolved on your end.

**Comment by lettore** [comment]
> Please pull down latest master and see if the problem is resolved on your end.

Solved

**Comment by SchrodingersGat** [comment]
Thanks for letting me know @lettore
