### ISSUE TITLE
github workflows without `apt-get update` will fail

### ISSUE THREAD

**Issue by markdedeuge** [inventree/InvenTree#1966]
Unless an apt-get update is run before the workflow, the workflow may (100% hit for me) fail. 
Fixed by #1949

**Comment by markdedeuge** [comment]
FYI issue

**Comment by SchrodingersGat** [comment]
@markdedeuge were you seeing these failures when trying to run the github workflows on your local machine?

**Comment by markdedeuge** [comment]
These were workflows running 'on github' as part of one of the docker PRs I had up. 
Its caused by the github images (ubuntu etc) having some older sources cached. So unless you update them, _certain_ packages will cause this issue. 
Some google-ing revealed that this problem is not new and has happened in the past. 

@SchrodingersGat i'll raise a PR today that sets the build images for each test to have a standard set of packages which should be easier to maintain.

**Comment by SchrodingersGat** [comment]
This does not seem to impact the CI builds, I'll let @markdedeuge re-open if they are keen but otherwise, close for now.
