### ISSUE TITLE
Assign a barcode to a Part/Supplier Part

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#1971]
Hi,

I'm thinking about implementing a feature that allows even more barcodes to identify parts. Seeing as we get a lot of Part's that have the same barcode, it might be awesome to allow a Part to be assigned a barcode in the same way that Stock Items can be assigned a barcode.

We have a lot of screws that arrive in small boxes with the same barcode for the same screw. I think it would be a great feature to be able to attach this barcode to a Part so we can scan the boxes when their empty and the system would be able to tell if we have more and where they are located. 

The issue that I imagine is that a Part is essentially a 'virtual' concept where a Part can be replaced by several variants, which probably messes up having several variants for a Part. Maybe we can alleviate this by being able to assign a barcode to a Supplier Part?

Please tell me what you think about this. Any feedback would be appreciated.

Kind regards,

**Comment by SchrodingersGat** [comment]
Yeah this makes a lot of sense. Most of the functionality is already in place for this:

- Parts already have internal unique barcodes
- Scanning a part's barcode on the app will launch the [Part Detail View](https://inventree.readthedocs.io/en/latest/app/part/#part-detail-view)

All that is required is the ability to assign a custom barcode to a *Part* in the same way you already can for a *Stock Item*.

**Comment by Guusggg** [comment]
I'm going to finish the Barcode scanning in the app and I will look into adding a field to the SupplierPart structure to add a barcode, and if it's already there I will focus on using the existing functionality to assign it to the part.

I'm personally thinking it's best to keep it at SupplierPart, since usually parts from the same supplier (that I know of) have the same barcode.

**Comment by BrettRD** [comment]
Could we also add external codes to storage locations?
I have a long-range RFID reader and matching tags on storage tubs; It would be amazing to be able to check-list a class-set of equipment and consumables into a van.

**Comment by matmair** [comment]
> Could we also add external codes to storage locations?
> I have a long-range RFID reader and matching tags on storage tubs; It would be amazing to be able to check-list a class-set of equipment and consumables into a van.
> 

Depends on how the reader interfaces. Could you provide a bit more information about the device and the workflow you envision?

**Comment by BrettRD** [comment]
I'd like to be able to write a module that keeps a checklist of storage tubs and equipment cases needed for a tutorial session or a remote task, and checks that a build order can be made using the parts contained in them.

I found a cheap ISO18000-6C compatible scanner (JRD-100) and I've written a Linux driver for it. (6m read range 50 tags/sec scan speed, half that for practical purposes).

The EPC tags it scans have some erasable memory, and not all tags have an erasable ID.

I'd like to be able to associate a tag ID to a storage location. The tag ID is a variable length byte array, typically 512B or less.

Similar requirements apply to every other RFID system, NFC has fixed IDs and erasable memory, 125KHz has fixed ID and no memory.  Ability to associate an external code with a storage location would make asset tracking more flexible

**Comment by SchrodingersGat** [comment]
@BrettRD we currently have the concept of a "UID" field for the [StockItem model](https://github.com/inventree/InvenTree/blob/2c889fbcffcdb899857ef351c322fb4785e80c92/InvenTree/stock/models.py#L444)

It would be a reasonably simple addition to implement a similar field for the `StockLocation` model, if that would suit your purpose. Still would need a way of interfacing the RFID reader into the database.

**Comment by matmair** [comment]
> 
> Still would need a way of interfacing the RFID reader into the database. 

@SchrodingersGat I looked a bit into that. Seems like it is possible to interface with serial interfaces via chrome and similar browsers. I am still not sure if we can depend on that as it is marked as experimental.

**Comment by matmair** [comment]
https://web.dev/serial/

**Comment by BrettRD** [comment]
A UID field for a StockLocation would be ideal.
I was going to use the link-barcode-to-item feature but my tags ended up on the box instead.

The reader makes the most sense as a portable unit, and an ESP32 handles the unit just fine with heaps of room for MQTT / websockets / REST / whatever else

The dev kits from most vendors seems to be compiled android libraries, hence the rewrite

**Comment by matmair** [comment]
@BrettRD does your device register as a keyboard or as a tag reader?

@SchrodingersGat I would target this for 0.7.0 if we need to integrate with that API

**Comment by BrettRD** [comment]
My reader has a bare TTL level uart plug on the back, I'm using a usb-serial adapter to test library code on a laptop.

I intend to run it as a standalone device on the wifi, probably with MQTT.

A first usage test for me is to load a tag ID into the scanner and go hunt for buried treasure.

**Comment by matmair** [comment]
I would chagne the target to 0.7 @SchrodingersGat

**Comment by SchrodingersGat** [comment]
@matmair agreed, the scope of this has expanded somewhat.

I do not think that a direct browser interface is the way to go, but the existing API / python bindings would be perfect for this kind of application. Maybe a plugin?

**Comment by BrettRD** [comment]
> I do not think that a direct browser interface is the way to go, but the existing API / python bindings would be perfect for this kind of application. Maybe a plugin?

enough schema to support a plugin is all I'm hoping for.
I know it takes a database migration run client-side so I'm happy to wait for a release.

**Comment by matmair** [comment]
@SchrodingersGat I would really like to support reading devices via a webworker but that will be far out. Would reduce the need for a lot of plugins (could also be a plugin 😇), I imagine.

> 
> enough schema to support a plugin is all I'm hoping for. I know it takes a database migration run client-side so I'm happy to wait for a release.

@BrettRD  We are working on a full-blown plugin system. I will ping you when that it is out about possible integrations.
In general, there are two possible ways:
- implement a small MQTT server via an IntegrationPlugin into InvenTree so the reader with a small board can ping its readings (and maybe a few button presses) back to InvenTree; You could have a nice interface to do fast actions via that too.
- implement a webworker that gives you the option to hook any usb / serial device to InvenTree and use it as an input method. So you could attach an android tablet or something like that to scan -> Although if you have windows / Linux drivers that emulates a keyboard you could just use that

**Comment by BrettRD** [comment]
I re-read the api docs, I think UID is not going to work for my case.

I need to filter the tag responses at the reader so I need to be able to query the database for a part, and retrieve the original tag-id/barcode, not just the hash.

The work-around would be a portable lib containing the barcode hash function inventree uses, but that excludes smaller microcontrollers from the job.

I'll get off this issue now and make a separate feature request.

**Comment by Bbillyben** [comment]
Hi there, 

I would add my voice to add this feature (barcode assigned to part, supplier part or manufacturer part)

As the last post is from 2021, I wonder if this feature is on the bench?



(For the moment, I will dedicate manufacturer MPN to store part barcode in order to retrieve the corresponding part, but it's a dirty workaround. )

**Comment by SchrodingersGat** [comment]
@Bbillyben on the bench but not forgotten. Just lack of time / resources - there are a lot of outstanding issues :)

**Comment by Bbillyben** [comment]
Many thanks for the info, 
I didn't mean to be pushy!
 Congratulations and thank you for this great tool (and frankly ergonomic vs. other ERPs)

I just opened the Django doc to see if I'm able to understand anything.

**Comment by matmair** [comment]
@Bbillyben you are welcome to spend the required time to build this out if you feel this is important.

**Comment by Bbillyben** [comment]
Many Thanks @SchrodingersGat ! It works like a charm, from update db to api call.
(I would really like to help matmair, but viewing modification from ScrodingerGat let me thing it's far over my skills and understandigns...)

**Comment by Bbillyben** [comment]
Many Thanks @SchrodingersGat ! It works like a charm, from update db to api call.
(I would really like to help matmair, but viewing modification from ScrodingerGat let me thing it's far over my skills and understandigns...)

**Comment by SchrodingersGat** [comment]
@Bbillyben this ended up requiring a refactor of some very old code! Most modifications we make are not this complex.

**Comment by Guusggg** [comment]
Wow, this is functional now? That's fantastic news, guys! A job well done. Thank you!
