### ISSUE TITLE
Build breaks when using `git pull origin master`

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#1975]
Hi,

Today, I noticed while trying to fix #1974 by checking out the master branch that the build currently breaks.
When running `inv update`, I get the error that it's trying to open `part_label.html.py` but the permission was denied. After checking the directory, it does not seem to be there. I think this might be caused by someone not committing all the files that are needed to get to the latest master branch.

Not sure what I can do to help fix this, I just wanted to make sure the issue is reported. As I'm currently on a different branch to implement my own features, it might be just my problem but I wanted to see if others have the same error.

Kind regards,

**Comment by eeintech** [comment]
I've just pulled latest master and don't have this issue :confused:

**Comment by Guusggg** [comment]
Alright then it might just as well be on my end... (I'm messing around a lot with permissions on the Linux box so thats definitely something that could be caused by myself). 

I'll close this for now, thanks a lot for checking it for me!

**Comment by eeintech** [comment]
No problem. I'm curious:

> I'm currently on a different branch to implement my own features

What features did you implement that are currently missing from master?

**Comment by Guusggg** [comment]
Nothing special, I have some custom formatting functions for StockItem and Part labels. Basically one `@property description_as_list` which returns the description, split by `"-"`.
