### ISSUE TITLE
`img_source` folder

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1976]
What is this for?

![image](https://user-images.githubusercontent.com/4020546/130080468-63453f34-6786-46c7-b7cd-5d36ac666d0b.png)

Can't seem to find anything using those two SVG images...

**Comment by matmair** [comment]
I can also not see what it is meant to do.

**Comment by SchrodingersGat** [comment]
Not sure either to be honest. I added them way back in 2018!

**Comment by matmair** [comment]
@SchrodingersGat so should we delete it as a test?

**Comment by eeintech** [comment]
Nice thanks 👍

**Comment by SchrodingersGat** [comment]
@matmair fix has been merged already
