### ISSUE TITLE
Create PurchaseOrder Modal Form returns `Server Error` although responseCode is 200

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#1984]
Hi,

Today I encountered an issues when using the Multi Part Order functionality. When selecting multiple parts from a Supplier and clicking Order Parts, the modal for ordering several parts shows up. However, when clicking the little green + button to create a new Purchase Order, a dialog shows up that says 
```
Error requesting form data
OK
Error Code - 200
Show Error Information
```
I looked a bit into it, and it seems the `launchModalForm()` function in `modals.js` expects to receive JSON to build the modal. However, looking into the console, it shows HTML so I think the URL wrongly sends HTML instead of JSON.

I currently do not have enough knowledge about the internals of the projects to fix this myself, however if someone can point me in the right direction I can do it!

Edit: I investigated some more and it seems all little green + buttons are affected, such as SupplierPart, PurchaseOrder, SalesOrder etc.

Any ideas?

Kind regards,

**Comment by eeintech** [comment]
I can confirm it is broken :confused: 

I think Oliver wanted to convert all secondary modals to API forms so hopefully he will have time to take a look at what it takes to fix that one :smiley:

**Comment by SchrodingersGat** [comment]
I've implemented a temporary fix for this one; a full refactor of the "order form wizard" will take considerably more effort.

**Comment by SchrodingersGat** [comment]
@Guusggg please check that this error is remedied now

**Comment by Guusggg** [comment]
Sorry for the slow reaction but it's functioning great now! Thanks a lot!
@SchrodingersGat
