### ISSUE TITLE
Sorting is broken on some "index" tables

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1986]
## Latest Parts (example sorting by "IPN")

![image](https://user-images.githubusercontent.com/4020546/130279279-b29287df-8a65-4f2b-8014-21eb87a2cfc8.png)

![image](https://user-images.githubusercontent.com/4020546/130279304-81da26a3-4e05-4ab5-805f-d1dbef9551b9.png)

## Recently updated (example sorting by "Stock")

![image](https://user-images.githubusercontent.com/4020546/130279780-09072237-5738-4fb2-b1e3-c227c1d34481.png)

![image](https://user-images.githubusercontent.com/4020546/130279808-b8e7e69d-601d-4d45-92ea-024e894dac1f.png)

**Comment by matmair** [comment]
@eeintech this is kind of expected behaviour: the tables that were affected had a fixed sorting so my PR disables the buttons.

**Comment by eeintech** [comment]
Makes sense, thanks @matmair

**Comment by eeintech** [comment]
@matmair Unfortunately sorting hasn't been disabled in the "Recently updated" table:

![image](https://user-images.githubusercontent.com/4020546/130481012-706f08fb-c586-420c-b756-e12bdf417fa6.png)
