### ISSUE TITLE
Purchase price can not be changed via API

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1988]
@matmair @eeintech 

Hi,

Today when implementing a barcode feature I notice that it's not possible to set the price for a StockItem through the API. The price is being copied from a PurchaseOrder but the API simply does not update it when sending an `update` for StockItem with keys `"purchase_price"` and `"purchase_price_currency"`. The Flutter API does return `true`, so it might seem the price is updated, however this is not reflected on the website. 

Is this issue on my side only or is it something that I can be working on in the near future?

Edit: I looked around in the source and the API simply does not take the `purchase_price` as it shows up in `print( str(request.data) )` but then after `item = serializer.save()`, it does not show up. `print( str(vars(item)) )` simply shows `purchase_price: None`...

Kind regards,

_Originally posted by @Guusggg in https://github.com/inventree/InvenTree/issues/1656#issuecomment-902007034_

**Comment by matmair** [comment]
@Guusggg can confirm that this does not work currently.

You are welcome to fix it if you want. Please ping us if you need assistance.

On another note: Are you building something public or private? I am always intrested in what ppl are building and we have a place to link projects in the [docs](https://inventree.readthedocs.io/en/latest/extend/integrate/).

**Comment by SchrodingersGat** [comment]
@matmair @Guusggg is working on some new features for the app

**Comment by SchrodingersGat** [comment]
The `purchase_price` field is essentially read only

https://github.com/inventree/InvenTree/blob/87a41c7e3912654975c89911d1dbe8e66e8d63b4/InvenTree/stock/serializers.py#L142

To support writing we would need to break this into separate `purchase_price` and `purchase_price_currency` fields as we have done with other similar serializers
