### ISSUE TITLE
[FR] pricing: tooltips for pricing

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1989]
@eeintech @sintech so a small tooltip with information what information was used for calculation would be ok? I would include multiple levels of information depending on the settings.

_Originally posted by @matmair in https://github.com/inventree/InvenTree/issues/1957#issuecomment-902925980_

**Comment by matmair** [comment]
This is a needed addition for the overall pricing project (#1656)

**Comment by sintech** [comment]
@matmair maybe it makes sense to add "Internal Cost" as separate column to BOM table and show it as additional line in "Pricing Information". Then it will be clear what are the sourses of Cost and/or Price even without tooltips.

**Comment by matmair** [comment]
@sintech while I generally agree with your idea to serve everything we know in own columns I try to keep certain tables as narrow as possible. In the pricing view for example we have only half a page width so longer partnames present a problem. Therefore I suggested a tooltip as that can contain a lot more information with very minimal footprint.

**Comment by SchrodingersGat** [comment]
Changing this to 0.6.0

**Comment by SchrodingersGat** [comment]
I am closing this issue out following the recent pricing refactor
