### ISSUE TITLE
[BUG] "Update prices" button clears up order modal form

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#2004]
Related to #1996 

To reproduce:

1. Click on "Buy" -> "Suppliers" -> Click on a Supplier
2. Click on either "Supplied Parts" or "Stock" tab
3. Select few parts in "Supplier Parts" or "Supplier Stock" table
4. Click on "Options" -> "Order Stock", the "Order Parts" form appears
5. Click on "Update prices" button

The following things can happen:

- the form clears up

![image](https://user-images.githubusercontent.com/4020546/130459345-975d932e-3ec8-4d2f-8d04-4352c3830819.png)

- **Or** another modal form comes up about Status Code not being selected

![image](https://user-images.githubusercontent.com/4020546/130459504-2fae6562-9a72-4ace-9654-bf66fdebfeaf.png)

But none of those are expected behavior.

Bonus bug
---

When calling the "Order Parts" form from the "Supplier Stock" table, there are two "Update prices" buttons:

![image](https://user-images.githubusercontent.com/4020546/130459916-e4511684-901d-4ad0-96cf-047de6b6ca8b.png)

**Comment by matmair** [comment]
@eeintech I think this comes from the refactors for the modal-code - I will try to find the bug-source but there is a lot of voodoo going on. Really need an UML generator for django / js.

**Comment by SchrodingersGat** [comment]
@matmair @eeintech do you think this is a small fix or will require a significant amount of work? I'm trying to determine if this should be slated for the `0.5.0` release :)

**Comment by matmair** [comment]
@SchrodingersGat no quite sure where it goes wrong, will try to look into it.

**Comment by matmair** [comment]
> 
> 
> Related to #1996
> 
> To reproduce:
> 
>     1. Click on "Buy" -> "Suppliers" -> Click on a Supplier
> 
>     2. Click on either "Supplied Parts" or "Stock" tab
> 
>     3. Select few parts in "Supplier Parts" or "Supplier Stock" table
> 
>     4. Click on "Options" -> "Order Stock", the "Order Parts" form appears
> 
>     5. Click on "Update prices" button
> 
> 
> The following things can happen:
> 
>     * the form clears up
> 
> 
> ![image](https://user-images.githubusercontent.com/4020546/130459345-975d932e-3ec8-4d2f-8d04-4352c3830819.png)
> 

This is expected behaviour: The parts start out with a quantity of 0 - if you update the prices parts with a quantity of zero get removed.

>     * **Or** another modal form comes up about Status Code not being selected
> 
> 
> ![image](https://user-images.githubusercontent.com/4020546/130459504-2fae6562-9a72-4ace-9654-bf66fdebfeaf.png)
> 

I can not reproduce this.

> ## Bonus bug
> 
> When calling the "Order Parts" form from the "Supplier Stock" table, there are two "Update prices" buttons:
> 
> ![image](https://user-images.githubusercontent.com/4020546/130459916-e4511684-901d-4ad0-96cf-047de6b6ca8b.png)

This is a bug for sure. Investigating now

**Comment by eeintech** [comment]
> This is expected behaviour: The parts start out with a quantity of 0 - if you update the prices parts with a quantity of zero get removed.

Umm okay, it does not feel quite right though to punish user to have to **re-open** the form after quoting a quantity 0...

**Comment by matmair** [comment]
> 
> 
> > This is expected behaviour: The parts start out with a quantity of 0 - if you update the prices parts with a quantity of zero get removed.
> 
> Umm okay, it does not feel quite right though to punish user to have to **re-open** the form after quoting a quantity 0...

I do not see it as punishment put a shortcut to remove lines from the form when you tab through the entries and select parts / set quantities.
I think we had a similar discussion when this function was added. Should I add an information bubble to the form?

**Comment by eeintech** [comment]
Well the way I see it is that I will pull the price before setting the quantity. So yes at least explain that updating price for 0 quantity will remove those parts from the modal form
