### ISSUE TITLE
Cannot start service inventree-worker

### ISSUE THREAD

**Issue by djex** [inventree/InvenTree#2029]
Hello. I followed the instructions here: https://inventree.readthedocs.io/en/latest/start/docker_prod/ for the Inventree production server and every time I go to start the server I get the following error. I'm not sure where to go from here. I'm using the latest release version 0.4.5 and have confirmed the file start_prod_worker.sh exists.

```
user:~/Programs/InvenTree-0.4.5/docker$ sudo docker-compose up -d
inventree-db is up-to-date
inventree-server is up-to-date
Starting a6102996672a_inventree-worker ... 
Starting a6102996672a_inventree-worker ... error

ERROR: for a6102996672a_inventree-worker  Cannot start service inventree-worker: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./start_prod_worker.sh": stat ./start_prod_worker.sh: no such file or directory: unknown

ERROR: for inventree-worker  Cannot start service inventree-worker: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./start_prod_worker.sh": stat ./start_prod_worker.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by djex** [comment]
Just an update. Followed instructions using latest from master and it's works without issue.

**Comment by SchrodingersGat** [comment]
@djex the docker build system recently got refactored so the latest docs may not match an older tagged release! Glad that you got it working :)
