### ISSUE TITLE
[BUG] Copy to clipboard icon shadowing

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#2032]
**Describe the bug**
Noticed this issue in the version modal, but it's everywhere on the UI:

![image](https://user-images.githubusercontent.com/4020546/132047096-879ea72d-6c0f-4afb-959f-f7c0b0c452aa.png)

Also there are some issue with loading the FontAwesome icons on this modal.

**Expected behavior**
Icon on right-hand side should be hidden:

![image](https://user-images.githubusercontent.com/4020546/132047168-6b599471-2f8f-46ce-b909-eef6408b56d2.png)

**Version Information**
See above (master)

**Comment by SchrodingersGat** [comment]
Introduced in c90f9b04472576bc805696372e829ac837c8f264

https://github.com/inventree/InvenTree/blob/c275bf8d986446a4978b1ab29e8af4c2f915af68/InvenTree/templates/clip.html#L4

`<i> .... </em>` is not valid HTML ;)

**Comment by eeintech** [comment]
Thanks @SchrodingersGat
