### ISSUE TITLE
[BUG] Unable to start Docker worker with latest tag

### ISSUE THREAD

**Issue by lettore** [inventree/InvenTree#2046]
**Describe the bug**
Using the latest https://github.com/inventree/InvenTree/blob/master/docker/docker-compose.yml I'm unable to start the worker container. While the server start but crashes as the worker in unable to boot, the worker started with the command: invoke worker crash with  ModuleNotFoundError: No module named 'django'.
I'm not running a docker compose but a swarm stack, it always worked until the last change in entrypoint setup.

**To Reproduce**
1. Deploy compose stack
2. Worker can't start 
3. Complete Error log
`/home/inventree/data/config.yaml exists - skipping
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    import django  # NOQA
ModuleNotFoundError: No module named 'django'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?`

**Expected behavior**

**Screenshots**

**Deployment Method**
Docker

**Version Information**
latest docker image

**Comment by matmair** [comment]
@lettore seems like the django install did not work. Maybe rerun the install steps.

**Comment by lettore** [comment]
This problem occurs only with latest tag, with 0.4.5 and before there's no problem so it's for sure a bug in the Docker build of the latest tag.

**Comment by matmair** [comment]
@lettore have you tried old tags on your current setup? That would be the only way to be sure.

**Comment by matmair** [comment]
@SchrodingersGat could that be any changes in docker?

**Comment by lettore** [comment]
I managed to find what is the problem, the container was running as user root, reverting to user inventree made all work.
I will close the issue and hope that will be useful for someone else.

**Comment by markdedeuge** [comment]
@SchrodingersGat Given the pythonpath is not registered for a root user, it might be a good idea to test the UID in the entrypoint script and throw a user-consumable error saying that django wont be found when running as root. And/or add in the corrections needed?

@lettore were you modifying the entrypoint or command directly? and were you specifying the `user: root` directive in your compose file?

**Comment by SchrodingersGat** [comment]
> it might be a good idea to test the UID in the entrypoint script and throw a user-consumable error saying that django wont be found when running as root. And/or add in the corrections needed?

@markdedeuge want to submit a PR for this?

**Comment by lettore** [comment]
@markdedeuge no I didn't changed the entrypoint or command.
In compose I added user: 0:0
