### ISSUE TITLE
[FR] Ability to display 'Issues' that have been detected in the server from within the Web UI

### ISSUE THREAD

**Issue by bevanweiss** [inventree/InvenTree#2057]
**Is your feature request the result of a bug?**
Nope (at least I don't think so)

**Problem**
I'm new to InvenTree, but it seems awesome for my at home electrical/electronics parts.
I've had some challenges getting a stable configuration however, but have got 0.4.5 currently working well enough for me to feel confident throwing data into it.
However, my docker based install does apparently have some 'Issues detected', and I'd like to fix them (or at least know what they are).
![image](https://user-images.githubusercontent.com/2055446/133202149-9b7985aa-c95d-43f8-b519-63f02c7d8a5f.png)
But whilst it shows me the little badge, it doesn't appear obvious how I can get the details of what the issues are.

**Suggested solution**
It would be absolutely beautiful if this 'Issues Detected' badge had a dropdown arrow on it with a list of one line summaries of the 'Issues', and if these had dropdown arrows which provided the full information on the issue, perhaps even with a reference back into doco of how to fix the issue.

**Describe alternatives you've considered**
I assume that this information is likely available if I do a docker run and tail out some log files or similar.  But for a Web UI driven application that doesn't seem ideal.
Display in the Web UI could be as simply as just a scroll box showing the raw issue detector text.

**Examples of other systems**
Unknown.

**Do you want to develop this?**
I think learning Django, alongside the project specific aspects might be a bit over my head.  If a Django-guide could point me at an existing Django implementation of similar, and an InvenTree-guide could point me to the formatting of the issue detector output then I could probably look into it...

**Comment by matmair** [comment]
@bevanweiss thanks for the report!

I think your problem can be solved by configuring email correctly. Information for that ca be found by clicking on the yellow alert below the issues detected

**Comment by bevanweiss** [comment]
Ahh, it was indeed one and the same.
I didn't care for the email settings at the time, so didn't configure, and there wasn't an obvious linkage between the 'issue detected' being that the email settings weren't configured.

The colours on the two indications didn't seem correlated (Issues detected red=critical, vs Email settings yellow=warning), and the email settings depiction wasn't "nested" under the Server Status / Issues detected area.

However, having added email config, both the email setting warning, and issues detected have gone away.
Thanks.
I still believe this could be conveyed in a more obvious manner to the user however, so I believe something similar to the feature request still stands.

**Comment by matmair** [comment]
@SchrodingersGat @eeintech should we 'fix' this or leave it?

**Comment by eeintech** [comment]
"Issues" is quite a strong word :smiley: 

I think it'll be nice to have more information :+1:

**Comment by SchrodingersGat** [comment]
I think we can definitely improve the messaging here. At the very least, if there are no *critical* issues, it should not display as RED
