### ISSUE TITLE
[BUG] App: Can't create/modify entities with umlauts in string

### ISSUE THREAD

**Issue by dermodmaster** [inventree/InvenTree#2059]
**Describe the bug**
I can't create/modify entities with umlauts (e.g. ä ö ü) in a name in the app.

**To Reproduce**
1. Go to parts > actions > new category
2. try to create the category "Geräte"
3. See error

**Expected behavior**
Entity should be created/modified without error

**Screenshots**
![Screenshot_20210917-122130](https://user-images.githubusercontent.com/22645685/133767612-a13eb18f-2580-4ede-921f-49c7fa544363.jpg)

**Deployment Method**
Docker

**Version Information**
0.5.0 dev

**Comment by SchrodingersGat** [comment]
Thanks for reporting this @dermodmaster 

Will have to look into this one for you :)

**Comment by SchrodingersGat** [comment]
@dermodmaster are you using the app on iOS or Android?

**Comment by SchrodingersGat** [comment]
@dermodmaster I've just uploaded `0.4.7` for release which fixes this issue. Normally takes a day or two to be available for download.

I'll close this issue out for now, if the new version does not address the issue for you please feel free to re-open and we can work on it further.

**Comment by dermodmaster** [comment]
android and the problem is fixed. Thank you! :)
