### ISSUE TITLE
Installation on LAMP stack

### ISSUE THREAD

**Issue by ugintl** [inventree/InvenTree#2061]
Is it possible to install it on a lamp stack with python?

**Comment by matmair** [comment]
@ugintl yes. Although I would not advise to use this method if you are not somewhat knowledable about linux, how webservers work and how to configure nginx or apache2
 The relevant docs are [here](https://inventree.readthedocs.io/en/latest/start/install/)

**Comment by ugintl** [comment]
I have seen the docs couple of times before, but I do not think I will be able to pull this off unless there is some proper documentation available for my use case. Thank you for your time. The option of using Mysql got me excited :)

**Comment by matmair** [comment]
@ugintl I will close this issue for now - if you encounter issues feel free to ask!
