### ISSUE TITLE
[3rd party integration] plugin repo

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2065]
Long term: Integrate a plugin repo/overview page like [ocotoprint](https://plugins.octoprint.org/) has it for example.

Part of #1421

**Comment by matmair** [comment]
@SchrodingersGat how do you feel about this? Would that be a long term goal for you or not?

**Comment by SchrodingersGat** [comment]
I like it! Obviously there's a lot of details to work out here, and I'd like the "core" plugins to be very carefully integrated and maintained. I'm excited about the idea, though.

**Comment by matmair** [comment]
@SchrodingersGat ok I will built in some stuff to support that in the future. A full repo with website etc. ist definitively 1.0 stuff though.

**Comment by matmair** [comment]
Currently testing out jenkins and UI frameworks; Should be pretty easy to set up;
https://github.com/invenhost/repo.invenhost.com / https://repo.invenhost.com/

**Comment by matmair** [comment]
This is not really needed for plugin functions as the install mechanism does not rely on anything like it. Could be a plugin itself tbh.

**Comment by matmair** [comment]
The new website will provide an overlook. Closing
