### ISSUE TITLE
General discussion: refactor of plugin structure

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2066]
Hey @inventree/maintainer @inventree/triage !
I am currently developing a broader plugin system (https://github.com/matmair/InvenTree/tree/plugin-2037) that enables a lot of different integrations into the system.

I would like to refactor the existing code for plugins (ReportPlugin, BarcodePlugin and ActionPlugin) to streamline them:
1. load all plugins at startup into settings variables -> only use references top those makes one-time loaded code etc. possible
2. provide overviews of what plugin modules/classes are loaded for each type
3. remove duplicated code
4. make a central directory from which any kind of plugin is loaded -> currently, there are multiples and invetree-code is mixed with custom code.
5. move sample implementations into their own files

These changes would be breaking for current plugin users. What do you think about that?

**Comment by SchrodingersGat** [comment]
100% the plugin architecture needs addressing. 

> These changes would be breaking for current plugin users. What do you think about that?

I do not think that there are currently *any* plugins, let alone users. The exiting plugin framework never received much attention, I'm glad that you have been giving it some thought!

I am very much in favor of a cleaner, streamlined implementation. With working examples would be great!
