### ISSUE TITLE
[BUG] invoke superuser asks for username then does nothing

### ISSUE THREAD

**Issue by r1me** [inventree/InvenTree#2069]
**Describe the bug**
I'm at the last steps of InvenTree installation on my RPi 3B+ buster. `invoke superuser` asks me for username, once I typed it in (or left it empty) and pressed Enter, it didn't ask me for password. Database is configured and server is running, InvenTree login page can be viewed fine.

**To Reproduce**
```
pi@raspberrypi:~ $ sudo su inventree
inventree@raspberrypi:/home/pi $ cd /home/inventree/
inventree@raspberrypi:~ $ source ./env/bin/activate
(env) inventree@raspberrypi:~ $ cd /home/inventree/src/
(env) inventree@raspberrypi:~/src $ invoke superuser
Username (leave blank to use 'inventree'): admin

```

**Expected behavior**
I believe I should get prompt for the user password

**Deployment Method**
Bare Metal

**Version Information**
trunk

**Comment by matmair** [comment]
@r1me python in the raspi seems to sometimes have a problem with pty.
Please try to run
'cd InvenTree
python manage.py createsuperuser'

**Comment by r1me** [comment]
Yup, that worked immediately. Thanks.
