### ISSUE TITLE
[APP] pages renders without style sheet

### ISSUE THREAD

**Issue by bobflycreek** [inventree/InvenTree#2070]
**Describe the bug**
A clear and concise description of the bug or issue

**To Reproduce**

1. Go to ...
2. Select ...
3. ...

**Expected Behavior**
A clear and concise description of what you expected to happen

**Screenshots**
If applicable, add screenshots to help explain your problem

**Version Information**

- App platform: *Select iOS or Android*
- App version: *Enter app version*
- Server version: *Enter server version*

**Comment by bobflycreek** [comment]
followed instructions to run production on bare metal. 
when testing gunicorn via /home/inventree/env/bin/gunicorn -c gunicorn.conf.py InvenTree.wsgi -b 127.0.0.1:8000

all that renders is the login / password box - no style and background images

**Comment by matmair** [comment]
@bobflycreek could you please fill out the template? We need that information

**Comment by bobflycreek** [comment]
> A clear and concise description of the bug or issue
when browsing to http:127.0.0.1:8000 all that renders is the login and password box without any style sheets
>Steps to reproduce the behavior:
followed instructions provided by setup instructions - followed baremetal production install
>A clear and concise description of what you expected to happen
expected full web page with styles and background
>If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/91205516/134365264-8ec009cc-6c65-4ffe-bb04-ecc30f48e812.png)
>App platform: ubuntu 20.4
>App version: Latest
>Server version: 0.5.0 Development

Should I be on an older version?

**Comment by matmair** [comment]
@bobflycreek if you want to run this in production yes. The bleeding edge can be buggy.

Are you sure you followed all instructions? Have you set up apache or nginx for serving static content and media?

**Comment by bobflycreek** [comment]
I went back through the setup again, this time when I run from the CLI it renders. when I run from supervisor the inventree-cluster fails to start
this the error in the log--> Error: Missing required database configuration value ENGINE

the config.yaml has the correct values

is there another config setting I am missing?

**Comment by bobflycreek** [comment]
My bad -- forgot YAML files are space sensitive

**Comment by matmair** [comment]
> My bad -- forgot YAML files are space sensitive
> 
> 

Happens to the best. Feel free to ask if any other problems arise.
