### ISSUE TITLE
[FR] Deleting a part is not discoverable

### ISSUE THREAD

**Issue by reilly-callaway** [inventree/InvenTree#2072]
**Problem**
At first glance, there is no way to delete a part. Requires marking a part as inactive first before revealing the "delete part" button. Makes deleting a part very undiscoverable in the ui.

**Suggested solution**
Show the delete part button even when a part is still active. When selected, prompt the user to mark the part as inactive first (or suggest the user leave the part as inactive instead of deleting).

**Describe alternatives you've considered**
 * A comment in the part attributes "active" toggle switch to indicate making the part inactive will allow you to delete it.
 * Update the docs on how to delete a part.

**Comment by SchrodingersGat** [comment]
Nice idea, button would still be hidden for users who don't have "delete" role for parts

**Comment by matmair** [comment]
@reilly-callaway would you be willing / able to develop this?
