### ISSUE TITLE
Stock allocation for template parts does not work in the same way as simple parts

### ISSUE THREAD

**Issue by G-Pereira** [inventree/InvenTree#2073]
Allocating stock of template parts shows stocks of all variants, however completely allocated stocks are also displayed, and once selected the count goes to zero on the second input field but there is no way of knowing which stock item has the required quantity unallocated. The only way of knowing is selecting one of them, checking if the value goes to zero on the other input field and if it does, close the allocation window and opening it again and try another stock item.

I would expect only available stock items are listed.

This tool is amazing, I am glad to be of help!

**Comment by SchrodingersGat** [comment]
@G-Pereira can you provide some screenshots of the issue here for clarity?

**Comment by SchrodingersGat** [comment]
Bump @G-Pereira  :)

**Comment by G-Pereira** [comment]
![image](https://user-images.githubusercontent.com/15521303/144725803-6223e5f9-efa7-494c-8337-b6d1b389dae1.png)

**Comment by SchrodingersGat** [comment]
Thanks for the clarification. What version of InvenTree are you running?

**Comment by G-Pereira** [comment]
I am on the latest stable version: 0.5.4

**Comment by SchrodingersGat** [comment]
The latest master version (0.6.x) already fixes this issue, by hiding stock items which are already allocated from this list.

Back-porting this fix to the 0.5.x branch would be quite difficult, I think that you will just have to wait for 0.6.0 stable release, which is now not too far away.

**Comment by G-Pereira** [comment]
That's completely acceptable!

**Comment by G-Pereira** [comment]
That's completely reasonable!
