### ISSUE TITLE
[3rd party integration] import key from github

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2076]
The plugin system supports checking if the plugin code (at least the last change on the plugin-class file) was signed.
If the pubic key is not in the gpg install of the server it is marked E. To solve this problem a mechanism to import public keys (to start with from github) should be integrated.

**Comment by SchrodingersGat** [comment]
@matmair sorry I hadn't seen this one :)

**Comment by matmair** [comment]
Not really imported - bumping to 0.8.x

**Comment by matmair** [comment]
This might be a security concern - will investigate further if we open the users up to problems with this.
