### ISSUE TITLE
Improve page load speed 

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2081]
Page loading speed (especially for the "part" page) can be very slow.

Compared to the API which is (normally) lightning fast.

- Profile the page load / template rendering
- Optimize DB hits

**Comment by matmair** [comment]
@SchrodingersGat the way the parts view works now all sections get loaded, maybe that could be optimized. I see 13 connections that need to be made every time. And a very long rendering time on the main HTML.

**Comment by SchrodingersGat** [comment]
Yes I think the main HTML loading is inefficient, most likely some poorly considered database hits in the background! Will need some profiling work :)

**Comment by rkalman** [comment]
A part category page (/part/category/{id}) has a large "parametricPartTable" which includes info about each part (note the line numbers on the left):
<img width="517" alt="Képernyőfotó 2022-03-17 - 23 06 21" src="https://user-images.githubusercontent.com/580623/158903184-a49be97a-8ff6-4d96-847d-bd0ac5129dba.png">
<img width="602" alt="Képernyőfotó 2022-03-17 - 23 07 04" src="https://user-images.githubusercontent.com/580623/158903192-8ad2a957-6ce8-4fdc-8fdd-3a8bfca08d3c.png">
I suppose this takes a lot of time (20secs in my case).

**Comment by matmair** [comment]
@SchrodingersGat that seem like a great place for a paged API

**Comment by SchrodingersGat** [comment]
@rkalman great insight, looks like this page is being rendered server side, rather than via the API (like most other pages).
