### ISSUE TITLE
0.5.0 dev install issues

### ISSUE THREAD

**Issue by bgrant85** [inventree/InvenTree#2092]
I've run into problems trying to install 0.5.0 out the box, with no changes.
However its apparently a problem on my local machine.
I tried installing it on a "new" windows 10 machine, which required that I first install docker.
After installing docker, which included WSL2, and update to WSL2, and reboot, I unpacked Inventree 0.5.0 and ran 
cd inventree/docker
docker-compose -f docker-compose.dev.yml build
docker-compose -f docker-compose.dev.yml run inventree-dev-server invoke update

which produced the error
[+] Running 2/2
 - Network docker_default  Created                                                                                                                                         0.8s 
 - Container inventree_db  Created                                                                                                                                         0.3s
[+] Running 1/1
 - Container inventree_db  Started                                                                                                                                         1.7s 
**/bin/bash: ../docker/init.sh: No such file or directory**

For various reasons I suspected it was not a inventree code issue, but something to do with my installation on this specific machine.
To prove this, I unpacked the same Inventree 0.5.0 on a different Windows 10 machine that already has a version of Inventree running under docker.  Follow the same instructions as above, all worked as expected.
Can anyone provide guidance on my machine setup that would cause this issue, apparently docker related on Windows?
I tried uninstalling and reinstalling docker (latest version for Windows).

**Comment by SchrodingersGat** [comment]
Might be an issue with folder permissions?

Can you run the following command (on the system which is failing) and provide the output:

```
docker volume inspect docker_src
```

Should provide something like :

![image](https://user-images.githubusercontent.com/10080325/135775696-0fef7c3c-4fb4-4b78-b8bc-0fba0a086f0b.png)

**Comment by bgrant85** [comment]
I ran this command.  The only difference in my result is that my compose version is 2.0.0
On my system that does work, my compose version is the same as yours.
Is this the issue?  Is there a way to install an older docker that has the 1.29.2 version?

**Comment by bgrant85** [comment]
I used the docker version command on both systems and the output is identical 

 Client:
 Cloud integration: 1.0.17
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by bgrant85** [comment]
I uninstalled docker desktop,  and reinstalled a version from 2.5 months ago.  I deleted all images and volumes and rebuilt, but still the same problem.  Inspection of the new volume still shows compose version 2.0.0 even though the docker version is considerably older, as shown by the version command.
 Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by bgrant85** [comment]
Ok, with lot of work, I was able to downgrade my docker-compose to 1.29 and it seems to have fixed the problem.

**Comment by SchrodingersGat** [comment]
@bgrant85 that's very strange. What was the process you had to follow to downgrade?

**Comment by bgrant85** [comment]
Actually it wasn't hard to do.  Just figuring out how was a bit of a challenge.
First download the new executable.  I found the link for this on the docs page for installing docker on **windows server**.
https://docs.docker.com/compose/install/
PS> Invoke-WebRequest "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Windows-x86_64.exe" -UseBasicParsing -OutFile $Env:ProgramFiles\Docker\docker-compose.exe

This command puts the target in the wrong place.  Probably could adjust the above command to put the target in the correct place, but I simply copied it to the correct place after running the above command.
Above command puts the target at c:\Program Files\Docker
You can find the correct place with the command:
PS> Get-command docker-compose
for me the correct place was  c:\Program Files\Docker\Docker\resources\bin
Test the result with the command:
PS>  docker-compose --version

**Comment by matmair** [comment]
@bgrant85 so can we close this issue? 😇

**Comment by bgrant85** [comment]
yes, thanks

**Comment by cmos2020-bit** [comment]
Hi guys,

I'm, having exactly the same problems on Linux Mint 20. I really want to try the program, it looks great.
I have followed every step, and when running

"docker-compose -f docker-compose.dev.yml run inventree-dev-server invoke update"

The message I get is:

"  /bin/bash: can't open './docker/init.sh': No such file or directory  "

I'll appreciate your help.

Thank you guys!!

Patricio

**Comment by bgrant85** [comment]
did you check your version of docker-compose?  My issue was fixed by going back to 1.29.  Version 2.x did not work for me.
`docker-compose --version`
Not sure if that issue is fixed or was just my problem.
