### ISSUE TITLE
[BUG] After updating to 0.5.0 only the Parts tab is shown

### ISSUE THREAD

**Issue by G-Pereira** [inventree/InvenTree#2096]
![image](https://user-images.githubusercontent.com/15521303/135897960-3674e989-1886-49fa-aa5f-c8be276df8b8.png)

**Comment by eeintech** [comment]
@G-Pereira Are other tabs enabled?

![image](https://user-images.githubusercontent.com/4020546/135912278-d263c0ea-66d1-4641-8cb2-59f0c3b57821.png)

**Comment by SchrodingersGat** [comment]
@G-Pereira did you stop the server before performing the update? Try restarting the server process

**Comment by G-Pereira** [comment]
@SchrodingersGat I didn't, but afterward I always reboot the system and this time was no exception.

@eeintech That did the trick weird how the update changes a thing like that. @SchrodingersGat was that intentional?

**Comment by G-Pereira** [comment]
Also I've noticed that enabling Sales orders does not enable Sales so enabling SO without enabling Sales is pointless.

**Comment by SchrodingersGat** [comment]
This is not an intended behavior, no. It needs addressing.

**Comment by eeintech** [comment]
@SchrodingersGat It happened to me too... see #2014 (this is a duplicate)

**Comment by G-Pereira** [comment]
Closing this since it's a duplicate! Thanks @eeintech

**Comment by eeintech** [comment]
@G-Pereira Do you remember from which exact version were you updating from? Or the commit hash?
Which backend do you use?

**Comment by G-Pereira** [comment]
> @G-Pereira Do you remember from which exact version were you updating from? Or the commit hash?
> Which backend do you use?

Yes, it was a tagged release as well 0.4.5
I am using a venv on bare metal at the moment

**Comment by G-Pereira** [comment]
Oh you've meant the database engine, MySQL

**Comment by eeintech** [comment]
Ok I don't know why it would but there could be in relation to the type of backend... it's quite rare error though and not reproducible...

**Comment by matmair** [comment]
@SchrodingersGat I would say revert #1999 and leave this behind us.
