### ISSUE TITLE
[FR] Add option to display stock quantity in "part" display (within forms)

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2104]
![image](https://user-images.githubusercontent.com/10080325/136137354-81fad1f1-ec45-4b0e-8da9-b36c40ea50cf.png)

Here it would be useful to know what stock is available for each part...

**Comment by matmair** [comment]
Nice idea @schrodingersGat the data gathering function should check if the user has the rights to access this kind of information before displaying it.
