### ISSUE TITLE
[BUG] "Available Stock" field is not presented correctly when exporting BOM 

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2109]
### Error

- "Available Stock" reported as e.g. 1.00000
- Should be normalized e.g. 1

- Specifically found in `.xslx` export format
- Need to try other formats

**Comment by SchrodingersGat** [comment]
Can not immediate reproduce. Will need to discuss further with coworker who reported it.

**Comment by matmair** [comment]
Also can not reproduce - maybe depends on the BOM itself?

**Comment by SchrodingersGat** [comment]
Looks like this may be due to particular versions of python packages, although I have not yet worked out which one.

Problem is very repeatable on my work database, but not on my development one.
