### ISSUE TITLE
[BUG] No suplier pricing is shown

### ISSUE THREAD

**Issue by 71GA** [inventree/InvenTree#2123]
I create a supplier (Digikey), I create the component and configure it as available from the created suplier. I make sure that Digikey's supplier number is inserted. When I check the pricing information for a component there is no pricing information available.

Are there any special requirments to do, before pricing information is available?

**Comment by 71GA** [comment]
@matmair Inventree didn't fetch any prices from Digikey. That is what I was trying. If this functionallity is not implemented, is there a way that at some point in time it will be?

**Comment by 71GA** [comment]
@matmair Yes. Website gives this impression. And I had to ask as some similar software uses it as well: https://partsbox.com/demo/purchasing/order/bhtfcjtqjggw49va0tn7hthz1z

**Comment by matmair** [comment]
> 
> 
> @matmair Yes. Website gives this impression.
Could you provide us with a link to where you saw that so we can revise that? It is suboptimal if ppl get the feeling that there is a feature that doe not exist.

> And I had to ask as some similar software uses it as well: https://partsbox.com/demo/purchasing/order/bhtfcjtqjggw49va0tn7hthz1z

Partsbox is great but costs if you want to have this kind of function enabled - as a hobbyist open-source software we do not have this. Contributions are always welcome!

**Comment by matmair** [comment]
Ah ok, it could well be that some wording is not perfect.
While we don't auto-fetch prices from suppliers we over a wide variety of tools for pricing, maybe take a look and check if it covers what you need.

**Comment by matmair** [comment]
@71GA https://inventree.readthedocs.io/en/latest/part/pricing/

**Comment by matmair** [comment]
@eeintech I already have that functioning. But there are a few things that need fixing/polish in the plugin system before I release that

**Comment by eeintech** [comment]
@matmair Yes I was referring to your work :wink: Better polish before jumping on the boat to quickly!
