### ISSUE TITLE
Prompt to add qty to an already existing in the bom when adding the same item again

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#2134]
It would be great if adding an item to the bom which already exists in the bom would cause a prompt to appear to tell the user that the item already exists and if the user wants to simply add the additionally requested qty on top of the qty already in the bom.

![image](https://user-images.githubusercontent.com/42826581/136719301-f06096fa-6c5c-4f2c-9c29-59af0c74b076.png)

**Comment by SchrodingersGat** [comment]
To achieve this we would need to add another layer of complex front-end form logic, more than just "display the form" and adjust the fields. I'm not sure how to do this in a simple manner. 

(Currently most of the form logic is actually generated on the back-end)

I'll have a chat with @afkiwers offline (we work together) about how this could potentially be implemented.

**Comment by SchrodingersGat** [comment]
While there is some value in such a feature, it adds a lot of extra complexity for a small use case. Will not fix for now
