### ISSUE TITLE
 Could not load common.InvenTreeSetting(pk=2): UNIQUE constraint failed: common_inventreesetting.key

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2136]
**Describe the bug**
Then try to import demo data with docker

**To Reproduce**
Download demo data to folder data, build the container, run migrations, and then  try to import demo data which get an  error(

**Expected behavior**
Fill database with demo data

**Screenshots**
![image](https://user-images.githubusercontent.com/78436722/136754646-9d4f6cda-bf4c-4bdb-b717-7d0900455d3b.png)

**Deployment Method**
Docker dev server

**Version Information**
The last version

**Comment by SchrodingersGat** [comment]
I think that would be it.

To clear the database completely (but leave the schema migrations intact) run:

```invoke delete-data```
