### ISSUE TITLE
[FR] Running under Apache 

### ISSUE THREAD

**Issue by 71GA** [inventree/InvenTree#2139]
**Is your feature request the result of a bug?**
No

**Problem**
I like to keep all the webpages on my server running under Apache. 

**Suggested solution**
Is there any way that at some point Inventree (production) server will run under Apache and not under Gunicorn?

**Comment by 71GA** [comment]
@matmair Okay. So any general tutorial on how to run Django App insiide Apache will probably do?

**Comment by SchrodingersGat** [comment]
@71GA I'm going to close this one out now - please comment back here if you have additional issues.

If you get it working and feel that some more documentation could help other users with an apache install, please submit a PR to the [inventree documentation](https://github.com/inventree/inventree-docs).
