### ISSUE TITLE
[FR] Add docker-compose v2 support

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2143]
Ref: https://github.com/inventree/InvenTree/issues/2092

[docker-compose v2](https://github.com/docker/compose/releases/tag/v2.0.0) is out, and breaks the current docker build for (as yet) unknown reasons.

Need to investigate if there is a way to support v2 and v2 of docker-compose simultaneously.

**Comment by Gigahawk** [comment]
Temporary workaround from https://www.docker.com/blog/announcing-compose-v2-general-availability/.

You can switch back to compose V1 with `docker-compose disable-v2` or via the desktop UI:
![image](https://user-images.githubusercontent.com/10356230/168881136-c2e8be99-7d40-43dc-b81e-ea30a77d555f.png)

**Comment by SchrodingersGat** [comment]
Latest docker compose scripts actually seem to work just fine now

**Comment by SchrodingersGat** [comment]
@matmair upon further (closer) inspection I have found what the issue is, and unfortunately it is not "fixed" in master yet.

https://github.com/inventree/InvenTree/blob/6c71a26613c90032007e80eca82e143350103f2a/docker-compose.yml#L104

docker-compose v2 [does not support relative paths for volumes](https://github.com/docker/compose/issues/9410)

Even though I have migrated my test setup to docker-compose v2, my test machine had a legacy named volume which was created with v1, and so it was still valid.

Manually deleting the existing volume (`docker volume rm`) and then running `docker compose up -d` caused the same "init.sh not found" error as seen in other reports.

I guess this means we are also *not* testing this in our docker build CI checks!

So our options are:

1. Mandate that users must continue to run docker-compose v1
2. Work out a way around the relative path restriction
3. Wait for docker-compose to be patched

@matmair thoughts? I'd like to support v2 just because it's annoying to force users to downgrade. But we'd need to work out how to "fix" the docker-compose file

Note that this is *only* for the dev image. The production image requires the user to provide a qualified local path.

**Comment by matmair** [comment]
@SchrodingersGat as it only pertains to latest/dev I think 1/3 are both valid options. I think we add a short note for the devs that this problem exsists limited for dev and that v1 should be used for that. As no one should run the dev image in production anyway that seems like an adequate response.

On that note: should we maybe switch from `latest` to `testing` as a tag for the dev images? Seems a bit more appropriate to what they are in reality.

**Comment by SchrodingersGat** [comment]
@matmair I actually found a way to do 2) - https://github.com/inventree/InvenTree/pull/3410

**Comment by matmair** [comment]
@SchrodingersGat a resolution is the best solution.
