### ISSUE TITLE
Build orders not able to filter Sequentially

### ISSUE THREAD

**Issue by Marbles87** [inventree/InvenTree#2147]
When trying to sort build orders by ascending or descending i get presented with an improper sequence.

1. Go to build orders 
2. Click on arrow to sort by ascending or descending 
3. See error

**Expected behavior**
To be able to sort in ascending or descending regardless of digit count.

**Screenshots**

![2021-10-07  Build Orders](https://user-images.githubusercontent.com/48982658/137047148-896cecae-5911-49f0-9d31-bcd60b3b3fe7.png)

**Version Information**
0.6.0 dev

**Comment by SchrodingersGat** [comment]
Valid request. This should be addressed for other order types too (i.e *Purchase Order* and *Sales Order*).
