### ISSUE TITLE
Completing a build order Quicker [FR]

### ISSUE THREAD

**Issue by Marbles87** [inventree/InvenTree#2148]
**Is your feature request the result of a bug?**
Unknown 

**Problem**
Unable to batch process completed items for a build order. To complete the build output I need to go to each unique unit and complete the build output, This involves assigning a location, Status and flipping the confirm box . This is time consuming as I could potentially have items greater the 20+.

**Suggested solution**
By having a check box next to the output items with the ability to complete as a whole, I could then select the completed units excluding the ones that have either not been completed, Damaged or are under investigation/Isolated.

![2021-10-13 11_08_16-BO111](https://user-images.githubusercontent.com/48982658/137051548-519adbc3-41c1-411f-8cb8-51ab4e6edf4f.png)

**Comment by SchrodingersGat** [comment]
@Marbles87 is the existing issue - https://github.com/inventree/InvenTree/issues/1738 - the same as this one?
