### ISSUE TITLE
 django.db.utils.OperationalError: could not translate host name "inventree-db" to address: Try again

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2172]
**Describe the bug**
When  run on production error went from eventree-worker container

**To Reproduce**
Run docker-compose up command  in production without detaching

![image](https://user-images.githubusercontent.com/78436722/137478041-d1b0bf32-f25a-4858-9948-3d43946abd70.png)

**Deployment Method**
Docker

**Comment by matmair** [comment]
Also a lot of ppl. rum this on old raspberry pis. That azure instance can run a lot more than that.

**Comment by SchrodingersGat** [comment]
@HelgiBergmann so to clarify this was an issue with your server hosting, not with the InvenTree software itself?
