### ISSUE TITLE
Can't import all data fields when importing excel file of parts

### ISSUE THREAD

**Issue by tse-tarn-france** [inventree/InvenTree#2181]
**Describe the bug**
Dear All,
I'm using lastest InvenTree version on Ubuntu LTS 20.04 Server ( automatic dowload when install as described is doc https://inventree.readthedocs.io )
I've created parts manually and then export to excel file to get I/O excel files format, then I tried to upload all our stock ( of resistors ).
Only a few fields are availables in the graphical parser ( lack at least stock, stock min, price, location, etc ... )

**To Reproduce**
1. Having a minimum filled database with parts and parts categories, and options for import excel set to on
2. Try to upload excel file with parts within a subcategory
3. Try to choose fields names

**Expected behavior**
I expect to be able to import all the available fiels of database's dataset "part"

**Screenshots**
If applicable, add screenshots to help explain your problem ; I'll give them if needed, with pleasure.

**Deployment Method**
Bare Metal ( local, dev )

**Last but no least**
How to communicate with each others ? Only github ? no mailing list ?
How to contibute with testing ? Where to start ?
How to contribute with features ? Where to start ?
We are EMS so InvenTree can be our daily S/W and of course we are self-motivated to contribute in proposing features, maybe coding features, but where to start to "enter into the code" ?

Regards,
Lea & JCh.

**Comment by eeintech** [comment]
@tse-tarn-france Bienvenue sur le projet InvenTree !

I can also try to reproduce but first, could you please confirm the steps are:
1. Create stock items using InvenTree UI
2. Use Admin interface to export newly created stock items to CSV/XLS sheet
3. Use Admin interface to re-import stock items from CSV/XLS sheet
4. Noticed missing fields for import

Can you please also provide information:
1. InvenTree version information in this
2. Screenshot showing the missing import fields
3. Is the re-import done in the same instance or a different one? If different, are instances running with the same configuration?
4. Backend: SQLite, MySQL, PostGreSQL (might matter for the final import process)

Merci :wink:

**Comment by matmair** [comment]
@tse-tarn-france I reproduced this and not all fields are exposed. I do not know how much of the documentation you have read but stock is not just a number. There are (one or multiple) stock items connected to the number so you can not just import a basic number.
Could you file which fields you are missing? The current fields are defined here
https://github.com/inventree/InvenTree/blob/22572c6f3505c5667e7b394959ca014427ed58f7/InvenTree/part/views.py#L234-L258

**Comment by tse-tarn-france** [comment]
Dear all,

my Inventree 
![versions](https://user-images.githubusercontent.com/92796696/138143503-0ea68145-b14f-46ef-b0ee-4cbccca0dea0.jpg)
[InvenTree_Parts_Export.xls](https://github.com/inventree/InvenTree/files/7383227/InvenTree_Parts_Export.xls)
[InvenTree_Parts_Export.xls](https://github.com/inventree/InvenTree/files/7383231/InvenTree_Parts_Export.xls)
version is 0.6.0 dev

here are some screenshots + excel demo files. Indeed, I think being able to import all fields could be nice ( see export excel file ).

Enclosed my basic stock file to upload ( stock is "in_stock" ). minimum_stock is nice to import as well but is already possible.
import last buy price or expected buy price would be usefull, because when we buy, we need to know the last negociated price, and which is then expected. Moreover for annual inventory evaluation, last buy price is necessary.

Hope this help !
![1](https://user-images.githubusercontent.com/92796696/138143196-1a410412-cceb-44c0-be6f-f3f492780cfc.jpg)
![2](https://user-images.githubusercontent.com/92796696/138143205-5c93f494-facb-4386-872e-28e15aa44803.jpg)
![3](https://user-images.githubusercontent.com/92796696/138143208-971f42fd-a7d3-4868-abff-315866a5fd20.jpg)
![4](https://user-images.githubusercontent.com/92796696/138143215-4a65e6f1-53b5-488e-b237-a9c19ae3c795.jpg)
[STOCK_TSE_IN_062021_C3.csv](https://github.com/inventree/InvenTree/files/7383216/STOCK_TSE_IN_062021_C3.csv)

**Comment by eeintech** [comment]
I did not realize you were using the part import, sorry for that @tse-tarn-france 
Importing part will not get you the stock items, you'll have to use the Admin interface in this case.

@matmair Maybe we need to be more clear what is and what is _not_ supported for the part import in the documentation?

**Comment by eeintech** [comment]
@tse-tarn-france In your file's header row, change:
* `REF` to `IPN`
* `Designation` to `name`

What do you get?

I get this on `stable` branch:
![image](https://user-images.githubusercontent.com/4020546/138356437-ad7ceb9b-7fc9-45d2-910d-8f2f73bb4319.png)

**Comment by matmair** [comment]
> 
> 
> I did not realize you were using the part import, sorry for that @tse-tarn-france Importing part will not get you the stock items, you'll have to use the Admin interface in this case.
> 
> @matmair Maybe we need to be more clear what is and what is _not_ supported for the part import in the documentation?

@eeintech I would rather add the missing fields as it is quite simple with the current wizard setup. I am just unsure what fields we really need. If stock is filled in we can create an initial stock item - just like with the part creation dialogue.
