### ISSUE TITLE
[FR] Ability to ship parts to a manufacturer to "transform" the part into another part

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#2186]
**Problem**
At the moment the way our supply line looks is:
1. Order bare-metal parts from local manufacturer
2. Send bare-metal parts to another local manufacturer which welds and paints the parts
3. Receive the parts from the second manufacturer and put them into stock.

At the moment I haven't found a way to effectively model this in InvenTree.

**Suggested solution**
It would be cool if we could send a "Build Order" of some kind to a manufacturer so that parts are taking from stock (which are sent to the manufacturer) and a receive order will be automatically created so that the system expects these parts to return in a new "state" which adjusts the price and creates new stock.

**Describe alternatives you've considered**
There could also be an overhaul of the manufacturer models because at the moment they don't really do too much I don't think.

**Do you want to develop this?**
Yes but I need help with the overview how this fits into InvenTree and how to make it helpful for other people too

**Comment by matmair** [comment]
@eeintech @Guusggg whatever is suggested to solve this we should try to not make InvenTree to complex with it and hide the added stuff by default -> this is more a business use case than a hobbyist.

My suggestion would be to just use BOs but buildorders could be extended to support 'locking' them once the stock is allocated.
