### ISSUE TITLE
Add  fields in BO datamodel

### ISSUE THREAD

**Issue by tse-tarn-france** [inventree/InvenTree#2189]
**Is your feature request the result of a bug?**
NO

**Problem**
We would need a "note" field in BO, and a dotted progress bar or step dot progress bar which could be a datamodel itself

Explanation :

When buyers exchange information with prodution teams regarding a SO ans its BO, they use today an excel file which one column is "notes" for example "Will lack 200 x 2N2222 awaited for March 11th" => with that king of informations production teams can state wether the start one batch now and 2nd batch when received missing 2N2222 or the whole BO in one batch on complete 200 last PCB later.

dotted progress bar ( I assume this is more hard to implement )

We use 5 or 6 key indicators to produce a PCB :
PCB are availables in inventory / Stencil does already exist or must be prepared ; if Stencils exists, include its Id
SMD components are availables in inventory ( means BO can start for SMD assembly step )
Trough-hole components are availables in inventory ( means BO can start for trough-hole assembly step )
Production datas are available ( P&P datas ) and ready to use or need to be prepared

**Suggested solution**
At first maybe 5 or 6 more fields and when possible these files will be concatened into a dotted progress bar ?

**Describe alternatives you've considered**
Just 5 or 6 more fields which name is "user-defined" with default set to "step1, step2, etc ..."

**Examples of other systems**
our excel file :

![BO_list+_excel](https://user-images.githubusercontent.com/92796696/138354866-2c1f9978-aa94-4326-a962-18e62a348753.jpg)

**Do you want to develop this?**
As previous, why not with help

**Comment by SchrodingersGat** [comment]
@tse-tarn-france I'm going to close out this issue for now, due to lack of response. If you have anything further to add to this, please get back to us!
