### ISSUE TITLE
Add display to Sale Order

### ISSUE THREAD

**Issue by tse-tarn-france** [inventree/InvenTree#2190]
**Is your feature request the result of a bug?**
NO

**Problem**
Lack of informations for origin of the shipment and sale order

**Suggested solution**

![SO0001](https://user-images.githubusercontent.com/92796696/138355369-18ca6c47-5f60-498c-a093-020d042ca8d6.jpg)

**Describe alternatives you've considered**
Can't imagine

**Examples of other systems**
Not Applicable

**Do you want to develop this?**
As previous, yes with help

**Comment by SchrodingersGat** [comment]
@tse-tarn-france what was your progress on this? Should we close out this issue now?

**Comment by SchrodingersGat** [comment]
@tse-tarn-france closing this issue due to inactive, please feel free to comment here if you're still working on this
