### ISSUE TITLE
[FR] Inventory valuation reporting

### ISSUE THREAD

**Issue by jbrogan** [inventree/InvenTree#2191]
**Is your feature request the result of a bug?**
No

**Problem**
I would like to be able to generate an inventory valuation report for the value of inventory on hand at a given point in time.  

**Suggested solution**
Options to select by location/sub-location and grouping by location/part category/part sub-category.  

**Describe alternatives you've considered**
Within Inventree today the "Stock" page provides some of this information but it does not aggregate when multiple stock records exist for a part and does not appear to compute cost when a part is an assembly of other parts. 

**Examples of other systems**
N/A

**Do you want to develop this?**
I could potentially work on this if I have someone as a point of contact to get up to speed on dev env and code base.

**Comment by matmair** [comment]
@SchrodingersGat isn't this the same as #2507 ?

**Comment by matmair** [comment]
@jbrogan ping us if you want/need pointers.
It has been a while so we made the DX a bit better. If you use VS Code as an editor you should get a popup when you open the repository to use a specially prepared dev environment in docker.

**Comment by SchrodingersGat** [comment]
@jbrogan been a while, but check out https://github.com/inventree/InvenTree/pull/4345 for the upcoming implementation
