### ISSUE TITLE
[FR] Two-Factor Authentication

### ISSUE THREAD

**Issue by r0l1** [inventree/InvenTree#2201]
Adding another layer of security to the authentication system would be a great addition (OTP).

**Do you want to develop this?**
No, but we are open to create an open-source bounty.

**Comment by matmair** [comment]
@r0l1 MFA is now in review and should be in the next release 0.6.0; that could take up to a month.
I do not recommend to run the current master as it is not stable and there are major changes

You can check out the new feature through gitpod, see the link in the first comment in #2221

**Comment by matmair** [comment]
MFA is default off and needs to be enabled through the gloabal settings -> Enforce MFA

**Comment by r0l1** [comment]
@matmair sorry for the delayed response. Thanks a lot for the implementation! I'll have a look at it soon!
