### ISSUE TITLE
[FR] Refactor themes for Bootstrap 5

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2211]
> Should we refactor the themes too?

Yes, to both these things. Let's address these with separate PRs.

_Originally posted by @SchrodingersGat in https://github.com/inventree/InvenTree/issues/2205#issuecomment-955198167_

**Comment by matmair** [comment]
@SchrodingersGat  the themes seem to work as is - some colour settings need adjustments but not something that would be release-blocking

**Comment by eeintech** [comment]
@matmair Sorry I've been super busy lately, I didn't even upgrade our instances to Bootstrap 5 :sweat:
I can check on the current themes and regenerate the CSS for the Dark Reader theme from the Chrome extension, if that's necessary

**Comment by SchrodingersGat** [comment]
@eeintech that would be super helpful :)

**Comment by eeintech** [comment]
I just realized the Dark Reader application is broken :x: 

Opened a bug report (https://github.com/darkreader/darkreader/issues/7328) will keep you posted when I get it to work again, it will be a very quick fix :wink:
