### ISSUE TITLE
[BUG] Auth screens broken

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2213]
Fix login / auth screens that are broken due to #2205 
![grafik](https://user-images.githubusercontent.com/66015116/139533184-94fad201-088c-4c5d-82c5-4178912561f4.png)

**Comment by SchrodingersGat** [comment]
I don't see this on my end. Is this on a tablet or PC?

**Comment by matmair** [comment]
@SchrodingersGat simluated iPhone 11, see it on iPad too.
