### ISSUE TITLE
[Bug] Fix displayed alerts

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2243]
Existing "alert" messages (e.g. displayed when a user performs an action) have been broken since the update to bootstrap-5.

Currently they either do not display, or display incorrectly.

There are two separate issues here:

- Alerts on the "main" pages
- Alerts on the "account" pages (e.g. login / logout)

**Comment by matmair** [comment]
@SchrodingersGat maybe we should template and include that section so it behaves the same on main and account pages.

**Comment by SchrodingersGat** [comment]
@matmair I have made some changes in https://github.com/inventree/InvenTree/pull/2244 which address this quite nicely :)
