### ISSUE TITLE
[FR] Idea for subcategory tree view

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#2250]
**Problem**
As a part of Bootstrap 5 introduction (#2205), category treeview was removed in favor of "Subcategory tab".
This leads to unnecessary clicks when user wants to change category outside of currently opened branch.

**Suggested solution**
Add drop-down category list to the header of every part/stock view with the same content as in "subcategory tab". Active category should be highlighted and selected.
This list could be combined with current breadcrumbs.
<details>
<summary>Mockups:</summary>

![изображение](https://user-images.githubusercontent.com/10057327/140276439-59036431-595c-4267-9d17-f40e93cee068.png)

![изображение](https://user-images.githubusercontent.com/10057327/140276697-1c4e363d-9f5b-45f5-b8a6-16f64fa54f77.png)

</details>

**Describe alternatives you've considered**
Restore old category tree view.

**Do you want to develop this?**
Unfortunately it is above my head.

**Comment by matmair** [comment]
@SchrodingersGat @eeintech this is not assigned to a milestone. Are we interested in this or `wontfix`?

**Comment by eeintech** [comment]
I use this category tree a lot in `0.5.x` so yeah I would love to see it restored!

**Comment by SchrodingersGat** [comment]
I think we should add the category tree back in some form for 0.6.0

**Comment by SchrodingersGat** [comment]
@eeintech @matmair clearly this was a popular feature! Let's work out a nice way of integrating it back in.

**Comment by matmair** [comment]
@SchrodingersGat should we solve this with an api powered widget? That could be conditional on when the  bar is opened.

**Comment by SchrodingersGat** [comment]
Yes definitely should be loaded via the API

**Comment by matmair** [comment]
@SchrodingersGat https://www.jstree.com/docs/json/ combined with an API endpoint seems like a good option. If the tree is visible we can load the root + the current branch and if any other branch is opened the data in that branch is loaded on the fly via ajax.

**Comment by matmair** [comment]
Working on this feature rn
