### ISSUE TITLE
[FR] Enable to Print labels directly to a network-attached label printer for faster inventory management.

### ISSUE THREAD

**Issue by Oakman-Dev** [inventree/InvenTree#2255]
Enable to Print labels directly to a network-attached label printer for faster inventory management. (Maybe with something like https://github.com/mbello/ezprinting)

Example use case, Dymo LabelWriter 450 with a small Pi Zero W as a CUPS server. The reason for wanting it on the interface would be that I could trigger a print from my phone or tablet browser and maybe in the future as part of the mobile app without having to deal with system dialogs and drivers etc.

This could also be further extended to trigger automatic label printing based on barcode scanner.

Ref: https://github.com/inventree/InvenTree/issues/1762

**Comment by matmair** [comment]
hi @Oakman-Dev! Could you answer the below questions so have a better understanding about the FR?

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Examples of other systems**
Show how other software handles your FR if you have examples.

**Do you want to develop this?**
If so please describe briefly how you would like to implement it (so we can give advice) and if you have experience in the needed technology (you do not need to be a pro - this is just as a piece of information for scheduling).

**Comment by matmair** [comment]
@Oakman-Dev I would like to put this onto my personal dev roadmap but I need more info to do this.

**Comment by SchrodingersGat** [comment]
@Oakman-Dev this is now ready to go!

Label printing plugins are now directly supported.

[Read the documentation](https://inventree.readthedocs.io/en/latest/extend/plugins/label/)

[See an example](https://github.com/inventree/inventree-brother-plugin)
