### ISSUE TITLE
Escaping out of modals does not work anymore

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#2256]
**Describe the bug**
Escaping out of scan barcode modal does not work. The other ones seem to work.
![image](https://user-images.githubusercontent.com/42826581/140427865-07cb778d-4d53-478b-b88e-a831cfd04bba.png)

**Steps to Reproduce**

**Expected behavior**
When set in settings, it should escape out of the modal when pressing ESC key
![image](https://user-images.githubusercontent.com/42826581/140427663-1da3e05f-f152-4d33-87bd-102d2c543a33.png)

**Deployment Method**
- [ ] Docker
- [ ] Bare Metal

**Version Information**
![image](https://user-images.githubusercontent.com/42826581/140427177-70ad6473-1782-4cc6-a241-7266950101c6.png)

**Comment by matmair** [comment]
@SchrodingersGat any idea?
