### ISSUE TITLE
State of Translations

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2257]
I noticed that a lot of the translations do not have a lot of translated or approved strings -> should we maybe set a base level of translated strings before which we hide the language behind a 'not finished translations' selection/link?

@SchrodingersGat @eeintech

**Comment by SchrodingersGat** [comment]
@matmair not following what you mean here. Are you talking about in the user language selection box?

**Comment by matmair** [comment]
> @matmair not following what you mean here. Are you talking about in the user language selection box?

Yes, most languages are under 10% translated - that's not a really helpful choice.

**Comment by SchrodingersGat** [comment]
Understood. Yeah I agree that this would be a good idae.
