### ISSUE TITLE
[FR] Inline Markdown editor

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2264]
**Problem**
Currently, there is no preview for markdown in textareas that have that enabled.

**Suggested solution**
A fast search brought out this MIT-licensed library that could be loaded by class and seems to be enough but not too much:
https://github.com/Ionaru/easy-markdown-editor

**Describe alternatives you've considered**
Maybe this is not needed - could be beneficial for new users / not devs

**Do you want to develop this?**
yes

**Comment by matmair** [comment]
@SchrodingersGat @eeintech go ahead (once 0.6 is done) or close?

**Comment by SchrodingersGat** [comment]
Yeah, looks like a great idea for next release (0.7.0)

**Comment by SchrodingersGat** [comment]
@matmair just had a look at easy mde, looks like it will be a great fit :)
