### ISSUE TITLE
[FE] Get s-o line by order_id and barcode of location for   further allocation

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2276]
I'm using this system for creating some custom features, can you give me the rights for creating branches?

**Comment by matmair** [comment]
Hi @HelgiBergmann !
Only @SchrodingersGat has permission to touch the repo directly. Please [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the repo to your personal account and submit a PR with the features. We only have one running branch, you can find more information in the [contributing section](https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md).

**Comment by HelgiBergmann** [comment]
@matmair Ok, thanks.

**Comment by matmair** [comment]
@HelgiBergmann feel free to make new issues or ask here if you run into problems! We are happy to help.
Before you make huge changes maybe ask about what you want to change/implement - it is quite possible that there is a setting or config that enables what you want.

**Comment by HelgiBergmann** [comment]
@matmair  I am going to implement api_view endpoint which will take the QR of location and allocate stock item by it in the case when we have unique item stock in locations. It is a feature for employees who have to complete an order with barcode scanner and press the scan button.
Example:
 I have orders in my app => I go to the order line items screen =>  I press the scan button - QR location is scanned and returns the item inside of it, then I determine in which order I have this item line and push the item to allocate.

**Comment by matmair** [comment]
@HelgiBergmann we actually have that somewhat on the roadmap in #1246. I am pretty sure we would merge an endpoint like that. Please make sure to work on a separate branch so we can merge cleanly.

**Comment by SchrodingersGat** [comment]
@HelgiBergmann sounds interesting , perhaps this functionality is already available via the existing API endpoints?

Currently you can scan a barcode, send the barcode data to the `barcode` API endpoint. If the barcode corresponds to a stock location, the server will respond with the ID of the stock location which can then be used for further API requests.

If there is a specific feature or data missing from the API please let us know, I'd be happy to merge in additional functionality if it makes sense :)

**Comment by HelgiBergmann** [comment]
@SchrodingersGat Ok, I'll write it, then we look at it and make a decision about merging, or you will point me to a better approach=)

**Comment by matmair** [comment]
@HelgiBergmann could you maybe change the title to something more descriptive? And move the '[FR]' to the front, please.

**Comment by SchrodingersGat** [comment]
@HelgiBergmann for your reference we have recently updated the barcode scanning API for greatly improved functionality: https://github.com/inventree/InvenTree/pull/3640

Is this issue still active? If you are still interested in this please re-open the issue :)

**Comment by HelgiBergmann** [comment]
@SchrodingersGat another team have started  develop warehouse app, and they decided to use another app(
