### ISSUE TITLE
[FR] Turn off reports by default

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2278]
**Problem**
A lot of report buttons do nothing on a fresh install

**Suggested solution**
Make reports a global setting and disable them by default.

**Describe alternatives you've considered**
We could also do nothing

**Do you want to develop this?**
Yes

**Comment by matmair** [comment]
@SchrodingersGat thoughts?

**Comment by SchrodingersGat** [comment]
Yeah good point. Perhaps we could disable report buttons if there are no available report template associated with the view?

e.g. if there are no active "build order" report templates, then the "print report" button won't appear on the build page.

This may be in addition to a global "enable reporting" setting, which would remove the report buttons globally.

**Comment by matmair** [comment]
@SchrodingersGat do you want to dev this or should I?

**Comment by SchrodingersGat** [comment]
Happy either way, depends who has more time!

If you do decide to go ahead with it, please let me know first, there are some existing models I'd like to be able to hook into for this.

**Comment by SchrodingersGat** [comment]
Either way is fine, if you decide to go ahead with it let me know, there are some subtleties around reporting that I might need to point out :)

**Comment by matmair** [comment]
Ok, I will try to do this. Really need to better my understanding of the reporting features. What should I look out fr?
