### ISSUE TITLE
[FR] Notification centre

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2279]
**Problem**
All the notifications are just email and can get crowded

**Suggested solution**
Some kind of centre where past notifications can be viewed would be great.

**Examples of other systems**
Github would be a great example.

**Do you want to develop this?**
Yes

**Comment by SchrodingersGat** [comment]
Oh I like this idea a lot! 

I'm imagining a new tab in the "settings" window, where each user can see a history of notifications pertinent to them. Each notification could also be dismissed (deleted) by the user. The presence of any notifications could be indicated by a bell icon in the top-right corner of the navbar.

**Comment by matmair** [comment]
@SchrodingersGat I will try to implement this in a separate view to reduce the loading times.

**Comment by SchrodingersGat** [comment]
Yeah good idea. I think it would be great to add. A"bell" icon to the main navbar in the top right corner, and pressing on it pulls out a sidebar from the right of the screen.

Notifications for the logged in user are loaded via the API and can be dismissed (deleted) individually by the user

**Comment by matmair** [comment]
![grafik](https://user-images.githubusercontent.com/66015116/143686841-0152eb54-a32a-4ace-a071-dc0190accbb5.png)
