### ISSUE TITLE
[BUG] demo instance : spanish caption for search box

### ISSUE THREAD

**Issue by fenugrec** [inventree/InvenTree#2290]
Just trying out the online demo instance, and I noticed the search box says "Buscar". Took me a few moments to realize... that's spanish for "search" , not some type of road vehicle : )

Interestingly ,the other searchbox at the top of page shows "Search" as expected ! Both are shown here:

![buscar](https://user-images.githubusercontent.com/10098613/141213459-c971c16c-960f-4f4b-815a-5dfc7f32d0f8.jpg)

**Comment by SchrodingersGat** [comment]
Interesting.. not seeing that on my computer

![image](https://user-images.githubusercontent.com/10080325/141214036-30d7bdba-c50a-4c05-b403-8041c1f440dc.png)

**Comment by matmair** [comment]
@SchrodingersGat the user might be Spanish speaking.

@fenugrec if you are / your current config is set to Spanish please go to the user settings and change the language to English.

**Comment by SchrodingersGat** [comment]
Strangely if I set the language to spanish for the "reader" account, then I get the inverse problem

![image](https://user-images.githubusercontent.com/10080325/141214170-f9bfbc72-f81d-4dae-bbe1-2696b0d269e5.png)

**Comment by matmair** [comment]
After changing the language you might need to hard-refresh the page as localisations for bootstrap table are buffered

**Comment by matmair** [comment]
@SchrodingersGat seems to work on my instance (latest)
![grafik](https://user-images.githubusercontent.com/66015116/141214507-6f791d62-4eb3-49b2-a641-a31b3ab8e71f.png)

**Comment by matmair** [comment]
@fenugrec can we close this? If you want to improve the Spanish translation we are happy to merge contributions here: https://crowdin.com/project/inventree

**Comment by fenugrec** [comment]
> @SchrodingersGat the user might be Spanish speaking.

No, I should have specified, I am not hispanophone (just happen to know a few words) and have never set any computer, browser, or demo instance language settings. In fact I checked and ES isn't even listed in the settings pane of the demo

**Comment by fenugrec** [comment]
Ok, I clicked around in the demo, and I can only get this to appear when I select "Subcategories" as seen at the top left. If I go in Parts  , the text changes to the normal 'Search' string !

**Comment by fenugrec** [comment]
Can it be some of the server env "leaking" into the docker somehow and some strings getting translated differently ? This is so weird, if I go in the System Information pane everything is in english except the button which says "Cerrar" ( == Close, of course)

**Comment by matmair** [comment]
Can not reproduce:
![grafik](https://user-images.githubusercontent.com/66015116/141215261-b0d85eaa-bda4-489c-a485-c133651b05a7.png)
![grafik](https://user-images.githubusercontent.com/66015116/141215315-a877604d-e1eb-49a2-bef6-7d247192db5f.png)

All frontend server-side rendering is per-user per-session based so only the current user session can influence what language is used.

**Comment by fenugrec** [comment]
@matmair , tried "System information" ? instead of Version info which works normally here too

**Comment by matmair** [comment]
![grafik](https://user-images.githubusercontent.com/66015116/141215708-f7431d58-26f5-44af-a8c0-b091509f6e66.png)
![grafik](https://user-images.githubusercontent.com/66015116/141215724-ff18a75d-f4f8-4f45-b88b-6540c9da12fd.png)
@fenugrec yes

**Comment by fenugrec** [comment]
Anything I can look at using the browser dev console to shed some light ?

**Comment by matmair** [comment]
@fenugrec not really. Please try to log out and back in and check if it is there anyway.

**Comment by fenugrec** [comment]
> @fenugrec not really. Please try to log out and back in and check if it is there anyway.

Tried, no change. In a different browser (chromium, vs firefox earlier) I can't repro the issue...

**Comment by fenugrec** [comment]
Cannot reproduce any more today. I'll reopen if it pops up again...
