### ISSUE TITLE
[FR] setting which need a server restart

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2291]
@matmair I see that there are settings which need a server restart .

It might be useful to add a `SERVER_RESTART_REQUIRED` setting:

- If `true` then a "server restart is required - contact system administrator` banner displays on each page
- When server starts, this is forced to "false"
- Any setting which requires a restart can have the `requires_restart` property, and when it is saved, automatically sets the `SERVER_RESTART_REQUIRED` setting

Can add this as a separate PR if you like, to simplify review of this one?

_Originally posted by @SchrodingersGat in https://github.com/inventree/InvenTree/issues/2074#issuecomment-966187462_

**Comment by SchrodingersGat** [comment]
@matmair I'm happy to tackle this one :)
