### ISSUE TITLE
[FR] White labeling

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2301]
**Problem**
A lot of companies do not want it to be known which software they use. Either for not letting their competitor know what they use or for security reasons.

**Suggested solution**
Removing all tags and graphics that identify InvenTree would be a great option.
Also hiding normal debug and version info from users should be an option.

**Describe alternatives you've considered**
This is nice to have.

**Examples of other systems**
Most 'big vendor' solutions come with a very reduced custom login page (that they charge for like they invented HTML). That should be enough.

**Do you want to develop this?**
Yes

**Comment by SchrodingersGat** [comment]
Fair enough as a run-time configuration option!

**Comment by matmair** [comment]
> 
> 
> Fair enough as a run-time configuration option!

I would phase it sometime after 0.7 - could you maybe add a 1.0 milestone for that? There is a ton to do before that gets important.

**Comment by matmair** [comment]
@SchrodingersGat I would start working on an option to remove any and every mention of inventree and all logos if that is ok with you. Should I go ahead for 0.7.0 or is this better for later?

**Comment by SchrodingersGat** [comment]
0.7.0 would be fine for this
