### ISSUE TITLE
[FR] Basket for sales orders with qrcode

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2303]
**Is your feature request the result of a bug?**
No

**Problem**
Allocators employee: When I start to allocate items from stock I put them into a basket, then when all stock items are allocated I left this basket for packaging and take another empty basket to allocate stock items. 
Packaging employee: When the basket is completely allocated I read its barcode and take my allocated order from it to additional verification before shipping. Then order goes to shipped status - basket becomes empty status.

**Do you want to develop this?**
Yes, I do. 
Create model baskets, labels for baskets, each basket can have multiple orders, but each order can lay only in one basket.
The scanning barcode of the basket on my order page set the status of the basket to busy and set relation of so to this basket. Then packaging employer is scanning the barcode of the completed basket it opens a screen for verifying so items. When it's done that sales order ships. After that basket status becomes empty.

**Comment by matmair** [comment]
@SchrodingersGat that seems like a great use case for a plugin - seems like a very enhanced workflow.

**Comment by SchrodingersGat** [comment]
@HelgiBergmann the "basket" concept sounds very similar to a "location", but with some extra considerations. There is a similar PR here - https://github.com/inventree/InvenTree/issues/2058 - which has similar requirements.

How are you currently managing your orders in InvenTree?

**Comment by HelgiBergmann** [comment]
> @HelgiBergmann the "basket" concept sounds very similar to a "location", but with some extra considerations. There is a similar PR here - #2058 - which has similar requirements.
> 
> How are you currently managing your orders in InvenTree?

@SchrodingersGat Currently, no way=) I need some third party integrations, so we have customers who store their products in storage, then order generates from the third-party marketplace and passed to basket workflow=) so I have a lot of work to do with this=)  I Will try to add som compatibility features and make Polish translate but a little further=)

**Comment by HelgiBergmann** [comment]
https://github.com/inventree/InvenTree/pull/2482 here request, now I am fixing conflicts

**Comment by HelgiBergmann** [comment]
This iis done, wait for review=)
