### ISSUE TITLE
[Plugin] Plugin Settings should be in a separate table

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2306]
@matmair with the implementation of multiple plugins, there is a chance that settings could clash. We also don't want plugin code to accidentally overwrite global settings

I suggest we create a new "Settings" table, separate to "GlobalSettings" and "UserSettings", called "PluginSettings".

Where the UserSettings are separated by the user ID, PluginSettings are separated by the "plugin key" field (which maps to the existing PluginConfig table). 

This way, multiple plugins can have the same setting name (e.g. "API_KEY") without conflict.

Ref: https://github.com/inventree/InvenTree/pull/2074

**Comment by matmair** [comment]
> @matmair with the implementation of multiple plugins, there is a chance that settings could clash. We also don't want plugin code to accidentally overwrite global settings

This is by design so that plugins can override behaviour.
> 
> This way, multiple plugins can have the same setting name (e.g. "API_KEY") without conflict.

I think it would be beneficial if plugins can share settings but I can change the default behaviour.

**Comment by SchrodingersGat** [comment]
There is nothing stopping plugins from accessing global settings too, but by default I think the plugin settings should be separated.
