### ISSUE TITLE
[Plugin] How do plugins store persistent data?

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2307]
@matmair a question which I thought of after reading https://github.com/inventree/InvenTree/issues/2303

Should we consider how a plugin may store persistent data? Can it store custom data in the database for tracking long running operations?

I do not think this impacts your current work on https://github.com/inventree/InvenTree/pull/2074, but something we should discuss! Have you had any thoughts about this?

**Comment by matmair** [comment]
@SchrodingersGat in theory each plugin can save data in any way the want - the full potential of python is available. In practice AppMixins can generate their own models and use the same database as inventree so that would be the preferred way.

**Comment by SchrodingersGat** [comment]
@matmair how would the plugins manage database migrations, etc? Would we have to have some complex checking code to allow each plugin to maintain its own set of tables within the core database?

**Comment by matmair** [comment]
> 
> 
> @matmair how would the plugins manage database migrations, etc?

Each plugin behaves like a normal Django app. They come with normal migration sets that get run with the integrated migration mechanisms.
>
> Would we have to have some complex checking code to allow each plugin to maintain its own set of tables within the core database?

The integrated mechanisms are used. You can even have normal tests and run a GitHub action that pulls the latest and stable InvenTree docker images and runs the integation and unit tests through them.

**Comment by SchrodingersGat** [comment]
Fair enough, sounds very nice. We'll have to add some notes to the docs regarding plugins which have database integration like this.

**Comment by matmair** [comment]
> Fair enough, sounds very nice. We'll have to add some notes to the docs regarding plugins which have database integration like this. 

@SchrodingersGat writing a integration using AppMixin requires a strong understanding of django apps in general. I already have a general warning about that there but I can expand that.

**Comment by matmair** [comment]
@SchrodingersGat do you think something should be coded for this or is this more a docs - thing? Trying to clean up all plugin issues right now.

**Comment by SchrodingersGat** [comment]
We might (in the future) need a more long-form "how to make a plugin" section in the docs? I'd not worry about it yet, though. At least not until the plugin code is integrated and stable.
