### ISSUE TITLE
[FR] Safe loading of plugins

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2308]
@matmair this one is not vital to fix for https://github.com/inventree/InvenTree/pull/2074 - another one for later on.

Ideally, a 'broken' plugin (e.g. the unfinished shopify one) should not bring down the InvenTree instance. Perhaps, it might be possible to "safe load" each plugin and if an error is detected, it is shown in the plugin list as "not loaded due to error", with error information available.

I am not sure of the mechanics of this one, might be difficult to achieve.

**Comment by matmair** [comment]
> @matmair this one is not vital to fix for https://github.com/inventree/InvenTree/pull/2074 - another one for later on.
> 
> Ideally, a 'broken' plugin (e.g. the unfinished shopify one) should not bring down the InvenTree instance. Perhaps, it might be possible to "safe load" each plugin and if an error is detected, it is shown in the plugin list as "not loaded due to error", with error information available.
> 
> I am not sure of the mechanics of this one, might be difficult to achieve.

This is done for some things like navigation or settings but nearly impossible for the AppMixin. It is very difficult to catch buggy apps - I would have to research that a lot.

**Comment by matmair** [comment]
@SchrodingersGat is this blocking?

**Comment by SchrodingersGat** [comment]
No, not blocking. A thought for later attention
