### ISSUE TITLE
Plugin Support in Docker

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2309]
Once https://github.com/inventree/InvenTree/pull/2074 is merged, we need to consider how to support plugins in a docker configuration.

In a "production" docker setup, the python environment is setup internal to the docker container as part of the dockerfile.

Installing any further python plugins will not be "persistent" as they are stored temporarily within the container instance.

The "development" container, on the other hand, places the python environment in the mounted volume external to the docker container. This means that installation of plugins in the "development" container is persistent...

Maybe we can move to storing the python environment externally for the "production" docker setup also? Or some other solution.

Whatever the solution we will need to add documentation for installing plugins under docker

**Comment by matmair** [comment]
@SchrodingersGat already working on that; installed plugins can be saved to a text file (like the secret) and the system checks on startup if all plugins in the file are there. This requires an install mechanism which I already have running with PyPI but not custom registries - which is a must for private plugins.
Also live - reload should be comming today or tomorrow, I am working out the kinks at the moment.

**Comment by SchrodingersGat** [comment]
@matmair OK I'll wait to see what you have worked out :)

**Comment by SchrodingersGat** [comment]
@matmair what's the status of this? If you have not done this, I have an idea for implementation.

- Add a new file called "plugins.txt" (similar to "requirements.txt") which contains a snapshot of required plugins
- Can be stored anywhere, specified as PLUGIN_REQUIREMENTS_FILE in `settings.py`
- In docker setup, this would be in "/home/inventree/plugins.txt"
- Add a new invoke command "invoke plugins" which installs the plugins (into the virtual env) based on this file

Let me know if you have any objections otherwise I'll work on implementing something.
