### ISSUE TITLE
Should I install env in docker, if so, server or worker?

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2311]
For creating a new app
```
 docker exec -ti  inventree-dev-server    /bin/bash 
 manage.py startapp <app>
```
But in containers, there is no env and installed requirements.

**Comment by HelgiBergmann** [comment]
But there is no such command like startapp=)

**Comment by SchrodingersGat** [comment]
@HelgiBergmann what are you trying to achieve? 

If you follow the [docker setup guides](https://inventree.readthedocs.io/en/latest/start/docker/) that should be all the info you need.

**Comment by HelgiBergmann** [comment]
1. Create env && source to env
2. Pip install -r requirements.txt
3. Pip install Django
4. And finally python manage.py startapp <app>

**Comment by SchrodingersGat** [comment]
If you are trying to manage docker containers manually (i.e. not using the provided docker-compose files) then you can use the example files under the `./docker/` directory as a starting point.
