### ISSUE TITLE
[FR] Attachments for manufacturer parts

### ISSUE THREAD

**Issue by sur5r** [inventree/InvenTree#2314]
**Problem**
I would like to be able to attach datasheets, 3d models and similar files to *manufacturer parts*.

As a *part* can reference multiple *manufacturer parts*, I would like to keep my parts as generic as possible (like "100k 1% 1/10W 0603") and link multiple *manufacturer parts* and *supplier parts* to them. Datasheets, however, are manufacturer specific, so I would like attach them to the *manufacturer part*.

**Suggested solution**
Implement an attachment feature for *manufacturer parts* like the one for *parts*.

**Describe alternatives you've considered**
Keep my inventory as 1:1:1 mapping between part/supplier part/manufacturer part. But this makes the ability to link multiple *manufacturer parts* to a *part* unused. It also complicates managing exchangable/equivalent parts.

**Do you want to develop this?**
I would love to but I doubt my Python and or Django skills are good enough, yet. Given some pointers/hints I'm willing to give it a try, tought.

**Comment by eeintech** [comment]
Makes a lot of sense :+1:

**Comment by matmair** [comment]
@sur5r great idea. Do you want to dev it? Would be pretty straight forward as we already have the needed functions in the code so it more or less about adapting the example. We can provide you with pointers where the different components are.
@eeintech added the manufacturer parts if I remember correctly and I am happy to provide you a code-tour.

**Comment by sur5r** [comment]
Given the code-tour, I would definitely give it a try. Thank you very much for the offer. How would you want to do the tour? BBB session maybe? Also, how much time would you recommend for the code tour?

**Comment by SchrodingersGat** [comment]
Hi @sur5r thanks for the suggestion, it does make a lot of sense to add this feature

A brief rundown of what you'd need to do to implement this is below. Let us know if anything is missing or you need further pointers :)

The code base is getting pretty large now, so don't feel bad if it initially feels overwhelming!

## Branch Code

All features need to be on a separate code branch. Fork this repo, create a new feature branch.

## New Table / Model

You will need to create a new database table for storing attachments against a ManufacturerPart. This is actually pretty straightforward.

### Base Model

The base model which represents an attachment can be found here:

https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/InvenTree/models.py#L89

The key thing to note here is that the class is marked as "abstract" (line 195) which means that it does not represent a database table itself, but can be used as a starting point to define actual tables.

### Create new Class

In `InvenTree/company/models.py` you will need to create a new model "ManufacturerPartAttachment"

You can use the "PartAttachment" class as an example:

https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/part/models.py#L2152

You will need to add the following:

```python
def getSubdir(self):
    return os.path.join("manufacturer_part_files", str(self.manufacturer_part.id))
````

```python
manufacturer_part = models.ForeignKey(
    ManufacturerPart,
    on_delete=models.CASCADE,
    verbose_name=_('Manufacturer Part'),
    related_name='attachments'
)
```

This will create the "python" representation of the model, but there's nothing in the database yet.

#### Perform Migrations

In the shell (and with the virtual environment active) run:

```
invoke migrate
```

This will actually create the new database model.

#### Assign Permissions

You will then need to tell InvenTree which permissions are required for the new model.

Add 'company_manufacturerpartattachment' here:

https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/users/models.py#L97

## Add API Endpoints

We need to be able to access the attachments via the API.

There are two files we are interested in here:

- `./InvenTree/company/api.py` - defines the API endpoints
- `./InvenTree/company/serializers.py` - defines how the attachments are serialized

For this example, we will look at how the `PartAttachment` model is implemented:

### Create Serializer

Add a new serializer (to serializers.py) called `ManufacturerPartAttachmentSerializer`.

For reference, check out how this is done for [part attachments](https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/part/serializers.py#L72)

### Add Endpoints

#### List Endpoint

This is necessary to get a list of all manufacturer part attachments (and filter against a particular manufacturer part)

Using [PartAttachmentList](https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/part/api.py#L277) as a starting point, create a new API endpoint called ManufacturerPartAttachmentList

#### Detail Endpoint

This one is very simple. It allows individual attachments to be edited / deleted via the API.

Using [PartAttachmentDetail](https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/part/api.py#L294) as a starting point, create a new API endpoint called ManufacturerPartAttachmentDetail

### Add URLs

At the end of the file you will find a set of URL patterns which defines how the API endpoints are accessed.

Add the URLs here: https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/company/api.py#L399

Use the PartAttachment API URLs as a starting point:

https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/part/api.py#L1422

You will need to add two URLs, with the following aliases:

| Endpoint | Alias |
| --- | --- | --- |
| ManufacturerPartAttachmentList | api-manufacturer-part-attachment-list |
| ManufacturerPartDetail | api-manufacturer-part-attachment-detail | 

### Associate URL with model

Now that the URLs are created, we need to associate the "LIST" URL with the model.

Where you created the `ManufacturerPartAttachment` model, add the following method to the model class:

```python
    @staticmethod
    def get_api_url():
        return reverse('api-manufacturer-part-attachment-list')
```

## Add UI Elements

Next, you will need to add UI elements to display a table of attachments in the "manufacturer part" view:

### Sidebar Item

You will need to add a new "sidebar item" in the side navigation menu for the manufacturer part page. It must be added here:

https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/company/templates/company/manufacturer_part_sidebar.html#L6

### New Content Panel

Add a new content panel to the manufacturer part page here:

https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/company/templates/company/manufacturer_part_sidebar.html#L6

*Note: Content is arranged into separate "panels" which are selectively shown when the user clicks on an item in the navigation bar on the side of the screen.*

The following code is copied from the [part attachment panel](https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/part/templates/part/detail.html#L297):

```html
<div class='panel panel-hidden' id='panel-attachments'>
    <div class='panel-heading'>
        <div class='d-flex flex-wrap'>
            <h4>{% trans "Attachments" %}</h4>
            {% include "spacer.html" %}
            <div class='btn-group' role='group'>
                {% include "attachment_button.html" %}
            </div>
        </div>
    </div>
    <div class='panel-content'>
        {% include "attachment_table.html" %}
    </div>
</div>
```

Note that most of the work is done by the call to '{% include "attachment_table.html" %}'. You can see what that is actually doing by [looking at the template file](https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/attachment_table.html).

## Add Javascript

The final step is to call the javascript function to load the table data.

This code should run the first time that the "attachments" panel is displayed.

Use the [part attachment table](https://github.com/inventree/InvenTree/blob/4e09f0110b5d3ba280370a649406e9d2c3af74b4/InvenTree/part/templates/part/detail.html#L1008) code as a starting point. You will need to change some of the API URLs, etc. But it should be pretty straight forward.

-------

If I have missed out anything or something doesn't quite work, please let me know :)

**Comment by matmair** [comment]
@SchrodingersGat you were way faster than me 😇 I think that should be everything

**Comment by sur5r** [comment]
Wow @SchrodingersGat that's impressive. Thank you very much! Given the milestone: Is there a time frame already? I'm asking because it will take at least two weeks before I may have time to actually start working on this.

**Comment by matmair** [comment]
@sur5r the assigned milestone is the next but one feature release so there is a lot of time.

**Comment by matmair** [comment]
@sur5r still intrested?

**Comment by sur5r** [comment]
Yes, thanks for pinging. Sadly, I couldn't find time yet. I didn't mean to hog this, so if someone else want's to do it: Please do. Or move it to a later milestone so I don't block 0.7.0.

**Comment by matmair** [comment]
@sur5r no worries or hurries. I am just going through and checking if stuff was already done and missed by us. Greetings from snowy Austria

**Comment by sur5r** [comment]
So I finally found some time to start implementing this. Please see https://github.com/sur5r/InvenTree/tree/issue2314 for current state.

I guess some tests should be added as well before merging.

The Python side of things was straightforward indeed, the HTML/JS part took some time for me to understand.

What I'm still wondering is how the permission name is related to anything given those strings show up nowhere else.

**Comment by matmair** [comment]
@sur5r looks good in general. Feel free to open a (draft) PR so we can easily comment on the code. Nothing sticks out from a quick glance but maybe we find something in functional testing.
