### ISSUE TITLE
[FR]Exporting a BOM should include component costs

### ISSUE THREAD

**Issue by rgilham** [inventree/InvenTree#2316]
I am using Inventree to calculate the total cost of a BOM, however when the BOM is exported it does not include the current cost of the components used to make up the BOM.

The pricing is shown on the pricing page - however the CSV file does not contain this information.

I could develop this (I have made contributions to the project in the past) but not certain if I am missing this somewhere.

**Comment by matmair** [comment]
@rgilham in general pricing info is momentary so I would never use info in a static file but feel free to submit a PR. Should be pretty straightforward. Not sure how much overhead it adds computationally.

**Comment by SchrodingersGat** [comment]
Pricing info in the exported BOM is a great idea. I think we need to sort out the other pricing issues before we implement this, though.
