### ISSUE TITLE
Status  codes make me crazy

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2317]
Can someone explain how it works?)

For example, I see salesOrderStatusDisplay function in js code for render table, but nowhere see where it defines.

**Comment by HelgiBergmann** [comment]
Ok, somehow I do it similar like was, even don't wanna know details=)

**Comment by matmair** [comment]
@HelgiBergmann could you solve your problem? The Status codes are defined as mixins so they are always present in the mixins

**Comment by HelgiBergmann** [comment]
ok, thanks=)  Just for now, it works=) When I will need some additional manipulation, I will look at it closely=)

**Comment by matmair** [comment]
@HelgiBergmann if you have questions feel free to ask them. I think InvenTree is quite easy to extend
