### ISSUE TITLE
[FR] [plugin] ui integrated plugin installing

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2318]
What is missing now for this to be merge-ready?
...
- ui integrated plugin installing?
...

_Originally posted by @matmair in https://github.com/inventree/InvenTree/issues/2074#issuecomment-969349728_

**Comment by matmair** [comment]
This is easy to implement via subprocess 'pip install '... but there needs to be some infrastructure in place to get that package name.

Also there should be support for third party sources and signature verification.

**Comment by matmair** [comment]
@SchrodingersGat any pointers for turning an API endpoint into a form? Struggling with adding helper texts atm
https://github.com/inventree/InvenTree/blob/bff4623a15aeccbec1ea8e708c4d08842f7f45d4/InvenTree/plugin/api.py#L60-L76

**Comment by SchrodingersGat** [comment]
@matmair the API forms implementation is pretty complex, I must admit.

The client side stuff is all found in `forms.js`

If you want to add data about a field, it should be done either in the model, or in the serializer.

The API should automatically report (to the client) some metadata about the available fields, for example:

- **label**: The "name" of the field (translated)
- **help_text*: Extra description (translated) about the field

e.g.

![image](https://user-images.githubusercontent.com/10080325/142333329-248d0175-33cb-4d72-be32-e020e45662dd.png)

The "metadata" is read out by performing an OPTIONS request to the API endpoint, e.g.

![image](https://user-images.githubusercontent.com/10080325/142333487-6ecd010b-f331-4086-8065-2a6e36d481f6.png)

This provides the client (i.e. javascript) all the information it needs to render the forms.

Read the code here to see how the metadata is constructed:

https://github.com/inventree/InvenTree/blob/master/InvenTree/InvenTree/metadata.py

That should be sufficient background - let me know if you have any specific questions!

**Comment by matmair** [comment]
@SchrodingersGat is the confirm button on the forms not submitted to the api?

**Comment by SchrodingersGat** [comment]
Correct, it only enables the "submit" button
