### ISSUE TITLE
[BUG] Unable to start docker stack: No module named common.tasks

### ISSUE THREAD

**Issue by lettore** [inventree/InvenTree#2321]
**Describe the bug**
Docker container start but it fails with this error log:
```
/home/inventree/data/config.yaml exists - skipping
Waiting for database...
Database connection sucessful!
Base currency changed from USD to EUR
Updating exchange rates from https://api.exchangerate.host/latest
Using base currency 'EUR'
00:12:46 [Q] INFO Q Cluster hydrogen-pennsylvania-tennessee-berlin starting.
00:12:46 [Q] INFO Process-1:1 ready for work at 17
00:12:46 [Q] INFO Process-1:2 ready for work at 18
00:12:46 [Q] INFO Process-1:3 ready for work at 19
00:12:46 [Q] INFO Process-1:4 ready for work at 20
00:12:46 [Q] INFO Process-1:5 monitoring at 21
00:12:46 [Q] INFO Process-1 guarding cluster hydrogen-pennsylvania-tennessee-berlin
00:12:46 [Q] INFO Process-1:6 pushing tasks at 22
00:12:46 [Q] INFO Q Cluster hydrogen-pennsylvania-tennessee-berlin running.
00:13:11 [Q] INFO Process-1:1 processing [sink-hotel-hydrogen-october]
00:13:11 [Q] INFO Process-1:2 processing [avocado-london-spaghetti-arkansas]
00:13:11 [Q] INFO Process-1:3 processing [fifteen-angel-colorado-cola]
00:13:11 [Q] ERROR Failed [sink-hotel-hydrogen-october] - No module named 'common.tasks'
00:13:11 [Q] ERROR Failed [avocado-london-spaghetti-arkansas] - module 'InvenTree.tasks' has no attribute 'delete_old_error_logs'
00:13:11 [Q] ERROR Failed [fifteen-angel-colorado-cola] - module 'InvenTree.tasks' has no attribute 'delete_old_error_logs'
```

**Deployment Method**
- [ x] Docker
- [ ] Bare Metal

**Version Information**
Docker 0.5.4

**Comment by SchrodingersGat** [comment]
Have you recently updated the docker instance? It might be that the "server" and "worker" containers are running different images?

Are you running docker-production or docker-development?

**Comment by lettore** [comment]
Docker-production, server and worker are running the same version of the
image.
I can access the web interface and all appears to work but the container
log is full of the above error at every web page request.

Il Gio 18 Nov 2021, 01:33 Oliver ***@***.***> ha scritto:

**Comment by SchrodingersGat** [comment]
Ok, so version `0.5.4` does not have `common.tasks.py` and `delete_old_error_logs` was not yet implemented.

Did you at some stage install a *newer* version and then go back to 0.5.4?

**Comment by lettore** [comment]
There's no newer tag on Docker Hub, but before I used the latest tag, and
after I saw it was not working I went back to 0.5.4. The mounted directory
is fresh new, just the database is the same.

Il giorno gio 18 nov 2021 alle ore 21:56 Oliver ***@***.***>
ha scritto:

**Comment by SchrodingersGat** [comment]
Ok, that makes sense. It has added some scheduled tasks from the newer version.

It is fine, it will keep running OK (just with error messages in the logs)

If you want you can delete the scheduled tasks from the admin view:

![image](https://user-images.githubusercontent.com/10080325/142514832-04c5db4d-465b-4728-8d71-06e010e9e473.png)
