### ISSUE TITLE
[FR] Demo Instance

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2322]
Add new "features" which only are available on the demo instance

- [x] Add link to demo docs on "login" page
- [x] Remove ability to change password
- [x] Remove access to "admin" page

**Comment by matmair** [comment]
@SchrodingersGat an option for a permanent message on all pages and a separate one on the login windows would be nice too. Also for general deployments so admins can communicate information to all users.

**Comment by SchrodingersGat** [comment]
Good point. In my implementation here I'll try to make it as generic as I can.

Maybe a section for "banner" messages which cannot be removed.
