### ISSUE TITLE
[FR][plugin] Verify packages before installing

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2324]
**Problem**
Currently if a package index is breached malicious packages could be updated into the plugin system. This is somewhat the case with all python packages.

**Suggested solution**
Add signature checking in the install step:
https://serverfault.com/questions/896228/how-to-verify-a-file-using-an-asc-signature-file

**Describe alternatives you've considered**
It seems to be an accepted practice to not check this.

**Do you want to develop this?**
Yes

**Comment by SchrodingersGat** [comment]
Is this a workable solution for the baseline packages too? i.e. requirements.txt

**Comment by matmair** [comment]
Reference:
https://dzone.com/articles/package-signing-in-pip-it-works-in-a-roundabout-so


For plugin workflow:
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

Store certificate as secret:
https://github.community/t/secret-ability-to-store-certificates/16930/4

Versioning assitant (important to easily compare if the right thing was verified):
https://pypi.org/project/setuptools-scm/

**Comment by matmair** [comment]
> Is this a workable solution for the baseline packages too? i.e. requirements.txt

In theory yes. To be honest supply chain safety is a bit a stepchild with python packages. Twine / Pypa is a great eco-system but there is a lot if trust in central entities.
We should be fine with the current way but it does not take too much to make it better for plugins at least. The requirements should be fine as long as the version is fixed in the txt. You can not re-release a package version once it is on pypi ever.

A lot of devs just do not care a lot about this stuff (adoption of commit-signing for example) so a few nerds like me complain.

**Comment by matmair** [comment]
No real community standard for this and only twine supports it. The code supply chain is a mess, perfection is not attainable - closing.

**Comment by SchrodingersGat** [comment]
Fair call @matmair :)

**Comment by matmair** [comment]
@SchrodingersGat not for a lack of trying. The features I was building off of are being sunsetted.

Users that need compliance will have to pay a Sec-Ops firm to provide them that as a service - we can not build in features for compliance if the underlying packages are just unverified by the registry.
Sadly building InvenTree to be just drop-in for ISO 27001 certified orgs is not possible currently although it still is a goal of mine.
