### ISSUE TITLE
[FR] Confirm to W293

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2335]
@SchrodingersGat I think we should confirm to W293 and probably review all exceptions in the setup.cfg:
https://github.com/inventree/InvenTree/blob/6a235c9f15d3731a736148eb25fedaaa2921e39d/setup.cfg#L2-L14

especially naming conventions. 0.6.0 is already a major refactor so we could fix those things as well. I would volunteer to do this.

**Comment by SchrodingersGat** [comment]
Sure, let's look into this. If you are going to submit PR's against this, please keep each rule (e.g. W293) in its own PR and we'll run through them one at a time.

**Comment by matmair** [comment]
@SchrodingersGat any rules you know you want to have ignored? Line length maybe?

**Comment by SchrodingersGat** [comment]
Yeah I think keep ignoring line length.
