### ISSUE TITLE
[FR] Convert "data import" functionality to API

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2341]
The current "import" features (e.g. BOM import) are pretty clunky, and notably, extremely slow.

In particular, the BOM importer is extremely slow because it renders everything server side, rather than "on demand" lookup of related fields.

It would be far better to use the existing DRF API and perform data upload via JSON serializers.

- Much more efficient than HTTP forms
- Reduce code duplication, focus on API support

[django-data-wizard](https://github.com/wq/django-data-wizard) looks like it might be a very good tool to use here.

Ref: https://github.com/inventree/InvenTree/issues/2331

**Comment by matmair** [comment]
@SchrodingersGat maybe a refactor of all import code would be great, I feel like there is a lot more code then necessary in each definition. Although the current matching is quite flexible. Some test coverage might be nice thought.

**Comment by SchrodingersGat** [comment]
Note that this has now been implemented for BOM data import - https://github.com/inventree/InvenTree/pull/2603

This concept needs to be abstracted, and used for other data import functions (e.g. "part" data)

**Comment by SchrodingersGat** [comment]
Replaced by #3101
