### ISSUE TITLE
[BUG] parts of interface can not be translated

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2347]
**Describe the bug**

Sidebar items and maybe also some newer modals can not be translated due to the way they call the trans function.

**Steps to Reproduce**

1. Open settings in german. The current merged translation have 95% coverage but the sidebar items are mainly english

**Expected behavior**

German

**Deployment Method**
- [x] Docker
- [x] Bare Metal

**Version Information**

latest

**Comment by matmair** [comment]
I will fix this tomorrow, just added this so i do not forget

**Comment by SchrodingersGat** [comment]
Interesting. Is it only the sidebar items?

**Comment by matmair** [comment]
@SchrodingersGat seems like it
