### ISSUE TITLE
[BUG] 502 Bad Gateway when trying to access WebUI (Docker)

### ISSUE THREAD

**Issue by Wystik-69** [inventree/InvenTree#2352]
Hi,
 I'm trying to install InvenTree since this morning with docker (Unraid Server), On Unraid, we don't have the docker compose, so I created two dockers, one containing InvenTree and another containing the Nginx, both are in bridge access. InvenTree was installed without too much difficulty however no way to access the web interface, I get a 502 error and the Nginx logs indicate: `"[error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream"`

**Concerning the docker :** 

- InvenTree 
![image](https://user-images.githubusercontent.com/63404022/143036368-b06a2bc2-ff03-4c7c-9b57-bd1df7f9abcc.png)
- Nginx
![image](https://user-images.githubusercontent.com/63404022/143035785-3f5a698d-b7b2-4d40-915b-85b7f0ac517e.png)

**I've used the Nginx conf files given on the repo :** 
server {
    # Listen for connection on (internal) port 80
    listen 80;
    server_name 192.168.0.50;
    location / {
        # Change 'inventree-server' to the name of the inventree server container,
        # and '8000' to the INVENTREE_WEB_PORT (if not default)
        proxy_pass http://192.168.0.50:8181;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;

        proxy_redirect off;

        client_max_body_size 100M;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_request_buffering off;

    }

    # Redirect any requests for static files
    location /static/ {
        alias /var/www/static/;
        autoindex on;

        # Caching settings
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }

    # Redirect any requests for media files
    location /media/ {
        alias /var/www/media/;

        # Media files require user authentication
        auth_request /auth;
    }

    # Use the 'user' API endpoint for auth
    location /auth {
        internal;

        proxy_pass http://192.168.0.50:8181/auth/;

        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }

}

**Logs for the InvenTree Docker Starting :** 

`"Starting background tasks...
Loading action plugins...
Discovered 1 action plugins:
13:23:07 [Q] INFO Q Cluster four-east-wisconsin-pennsylvania starting.
13:23:07 [Q] INFO Process-1:1 ready for work at 18
13:23:07 [Q] INFO Process-1:2 ready for work at 19
13:23:07 [Q] INFO Process-1:3 ready for work at 20
13:23:07 [Q] INFO Process-1:4 ready for work at 21
13:23:07 [Q] INFO Process-1:5 monitoring at 22
13:23:07 [Q] INFO Process-1 guarding cluster four-east-wisconsin-pennsylvania
13:23:07 [Q] INFO Q Cluster four-east-wisconsin-pennsylvania running.
13:23:07 [Q] INFO Process-1:6 pushing tasks at 23
13:23:36 [Q] INFO Enqueued 1
13:23:36 [Q] INFO Process-1 created a task from schedule [InvenTree.tasks.delete_successful_tasks]
13:23:36 [Q] INFO Enqueued 2
13:23:36 [Q] INFO Process-1 created a task from schedule [InvenTree.tasks.check_for_updates]
13:23:36 [Q] INFO Enqueued 3
13:23:36 [Q] INFO Process-1 created a task from schedule [InvenTree.tasks.heartbeat]
13:23:36 [Q] INFO Enqueued 4
13:23:36 [Q] INFO Process-1 created a task from schedule [InvenTree.tasks.update_exchange_rates]
13:23:36 [Q] INFO Enqueued 5
13:23:36 [Q] INFO Process-1 created a task from schedule [InvenTree.tasks.delete_expired_sessions]
13:23:36 [Q] INFO Enqueued 6
13:23:36 [Q] INFO Process-1 created a task from schedule [stock.tasks.delete_old_stock_items]
13:23:36 [Q] INFO Process-1:1 processing [grey-dakota-two-hamper]
13:23:36 [Q] INFO Process-1:2 processing [floor-snake-papa-cold]
13:23:36 [Q] INFO Process-1:3 processing [red-floor-louisiana-mississippi]
13:23:36 [Q] INFO Process-1:4 processing [hawaii-sodium-lima-ten]
Could not perform heartbeat task - App registry not ready
13:23:36 [Q] INFO Process-1:3 processing [low-music-undress-magnesium]
13:23:36 [Q] INFO Process-1:1 processing [virginia-pennsylvania-seventeen-yankee]
Deleting 0 expired sessions.
Updating exchange rates from https://api.exchangerate.host/latest
Using base currency 'USD'
13:23:36 [Q] INFO Processed [red-floor-louisiana-mississippi]
13:23:36 [Q] INFO Processed [grey-dakota-two-hamper]
13:23:36 [Q] INFO Processed [low-music-undress-magnesium]
13:23:36 [Q] INFO Processed [virginia-pennsylvania-seventeen-yankee]
Latest InvenTree version: '0.5.4'

13:23:37 [Q] INFO Processed [floor-snake-papa-cold]
13:23:37 [Q] INFO Processed [hawaii-sodium-lima-ten]
13:35:08 [Q] INFO Enqueued 7
13:35:08 [Q] INFO Process-1 created a task from schedule [InvenTree.tasks.heartbeat]
13:35:08 [Q] INFO Process-1:3 processing [six-utah-sodium-seven]
Could not perform heartbeat task - App registry not ready
13:35:08 [Q] INFO Processed [six-utah-sodium-seven]"`

**Deployment Method**
- Docker on Unraid Server

Thanks for Your Help !

**Comment by matmair** [comment]
Hi @Wystik-69 as far as I can see the logs are just from the worker. The InvenTree image can either be started as a webserver or as a background d worker. Maybe that is your problem.

**Comment by matmair** [comment]
@SchrodingersGat @nwns any idea?

**Comment by Wystik-69** [comment]
Thanks @matmair first problem solved I didn't paid attention to this detail at all, my docker was alone and running with the post "Invoke Worker" only., now I can access the WebUI directly from the Inventree docker but not passing through the nginx docker, which is not a bad thing, I would have one less docker to manage, will it be a problem if I use it directly without Nginx or do I have to use Nginx? Because for the moment I still have a 502 problem.

**Comment by Wystik-69** [comment]
Another question what is the default login/password, because the invoke superuser didn't work at all for me.

**Comment by nwns** [comment]
@Wystik-69 I don't believe InvenTree loads a default username and password unless you are loading one of the demo datasets.  The `invoke superuser` creates the first user on the system.

What installation instructions are you following?  Which database server do you have configured?

**Comment by Wystik-69** [comment]
I've followed the docker guide install from the doc, I use MariaDB so I've configured the docker to work with mysql. Invoke user has worked, so it's ok for the login password. 

For now everything is ok, Nginx keep showing the 502 gateway error.

**Comment by matmair** [comment]
@Wystik-69 Nginx serves as a proxy. You do not really need it but it enhances the performance and takes care of serving static content. I would not recommend exposing your instance to the internet without a proxy and some kind of ddos protection (Cloudflare for example).

**Comment by Wystik-69** [comment]
I have a caddy server, I will put the instance behind it, I also have a CloudFlare plan over the Caddy, so I suppose it will be ok, I was just woried about security and stability concerning the docker and if it must run obligatory behind Nginx or not. Many Thanks for your help guys 👍

**Comment by matmair** [comment]
@Wystik-69 can we close this now?

**Comment by Wystik-69** [comment]
Yes, I think so :) I will try the system tomorrow, I hope it will work like a charm, for now I'm translating InvenTree in French on crowdin because no one has done it lol !
