### ISSUE TITLE
[FR] testing language

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2353]
> you should really try replacing all translation strings with xxx

Can we make a "testing" language which does this automatically?

_Originally posted by @SchrodingersGat in https://github.com/inventree/InvenTree/pull/2350#issuecomment-976098066_

**Comment by SchrodingersGat** [comment]
Ideally this language would only be available if "DEBUG" mode is ON?

**Comment by matmair** [comment]
@SchrodingersGat i already started dev on this and my idea would be:
- new invoke command 'test-translation'
- creates new language with the 'xx' lang-code
- replaces all translations for that language with 'xxx'
- set default language to 'xx'
- starts the dev server
- 'xx' locale gets added to gitignore so we nothing will ever leak out
