### ISSUE TITLE
Translation Stats in Demo Instance

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2364]
The translations stats say 0% translation for all languages in the demo instance:

![image](https://user-images.githubusercontent.com/10080325/143500672-e540ffaa-b9a6-4932-9e3e-0a71f07b3d18.png)

The `.json` stats file gets exported locally to the code directory. However this is inside a docker container and does not "persist" past a particular container run.

### Proposed Solutions

1. Store JSON stats file in a persistent (local storage) directory 
2. Run translation stats script each time the server boots (so the file is always updated)
3. Calculate translation stats as part of "settings.py" (and don't store to an external file at all)

@matmair any thoughts on how we could solve this?

**Comment by matmair** [comment]
@SchrodingersGat calculating the stats can be expensive as gnu gettext is called. I strongly suggest just fixing the storage location / bringup of the instance as the locales file is a very compute optimised action.
Translations can not be changed easily by the admin so the files should not change often.
