### ISSUE TITLE
[FR] Plugins - Internal Hooks

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2377]
The existing (or planned) plugin architecture supports external webhooks. External stimuli can initiate an action on the server via the API.

We should also add facility for "internal" hooks, which plugins can register with to perform actions.

For example, a "part.created" hook is called whenever a new part is created in the database.

Any plugin can register a callback function for "part.created" which gets called with the new part as an argument.

This can then be used (by plugin code) to push notifications out to external applications, etc, etc.

**Comment by SchrodingersGat** [comment]
@matmair thoughts here? I think this is a distinct idea from the external "webhooks" functionality but let me know what you think.

**Comment by matmair** [comment]
@SchrodingersGat I thought we could just use signals for that. I am still refactoring the notification stuff and thought about adding a function that can be called there. But some general hooks would be possible for sure. Maybe we could also use signals for that?

**Comment by SchrodingersGat** [comment]
Definitely signals would work here.

**Comment by matmair** [comment]
@SchrodingersGat this is implemented with the event, right?

**Comment by SchrodingersGat** [comment]
Ah, yep, good point!
