### ISSUE TITLE
[BUG] JS column table

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2379]
Then load inventree table, in columns I should set two times column "reference" for sales order because if I set it  once it becomes visible false, don't know why
![image](https://user-images.githubusercontent.com/78436722/143864895-c2df918d-b3b7-4743-a313-84b22eb29793.png)

For  sales order was added in model relationship field basket

**Comment by SchrodingersGat** [comment]
@HelgiBergmann sorry, I am not sure that I understand what you are asking here.

Are you trying to add new columns to the sales order table? Or are you describing a bug in the current operation of the software?

**Comment by HelgiBergmann** [comment]
@matmair 
js - https://github.com/HelgiBergmann/InvenTree/blob/ae8424fee3cdec0811c99ddd81d468746c24c7e4/InvenTree/templates/js/translated/order.js#L981
model - https://github.com/HelgiBergmann/InvenTree/blob/ae8424fee3cdec0811c99ddd81d468746c24c7e4/InvenTree/order/models.py#L842 , added basket field

**Comment by matmair** [comment]
@HelgiBergmann Have you checked if the column is hidden? I get two columns for reference if I run your code.

**Comment by HelgiBergmann** [comment]
@matmair I going to find the problem, but a little later, now it is a little ugly to have duplicated column, but it  works  at least

**Comment by matmair** [comment]
Removing `bug` tag as it seems to be not related to mainline InvenTree

**Comment by SchrodingersGat** [comment]
@HelgiBergmann please let us know if you need any further assistance on this

**Comment by HelgiBergmann** [comment]
@SchrodingersGat I will check it on Monday.

**Comment by HelgiBergmann** [comment]
Strange but when doubling column in js only one column appears in html. Then I  deploy to production doubling also appears in HTML. So I think the problem is in the local SQLite db.

**Comment by matmair** [comment]
@HelgiBergmann bootstraple table has a unique constraint for column keys

**Comment by HelgiBergmann** [comment]
@matmair has been fixed after merging with the master branch. wheee=)
