### ISSUE TITLE
[FR] Search Results "mega menu"

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2384]
The search-bar "quick results" only searches parts.

It may be useful to have multiple columns in a "mega menu" style, where new columns are added to display results for stock items, purchase orders etc.

Each column can be individually enabled by the user if they want to show results for that category.

**Comment by r0l1** [comment]
It would be great to be able to search by MPN.

**Comment by matmair** [comment]
@SchrodingersGat do you want to have that menu in the quick search dropdown or in the full view?

**Comment by SchrodingersGat** [comment]
My idea would be to add new columns to the quick search dropdown, thusly:

![image](https://user-images.githubusercontent.com/10080325/144133891-48117cd2-daa8-48ec-82cf-9e62f7c80e9c.png)

**Comment by matmair** [comment]
We will have to check how efficient the Search API is with the number of requests increasing.
