### ISSUE TITLE
Existing Purchase Order not displayed

### ISSUE THREAD

**Issue by jpeterse** [inventree/InvenTree#2386]
Just completed a new install.
I'm finding that on the regular site, an purchase order I entered is not shown. A "Loading Data" message is shown instead.
I don't see any obvious errors in the console output.
If I enter /1/ at end of URL, the purchase order is shown.

Background of steps before error occurred.
I performed the initial setup steps.
Entered an initial supplier, part and purchase order
I then wanted to see how the default demo data looked like
So I exported the data and deleted the database
Reinitialized the database
Loaded the demo data set.
After looking it over I then deleted the database
Created a new database and initialized it.
performed the invoke migrate and invoke superuser
imported the exported data from my original data entry.

Now the default page at "/order/purchase-order" does not display the purchase order, but the admin page does, and it comes up as well, when I go to /order/purchase-order/1/

**Comment by SchrodingersGat** [comment]
I can confirm that this is a bug on latest master.. Will get a fix out ASAP

**Comment by SchrodingersGat** [comment]
Very simple fix for a very silly bug. Will be merged in soon. Thanks for reporting!

**Comment by jpeterse** [comment]
wow - talk about fast support :-)

**Comment by SchrodingersGat** [comment]
we aim to please :D
