### ISSUE TITLE
[Question] New Docker Release

### ISSUE THREAD

**Issue by r0l1** [inventree/InvenTree#2389]
When can we expect the next docker release? Eager to try the new features!

**Comment by matmair** [comment]
The latest tag is always the current master. As we are going through major refactoring, a new UI framework and a lot of changes in many components it will take time till the next release is happening. In the end @schrodingersGat will have to decide but I think it will take at least a few weeks.

**Comment by matmair** [comment]
@r0l1 I would also never test in a production environment. I recommend spinning up a second environment or just click the magic gitpod.io button on each PR, that launches a free environment in which the server set itself up in few minutes including a full test-dataset.
