### ISSUE TITLE
Feature or Bug. Items allocation.

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2390]
Why we can allocate more quantity than line items has?

**Comment by lookme2** [comment]
I am seeing this also.  I reported it but was asked for some screen shots.  I'm not in my office so cant do that yet.  Seems to only happen when you use the "Auto Allocate" button.

**Comment by SchrodingersGat** [comment]
Duplicate of https://github.com/inventree/InvenTree/issues/2380
