### ISSUE TITLE
[BUG] Exception thrown when opening part "'NoneType' object has no attribute 'strftime'"

### ISSUE THREAD

**Issue by jpeterse** [inventree/InvenTree#2391]
I entered a new part yesterday, complete with picture and all. Attached it to an order, and issued the order.
I.e. on all accounts the part was fine yesterday.
I started the server again today, and now opening the part overview page, I get "'NoneType' object has no attribute 'strftime'".
I have attached the traceback.

I can open the part in the admin site. There it looks fine.
 I tried updating an attribute on the part there and save, but it didn't resolve the issue.

How the part got into this state, I don't know. Unfortunately, I can't retrace the steps I may have done to cause this issue.

I'm running the main branch on bare metal.

[traceback.txt](https://github.com/inventree/InvenTree/files/7627107/traceback.txt)

**Comment by SchrodingersGat** [comment]
Thanks for reporting @jpeterse I'll look into it
