### ISSUE TITLE
[BUG] Missing encoding of Description field when creating new part

### ISSUE THREAD

**Issue by jpeterse** [inventree/InvenTree#2392]
When creating a new part, if a special characters is added in the description field, say a 'Ω' character, the server throws an exception.
I'm running the main branch on bare metal.
![createPartDia](https://user-images.githubusercontent.com/8325689/144087045-5a76be0b-a87c-481f-a626-81a0b25974a3.png)
![exception thrown](https://user-images.githubusercontent.com/8325689/144087066-3681d5b1-4407-405d-bf5a-a2d01310f733.png)
l.

**Comment by SchrodingersGat** [comment]
What database backend are you running?

Can you please share the error message? Historical error messages are available at `/admin/error_report/error/`

**Comment by jpeterse** [comment]
I'm running Maria DB
mysql  Ver 15.1 Distrib 10.3.31-MariaDB

I don't see an error that corresponds with the timestamp in the history error log.
Even when recreating the error, I don't see a new entry appear.
But this what I see on the console:

[backtrace.txt](https://github.com/inventree/InvenTree/files/7629321/backtrace.txt)

**Comment by matmair** [comment]
@jpeterse what collation and character set is set on your database?

**Comment by jpeterse** [comment]
Ohh, it's set to latin1

DEFAULT_CHARACTER_SET_NAME: latin1
    DEFAULT_COLLATION_NAME: latin1_swedish_ci

Let me try and drop it and recreate it with UTF8

**Comment by jpeterse** [comment]
Yes, fixed by switching to
DEFAULT_CHARACTER_SET_NAME: utf8
    DEFAULT_COLLATION_NAME: utf8_general_ci
 
Honestly don't know why the defaults of mariaDB install was set to Latin1.
I'm located in the US, and don't have any settings that are latin1 based normally. Maybe the install instructions should include the full syntax for creating the data, including the character set and collate.

**Comment by matmair** [comment]
@jpeterse if I got a euro for each time I had that problem I would be rich. It's so typical.
The Swedish collation was/is often used to support germanic languages, maybe you followed a tutorial that was optimised for that.

So can we close this issue?

**Comment by SchrodingersGat** [comment]
Thank @jpeterse we'll add that to the docs

**Comment by matmair** [comment]
@jpeterse if you ever encounter that error again: you do can switch both character set and collation on a database while it is running in mysql, oracle and mariadb - data that was mangled on input will still be corrupt but it could save you hours of downtime.

**Comment by jpeterse** [comment]
yes, but I wanted to do a clean test for y'all.  :-)
I've re-imported my data now, I'll keep eye on it, that those entries still might be corrupt.
