### ISSUE TITLE
MariaDB config file not found

### ISSUE THREAD

**Issue by Matthewmads** [inventree/InvenTree#2393]
**Describe the bug**
Working on setting up a production environment on a fresh install of ubuntu 20.04.3. Went thru the steps listed on the readthedocs site (using mysql/MariaDB). When I enter the "pip3 install mysqlclient mariadb" command (in the virtual environment) I get the following ...

`
(env) inventree@Meta:~$ pip3 install mysqlclient mariadb
Collecting mysqlclient
  Using cached mysqlclient-2.1.0.tar.gz (87 kB)
Collecting mariadb
  Using cached mariadb-1.0.8.zip (85 kB)

 ERROR: Command errored out with exit status 1:
     command: /home/inventree/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xibnrply/mariadb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xibnrply/mariadb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xibnrply/mariadb/pip-egg-info
         cwd: /tmp/pip-install-xibnrply/mariadb/
    Complete output (17 lines):
    /bin/sh: 1: mariadb_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xibnrply/mariadb/setup.py", line 26, in <module>
        cfg = get_config(options)
      File "/tmp/pip-install-xibnrply/mariadb/mariadb_posix.py", line 59, in get_config
        cc_version = mariadb_config(config_prg, "cc_version")
      File "/tmp/pip-install-xibnrply/mariadb/mariadb_posix.py", line 28, in mariadb_config
        raise EnvironmentError(
    OSError: mariadb_config not found.

    Please make sure, that MariaDB Connector/C is installed on your system.
    Either set the environment variable MARIADB_CONFIG or edit the configuration
    file 'site.cfg' and set the 'mariadb_config option, which should point
    to the mariadb_config utility.
    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>
    provides latest stable releease of Connector/C.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
'

I am somewhat new to python env so I'm unsure of where to look for the specified config files or how they relate to the environment variables. 

**Expected behavior**
Unsure of expected behavior, When I move on to the next steps (creating database and user within MySQL) the database is created but I get the following when trying to grant permissions...

' 
mysql> CREATE USER 'inventree'@'%' IDENTIFIED WITH mysql_native_password BY 'doors2021!';
Query OK, 0 rows affected (0.12 sec)

mysql> GRANT ALL ON inventree.* TO 'djangouser'@'%';
ERROR 1410 (42000): You are not allowed to create a user with GRANT
'

**Deployment Method**
- [ ] Bare Metal - Ubuntu 20.04.3

**Comment by SchrodingersGat** [comment]
> Please make sure, that MariaDB Connector/C is installed on your system.

Did you complete this step?

**Comment by Matthewmads** [comment]
I wasn't sure if that was specific or just a generic message. I tried to download and got the following. Not sure if my syntax is correct.

I used 
`sudo apt install https://downloads.mariadb.com/Connectors/c/connector-c-3.2.5/mariadb-connector-c-3.2.
5-ubuntu-impish-amd64.tar.gz.asc` (tried with both the tar.gz.asc and the tar.gz filetypes).

to try to download the connector but got this error, 

`Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package https://downloads.mariadb.com/Connectors/c/connector-c-3.2.5`

I also found an article that mentioned these packages 
'sudo apt-get install libmariadb3'
'sudo apt-get install libmariadb-dev'

but I can't tell whether or not they contain the c connector. 

I'm somewhat new to linux so any insight you can provide is helpful. Thanks

**Comment by matmair** [comment]
@Matthewmads 
Files with `.asc` file ending contain information to verify that a file was signed by a specific entity or person. It is part of PGP / GPG a good answer with explanations how that would work is here: https://serverfault.com/questions/896228/how-to-verify-a-file-using-an-asc-signature-file
A lot of linux devops guys and gals are very keen on verifying everything they install. Your package manager does that for you normally.

From your examples I guess you are using some distro from the debian family; a package with the connector would be [this](https://packages.debian.org/stretch/libmariadb-dev) so your second install command would be correct. When in doubt check the package repo or serverfault, the sheer number of package can be overwhelming sometimes.

**Comment by Matthewmads** [comment]
I followed thru with installing the  

'sudo apt-get install libmariadb3'
'sudo apt-get install libmariadb-dev'

commands and it seems to be working. 

I've encountered a new issue related to gunicorn so I will open a new issue for that. 

Thank you both @SchrodingersGat and @matmair for all of your help.

**Comment by huseyinkogo** [comment]
**RELATED**:
fresh install on debain 10.

```
root@localhost:~# sudo mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 40
Server version: 10.3.31-MariaDB-0+deb10u1 Debian 10
```
Getting this syntax error
when i input create user command

```
MariaDB [(none)]>  CREATE USER 'inventree'@'%' IDENTIFIED WITH mysql_native_password BY '3gssdg2srhgsd!';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY '3gssdg2srhgsd!'' at line 1

```
