### ISSUE TITLE
[FR] Fullfill in line item one by one

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2398]
So during my current studying of the stock model, I realize what we can allocate stock only once for each line item, and then all of our lite items allocated we can do order.ship() - by that method it takes these stock of allocated line items and creates a copy of them and applies order to them. 

Now  I think about fulfilling line items in sequence, so the question is, can I have stock items copies of stock items with doubling orders in it.

**Comment by HelgiBergmann** [comment]
I think we can=)

**Comment by HelgiBergmann** [comment]
I am going to use an endpoint that gets allocation stock items by barcode and then complete allocation.

**Comment by matmair** [comment]
@HelgiBergmann if you implement this please do it as a separate feature per branch so reviewing and merging is easier.

**Comment by HelgiBergmann** [comment]
@matmair I have already messed it with my basket branch a little. but I've switched now=)
