### ISSUE TITLE
[FR] Required for build orders: add suggested ammount

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2399]
That page indeed list the parts that are needed, but not the amount we need to order to reach minimum stock level + stock for the build orders. Ideally this would be available via a report (Excel, PDF, printable web page) that also shows the current stock level so we can validate stock level before ordering.

![image](https://user-images.githubusercontent.com/53965859/144202947-5d8a4e9a-ebe3-427c-bcfa-9c7d25a59595.png)

_Originally posted by @JustusRijke in https://github.com/inventree/InvenTree/discussions/2383#discussioncomment-1726946_

**Comment by JustusRijke** [comment]
More details:

As a user, I'd like to be able to retrieve a list of purchasable parts needed to complete _all_ build orders.
This info is available per part, as "Required for Build Order".

Ideally, this list will not only contain the "Required for Build Order" field, but also a field suggesting the user how much needs to be ordered.
I imagine this being a calculation that takes the following fields into account:
1. In Stock
2. Minimum stock level
3. Estimated build wastage quantity

**Comment by matmair** [comment]
@SchrodingersGat can we bump this?

**Comment by SchrodingersGat** [comment]
I'm waiting to see if I can cover it off in #4855
