### ISSUE TITLE
Filter stock by part and location

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#240]
In stock view page, allow filtering by the location (already done) AND the part.

e.g. show all 2K2 resistor stock in location "Work/Office2"

**Comment by jnewlands** [comment]
Should also be able to filter stock items on whether they belong to a given part's BOM. Other filter ideas should be considered.

Should be able to combine filters

**Comment by SchrodingersGat** [comment]
Stock items can now be filtered by:

- Part
- Location
- Category
- Supplier Part
