### ISSUE TITLE
[BUG] Out of range Reference_ID field error when creating Purchase Order

### ISSUE THREAD

**Issue by jpeterse** [inventree/InvenTree#2400]
I was entering an purchase order, when a got a non-descript internal error flash up on screen.

Appears to be an out of range error on the Reference_ID field.

Running Main branch on bare metal, with MariaDB.

It would be good to create a more user friendly error message, in place of this:
![Error Message](https://user-images.githubusercontent.com/8325689/144303458-9f22be9c-29ee-404a-b4e4-38bee9cfcb01.png)

Here's the purchase order data I entered on the form:
![Purchase Order Entry](https://user-images.githubusercontent.com/8325689/144302967-1ae30797-7a5b-4420-8ee9-0a10ca12ebac.png)

I haven't found our why the field is out of range. The supplier record appear to be fine.
Attached is the traceback from console.
[purchase order error traceback.txt](https://github.com/inventree/InvenTree/files/7636736/purchase.order.error.traceback.txt)

**Comment by matmair** [comment]
Hi @jpeterse thanks for the bug report!
The first reference field has a to high number for our current field definition. These are normally automatically increased so a number that high is highly unlikely. We need to add a validation against that. I am somewhat stunned that this is not happening automatically.

A more descriptive error won't happen as the error was raised by the database engine not django. Returning raw error messages could be very dangerous as it might lead to exposing secrets if they are in the offending line. I understand your whish but 500 errors are generally not likely to occur to users and normally mean we messed up somewhere in the code. You should get a validation error, which highlights the failing column / field.

**Comment by jpeterse** [comment]
ohh, does that not create a problem of there is a separate purchase department with their own order references?
If the field is to be auto generated, it would be best (IMHO) to hide the field, and maybe allow for a separate field to enter a user specific PO number?

**Comment by matmair** [comment]
> ohh, does that not create a problem of there is a separate purchase department with their own order references?
> If the field is to be auto generated, it would be best (IMHO) to hide the field, and maybe allow for a separate field to enter a user specific PO number?

That's a point for discussion. I will fix the 500, big changes to refs like that should be approved by the maintainer @SchrodingersGat . Maybe that should be a separate FR

**Comment by SchrodingersGat** [comment]
Hey @jpeterse thanks for raising this error report. The cause for this bug is pretty obscure, so it is reasonable that it is not obvious to you!

To get technical:

The database saves *two* copies of the reference field:

- **reference** (string) - the raw value of the reference as supplied
- **reference_int** (integer) - an integer cast of the reference value (or as close as can be cast) which is used for natural sorting

However the **reference_int** field is implemented as an [IntegerField](https://docs.djangoproject.com/en/3.2/ref/models/fields/#integerfield) which is a 32-bit signed value. The reference string you have added is much larger than that!

I had not considered the case of really big numbers when I implemented this field.

@matmair we could migrate the `reference_int` field to a [BigIntegerField](https://docs.djangoproject.com/en/3.2/ref/models/fields/#bigintegerfield) which supports 64-bit numbers. 

However we would still need to catch the case where the number is too large (positive or negative) and either:

a) Throw an error (invalid reference)
b) Clip the `reference_int` field to some limiting magnitude

**Comment by matmair** [comment]
@SchrodingersGat I just added validation right now -> will also change it to big integer and add migrations

I would vote for a) and leave it to the first person needing something bigger to add another (API speed friendly) way to do sorting

**Comment by matmair** [comment]
Ok that is strange; I just checked because I thought that integer fields had autovalidators for their values... and they do! Will have to see why they fo not get called!

(from django source code)
``` python
class BigIntegerField(IntegerField):
    description = _("Big (8 byte) integer")
    MAX_BIGINT = 9223372036854775807

    def get_internal_type(self):
        return "BigIntegerField"

    def formfield(self, **kwargs):
        return super().formfield(**{
            'min_value': -BigIntegerField.MAX_BIGINT - 1,
            'max_value': BigIntegerField.MAX_BIGINT,
            **kwargs,
        })
```

**Comment by jpeterse** [comment]
@SchrodingersGat That makes sense. But does raise from questions.

FWIW, in previous companies I have worked for, every time a system was relying on user entered data as a reference or id field, it always – without fail – came back to create problems, or in some cases, outright made us change out the system for another.
User entered data is never guarantied to be unique nor immutable.
Creating an index on user data is fine, as long as the index is not expected to hold only unique values.

If I’m not mistaking, in this case the reference_id field is set as a unique index?
So purchase orders “123 my order”, and “123 additional items” cannot coexist?

**Comment by SchrodingersGat** [comment]
> If I’m not mistaking, in this case the reference_id field is set as a unique index?

You are mistaken! The `reference_id` field is wholly separate from the unique-id field in the database. `reference_id` is a calculated field which is used for numerical sorting of the purchase orders

- It does not have a uniqueness requirement
- It does not *matter* what the value of this field is
- The error here is that this field does not support really really big numbers

**Comment by jpeterse** [comment]
Happy to hear I was mistaken.  :-)

**Comment by matmair** [comment]
@jpeterse fix is in now. If you think the field should be changed in general we are always open for FRs and new ideas
