### ISSUE TITLE
Create Initial Stock while duplicating item

### ISSUE THREAD

**Issue by Acvarium** [inventree/InvenTree#2407]
The option to Create Initial Stock greatly improved my workflow. Some times it is quicker to just duplicate existing part. But there is no option to create initial stock on a Duplicate Part dialogue.
Adding of this feature will allow in some cases to create and store items in a few clicks.

**Comment by SchrodingersGat** [comment]
@Acvarium see fix here - https://github.com/inventree/InvenTree/pull/2408

**Comment by Acvarium** [comment]
Thanks
