### ISSUE TITLE
Transaction records

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#241]
Create part transaction records when performing stock actions

**Move Stock**

When moving stock, automatically create a StockMovement object which tracks which parts were moved, recording:

* StockItem / Part
* Quantity
* Original location
* Destination

This StockMovement can then be used to (e.g.) print a PackingList 

Make this generation optional (default = ON, user can turn off in dialog) so that simple moves (e.g. box-1 to box-2) don't have to be recorded in the database.

**Stocktake**

Keep a record of stocktake data.

* Can be printed out or reviewed at a later date

**Comment by eeintech** [comment]
@SchrodingersGat Isn't this describing the current stock tracking system in place?

> Make this generation optional (default = ON, user can turn off in dialog) so that simple moves (e.g. box-1 to box-2) don't have to be recorded in the database.

This option is probably missing though?
