### ISSUE TITLE
[FR] Add part specific info to "Part / Purchase orders" tab

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#2412]
**Problem**
Currently "Purchase orders" tab displays a list of POs related to this Part. 
But is doesn't display Part specific info from PO like item quantity, purchase price, number of received items etc.

**Suggested solution**
Add columns to "Purchase orders" tab: item quantity, unit price, received items of this part.
Remove confusing column "Items".

**Describe alternatives you've considered**
leave intact

**Comment by SchrodingersGat** [comment]
Funnily enough I was actually thinking about this exact feature today:

![image](https://user-images.githubusercontent.com/10080325/144582507-52e6f617-ad7a-4760-ac52-3320979c882b.png)
