### ISSUE TITLE
[BUG] Parameter Template search/filtering not working

### ISSUE THREAD

**Issue by deepthought-64** [inventree/InvenTree#2414]
**Describe the bug**
Filtering/searching the Parameter Template when adding a Parameter does not work - instead all Parameter Templates are shown.

When adding a new parameter to a Part via the "New Parameter" Button, the shown modal window "Add Parameter" has a searchable ComboBox where I must select the Template. Whatever text is entered there does not lead to the correct Template being filtered/searched.

**Steps to Reproduce**

1. Prerequisite:  some parameter templates must exist
2. Select a part
2. Select "Parameters"
3. Click on "New Parameter"
4. Click on the ComboBox labeled "Template*"
5. Enter some text that represents an existing template name

**Expected behavior**
I would expect that only Parameter Templates with a name that matches the filter-string are shown.

**Actual behavior**
All Parameter Templates known to InvenTree are shown in the list.
Also: The Templates are not sorted by Name but it seems by ID - or at least the most recently added templates are at the bottom of the list. This makes it very cumbersome to find the correct one because one has to look through the whole list.

**Screenshots**
Here you can see that I was searching for "Color" but was shown all the templates in the system (there were 2 :
![image](https://user-images.githubusercontent.com/5528887/144603608-b0617641-0d05-4248-b171-080e28986da5.png)

**Deployment Method**
- [X] Docker
- [ ] Bare Metal

**Version Information**
```
# Version Information:
InvenTree-Version: 0.5.4
Django Version: 3.2.5
Commit Hash: 66a08fe
Commit Date: 2021-11-03
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
```

**Comment by aserputov** [comment]
Hello, @deepthought-64 @matmair. I want to work on this issue. Could you please assign me?

**Comment by matmair** [comment]
Hi @aserputov !
Thanks for your interest. I generally suggest pinging @inventree/triage @inventree/maintainer if you need quick answers as any one of us can be AFK.
If you encounter problems with tackeling this or finding the relevant code parts feel free to ping me.

**Comment by SchrodingersGat** [comment]
I believe this issue has been fixed in master:

![image](https://user-images.githubusercontent.com/10080325/144684222-f69db41b-b86f-4132-9cae-ec394cdfb3fa.png)

**Comment by deepthought-64** [comment]
Hi everyone,
thanks for looking into this!

@SchrodingersGat 
Can you estimate when 0.5.5 will be available for an update? :wink:

**Comment by matmair** [comment]
@deepthought-64 the fix for this most likely won't make it into 0.5.x but 0.6.x as we had major changes and it would be would be difficult to fix it in the old release.

**Comment by deepthought-64** [comment]
Allright. Is there any 0.6.x release on your schedule yet?

**Comment by matmair** [comment]
Working hard on it, you can check the milestones to get a feel for how far we are.

**Comment by deepthought-64** [comment]
Thanks, looking forward to 0.6.x. 
And thanks for your effort!

**Comment by matmair** [comment]
Will close this as `wontfix` as we kindof have it fixed but won`t in old versions.

**Comment by matmair** [comment]
@aserputov thanks for the interest in fixing this. We have some good starter issues and things we need help on marked in the issues. If you are interested in something don`t hesitate to hit us up!
