### ISSUE TITLE
[BUG] maintenance_mode_state.txt permissions

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2422]
@matmair I've had some issues updating an InvenTree instance to latest master after the plugin merge.

The error was the user which runs the server does did not have permissions to write to this file:

`./InvenTree/InvenTree/maintenance_mode_state_.txt`

I sorted the permissions out, but I am wondering if this file needs to be brought out of the source directory as it is a "user configurable" (or at least run-time configurable) file.

For example we bring "config.yaml" out into a separate directory.

Could this file path be specified as part of the InvenTree run-time settings? Either as an environment variable or a variable within config.yaml?

**Comment by matmair** [comment]
@SchrodingersGat I think your PR is a great fix!
