### ISSUE TITLE
[BUG] Stock tracking information alignment

### ISSUE THREAD

**Issue by wengtad** [inventree/InvenTree#2428]
**Describe the bug**
The alignment of the table is not consistency. For example, the customer name, will it be good to make it consistency or is there a purpose to be like this?
This is took from https://demo.inventree.org/stock/item/232/

**Steps to Reproduce**
1. Go to https://demo.inventree.org/stock/item/232/
2. Scroll down to 'Stock Tracking Information'

**Expected behavior**

**Screenshots**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/12437747/144858331-46fa52a1-8322-41b1-bd68-6ddc1a27608a.png">

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
InvenTree-Version: 0.6.0 dev [DEMO]
Django Version: 3.2.5
Commit Hash: b7f3a04
Commit Date: 2021-12-06
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by wengtad** [comment]
One more, after the stock returned from customer, I couldn't find it in the location.

**Comment by matmair** [comment]
Hi @wengtad thanks for the report! If you submit more of them please include the version information block as the demo is changing daily and it adds some steps to find out what version contains a bug.
Would you be willing to submit a fix? Seems to be a simple css / html thing. You do not have to but I always try to encourage ppl. to try with the easy fixes. You could always ping me for advice / to review.

**Comment by matmair** [comment]
> One more, after the stock returned from customer, I couldn't find it in the location.

Could you try to reproduce with full steps and check if you looked in the same location as you returned it to? It is easy to switch the different locations in the head, which happens to me sometimes when debugging. If it still appears pls. open a new issue so we can keep this one clean. Thank you for your intrest in InvenTree!

**Comment by wengtad** [comment]
> > One more, after the stock returned from customer, I couldn't find it in the location.
> 
> Could you try to reproduce with full steps and check if you looked in the same location as you returned it to? It is easy to switch the different locations in the head, which happens to me sometimes when debugging. If it still appears pls. open a new issue so we can keep this one clean. Thank you for your intrest in InvenTree!

Yup, I will open a new issue after my finding, I will try to reproduce using demo site and with steps, not sure whether I use it in a correct way or not.
