### ISSUE TITLE
[FR] Using Distributor's API for Part and PO import

### ISSUE THREAD

**Issue by Nerade** [inventree/InvenTree#2439]
**Problem**
We are about to roll-out InvenTree in our small research institue. To create all parts representing all used components by our team would cost us weeks if done manually.

**Suggested solution**
What I was thinking about is that all the information which parts we should have can be extracted from our main distributors via their respective API from order history. This also enables fetching more information and parameters for parts from their API. One way to I can think of how to integrate this into InvenTree would be to have an "Import PurchaseOrder".

**Describe alternatives you've considered**
For the roll-out preparation a simple script making use of InvenTree's and the distributor's API can fix the initial setup of parts but on the other hand it might be interesting to be able to order parts and later import this to Inventree as a PO with all needed information already present on distributors site.

**Do you want to develop this?**
Since I have some allowance to spent time on integration InvenTree I would like to have a look at this. For me right now this seems like a bigger task to implement since its kind of deep packed into the core logic. So I would like to here your opinion on this and also if I have missed a feature already present for this kind of problem and workflow.

**Comment by matmair** [comment]
Hi @Nerade und willkommen in der community,

**current situation**
in general, I suggest using the extensive import functions provided by InvenTree. For mass import there is the [admin interface](https://inventree.readthedocs.io/en/latest/settings/import/), end-users can use import functions for POs or parts if that setting is enabled.

**about your suggestion/question**
This is a very valid suggestion and I greatly appreciate that you are willing to contribute! We recently merged plugin functionality (docs are still on their way, but maybe [peek here](https://github.com/inventree/inventree-docs/pull/192)). I have some PoCs for the suggested functions running in-house but they are not ready for mass deployment. If you want I can give you pointers.

**recommended path**
Depending on your planned adoption schedule a small import script or loading csv files might be faster. If you have the time a plugin might be a way better long term solution and maybe you will enjoy working on the codebase.

Regards, Matthias

**Comment by Nerade** [comment]
Hi @matmair danke für den herzlichen Empfang, 

based on your answer I guess I will then prepare a script for the initial import as a fallback and start sketching a concept and getting familiar with the codebase. It has been quite some time since the last I touched django.
I am also delighted that my idea finds resonance. I'll see how far I can get so far.
Thanks already and best regards
Marcel

**Comment by SchrodingersGat** [comment]
Marcel, ok to close out this issue?

**Comment by matmair** [comment]
@Nerade Maybe play around with the software itself and get familiar with the different concepts. For codebase, it should be enough to look at the sample implementation at `InvenTree/plugin/sample/integration` to see a basic integration plugin - which should be perfect for what you want.

**Comment by Nerade** [comment]
@SchrodingersGat yes, I think for now I know everything I need to tackle this. Also thanks again @matmair for the input. I will start playing on this today.
