### ISSUE TITLE
[BUG] Stock item purchase price > 9999.99 causes BOM list to fail to load

### ISSUE THREAD

**Issue by YeomansIII** [inventree/InvenTree#2440]
**Describe the bug**
Setting a stock item purchase price of greater than 9999.99 causes the /api/bom endpoint (and the BOM UI of a part) to fail and not show any BOM items. This happens if a single BOM part/stock item has a purchase price greater than 9999.99. The stock item we are setting the purchase price of is a serialized stock item.

**Steps to Reproduce**

1. Create part - purchasable true
2. Add serialized stock item
3. Set same stock item's purchase price to anything greater than 9999.99
4. Add the created part as a BOM item to another part
5. Attempt to load BOM list
6. BOM list fails to load with 500 error and UI shows list as empty

**Expected behavior**
The BOM list should load just fine even if a stock item in the BOM list has a price greater than 9999.99

**Screenshots**
![image](https://user-images.githubusercontent.com/3809115/145433384-efd1f07b-6eaf-4adf-8e2c-0d481d53f0ba.png)

**Deployment Method**
- [X] Docker
- [ ] Bare Metal

**Version Information**
InvenTree Version | 0.6.0 dev
Commit Hash | 2b27fab

Also happened on previous 0.5.x version, we updated to the latest to see if the issue was fixed (it is not).

**Comment by matmair** [comment]
@YeomansIII thank you for your bug report!
@SchrodingersGat I can reproduce this. The error seems to happen at serialisation of the decimal field for fields equal to or greater than 10.000:
``` python
File ".../InvenTree/venv/lib/python3.9/site-packages/rest_framework/fields.py", line 1127, in to_representation
quantized = self.quantize(value)

File ".../InvenTree/venv/lib/python3.9/site-packages/rest_framework/fields.py", line 1146, in quantize
return value.quantize(

decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

**Comment by SchrodingersGat** [comment]
@YeomansIII @matmair having some trouble reproducing that on my end.

> The error seems to happen at serialisation of the decimal field for fields equal to or greater than 10.000:

A greater numerical value, or a longer string value?

**Comment by YeomansIII** [comment]
@SchrodingersGat A greater numerical value of the stock item's purchase price. Greater than 9999.9999 numerical value.

**Comment by SchrodingersGat** [comment]
@YeomansIII managed to work it out, a strange issue without how the calculated price fields were encoded.
