### ISSUE TITLE
[QUESTION] Any tips on how I can reconcile parts "produced" by other parts?

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#2441]
Hi,

Today I came across a "philosophical" question about how to reconcile when a part is produced by other parts.
The reality is that we order one tube of 6 meters. I want to specify to InvenTree that, in order to produce a tube of 1 meter, it will consume one 6m tube to create 6 1m tubes. 

I tried using build orders, but they can only do the inverse. 6 6m tubes would make 6 1m tubes. 

Is this possible to reconcile, or do you have any tips on how I can handle this effectively?

Kind regards,

**Comment by SchrodingersGat** [comment]
I would suggest that the simplest approach would be to set the "units" of the `Tube` part to "metres" - you will then have a single stock item of 6m which you can "use" to make smaller lengths?

**Comment by SchrodingersGat** [comment]
Also we now have opened up a page for [discussions](https://github.com/inventree/InvenTree/discussions) which are separate from issues - where this would be a more appropriate query :)

**Comment by Guusggg** [comment]
Thank you so much Schrodinger! I'll go to the discussions right away.

**Comment by Guusggg** [comment]
@SchrodingersGat Hey I've been playing all days with units in InvenTree but it seems as they are strings, they don't really do anything meaningful in terms of dividing bigger items into smaller ones. Care to throw me a bone?

**Comment by matmair** [comment]
@Guusggg as far as I know units are just what is shown; You can use fractions of a part (0,25 cm of a part that is per 1m for example)  in a BOM (it can not be tracked then) -> if you need it tracked make a part with the metered part as the only BOM item.

**Comment by SchrodingersGat** [comment]
As @matmair suggested, the "units" are only an aid to the user, they do not provide any functional logic. My suggestion was simply to specify that stock levels for the "Tube" are recorded in units of "metres" and then plan your bills of materials accordingly
