### ISSUE TITLE
[BUG] Stock allocation quantity

### ISSUE THREAD

**Issue by irameez** [inventree/InvenTree#2444]
Describe the bug
Before the recent update when you go to "Allocate Stock Item" Quantity field was filled up by default, now it shows max stock quantity.
Now you have to first check the quantity entered in the order and then manually enter it, and if you are entering it from more than one stock record you have to calculate the remaining amount, in the previous versions this was done automatically.
In addition to this, you can enter quantity greater than the one entered in the order, I believe this was not the case before.

This seems to be a reoccurring bug as I pointed out this before here:
https://github.com/inventree/InvenTree/issues/2183

To Reproduce

1. Create a new sales order
2. Enter a new part
3. Click the allocate stock icon
4. See error (Default quantity is max quantity instead of the actual quantity in sales order)
5. Expected behavior
6. By default it should show the actual quanity required in the sales order, and if you have to enter quantity from more than one stock record it should acutomatically calculate the remaining quantity.

Screenshot
![allocated quantity](https://user-images.githubusercontent.com/82723964/145573113-c95ebb4d-67b4-4d23-833c-d11774ba622c.png)
:

Deployment Method
Bare Metal

Version Information

0.6.0 dev
Development Version

**Comment by SchrodingersGat** [comment]
Thanks for the bug report @irameez 

Please check once https://github.com/inventree/InvenTree/pull/2446 is merged :)
