### ISSUE TITLE
[BUG] Build Order creating parts out of thin air

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#2459]
Hi,

Today I noticed what I consider to be a bug in the Build Orders, but I'm not so sure. I've searched a bit in past issues containing the word 'build order' but I could not find this reported yet. Btw my `Build Order` only contains **Optional** BOM's as I haven't found out how to make a BOM with **at least one of the optional** requirement.

**Describe the bug**
Build Output can be created without allocating stock, which (when people don't read carefully) results in parts created from thin air.

**Steps to Reproduce**

**NOTE:** If you refresh the page after creating a Build Output, confirming works again. Still I don't think this is expected behavior and in my opinion it would make sense to check for allocated stock before completing a Build Output so the allocated stock can actually be subtracted to reduce human errors.

1. Create a `Build Order` for a part.
2. Go to Build Output and create a new `Build Output`.
3. Confirm the creation of `Build Output`
4. **Stock Item gets created already, with no source of parts**
**NOTE:** If you want the to complete the `Build Order` now, there will be an error because there's no allocated stock, so that's as expected. Confirming the build as complete fails however as **when clicking on `Complete Build`; nothing happens.** (No forms get submitted)

1. Go to `Build Order` -> `Allocate Stock`
2. Click `Auto Allocate`
3. Click `Confirm`
4. **Nothing happens** (No forms get submitted)

1. Go to `Build Order` -> `Allocate Stock`
2. Click on a BOM Line Item -> `Allocate Stock`
3. Click `Confirm`
4. **Nothing happens** (No forms get submitted)

**Expected behavior**
Somewhere along the way I would expect an error. I think the best way to solve this is at the root, and check for allocated stock when creating a `Build Output`.

**Deployment Method**
- [x] Bare Metal

**Version Information**
**0.5.3** (Haven't gotten around to updating yet)

**Comment by Guusggg** [comment]
Hi,

So I'm not really sure what to do about this. I think it makes sense to check for allocated stock before creating `Item Stock` but ofcourse there's a feature in first completing 10 ouputs and then allocating stock afterwards... I'm conflicted. Please tell me what you think about this.

Kind regards,

**Comment by SchrodingersGat** [comment]
@Guusggg thanks for raising this point. When I first implemented the build order process, I wanted to allow some flexibility. 

By "flexibility", here I mean not forcing the user to fully complete every line to complete the build. Perhaps there is stock being allocated but has not been consolidated into the system, or maybe the build output has been completed "without" those items (maybe they're delivered late and will be allocated later)?

In any case, I think that the "build completion" process definitely needs to offer a more obvious warning that the build has not had all required parts allocated. An extra "are you sure" message, or something like that?

> Maybe not allowing the build to complete before all stock is allocated?

Currently, a "warning message" is displayed but that does not actually stop the user from completing the build. I think some extra confirmation dialog which needs explicit consent from the user if the build has not been fully completed.

I agree that this is worthy of some attention and needs improving.

**Comment by Guusggg** [comment]
@SchrodingersGat Thank you so much for your comment. It's nice to know it's a valid concern, but I definitely understand that there hasn't been any need to change it yet. An extra "are you sure message" would more than solve my problem, as I know the Confirm dialog is there, but it is ignored. 

(Just a side note, I"m really excited for 0.6.0 man, amazing work all you guys did. I don't want to upgrade to the latest yet as I know that 0.6.0 will blow me away lol)
