### ISSUE TITLE
[FR] Extend the syntax of Serial Number input to include continuing from the last assigned Serial Number

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#2484]
Hi,

After discussing with @matmair I wanted to request a feature to extend the special syntax when entering Serial Numbers to include the possibility of selecting the next Serial Number. InvenTree already knows what the next Serial Number will be but I haven't found a way to actually input it without typing manually, which is cumbersome cause the next Serial Number disappears as soon as you enter something in the field (it's the placeholder message)

**Problem**
I want be able to assign the next serial number when assigning a serial number to a newly built part.

**Suggested solution**
There's already a system in place to assign serial numbers by using a special syntax. Extend this syntax with a wildcard token or accept an empty string to assign the next serial number in a row.

**Describe alternatives you've considered**
I tried using `1+` or just `+` in the input field but it didn't do what I wanted.

**Do you want to develop this?**
I wouldn't mind adding it but I think it's easier for someone who has more knowledge in this part of the code to implement it. I think extending the syntax would not be a daunting task, as I would propose a single new wildcard token or just accepting an empty string.

**Comment by SchrodingersGat** [comment]
@Guusggg I see what you are saying, trying to think how we could implement. Currently, the "placeholder" text of the serial-number inputs shows you what the next serial number will be, right?

**Comment by Guusggg** [comment]
@SchrodingersGat It does indeed, however when you type into the field it disappears and we currently used numbers like 221020xxxx which makes it difficult copy. I would suggest just adding functionality to the `+` sign, so `1+` will behave like `from 1 to x` and a single `+` could be the next serial number and `+1` could be `next serial number + 1`.

I understand this is getting kinda 'detailly' so please keep it mind it's not a life threatening issue and I'll definitely manage without it! Thanks

**Comment by matmair** [comment]
@Guusggg the `+`sign is already taken but `~` was free. I added the function, PR is in. See the docs PR for details https://inventree--220.org.readthedocs.build/en/220/part/trackable/#assign-serial-numbers

**Comment by Guusggg** [comment]
@matmair Damn that is looking awesome! Thanks a lot for the hard work! Greatly appreciated

**Comment by eeintech** [comment]
Great job @matmair !
