### ISSUE TITLE
[Question] Plugin guide

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2485]
Please, can someone give me a brief explanation of how to work with plugins? Suppose I want to integrate some third-party API for local shipment, should I use plugins or just create another branch and do whatever I want.

**Comment by SchrodingersGat** [comment]
I'd suggest you wait only a little bit longer until the new 0.6.0 release. The plugins are still a work in progress and there will be some major changes before the release! We will add some comprehensive documentation also before the next release

**Comment by matmair** [comment]
@HelgiBergmann there is a PR for the docs so maybe start there:
https://github.com/inventree/inventree-docs/pull/192
There is also [CI build](https://inventree--192.org.readthedocs.build/en/192/)
