### ISSUE TITLE
[FR] DevOps improvments

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2493]
Important dirs in the following are:
- InvenTree/common/
- InvenTree/InvenTree/

Suggested devops code-changes:
- [x] enforce docstrings and a docstyle for all important dirs
~~- [ ] enforce real unit tests on important dirs (atm we test that each URL responds as part of the test cases so a lot of coverage is just from that branch)~~
~~- [ ] add unit tests (selenium or npm tests) for all generally reused js-functions~~
- [ ] add developer docs that ship with the codebase (prob. sphinx) so that class and implementation docs help with onboarding. Via napoleon / autodoc the docstrings can be used for that
- [x] check for docstrings optionally in CI -> #2652 / #2653 / #3089
- [x] rethink static code / third party js structure -> maybe add webpack / npm to deliver fewer small files and compress all deliveries. The 3rd party js / CSS code is currently a bit scattered and a lot of unneeded stuff is placed into the webservers static (would be intrestng if ppl. use CDNs / S3 as storage provider -> #2789 

QoL improvments:
- [x] add an automatic welcome message to new issue authors to provide links to docs and some general info on what kind of info helps with debugging
- [x] restructure CONTRIBUTING to add more info about architecture and workflows
- [x] add an automatic message for each new PR author to the contributing file

**Comment by matmair** [comment]
This is very longterm

**Comment by matmair** [comment]
After https://github.com/inventree/InvenTree/pull/3089 closes we can add inline docs and then close this one.

**Comment by simonkuehling** [comment]
As found in #4421, it would be good to include `django-extensions` in the dev environment for graphing DB schemas etc.

Since I just tried it in the current dev-Docker image, I have gathered what is missing in requirements for this:
```
$ apt-get install libgraphviz-dev
$ pip3 install pygraphviz
$ pip3 install django-extensions
```
and in https://github.com/inventree/InvenTree/blob/master/InvenTree/InvenTree/settings.py
```
INSTALLED_APPS = [
[...]
    'django_extensions',
]
```

**Comment by matmair** [comment]
Regarding python autodoc: https://github.com/mkdocstrings/mkdocstrings

**Comment by SchrodingersGat** [comment]
@matmair wrt mkdocstrings - the intent here is that we can extract code documentation and include at docs.inventree.org on each release?

**Comment by matmair** [comment]
Yes, in the end. I still have to look into it - just very short on spare time right now so I am documenting my ideas before they are gone again.

**Comment by matmair** [comment]
Mostly addressed now
