### ISSUE TITLE
[FR] Local plugin source directory should be configurable

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2496]
e.g. for a docker install, the "plugins" directory should be exposed to the host machine, e.g. `/home/inventree/plugins/`

@matmair any thoughts here?

My understanding is that (currently) plugins can be installed from:

- External path (e.g. pypi)
- Local path (`./InvenTree/plugins/`)

Is this a correct assessment?

**Comment by matmair** [comment]
Yes. One could just mount any directory via docker-compose into the path for plugins. Seems like an easy fix - although pip has a lot of things going for it as a deployment method. Dependency management for example.

**Comment by SchrodingersGat** [comment]
I think the simplest approach is to leave things as they are, and rely on the new "plugins.txt" support provided in https://github.com/inventree/InvenTree/pull/2504

If a user *really* wants to, they can mount an external volume for local plugins
