### ISSUE TITLE
[FR] [APP] Button to enable flashlight during barcode scanning

### ISSUE THREAD

**Issue by ldet** [inventree/InvenTree#2498]
**Problem**
I've got labels inside drawers, which I am currently unable to scan with the InvenTree Android app, because of low light.

**Suggested solution**
A Button to enable the flashlight in the scanning screen would be nice.

**Examples of other systems**
Most other barcode scanning apps have a button to enable the flashlight. I can scan the labels without issue with those apps.

Device: Oneplus 6
OS: Android 11

**Comment by SchrodingersGat** [comment]
Good idea!

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/148145453-c36c43be-5032-415e-a5ed-055906f23298.png)

New version of the app will have buttons to toggle flash and switch between front and back cameras. Should be released later today :)

**Comment by ldet** [comment]
Thanks. That was very quick and works perfectly!
