### ISSUE TITLE
[BUG] The web interface dose not function

### ISSUE THREAD

**Issue by Rubisco16** [inventree/InvenTree#2500]
Hi, I have installed Inventree 0.4.5 successfully, other version are always failed in installation. And now the admin page functions normally, but the homepage dose not function.

**Describe the bug**
The Settings menu and System Information menu, and others like Parts, after clicking, there's no response or any changes.
![image](https://user-images.githubusercontent.com/78011365/148181525-b84c58e7-2341-4f34-a0da-775e18aa3591.png)
![image](https://user-images.githubusercontent.com/78011365/148181583-d4d28692-82cd-4924-a71f-d0416082ff8e.png)

**Steps to Reproduce**
1. Go to 'Homepage'
2. Click on 'Stock'
3. Click on 'Plus sign'
4. No response

The inventree-proxy shows error as below,
2022-01-05 07:01:04 | stderr | 2022/01/05 07:01:04 [error] 25#25: *560 open() "/var/www/static/i18n/zh-cn.part.js" failed (2: No such file or directory), client: 172.18.0.1, server: , request: "GET /static/i18n/zh-cn.part.js HTTP/1.1", host: "192.168.1.192:1337", referrer: "http://192.168.1.192:1337/settings/"

**Deployment Method**
Docker on synology

**Version Information**
0.4.5

**Comment by SchrodingersGat** [comment]
Do you mean version 0.5.4, rather than 0.4.5 (which is quite old now)...

It looks like the `inventree-proxy` container can't see the static files. Have they been compiled? CLI into the `inventree-proxy` container and see if there is anything at `/var/www/static/`...

If you are running docker on synology, have you confirmed that the multiple containers have access to the same shared volume?

If not, then this will explain why the proxy can't see the shared static files!

**Comment by Rubisco16** [comment]
Yes, it is 0.4.5, but other versions are always failed during installation, only 0.4.5 is successful installed, and I don't why...

I'll check it. Thanks you.

**Comment by matmair** [comment]
@Rubisco16 in general Synology is not really supported as we need docker-compose to deploy multiple containers that access the same data. Also, there is the concept of a worker-container, that does all the long-running tasks - which is needed for newer versions to keep everything running smoothly.
I would strongly suggest trying to install the current stable version.

**Comment by SchrodingersGat** [comment]
@Rubisco16 if you find anything on your end about why it can't see the static files, please let us know. Perhaps we can update the docs.

**Comment by Rubisco16** [comment]
Hi there,
So I have upgraded the system version to 0.5.4, and also fixed the problem you mention as "It looks like the inventree-proxy container can't see the static files. Have they been compiled? CLI into the inventree-proxy container and see if there is anything at /var/www/static/...".
But there is still not working, and the Inventree-worker has new errors.
![image](https://user-images.githubusercontent.com/78011365/149050281-35d92628-1505-4487-ae9b-b15444c5dd08.png)

**Comment by SchrodingersGat** [comment]
Did you stop and then re-start the `inventree-worker` container? It looks like it was not restarted properly, or it did not get updated in sync with the `inventree-server` container...

**Comment by Rubisco16** [comment]
There's new error in Inventree-Worker.

2022-01-12 03:27:55 | stdout | django.db.utils.ProgrammingError: column stock_stockitem.scheduled_for_deletion does not exist

**Comment by matmair** [comment]
@Rubisco16 did you follow the update docs? Seems like the containers were not restarted and 'inv update' was not run
