### ISSUE TITLE
[FR] Non-interactive, environment variable based set-up in Docker deployments

### ISSUE THREAD

**Issue by MrManny** [inventree/InvenTree#2501]
**Is your feature request the result of a bug?**
No. It is a quality of life improvement.

**Problem**
As discussed on the side in #2454, Docker-based deployment could be simplified a little bit. Some systems, in particular Synology NAS, do not have docker-compose nor do they allow for easy terminal access.

**Suggested solution**
I could also see an approach where bootstrapping is done through environment variables which could be removed by the user once it's set up (and then heavily complains about it if the user doesn't unset them afterwards), e.g., `INVENTREE_ADMIN_USER` and `INVENTREE_ADMIN_PASSWORD`. A start-up script could check for the presence of these, run migrations and create user accounts accordingly. That would probably be a more generic approach that might also work for other non-Synology deployment situations.

**Describe alternatives you've considered**
None on a generic level; for Synology NAS systems, a Synology package could work.

**Examples of other systems**
Show how other software handles your FR if you have examples.

**Do you want to develop this?**
Please no, my bash is terrible 😅

**Comment by SchrodingersGat** [comment]
I believe that @matmair was looking into a Synology docker setup, it seems that this would be a popular feature!

**Comment by matmair** [comment]
@SchrodingersGat very much so! Already looking into more container stuff as most new issues seem to be associated with that. This also plays into #2309, possible self-updating and a getting started setup in general.

**Comment by MrManny** [comment]
@SchrodingersGat: sounds great! If you want to, you can reject this FR. I personally think this approach would be slightly more open to other deployment targets where the initial assumptions hold true (lack of docker-compose and/or interactive terminals are difficult).

**Comment by matmair** [comment]
@MrManny due to our architecture it will never be a great experience using inventree with only one container as long running actions will become blocking then.

**Comment by MrManny** [comment]
I think there is a misunderstanding. I am not asking to throw everything into one container. I am asking for environment variables to automate the steps that would require an interactive terminal, i.e., `invoke update` and `invoke superuser` using input provided through environment variables.

**Comment by matmair** [comment]
@MrManny I understood that but without an orchestrator like docker-compose or Kubernetes, you will run into errors as all things need to be running for everything to work. So a simple interface like for example Synology might not be enough / cause random errors.

**Comment by matmair** [comment]
@mrmanny I have a running package now for a DS920 / DS720. One question: where would you recommend publishing? It seems quite hard to publish to the official store itself and there are a ton of other options. Not sure what would be applicable.

**Comment by MrManny** [comment]
@matmair: that is an excellent question that I am unfortunately unable to answer 😅 I have not published anything on Synology before. But if you want me to test a package on my DS218+ running DSM 7.0.1-42218, I am all yours!

**Comment by matmair** [comment]
@MrManny This was merged and released
