### ISSUE TITLE
[BUG] Popup dialogs on stock items page dont work on German locale

### ISSUE THREAD

**Issue by ldet** [inventree/InvenTree#2505]
**Describe the bug**

Popup dialogs on stock items page dont work on German language. English language works fine.

**Steps to Reproduce**

1. Set Locale to German (Deutsch (de))
2. Go to a Stock Item and try to add Stock
3. Popup does not open

**Initial Debugging**

I already did some debugging on the issue and found that django template is "translating" floats and because in Germany we use "," as the decimal separator so 2.0 in english is translated to 2,0.
So whenever floats are inserted into javascript code, it results in a Javascript SyntaxError.
This happens in: https://github.com/inventree/InvenTree/blob/09777c57640c8ded8d3fe3b95f542b3dbfc0f7d5/InvenTree/stock/templates/stock/item_base.html#L432

Similar issue was addressed in #1928

https://docs.djangoproject.com/en/3.2/topics/i18n/formatting/#unlocalize

**Deployment Method**
- [ ] Docker
- [x] Bare Metal

**Version Information**
InvenTree-Version: 0.6.0 dev
Django Version: 3.2.10
Commit Hash: c93259745
Commit Date: 2022-01-06
Database: mysql
Debug-Mode: True
Deployed using Docker: False

**Comment by SchrodingersGat** [comment]
Thanks for reporting this, and for submitting a fix!
