### ISSUE TITLE
[Question]: Will the App be opensourced?

### ISSUE THREAD

**Issue by hacker-h** [inventree/InvenTree#2508]
Hi,
InvenTree looks really promising but for my usecase I have to extend the android app's functionality.
The particular feature I'm looking for is RFID tag support (additionally to barcodes).
Will it be opensourced or how are new features collected/added?
Also I noticed that it is only available via Google Playstore for Android which makes it impossible to buy&install for ungoogled Android devices. Also saw https://github.com/inventree/InvenTree/issues/2204 so upon opensourcing F-Droid is the way to go to distribute FOSS apps.

Thank you in advance!

**Comment by hacker-h** [comment]
will be also an update for https://github.com/inventree/InvenTree/issues/1951

**Comment by matmair** [comment]
@hacker-h as far as I am aware the questions were already answered in the linked issues. F-Droid does not work with the current model and is too small of an audience for the effort. This project is done solely in spare time by volunteers.

If you have feature requests please file them using the FR template.

**Comment by matmair** [comment]
@SchrodingersGat do you have anything to add to this or can I close?

**Comment by hacker-h** [comment]
APK releases would also be fine.
Upon opensourcing it will be easy to add additional release formats, otherwise will have to build another app and reinvent the wheel :/

**Comment by matmair** [comment]
As of now, there are no intermediate plans to open source, pls enjoy the great free inventory solution you were given and consider making an FR for the thing you want specifically. The maintainer of the app is great in delivering new features of they make sense.
You are free to create your own app, we provide APIs for that reason. If you do please kee an eye on
https://github.com/inventree/InvenTree/blob/4a5e4a88ac3e91d64a21e8cab3708ecbc6e2bd8b/InvenTree/InvenTree/version.py#L15-L27
changes in the API are marked by incrementing the version counter, you have to check for the version before assuming an endpoint exists.
