### ISSUE TITLE
[BUG] Keep getting "Build Order is incomplete"

### ISSUE THREAD

**Issue by elmo2k3** [inventree/InvenTree#2516]
**Describe the bug**
Can"t complete build order as the above message is always shown.

**Screenshots**
![Screenshot_20220108_173706](https://user-images.githubusercontent.com/20565/148652262-a91b0508-5d2c-4023-b76e-399239cd35a4.png)
![Screenshot_20220108_173819](https://user-images.githubusercontent.com/20565/148652263-c811a927-61e7-4379-8e81-b0211b4d27cb.png)
![Screenshot_20220108_173837](https://user-images.githubusercontent.com/20565/148652264-7944a924-9e99-4c76-9138-1fd9cad967f3.png)

**Deployment Method**
- [X] Docker
- [ ] Bare Metal

**Version Information**

# Version Information:
InvenTree-Version: 0.6.0 dev
Django Version: 3.2.10
Commit Hash: 4a5e4a8
Commit Date: 2022-01-07
Database: postgresql
Debug-Mode: True
Deployed using Docker: True

**Comment by matmair** [comment]
@elmo2k3 thanks for the bug report!
Can you give me some details on the settings of the produced part? From the screenshots, it would seem like a bug and I am almost certain that it is, but can not reproduce currently.

**Comment by elmo2k3** [comment]
Hey,
here are the details of this part:
![Screenshot_20220108_184735](https://user-images.githubusercontent.com/20565/148654325-8567b416-2d46-4a62-a51a-65e542a1bfa1.png)
I don't know if it has anything to do with it, but my bill of material contains two optional parts. 
The version I used before and worked fine was about 3 months old and I just recently updated to the latest version.

**Comment by matmair** [comment]
@elmo2k3 Can reproduce with optional parts, wil look into a fix shortly

**Comment by SchrodingersGat** [comment]
Thanks for reporting - see fix in https://github.com/inventree/InvenTree/pull/2517

**Comment by matmair** [comment]
@SchrodingersGat dam you were faster👍🚀

**Comment by SchrodingersGat** [comment]
I only just wrote this bug a couple of days ago, so I knew exactly where to look :)

**Comment by elmo2k3** [comment]
Great, thanks a lot!

**Comment by elmo2k3** [comment]
Just tried with the latest commit and docker image. Now I get one step further but then see "Form errors exists"

![image](https://user-images.githubusercontent.com/20565/148661818-56bacbf7-c9de-4999-8c8e-30c996ffda38.png)

**Comment by SchrodingersGat** [comment]
Huh, that's odd. Can you open the browser developer tools tab, and show the data the server is sending back when you hit "submit"?

**Comment by elmo2k3** [comment]
![image](https://user-images.githubusercontent.com/20565/148662443-89b70bcf-64d1-4973-9861-d7bd2f9a10a1.png)

This part has two positions in its BOM that are optional. Formerly I only allocated the one I really used and left the other one unallocated. Just for testing I now allocated both but that did not fix it.

**Comment by SchrodingersGat** [comment]
Ah.. OK I see what has happened here. I'll have a fix for you later on today.

**Comment by SchrodingersGat** [comment]
@elmo2k3 see here - https://github.com/inventree/InvenTree/pull/2520

**Comment by elmo2k3** [comment]
Now it works fine. Thanks a million!
