### ISSUE TITLE
[FR] Disable plugins for demo server

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2527]
@matmair I think it might be a good idea to disable plugins for the demo server? Otherwise, we have to worry about people potentially installing dangerous plugins, as there is a web-facing admin account.

How best to approach this, do you think? Disable plugins entirely, or just the ability to install them via the web interface?

**Comment by matmair** [comment]
@SchrodingersGat maybe add a switch in the config to turn it off entirely?

**Comment by SchrodingersGat** [comment]
Yeah, that's a better idea.
