### ISSUE TITLE
pip3 install psycopg2 pgcli on rp4 server

### ISSUE THREAD

**Issue by huseyinkogo** [inventree/InvenTree#2528]
Hey,

Love the software, wanted to install Inventree on my RPI 4, however need help installing on pip3 install psycopg2 pgcli on rp4 server, getting the errors please see attached screenshot.

I'm stuck on this part of the guide https://inventree.readthedocs.io/en/latest/start/install/#install-python-bindings

Also tried pip3 install mysqlclient mariadb it failed too.

And on my next new session, how can enter (env) through the cli
![image_2022-01-10_205531](https://user-images.githubusercontent.com/76049382/148746953-b7aaf556-9113-4a2d-a1e9-8145e7d6acca.png)

**Comment by eeintech** [comment]
What is your version of `pip` and `python`?

```
$ pip --version
pip 21.3.1 from /home/xxx/.local/lib/python3.8/site-packages/pip (python 3.8)
```

Try `pip install -U packaging` maybe?

**Comment by huseyinkogo** [comment]
```
python --version
Python 2.7.16
```
```
pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```
```
pip --version
-bash: pip: command not found

```

**Comment by huseyinkogo** [comment]
> 



> What is your version of `pip` and `python`?
> 
> ```
> $ pip --version
> pip 21.3.1 from /home/xxx/.local/lib/python3.8/site-packages/pip (python 3.8)
> ```
> 
> Try `pip install -U packaging` maybe?

Should do that command on the (env)?
if so what is the command to enter (env)

thanks

**Comment by huseyinkogo** [comment]
> @huseyinkogo do you have the Postgres client libraries installed?

Do you mean in the (env) ? 
if so i don't think so, is it `pip install postgres.client` ?

**Comment by eeintech** [comment]
> > 
> 
> > What is your version of `pip` and `python`?
> > ```
> > $ pip --version
> > pip 21.3.1 from /home/xxx/.local/lib/python3.8/site-packages/pip (python 3.8)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Try `pip install -U packaging` maybe?
> 
> ```
> python --version
> Python 2.7.16
> ```
> 
> ```
> pip3 --version
> pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
> ```
> 
> ```
> pip --version
> -bash: pip: command not found
> ```

Your pip version is really old... you need to update it: `pip3 install -U pip3`

**Comment by huseyinkogo** [comment]
```
~ $ pip3 install -U pip3
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pip3
Could not install packages due to an EnvironmentError: 404 Client Error: Not Fou                                                              nd for url: https://pypi.org/simple/pip3/
```

is the output getting when `pip3 install -U pip3`

I assume i need to enter the command in the (env) right?

**Comment by eeintech** [comment]
Your environment does not look right at all but it's difficult to guess what's happening. Please google your way through until you can install psycopg2, this is not InvenTree specific but an environment issue.

**Comment by matmair** [comment]
@huseyinkogo please try to update your whole pi? With
``` bash
sudo apt update
sudo apt upgrade
```
you can update your package-manager repo and then update everything that can be updated. Not being able to update pip normally points to a very old version, the update should install a new version of python3 and pip with that (except for if you pinned it)

**Comment by huseyinkogo** [comment]
thanks guys, however its not worth the hassle because raspbian doesn't uploaded to the lastest ver. However i will install in fresh Debian server soon.
