### ISSUE TITLE
[FR] Form polishing (check boxes)

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#2532]
@SchrodingersGat @matmair Not sure if this would be the right milestone but would be nice to polish the check boxes in the following forms. I'm going to keep hunting to see if I find any other forms like those below and report them here.

### Issue Purchase Order

![image](https://user-images.githubusercontent.com/4020546/148769453-1fd0f5bb-6c96-4ac5-891e-d61d101ba9a4.png)

### Complete Order

![image](https://user-images.githubusercontent.com/4020546/148769579-c2b8ee25-48da-453f-966e-c95090a06324.png)

**Comment by eeintech** [comment]
## Part

### Delete Part

![image](https://user-images.githubusercontent.com/4020546/148769974-ae931313-b8bd-4d31-8806-8704c62b7b55.png)

**Comment by SchrodingersGat** [comment]
Related issue: https://github.com/inventree/InvenTree/issues/2253

**Comment by eeintech** [comment]
Oh I missed that one sorry. Should #2253 be marked for `0.6.0` milestone?

**Comment by eeintech** [comment]
Looks good thanks @SchrodingersGat
