### ISSUE TITLE
[BUG] Table filter banner grows vertically when activated and filters already selected

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#2533]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4020546/148773691-0fc8c0b1-c4c3-4b1a-be80-47765a358b9e.png)

After clicking the "Add new filter" ![image](https://user-images.githubusercontent.com/4020546/148773330-2f0e1870-cd4f-4b85-967a-45dc0cdc3945.png) button:

![image](https://user-images.githubusercontent.com/4020546/148773740-d70ecc1f-cd6f-4983-beff-9397e51a86df.png)

**Steps to Reproduce**

1. Navigate to parts
2. Click on "Add new filter"  ![image](https://user-images.githubusercontent.com/4020546/148773330-2f0e1870-cd4f-4b85-967a-45dc0cdc3945.png) button above the parts table

**Expected behavior**

It should expand horizontally rather than vertically?

**Version Information**

Tested on demo version.

**Comment by SchrodingersGat** [comment]
looks like a css issue?
