### ISSUE TITLE
[BUG] Demo Instance Javascript Language

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2538]
Javascript files for the demo instance seem to be "stuck" on the german translation.

**Comment by matmair** [comment]
Still trying to reproduce, maybe we have a blocking rendering error in the current translation files

**Comment by matmair** [comment]
@eeintech @SchrodingersGat I have trouble reproducing on a fresh install, my other instances are shot due to the features I am deving rn. Could you try running `inv update` and restart the webserver?

**Comment by SchrodingersGat** [comment]
Just refreshed and rebooted the server for you

**Comment by matmair** [comment]
@SchrodingersGat seems to work now

**Comment by SchrodingersGat** [comment]
Yes, but.. nothing significant has changed in the last few days (and the demo instance resets every day).

There must be something "sticky" which is causing the wrong i18n javascript files to be loaded from the server...

**Comment by matmair** [comment]
Not really sure what it could be, the underlying mechanisms are pretty easy so not a lot that could fail. Maybe it is in our i18n switching code.

**Comment by SchrodingersGat** [comment]
I think this needs some further attention, let's not close it out yet.

**Comment by eeintech** [comment]
I'm back to english too:

![image](https://user-images.githubusercontent.com/4020546/149144416-86705ec0-d364-475e-802e-76c97a1b97ea.png)

And changing the language does not reload the content of the `i18n` folder therefore only the non-JS part of the UI are switched to the new language (Ctrl+R does not help).
Same result on my company, locally host instances.

This folder don't seem to show up running locally with `invoke server` and the translation switch works fine (JS is switched).

**Comment by matmair** [comment]
@eeintech the folders are linked dynamically using the language set in Django.

**Comment by SchrodingersGat** [comment]
I've noticed something else that is interesting - the 'language setting' seems to be tied to the session, and not the user:

Here I have logged in twice as "admin":

![image](https://user-images.githubusercontent.com/10080325/149244642-93e84983-f3af-4c38-8391-963d7d90d480.png)

Maybe the "multiple sessions" are messing with the language settings somehow?

![image](https://user-images.githubusercontent.com/10080325/149244694-f9dc94b9-3124-4c33-96f4-0db1ec451dad.png)

**Comment by matmair** [comment]
@SchrodingersGat everything tied to sessions (including language) is saved as database objects. I use this exact library in all my projects, I highly doubt that it is making the problems.

I tried to debug but can not really find where it comes from. Our mechanism for language selection is using standard mechanisms of django and as simple as it gets. It could be a caching thing but the language identifier is in the url so it should not matter.

**Comment by matmair** [comment]
Safeing the language setting per user would require its own mechanism and a new table so I would try to not do that as it is more likely to cause errors.

**Comment by SchrodingersGat** [comment]
@matmair I'm not suggesting that we set the language per user, I think that's not necessary and agree that it's a vector for more problems.

I was just wondering if maybe the weird issues we are seeing here is due to multiple active user sessions?

This problem is (most likely) only going to present on the demo instance. I'll leave this open until we're ready for 0.6.0 and if we haven't found anything further by that stage, I'll close it.

**Comment by eeintech** [comment]
Sorry to kill the mood here @SchrodingersGat and @matmair but again this is happening on our company instances and nobody is sharing accounts there.

I have one instance which I have switched my session to Italian and now cannot revert back to English...

![image](https://user-images.githubusercontent.com/4020546/149296991-3f6e45dc-1a8f-49cd-b929-b5eaf6977fe1.png)

After rebooting the web server and not changing anything, I'm back to English

![image](https://user-images.githubusercontent.com/4020546/149298007-ce2628a3-8763-4587-8a39-b3be54b8d596.png)

Changing it back to Italian, no JS switch (Ctrl+R neither):

![image](https://user-images.githubusercontent.com/4020546/149298310-22489197-cbfd-4db3-9d40-912c03c2aec3.png)

Rebooted web server and here comes the Italian

![image](https://user-images.githubusercontent.com/4020546/149298468-eeaf3a18-3d7d-4aa9-849b-ce26f2b54fc5.png)

And stuck until next web server reboot.
