### ISSUE TITLE
Cookie Permissions / GDPR Requirements

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2551]
- Add an informative banner regarding cookies
- Allow users to ~~opt-out~~ opt-in to any applicable cookies
- Link to "privacy" page on readthedocs (need to create this!)

**Comment by SchrodingersGat** [comment]
This plugin might be of interest https://django-cookie-consent.readthedocs.io/en/latest/index.html

**Comment by matmair** [comment]
> This plugin might be of interest https://django-cookie-consent.readthedocs.io/en/latest/index.html

Seems to be a solution for serverside stuff, so not really useable for the docs site.

**Comment by matmair** [comment]
> - Allow users to opt-out of any applicable cookies
Opt out is not allowed, the user must accept before data gets collected

**Comment by SchrodingersGat** [comment]
docs ref: https://github.com/inventree/inventree-docs/pull/233
