### ISSUE TITLE
Decimal Values: Server Error (500)

### ISSUE THREAD

**Issue by huseyinkogo** [inventree/InvenTree#2552]
When I try to add a stock with decimal value quantity i get a Server Error (500) when i submit the form. (received stock and add stock)

I purchase and build parts with decimal value.

**Eg**.
- I purchase 230.34KG of salt
- I build a part with 1.21kg of Salt

**Screenshots**
--->
![Screenshot-20220115210315-1558x385](https://user-images.githubusercontent.com/76049382/149617988-a0498a9a-1f55-4c8b-b8a7-91a87f3bc51e.png)

**Deployment Method**
- [ ] Docker

**Version Information**
- [ ] 0.5.4

**Comment by huseyinkogo** [comment]
Also played with the https://demo.inventree.org/order/purchase-order/3/, it doesn't let you receive items in decimal value

![image](https://user-images.githubusercontent.com/76049382/149618428-2e33a30d-282f-4086-be5a-43fc3c2fc52a.png)

**Comment by huseyinkogo** [comment]
However I could add 12, the form accepts the submission.

On the remaining 0.56, i get this form with over 12 digits after decimal.
![image](https://user-images.githubusercontent.com/76049382/149618521-d18f1b66-59b8-4959-adc5-1e32baf0d342.png)

after manually removing the excess amount of digits, still same error appears: when i submit
![image](https://user-images.githubusercontent.com/76049382/149618552-0db58ec6-9486-46e3-8b43-24338501a922.png)

**Comment by matmair** [comment]
Hi ther @huseyinkogo 
In general quantities should support fractals, although it is not a regular testing scenario.
Without the error message it is quite difficult / impossible to find out more without reproducing everything. I would suggest including the error message as error 5** is almost everything that can happen serverside.

**Comment by huseyinkogo** [comment]
Hey @matmair

I have included the error code of Server error (500) however that was all i received. When i submitted the form with a whole it succeed.

All the recent comments were from the demo page.  https://demo.inventree.org/order/purchase-order/3/

**Comment by matmair** [comment]
@huseyinkogo the demo instance resets daily, so examples from there are not really working.

I can reproduce the error, the API seems to block receiving of fractal parts.

We are very shortly before the next release so I tag the next version for it.

**Comment by huseyinkogo** [comment]
@matmair 

Roughly how many weeks are saying to resolve this bug.

**Comment by eeintech** [comment]
@matmair I made a pass to fix this bug, I believe this should target `0.6.0` not the next release.

**Comment by matmair** [comment]
@eeintech feel free to fix every bug you want😇!
At some point I would like to have a stable release so I can  merge, test and release my plugins but small bugfixes should not stir in the APIs so why not.

**Comment by SchrodingersGat** [comment]
Definitely worth fixing this one before stable release. Thanks @eeintech for fixing and @huseyinkogo for reporting!

**Comment by eeintech** [comment]
@huseyinkogo It's on master now, let us know if you still have issue with decimals

**Comment by huseyinkogo** [comment]
Can verify its fixed :) @eeintech @SchrodingersGat
