### ISSUE TITLE
[FR] Pallet/Box Tracking

### ISSUE THREAD

**Issue by huseyinkogo** [inventree/InvenTree#2562]
**Problem**
99.9% Businesses will receive parts/items in pallets/boxes.
_OR_
will store parts/items in pallets/boxes.

**Suggested solution**
Having certain parts received or built part assigned to a pallet/boxes. And assign the pallet/boxes to a location,

Like the pallet/box could have many items that needs to be moved to another location. I don't want to scan every item in the pallet/box and move its location.

I think the pallet/box could have its own barcode/qr cpde

**Comment by eeintech** [comment]
Seems quite related to #2058

**Comment by huseyinkogo** [comment]
@eeintech  its actually related to #2058, i think it should be merged?

**Comment by eeintech** [comment]
I would keep it separate as it's a good indicator there is demand for this feature.

**Comment by matmair** [comment]
The referenced issue is on the roadmap for 0.7.0 so this duplicate does not need a milestone.

**Comment by geniesis** [comment]
This can also be related to #2624

The parts may be ordered from the supplier as a box/pallet lot which has its own supplier part number/order code which could then be stored as is, then split up in future into individual items when sold.
