### ISSUE TITLE
[FR] Reports behave strangely

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#2566]
**Describe the bug**
When uploading a new report HTML file, InvenTree sometimes seems to remember the old file. 

**Steps to Reproduce**
If the files have the same name, it will generate a random one. This one will be shown. However if you decide to upload the same file again, it will be uploaded as the original filename. InvenTree will generate the old report in this case.

1. Upload a HTML file for your report (I've used Purchase Orders and Build Orders) as "filename.html"
2. Verify that the report is generated correctly.
3. Change something in the HTML file, and upload it again.
4. Verify that the change happend.
5. Change something in the HTML again, and upload it again.
6. See that the old HTML file (the one from step 1) is used as generated report 

**Expected behavior**
InvenTree should use the latest version of the file I uploaded.

**Deployment Method**
- [ ] Docker
- [x] Bare Metal

**Version Information**
InvenTree-Version: 0.6.0 dev
Django Version: 3.2.10
Commit Hash: 8597ae89b
Commit Date: 2022-01-06
Database: mysql
Debug-Mode: False
Deployed using Docker: False

**Comment by matmair** [comment]
@Guusggg that is somewhat expected behavour, all templates in django are cached (with our settings).
We could add a button to clear the cache / improve the upload method to clear the cache for that template. Should be straight forward.

**Comment by matmair** [comment]
@Guusggg I have not touched templates for over half a year, I would have to look into that. There could be other things connected to that - it for sure needs testing once it is being implemented.
Template behaviour is controlled in the settings, the LRU caching used normally by Django supports per-entry deletion, so it maybe could be implemented in the loader method.

**Comment by matmair** [comment]
@Guusggg maybe change the title to a FR so it is identifiable.

**Comment by SchrodingersGat** [comment]
@matmair I've run into this problem now too, and would like to address ASAP.

> Template behaviour is controlled in the settings, the LRU caching used normally by Django supports per-entry deletion

Can you provide any more information about this? Link to the docs? I'm happy to implement, just not quite sure where to start.

**Comment by matmair** [comment]
@SchrodingersGat a quick fix would be to just disable caching on templates in the reports for now.
Take a look at the template section in the settings.py. everything there is wrapped into a cached loader. You could either modify the appDirLoader to exclude the reports app paths and add them pack in without the cacher or write a method that resets the LRU cache of the cacher.

**Comment by matmair** [comment]
@SchrodingersGat you could also just reset the template cache loader on changes - https://github.com/django/django/blob/760b7e7f4f62eafdc79a2188d2a7739abaa6ca8b/django/template/loaders/cached.py#L98

**Comment by matmair** [comment]
@SchrodingersGat nice and simple solution!

**Comment by Guusggg** [comment]
Perfect guys! I'm very happy!
