### ISSUE TITLE
[FR] Add CNY (chinese yuan) as a currency support

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#2567]
**Is your feature request the result of a bug?**

Nope

**Problem**

We produce our products in China which requires buying components within mainland China and the entire process is basically produced there, if we use USD it won't be accurate and right for the components and value of things that we own within Chinese warehouses.

**Suggested solution**

Add a CNY currency support

**Do you want to develop this?**

Unfortunately I don't have the necessary skills to do so.

**Comment by matmair** [comment]
Hi there @Zontex 
there is a setting for that, please take a look at the [config file](https://inventree.readthedocs.io/en/stable/start/config/#configuration-file). You can add as many currencies as you like, we ship a small set of defaults based on the current user base. If that changes we might change the defaults.
Cheers
