### ISSUE TITLE
[FR] Uploaded images to static, change filename related to the part

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#2579]
**Is your feature request the result of a bug?**

No

**Problem**

When you upload an image, for example, cute_cat.png as a part image to InvenTree it will be uploaded AS-IS with the filename cute_cat.png, if the file already exists it will create a random string something like cute_cat_AjXuzCsA.png this creates a confusing pattern that is difficult to replicate or use the uploaded files later on for other purposes without going into the databases and getting the items that the image is linked to.

**Suggested solution**

When an image is uploaded under a specific item, change the file/image name related to the item such as timedate_category-number_partnumber.png or something related, it will be possible to recognize or scrap through all the images later on without opening one by one and understanding which one it is,

Many times I download images online and they come with random names and I upload as is because I don't want to change the names one by one, found out by looking into the static directory the names are kept as is which I believe isn't a good practice.

**Examples of other systems**

Usually, images will also have a unique ID to not be able to literate through them (security risk) but here it's not the case I believe, the file names should be readable by the name so if you'd get a list of all the files you'll know to what they belong without need to cross-filter them with the database of actual items.

**Do you want to develop this?**

I would like to give it a try, I believe it's few lines in the upload mechanism to change the file name to the item being uploaded with some extra parameters.

**Comment by matmair** [comment]
@Zontex seems like a niche use case. I would much prefer to have semi-random names as those prevent ppl. from scraping larger repos fast and without API access. The current mechanism is the default of django and pretty well tested.
If you want to dev this I do not object to it - feel free. I would just ask two things:
- make it an optional setting. I am not a fan of somewhat easily recognisable patterns in the metadata of my EE stuff (not paranoid, just conscious 😇) and recon this might be the case with a lot of engineers
- please make it ~100 covered with E2E and unit tests. Test for existing files, files that do not conform to your naming convention, files with special symbols in the name, big files, lots of files, multiple uploads at once. If you need help with that feel free to ping me.

@SchrodingersGat would you merge this?

**Comment by SchrodingersGat** [comment]
There is a subtlety here to consider.

The part images uploaded do not necessarily correspond only to a single part. Images can be shared by multiple parts - for example you may have 500 different 0603 resistors which all reference the same image.

Originally the image upload function worked exactly as suggested here - a filename was generated based on the part pk.

However this was scrapped when the image re-use function was implemented.

What it your intended use case where you want to iterate through the files without touching the database?

**Comment by Zontex** [comment]
> There is a subtlety here to consider.
> 
> The part images uploaded do not necessarily correspond only to a single part. Images can be shared by multiple parts - for example you may have 500 different 0603 resistors which all reference the same image.
> 
> Originally the image upload function worked exactly as suggested here - a filename was generated based on the part pk.
> 
> However this was scrapped when the image re-use function was implemented.
> 
> What is your intended use case where you want to iterate through the files without touching the database?

After thinking and looking up the current design, I don't think its relevant. seems like not anything worth looking at for the moment.
