### ISSUE TITLE
Change Date format

### ISSUE THREAD

**Issue by marea69** [inventree/InvenTree#2581]
Hi

How do I change date format in Part stock result > Last updated ,
in mm dd yyyy?

![Cattura](https://user-images.githubusercontent.com/61009409/151659594-adce30b3-0d4c-4907-bd0e-651805e8cf27.PNG)

**Comment by matmair** [comment]
Hi there @marea69
Please use discussions for questions, issues are for bugs or feature requests.
As far as I am aware this is currently not possible. Also sorting will not really work with the format you suggested.
If you think the feature should be added please open a [FR](https://github.com/inventree/InvenTree/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=%5BFR%5DCustom%20Date%20Format)

**Comment by SchrodingersGat** [comment]
This would be possible to add as a per-user preference, I think table sorting would be preserved, as the setting would only change how the date is displayed to the user.

@marea69 would you like to implement this yourself? Otherwise it will be added to the development plan for next stable release
