### ISSUE TITLE
[BUG] Inventree fiddles with files directly rather than using Django Storage api

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#2585]
**Describe the bug**
Django provides an abstract [storage api](https://docs.djangoproject.com/en/4.0/ref/files/storage/#django.core.files.storage.get_storage_class) that should be used for all file accesses so that the server can be run from places that do not have a local filesystem and/or shared filesystem to store the media files.

**Steps to Reproduce**

Run Inventree API server on a node with a readonly filesystem and you will crash out in [label/app.py](https://github.com/inventree/InvenTree/blob/dd3ac58f38e0f27f18b48dcded7bc84043539d5f/InvenTree/label/apps.py#L70) because it cannot create the folders, no matter what the DEFAULT_STORAGE_CLASS is set to.

**Expected behavior**
I expect that inventree should honour the DEFAULT_STORAGE_CLASS for writing and reading its media files.

**Deployment Method**
- [x] Docker
- [x] Kubernetes
- [ ] Bare Metal

**Version Information**
Application fails to start up.  This using the master branch of the main Inventree repository.

**Comment by matmair** [comment]
@nwns this is a known side effect of the current implementation of file access. The storage API can help with this but introduces a number of possible bugs/security issues with different storage providers as some of them (boto for example) do not respect the originally intended access rights.
We have to rewrite at least 30 code blocks, possible more, to get full compliance with the API and introduce extra security measures so that users do not just expose all their part files, photos, test results and reports to the world. Especially with cloud deployments like Kubernetes in mind.

So this is a rather sensitive task - contributions are very welcome. I would love to get to this but I am slammed with work rn.
When implementing this we should also document and test a few possible storage classes and recommended settings for those. Especially block storage services like Amazon S3 can be dangerous as they enable fast misconfiguration and could lead to circumvention of our privileges system.

**Comment by nwns** [comment]
The changes for running in k8s will come with at least one example of a S3 like API for testing.

More importantly, we need to stop adding new code that directly fiddles with the filesystem and uses the Storages api, even if the only production supported storage is local files for now.

**Comment by matmair** [comment]
@nwns I will have to disagree here. Current standard in the codebase is to use pythons built-in file-APIs (fiddle as you call it). Using 2 different APIs for the same thing sounds like a great source for strange, hard to reproduce, special case bugs.
If we switch to Django's storage API this needs to be for the whole codebase and not a bit-per-bit situation as there need to be docs etc. connected to it. The storage API can behave strange with symlinks on windows, some user might have to change their storage setups after the switch.

**Comment by nwns** [comment]
@matmair 
>Using 2 different APIs for the same thing sounds like a great source for strange, hard to reproduce, special case bugs.

Agreed.  However, I will also note, from what I can tell, Inventree hardcodes the default file storage so until that can be changed, it should be fine.  Unless, someone is maintaining their own settings.py (which I used to do, I would *not* recommend), but if they are, they are also advanced enough to know how this works.

Who is using symlinks? How are they using symlinks?  For the media files?  I searched the code and the only symlink stuff I can find is in various libraries, all of which should know if what they are trying to do will not work on windows and do a copy.  In particular django itself can use symlinks for collect static, but this is about media files.

To be clear, I am not suggesting that Inventree should change the default location for media files or the default behaviour, they are both fine when Inventree is run on a single machine with a persistent writable disk.

**Comment by matmair** [comment]
@nwns symlinks are often used in big MSFT environments when deploying with IIS. I would never recommend using that but some enterprises have strict rules on what can be deployed so they have to use IIS.
Overriding the settings is done a lot from what I hear. One of the reasons a lot of ppl. keep using old releases for a long time.
I find it a bad idea to use 2 APIs, feel free to submit PRs how you like. There are no concrete coding styles for this org.

**Comment by matmair** [comment]
@SchrodingersGat I look at this while handling #2861 and my suggestion would be to move plugins.txt and config.yaml to the root media folder

**Comment by SchrodingersGat** [comment]
Moving these files to the media directory would allow read access to any authenticated user. Especially in the case of config.yaml this could potentially expose some very sensitive data

**Comment by matmair** [comment]
@SchrodingersGat already working on that. Thanks to our existing /auth route not too difficult. My concern is more misconfigured 3rd party storage-backends like S3 that use external auth settings.

**Comment by nwns** [comment]
Hello @matmair , thank you for tackling this problem.

I have to say, I am not completely clear why all three files need to be in the media folder.

`plugins.txt` - I see the logic on why the code needs to write to it from a usability standpoint, however, putting something that would just give code execution to anyone that can write to the media files (which could be any user with upload privileges) seems like a good way to collect some CVE's in the future.  I think it should stay where it currently is and if it can't be written to, just fail and advise the user on how to move forward (point them to the documentation) as anyone that is running has a readonly root will probably also be blocking everything that pip attempts to do and the operator should also be technically savvy enough to figure it out.

Additionally, readonly installs would likely have multiple instances, so pip is only going to run on a random instance.

I would also suggest that, this is probably better suited for to be in the database in general, though I am not familiar with what all the plugins are allowed to do.

`config.yaml` - As far as I can tell the code does not write to the file, so would also be fine staying where it is.    Readonly root situations have systems for injecting config files on disk.  `plugins.txt` would probably also be treated as a config file in this environment.

If `locale_stats.json` is what I think it is, it should just moved into a resources folder or into the templates, and just served to the through the API or a template.

**Comment by SchrodingersGat** [comment]
I'd have to agree with @nwns here - is there a way we can avoid "raw file operations" while still keeping these files out of `/media/` directory?

**Comment by nwns** [comment]
Because I was not clear in the OP, the raw file operations that I was referring to are the media files, that is, files uploaded by users or are override-able by users like the labels in the OP.  These three files are not media files in my mind.

For `config.yaml` and `plugins.txt`, as long as the code working on the files handles readonly roots, they can stay the way they are right now.

I have had a chance to look at `locale_stats.json` and it is a good candidate for [importlib.resources.read_text](https://docs.python.org/3/library/importlib.html?highlight=resources#importlib.resources.read_text).  Because it is generated by the administrator (that is, with invoke) the generation code could generate a python module with the stats in it instead and simplify the reading code if Inventree supports python's older than 3.7.

**Comment by matmair** [comment]
@nwns the plugins.txt must be kept outside of the db as the install runs without db-access (for migrations etc). It can be written to on runtime so it needs to be somewhere writable.
Config.yaml should also be writable as we will need this to make auto-updates.

I am very open to handle locales in another way - please feel free to suggest a change.

**Comment by matmair** [comment]
Partly addressed by https://github.com/inventree/InvenTree/commit/11992918358e8ae4c4a9a10167c8aaa43c0b64b5
