### ISSUE TITLE
Remove "delete_on_deplete" field

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2612]
The existing "delete on deplete" option is opaque and I don't think we need the functionality at all.

Instead, stock items should be correctly deleted from the database only under a certain set of conditions (excepting manual deletion by the user).

So, some thought into how to remove this feature, and perform the correct data migrations is required.

**Comment by sintech** [comment]
It would be nice if "delete on deplete" conditions were configurable in settings. 
I mean currently it is "on" by default and you can only disable it for specific stock items.

**Comment by SchrodingersGat** [comment]
This has now been made "configurable" in the settings, instead of removing
