### ISSUE TITLE
New BoM upload tool

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#2617]
## Part matching issue

Part matching is not working, here is the BoM:
![image](https://user-images.githubusercontent.com/4020546/153447506-911fa196-412e-44d8-afa8-5546e2f1d6ff.png)

Result of the upload:
![image](https://user-images.githubusercontent.com/4020546/153447640-66206aa4-6a76-45d1-b739-9b82b002af33.png)

## No way to re-upload file (if wrong file selected)

"Upload BOM file" button should always be shown and fonction activated:
![image](https://user-images.githubusercontent.com/4020546/153448134-749aa3f2-2c23-4fb2-a68a-12a6daa5e76b.png)

Here:
![image](https://user-images.githubusercontent.com/4020546/153448220-107c2b82-7e83-4960-80b5-1e99134e5459.png)

Forced to return to part view:
![image](https://user-images.githubusercontent.com/4020546/153448273-4d8c5e6c-909c-456f-9df6-1ab63928b758.png)

## Template file

Template file should only be a helper, it shouldn't force users to convert ALL their BOMs in the exact same format because most CAD outputs will NOT match the format of InvenTree, an extra step in the process of uploading BOMs is not welcome.
I **strongly** suggest to revert to the field matching step after upload to avoid issue like part matching:

![image](https://user-images.githubusercontent.com/4020546/153448938-2a2d593b-9b7f-4fe4-afa8-be1cdca10dd8.png)

**Comment by SchrodingersGat** [comment]
@eeintech thanks for the feedback and I can appreciate that these changes seem like a step backwards in some ways.

The major focus here was speed. On my test system, using the old upload system, one particular BOM file took 5 minutes to initially process! Now that returns in around 2 seconds.

The column matching issue is the only one here which will be difficult. The backend needs to know which columns are which *before* it attempts to extract data. This will probably mean that the file needs to get processed twice - once to initially extract the columns and a second time to extract data once the user has selected column mapping.

I'd also look to make this behaviour generic so we can replace the other data importers too.

**Comment by eeintech** [comment]
I'd definitely endorse any effort in improving the upload process and speed, however the new tool should really be completely finished and polished before releasing `0.6.0` because we use it a lot in our company and I wouldn't be able to upgrade to next release with a half-baked solution... Let me know if you need help to test it :wink:

**Comment by matmair** [comment]
It would also be cool if we could control the import via API - a possibility would be to put it into steps e.g. `/api/bom/import/{import_id/{step_number}/`
