### ISSUE TITLE
[BUG] Cant invoke superuser

### ISSUE THREAD

**Issue by MIFD670** [inventree/InvenTree#2618]
env) inventree@Drop:~/src$ invoke superuser
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory
cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory
cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory
You may require some further system packages to be installed.

**Comment by matmair** [comment]
Hi there @MIFD670 ! Welcome to InvenTree.

In the future please use the bug report template for reporting - we need the info that is asked for there.

> OSError: no library called "cairo-2" was found
> no library called "cairo" was found
> no library called "libcairo-2" was found

These libraries are missing from your system. As we do not know what system you use I will guess that you use something Debian / ubuntu based. The command to install the packages would be:
```
sudo apt-get install libcairo2-dev
```
If you use another distro have a [look here](https://opensource.com/article/18/8/how-install-software-linux-command-line) for a general overview. For windows or Mac [look here](https://www.cairographics.org/download/).

**Comment by SchrodingersGat** [comment]
@MIFD670 did you follow the advice from @matmair above? Any luck?

**Comment by SchrodingersGat** [comment]
Closing due to lack of response. @MIFD670 please ping us if you need any further assistance.
