### ISSUE TITLE
After the update no view on the parts 

### ISSUE THREAD

**Issue by Agilitytime** [inventree/InvenTree#2625]
After the update to the latest version (I should not have done, I know....) I can view  parts, settings, categories, etc.. 
i can't create parts, categories, etc. either.
do you have any idea how I can solve this ? 

 
<img width="1169" alt="grafik" src="https://user-images.githubusercontent.com/62443876/153846400-6f849a67-0744-4230-8e8b-d7f7dd0886d0.png">

<img width="1184" alt="grafik" src="https://user-images.githubusercontent.com/62443876/153846661-6a8f7d8a-7819-4299-8038-3bdeaea6e274.png">

**Comment by SchrodingersGat** [comment]
@Agilitytime try doing a hard-refresh of the page and see if this makes any difference.

If that does not work, can you open the developer console on your browser, and show if there are any javascript errors?

**Comment by gabryelreyes** [comment]
Same problem here! And the console gave me this just once and I am not able to reproduce the error message
![image](https://user-images.githubusercontent.com/66941456/153870290-5741d3b8-c117-428b-9a6a-e715e5284f0d.png)

**Comment by SchrodingersGat** [comment]
Some recent changes to the template code seem to be the culprit here. It should be rectified now - please pull down latest code and confirm that it works!

**Comment by Agilitytime** [comment]
can you Push the Latest version to Docker

**Comment by SchrodingersGat** [comment]
@Agilitytime currently in progress, will be available on docker hub soon.

**Comment by Agilitytime** [comment]
now it works again ! thank you very much! This is really a great project

**Comment by SchrodingersGat** [comment]
Thanks for the feedback @Agilitytime , and thanks for reporting the bug :) Happy to get it fixed quickly for you
