### ISSUE TITLE
[BUG] Breadcrumb tree doesn't work in Stock

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#2633]
**Describe the bug**
Stock location can't be opened using "Breadcrumb tree" from stock item view.

**Steps to Reproduce**
1. Open any stock item
2. Click on burger button and select any location except active
3. Some random stock item is opened

**Expected behavior**
Stock location should be opened

**Deployment Method**
demo.inventree.org

**Comment by SchrodingersGat** [comment]
@sintech seems to work fine for me:

![image](https://user-images.githubusercontent.com/10080325/154154764-cc0f8c62-2001-460f-aa5b-d802fed8cad0.png)

**Comment by matmair** [comment]
@SchrodingersGat can not reproduce, works on demo.inventree.org for me.
Also @sintech please try to also add the version info for the demo site - it updates automatically so we do not really know what version was affected.
Steps to get the info:
1. On any page:
![grafik](https://user-images.githubusercontent.com/66015116/154165110-4c4af1f2-5eb9-4454-bc94-4a8bcd006533.png)
2. click the copy button at the bottom of the dialogue
![grafik](https://user-images.githubusercontent.com/66015116/154165252-c878484c-c528-47b5-ac21-5ef9141197e2.png)
3. Paste at the foot of the issue
![grafik](https://user-images.githubusercontent.com/66015116/154165306-1f60878f-f656-4eb9-9880-2b45c8a48e69.png)

Thanks!

**Comment by sintech** [comment]
My mouse cursor is hovered over "Storage Room A". Pls note the link in bottom left corner.

![изображение](https://user-images.githubusercontent.com/10057327/154252733-9bca7dce-9ccc-46df-8c19-ee5131597d9a.png)

# Version Information:
InvenTree-Version: 0.6.0 dev
Django Version: 3.2.12
Commit Hash: 6c32f5c
Commit Date: 2022-02-16
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by sintech** [comment]
> @sintech seems to work fine for me:

It seems you missed the first step, it is reproduced only when current page is stock item.

**Comment by SchrodingersGat** [comment]
Thanks for the clarification @sintech I can reproduce now.  Fix incoming.

**Comment by SchrodingersGat** [comment]
Should be good now @sintech - it will take a while for the demo website to refresh, though.
