### ISSUE TITLE
Category path is invalid

### ISSUE THREAD

**Issue by 4li-fth** [inventree/InvenTree#2636]
**Describe the bug**

category path is just falling apart. its showing a random stream with random length of category names as child-parents that are not bound to a child parent relation at all.
it is consistent on refresh, and changes in a not predictable pattern as i change some category parent somewhere
**correct categories are shown as children when i navigate to a parent category**, but in "path", "breadcrumb" and "select parent category" there just horribly wrong

**Steps to Reproduce**

Don't know. i just found out it happened as i was adding parts to the categories. it was fine when i added all the categories

**Screenshots**
![image](https://user-images.githubusercontent.com/99790493/154216785-0e88d651-19ff-4c70-b2f5-bb72eefba886.png)
![image](https://user-images.githubusercontent.com/99790493/154216856-6d826226-ca19-4c98-a18a-a349bd67b202.png)
![image](https://user-images.githubusercontent.com/99790493/154216952-ebbf5e47-7e73-432b-ad44-4cb0b1c3b6a6.png)

**Deployment Method**
- Docker

**Version Information**
InvenTree-Version: 0.5.4
Django Version: 3.2.5
Commit Hash: 66a08fe
Commit Date: 2021-11-03
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
Seems to be related to https://github.com/inventree/InvenTree/issues/2633

**Comment by SchrodingersGat** [comment]
@4li-fth did you recently perform an install / update after which this changed? If so, can you please advise:

- The previous version you updated from
- The process you followed
- Any error messages displayed

**Comment by 4li-fth** [comment]
i didn't have an update, just installed the mentioned version like 2 days before this happened following through install docs for docker. it was working as expected during category insertion

**Comment by SchrodingersGat** [comment]
This is a very strange one. @eeintech @matmair ever seen an issue like this before?

**Comment by SchrodingersGat** [comment]
@4li-fth does this happen for every category? Or only some?

**Comment by 4li-fth** [comment]
> @4li-fth does this happen for every category? Or only some?

only some ( most of em by now ) , but as i edit categories and change parents, more unrelated, untouched categories on other places start to display wrong path.

**Comment by 4li-fth** [comment]
i can send a pgsql dump if it helps

**Comment by SchrodingersGat** [comment]
> i can send a pgsql dump if it helps

That might be useful!

You can also export the dataset using `invoke export-records -f dump.json`

**Comment by 4li-fth** [comment]
here's the json dump from the faulty server
[dump.tar.gz](https://github.com/inventree/InvenTree/files/8078730/dump.tar.gz)

**Comment by SchrodingersGat** [comment]
Looking through the dataset, nothing seems amiss. The categories are arranged correctly. I threw together a quick script to rebuild the category trees, and it looks OK:

![image](https://user-images.githubusercontent.com/10080325/154244139-4a838b02-70e5-4832-858d-827132019720.png)

It must be something to do with the way that the server is formatting the "path" of the category...

I do not have time right now to look into this any further, hopefully later on this week. In the mean time, if you can provide any more info about the problem that would be appreciated.

**Comment by 4li-fth** [comment]
yea the relation tree is ok since its displayed correctly (correct children under correct parents) in the software but the path is not 
tnx i'll be waiting to hear from it
no other problems i can think of... other than the '500 server error' i get when i try to change or remove a category sometimes. but then it works the next time.
and the order which the subcategories are displayed is different from the time it didn't have the path problem. might narrow things down...

**Comment by matmair** [comment]
No idea either. I just tried to reproduce the db drop but could not on current master.
@4li-fth did you only use the main interface or also API/admin?

@SchrodingersGat @eeintech total shot in the dark but could this be a case where the tree is not rebuild? I can not think of another option. If we find the cause and it is ui related we should really try to add tests for the edge case.

**Comment by SchrodingersGat** [comment]
If we do find a bug associated with this, we'll add a fix to 0.6.1

**Comment by matmair** [comment]
@4li-fth could you try again with the current code and a clean database? I would really like to fix / figure out this. So far I have a hard time to reproduce the behaviour so please provide all steps you did after install (fi possible)

**Comment by matmair** [comment]
@SchrodingersGat how long should we keep this open?

**Comment by SchrodingersGat** [comment]
@matmair we were both unable to reproduce, it may be specific to their setup. I'll close, but @4li-fth please feel free to add more information
