### ISSUE TITLE
[FR] "Submit and create next part" option on Create Part dialogue

### ISSUE THREAD

**Issue by Acvarium** [inventree/InvenTree#2642]
**Problem**
Usually I add 10-20 new parts in a row. It would be great in those cases to go from completed and submitted "Create Part" dialogue to a fresh one, for the next part.

**Suggested solution**
Something like "Submit and create next" button on a bottom at the "Submit".

Just a small thing to speed up the workflow

**Comment by SchrodingersGat** [comment]
Anything to save some clicks! I really like this idea.
