### ISSUE TITLE
[FR] RFID support (especially on Android App)

### ISSUE THREAD

**Issue by hacker-h** [inventree/InvenTree#2643]
**Problem**
I have a lot of RFID tagged items which I would like to index.

**Suggested solution**
InvenTree should support a field for an RFID field.
On the Android App it should be possible to scan an RFID tag and immediately display the corresponding item along with its data.
This can be part of a background functionality listening for rfid scans all the time (can be switched on).

**Describe alternatives you've considered**
Add an RFID data field for each item and a search filter to find it which supports scanning of RFID tags on mobile devices and plain text search on the web gui.

**Examples of other systems**
ERP systems usually make the entire data scheme for items fully customizable, e.g. https://github.com/frappe/erpnext
For the RFID scanning functionality in particular the way to go in ERP systems would be customizing + additional software feature implementations, but I'm not aware of a specific opensource tool having this feature in place already.

**Do you want to develop this?**
I would like to, but I cannot. Since it is quite similar to the barcode functionality it should not be super complicated.
With some general guidance I could perhaps develop the feature for the backend, however the Android App functionality is most important to me, but it is closed source :/

**Comment by matmair** [comment]
@hacker-h what stops you from using the barcode field? You can put in anything you want in there. The app would need an integration but i do not see the need for an additional field in the db.
Also you can extend the part with parameters.

**Comment by matmair** [comment]
@hacker-h could you expand on what you mean?
I see two possible scenarios here:
1) If each tagged item has different properties, you need to create them separately (or as variants of the main part if only a few parameters differ).
2) If you have many tagged stock items of the same part (multiple rolls of the same capacitor) you create one part and then add stock items - where you only need the quantity per stock (multiple parts per tag) and then need to attach the tag. A variant of that is if each stock item has a unique tag - there are pretty fast ways to handle those too.

In general: InvenTree is an **inventory management system**, it is focused on the manufacturing of parts by combining other parts together (think of PCBA for eg). If you have many unique parts in low quantities maybe an **asset management system** would be a better fit. If you just buy and sell the parts (with a warehouse where you store the stuff in between these events) an **ERP** or **warehouse managmet system** would be more fitting.

**Comment by hacker-h** [comment]
You are probably right.
I will do some more research, thank you

**Comment by SchrodingersGat** [comment]
@hacker-h I do like the idea of adding RFID support to the app, I think that's a great new feature!

It would probably be sufficient to make use of the existing `UID` field (which is where we store the barcode data), unless we think there would be cases where a particular stock item would have both a barcode *and* an RFID tag.

**Comment by matmair** [comment]
@hacker-h pls do not get me wrong: I like the idea of using RFID tags or any other method of unique marking systems. It just smells a lot like feature-creep to add a new field for each method - renaming the barcode field possibly would be a better solution.
Also sounds like we get a free upgrade from @SchrodingersGat so yeay!

**Comment by hacker-h** [comment]
For my individual use case I will use a simple table sheet and later maybe expand to an ERP system.
I feel like using InvenTree is overkill for me after trying it for a while.
Thanks for your suggestions and your support.

**Comment by matmair** [comment]
@hacker-h thanks for the input, I think the RFID functions will be a valuable addition nonetheless

**Comment by Zontex** [comment]
@hacker-h I'm working on a custom react-native (android + iOS) app to enable smart LEDs and label printing from the app itself, could you describe what RFID functionality you want? i.e what's the procedure you usually take when using RFID cards, I will try to implement a demo and test it.

<img width="442" alt="Screen Shot 2022-03-04 at 2 38 15 AM" src="https://user-images.githubusercontent.com/19342533/156630407-ab0658dd-04b5-4669-89ac-423fe8fd73f7.png">

**Comment by hacker-h** [comment]
@Zontex My first use case:
When I scan an RFID tag with a smartphone it immediately shows me which item this is, where it is currently used etc.
My second use case:
To move X items from one location to another I press a button to start a selection, then I scan the RFID tag of each item that shall be moved, finally I select to which location to update all selected items.

**Comment by SchrodingersGat** [comment]
The source code for the mobile app is now released - please redirect this discussion over to the new repo - https://github.com/inventree/inventree-app
