### ISSUE TITLE
[BUG] Virtual Item in Build Order

### ISSUE THREAD

**Issue by markusEmm123** [inventree/InvenTree#2648]
I'm using the german version of Inventree, most of my translations are guessed. Pleas excuse, if the names in the english version are different.

**Describe the bug**
When assigning stock items to a build order i also can/should/need to select virtual items assigned to the BOM for this job.
I can't creat any stock items for a virtual item, which in my opinion makes sense, because there is no countable amount of the virtual item stored anywhere and if it would be, it would not be used up by a build order.
And because there is none of this virtual item in stock, i can't assign it in the build order.

**Steps to Reproduce**

1. Create a virtual item (e.g. "one hour of solder work").
2. Create an item consisting of the virtual item and other items (non-virtual, e.g. raw PCB and some parts to be soldered on there), let's call it "PCB assembly 1".
3. Create a build order for the "PCB assembly 1".
4. Assign the non-virtual parts for the build order.
5. Assigning the non-virtual item is not possible because there is none of this in stock.
6. When trying to create a new stock item for the virtual item, i get an error message that the base part is not valid.

**Expected behavior**
Let assign virtual parts in the build order without using them up (without the need to specify a stock object) or let create a stock item from a virtual object.

Or explain to me how virtual items are inteded to be used for build orders :)

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
Version 0.6.0 dev
Commit hash 95db82a
Commit-Date 2021-12-12

**Comment by matmair** [comment]
@markusEmm123 this is by design currently - I do mark licenses as optional so they do not block the built process.

@SchrodingersGat would you be open to changing this behaviour? Having a way to serialize virtual parts sure would be nice.

**Comment by SchrodingersGat** [comment]
@matmair can you provide an example of what a serialized virtual part might look like?

**Comment by matmair** [comment]
@SchrodingersGat software licenses (for identifying the system on support requests) for example. Or downloadcodes.

**Comment by matmair** [comment]
@schrodingersgat maybe we should make the docs clearer about the use case for the virtual tag. I imagined it could be used for that.
The question is if one could not just use a default part and its workflows - seems like a good feature creep point.

**Comment by SchrodingersGat** [comment]
Perhaps improvements to the docs would be the best approach here. And perhaps, we need some better management of the build process - like not displaying "virtual parts" as requiring allocation? Or virtual parts display specifically as "no allocation needed"?

**Comment by matmair** [comment]
I think a few more tips in the interface would not be bad but that is more of a low priority in my mind.
Docs updates should do it.
@markusEmm123 could you work with just using it as a normal part and creating stock upfront?

**Comment by Geekly** [comment]
We're trying to manage configuration files and track them. A virtual part seems like the best way to do that. Currently (0.9.0 dev) we can't complete any build orders with virtual components without making them optional, because we can't allocate stock for virtual components. 

We were able to work around this by changing the part to Not virtual, serializing it and allocating stock, then changing it back to Virtual. I don't recommend this practice, as there's no guarantee this functionality will persist since it breaks the rules.

**Comment by matmair** [comment]
@Geekly this sounds like it could benefit from a separate part category that has separate API endpoints etc. Do you use the UI or scripts to process builds?

**Comment by Geekly** [comment]
We use the UI exclusively, but it might make sense to use the scripting API to manage the configuration files.
