### ISSUE TITLE
[FR] Check for docstrings optionally in CI

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2652]
check for docstrings optionally in CI

_Originally posted by @matmair in https://github.com/inventree/InvenTree/issues/2493

**Comment by matmair** [comment]
@SchrodingersGat this requires some huge refactoring in the comments -> bump to 0.8.0 or should I do this right before release of 0.7.0 as a last thing when everything else is merged (will create some conflicts else)

**Comment by SchrodingersGat** [comment]
I think best to make it first thing after we do 0.7.0

**Comment by matmair** [comment]
@SchrodingersGat pleas LMK when I should start working on this - will clean up this branch rn
