### ISSUE TITLE
[BUG] Login error

### ISSUE THREAD

**Issue by chevdor** [inventree/InvenTree#2659]
**Describe the bug**
Error while login in:

```
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ProgrammingError at /accounts/login/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">relation "django_session" does not exist
LINE 1: SELECT (1) AS "a" FROM "django_session" WHERE "django_sessio...
                               ^
</pre>

Request Method: | POST
-- | --
http://192.168.9.115/accounts/login/?next=/
3.2.5
ProgrammingError
relation "django_session" does not exist LINE 1: SELECT (1) AS "a" FROM "django_session" WHERE "django_sessio...                                ^
/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py, line 84, in _execute
/usr/bin/python3
3.8.10
['/home/inventree/InvenTree',  '/home/inventree',  '/usr/bin',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/inventree/.local/lib/python3.8/site-packages',  '/usr/lib/python3.8/site-packages',  '/home/inventree/.local/lib/python3.8/site-packages/odf',  '/home/inventree/.local/lib/python3.8/site-packages/odf',  '/home/inventree/.local/lib/python3.8/site-packages/odf',  '/home/inventree/.local/lib/python3.8/site-packages/odf',  '/home/inventree/.local/lib/python3.8/site-packages/odf',  '/home/inventree/.local/lib/python3.8/site-packages/odf',  '/home/inventree/.local/lib/python3.8/site-packages/odf']
Mon, 21 Feb 2022 12:25:32 +0000
```

**Steps to Reproduce**

- fresh install on k8s
- invoke update
- invoke superuser

- go to home
- login

**Expected behavior**

login works

![image](https://user-images.githubusercontent.com/738724/154955647-d3341abb-cf96-498d-ac0d-6d02d4591730.png)

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
stable (0.6.0)

**Comment by chevdor** [comment]
Closing this issue. Having issues running `invoke update` in the k8s pod and thinking it only takes care of the db migrations, I ended up running this locally, only in order to create the tables. I did not realize that it also creates the static resources required everywhere.

So there is no issue per say but the doc should probably explain that.

**Comment by matmair** [comment]
@chevdor the docs state clearly that the command needs to be run on installation and for each update, I do not see an issue here. The command does actually a lot of things that are needed to keep the whole system functioning:
 - migrations
 - creation of custom model migrations (if you tempered with your branch)
 - collection of static files
 - pre-rendering of translated frontend files
 - translation-checks and statistics (you could manually pull the translations from Crowdin and drop them in)
 - a general health check
 - everything your plugins want to do on update

So documenting this could be a bit much for quick install docs.
Happy to hear a differing opinion.

**Comment by laurensramandt** [comment]
I am maintaining manifests at https://github.com/laurensramandt/inventree-kubernetes . 
They are not perfect in the way that certain static assets are written to the data volume at startup, but they are functional.

**Comment by laurensramandt** [comment]
@matmair , I would but: 
- my repo only contains manifests
- the repo by Frankkkkk (https://github.com/Frankkkkk/inventree-helm) seems to be more mature: these are real helm charts.

Maybe we could fork Frankkkkk's after testing it

**Comment by matmair** [comment]
@laurensramandt going to continue this in https://github.com/inventree/InvenTree/discussions/8823
