### ISSUE TITLE
[FR] PO receive trackable items with batch code / serial no

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#2660]
**Problem**
I track most stock items by serial number, which is unfortunately a string not a number. So I use the Batch Code field to store them what is great and works very well. But when tracking the purchase orders, there is no possibility to enter the batch code / serial no. directly when I fill the Receive Items form. So it have to be done later editing each stock item individually. 
More problem arise when a PO line contains more than one quantity of a trackable item.  When receiving such an item in one pass, a stock item from a trackable part is created with a quantity more than 1.  I cannot find a possibility how to split this into individual unique stock items with own batch no / serial.  

**Suggested solution**
It would be nice if I can assign the batch code / serial no. directly on the receive items form, and create individual stock items with its own batch/serial even if the PO line contains more than 1 received quantity.

**Describe alternatives you've considered**
Order trackable items one-by-one, or receive them one-by-one, then go to the stock and edit them individually in order to fill in the batch code.

This would greatly speed up the workflow with trackable parts. Keep up this good work, thank you!

**Comment by matmair** [comment]
Hi there @rkalman welcome to the InvenTree community!

Sound like a good idea to make the workflow faster. Are you typing in the serial numbers by hand or do you scan them?

The number of devs is quite small (the maintainer @SchrodingersGat and a handful of semi-regulars if we find time) so it could take a while for this to be developed. Would you be willing to submit a PR for it? Reviewing code is not as time-consuming as developing and testing what fits best 😇.

Regards, Matthias

**Comment by SchrodingersGat** [comment]
@rkalman to clarify, you would like to add serial numbers / batch codes to incoming stock items when you receive them against a purchase order?

**Comment by rkalman** [comment]
@matmair: I use a scanner, but just as a native keyboard, so basically I type them. Regarding the PR unfortunately I'm pretty new in python&js (however with a massive 20+ years experience in c++/c#) so I think you guys handle it much more faster and better. But one day maybe..

@SchrodingersGat: Yes, exactly what I propose, thank you!

**Comment by SchrodingersGat** [comment]
@rkalman thanks for confirming. It sounds like a great addition, it will be added in the next feature release.

**Comment by SchrodingersGat** [comment]
@rkalman here's how I have implemented it:

![image](https://user-images.githubusercontent.com/10080325/155982643-01d1f3c6-a22c-476a-b25b-f6a09730b833.png)

On the "receive items" form, the user can choose to expand the available options to include a "batch code" or "serial numbers" which get applied to the stock items as they are received.

**Comment by rkalman** [comment]
Thank you, perfect solution!
