### ISSUE TITLE
[BUG] Unable to create build output

### ISSUE THREAD

**Issue by ssewell** [inventree/InvenTree#2663]
**Describe the bug**
On a fully allocated Build Order, I'm unable to create a build output.

**Steps to Reproduce**

1. Create any new Build Order
2. Fully allocate the stock as normal
3. Under the "Pending Items" tab, click "New Build Output"
4. Populate the Quantity field, check "Confirm" then click Submit

**Expected behavior**
The Build Output would be created.

**Actual Behavior**
Blocker: The application presents "Form errors exist" and no further action can be taken (as the required fields are complete)
![image](https://user-images.githubusercontent.com/2242776/155065676-936f6ece-8864-4227-a9ba-103af6f6addf.png)

Further inspection of the network in DevTools, shows a post to /api/build/1/create-output/ with the response:
```json
{"auto_allocate":["This field may not be null."]}
```

**Deployment Method**
- Docker

**Version Information**
InvenTree-Version: 0.6.0
Django Version: 3.2.12
Commit Hash: 37bd573
Commit Date: 2022-02-21
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by ssewell** [comment]
Confirmed that intercepting the POST and changing the payload to include `"auto_allocate":false` in the JSON results is successful creation of the build output.

**Comment by matmair** [comment]
@ssewell thanks for reporting!
I will take a deeper look in a few hours, should be a simple fix.

**Comment by matmair** [comment]
@ssewell could you provide the settings of the part you are trying to build?

**Comment by ssewell** [comment]
Do you have a particular query I can run against PostgreSQL? Or which attributes do you need?

**Comment by matmair** [comment]
A screenshot of the parts page should be enough
![grafik](https://user-images.githubusercontent.com/66015116/155243904-f8a2b784-72f7-4a69-9272-c5149e6545eb.png)

**Comment by matmair** [comment]
@ssewell found it, is a one-line fix.

**Comment by ssewell** [comment]
Thanks @matmair! Cherry-picked the change into my local environment and tested that I can create the build output for the part now. A little late, but here's a screenshot of the part's attributes that is being assembled for reference:
![image](https://user-images.githubusercontent.com/2242776/155253014-08664746-796e-4e27-bf6a-02bd6d2620f7.png)
