### ISSUE TITLE
Docker compose web interface broken in production mode

### ISSUE THREAD

**Issue by flinthamm** [inventree/InvenTree#2664]
**Describe the bug**
Follow Docker setup instructions https://inventree.readthedocs.io/en/latest/start/docker/ to successfully install Inventree using 2 containers and external mariadb (mysql) database.

**Steps to Reproduce**

1) Follow https://inventree.readthedocs.io/en/latest/start/docker/ instructions 
2) Use modified docker-compose.yml https://github.com/inventree/InvenTree/blob/master/docker/docker-compose.yml keeping everything the same but commenting out inventree-db section and references.
3) Use https://github.com/inventree/InvenTree/blob/master/docker/dev-config.env but change INVENTREE_DB_ENGINE to mysql and specify MariaDB external db settings
4) Use mariadb tools to create blank database and user
5) Use instructions from (1) to create database, initialise \static folder, create superuser, etc.

**Expected behavior**
Expect the normal login page and interface, rather than the one depicted at the beginning of closed issue #1720

Everything appears to install smoothly, the tables are create and initialised the super user created after prompting for details, etc, etc. but on bringing up the web interface it is broken? 

If the INVENTREE_DEBUG environment variable is changed from 'False' to 'True' (nothing else) and the containers restarted everything appears to run and the web interface displays and behaves as expected?

<!---
![image](https://user-images.githubusercontent.com/1732958/155105940-395db983-b709-44d5-8b30-fb2fd650d4ba.png)

**Deployment Method**
- Docker compose

**Version Information**
inventree/inventree:stable

**Comment by SchrodingersGat** [comment]
It looks like you are missing the static files (CSS etc). Can you check in docker whether the inventree-proxy container is running?

**Comment by flinthamm** [comment]
Hi @SchrodingersGat and thank  you for a very prompt reply.  I can confirm the proxy is not running (this will only be accessed internally) but this is the same case in both instances i.e. the web interface is broken when the INVENTREE_DEBUG=False but then after ONLY changing this environment to True and re-starting the container everything is okay? Is this expected?

**Comment by matmair** [comment]
@flinthamm the proxy also serves the static and media files in production mode, I recommend to keep it running.

**Comment by matmair** [comment]
This is expected, in debug mode incentree-server itself serves the files. This is not good performance wise - so nginx (in the proxy container) is used to facilitate that much faster.

**Comment by flinthamm** [comment]
![image](https://user-images.githubusercontent.com/1732958/155115502-2443abda-968f-4d26-9792-1ad5d47812ac.png)
This is what's displayed when accessing /static/ when the web interface is working (i.e. DEBUG=True) and logged in.

Thank you @matmair for your reply and update. I was just about to reply before your second message but if this is expected then that's fine now I know (and hopefully this might help others) and please consider this case closed. 

A closing comment, which I know it's off topic but is there a trial version of the Android app, so the system can be tested properly before commitment?

**Comment by matmair** [comment]
@flinthamm the development server is not production ready so there are a few things missing on it.

The app is a private endeavour by the maintainer @SchrodingersGat . As far as I know there is no trial - I find it worth its price but I am somewhat biased towards the creator.

**Comment by SchrodingersGat** [comment]
@flinthamm just to chime in again here - check out the docs related to [running in debug mode](https://inventree.readthedocs.io/en/latest/start/intro/#potential-issues) - where this is documented in further detail.

I believe that the android play store lets you trial an app and get a refund within a certain amount of time? The one-off cost of the app is pretty low, in any case.

**Comment by flinthamm** [comment]
Well, excellent work and hat's off to @SchrodingersGat and hopefully some purchases will be made once some more testing has taken place. 
Yes totally agree (the word cheap skate comes to mind ;) and thanks for the link. Hopefully speak again at some point.
