### ISSUE TITLE
[FR] Location specific stock minimums

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#2665]
**Problem**
We have multiple locations that should always have a minimum number of spares but it seems that the minimum stock alerts are system wide.

As an a example of the problem we are trying to solve, we keep spare GPS puck antennas because they are built really cheap and they live a rough life.  We buy the pucks by the box (so 10 at a time) so the main location has 10, but the other location should have 1 spare puck so that it is available when they inevitably break the puck.

**Suggested solution**
Specify and get stock alerts for a specific location rather than just global.

**Describe alternatives you've considered**
A separate installation for each location seems to be excessive since they would be largely duplicated as the same hardware moves between the locations.

I am not familiar enough with what is exposed in InvenTree's api to know if it could do this, but that is the current plan for this feature.  This is not ideal though as the Operations Manager who would like to set these mins is not a programmer so any changes would require a developer.

**Examples of other systems**
I have not looked into how other inventory systems do this.

**Do you want to develop this?**
Possibly, but it would likely not happen for quite some time.

**Comment by matmair** [comment]
@nwns please add a title if you find time to.

This seems like a good use case for a plugin - with the [EventMixin](https://inventree.readthedocs.io/en/latest/extend/plugins/event/) and possible wait till the notificaton remaster is done #2372

**Comment by nwns** [comment]
Definitely still relevant, though have not had time to look into the plugin system.

**Comment by SchrodingersGat** [comment]
@nwns I'm going to close this issue out for now, please re-open if you get a chance to look into it!
