### ISSUE TITLE
Question about docker images

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2669]
Hi, is it normal  to have these images?
```
 REPOSITORY                    TAG       IMAGE ID       CREATED          SIZE
docker_inventree-dev-server   latest    9cdf27fa25da   10 minutes ago   1.02GB
docker_inventree-dev-worker   latest    9cdf27fa25da   10 minutes ago   1.02GB
<none>                        <none>    e06963446dfe   10 minutes ago   1.22GB
postgres                      13        faa0ddfa0c0f   8 days ago       371MB
alpine                        3.13      6b7b3256dabe   3 months ago     5.62MB
```
The most questionable that one <none>.

**Comment by matmair** [comment]
@HelgiBergmann in general yes. No idea about that middle container but the others are normal if you created the images on your system.

**Comment by SchrodingersGat** [comment]
Yep, that is perfectly normal. I would *think* that the `<none>` image is part of the multi-stage-build from *docker-compose*, but could be wrong about that.
