### ISSUE TITLE
Request: Add droplet as deployment method

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2670]
Hi there @schrodingersgat @eeintech!
I would like to add the DigitalOcean droplet I recently created as a deployment method. There is the possibility to add a referral code to the link. If it is ok with you I would create a PR that adds a button to the Readme that enables a secure deployment to DigitalOcean within 3-5 min (if you already have a DigitalOcean account - else it is around 10 from start to ready deployment).

https://marketplace.digitalocean.com/apps/inventree

The update to 0.6.0 is already in review. The referral terms are: I get 25$ once a new customer (came from the app) spend 25$ as a credit on their plattform. I currently use Linode so I would not have use for it but I will switch if one or two referrals come in. I would be open to porridge resources for hosting the demo instance if you want.

**Comment by SchrodingersGat** [comment]
Sounds like a great idea, I'd be happy to merge such a PR
