### ISSUE TITLE
[BUG] Plugins don't work on pre-2.2.0 versions of git

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#2672]
**Describe the bug**
All plugins in Settings->Plugin Settings->Plugins are in Error state with message `Invalid isoformat string: '%aI'`.

This message is caused by "%aI - author date, strict ISO 8601 format" git log option introduced in git ver 2.2.0-rc0.
https://github.com/inventree/InvenTree/blob/733062385c455d02371e34890a90b3be9e2dee04/InvenTree/plugin/helpers.py#L98
On some distros (Centos 7, EOL June 30, 2024) latest git is only 1.8.3.
This issue can be fixed by updating git to the latest (post 2.2.0 version).

**Deployment Method**
- Bare Metal

**Version Information**
InvenTree-Version: 0.6.0
Django Version: 3.2.12
Commit Hash: ad702e794
Commit Date: 2022-02-24
Database: mysql
Debug-Mode: True
Deployed using Docker: False

**Comment by matmair** [comment]
Ok that is my fault. Sorry about that. I will add a catch for that on the weekend.
Thank you for reporting and finding a fix @sintech ! How do you like the release except for that?

**Comment by sintech** [comment]
> How do you like the release except for that?

I just updated and still can't get used to the new design ;). Working on a "classic" theme to mimic BS4 colors and forms.

**Comment by matmair** [comment]
> I just updated and still can't get used to the new design ;). Working on a "classic" theme to mimic BS4 colors and forms.

If that is the only complaint after rewriting over 25% of the codebase I am happy. The old library was not supported for years and thete were a few security issues with it, this one will get us through for at least a few years. Also the UI works a lot better in a lot of places if there are a lot of parts in the DB.
