### ISSUE TITLE
[FR] Zapier integration

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2681]
**Problem**
Zapier offers a ton of further integrations. One integration opens up a lot of possibilities.

**Suggested solution**
Add an [integration](https://developer.zapier.com/) to Zapier

**Do you want to develop this?**
Yes, in the distant future. If somebody else wants to I am happy to review/discuss.

**Comment by SchrodingersGat** [comment]
Looks interesting. Would you suggest this is implemented as a core feature or as a plugin? I'm assuming the integration would need authentication keys etc for the Zapier service

**Comment by matmair** [comment]
@SchrodingersGat that is yet to be evaluated. My todo is full till thanksgiving as far as I calculated so I did not investigate more than 'should be possible'.
The question is also if they will work with the self-hosting that is currently a core concept. I have ways to get around that but I will think about that once I get all security, architecture and website stuff done.
