### ISSUE TITLE
[FR] Ability to display location information in BOM section of a build

### ISSUE THREAD

**Issue by bkcorwin** [inventree/InvenTree#2683]
**Problem**
We are using the software to setup repeated builds as parts.  As near as we can tell, in order to find the location of each part (row 3 bin 4) you have to click on each item in the BOM and look at its location. 

**Suggested solution**
Is there a way to do one of the following.  1) simply add a location column in the BOM line item section in a build? 2) generate a "pick sheet" which gives a person a printout that lets them know where to find each part they need.

**Comment by matmair** [comment]
Hi there @bkcorwin , welcome to InvenTree!
The locations are normally shown if you extend the line in the build order view.
I have a feeling that you could not use build orders but just the BOM view. As there can be multiple storage locations for each part we do not show the in the BOM view of the part. Once you start a build order you can allocate parts and then get shown where the parts for the build come from. Find details in the docs: https://inventree.readthedocs.io/en/latest/build/build/

**Comment by matmair** [comment]
> Hi @matmair  I think I am doing what you say.  I have an assembly created.  I generate a build order for that assembly.  I goto the allocate stock section to allocate my stock.  However this list of allocated stock still doesn't show a location? 
> ![Screen Shot 2022-02-28 at 8 24 07 AM](https://user-images.githubusercontent.com/16884141/156019492-72925178-fd68-4b61-b095-7db516c1e154.png)
>  

@bkcorwin You are 99% there. If this does not turn into a bug report the locations are under the pluses next to each part name.

**Comment by matmair** [comment]
@bkcorwin no problem. Please close if this is resolved. And feel free to fill out our community survey in the discussions!
