### ISSUE TITLE
Part and BOM Pricing

### ISSUE THREAD

**Issue by hammsbeerman** [inventree/InvenTree#2690]
I am trying to wrap my head around the BOM. 

Perhaps I am missing it, but it would be convenient to have the last price or average price show up on each part, and then have a part that contains a BOM to have the total cost for all line items in the BOM.

**Comment by matmair** [comment]
@hammsbeerman 
There is a pricing modal on parts with a BOM. It is a dollar sign in the right upper corner.

There are more pricing features but they suffer from a few performance problems so they are turned of by default.

**Comment by SchrodingersGat** [comment]
@hammsbeerman if you have any questions or suggestions with regard to pricing, now is the time... The pricing models are in the process of being reworked (significantly) in preparation for the next stable release!
