### ISSUE TITLE
[BUG] Serialized stock can only be deleted from parts page

### ISSUE THREAD

**Issue by reilly-callaway** [inventree/InvenTree#2691]
**Describe the bug**
Serialized stock cannot be deleted from the stock item page. The only page serialized stock can be deleted from is the stock tab in the associated parts page. This is inconsistent with non-serialized stock and less discoverable when deleting a single serialized stock item.

**Expected behavior**
Serialized stock should be able to be deleted from the stock page, the same as non-serialized stock.

**Screenshots**
The only way of deleting serialized stock is from the parts page:
![only_current_method](https://user-images.githubusercontent.com/7870267/156075865-be5dd52d-51a2-4e72-bb53-24cead24f6f5.png)

Non-serialized stock can be deleted from the stock page:
![non-serial-stock](https://user-images.githubusercontent.com/7870267/156076208-2c6d0af1-529f-4e23-a7b9-9db695c174fd.png)

Serialized stock should also be allowed to be deleted from the stock page:
![suggest_solution](https://user-images.githubusercontent.com/7870267/156077104-890c874c-62bd-4bcb-97aa-ad73167c5148.png)

**Deployment Method**
- [ ] Docker
- [X] Bare Metal

**Version Information**
InvenTree-Version: 0.7.0 dev
Django Version: 3.2.12
Commit Hash: 010ce48
Commit Date: 2022-02-28
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by matmair** [comment]
Hi there @reilly-callaway !
Would you be willing to dev this?
Thank you for reporting this
