### ISSUE TITLE
New stock items from trackable parts

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#2716]
Dear Team,
I encountered a small problem. I hope somebody can make a PR:
When you create a new stock item from a trackable part, it has the same behavior like normal stock items. I mean you can edit the quantity, or even have more than 1 quantity, so the new item is definitely not unique. But when you open the edit stock item dialog and just save it without making any changes the item finally becomes unique (see screenshots below).
As I understand there is a step called serialization, where you can assign unique serial numbers for these stock items, but in my case where alphanumeric serials needed I cannot use it.

**Steps to Reproduce**
1. create a new stock item from a trackable part. Note there is a quantity displayed, and no "serialized" message shows up, and in the menu you can add/remove quantities
<img width="1050" alt="Képernyőfotó 2022-03-06 - 9 06 23" src="https://user-images.githubusercontent.com/580623/156914772-c67f5638-b21f-4102-8590-11992015d5b5.png">

2. Edit stock item and just save it without making any changes
<img width="325" alt="Képernyőfotó 2022-03-06 - 8 54 21" src="https://user-images.githubusercontent.com/580623/156914396-90dc8ce7-9df0-46dd-a1cc-2ea1649111d7.png">
<img width="761" alt="Képernyőfotó 2022-03-06 - 8 54 30" src="https://user-images.githubusercontent.com/580623/156914402-3c8d062e-6e5f-47f1-a84a-e349cd52d7b3.png">

3. now it is unique
<img width="876" alt="Képernyőfotó 2022-03-06 - 9 06 49" src="https://user-images.githubusercontent.com/580623/156914786-7e3f0305-d77b-4aea-a379-908734c4144c.png">

**Expected behavior**

When I create a new stock item with quantity is 1, it means no further serialization needed, so it can be unique directly. In this case the serial/batch should be specified.  It will be nice to indicate "this is a trackable part" somehow on the form as well.

**Version Information**
recent master branch

**Comment by SchrodingersGat** [comment]
Confirmed on latest master

**Comment by rkalman** [comment]
Thank you!

**Comment by rkalman** [comment]
Sorry I have just realized the serial field can be alphanumeric as well :) I thought it has to be numeric. 
However if I specify a serial number which is greater than 2^31, the API call api/stock/xxx returns with an error 500.

**Comment by SchrodingersGat** [comment]
@rkalman I thought that specific error had been fixed.. Apparently not. Can you send through the complete error message you see?

**Comment by SchrodingersGat** [comment]
@rkalman managed to reproduce that too.. fix incoming - https://github.com/inventree/InvenTree/pull/2721
