### ISSUE TITLE
[BUG] App QR scanner fails with server version 0.6

### ISSUE THREAD

**Issue by cjdet** [inventree/InvenTree#2718]
**Describe the bug**

Barcode / QR code scanner in iPhone App does not work. App version 0.5.6 and Inventree version 0.6.1

**Steps to Reproduce**

1. Installed a fresh docker version of 0.6.1. 
2. Added a part category and a single new part and displayed the QR code for that part.
3. Opened the iPhone App (version 0.5.6), connected to server.
4. Scan barcode within the app5. 
5. App fails with "No match for barcode" message

**Expected behavior**

Expected to open the part in the App as it worked in 0.5.4 of Inventree with the App.

The App fails with the message "No match for barcode"

inventree-proxy log contains message  "POST /api/barcode/ HTTP/1.1" 200 130 "-" "Dart/2.13 (dart:io)" "-"  

**Deployment Method**
- [x ] Docker
- [ ] Bare Metal

**Version Information**

App version 0.5.6 and Inventree version 0.6.1

**Comment by matmair** [comment]
@SchrodingersGat

**Comment by SchrodingersGat** [comment]
Confirmed the bug, working on a fix.
