### ISSUE TITLE
[BUG] Text cannot be translated

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#2734]
On this form the marked text is always in english, no translation available on crowdin:
<img width="1277" alt="Képernyőfotó 2022-03-09 - 23 25 07" src="https://user-images.githubusercontent.com/580623/157551263-b7f4dd29-3050-437a-b77f-7c9bb0720eee.png">

**Comment by SchrodingersGat** [comment]
Thanks for reporting @rkalman - fix at #2735
