### ISSUE TITLE
[FR] Live editor for report and label templates

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2777]
Currently the process of adding report and label templates is complex, requiring upload of template files (.html) without a "live preview".

An alternative workflow could be to provide a "preview" window, much like the markdown editor.

The templates can be rendered to an image, rather than PDF, allowing "live" rendering as the template is edited.

This would make the whole reporting / labelling ecosystem much more user friendly.

**Comment by matmair** [comment]
@SchrodingersGat sounds like a huge task. I thought about that too. Monaco editor or CodeMirror could be a reasonable way to build it.

**Comment by SergeoLacruz** [comment]
Looks like a cool feature. But is it worth the effort? How much time does the team save in daily usage. It depends on the use cases. 
I see the templates being created once by an administrator or an administrative team. Them they are stable for years and just used by the designers. But that's just my use case. There might be others.

**Comment by matmair** [comment]
@SergeoLacruz thank you for your inside. The idea is to lower the barrier of entry for creating reports - we have many open FRs that are more important so this is more theory till someone who wants to dev it comes around.

**Comment by SchrodingersGat** [comment]
Interesting reference: https://printcss.live/

**Comment by matmair** [comment]
@SchrodingersGat should we move this to a plugin and off this milestone?

**Comment by SchrodingersGat** [comment]
This has been closed now, thanks to the great work by @wolflu05  :)
