### ISSUE TITLE
[BUG] Floating point precision problem when calculating required quantities in a build order

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#2781]
This is a tricky one.

Create a new part to build, with a BOM item that require fraction quantities:
<img width="1674" alt="Képernyőfotó 2022-03-27 - 9 34 40" src="https://user-images.githubusercontent.com/580623/160271874-908fd778-6e2d-4d84-8c2f-202519907b80.png">

Create new build order with more than one quantity:
<img width="1242" alt="Képernyőfotó 2022-03-27 - 9 35 51" src="https://user-images.githubusercontent.com/580623/160271903-c86c966a-3617-4471-927c-721466615244.png">

And note the required quantity:
<img width="1650" alt="Képernyőfotó 2022-03-27 - 9 36 03" src="https://user-images.githubusercontent.com/580623/160271930-2bae9669-8574-425c-8b02-02eedadf12b6.png">

Try to allocate:
<img width="1243" alt="Képernyőfotó 2022-03-27 - 9 36 59" src="https://user-images.githubusercontent.com/580623/160271956-796f8e8d-479d-47ed-9cb1-e5c8a36ceff8.png">

**Comment by SchrodingersGat** [comment]
@rkalman thanks for reporting this, looks like the age-old floating point issues have reared their head again! Fixes in https://github.com/inventree/InvenTree/pull/2782
