### ISSUE TITLE
[BUG] 404 missing url api/plugin

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#2784]
When you want to print labels, note the red message in the background:
<img width="356" alt="Képernyőfotó 2022-03-28 - 9 23 51" src="https://user-images.githubusercontent.com/580623/160347355-e38ca98e-6e6f-4ca1-abde-8860cf9bb2c6.png">
<img width="564" alt="Képernyőfotó 2022-03-28 - 9 23 57" src="https://user-images.githubusercontent.com/580623/160347369-ac7f2150-45c1-4521-926a-db94310586d9.png">

**Comment by SchrodingersGat** [comment]
Do you have plugins enabled on the server?

**Comment by rkalman** [comment]
It is coming from demo.inventree.org, possibly plugins not enabled.
But it would be nice to avoid this red message even if no plugins enabled.

**Comment by SchrodingersGat** [comment]
Fix incoming at https://github.com/inventree/InvenTree/pull/2785

**Comment by rkalman** [comment]
Thank you!
