### ISSUE TITLE
[BUG] Check-in broken after update to 0.6.2

### ISSUE THREAD

**Issue by alexisvl** [inventree/InvenTree#2787]
**Describe the bug**
After updating to 0.6.2 from 0.5.something (sorry) I'm having a weird issue with the "Check-in items" tool on stock locations. See screenshot - this is after scanning a valid barcode. It says "added stock item", but the table shows nothing, and the check-in button is not clickable. If I re-scan the item, it then says "Stock item already scanned" and I can click Check In now and it seems to work, but the item is still not shown in the dialog.

This doesn't seem to happen _every_ time but it does happen most times.

**Steps to Reproduce**

1. Go to a stock location.
2. Choose "Check-in items".
3. Start scanning.

**Expected behavior**

The item is shown in the dialog box's table on the first scan.

**Screenshots**

![checkin](https://user-images.githubusercontent.com/8991037/160504472-d2120fc8-79ec-4e56-bf6a-fcd0f50a99b6.png)

(The little green icon in that dialog is from a browser extension, I did try with that disabled, no difference.)

**Deployment Method**
- [X] Docker
- [ ] Bare Metal

**Version Information**
InvenTree-Version: 0.6.2
Django Version: 3.2.12
Commit Hash: 950d185
Commit Date: 2022-03-10
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by alexisvl** [comment]
Actually, I said that double-scanning will make it work, but I just tried it this time and got a 400 error. I'm too nooby with web app anything to know where to get more info about that, I checked /var/log inside the container for anything interesting with no luck and the "Error report" page in the admin interface shows nothing.

**Comment by alexisvl** [comment]
I just got the "Stock item already scanned" from the _main_ barcode scan dialog this time - the one that should take me to that stock item's page on scan. Something is very very weird here.

**Comment by alexisvl** [comment]
To maybe put some more bounds on this issue - I also get the 400 if I go to the stock item page first and then "Scan to location", but it's happy to let me reassign the location via "Transfer stock".

**Comment by SchrodingersGat** [comment]
@alexisvl thanks for reporting this, we'll take a look :)

**Comment by SchrodingersGat** [comment]
@alexisvl fixes in https://github.com/inventree/InvenTree/pull/2803

Are you able to check if it works (as far as you can tell)?

You can click on the "gitpod" link on the referenced PR to launch the new code in a web browser without having to download or run anything locally.

**Comment by SchrodingersGat** [comment]
Fix has been made, lmk if you still see any issues!

**Comment by alexisvl** [comment]
Weird, apparently I wasn't getting notifications. Oops. Thank you so much, I'll test this out soon.

**Comment by alexisvl** [comment]
This was fixed, but it's broken again recently. Nearly identical symptoms, except now a bit of a gap gets added to the table:

![Screen Shot 2022-10-05 at 19 32 58](https://user-images.githubusercontent.com/8991037/194195055-d0d21947-8086-4f76-932b-c58231bb68f3.JPG)

0.9.0 dev / 61a6ecd

**Comment by alexisvl** [comment]
> @alexisvl please don't hijack closed issues.

Underneath "lmk if you still see any issues!" seemed like an apt place to let them know I still saw issues. Please don't use rude terms like "hijack" to politely suggest etiquette.

**Comment by matmair** [comment]
@alexisvl issue closed, affirmed resolve, 6 months and 2 point releases later => not related => hijack of fixed and closed bug. I stand by my wording choice.
