### ISSUE TITLE
[BUG] Deleting a Customer Breaks Associated Sales Orders

### ISSUE THREAD

**Issue by maksimstojkovic** [inventree/InvenTree#2788]
**Describe the bug**

After deleting a Customer, any existing Sales Orders associated with the Customer receive the name "Invalid Customer", and cannot be opened using the left-side link in the Sales Order table.

**Steps to Reproduce**

1. Go to page for specific Customer.
2. Access admin panel using blue icon with tooltip "View in Administration Panel".
3. Scroll to bottom of admin panel page and delete customer.
4. Return to Sales Order list page.
5. Click on Sales Order which now says "Invalid Customer".

**Expected behavior**

Open Sales Order window where line items, shipments and allocations can be viewed.
If this expected behaviour is incorrect, please let me know an alternative for handling access to the broken SO.

**Screenshots**

![image](https://user-images.githubusercontent.com/18454392/160542110-3060d0fb-5e67-47b1-8980-a37c62ffe775.png)

I believe the following line in `InvenTree/order/models.py` is the cause of the issue as it references `None` since the customer no longer exists.

![image](https://user-images.githubusercontent.com/18454392/160542692-a4dffc0c-f663-4b60-a530-d9b6dd922d4a.png)

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**

InvenTree-Version: 0.6.2
Django Version: 3.2.12
Commit Hash: 950d185
Commit Date: 2022-03-10
Database: mysql
Debug-Mode: True
Deployed using Docker: True

**Comment by matmair** [comment]
Hi there @maksimstojkovic !
Is there a specific reason you use the admin panel to delete the company? We generally do not recommend to use the admin panel if not advised to as some business logic is not applied there.

**Comment by maksimstojkovic** [comment]
Hi @matmair!

There was no particular reason for using the admin panel. I just tested deleting a customer without accessing the admin panel and the same behaviour was observed.

It appears the issue is in the string shown in the page breadcrumb.

**Comment by maksimstojkovic** [comment]
I believe that the behaviour of Sales Orders remaining after customer deletion is correct as allocations should not be destroyed during customer deletion (e.g. deleting customer after an SO has been shipped).

**Comment by matmair** [comment]
@maksimstojkovic just trying to root out causes while I am away from my dev environment.
I think it should be an easy fix. You are right about orders being persistent. In general i do not recommend deleting anything.

**Comment by SchrodingersGat** [comment]
@maksimstojkovic thanks for raising this issue. Deciding on the "correct" behaviour here is tricky. If the customer (`Company`) object is deleted, but you wish to retain orders associated with the customer, then those orders lose the reference to the original customer.

As @matmair suggests, if you want to retain this data, then not deleting the customer is the way to go.

However, clearly you've found a non-viable situation - deleting the existing customer breaks the sales order page.

I think that this problem might also affect "suppliers" and "purchase orders".

So, the options, as I see them, are:

1. Delete orders associated with a company when that company is deleted
2. Retain order information when a company is deleted, and allow these orders to be displayed without error
3. Do not let a company be deleted if there are orders associated with the company

There may be some other options here to, which I'd be open to.

But, clearly we need to make a decision!

**Comment by matmair** [comment]
@SchrodingersGat I choose to implement 2 as it seems to be the solution that keeps the most options for users whilst providing good data retention. I will use a custom manager and models.SET() for that.

**Comment by matmair** [comment]
@maksimstojkovic this is now fixed in master

**Comment by maksimstojkovic** [comment]
Thanks for resolving this! I look forward to seeing the fix in the next release. 🙂
