### ISSUE TITLE
[FR] Include substitute items into "Available" stock in BOM table

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#2790]
**Problem**
Currently only stock for base Item is displayed in BOM table. When we have substitutes for an item, their stock is not counted as available and only can be seen in "Edit BOM Item Substitutes" window. "Can Build" column is also calculated only for base item.

**Suggested solution**
Display total stock of substituted items plus base item.

**Describe alternatives you've considered**
Show total availability of substitute stock in parentheses after base item availability. Same with "Can Build".

**Do you want to develop this?**
Not sure I can.

**Comment by SchrodingersGat** [comment]
This is a good idea, might be a little complex to implement but should be able to make it work :)

**Comment by matmair** [comment]
@SchrodingersGat this could get complex fast. Do you think 0.7.0 is realistic?

**Comment by SchrodingersGat** [comment]
This has now been implemented - substitute stock quantities are included in BOM table
