### ISSUE TITLE
[BUG] BOM table available stock calculation

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#2795]
**Describe the bug**
BOM table shows "in stock" in "Available" column instead of "Available stock". So this field excludes allocations.

**Steps to Reproduce**
![Képernyőfotó 2022-03-31 - 17 28 27](https://user-images.githubusercontent.com/580623/161093293-5f116d89-6df8-47f1-8165-713a45cdcf25.png)
![Képernyőfotó 2022-03-31 - 17 29 35](https://user-images.githubusercontent.com/580623/161093307-f0b9e681-6fa7-4a05-a866-9a6d4af9cb81.png)

**Expected behavior**
Show available stock in the available column.

**Version Information**
demo.inventree.org

If you agree I can submit a PR for this to review.

**Comment by matmair** [comment]
Thanks for the report @rkalman !
Please also add the version information if you report errors on demo.inventree.org . We update daily so it becomes hard to find the effected tag after a few days. If something is dormant for a while it is nearly impossible to identify which versions need patching.

**Comment by rkalman** [comment]
# Version Information:
InvenTree-Version: 0.7.0 dev
Django Version: 3.2.12
Commit Hash: 6eab3db
Commit Date: 2022-03-30
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by rkalman** [comment]
Fixed by #2796
