### ISSUE TITLE
[BUG] ValueError: Field 'id' expected a number but got ''.

### ISSUE THREAD

**Issue by marianhlavac** [inventree/InvenTree#2800]
After few weeks of using the self-hosted Inventree instance we noticed, after a few days of not using it, that it is not acessible anymore and returns 500 to all requests. After exploring the logs it seems there is some kind of database access failure.

There is a little chance we had database corruption due to service outage. We host the Postgres instance on Amazon RDS and we never touched the database dedicated to Inventree. Other databases are intact. Database logs contains no evidence of errors, only suddenly failing SELECT queries, which probably is related to the 500:

```
inventree@inventree:[32588]:STATEMENT: SELECT "common_notificationentry"."id", "common_notificationentry"."key", "common_notificationentry"."uid", "common_notificationentry"."updated" FROM "common_notificationentry" WHERE "common_notificationentry"."updated" <= '2021-12-23T09:40:05.766670+01:00'::timestamptz
inventree@inventree:[32588]:ERROR: relation "common_notificationentry" does not exist at character 151
```

These two lines are repeating in postgres logs, and it seems that each day there are more of them. Not sure if this is caused by inventree or by our container orchestrator, but it definitely puts/might put an unnecessary stress to our database.

![Screenshot 2022-04-03 at 11 16 55](https://user-images.githubusercontent.com/3010503/161420575-d2f7e88d-5ffc-4977-a77f-64d2adaf9502.png)

What seems to be relevant — there were few container failures (non-zero exits) in the task history of our container orchestrator on the inventree-server container, but unfortunately we don't have historical logs for these failed containers. Either way, if the non-zero exists are the cause, they shouldn't irrevertibly corrupt the database.

**Logs**

<details>
<pre>
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
w35is     return self.template.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
w35is     return self._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
w35is     return compiled_parent._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
w35is     return template.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
w35is     return self._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
w35is     output = self.func(*resolved_args, **resolved_kwargs)
w35is   File "/home/inventree/InvenTree/part/templatetags/inventree_extras.py", line 258, in settings_value
w35is     return InvenTreeUserSetting.get_setting(key, user=kwargs['user'])
w35is   File "/home/inventree/InvenTree/common/models.py", line 299, in get_setting
w35is     setting = cls.get_setting_object(key, **kwargs)
w35is   File "/home/inventree/InvenTree/common/models.py", line 1241, in get_setting_object
w35is     return super().get_setting_object(key, user=user)
w35is   File "/home/inventree/InvenTree/common/models.py", line 249, in get_setting_object
w35is     settings = settings.filter(user=user)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
w35is     return self._filter_or_exclude(False, args, kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
w35is     clone._filter_or_exclude_inplace(negate, args, kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
w35is     self._query.add_q(Q(*args, **kwargs))
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1393, in add_q
w35is     clause, _ = self._add_q(q_object, self.used_aliases)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
w35is     child_clause, needed_inner = self.build_filter(
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
w35is     condition = self.build_lookup(lookups, col, value)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
w35is     lookup = lookup_class(lhs, rhs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/lookups.py", line 25, in __init__
w35is     self.rhs = self.get_prep_lookup()
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 117, in get_prep_lookup
w35is     self.rhs = target_field.get_prep_value(self.rhs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
w35is     raise e.__class__(
w35is ValueError: Field 'id' expected a number but got ''.
w35is  
w35is During handling of the above exception, another exception occurred:
w35is  
w35is Traceback (most recent call last):
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
w35is     return int(value)
w35is ValueError: invalid literal for int() with base 10: ''
w35is  
w35is The above exception was the direct cause of the following exception:
w35is  
w35is Traceback (most recent call last):
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
w35is     response = get_response(request)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
w35is     response = response or self.get_response(request)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
w35is     response = response_for_exception(request, exc)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
w35is     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
w35is     return callback(request)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
w35is     response = view_func(request, *args, **kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/views/defaults.py", line 97, in server_error
w35is     return HttpResponseServerError(template.render())
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
w35is     return self.template.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
w35is     return self._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
w35is     return compiled_parent._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
w35is     return template.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
w35is     return self._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
w35is     output = self.func(*resolved_args, **resolved_kwargs)
w35is   File "/home/inventree/InvenTree/part/templatetags/inventree_extras.py", line 258, in settings_value
w35is     return InvenTreeUserSetting.get_setting(key, user=kwargs['user'])
w35is   File "/home/inventree/InvenTree/common/models.py", line 299, in get_setting
w35is     setting = cls.get_setting_object(key, **kwargs)
w35is   File "/home/inventree/InvenTree/common/models.py", line 1241, in get_setting_object
w35is     return super().get_setting_object(key, user=user)
w35is   File "/home/inventree/InvenTree/common/models.py", line 249, in get_setting_object
w35is     settings = settings.filter(user=user)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
w35is     return self._filter_or_exclude(False, args, kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
w35is     clone._filter_or_exclude_inplace(negate, args, kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
w35is     self._query.add_q(Q(*args, **kwargs))
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1393, in add_q
w35is     clause, _ = self._add_q(q_object, self.used_aliases)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
w35is     child_clause, needed_inner = self.build_filter(
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
w35is     condition = self.build_lookup(lookups, col, value)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
w35is     lookup = lookup_class(lhs, rhs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/lookups.py", line 25, in __init__
w35is     self.rhs = self.get_prep_lookup()
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 117, in get_prep_lookup
w35is     self.rhs = target_field.get_prep_value(self.rhs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
w35is     raise e.__class__(
w35is ValueError: Field 'id' expected a number but got ''.
w35is  
w35is During handling of the above exception, another exception occurred:
w35is  
w35is Traceback (most recent call last):
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
w35is     return int(value)
w35is ValueError: invalid literal for int() with base 10: ''
w35is  
w35is The above exception was the direct cause of the following exception:
w35is  
w35is Traceback (most recent call last):
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
w35is     response = get_response(request)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
w35is     response = response or self.get_response(request)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
w35is     response = response_for_exception(request, exc)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
w35is     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
w35is     return callback(request)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
w35is     response = view_func(request, *args, **kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/views/defaults.py", line 97, in server_error
w35is     return HttpResponseServerError(template.render())
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
w35is     return self.template.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
w35is     return self._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
w35is     return compiled_parent._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
w35is     return template.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
w35is     return self._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
w35is     output = self.func(*resolved_args, **resolved_kwargs)
w35is   File "/home/inventree/InvenTree/part/templatetags/inventree_extras.py", line 258, in settings_value
w35is     return InvenTreeUserSetting.get_setting(key, user=kwargs['user'])
w35is   File "/home/inventree/InvenTree/common/models.py", line 299, in get_setting
w35is     setting = cls.get_setting_object(key, **kwargs)
w35is   File "/home/inventree/InvenTree/common/models.py", line 1241, in get_setting_object
w35is     return super().get_setting_object(key, user=user)
w35is   File "/home/inventree/InvenTree/common/models.py", line 249, in get_setting_object
w35is     settings = settings.filter(user=user)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
w35is     return self._filter_or_exclude(False, args, kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
w35is     clone._filter_or_exclude_inplace(negate, args, kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
w35is     self._query.add_q(Q(*args, **kwargs))
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1393, in add_q
w35is     clause, _ = self._add_q(q_object, self.used_aliases)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
w35is     child_clause, needed_inner = self.build_filter(
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
w35is     condition = self.build_lookup(lookups, col, value)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
w35is     lookup = lookup_class(lhs, rhs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/lookups.py", line 25, in __init__
w35is     self.rhs = self.get_prep_lookup()
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 117, in get_prep_lookup
w35is     self.rhs = target_field.get_prep_value(self.rhs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
w35is     raise e.__class__(
w35is ValueError: Field 'id' expected a number but got ''.
w35is  
w35is During handling of the above exception, another exception occurred:
w35is  
w35is Traceback (most recent call last):
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
w35is     return int(value)
w35is ValueError: invalid literal for int() with base 10: ''
w35is  
w35is The above exception was the direct cause of the following exception:
w35is  
w35is Traceback (most recent call last):
w35is   File "/usr/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
w35is     self.handle_request(listener, req, client, addr)
w35is   File "/usr/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
w35is     respiter = self.wsgi(environ, resp.start_response)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
w35is     response = self.get_response(request)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
w35is     response = self._middleware_chain(request)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
w35is     response = response_for_exception(request, exc)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
w35is     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
w35is     return callback(request)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
w35is     response = view_func(request, *args, **kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/views/defaults.py", line 97, in server_error
w35is     return HttpResponseServerError(template.render())
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
w35is     return self.template.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
w35is     return self._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
w35is     return compiled_parent._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
w35is     return template.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
w35is     return self._render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
w35is     return self.nodelist.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
w35is     bit = node.render_annotated(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
w35is     return self.render(context)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
w35is     output = self.func(*resolved_args, **resolved_kwargs)
w35is   File "/home/inventree/InvenTree/part/templatetags/inventree_extras.py", line 258, in settings_value
w35is     return InvenTreeUserSetting.get_setting(key, user=kwargs['user'])
w35is   File "/home/inventree/InvenTree/common/models.py", line 299, in get_setting
w35is     setting = cls.get_setting_object(key, **kwargs)
w35is   File "/home/inventree/InvenTree/common/models.py", line 1241, in get_setting_object
w35is     return super().get_setting_object(key, user=user)
w35is   File "/home/inventree/InvenTree/common/models.py", line 249, in get_setting_object
w35is     settings = settings.filter(user=user)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
w35is     return self._filter_or_exclude(False, args, kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
w35is     clone._filter_or_exclude_inplace(negate, args, kwargs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
w35is     self._query.add_q(Q(*args, **kwargs))
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1393, in add_q
w35is     clause, _ = self._add_q(q_object, self.used_aliases)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
w35is     child_clause, needed_inner = self.build_filter(
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
w35is     condition = self.build_lookup(lookups, col, value)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
w35is     lookup = lookup_class(lhs, rhs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/lookups.py", line 25, in __init__
w35is     self.rhs = self.get_prep_lookup()
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 117, in get_prep_lookup
w35is     self.rhs = target_field.get_prep_value(self.rhs)
w35is   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
w35is     raise e.__class__(
w35is ValueError: Field 'id' expected a number but got ''.
</pre>
</details>

**Deployment Method**
Docker (using Docker Swarm mode)

**Version Information**
Using image `inventree/inventree:stable` (6fcd108c39288b878307714ed1fc3fe4f118dc3ff9bdb32098e5db1345ff4e4f)

**Comment by marianhlavac** [comment]
Ah, managed to figure it out, of course right after opening the issue.

What I haven't noticed was failing runs of `invoke update` after version update. There was new version pushed to the stable channel, but the migrations were never performed. I ran `invoke migrate` and the problems went away.

But still the issue with `invoke update` persists and caused this situation.

For some reason it cannot be performed due to missing requirements.txt. We haven't modified the inventree/inventree:stable image.

```
bash-5.1$ invoke update
Installing required python packages from 'requirements.txt'
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by SchrodingersGat** [comment]
I'm assuming you're attempting to run `invoke update` from the default directory inside the docker container? (e.g. `/home/inventree`)?

@matmair do you have any experience running docker swarm?

**Comment by matmair** [comment]
While I do not deploy with swarm it should work. I am using k8 in my deployments without problems. Probably a problem withe the path.
@marianhlavac can you check if the file is existing in the image?

**Comment by matmair** [comment]
@marianhlavac the requirements file should be in / and in /docker (from the containers entrypoint - which normally is /home/InvenTree/). Could you check for them in the image?

**Comment by marianhlavac** [comment]
Hi guys, thanks for giving attention to this, sorry for the delay.

@matmair is right, the working directory was incorrect, I was running the `invoke update` command using `docker exec` instread of `docker run`. For some reason (will investigate later) the working directory is different for these two commands:

```
❯ docker compose run inventree-server pwd
[+] Running 1/0
 ⠿ Container inventree-db  Running                                                                                                                                                     0.0s
Creating directory /home/inventree/data/static
Creating directory /home/inventree/data/media
Copying config file to /home/inventree/data/config.yaml
InvenTree translation coverage: 15%

/home/inventree
```

vs

```
❯ docker compose up inventree-server -d
[+] Running 3/3
 ⠿ Network docker_default      Created                                                                                                                                                 0.0s
 ⠿ Container inventree-db      Started                                                                                                                                                 0.2s
 ⠿ Container inventree-server  Started                                                                                                                                                 0.4s

❯ docker compose exec inventree-server pwd

/home/inventree/InvenTree
```

Thanks for the help, this issue was caused just because of wrong configuration and wrong expectations.

**Comment by matmair** [comment]
@marianhlavac no problem. If the documentation could be clearer do not hesitate to point it out.
We always try to improve and are pretty new to these technologies ourselfs.
