### ISSUE TITLE
[BUG] "invoke superuser" hangs

### ISSUE THREAD

**Issue by nelsonov** [inventree/InvenTree#2802]
**Describe the bug**
invoke superuser hangs
```
(env) inventree@rpi07:~/src $ invoke superuser
Username (leave blank to use 'inventree'): inventree

```
There is a CR/LF after the Username prompt, but then nothing more.

**Steps to Reproduce**

```
source ~/env/bin/activate
cd ~/src/InvenTree
invoke superuser
```

**Expected behavior**
command executes and completes 

**Deployment Method**
- [ ] Docker
- [x] Bare Metal

**Version Information**
git commit d1d7db76cc1109f46cc8404470f93a96ad0ca51f

**Environment**
Bare metal Raspberry Pi 4B
Raspberry Pi OS 10
python 3.7.3
MariaDB 

**Additional Info**
Database inventree exists
Can connect to database from command line and `show tables;` using credentials from config.yaml

**Comment by nelsonov** [comment]
Is there a way to replicate the commands that "invoke superuser" would have done?  Does it just create entries in the database or does it do a lot more?  I know nothing about Django, so this may be a silly question.

**Comment by nelsonov** [comment]
I answered my own question.  I poked around and was able to do this:
```
(env) inventree@rpi07:~/src/InvenTree $ ./manage.py 'createsuperuser'
Username (leave blank to use 'inventree'): 
Email address: lnelson@nelnet.org
Password: 
Password (again): 
Superuser created successfully.
```

I am now able to login as that user.

**Comment by SchrodingersGat** [comment]
@nelsonov great that you got it sorted, but very strange that your solution worked! The `invoke superuser` command is simply running exactly what you are doing behind the scenes...

![image](https://user-images.githubusercontent.com/10080325/161456425-be1f6f51-4e99-4118-9650-44e6c350841b.png)

**Comment by nelsonov** [comment]
Lot's of grep'ing led me to the same path you show above.  I even tried the `invoke superuser` command in the same terminal immediately before running  `manage.py`. `invoke superuser` hung but `manage.py` did not.  Very weird.  I blame gremlins.

**Comment by SchrodingersGat** [comment]
Ah, yes we would suggest that any gremlins are removed from the system before installation.
