### ISSUE TITLE
[BUG] Complete Sales Order Without Refreshing Page

### ISSUE THREAD

**Issue by maksimstojkovic** [inventree/InvenTree#2810]
**Describe the bug**
Upon completing all shipments associated a sales order in the pending shipments menu, the page needs to be refreshed before the order can be completed using the "Complete Order" button. If the page is not refreshed, the button is slightly faded and cannot be clicked.

Additionally the value shown in the "Completed Line Items" is not updated after allocating stock or removing line items.
The "Completed Shipments" field also experiences the same issue when creating, deleting or completing a shipment (regardless of whether it is a partial or complete shipment of the SO).

**Steps to Reproduce**

1. Ship last pending shipment in SO.
2. View "Complete Order" button at top right of screen.

**Expected behavior**

The "Completed Line Items" and "Completed Shipments" fields should be updated and the "Complete Order" button should be clickable. (Minor quality of life improvement).

**Screenshots**

Before Refresh:
![image](https://user-images.githubusercontent.com/18454392/161910527-f5148c8e-e009-4c03-aaed-f96589cf21dd.png)

After Refresh:
![image](https://user-images.githubusercontent.com/18454392/161910602-3b6ef3c8-61f2-4377-8eca-afa357e3b746.png)

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
InvenTree-Version: 0.6.2
Django Version: 3.2.12
Commit Hash: 950d185
Commit Date: 2022-03-10
Database: mysql
Debug-Mode: True
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
Thanks @maksimstojkovic

**Comment by pulimoodan** [comment]
Can you please assign this issue to me

**Comment by matmair** [comment]
@pulimoodan any progress on this? Let us know if we should assist

**Comment by rkalman** [comment]
We also have the same behaviour on other pages ("header" does not refresh automatically to show uptodate information):
 - build order (badges on the left, completed quantity on the right)
 - purchase order (order status on the left, completed line items and dates on the right)

**Comment by SchrodingersGat** [comment]
@rkalman you are right, a lot of pages could be updated to be more "reactive" and make use of the API rather that being rendered statically. This will require a bit of work

**Comment by SchrodingersGat** [comment]
I am reluctant to spend heaps of effort on a patch fix given we are intending to move to a API-heavy framework anyway.

**Comment by pulimoodan** [comment]
Sorry for the long time to reply, I had been into something else.
I tried playing around this issue. As it is Django static template we have to refresh the page or implement it with Ajax and JS. But Ajax will look more complex when we have to work over it for more feature.
Like @matmair  said, it's good to implement this feature in React or Vue and it's easy to do that. Are we moving to any API framework. If the front-end is going to be build in React, I can help you.

**Comment by rkalman** [comment]
I think everyone can live with this behaviour, I just mention them because they are all similar to the first one.

**Comment by maksimstojkovic** [comment]
It's probably a little primitive in the context of robust software implementation, but it's possible to make the Shipment Completion form (and all other offending forms) automatically reload the page on submission, effectively automating the page refresh.

Given that it is not currently worth everyone commiting time to a large-scale change with an upcoming release and future updates already in the dev pipeline, is this a sufficient fix in the mean time, or is it likely to cause problems in the future?

**Comment by SchrodingersGat** [comment]
@maksimstojkovic I'm happy with the proposed fix as a "bandaid" pending UI overhaul.
