### ISSUE TITLE
Exception while importing purchase order file

### ISSUE THREAD

**Issue by G-Pereira** [inventree/InvenTree#2811]
**Describe the bug**

When I try to submit a CSV to a purchase order right after I click "Upload File" I get an Internal Server Error [with this log](https://pastebin.com/sAsdZ8QU)

**Steps to Reproduce**

**Expected behavior**

A file choosing window to select which file on my computer should be uploaded

![image](https://user-images.githubusercontent.com/15521303/162052574-0e758edc-0f53-4184-aa89-302bb90558f1.png)

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**

0.6.3

**Comment by eeintech** [comment]
@G-Pereira Can you please use the standard bug report template for your issue? See below.

```
<!---
Everything inside these brackets is hidden - please remove them where you fill out information.
--->


**Describe the bug**
<!---
A clear and concise description of what the bug is.
--->

**Steps to Reproduce**

Steps to reproduce the behavior:
<!---
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
--->

**Expected behavior**
<!---
A clear and concise description of what you expected to happen.
--->

<!---
**Screenshots**
If applicable, add screenshots to help explain your problem.
--->

**Deployment Method**
- [ ] Docker
- [ ] Bare Metal

**Version Information**
<!---
You can get this by going to the "About InvenTree" section in the upper right corner and clicking on to the "copy version information"
--->
```

**Comment by G-Pereira** [comment]
Sorry @eeintech no idea why the page took me straight to a blank issue

**Comment by G-Pereira** [comment]
Please check now @eeintech

**Comment by eeintech** [comment]
@matmair I can reproduce the error, and it is the same error than one for the view to import parts, I just tested that view in https://github.com/inventree/InvenTree/discussions/2807#discussion-3988597
