### ISSUE TITLE
Default system time

### ISSUE THREAD

**Issue by Rubisco16** [inventree/InvenTree#2813]
Hi there,
Can I change the default system time zone of my inventree system? When I export the stock item tracking imformation, the default time zone is GMT. If I want to change to other time zone, what can I do?

**Comment by SchrodingersGat** [comment]
Change the "timezone" option in `config.yaml` file 

https://inventree.readthedocs.io/en/latest/start/config/

**Comment by Rubisco16** [comment]
Thank you!!!
