### ISSUE TITLE
Not importing in_stock from csv or xlsx

### ISSUE THREAD

**Issue by nelsonov** [inventree/InvenTree#2815]
**Describe the bug**
Not importing in_stock from csv or xlsx

**Steps to Reproduce**

Two scenarios:
A:
1) Export an example of the parts to be imported
2) Modify/Add to the spreadsheet to contain new parts
3) Make sure in_stock column is populated
4) import into IvenTree

B:
1) Export parts whose in_stock field is to be updated
2) Modify the spreadsheet to update in_stock column
3) Import into InvenTree

I am using Libre Office.  In both scenarios I have tried saving as both csv and xlsx.  I have tried tricks like formatting the column to be numeric and even numeric with decimals.

**Expected behavior**
Expect stock to be what was in the in_stock column in the spreadsheet

**Screenshots**
![Screenshot 2022-04-08 203345](https://user-images.githubusercontent.com/1811554/162554933-de8486f6-9561-4314-8f3a-2b109e67180a.jpg)
![Screenshot 2022-04-08 203505](https://user-images.githubusercontent.com/1811554/162554941-42a358b1-a457-488e-8b24-adac3421f457.jpg)
![Screenshot 2022-04-08 203541](https://user-images.githubusercontent.com/1811554/162554943-ea5014f2-e37d-4d15-bb49-0936bcf2a348.jpg)

**Deployment Method**
- [ ] Docker
- [ X] Bare Metal

**Version Information**
commit d1d7db76cc1109f46cc8404470f93a96ad0ca51f

**Comment by SchrodingersGat** [comment]
@nelsonov this is expected behaviour, as the "in_stock" column is a *calculated* read-only value.

After importing parts, stock items must be imported as a separate step.

**Comment by nelsonov** [comment]
Ah, that makes sense.  I was getting ahead of myself.
