### ISSUE TITLE
[BUG] BOM import fields limited to 500 characters

### ISSUE THREAD

**Issue by 4jag** [inventree/InvenTree#2819]
**Describe the bug**
Importing an XLSX file with greater than 500 characters in a fields produces an error -- I have some large boards that have Reference field with MANY locations.

**Steps to Reproduce**
1. Create a BOM data file with a >500 characters in any field (I ran into this on "Reference" column)
2. Go to `part/<id>/bom-upload`
3. Click on 'Upload BOM File'
4. Browse to file, Open
5. Submit, match fields
6. Submit
8. See error "Ensure this field has no more than 500 characters."

**Screenshots**
![image](https://user-images.githubusercontent.com/84933394/163060254-3a044e51-504a-45a6-ba1e-3156985226e1.png)

**Deployment Method**
- [X ] Docker
- [ ] Bare Metal

**Version Information**
0.6.3

**Comment by matmair** [comment]
Not a bug, this is a known (and as seen in the screenshot validated) limitation to keep imports reasonably fast.
We are always open for PRs that enable longer imports while keeping response times under 30secs per API call.

**Comment by SchrodingersGat** [comment]
Agreed, this field is simply limited to 500 characters

**Comment by SchrodingersGat** [comment]
@4jag this is a separate issue to the "500 character limit" issue.

If you are importing a BOM file with 1500 parts, that is a *lot* of data for the backend to process and serve back to the client via the API.

Can you please share some information on the error you are seeing now? Is the system reporting a timeout to the server?

**Comment by 4jag** [comment]
I was just responding to @matmair 's comment that it's a _"known limitation to keep imports reasonably fast. ... while keeping response times under 30secs per API call."_ I find when the import takes longer than 30 seconds, I get a "Bad gateway" error from NGINX, and I wasn't sure if that's an artificial timeout or something that could be lengthened to accommodate larger data imports. 

So it sounded to me like maybe you want to limit the import data size in order to avoid the timeout from NGINX. If that's the case, and if it's possible to increase the timeout above 30 seconds, then ...  On the other hand, allowing larger field sizes but having to break up imports into several files would be preferred over limiting the fields sizes, because limiting the field size can forces bad data (such as in my case).

**Comment by matmair** [comment]
@4jag the 30 seconds comes from nginx which used the default of apache2. Setting any higher value will lead to security warnings with a lot of enterprise cmdbs or outright alerts by monitoring tools.

This is why django and most libraries come with settings to be well under this limit. That is where the 500 characters come from - it is a battle-tested default.
I strongly suggest to not make users change their webserver settings and instead fix the performance issue at hand - If possible.

**Comment by fjullien** [comment]
Hi, I have this exact same issue.
I generated a BOM where I split long list of references:

![image](https://user-images.githubusercontent.com/1468818/217495387-8c109d1e-e10b-41f2-92cd-c52cbd58911a.png)

However, when I have two lines with the same IPN, the second line is ignored and is not imported:

![image](https://user-images.githubusercontent.com/1468818/217495696-64bba297-2494-4171-ba8a-1ee2b54cf293.png)

What would be the workaround ? Generate multiple csv files and import them one by one ?

**Comment by SchrodingersGat** [comment]
> Hi, I have this exact same issue.

@fjullien can you clarify the issue you are having? This discussion has covered a few different topics already

**Comment by fjullien** [comment]
As you can see on the screenshots, I have 123 capacitor PRT00020.
Because the reference "C53, C56..., C258" is too long, I split this in two lines in my csv file.

When I import this csv file, I can see only 80 PRT00020 (the ones from the first line).
It should be 123 because there is 80 + 43 PRT00020.

I may have miss something above....

**Comment by matmair** [comment]
The reference field is limited to 500 characters. Splitting the row in the CSV into 2 rows will not change that. Also there is currently no way for InvenTree to detect that you did the split so you will lose everything in the second line/it will not be imported.

> Agreed, this field is simply limited to 500 characters

**Comment by fjullien** [comment]
@4jag have you found a workaround for this limitation ?
I think I'll have to move to another solution to generate my BOM.
