### ISSUE TITLE
[FR] Identification Plugin System

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2845]
Add a new plugin system for "identifiying" or "locating" components. Could be used from the web or the app.

This has been implemented (custom) with great effect already, it would be fantastic to add proper support for this via the plugin ecosystem.

### References

- https://github.com/inventree/InvenTree/discussions/2678
- https://www.reddit.com/r/raspberry_pi/comments/t0c99r/raspberry_pi_cm4_smart_inventory_management/

**Comment by matmair** [comment]
@schrodingersgat how do you plan to do this? I would suggest adding a model that holds an identifier (token, address etc) and can be assigned to (multiple) stock location(s).
If you identify a stock item via ui or api a simple lookup is performed and all required identifiers are handed over to a plugin function. The plugin then needs to handle the rest.
I would love to write a small demo with an Adafruit MagTag and neopixels once you get the code done.

**Comment by SchrodingersGat** [comment]
The plan is to rely on the plugin as much as possible - much like the way the "label printing" plugin works. Simply pass the StockLocation object to the plugin, and leave it at that. The plugin could call an external network API or something?

**Comment by matmair** [comment]
@SchrodingersGat I would do the association / datahandeling in InvenTree to make that portable (change the illumination plugin for example / use multiple plugins at the same time (one system for the workflow and another for R&D. The association between location and identifier could be handled in the admin.
