### ISSUE TITLE
Update to Django 4.x

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2853]
As raised in #2849 update to Docker 4.x -> might be a lot of work.
This will break a lot of forks.

**Comment by SchrodingersGat** [comment]
Yeah, let's leave that one for now! :D

**Comment by matmair** [comment]
I checked what will be blocking here and it turns out it is the dependencies - not our own own codebase,

**Comment by SchrodingersGat** [comment]
It's always the dependencies! Which ones are blocking us right now?

**Comment by matmair** [comment]
@SchrodingersGat Multiple - I stopped checking after the 3rd. We will have to wait for upstream to get ready for 4.0 . This is currently slated for 1.0 so I would not worry about it - the comment was more for myself to know why I waited.

**Comment by matmair** [comment]
django 3.2 is going EOL fast - this needs to be fast tracked
