### ISSUE TITLE
Error when updating from version 0.5.4

### ISSUE THREAD

**Issue by cmos2020-bit** [inventree/InvenTree#2857]
Hi guys,

I get the following error when updating:

Running InvenTree database migrations...
========================================
2022-04-20 23:29:52,716 ERROR Missing required database configuration value ENGINE
Error: Missing required database configuration value ENGINE

Don't know what to do next.

Please help.

cmos

**Comment by SchrodingersGat** [comment]
We'll need some more information on your setup, but essentially you have not provided the required context information to inventree. 

- Are you running bare metal or docker?
- What database backend (ENGINE) have you been using?

**Comment by cmos2020-bit** [comment]
Hi Oliver,

Thanks for your reply


   - Are you running bare metal or docker?

I'm using docker.

   - What database backend (ENGINE) have you been using?

And the container inventree-db is based on PostgreSQL database as shown in
https://inventree.readthedocs.io/en/latest/start/docker_prod/ .
I followed the instructions found in that URL for installing it on my
server.

Thanks again for your help

cmos

**Comment by SchrodingersGat** [comment]
Are you using the `.env` and `docker-compose.yml` files exactly as provided, or are you editing them at all?

The `.env` file sets the `INVENTREE_DB_ENGINE` parameter:

https://github.com/inventree/InvenTree/blob/d647153cc21e55ab3498ad01cc0e79d2fab576e4/docker/production/.env#L21

Can you please run through the exact sequence of steps you are following, and where in that sequence you see the error.

**Comment by cmos2020-bit** [comment]
Hi,

Unfortunately I did something wrong and damaged my installation. Due to this I did a clean install, but before I made a backup of the database and of the complete inventree-data directory.
Can you please tell me how to restore the database and the contents of the previous inventree-data directory?

Thank you very much

cmos

**Comment by SchrodingersGat** [comment]
If you are running docker/postgres and you have a backup of the `inventree-data` directory, that directory should look something like this:

![image](https://user-images.githubusercontent.com/10080325/164579138-6db38fcf-84b2-4251-af61-ea81836070a3.png)

The process here is:

1. ensure the docker containers are not running - `docker-compose down`
2. Replace the *entirety* of the `inventree-data` directory with your backup
3. Bring the containers back online - `docker-compose up -d`
4. Update the containers - `docker-compose run inventree-server invoke update`

**Comment by cmos2020-bit** [comment]
Thanks Oliver,

Can I do this procedure with the latest version? Or do I need to install
the same version as before? In my case 0.5.4.

Thank you

Cmos

**Comment by cmos2020-bit** [comment]
I forgot to ask you, how can I restore the database from the backup I made
earlier into the new clean install?

Thank you

Cmos

**Comment by SchrodingersGat** [comment]
> I forgot to ask you, how can I restore the database from the backup I made earlier into the new clean install?

what sort of backup did you make? the raw database files? A JSON data dump?

**Comment by SchrodingersGat** [comment]
> Can I do this procedure with the latest version?

Yes, you can use the latest version and follow the process I outlined above.

**Comment by cmos2020-bit** [comment]
> > I forgot to ask you, how can I restore the database from the backup I made earlier into the new clean install?
> 
> what sort of backup did you make? the raw database files? A JSON data dump?

Hi Oliver,

I made a backup using the following command:

docker exec -t inventree-db pg_dumpall -c -U postgres > dump.sql

I tried to restore it without success using the idea from
https://stackoverflow.com/questions/24718706/backup-restore-a-dockerized-postgresql-database

your help will be greatly appreciated

thanks

**Comment by matmair** [comment]
@cmos2020-bit have you tried with something like this:

```

cat dump.sql | docker exec -i inventree-dB psql -U pguser -d inventree

```

**Comment by matmair** [comment]
@cmos2020-bit have you checked your backup is containing data? We used to have the default user pguser, not postgres

**Comment by cmos2020-bit** [comment]
> 

Hi, yes I tried it and it worked, thank you @matmair and @SchrodingersGat

**Comment by cmos2020-bit** [comment]
To summarize the complete process of back up and restore, I did the following: (based on the help provided by @SchrodingersGat and @matmair )

For the backup:
1. Backup the `inventree-data` directory - `cp inventree-data inventree-data_backup -r`
2. Backup the database - `docker exec -t inventree-db pg_dumpall -c -U postgres > database_backup.sql` 

Fo the restore:

1. Ensure the docker containers are not running - `docker-compose down`
2. Delete the `inventree-data` directory  -  `rm inventree-data -r`
3. Duplicate the `inventree-data_backup` directory and name it `inventree-data` -  `cp inventree-data_backup inventree-data -r`
4. Bring the containers back online - `docker-compose up -d`
5. Update the containers - `docker-compose run inventree-server invoke update`
6. Restore the database from the backup with -  `database_backup.sql | docker exec -i inventree-db ps
ql -U pguser inventree`
7. Update the containers - `docker-compose run inventree-server invoke update` (not sure if really needed)

Thank you very much.

cmos

**Comment by matmair** [comment]
Happy you got it resolved @cmos2020-bit 

Two small things about your steps:
- We recommend to use the included records-commands (see [here](https://inventree.readthedocs.io/en/latest/start/migrate/#import-data))
- I would switch step 5 with 6 and remove 7

Could you close this issue if you feel that your problems were addressed fully?

**Comment by cmos2020-bit** [comment]
Thanks @matmair 

Let's consider this closed. I added your suggestions to the list.
You are right, the best way is to use the included records-commands (at the moment of doing the backup they were unknown for me, that's why I did it using other process (complex and error prone).

For the backup:
1. Backup the `inventree-data` directory - `cp inventree-data inventree-data_backup -r`
2. Backup the database - `docker exec -t inventree-db pg_dumpall -c -U pguser > database_backup.sql` 

For the restore:

1. Ensure the docker containers are not running - `docker-compose down`
2. Delete the `inventree-data` directory  -  `rm inventree-data -r`
3. Duplicate the `inventree-data_backup` directory and name it `inventree-data` -  `cp inventree-data_backup inventree-data -r`
4. Bring the containers back online - `docker-compose up -d`
5. Restore the database from the backup with -  `database_backup.sql | docker exec -i inventree-db psql -U pguser inventree`
6. Update the containers - `docker-compose run inventree-server invoke update`

Thank you very much.

cmos


Best regards,

**Comment by eeintech** [comment]
@matmair @SchrodingersGat Should be added to docs?

**Comment by matmair** [comment]
@eeintech I was under the impression it was

**Comment by eeintech** [comment]
Right, some instructions here: https://inventree.readthedocs.io/en/latest/start/docker_prod/#updating-inventree

I am confused on why we have steps 4-6 reversed with @cmos2020-bit :
![image](https://user-images.githubusercontent.com/4020546/165380015-acc52504-3979-4768-bb5a-96977c7b9286.png)
