### ISSUE TITLE
[FR] Registration / Onboarding screen

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2866]
**Is your feature request the result of a bug?**
No

**Problem**
We currently do not provide a UI for self-registration (or setting additional user details after auth via a third party).

**Suggested solution**
Create a registration flow for:
- all user details
- email address(es)
- possibly social auth sources

Add the option to require admin confirmation.

**Describe alternatives you've considered**
The current way works - not for bigger enterprise/education users though

**Examples of other systems**
Gitlab registration

**Do you want to develop this?**
Yes. I will wait till core-dev / maintainer consensus on position on the roadmap is clear

**Comment by matmair** [comment]
Related to #2865 #1693
@SchrodingersGat @eeintech any inputs on viability/roadmap timing? This is more a quality of live FR for user-heavy instances.

**Comment by SchrodingersGat** [comment]
I'd be happy for you to work on this @matmair , if you are confident it fits well within the existing framework. I'd say we target for 0.8 release.

**Comment by matmair** [comment]
@SchrodingersGat thanks.
I was surprised when I realised we have no self-registration as I implemented #2865

**Comment by eeintech** [comment]
> Add the option to require admin confirmation.

This is a must for our organization, thanks!

**Comment by matmair** [comment]
So ... it turns out I already implemented this feature when I did SSO. @eeintech could you check if it fits your needs? If you have 0.6.0 running it is in the login-section
![grafik](https://user-images.githubusercontent.com/66015116/167026865-32ad1985-b685-4d47-9c3a-8481cf9a0363.png)

**Comment by eeintech** [comment]
@matmair That's right but without action from admin, the user is not associated to any group and UI is empty. Was there an option for a default group upon user creation?

![image](https://user-images.githubusercontent.com/4020546/167167213-bd209405-ac54-4211-bddb-f109c95ec38b.png)

**Comment by matmair** [comment]
@eeintech Yes. It is named default group and in the login-section.

**Comment by eeintech** [comment]
Very cool, I didn't know this existed already, great work!

**Comment by matmair** [comment]
Sometimes I forget what I programmed myself
