### ISSUE TITLE
[BUG] Inconsistent use of variant_of / ancestor in the API

### ISSUE THREAD

**Issue by bcc** [inventree/InvenTree#2868]
**Describe the bug**
I have a small application that generates a 'low stock' summary using the Inventree API - it understands the breakdown of sites and the amount of stock that should be present on each site for each part. It also understands that variant parts should be summed together for this. For example, I need a certain (variable) number of 4TB hard disks at each site, I don't particularly care which manufacturer they are. Variant parts solve this perfectly for me. I recently upgraded Inventree and this tool stopped working properly. After some digging it turned out that Part.list(variant_of=part) has changed to Part.list(ancestor=part)

Under /api-doc/#part-list variant_of is still listed although it no longer works and it's still used elsewhere in the documentation. variant_of no longer shows up in the interactive API form for /part/list but neither does ancestor.

**Steps to Reproduce**
* https://inventree.example.com/api/part/?variant_of=3 now lists all parts rather than just the variants of this part. 
* https://inventree.example.com/api/part/?ancestor=3 gives the previous result that variant_of used to.

**Expected behavior**
A note that variant_of is deprecated would have been handy. I was thinking I'd submit a simple documentation PR, but I'm not actually sure what the desired behaviour is intended to be.

**Deployment Method**
* Bare Metal

**Version Information**
I noticed the issue with 0.6.3, but I just upgraded to  to verify it's not already fixed, currently running: 0.7.0 dev - Commit Hash: dbcdbe399

**Comment by matmair** [comment]
@SchrodingersGat any idea if this os intended?

**Comment by SchrodingersGat** [comment]
@bcc thanks for raising this. The `ancestor` and `variant_of` filters are for subtly different purposes, and *both* should be working.

However it would appear that you are correct, the `variant_of` filter does not work!
