### ISSUE TITLE
Printing multiple part++part labels

### ISSUE THREAD

**Issue by cmos2020-bit** [inventree/InvenTree#2872]
Hi,

Is it possible to print multiple part labes for selectd parts?
I know it is possible with stock labels, but I can't do it with part labels.

Thanks

cmos

**Comment by SchrodingersGat** [comment]
Currently this is not possible via the web interface, but would be pretty simple to add, following the methodology of the 'stock items' printing

**Comment by cmos2020-bit** [comment]
Thanks Oliver!

**Comment by SchrodingersGat** [comment]
@cmos2020-bit would you be willing to tackle this one? Our developer time is severely stretched right now!

**Comment by cmos2020-bit** [comment]
Hi Oliver,

At the moment I'm very busy, however in a couple of weeks I think I would be available. However I have no experience with Django and I know very little about Docker, so I will have to learn these things first. Maybe you can point me in the right direction where to look for info on getting started. Once I know a little more, I'll happy to help.

Thanks for your offer.

BR,

cmos

**Comment by SchrodingersGat** [comment]
Awesome, I'd be happy to help point you in the right direction. LMK when you have some time available!

**Comment by matmair** [comment]
@cmos2020-bit please let us know if we can assist you with gearing up in any way.

**Comment by matmair** [comment]
@SchrodingersGat bump this to `0.7.x` ?

**Comment by cmos2020-bit** [comment]
Hi guys,

Sorry for not replying earlier, but right now I have been extremely busy.
To be honest I don't see it possible for me to work before July on this
project. Please tell me if this is ok.

Thanks

Patricio

**Comment by SchrodingersGat** [comment]
No worries, this is not a pressing issue so we will bump it to the next release cycle

**Comment by SchrodingersGat** [comment]
@cmos2020-bit have you have any chance to look into this?

**Comment by Rincewind34** [comment]
@SchrodingersGat this looks like a very low hanging fruit, I'm currently looking into this project and would be very happy to contribute here and there.

**Comment by matmair** [comment]
@Rincewind34 do you want this to be assigned to you? Feel free to ping us if you have questions or to create a  draft PR if you want early feedback.

**Comment by Rincewind34** [comment]
@matmair Great, I think I can spare a few ours late next week.

**Comment by matmair** [comment]
Nice @Rincewind34 - no time pressure on this from our side; the milestone is just a rough suggestion and has no meaning.

**Comment by SchrodingersGat** [comment]
@Rincewind34 is it next week yet? ;)

**Comment by Rincewind34** [comment]
@SchrodingersGat yeah, so sorry about it. I want to make sure I got the software figured out before I start touching anything. And right now I have a massiv problem with the bar codes, that I tried to solve for the past few days.

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by simonkuehling** [comment]
May I ask, which feature exactly is described here? As far as I can tell, the printing of multiple part labels (from the parts list) is currently implemented:

![Bildschirmfoto vom 2023-02-28 21-24-53](https://user-images.githubusercontent.com/296454/221970162-43ba1fad-effe-408d-921b-dec5ebafeba3.png)

...let me know if I misunderstood the topic - would be happy to take care of it if needed...

**Comment by SchrodingersGat** [comment]
@simonkuehling it is a subtle distinction

Currently when printing labels to an external plugin, the label files are sent one by one as separate requests .

However some users want to be able to send multiple labels in a single request, for example to print them on one of those large sheets of paper which has peelable labels on a grid. 

The change here would be to extend the plugin functions to accept multiple labels in a single call. I started to look into this but the complexities come with caching the label data for the background worker to send to the printer plugin.

**Comment by SchrodingersGat** [comment]
@simonkuehling oh my bad, I had the wrong context for this issue. My response makes sense for #4167 but not this one.. Oops!

**Comment by SchrodingersGat** [comment]
So, it does look like this has been implemented and works as expected.
