### ISSUE TITLE
Serialisation prevents use of hypen in serial numbers

### ISSUE THREAD

**Issue by exp** [inventree/InvenTree#2885]
**Describe the bug**
The database schema supports (and should continue to support (IMO)) hyphens in serial numbers, as these are common. When serialising a number of items, any hyphen is interpreted as a range operation even in cases where it is nonsensical.

**Expected behavior**
Some variation of the following logic should be added to group definitions:
  * If the count of serial entries == the number of items to be serialised, skip group interpolation
  * If there is more than one hyphen per word, skip group interpolation for this word

**Version Information**
master

I am happy to write this patch but want to discuss that it is acceptable first.

**Comment by matmair** [comment]
Not a bug - was an intentional design decision to enable after input

**Comment by matmair** [comment]
@SchrodingersGat @eeintech what are your opinions here? I see no reason to not change it if the fast input gets preserved.
Some clear way to communicate the change in the UI should be added though.
Would be happy to see @exp work on this if above questions are resolved.

**Comment by exp** [comment]
Proposed UI communication:

Enter serial numbers for new items ­— You may use groups (`1-10`) or sequences (`5+`) if you enter fewer serial numbers than items.

Do you want to keep this strictly to very few words? Mentioning space or comma separation I think would also be valuable.

**Comment by matmair** [comment]
@exp I do not really care about the length of the documentation/info as long as the syntax for input is not becoming complex 

Small wrong example (which I have seen in another system):
``
1{{-}}5

{1-{{15}}}-{1-{{20}}}
``

**Comment by SchrodingersGat** [comment]
Using a reserved token character in the serials will vastly increase complexity and associated considerations here.

@exp if you can show a "one size fits all" solution which accommodates hyphens in the serial numbers, we can consider it, but not if it has complex edge cases that need to be communicated to users (across multiple languages!)

e.g. what does the following string evaluate to?

5 unique serial numbers to be extracted from `1-5, 2, 3-5` 

This could be ambiguous!

**Comment by exp** [comment]
@SchrodingersGat I think prohibiting `-` from being included in serials would be a mistake, as there are millions of physical items with those serials lying around. Furthermore you can already edit the serial attribute to include this, so production Inventree databases and printed labels undoubtedly exist with them already.

The example you give already fails due to the expansion of those groups so I can't really tell you how it should behave, but there exists one case I can think of that would currently cause an error but after patching, would be accepted erroneously:

`Count: 5; Serials: '1 2 3 4 5-10'`

In my proposal the 5th item would be given the serial `5-10` instead of the expansion flagging an error for too many serials. I think that's what you're alluding to, but I think that's quite a minor worry. There are no proposed syntax changes and the code complexity is extremely simple (`len(groups) == expected_quantity` and the removal of one error case).

If the above is more of a worry than I think, would you accept a javascript driven warning as an alternative? I really don't want to have to mangle (literally hundreds of) serial numbers across my stock. Thanks for your time!

**Comment by SchrodingersGat** [comment]
@exp I would tend to agree, if you submit a PR with the proposed set of changes we'll certainly take a look!

**Comment by exp** [comment]
Understood, this isn't strictly related to this bug, but I assume you envisage a serial field of `1 2 ~ ~ ~` to imply ` 1 2 3 4 5` and not `1 2 3 3 3`? I figured that might as well be fixed too.

**Comment by SchrodingersGat** [comment]
I don't think we had ever considered the case of multiple sequential ~ characters, tbh

**Comment by exp** [comment]
This has been merged, not sure why the PR wasn't linked to this automatically.
