### ISSUE TITLE
[BUG] Multi level BOMs strain server resources

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2889]
A large multi-level BOM requires *many* API requests and page load times can stretch into the tens of seconds.

The issue is that the BOM table makes a secondary API request for each item in the BOM, and then if that item has child items, a request for each of those items, and any of *those* items etc etc

This quickly snowballs out of control if BOMs are more than two levels deep.

### Possible Solutions

1. These extra requests should only be made as the BOM rows are expanded by the user
2. Display only top-level BOMs and do not facilitate a "multi level" BOM table

**Comment by matmair** [comment]
@SchrodingersGat I would prefer solution 1 and to maybe add a button to load the whole BOM (with one request)
