### ISSUE TITLE
[FR] Enable Downloading BOM Pricing

### ISSUE THREAD

**Issue by cjdet** [inventree/InvenTree#2891]
**Describe the bug**
For an assembled part the Pricing page shows a BOM Cost. The table on the page is populated, however, it is not possible to download the table despite the download icon being shown. For instance in this figure:

**Steps to Reproduce**
1. Create a part with a BOM.
2. Go to the Pricing page of that part.
3. BOM Cost section of the page displays costs
4. Clicking on the download image does not download 

**Expected behavior**
Should be able to download the BOM Cost table similar to how all the other tables can be downloaded with the save icon.

**Screenshots**

![926FE924-A2DC-4D7F-9E05-652463DD3495](https://user-images.githubusercontent.com/10247014/165667179-ac3bc6ca-c679-466a-8be6-77d8c2300802.jpeg)

**Deployment Method**
- [X] Docker
- [ ] Bare Metal

**Version Information**

InvenTree-Version: 0.6.3
Django Version: 3.2.12
Commit Hash: 86b0b50
Commit Date: 2022-03-30
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

Same behavior was present in 0.6.1, not sure about other versions.

**Comment by matmair** [comment]
@cjdet thanks for the report The export function is not available for this table at this point in time. Therefore it is greyed out - to signal that the function is not available.

The core devs are currently working on issues and a lot of new features in other areas of the software - you are welcome to submit a PR if you want the feature fast.
The code base contains multiple examples how we typically would implement this, feel free to ask questions if you run into problems.

**Comment by cjdet** [comment]
Thanks @matmair. This would be a very useful feature. I appreciate all the great features you have added!

**Comment by matmair** [comment]
@cjdet could you please change the title to Something like `[FR] Make ...` so it is visible from the overview that this is a FR?
