### ISSUE TITLE
[FR] Batch number in part allocation row

### ISSUE THREAD

**Issue by lewispb** [inventree/InvenTree#2921]
**Problem**
When assigning stock items to a build order in the "Allocate Stock Items to Build Order" modal, there's no batch number displayed in the Stock Item select2 dropdown. This means "duplicate" stock items are displayed in the dropdown, with only the quantity varying.

**Suggested solution**
Add the batch number for each stock item to the select2 dropdown.

**Do you want to develop this?**
Sorry, I'm more of a Rails guy

**Comment by matmair** [comment]
Hi there @lewispb 
Thanks for the FR. While I see no technical problem with the request I can not guarantee a timeline for implementation as core devs are working on other parts of InvenTree right now. I have marked it for general contribution.

**Comment by SchrodingersGat** [comment]
@lewispb this has actually been implemented on latest master:

![image](https://user-images.githubusercontent.com/10080325/166343131-68fe4fef-a326-494e-a029-14b9471a8dd0.png)

What version are you using?

**Comment by lewispb** [comment]
Ah! My bad sorry. Forgot to run invoke static after upgrading!
