### ISSUE TITLE
[FR] Settings API - use KEY as URL identifier

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2925]
Ref: https://github.com/inventree/InvenTree/pull/2805

Currently, we use the PK (primary key) of the setting instance to determine the API access URL

e.g. `/api/settings/1/`

However, there are a number of issues here:

- No way of accessing a setting object without knowing the PK value
- Settings get 'instantiated' on request, so we can't even read out the "default" value *until* it has a pk

### Suggestion

We should change the setting access API to use the unique KEY of the setting as the lookup URL, e.g.

- `/api/setting/ENABLE_REPORT/`
- `/api/setting/user/SEARCH_RESULTS_COUNT/`

This has some other advantages:

- Makes writing front-end access code (e.g. js / templates) much easier
- We can "create" a setting on request, if it does not exist in the database
- We can return an error code if an invalid KEY is requested

**Comment by matmair** [comment]
@SchrodingersGat sounds like a good idea!
