### ISSUE TITLE
[FR] Add test data from build output screen

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2933]
![image](https://user-images.githubusercontent.com/10080325/166842727-301f2c32-6e31-4758-ba49-b2f41e70bb30.png)

It would be handy to be able to see the status of individual tests, maybe by hovering over the "Completed Tests" progress bar, and then also check off test results directly from the build output table.

Currently you have to navigate to the detail page for the stock item (build output) to mark off tests.

**Comment by matmair** [comment]
@schrodingergat this sounds like a perfect thing for React/Vue to do ;-)

**Comment by matmair** [comment]
@SchrodingersGat is this still valid on pui?
