### ISSUE TITLE
How to display pricing information

### ISSUE THREAD

**Issue by spectre-ns** [inventree/InvenTree#2938]
Sorry for my inability to make sense of this tool. But what is the image below trying to tell me? It says no pricing information is available but I cannot tell when it would ever be available where it currently isn't integrated with suppliers. Please help!

<img width="883" alt="image" src="https://user-images.githubusercontent.com/96780897/167196032-19dcfd21-c2a3-4027-9275-06e4b1cbc3a1.png">

**Comment by matmair** [comment]
Hi there @spectre-ns !
You need to enter pricing info in the supplier parts pricing tab or add prices to some stock or create an order and add prices to the lines to see pricing in the overall part pricing tab.

**Comment by matmair** [comment]
In general it is rather easy to integrate suppliers via plugins. Multiple vendors did actively discourage implementation of their APIs as they only provide APIs to select few.

**Comment by spectre-ns** [comment]
Where is the supplier pricing tab I don't se it under the supplier? 

![image](https://user-images.githubusercontent.com/96780897/167254888-b04ab027-afd4-47a8-8796-1c55d02ac335.png)

**Comment by SchrodingersGat** [comment]
@spectre-ns you'll want to look at the "SupplierPart" view, not the "Supplier":

![image](https://user-images.githubusercontent.com/10080325/167255241-add3f2c3-d0ed-4ed9-9b97-c8fd0c20f6e8.png)

**Comment by spectre-ns** [comment]
Thanks that is very helpful. How hard would it be to link this to digikey?

**Comment by matmair** [comment]
Depends on what information you want to have linked and how well you know python. My suggestion would be to familiarize yourself with InvenTree, evaluate what your needs are (and if you need to track pricing info in InvenTree) and then decide if you want to roll it out.
Simple price fetching is not too difficult - placing orders is only possible if you get that greenlit by DigiKey themself.
On another note: Could you please close the issue if you were answered to a satisfactory level?

**Comment by spectre-ns** [comment]
@matmair Thanks for all the answers. I'm very new to this and I'm really liking this platform for far and I'm hoping it can grow with our company. Sounds like we can add functionality if we really want it. Apologies for leaving the issue open.

**Comment by matmair** [comment]
@spectre-ns no worries. We are happy to help. If you roll InvenTree out we would be happy to receive bug reports, feature requests or doc updates (there can never be enough docs for endusers). But there are no obligations ofc.
Once you are ready to add something feel free to create a discussion or ping me - maybe there is already a solution. If you just want to read up on the topic: [plugins](https://inventree.readthedocs.io/en/latest/extend/how_to_plugin/)
