### ISSUE TITLE
[FR] Add purchasing price entry 

### ISSUE THREAD

**Issue by cjdet** [inventree/InvenTree#2939]
**Problem**
When using Order Part from the Purchase Order page on a part you cannot put in the purchasing price. 

This would reduce the number of steps involved. I do not use supplier part pricing because the pricing varies too much these days to spend the time entering all of them.

**Suggested solution**
Have an entry in step 1 in the order parts dialog to set the price if not price is set from the supplier.

**Describe alternatives you've considered**
Right now after adding it to a PO, I click the PO, find the part, edit the line item, and enter the purchase price. 

**Do you want to develop this?**
Not at the moment, but perhaps I'll have to dig into the internals soon.

**Version Info**
# Version Information:
InvenTree-Version: 0.6.3
Django Version: 3.2.12
Commit Hash: 86b0b50
Commit Date: 2022-03-30
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by matmair** [comment]
@cjdet seems reasonable. I have plugins that add the real-life prices after I receive orders - in larger companies that is the way to go but for smaller installs your suggestion makes sense.

**Comment by matmair** [comment]
I tagged this for the release after the next one but without an assignee we do not guarantee that it will be implemented.
