### ISSUE TITLE
Serialisation and stock item 'movement'

### ISSUE THREAD

**Issue by jnewlands** [inventree/InvenTree#294]
How to handle uniquely identifiable items? How to handle batched items? Are they special cases of stock items.

Generic stock items can be put into a serialised stock item, and the generic parts disappear. Batched items or other serialised items must not disappear - they should have a 'location' of the higher level item. How do batched items get split up for use in assemblies?

Can non-serialised parts come back out of an assembly, but then retain their link? This could be useful in the case of parts that are removed during a repair.

Is there ever a use case for a stock item (that is unique) not corresponding to a part? This could be used to deal with one off items that need to be tracked/have notes.

**Comment by eeintech** [comment]
@jnewlands Could you verify with the latest version of InvenTree if your requests have been implemented, and what's missing?

**Comment by SchrodingersGat** [comment]
@eeintech this one has definitely been addressed now - I have discussed this one with @jnewlands 

Thanks for bringing attention to these old PR's :)
