### ISSUE TITLE
[FR] Extend existing notifications 

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2950]
Currently the available notifications are limited to "low_stock" - i.e. the available stock quantity for a given part has fallen below a configured level.

Now that the notification system has been expanded, and includes the ability to write custom notification plugins, we should expand the different notifications that can actually be sent.

This issue is open for general discussion, to determine what "events" should be available as notifications. 

### Ideas

- [x] Purchase order is overdue - https://github.com/inventree/InvenTree/pull/3114
- [x] Sales order is overdue - https://github.com/inventree/InvenTree/pull/3114
- [x] Build order is overdue - https://github.com/inventree/InvenTree/pull/3114
- [x] ~~Stock items(s) have not been updated (e.g. stocktake) in a certain amount of time?~~
- [x] Items have been received against a purchase order (notify assigned user) - https://github.com/inventree/InvenTree/pull/3259
- [x] Build order has been completed (notify user who issued the order, if not the same person as the responsible user) - https://github.com/inventree/InvenTree/pull/3255
- [x] Build order has been completed (notify user responsible for "upstream" build order) - https://github.com/inventree/InvenTree/pull/3255
- [x] Build order has been completed (notify user responsible for "upstream" sales order) - https://github.com/inventree/InvenTree/pull/3255
- [x] New sales order has been created and assigned to you (if you were not the user who created it) - https://github.com/inventree/InvenTree/pull/3145
- [x] New purchase order has been created and assigned to you (if you were not the user who created it) - https://github.com/inventree/InvenTree/pull/3145
- [x] New build order has been created and assigned to you (if you were not the user who created it) - https://github.com/inventree/InvenTree/pull/3145

**Comment by SchrodingersGat** [comment]
@eeintech @matmair any thoughts on this one?

**Comment by matmair** [comment]
@SchrodingersGat I do not really need additional notifications (I think but who knows till they are there).

**Comment by eeintech** [comment]
When a BO or PO passed the target date maybe? Opening it to plugins is a great idea

**Comment by SchrodingersGat** [comment]
Yeah I had some similar ideas @eeintech 

Plugins can already trigger notifications, adding some more "core" notifications would be a good idea

**Comment by rkalman** [comment]
It would be great to get a notification if ordered items are arrived - sent to the responsible of the PO. (Sometimes somebody else receives the items, so you need to poll the open POs)
