### ISSUE TITLE
Creating barcode labels instead of qr code labels

### ISSUE THREAD

**Issue by isa-tt** [inventree/InvenTree#2958]
hi!
This is my first time issuing something on github, i'm new to the platform so sorry in advance if i'm not following the guidelines strictly. Currently i'm setting up inventree for the company i'm working at and to begin i'm playing with the label creation feature and having some issues with it. By reading the documentation i have been able to create and customize qr labels but i'm clueless as to how exactly create labels that display barcodes instead. i've been trying for a couple of days with no results so i though i could ask over here.
The main issue i'm trying to get a grip on is if there's an analog for qr-data but for barcode data so i can create the barcode image, also im wondering if a barcode label is only available from stockitem labels and not parts since in this category is where the barcode identifier field is availbale. 
I've tried different variants of the html code shown in the docs

`<img class='custom_class' src='{% barcode "12345678" %}'>`

where custom_class is the item i defined in the css part of the code. My first try was 
```
{% load barcode %}   
<style>
    @page {
        width: 80mm;
        height: 60mm;
        padding: 1mm;
    margin: 0.5px 0.5px 0.5px 0.5px;
    }

    .part {
        font-family: Arial;
        float: right;
        vertical-align: middle;
        position: absolute;
        font-size: 1px;
        overflow: visible;
    }
    .bar {
        margin: 1px;
        width: 35mm;
        height: 35mm;        
    }
</style>

<img class='barcode' src='{% barcode "12345678" %}'>

<div class='part'>
{{ part.full_name }}<br>
{{ part.category }}<br>
{{ part.default_location }}
</div>

```
And this leads me to **Internal Server Error** when generating the label but works pretty fine if i change the barcode settings to qr code. I've also tried different bits of the same thing (sort of, i got desperate)

`<img class='barcode' src='{% barcode part.format_barcode %}'>`
`<img class='barcode' src='{% barcode ipn.format_barcode %}'>`
`<img class='barcode' src='{% barcode barcode_identifier %}'>`
`<img class='barcode' src='{% barcode barcode_identifier.format_barcode %}'>`
`<img class='barcode' src='{% barcode barcode_data %}'>`

Apparently these are silly different iterations of the above, the result is always **Internal Server Error**. Guess i should mention the intention of creating barcode labels is to use inventree with a handheld barcode scanner. Hope the details i provide are enough to get some help! Thanks in advance!

**Comment by matmair** [comment]
Hi there @isa-tt 
The code you posted seems to be ok. The docs on 1 and 2-d codes themself can be found here: https://inventree.readthedocs.io/en/latest/report/barcodes/

In general when creating issues you are encouraged to use the [templates](https://github.com/inventree/InvenTree/issues/new/choose) that are provided as we tend to need the same set of infos for these things all the time. Blank issues tend to touch on multiple problems at once or a bug and a feature request - which makes it easy to overlook something.

**Comment by SchrodingersGat** [comment]
@isa-tt thanks for posting :)

In addition to the comments by @matmair above you can check out the templates for the default labels that are shipped with InvenTree: https://github.com/inventree/InvenTree/blob/master/InvenTree/label/templates/label/stocklocation/qr_and_text.html

**Comment by SchrodingersGat** [comment]
@isa-tt if this sufficiently answers your question, please close this issue :)

**Comment by isa-tt** [comment]
Thanks @matmair for the info on the guidelines, i went for a blank issue because i wasn't sure this could be a bug and clearly wasn't a request. I've checked the documentation on the barcodes but so far haven't been able to get my code to work.
 And @SchrodingersGat I did also look for the templates in the InvenTree folder, and that's what I used to customize qr labels to start (all templates are qr from what i've seen) but I still have no luck with the barcode ones, even though the only difference with the working code from the templates and the one i'm trying, is that there's no qr_data.  So maybe more specifically, which is the attribute/function/variable that contains the barcode info, is there a barcode_data? or barcode_identifier like the field that is customizable directly on the platform for a certain part? I'm still at loss and with the labels not woking properly

**Comment by isa-tt** [comment]
Thanks @matmair for the info on the guidelines, i went for a blank issue because i wasn't sure this could be a bug and clearly wasn't a request. I've checked the documentation on the barcodes but so far haven't been able to get my code to work.
 And @SchrodingersGat I did also look for the templates in the InvenTree folder, and that's what I used to customize qr labels to start (all templates are qr from what i've seen) but I still have no luck with the barcode ones, even though the only difference with the working code from the templates and the one i'm trying, is that there's no qr_data.  So maybe more specifically, which is the attribute/function/variable that contains the barcode info, is there a barcode_data? or barcode_identifier like the field that is customizable directly on the platform for a certain part? I'm still at loss and with the labels not woking properly

**Comment by isa-tt** [comment]
This is the code i'm currently using for part qr labels

```{% extends "label/label_base.html" %}

{% load barcode %}

{% block style %}


.qr {
    position: fixed;
    left: 1mm;
    top: 3mm;
    height: 20mm;
    width:  20mm;
}

.partt {
    font-family: Arial, Helvetica, sans-serif;
    font-size:10px;
    display: inline;
    position: absolute;
    left: 22mm;
    top: 2mm;
}

.locat {
    font-family: Arial, Helvetica, sans-serif;
    font-size:10px;
    display: inline;
    position: absolute;
    left: 2mm;
    top: 25mm;
}

{% endblock %}

{% block content %}

<img class='qr' src='{% qrcode qr_data %}'>

<div class='partt'>
{{ part.full_name }}
<hr>
{{ part.category }}
<hr>
</div>

<div class='locat'>
 {{ part.default_location.parent.name }},  {{ part.default_location.name }}
</div>

{% endblock %} 
```
and it creates the following label 

<img width="287" alt="image" src="https://user-images.githubusercontent.com/102771420/167681241-617429cf-b5d1-42e6-8470-3a7a8cbbcdf0.png">

Following the docs indications/examples and following the logic there, if i change the code generating part (and update the class definition to match) to this 
`<img class='barcode' src='{% barcode barcode_data %}'>`
or this
`<img class='barcode' src='{% barcode "12345678" %}'>`

I get **Internal Server Error** anyways, still can't get it to function properly and display a barcode. Tried to figure out what could be the error by looking at the plugin's code but still no luck. Hope i can get a hand with this!

**Comment by matmair** [comment]
@isa-tt this seems to be an error in your template. I just tried it and it works fine on my site with different types of barcodes. My best guess Ishtar you are using the class ‚barcode‘ and the value ‚barcode_data’ without defining it first. Could you try using
`<img class='qr' src='{% barcode qr_data %}'> `
?

**Comment by matmair** [comment]
Also please provide error logs when posting a bug report. Details on where those can be found are [in the docs](https://inventree.readthedocs.io/en/latest/settings/logs/).

**Comment by isa-tt** [comment]
@matmair i just tried the example you just gave, and i still get the internal server error.  This is the last thing on my error log just after trying out `<img class='qr' src='{% barcode qr_data %}'>`
```
Error object (71)
[HISTORY](http://localhost:1337/admin/error_report/error/71/history/)

Type:
AttributeError
Path:
http://localhost:1337/api/label/part/7/print/?parts[]=4&
Info:
module 'barcode' has no attribute 'get_barcode_class'
When:
May 10, 2022, 7:24 p.m.
Data:
Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/inventree/InvenTree/label/api.py", line 487, in get
return self.print(request, parts)

File "/home/inventree/InvenTree/label/api.py", line 110, in print
pdf = outputs[0].get_document().write_pdf()

File "/home/inventree/.local/lib/python3.8/site-packages/django_weasyprint/views.py", line 80, in get_document
string=super().rendered_content,

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
return template.render(context, self._request)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
return self._render(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/home/inventree/InvenTree/report/templatetags/barcode.py", line 70, in barcode
constructor = python_barcode.get_barcode_class(barcode_class)

AttributeError: module 'barcode' has no attribute 'get_barcode_class' 
```

**Comment by matmair** [comment]
@isa-tt thank you for the stack trace - what version are you running (hash)?

**Comment by matmair** [comment]
@isa-tt the update released earlier today: reading through the changelog it might solve your problem.
Please update and make sure to run 'Inv update' so all parts get updated after pulling the new source.

**Comment by matmair** [comment]
If it is not working please run the following in your environment:
`pip show python-barcode`
So I know we are talking about the same library version

**Comment by matmair** [comment]
@isa-tt can confirm this is a bug. Although a bit of a tricky one to verify and fix. I have test that fail now - fix incoming today or tomorrow in #2966

**Comment by matmair** [comment]
@SchrodingersGat the problem only arises with activated plugins as there are namespace and import conflicts in the global context.

**Comment by SchrodingersGat** [comment]
Ah yeah that's a gotcha. Good find @matmair

**Comment by isa-tt** [comment]
@matmair great! i'll be waiting the update then, thanks so much for the help so far!

**Comment by isa-tt** [comment]
The template label shows a piece of text {"part":4} like the image shows

<img width="401" alt="image" src="https://user-images.githubusercontent.com/102771420/167864103-bb6a9bd1-86c1-4ef7-bd2f-b72f1838684b.png">

And the same happens when another template is used, for example this 
```
<style>
    @page {
        width: 40mm;
        height: 30mm;
        padding: 1mm;
    margin: 0.5px 0.5px 0.5px 0.5px;
    }

    .part {
    font-family: Arial, Helvetica, sans-serif;
    font-size:50%;
    display: inline;
    position: absolute;
    left: 0mm;
    top: 15mm;
    }
    .locat {
    font-family: Arial, Helvetica, sans-serif;
    font-size:50%;
    display: inline;
    position: absolute;
    left: 0mm;
    top: 25mm;
    }
    .qr {
        margin: 1px;
        width: 40mm;
        height: 16mm;        
    }

</style>
{% load barcode %}   

<img class='qr' src="{% barcode qr_data %}"/>

<div class='part'>
    {{ part.full_name }}<br>
    {{ part.category }}
    </div>
    
    <div class='locat'>
     {{ part.default_location.parent.name }},  {{ part.default_location.name }}
    </div>
    
</div>
```
<img width="242" alt="image" src="https://user-images.githubusercontent.com/102771420/167864763-3d25e928-cdbe-4ab7-b915-00aed21005be.png">

**Comment by matmair** [comment]
@isa-tt the text is part of a rule compliant code 128 - it is the codes data human-readable
