### ISSUE TITLE
[FR] "External" locations

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2960]
This one requires some thought, and the concept is not fully fleshed out

It would be handy to be able to mark certain locations as "external", for example if stock is located at an external supplier, board assembler, etc

Being able to differentiate between "internal" and "external" stock might be useful.

**Comment by matmair** [comment]
@SchrodingersGat do you imagine this as an informal field or to influence business logic?
Also would you like to expose these external locations on a webinterface to external parties?

**Comment by SchrodingersGat** [comment]
I would imagine it influences the business logic, somehow.

**Comment by gooutbefree** [comment]
At least a boolean to mark external locations and available over API would help. 
We are thinking of using sell orders to move components in an external stock (virtual stock to track assembly company's stock) and have the benefit of all shipping documents etc.
In a first step we can use a plugin to do that
