### ISSUE TITLE
[FR] Shipment Creation in Stock Allocation Menu

### ISSUE THREAD

**Issue by maksimstojkovic** [inventree/InvenTree#2970]
**Is your feature request the result of a bug?**
No

**Problem**
I find that through SO fulfillment I often have to close the Line Item allocation menu to create a new Shipment in the Pending Shipments menu. This is somewhat inconvenient when entering SOs manually.

**Suggested solution**
Add the "New Shipment" button in the "Allocate Stock Items to Sales Order" modal to allow for the creation of a shipment within the allocation menu.

**Describe alternatives you've considered**
Provide the option to create a shipment automatically every time an SO is created, so the Pending Shipments menu only has to be visited. This option could be added to the Sales Orders menu in Settings. (This could be done together with the solution above to streamline the SO fulfillment process).

**Examples of other systems**
I only have experience with InvenTree with regard to this aspect of fulfillment.

**Do you want to develop this?**
No, as I don't have experience working with Django.

**Comment by SchrodingersGat** [comment]
@maksimstojkovic greetings from Tasmania! You're right, a button in this location would be super handy. I've pinned this to the next release, it should be a relatively simple fix, all front-end (javascript) code.

**Comment by maksimstojkovic** [comment]
@SchrodingersGat greetings from NSW! In addition to the button above, what are your thoughts on automatically creating a shipment for SOs, since it is not possible to complete an order without completing at least one shipment?

**Comment by SchrodingersGat** [comment]
Yeah that's a reasonable suggestion. A default shipment which gets created an a SalesOrder is created would improve the workflow considerably. Most orders would only ever have one shipment so it could cut out the manual shipment creation process entirely.

**Comment by matmair** [comment]
@SchrodingersGat still valid that we will fit this in 0.7.0 ?

**Comment by SchrodingersGat** [comment]
Probably not, `0.7.0` is getting pretty close. If this does not receive any attention soon I'll bump it to `0.8.0`

**Comment by maksimstojkovic** [comment]
I'll try working on this feature. Please assign it to me when possible.

Bump this feature to `0.8.0` if necessary to avoid release delays.

**Comment by SchrodingersGat** [comment]
Thanks @maksimstojkovic  - please ping me if you have any questions about this
