### ISSUE TITLE
[FR] Complete All Pending SO Shipments in SO Page Actions Menu

### ISSUE THREAD

**Issue by maksimstojkovic** [inventree/InvenTree#2986]
**Is your feature request the result of a bug?**
No.

**Problem**
Upon completing all SO stock allocations, each pending shipment has to be completed individually before an SO can be completed.

**Suggested solution**
Add a complete all allocated shipments option to the SO #page-actions menu to make it possible for easier order processing. Implementation rationale may vary based on industry, so discussion may be required, but I proposed an item in the #order-options dropdown to make it less likely that it is clicked by accident, and that the button should process all orders which have at least one item in them. The modal created for this action should include a confirmation toggle like most other modals.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/18454392/168199456-be5a7f7a-c8c5-437e-94da-b55e1f3a58a2.png">

**Describe alternatives you've considered**
A complete pending shipments button could be added to the #page-actions menu next to complete orders, but this is likely to cause errors if clicked by accident.

**Examples of other systems**
I only have experience with InvenTree with regard to this aspect of fulfillment.

**Do you want to develop this?**
No, as I don't have experience with frontend development using JS.

**Comment by matmair** [comment]
@maksimstojkovic thanks for the suggestion!
I would like to discuss how this fits into a shops workflow.

You generally create multiple shipments because you do not want to wait for a few parts to ship everything. You close each shipment as soon as it is possible to ship - so I am not sure why you should have multiple shipments open at once.

I am open for feedback but with the current set of information I am sceptical what value the action would bring.

**Comment by maksimstojkovic** [comment]
@matmair I totally agree. Logically it would only make sense to have one shipment pending at any given time.

Given this context, my suggestion above should have focused more on the semi-redundant nature of navigating to the Pending Shipments menu to press Complete Shipment. My suggested solution is adding an option to the Page Actions menu under the Order Options dropdown to complete the pending order (as you've mentioned, only one order should be pending).

What I've described in my original FR is an edge case where multiple shipments are pending (which is somewhat unlikely and lacks business logic), in which case any shipments which have been allocated stock should be processed for completion, with a confirmation modal. Checkboxes designating which shipments should be completed could also be added if desirable.

**Comment by SchrodingersGat** [comment]
@maksimstojkovic this mirrors similar behaviour in other tables, where an action can be performed on multiple items selected from a table. I think this makes sense as an addition, but is of low priority given all the other dev tasks we have on.

Is this something you would be willing to tackle?

**Comment by maksimstojkovic** [comment]
I'll try working on this feature. Please assign it to me when possible.

Bump this feature to 0.8.0 if necessary to avoid release delays.
