### ISSUE TITLE
[FR] Support webp images

### ISSUE THREAD

**Issue by opcod3** [inventree/InvenTree#2988]
**Is your feature request the result of a bug?**
No

**Problem**
Some websites such as mouser use webp images, this makes copying them into inventree annoying as they have to be converted to jpeg or png.

**Suggested solution**
Implement support for uploading/downloading webp images.

**Describe alternatives you've considered**
Possibly automate conversion to png/jpeg, but this feels to be a more complex solution.

**Examples of other systems**
This is not really relevant to this problem.

**Do you want to develop this?**
I don't have any experience with django so I don't feel comfortable implementing this feature. But I feel it should be relatively straightforward.

**Comment by SchrodingersGat** [comment]
@opcod3 I thought it did already support webp, I have definitely uploaded images directly from Mouser / Digi-Key before. Maybe this behaviour is a new issue... Can you please share the exact issues / error you are seeing when you try to add .webp files?

**Comment by opcod3** [comment]
Using the following image: [Image](https://www.mouser.it/images/kemet/images/Kemet_SMD_MLCC_DSL.jpg)

Directly pasting the url into InvenTree yields the following form:
```
Error posting form data

error
Error Code - 0

Show Error Information
undefined
```

By downloading the image I get the following file: `Kemet_SMD_MLCC_DSL.webp`. When I try to upload it I get: 
```Upload a valid image. The file you uploaded was either not an image or a corrupted image.```

**Comment by SchrodingersGat** [comment]
Yeah most likely due to docker dependency issues. If you are able to do so please submit a PR

**Comment by opcod3** [comment]
I'll try to, but I'm a low level developer by trade... Docker is generally black magic to me
