### ISSUE TITLE
[BUG] Missing tests for plugins

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2992]
**Describe the bug**
There are tests missing for multiple mixins:
- events
- ~~custom panels~~ - https://github.com/inventree/InvenTree/pull/3034
- ~~locate plugin~~ - https://github.com/inventree/InvenTree/pull/3027
- printing - https://github.com/inventree/InvenTree/pull/3037

**Steps to Reproduce**
Current coverage graph

**Expected behaviour**
There are **no** functional tests - they can be broken by accident easily. Coverage at least for the functions is expected.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/66015116/168453439-03170ff8-5ab4-4080-9cc2-b3a3384b93df.png)

**Deployment Method**
- Any

**Version Information**
current master

**Comment by SchrodingersGat** [comment]
@matmair are you happy with the coverage for the `events` plugin system, or would like to see more work on it before `0.7.0` release?

**Comment by matmair** [comment]
@SchrodingersGat I would appreciate if we could cover all mixins and samples - but this is a soft target for me.
