### ISSUE TITLE
[FR] Remove python 2 / 3.7 support from codebase

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#2996]
**Is your feature request the result of a bug?**
#2994 

**Problem**
We have some stuff in the codebase that targets python2 / 3.7 compatibility

**Suggested solution**
I suggest standardising the codebase to python 3.8 (ships with the major *ix distros). This means:
- removing unicode_literall imports
- removing encoding headers
- remove imports that are targeted for stdlib paths lower than 3.8

**Describe alternatives you've considered**
Not doing this does not hurt us directly - fewer LoCs would just be easier to maintain

**Examples of other systems**
Show how other software handles your FR if you have examples.

**Do you want to develop this?**
Yes

**Comment by matmair** [comment]
@inventree/maintainer @inventree/triage thoughts?

**Comment by SchrodingersGat** [comment]
@matmair I am on board. Any estimate of how much 2.x / 3.7 code we have currently?

**Comment by matmair** [comment]
@SchrodingersGat currently looking into it. Most things are Unicode patches (python3 is Unicode by default) and encoding headers. Those can just be deleted - the rest needs to be looked at. I am running an upgrade analyzer rn.
