### ISSUE TITLE
Additional Information on Purchase/Sales Orders

### ISSUE THREAD

**Issue by jonasexpleo** [inventree/InvenTree#3003]
**Is your feature request the result of a bug?**
Discussed in https://github.com/inventree/InvenTree/discussions/2867

**Problem**
I'm trying to use the sales order report system for printing a delivery note.
In the delivery note we need some additional information:

* for a bigger company we need to define the recipient of the package,
* in some cases a different shipping address (most companies have different locations)

For filtering and ordering of the SO:

* order priority
* a tag like product cluster for filtering the orders

**Suggested solution**
I like to have additional fields which are associated to an order. These filed should be filled during creation of an order. The report generator can access the set values.

Additionally it would be great to be able to filter in the overview and to search after a set value.

**Describe alternatives you've considered**
I have considered:

* Using the description field for the information. It would be usable for me, for example with a comma as separation between the data, but there are users with no technical background and it would be easy to miss/mix up the information.
* Using the notes field. But we have in our big overview table already a notes/comment field and I rather want to let the users to append comments.
* Adding for each recipient/address of a company an inventree company. One side this is doable, but it would reduce the possibility to get an overview how many/which orders went to a company. Additionally many recipient-companies would have only one order.

**Benefits**
* The user has the possibility to adapt the field to his needs and no code needs to be changed.
* A parameter like storage has the possibility to reuse the data in the reporting system.
* The structured data has also the possibility to easily change the data through the API.
* This would have also the benefit to easily spot missing data, e.g. with a script

**Examples of other systems**
I did not search for solution in other system, but inventree has a similar functionality with the parameters for parts.

**Do you want to develop this?**
preferred not, as I won't have the time in the next half year.

**Comment by SchrodingersGat** [comment]
@jonasexpleo I am currently working on implementing a "metadata" extension system - as part of https://github.com/inventree/InvenTree/pull/2957

This would basically add a `metadata` field to the internal models, which would allow addition of arbitrary JSON data 

- The metadata would not be used by InvenTree business logic
- The metadata can be used by the user for *some purpose* but this purpose is not defined
- Ideally, this is to be used by custom plugins for storing custom information

I think that would suit your purpose. Implementing custom fields for every possible use case is not something we are going to consider. What do you think of the metadata approach?

**Comment by jonasexpleo** [comment]
@SchrodingersGat I like the approach with metadata.
I understand your hesitation against implementing specific custom fields, I wouldn't use this approach either. 

Just to be clear: when I speak from fields, I speak from the view of an user, not how the information are stored.
I was more thinking from the GUI perspective, where a staff or admin could add the custom fields and the user can use the fields. The storage could then be the metadata field. As from my point, no business logic needs to interact with it (except report generator for accessing the data).

How would you handle the GUI? Is it better in a plugin or should this be integrated in to the main code?

**Comment by matmair** [comment]
@jonasexpleo this sounds like a good plugin candidate. We try to not balloon the core feature set (we are only achieving that somehow. A lot is being added lately - but it is cool stuff).
You can def. ping me if you run into problems. We always appreciate plugins that can serve as examples.

**Comment by SchrodingersGat** [comment]
Closed by https://github.com/inventree/InvenTree/pull/2957
