### ISSUE TITLE
[TODO] Refactor "success" and "onSuccess" in javascript

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3007]
Currently the javascript code mixes use of "success" and "onSuccess" for naming of callback functions.

This should be consolidated to use `success` callback functions for all InvenTree js code.

**Comment by SchrodingersGat** [comment]
@architsinghal-mriirs gladly, please let me know if you need any pointers on where to dive into the code!

**Comment by SchrodingersGat** [comment]
Hey @architsinghal-mriirs how's it going? Need any pointers?

**Comment by architsinghal-mriirs** [comment]
Hi @SchrodingersGat , As per my understanding, I have to replace all occurrences of 'onSuccess' with 'Success' . is this right ?

**Comment by SchrodingersGat** [comment]
Correct!

**Comment by SchrodingersGat** [comment]
Closing this one out, we will be refactoring the entire front-end to use a modern framework, no point making this change..
