### ISSUE TITLE
[FR] Refactor multi-delete forms

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3008]
Ref: https://github.com/inventree/InvenTree/pull/3006

There are multiple forms which are currently used to perform multiple object deletions which need to be refactored. The `DELETE` calls should not be run in parallel, and the forms themselves could use some visual enhancements.

These forms could also be refactored to include the single item deletion, and thus work towards implementing https://github.com/inventree/InvenTree/pull/2934

- ~~Delete SupplierPart(s)~~
- ~~Delete ManufacturerPart(s)~~ - https://github.com/inventree/InvenTree/pull/3067
- Delete parameter(s)
- Delete StockItem(s)

**Comment by matmair** [comment]
@SchrodingersGat bump this to `0.7.x` ?
