### ISSUE TITLE
[BUG] Serial numbers are not allowing letters

### ISSUE THREAD

**Issue by wolffam** [inventree/InvenTree#3015]
**Describe the bug**
We are finding that serial numbers are now required to be only numbers as opposed to alphanumeric characters.  Some parts will have a serial number such as "2PE34354SER."  Entering such a serial number for a stock item now returns an error "Invalid group" on the Add Stock Item form.  We currently get around this by putting in a dummy numeric serial number and then editing the stock item to put in the actual one.

**Steps to Reproduce**

1. Add new stock item for a trackable part
2. Enter serial number "2P"
3. Note the form error

**Expected behavior**
- Adding a new stock item with a serial number containing alphanumeric characters is allowed

![Screen Shot 2022-05-16 at 11 23 27 AM](https://user-images.githubusercontent.com/11801197/168657862-8f70ece1-1a60-4150-a08e-5a6b4ae3ce2e.png)

**Deployment Method**
- [ X] Docker
- [ ] Bare Metal

**Version Information**
InvenTree-Version: 0.6.3
Django Version: 3.2.12
Commit Hash: 86b0b50
Commit Date: 2022-03-30
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
@wolffam looks like this has been fixed in master - `0.7.0` release is imminent

![image](https://user-images.githubusercontent.com/10080325/168692546-d3d0808f-acad-4b93-a553-4531bdffad88.png)

Can you please check on https://demo.inventree.org and confirm that the issue has been addressed?

**Comment by wolffam** [comment]
Seems like it has!  Easiest bugs are the ones already squashed ;)

I'll be sure to check against the demo in the future.

![Screen Shot 2022-05-16 at 3 30 11 PM](https://user-images.githubusercontent.com/11801197/168692979-38ee5b2d-3066-48f6-a4ff-068b661095e1.png)
