### ISSUE TITLE
[FR] Possibility to add parts to Purchase order without prior assignment to Supplier

### ISSUE THREAD

**Issue by Angrite** [inventree/InvenTree#3021]
**Problem**

Imagine Purchase Orders for e-commerce companies, such as Amazon and eBay, where almost any part can be ordered. 
It would be a nice feature, if for such seller any part can freely added in Purchase Order, without prior manual parts assignment to such seller. 

**Suggested solution**
For each Supplier option (chekbox) “e-commerce company” can be checked (unchecked by default).
When forming PO for such Supplier, any Inventree existing purchasable part can be placed without prior assignment to a Supplier.

**Describe alternatives you've considered**
May be wanted workflow (put in order any part) can be realised in different way? Currently can’t imagine alternative.

**Do you want to develop this?**
Unfortunately, not familiar with Inventree code quite enough yet

**Comment by matmair** [comment]
@Angrite thank you for the suggestion.

The current system is built around traceable and versatile part definitions. Therefore we have the system of parts, supplier-parts and manufacturer parts. These need certain data so just adding a button 'add anything' will dilute the quality of data in the system and make it difficult to ensure the exact and right part is ordered again.
Therefore I would give this a low priority. The button should also have a less usage oriented name ('order online parts') but more functional ('do not enforce supplier-part definitio'n or 'use parts for order lines'). This transports the function and therefore is more open for other workflows that need that action but are not online ordering.

**Comment by matmair** [comment]
Also could you please make the title a bit clearer - the current one could suggest you want to order from an e-commerce outlet from within InvenTree or that we do not support online sellers currently.

**Comment by Angrite** [comment]
> Also could you please make the title a bit clearer - the current one could suggest you want to order from an e-commerce outlet from within InvenTree or that we do not support online sellers currently.

Changed to "Possibility to add parts to Purchase order without prior assignment to Supplier"

**Comment by matmair** [comment]
@SchrodingersGat where in the roadmap would see a feature like that/is this a plugin candidate? Technically it would be possible to add a custom page which serves as an order agent.

**Comment by SchrodingersGat** [comment]
The current `Part <- SupplierPart <- Supplier` relationship is very important, allowing users to keep track of supplier information for any given part.  I'm not sure that this could (or should) be integrated as a core feature - I would definitely like to keep the requirement that a `SupplierPart` is required for a `PurchaseOrder`.

Maybe we could make the linking between part / supplierpart / supplier easier, and enable this as an inline operation on the purchaseorder form?

**Comment by matmair** [comment]
@SchrodingersGat I can see the appeal but this would rank rather low on my list of important issues. Better said: I would not block a PR that implements it but do not plan to do any dev on it. And if it were to be implemented I would strongly suggest full e2e and unit testing as there are many things that can break.

**Comment by SchrodingersGat** [comment]
Agreed. I'm not going to dedicate any time to this, and I am against loosening the requirements for the SupplierPart model as it exists currently.

**Comment by SchrodingersGat** [comment]
@Angrite I don't think the suggestion fits with our development goals. Maybe it could work as a custom plugin?
