### ISSUE TITLE
[BUG] Supplier Multiple not taken into account

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3030]
I am new to InvenTree, am just getting started implementing it in a way which suits me. So far it seems to do just what I want!

**Describe the bug**
The admin interface allows adding a Multiple (Order multiple) to a supplier part. I assume that a part I buy in a 3-pack from a supplier, should have an order multiple of 3 here - and if I order one of the corresponding supplier part, I should obtain 3 parts in stock.

**Steps to Reproduce**

1. Go to admin/company/supplierpart/xx/change/
2. Put '3' in Multiple field
3. Place order for the corresponding part. Order 1 pack.
4. Receive pack of 3
5. Check in order, assume that stock is now 3.
6. Stock is 1

**Expected behavior**
6. Stock should be 3

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
# Version Information:
InvenTree-Version: 0.6.4
Django Version: 3.2.12
Commit Hash: ee00057
Commit Date: 2022-05-10
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by matmair** [comment]
Hi there @miggland 
This is not a bug. If a function or model is not exposed in the UI it is not meant for public consumption. We have some fields that are there for historic reasons but mot accesible through the user interface. If you want a certain function please open a feature request.

**Comment by matmair** [comment]
A pretty similar frature request already exist here: #1435

**Comment by miggland** [comment]
Hello @matmair . Thanks for the reply. The feature request does sound similar, I am fine with continuing there..
