### ISSUE TITLE
Inventree - Inaccurate stock item quantity post allocation

### ISSUE THREAD

**Issue by palagap** [inventree/InvenTree#3053]
I'm running into the following issue: 

When allocating stock to a build, the main page for the part is updated to reflect the deceased quantity of the part, but the actual batch for the part is not automatically updated. Attached below is a more detailed description of the issue. Would appreciate any guidance on how to resolve this discrepancy.

[InvenTree Stock Allocation Issue.pdf](https://github.com/inventree/InvenTree/files/8758064/InvenTree.Stock.Allocation.Issue.pdf)

**Comment by matmair** [comment]
Hi there @palagap !
Please fill out the [bug template](https://github.com/inventree/InvenTree/issues/new?assignees=&labels=bug%2C+question&template=bug_report.md&title=%5BBUG%5D+Enter+bug+description) - due to security concerns some users will not open unknown pdfs.

**Comment by palagap** [comment]
Thanks, @matmair - I'll do that and close this issue.
