### ISSUE TITLE
Inaccurate stock item quantity post allocation

### ISSUE THREAD

**Issue by palagap** [inventree/InvenTree#3055]
Hi there,

The issue I am encountering, is an inaccurate count of an available stock item in InvenTree. To demonstrate this issue, I'll walk through the example below. 

First, I logged into the InvenTree demo account (https://demo.inventree.org/) with the username as `admin` and the password as `InvenTree`. Then, I created a new build order – in this case, a blue chair:

<img width="1915" alt="Screen Shot 2022-05-23 at 12 54 29 PM" src="https://user-images.githubusercontent.com/40808444/169915915-0d61113a-e540-429b-9c96-2389aae86d84.png">

Looking at the “Allocate Stock” panel at the bottom of the page, we can see the required parts and the respective available quantities:

<img width="1656" alt="Screen Shot 2022-05-23 at 12 54 55 PM" src="https://user-images.githubusercontent.com/40808444/169915989-7a4cc0c8-7ab6-4b73-a92a-c4b8a8074f60.png">

For this example, we’ll allocate the Leg (4) and Wood Screw (5) to the build:

<img width="1678" alt="Screen Shot 2022-05-23 at 12 55 10 PM" src="https://user-images.githubusercontent.com/40808444/169916040-114ea04c-11b0-4dba-851b-01ebea326d99.png">

Before doing this, we click on the Leg and Wood Screw links to see the available quantities pre-allocation:

<img width="1684" alt="Screen Shot 2022-05-23 at 12 56 03 PM" src="https://user-images.githubusercontent.com/40808444/169916071-a6ca3297-a170-47e8-ab9a-d715e44232e9.png">
<img width="1672" alt="Screen Shot 2022-05-23 at 12 56 14 PM" src="https://user-images.githubusercontent.com/40808444/169916082-7cab3bf6-68de-46b0-b9ad-ac3d61143e9e.png">

In this case, there are 877 legs and 1679 wood screws currently available. We allocate by selecting the stock items from the appropriate batches:

<img width="1247" alt="Screen Shot 2022-05-23 at 12 55 35 PM" src="https://user-images.githubusercontent.com/40808444/169916137-f2ece5b6-578c-450d-8f52-362bbf31bd18.png">

After allocation, we see the following:

<img width="1657" alt="Screen Shot 2022-05-23 at 12 55 51 PM" src="https://user-images.githubusercontent.com/40808444/169916178-20f88403-f7d2-446b-9fd8-32f4d0660066.png">

We see that the available quantities for the Leg and Wood Screw have decreased to 873 and 1674, respectively. This is also reflected in the individual pages for each part:

<img width="1685" alt="Screen Shot 2022-05-23 at 12 56 56 PM" src="https://user-images.githubusercontent.com/40808444/169916249-87f53c76-9671-49b8-9101-9ff579ec22ae.png">

<img width="1667" alt="Screen Shot 2022-05-23 at 12 57 05 PM" src="https://user-images.githubusercontent.com/40808444/169916256-239c5683-f3a4-4049-b842-0e233c4a82d5.png">

If we select the “Stock” tab on the left half of the screen, however, we see that the stock numbers are not updated. For instance, we allocated 4 legs from the batch of 100 (2022-5-23), but the batch is still listed at 100 rather than 96. The same is true for the wood screws, which are still listed at 1084. 

<img width="1687" alt="Screen Shot 2022-05-23 at 12 56 27 PM" src="https://user-images.githubusercontent.com/40808444/169916322-0f2f6617-5713-4e4a-b833-ed30ded5047b.png">

<img width="1673" alt="Screen Shot 2022-05-23 at 12 56 38 PM" src="https://user-images.githubusercontent.com/40808444/169916347-9e7ad49b-31e9-428f-a1a2-a60c59e89474.png">

We would need to click on the stock number to access the panel below, where we can see that despite there being 100 listed parts, 4 are already allocated to a build. In other words, we would need to do the computation ourselves to determine that there are 96 rather than 100 parts available for use in this batch. Having this number automatically updated, as the main part page is, would be very helpful.

<img width="1696" alt="Screen Shot 2022-05-23 at 12 57 21 PM" src="https://user-images.githubusercontent.com/40808444/169916401-e1ab65a3-5c9a-4987-8d8b-8713104382b3.png">

**Deployment Method**
- [ X ] Demo (Web)
- [ ] Docker
- [ ] Bare Metal

**Version Information**
0.7.0 dev

**Comment by SchrodingersGat** [comment]
@palagap fair point, it would be useful  to be able to see the "available" quantity on the stock detail page!

**Comment by palagap** [comment]
Great, thanks! :)

**Comment by matmair** [comment]
@SchrodingersGat should this be 0.7.0 or be moved to 0.7.1?

**Comment by SchrodingersGat** [comment]
@matmair I'll be able to squeak it in, will only be a very minor change

**Comment by SchrodingersGat** [comment]
@palagap check out https://github.com/inventree/InvenTree/pull/3057
