### ISSUE TITLE
[FR] Make "confirm" buttons a user-configurable option

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3069]
Some complaints from users that the "confirm" buttons on some dialogs are too "onerous"

Might be worth making this a simple user-configurable option (default=on)

**Comment by matmair** [comment]
While I cannot see me disabling this an option cannot hurt.

**Comment by nwns** [comment]
I assume this is referring to the confirm slider on some dialogs not the entire confirm dialog in general?

**Comment by matmair** [comment]
I mean a default that does not change the current behavior should be fine. Hobbyists probably do not need the extra check.
