### ISSUE TITLE
[BUG] Search Menu Not Finding Items

### ISSUE THREAD

**Issue by maksimstojkovic** [inventree/InvenTree#3073]
**Describe the bug**

The search menu appears to be perpetually "searching", both before and after entering text in the search bar.

**Steps to Reproduce**

1. Open search menu.
2. Type in product name.

**Expected behavior**

 Items should appear in the search bar.

**Screenshots**

**Note:** Instance was recently updated from 0.6.4 to 0.7.0 and `invoke update` was called.

Before Entering Text in Search Bar:
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/18454392/170184479-f57975b2-e344-4535-9824-e4863bf0b4e5.png">

After Entering Text in Search Bar:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/18454392/170186278-caa87faf-6377-4097-8cc7-6717f4b1e1c5.png">

Below are reference images of the same actions performed in the demo instance for comparison.

Before Entering Text in Search Bar:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/18454392/170186404-c68b8319-f99d-456d-9ee6-8b173c96efcb.png">

After Entering Text in Search Bar:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/18454392/170186477-0f1f4d29-064d-4be3-8ea7-8ab0f1cb9893.png">

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**

InvenTree-Version: 0.7.0
Django Version: 3.2.13
Commit Hash: 044315a
Commit Date: 2022-05-24
Database: mysql
Debug-Mode: True
Deployed using Docker: True

**Note:** Instance was recently updated from 0.6.4 to 0.7.0 and `invoke update` was called.

**Comment by maksimstojkovic** [comment]
@SchrodingersGat correct. Those images were just for comparison.

**Comment by SchrodingersGat** [comment]
Have you tried doing a hard-refresh of your browser? Maybe the javascript files have been cached incorrectly.

**Comment by maksimstojkovic** [comment]
That was it! I overlooked hard refreshing after upgrading. Thank you!
