### ISSUE TITLE
[FR] Sign artifacts with sigstore

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3077]
**Problem**
We are not signing our artefacts (docker images, pypi packages) right now.

**Suggested solution**
The big players are working together on a framework for this called sigstore.
This article describes how to do it on docker: https://dev.to/n3wt0n/sign-your-container-images-with-cosign-github-actions-and-github-container-registry-3mni
I am looking into pypi right now.

**Describe alternatives you've considered**
The current way works - it would be cool to be on the leading side of security in the industry though.

**Do you want to develop this?**
Yes if now one else wants to

**Comment by matmair** [comment]
@SchrodingersGat would that be possible with #3042 ?

**Comment by SchrodingersGat** [comment]
@matmair looks like a nice idea, am certainly keen to look into implementing that. Definitely if it is part of the automated build procoess

**Comment by matmair** [comment]
@SchrodingersGat it is only 2 additional actions and no manual work so docker should be no problem. Pypi seeks a bit more involved right now.
