### ISSUE TITLE
[FR] Automated releases

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3078]
**Problem**
Releases are currently a very manual process. That covers multiple repos.

**Suggested solution**

- [x] Use GitHubs automatic release note creation (with attribution, new contributors, section etc) [the docs are great](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)
- [ ] Create a release action that runs after a release is created on invenTree/InvenTree and then runs on inventree-docs and inventree-python #3100 
- [ ] Create a PR template for releases

**Do you want to develop this?**
This would be a team effort but would be happy to do the dev-ops side

**Comment by matmair** [comment]
Inspiration for workflow: https://gist.github.com/riggaroo/d828c5ffecf261d3ccc7bde89817dba5

**Comment by matmair** [comment]
https://github.com/gr2m/twitter-together for releasing tweets

**Comment by matmair** [comment]
https://github.com/marketplace/actions/release-for-reddit for releasing reddit post

**Comment by SchrodingersGat** [comment]
This is definitely on my radar, every release cycle takes so much work, and invariably I'll overlook one of the many steps

**Comment by matmair** [comment]
@SchrodingersGat should we maybe start with a list of steps?

**Comment by SchrodingersGat** [comment]
### Release Notes / Changes / Milestones

Currently we assign PRs and issues to milestones, so we can look back and see exactly what has been done for a certain release.

We then also copy / reproduce this information over on the documentation repo, e.g. https://inventree.readthedocs.io/en/latest/releases/0.7.0/

This is a major duplication of data, ideally there would be a way of automating this / removing duplication?

### Post Release Steps

There a number of post-release steps which are currently performed manually

- Twitter post
- Reddit post
- GitHub discussion post
- Tag and release matching [documentation version](https://github.com/inventree/inventree-docs)
- Push new release to 'stable' branch also
- Release new version of python bindings (if applicable)
- Release new version of mobile app (if applicable)

**Comment by matmair** [comment]
@SchrodingersGat the GitHub automated release note creation could take care of the first part - the rest could be done by a workflow that runs on release publishing.
