### ISSUE TITLE
[FR] Parameter filtering 2.0

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#3080]
## 0.6.4 stable

![image](https://user-images.githubusercontent.com/4020546/170566376-3e4db1d7-1870-45b6-978c-fa1b252f454c.png)

## 0.7.0 stable

![image](https://user-images.githubusercontent.com/4020546/170566942-0c1d1b16-c35d-41cb-a097-ed5b0f652054.png)

## Bug description

See screenshots above, I would like to get back to the `0.6.4` table filter settings if possible, as I use this feature often :smiley:

**Comment by matmair** [comment]
@eeintech seems to be a regression rather than a bug.

**Comment by eeintech** [comment]
@matmair https://en.wikipedia.org/wiki/Software_regression

"A software regression is a type of [software bug](https://en.wikipedia.org/wiki/Software_bug) where a feature that has worked before stops working."

Anyway happy to label it otherwise in the title, lemme know

**Comment by SchrodingersGat** [comment]
@eeintech this was probably broken in https://github.com/inventree/InvenTree/pull/2761 which moved the part parameter table to use the API

The 'table filter' function required all the data to be loaded into the table when the table is initialized. For large datasets this made the page take dozens of seconds to load (which is not tenable). So, we moved to using the API, and all was right with the world.

However, I did not realize that this "filter" feature relied on the old way of doing things.

If you want this feature back, we'll have to work out a way of filtering part parameters via the API.

This is something I've wanted to do for ages, to be able to say (for example) "give me all bits of wood which have a length between 20mm and 200mm"

Until we have that system in place, this table will be sadly lacking in any filters.

**Comment by SchrodingersGat** [comment]
Parameter filtering will be a super powerful feature, will take some thinking to get it implemented though :)

**Comment by matmair** [comment]
@SchrodingersGat I think we should try to get that working with the general filter setup

**Comment by SchrodingersGat** [comment]
Absolutely!

**Comment by eeintech** [comment]
Changed the title as while being a regression this is now oriented towards a better implementation!

**Comment by SchrodingersGat** [comment]
@eeintech check out some of the work going on in https://github.com/inventree/InvenTree/pull/4823

**Comment by eeintech** [comment]
@SchrodingersGat Really cool, thanks!
