### ISSUE TITLE
[BUG] 0.7.0 New search bar creates error banner related to permission

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#3082]
**Describe the bug**

See below:
![image](https://user-images.githubusercontent.com/4020546/170575749-539939c5-e5e0-40ca-9d4b-6111fcc0ad3c.png)

**Steps to Reproduce**

1. Create group with no "Sell" permission, create user inside that group
2. Enter string in search bar
3. Red banner pops up in the main view (behind search bar)

**Expected behavior**

API search should not be triggered for items that are not in allowed to be viewed by user.

**Version Information**

0.7.0 stable

**Comment by SchrodingersGat** [comment]
@eeintech good catch!
