### ISSUE TITLE
[BUG] Shipment tracking information lost on completing shipment

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3085]
**Describe the bug**
When creating shipments for sales orders, there is the possibility of adding a tracking number at the beginning, and at completion of the shipment.
If it is added at creation, and no information is added on completion, the tracking ID is lost.

**Steps to Reproduce**

1. Create Shipment under 'pending shipments'. Enter a tracking ID
2. Assign stock to shipment
3. Click on 'Complete shipment'
4. Do not enter a tracking ID (since it has already been entered)
5. Check for tracking ID under completed shipments - there is none.
--->

**Expected behavior**
If I enter a tracking ID, it should not be silently removed. The possibility to change is good.
It would be enough if the tracking ID is filled in when completing the shipment, so that it is either carried forward, or can be changed.

**Deployment Method**
- [ ] Docker

**Version Information**
```
# Version Information:
InvenTree-Version: 0.6.4
Django Version: 3.2.12
Commit Hash: ee00057
Commit Date: 2022-05-10
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

```

**Comment by SchrodingersGat** [comment]
@miggland can you please see if you can replicate this behaviour on the demo server (https://demo.inventree.org) - I *believe* that this has already been fixed? Please let me know either way

**Comment by miggland** [comment]
@SchrodingersGat: Your demo server is living in the future :) The issue has been fixed, and does not occur on the demo server.

**Comment by SchrodingersGat** [comment]
That's great to hear! 0.6.4 is a little outdated now is all

**Comment by miggland** [comment]
You're obviously moving fast, which is great. I did just install the system within the last month though! I will update to 0.7.0 asap
