### ISSUE TITLE
[BUG] Missing /bin/bash: ../docker/init.sh: in docker

### ISSUE THREAD

**Issue by markusEmm123** [inventree/InvenTree#3088]
**Describe the bug**
When starting a docker image "latest", the container immideately terminates with (only) the error message
/bin/bash: ../docker/init.sh: No such file or directory

**Steps to Reproduce**

1. Download image inventree/inventree:latest (or stable) on May 28th
2. Set up a container with volume link to existing inventree static data folder
3. Run container

"/docker/inventree/" on the host system is linked to "/home/inventree/" in the container.
"/docker/inventree/" on the host contains the folder "data" and in there "media","static", the keyfile and so on. This folder is from a backed up installation from before a hard drive crash. 
In addition a new folder "InvenTree" is created in the /docker/inventree folder on execution of the container.

**Expected behavior**
Inventree starts.

**Deployment Method**
- [x] Docker (Synology)
- [ ] Bare Metal

**Version Information**
Info section not reachable

**Comment by matmair** [comment]
@markusEmm123 could you pull the hash of the image you are experiencing the problem with?

**Comment by matmair** [comment]
@markusEmm123 we are currently restructuring the docker-files pls use the 0.7.0 release / :stable if you need a running install - latest is always bleeding edge, sometimes without corresponding docs.

**Comment by matmair** [comment]
@SchrodingersGat could this be a result of the current refactoring?

**Comment by markusEmm123** [comment]
Thanks for the quick response.

Error persists with :stable (identical behaviour to :latest concerning this error)

Error does not occur when i remove the link to the persistent storage (the container then runs until it encounters some error caused by the misconfiguration due to the wrong home folder)

..working on the hash...

**Comment by markusEmm123** [comment]
Name: inventree-inventree(stable).syno.tar
Size: 1854420480 Bytes (1768 MiB)
SHA256: 4012344A5AF09DFE84C3C9A0FD09B098B7235E84F1D19BADEFF9937130E38F67

Those are the values of an exported image from the Synology Docker app though. I don't know if that is a 100% identical copy of the image from docker hub.
But as the error occurs with both :stable and :latest i would rule out some download/data error if that was what you were going for.

**Comment by matmair** [comment]
Intresting. Our docker pipeline runs through. Could you compare cour docker-compose file with [this](https://github.com/inventree/InvenTree/blob/master/docker/docker-compose.yml) for development and this for [production](https://github.com/inventree/InvenTree/blob/master/docker/production/docker-compose.yml)?

**Comment by markusEmm123** [comment]
@matmair unfortunately i'm running the container on my Synology NAS and therefore can't access the compose file as far i know.
From what i can tell the main differences are that 
1. i use MariaDB (mysql) as database server (not running in a container) and 
2. i only have one container running (not split up in server and worker)

That way it has worked up to now, but i'm not sure which version i was running when my system crashed and if the behaviour has changed since that version.

**Comment by markusEmm123** [comment]
Actually the screenshot from my former bug report helped me get the seetings right.
I had to link /docker/inventree/data to /home/inventree/data (not /docker/inventree to /home/inventree).
I was missing the /data subdirectory in the volume link.

**Comment by SchrodingersGat** [comment]
@markusEmm123 so it is all working for you now, or still problems persist?

**Comment by matmair** [comment]
@markusEmm123 regarding 2: in this way a low of new functions will not work as we are offloading more and more functions (especially notifications, events, plugins) to make the user interface speedier.

Is it working now?

**Comment by markusEmm123** [comment]
Thanks for all the support, it is working now.
And thank you for the hint with the split-container setup, i will work on that.
