### ISSUE TITLE
[BUG] 0.7.0 BOM Import fails to match parts by Part ID

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#3097]
**Describe the bug**

On last step of BOM import, it fails to match parts by Part ID field:

![image](https://user-images.githubusercontent.com/4020546/170979893-ed5ddb7e-51fa-4f45-bd28-9d0b6348d1f3.png)

**Steps to Reproduce**

1. In Part view, click "Bill of Materials" then click tools dropdown and "Upload BOM"
2. Select a file which contains valid reference, part ID and quantity columns
3. Match the columns to InvenTree fields and click submit
4. Part matching fails to automatically select corresponding InvenTree parts designated by Part IDs

**Expected behavior**

Part matching should be successful.

**Version Information**
InvenTree-Version: 0.7.0 (stable)
Django Version: 3.2.13
Commit Hash: 044315afb
Commit Date: 2022-05-24
Database: postgresql
Debug-Mode: False
Deployed using Docker: False

Deployment Method: Bare Metal

**Comment by SchrodingersGat** [comment]
Any fix here will have to include improving our unit testing around the BOM import tool

**Comment by eeintech** [comment]
You know what, it was a user issue... I mixed up Part ID and IPN :clap: :disappointed: 

Import works just fine, sorry for the noise.
