### ISSUE TITLE
[BUG] 0.7.0 PO Import tools issues

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#3098]
**Describe the bug**

There are multiple issues with the Purchase Order import tool:
1. When user selects a file, file name is shown twice

![image](https://user-images.githubusercontent.com/4020546/170981428-b1c1f974-a8d9-4f6e-8241-b80bcee46e00.png)

2. On step 2, the file column names are missing from the view

![image](https://user-images.githubusercontent.com/4020546/170981598-1eacb750-73f3-4f93-a877-812a407df7f4.png)

3. Still on step 2, the two actions buttons are "Previous Step" and "Upload File", but file was **already** uploaded

![image](https://user-images.githubusercontent.com/4020546/170981757-3fd88bee-6aae-44ac-aaab-a62b6e74b8f7.png)

4. Attempt to go to step 3 clicking on "Upload File" results in automatic error

![image](https://user-images.githubusercontent.com/4020546/170981932-cef32a8a-4b7c-4269-8a62-695a88ba98ad.png)

**Steps to Reproduce**

1. Click on an existing and pending purchase order
2. Click on "Upload File" button
3. Follow the form

**Version Information**
InvenTree-Version: 0.7.0
Django Version: 3.2.13
Commit Hash: 044315afb
Commit Date: 2022-05-24
Database: postgresql
Debug-Mode: False
Deployed using Docker: False

Deployment Method: Bare Metal

**Comment by SchrodingersGat** [comment]
I think we should make the leap and migrate the Purchase Order importer to the API importer (as is used for BOM importing)

Ref: https://github.com/inventree/InvenTree/issues/3097

**Comment by SchrodingersGat** [comment]
There is too much work required here to fix this, as we will be overhauling the entire import tool in #3101

**Comment by Geekly** [comment]
Is there a workaround for this, or is importing for a PO just not going to work?

**Comment by eeintech** [comment]
@matmair Could there be a workaround before `1.0.0` / #3101 gets around?

**Comment by matmair** [comment]
For sure; one could simply add the importer improvements discussed in the issue and close it. 1.0 is basically a big wishlist that signals that the issue would be nice and a lot of work.
I have in the back of my mind that @SchrodingersGat wanted to tackle it this year but I could be wrong about that.
