### ISSUE TITLE
[FR] Additional actions for 'release' workflow

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3100]
Some additional actions performed in the 'release' workflow would reduce the manual operations required after completing a release version:

### Stable Branch

- Determine if the 'tag' is the 'newest' one (i.e. highest major.minor.patch semver release)
- If so, push current commit to the 'stable' branch (force?)
- Also push the docker image to dockerhub with the 'stable' tag

**Comment by matmair** [comment]
Ref #3078
