### ISSUE TITLE
[FR] Metaparts

### ISSUE THREAD

**Issue by chrissnow** [inventree/InvenTree#3108]
**Is your feature request the result of a bug?**
No

**Problem**
Alternative concept to PartKeepr Metaparts

**Suggested solution**
Having used PartKeepr for a number of years the lack of development and bugfixes is getting a bit problematic.

InvenTree seems to be a much more mature and modern platform but I think lacks one major concept for Electronics which PartKeepr actually does rather well, Metaparts
https://readthedocs.web.cern.ch/display/PARTK/03+-+Meta-Parts

It works really well, because you can use generic parts in projects but real parts which are filtered based on parameters.

InvenTree supports parameters but I don't think the concept of Metaparts, or any similar method?
**Describe alternatives you've considered**
NA
**Examples of other systems**
[Show how other software handles your FR if you have examples.
](https://readthedocs.web.cern.ch/display/PARTK/03+-+Meta-Parts
)
**Do you want to develop this?**
Yes, but I have limited web development experience.

**Comment by SchrodingersGat** [comment]
I believe that the existing concept of "template" parts would fit here. You can have a generic master part that you put in your BOM, and fulfil the requirement with a specific *variant* part 

https://inventree.readthedocs.io/en/latest/part/template/

Does this fit your requirement?

**Comment by chrissnow** [comment]
That may be similar, though would require manually setting up each time a new part is bought? the nice thing about Metaparts is that it's purely based on parameter filters.

For example a 10K 0402 1%
![image](https://user-images.githubusercontent.com/3310276/171290232-2d2df4db-9b3b-4011-8546-4a4b8faef55e.png)

0402 100nF 16V X7R 10%
![image](https://user-images.githubusercontent.com/3310276/171290297-034a8a20-be55-4468-8ea5-b65d94bc2df5.png)
 
![image](https://user-images.githubusercontent.com/3310276/171290592-05e65887-3998-44eb-9e3c-237b6a74bd21.png)

**Comment by matmair** [comment]
@SchrodingersGat from the examples this seems to be a use case for variants?

**Comment by SchrodingersGat** [comment]
@chrissnow ah I see what you mean about specifying parts simply based on parameters. Currently we don't have the framework to support that. There are some roadmap items to improve our parameter functionality (which is currently pretty meagre) but nothing like the full "meta part" concept.

**Comment by SchrodingersGat** [comment]
@chrissnow closing this issue out as stale. Please let us know if you would like to discuss it any further.
