### ISSUE TITLE
[FR] Add table filters to "allocate stock" table in build order

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3109]
Needs some table filters to allow discrimination by:

- Lines which are fully allocated / not fully allocated
- Lines where stock is available / not available

**Comment by SchrodingersGat** [comment]
Duplicate of https://github.com/inventree/InvenTree/issues/4250

**Comment by method1020** [comment]
Sorry if this is the wrong place to ask this. But this looks like it is slated for v0.11.0. Is this accurate?
