### ISSUE TITLE
Incorrect stock allocation when building new part

### ISSUE THREAD

**Issue by palagap** [inventree/InvenTree#3112]
**Describe the bug**

Hi there,

I'm running into an issue in InvenTree - when building a new part / assembly, installing stock items in its BOM ends up clearing the inventory of those parts. The example below, using the InvenTree demo version, illustrates this. 

**Steps to Reproduce**

First, we'll choose to make a widget assembly:

<img width="1694" alt="Screen Shot 2022-06-01 at 10 57 06 AM" src="https://user-images.githubusercontent.com/40808444/171483066-fdc7b87f-e7cc-4876-93f5-3287e2fddd33.png">

The following is its BOM (we'll be focusing on the M3x8 Torx): 

<img width="1683" alt="Screen Shot 2022-06-01 at 10 57 21 AM" src="https://user-images.githubusercontent.com/40808444/171483192-e35fd947-1fc4-4ee4-8799-cb927642e250.png">

We search for the part "Widget Assembly" in the upper right corner, and select it:

<img width="780" alt="Screen Shot 2022-06-01 at 10 57 42 AM" src="https://user-images.githubusercontent.com/40808444/171483287-51c3c4d8-6923-491a-b67a-fc31c380b013.png">

We then create a new stock item for it:

<img width="1695" alt="Screen Shot 2022-06-01 at 10 57 58 AM" src="https://user-images.githubusercontent.com/40808444/171483672-289b6e00-9f52-4128-b312-11861a33be27.png">
<img width="1251" alt="Screen Shot 2022-06-01 at 10 58 19 AM" src="https://user-images.githubusercontent.com/40808444/171483677-7270d1b3-cb3b-4fc2-a630-504bb7547124.png">
<img width="1654" alt="Screen Shot 2022-06-01 at 10 58 36 AM" src="https://user-images.githubusercontent.com/40808444/171483721-8e69f8d9-fc1c-4734-ac3b-b6ddb83beafa.png">

In the installed items tab, we then click the "Install Stock Items" option:

<img width="1914" alt="Screen Shot 2022-06-01 at 10 59 17 AM" src="https://user-images.githubusercontent.com/40808444/171483875-2c5d8ff3-e2e5-43b2-8f4d-c1716a76776c.png">

We select the M3x8 Torx, of which there are 485/560 available. We can confirm the available quantity by opening the part page in a new window:

<img width="1694" alt="Screen Shot 2022-06-01 at 11 00 18 AM" src="https://user-images.githubusercontent.com/40808444/171484126-90ba0002-6a7d-4eff-9b73-22e1688d6eac.png">
<img width="1686" alt="Screen Shot 2022-06-01 at 11 00 50 AM" src="https://user-images.githubusercontent.com/40808444/171484161-26140b8d-44cf-4787-aa75-5ef6d141d3c8.png">

We then install the part:

<img width="1249" alt="Screen Shot 2022-06-01 at 11 00 34 AM" src="https://user-images.githubusercontent.com/40808444/171484218-37c748d5-369e-4853-ba20-0a3b1b68cc44.png">

After reloading the M3x8 Torx page, though, we see that all the stock has been depleted, even though only 5 of the part was required (as seen in the BOM):

<img width="1696" alt="Screen Shot 2022-06-01 at 11 01 03 AM" src="https://user-images.githubusercontent.com/40808444/171484424-23b8ab51-0332-49c6-9cab-ab17d8d31b50.png">

We also see that all the stock of the part is gone in the BOM:

<img width="1667" alt="Screen Shot 2022-06-01 at 11 01 26 AM" src="https://user-images.githubusercontent.com/40808444/171484508-c022a316-33c0-46c0-9f81-424b1a3ea041.png">

**Expected behavior**

Only the amount of the installed item necessary for the assembly should be deducted - not the entire stock of that item. 

**Deployment Method**
- [x] Demo
- [  ] Docker
- [  ] Bare Metal

**Version Information**

[0.8.0 dev]

**Comment by matmair** [comment]
@palagap this is expected from my understanding of your steps.
You are installing the stockitem (containing however much instances of a part) into the assembly - if you want to allocate stock to a build according to the BOM this needs to be done in the allocation tab of the build.

**Comment by SchrodingersGat** [comment]
@palagap yes this is "expected" behaviour - although the steps you are performing are not the intended way to install stock via a build order.

Manual installation of one stock item inside another stock item consumes the entire quantity of that stock item. Manual installation is not intended to be a normal workflow step.

You want to follow the [allocation procedure](https://inventree.readthedocs.io/en/latest/build/allocate/) outlined in the documentation. Here, you allocate stock as part of a build order and it uses the information contained in the Bill of Materials to determine the quantity of each stock item to be installed.

**Comment by palagap** [comment]
Got it, thank you for the clarifications @SchrodingersGat and @matmair.

**Comment by matmair** [comment]
@palagap if you have a suggestion for a short description we should add to the form I would be happy to add it.
