### ISSUE TITLE
[FR] add custom parameters to SupplierPart

### ISSUE THREAD

**Issue by papgrap** [inventree/InvenTree#3153]
**Is your feature request the result of a bug?**
No.

**Problem**
It would be great to have custom parameters on SupplierParts, just like the way they are implemented in Parts and ManufacturerParts.

**Suggested solution**
Using custom parameters on SupplierParts it would be possible to add lead times or cancellation times which are sometimes unique to each part and supplier. These parameters could then be used for further evaluation regarding stock management using plugins.
For example, if the delivery date minus the cancellation time is due, a notification could be generated that there is only one day left if the order needs to be cancelled.

**Describe alternatives you've considered**
It would be possible to use the notes attached to the SupplierPart. But that is not very practical.

**Do you want to develop this?**
I have some experience in python and django but am lacking familiarity with the inventree codebase.

**Comment by matmair** [comment]
@papgrap seems interesting - although I have no need for it as I use metadata to save data for my plugins.
I generally advise ppl. to implement the features they want themself as it can take a while for stuff to get developed if no core-dev is interested in it. If you want to and need pointers feel free to ask.

**Comment by SchrodingersGat** [comment]
@papgrap actually there is work in progress (but, long since stalled) for a "lead_time" field on the SupplierPart model:

https://github.com/inventree/InvenTree/blob/258957c14c371b16578337bb8a440279d4b8fa74/InvenTree/company/models.py#L530

However it needs some attention to implement! 

> I have some experience in python and django but am lacking familiarity with the inventree codebase.

Implementation of a "lead_time" field might be a good introductory exercise. I'd be happy to help point you in the right direction :)

**Comment by smithcv** [comment]
@SchrodingersGat I've been building out our supplier part data and I have some similar lead time and country of origin fields that would be good to have broken out.  It just occurred to me that the metadata JSON may be a good place to put this type data.  The only real negative there is that you have to add a plugin to display the data or format it in a report.

**Comment by SchrodingersGat** [comment]
@smithcv thanks for your feedback. I think this is quite similar to this PR - https://github.com/inventree/InvenTree/issues/9192

Perhaps a general solution would be to allow parameters to be allocated more generally
