### ISSUE TITLE
FR: Reduce tasks

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3157]
At least the task 'style' is redundant with pre-commit. I think we should clean up the tasks and remove everything we do not need to make it easier to keep an overview.

**Comment by matmair** [comment]
@SchrodingersGat what is your opinion regarding this?

**Comment by SchrodingersGat** [comment]
It is worth looking at, it has been quite a while since we assessed this file. We can look at each task and determine whether it is worth keeping.
