### ISSUE TITLE
[BUG] newline characters in the description can break part pages

### ISSUE THREAD

**Issue by papgrap** [inventree/InvenTree#3161]
**Describe the bug**
When importing data via the python api, it is possible to save part descriptions containing newlines.
This causes pages of parts that use a part with a "newline-description" in their bill of materials to break. The page is not fully loaded and doesn't react to any input.
This happened to me because I imported some parts and BOMs from Google Sheets via the python api, where some descriptions contained newline characters.

**Screenshots**
The broken page of the part with the BOM:
![image](https://user-images.githubusercontent.com/68426415/172600709-3b212c9d-3d0d-484c-be37-df81adbd3717.png)
The page of the part that is in the BOM:
![image](https://user-images.githubusercontent.com/68426415/172602712-62565a65-41ef-4e9a-ab36-3ed0bd028196.png)

**Steps to Reproduce**
1. Create two parts (via api or webapp) (Part A and Part B).
2. Set the assembly flag on one part (Part A) and add the other part to the bill of materials (Part B).
3. Change the description of the part which is in the BOM (Part B) via the api to something that contains newline characters.
4. Open the page of Part A. The page should be broken.

**Expected behavior**
Maybe the api should not accept strings that contain newline characters as the description or the BOM panel should ignore newline characters just like the description field in the part page.

**Deployment Method**
- [ ] Docker
- [x] Bare Metal

**Version Information**
0.7.0

**Comment by matmair** [comment]
Can confirm. Needs patches ng in the API validation - I am a bit amazed that this is not triggering already.
Thanks for the report @papgrap !

**Comment by SchrodingersGat** [comment]
This is definitely a concern. Shouldn't the template rendering engine be escaping the newlines, though?
