### ISSUE TITLE
Minimum and Recommended System Requirements

### ISSUE THREAD

**Issue by spectre-ns** [inventree/InvenTree#3165]
I have inventree on AWS and so far it is amazing! It is running a bit on the slow slide though. I'm curious what kind of hardware (Virtual or physical) people are using to power inventree? trying to make sure I'm not doing anything dumb that is making it artificially slow.

**Comment by matmair** [comment]
This does not seem like a feature request or an issue - I am going to close this. If you want to have a general discussion please consider using discussions.

Regarding your question: InvenTree can run on as low as 265 mb of ram and half a vCPU in a usable state. A normal 5€ cloud instance with 500-1000Mb should be enough for up to 5 concurrent users.

Speed really depends on your setup. The main bottleneck is normally either the database system or the worker count. My suggestion would be to use PostgreSQL, set up Redis, enable caching or a CDN for static content, set appropriate caching headers on all media and scale up workers and gunicorn processes as much as the CPU lets you.
Our guides only cover basic setups. Deploying a SaaS level website requires a lot of configuration and is highly dependent on your deployment situation and requirements.

**Comment by matmair** [comment]
Ref #3166
