### ISSUE TITLE
[BUG] Static files take a long time to get from the server

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3169]
Ref: https://github.com/inventree/InvenTree/discussions/3166

Some static files are taking multiple seconds to retrieve from the server, impacting total page load time.

In particular, the bootstrap icons take a while to load, which impacts the page visually.

**Comment by matmair** [comment]
@SchrodingersGat if the caching headers are set right I see no problem here as the files will be reloaded only a few times a year.

**Comment by matmair** [comment]
Static file serving is done in nginx - or whatever the user deploys with. So more a configuration thing. And the server for development is always going to be slow as it is not meant for deployment.

**Comment by SchrodingersGat** [comment]
@matmair the demo server for example is running behind nginx - the config file is here:

https://github.com/inventree/InvenTree/blob/master/docker/production/nginx.prod.conf

I am wondering if there are some optimizations that should be enabled for this configuration?

- https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/
- https://docs.nginx.com/nginx/admin-guide/web-server/compression/
- https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/

Does anything jump out at you with the current nginx conf setup? My limited nginx knowledge certainly could have missed something

![image](https://user-images.githubusercontent.com/10080325/173060366-4f3787a2-c35c-485f-997e-81d40ea9ebca.png)

**Comment by spectre-ns** [comment]
Additionally to this: 

<img width="356" alt="image" src="https://user-images.githubusercontent.com/96780897/173113602-aa29e661-dde5-4601-a961-dab6922e0b14.png">

It takes 6+ seconds to load the initial static page for the part.

**Comment by spectre-ns** [comment]
Additionally, the API call to fill the BOM information takes an eternity as well:

https://{domain}/api/bom/?search=&part=30&ordering=name&include_pricing=true&sub_part_detail=true

<img width="355" alt="image" src="https://user-images.githubusercontent.com/96780897/173114163-43c8bab3-1bad-421d-886b-772fe08bf300.png">

**Comment by matmair** [comment]
Hi there @spectre-ns I appreciate the reports but please keep it one problem per issue.
It is very difficult to make sure everything is resolved when multiple things are covered per issue.

**Comment by spectre-ns** [comment]
Removed comment with API call.

**Comment by matmair** [comment]
@spectre-ns this issue here is specifically about static files (css, icons) - which concerns webserver configs. Feel free to open as many issues as you want. It is easier closing multiple with PRs.

**Comment by spectre-ns** [comment]
@matmair  thanks! :) You guys are awesome maintainers.

**Comment by matmair** [comment]
Thanks! @SchrodingersGat is the maintainer though. I am just very active and owning a few submodules.

**Comment by matmair** [comment]
@spectre-ns no, I am setting up on ubuntu-server bare metal.

**Comment by SchrodingersGat** [comment]
May be docker related, closing out for now unless we come up with something concrete
