### ISSUE TITLE
BUG: Pages render slowly

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3173]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/96780897/173113602-aa29e661-dde5-4601-a961-dab6922e0b14.png">

It takes 6+ seconds to load the initial static page for the part. 
https://{Domain}/part/30/

Part 30 happens to be a part with a 196 item BOM

_Originally posted by @spectre-ns in https://github.com/inventree/InvenTree/issues/3169#issuecomment-1152551180_

**Comment by spectre-ns** [comment]
Thanks @matmair  I guess I was conflating two different problems.

**Comment by matmair** [comment]
No worries. These things are very likely totally unrelated. Them happening together is... not making it better.
