### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [inventree/InvenTree#3186]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@saharshtapi) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by matmair** [comment]
Hi There @JamieSlome / @huntr-helper / @saharshtapi

We have to talk about a policy in the core team first but please shoot me a mail to soc AT mjmair DOT com about the issue. I will share it on backchannel with the rest of the team so we can get a fix out.

@SchrodingersGat thoughts on a security.md ?

**Comment by SchrodingersGat** [comment]
@JamieSlome thanks for reaching out. We will certainly take this seriously. And your suggestion for adding a security policy to the project is well noted :)

**Comment by JamieSlome** [comment]
Hello, @matmair @SchrodingersGat - thanks for your response and diligence 👍

Not sure if you are interested, but you can always point your community toward our platform for your security management, as an example:

https://huntr.dev/repos/inventree/inventree

You can also see the first report here if you sign-up:
https://huntr.dev/bounties/4cae8442-c042-43c2-ad89-6f666eaf3d57/

If signing up is out of the question, let me know and we will just wait for you to create a security e-mail, and we will get the details sent over :)
