### ISSUE TITLE
[BUG] Stock going to 0 when making adjustments

### ISSUE THREAD

**Issue by studious95** [inventree/InvenTree#3192]
Hello, 

My IT team is having an issue with Inventree where any adjustments to stock we make bring the number of said item to 0. We have a Docker Production Server setup, and I have updated the Inventree Database, but that didn't seem to fix the issue. I have a decent amount of knowledge with Docker, but I replaced the person that implemented this is system, so I am at a bit of a loss on how else to troubleshoot this problem. Any suggestions or input would be greatly appreciated.

![IMG_0001](https://user-images.githubusercontent.com/107277531/173399758-6c81b88e-9f6c-4b27-bbce-6ba6120444db.PNG)
![IMG_0002](https://user-images.githubusercontent.com/107277531/173399782-3d9dd8e1-5fef-4711-863f-73b9d2320358.PNG)
![IMG_0003](https://user-images.githubusercontent.com/107277531/173399791-4084432f-8cc0-49bf-8a7c-235c990d4de8.PNG)

**Deployment Method**
- [X] Docker
- [ ] Bare Metal

**Version Information**
0.5.4

**Comment by SchrodingersGat** [comment]
@studious95 this is strange. What version of the app are you running?

**Comment by matmair** [comment]
@studious95 @SchrodingersGat in the original report I see 0.5.4 - that is quite an old version. Is that correct?

**Comment by SchrodingersGat** [comment]
I spotted that too, wondering if the combination of the old software with new app version is the problem here.

**Comment by SchrodingersGat** [comment]
Closing due to lack of response. @studious95 please get back to us if you need further interaction on this.
