### ISSUE TITLE
[BUG] Duplication of "base URL" setting

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3196]
Currently there are two distinct places to set the base URL for the server, and the two values are functionally distinct:

![image](https://user-images.githubusercontent.com/10080325/173743926-45aabbe6-5d53-42cc-ae02-657b67496642.png)

![image](https://user-images.githubusercontent.com/10080325/173743612-19d8c7ad-7d2e-4927-a74b-7f394fe8496c.png)

The second option was added when added support for django-allauth, but did not consider the interplay with the existing setting!

What we should do:

- Remove the custom global parameter `INVENTREE_BASE_URL` in favour of the option provided by django-allauth
- Expose the django-allauth settings to the "settings" page (rather than requiring the user to navigate to the admin section)
- Refactor any existing code that uses `INVENTREE_BASE_URL` to use the domain name setting configured in django-allauth

Ref: https://github.com/inventree/InvenTree/discussions/3195

**Comment by SchrodingersGat** [comment]
@matmair thoughts on this? Feels like this has been an oversight more than anything else.

**Comment by matmair** [comment]
@SchrodingersGat this is not a duplication - you can have multiple domains pointing to the same service and name the sites different names in the interface.

Ex:
https://example.com -> Parts Registry
https://dep1.example.com -> Department 1 Parts Registry

This is the core functionality of the sites framework - this is used for auhtentication, registration, password forgetting.

**Comment by SchrodingersGat** [comment]
I understand that the domain info is crucial - the needless duplication (as I understand it) is the `INVENTREE_BASE_URL` (which is an Inventree specific setting) could be refactored (removed) and we use the allauth setting in its place.

**Comment by matmair** [comment]
@SchrodingersGat that could be more difficult than you might think - if you have two or more domains the behaviour gets a bit trickier to test repetable.

**Comment by SchrodingersGat** [comment]
I have not considered the use case where multiple domains are used. With your perspective what is the purpose of the `INVENTREE_BASE_URL` (separate from the django-allauth values)

**Comment by matmair** [comment]
@SchrodingersGat the 'site' stuff actually is a core part of [django](https://docs.djangoproject.com/en/4.0/ref/contrib/sites/). I am not really sure what the base_url is used for. Maybe for links?

**Comment by SchrodingersGat** [comment]
@matmair here's a crazy thought, for a potential solution here. We currently have the `INVENTREE_BASE_URL` which is used in a bunch of places for generating URL links etc, and the "site domain name" 

We could implement a per-setting "on_save" callback for the InvenTreeSetting class, and then whenever `INVENTREE_BASE_URL` is updated, write the same value to the "site domain name". This means that:

- Domain name is exposed to the existing settings framework
- The two values do not get out of sync
- Users do not have to navigate to the admin site to change this value

**Comment by matmair** [comment]
@SchrodingersGat seems to be error prone. How do you select which site to update? There can be multiples.
The `INVENTREE_BASE_URL` in pratice sets the 'main' url for a project. We could add a link and note to the setting but I would not try to figure out the right `Site` instance. Maybe if we only have one it could work.

**Comment by SchrodingersGat** [comment]
We know which one the "main" site is (by looking at the `SITE_ID` parameter in settings.py).

**Comment by matmair** [comment]
@SchrodingersGat that is not always the case - if there is only 1 for sure. If you have multiple it most often is the first.
