### ISSUE TITLE
Facing issue with installation on docker

### ISSUE THREAD

**Issue by AkshayraviC09YC47** [inventree/InvenTree#3212]
The InvenTree docker image is restarting automatically and not able to install due to this issue
The steps i have done for the setup:
1. Cloned the repo and pulled that to docker using `docker-compose up -d `

<img width="1177" alt="Screenshot 2022-06-16 at 10 12 47 PM" src="https://user-images.githubusercontent.com/58636452/174123833-dd287083-756e-42f0-b755-7859694e9907.png">

**Here is the error log:**
[error1.txt](https://github.com/inventree/InvenTree/files/8920874/error1.txt)
[error2.txt](https://github.com/inventree/InvenTree/files/8920875/error2.txt)

**Comment by AkshayraviC09YC47** [comment]
<img width="1552" alt="Screenshot 2022-06-16 at 10 29 07 PM" src="https://user-images.githubusercontent.com/58636452/174125853-f5b5d048-478e-4f9c-ace1-3fc850d29740.png">

**Comment by SchrodingersGat** [comment]
@AkshayraviC09YC47 you've missed some steps according to the [setup guide](https://inventree.readthedocs.io/en/latest/start/docker_dev/) 

Start here - https://inventree.readthedocs.io/en/latest/start/docker_dev/#perform-initial-setup
