### ISSUE TITLE
[FR] Shopify Integration

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#3216]
**Problem**
Recently we switched from WordPress to Shopify and it would be very helpful to have a plugin that supports this. I know @matmair is working on this, and I'm mostly making this issue to ask him how the development is progressing and if I can help him with this. I'm sorry for this, there is just no direct way to contact him without sending an unsolicited email.

**Describe alternatives you've considered**
I'm about to start writing a plugin that just hourly gets the orders from our store. I don't want to do double work and I might even be able to contribute to a better, fully featured plugin.

**Do you want to develop this?**
Yes, I definitely want to develop this. I would like to know the status of the plugin at this point and I can contribute to this.

**Comment by matmair** [comment]
Hi there @Guusggg I worked.on that a while ago and got a MVP running. My main user switched store backend so I stopped working on it but it should not be missing much.
I will have a look tonight and update to the changed APIs in 0.7.0 .
Please take a look at github.com/matmair/ShopifyIntegrationPlugin and maybe create an issue there with what you expect from the plugin and what workflow you imagine. Shopify supports webhooks so my approach uses them to immediately react to changes on both ends.

**Comment by Guusggg** [comment]
Thank you so much. It's pretty stupid that I didn't think about posting an issue on the actual repo...
