### ISSUE TITLE
Edit Part Properties - Invalid character

### ISSUE THREAD

**Issue by jetholloway** [inventree/InvenTree#322]
A part can be created with a Name that includes the characters: "/,".

But, when editing a part, you cannot submit your changes if the Name includes these characters, even if you didn't edit the Name field.

**Comment by SchrodingersGat** [comment]
From what screen did you create the part? I cannot replicate:

![image](https://user-images.githubusercontent.com/10080325/57667817-683c0e80-7648-11e9-8731-2d43b013fc7d.png)

**Comment by SchrodingersGat** [comment]
This is only an issue for parts created before this feature was introduced. No fix required.
