### ISSUE TITLE
[FR] Update to OpenAPI from CoreAPI

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3226]
DRF has deprecated CoreAPI - move to OpenAPI
https://www.django-rest-framework.org/coreapi/schemas/

**Comment by SchrodingersGat** [comment]
As we are getting pretty close to 0.8.0 I'd like to push any changes to DRF off to the next release - unless there are any pressing changes to update this right now?

**Comment by rcludwick** [comment]
Frankly I prefer drf-spectacular.

**Comment by matmair** [comment]
I have not made a switch in any project yer - only started new ones on OpenAPI or pinned to a lower version.

@rcludwick have you done that before? I do not really care what tooling we use but always prefer the leanest way (a new dependency always exposes you to new multi-dimensional risk).
