### ISSUE TITLE
[FR] Allow to disable Description field when adding new Manufacturer Part

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#3229]
**Problem**
I'd like to keep the company description as part of my manufacturer dataset. However, when adding a new Manufacturer Part the description if long clutters the view a lot.

![image](https://user-images.githubusercontent.com/42826581/174503704-a34c18af-8075-4cf8-9d49-7c7ccf643e09.png)

**Suggested solution**
It would be great if one could simply disable the description in the settings. 

Also, when disabled remove the - which appears behind the manufacturer name to separate the description form the name.

**Describe alternatives you've considered**
Removing the description text altogether

**Do you want to develop this?**
Not at the moment

Version: [0.7.1]

**Comment by matmair** [comment]
Hit there @afkiwers please do not leave placeholder text in the report. I removed it already this time - just for the future.

**Comment by SchrodingersGat** [comment]
Probably a more generic solution would be to truncate long data entries which are displayed in these form fields.
