### ISSUE TITLE
[BUG] Allocated stock is not decreased if build order quantity is reduced

### ISSUE THREAD

**Issue by mattbnz** [inventree/InvenTree#3236]
**Describe the bug**

If you complete a build order which had its quantity reduced after stock was fully allocated, all the allocated stock is removed from inventory, despite only some of it actually being consumed by the build outputs. This leaves your inventory in an incorrect/inconsistent state with more consumed than has actually been used. 

**Steps to Reproduce**

1. Create a new new build order with a quantity greater than 1 (e.g. 2)
2. Fully allocate stock to the build order
3. Create a build output for a single unit
4. Edit the build order to decrease the quantity to 1 (e.g. because you changed your midn on how many to build)
5. Complete the Build Order. 

**Expected behavior**

Only 1 builds worth of inventory should be removed from each component part used in the build. 

**Actual behaviour**

All allocated stock is removed from inventory, even though only half of it was consumed in the build outputs that were actually build.

**Comment by mattbnz** [comment]
I'm playing around with fixing this, options I see are:

1) Attempting to decrease allocated stock at edit time if we see the quantity is decreasing and stock is now over-allocated
2) Modifying the allocation completion logic to only subtract the quantity used in build outputs, rather than the quantity allocated at completion time.
3) both for good measure....

I'm leaning towards option 2, but opinions welcome.

**Comment by SchrodingersGat** [comment]
@mattbnz this is verging on "intended" behaviour, certainly it is "allowed" behaviour. The user is free to complete a build which has over-allocated or under-allocated stock. There are valid examples of both cases, I think. 

There may be any number of reasons that the number of items allocated to a build does not match the simple multiple of the BOM line by the number of output items. This strict requirement has been deliberately relaxed based on feedback from multiple users and in practice allows some flexibility for the build system to be used in a wide variety of situations.

A very simple example would be that 150mm of heat-shrink is required for a build, but 175mm was actually used due to an operator mistake. This should be reflected in the stock consumption against the build order, even if the number of build outputs remains unchanged.

What I would suggest is that we can add a "warning" if line items are "over allocated" and require the user to manually check an "accept overallocated stock" option when completing the build.

**Comment by mattbnz** [comment]
I understand the need to track destroyed/wasted stock consumed during a build, but I think relying on overallocation as the mechaism to do that is a poor/unexpected user experience, not least beacuse of the display issues it causes elsewhere in the progrm (e.g. 11/10 allocated on the part screen, etc), but more generally it feels to me like it's mixing a future oriented concept "allocation" which expresses an intent/possibility, with a defined/concrete outcome that has occurred "consumed" or "wasted", etc. The actual is mixing into the probably in the same concept.

Perhaps a workable approach here would be:
1) Explicitly add the concept of "scrapped" items that can be added to a build order, which would count against the allocation alongside build ouputs such that the allocated == consumed/scrapped sum always zeros. I see this is already contemplated/suggested in #1672.

2) (optionally) You could also add a BOM item property to express that a particular bom item is not consumed in a fixed quantity (like 1 or 2), but as a variable amount, which could have a default in the BOM and then also allow overriding with actual quantity consumed when the build output is completed, etc. 

This would give the flexibility to avoid the "11/10" display and would make more logical sense for things like heatshrink, etc. 

Thoughts?

**Comment by mattbnz** [comment]
Interesting to hear the different perspectives! :)

I definitely see the value in the distinction between "used in a finished output" and "scrapped, useless" - it's interesting to hear that there are finished outputs that would use more components than in the BOM however, that's not a situation I've come across in my experience before. I wonder however if the existing "overage" field in the BOM item should however be used to cover that situation? 

I think the key property I'm looking for is explicitness of where the inventory was consumed, currently you can have a piece of inventory magically disappear into thin air once the build is completed - it's not consumed in a build item, it's not marked as scrapped, the build item allocation is no longer present and so if you come to try and stocktake/audit and you find Inventree reporting less stock than you thought you used, figuring out how/where/why the extra pieces got used is hard (this really happened to me ;p)

That desire for explicitness is why I think the current behaviour of relying on overallocation is a bug...

**Comment by matmair** [comment]
Overage is for waste. Overage describes the amount of parts that are consumed over the allocation without being installed (setup for a PnP for example: some machines just pick passives, check their orientation and then discard them on job start).

What i am talking about is bodging. With a multi-thousand € scientific instrument you will not just grab a new pcb and start over. You will try to find the problem and fix it - maybe by adding a passive somewhere to reduce some unexplainable source of EMI or sneaking current. And that certainly does not warrant a new revision / part in InvenTree.

**Comment by SchrodingersGat** [comment]
> currently you can have a piece of inventory magically disappear into thin air once the build is completed

This is partly what #3012 is intended to address - when you don't allocate each and every stock item to a particular build output, you still know *where* the inventory went, because those items are removed from stock and assigned to the completed build order.

**Comment by SchrodingersGat** [comment]
@mattbnz as part of a solution to this, I have added a warning and confirmation if a build is over-allocated: https://github.com/inventree/InvenTree/pull/3272
