### ISSUE TITLE
[BUG] Traceable stock should require serial or batch

### ISSUE THREAD

**Issue by stijnloeys** [inventree/InvenTree#3247]
**Describe the bug**
A stock item that is tracable should have a batch or serial number, it can not be created without one of these two, but it can be.

**Steps to Reproduce**

1. create a part that is tracable
2. create a stock item without serial or batch number (should not be possible)

**Expected behavior**
prompt to fill in serial or batch number

**Version Information**
0.7.1

**Comment by toastedcrumpets** [comment]
Do you want to rename the issue from "Enter bug description" to "Require StockItems with Tracable=True to have batch or serial numbers"?

**Comment by matmair** [comment]
Hi there @stijnloeys you can enter serial number(s) on the stock creation form or by using the 'serialize' action button on the stock items page or in select table rows or multiselection sections.

They are not enforced as it was proving to be cumbersome when dealing with items that get serialized later in production after a user request.

I am closing this therefore as won't fix. This does however not mean that we do not value your opinion. If you feel this is an error please make a suggestion how users that get in multiple items and serialize them at some later point could be accommodated. I and the maintainer @SchrodingersGat are always glad to get feedback and improve the experience.
