### ISSUE TITLE
[FR] Add custom logo without manually replacing the file

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3257]
**Is your feature request the result of a bug?**

No

**Problem**

It will be nice to have the option to run inventree with organization branding.

**Suggested solution**

In general settings to be able to upload a new logo which will replace the default inventree logo in login screen and main dashboard

**Describe alternatives you've considered**

Replacing the logo manually in static folder

**Comment by matmair** [comment]
This is already available.
https://github.com/inventree/InvenTree/blob/56bbda60b5bfcfcf2758dee1ed8369d033398242/InvenTree/config_template.yaml#L211
