### ISSUE TITLE
How are virtual parts assigned to sales orders?

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3264]
### Discussed in https://github.com/inventree/InvenTree/discussions/3262

<div type='discussions-op-text'>

<sup>Originally posted by **miggland** June 28, 2022</sup>
Hi,

I have added a virtual part to a sales order. It's the only part in the sales order. So far so good.

Before I can complete the order, I need to assign stock - I have no stock yet, so I go the part page ( ... /part/107/), Stock page and click "New Stock item":

![image](https://user-images.githubusercontent.com/1314853/175980441-ec425316-69b0-4723-b569-eece3ea2ee5b.png)

However, when I try to submit I get the following:

![image](https://user-images.githubusercontent.com/1314853/175980504-cdb28c1c-5beb-4271-af1a-24f27d42da0b.png)

So I'm stuck - I have no stock to assign in the sales order, and I can't assign any because of that error message.

Is this a bug, or is this not the intended procedure?</div>

**Comment by SchrodingersGat** [comment]
@miggland the way that virtual parts are currently implemented, they cannot have stock items created against them, and thus should not be able to be assigned to sales orders. That's the first element of the bug here - you should not be able to assign a virtual part to a sales order.

The second part is the `Invalid pk "107" - object does not exist`

The object *does* exist, but it is not a valid choice for creating a StockItem:

https://github.com/inventree/InvenTree/blob/ad57ca5ddfff2a4e4da17dbde4dcf97b644e85e7/InvenTree/stock/models.py#L587

However the error message shown in the form does not correctly reflect this..

The second part of the bug is that the error message should be displaying something sensible!

**Comment by miggland** [comment]
Thanks for the quick reply - and fix.
However, I'm wondering about this:
> That's the first element of the bug here - you should not be able to assign a virtual part to a sales order.

Why not? What's the purpose of virtual parts if I can't sell them? Can I buy them via Purchase Orders?

**Comment by SchrodingersGat** [comment]
You can mark a part as virtual to signal that it is not a "real" physical part which can have stock items. If you need that functionality don't mark the part as virtual.

**Comment by nikolai2111** [comment]
How do I record e.g. software licenses or working hours which I want to charge per sales order? Isn't that the intention of a virtual part?
