### ISSUE TITLE
[BUG] PO Import

### ISSUE THREAD

**Issue by spectre-ns** [inventree/InvenTree#3293]
**Describe the bug**
When I try to import data from a CSV to a PO it complains that 'Fields matching failed' I cannot find a template for the import but it appears to be looking for the following fields: quantity, reference, notes, supplier_sku,  purchase_price, manufacturer_mpn. I would like to be able to import a BOM into a PO when I'm trying to build a particular assembly.

**Steps to Reproduce**
Import a file into the PO importer

**Expected behavior**
Allows matching of fields to columns in the imported data

![image](https://user-images.githubusercontent.com/96780897/177207291-e5fab2a6-482b-411f-ae2d-9260a1e64ab6.png)

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
7.0.0

As always thanks for your amazing open source development efforts!

**Comment by matmair** [comment]
This is a
Duplicate #3098

**Comment by matmair** [comment]
Reference https://github.com/inventree/InvenTree/issues/3101
