### ISSUE TITLE
[FR] RMA/ Repair Order function

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#3298]
**Is your feature request the result of a bug?**
No

**Problem**
When a faulty PCB/Device is returned it would be nice to have something like the build order interface which would automatically create an RMA number. At the moment if parts are used for the repair, one has to take them out individually or use a BO for that.

**Suggested solution**
Let's call it RO for now. The RO should link to the serial number of the PCB if available. It should offer an interface where the user can select the parts for that corresponding BOM to replace broken ones if needed. I would imagine a search box for designators or so. The search results should then be addable via click or drag&drop to a list/table below. Then there should be a QYT field which should offer the possibility to add more than just the one part in case parts were lost during the process.

Then a button click would remove those parts automatically. Additionally, after the repair, the RMA could also link to the new commissioning data. Which would have to be done to make sure the device is working properly. Once every box has been ticked, it could initiate a new 'free of charge' sales or or so the get it shipped back to the customer.

This way an RMA would be nicely tracked and linked to the original unit, parts would be removed automatically, new commissioning results are directly linked with the RMA and could be compared to original ones but would still be separated nicely, a new sales order is created only when the RMA is completely done and every box has been ticked.

**Describe alternatives you've considered**
BO which is a bit hacky

**Examples of other systems**
Don't have any

**Do you want to develop this?**
Not a the moment

**Comment by SchrodingersGat** [comment]
There are a couple of separate features here, I think, which should be separated

### RMA

- Items are returned from a customer
- Single or multiple items can be returned
- Shipping numbers, etc
- Somewhat like a "sales order" except inverse
- Each item can have a status e.g. "repaired" "replaced" "scrapped" 

### Repair

This part is much more complicated, and may be a bit too "custom" to be implemented well. This might track parts which are removed, repaired, replaced, etc. 

This can currently be done manually (kind of) with manual stock operations but is cumbersome.

---------------

Of these two, the **RMA** concept is something I would put more effort into.

**Comment by matmair** [comment]
Seems to be an involved project. @SchrodingersGat maybe a more abstract kind of order could be the base for SO BO RO and whatever comes after that? Both in back and front end.

Regarding repair: @afkiwers are you aware of https://github.com/inventree/InvenTree/issues/2817 ? Processes as suggested there might be helpful for custom workflows.

**Comment by afkiwers** [comment]
@matmair yes I saw that but that wouldn't really offer a BOM where one could pick replaced parts etc and link everything against an RMA.

Having that kind of linkage could result in automatically generated reports which could indicate issues with chosen parts etc; e.g. a TVS diode user in the input voltage protection circuitry which is around 70V but really should have been selected to be around 90V.

Cheers

**Comment by matmair** [comment]
@afkiwers I can see the appeal.
Implementing this with API endpoints, full coverage and in a performant way will / would be a lot of work and we have literally 100 open requests right now. Not sure how fast this will be tackled without a dev needing it for themself / their work.

**Comment by afkiwers** [comment]
@matmair I do understand. I ran into this issue a few times already and thought it's worth mentioning it here.

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by SchrodingersGat** [comment]
Not stale
