### ISSUE TITLE
[FR] Create more than one location at a time

### ISSUE THREAD

**Issue by joaoferreira-git** [inventree/InvenTree#3302]
**Is your feature request the result of a bug?**
No

**Problem**
I have a couple of [storage drawers](https://miro.medium.com/max/1400/1*gQyH5CAlsKK306UaqfabXw.png) for electronic parts and it takes a lot of time to create 32 location for each storage. 
This is just one of the [storage drawers](https://prnt.sc/xdeLrunBwxCp)

**Suggested solution**
Not really sure how to implent this but this is my thinking below.
Im not sure if it's even possible to do but something that would allow to create for example 4 drawers with a naming like this: 
'Drawer - A1'

We would just need to tell it to make 4 locations and starting with: Drawer - A1 > Drawer - A4 

**Describe alternatives you've considered**
Nothing comes to mind

**Examples of other systems**
Not sure if any do this.

**Do you want to develop this?**
Almost sure i wont be able since i barely know how to code, but if you point me to the right docs and code examples i might be able to try.

**Comment by matmair** [comment]
This would be a great small plugin.
We are already working on a pattern matching feature and have something similar to this with serial numbers. Maybe this could reuse these feature @SchrodingersGat ?
Not sure how important/used this feature is/would be.

**Comment by luwol03** [comment]
Just for reference. Sorry, haven't seen that issue at the time I created my one #3366

**Comment by matmair** [comment]
@SchrodingersGat should we close this one too?

**Comment by SchrodingersGat** [comment]
@joaoferreira-git closing this out, it would make sense to implement this as a plugin. Please let us know if you need any further information!
