### ISSUE TITLE
[FR] Login Rate Limiting

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3305]
It might be worth investigating login rate limiting?

e.g. [django-defender](https://github.com/jazzband/django-defender)

**Comment by nwns** [comment]
That seems like it would be prudent.  We should make sure that this protection is extended to the api as well.

**Comment by matmair** [comment]
This package seems to require Redis. Maybe we should find something that works without it as it makes bare metal deployments a lot harder @SchrodingersGat .
I use nginx for limiting, maybe we should just put that into the docs.

**Comment by nwns** [comment]
Doesn't Inventree need Redis already for the background task system?

**Comment by matmair** [comment]
@nwns actually not. Redis is a very new addition and only used as a general and database cache. Tasks are database based and use whatever backend is provided.

**Comment by matmair** [comment]
Traditional architecture would be to use Redis or RabbitMQ for that. You can deploy InvenTree with python and SQLite (should be already there) as only dependencies on standard Debian (although it is really not encouraged).

**Comment by matmair** [comment]
@SchrodingersGat I did some research and I think [django-axes](https://github.com/jazzband/django-axes) could be a better fit. It works either a database or cache-based backend.

**Comment by SchrodingersGat** [comment]
Might be worth adding is as a user-configurable integration

**Comment by matmair** [comment]
@SchrodingersGat I tested multiple Django solutions for this - it proved very problematic in production. This should be handled through the proxy IMHO.

**Comment by SchrodingersGat** [comment]
@matmair fair enough, I am happy to close this one then.
