### ISSUE TITLE
[FR] Negative amounts in order

### ISSUE THREAD

**Issue by markusEmm123** [inventree/InvenTree#3306]
**Problem**
I can't enter lines with a negative sum in the "additional lines" of a purchaes order.
When creating purchase orders I can't copy the contents of an invoice if there e.g. is a discount included.

**Suggested solution**
Allow negative values as price (at least for additional lines).

**Describe alternatives you've considered**
Leave out the "discount" positions of the invoice and control manually with a calculator as the sums (between inventree and the original invoice) don't add up anymore.

**Examples of other systems**
E.G. excel allows negative numbers.

**Do you want to develop this?**
Unfortunately my understanding of the underlying programs are not deep enough to implement that myself.

**Comment by SchrodingersGat** [comment]
@markusEmm123 closed in https://github.com/inventree/InvenTree/pull/3311
