### ISSUE TITLE
[FR] Emailed reports

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#3317]
**Is your feature request the result of a bug?**
No?

**Problem**
As discussed in the #3304 accountants need to know how much stock is in inventory at a specific time.  In principle Inventree records enough information to back calculate this but there are potential pitfalls as discussed in 3304.

**Suggested solution**
For my situation, emailing the current inventory on the first of every month would solve this issue going forward because there would be a backup of the state of the stock in inventory separate from Inventree and since this report could be archived (by Inventree directly or by the email recipient separately) we don't need to worry about keeping a backup of Inventree's database for years.

Required Fields for each stock item
* Part Name (`item.part.full_name`)
* Quantity
* Purchase Order Number
* Batch Number
* Serial Number (if serialized)
* Location (the full location path, not just the assigned location name, as every set of bins has a 'B3')
* Item Cost per Quantity
* Total Cost (Quantity * Cost per Quanity).  Not strictly necessary is it is easy enough to multiply two columns in a spreadsheet but it was requested as a Quality of Life thing.

**Describe alternatives you've considered**
Using the download as spreadsheet functionality of the stock page is a partial solution.  It is is missing a few useful columns which can be fixed, but more importantly this doesn't happen automatically.  The beginning of the month is very busy for my organisation (and I imagine for most) so this would likely get forgotten at somepoint and then we are back to trying to figure it out by working backwards through Inventree and hoping that Inventree has not removed something important.

Also, the download as spreadsheet functionality seems to be more for backup or sync with other systems with all of the ids it includes and less as a report.

**Examples of other systems**
I don't have a specific example of this.

**Do you want to develop this?**
Possibly.

I think ideally this would be manifested as scheduled emailed reports, as a spreadsheet (as .xls/.xlsx, because Accountants), emailed to the address of a list or group of users in the Inventree database.  I would like to see it as a first party plugin, if only because it makes a nice, generally useful example plugin.

I see that the plugin system can do scheduled tasks, though it is unclear to me if emailing from plugins is supported or if the reporting system can create spreadsheets rather than pdfs.

**Comment by nwns** [comment]
Another unrelated report would be to email a specific person a list of Sales Orders closed in the previous day.  Though I am thinking this might be better handled by integrating the Inventree with the accounting package.

**Comment by SchrodingersGat** [comment]
I agree that this would make sense to develop as a plugin, as the requirements may vary from one company to the next.

> I see that the plugin system can do scheduled tasks, though it is unclear to me if emailing from plugins is supported

Yep, emails can be sent from the plugin interface

> if the reporting system can create spreadsheets rather than pdfs.

Stock reports can already be generated as spreadsheets, it would be trivial to make this happen periodically

**Comment by SchrodingersGat** [comment]
Ref: https://github.com/inventree/InvenTree/issues/1694

**Comment by SchrodingersGat** [comment]
@nwns after some further thought on this, I have an exciting idea about how I would implement this. However with all the other work to do, this could take some time before it receives any attention. If you would like to see some effort on this sooner, perhaps your company would consider [sponsoring](https://github.com/sponsors/inventree) this feature?

**Comment by nwns** [comment]
@SchrodingersGat We would consider sponsoring a feature, though of course it depends on the details.

#1694 looks like a start but doesn't cover this feature request as written.

If you like, I can reach out to you, we can continue this discussion offline.

**Comment by SchrodingersGat** [comment]
@nwns #1694 is only a starting point, I have some bold ideas which extend upon your requirements as outlined here. Please reach out and we'll see what we can do!

**Comment by matmair** [comment]
I see 2 connected requests here:
1. A template to get a full inventory rundown report
2. The possibility to schedule report calculation and delivery via <Notification channel>

@SchrodingersGat @nwns maybe it makes sense to split this into two separate FRs - what do you think?

**Comment by SchrodingersGat** [comment]
@matmair yes I think the scope of this has expanded somewhat, where 2 separate FRs would make sense

**Comment by SchrodingersGat** [comment]
@nwns please note that this has now been implemented in https://github.com/inventree/InvenTree/pull/4345 :)
