### ISSUE TITLE
[FR] Add export for part price from supplier

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3321]
**Is your feature request the result of a bug?**

Not sure

**Problem**

When exporting a BOM and asking to include supplier information, there is no price in the exported BOM.

**Suggested solution**

Good behavior will be that the price according to the quantity in the BOM will be included to show how much it costs to produce the batch in one single piece.

**Describe alternatives you've considered**

Creating a python script that will export BOM according to my demands.

**Comment by SchrodingersGat** [comment]
@Zontex a custom python script might be the best approach *for now*.

There are currently a *lot* of outstanding issues with the way we handle pricing information. After next major release (`0.8.0`) I am going to start work on a major overhaul for the pricing system. Until then, I won't be making or accepting any major changes to how pricing is currently handled.
