### ISSUE TITLE
[BUG] After part price updated, BOM sort by price order shows old order

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3326]
**Describe the bug**

I manually updated the component price and then went back to the BOM of the part and set to order by price (from the most expensive one to the cheapest one) but still, the position of the component was the old position even tho it's the most expensive component in the list.

**Steps to Reproduce**

1. Go to parts
2. Click on the bill of materials
3. Click on "supplier cost" to sort based on supplier cost
4. Go to one of the parts (not the first one) in the list
5. Change the component price to be more expensive than other components in the list
6. Go back to the bill of materials and repeat step 3 to see that it's still in the same position.

**Expected behavior**

The most expensive component should be in first place in the list, according to the updated pricing.

**Screenshots**

<img width="571" alt="Screen Shot 2022-07-14 at 13 57 02" src="https://user-images.githubusercontent.com/19342533/178967634-b07115a1-e7ef-4d7d-8081-6f6bde5356f8.png">

**Deployment Method**
- [ ] Docker
- [x] Bare Metal

**Version Information**

inventree version: 3.10.4
django version:  3.2.14

**Comment by SchrodingersGat** [comment]
@Zontex I am unable to reproduce this with a trivial example... Which version of InvenTree are you running? `3.10.4` is not a valid InvenTree version number

**Comment by Zontex** [comment]
@SchrodingersGat Sorry my bad:

version: 0.8.0 dev
commit hash: 67732f8f8
commit date: 2022-07-11

**Comment by Zontex** [comment]
<img width="166" alt="Screen Shot 2022-07-14 at 23 43 43" src="https://user-images.githubusercontent.com/19342533/179080133-bb57510a-a789-4a43-bbad-c5fa87c641da.png">

Just lowered to stable branch 0.7.4 and still see the issue, if you look at the screenshot the issue is with the table not showing from the highest price to the lowest although using the filtering function.

**Comment by SchrodingersGat** [comment]
@Zontex looks like it is using string sorting rather than numerical (natural) sorting!
