### ISSUE TITLE
[FR] :checkered_flag: Add last updated column for supplier parts

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3327]
**Is your feature request the result of a bug?**

No

**Problem**

Some supplier links are constantly updated, need to replace the old link with the new link and/or add a new price for the component. if can go to the supplier parts page and see when each part was last updated it will give an indication over which parts need to be checked and when especially in a process of mass updating components if I lose track I have no idea to know which I already updated and which not.

<img width="1542" alt="Screen Shot 2022-07-14 at 14 22 35" src="https://user-images.githubusercontent.com/19342533/178972093-655cf3d0-a5be-488e-b5bd-e615750c8937.png">

**Suggested solution**

Add a last-updated column, I believe this kind of last-updated already exists in some inventory datasets inside the data for things like pricing, etc ...

**Describe alternatives you've considered**

No automated alternative for it using scripting as I see.

**Comment by matmair** [comment]
@Zontex metadata could be added with a script / plugin to achieve this.
Would you be willing to submit this to core?

**Comment by SchrodingersGat** [comment]
Adding an "updated_on" field to the `SupplierPart` table would be trivial, however this would only cover the fields in the model itself. Pricing data is stored in the `SupplierPriceBreak` table and would not be covered by this simple addition. Might need some more thought than this

**Comment by matmair** [comment]
Not stale

**Comment by Zontex** [comment]
Not stale

**Comment by matmair** [comment]
@Zontex this should be fixed by #4214 - do you mind checking if this covers your request?

**Comment by Zontex** [comment]
@matmair yes looks perfect, shall we close this issue?

**Comment by matmair** [comment]
@Zontex great to hear! I war not sure if there was context discussed I forgot - therefore I tagged you. The issue should close automatically once the PR is merged.
