### ISSUE TITLE
[BUG] Sorting issues in Part BOM when non-latin chars are in part names

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#3330]
**Describe the bug**
Sorting by part name in BOM table is wrong when non-latin (cyrillic) chars are used in part name.
At the same time sorting works correctly in Parts table.

**Steps to Reproduce**
1. Create parts with cyrillic names: К555ЛН1, К157УД2, К555ТМ7
2. Create assembly
3. Add parts to BOM
4. Check sorting by part name

**Expected behavior**
Sorting according to alphabet:
![изображение](https://user-images.githubusercontent.com/10057327/179025205-48597189-de74-401d-9797-8c76003f15d2.png)

**Actual behavior**
![изображение](https://user-images.githubusercontent.com/10057327/179024279-f800d079-d678-4d4e-8229-5892c3694cf0.png)

**Deployment Method**
- [*] Bare Metal

**Version Information**
InvenTree-Version: 0.7.3
Django Version: 3.2.13
Commit Hash: b9c6cd70d
Commit Date: 2022-06-16
Database: mysql
Debug-Mode: True
Deployed using Docker: False

Also tested on demo instance with the same results:
https://demo.inventree.org/part/846/

**Comment by SchrodingersGat** [comment]
@sintech this looks to be specific to the BOM table. This table is "sorted" on the client side, not by the server, so this might be why it is showing differently with cyrillic characters

**Comment by sintech** [comment]
I have tested it using the same version of bootstrap-table (1.18.3) without any issues at least on this trivial example.
https://live.bootstrap-table.com/code/sintech/12190
@SchrodingersGat have you modified somehow sorting algorithm for BT?

**Comment by SchrodingersGat** [comment]
@sintech I think I have worked it out, it's very silly.

![image](https://user-images.githubusercontent.com/10080325/181202547-a5bc427d-21b7-4cba-9c80-0a2876c8f558.png)

The "part" column in the BOM table is actually sorting by the ID (PK) of the part, *not* the name at all...

Should be a very simple fix, much simpler than diagnosing the issue!

**Comment by sintech** [comment]
@SchrodingersGat, great, thank you for your time.
