### ISSUE TITLE
[FR] Finding/creating supplier parts during PO Add Line Item

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#3331]
**Is your feature request the result of a bug?**
No.

**Problem**
In the add line item search on a PO, it only finds a part if there is already a supplier part for this part.  This then means, you need to cancel adding the line item, search for the part number, create the part if needed, create the supplier part, navigate back to the PO, click Add Line Item, search for the part and then add it.

**Suggested solution**
In the add line item search, all parts and supplier parts of all suppliers that match the search string should be shown.  Current supplier parts first, followed by items of other suppliers, followed by items that do not have a supplier, finally a link to the create part dialog.  Items that are missing a supplier part for the current supplier should a link/button that allows you to create the supplier item right from the Add Line Item dialog.

The opened dialog for the part should copy whatever the user has entered into the child dialog box and then should copy back the link to the correct item.

#3261 should be able to add searching the suppliers api for the search string and present the results in the same dropdown but allow creating the supplier part directly and/or the entire part.  Searching all Suppliers with an api would not likely be useful as we are creating a line item on a PO for a specific supplier.

**Describe alternatives you've considered**
Our suppliers do not have digital catalogues for their parts, and if they do have a website for searching parts, they do not have an api. As well most of the parts that a specific company carries are not relevant to us so loading the catalogue would not be very helpful in most cases.

**Examples of other systems**
The add part dialog can add a single part, though this would probably be better as another modal coming up over top of the Add Line Item dialog rather than being tacked on to the end of the existing dialog.

**Do you want to develop this?**
I could.  I am not sure how much the current system supports the sort of behaviour we are looking for, in particular layering having child dialogs.  I don't know how easy it would be to reuse the existing dialogs for the child dialogs.

**Comment by matmair** [comment]
@nwns my suggestion would be to consider performance of the search field. Adding all the suggested options could make autocompleting slow so please keep that in mind.

**Comment by SchrodingersGat** [comment]
@nwns adding secondary dialogs is currently possible with the current forms implementation, maybe this would get you most of the way there? I am not sure I follow your suggestions here 100% but certainly a decent part of it can be achieved with what is already in place.

**Comment by nwns** [comment]
Yeah, performance could be an issue, but I think the end users would much appreciate the timesaved by not having to go through the problem process manually.  Also, I think if this is implemented, it would be handled by the UI sending multiple requests rather than waiting for a single api call to return with all the results.

Yeah, just adding to the wishlist for 3261.  It would be a useful feature of an api assuming the supplier and/or supplier integration implements it.

@SchrodingersGat I will have to look into it then.  I did not get the impression that the current dialog system could load dialogs that were not sent as part of the page.

**Comment by matmair** [comment]
@nwns you can attach button callbacks to fields (most modals are actually build on the fly with API requests) which will then create a new modal that pops over.

Regarding performance I would prefer if the stock interaction and API is not changed as the performance there is acceptable. Maybe a new button in that fieldset would be good? That button could load a new modal where all the searching and adding takes place.

**Comment by nwns** [comment]
Personally, I think any performance issues should be solved by optimizing the database schema to fix the performance issues as they come up.

However, @matmair would you be more open to the part search having a link/button at the bottom of the autocomplete list that either changes filtering rules to the proposed or opens a modal to do the proposed searches? Because the end user's problem is primarily the round about and error prone process for finding/creating the parts and/or supplier parts.  This way any potential performance issues are out of any of the happy path.

**Comment by SchrodingersGat** [comment]
@nwns my overview is that *most* of what you want here could be achieved by adding a link to open a secondary modal dialog:

![image](https://user-images.githubusercontent.com/10080325/179442145-fb180c8f-b0f8-480d-8197-ddbd413bc134.png)

You can then create a new supplier part "in line" and it will be back-filled into the first form after being created. That is all achievable using the current tech stack.

However adding in external API / plugins / etc is far outside the scope of this for now. We are currently discussing the future of [supplier integration](https://github.com/inventree/InvenTree/issues/3261) via plugins but that is way down the line.

If you are happy with the approach I have "sketched" above that can be implemented reasonably quickly.

**Comment by nwns** [comment]
@matmair Honestly, my users don't care about the autocomplete being fast.  They generally are not even looking at the screen while typing in the part number, so as long as the autocomplete responds by the time they look back up it will be fine.

**Comment by matmair** [comment]
@nwns it is good for you if your users have low expectations. I and my user base get annoyed by lagging autocomplete as it makes data entry slow.
