### ISSUE TITLE
[FR] Merging duplicate parts

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#3332]
**Is your feature request the result of a bug?**
No

**Problem**
Because of limitations of the various searches or the existing part not having a specific keyword it was missed and a duplicate of the item was created.  Once this duplicate is found, the admin needs to edit the models of the part to merge the parts and histories together or the user need to reenter everything under the correct part.

**Suggested solution**
A dialog (that is possibly on the admin site so that an admin or a user with a specific staff permission) can compare the parts and pick which fields are copied over and which are merged together.

Not sure if the end result would be a completely new part that is the amalgam of both (or more) other parts and the source parts are disabled or one of the parts is kept and the others are disabled.

The advantage of the new part would be this merge could be undone assuming sufficient tracking of which stock items were merged from where.

**Describe alternatives you've considered**
Alternatives are manual rework or database fiddling.

**Examples of other systems**
The first thing that comes to mind for me is source control and conflicting changes to a file.  Google Contacts contact merger does more or less as described above.

**Do you want to develop this?**
Since we don't duplicate parts that often, I don't know how soon I would work on it, but I think it is a fairly straight forward implementation (especially on the admin site) once how it is to behave is nailed down.

**Comment by SchrodingersGat** [comment]
@nwns I have run into this problem myself, and have a python script which I run to solve it manually. The issue is becomes complex when the duplicate parts have stock items, supplier data, bill of materials etc etc. 

I think that the way to "solve" this is to pick which part remains (A) and which part will be deleted (B). Find every reference to part B and update to point to A. Example stock items, purchase orders, etc etc. Then delete B. 

Merging conflicting fields is probably too difficult. Maybe present the conflicts to the user and they have to choose. 

This is obviously not an everyday operation and any change would be permanent.

**Comment by matmair** [comment]
Interesting suggestion @nwns .
@SchrodingersGat I see a potential problem with serialized stock: numbers must be unique. Also template data could present problems. A PR should definitely contain unit tests for these edge cases.

**Comment by SchrodingersGat** [comment]
@matmair good point. Any merging system must check for conflicts before applying any changes, and probably just fail (loudly) if it cannot apply a clean merge.

**Comment by matmair** [comment]
@SchrodingersGat maybe we can use the serialized representation of parts to make a simple diff? Would reduce the effort needed to add merging to other parts of the ecosystem and be easier to handle. JSON diffs should be somewhat solved judging by the popularity of the format.

**Comment by Zontex** [comment]
@matmair @SchrodingersGat for me personally I defined the IPN to be unique and I use a way to remember how I name them for example for resistors it would be something like R-120K-1-0603-S and if I keep following this way to add components I will sometimes get "duplicate" error if added twice so I know I must have missed it during the search.
