### ISSUE TITLE
[BUG] Permission issues with docker setup

### ISSUE THREAD

**Issue by G-Pereira** [inventree/InvenTree#3337]
**Describe the bug**
Permissions errors while setting up the server with Docker in production.

**Steps to Reproduce**

- Copy the files from ```docker/production``` (either from the master branch or the stable branch, same result)
- Rename ```index.env``` to ```.env```
- On the env file uncomment and set the following variables:
  - INVENTREE_EXT_VOLUME
  - INVENTREE_ADMIN_USER
  - INVENTREE_ADMIN_PASSWORD
  - INVENTREE_ADMIN_EMAIL
  - INVENTREE_DB_USER
  - INVENTREE_DB_PASSWORD
- run ```docker-compose run inventree-server invoke update```

**Output**
```bash
[+] Running 0/1
 ⠹ Container inventree-db  Creating                                                                                                                                    0.3s
Error response from daemon: failed to mount local volume: mount ./inventree-data:/var/lib/docker/volumes/inventree-production_inventree_data/_data, flags: 0x1000: no such file or directory
```

**Expected behavior**
The initial configuration of the server would be successful and the server would be running

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
```stable``` docker tag

**Comment by SchrodingersGat** [comment]
Looks like there is some pathing issue with the data volume. Can you share the (non sensitive) portions of your `.env` and `docker-compose.yml` files which relate to the volume paths?

**Comment by G-Pereira** [comment]
Thank you for your help @SchrodingersGat ! 
```
INVENTREE_EXT_VOLUME=/home/gpereira/Documents/boxing/inventree/inventree-data
```
The inventree-data folder is being created automatically along with the database files inside it. It is only the folders related to InvenTree docker image that are failing.

The ```docker-compose.yml``` was not touched

**Comment by SchrodingersGat** [comment]
What version of `docker-compose` are you running?

**Comment by G-Pereira** [comment]
Tried with:
```
Docker Compose version 2.6.1
```
and
```
Docker Compose version 2.5.0
```

**Comment by G-Pereira** [comment]
I've cleaned again my environment, purged volumes, removed containers and it worked. Not sure what I did differently but it now works. Feel free to close this if you can't recreate the issues on your side

**Comment by matmair** [comment]
@G-Pereira I can not reproduce this? Did you move the folders or touch any upstream folders by any chance? I strongly believe this to be a simple permission error.

**Comment by G-Pereira** [comment]
No I haven't, I've move the three configuration files out of the repository directory and then used the image from Docker Hub. Well the issue went away so I am closing this. Thank you both for your help!

**Comment by SchrodingersGat** [comment]
> I've cleaned again my environment, purged volumes, removed containers and it worked. Not sure what I did differently but it now works. Feel free to close this if you can't recreate the issues on your side

Might have been some cached volume settings which were causing the issue. I've had some weird problems with mounted volumes before which seem to require a full purge to fix. 

Glad you got it sorted :)

**Comment by G-Pereira** [comment]
Got this issue again in another installation. It turned out to be starting with a wrong value on `INVENTREE_EXT_VOLUME`, and to change it one must run the following command before running again `invoke update`:
```
docker volume -d inventree-production_inventree_data
```

**Comment by matmair** [comment]
@G-Pereira thanks for the hint. Pointed out that makes a lot of sense. @SchrodingersGat could that be part of some of the other problems we had with docker recently and should we add that to the docs?

**Comment by SchrodingersGat** [comment]
We have certainly seen a few issues related to docker volumes not being cleaned out properly. Would be well worth adding to the docs
