### ISSUE TITLE
[BUG] Validate BOM warning stays after pressing "validate" on the one component that changed

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3342]
**Describe the bug**

I found out my part name was wrong and I changed it, due to that, the BOM asked me to validate the part. there was the little "V" icon next to the part to validate it, I pressed it, but the warning "The BOM for XXX | 1 has changed, and must be validated." keep persisting. 

The way to remove this warning was to press "Validate entire Bill of Materials" on the settings of the BOM.

**Steps to Reproduce**

1. Go to an existing part BOM
2. Select one part and change the name
3. Head back to the part BOM
4. You will notice a "BOM needs validation" warning due to the change
5. Press the "V" icon next to the component with the name change to validate it.
6. Notice that the warning stays. even after refreshing the page.
7. To remove the warning, go to the settings tab and validate the entire BOM.

**Expected behavior**

Once no more components to validate (those required validations have been validated) the warning will be gone.

**Deployment Method**
- [ ] Docker
- [X] Bare Metal

**Version Information**

Latest stable branch

**Comment by matmair** [comment]
Hi there @Zontex could you please add a valid version number or commit hash? It is hard to pin issues and do backports without that

**Comment by Zontex** [comment]
> Hi there @Zontex could you please add a valid version number or commit hash? It is hard to pin issues and do backports without that

Yup sorry about that:

# Version Information:
InvenTree-Version: 0.7.4
Django Version: 3.2.13
Commit Hash: 674d0f0e8
Commit Date: 2022-07-14
Database: mysql
Debug-Mode: False
Deployed using Docker: False

**Comment by SchrodingersGat** [comment]
@Zontex I think this makes sense, at least with what the current implementation does. 

Currently each line item can be individually validated, but the entire BOM needs to be validated also. Even if each individual line is valid, the overall BOM might be invalid (what if there are missing lines, etc)?

This workflow was developed entirely for my requirements and so it might be not the best approach. Happy to take suggestions!

**Comment by Zontex** [comment]
> @Zontex I think this makes sense, at least with what the current implementation does.
> 
> Currently each line item can be individually validated, but the entire BOM needs to be validated also. Even if each individual line is valid, the overall BOM might be invalid (what if there are missing lines, etc)?
> 
> This workflow was developed entirely for my requirements and so it might be not the best approach. Happy to take suggestions!

The issue comes when the entire BOM was already validated, then change one part name, the BOM goes invalidated and validating that particular component doesn't help and need to press validate entire BOM again.

If this is by design, then we can close this issue, it's not critical just thought its might be a bug :) your design makes sense as well!

**Comment by SchrodingersGat** [comment]
It is by design, it is very conservative to ensure that any changes to the BOM are flagged
