### ISSUE TITLE
[BUG] Searching Purchase Orders Always Results in No Results

### ISSUE THREAD

**Issue by spectre-ns** [inventree/InvenTree#3352]
**Describe the bug**
All searches in purchases orders result no items found

**Steps to Reproduce**
Search a string in a purchase order

**Expected behavior**
Searching a part number on the PO should result in that part number being returned

**Screenshots**
See U6 designator is present:
![image](https://user-images.githubusercontent.com/96780897/179513351-5e907cba-a8ad-45a2-85b5-fb69f7c681e8.png)

After searching U6:
![image](https://user-images.githubusercontent.com/96780897/179513460-30345227-b42d-48a7-8ebd-ffe4a3d673b1.png)

**Deployment Method**
- [x ] Docker
- [ ] Bare Metal

**Version Information**
0.7.0

**Comment by matmair** [comment]
Hi there @spectre-ns 
If there is no reason for running 0.7.0 I would strongly suggest to updated to the latest patch 0.7.5 and then try again before we start debugging. This might already be fixed.

**Comment by spectre-ns** [comment]
@matmair apologies. is there an automated email for new updates through github I can track by chance? You guys are working through updates fast.

**Comment by matmair** [comment]
@spectre-ns no problem. You can
a) Watch for releases on github with starting the repo or using activation 'Watch' and 'Releases' (on the upper right corner
b) InvenTree regularly checks for new releases and adds an info-marker on the upper right corner

**Comment by spectre-ns** [comment]
@matmair the problem persists on 0.7.5 and is reproducible on the demo server.

![image](https://user-images.githubusercontent.com/96780897/179583129-f52bf625-aa0e-4f19-9cec-f0c18ee1f491.png)

I should be able to search the part number... Right?

![image](https://user-images.githubusercontent.com/96780897/179583230-655cd27b-bfe2-4f89-8936-f8ea04e4408b.png)

PO00003 on the demo server.

**Comment by spectre-ns** [comment]
Thanks @SchrodingersGat that was quick.
