### ISSUE TITLE
[FR] Update 2FA library

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3359]
django-allauth-2fa have recently [added configurable redirect URLs](https://github.com/valohai/django-allauth-2fa/issues/142) - will be available in the 1.0 release

Once the 1.0 release is out, we should update and remove our custom view code.

**Comment by matmair** [comment]
@SchrodingersGat this will remove the need for a bunch of code, great news!

**Comment by matmair** [comment]
@SchrodingersGat should we just fork and release to PyPI like brother_ql to update now? Not sure when they will update.
Looking at https://github.com/valohai/django-allauth-2fa/issues/133 and https://github.com/valohai/django-allauth-2fa/issues/119 I am not sure if it is really maintained anymore.

**Comment by SchrodingersGat** [comment]
I think if we have to add any further custom code, it would be worth it. At the moment our custom views are pretty "stable"?

**Comment by matmair** [comment]
still waiting for a relase

**Comment by SchrodingersGat** [comment]
@matmair sorry somehow I did not get notified of this one (or missed the notification). Are there any alternative packages which would drop-in for django-allauth-2fa?

**Comment by matmair** [comment]
Not without a bunch of work. There are some issues like token management, passkey, passwordless & magic link login etc. that would be easier with a custom user, groups and security stack.
In general, I would love to work on something like this as I reimplement the same things in all of my applications but I value #2789 #4826 #2817 higher rn

**Comment by SchrodingersGat** [comment]
Fair enough, we'll leave this one hanging for now
