### ISSUE TITLE
[FR]Using product images in labels

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#3365]
Hello folks,

I tried to create a part label which would display the product image in the label.

I made a template which contains the image reference in the following way:
```
<img class='partimage' src="http://localhost:8000/media/{{ part.image }}"/>
```

I came across two issues: 
- The part.image only contains the url after the media folder. Is there any context variables for accessing the server based url? If there is no such a variable I can send a PR to overcome this.
- The images does no get displayed because the WeasyPrint accesses them without the session cookie I think:
```
[20/Jul/2022 09:24:37] "GET /api/label/part/?enabled=true&parts%5B%5D=113 HTTP/1.1" 200 473
Unauthorized: /media/part_images/FLIR00019.bmp
Unauthorized: /media/part_images/FLIR00019.bmp
Failed to load image at 'http://localhost:8000/media/part_images/FLIR00019.bmp': HTTPError: HTTP Error 401: Unauthorized
[20/Jul/2022 09:24:39] "GET /media/part_images/FLIR00019.bmp HTTP/1.1" 401 12
```
Do you have recommendation how to patch this issue? My idea is to pass the browser's cookies to the PDF generator.

**Comment by SchrodingersGat** [comment]
Hey @martonmiklos what you want to do is possible, but I realize that it is not currently documented.

You want to make use of the `part_image` template function:

https://github.com/inventree/InvenTree/blob/aca58dedc063cf79f75905ba5bec4a6327550a1c/InvenTree/report/templatetags/report.py#L35

In your report you will want something like

```html
{% load report %}

<img class='partimage' src='{% part_image part %}'/>
```

Please give this a go and let me know if it works for you.

**Comment by martonmiklos** [comment]
My bad, I missed the importance of the ```{% load report %}```

**Comment by matmair** [comment]
Hi there @martonmiklos . Please consider using the templates shown in the issue creation screen as the information included there helps the core dev team work through everything faster.
