### ISSUE TITLE
[FR] Add Line Item on Sales Orders does not search Supplier Part Names

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#3369]
**Is your feature request the result of a bug?**
No

**Problem**
A number of our parts have 3 or more valid numbers because of History, Standards Bodies, or assembly manufacturers.

As an example. So the manual says use NumberA.  The supplier calls it 1970StdBdy-A. The part is entered into our instance as NumberA.  We ordered the part from the supplier as 1970StdBdy-A.  The part arrived with 2020StdBdy-123 written on it.

The mechanic then wrote the part down on the workorder as 2020StdBdy-123.  At the point data entry is being done the person entering data only sees 2020StdBdy-123 but the Add line item on the search doesn't find it.  So they search the name using the Omni Search at the top right, they find 2020StdBdy-123 and get frustrated that the search is not working.

**Suggested solution**
Also search the supplier part names when adding parts to Sales Order.

**Describe alternatives you've considered**
This can be fixed by adding all of the Supplier Part Names to the keywords of the part but why enter the data into the system twice?

**Do you want to develop this?**
I probably could.  I think this should be as simple as adding the correct field name to the list of search fields.

**Comment by matmair** [comment]
Intresting find, I only use internal IPNs everywhere but I can see how this problem comes up. I assigned this the 1.0 milestone - that means basically whenever. Feel free to ping inventree/maintainer if you need pointers / want feedback etc.

**Comment by SchrodingersGat** [comment]
@nwns should be an easy addition to the API search fields as you say.

**Comment by SchrodingersGat** [comment]
@nwns I think that it currently does work as you intend, actually:

Create a part with a supplier part name (SKU) as follows:

![image](https://user-images.githubusercontent.com/10080325/180352635-3f56876e-6ad2-4607-a437-de812add8107.png)

Search on this SKU in the "add line item" form:

![image](https://user-images.githubusercontent.com/10080325/180352734-f198bd56-ed1b-474f-aa23-0db1eb1c52ce.png)

I believe this is what you are looking for?

**Comment by SchrodingersGat** [comment]
Note that this is running latest master, not stable. Might be different on stabl.

**Comment by SchrodingersGat** [comment]
@nwns can you please confirm if you still see this issue on latest version (e.g. on the demo site). Otherwise I'll close it out.

**Comment by nwns** [comment]
@SchrodingersGat It doesn't seem to be working
![image](https://user-images.githubusercontent.com/10690911/185416622-3039b9b3-9002-4001-afd1-4eca8cc55553.png)

![image](https://user-images.githubusercontent.com/10690911/185416391-111b0049-c6e8-4d80-9317-f8aa56b1b52e.png)

**Comment by SchrodingersGat** [comment]
@nwns really confused here. This is on current "latest" master branch:

![image](https://user-images.githubusercontent.com/10080325/185523824-6e8c26ed-4aec-49c7-9fb3-56a1259f9aa6.png)

![image](https://user-images.githubusercontent.com/10080325/185523893-3e2a47cd-3a14-4c3d-b643-629df69e77f5.png)

**Comment by nwns** [comment]
@SchrodingersGat This request is for **Sales Orders**, it currently works fine on Purchase Orders as you noted.

**Comment by SchrodingersGat** [comment]
@nwns I guess I can't read? I'll look into *Sales Orders* ;)

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/185538692-8562494d-40dd-4dfb-8d9f-879e8110ca08.png)

Seems to work for sales orders on my end...

**Comment by nwns** [comment]
Hrm. I was trying it on the public demo server. Is the demo server master or stable?  I will have try this again tomorrow @SchrodingersGat

**Comment by SchrodingersGat** [comment]
This is on current master

**Comment by nwns** [comment]
Figured it out.  It does seem to work on the demo server and on master.  Problem was the part was not saleable.
