### ISSUE TITLE
[FR]Recursive part category deletion

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#3384]
**Is your feature request the result of a bug?**
No

**Problem**
I have imported a category tree from an external source (TME API), and I have categories with child categories what I would like to delete.
Deleting the topmost categories will result the child categories to be moved one level upward. 

**Suggested solution**
![kép](https://user-images.githubusercontent.com/1609182/180296806-fdb03656-c76a-4fd3-be71-da88e0beb61b.png)
I would recommend adding a two comboboxes in this area:
- What to do with the Child categories: move to parent/delete (together with associated parts)
- What to do with the items associated to this category: move to parent/delete

**Describe alternatives you've considered**
Using raw SQL commands ;)

**Examples of other systems**
I am not aware of any.

**Do you want to develop this?**
Sure.

**Comment by matmair** [comment]
Good suggestion @martonmiklos please do not forget unit tests. Deleting all subcategories of `electronics` e.g. could be a bit of work for some users ;-)

**Comment by SchrodingersGat** [comment]
Related issue: https://github.com/inventree/InvenTree/issues/757

**Comment by martonmiklos** [comment]
Hi guys,

May I ask for a bit of help?
Is there any way to add non model fields to the forms generated by the [constructForm in the forms.js](https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/js/translated/forms.js#L324)

I tried to create the form this way:
```
constructForm(url, {
        title: '{% trans "Delete Part Category" %}',
        method: 'DELETE',
        fields: {
            child_categories_action: {
                name: '{% trans "What to do with the parts associated to this category:" %}',
                choices: subChoices
            },
            child_parts_action: {
                name: '{% trans "What to do with the child categories (and parts associated to them):" %}',
                choices: subChoices
            },
        },
        preFormContent: html,
        onSuccess: function(response) {
            handleFormSuccess(response, options);
        }
    });
```
However if I pass any fields in the options the following line will run to error:
https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/js/translated/forms.js#L469
because the fields is a simple boolean true (OPTIONS.actions.DELETE passed in constructDeleteForm [here](https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/js/translated/forms.js#L393))

**Comment by matmair** [comment]
@SchrodingersGat is the expert for the frontend, he built all the magic 😜.
I think it should work this way but assuming this question is related to the FR above: Why not just build an endpoint for deleting stuff?You will need backend code for checking the results of the questions anyhow so it might be fast to just build a normal CBV (inheriting from the [DestroyApiView](https://www.django-rest-framework.org/api-guide/generic-views/#destroyapiview)) that handles the whole processing in the destroy() method of that class. A good example would be the method found [here](https://github.com/inventree/InvenTree/blob/805accb47903e07cbfaf1a1360b1e1129d5fe80e/InvenTree/part/api.py#L747) you just need to reference the CBV-class you created in the api like [this](https://github.com/inventree/InvenTree/blob/c42c0e1e4819da3ab5f87d89cb564e804aa2224c/InvenTree/part/api.py#L2046).

Or you could just extend [this class](https://github.com/inventree/InvenTree/blob/648faf4ed2a8b05e034abefffd3f1c8f805b5b4e/InvenTree/part/api.py#L162) with a destroy() method and then build the form dynamically from the endpoint.

**Comment by SchrodingersGat** [comment]
@martonmiklos nice catch, I guess we've never tried to put custom fields onto a `DELETE` API form until now :)

Here's what you'll need to do to fix it:

https://github.com/inventree/InvenTree/blob/4d5e267753cf123bfad8117c058dba7f6e52ca59/InvenTree/InvenTree/metadata.py#L96

Change this line to:

```python
actions['DELETE'] = {}
```

https://github.com/inventree/InvenTree/blob/4d5e267753cf123bfad8117c058dba7f6e52ca59/InvenTree/InvenTree/metadata.py#L100

Change this line to:

```python
actions['GET'] = {}
```

Then you can do stuff like:

![image](https://user-images.githubusercontent.com/10080325/181682976-05eeb13d-28a9-4811-b8e4-bfddaa111dda.png)

**Comment by matmair** [comment]
@martonmiklos if you run into further problems/want feedback please open a draft PR - that way we can suggest and comment on the actual code.

**Comment by luwol03** [comment]
@martonmiklos Will this PR cover all types of deletionable items? E.g. also the StockLocation?

**Comment by martonmiklos** [comment]
Hi @luwol03 
Well my intention was to handle the recursion only on the Part categories.
But if I manage to pass through initial issues I will likely add similar options to the Stock locations as well.
And keep in mind that this PR is no ready at all. I started from the frontend side and submitted it here to being able to easier share my issues with the other folks.

**Comment by martonmiklos** [comment]
> @martonmiklos if you run into further problems/want feedback please open a draft PR - that way we can suggest and comment on the actual code.

Good idea!

It looks that I managed to sort out the frontend issues thanks to Oliver's hints.

By moving to the backend side I faced with the following question: where shall I handle the recursive deletion?
In the custom destroy what @SchrodingersGat  pointed out:
https://github.com/inventree/InvenTree/blob/4d5e267753cf123bfad8117c058dba7f6e52ca59/InvenTree/part/api.py#L162
I can access the request just fine.

However I am under the impression that the handling of the subcatgegories/parts deletion shall be done in the model here as the current (move everything to the parent category is done there):
https://github.com/inventree/InvenTree/blob/4d5e267753cf123bfad8117c058dba7f6e52ca59/InvenTree/part/models.py#L66

What is the king's way to pass the request data down to the model?

**Comment by SchrodingersGat** [comment]
@martonmiklos great questions.

My approach would be to implement the custom delete behaviour in `PartCategory.delete()`. The `PartCategory` instance should be in charge of what happens when it is deleted. You can pass any arguments through to this function as `**kwargs` from the `CategoryDetail` API view.

**Comment by martonmiklos** [comment]
> My approach would be to implement the custom delete behaviour in `PartCategory.delete()`. The `PartCategory` instance should be in charge of what happens when it is deleted. You can pass any arguments through to this function as `**kwargs` from the `CategoryDetail` API view.

Great so it is quite aligned with my plans.

My issue is right now that the kwargs does not get propagated to the PartCategory.delete().

The call stack is the following:

```
File "/home/mm/Projektek/inventree/src/InvenTree/part/api.py", line 198, in destroy
    return super(CategoryDetail, self).destroy(request,
File "/home/mm/Projektek/inventree/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
File "/home/mm/Projektek/inventree/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
File "/home/mm/Projektek/inventree/src/InvenTree/part/models.py", line 73, in delete
    for line in traceback.format_stack():
```

In the api.py I have the request data fine, but if I pass it via the kwargs it will land here:
https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L89

And as you see the kwargs does not get passed to the actual instance.

Shall we override the DestroyModelMixin.destroy with a custom implementation to pass kwargs?

Sorry for the "pig on the ice" grade questions, but my "learing django by doing" approach harder than I expected ;)"

**Comment by SchrodingersGat** [comment]
> Shall we override the DestroyModelMixin.destroy with a custom implementation to pass kwargs?

Yep, looks like that will be necessary to pass through the values extracted from the form fields!

Similar to how parts are deleted via the API:

https://github.com/inventree/InvenTree/blob/4d5e267753cf123bfad8117c058dba7f6e52ca59/InvenTree/part/api.py#L747

**Comment by martonmiklos** [comment]
Hi guys.

I managed to get it rolling. No tests so far. Would you mind to take a look on the #3435?

**Comment by matmair** [comment]
@martonmiklos please ping us if you need feedback by naming us - that makes it more clear who you need. You can also do that in PRs - reduces the number of needed clicks to get to reviewing. Looks good in general btw.

**Comment by martonmiklos** [comment]
Hi folks,

How do you do unit testing? I started to write unit tests in the test_api.py, but I am unsure how to run that.

Tried invoke test, but it takes ages. Any best practice would be warmly welcome!

**Comment by luwol03** [comment]
Hi @martonmiklos ,

I was at the same point like you. I tried to modify some code to get it running in under 30s. My closest solution was to do `python manage.py test stock.api_test.ClassName.functionName` but this also took 20s on my machine so it was a pretty bad solution. I'm also hoping the team has some better idea.

luwol03

**Comment by martonmiklos** [comment]
> python manage.py test stock.api_test.ClassName.functionName

Many thanks for the hint! I think the api_test part shall  be test_api ;)

**Comment by luwol03** [comment]
> Many thanks for the hint! I think the api_test part shall  be test_api ;)

Oh yes, I wrote this with gh mobile out of my head. Hope this helped and you got the idea.

**Comment by matmair** [comment]
@martonmiklos @luwol03 this is the default Django testing solution. The system takes quite a few seconds to set up the testing database etc. the tests themself are normally pretty fast. You can limit what tests run with the syntax provided by @luwol03 but that is all you can do. I actually tent to develop the tests in the debug console / shell mode and then just paste the code. The PR checks run all tests anyway so you can be sure that you did not break anything.

**Comment by martonmiklos** [comment]
The --keepdb helped a lot in my case (the test is 'agnostic' to the initial db state).

**Comment by matmair** [comment]
@martonmiklos that is not a good idea as it leads to problems with several tests.

**Comment by martonmiklos** [comment]
Hello Django gurus

It am a bit stuck with getting the tests rolling (see PR), test ran with:
`python3 InvenTree/manage.py test --keepdb  part.test_api.PartCategoryAPITest.test_category_delete`


The model code updates the child categories as it should:
Lines in order: ID, old parent, new parent.
`move child categories up
407
Parent Cat/Cat to delete - Some name 
Parent Cat - Some name of parent category
408
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
409
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
410
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
411
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
412
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
413
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
414
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
415
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
`

And in the test:
`
407
OK
408
OK
409
OK
410
OK
411
OK
412
OK
413
OK
414
OK
415
F
======================================================================
FAIL: test_category_delete (part.test_api.PartCategoryAPITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mm/Projektek/inventree/src/InvenTree/part/test_api.py", line 348, in test_category_delete
    self.assertEqual(child.parent, parent_cat)
AssertionError: <PartCategory: Parent Cat/Cat to delete - Some name> != <PartCategory: Parent Cat - Some name of parent category>
`
As you see the first 9 category had been moved fine, but the last did not.

First I suspected the transaction handling, so I added an [on_commit](https://github.com/inventree/InvenTree/pull/3435/commits/3c242d50c9073163283da2cc78878d94db39dcfe) hook to see where it commits the changes, but it does not looks to be called at all. May I ask you @matmair  @SchrodingersGat  what did I overlooked/missed?

**Comment by SchrodingersGat** [comment]
That's a strange one. If you change the quantity from 10 to some other number (smaller / larger / odd) does it alter the behaviour?

**Comment by martonmiklos** [comment]
> That's a strange one. If you change the quantity from 10 to some other number (smaller / larger / odd) does it alter the behaviour?

Hmm. I have 4 test 'sub' cases (which is broken atm in the test and performing the first behavior in each subcase): 
- all child categories and parts moved under the parent category (old behavior)
- move subcategories to parent, delete all parts
- delete subcategories, move parts to parent
- delete subcategories, delete all parts
- 
If I lower the subcategory count to 3 (in each subtest) the it fails in the 3rd iteration first subcategory (7th created subcategory)...

I suspected the transaction handling so I separated the recursively iterated portion into an another method, so now the first (and only) transaction scope covers the whole operation.

**Comment by martonmiklos** [comment]
Something must be with the transactions: I added an on_commit hook but never got called.

Then I read some docs and changed the InvenTreeAPITestCase to derive from APITransactionTestCase (not from APITestCase).

This way the on_hook started to get called, but it does not get called after the recursive delete operation is performed:

```
(env) mm@lapos:~/Projektek/inventree/src$ python3 InvenTree/manage.py test --keepdb  part.test_api.PartCategoryAPITest.test_category_delete
Using existing test database for alias 'default'...
System check identified no issues (1 silenced).
10365
10366
10367
10368
10369
10370
10371
10372
10373
10374
{'pk': '55', 'delete_parts': False, 'delete_child_categories': False}
False 
commit <---- this is the end of the test case child/category deletion in the test case, delete operation starts below
move part to parent
1st iteration
move part to parent
1st iteration
move part to parent
1st iteration
move part to parent
1st iteration
move part to parent
1st iteration
move part to parent
1st iteration
move part to parent
1st iteration
move part to parent
1st iteration
move part to parent
1st iteration
move part to parent
1st iteration
move child categories up
56
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
57
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
58
Parent Cat/Cat to delete - Some name
Parent Cat - Some name of parent category
< ---- delete operation ended here (no commit??) and the test starts comparing 
56
OK
57
OK
58
OK

```

**Comment by martonmiklos** [comment]
I started suspecting the caching rather than the transactions. It does not looks to be tied to database related things.
I saw cache.clear() a few places in the test and other places, however adding a fair amount of these lines did not helped either :(

**Comment by SchrodingersGat** [comment]
Hey @martonmiklos where are you up to with this? I'd like to get this into the next stable release, LMK if you need some assistance with it!

**Comment by martonmiklos** [comment]
Hey @SchrodingersGat I am working on it really. 
I managed bypass the weird issue, at least when running the test in 4 different config (delete parts+delete subcategories, delete parts+move subcategories up, move parts up+delete subcategories, move parts+move subcategories up) it does not appear. 
I am sorry for being very late with it, but I had many other things to do.

**Comment by SchrodingersGat** [comment]
@martonmiklos no worries at all, this is a volunteer effort and we all have busy lives!

LMK if you need any help, or review :)

**Comment by martonmiklos** [comment]
> LMK if you need any help, or review :)

Could you please help with the following:
How can I ran the CI checks locally? I found a flake8 config in the setup.cfg.
So I ran `flake8 --config setup.cfg --verbose .`
But the CI python style checks are still failing. 
What could I missed here?

**Comment by SchrodingersGat** [comment]
In the root directory run `invoke setup-dev` which will configure your local setup correctly. It will then run a bunch of checks on each commit.
