### ISSUE TITLE
Not able to setup the Development Server.

### ISSUE THREAD

**Issue by kushalesmart** [inventree/InvenTree#3388]
Please arrange the step by step setup process of inventree project. Because i am getting the error when i try to setup the inventree solution by the help of Docker. 
WARNING: Discarding https://files.pythonhosted.org/packages/cc/98/8a258ab4787e6f835d350639792527d2eb7946ff9fc0caca9c3f4cf5dcfe/cryptography-3.4.8.tar.gz#sha256=94cc5ed4ceaefcbe5bf38c8fba6a21fc1d365bb8fb826ea1688e3370b2e24a1c (from https://pypi.org/simple/cryptography/) (requires-python:>=3.6). Command errored out with exit status 1: /home/inventree/dev/env/bin/python3 /home/inventree/dev/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpi1j1pum5 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cryptography==3.4.8 (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.9, 0.9.1, 0.9.2, 0.9.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.6, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.9, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2, 2.2.1, 2.2.2, 2.3, 2.3.1, 2.4, 2.4.1, 2.4.2, 2.5, 2.6, 2.6.1, 2.7, 2.8, 2.9, 2.9.1, 2.9.2, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.3.2, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 35.0.0, 36.0.0, 36.0.1, 36.0.2, 37.0.0, 37.0.1, 37.0.2, 37.0.3, 37.0.4)
ERROR: No matching distribution found for cryptography==3.4.8
WARNING: You are using pip version 21.1.1; however, version 22.2 is available.
You should consider upgrading via the '/home/inventree/dev/env/bin/python3 -m pip install --upgrade pip' command.
ERROR: 1

**Comment by SchrodingersGat** [comment]
@kushalesmart please provide some further information here. Can you run through the steps you are following and exactly where you get to this error message?

**Comment by kushalesmart** [comment]
Firstly i download the source code zip from this Link - https://github.com/inventree/InvenTree/releases/tag/0.7.5
then I Install Docker and Docker-Compose on my Mac Mini with version 20.10.14 and 1.29.2
Then I navigate the root directory of downloaded source code
then navigate to docker folder in source code zip "cd docker"
then "docker-compose run inventree-dev-server invoke update"

then I get this Below Error 
WARNING: Discarding https://files.pythonhosted.org/packages/cc/98/8a258ab4787e6f835d350639792527d2eb7946ff9fc0caca9c3f4cf5dcfe/cryptography-3.4.8.tar.gz#sha256=94cc5ed4ceaefcbe5bf38c8fba6a21fc1d365bb8fb826ea1688e3370b2e24a1c (from https://pypi.org/simple/cryptography/) (requires-python:>=3.6). Command errored out with exit status 1: /home/inventree/dev/env/bin/python3 /home/inventree/dev/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpi1j1pum5 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cryptography==3.4.8 (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.9, 0.9.1, 0.9.2, 0.9.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.6, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.9, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2, 2.2.1, 2.2.2, 2.3, 2.3.1, 2.4, 2.4.1, 2.4.2, 2.5, 2.6, 2.6.1, 2.7, 2.8, 2.9, 2.9.1, 2.9.2, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.3.2, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 35.0.0, 36.0.0, 36.0.1, 36.0.2, 37.0.0, 37.0.1, 37.0.2, 37.0.3, 37.0.4)
ERROR: No matching distribution found for cryptography==3.4.8
WARNING: You are using pip version 21.1.1; however, version 22.2 is available.
You should consider upgrading via the '/home/inventree/dev/env/bin/python3 -m pip install --upgrade pip' command.
ERROR: 1

> @kushalesmart please provide some further information here. Can you run through the steps you are following and exactly where you get to this error message?

**Comment by kushalesmart** [comment]
> @kushalesmart please provide some further information here. Can you run through the steps you are following and exactly where you get to this error message?

Firstly i download the source code zip from this Link - https://github.com/inventree/InvenTree/releases/tag/0.7.5
then I Install Docker and Docker-Compose on my Mac Mini with version 20.10.14 and 1.29.2
Then I navigate the root directory of downloaded source code
then navigate to docker folder in source code zip "cd docker"
then "docker-compose run inventree-dev-server invoke update"

then I get this Below Error 
WARNING: Discarding https://files.pythonhosted.org/packages/cc/98/8a258ab4787e6f835d350639792527d2eb7946ff9fc0caca9c3f4cf5dcfe/cryptography-3.4.8.tar.gz#sha256=94cc5ed4ceaefcbe5bf38c8fba6a21fc1d365bb8fb826ea1688e3370b2e24a1c (from https://pypi.org/simple/cryptography/) (requires-python:>=3.6). Command errored out with exit status 1: /home/inventree/dev/env/bin/python3 /home/inventree/dev/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpi1j1pum5 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cryptography==3.4.8 (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.9, 0.9.1, 0.9.2, 0.9.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.6, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.9, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2, 2.2.1, 2.2.2, 2.3, 2.3.1, 2.4, 2.4.1, 2.4.2, 2.5, 2.6, 2.6.1, 2.7, 2.8, 2.9, 2.9.1, 2.9.2, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.3.2, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 35.0.0, 36.0.0, 36.0.1, 36.0.2, 37.0.0, 37.0.1, 37.0.2, 37.0.3, 37.0.4)
ERROR: No matching distribution found for cryptography==3.4.8
WARNING: You are using pip version 21.1.1; however, version 22.2 is available.
You should consider upgrading via the '/home/inventree/dev/env/bin/python3 -m pip install --upgrade pip' command.
ERROR: 1

**Comment by SchrodingersGat** [comment]
Have you followed the instructions from here - https://inventree.readthedocs.io/en/0.7.5/start/docker_dev/

I have just tried this myself, with a fresh copy of `0.7.5` and it seems to work without error.

**Comment by matmair** [comment]
@kushalesmart the error message contradicts itself as the searched version is in the list of available versions. Could you try setting up the virtual environment again and confirm the python version and os you are running in the venv?

**Comment by kushalesmart** [comment]
> Have you followed the instructions from here - https://inventree.readthedocs.io/en/0.7.5/start/docker_dev/

Yes I have tried with this link also but same issue happen.

**Comment by Bbillyben** [comment]
Hi there, 
I'm stucked on the same issue

    Debian Buster/10 VM (freshly installed before my test on Inventree !).
    Docker version 20.10.17, build 100c701
    Docker Compose version v1.29.2

(my) Steps to reproduce (in the folder where I clone the repo) : 

clean previous test : 

```
sudo rm -R Inventree
sudo docker system prune -a
docker volume rm inventree-development_inventree_src
```
then start process :

```
git clone -b 0.7.5 https://github.com/inventree/InvenTree // or -b stable => same issue
cd Inventree/docker
docker-compose run inventree-dev-server invoke update
```

Error : 
```
/home/inventree/dev/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpx596rx_7 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cryptography==3.4.8 (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.9, 0.9.1, 0.9.2, 0.9.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.6, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.9, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2, 2.2.1, 2.2.2, 2.3, 2.3.1, 2.4, 2.4.1, 2.4.2, 2.5, 2.6, 2.6.1, 2.7, 2.8, 2.9, 2.9.1, 2.9.2, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.3.2, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 35.0.0, 36.0.0, 36.0.1, 36.0.2, 37.0.0, 37.0.1, 37.0.2, 37.0.3, 37.0.4)
ERROR: No matching distribution found for cryptography==3.4.8
WARNING: You are using pip version 21.1.1; however, version 22.2 is available.
You should consider upgrading via the '/home/inventree/dev/env/bin/python3 -m pip install --upgrade pip' command.
ERROR: 1
```

warnings are : 
```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[...]
  WARNING: The script python-barcode is installed in '/home/inventree/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script qr is installed in '/home/inventree/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/home/inventree/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer is installed in '/home/inventree/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pybabel is installed in '/home/inventree/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script django-admin is installed in '/home/inventree/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script weasyprint is installed in '/home/inventree/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown_py is installed in '/home/inventree/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
[...]
WARNING: Image for service inventree-dev-server was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
[...]
WARNING: Discarding https://files.pythonhosted.org/packages/cc/98/8a258ab4787e6f835d350639792527d2eb7946ff9fc0caca9c3f4cf5dcfe/cryptography-3.4.8.tar.gz#sha256=94cc5ed4ceaefcbe5bf38c8fba6a21fc1d365bb8fb826ea1688e3370b2e24a1c (from https://pypi.org/simple/cryptography/) (requires-python:>=3.6). Command errored out with exit status 1: /home/inventree/dev/env/bin/python3 
```


full install output :
[Install Output.txt](https://github.com/inventree/InvenTree/files/9180406/Install.Output.txt)

**Comment by SchrodingersGat** [comment]
Ok @kushalesmart @Bbillyben @matmair I think I have worked out what is going on here.. It's pretty annoying, and I'll need you to check something on your end before we go and try to issue a fix.

In `tasks.py` (in the top level directory) please add the following command at **line 97**:

```python
c.run('pip3 install --upgrade pip')
```

![image](https://user-images.githubusercontent.com/10080325/180796535-f73a452b-84ba-4d21-bef3-93fc02f300bc.png)

And then, run the same command again:

```
docker-compose run inventree-dev-server invoke update
```

Please let me know if the command then runs properly.

**Comment by Bbillyben** [comment]
It has compiled!!

same process : 
```
sudo rm -R Inventree
sudo docker system prune -a

git clone -b 0.7.5 https://github.com/inventree/InvenTree
cd InvenTree
nano task.py // => add the line 97

cd docker
docker-compose run inventree-dev-server invoke update
docker-compose run inventree-dev-server invoke superuser
docker-compose up -d
```

and now the server is up and ready for testing

Gratz @SchrodingersGat !!

**Comment by matmair** [comment]
@SchrodingersGat this keeps popping up. Dependencies are such a hastle.

**Comment by matmair** [comment]
@kushalesmart could you please test and confirm this solves your problem?

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat this keeps popping up. Dependencies are such a hastle.

In this case it appears that [alpine:3.14](https://hub.docker.com/layers/alpine/library/alpine/3.14/images/sha256-a573d30bfc94d672abd141b3bf320b356e731e3b1a7d79a8ab46ba65c11d79e1?context=explore) was recently updated on dockerhub, and has moved to `python 3.9`. So, this has broken *stuff*. So frustrating!

**Comment by SchrodingersGat** [comment]
@kushalesmart @Bbillyben we'll release `0.7.7` soon which will include this fix.

Note that if you are going to build a development installation yourself, `inventree:latest` is much more "up to date" than `inventree:stable`. But depends what you're looking to achieve :)

**Comment by kushalesmart** [comment]
> @kushalesmart could you please test and confirm this solves your problem?

It has compiled!!
thanks a lot.

**Comment by SchrodingersGat** [comment]
@kushalesmart great! Thanks for submitting the error report.
