### ISSUE TITLE
[BUG] 	SampleIntegrationPlugin does not render

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#3389]
**Describe the bug**
When I enable the SampleIntegrationPlugin, custom panel do not show up. I get an error log telling
```
TemplateSyntaxError | Invalid block tag on line 1: 'tag_not_loaded'. Did you forget to register or load this tag?
```
I changed the %  inline 92 and 99 in custom_panel_sample.py to curly brackets:

```python
panels.append({
                'title': 'Broken Panel',
                'icon': 'fas fa-times-circle',
                'content': '{{ tag_not_loaded }}',
                'description': 'This panel is broken',
                'javascript': '{{ another_bad_tag }}',
            })
``
Then it works fine. 

**Version Information**
0.8.0 dev

**Comment by SchrodingersGat** [comment]
@SergeoLacruz a few things here ...

Firstly, that is *supposed* to be broken, to test the panel functionality. However it should not be showing up when you load the `SampleIntegrationPlugin`, rather the `CustomPanelExample` plugin.

1. Can you please confirm (with screenshots) where you are seeing the error message?
2. Do you have the `CustomPanelExample` plugin installed / activated?

**Comment by SergeoLacruz** [comment]
You are right. of course I am talking about the Custom Panel Example. Sorry for mixing that up. 
Here is the screenshot:

![tag_not_loaded](https://user-images.githubusercontent.com/10836099/180595550-399f7a61-ba5a-4d41-a0b1-f26072c95f27.png)

But yes, there is a switch to turn the "Enable broken panel" off. Got it.

**Comment by SchrodingersGat** [comment]
Ok to close this issue out then?

**Comment by SergeoLacruz** [comment]
OK, can be closed
