### ISSUE TITLE
[BUG] docker-compose v2.7.0 fails build on Inventree v0.7.6

### ISSUE THREAD

**Issue by xcoder123** [inventree/InvenTree#3398]
**Describe the bug**
Build process doesn't work for docker-compose V2.7.0

It seems to build fine, but when running user creation it complains about missing files:

```
/bin/bash: ../docker/init.sh: No such file or directory
```

Essentially same issues as mentioned in:
https://github.com/inventree/InvenTree/issues/2092
https://github.com/inventree/InvenTree/issues/2143

I noticed https://github.com/inventree/InvenTree/issues/2143 is part of milestone 0.8.0, so it might be fixed already
Note that with docker-compose v1.29.2 build works fine.

**Steps to Reproduce**

1. Install docker-compose v2.7.0
2. Follow build steps laid out in https://inventree.readthedocs.io/en/latest/start/docker_dev/

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
# Version Information:
InvenTree-Version: 0.7.6
Django Version: 3.2.13

Database: postgresql
Debug-Mode: True
Deployed using Docker: True

**Comment by matmair** [comment]
hi there @xcoder123 thank you for the clean report!
As fas as I am aware :latest should already contain a fix - could you test with that tag?

**Comment by SchrodingersGat** [comment]
@xcoder123 as specified in the [docs](https://inventree.readthedocs.io/en/0.7.6/start/docker/#docker-compose) there are issues running docker-compose v2 for current `inventree:stable`.

You will need to downgrade to docker-compose v1 for this to work!

The docker setup has been updated for the upcoming `0.8.0` release and will support docker-compose v2
