### ISSUE TITLE
[FR] Should a PurchaseOrder be marked as complete even if items are not received?

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3400]
**Problem**
If a PO is marked as complete, the line-items are left as-is without warning (especially via API). It would be elegant to be able to prevent this. IE `accept_incomplete` is False, then prevent marking PO as complete if there are open items.

Going further: 

**Suggested solution**
Similar to build orders, eg `/api/build/{id}/finish/`, there could be a flag to mark remaining items as received.

**Examples of other systems**
See build API.

**Do you want to develop this?**
Approach would be to copy-paste the flag called `accept_incomplete`from `BuildCompleteSerializer`.

**Comment by matmair** [comment]
@SchrodingersGat what do you think about this? I think there are use cases where a PO is done but not all line-items are delivered so this has to be handled carefully.

**Comment by SchrodingersGat** [comment]
@miggland a warning (which requires a checkbox override) to complete an order with outstanding items is a great idea.

There are valid instances where an order may be closed out without receiving everything!

Do you want to tackle this one?

**Comment by miggland** [comment]
Yeah, I'm on it.

**Comment by miggland** [comment]
I just realised that the SalesOrder prevents orders from being marked as completed, without the option to override.

**Comment by SchrodingersGat** [comment]
@miggland yep sales orders should be updated accordingly too.

**Comment by SchrodingersGat** [comment]
@miggland any progress on this? :) ping me if you need anything

**Comment by miggland** [comment]
Hi @SchrodingersGat - you might have to keep reminding me :). No progress yet, I have had too many other things to take care of. I have not made much progress, if anyone else wants to take over this issue that is perfectly fine with me... ;)
