### ISSUE TITLE
[BUG] Extra url schemes not working.

### ISSUE THREAD

**Issue by papgrap** [inventree/InvenTree#3411]
**Describe the bug**
Adding extra url schemes in the config.yaml file doesn't do anything.
I added file, mailto, git and ssh to the extra_url_schemes.

![image](https://user-images.githubusercontent.com/68426415/181010426-71296bfd-39b4-41c9-928a-cf9f6c14899b.png)

I tried the following links:
- git://github.com/inventree/InvenTree.git
- file://host.example.com/path/to/file
- mailto:chris@example.com
- mailto://chris@example.com

**Steps to Reproduce**
1. Add url schemes to extra_url_schemes in the config.yaml files.
2. Create a Part.
3. In the form try to add a link.
4. It is rejected.

**Deployment Method**
- [ ] Docker
- [x] Bare Metal

**Version Information**
0.7.6

**Comment by matmair** [comment]
@papgrap thank you for the accurate report. I can confirm your report.

**Comment by matmair** [comment]
@papgrap Thank for the report again. A patch is available as #3414 . Feel free to test it further but that should fix this issue in my testing.
