### ISSUE TITLE
[FR] Add the ability to calculate (linear) depreciation of stock items

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#3424]
**Problem**
It would be nice to have the ability to calculate depreciation of a stock item based on the purchase date and the initial cost of purchase.
This feature is usually found in asset management systems and would make InvenTree even more versatile as both an inventory management and an asset management system.

**Suggested solution**
Add an extra fields to the stock item with 
- purchase price (already exists, although it is not clear whether this price is for a SINGLE item or ALL items in the stock)
- purchase currency (already exists, although very few currencies are available)
- purchase date
- purchase order/invoice (does not appear to be possible to edit)
- required depreciation (eg. 5 year/60 months)
- fully depreciated (based on purchase date and depreciation)
- current value, calculated based on the above fields.
2. Add a menu where a depreciation report can be generated for selected stock items. This report should contain the current value of all purchases, based on their purchase date, cost and the depreciation.

**Examples of other systems**
Asset mgmt. systems such as SnipeIT can do this but unfortunately, this system lacks severely in other areas.

**Do you want to develop this?**
Yes, if pointed in the right direction on where/how to add the functionality.

**Comment by matmair** [comment]
Hi there @tehkillerbee
Cool idea 👍 
There is a lot stuff that is requested in pricing. With the limited number of devs we have it might take a while till we get to it: https://github.com/inventree/InvenTree/issues/1656

**Comment by SchrodingersGat** [comment]
@tehkillerbee very interesting idea! I'm wondering whether this might work well as a plugin? In any case this will need to wait for the outstanding pricing issues but we can certainly discuss implementation ideas

**Comment by matmair** [comment]
@SchrodingersGat might work well as an `AppMixin`

**Comment by tehkillerbee** [comment]
@matmair @SchrodingersGat Good to hear you like the suggestion. A plugin would work fine for us to display the depreciation, although I assume the necessary fields must be added to the database somehow?

**Comment by SchrodingersGat** [comment]
@tehkillerbee you could keep a completely separate set of database tables, to ensure that the core database fields are kept clean. Then some logic to map a "depreciation" to a particular stock item.

**Comment by matmair** [comment]
I might add that metadata fields might also work. For a lookup a separate db might help.

**Comment by tehkillerbee** [comment]
I also realised that it is possible to add custom part parameter fields. Perhaps this could be a way to add the necessary fields for purchase date/value/currency/order etc. although I guess the fields must be added manually. Are these the metadata fields you refer to @matmair?

@SchrodingersGat I did consider just using a separate database for this but I figured the user experience would be better if it was integrated in InvenTree frontend, either directly or as a plugin. It would also make it easier to maintain, as the necessary data (purchase date, cost etc.) could easily be entered through the InvenTree interface.

I could imagine the depreciation table could be generated/displayed using a plugin but it would have to get the necessary data (purchase date, value) from somewhere. So being able to add these fields easily for each part would probably be necessary as a starting point. 

When adding part parameter fields, do they behave in a similar way as "normal" part parameters such as description, IPN, cost etc.? Can they be accessed - eg. from a plugin in the same way?

**Comment by matmair** [comment]
Part parameters are something else. You can access .metadata dict fields on all principal models (from a plugin) to save data there.

**Comment by SchrodingersGat** [comment]
@tehkillerbee please indicate if you are still interested in this, otherwise we'll close it out.

**Comment by tehkillerbee** [comment]
@SchrodingersGat It would be a very nice feature to have, that's for sure, but I understand that there are some issues such as pricing that need to be handled first.

**Comment by tehkillerbee** [comment]
This would still be a very useful feature.

**Comment by tehkillerbee** [comment]
One way we could get started would be to add the following fields to a stock item and edit them manually
- purchase date
- purchase price, currency (already exists, although with limited currencies available)

As I understand, purchase price and currency for a stock item are usually populated automatically when creating a purchase order, correct? If so, it would make sense to add purchase date and also update it automatically when creating a purchase order.

All calculation related to depreciation can then be handled by a separate plugin, where we put in the 
- Input: required depreciation (eg. 5 year/60 months)
- Output: fully depreciated (based on purchase date and depreciation)
- Output: current value, calculated based on the above fields.

**Comment by SchrodingersGat** [comment]
Purchase "date" is most like the creation date of the stock item itself, if it was received via a purchase order. Handling the actual depreciation via a plugin is a good idea.

**Comment by tehkillerbee** [comment]
@SchrodingersGat That makes sense. However, we would like to be able to edit the creation date (just like purchase cost), without having to create purchase orders for existing stock items. Is this possible somehow?

Otherwise, we will have to use a different field to specify the original purchase date.

**Comment by matmair** [comment]
@tehkillerbee the creation date is set on creation of the database entry and it is assumed that that is consistent. Changing this seem like a bad idea, do you have a concrete example why this needs to be editable?

**Comment by tehkillerbee** [comment]
First of all, I would like to say that I have not properly tested the purchase order workflow for our existing stock items, so I apologize if I do not know everything that is possible with it. Generally, I think the workflow makes sense good for a pure components, after all this is what InvenTree is designed for.

But eg. for unique assets, we will have to create individual purchase orders for *each* unique stock item - just to be able to add a purchase date/cost/etc. to it. That seems like a lot of extra steps.

Also, if we are supposed to use purchase orders for all stock items, it seems counterintuitive that we can still edit some of the fields manually (purchase cost, purchase currency etc.).  Instead, if we add a field such as purchase date and purchase invoice/reference as a field that can be edited for each stock item, it would give a more consistent user experience. Then you can *either* use the purchase order workflow *or* enter the information manually if necessary.

My idea is that each stock item should contain the purchase date, purchase cost and reference (and other fields that can also be updated by the purchase order). But instead of relying only on the purchase order workflow to populate these fields, the information should also be possible to enter/update manually by the user.

**Comment by matmair** [comment]
Changing how the creation date works will fundamentally break plugins - so we should have a good reason that can not be covered by adding metadata in a plugin for one specific use-case.

**Comment by tehkillerbee** [comment]
I agree, I would say it should be a separate field in that case. Similar to how we can set Expiry Date for a stock item

**Comment by tehkillerbee** [comment]
I ended up using the "batch" field as a workaround to enter the purchase dates manually. This works fine - since we can enter anything we want in this field and we can easily transfer our existing purchase dates over. The purchase cost has been entered in the appropriate field. 

To generate the output report, I used the Python API to export the data in a format suitable for excel. (similar to this issue https://github.com/inventree/InvenTree/issues/2507) I must say, this worked rather well - since the API was very well thought out. Main challenge was figuring out how to get the location of stock that belong to a customer and/or a different stock item.

Below is the quick&dirty(TM) script

```Python
from inventree.api import InvenTreeAPI
from inventree.stock import StockLocation, StockItem
from inventree.part import Part
from inventree.company import Company

import xlsxwriter

from datetime import datetime, date

# This is a sample Python script.
SERVER_ADDRESS = 'http://AAA.BBB.CCC.DDD:1337'
MY_USERNAME = '<enter your user here>'
MY_PASSWORD = '<enter your password here>'

# Setup file output parameters
today = date.today()
date = today.strftime("%d-%m-%Y")

def do_inventree_report():
    api = InvenTreeAPI(SERVER_ADDRESS, username=MY_USERNAME, password=MY_PASSWORD)
    items = StockItem.list(api)

    workbook = xlsxwriter.Workbook('InventoryReport_{}.xlsx'.format(date))
    worksheet = workbook.add_worksheet()
    workbook1 = xlsxwriter.Workbook('InventoryReportExcluded_{}.xlsx'.format(date))
    worksheet1 = workbook1.add_worksheet()

    # Write header
    my_list = ["IPN", "Serial", "Name", "Description", "Quantity", "Status", "Location", "PurchaseDate", "PurchasePrice", "PurchasePriceCurrency"]
    worksheet.write_row(0, 0, my_list)

    my_list = ["IPN", "Serial", "Name", "Description", "Quantity", "Status", "Location", "PurchaseDate",
               "PurchasePrice", "PurchasePriceCurrency"]
    worksheet1.write_row(0, 0, my_list)

    items_without_price = 0
    total = 0
    stock_row = 1
    stock_excl_row = 1
    for item in items:
        try:
            part = item.getPart()
        except:
            continue
            
        # skip all items that does not have a purchase price set
        if item.purchase_price:
            # skip items with a purchase cost of less than 100 (Irrespective of currency)
            if float(item.purchase_price) <= 100:
                continue
                
            # get full location as string, attempt to get indirect location from items installed in other hardware
            locationStr = "None"
            location = None
            customer = None
            serial = None

            try:
                if item.belongs_to:
                    # Determine location from assign
                    itemA = StockItem(api, pk=item.belongs_to)

                    if itemA.serial:
                        serial = itemA.serial
                    elif itemA.customer:
                        # Determine location from customer
                        customer = Company(api, itemA.customer)
                        location = None
                    elif itemA.location:
                        location = itemA.getLocation()
                    else:
                        location = None
                elif item.customer:
                    customer = Company(api, item.customer)
                else:
                    location = item.getLocation()

                if location:
                    locationStr = location.pathstring
                elif customer:
                    locationStr = "Deployed: {}".format(customer.name)
                elif serial:
                    locationStr = "Assigned: {}".format(serial)
                else:
                    locationStr = "None"

            except:
                locationStr = "None"

            fields = [part.IPN, item.serial, part.name, part.description, item.quantity, item.status_text, locationStr,
                      item.batch, item.purchase_price, item.purchase_price_currency]
            print(*fields, sep=", ")
            worksheet.write_row(stock_row, 0, fields)
            stock_row += 1
        else:
            fields = [part.IPN, item.serial, part.name, part.description, item.quantity, item.status_text, "Location",
                      item.batch, item.purchase_price, item.purchase_price_currency]
            worksheet1.write_row(stock_excl_row, 0, fields)
            #print(*fields, sep=", ")
            stock_excl_row += 1
            items_without_price += 1
        total += 1
    workbook.close()
    workbook1.close()

# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    do_inventree_report()
```

**Comment by matmair** [comment]
@tehkillerbee thank you for the example. We need some way to share those better in a central place.

I know I am a bit late but there might actually be a better/more future safe way to save the information. There are the methods `getMetadata` and `setMetadata` which can be used to save arbitrary data to the model and an extra field.
https://github.com/inventree/inventree-python/blob/d13d8af985fa9d5321ddd6f85c693ded2d6c5d2b/inventree/base.py#L432-L433

https://github.com/inventree/inventree-python/blob/d13d8af985fa9d5321ddd6f85c693ded2d6c5d2b/inventree/base.py#L446-L452


I opened an issue regarding the docs https://github.com/inventree/inventree-docs/issues/425, there is also a PR to add metadata to more models #4202

**Comment by tehkillerbee** [comment]
@matmair That is a good idea too. This script was largely based on an existing script I found by accident. But it was easy to adapt so I could export only the required fields from the inventory. Very nice and easy to set up.

Regarding metadata, as I understand, they can only be accessed through the API, or? 
In our case, some users prefer a more graphical way to enter values (i.e. the webinterface), so that was the reason why I used the batch field to enter the dates.

**Comment by matmair** [comment]
You can show them with a few LoC. My concern mainly is that we will start doing *something* more intelligent with the batch field *sometime* and break your workflow by assuming that there is only batch info there.

**Comment by tehkillerbee** [comment]
@matmair Also in the web interface? I will have to try that then.

No worries, using the batch field was a hack in any case. I think I can make a quick python script that can move the batch field contents, as soon as there is somewhere else I can put them. We needed to finish the inventory, so I had to find a quick solution.

**Comment by tehkillerbee** [comment]
Closing this issue, as it has been solved using the Python API.
