### ISSUE TITLE
[FR] Custom Serial Number Mapping

### ISSUE THREAD

**Issue by NPaes12** [inventree/InvenTree#3428]
**Problem**
Our company currently uses an alphanumeric Serial Number (S/N) system ex. L4Z, L51 ... L59, L5A etc. This alpha numeric system grants us over 30,000 permutations of S/Ns with very few characters (We exclude the letters O, I and the number 0). This is preferable as we make small PCBs and these serial numbers easily fit on them. I understand that the newest version of Inventree now supports manual entry of these non-integer S/Ns but not the auto-generation of them. To eliminate the need to generate these S/Ns elsewhere we would like to have it all done in Inventree.

**Suggested solution**
Create a S/N "mapping" that takes the integer Inventree auto-generated number and maps it to a company-specific one. So perhaps in the admin tab, there is a simple CSV file that has integers in one column (0,1,2,3...) and company-specific S/Ns in the other column (AB1, AB2, AB3 ...). Inventree can still use its default integer auto generation on the backend but display the company S/N on the front end. This is useful for organizations looking to move to Inventree but who want to maintain their current S/N format and start point. 

- Add a "Serial Number Mapping" tab in the Inventree admin panel
- Default mapping contains a file with a 1-to-1 mapping with integers in both columns
- Create the ability to then upload a custom mapping with company-specific serial numbers

**Examples of other systems**
I do not have examples of this elsewhere.

**Do you want to develop this?**
I do not have the know-how to develop this.

**Comment by matmair** [comment]
@NPaes12 intresting idea!
Sounds plausible but with the current backlog I am not sure if/when a dev of the core team will have time for this.
@SchrodingersGat would this be a go from you and should we tag it `help wanted`? I have no real use so won't commit at this time.

**Comment by SchrodingersGat** [comment]
@NPaes12 thanks for the input. We recently [refactored the order reference fields](https://github.com/inventree/InvenTree/pull/3267) to support *some* level of customization. A similar approach could be extended to serial number fields.

However it's a pretty complex proposition to provide a "general purpose" generation tool which meets the particular requirements of every company. Perhaps this would be a good use case for a custom plugin, which takes an existing serial number and generates the next one in the sequence.

The current "increment" function looks like this:

https://github.com/inventree/InvenTree/blob/4d5e267753cf123bfad8117c058dba7f6e52ca59/InvenTree/InvenTree/helpers.py#L283

I would suggest that for users looking for "custom" incrementing here, a custom plugin (or some other way to hook in a custom method) would be ideal. This would require extension of the existing plugin architecture.

@matmair would there be a way (besides plugins) to allow custom function hooks? A *dangerous* idea would be to allow the user to upload raw python code and run that.

**Comment by matmair** [comment]
>
> @matmair would there be a way (besides plugins) to allow custom function hooks? A _dangerous_ idea would be to allow the user to upload raw python code and run that.

@SchrodingersGat I am going to just ping @dievus to make discovery easier for him. Joke aside thanks for your disclosures again - made us a lot more aware of security in the app.

I think there are 2 obvious solutions:
1. importing a list of serial numbers and using them is a good low barrier method
2. a simple PluginMixin should cover more complex

You could solve this with pattern matching, a custom syntax like we have with serial number entry etc. but I think if anyone wants that they can submit a FR. Solutions 1 and 2 should cover more than 80% so I would suggest doing them in that order.

**Comment by matmair** [comment]
These solutions should cover numbers in general. We need this for at least serials and IPNs, maybe also BO, SO, PO and so on. Suggested name for solution 1: pre-calculated reference.

**Comment by dievus** [comment]
Definitely had a giggle when I read that. 

A couple of suggestions. First, if you want to implement that, maybe make it needs based rather than being available or enabled by default (looks like that's a possibility if it's added as a plugin). Security principles should always ensure that the least amount necessary is available. I would definitely avoid exec(), eval(), and input(), as well as any other function that might allow backend execution beyond the application itself.

If you all want me to poke at it before doing a full release just let me know and I'll see if there's anything I can find.

**Comment by NPaes12** [comment]
Appreciate all the feedback. I am new to Github so was quite surprised with how responsive everyone here is!

**Comment by matmair** [comment]
@NPaes12 we are generally fast to repsonse arounde here ;-)
I reopened this as the solution is not ready for endusers as of now. I would also like to look into solution 1 at some point as it is easier for non-programmers.
