### ISSUE TITLE
[FR] Add plugin to generate (seria|IPNl) numbers

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3430]
Create a PluginMixin to generate numbers for at least IPNs and serialnumbers. Should be pretty forward: integer and instance in -> some string out.

I want to dev this.

Original text:
2. a simple PluginMixin should cover more complex

_Originally posted by @matmair in https://github.com/inventree/InvenTree/issues/3428#issuecomment-1199654297_

**Comment by matmair** [comment]
Ref serial #3428 
Ref IPN #2848

**Comment by SchrodingersGat** [comment]
Multiple plugins could exist, with each plugin providing different S/N generation based on the part instance. Iterate through each plugin which supports this mixin, and the first one to return a non-null value "wins"

**Comment by matmair** [comment]
Having multiple plugins creates some real plugins, I am going to shelf this in favor of more general improvements for now.

**Comment by SchrodingersGat** [comment]
This has (mostly) been implemented now, with the new "validation" mixin type!
