### ISSUE TITLE
[BUG] fatal: detected dubious ownership in repository at '/home/inventree'

### ISSUE THREAD

**Issue by Fivefold** [inventree/InvenTree#3442]
**Describe the bug**
My inventree-server container log is getting filled with ownership errors. I get several of them each time I load a page via browser. Seems to be the case for any page aside from django admin.
```  
fatal: detected dubious ownership in repository at '/home/inventree'
To add an exception for this directory, call:
	git config --global --add safe.directory /home/inventree
```

Ownership of the volume directory (outside of the docker container) looks like this:
```
drwxrwxrwx  5 systemd-coredump systemd-coredump 4096 Jul 31 11:44 inventree-data
```
And the contents of the volume:
```
-rw-r--r--  1 _apt             systemd-timesync  5260 Jul 30 23:09 config.yaml
-rw-r--r--  1 _apt             systemd-timesync 55768 Jul 31 11:41 data.json
-rw-r--r--  1 _apt             systemd-timesync 50211 Jul 31 11:41 data.json.tmp
drwxr-xr-x  5 _apt             systemd-timesync  4096 Jul 31 10:41 media
drwx------ 19 systemd-coredump root              4096 Jul 31 11:56 pgdb
-rw-r--r--  1 _apt             systemd-timesync    53 Jul 30 23:39 plugins.txt
-rw-r--r--  1 _apt             systemd-timesync   100 Jul 30 23:09 secret_key.txt
drwxr-xr-x 20 _apt             systemd-timesync  4096 Jul 30 23:58 static
```

**Steps to Reproduce**
This is on a fresh docker-compose setup using portainer.
1. Use the official [production docker-compose file](https://github.com/inventree/InvenTree/blob/master/docker/production/docker-compose.yml) (with redis disabled)
2. Use a folder in the home directory of the standard linux user (not root) for the volume
3. Set a different port than 8000 for the web interface in the .env file
4. Define an admin user in the .env file
5. Use the official [production nginx file](https://github.com/inventree/InvenTree/blob/master/docker/production/nginx.prod.conf)
_Note that contrary to the documentation I had to use port 8000 instead of my actual external web port. Otherwise I would get `502 Bad Gateway` errors_
https://github.com/inventree/InvenTree/blob/d4eae9da116be3a1770ee757db0acdd25b2d471c/docker/production/nginx.prod.conf#L27-L29
6. `invoke update` on first stack start since this is a fresh setup
7. Start stack regularly

**Expected behavior**
No errors in the log.
Not sure if this is actually a problem since InvenTree seems to be working, aside from ki-nTree

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
InvenTree-Version: 0.7.7
Django Version: 3.2.13

Database: postgresql
Debug-Mode: False
Deployed using Docker: True

## Additional context

I suppose it's not related but I also have the problem of ki-nTree crashing while halfway creating a part. The part is created but parameters, supplier information, etc. is missing. It crashes while fetching parameter templates apparently. 

```
    File "c:\program files\python38\lib\site-packages\inventree\part.py", line 39, in get_category_parameter_templates
         return self.list(self._api,
    File "c:\program files\python38\lib\site-packages\inventree\base.py", line 139, in list
        if isinstance(response, dict) and response['results'] is not None:
KeyError: 'results' 
```
inventree-proxy log shows this at the time:
https://pastebin.com/9Du8xfHh

I checked the last API URL accessed (`GET /api/part/category/6/parameters/?fetch_parent=True`) and it seems to be accessible just fine.

**Comment by matmair** [comment]
Hu there @Fivefold this is a problem with certain git versions and distros. Are you using the image from dockerhub or building your own?

For the Ki-n-Tree issue please open an issue on their repo. This repo/org only maintains core code.

**Comment by matmair** [comment]
Regarding the nginx config: are you sure you are not running more then 1 instance of inventree? It should not really work if another port is served by gunicorn that is proxied by nginx.

**Comment by Fivefold** [comment]
Thank you for the lightning fast response, @matmair!
> Hi there @Fivefold this is a problem with certain git versions and distros. Are you using the image from dockerhub or building your own?

This is using the image from dockerhub.

> Regarding the nginx config: are you sure you are not running more then 1 instance of inventree? It should not really work if another port is served by gunicorn that is proxied by nginx.

I had a testing instance from January that I completely tore down before starting the new one (i.e. not using the same docker images, docker-compose file or volume). Currently there is one instance each of inventree-db, inventree-proxy, inventree-worker and inventree-server running.

I do have [nginx proxy manager](https://nginxproxymanager.com/) running on this system but it shouldn't matter, since I'm accessing inventree with http://server-ip:port/ for now (with port being the defined web port, not 8000).

> For the Ki-n-Tree issue please open an issue on their repo. This repo/org only maintains core code.

I will do that, thanks. I just added it in the unlikely case it is somehow connected and helps with troubleshooting.

**Comment by luwol03** [comment]
Which OS are you using? Also had this issue on my Mac, but I just ignored it, as it is just a warning from git. You can also execute the suggested command in the error to fix the problem.

**Comment by SchrodingersGat** [comment]
@Fivefold thanks for reporting. This is due to a recent git update, which started throwing this error message.

The next stable release (0.8.0) is just around the corner, and we have changed the way that we build the docker image, so this message will no longer appear. For now, I think you will just have to deal with this message in your logs, sorry!

**Comment by Fivefold** [comment]
> Which OS are you using? Also had this issue on my Mac, but I just ignored it, as it is just a warning from git. You can also execute the suggested command in the error to fix the problem.

Just for completion and reference in the future: Debian 11


> @Fivefold thanks for reporting. This is due to a recent git update, which started throwing this error message.
> 
> The next stable release (0.8.0) is just around the corner, and we have changed the way that we build the docker image, so this message will no longer appear. For now, I think you will just have to deal with this message in your logs, sorry!

@SchrodingersGat No worries about the log, as long as nothing is actually broken. I guess this will stay open until next release as it's not technically fixed yet? (on stable at least). Feel free to close otherwise.

**Comment by SchrodingersGat** [comment]
@Fivefold happy to close out thanks. Next stable release is imminent!
