### ISSUE TITLE
Add ability to merge stock items

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#346]
- Must be of the same part
- Must be of the same supplier part?

**Comment by eeintech** [comment]
@SchrodingersGat Isn't it what the "Group by Part" stock global settings is intended for?

**Comment by SchrodingersGat** [comment]
No, "merging" here means taking two separate stock item entries and making them into a single entry.

For example, you have a packet of 7 red pencils, and a packet of 2 red pencils. Merge them into a single packet of 9 red pencils.

However there are so many potential edge cases to handle here, so this one has been waiting for a while.

**Comment by eeintech** [comment]
Ok makes sense 👍

**Comment by afkiwers** [comment]
@SchrodingersGat 

Just wondering, couldn't you just add up what's left in those stock items (the once you'd like to merge) and then create a new one which combines all the others and delete the ones you sourced from?

**Comment by SchrodingersGat** [comment]
@afkiwers yep, that could be done. The question is what do you do with the "history" of the stock items..

I think that the simplest option is that if the user wants to merge stock items, the history is gone and they just have to accept that. There could be a warning message to this effect.

**Comment by afkiwers** [comment]
@SchrodingersGat When you say history, couldn't you just add an automatic note to the new item which contains information about what stock was merged together (location etc) and when using simple formatted text?
