### ISSUE TITLE
[BUG] Currency unit display is not consistent

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#3460]
**Describe the bug**
Currency unit display and formatting is not consistent in inventree tables and forms.
In Part->Pricing and Part->BOM table amount is prefixed by ISO code without space. Two decimal digits.

![изображение](https://user-images.githubusercontent.com/10057327/182334801-5ab149ff-0b39-4df1-9a7a-54427ea5e1a9.png)
![изображение](https://user-images.githubusercontent.com/10057327/182334872-029e1bd0-8c67-420b-b6f6-44b1bf8296de.png)

While in Stock table it displayed correctly: amount with currency suffix. Four decimal digits.

![изображение](https://user-images.githubusercontent.com/10057327/182335105-24e3ee8b-f6ca-4c5d-af22-3ef47f89c216.png)

In sales orders it is again: code, hard space, amount. Two decimal digits.

![изображение](https://user-images.githubusercontent.com/10057327/182341564-9c9fb1a9-cf1f-49a9-963a-c8be766479ed.png)

I understand that this topic is not so simple and there are a lot of currencies and countries with their own rules.
Even in Europe some countries put EURO sign before amount and some after. http://publications.europa.eu/code/en/en-370303.htm#position
In 0.7.x at least for RUB it was more consistent.
 
P.S. Why inventree uses 4 decimal digits for stock money field, do we really need this precision? Only for BTC maybe?

**Expected behavior**
Same system-wide currency display approach: $10, 50 руб., etc. 

**Deployment Method**
- Bare Metal

**Version Information**
InvenTree-Version: 0.8.0
Django Version: 3.2.14
Commit Hash: 6118d1319
Commit Date: 2022-08-01
Database: mysql
Debug-Mode: True
Deployed using Docker: False

**Comment by matmair** [comment]
Hi there @sintech 
Pricing display is handled by the underlying libaries for front / backend and they sometimes change how they handle different currencies. There are multiple ISO codes for nearly every currency so it is really hard to say which one is the correct one. We do not choose in any case, it is handled by django-money and js-intl. Which are controlled by different entities.
It is standard to handle money with at least 4 decimalplaces - most systems actually use 11. Also keep in mind that this software handles electronics. Some passives do need the decimals as they are bought in huge quantities and the difference adds up quickly.

PRs to change the behaviour / make it more consistent are very welcome. I would not classify this as a bug as both displays are following (sometimes differing) ISO codes. So it is fairly low on the priority list.

**Comment by SchrodingersGat** [comment]
> P.S. Why inventree uses 4 decimal digits for stock money field, do we really need this precision? Only for BTC maybe?

- https://github.com/django-money/django-money#model-usage
- https://stackoverflow.com/questions/224462/storing-money-in-a-decimal-column-what-precision-and-scale/224866#224866

**Comment by SchrodingersGat** [comment]
@sintech pricing needs a major overhaul across the board. Standardization of displaying currency is going to be a big part of that, so thanks for reporting this ):

**Comment by sintech** [comment]
Hello @matmair thank you for the explanation. Now I see where "RUB" comes from (at least for js-Intl). When locale is set to 'ru' it returns `1 234,50 ₽` which is fine, but when it set to "en-US" it returns `RUB 1,234.50`. 
BTW, quick search by inventree source code revealed only 3 usages of "Intl.NumberFormat", so in all other places it comes from python?
@SchrodingersGat, thanks for the links, I fully understand why money should be stored in database with more decimals, but why display it in GUI?

**Comment by matmair** [comment]
@sintech 4 decimals are actual standard with the ordering software I use at work - I often see management solutions use 4 places. Not sure where it comes from but at least for electronics I think it makes sense.
