### ISSUE TITLE
[FR] Improve templates for bugs and feature requests

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3470]
I just saw awesome tempaltes and I think they should be adapted and then used here. Enforces the style and is a lot non-programmer friendly then the current template (wonder who made those 😇)

Qucik Ref: https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=feature-request&template=feature_request.yaml

I want to develop this.

**Comment by matmair** [comment]
@SchrodingersGat I would like to add 2 new labels to mark their status:
1) `triage:not-checked`
2) `triage:not-approved`

to mark that
1) a bug report/pr was not confirmed/looked at by any of the core team members
2) a FR or PR was not given the green-light by you
.

this would make it easier to see the status of bugs/FRs/PRs in one look. Optionally more `triage` labels could be added to show a state but these 2 should be sufficient for now.

**Comment by SchrodingersGat** [comment]
Looks like this would be a great improvement :)

**Comment by matmair** [comment]
I will look to get to it on the weekend.
