### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by guillaumesoucy94** [inventree/InvenTree#3471]
Hello, 

I'm trying to deploy Inventree. I'd followed all steps from here: https://inventree.readthedocs.io/en/latest/start/install/ and it give me that error when doing: invoke update

```
Traceback (most recent call last):
  File "/mnt/disk/inventree/src/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/disk/inventree/src/InvenTree/InvenTree/settings.py", line 86, in <module>
    STATIC_ROOT = config.get_static_dir()
  File "/mnt/disk/inventree/src/InvenTree/InvenTree/config.py", line 133, in get_static_dir
    raise FileNotFoundError('INVENTREE_STATIC_ROOT not specified')
FileNotFoundError: INVENTREE_STATIC_ROOT not specified
```

What I need to do to make it work?

Thank-you,

Guillaume

**Comment by matmair** [comment]
I transfered this issue as it is more fitting here.

**Comment by SchrodingersGat** [comment]
@guillaumesoucy94 I'm going to close this one out, but please feel free to ping us again here if you are still having any issues.

**Comment by guillaumesoucy94** [comment]
Hello, 

When sending `inv update`

`(env) root@inventory-dc:/mnt/disk/inventree/src/env# inv update
Installing required python packages from 'requirements.txt'
Requirement already satisfied: pip in ./lib/python3.10/site-packages (22.0.2)
Collecting pip
  Downloading pip-22.2.2-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 3.6 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-22.2.2
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
(env) root@inventory-dc:/mnt/disk/inventree/src/env#`

**Comment by SchrodingersGat** [comment]
Looks like you are running the command from the wrong directory.

cd up two levels to the same directory where tasks.py is located

**Comment by guillaumesoucy94** [comment]
Hello, 

I'd cd up two levels and this is what it returns me:

`(env) root@inventory-dc:/mnt/disk/inventree/src/env# cd ../../
(env) root@inventory-dc:/mnt/disk/inventree# inv update
Can't find any collection named 'tasks'!`

**Comment by SchrodingersGat** [comment]
You need to be in the root directory of inventree where **tasks.py** is located

**Comment by guillaumesoucy94** [comment]
The root directory is `/mnt/disk/inventree`

When I'd create the inventree user I'd put `/mnt/disk/inventree` instead of `/home/inventree`

**Comment by guillaumesoucy94** [comment]
Hello, 

I still need help.

Thank-you

Guillaume

**Comment by SchrodingersGat** [comment]
@guillaumesoucy94 please first locate the directory where `tasks.py` is located and run the invoke command from there.  

From your error message you are clearly not running from the right directory

**Comment by guillaumesoucy94** [comment]
@SchrodingersGat What is the easiest way to find that file?

**Comment by SchrodingersGat** [comment]
It is wherever you downloaded the inventree source code to

**Comment by guillaumesoucy94** [comment]
I downloaded to source code to /mnt/disk/inventree 

This is the directory listing:

`root@inventory-dc:/mnt/disk/inventree# ls -all
total 52
drwxr-x---  9 inventree inventree 4096 Aug  3 04:34 .
drwxr-xr-x  5 root      root      4096 Aug  3 03:52 ..
-rw-------  1 inventree inventree  847 Aug  3 04:34 .bash_history
-rw-r--r--  1 inventree inventree  220 Jan  6  2022 .bash_logout
-rw-r--r--  1 inventree inventree 3771 Jan  6  2022 .bashrc
drwxrwxr-x  3 inventree inventree 4096 Aug  3 03:55 .cache
drwxrwxr-x  2 inventree inventree 4096 Aug  3 03:53 data
drwxrwxr-x  6 inventree inventree 4096 Aug  3 03:56 env
drwxrwxr-x  3 inventree inventree 4096 Aug  3 04:07 .local
drwxrwxr-x  2 inventree inventree 4096 Aug  3 03:53 log
-rw-r--r--  1 inventree inventree  807 Jan  6  2022 .profile
drwxrwxr-x 10 inventree inventree 4096 Aug  4 15:15 src
drwxrwxr-x  2 inventree inventree 4096 Aug  3 03:53 static
root@inventory-dc:/mnt/disk/inventree#`

Is this could be a great idea to start over? I took a snapshot of the VM just after the fresh Ubuntu install.

**Comment by guillaumesoucy94** [comment]
what I need to do next?

**Comment by guillaumesoucy94** [comment]
Hello, 

I still need help. 

Thank-you, 

Guillaume

**Comment by SchrodingersGat** [comment]
@guillaumesoucy94 sorry I am not sure what else to say - I cannot tell you where you have put the files on your system.

Have a look at the image below - the `tasks.py` file is located in the top-level directory of the InvenTree project. Please ensure you are working from the directory that contains this file.

![image](https://user-images.githubusercontent.com/10080325/186124271-5941d2b6-9133-468c-a0e1-04b12b5d819e.png)

**Comment by guillaumesoucy94** [comment]
Hello, 

I start over, I add the static file and media root location in config.yaml and when running `invoke update` returns:

`Traceback (most recent call last):
  File "/usr/bin/invoke", line 11, in <module>
    load_entry_point('invoke==1.4.1', 'console_scripts', 'invoke')()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/lib/python3/dist-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/mnt/disk/inventree/src/tasks.py", line 96, in plugins
    plugin_file = get_plugin_file()
  File "/mnt/disk/inventree/src/InvenTree/InvenTree/config.py", line 150, in get_plugin_file
    plugin_file = get_setting('INVENTREE_PLUGIN_FILE', 'plugin_file')
  File "/mnt/disk/inventree/src/InvenTree/InvenTree/config.py", line 84, in get_setting
    cfg_data = load_config_data()
  File "/mnt/disk/inventree/src/InvenTree/InvenTree/config.py", line 56, in load_config_data
    data = yaml.safe_load(cfg)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/mnt/disk/inventree/src/InvenTree/config.yaml", line 8, column 1
expected <block end>, but found '<block mapping start>'
  in "/mnt/disk/inventree/src/InvenTree/config.yaml", line 129, column 2
`
tasks.py is now present:

![Screenshot at 2022-08-24 03-37-50](https://user-images.githubusercontent.com/22561876/186359522-1d79002b-c718-419a-b9f9-76c783ffee63.png)

Thank-you, 

Guillaume

**Comment by SchrodingersGat** [comment]
Clearly from the error message there is something wrong in your `config.yaml` file. Most likely a formatting issue. What did you change there? Specifically on the lines called out in the error log.

**Comment by guillaumesoucy94** [comment]
Hello, 

I specified the database information such as the credentials, the media root and the static root. 

I didn't touch the other files. 

I'd post my config.yaml file [here](https://plik.zsites.ca/file/662Awc9hP590MEKQ/Gt9vG1sCIFFjj3zR/config.yaml)

Thank-you,

Guillaume

**Comment by guillaumesoucy94** [comment]
Hello,

What should I do next?

**Comment by SchrodingersGat** [comment]
Remove these spaces.

![image](https://user-images.githubusercontent.com/10080325/187119870-491753d8-26e2-4a82-b5fc-a14ee6bddd3f.png)

**Comment by matmair** [comment]
@guillaumesoucy94 have you read the full installation guide? All your questions are answered there; Running as a service: https://inventree.readthedocs.io/en/latest/start/production/#install-supervisor

**Comment by guillaumesoucy94** [comment]
I just red it, thanks to pointing to that documentation. However, I do have another question. I did followed the instructions for development server, the link https://inventree.readthedocs.io/en/latest/start/production/#install-supervisor[https://inventree.readthedocs.io/en/latest/start/production/#install-supervisor](https://inventree.readthedocs.io/en/latest/start/production/#install-supervisor) refer to Production one, is those instructions could work with the development server or I will need to start over and going with the production server instead?

Regards,

Guillaume

**Comment by SchrodingersGat** [comment]
The production and development setup guides are intended for very different purposes. If you are looking for a production setup, follow the production guide.

**Comment by guillaumesoucy94** [comment]
Okay, I will do the setup again using the prod documentation.

 Will post again here if there anything.

Best regards,

Guillaume

**Comment by guillaumesoucy94** [comment]
Running Inventree in production mode now. 

Thanks!

Guillaume

**Comment by Zontex** [comment]
@SchrodingersGat @matmair I know it's old but I just came upon this issue and solved it. I did bare metal install with automated install script. apperently, it doesn't copy the config.yaml file into /opt/inventree/InvenTree so I had to take the config.yaml file from /etc/inventree/config.yaml and put it in /opt/ directory to fix the issue. then I could invoke update

**Comment by matmair** [comment]
That is not a `fix` - just a quick workaround.
The "right" and only place for the config is /etc/inventree - that is what the server uses. If you want to call invoke in a stable and predictable way use `inventree run cli` instead. Just copying the config file to /opt will break in any but the simplest installs.

**Comment by grabbat** [comment]
Anybody knows what is the default username and password?
The password in etc/inventree/admin_password.txt is not working. I change it as well with no luck. (reboot after)
So i'm using admin as username and password that is located in etc/inventree/admin_password.txt 
This is the 1st initial setup.
Any help is appreciated.
Thanks
