### ISSUE TITLE
[BUG] upgrade fails due to incompatibility of config.yaml in 0.7.X and 0.8.X

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3475]
**Describe the bug**

Previously I was on version 0.7.4 and wanted to upgrade to 0.8.X. I performed the upgrade as usual and received 502 error. while ensuring nothing wrong with the scheme or MySQL database I've decided to wipe the entire folder and clone the stable branch again. Same thing, 504 error. Then I realized that it might be something due to configuration.

I invoked debugging server and found out the images don't load (static / media) but confirming the location all seems correct. later on the way, I fixed it by copying the crucial information from config.yaml to the new template_config.yaml, I realized there are new options there such as remote_login_enabled and remote_login_header which didn't show up on 0.7.4 config, by setting them correctly I found out that this was the issue.

**Steps to Reproduce**

1. have a 0.7.X copy of inventree
2. pull the latest stable branch and invoke database backup
3. upgrade to 0.8.X but leave the previous config, the config.yaml from the previous installation of 0.7.4 will still exist.
5. get 504 error/assets not loading up

**Expected behavior**

The expected behavior is that the new values in the 0.8.X config will have default values, if not given, the defaults will be used. it seems that if emote_login_enabled and remote_login_header are not configured properly either they don't have default values or those values don't match the one in the config_template.YAML file.

By correctly setting those default values even if you upgrade without touching the config files your inventory system will still work as expected.

**Solution**

modify config_template.yaml from 0.8.x according to your needs and apply it, do not use 0.7.X config file.
later on to fix it there should probably be some check on those values and they should default if not set explicitly.

**Deployment Method**
- [ ] Docker
- [X] Bare Metal

**Comment by SchrodingersGat** [comment]
@Zontex thanks for raising this. Is it just the `remote_login_enabled` and `remote_login_header` ones that you had to disable?

**Comment by Zontex** [comment]
> @Zontex thanks for raising this. Is it just the `remote_login_enabled` and `remote_login_header` ones that you had to change? And what did you have to change them to specifically?

They didn't exist in the previous config.yaml from 0.7.4 so I just copied those parameters AS IS from config_template.yaml of version 0.8.0 and it fixed the problem.

**Comment by matmair** [comment]
@SchrodingersGat this seems to stem from the settings refactors - I am working on a fix; we should update the 0.8.0 image once we have confirmed the fix.

**Comment by SchrodingersGat** [comment]
@matmair sure LMK if you can replicate. I cannot seem to reproduce the issue on my end.

**Comment by Zontex** [comment]
> @matmair sure LMK if you can replicate. I cannot seem to reproduce the issue on my end.

Have you tried deleting remote_login_enabled and remote_login_header from your config.yaml at version 0.8.x?

**Comment by SchrodingersGat** [comment]
Yep I have tried exactly that. Currently running without issue

**Comment by SchrodingersGat** [comment]
Are you running in production or debug mode? And behind any other proxy / server / etc?

**Comment by Zontex** [comment]
Tried both production and debug mode
Production gives error while debugging doesn't load the static and media
content. Running on bare metal behind nginx proxy

**Comment by matmair** [comment]
@Zontex I now have tried to reporduce this with every release of 0.7.x to 0.8.0. I always tried on bare metal (debian buster) and pulled the branch into a fresh folder, set database, media and static folder and ran inv update. After checking it works I pulled 0.8.0 and ran inv update again.
Is there anything else you changed?

**Comment by Zontex** [comment]
> @Zontex I now have tried to reporduce this with every release of 0.7.x to 0.8.0. I always tried on bare metal (debian buster) and pulled the branch into a fresh folder, set database, media and static folder and ran inv update. After checking it works I pulled 0.8.0 and ran inv update again. Is there anything else you changed?

I don't think so. if you can't reproduce it, close it. maybe someone else will come up with duplicate of how they had this so this can be fixed? or perhaps wait for 0.9.0 update see if it happens to me again haha

**Comment by SchrodingersGat** [comment]
I'll close out for now but we will keep an eye on this for sure. We take stuff like this seriously! Please let us know if you gain any more insight into this.

**Comment by matmair** [comment]
@Zontex are you using environmental values by any chance? Maybe there is something set in your env that causes this
