### ISSUE TITLE
[FR] Add plugin keys, state and version  to version info

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3477]
We should include info about the plugin environment to make debugging that stuff easier.

I want to develop this.

Ref: https://github.com/inventree/InvenTree/issues/3355#issuecomment-1206532243_

**Comment by Zontex** [comment]
@matmair This sound like a brilliant idea. if the author of the plugin didn't confirm the plugin works for > X version and modified it accordingly to support, the plugin will be disabled by default and can't be re-enabled unless the version is modified.

**Comment by matmair** [comment]
@Zontex that might also be good but will most likely require a breaking change to the basic plugin metadata so the earliest this could be done is 0.9.x
Do you mind opening a issue for that?

**Comment by Zontex** [comment]
> @Zontex that might also be good but will most likely require a breaking change to the basic plugin metadata so the earliest this could be done is 0.9.x Do you mind opening an issue for that?

#3478
