### ISSUE TITLE
[FR] Plugins compatible version in metadata

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3478]
**Is your feature request the result of a bug?**

Might be if no other solution could work, bug: #3355

**Problem**

During major upgrades some plugins might break or will be unsupported, this is normal. WordPress, Firefox, Chrome, and major SaaS providers also define versions for each plugin/extension/addon to ensure consistency across versions.

There should be version control for plugins so that when an author creates a plugin, users could ensure such a plugin works for their build and won't break it.

**Suggested solution**

Define system supported version in metadata, if the plugin support < system version, disable the plugin by default, and when the user wants to enable it create a warning that this plugin was not designed for the newest version which might result in unexpected behavior.

**Describe alternatives you've considered**

None

**Examples of other systems**

WordPress, Firefox, Chrome etc ... all have versions for their plugins and compatibility list according to platform version.

**Comment by matmair** [comment]
Might be breaking so only next major

**Comment by matmair** [comment]
@Zontex this is currently already possible in the plugin itself as the API and InvenTree versions are exposed.

**Comment by Zontex** [comment]
> @Zontex this is currently already possible in the plugin itself as the API and InvenTree versions are exposed.

Yes but what I meant is that inventree need to read plugin compatible version and if inventree version != Plugin supported version, don't let the plugin to run. On the plugin such thing can be done to prevent running the plug-in if inventree version don't match but I doubt anyone will do that.

**Comment by matmair** [comment]
@Zontex my commercial plugins all do that - it is part of my licensing checks. So at least one person does ;-)

**Comment by matmair** [comment]
@Zontex there is a functioning PR for this in #3535 - it enables setting upper and lower version checks.
