### ISSUE TITLE
[BUG] About Inventree Dialog Doesn't Appear

### ISSUE THREAD

**Issue by spectre-ns** [inventree/InvenTree#3479]
**Describe the bug**
Clicking on the about inventree button on the home page does nothing after upgrading from 0.7.5 -> 0.8.0

**Expected behavior**
Dialog with inventree version appears

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
0.8.0 - I think

**Comment by spectre-ns** [comment]
Additionally, it seems that the installation is generally broken after updating from 0.7.5 to 0.8.0 there are several features I cannot see like the tree view in the build orders. I've reverted back to a previous state until 0.8.X is more stable.

**Comment by matmair** [comment]
@spectre-ns have you:
- run `inv update` after updating to the newest image
- hard refreshed your browser cache after doing that

**Comment by spectre-ns** [comment]
@matmair  I ran the following command from the documentation: 

```
docker-compose run inventree-server invoke update
```

**Comment by SchrodingersGat** [comment]
https://inventree.readthedocs.io/en/latest/faq/#feature-x-is-not-visible-after-update

Please try clearing the browser cache and report back :)

**Comment by spectre-ns** [comment]
Thanks @SchrodingersGat @matmair  that worked. Back running on 0.8.0! :)
