### ISSUE TITLE
[BUG] URL fields are not behaving correctly

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3482]
URL field length is apparently clipped at 125 characters:

- The "default" value here should be 200 characters as set by the django URLfield
- We should probably increase this to a larger default value

Also, the error message in the API forms is repeating multiple times:

![image](https://user-images.githubusercontent.com/10080325/183223851-d5698a91-5d78-453a-8c16-db3fa94a154c.png)

**Comment by SchrodingersGat** [comment]
Ok, *spooky discovery* time...

The `max_length` parameter in the following line changes the `max_length` for *all* `InvenTreeURLField` fields.

https://github.com/inventree/InvenTree/blob/e1d3392f3743f7813c0aba0705223f1442526ca7/InvenTree/stock/models.py#L648

**Comment by SchrodingersGat** [comment]
First step was to override the `InvenTreeRestURLField` model to enforce `max_length=250` - that fixed the API fields. However the database model fields were still limited to different lengths

So we need to force a migration for existing fields to update the tables columns.

*However* if you try to specify or change the `max_length` parameter on any instance of `InvenTreeURLField` and then run `invoke migrate` then there are no detected migration changes. 

Changing other field attributes (e.g. "verbose_name") does cause a new migration to be created.

@matmair any thoughts on this one?

**Comment by SchrodingersGat** [comment]
Changing `max_length` parameter on other fields *does* result in a new migration being created:

https://github.com/inventree/InvenTree/blob/e1d3392f3743f7813c0aba0705223f1442526ca7/InvenTree/company/models.py#L280

**Comment by matmair** [comment]
@SchrodingersGat that is interesting … might it be an issue with it being instanciated to early?

**Comment by eeintech** [comment]
Works great, thanks @SchrodingersGat !!
