### ISSUE TITLE
[BUG] Notification link to error message fails

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3483]
If an error occurs, a notification is provided to staff users.

However the URL reverse fails and causes a 500 error:

![image](https://user-images.githubusercontent.com/10080325/183224005-c87db580-2218-418a-8030-e268e2adc679.png)

Ref: https://github.com/inventree/InvenTree/pull/3431

Note: This seems to be related to https://github.com/inventree/InvenTree/issues/3355 - only saw this in the condition where the simpleactionplugin was enabled.

The proposed fix in https://github.com/inventree/InvenTree/pull/3484 also seems to address this issue.

**Comment by matmair** [comment]
@SchrodingersGat I have no idea why this stuff is all resulting from the app order; probably has to do with overwritten urls.
