### ISSUE TITLE
[BUG] Custom logo not displaying until user logs in

### ISSUE THREAD

**Issue by snorkrat** [inventree/InvenTree#3486]
**Describe the bug**
By default in the nginx config the media files in the media directory require user authentication.  This means that when you specify a custom logo it can not be seen in the login page as the user has not logged in/authed yet. 

**Steps to Reproduce**
1. Specify a custom logo in .env or config.yaml
2. Open incognito browser and go to login page
3. Logo is not displayed

**Expected behavior**
Logo is displayed

**Deployment Method**
- [ ] Docker

**Version Information**
InvenTree-Version: 0.8.0
Django Version: 3.2.14
Commit Hash: 6118d13
Commit Date: 01-08-2022
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Possible Solution**
Consider using a different folder for custom logos? Possibly `static/img` or a new `static/custom` directory

**Comment by SchrodingersGat** [comment]
@snorkrat very good point, custom images should be relative to the `static/` directory. Will have to look into this.

**Comment by SchrodingersGat** [comment]
@snorkrat should be fixed in master now

**Comment by matmair** [comment]
@SchrodingersGat depending on the name the file in static could be overwritten when `inv update` is run. Just a small caveat to look out for.

**Comment by SchrodingersGat** [comment]
Would be a good idea to put it in a custom subdirectory maybe...
