### ISSUE TITLE
[FR] Specify custom background image for login screen.

### ISSUE THREAD

**Issue by snorkrat** [inventree/InvenTree#3487]
**Problem**
Can not specify custom background image for login screen.

**Suggested solution**
Similar to how I can specify a custom logo in the .env or config.yaml, there could be an option to specify `custom_bg` and `custom_bg_large` to replace `paper_splash.jpg` and `paper_splash_large.jpg`

_However, as noted in https://github.com/inventree/InvenTree/issues/3486 these would need to be in the` /static ` folder or somewhere other than the `/media` folder as by default files in the media folder require user authentication, so the splash background would not be seen as a user has not logged in._ 

**Describe alternatives you've considered**
I have manually replace the `paper_splash.jpg` and `paper_splash_large.jpg` files in the `static/img` directory.

**Comment by matmair** [comment]
@snorkrat do you want to develop this? We are currently focusing on other parts of the project so it might take a while for anybody to get to this.

**Comment by SchrodingersGat** [comment]
Ref: https://github.com/inventree/InvenTree/pull/3489 - closely related issue which would help with implementing this feature.

**Comment by snorkrat** [comment]
> @snorkrat do you want to develop this? We are currently focusing on other parts of the project so it might take a while for anybody to get to this.

I don't really have any experience or know how to develop this sorry!
