### ISSUE TITLE
[FR] Update version from web interface

### ISSUE THREAD

**Issue by spectre-ns** [inventree/InvenTree#3494]
**Is your feature request the result of a bug?**
No

**Problem**
It would be nice if the updating process was wrapped up so the person running the system doesn't need to know docker commands and linux. There are Java based web application that permit this sort of operation from the web interface.

**Suggested solution**
Notify the user of when an update is available through the web interface (I think this is current functionality) and then allow the user to do a one click upgrade to the new version from the web interface

**Describe alternatives you've considered**
Alternative is running the docker commands... They're easy for someone who knows what's happening but it would be great if it were as easy as something like wordpress.

**Examples of other systems**
Jira, Confluence, Wordpress...

**Do you want to develop this?**
Sorry. I don't have the background to help on this one.

**Comment by matmair** [comment]
@spectre-ns this is not as easy as it sounds and not on the roadmap. PRs are welcome.

**Comment by SchrodingersGat** [comment]
> so the person running the system doesn't need to know docker commands and linux. 

The person *installing* the system does need to know either docker or linux commands and is typically the person charged with keeping the system up-to-date. 

A system which "automates" this exposes a lot of vulnerabilities and potential edge cases, and to non-technical users to boot.

**Comment by Zontex** [comment]
@spectre-ns check kubesail.com what you need is cloud container management software. as @SchrodingersGat and @matmair mentioned this is not as easy as it sounds and security will be a big concern.
