### ISSUE TITLE
[FR] Public link with SO reference to see order progress

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3502]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Currently, I have distributors that I need to fulfill hardware orders for them. I need to update them manually over the progress. it's all through emails / Github and very complex to let them know every time when we progress buying components etc, building, testing ...

### Suggested solution

it would be nice that once a sales order was made and associated with the build order and the order of the components there could be a public link to be shared with the distributor/customer so he/she/they could follow it at any time about their order.

### Describe alternatives you've considered

Sharing manually. or building my own react web app using inventree open API.

### Examples of other systems

I know it's not a good example but if you go to dominos pizza there is a "pizza tracker" that shows u the progress as it's baking, topping, packaging, and delivered ... eBay also has a similar thing now when you order from a buyer to see a progress bar of where the package is.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
I can see this being a very "customer specific" requirement. Different sorts of orders would need different information, would vary from customer to customer, etc.

I strongly feel this is in the realm of a plugin or external integration. All the data is there in the API!

**Comment by matmair** [comment]
@Zontex please consider to put an API gateway in front of your API if you plan to expose it to the world. This should at least implement throtteling and possibly also log connections for abuse and usage analysis.

**Comment by Zontex** [comment]
> @Zontex please consider to put an API gateway in front of your API if you plan to expose it to the world. This should at least implement throtteling and possibly also log connections for abuse and usage analysis.

Good idea, will definitely consider security when making this one. closing this for now as I agree with @SchrodingersGat
