### ISSUE TITLE
[FR] Add "RoHS" check button when adding a part

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3508]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Components have regulatory requirements to be RoHS compliant. Normally, need to go for each supplier component and see if it's RoHS compliant. need to collect all the certificates and then sign a deceleration form. Another option is to go with a testing facility to produce a test report for the hardware which might be costly.

### Suggested solution

Provide a "RoHS compliant" check switch button when adding a new part, once the check button checks it will offer to add a link to the certificate. In the BOM view can see clearly if one component is not mentioned to be RoHS compliant.

### Describe alternatives you've considered

Producing a test using facility and not caring about each component, they will tell you if any component is not correct.a 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
@Zontex this seems like the perfect use of a part parameter - or two (one for a simple boolean check and one for a link).
This would not add a special icon put you would see it in exports etc. As there are many different requirments for certitifactions implementing checks per certification could quickly become a feature creep source.

**Comment by SchrodingersGat** [comment]
I agree with @matmair here - the framework already exists to achieve what you want (parameters + attachments). Not everyone uses inventree for electronics, adding a specific ROHS attribute here does not fit with the "general purpose" nature of the software.

**Comment by Zontex** [comment]
Sounds fair @SchrodingersGat @matmair Parameters to go then !
