### ISSUE TITLE
[FR] Add an extra "Add BOM item" button in the bottom of the BOM list.

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#3514]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

When adding items to an already long BOM, it is necessary to scroll up to the top each time.

### Suggested solution

The "Add BOM item" button could be duplicated in the bottom of the BOM list, making it more intuitive to add more items when the BOM is very list.

### Describe alternatives you've considered

Scrolling up each time.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
This is a simple html / js thing to implement. Good first issue.
