### ISSUE TITLE
Build Order can be completed if "required build quantity has not yet been completed" only if at least 1 output defined

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3515]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

The flag "Accept Incomplete" for Build Orders seems not to work if there are no outputs - it does work when there is at least 1 output, however.

This is true for the API and the GUI. In the API, the POST data is:
```
{
    "accept_overallocated": false,
    "accept_unallocated": false,
    "accept_incomplete": true
}
```
error returned is the following:
```
{
    "non_field_errors": [
        "No build outputs have been created for this build order"
    ]
}
```

### Steps to Reproduce

1. Choose a Build Order which has zero completed outputs.
2. Set "Accept Incomplete" flag to true in Build Order complete window / post this flag as true
3. See the error:
![image](https://user-images.githubusercontent.com/1314853/183951952-75a32fa2-da40-46b0-9538-bd4eba27a52b.png)

Or in the API, error returned is the following:
```
{
    "non_field_errors": [
        "No build outputs have been created for this build order"
    ]
}
```

### Expected behavior

The flag is "accept incomplete", so I do not see a large difference between zero and 1 outputs.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 139e059a4
Commit Date: 2022-08-10
Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Active plugins: []

**Comment by SchrodingersGat** [comment]
@miggland nice report - now that we have the override for incomplete outputs it does not make sense to have this limitation.
