### ISSUE TITLE
Disable plugin signatures by default

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3520]
Plugin signatures lead to confusion. While I think it is very important for users that are concious of their supply-chain security most do not need it.

This should be hidden by default.
I want to dev this.

@matmair Thank you very much, now it's working.
But one thing is not clear to me, what is the purpose of this signature field? And how can I get my plugin a signature? 
![image](https://user-images.githubusercontent.com/76838159/184122182-5f8b0fe3-3327-4242-a9b3-fb8ee40c5466.png)

_Originally posted by @wolflu05 in https://github.com/inventree/InvenTree/discussions/3506#discussioncomment-3373793_

**Comment by wolflu05** [comment]
Why disabling it by default? I haven’t meant that, was just curious how I can get my plugin signed.

**Comment by matmair** [comment]
@wolflu05 this mainly confuses users, nothing specifically to do with your request.
