### ISSUE TITLE
[FR] Icons for stock locations

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#3522]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Having a big tree for storage locations can get quick very messy to differentiate between rooms/boxes/sections/...

### Suggested solution

It would be cool if we could assign each location a font awesome icon. To implement this, I have two ideas:
1. add a field to the `StockLocation` model and save the font awesome icon name in there
2. add a separate table where we can create presets of locations which can then be selected in the `StockLocation`. Suggestion for the `StockLocationPreset` table:
   | id | name| icon |
   | --- | --- | --- |
   | `0` | `garage` | `fas fa-garage` |
   | `1` | `warehouse` | `fas fa-warehouse-alt` |
   | `2` | `box` | `box-alt` |

The advantage of the second variant would be, that we can change the icons later without going through each location which has the box icon.

One further improvement of the second would be that we can add custom icons, because fontawesomes iconset is very limited what storage containers/locations concerns.

### Screendesigns

I Imagine this feature looking something like this: 
![image](https://user-images.githubusercontent.com/76838159/184429377-e6d804a0-9f95-452a-a183-29376f1481ca.png)

### Describe alternatives you've considered

\-

### Do you want to develop this?

- [X] I want to develop this.

**Comment by wolflu05** [comment]
@matmair what is your opinion on that? And second or first variant?

**Comment by matmair** [comment]
Hi there @wolflu05 sounds good to me.
I would strongly prefer option 1 as it keeps things a lot easier and the code base leaner. If this turns out to be a problem we can always switch to option 2 and create migrations.

Some pointers about implementation. I take error the first entry you would like to dev this.
My suggestion would be to start with the model and api and then do the frontend last.
- model field: A charField with a reasonable small max_length should be fine. Please add a translateable help_text and verbose_name
- include the field in admin
- include in api. Maybe filtering on the field would be cool too
- add the field to the stock location form api
- (optional) picker for the frontend-component. Maybe start out with a simple text field and add this later
- add icon to general stock location template
- change the dropdown rendering component for stock locations to include the icon

If you want feedback or need further pointers I would suggest to start a draft PR with the code first and then just ping  inventree/maintainer inventree/triage so we can work directly in the issue with you.

**Comment by matmair** [comment]
> @matmair what is your opinion on that? And second or first variant?

Sorry for the delay, needed to sort my thoughts on a good suggested implementation path

**Comment by wolflu05** [comment]
> > @matmair what is your opinion on that? And second or first variant?
> 
> Sorry for the delay, needed to sort my thoughts on a good suggested implementation path

@matmair Oh no problem, sorry that I was so impatient.


> I would strongly prefer option 1 as it keeps things a lot easier and the code base leaner.

i personally would really prefer option two, because we can easily change the icons if we want later all by one action. For my setup, I have a few different types of storage locations. As I wrote, the font awesome icons are very limited in stock type icons, so an upload would be cool. But I don’t know how this scales on db level, because this would always require a join to get the icon class/url.

**Comment by matmair** [comment]
@wolflu05 I do not really see enough added benefit in the added complexity.
My suggestion is to add this first just with fa and get it performant and fully tested.

**Comment by wolflu05** [comment]
Ok. An alternative for bulk updating would be to use RAW database queries like `UPDATE WHERE icon = "fas fa-box"`. Yeah, I'll try my best for a first implementation for variant 1.

**Comment by matmair** [comment]
@wolflu05 you could also do that with the shell and filter statements - would be a bit safer then SQL statments.

**Comment by wolflu05** [comment]
> @wolflu05 you could also do that with the shell and filter statements - would be a bit safer then SQL statments.

@matmair How do you mean?

**Comment by wolflu05** [comment]
One question for the implementation. Should we have a default icon (maybe a setting) or should we just omit the rendering of the icon in front of the name if no icon is set?

**Comment by matmair** [comment]
@wolflu05 I think no icon should be the default. A setting would be cool too.

> @matmair How do you mean?

python manage.py shell open an interactive python shell that enables you to work with the models -> that is a bit typo-safer then SQL

**Comment by SchrodingersGat** [comment]
> One question for the implementation. Should we have a default icon (maybe a setting) or should we just omit the rendering of the icon in front of the name if no icon is set?

Any change should (where possible) not change the user experience. So the default should be "no icon". A setting (default = off) to allow custom icons would be a good idea too.

This extra field should be added to the `InvenTreeTree` model (which is the parent class for both `StockLocation` and `PartCategory`) so we can add icons to both.

**Comment by wolflu05** [comment]
@SchrodingersGat Do you really think an icon is a typical behavior of a tree? I mean what if we later have a tree where ab icon doesn't make sense? I think I should implement this two times one time for StockLocation and one time for PartCategory.

**Comment by SchrodingersGat** [comment]
@wolflu05 I don't really mind either way - I just would like it to be implemented for both child classes!

**Comment by wolflu05** [comment]
@matmair @SchrodingersGat I created my first PR in #3542. Let me know what you think.
