### ISSUE TITLE
Permissions for receiving Purchase order line items are not implemented as expected

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3527]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I want my guy in the warehouse to be able to mark order lines as received, but not do everything in InvenTree (lock it down, less potential for mistakes ;))

However, I've given his user these permissions without the user being allowed to mark lines as received:
![image](https://user-images.githubusercontent.com/1314853/184329505-c5c0b39a-41fa-47e1-a83c-1fdf02f6a456.png)

The message is:
![image](https://user-images.githubusercontent.com/1314853/184329663-d2e1c274-7b83-4603-9aba-18427b938352.png)

Which create permission is required here?

### Steps to Reproduce

1. Set permissions as above for a certain user.
2. Attempt to receive items on a PO as that user
3. Fail.

### Expected behavior

InvenTree should allow a user with permissions to receive items..

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.0
Django Version: 3.2.14
Commit Hash: 6118d13
Commit Date: 2022-08-01
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
> 3. Fail.

Do you get an error message? Can you share a screenshot?

**Comment by miggland** [comment]
Yeah, the one above:
"Action Prohibited.
Create operation not allowed"

It's worded differently in the app, but is similar - permission denied.

-Martin

**Comment by SchrodingersGat** [comment]
You might need to add the "add" permission for purchase orders, for this to work? Please try that and report back

**Comment by miggland** [comment]
Yes, you're right, it works if I put the "add PO" permission.

However, does that make sense? I don't actually want this user to be able to add purchase orders..

**Comment by SchrodingersGat** [comment]
It "makes sense" in that it is the limit of granularity that the current permission system allows. To allow finer grained control of permissions would require us to expand the permissions system

**Comment by miggland** [comment]
So there's no way to change it to `change`permissions either?

**Comment by matmair** [comment]
It is consistent with the permission system as it adds an item to the PO when an item is received.

@miggland  A more granular permission system would be nice but require a more general look at that stuff. There is a ref for this - any work as appreciated #2323

**Comment by miggland** [comment]
> It is consistent with the permission system as it adds an item to the PO when an item is received.

Does it? I thought receiving only added stock items, and changed the PO line item..

**Comment by matmair** [comment]
@miggland it also adds an entry to a lookup table that belongs to PO. That way you can see from which PO an stock item stems.

**Comment by miggland** [comment]
> @miggland it also adds an entry to a lookup table that belongs to PO. That way you can see from which PO an stock item stems.

I can only see that information in the stock section - can you point me to where the table is you're referring to? (I'm trying to understand how the system works :) ) Thanks!

**Comment by matmair** [comment]
@miggland it is a database table.
The info is surfaced in stock tracking 
![grafik](https://user-images.githubusercontent.com/66015116/184670949-6b8828c7-ebc9-40a7-8b6a-b1288bdd3fe3.png)
or in the part table
![grafik](https://user-images.githubusercontent.com/66015116/184671080-609ab55c-408a-4ce4-be40-0464f473474a.png)

**Comment by matmair** [comment]
@SchrodingersGat can we mention the permission thing in the docs and close this as `wontfix`?

**Comment by miggland** [comment]
> @miggland it is a database table.

Yes, I understood that.. I had a look through what I can see in the admin section, and only find that data in `stock items` table - not in the PO itself.

That's why I feel the relevant permission should be 'add stock`, not `add PO`...

**Comment by miggland** [comment]
See https://github.com/inventree/inventree-docs/pull/358

I still think it could be better, but let's drop this. Improved permissions, as in #2323, are the better solution
