### ISSUE TITLE
Label text looks weird if multiple labels are printed.

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3528]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When printing multiple labels to a PDF, the text includes spacing. When printing a single PDF, this does not occur.

Example with the built-in part label template `Barcode Part Label - Simple part label with Code128 barcode`:
One label created:
![image](https://user-images.githubusercontent.com/1314853/184400791-5dba0cf4-28e1-43ac-8b8f-38f926eb9124.png)

Two labels created:
![image](https://user-images.githubusercontent.com/1314853/184400846-7de74142-ea1b-4f05-aaca-97671625a3bc.png)

Example with a stock item template I made. These use the same template, but in one I call:

Output with one single label:
![image](https://user-images.githubusercontent.com/1314853/184399658-e9f4caad-ca77-44c4-a08a-2510f4e4f8bb.png)

Output with multiple labels:
![image](https://user-images.githubusercontent.com/1314853/184399778-4381fa89-da76-43d8-9c4b-ea4f8723920d.png)

The fact that some lines are missing is not a problem, that is due to the template. However, where is the spacing from?

### Steps to Reproduce

1. Print label with text for one part.
2. Print label with text for several parts at once.
3. Compare, and see that it looks weird in one case.

### Expected behavior

The output should look the same regardless of whether I create multiple labels at once or not.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 139e059a4
Commit Date: 2022-08-10
Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Active plugins: []

**Comment by miggland** [comment]
I tried seeing what happens by going to debug mode, but that unfortunately puts the second label on top of the second label so doesn't really help..

**Comment by nwns** [comment]
I am seeing the same sort of issue with 0.8.1 running on bare metal (Debian 
Bullseye (11)).
![image (2)](https://user-images.githubusercontent.com/10690911/184453457-9317ac1f-64e3-454b-b7f8-514a2f0624d6.png)
![image (1)](https://user-images.githubusercontent.com/10690911/184453461-1af2245e-5205-4110-bd5c-576e63a6fdeb.png)
![image](https://user-images.githubusercontent.com/10690911/184453462-25e31651-c572-4276-90a3-bd38084efaaf.png)


My system information is not copy and paste able for some reason.
![image](https://user-images.githubusercontent.com/10690911/184453296-bf6c6590-f9ec-4d80-b9e8-51ffe864835b.png)
```
arrow==1.2.2
asgiref==3.5.2
Babel==2.10.3
bleach==5.0.0
blessed==1.19.1
Brotli==1.0.9
certifi==2022.6.15
cffi==1.15.0
charset-normalizer==2.0.12
cli-helpers==2.2.1
click==8.1.3
configobj==5.0.6
coreapi==2.3.3
coreschema==0.0.4
cryptography==3.4.8
cssselect2==0.6.0
defusedxml==0.7.1
diff-match-patch==20200713
Django==3.2.14
django-allauth==0.51.0
django-allauth-2fa==0.10.0
django-cleanup==6.0.0
django-cors-headers==3.13.0
django-crispy-forms==1.14.0
django-error-report==0.2.0
django-filter==22.1
django-formtools==2.3
django-import-export==2.5.0
django-js-asset==2.0.0
django-maintenance-mode==0.16.3
django-markdownify==0.9.2
django-money==2.1.1
django-mptt==0.11.0
django-otp==1.1.3
django-picklefield==3.1
django-q==1.3.9
django-redis==5.2.0
django-sql-utils==0.6.1
django-sslserver==0.22
django-stdimage==5.3.0
django-user-sessions==1.7.1
django-weasyprint==2.1.0
django-xforwardedfor-middleware==2.0
djangorestframework==3.13.1
et-xmlfile==1.1.0
fonttools==4.33.3
gunicorn==20.1.0
html5lib==1.1
idna==3.3
importlib-metadata==4.12.0
itypes==1.2.0
Jinja2==3.1.2
Markdown==3.3.7
MarkupPy==1.14
MarkupSafe==2.1.1
oauthlib==3.2.0
odfpy==1.4.1
openpyxl==3.0.10
pdf2image==1.16.0
pendulum==2.1.2
pgcli==3.4.1
pgspecial==1.13.1
Pillow==9.1.1
pkg_resources==0.0.0
prompt-toolkit==3.0.30
psycopg2==2.9.3
py-moneyed==1.2
pycparser==2.21
pydyf==0.2.0
Pygments==2.12.0
PyJWT==2.4.0
pyphen==0.12.0
python-barcode==0.14.0
python-dateutil==2.8.2
python-fsutil==0.6.1
python3-openid==3.2.0
pytz==2022.1
pytzdata==2020.1
PyYAML==6.0
qrcode==7.3.1
rapidfuzz==0.7.6
redis==3.5.3
requests==2.28.0
requests-oauthlib==1.3.1
sentry-sdk==1.6.0
setproctitle==1.3.2
six==1.16.0
sqlparse==0.4.2
tablib==3.2.1
tabulate==0.8.10
tinycss2==1.1.1
uritemplate==4.1.1
urllib3==1.26.9
wcwidth==0.2.5
weasyprint==55.0
webencodings==0.5.1
xlrd==2.0.1
xlwt==1.3.0
zipp==3.8.0
zopfli==0.2.1
```

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/blob/427404b3bafaec50a17836c864be3f89baaef58c/InvenTree/label/api.py#L161

I would imagine it is due to this line here. Weird. I'll try to reproduce on my end.

**Comment by SchrodingersGat** [comment]
I can reproduce pretty easily. The issue *may* be one of the following:

1. Something about the HTML template which is causing issues around page-breaks
2. An upstream issue with weasyprint

If I had to put money on it, probably 1

**Comment by matmair** [comment]
@nwns 
Question: Are you experiencing the copy problem on ther server info or about screen?
Note: Only the about screen contains copy buttons

**Comment by nwns** [comment]
I would tend to agree that the issue is related to how Inventree merges the separate labels.

In my experimentation trying to figure out what the cause was I tried replacing the substitution with static text and the text came out fine.

@matmair That would be what is it.  I was on the server information screen not the about screen.

**Comment by SchrodingersGat** [comment]
@nwns I tried out a few different ways of merging the pages but all with the same outcome. 

If you can work out the key to getting the rendering right please let us know

**Comment by miggland** [comment]
Fast, as usual @SchrodingersGat ! Nice work.

Works for me (after `invoke update` so that the weasyprint version is corrected).

**Comment by SchrodingersGat** [comment]
> Works for me (after invoke update so that the weasyprint version is corrected).

You can also append the old weasyprint version into your `plugins.txt` file - this way it will override the default version :)
