### ISSUE TITLE
[FR] View image attachments inline

### ISSUE THREAD

**Issue by kes999** [inventree/InvenTree#3529]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Not a bit thing, but to have more images of a part I've tried to upload them as attachments, but when viewing them they get downloaded.

### Suggested solution

 Would maybe be better to show image attachment inline in the browser?

### Describe alternatives you've considered

Download and view on computer.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
This is by design for security reasons - allowing attachments to auto-open in the browser can cause potential security issues if it is a malicious file.

Can you right-click-open-in-new-tab for the imgae?

**Comment by matmair** [comment]
@SchrodingersGat should we tag this wontfix ?

**Comment by kes999** [comment]
As long as this is a security concern, I'm totally fine with closing this, I'm also certain there are more pressing issues than this. However for my (edge?) use case; I have pictures of parts from different angles. If more image handling were to be considered in the future, maybe an idea is to have an own Image "category" (where the Notes, Attachment and so on is) where image files could be handled even cooler :) Keep up the good work, impressed with InvenTree so far!
