### ISSUE TITLE
[FR] Tie github actions to specific commit hashes

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3530]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

It would be a good idea to tie every external github action to a specific git commit hash to prevent potential supply chain attacks.

### Suggested solution

tie every external github action to a specific git commit hash 

### Describe alternatives you've considered

Leave the project vulnerable to malicious agents to push new versions of the actions

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
@SchrodingersGat on it.
