### ISSUE TITLE
[FR] Add email link based logins

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3531]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

We currently have no password-less forms of logging in

### Suggested solution

Implement magic links like slack provides.
Ref: https://github.com/aaugustin/django-sesame

### Describe alternatives you've considered

Allauth options are also good for now

### Examples of other systems

Slack

### Do you want to develop this?

- [X] I want to develop this.

**Comment by rkalman** [comment]
Using WebAuthn can be a good alternative for passwordless logins.
https://github.com/inventree/InvenTree/issues/2326#issuecomment-1299080622

**Comment by matmair** [comment]
@rkalman WebAuthn has nothing to do with link based logins (often called magic links) and should be its separate FR if you want it.

WebAuthn is an additional factor for login while link-based logins replace the login entirely with a mail with a short lived token for single-use login. The first is used to add security while the latter is mostly used for users that seldomly use a platform.
