### ISSUE TITLE
[FR] Make AppMixin plugin loading more flexibel

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3534]
# Issue
AppMixin plugins have to be contained in a package named the same as the `NAME` of the plugin.

# Solution
Make it dynamically register the packagename and use that to load the AppConfig - Maybe even make the name of the AppConfig configurable in the plugin.

# Ref
@wolflu05 I checked out the issue and the behaviour for packages is hard-coded right now.
That has no technical reason - it just reflects that I build plugins around my workflows - in which `NAME` and package-name are atomically the same.

We can only change it in `0.9.9` as it will be breaking but I think we can change it till then. There are at least a few changes lined up for plugins so it does not hurt.

_Originally posted by @matmair in https://github.com/inventree/InvenTree/discussions/3523#discussioncomment-3391097_

**Comment by matmair** [comment]
Reference to the the line causing the issue: https://github.com/inventree/InvenTree/blob/427404b3bafaec50a17836c864be3f89baaef58c/InvenTree/plugin/registry.py#L574

**Comment by wolflu05** [comment]
@matmair does this should also fix the migraions?

**Comment by matmair** [comment]
@wolflu05 no - it only covers what is stated. If you have a seperate request that should be filed in a seperate issue.

**Comment by wolflu05** [comment]
> @wolflu05 no - it only covers what is stated. If you have a seperate request that should be filed in a seperate issue.

@matmair I mentioned that in #3523.

**Comment by matmair** [comment]
@wolflu05 #3523 is a general question about persistance. If we need to fix something file an issue. We have a lot on our plate and especially I tend to forget about things if they do not have a dedicated todo.
![grafik](https://user-images.githubusercontent.com/66015116/184670234-e2a16697-1845-449e-ad53-2f2925fdcc8f.png)
You just have to click on the options of a thread and file a new issue.
