### ISSUE TITLE
[BUG] Ordering of purchase orders by reference is wrong

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3544]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When ordering by reference, the output order is not as expected. See example, where the last PO is in the wrong place. It was created after the rest, for historical reasons, but this should not affect the ordering IMHO:

![image](https://user-images.githubusercontent.com/1314853/184645130-e1e5146d-6355-4b2c-96ca-496747f54ca7.png)

Another example, from the test system (which is on the newest version):
![image](https://user-images.githubusercontent.com/1314853/184645666-11aa839d-6600-4c76-9dc0-f287634ab6d0.png)

### Steps to Reproduce

1. Go to purchase order page
2. Order by reference
3. Maybe see wrong order, depending on style of references used?

Same result in the API as in the GUI.

### Expected behavior

I would expect alphabetical ordering, ie that "PO3112-.." comes first in the list and not last as in the example.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 956701a58
Commit Date: 2022-08-15
Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Active plugins: []

**Comment by matmair** [comment]
I can not reproduce this:
![grafik](https://user-images.githubusercontent.com/66015116/184720799-ab5d0df4-bd32-405d-a729-2b19878cfc5a.png)
# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 956701a
Commit Date: 2022-08-15
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by miggland** [comment]
Can you create a Po called PO-0010, then one called PO-0007 and try again?

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/184808642-a341ddd7-ea58-4f69-81da-43d901921769.png)

Just tried this on the demo server.

Only thing I can think of is that perhaps your purchase order reference formatter is messing with this. What do you have configured for your "Purchase Order Reference Pattern"?

![image](https://user-images.githubusercontent.com/10080325/184808743-e1c50923-7a39-452b-ab76-6535a4772917.png)

**Comment by miggland** [comment]
The thought did occur to me after I posted that.

In the first case, I have this: `PO{ref:04d}-????`. However, this was changed after creation of most of the POs.

In the other case, it is set to: `PO-{ref:01d}-?`. If I change to `PO-{ref:04d}` I get the same order, however.

**Comment by SchrodingersGat** [comment]
@miggland so the "ordering" of reference fields here is somewhat obscured. Basically in the background InvenTree attempts to convert your reference value (which is a string) to an integer, for better natural sorting. 

What *might* be happening here is that the integer conversion is not working properly. Could you run the following (open a shell inside your docker container):

```bash
cd InvenTree
python ./manage.py shell
```

```python
from order.models import PurchaseOrder

for po in PurchaseOrder.objects.all():
    print(po.reference, po.reference_int)
```

And post the results back hereA?

**Comment by miggland** [comment]
Hi, that makes sense - and ordering by the ref part of the defined PO pattern is what makes most sense.

One of these is wrong, which is reflected in the order of the POs:
```
PO3113-5512 3113
PO3121-5501 3121
PO3119-5501 3119
PO3120-5501 3120
PO3128-5531 3128
PO3125-5501 3125
PO3132-5532 3132
PO3122-5501 3122
PO3124-5501 3124
PO3115-5526 3115
PO3123-5501 3123
PO3126-5512 3126
PO3130-5526 3130
PO3129-5526 3129
PO3116-9999 3116
PO3127-5512 3127
PO3112-9999 9999
PO3134-5501 3134
```

What I don't understand is why.

I have tried a few difference reference patterns in the settings, all with the same result - however, the settings page shows me weird stuff. Without changing anything, it sometimes looks like this:

![image](https://user-images.githubusercontent.com/1314853/184862233-cd1b8b5d-3841-4f4d-9045-9673d618cb9d.png)

![image](https://user-images.githubusercontent.com/1314853/184862201-36e7bbd2-59cd-4cfc-ad5e-4926a87d61ec.png)

**Comment by miggland** [comment]
This is the output from the other case, my dev/test server:
```
PO-0001 0
PO-0002 0
PO-0003 0
PO-0004 0
PO-0005 0
PO-0006 0
PO-0007 0
PO-0008 8
```

**Comment by SchrodingersGat** [comment]
Try re-saving one of the orders which has an invalid reference_int field - and see if it gets recalculated.

**Comment by miggland** [comment]
Yes, re-saving even without changing anything seems to solve this. Probably the recalculation should be triggered if the reference pattern is changed?

**Comment by SchrodingersGat** [comment]
@miggland might be a weird edge case - I have updated multiple systems without negative impact... Are you happy to re-save any weird ones and move on? :)

**Comment by miggland** [comment]
You mean changing the reference pattern is a weird edge case? With it just recently introduced, I expect this to appear a bit more often. However, you may be right in the future..

But yeah, fine with me. The next user to have this problem will hopefully find this issue and not have too many orders to re-save :)
