### ISSUE TITLE
[FR] Low Stock items, filter on-order

### ISSUE THREAD

**Issue by axibo-reiner** [inventree/InvenTree#3550]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

When we are ordering parts when we get a low stock notification we cannot see if the parts have already been ordered until they are clicked on. 

### Suggested solution

Allow filtering out parts that are on order in the low stock table. 

Also it is worth noting that on-order is a label, but they display of the label is overwritten by the low-stock label. Low stock label cannot be rectified until stock is received. 

### Describe alternatives you've considered

Currently we have a python script that checks what is low stock and checks if it is on order and prints it out 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
General comment: I do not really see a problem here, the notification and label are for low stock - until the inventory is received your stock is low. You can not build with something that is not in your warehouse.

Implementation comment: Look-ahead fields can be implemented but come with a certain penalty in regards to speed so I would be careful with adding a straight lookup.

Development: Maybe the maintainer has an interest in developing this, I currently have no use for this feature and will not develop it.

**Comment by SchrodingersGat** [comment]
@axibo-reiner you are talking about these badges here?

![image](https://user-images.githubusercontent.com/10080325/184810275-edc6c49a-ac84-40ef-bc4d-01f533f8a956.png)

I would suggest that instead of having a single display badge for "on order" or "low stock" the badge system gets updated to have multiple smaller icons with hover-over text. This way it can display more information.

**Comment by SchrodingersGat** [comment]
e.g. how we currently show "on order" quantity in the BOM table is a lot neater:

![image](https://user-images.githubusercontent.com/10080325/185015338-35b309ed-323f-426d-a72e-31ca3bbe5f6d.png)
