### ISSUE TITLE
Horizontal scrolling in Firefox

### ISSUE THREAD

**Issue by tedd-wq** [inventree/InvenTree#3569]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Some pages have horizontal scrolling in Firefox. The same page in Edge, for example, does not.

Edge browser: 
![Edge](https://user-images.githubusercontent.com/49110506/185373102-ce6254d9-2a95-4fa5-a7eb-a833e1a9a0d2.png)

Firefox browser: 
![Firefox Left](https://user-images.githubusercontent.com/49110506/185373113-1c8aac18-7279-40d9-9d40-dd445c726f6d.png)
![Firefox Right](https://user-images.githubusercontent.com/49110506/185373111-c2e727c0-19e8-428c-83ff-64cb525ea7f6.png)

### Steps to Reproduce

See images.

### Expected behavior

No horizontal scrolling in Firefox, same as the other browsers.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.1
Django Version: 3.2.15
Commit Hash: fb97385
Commit Date: 2022-08-08
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by miggland** [comment]
I've seen the scroll bar appear in Chromium on Linux, on a page were it doesn't appear in Firefox.

IMO, horizontal scrolling is fine, however.. better than making the table columns so narrow they can't be read.

**Comment by matmair** [comment]
Can reproduce. Not really sure what is causing this, it is exactly the same CSS.
As far as I can see all the info is there on either site, the info is just spread differently.

**Comment by tedd-wq** [comment]
> IMO, horizontal scrolling is fine, however.. better than making the table columns so narrow they can't be read.

I agree. However, both Edge and Firefox are already showing a horizontal scrollbar in the table. That's fine.

Inventree in firefox scrolls the entire page. The top bar is the right width, but nothing else is.

**Comment by miggland** [comment]
Can you clarify in your original post which image is from which browser?

**Comment by tedd-wq** [comment]
> Can you clarify in your original post which image is from which browser?

Done

**Comment by fireboyff** [comment]
Hi
in Google Chrome Vers. 103.0.5060.134 and Microsoft Edge ist it the same problem. Running on Windows 10.
lg Fire
