### ISSUE TITLE
Virtual items don't show stock level in list, but do on its own page

### ISSUE THREAD

**Issue by tedd-wq** [inventree/InvenTree#3570]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Looking in the list of parts in a category, a virtual part has a stock level of 0, whereas on the page for the virtual part, the stock level correctly shows the level as a sum of all real parts. Screenshots from the demo server shown. Version information below also from the demo server.

![2022-08-18 20_54_21-InvenTree Demo Server _ Part Category - Furniture_Chairs - — Mozilla Firefox](https://user-images.githubusercontent.com/49110506/185378949-c72bf333-76ca-424d-8846-d753894a41a0.png)
![2022-08-18 20_54_44-InvenTree Demo Server _ Part - Chair — Mozilla Firefox](https://user-images.githubusercontent.com/49110506/185378958-3cfceb15-9561-4a67-a78d-a323a3decaeb.png)

### Steps to Reproduce

See images

### Expected behavior

Virtual part stock levels to be consistent whether looking at the part list or part details.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 7384a85
Commit Date: 2022-08-18
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
@tedd-wq thanks for the report. It is not an issue with virtual parts. Instead, "variant" stock is not correctly being shown in the table.
