### ISSUE TITLE
Welcome Github workflow has error

### ISSUE THREAD

**Issue by tedd-wq** [inventree/InvenTree#3571]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Reporting my first issue, I got an email from Github saying that a 'welcome workflow' had failed.
![2022-08-18 21_01_51-Horizontal scrolling in Firefox · inventree_InvenTree@7384a85 — Mozilla Firefox](https://user-images.githubusercontent.com/49110506/185379927-7519a5d2-9634-4111-b227-db52d1cc2b0a.png)

### Steps to Reproduce

Report your first issue on Inventree github.

### Expected behavior

Don't send me emails.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

Irrelevant

**Comment by matmair** [comment]
Seems to be related to the default permission setup with new contributors before the first successful commit.

**Comment by matmair** [comment]
@tedd-wq thanks for the report

**Comment by SchrodingersGat** [comment]
As this action has now been removed, I'm closing this out.
