### ISSUE TITLE
`AppMixin` plugin requires a `Meta` class with `app_label`

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#3588]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

After the changes from #3535, my plugin doesn't load anymore, but instead with the following error in the plugin error stack:
```
discovery | django | Model class inventree_bulk.models.BulkCreationTemplate doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

I guess this has something todo with a wrong configuration, but I cannot see where. This is my plugin [repo](https://github.com/wolflu05/inventree-bulk-plugin/tree/dev).

If I add a `Meta` class with an app label, this error is gone and the plugin loads without issues, but how do I get it working without that extra meta class like it was working before these changes?

_originally commented at https://github.com/inventree/InvenTree/pull/3535#issuecomment-1220751210, but this was the wrong place, as this is a real new issue, not just a simple further question_

### Steps to Reproduce

1. Create an `AppMixin` plugin
2. Add a model without a `Meta` class
3. Load the plugin to inventree
4. Goto Settings > plugins 
5. See error stack

### Expected behavior

Plugin should load correctly without a `Meta` class like it was before #3535

### Deployment Method

- [X] Docker
- [X] Bare metal

### Version Information

```
# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: b886e5470
Commit Date: 2022-08-19
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'CupsLabels', 'slug': 'cups', 'version': '0.1.0'}]
```

**Comment by SchrodingersGat** [comment]
@matmair do you have any insights here? What did you change in #3535 in particular which may have caused such issues?

**Comment by matmair** [comment]
@SchrodingersGat it fixed the way App names are computed, before there could be a missmatch between the packagename and appeared - that lead to collisions with 3rd party modules. The PR changed it to follow Django standards as I understand them.
Adding a Meta class to them model should fix this issue.

**Comment by SchrodingersGat** [comment]
@wolflu05 is it an acceptable solution to simply add a metaclass to your plugin? I think this would be the simplest way to move forward here.

**Comment by wolflu05** [comment]
@SchrodingersGat Yeah that is also fine if this is now the intended way of doing it. Thank you very much for resolving those two issues. No I can continue develop my plugin if I had some more time. We can close this from my side.
