### ISSUE TITLE
[FR] Allow using special characters in names of parameters (templates)

### ISSUE THREAD

**Issue by MR-DOS** [inventree/InvenTree#3589]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

When adding parameter templates it's not possible to use any characters other than [a-z][A-Z][0-9]. I only started adding templates for transistors and operational amplifiers and I already have 114 necessary parameters. Given that I cannot use ",.()[]{}/*", it's impossible to write hints into the parameter names. For example,now I need a parameter with unreadable name "dVbrdss divided by dTj". If I could insert symbols for derivation and slash, everyone would know what I mean. Or if I could add "(dependence of breakdown voltage on junction temperature)", it would also be obvious. Obviously, I can't since parentheses are disallowed so all I could get is unreadable and even more mysterious junk.

### Suggested solution

Allow using any ASCII characters (OK, no BEL and other funny things) in names of parameters.
Even better, allow UTF-8 entry.

### Describe alternatives you've considered

At least allow usage of ",.()[]{}/*" in names of parameters since these are often required for electronic components.

### Examples of other systems

Well, in Inventree, you can write those symbols just about anywhere including the parameter values, just not their names. So if it already works in most of Inventree, it could work here as well.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by wolflu05** [comment]
What a about a new field hints or description for a parameter template? This could then be visible on hover or an own column in the table.

**Comment by MR-DOS** [comment]
That's a possibility. But doesn't solve the issue that there are many parameters which use "/()" symbols, whether it's some coefficient or a note which describes conditions of test. Not being able to write subscripts is also a pain, but one which electrical engineers have to deal with everyday. And also, there is only 2 ways how to separate parts of parameter name, either space or mixing large and small characters. At least having parentheses would help.

Here is an example of some of parameters I use to show how problematic this may be for using InvenTree for electric components (currently, I have 120 separate parameters and that's maybe 1% of my stock being recorded).
![image](https://user-images.githubusercontent.com/29711626/186250239-b71b132c-51c6-4c8a-af39-9200ac166a55.png)

**Comment by matmair** [comment]
We are happy with looking at PRs @MR-DOS .
The current system is a result of frontend collisions but if you come up with a solution it could be done. Validation is done here but the real challenge is to not break the frontend
https://github.com/inventree/InvenTree/blob/a3392ea4b1675c0439157ccf1e065a801942e2c5/InvenTree/part/models.py#L2370

All ASCII or UTF8 characters are not going to happen - that would be a security concern.

**Comment by MR-DOS** [comment]
Well, this is a slightly embarrasing situation. That function really doesn't handle text correctly in any way. It allows the use of ASCII control characters, ":;" and DEL. It also has no abilities to block UTF-8.
So, now that we know that UTF-8 works, maybe we could also drop some of that false sense of security and allow the normal ASCII characters? After all... values of parameters can have all characters, why not names of parameters? Is it really handled so differently?
But for me, I have a working solution. Not good, but working. Imitating symbols I need with similar UTF-8 symbols.
![image](https://user-images.githubusercontent.com/29711626/186276967-9d196214-0681-43bc-a2b2-95616c0aaf6f.png)

**Comment by matmair** [comment]
@MR-DOS I don't think we are talking about the same security issues. ASCII characters per se are no issue. There is a specific subset that could be used to run [XSS](https://owasp.org/www-community/attacks/xss/) attacks. And those security measures work on stable:
![grafik](https://user-images.githubusercontent.com/66015116/186277818-e0592062-0cb5-4652-92c9-18b498be0ad4.png)

The only thing embarrassing here is your tone in a free - as in beer - project with NO warranty or monetary charges.

**Comment by matmair** [comment]
You are free to look into the code and discover that the names are used as references in JS.
If you do not have a productive change in mind I do not see this getting any work from my side. Maybe someone else is willing to pick this up.

**Comment by MR-DOS** [comment]
Well, sorry for my tone. But if the XSS script is a concern in name of the parameter, why not in its value?
![image](https://user-images.githubusercontent.com/29711626/186278603-fdba1f2c-19f6-4e00-96d4-515544cdc4a8.png)

**Comment by matmair** [comment]
There is also protection against XSS in the value fields. I attached a screenshot of that too now.
Nearly every field is tested for XSS before entry into the database. This is part of the general model setup. SQL unsafe special control characters are also generally escaped.
![grafik](https://user-images.githubusercontent.com/66015116/186279436-f8f423fb-d548-415d-8dc6-bad75d482ec1.png)

**Comment by MR-DOS** [comment]
Sorry for my tone.
OK, I will leave with using UTF-8 to emulate the forbidden characters.

Still, I would think that if at least "<>" are forbidden, then no HTML tag for XSS injection can be created and thus the other symbols could be allowed. After all, ":;" are considered to be harmless in that function while they are also used and necessary in some XSS code. But I may be wrong, never worked with JS / SQL and so on.

I had a somewhat productive change in mind (depends on point of view) - making Inventree parameters useable for parameters of electronic components without a lot of head scratching. If that can't be, OK, just wanted to know. I first searched the documentation, but could not find any mention of these artificial limits which was mainly why I wanted to find out why it behaves so.

And thanks for the tip to read the whole codebase before asking. Will do that next time.

**Comment by SchrodingersGat** [comment]
@MR-DOS an update to what characters are allowed here would be fine. I'm going to re-open this as a I think it is a valid development target. Would you be willing to work on this?

I would also suggest that we add a "description" field for the PartParameter model as suggested by @wolflu05 

On a related note - I have a parallel PR for removing non-printable characters on the client side: https://github.com/inventree/InvenTree/pull/3591

**Comment by wolflu05** [comment]
The question from my side is, why are you permit the usage of <> instead of escaping them and use the id for reference?

**Comment by MR-DOS** [comment]
@SchrodingersGat Hi. Sadly, I specialise on hardware and don't consider myself a good programmer. Given that this issue revolves around security holes in XSS / JS /SQL (which I know nothing about), I believe any modification from my side would probably lead to severe hazards. If it were good old embedded system programming, I'd happily give a helping hand :-)

I tested some of the non-printable ASCII characters and they usually show in the editing field, but do not show up once saved. Some cannot even be inserted, probably due to the nature of the editing field (like LF).

The description field sounds like a good idea for me.

**Comment by matmair** [comment]
@wolflu05 this is a grown system, it was originally implemented this way. The limited resources are currently spent on more pressing issues.
