### ISSUE TITLE
Avoid Build order for subassembly

### ISSUE THREAD

**Issue by gunstr** [inventree/InvenTree#3606]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Thanks a lot for creating this amazing software. I have maybe more of a question than a feature request...

When designing a PCA board in KiCad I can import most items for the complete board to InvenTree. But some items like the PCB itself, heat sinks, screws & nuts etc will not come from KiCad and has to be added for a complete BoM. To simplify the work with new revisions I have tried to find a way to reuse the BoM for the added items, upload a new file with the KiCad changes and merge the two together. But I do not really find a good way to achieve this.

### Suggested solution

I guess the part template is not really designed for this use case. Do you have any other suggestion how to use already existing features to achieve what I'm looking for? If not, would a template part that can be marked as virtual make sense? Or would that violate the idea with template parts?

### Describe alternatives you've considered

My first attempt was just to duplicate the PCA part and remove all parts that will come from KiCad before uploading the new revision. But it's manual work and rather easy to remove one item to much or to little for larger BoMs.

What I then tried is to create a subassembly as a template part, and there I import the KiCad components. Then I create a "top level" part for the PCA (or rather a child as it is described in the template documentation) where the BoM consists of the sub assembly part plus the extra material. My thought for a new revision was then to create a new subassembly part where I import the updated KiCad BoM, duplicate the top level PCA part and in the BoM just change the part code for the subassembly to the new revision. Minimum of manual editing.

I have used this model for a few examples and it all works fine. But what I cannot find a solution to is that I have to create a "fake" build order also for the sub assembly. I have played around with the inherited tagging of BoM line items but I do not really see any impact. The Subassembly BoM itself can so nicely be expanded from the top level BoM, pricing seems to work also but there is always a need for this extra build order.

I have even tried to set the subassembly as virtual as that level should/will never exist as a real part. Does not work either but as I have understood the virtual part it's intended for another use case.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@gunstr I'm struggling a little to follow what you are describing here, but I'll make some suggestions below. I also use KiCad and am often importing BOMs in a similar fashion.

### Track Parts in KiCad

You can add a 'virtual' part to your schematic, which does not get added to the PNP file, for tracking things like PCB, enclosure, etc. This part is only on the schematic, does not appear in the PCB and does not appear in the exported placement files. However it should get exported in the BOM and then you can upload in InvenTree

### Upload and Append

Alternatively you could create a separate BOM file which just contains these "extra" parts, and then when you upload this BOM, ensure that you do not check the "clear existing BOM".

![image](https://user-images.githubusercontent.com/10080325/186554098-667b72d4-eb34-43a1-8de2-48cdfb94907d.png)

This should then act to "append" the new BOM items

**Comment by gunstr** [comment]
@SchrodingersGat Sorry if my description is unclear. The use case is exactly what you describe. Difference is that I tried to find a way to maintain the BoM with "extra" parts inside InvenTree rather than outside.

### Track Parts in KiCad

That is actually where I started and definitely an option. The drawback is that a symbol for each "extra" part then has to be created in KiCad.

### Upload and Append

Also an alternative I have considered and probably better as the "extra" symbols are not needed in KiCad.

One possibility that just came to my mind is to create a separate part in InvenTree only to maintain the BoM for the "extras". I can then just duplicate that part as a basis for the new revision, then upload and append the KiCad BoM. I believe I was thinking too much about using a template, so I did not see this possibility. I will give it a try, I think that should really be a nice way to manage this.

**Comment by gunstr** [comment]
I have tested now and it's definitely a way that feels efficient. The model I use is:

1. Create one part in InvenTree for all the extras (I use a code in the IPN indicating it's a base part for the board)
2. Copy this base part including the BoM for each new revision and assign an IPN for the final board.
3. Upload and append the KiCad components for the latest revision.

This way I can keep the maintenance of the BoM for the "extras" inside InvenTree, but still have an easy way to create a new BoM on board level for each new revision.

@SchrodingersGat, thanks a lot for pointing me in the right direction. I'm closing this issue now.
