### ISSUE TITLE
[FR] Weasyprint Update

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3607]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Currently weasyprint is pinned to an older version due to PDF merging issues.

[This thread](https://github.com/Kozea/WeasyPrint/issues/1662) provides a solid workaround

### Suggested solution

Implement proposed workaround and update to latest weasyprint version

### Describe alternatives you've considered

Live in the past, stay locked in to current pinned version.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
@SchrodingersGat do we need the new version of weasyprint? Seems like this would need another dependency stack that can be avoided.

**Comment by SchrodingersGat** [comment]
Not necessarily at all. The current version is serving us quite well.

**Comment by SchrodingersGat** [comment]
I'm going to close this out as "won't fix" until we find some good reason to actually update
