### ISSUE TITLE
Issues with maintenance_mode.txt

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3618]
### Discussed in https://github.com/inventree/InvenTree/discussions/3617

<div type='discussions-op-text'>

<sup>Originally posted by **miggland** August 29, 2022</sup>
My Inventree server crashed today, while not in active use.

I have tried restarting the containers, but no luck yet.

------------------------------------------

There are two main issues here:

### Multiple File Copies

Multiple copies of the maintenance file are being created - should be limited to a single copy which gets overwritten.

### Error Handling

maintenance_mode code crashes if the file is empty

**Comment by matmair** [comment]
@miggland some questions for reproducing:
- a) Are you running in a cluster with +1 server (or gunicorn) instances?
- b) Are you running multiple maintenance scripts (invoke tasks) at the same time?
- c) Is the server stopped when you run maintenance scripts?
- d) Do you have plugins installed and enabled?
- e) Are you monitoring your instance (via webcrawler, auto-check etc - important thing is that a http/s call is made to the site)?

**Comment by miggland** [comment]
> @miggland some questions for reproducing:
> 
>     * a) Are you running in a cluster with +1 server (or gunicorn) instances?

No

>     * b) Are you running multiple maintenance scripts (invoke tasks) at the same time?

Not as far as I'm aware of.

>     * c) Is the server stopped when you run maintenance scripts?

Not always - I run `export records` when the server is running, for example. After an update, I usually run `invoke update` before starting all the containers.

>     * d) Do you have plugins installed and enabled?

Enabled yes, but none are installed - see the discussion topic; the install failed for the plugin I was trying to install.

>     * e) Are you monitoring your instance (via webcrawler, auto-check etc - important thing is that a http/s call is made to the site)?

No.

**Comment by Gigahawk** [comment]
Ran into the same issue today, deleting all the `maintenance_mode_state*` files in the media folder fixes the issue for now

**Comment by SchrodingersGat** [comment]
@matmair what should we do here? In particular I would like to prevent the multiple copies of maintenance_mode.txt file:

![image](https://user-images.githubusercontent.com/10080325/200980998-09898f23-f01b-4adb-84de-b156943c7bfd.png)

**Comment by matmair** [comment]
@SchrodingersGat I am not really sure where this comes from. Normally this should be handled by the library. Maybe we should move the file to static? Could be a problem with the location being in media.

**Comment by SchrodingersGat** [comment]
I think it is going to be related to being in the media dir. Perhaps moving to static would be sufficient?

**Comment by matmair** [comment]
@SchrodingersGat I still was not able to reproduce this while running 50+ instances.

**Comment by SchrodingersGat** [comment]
Sentry threw an error on the demo server today:

![image](https://user-images.githubusercontent.com/10080325/203678409-e9b3be2c-dd32-43e7-b6cf-3aca0147f66b.png)

**Comment by matmair** [comment]
@SchrodingersGat well this is very helpful. I should turn this on on my instances again - I got too many transactions for the free tier.
I will work out a PR. It should work if we move it to static and ensure the file exists on startup.

**Comment by matmair** [comment]
Sooo... I created a PR to upstream https://github.com/fabiocaccamo/django-maintenance-mode/pull/97
I think we should ship that change as part of InvenTree for now as it seems to fix the problems with multiple files etc.
@SchrodingersGat thoughts?

**Comment by SchrodingersGat** [comment]
@matmair looks great to me. If you can submit a local PR for us, and we can update d-m-m if they ever update

**Comment by SchrodingersGat** [comment]
@matmair another type of error thrown by the library:

![image](https://user-images.githubusercontent.com/10080325/204081284-ad6bf791-a4b6-44be-b7c7-aaf59978016a.png)

**Comment by matmair** [comment]
@SchrodingersGat that is a new one - no idea how that can happen

**Comment by SchrodingersGat** [comment]
Might be a race condition if the file is created but empty, with multiple workers booting at the same time? We should not throw an error here I think

**Comment by miggland** [comment]
That was the original error which caused me to submit https://github.com/inventree/InvenTree/discussions/3617 ... I had the case of an empty `maintenance_mode.txt` when this error appeared.

**Comment by matmair** [comment]
Due to the way the file is created it should never be empty. @miggland is the empty file just appearing? Do you use any special storage class?

**Comment by miggland** [comment]
Yes, it just appeared - unclear under which circumstances. I store the files on the filesystem, so nothing special - however, it's a virtual machine with a bit of a special backend which sometimes lags out a bit.

Why not, as @SchrodingersGat suggests, give a default value of 0 and not throw an error? (Only a warning?)

**Comment by SchrodingersGat** [comment]
@matmair are you still planning on pushing a PR for this before next release?

**Comment by matmair** [comment]
@SchrodingersGat still validating my change in production. It is kind of hard to produce this issue.

**Comment by SchrodingersGat** [comment]
Do you have  a branch I can look at?
