### ISSUE TITLE
[BUG] Link defined in parts/urls.py points to non-existant template

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3621]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

The link `/part/category/subcategory/`, as defined here:
https://github.com/inventree/InvenTree/blob/c8e8991cf5766e93a7f68c22a7201835a0f4860a/InvenTree/part/urls.py#L32

leads to an error, since part/subcategory.html does not exist:

### Steps to Reproduce

1. Go to the page [https://demo.inventree.org/part/category/subcategory/](https://demo.inventree.org/part/category/subcategory/)
2. Get an error message

### Expected behavior

I'm not sure what this page should show, maybe the URL doesn't need to exist?

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

From Demo server

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: c8e8991
Commit Date: 2022-08-30
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

### Relevant log output

```shell
Traceback (most recent call last):

File "/root/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
response = response.render()

File "/root/.local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
self.content = self.rendered_content

File "/root/.local/lib/python3.9/site-packages/sentry_sdk/integrations/django/templates.py", line 73, in rendered_content
return real_rendered_content.fget(self)

File "/root/.local/lib/python3.9/site-packages/django/template/response.py", line 81, in rendered_content
template = self.resolve_template(self.template_name)

File "/root/.local/lib/python3.9/site-packages/django/template/response.py", line 63, in resolve_template
return select_template(template, using=self.using)

File "/root/.local/lib/python3.9/site-packages/django/template/loader.py", line 47, in select_template
raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)

django.template.exceptions.TemplateDoesNotExist: part/subcategory.html, part/part_list.html
```

**Comment by SchrodingersGat** [comment]
@miggland was there a particular link that you clicked on to hit that URL? That URL is broken, the template it points to was deleted a long time ago.

I have made a [new PR](https://github.com/inventree/InvenTree/pull/3623) to fix this issue

**Comment by miggland** [comment]
No, I found the URL defined in the file (urls.py) and entered it manually. I assumed it was a artifact, but wasn't sure. Deleting it seems like the right solution.
