### ISSUE TITLE
[BUG] Direct link to part via IPN does not work for some IPNs

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3622]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

As discussed in #3374, it should be possible to access a part via its IPN using a link such as `/part/{IPN}/`

This does not work in my case. Probably, this is because I use IPNs consisting of only digits.

Instead of showing the part, a "Page not found" error is returned. On the test system, the following error is shown:
```
Page not found (404)

No Part found matching the query

Request Method: 	GET
Request URL: 	http://ubuntuvm:8000/part/90703/
Raised by: 	part.views.PartDetail

Using the URLconf defined in InvenTree.urls, Django tried these URL patterns, in this order:

    ^build/
    ^common/
    ^company/
    ^order/
    ^manufacturer-part/
    ^part/ ^import/ [name='part-import']
    ^part/ ^import-api/ [name='api-part-import']
    ^part/ ^bom_template/? [name='bom-upload-template']
    ^part/ ^(?P<pk>\d+)/ ^bom-download/? [name='bom-download']
    ^part/ ^(?P<pk>\d+)/ ^pricing/ [name='part-pricing']
    ^part/ ^(?P<pk>\d+)/ ^bom-upload/? [name='upload-bom']
    ^part/ ^(?P<pk>\d+)/ ^qr_code/? [name='part-qr']
    ^part/ ^(?P<pk>\d+)/ ^thumb-select/? [name='part-image-select']
    ^part/ ^(?P<pk>\d+)/ ^.*$ [name='part-detail']

The current path, part/90703/, matched the last one.
```
No digit-only IPNs seems to work.
Also, IPNs including decimal points such as `90307.Parts`, `9.Parts`, `R.CH` don't work (on any system, including the demo server).

### Steps to Reproduce

1. Create part with numeric IPN, or IPN containing a period
2. Try to open page for this part via direct URL /part/IPN/
3. Fail

### Expected behavior

The function is great (undocumented?) but it would be nice if it worked for more types of IPNs.

One solution could be to use a URL of the form `/part/ipn/xxxxx/` as an additional option, eg:

`    re_path(r'^ipn/(?P<slug>.+)/', views.PartDetailFromIPN.as_view(), name='part-detail-from-ipn')`

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

Demo server,

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: c8e8991
Commit Date: 2022-08-30
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by matmair** [comment]
Current state: @miggland this function is not documented because of the limitations you listed. I would not consider it as a bug as it is not used by the software or advertised anywhere. From what I remember, this is mainly in the code base for backwards compatibility. It does not work for digit-only IPNs as those match as part PKs.

General comment: Due to the (somewhat) recently widened IPN format options matching IPNs to URL paths is not always possible (think `/ & ? %`. This is a general problem with all reference fields that are getting their character options expanded due to user requests.

On FR development: I will not spend time on this feature as I do not see a significant value-add. It would be nice for users who like nice URLs (keeping in mind the above-mentioned limitations) so feel free to file a PR.

**Comment by miggland** [comment]
I'll reply here and not in #3374 to keep things focused.

I understand, and some of those limitations will probably have to remain. I also agree that this is not a big deal. However, I think my suggestion will work, so I'll take care of the PR for this.

In response to your comment in #3374:
> I would not bet on it working and use the pk/id. Only those are guaranteed to stay the same throughout the object life-cycle btw - Users can change IPNs.

Sure - however, for historical reasons we have IPNs listed in other systems, which don't match the PK. Being able to access the part directly knowing the IPN (which is what is listed on other documents such as drawings) would give an advantage.

**Comment by matmair** [comment]
@miggland I am of the mindest that a half-baked solution will only cause confusion and bug reports.
My suggestion would be to close this as `wontfix` @SchrodingersGat thougts?

**Comment by wolflu05** [comment]
What about appending a `/ipn/:ipn` to make it specific?

**Comment by SchrodingersGat** [comment]
@wolflu05 that should be opened as a separate issue - however there is the issue that IPNs are not guaranteed to be unique.

**Comment by miggland** [comment]
> What about appending a `/ipn/:ipn` to make it specific?

That was one of my suggestions also...

> One solution could be to use a URL of the form /part/ipn/xxxxx/ as an additional option, eg:
