### ISSUE TITLE
Update Master => ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by Bbillyben** [inventree/InvenTree#3630]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I'm trying to update from the master branch

and it ends with an error, I'm not sure it has not completed as I'm able to deploy the 3 containers and the plateform has launched.

### Steps to Reproduce

1. cd Inventree folder
2. run : `docker system prune (`to wipe all docker items)
3. run : `git reset --hard` (to be sure I'm lot leaving som mods)
4. run : `docker compose run inventree-dev-server invoke update`

complete log : 
[update_master.log](https://github.com/inventree/InvenTree/files/9471203/update_master.log)

note : 
When I run : `docker-compose run inventree-dev-server invoke superuser `, it works as expected
and when I deploy : `docker-compose up -d` it seems working too (as far as I can tell as I wiped all my datas!)

### Expected behavior

update without error

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

` git branch -a                                                                                                                                                     0.8.0                                                                                                                                                                                          * master                                                                                                                                                                                           remotes/origin/0.6.x                                                                                                                                                                             remotes/origin/0.7.x                                                                                                                                                                             remotes/origin/0.8.x                                                                                                                                                                             remotes/origin/HEAD -> origin/master                                                                                                                                                             remotes/origin/l10                                                                                                                                                                               remotes/origin/l10_crowdin                                                                                                                                                                       remotes/origin/master                                                                                                                                                                            remotes/origin/stable  `

from the plateform : InvenTree Version | 0.9.0 dev

VM : Debian GNU/Linux 10 (buster) / Linux 4.19.0-21-amd64 https://github.com/inventree/InvenTree/pull/1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
Docker version 20.10.17, build 100c701
docker-compose version 1.29.2, build 5becea4c
git version 2.20.1

### Relevant log output

```shell
=> lands with : 

Traceback (most recent call last):
  File "/usr/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/usr/lib/python3.9/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/lib/python3.9/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/lib/python3.9/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/lib/python3.9/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/inventree/tasks.py", line 94, in plugins
    from InvenTree.InvenTree.config import get_plugin_file
  File "/home/inventree/InvenTree/InvenTree/config.py", line 10, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
(see complete log above)

when I deploy the containers, the log of inventree-dev-server shows an alert after the system check :
```
You have 8 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): part, stock.                                                                    Run 'python manage.py migrate' to apply them.   
```
```

**Comment by Bbillyben** [comment]
note : I've upgraded my docker-compose to version 2.10.x, but I've got the same issue

**Comment by Bbillyben** [comment]
note : I've upgraded my docker-compose to version 2.10.x, but I've got the same issue

edit : sorry I miss clicked on the close button....

**Comment by SchrodingersGat** [comment]
@Bbillyben can you confirm what git commit hash you are running from?

From your log file, `pyyaml` is being installed. So this is strange. It may be because `invoke` is running from `/usr/bin/python3.9/site-packages/invoke` (as per the log) and does not have access to `pyyaml` which is installed within the virtual environment...

@matmair any thoughts here?

**Comment by Bbillyben** [comment]
Hi @SchrodingersGat 

the hash is : 23edd794312b5eea2e00878d2216150048747a4e

**Comment by SchrodingersGat** [comment]
Did you completely rebuild your `inventree-dev-server` image? Depending on how old your previous image was, the base image might not have the required python packages.

e.g.

```
docker-compose build --no-cache
```

**Comment by Bbillyben** [comment]
That was the issue. 

I've rebuild and invoke the update, and seems everything has ran smooth ! (except a time out on my first try to rebuild)

And I was even able to import datas from another instance!

**Comment by SchrodingersGat** [comment]
Glad you got it working. I'll add a note about this to the documentation.

**Comment by Bbillyben** [comment]
I'm feeling quite dumb about this.... 

I assumed that wipping all docker items will force image updating..

**Comment by SchrodingersGat** [comment]
I think perhaps that cleans the container instances but not the images on which they are based? There are a *lot* of different things that can go "wrong" in an interesting way with docker :P
