### ISSUE TITLE
Having a Search Bar for Incomplete Outputs

### ISSUE THREAD

**Issue by palagap** [inventree/InvenTree#3631]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

When in the process of making a build order, is it possible to have a search bar to find parts in the incomplete outputs tab? It would be helpful in case there are many parts listed. This search bar is present in completed outputs.

<img width="1656" alt="Screen Shot 2022-08-31 at 2 13 23 PM" src="https://user-images.githubusercontent.com/40808444/187969722-cf7ee69d-c691-43f4-8355-7a6957a8adaa.png">

Vs.

<img width="1678" alt="Screen Shot 2022-08-31 at 2 13 55 PM" src="https://user-images.githubusercontent.com/40808444/187969738-fee41703-3514-4337-8bb8-c9a0fa13dc90.png">

### Suggested solution

The same search bar that is present for completed outputs would also be available for incomplete outputs.

### Describe alternatives you've considered

Manually looking through the parts listed in an incomplete output.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Ref: v
