### ISSUE TITLE
Sales and Purchase Report Permissions

### ISSUE THREAD

**Issue by jdh313** [inventree/InvenTree#3632]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Printing sales and purchase reports requires admin: view permission in order to print/download.

### Steps to Reproduce

1. Go to Buy -> Purchase Orders or Sell -> Sales Orders
2. Click on one of the orders
3. Click the print button, followed by Print build order report
4. 403 error occurs

### Expected behavior

The report should download

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.0
Django Version: 3.2.14
Commit Hash: 6118d13
Commit Date: 2022-08-01
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
@jdh313 can you share a screenshot or log of the error you are seeing? I have tried to replicate locally but it seems to work as expected.

**Comment by jdh313** [comment]
@SchrodingersGat sure, here's the error that pops up on sales reports, along with the permission set: 
<img width="537" alt="CleanShot 2022-09-02 at 08 27 17@2x" src="https://user-images.githubusercontent.com/13279035/188143003-12cbe6d7-a5fb-4459-be2a-58e1835a9255.png">
<img width="799" alt="CleanShot 2022-09-02 at 08 28 11@2x" src="https://user-images.githubusercontent.com/13279035/188143017-5287f248-64de-4e91-8aaf-ec731caba7a6.png">

**Comment by SchrodingersGat** [comment]
@jdh313 thanks, I can confirm that this is a bug. Fix incoming.

**Comment by jdh313** [comment]
Awesome, thank you so much!!!
