### ISSUE TITLE
BOM Pricing is not working

### ISSUE THREAD

**Issue by Guusggg** [inventree/InvenTree#3638]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Recently I've noticed that the BOM Pricing does not show up anymore in my InvenTree instance. We carefully use Purchase Order to track prices and we carefully made the BOM subs to make sure everything is tracked properly.

I'm not sure when it stopped working, but it did work in the past but this must have been InvenTree `0.4`, since I didn't update for a while and updated to `0.7.2` then. Right now I'm on `0.8.2` but it's still not showing up.

![image](https://user-images.githubusercontent.com/6216482/188118000-9a2acca6-95e8-4f5b-ad69-b88476fa2ec7.png)
Notice that the purchase pricing range says `-`, so this might just be something I messed up. 

![image](https://user-images.githubusercontent.com/6216482/188118606-99daf1dd-4b31-43a6-8e6d-c8c8dd33fba4.png)
Should I validate the build orders to make the pricing work?

### Steps to Reproduce

...

### Expected behavior

...

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.2
Django Version: 3.2.15
Commit Hash: 3e27509bc
Commit Date: 2022-08-30
Database: mysql
Debug-Mode: False
Deployed using Docker: False

**Comment by SchrodingersGat** [comment]
@Guusggg do you have the "Show Price in BOM" option enabled?

![image](https://user-images.githubusercontent.com/10080325/188122153-4ad0d5b5-f386-450f-abb0-0da92d9e638e.png)

This option was introduced as displaying pricing in the BOM table is currently very expensive (computationally). It is on the agenda to address this in a major pricing restructure

**Comment by Guusggg** [comment]
Hi @SchrodingersGat,

Thank you so very much for the detailed response! I managed to get it back, not by enabled the `Show Price in BOM`, which was enabled, but I enabled `Display historical pricing for Part` which brought back the complete pricing picture.

Thank you so much! It's an amazing feat what you pull off with this project ^^ (and with others, ofcourse!)

Kind regards,
