### ISSUE TITLE
[FR] Suggestion for keyboard shortcuts, eg ESC as Cancel.

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#3647]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Pressing escape ESC when a window is open should automatically press "cancel" button. I have noticed this issue eg. when the "Edit Part" window is open. Out of habit, I press esc to close the window but this does nothing. Therefore, I must click "Cancel" using the mouse instead.

Perhaps there are other keyboard shortcuts that could make sense to add. Feel free to add them to this issue.

### Suggested solution

I suggest allowing ESC key to act as "Cancel" button.

### Describe alternatives you've considered

Using the mouse :)

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
@tehkillerbee please check if features are available before suggesting them. This feature has been there for a few months and can be activated per-user in the settings.
![image](https://user-images.githubusercontent.com/66015116/188592059-29205980-3828-4cce-badd-5648af1b2ae6.png)

**Comment by tehkillerbee** [comment]
@matmair Thank you, I guess I was looking in the wrong setting menu.
