### ISSUE TITLE
[FR] Accessing base part of a part listed in stock requires extra steps.

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#3648]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Whenever I need to access the base part for a part listed in the stock, I need to first click the stock item and then click "base part". This is slightly cumbersome.

### Suggested solution

It would be nice if there is an easier way to access base part from the stocks list, without additional clicks. Perhaps the base part can be added/listed in the stocks table or accessible as a direct link somehow? It's a small feature but it would make the user experience better.

### Describe alternatives you've considered

N/A

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@tehkillerbee clicking on the link in the "part" column should take you to the part instance, but it seems it actually takes you to the stock-item instance. This is duplicate behaviour as the link in the "stock" column already takes you there. So this should be addressed.
