### ISSUE TITLE
[Bug] Accessing "Site Administration" and then clicking "change" menu hides the change buttons

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#3649]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Accessing "Site Administration" and then clicking "change" menu results in a layout change that makes it impossible to click "change" links for other submenus. This makes changing multiple settings rather cumbersome.

### Steps to Reproduce

1. Click Site administration
2. Click "Add" or "Change" for any menu. 
3. Sidebar menu changes width, making it impossible to click "Change" again
4. You now have to reload "Site administration" page to start over.

### Expected behavior

Sidebar menu should not change width. Alternatively, the menu width should be possible to adjust manually.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.7.0
Django Version: 3.2.13
Commit Hash: 044315a
Commit Date: 2022-05-24
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
@tehkillerbee you should be able to toggle the sidebar with the button shown here:

![image](https://user-images.githubusercontent.com/10080325/188610499-be3191a1-a208-41e2-968c-cd4f2103f486.png)

**Comment by tehkillerbee** [comment]
@SchrodingersGat I can definitely toggle the menu - but the link is still not possible to click due to the menu width being smaller:

Before clicking:
![image](https://user-images.githubusercontent.com/815886/188620777-24d85693-624d-4228-b845-7b9647e24c37.png)

After clicking:
![image](https://user-images.githubusercontent.com/815886/188620586-39e99be8-42ff-4235-8893-0922584787d7.png)

**Comment by SchrodingersGat** [comment]
@tehkillerbee indeed, the links are identical. This is the default django admin page, might just be a strange layout quirk.
