### ISSUE TITLE
[FR] Allow displaying additional base part details when accessing a stock item.

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#3650]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

When browsing a base part, the part description is displayed. When accessing a stock item for that same part, no description is displayed but only the Part (Name and IPN). If the Name/IPN does not contain any descriptive data but just a model no., this makes it difficult to identify the part, without having to view the base part again separately. 

### Suggested solution

Allow enabling/disabling display of fields for a stock item, eg. "description", "link" etc. Perhaps this could be enabled from the settings menu?

### Describe alternatives you've considered

Modifying the Part Name Display Format directly in the "Parts settings" menu as listed below:

```
{{ part.IPN if part.IPN }}{{ ' | ' if part.IPN }}{{ part.name }}{{ ' | ' if part.revision }}{{ part.revision if part.revision }}{{ ' | ' if part.description }}{{ part.description }}
```

This is not an ideal solution, as it will affect the part name everywhere.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
The stock display is only meant to show stock specific information. I think it will confuse users more then anything if we duplicate inforamtion around the system. If you want information about the part click on the part name, if you want to change stuff about the stock use the stock display in my opinion.

**Comment by tehkillerbee** [comment]
@matmair I see your point. However, the issue occurs when I browse the stock page since our inventory contains many parts that have similar IPNs. I would need to memorize what a specific part name/IPN is related to - or click the base part and view the description of it each time. Otherwise, I risk mixing up stocks. 

Therefore, it is primarily the base part description field that is missing. If I need more detailed information about the part, I can just view the base part, as you suggest.
