### ISSUE TITLE
Can't turn off email notifications

### ISSUE THREAD

**Issue by reilly-callaway** [inventree/InvenTree#3654]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Emails notifications are still being sent after turning off "Enable email notifications".

### Steps to Reproduce

1. Turn on "Enable email notifications"
1.5. I suppose I left email notifications on for a few days, received some email. Probably not a required step.
2. Turn off "Enable email notifications"
3. Create a PO, BO, etc. that will generate a notification.
4. Still get email!!

### Expected behavior

Stop sending email notifications after turning off the setting.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 0fae2432b
Commit Date: 2022-08-26
Database: mysql
Debug-Mode: True
Deployed using Docker: False

**Comment by SchrodingersGat** [comment]
The user setting is never checked anywhere. Need to add check to the `send_bulk` function:

https://github.com/inventree/InvenTree/blob/ea60cdc6a8a7eaa5a445148f5067e5c0137c5377/InvenTree/plugin/builtin/integration/core_notifications.py#L73

**Comment by matmair** [comment]
It is checked a few lines above in get_targets

**Comment by SchrodingersGat** [comment]
You're right, it should be being called through that...

**Comment by rkalman** [comment]
Maybe something is wrong with setting the property itself, I mean update the setting value through the api. 
I am trying to get email notifications live, and I have a problem with enabling/disabling settings like:

Menu item User settings / Notifications / Enable email notifications: I get 404 for URL: /api/settings/global/NOTIFICATION_METHOD_MAIL/

Menu item Plugin settings / CoreNotificationsPlugin / Enable email notifications: I get 404 for  URL: /api/settings/global/ENABLE_NOTIFICATION_EMAILS/ 

Bare metal install, always upgraded to recent master branch. (now b306d2a34a60c453aab57197c895ed7a64651f18)

**Comment by lawson89** [comment]
I get similar errors for /api/settings/global/REPORT_INLINE/ and others
I don't see NOTIFICATION_METHOD_MAIL or REPORT_INLINE in the InvenTreeSetting.SETTINGS (Dict of all global settings values)

Shouldn't these be calling user settings instead of global?

**Comment by lawson89** [comment]
Also I don't see these settings in InvenTreeUserSetting

So I think
1. It's calling the wrong api
2. Even if calling user settings api, I don't see some of the settings defined there

I'm very new to this project so entirely possible I am missing something

**Comment by SchrodingersGat** [comment]
@rkalman thanks for pointing this out, sorry took me so long to get back around to this one. Certainly something is going wrong with the settings page / API there.

**Comment by SchrodingersGat** [comment]
I'm not sure that the API bug is the same as what is preventing the email from being turned off, but we'll see
