### ISSUE TITLE
"Copy to clipboard" buttons are not working

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#3668]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

The "copy to clipboard" buttons are not working, at least on Safari.
One exception the buttons located on the version information form, which are working but all does the same.

### Steps to Reproduce

Open any page, click that button, nothing copied to the clipboard.
<img width="971" alt="Képernyőfotó 2022-09-11 - 14 02 16" src="https://user-images.githubusercontent.com/580623/189526546-2049e6e2-b2d9-4494-8404-340d2bc0917f.png">

### Expected behavior

It would be nice if they work, or would be removed.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

demo.inventree.org:
# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: b306d2a
Commit Date: 2022-09-09
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by wolflu05** [comment]
Do you access inventree over https and do you use localhost or an remote address?

**Comment by rkalman** [comment]
https://demo.inventre.org to be very specific

**Comment by rkalman** [comment]
It seems the js code is missing for that buttons...
