### ISSUE TITLE
[FR] List PO/SO/BO by reference in API

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3671]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

When accessing orders through the API, I always have to find the ID of the order first - ie list them, look for the reference I want, then get the ID.
If the API would accept a reference field, this would be reduced to one step, eg:
`https://demo.inventree.org/api/order/po/?reference=PO0006`

### Suggested solution

Compare to how Parts works: I can request an IPN directly using the URL:
`https://demo.inventree.org/api/part/?IPN=widget.blue`

### Describe alternatives you've considered

List -> search for reference -> return ID

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@miggland should be reasonably straight-forward as the reference field is guaranteed to be unique (unlike the Part IPN field)

**Comment by miggland** [comment]
This is still relevant.
