### ISSUE TITLE
Strange behaviour when running `invoke export-records'

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#3672]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Hello guys, 

I have been upgrading our inventree-server to the latest version, as per the guide listed [here](https://inventree.readthedocs.io/en/latest/start/docker_prod/).
```
docker-compose down
docker-compose pull
...
```

After upgrading, I wanted to export the database. However, when I follow the guide, the outcome is not what I expected: 
1. When replacing the .json path with a path to a local share, I get a `No file or directory` error, even though the path exists. 
```
[/share/data/docker/inventree] # docker-compose run inventree-server invoke export-records -f /share/homes/inventree_bk/data/data.json
Creating inventree-production_inventree-server_run ... done
/home/inventree/data/config.yaml exists - skipping
InvenTree translation coverage: 19%
Exporting database records to file '/share/homes/inventree_bk/data/data.json'
CommandError: Unable to serialize database: [Errno 2] No such file or directory: '/share/homes/inventree_bk/data/data.json.tmp'
```
2. When using `data_bk.json` as the path, the export proceeds with no error. 
```
[/share/data/docker/inventree] # docker-compose run inventree-server invoke export-records -f data_bk.json
Creating inventree-production_inventree-server_run ... done
/home/inventree/data/config.yaml exists - skipping
InvenTree translation coverage: 19%
Exporting database records to file '/home/inventree/data_bk.json'
[...........................................................................]
Running data post-processing step...
Data export completed
```
However - the `/home/inventree/` path does not exist on this system so the file cannot exist.

What is going wrong? Am I using the tools incorrectly?

A sidenote: After upgrading to the latest version as per the instructions listed [here](https://inventree.readthedocs.io/en/latest/start/docker_prod/), I cannot open `About Inventree` window anymore. When clicking `About Inventree`, nothing happens. I am sure this worked before the update. Perhaps this is a bug?

Thanks for your help and for the great work on InvenTree.

### Steps to Reproduce

Follow the guide as listed in 

https://inventree.readthedocs.io/en/latest/start/docker_prod/
or 
https://inventree.readthedocs.io/en/latest/start/migrate/

### Expected behavior

a data.json backup file.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

After upgrading to the latest version as per the instructions listed [here](https://inventree.readthedocs.io/en/latest/start/docker_prod/), I cannot open this window anymore(!?). Perhaps this is a bug?

**Comment by SchrodingersGat** [comment]
As @miggland has outlined above, the file `data_bk.json` will be found at the location of `INVENTREE_EXT_VOLUME` as per your container setup. Please re-open this issue if you cannot locate the file there.

**Comment by tehkillerbee** [comment]
Thanks for elaborating, that makes sense.
