### ISSUE TITLE
Web display broken after upgrade from 0.7.0 to 0.8.2 on Synology docker

### ISSUE THREAD

**Issue by markusEmm123** [inventree/InvenTree#3684]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

After updating from 0.7.0 to 0.8.2 on Synology docker the installation seems broken.
I am still logged in but it seems like no external resources (images or css or javascript) can be loaded and all i see is a pretty messed up site, see screenshot:
![image](https://user-images.githubusercontent.com/96077472/190522463-00e6005c-be9e-4c6e-858d-4f07842b86a1.png)

### Steps to Reproduce

1. Stop container
2. load new image
3. start container with "invoke update" as run command
4. start regular container(s)

### Expected behavior

Regular user interface, being able to load the external ressources.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.8.2 on Synology docker

### Relevant log output

```shell
Log output mentions many lines similar to
Saving setting 'InvenTreeUserSetting:HOMEPAGE_SO_OVERDUE_user:<my username>' to cache
apart from that no information which looks suspicious or different from normal behaviour.
```

**Comment by markusEmm123** [comment]
It does work as expected if i set the enviroment variable "INVENTREE_DEBUG" from "False" to "True".
Returing it to "False" reproduces the error.

**Comment by SchrodingersGat** [comment]
> It does work as expected if i set the enviroment variable "INVENTREE_DEBUG" from "False" to "True".
> Returing it to "False" reproduces the error.

This means that your static files are not being served correctly in production mode (`INVENTREE_DEBUG=False`).

When you load the page, (with the developer console open in your browser) you should see lots of error codes for all the .css and .js files. Can you share those error messages here?

As you are running docker under synology, I am assuming that you have setup a proxy image (e.g. nginx) to serve the static and media files as per the documentation? Is that image running correctly?

**Comment by markusEmm123** [comment]
Thank you, that was obviously the reason.
After i have configured nginx correctly everything works as inteded.
