### ISSUE TITLE
Add full location path to build allocation table

### ISSUE THREAD

**Issue by gunstr** [inventree/InvenTree#3685]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I use the build allocation page to pick components. When I have locations with the same name under a tree (like "shelf1/box1" and "shelf2/box1" I can only see "box1" in the allocation table.

Screenshot from the demo site:

![Screenshot 2022-09-16 150235](https://user-images.githubusercontent.com/41468206/190645107-6c69bf06-b27a-47c2-a6bd-ba0b761582dd.jpg)

### Suggested solution

Add the full location path to the allocation table.

### Describe alternatives you've considered

The option I use now is to open the location for each part in a new tab to check the full path.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
@gunstr This would be rather easy to implement by adding a new column to this table in the frontend-js code and maybe extend the api for faster rendering of the values.

**Comment by gunstr** [comment]
@matmair I do not think a new column is needed, the full path can just be added to the existing location column in the same way as in the  Part/Stock table:

![Screenshot 2022-09-17 094659](https://user-images.githubusercontent.com/41468206/190846408-2acb18b3-642a-475d-bbf2-a050b3939885.png)

**Comment by matmair** [comment]
@gunstr that will make the tables hard to read/wide and deep as the full path tends to be long. I would recommend against that and add a new column so that you can choose to have very wide tables will the rest of the userbase keeps the normal experience.

**Comment by SchrodingersGat** [comment]
@gunstr another option would be to leave the current text, but add the "fully qualified path" as the hover-text - i.e. when the user mouses-over the location string they see the whole thing. This would keep the table clean but still provide the required data. Would such a solution be acceptable for you?

**Comment by gunstr** [comment]
@SchrodingersGat Although I do not really see why the behavior should be different to the Part Stock or other tables showing the stock location (or any other long strings for that matter) a hover-text is also a good solution.
There is of course a little mouse action required to see it, but it's far better than having to open another window to see the full path.

**Comment by SchrodingersGat** [comment]
@gunstr I've come up with a "hybrid" solution here - the tables will display the full path, unless that full path is very long, in which case it will be shortened for display but you can view the entire path with the tooltip:

![image](https://user-images.githubusercontent.com/10080325/191161982-f1ce4b7d-5372-4a41-8248-1505c137386e.png)

**Comment by SchrodingersGat** [comment]
@gunstr this will be fixed in https://github.com/inventree/InvenTree/pull/3695 - please LMK if there are any other tables where you think this should be applied

**Comment by gunstr** [comment]
@SchrodingersGat Very clever solution, thanks a lot. For now I have not seen any other place where the full path is missing but will let you know if I bump into one. Long paths has so far not been an issue for me as I normally are on a wide screen.

**Comment by matmair** [comment]
@gunstr there are a bunch of users with workbench-mounted iPads - myself included. So `long` might mean something else for other users than you.

**Comment by SchrodingersGat** [comment]
> @gunstr there are a bunch of users with workbench-mounted iPads - myself included. So `long` might mean something else for other users than you.

Fair point I'll add in a user setting for this new "feature"

**Comment by gunstr** [comment]
@SchrodingersGat @matmair To have it configurable make sense to support iPads, I guess a hover-text is not feasible at all for touch screens? If you anyway look into that you maybe want to align the behavior also for the allocation table for sales orders. As I primarily use wider screens it's not a problem for me, but I happened to notice that the full location path is actually already displayed in that table.

**Comment by Gigahawk** [comment]
Can this feature also be added for the Stock Item view?
Right now I have individual locations set up for each section of a tray, where the path is something like `Tray X/A4`.
If I have multiple identical trays the Stock Item view only shows the last part of the path `A4`, which is ambiguous:
![image](https://user-images.githubusercontent.com/10356230/191942084-1aaaef6e-c968-479e-861d-b7a7ad1f9686.png)

**Comment by matmair** [comment]
@Gigahawk please do not use closed issues for new requests
