### ISSUE TITLE
Upgrading from 0.7.0 to 0.8.x on Synology docker

### ISSUE THREAD

**Issue by markusEmm123** [inventree/InvenTree#3686]
As i had a little struggle with updating from 0.7.0 to 0.8.2 on my Synology, i will try to describe what i have done to help others or remind me next time...
Unfortunately i know no better place for the moment than here.

1. Make a backup of database and data folder
2. Stop the inventree containers
3. Create a backup of the old configuration by selecting "settings-> duplicate settings" in the container overview and name it something like "inventree-backup".
4. Duplicate the settings with the old name, having a new container with the old name and a backup-container with the old configuration.
5. Create a new folder "docker" in a Synology shared folder (in my case /docker/inventree/docker") and link it to /home/inventree/docker - in parallel to /home/inventree/data
6. Download https://github.com/inventree/InvenTree/blob/187707c89259ded328af0b63ce19a8e61ba53d5c/docker/gunicorn.conf.py and copy it to the newly created "docker" folder. 
7. Update the docker image via "Registry". The old image will be overwritten.
8. Create a completely new container based on the inventree-image. Name it for example "inventree-update". The important part: For this newly created container type as the execution command (or run command; i do not have an english version of the Synology docker GUI) "invoke update".
9. Link the volumes as with the regular container (/home/inventree/data) to the persistent data folder on the Synology. Set the enviroment variables as in the regular container (especially the database configuration).
10. Run the inventree-update container.
11. Monitor the protocol output. It may take some time until the update is finished. The container should "shut down unexpectedly" when finished.
12. Keep this container for the next update, but you won't need it for the moment.
13. Start your regular inventree containers.

**Comment by wolflu05** [comment]
You could have posted this to the discussions in the category show & tell.
