### ISSUE TITLE
[FR] Detail report for Build Order Template

### ISSUE THREAD

**Issue by AlexeyHaritonov** [inventree/InvenTree#3690]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Hello,

When creating Build Order that contains few products.
You have to print each products BOM separately, but even then it doesn't multiply with quantity of the products.

For example:
**New BO0002**
Product_PCB_1    quantity 2
Product_PCB_2    quantity 3

Product_PCB_1 BOM
resistor 15K 0402  quantity 10
capacitor 20uF      quantity 2

Product_PCB_2 BOM
resistor 4K 0603    quantity 4
capacitor 20uF      quantity 5

the problem is when you what to have a report or a hard copy for all BOMs
something like:

BO0002 BOM
resistor 15K 0402  quantity 20
capacitor 20uF      quantity 19
resistor 4K 0603    quantity 12
 
It could be nice to get a full BOM for full order, or maybe few BOM's one for each product....

### Suggested solution

I think it is possible to generate using report template.....but unfortunately I do not have any experience with web developing.

### Describe alternatives you've considered

Currently the only solution is to print each BOM for each product and multiply it by hand.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
@AlexeyHaritonov this should be possible with reports - see the docs [here](https://inventree.readthedocs.io/en/latest/report/report/)

**Comment by AlexeyHaritonov** [comment]
I would like to use something similar from BOM report

<tbody>
        {% for line in bom_items.all %}
          <tr>
            <td>{{ line.sub_part.IPN }}</td>
            <td>{{ line.sub_part.name }}</td>
            <td>
              {% for manf in line.sub_part.manufacturer_parts.all %}
               {{ manf.manufacturer.name }}
               {% endfor %}
          </td>
          <td>{% decimal line.quantity %}</td>
          <td>{{ line.reference }}</td>
            <td>
              {% for sub in line.substitutes.all %}
            {{ sub.part.IPN }}<br>
            {% endfor %}
          </td>
          </tr>
        {% endfor %}
    </tbody>

How can I get "bom_items" object from "build" object???
{% for prt in build.part.all %}
         {% for line in prt.bom_items.all %}
         {% endfor %}
{% endfor %}

Is this correct?

**Comment by AlexeyHaritonov** [comment]
I can't find sub_parts or bom varialbles in all Context variables.
Any idea?

**Comment by SchrodingersGat** [comment]
@AlexeyHaritonov the available context variables are documented here - https://inventree.readthedocs.io/en/latest/report/build/

This should be enough to get you up and running

**Comment by AlexeyHaritonov** [comment]
I can't find variables from build object-> to BOM
Maybe you can point it please?

**Comment by AlexeyHaritonov** [comment]
@SchrodingersGat 
Checked one more time in [(https://inventree.readthedocs.io/en/latest/report/build/)]
don't see any path from build object to BOM (sub_parts...etc...)
the closest is "build.part"......but what when?
Part object doens't have any sub part variables

**Comment by SchrodingersGat** [comment]
From [the docs](https://inventree.readthedocs.io/en/latest/report/build/):

You can iterate over the list of BOM items as follows:
```
{% for line in build.bom_items %}
```

**Comment by SchrodingersGat** [comment]
@AlexeyHaritonov did the suggestion above work for you?

**Comment by rkalman** [comment]
I had similar situation, finally I found the allocated items are better suitable for a "pick list".
I use this, hope it helps:
```
 {% for item in build.allocated_stock.all %}
    <tr>
        <td class='left'>{{item.stock_item.location.pathstring}}</td>
        <td class='left'>{{item.stock_item.part.full_name}}</td>
        <td class='left'>{{item.stock_item.part.description}}</td>
        <td class='right'>{% decimal item.quantity %}</td>
        <td class='left'>{{ item.stock_item.part.units }}</td>
        <td><div class='checkbox'></div></td>
    </tr>
    {% endfor %}
```

**Comment by matmair** [comment]
@SchrodingersGat can we close this with the latest merges?

**Comment by wlcx** [comment]
For anyone finding this now, I did this (include the BOM for a build order with the correct quantities) with the below snippet:
```
{% for line in line_items.all %}
        <tr>
            <td>
                <div class='thumb-container'>
                    <img src='{% part_image line.bom_item.sub_part height=240 %}' alt='{% trans "Image" %}' class='part-thumb'>
                </div>
                <div>
                    {{ line.bom_item.sub_part.full_name }}
                </div>
            </td>
            <td>{% decimal line.quantity %}</td>
            <td>{{ line.bom_item.reference }}</td>
            <td>{{ line.bom_item.sub_part.parameters_map.PP_Part_Num }} </td>
            <td>{{ line.bom_item.notes }}</td>
        </tr>
        {% endfor %}
```
