### ISSUE TITLE
PO report template doesn't work

### ISSUE THREAD

**Issue by AlexeyHaritonov** [inventree/InvenTree#3691]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Hello,

I'm running docker on Windows 10
After adding all reports BO, BOM, PO, SO
Everything works fine except of PO report
I get an error when using PO report template (inventree_po_report.html):
{"error":"TemplateSyntaxError","error_class":"<class 'django.template.exceptions.TemplateSyntaxError'>","detail":"Error details can be found in the admin panel","path":"/api/report/po/6/print/","status_code":500}

### Steps to Reproduce

Just add inventree_po_report.html as PO report template in admin panel

### Expected behavior

Should print a report

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.2
Django Version: 3.2.15
Commit Hash: 62f44d0
Commit Date: 2022-08-25
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by AlexeyHaritonov** [comment]
Fixed in #3677 
still not in stable :(
current stable 0.82

**Comment by SchrodingersGat** [comment]
@AlexeyHaritonov 0.8.3 should be out pretty soon
