### ISSUE TITLE
Some part parameters not shown when sorting ascending

### ISSUE THREAD

**Issue by chris-thorn** [inventree/InvenTree#3703]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I have imported parameters for a group of parts, and the parameters all display correctly when the parts are sorted by Part Name:

![image](https://user-images.githubusercontent.com/3541291/191485596-8fed75cb-26a2-4731-a9b6-a2685ae8d604.png)

If I click the column header 'Resistance' to sort the parts, it initially sorts them in descending order and they display correctly:

![image](https://user-images.githubusercontent.com/3541291/191485817-c27fe6de-1886-4242-ba4c-25e422e6e9a7.png)

However, if I click the header again to change the sort direction to ascending, a large number of parameter values are replaced by a hyphen:

![image](https://user-images.githubusercontent.com/3541291/191488954-bcbdfd09-00c8-4d51-905e-7f0898f17459.png)

This issue occurs regardless of which parts or which parameters I am looking at.

### Steps to Reproduce

1. Go to Parts
2. Click Subcategories and select a subcategory
3. Click Parameters
4. Click a column header in the table of parameters to sort that column

### Expected behavior

The sort function should work correctly regrdless of the sort order.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 187707c
Commit Date: 2022-09-15
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
Can you confirm that the parameter values are actually set for those parts? If the part does *not* have an associated parameter (e.g. for "resistance") it will be displayed as a `-` character instead.

**Comment by chris-thorn** [comment]
Sorry, I should have made that clear.

Yes all parts have parameters. I have 23 parts in that particular category, all of which can be seen here:

![image](https://user-images.githubusercontent.com/3541291/191491198-535638ba-bb6d-4182-8ff9-5187083af279.png)

**Comment by SchrodingersGat** [comment]
@chris-thorn yes I am able to replicate this problem. A very strange one...

**Comment by chris-thorn** [comment]
Just on the off chance it was an issue with bootstrap-table, I replaced `data/static/bootstrap-table` (v1.18.3) with the latest release (v1.21.0) and rebuilt the docker containers, but it doesn't seem to have made a difference.

**Comment by SchrodingersGat** [comment]
It *was* an issue with bootstrap-table, kind of... Fix in https://github.com/inventree/InvenTree/pull/3704

**Comment by chris-thorn** [comment]
Fantastic - thank you very much for your efforts!

Chris

**Comment by chris-thorn** [comment]
Hmm... I've just pulled the latest image from Docker and recreated the containers but the issue persists.

Once commit 829a9d8 was made available to pull from Docker I pulled the updated image, ran `docker compose down` followed by `docker-compose up -d` and the InvenTree containers were recreated.

Here is another example of the behaviour, this time of a category that contains only three parts, each of which has a single parameter 'Thickness'.

**Default sort order:**

![image](https://user-images.githubusercontent.com/3541291/191541688-93bb13ff-acdb-4db5-8a4e-999bfc88d43c.png)

**First click** on 'Thickness' column header to **sort descending**:

![image](https://user-images.githubusercontent.com/3541291/191541988-21beb129-c9f9-481b-ab17-1d77d0a858ee.png)

**Second click** on 'Thickness' column header to **sort ascending**:

![image](https://user-images.githubusercontent.com/3541291/191543129-20047787-bbd7-4b9c-8bcd-42bf33708db2.png)

(Apologies if this should be raised as a new issue instead of reopening a closed issue.)

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 829a9d8
Commit Date: 2022-09-21
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False
