### ISSUE TITLE
Part parameter sort order issue

### ISSUE THREAD

**Issue by chris-thorn** [inventree/InvenTree#3705]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

This is a follow-on from issue #3703 - I've just pulled the latest InvenTree image from Docker and recreated the containers but the original issue persists.

(Apologies for creating a new issue if I should have just commented on the original issue and waited!)

Once commit 829a9d8 was made available to pull from Docker I pulled the updated image, ran `docker compose down` followed by `docker-compose up -d` and the InvenTree containers were recreated.

Here is another example of the behaviour, this time of a category that contains only three parts, each of which has a single parameter 'Thickness'.

**Default sort order:**

![image](https://user-images.githubusercontent.com/3541291/191541688-93bb13ff-acdb-4db5-8a4e-999bfc88d43c.png)

**First click** on 'Thickness' column header to **sort descending**:

![image](https://user-images.githubusercontent.com/3541291/191541988-21beb129-c9f9-481b-ab17-1d77d0a858ee.png)

**Second click** on 'Thickness' column header to **sort ascending**:

![image](https://user-images.githubusercontent.com/3541291/191543129-20047787-bbd7-4b9c-8bcd-42bf33708db2.png)

### Steps to Reproduce

1. Go to Parts
2. Click Subcategories and select a subcategory
3. Click Parameters
4. Click a column header in the table of parameters to sort that column

### Expected behavior

The sort function should work correctly regrdless of the sort order.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 829a9d8
Commit Date: 2022-09-21
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
Have you performed a full reset of your browser cache so that the JavaScript files are updated?

**Comment by chris-thorn** [comment]
Yeah, that was the first thing I tried. I've tried it again just now on a different PC using a different browser in private browsing mode but it still behaves the same.

Do I need to delete any of the files in the `static/` directory of the Docker data volume before I run `docker-compose up -d`... or anything like that?

**Comment by SchrodingersGat** [comment]
Alright I'll have another look and see if I can replicate.

**Comment by SchrodingersGat** [comment]
> Once commit https://github.com/inventree/InvenTree/commit/829a9d8311307aed092c554ae128773d4c9d2c75 was made available to pull from Docker I pulled the updated image, ran docker compose down followed by docker-compose up -d and the InvenTree containers were recreated.

You need to run `docker compose run inventree-server invoke update` [as per the documentation](https://inventree.readthedocs.io/en/latest/start/docker_prod/#update-database) - the static javascript files will not have been updated

**Comment by SchrodingersGat** [comment]
Please close this issue out when you've got it working :)

**Comment by chris-thorn** [comment]
Oh nuts, I'm sorry - I completely missed that section in the docs 🙄

All working as expected now after clearing browser cache - thanks for your patience!

Chris
