### ISSUE TITLE
Add full location path to Stock Item location entry

### ISSUE THREAD

**Issue by Gigahawk** [inventree/InvenTree#3711]
Can this feature also be added for the Stock Item view?
Right now I have individual locations set up for each section of a tray, where the path is something like `Tray X/A4`.
If I have multiple identical trays the Stock Item view only shows the last part of the path `A4`, which is ambiguous:
![image](https://user-images.githubusercontent.com/10356230/191942084-1aaaef6e-c968-479e-861d-b7a7ad1f9686.png)

_Originally posted by @Gigahawk in https://github.com/inventree/InvenTree/issues/3685#issuecomment-1256045401_

**Comment by SchrodingersGat** [comment]
There's a fully-qualified path here:

![image](https://user-images.githubusercontent.com/10080325/192074132-c26c8ccc-880b-47c2-a33d-45ec81d10443.png)

Is this not sufficient?

**Comment by Gigahawk** [comment]
I suppose, just seems like some wasted there, especially since the short strings code is already implemented elsewhere

**Comment by SchrodingersGat** [comment]
The "short strings" is implemented in a different spot and won't transfer to rendering the data here. As the fully qualified path is already displayed here, I'm going to close this one out :)
