### ISSUE TITLE
[Bug] Selecting and deleting multiple BOM items does not delete multiple items.

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#3718]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I noticed that when I select(using checkbox) multiple BOM items and click "delete", I will get a "Delete selected BOM items?" prompt but only one of the selected items will be listed in the prompt and only one of them will be deleted.

Furthermore, when clicking the "Tools" button above the BOM and then clicking "Delete items", nothing happens.

### Steps to Reproduce

Issue A:
1. Browse a BOM
2. Select >1 items with the checkboxes
3. Click the red "delete" button on the right side of the BOM item
4. Prompt displays only one item and only one item will be deleted

Issue B:
1. Browse a BOM
2. Select 1 or more items with the checkboxes
3. Click "Tools" menu above the BOM, click "Delete items"

### Expected behavior

When selecting one or more items using the checkboxes, it is expected that they will all be deleted

When clicking the Tools-Delete Items menu, it is expected that items will be deleted. 

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.8.3

**Comment by SchrodingersGat** [comment]
@tehkillerbee so you don't see a dialog box like this:

![image](https://user-images.githubusercontent.com/10080325/192248910-64559a99-ded2-4aad-b3da-1d6d75c6eb2a.png)

**Comment by tehkillerbee** [comment]
@SchrodingersGat I first tried clicking the "Delete items" button above the BOM but nothing happened.
![image](https://user-images.githubusercontent.com/815886/192251815-d20c3c0f-633c-4402-b765-b354e81bda7c.png)

Then I tried clicking the Delete button next to one of the items (after checking multiple items)
![image](https://user-images.githubusercontent.com/815886/192252068-15b73c85-6e68-40b9-bd6b-88c4274a5a13.png)
In this case, only the specific item that I clicked delete will be listed.
![image](https://user-images.githubusercontent.com/815886/192252218-537b778d-9d20-41aa-879f-bf06b91c5cc3.png)

How did you get the prompt with multiple items listed? Perhaps there is something broken with my installation?

**Comment by SchrodingersGat** [comment]
> I first tried clicking the "Delete items" button above the BOM but nothing happened - the menu just closes again.

This is what I did. Maybe there's an error? Open up the developer tab and see if there are any error messages in the console.

> Then I tried clicking the Delete button next to one of the items (after checking multiple items)

The delete buttons in each row are for deleting individual items - it does not matter which rows are "selected" via the checkbox in this case.

**Comment by tehkillerbee** [comment]
@SchrodingersGat Ok, so it could be an error with my setup then. How do I view the developer tab?

> The delete buttons in each row are for deleting individual items - it does not matter which rows are "selected" via the checkbox in this case.

That makes sense, I also usually use the "Tools" menu above the list when editing multiple items.

**Comment by SchrodingersGat** [comment]
> How do I view the developer tab?

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools

**Comment by tehkillerbee** [comment]
@SchrodingersGat Hah, sorry for the stupid question, I assumed it was a feature built into InvenTree - and not the browser developer tools tab that I am very much aware of :). When clicking the "Delete items" button, I immediately get this error in the console:
```
Uncaught ReferenceError: getTableData is not defined
    <anonymous> http://192.168.10.154:1337/part/77/:2030
    jQuery 9
    <anonymous> http://192.168.10.154:1337/part/77/:2027
    onPanelLoad http://192.168.10.154:1337/js/dynamic/nav.js:79
    jQuery 7
    activatePanel http://192.168.10.154:1337/js/dynamic/nav.js:54
    enableSidebar http://192.168.10.154:1337/js/dynamic/nav.js:100
    jQuery 9
    enableSidebar http://192.168.10.154:1337/js/dynamic/nav.js:94
    <anonymous> http://192.168.10.154:1337/part/77/:2373
    jQuery 13
```
There are a few other warnings/errors displayed, although I am not sure if they are important
```
Source map error: Error: request failed with status 404
Resource URL: http://192.168.10.154:1337/static/script/chartjs-adapter-moment.js
Source Map URL: chartjs-adapter-moment.min.js.map
...
Source map error: Error: JSON.parse: unexpected character at line 13 column 1 of the JSON data
Resource URL: http://192.168.10.154:1337/static/script/moment.js
Source Map URL: /sm/ac6ca6e51d8435fbb492538442f7060550b81bb0c2505d4048856d957213e3a8.map
```

**Comment by SchrodingersGat** [comment]
```
Uncaught ReferenceError: getTableData is not defined
```

This function is defined in `tables.js`

https://github.com/inventree/InvenTree/blob/8bcf72fbb2d0f7285cd21a96a03d32703097429f/InvenTree/templates/js/translated/tables.js#L105

Is it possible that your browser has cached an older invalid version of this javascript file?

Please trying doing a hard-refresh of the page (e.g. Ctrl+Shift+R) and see if the error message goes away

**Comment by tehkillerbee** [comment]
@SchrodingersGat Ah, perfect! I did as you suggested and now I can delete etc. without any problems. So it looks like I need to remember doing a hard-refresh when updating InvenTree. 

I will close this issue, since there is no bug after all. :)
