### ISSUE TITLE
Webcam barcode reading failed with "no URL in response"

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#3724]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Scanning a valid stockitem QR code results an error. QR codes not interpreted.

### Steps to Reproduce

Select a stockitem
Print a QR code
Open "scan barcode" dialog
Use a hand scanner or the webcam scanner to scan the code
You will get:
<img width="562" alt="Képernyőfotó 2022-09-27 - 18 09 12" src="https://user-images.githubusercontent.com/580623/192579338-cf0af2ab-c5a5-477f-82c0-4cfd84bb0473.png">

### Expected behavior

Interpret the QR code like before and jump to the part/stockitem/etc

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

Recent master, demo.inventree.org
# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: fbde70d
Commit Date: 2022-09-27
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by rkalman** [comment]
InvenTree/templates/js/translated/barcode.js
barcodeScanDialog() / onScan
Handling the new server response format is completely missing...

**Comment by SchrodingersGat** [comment]
@rkalman thanks for reporting this. Fix incoming in #3727

**Comment by rkalman** [comment]
Thank you Oliver!
