### ISSUE TITLE
docker-compose invalid interpolation format

### ISSUE THREAD

**Issue by totallylostagain** [inventree/InvenTree#3733]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Greetings,

I'm, not sure if this is a bug or I am just too dumb so I thought I might ask here.
Currently I'm trying to install it via Docker, which already worked on a Ubuntu 22.04 Teststation. So now I am trying to install it on a Corporate VM which runs on a CentOS 7. The Image is pulled and ready, I copied the 3 files from the instruction page and edited the .env file. They are currently copied to /docker/production

I changed the volume to INVENTREE_EXT_VOLUME=/docker/production also I have changed and uncommented the INVENTREE_DB_USER and INVENTREE_DB_PASSWORD
But as soon as I start "docker-compose run inventree-server invoke update" I get this error:
 
ERROR: Invalid interpolation format for "environment" option in service "inventree-db": "POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}"

Regards,
Alex

### Steps to Reproduce

1. sudo su
2. cd /docker/production
3. ls -> shows all 3 files
4. docker-compose run inventree-server invoke update

### Expected behavior

Installing Inventree

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.8.3 Stable

### Relevant log output

```shell
Invalid interpolation format for "environment" option in service "inventree-db": "POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}"
```
[env.txt](https://github.com/inventree/InvenTree/files/9675034/env.txt)

**Comment by matmair** [comment]
@totallylostagain you need to provide the name of the postgres database in the .env file under the variable `INVENTREE_DB_NAME` -  as the error describes it.

**Comment by matmair** [comment]
Also not sure how happy your IT security person is with copying files and running docker as superuser  - that means you probably will also run as superuser. That is not really best practice - [this SO article](https://stackoverflow.com/questions/68155641/should-i-run-things-inside-a-docker-container-as-non-root-for-safety) has lots of good info why that can be problematic.

**Comment by totallylostagain** [comment]
Thanks for the quick reply, I will try it out and report back. I was just a bit confused because when I set it up under Ubuntu I didnt have to set up a Database or change a name. All I did was download the Image and run the docker-compose command and everything was set up to the point I just had to start it and access it under 127.0.0.1.

**Comment by matmair** [comment]
@totallylostagain are you sure you are using the same settings? We have a development setup (not save for production usage!!) that just runs and is not very performant and a production setup that is a bit more involved. See the details here: https://inventree.readthedocs.io/en/latest/start/docker_prod/

**Comment by totallylostagain** [comment]
@matmair Yeah, i've been closely following the docker_prod instructions. On my testbench I was using the 3 provided files.
I think I've copied the wrong error message though, I am very sorry. 

Invalid interpolation format for "environment" option in service "inventree-db": "POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}"

The thing is, in the .env file I have provided a INVENTREE_DB_USER and a INVENTREE_DB_PASSWORD
Let me attach my .env (I will just replace the name and password with the standard)

[env.txt](https://github.com/inventree/InvenTree/files/9674661/env.txt)

**Comment by totallylostagain** [comment]
I pulled up my command history of my testbench and did the exact same steps like before, still getting the "you must provide the Inventree_DB_USER variable in the .env file!" error.
Is there some kind of different approach on CentOS 7 that I am missing?

**Comment by matmair** [comment]
@totallylostagain I have not used CentOS in years but a shot in the dark: have you looked into the permissions for docker and the .env file?

**Comment by SchrodingersGat** [comment]
@totallylostagain what version of docker compose are you running?

```
docker-compose --version
```

**Comment by SchrodingersGat** [comment]
@totallylostagain I'm going to close this out due to inactivity. If you have any further queries please comment again here
