### ISSUE TITLE
[FR] Add native LDAP

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3746]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

We currently do not provide a native LDAP integration - which is often needed together with SAML for enterprise users.

### Suggested solution

Native inclusion of ldap - maybe via django-auth-ldap. A problem I see is the native dependency tree for python-ldap; Maybe it could be modified to use python-ldap3 to make the footprint slimmer.

### Describe alternatives you've considered

Current way with cusotm middleware and auth backends works too - but only for advanced users.

### Examples of other systems

netbox

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
This is a prime candiatate for a company or enterprise to sponsor an implementation.

**Comment by gooutbefree** [comment]
As a starting point:
In our system I did a dirty hack and modified settings.py. It works for authentification but the mail address isn't taken from the ldap -> problems with allauth? I'm not good enough to propose a clean solution
(works with stable 0.8.x)

```
import ldap
from django_auth_ldap.config import LDAPSearch, LDAPGroupQuery, PosixGroupType
```

```
AUTHENTICATION_BACKENDS = CONFIG.get('authentication_backends', [
    'django.contrib.auth.backends.RemoteUserBackend',           # proxy login
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',      # SSO login via external providers
    'django_auth_ldap.backend.LDAPBackend',
])

AUTH_LDAP_SERVER_URI = "ldap://localhost:389"
AUTH_LDAP_BIND_DN = ""
AUTH_LDAP_BIND_PASSWORD = ""
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "ou=people,dc=company,dc=com", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
)

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    "ou=group,dc=company,dc=com",
    ldap.SCOPE_SUBTREE,
    "(objectClass=posixGroup)",
)
AUTH_LDAP_GROUP_TYPE = PosixGroupType(name_attr="cn")
AUTH_LDAP_REQUIRE_GROUP = "cn=users,ou=group,dc=company,dc=com"
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "cn=users,ou=group,dc=company,dc=com",
    "is_superuser": "",
#     "is_staff": "cn=users,ou=group,dc=company,dc=com",
}

AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_CACHE_TIMEOUT = 2000
ACCOUNT_EMAIL_VERIFICATION = "none"
```

**Comment by matmair** [comment]
@gooutbefree this is really not advised. Updates are gonna be a PITA with this and the installer etc. probably will break too. A better way is to import the settings in a new settings file, add those changes there and then set the [environment variable](https://docs.djangoproject.com/en/4.1/topics/settings/#envvar-DJANGO_SETTINGS_MODULE) accordingly.

The package also requires os-level packages (at least on Debian 11) if anyone else sees this. Please look at [django-auth-ldap](https://django-auth-ldap.readthedocs.io/en/latest/install.html) and the [ldap](https://www.python-ldap.org/en/python-ldap-3.4.3/installing.html) requirements.

**Comment by matmair** [comment]
Still searching for sponsor

**Comment by compumatter** [comment]
@SchrodingersGat @matmair I have an interest in sponsoring native LDAP functionality depending on what that is.  Please reach out to me with your thoughts on that.

**Comment by matmair** [comment]
If https://github.com/django-auth-ldap/django-auth-ldap/pull/208 or something similar gets merged LDAP support would be included instantly so maybe direct your monetary contributions there. There is a very current discussion around the inclusion [here](https://github.com/django-auth-ldap/django-auth-ldap/issues/325).

I will integrate python-auth-ldap myself, I have used it over a dozen times. I just really do not want to deal with OpenLDAP and all the hassle it brings users during the installation. And the container image increase it brings.

**Comment by compumatter** [comment]
Just a follow up on this.  Samba no longer requires on OpenLDAP as a solution.   Samba 4 comes AD DC comes embedded with it's own LDAP solution now which is more closely aligned with the Microsoft AD implementation.  They are now in control of their own destiny.  From what I can tell they have zero plans to support OpenLDAP moving forward.  https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller

**Comment by matmair** [comment]
I just rechecked other Django projects: netbox also does not include LDAP (anymore I think, I seem to recollect it did at some time). They point to the same library and docs as we do for LDAP.
https://demo.netbox.dev/static/docs/installation/6-ldap/

**Comment by User220419** [comment]
Is SimpleSAMLphp an option? https://github.com/simplesamlphp/simplesamlphp-module-ldap
I know extremely little of SAML so I'm quite lost on this topic. I'm just trying to get authentication to work with with method provided by IT - that is LADPS.

**Comment by matmair** [comment]
You could probably use that as middleware. InvenTree is written in Python so you would need a small PHP web app that does the conversion.
