### ISSUE TITLE
Keep a complete history of records

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#377]
Use django-simple-history

https://django-simple-history.readthedocs.io/en/2.7.2/

**Comment by fenugrec** [comment]
Does this refer to, for example, keeping track of stock operations ? I have in mind something like an entry "[part], [date] : removed N items for [reason/project]" for every operation , similar to what partkeepr does.

**Comment by SchrodingersGat** [comment]
Exactly right. Currently InvenTree does do this but in a very naive way. Migrating to using django-simple-history would provide a much richer experience (although it will be a headache to achieve!)

**Comment by eeintech** [comment]
@SchrodingersGat Where do you stand on history tracking for all InvenTree instances? Is that still on your wishlist?

I'm just curious to know what forces would drive the use of history tracking package, because other than stock (which is tracked already) I don't clearly see a path forward with this.

**Comment by SchrodingersGat** [comment]
Not really sure on where I want to see this going, currently. It is a *very* complex problem. Even if you have a complete history, how do you "unwind" without breaking some other data?

This one will probably have to stay on the backburner for a while

**Comment by eeintech** [comment]
The more wait, the more complex it gets 😃 But yes I agree with you, I don't have much experience with it either besides my tiny attempt to create history for parts. This could be a full time project for a while.
