### ISSUE TITLE
[FR] Using # in Part Names

### ISSUE THREAD

**Issue by Fluxus00** [inventree/InvenTree#3775]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I am currently trying to import my old partkeepr database into partkeepr, but it seems like Invnetree is not allowing '#' in a part name. Those # are quite important for my inventory structure, and it would not be easy to replace those.

There might be some other people out there with the same or a similar problem, that is why i would recommend to allow # in part names.

### Suggested solution

I would suggest to support # in part names.

### Describe alternatives you've considered

-

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
The existing part naming restrictions are outdated now, recent improvements (especially around sanitisation of data) may have rendered these redundant.

@matmair can you see any reason not to allow these restricted characters back into the part naming schema?

**Comment by matmair** [comment]
@SchrodingersGat I see no security reason; the only thing I can think of is possible collisions in the URL schema (ie if we use a part name there a # is certainly not a good symbol to have).
Should be good to go. TBH this is very low on my priority list - would be a good first issue / hacktober thing.

**Comment by matmair** [comment]
A good starting point for the required changes is this validator; The character should be removed from the blocklist and then some testing (if something broke) is required
https://github.com/inventree/InvenTree/blob/193b69eeb59e0fb8fe431dd1905626b380446067/InvenTree/InvenTree/validators.py#L40-L46

**Comment by SchrodingersGat** [comment]
@matmair I've another PR in the works which makes sense to roll this into, I'll tackle it :)

**Comment by gooutbefree** [comment]
I would appreciate # because e.g. Texas Instruments uses it in standard part names and these parts can't be handeled right now

**Comment by matmair** [comment]
@gooutbefree we are working on it. Small team so it might take a while.
