### ISSUE TITLE
[FR] Add backup into inventrees lifecycle

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3778]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

We are currently leaving database and media backups up to the users. As the user base seems to be less and less technical it might be good to include some basic backup into the product.

### Suggested solution

I use [dbbackup](https://github.com/jazzband/django-dbbackup) in other codebases, it works reasonable enough and would be compatible with the storage backend - should we choose to support k8 in the future.

### Describe alternatives you've considered

The current way works for seasoned sysadmins.

### Examples of other systems

Snipe-IT, Nextcloud have good backup systems.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
This might also be interesting for enterprise users; maybe some company using InvenTree is willing to sponsor the project a bit for getting this into the codebase.

**Comment by SchrodingersGat** [comment]
This is a great idea
