### ISSUE TITLE
[FR] Add monitoring endpoint

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3781]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

We currently do not provide a fully documented monitoring endpoint.

### Suggested solution

- [ ] Add endpoint that returns json of current state
- [ ] use a token to secure access
- [ ] include django state check results
- [ ] include background job stateDjango

### Describe alternatives you've considered

NA

### Examples of other systems

Zammad has a good, simple implementtion: [docs](https://admin-docs.zammad.org/en/latest/system/monitoring.html)

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
This is a pretty simple, isolated issue with a good reference to sample docs. Leaving this for volunteers for now.

**Comment by SchrodingersGat** [comment]
@matmair if you navigate to `/api/` some of this functionality already exists. Do you want some specific details above and beyond this?

![image](https://user-images.githubusercontent.com/10080325/195460767-2297e349-3d8a-494d-8b06-fc12ca8ae646.png)

**Comment by matmair** [comment]
@SchrodingersGat I would like to have something dedicated like Zammad; my normal setup is to call that endpoint every 30 seconds so something really speed/resource optimised would be great. Also if everything is fine I just want an 'ok' and maybe a version back.

**Comment by matmair** [comment]
The better caching solution took care of this.
