### ISSUE TITLE
[FR] Assign Bar Code to Part

### ISSUE THREAD

**Issue by Rincewind34** [inventree/InvenTree#3786]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

(_maybe I was too dumb to find it in InvenTree and it is already possible - my deepest apologies if that is the case)_

In my system, I have parts that have serial numbers (and everyone has their own bar code /= stock item) and I have parts that don't have a serial number e.g. cables or adapters. I still want to be able to assign a bar code to these components and ideally, they would all have the same bar code.

### Suggested solution

I'd like to be able to assign a bar code to the Part and by scanning an the bar code being referred to the Part instead of concrete Stock Item.

### Describe alternatives you've considered

I'd be very happy on input concerning this topic.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
hi there @Rincewind34 

This should be already possible; You can link the part but not the non-serialised stock-item.
![grafik](https://user-images.githubusercontent.com/66015116/196008502-a9217194-e6c9-47b2-8ad4-b8111bfed454.png)

Is this what you are looking for?

**Comment by Rincewind34** [comment]
@matmair Yes, I wasn't running the lastest development version but saw it in the source code. Thanks!

**Comment by matmair** [comment]
@Rincewind34 you do not need to be; if you have time you could verify on the [demo](https://inventree.readthedocs.io/en/latest/demo/) - that is running bleeding edge.

**Comment by SchrodingersGat** [comment]
@Rincewind34 this feature will be released to "stable" when [0.9.0](https://github.com/inventree/InvenTree/milestone/20) is available :)
