### ISSUE TITLE
[Bug] User without stock location role can see locations of individual items.

### ISSUE THREAD

**Issue by Weissnix4711** [inventree/InvenTree#3796]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Not sure if this is a bug, or just an oversight in the current permissions / roles system.

A user without permission to view stock locations (ie, not assigned to a group with the stock locations role), can still see the stock locations of individual stock items, both in the stock items list (`/stock/`) and in the individual stock items' pages (`/stock/item/xx/`).

See screenshot. I've had to remove part of the stock location, because it contains an address.

![Screenshot from 2022-10-16 17-09-26](https://user-images.githubusercontent.com/42943391/196046040-e883dd99-d34f-4c61-ad8c-17f22a3c05fa.png)

### Steps to Reproduce

Create a new user, and assign it to a new group with Stock Item view permission but uncheck all permissions related to Stock Location.

### Expected behavior

I would expect the stock location information to be hidden everywhere, for users without that role.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.1
Django Version: 3.2.15
Commit Hash: fb97385
Commit Date: 2022-08-08
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by matmair** [comment]
Thanks for the report @Weissnix4711 !

**Comment by SchrodingersGat** [comment]
I think there are a *lot* of small instances like this where permissions are not correctly observed in the UI.

Moving to react means we have to make more use of the API, which *does* enforce permission checks, so probably best (and simplest) to address it then.

**Comment by SchrodingersGat** [comment]
@Weissnix4711 a long time coming but this is getting closed in https://github.com/inventree/InvenTree/pull/8785

I am not saying that we have fixed *all* the permission issues, but the new user interface is now in place and it has a much improved permissions system.
