### ISSUE TITLE
Natural Sort on Part Name

### ISSUE THREAD

**Issue by mk2driver** [inventree/InvenTree#3812]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I've seen a few reports of natural sort issues and some of these have been resolved, but it also seems to be missing in the main Parts listing table.  Is this a bug or is there an option to set the sort behaviour somewhere that I'm missing?

### Steps to Reproduce

Go to Parts or select a subcategory of parts that contain numeric substrings.  Taking the following parts as an example, they are listed using non-natural sorting.

Widget 1.123
Widget 10.500
Widget 11.800
Widget 5.050
Widget 9.750 

### Expected behavior

When clicking on the Part header to sort by part name (incrementing), these parts should be listed as follows...

Widget 1.123
Widget 5.050
Widget 9.750
Widget 10.500
Widget 11.800 

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.3
Django Version: 3.2.15
Commit Hash: f9d2b14
Commit Date: 23-09-2022
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
@mk2driver thanks for asking. This is *not* a bug, as natural sort has not been implemented for part numbers.

"Natural" sorting does not have a single solution, as what the user considers "natural" may vary from one setup to another. 

Some database fields support custom sorting:

- Serial number
- Sales / Purchase / Build Order reference

Initially the sorting was very naïve - if the field "look" like an integer, we extract and cache that integer for storage. This means that each field has another field (e.g. `serial_int` vs `reference`) which is used as a primary field for sorting.

However, recently I implemented a [plugin system](https://github.com/inventree/InvenTree/pull/3776) to allows users to specify custom management of serial numbers. 

It would be possible to extend this plugin system (and add a secondary name sorting field to the "part" model) to provide the functionality you want. At this stage this is not a development priority, but if you would like to contribute this yourself, or sponsor the feature, that would be a way to get it developed quicker.

**Comment by SchrodingersGat** [comment]
@mk2driver marked as "roadmap" for now :)

**Comment by matmair** [comment]
@mk2driver sorting in even one DBMS can fill multiple chapters in a computer science book - it is a fascinating and hard-to-generalise problem. One example is [number ordering within strings](https://dba.stackexchange.com/questions/285222/how-to-treat-numbers-within-strings-as-numbers-when-sorting-a3-sorts-before).
As we support multiple engines we can not use all the specialised features some systems like PostgreSQL supply so this one might be farther out.

**Comment by matmair** [comment]
@SchrodingersGat should we leave this open or close as `wontfix`? I feel like this is intended behaviour.

**Comment by SchrodingersGat** [comment]
Potentially could be implemented as a plugin, but no interest from me and would be difficult to implement from a DB perspective.
