### ISSUE TITLE
Error 404: Resource not found - /api/settings...

### ISSUE THREAD

**Issue by mrkylegp** [inventree/InvenTree#3813]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Fresh install via the single install script. I only changed the port to 83 in the nginx config for inventree because I have another apache site running on port 80 already.

I can access inventree fine via the local ip and port 83 (Eg. 192.168.1.111:83)

Most things work, images load, I can create categories, parts etc. but whenever I try to change a variety of setting I get a 404 for /api locations.

Any idea why this might be occuring?

![Screenshot 2022-10-20 094005](https://user-images.githubusercontent.com/52687659/196818378-ffa58c68-a231-447a-b55f-97b6a333d524.png)

### Steps to Reproduce

Attempt to change most setting toggles

### Expected behavior

Settings change with no error

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.9.0 Development

**Comment by SchrodingersGat** [comment]
@mrkylegp can you please share the exact commit hash for the version you are running? This seems like a [bug which was recently fixed](https://github.com/inventree/InvenTree/pull/3760)

**Comment by mrkylegp** [comment]
> @mrkylegp can you please share the exact commit hash for the version you are running? This seems like a [bug which was recently fixed](https://github.com/inventree/InvenTree/pull/3760)

@SchrodingersGat 
I only just installed it today with the auto install script. I've also checked that it's up to date with apt update.

How can I get the hash commit?

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/196914018-b50cf8f6-3f68-44e4-9fcb-ace8f6da621e.png)

![image](https://user-images.githubusercontent.com/10080325/196913924-7a6a0371-1405-4dfa-9361-838b098a207d.png)

**Comment by matmair** [comment]
@SchrodingersGat git metadata is optional and depends on git being installed.
@mrkylegp could you install git and restart inventree?
```bash
sudo apt install git -y
sudo service inventree restart
```

**Comment by mrkylegp** [comment]
> ```shell
> sudo apt install git -y
> ```

@matmair Git is already installed. Restarting Inventree made no difference in behaviour.

**Comment by matmair** [comment]
@mrkylegp full git client or the slim variant?

**Comment by mrkylegp** [comment]
> @mrkylegp full git client or the slim variant?

@matmair The full client.

**Comment by SchrodingersGat** [comment]
@mrkylegp can you try doing a hard-refresh in your browser? It is possible that some of the javascript files are not being updated properly after upgrade, due to browser cache. LMK if that fixes it.

**Comment by mrkylegp** [comment]
> @mrkylegp can you try doing a hard-refresh in your browser? It is possible that some of the javascript files are not being updated properly after upgrade, due to browser cache. LMK if that fixes it.

@SchrodingersGat Thanks for the suggestion but I already tried this in addition to testing on a completely separate PC that has never loaded Inventree before as well as installing a few different browsers on my own PC and still the same issue.

**Comment by mrkylegp** [comment]
I have switched to a docker setup for now but would be happy to test further regarding this bare metal install issue. Let me know if you have any further suggestions as I've exhausted everything I can think of.

**Comment by SchrodingersGat** [comment]
@mrkylegp only other thing I can think of at this point is for you to extract the git commit hash manually.

Navigate to where InvenTree is installed on your machine, and run ```git rev-parse --short HEAD```

**Comment by mrkylegp** [comment]
I'm gonna spin up an Ubuntu 20.04 server in a fresh VM, run the install script and see if I have any issues there then report bacl.

**Comment by SchrodingersGat** [comment]
I believe that I have now squashed this bug in master. I'm going to close this out for now, please comment here again @mrkylegp if you think it is still present.
