### ISSUE TITLE
[FR] Breadcrumb/Burger Menu navigation improvement

### ISSUE THREAD

**Issue by Zennate** [inventree/InvenTree#3814]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

The breadcrumb/burger menu at the top of the main menu needs precision to be navigated correctly.
Example:
![grafik](https://user-images.githubusercontent.com/92428456/196888650-4d4fab48-9ef1-4f38-8628-678773afcdf6.png)
Clicking on the field of Category A reveals Sub-category B.
Clicking on the names of Category A or B loads the appropriate name.
Clicking on the field of Category B has no effect, despite the changed cursor.

Additionally exiting this menu without switching can only be achieved by clicking the button again. This can be irritating when trying to traverse the menu quickly on larger displays.

### Suggested solution

Expanding the \<a\>-tag of categories that do not have a sub-category to cover the entire field would make it easier to select the desired category. The behaviour of Category A should probably not be changed, since these categories are most likely used for organizing sub-categories.

Exiting the menu could alternatively be achieved by clicking an empty space that is not part of the menu itself. I'm unsure if this would need a seperate FR, since it affects the same menu and functionality.

### Describe alternatives you've considered

An alternative to using this menu altogether would be a mixed view in the main window, where you could see sub-categories and parts contained in your selected category in one list, instead of switching between categories and parts using the left-hand menu. This would probably require more effort overall though.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@Zennate thanks for reporting. Would you like to contribute this enhancement yourself?

**Comment by matmair** [comment]
@SchrodingersGat I would recommend moving this to 0.10.x and closing 0.9.x for new issues if not related to bugs.

**Comment by Zennate** [comment]
@SchrodingersGat thanks for the quick response. I'm sadly out of my depth with the current codebase, so I'll stick to providing feedback for now.

**Comment by matmair** [comment]
TBH any work done on this would probably be lost in the transition to a framework as it would probably be tailored to the current jquery way of doing things.
If somebody really wants that change they can send a patch - I have no objection to changing this.  Changing the tree menu while keeping it somewhat performant (the current solution is by no means fully optimised) could represent a significant amount of work as it took several iterations to come to the current one.
