### ISSUE TITLE
[FR] Remove need to refresh browser cache after update

### ISSUE THREAD

**Issue by MR-DOS** [inventree/InvenTree#3816]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

It seems that if Inventree is updated (in my case from 0.7.6 to 0.8.3), previously active user sessions still work but certain unexpected things may break.
I noticed that in the Parts-Categories view, you cannot see the amount of parts in categories. Also, "About Inventree" button does not work.
Happens on admin/superuser account as this is the only one I use on my computer, cannot tell for other users.
Clearing cookies resolves the problem.
No errors are thrown, at least not visible under the admin panel.

### Steps to Reproduce

1. Start up 0.7.6 Inventree from Docker.
2. Log in, create some categories and parts. You should be able to see amount of parts in a given category in tree view. Do not log out. My computer with this session was hibernated while I was upgrading the server.
3. Stop the server and upgrade image to 0.8.3, invoke update.
4. Start the server. (At this step, for me, a lot of errors from database about some not existing columns were thrown. It looked like it was mostly if not all about user session keys. As usual - I'm a user who does not understand what happens under the lid.)
5. Open the Parts-Categories view. Instead of numbers of the parts, all you can see, is "-". The error persists until cookies are cleared manually.
6. Try pressing the "About Inventree" button. Nothing happens. The error persists until cookies are cleared manually.

### Expected behavior

After server update, Inventree should detect that incompatible cookies are stored on user computer and they should be corrected/invalidated.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.3
Django Version: 3.2.15
Commit Hash: f9d2b14
Commit Date: 2022-09-23
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
@matmair do you know if there is any way of automatically invalidating the cookie when the version is updated? Perhaps we could tie the session cookies to the version number?

**Comment by matmair** [comment]
We could just invalidate all sessions on update but that would force all users to log back in - might be a bit much.

**Comment by MR-DOS** [comment]
@matmair I removed all data (cookies+whatever else) originating from my server's domain since I could not find any other way to do such an operation in Firefox. Then I switched back to Inventree (interestingly, I did not land on login page but some kind of internal Firefox dialog popped up, so I had to click several times on cancel), logged in and everything went back to normal.

**Comment by matmair** [comment]
Ok I am pretty sure this is a problem with the assets.
@SchrodingersGat we could switch to using [ManifestStaticFiles](https://docs.djangoproject.com/en/4.1/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage) - that would make refreshes unneeded; Might add slight overhead storage wise in the static files section as normally old files are not deleted. The tradeoff is well worth it in my book.

**Comment by matmair** [comment]
@SchrodingersGat I started working on ManifestStaticFiles as a storage backend, the whole refreshing problem will completely be gone with it implemented.
Go ahead with that solution? Not really a bug but a section in the docs that is often missed and would be cool to be removed.

**Comment by SchrodingersGat** [comment]
@matmair I'd like to know if the manifest static files approach works well with our pre-compiled translated javascript files?

Otherwise, it looks like a good idea, we have to troubleshoot so many problems which just come down to outdated javascript!

I'd like to integrate some sort of "cleanup" method too, if we can, so that the static dir does not become clogged with old files.

**Comment by matmair** [comment]
@SchrodingersGat 
1) yes, as we first precompile, Place them into static and then collect static. At this point the would/will be indexed
2) the easiest way would be to clean static and then just copy everything over again. Not sure how sufficient that is speed wise - probably slower then what we do right now

**Comment by matmair** [comment]
![grafik](https://user-images.githubusercontent.com/66015116/197365869-6be60977-a315-431d-a695-ad937cf418a0.png)
https://inventree.readthedocs.io/en/latest/faq/#feature-x-is-not-visible-after-update
This is known behaviour so fixing this in the release after the next one should be fine

**Comment by SchrodingersGat** [comment]
@matmair sounds like a good idea overall, then.

**Comment by matmair** [comment]
PUI does not have this problem so I am wondering if we have to address it in CUI or can close this. Thoughts @inventree/triage @inventree/maintainer?

**Comment by wolflu05** [comment]
IMO we could close this, because PUI will replace CUI in some time and its not worth the time to implement this also in CUI.

**Comment by SchrodingersGat** [comment]
Agreed
