### ISSUE TITLE
Subcategories view is unstable if switching between flat and tree view until page is reloaded

### ISSUE THREAD

**Issue by MR-DOS** [inventree/InvenTree#3817]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Switching between Display as list and Display as tree view does not work correctly and requires reloading the page to work properly.
Tested on Parts-Subcategories and Stock-sublocations.
Tested both on 0.8.3 official docker image and 0.9.0 dev version from Inventree demo.

### Steps to Reproduce

1. Open Inventree demo. Open the Parts-Subcategories view.
2. Switch to Display as list. Press F5.
3. Switch to Display as tree view. The list looks the same as it does not show subcategories. (Note - by default, no filters shall be applied.)
4. Press F5. Now, the tree view correctly shows up as tree.
5. Switch back to Display as list. The list still lists the tree view, just as a "flat" display with no indentation and any hints on the tree structure.
6. Press F5. Now, the list is correctly shown and no subcategories are shown.
7. Now, apply filter "Include subcategories = true". Switch to Display as tree view. All entries are now indented by the same amount and the drop-down arrows are not shown, thus it does not look like tree view.

### Expected behavior

The page could be reloaded when switching view methods.
Also, the whole display area could reload.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.3
Django Version: 3.2.15
Commit Hash: f9d2b14
Commit Date: 2022-09-23
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by matmair** [comment]
hi there @MR-DOS thanks for the great report. I can confirm the problem, not really sure where it has its origin. @SchrodingersGat Could this be something to do with the frontend code?
