### ISSUE TITLE
[FR] External Part Number (EPN)

### ISSUE THREAD

**Issue by Rincewind34** [inventree/InvenTree#3823]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Most of the parts I order to build my products have an unique ID. That helps especially when there are multiple very similar parts that can be bought. As a practical example:
Neutrik produces two HDMI ports. One in a metal chase (NAHADMI-W) and one in a plastic chase (NAHADMI-W-B). As you can see this is very easy to get wrong when my description just says "Neutrik HDMI Port".

### Suggested solution

Add a value field to the part for that purpose.

### Describe alternatives you've considered

- Use the IPN. We don't use the number for anything (I think, still new to all of this) but in general this value field serves the right functionality.
- Use a part parameter (template). This seems to serve exactly my situation but it wouldn't be displayed in the parts table. (or can it?)
- Somehow maintain that in the supplier part. This wouldn't be a good idea at all, since Neutrik sells over multiple suppliers, which of course all sell under the same "EPN".

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
I believe all the functionality you need is right there. If you want to track a unique part "number" for a part, that's exactly what `IPN` (internal part number) is for.

If you want to track different parts from suppliers, that is what the Supplier Part model is for :)

**Comment by Rincewind34** [comment]
Ah ok great! I was a bit confused about "internal". Because in theory our assembled parts have of course a (four digit) number, that later becomes either the entire bar code or part of the bar code, if we are tracking individual stock items. In my head this was kind of how I wanted to use the IPN.
Is there a way to do it you would recommend?

**Comment by SchrodingersGat** [comment]
> Is there a way to do it you would recommend?

You can make use of this IPN field however you like :) Also check out the [validation plugin](https://inventree.readthedocs.io/en/latest/extend/plugins/validation/#part-ipn) which allows you to customize the IPN implementation even further :)

**Comment by Rincewind34** [comment]
Thank you very much!
