### ISSUE TITLE
[FR] Session IP address behind Cloudflare Tunnel

### ISSUE THREAD

**Issue by rezafouladian** [inventree/InvenTree#3824]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

When using Cloudflare Tunnels as a reverse proxy, all sessions are shown as 127.0.0.1.

This is running using the one line deployment script from Ubuntu 20.04.5.

### Suggested solution

As a patch on my end, I edited `/etc/nginx/sites-enabled/inventree.conf`, which was originally:
```
server {

    # Listen for connection on (internal) port 80
    listen 80;

    real_ip_header proxy_protocol;

    location / {
```

I changed it to:
```
server {

    # Listen for connection on (internal) port 80
    listen 80;

    set_real_ip_from 127.0.0.1/0;
    real_ip_header CF-Connecting-IP;

    location / {
```

This successfully resolved the issue. However I am unsure what issues this may cause when not using Cloudflare Tunnel as a reverse proxy. When connecting locally bypassing the tunnel, it detected my local IP address correctly.

### Describe alternatives you've considered

There seem to be a few other methods of doing this, I'm not certain which one would be best.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
As this is Cloudflare specific I think this will not get merged; Maybe this would be a good addition to the docs @rezafouladian?
@SchrodingersGat do you disagree/agree?

**Comment by SchrodingersGat** [comment]
@matmair I agree, this is more of a problem for the sysadmin, not a native InvenTree "feature". However would be useful to add  a note to the docs

**Comment by nikolai2111** [comment]
@rezafouladian do you currently run the latest inventree through a cloudflare tunnel?

With the latest release I'm unable to configure the docker correctly, I nearly tried every config.

**Comment by rezafouladian** [comment]
@nikolai2111 I can update and see if it still works, I do not use docker however, just Ubuntu. 

This is my cloudflared config file, just points to nginx running on port 80:
```
tunnel: ___
credentials-file: /root/.cloudflared/___.json

ingress:
        - hostname: inventree.example.com
          service: http://localhost:80
        - service: http_status:404
```

**Comment by nikolai2111** [comment]
Thanks for your quick answer.
I'm not sure, but currently inventree is no longer using nginx.

I have running the endpoint of the tunnel on my proxmox host to access more than one VM through the tunnel. In the `.env` file I have specified a local URL for my inventree something like `http://inventree.local`. When I define one tunnel in cloudflare to direct to this local URL from something like `https://inventree.example.com` I can reach the server with commands like `ping` or `tracert` but in the explorer there is only a black page.

In my `.env` file I only have specified the following:
```
INVENTREE_SITE_URL="http://inventree.local"
```

I tried to add different combinations from the [Server Access Site](https://docs.inventree.org/en/stable/start/config/#server-access). One config I thought would work is the following:
```
INVENTREE_TRUSTED_ORIGINS=["http://inventree.local", "https://inventree.example.com"]
INVENTREE_CORS_ORIGIN_WHITELIST=["http://inventree.local", "https://inventree.example.com"]
```
But this does not work.

Could you please help me, I'm a noob at this kind of stuff.

**Comment by rezafouladian** [comment]
@nikolai2111 Are you able to reach the server at that address from the same point that the Cloudflare tunnel is running, like `curl http://inventree.local`?

Also do you have anything providing the DNS resolution for `inventree.local` to an IP address? Because just telling Inventree what URL it expects to be at won't do that.

**Comment by nikolai2111** [comment]
Thanks, for your answers, but I currently have other problems with the server.

I can ping it from the network and have added the same address to the Cloudflare tunnel.

**Comment by nikolai2111** [comment]
@rezafouladian, I solved the other problems, now I'm back and working on the problem with Cloudflare.

> @nikolai2111 Are you able to reach the server at that address from the same point that the Cloudflare tunnel is running, like `curl http://inventree.local`?
> 
> Also do you have anything providing the DNS resolution for `inventree.local` to an IP address? Because just telling Inventree what URL it expects to be at won't do that.

As you mentioned I used `curl -v inventree.local` and got the following output:
```
* Host inventree.local:80 was resolved.
* IPv6: (none)
* IPv4: 192.168.0.20
*   Trying 192.168.0.20:80...
* Connected to inventree.local (192.168.0.20) port 80
> GET / HTTP/1.1
> Host: inventree.local
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Content-Language: en
< Content-Length: 0
< Content-Type: text/html; charset=utf-8
< Cross-Origin-Opener-Policy: same-origin
< Date: Sun, 18 Aug 2024 15:54:34 GMT
< Location: /accounts/login/?next=/
< Referrer-Policy: same-origin
< Server: Caddy
< Server: gunicorn
< Vary: Accept-Language, Cookie
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< 
* Connection #0 to host inventree.local left intact
```

**Comment by GilDev** [comment]
@nikolai2111 Did you manage to get this to work at some point?

**Comment by nikolai2111** [comment]
> [@nikolai2111](https://github.com/nikolai2111) Did you manage to get this to work at some point?

Sadly nope, I'm sorry.

**Comment by GilDev** [comment]
I actually finally did. I struggled quite a bit, then started from scratch and now I’m in a configuration where both interfaces work through my tunnel! I can’t access InvenTree without the tunnel like from my LAN now but I guess that’s normal.

**Comment by nikolai2111** [comment]
Nice!

Can you share the `.env` file?

**Comment by GilDev** [comment]
Sure thing, it’s actually pretty bare, I only have this at the end of the default .env:

```
INVENTREE_SITE_URL="http://inventree.mydomain.com"
INVENTREE_TRUSTED_ORIGINS="http://10.0.0.9,https://10.0.0.9"
INVENTREE_CORS_ORIGIN_ALLOW_ALL=True
```

And this at the top of the Caddyfile:

```
{
    auto_https off
}
```
