### ISSUE TITLE
[BUG] Confirmation Email uses local ip for link URL

### ISSUE THREAD

**Issue by mrkylegp** [inventree/InvenTree#3827]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When sending a verification email, it shows the local IP not the set base URL

Eg. mywebsite.com

Hello from InvenTree!

You're receiving this e-mail because user kyle has given your e-mail address to register an account on https://mywebsite.com

To confirm this is correct, go to http://192.168.1.111:83/accounts/confirm-email/MQ:1olnC0:UXQyFESkK7GxGnQOOEJcP8AXY1gkd-bbeIK02tDoxoo/

Thank you for using InvenTree!
https://mywebsite.com

### Steps to Reproduce

1. Set base URL
2. Add an email
3. Send a verification email

### Expected behavior

URL should respect the base URL setting

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.3
Django Version: 3.2.15
Commit Hash: f9d2b14
Commit Date: 2022-09-23
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by matmair** [comment]
Can confirm.

**Comment by matmair** [comment]
Thanks for the excellent report @mrkylegp ! Should be an easy fix, starting work now.
