### ISSUE TITLE
[FR] Add package support for CentOS, SLE, Ubuntu 22.04

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3836]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

We currently do not package for [all possible](https://github.com/crohr/pkgr/wiki/Supported-distributions) operating systems. Missing are:
- [ ] Ubuntu 22.04
- [ ] CentOS
- [ ] Suse Linux Enterprise Server

### Suggested solution

Add support. That involves (per OS):
- [ ] extend the packaging configs
- [ ] check that all packaging scripts run through
- [ ] test installing on a local machine
- [ ] test updates
- [ ] test full plugin support
- [ ] test setting config values
- [ ] check all logs for errors
- [ ] check that logs work
- [ ] extend the installer
- [ ] full run-through with the installer on a new machine (DO, AWS, GCP, Azure, ...)
- [ ] check the set permissions, opened ports and added 3rd party software configs following security-best-practices
- [ ] extend docs with support

### Describe alternatives you've considered

The current support covers major LTSs and bare metal works on everything else

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Some more infos for anybody willing to tackle this:
- we use pkgr / packager.io for packaging
- the current state can be found on the [dashboard](https://packager.io/gh/inventree/InvenTree)
- the per-os settings are in this file: https://github.com/inventree/InvenTree/blob/master/.pkgr.yml
- packaging scripts are in this dir: https://github.com/inventree/InvenTree/tree/master/contrib/packager.io
- we only build the branches master/stable
- for development I recommend creating a fork, initiating packager.io for this fork (only enable the branch you use for packager work); this only works for public repos

**Comment by matmair** [comment]
Not stale, just nobody working on it

**Comment by SchrodingersGat** [comment]
Not stale  @github-actions

**Comment by matmair** [comment]
I think there is no visible intrest by users @SchrodingersGat can we close this?

**Comment by SchrodingersGat** [comment]
I'm happy to close it out if you think it's not worthwhile

**Comment by artizirk** [comment]
To get Inventree installed on Debian 13 Trixie I did the following


1. Create fake packages for python3.11 python3.11-dev python3.11-venv using `equivs` and install the resulting deb
	https://askubuntu.com/a/656153
2. Modify [install.sh](https://github.com/inventree/InvenTree/blob/master/contrib/install.sh#L76) by adding modifying debian version detection with those lines

```
if [[ $VER == "13" ]]; then
  DIST_VER="11" 
  SUPPORTED=true
```

3. Run install script

```
apt install python3.13 python3.13-venv python3.13-dev
SETUP_PYTHON=3.13 bash install.sh
```

It probably fails the first time when installing python deps 

4. Remove `xmlsec` from `src/backend/requirements.txt` and install it manually

```
/opt/inventree/env/bin/pip install xmlsec
```

I also needed to install some additional pip packages

```
/opt/inventree/env/bin/pip standard-imghdr psycopg2-binary
```

5. Run invnetree package install again

```
apt install --reinstall inventree
```

I also had to run invoke update to get all python deps installed.

```
inventree run invoke update --skip-backup
```

After all that is started working for me.

**Comment by SchrodingersGat** [comment]
@artizirk would you be able to submit a PR with these improvements for our installer?

**Comment by artizirk** [comment]
I will try to take a look at it this weekend but cant promise anything. 

* requirements.txt update for Python 3.13 should be quite straight forward
* imghdr was a standard library but got [removed in 3.13](https://docs.python.org/3.12/library/imghdr.html). standard-imghdr package is an option but maybe it would make sense to use something more propper
* I will need to look into what pkgr is and how it is used here so that correct package for Debian 13 could be built.

(Thank you for working on InvenTree. I think it is a pretty awesome pice of software. ❤️)

**Comment by matmair** [comment]
I am not sure the softwares dependencies will support 3.13 without problems, expect surprises along the way

**Comment by artizirk** [comment]
I have been running InvenTree on python 3.13 for few days now. Besides `imghdr` missing and `xmlsec` being to old, I have not yet noticed any problems. Tho I'm also not using all the features so there still might be some issues.

`imghdr` Python 3.13 was also reported in https://github.com/inventree/InvenTree/issues/8582

**Comment by matmair** [comment]
We have had some issues with crypto, open telemetry and ldap the last time we did a quick check. Mostly stuff that interfaces with system dependencies.
Getting a 3.13 ci running would also be nice
