### ISSUE TITLE
[FR] Is there a default library of electronic categories and parts that I could import?

### ISSUE THREAD

**Issue by ndbroadbent** [inventree/InvenTree#3842]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I've just started trying out InvenTree to organize my home workshop and keep track of all my electronic components. I saw that InvenTree is installed as a blank slate and doesn't come with any options for predefined categories or parts. (As far as I'm aware.) This means that it will be quite tedious to set up lots of common categories for my electronic components.

I found the feature request issue for supplier integrations, and this sounds very interesting: https://github.com/inventree/InvenTree/issues/3261

I'm in New Zealand, and I would be very interested in integrations with the following suppliers:

* Mouser electronics
* RS Components
* Element14
* Digi-Key
* Jaycar electronics
* Surplustronics
* Adafruit
* Sparkfun

In the meantime, it would be really helpful if I could import some basic categories for electronic components (e.g. resistors, LEDs, relays, switches.) Maybe also some common parts that can be ordered from any supplier (resistors, transisitors, diodes, push button switches, etc.) I don't want to start from scratch and add all these myself if someone already has a database that they could share.

### Suggested solution

Are there any database dumps that I could import, so that I could start with a basic list of categoriess and parts?

### Describe alternatives you've considered

Manually enter everything myself

### Examples of other systems

Not sure

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by ndbroadbent** [comment]
I found the [Ki-nTree integration](https://github.com/sparkmicro/Ki-nTree/). This provides [a really handy script that can set up lots of default categories](https://github.com/sparkmicro/Ki-nTree/#before-starting): `python3 -m kintree.setup_inventree`. That's awesome!

<img width="783" alt="Screen Shot 2022-10-24 at 2 34 43 PM" src="https://user-images.githubusercontent.com/139536/197430707-d7a58d6f-2674-46b2-bb70-1a2d58386280.png">

<img width="1315" alt="Screen Shot 2022-10-24 at 2 36 43 PM" src="https://user-images.githubusercontent.com/139536/197430862-e8fc3ce9-1b9b-46c8-ab49-d270fd16a32c.png">

I think it would be really useful if there was an option to use this default list of sub-categories when installing InvenTree, because it took me a little while to figure this out.

I also got the Digikey API integration working, so I can import part numbers via their API:

<img width="581" alt="Screen Shot 2022-10-24 at 2 37 57 PM" src="https://user-images.githubusercontent.com/139536/197430995-33ee78f1-6c9a-4bba-9bed-25ea6c51c75b.png">

<img width="1531" alt="Screen Shot 2022-10-24 at 2 38 29 PM" src="https://user-images.githubusercontent.com/139536/197431067-281c0d55-77bf-4399-ad7c-96e7276da38b.png">

I'm really loving this software so far! Thanks to all the developers!

**Comment by SchrodingersGat** [comment]
@ndbroadbent greetings from across the Tasman! 

> Is there a default library of electronic categories and parts that I could import?

No, nothing like this "out of the box". InvenTree is used for a diverse range of applications, and also particular requirements for categories etc would vary too much between different users. There are already so many questions about naming conventions, etc, that it is left completely up to the user.

> I found the [Ki-nTree integration](https://github.com/sparkmicro/Ki-nTree/)

Thanks to @eeintech for that one :)

> I'm really loving this software so far! Thanks to all the developers!

Much appreciated! Any suggestions (or especially contributions) are welcome!
