### ISSUE TITLE
[FR] Slack notification

### ISSUE THREAD

**Issue by larchen** [inventree/InvenTree#3843]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I'd like to have slack as an alternative notification delivery method to email, with the ability to specify which notifications trigger a message, and which channels they should send the message to. Ideally this could all be configured through the settings page.

### Suggested solution

It looks like this would involve adding a new plugin to handle the message send logic. If I understand correctly it seems that I can use the `CoreNotificationsPlugin` as a template. Do I also need to use the `EventMixin`? 

Sending messages to slack channels is relatively straightforward with [webhooks](https://api.slack.com/messaging/webhooks) and the Slack API.

I'm relatively new to this so would appreciate any suggestions/advice on how best to proceed.

### Describe alternatives you've considered

Open to other suggestions.

### Examples of other systems

Prometheus/Alertmanager has nice integration with slack webhooks: https://prometheus.io/docs/alerting/latest/configuration/#slack_config

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
@larchen that would be a pretty simple addition and I think we might be open to ship it as built-in.
You can basically copy the code from CoreNotificationsPlugin, as you will see there you only need to implement the sending itself.
The settings/notification framework enable you to use both general and user settings. That way you could for example send notifications to a general channel and to users directly.

Regarding events: Notifications are triggered directly and can be addressed (to the responsible user) while events are just database/ORM changes. Therefore working with events requires a bit more code as you need to filter and address target users yourself.
We ship with notifications for some common use cases like low stock. Those are notifications that get triggered (mostly) daily.

**Comment by larchen** [comment]
Sounds good I'll take a stab at this over the weekend.

One additional question is whether or not there is currently a builtin mechanism for routing notifications to different sources? Let's say I want to send all low stock notifications to one slack channel, purchase order notifications to a different channel, but server error notifications to email. I guess this could be done by having a filter on notifications for each notification method.

**Comment by matmair** [comment]
@larchen filtering based on category is currently not done but would be certainly possible; for the first try I would recommend getting the plugin and slack running, adding filtering ontop should be rather easy.

I think more setting for notifications (distribution channel per category/team/user, delayed delivery on some channels, aggregation) would be certainly welcome in core. From an architectural point I would prefer everything else then final channel delivery in the core notification code; that makes reuse simpler and keeps coverage high (delivery channels are not well tested in general).

**Comment by matmair** [comment]
@larchen I have a PR ready if you want to test.
