### ISSUE TITLE
[FR]Remove special character restrictions in parameter template names

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#3852]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I tried to add a parameter template with a name 'Current - Collector (Ic)' and it failed with: 'Illegal character in template name (()'
Are there any objections on removing this limitation like it was done in #3370?

### Suggested solution

Remove special characters limitation

### Describe alternatives you've considered

none

### Examples of other systems

I am working on an importer which transforms the data stored in the Arena and there the parameter names could have special characters like (-s

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@martonmiklos sure, happy for you to submit a PR on this!
