### ISSUE TITLE
[BUG] Newest master branch - fails because of missing backup directory setting

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3857]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

On current master branch:

```
> docker-compose run inventree-dev-server invoke install
Starting inventree-dev-db ... done
Creating inventree_inventree-dev-server_run ... done
Creating directory /home/inventree/data/static
Creating directory /home/inventree/data/media
Creating directory 
mkdir: missing operand
Try 'mkdir --help' for more information.
ERROR: 1

```

### Steps to Reproduce

1. See above.

### Expected behavior

Start, as normal.

If something needs to be changed in the docker-files, this needs to be communicated in release-notes/documentation/whatever before this is released.

This can be fixed by adding the following lines to `docker.dev.env`:
```
INVENTREE_BACKUP_ENABLE=False
INVENTREE_BACKUP_DIR=backups
```

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

commit b13e0c313821b91044b72db192fc1d5ef8358ac1

### Relevant log output

```shell
See above.
```

**Comment by miggland** [comment]
Also, after adding those two lines above, I have the following new directories in my Inventree directory:
```
drwxr-xr-x  2 root   root     4096 Oct 26 09:54 backup/
drwxr-xr-x  2 root   root     4096 Oct 26 09:57 backups/
```

**Comment by SchrodingersGat** [comment]
@miggland the dockerfile already contains this file:

https://github.com/inventree/InvenTree/blob/b13e0c313821b91044b72db192fc1d5ef8358ac1/Dockerfile#L34

So, perhaps what is happening here is that  you need to rebuild the docker image?

```docker compose build```

**Comment by miggland** [comment]
OK.. I was confused again, sorry. This image works a bit differently to other Docker projects I'm used to (lot's of invoke versions etc..)
