### ISSUE TITLE
[BUG] Inventree ver 0.7.4 missing static images after fresh install

### ISSUE THREAD

**Issue by t0roide** [inventree/InvenTree#3861]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

After a bare metal install of the 0.7.4 version the website doesn't display the static images. 
Following some of the advice on similar issues for docker installation, I checked the errors on the developer console but I'm still not sure how I can solve this, been doing some serious googling for a couple days now.
Previously I had a very similar issue with the website not showing images (on another setup) and it was a permission issue with the static images folder but apparently this is not the case since that solution didn't work.
There's nothing else running on the pc where I'm running inventree, in case that might be relevant.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/102771420/198111735-ddfc2d8e-61b2-4b0d-9916-71ca232a78e7.png">

I've tried reinstalling a couple times but no luck, I haven't been able to make the images show and the errors in the developers console have always been the same. 

### Steps to Reproduce

Followed instructions from the docs, currently on Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-131-generic x86_64), configuring everything remotely using a VPN.

### Expected behavior

 Just followed the instructions on the docs without problem https://inventree.readthedocs.io/en/latest/start/install/, so I expected the login page to show normally with it's images and everything, I have done the procedure successfully before.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

InvenTree Version | 0.7.4 
  | InvenTree Documentation | https://inventree.readthedocs.io/en/0.7.4
  | API Version | 50
  | Python Version | 3.8.10
  | Django Version | 3.2.13

**Comment by wolflu05** [comment]
Hello @t0roide,

can you please also share the contents of the network tab in the dev console window you already found. Especially take a look at the responses of an css/js file. I guess this might be some custom html page which renders some message instead of returning the actual css/js file.

**Comment by t0roide** [comment]
Hi @wolflu05 , this a bit of what I can see from the network tab

<img width="782" alt="image" src="https://user-images.githubusercontent.com/102771420/198121943-802548fc-65f7-42f4-ac47-e0804c23aed7.png">

<img width="601" alt="image" src="https://user-images.githubusercontent.com/102771420/198122184-41a54f62-cf0b-4188-b484-a016c2ffc169.png">

<img width="599" alt="image" src="https://user-images.githubusercontent.com/102771420/198122282-d7936a98-e5c7-4ebf-9c91-eec9b9500632.png">

**Comment by wolflu05** [comment]
Have you already make sure, that this is no caching issue. (Used a different browser, incognito tab, ...)?

**Comment by t0roide** [comment]
Yeah, I have. I mainly use Opera and tried a regular tab and one in incognito mode but the problem still there and the messages in the developer console are the same too. Tried with Microsoft Edge also and the issue remains.

**Comment by SchrodingersGat** [comment]
@t0roide it looks like all the static files are redirecting to the index page. How are you hosting the static files? If you are running in production mode, the static files need to be served separately (e.g. using something like nginx).

Have you setup a serving solution for the static (and media) files?

**Comment by t0roide** [comment]
Hi @SchrodingersGat , I haven't setup nginx to serve the static files, on previous installations I didn't either and everything worked just fine, never had issues with the static files other than the issue I mention regarding permissions, but that was solved easily.

I understand how that might be the underlying problem here, so currently I'm looking at the nginx config file for docker changing the root paths for the media and static files to /home/inventree/data but no luck. This is the file I'm using to try based on the docker file,

`server {

    # Listen for connection on (internal) port 80
    listen 80;

    real_ip_header proxy_protocol;

    location / {

        proxy_set_header      Host              $http_host;
        proxy_set_header      X-Forwarded-By    $server_addr:$server_port;
        proxy_set_header      X-Forwarded-For   $remote_addr;
        proxy_set_header      X-Forwarded-Proto $scheme;
        proxy_set_header      X-Real-IP         $remote_addr;
        proxy_set_header      CLIENT_IP         $remote_addr;

        proxy_pass_request_headers on;

        proxy_redirect off;

        client_max_body_size 100M;

        proxy_buffering off;
        proxy_request_buffering off;

        # Change 'inventree-server' to the name of the inventree server container,
        # and '8000' to the INVENTREE_WEB_PORT (if not default)
        proxy_pass http://localhost:8000;
    }

    # Redirect any requests for static files
    location /static/ {
	root /home/inventree/data;
        autoindex on;

        # Caching settings
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }

    # Redirect any requests for media files
    location /media/ {
	root /home/inventree/data;

        # Media files require user authentication
        auth_request /auth;

        # Content header to force download
        add_header Content-disposition "attachment";
    }

    # Use the 'user' API endpoint for auth
    location /auth {
        internal;

        proxy_pass http://localhost:8000/auth/;

        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }

}`

This file I'm creating at `/etc/ginx/conf.d/` but it shows me the following error message when I run` nginx -t` ,

`nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2022/10/26 22:28:39 [warn] 608960#608960: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
2022/10/26 22:28:39 [emerg] 608960#608960: open() "/run/nginx.pid" failed (13: Permission denied)
nginx: configuration file /etc/nginx/nginx.conf test failed`

The structure of my inventree home directory is like the docs, so I have /home/inventree/data where static and media folders are but also /home/inventree/static, just mentioning this in case it's helpful. So I'm thinking the redirecting has to be from /home/inventree/data. 

Also I was looking at this tutorial https://arctype.com/blog/install-django-ubuntu/ and with that trying (unsuccesfully) a nginx config file like this

`server {  
	listen 80;     
	server_name localhost:8000;    
	location = /favicon.ico { access_log off; log_not_found off; }    
	location /static/ {         
		root /home/inventree/data;     
	}    
	location / {         
		include proxy_params;         
		proxy_pass http://unix:/run/gunicorn.sock;     
	}
}`

**Comment by wolflu05** [comment]
Seems like its not working correctly, I guess some js scripts are not loaded, which define the `inventreeGet` function.

**Comment by t0roide** [comment]
Any ideas on how can I solve this? Is this a nginx related issue or something else? Thanks @wolflu05 for the quick response!

**Comment by SchrodingersGat** [comment]
@t0roide that looks great, well done figuring that out.

Regarding the console error (**specific to the login page**):

On older stable versions (i.e. 0.7.x) there is a bug where some javascript files are attempted to be loaded on the index page, but because you are not logged in you don't have the right permissions. This does not negatively impact functionality, and should only be an issue on the login page. You should be safe to ignore this one.

**Comment by matmair** [comment]
@t0roide do I see correctly that you are serving static and media files both from `/home/inventree/data`? That might lead to collisions. We generally check for that but I would still recommend checking up on that.
The permissions could also be a problem with the ngingx-process-user (most likely www-data) not having sufficient rights to accesss `/home/inventree/data` - have you checked on that?

**Comment by t0roide** [comment]
@SchrodingersGat That sounds like great news but even after logging the similar alerts keep popping up when navigating the website, so right after logging for example I get the following

<img width="632" alt="image" src="https://user-images.githubusercontent.com/102771420/198416823-66b866b5-97b5-4aa3-afb7-4af5f1f4f29d.png">

@matmair so it would be better to to something like `/home/inventree/media` and `/home/inventree/static` for example? I did it in that way because I was just following the docs but now that the topic rises, when installing at the very first steps there's a `/home/inventree/static` folder that is created and it seems to be unused, maybe moving the statics over there would be a good idea considering your comment. 

And prior to this I didn't check the permissions for the www-data user, but just now I gave that user read and write permissions like this `setfacl -R -m u:www-data:rw /home/inventree/data`, and the issue remains.

Another thing I've been noticing is that for me every static is displayed properly despite these alerts in the developers console, but for some of my coworkers that are accessing directly from the network where inventree is hosted, they have even worst issues, some of them don't see statics at all so it looks plain like my initial picture, another one only sees some statics. Their alerts on the developers console look the same though, here's a picture after logging.

![image](https://user-images.githubusercontent.com/102771420/198418702-8210035e-6d7d-4ead-85a3-68c98432bf2c.png)


Thanks for the help so far!

**Comment by t0roide** [comment]
I was just testing the website in general to see how the alerts changed and the page after loggin seems to be the one that has more alerts (first image in the previous comment), when navigating through parts, suppliers, build orders and such the alerts remain the same and are only 3, the following image shows this

<img width="396" alt="image" src="https://user-images.githubusercontent.com/102771420/198627753-017cf7bd-6bc9-404b-801e-57be1044fd77.png">

I'm thinking maybe the visualization problem people connecting directly through the network have, might be related to something else and not necessarily the serving of the images, maybe something related to the network itself (router configs maybe?), or it might work with opera and nothing else, which would still be pretty weird. I'll keep looking into this and update if I find something interesting!

**Comment by matmair** [comment]
@t0roide I have a hard time replicating this with docker. Is there a specific reason you are running 0.7x and not stable? If the issue is in code we will not issue an update for 0.7x as we generally only support current stable and master with updates/fixes.

**Comment by t0roide** [comment]
@matmair The reason to install in 0.7.4 was actually because I had to do a migration, the database backup I had was from that version so the fresh install had to be in the same version. And in that regard everything is done, the migration worked and I can see everything is in order.

When I first started to have this problem I thought that maybe after migration I could upgrade to the latest version and it would fix the problem, I'm honestly trying to avoid updating because when following the instructions I got the message `Automatic merge failed; fix conflicts and then commit the result` and I got scared about fixing and commit things manually.
I read about that message and some tutorials explaining how to do it but I'm not 100% sure I understand it fully in order to actually do it. So that's where I'm at.

**Comment by wolflu05** [comment]
Sorry, I didn't got when this error occurred. What have you executed that you this uncommitted changed error?

**Comment by t0roide** [comment]
@wolflu05 I think it might be the nginx config I added, or the file with the data I imported from the previous installation.

But on some good news, the issue definitely was not from the installation itself, like I said on older comments, from my end everything was working and the images were displayed correctly (despite some alerts here and there) but some other people accessing locally were having issues even after I added the nginx to serve images. And the issue was finally solved by cleaning the browser they were using , cookies, images and other cached files. I guess that means there's no bug.

Anyways, the update is much needed on my setup and I'll get to it once I understand the git message and the solution for it better. 
Thanks so much to all of you for your time and help! @matmair @SchrodingersGat @wolflu05

**Comment by wolflu05** [comment]
To understand how to help you, I need to know after what command you got this git uncommitted files error.

**Comment by matmair** [comment]
The solution is pretty straightforward and you already wrote about it @t0roide. It would help if you moved the data file out of Inventrees path then there should be no git errors anymore.
The new installer works without git, which should make stuff easier regarding updates.

**Comment by SchrodingersGat** [comment]
@t0roide I'm going to close this issue out due to inactivity. If you have any more to add, or any further questions, please comment again here.
