### ISSUE TITLE
[FR]Dropdown type part parameter templates

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#3862]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

It would be nice if a part parameter could be specified with a combobox.
The items of the combobox would be set in the template itself.

### Suggested solution

Add a property to the part parameter templates: is_selectable
The template editor form should be extended with an input (checkbox) to activate this.
If activated a list editor shall be shown. (And maybe the unit shall be hidden, I do not know if it makes sense to have a selectable attribute to have unit.)
In the part parameter editor form (in the case if the template is a selectable one) a combobox should be shown with the items of the template.

### Describe alternatives you've considered

Using freetext part attributes.

### Examples of other systems

Arena PLM system has this feature for part attributes.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
Hint #2789 ;-) but totally agree

**Comment by martonmiklos** [comment]
Hi folks, 
I started to work on this one. 
So far so good the admin side is working.
Can you think about a parameter where dropdown an unit would make sense together?

**Comment by matmair** [comment]
@martonmiklos unit and parameter are normally linked so not sure what you mean.

**Comment by martonmiklos** [comment]
> @martonmiklos unit and parameter are normally linked so not sure what you mean.

In the case if we make a parameter template to dropdown 'type' then it does not really make sense to have the unit specified. I added some javascript tweak to show & hide the dropdown items according to the Dropdown checkbox:
![kép](https://user-images.githubusercontent.com/1609182/202913866-197d3a44-e413-40b0-8f2f-33b94f070a64.png)
![kép](https://user-images.githubusercontent.com/1609182/202913875-515c2ac8-21ac-46b4-9179-edc184bd6fc8.png)

The same way the Unit field could be hidden if the Dropdown is checked.

**Comment by martonmiklos** [comment]
@SchrodingersGat , @matmair could you please help me to find where the OPTIONS responses generated? If I think correctly I need to alter them to present the dropdown in the edit/add parameter UI:

![kép](https://user-images.githubusercontent.com/1609182/202923686-05536bca-ac77-43ee-8900-2e93d6e3fde1.png)

**Comment by SchrodingersGat** [comment]
@martonmiklos I think it would be better to adjust this on the front-end. When generating the form, perform an API request to get the list of available templates, rather than generating this list on the server side.

**Comment by martonmiklos** [comment]
@SchrodingersGat the parameter edit/add form is handled with the constructForm method which populates the form fields automatically based on the OPTIONS response. Re-implementing it to a level where the options would be overwritten is quite a pain.
As a workaround we could hide the string input field and if the API query finished we could hide it or display a select instead of this. I also consider this a bit hackish, but I have not been able to figure out how can we trick the serializer on the server side.

**Comment by SchrodingersGat** [comment]
@martonmiklos this could be achieved either via client side (API) or server-side (augmenting the OPTIONS request)

### Client Side

Note that the "fields" attribute for any client-side forms is initially retrieved via an OPTIONS request, but can be adjusted / overridden by client code:

https://github.com/inventree/InvenTree/blob/10ae170d2a9437ab02b6a3895413067b2935e669/InvenTree/templates/js/translated/company.js#L91

See here that we can select which fields we want to use, and manually override any field parameters.

### Server Side

OPTIONS metadata is constructed here: https://github.com/inventree/InvenTree/blob/master/InvenTree/InvenTree/metadata.py

Note that it is intended to be "generic" (trying to avoid custom use-cases as much as possible). It would be probably possible to achieve what you want this way, but I think using the API would be easier.

### Suggested Approach

I think a client-side approach is cleaner. Note that we are moving towards an "API only" single-page approach in the next few release cycles, so focusing on using the API is recommended.

One key reason that I suggest you use the API: In the form, when you select which template you want to use, this changes the available selection of "template values" you can choose from. The OPTIONS request is somewhat static - it won't deliver the template values for the new template that the user selects. But, the forms framework allows you to attach a callback function when a field is changed - and you can then re-populate the choices for the related field.

**Comment by martonmiklos** [comment]
Many thanks for the hint, I will be able to make it based on the editManufacturerPart  example!

**Comment by SchrodingersGat** [comment]
Here's a more complete example of the "onEdit" callback functionality:

https://github.com/inventree/InvenTree/blob/10ae170d2a9437ab02b6a3895413067b2935e669/InvenTree/templates/js/translated/order.js#L797

**Comment by matmair** [comment]
@martonmiklos sounds nice. Please make an FR - changing the API should be done carefully as there are possibly multiple consumers.

**Comment by martonmiklos** [comment]
@SchrodingersGat  May I ask for a bit of help with the PR for this one?
The QC checks are failing in the users.tests.RuleSetModelTest:
https://github.com/inventree/InvenTree/actions/runs/3518375224/jobs/5897256781
I made a new model, and I do not know what else do I need to do with it to being inculded in the RuleSet.

**Comment by SchrodingersGat** [comment]
@martonmiklos looks like you've worked it out, that's exactly where I would have suggested you update the `RULESET_MODELS` :)

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by martonmiklos** [comment]
> Not stale

Uhm, yeah, I started to rework it to support numeric, and boolean types and I ran out of free time since then.
But yes I still have the willingness to implement it.

**Comment by matmair** [comment]
No stress @martonmiklos the bot is mainly there to remind us of PRs and Bug Reports we forgot

**Comment by martonmiklos** [comment]
Not stale ;)

**Comment by martonmiklos** [comment]
> This issue seems stale. Please react to show this is still important.

No way.
