### ISSUE TITLE
Hide IP in Demo

### ISSUE THREAD

**Issue by semaf** [inventree/InvenTree#3865]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Visitor IPs are shown. 
![image](https://user-images.githubusercontent.com/8831145/198290289-1f7feb20-8412-41ab-b20c-56117032913e.png)

### Suggested solution

Hide them

### Describe alternatives you've considered

Do not visit the demo

### Examples of other systems

GDPR

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
hi there @semaf ! I am actually a happy customer of yours for a few years now so hyped to see you here.

We discussed this feature regarding GDPR a while ago and here is my assessment from then (shortened):
- only shown for at most the last 24 hours
- not connected to PII (username, exact location, personal data)
- shown as a demonstration of the core functionality of tracking sessions and IPs - which is needed technically
- we do not keep copies or share the data with 3rd parties
Therefore the feature is activated. The instance is cleared every 24h, we do not keep logs.
As far as I see it we are in the requirements of the law. Do you disagree or can we close this issue?

**Comment by wolflu05** [comment]
I would more agree to @semaf . I also really don't preferre the demo instance due to that after I first saw the **everyone** on the internet has access to it. It doesn't matter to me, if one could only see it for a short period and anonymous, because you can think that @semaf ip must be the ip in the range where the screenshot above is made. And if there aren't a lot of people, it's very easy to reduce the ips to identify @semaf . My solution would also be to disable that feature only for demo or maybe only show Xxx.xxx.xxx.xxx with the time instead of the ip.

**Comment by SchrodingersGat** [comment]
Hiding or obscuring the IPs seems like a reasonable request here

**Comment by matmair** [comment]
@SchrodingersGat I would at least show the first two numbers to show (and be able to check) that our session code still works. In general, it is established practice in the EU that it is fine to show the IP as long as there is a valid technical reason.
Moreover creating a connection between the IP and the (home-user; businesses might have static IPs) users is only possible if PII is entered into the system willingly - everybody uses the same few users. ISPs shuffle through their user's public IPs pretty regularly and there is not enough other info there to create a matchable fingerprint.

**Comment by semaf** [comment]
> hi there @semaf ! I am actually a happy customer of yours for a few years now so hyped to see you here.
> 
> We discussed this feature regarding GDPR a while ago and here is my assessment from then (shortened):
> 
> * only shown for at most the last 24 hours
> * not connected to PII (username, exact location, personal data)
> * shown as a demonstration of the core functionality of tracking sessions and IPs - which is needed technically
> * we do not keep copies or share the data with 3rd parties
> 
> Therefore the feature is activated. The instance is cleared every 24h, we do not keep logs. As far as I see it we are in the requirements of the law. Do you disagree or can we close this issue?

Hey Mat,
Nice to see you a customer of us here :) I never could imagine that I meet somebody we had a touch before.

My point is just to hide the visitor IPs to the public. Anybody will be able to collect IPs, especially company IP who are looking for solutions and try to attack them. You could build a function to show/hide the IP where only admins can toggle it, even block this function for demo users.

I was planning to test your code with a RPI but missed some functions on the demo.

**Comment by SchrodingersGat** [comment]
@semaf thanks for raising this but after discussion we are going to leave it as it is. Hope you are otherwise finding InvenTree to be useful!
