### ISSUE TITLE
[BUG] Server error:  TemplateSyntaxError - unexpected char '&' at 29

### ISSUE THREAD

**Issue by JustusRijke** [inventree/InvenTree#3867]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

A server error is generated when clicking on any of the menu items (parts, stock, build, etc).
Parts and stock are no longer visible.

Contents of the error:

**Type:** TemplateSyntaxError
**Path:** /api/part/
**Info:** unexpected char '&' at 29
**When:** Oct. 27, 2022, 6:23 p.m.
**Data:**
    Traceback (most recent call last):
    
    File "/root/.local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
    
    File "/home/inventree/InvenTree/InvenTree/api.py", line 176, in get
    return super().get(request, *args, **kwargs)
    
    File "/root/.local/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
    
    File "/home/inventree/InvenTree/part/api.py", line 1013, in list
    data = serializer.data
    
    File "/root/.local/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
    
    File "/root/.local/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
    
    File "/root/.local/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
    
    File "/root/.local/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    
    File "/root/.local/lib/python3.9/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
    
    File "/root/.local/lib/python3.9/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
    
    File "/root/.local/lib/python3.9/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
    
    File "/home/inventree/InvenTree/part/models.py", line 648, in full_name
    template_string = Template(full_name_pattern)
    
    File "/root/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1208, in __new__
    return env.from_string(source, template_class=cls)
    
    File "/root/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
    
    File "/root/.local/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
    
    File "/root/.local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
    
    File "<unknown>", line 1, in template
    
    jinja2.exceptions.TemplateSyntaxError: unexpected char '&' at 29

### Steps to Reproduce

Unfortunately I do not have a reproduction scenario. It seems to have started after adding stock of a part. The part is a variant of another part. This happened on a clean install of InvenTree (only 3 parts in the database).

### Expected behavior

Feedback to the user explaining what it is the problem, and how to solve it.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by JustusRijke** [comment]
Added data.json (removed user info)

[data.zip](https://github.com/inventree/InvenTree/files/9882274/data.zip)

**Comment by SchrodingersGat** [comment]
@JustusRijke thanks for reporting. Looks like a data sanitization issue with regard to the `PART_NAME_FORMAT` setting:

![image](https://user-images.githubusercontent.com/10080325/198403120-f750439c-1899-4c93-b310-e7ca75554daa.png)

If you edit the setting via the web interface, the quotation chars are replaced, which causes the template rendering to fail:

![image](https://user-images.githubusercontent.com/10080325/198403280-409d0997-958a-4e84-8f04-044ed2c9d45b.png)

**Comment by matmair** [comment]
@SchrodingersGat was also looking at this. Will supply a fix shortly.

**Comment by SchrodingersGat** [comment]
Looks like the front-end forms are passed through the `sanitizeData` function which may be unnecessary now!

**Comment by matmair** [comment]
@SchrodingersGat frontend is more your thing nromally. Dou you want to tackle this?

**Comment by SchrodingersGat** [comment]
Sure, I can take a look at it.

**Comment by matmair** [comment]
Now I can't reporduce #3864 I am starting to wonder if these are both just (old static) JS.

**Comment by SchrodingersGat** [comment]
I have been able to replicate this one. I'll check out #3864 also

**Comment by JustusRijke** [comment]
Thanks for looking into this so quickly!

Now that the core problem is clear, how can someone resolve it?

I tried changing **Part Name Display Format** in the Settings screen to `{{part.name}}`, but after I click on the Parts menu, this settings reverts back to `{{ part.IPN if part.IPN }}{{ &#039; \|  &#039; if part.IPN }}{{ part.name }}{{ &#039; \| &#039; if  part.revision }}{{ part.revision if part.revision }}`

I could change this in the `data.json` file, however there seems to be no information in the docs about how to restore this file.

**Comment by JustusRijke** [comment]
Found instructions on restoring a backup here: https://inventree.readthedocs.io/en/latest/start/migrate/#import-data

Changing the value of PART_NAME_FORMAT in the `data.json` file and importing it by executing

    docker-compose run inventree-server invoke import-records -c -f /home/inventree/data/data.json

did the trick.

**Comment by JustusRijke** [comment]
Thought the quick fix worked, but unfortunately not.

The parts are visible in the Parts browser, but when clicking on a part (i.e., browsing to `
http://192.168.178.17:1337/part/3/`), the result is an Internal Server Error.

The error remains the same: `unexpected char '&' at 29`

**Comment by SchrodingersGat** [comment]
@JustusRijke to fix this:

**Navigate to admin interface**

e.g. http://localhost:8000/admin/common/inventreesetting/

(replace localhost with your actual URL)

**Find `PART_NAME_FORMAT`**

![image](https://user-images.githubusercontent.com/10080325/198528776-55ad8918-6a2e-42e2-b83e-e211c0d4280c.png)

**Delete this setting**

Delete this setting to revert it to the default value.

**Comment by JustusRijke** [comment]
Worked, thanks!
