### ISSUE TITLE
Python API: setInternalPrice breaks on floats

### ISSUE THREAD

**Issue by JustusRijke** [inventree/InvenTree#3872]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

`some_part.setInternalPrice(1, 1.0)` works fine (passing an integer value), but `some_part.setInternalPrice(1, 1.1)` (passing an actual float) returns:

    requests.exceptions.HTTPError: {'detail': 'Error occurred during API request', 'url': 'http://192.168.178.17:1337/api/part/internal-price/', 'method': 'POST', 'status_code': 400, 'body': '{"price":["Ensure that there are no more than 19 digits in total."]}', 'headers': {'AUTHORIZATION': 'Token 26df295ad7522c38f3226c5e7a62f6c1ce26b5ee'}, 'params': {'format': 'json'}, 'data': {'part': 60, 'quantity': 1, 'price': 1.1}}

I noticed that the `test_set_price` in https://github.com/inventree/inventree-python/blob/master/test/test_part.py tests with value 1.0, maybe it breaks with 1.1 ?

### Steps to Reproduce

See description

### Expected behavior

Internal price is set

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: https://github.com/inventree/InvenTree/commit/ca1fbf9ff0963f90cf0780c7228f4362d5e95011
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
Hey @JustusRijke I can replicate this one, looking into it now.

**Comment by SchrodingersGat** [comment]
@JustusRijke should be fixed in latest master commit now

**Comment by JustusRijke** [comment]
Great, thanks!
