### ISSUE TITLE
Upload image results in 403 Forbidden

### ISSUE THREAD

**Issue by JustusRijke** [inventree/InvenTree#3875]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When uploading an image using the Python API, e.g.:

    part.uploadImage("BC3150__web_preview_1.png")

The image is uploaded and the image URL is updated.

Contents of the `/media/part_images` folder:

![image](https://user-images.githubusercontent.com/53965859/198724646-e179996e-68db-4a24-bec8-269a2e446045.png)

URL (on the Part details page): `http://<MY IP>:1337/media/part_images/BC3150__web_preview_1.preview.png`

So the URL seems correct, however it returns __403 Forbidden__

### Steps to Reproduce

Upload an image with the Python API

### Expected behavior

Image URL is reachable

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by JustusRijke** [comment]
Tested a bit further: this also happens when manually uploading an image using the web frontend.

**Comment by SchrodingersGat** [comment]
403 would indicate a permissions issue. 

To be clear, if you navigate your browser to the part page, does the image display? Or do you get a broken image link? Can you share a screenshot?

**Comment by JustusRijke** [comment]
The part page shows a broken image:
![image](https://user-images.githubusercontent.com/53965859/198824738-9987aad9-ef4f-4a60-92b0-31cd2d5dd5ae.png)

Entering the image URL directly in the browser gives a 403:
![image](https://user-images.githubusercontent.com/53965859/198824770-f247e798-8b2e-446e-8084-fc5e6215b8f8.png)

I could not reproduce this on a clean install. I'll try to reproduce the problem. Could be related to restoring backups of the image folder, combined with my limited knowledge of unix file permissions ;-)

**Comment by JustusRijke** [comment]
Yup, it was a permissions issue. Thanks for helping out.

Media folder on a instance of IvenTree without problems:

	drwxr-xr-x  5 root root     4096 Oct 28 19:27 media

The same folder, on the InvenTree instance with the 403 error:

	drwxr-x---  5 root root     4096 Oct 28 20:04 media

Fixed with `chmod u=rwx,g=rx,o=rx media`
