### ISSUE TITLE
Printer plugins do now work

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#3878]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I installed the Zebra printer plugin from
https://github.com/SergeoLacruz/inventree-zebra-plugin
and the brother plugin. Both install fine but do not work. when I try to print a label I get an error message in the worker log telling 
Could not find matching plugin for 'brother' or
Could not find matching plugin for 'zebra'

### Steps to Reproduce

1. Install plugin
2. select a part
3. go print label
4. select Brother Labels or Zebra Labels
5. watch the output of the worker

### Expected behavior

Label on printer

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

 0.9.0 dev
Commit Hash e6461929b
API Version  78
Python Version 	3.10.6
Django Version 	[3.2.16]

### Relevant log output

```shell
...
07:11:34 [Q] INFO Process-1:1 processing [lima-batman-monkey-purple]
Could not find matching plugin for 'brother'
07:11:34 [Q] INFO Processed [lima-batman-monkey-purple]
07:11:58 [Q] INFO Enqueued 4526
...
```

**Comment by SchrodingersGat** [comment]
@SergeoLacruz looks like a simple fix in the end - https://github.com/inventree/InvenTree/pull/3879
