### ISSUE TITLE
[Barcode] Barcode scan endpoint takes too long

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3882]
The recent [barcode refactor](https://github.com/inventree/InvenTree/pull/3640) has introduced a bug where the barcode scan endpoint takes over 2 seconds to return a result (or even no result).

This is because two new plugin instances are created every time a barcode is scanned. Spinning up a plugin takes a lot of time!

**Comment by matmair** [comment]
@SchrodingersGat the fundamental problem is that plugins are not enabled by default - so we do all the time-consuming init steps on each scan.
If we switch to default on plugins and add a warning that barcodes do not work without plugins times should be much lower. Thoughts?
