### ISSUE TITLE
Plugins - translation missing

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#3892]
It is a small thing, in the settings sidebar the plugin related section is not translatable:
https://github.com/inventree/InvenTree/blob/d84b67ddf4b423d82862ff9a4c7b1c2d1474342a/InvenTree/templates/InvenTree/settings/sidebar.html#L56
Maybe this also affects the plugin interface (plugin.human_name), I don't know if its output is translated or not...

**Comment by SchrodingersGat** [comment]
@rkalman thanks, please let us know if there are any other strings which are not exposed for translation. Fix in https://github.com/inventree/InvenTree/pull/3893
