### ISSUE TITLE
[FR]Support "structural" categories

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#3897]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

It would be great if there would be an option to create part categories which would not allow direct part creation.
I.e. I would not like that lazy people in my team would add parts directly under the documentation category, they should either use the proper categories or create a new one.

The same might be useful for the Stock locations as well. 

### Suggested solution

Implement it ;)

### Describe alternatives you've considered

-

### Examples of other systems

Arena PLM has this option, they call Structural categories

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@martonmiklos adding a field to the PartCategory model would not be difficult. I can see some complications arising with how the "logic" is implemented, but with sufficient unit testing this would be OK.

**Comment by martonmiklos** [comment]
Hi folks,

I started to work on this one but I got stuck a little bit.

I have added the structural field to the model, invoke migrated run just fine (database field got created):
https://github.com/martonmiklos/InvenTree/blob/fix_3897_add_stuctural_partcategory_support/InvenTree/part/models.py#L117

If I only add the following to the form code (like the same way as the is_supplier field is added in the company form): 
```
structural: {},
```

The form control did not get created:
![kép](https://user-images.githubusercontent.com/1609182/201667783-32e13f2a-aa3d-4350-af5a-73e4b78e5401.png)

If I add the following to the form:
```
structural: {
            label: '{% trans "Structural" %}',
            type: 'boolean',
            help_text: '{% trans "Parts may not be directly assigned to a structural category, but may be assigned to it&quot;s child categories." %}',
        },
```

![kép](https://user-images.githubusercontent.com/1609182/201676462-85c899d5-f4be-46bd-b13c-b3ed48afab29.png)

The form got appeared correctly, however in the clean method of the model the structural parameter stays False regardless to the form control state.

 @matmair @SchrodingersGat do you happen to have any hint what did I missed?

**Comment by matmair** [comment]
Good question @martonmiklos . I am not an expert in the frontend code but I think there is something missing in the OPTIONS call. Any insights @SchrodingersGat?

**Comment by martonmiklos** [comment]
> Good question @martonmiklos . I am not an expert in the frontend code but I think there is something missing in the OPTIONS call. Any insights @SchrodingersGat?

Good hint, I added the new field to the serializers.py
