### ISSUE TITLE
Build a part when its BOM has trackable part(s)

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#3915]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

It needs more investigating, but it seems something is wrong handling a build order of a part which has trackable items in its BOM. 

### Steps to Reproduce

0. Make a new part, make a BOM, get a trackable (serialized) part and an untracked part 
1. Make a new build order for that part
2. In the build order where you allocate the parts the trackable item from the BOM are missing completely. So you cannot allocate it.
3. In order to go forward with the build, I set the trackable part to untrackable. After this it shows up in the list.
4. complete the allocation, complete the build
5. the allocated trackable part still remains on the stock, while the untracked one do not.

### Expected behavior

Handle trackable BOM parts correctly

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

reproduced on demo server
# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.16
Commit Hash: 0bb2dd5
Commit Date: 2022-11-10
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
@rkalman it sounds like the system is working as intended. "tracked" BOM items need to be allocated against a particular build output, not against the build itself.

https://docs.inventree.org/en/latest/build/allocate/#untracked-vs-tracked-stock

Please close the issue if you feel it has been adequately addressed

**Comment by rkalman** [comment]
Oh, I am sorry, I completely missed that part of the documentation.
And yes it is working correctly in these situations:

1. if we have a stock item of a tracked part with serials assigned:
  - this is the case I missed completely, we can allocated individual stock items to the build output, nice and ok, thank you
  - allocated item installed in the completed build output 

2. if we have a stock item of an untracked part without serials:
  - allocate stock to build as normally do
  - stock consumed if the build finished
  
3. if we have a stock item of a tracked part, which has no serials assigned
  - we can allocate it to the individual build output without serial, I guess it is ok, we can complete the build without the tracked BOM item serial if it is not provided
  - Just a small note here, even if the part is tracked it is not required to supply the serials, so basically we can have a stock item of tracked parts without serials, so basically they are untracked... For example if somebody receives the arrived stock items against a PO and forget to fill in the serials. But it is acceptable and I think anybody can live with this behaviour.

And the problem which I met:

4. if we have a stock item of an untracked part which has serials assigned
 - yes I know it is crazy, but if you remove the tracking requirement from the part, the serials remains there on the stock items (for ex. somebody has changed the part from tracked to untracked but there are serialised and unserialised stock items present)
 - we can allocate these stock items to the build as we do with normal untracked BOM items
 - and finally when you complete the build these items are not removed from the stock. They are not consumed by the build, each of them remains available.

So I think one solution would be to remove all the serials from the stock items when the part goes from tracked to untracked, or investigate why these items remains on the stock after the build completes.

Thank you for your time!
