### ISSUE TITLE
[FR] Edit parameters in the component part form

### ISSUE THREAD

**Issue by fjullien** [inventree/InvenTree#3916]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Every time a parameter needs to be changed in a component, one need to click on "Edit parameter". It would be much efficient if the value could be directly enter in the component form.

### Suggested solution

Would it be possible to edit parameters of a component directly in the component form here (without clicking every time on "Edit parameter" for each line):

![image](https://user-images.githubusercontent.com/1468818/201194046-eadb8738-87a4-42c6-aeb3-0b3198d2d2d1.png)

### Describe alternatives you've considered

-

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
@fjullien seems like a reasonable wish. Not sure if anybody has the bandwidth to develop this.

**Comment by SchrodingersGat** [comment]
@fjullien we have previously discussed adding "inline editing" to all table view, to streamline workflows.

As we are planning on making the jump to react for the front-end, I will not be giving any attention to this until then.

However that's a little while off, so if you wanted to contribute this feature yourself, I'd certainly be open to that.

**Comment by fjullien** [comment]
No problem, I understand. 
In general, I like doing it myself. However, I'm comfortable with a lot of things (hardware/software/FPGA) except web development.
It would take me time to start contributing.
I may do it at some point. Add this to my do-to list ;)

**Comment by matmair** [comment]
@fjullien that is actually the case for most ppl. here so welcome to the club!
Before you start actually developing please ping us, there might be some drastic UI framework changes around the corner. Would be a shame to droop something that get's only used for a few weeks.

**Comment by wolflu05** [comment]
I guess this is still relevant in the new react ui.

**Comment by matmair** [comment]
I am not really sure if it is as there was minimal interaction but we will see if there is more interest in the future
