### ISSUE TITLE
[Bug] Cannot mark notifications as read / unread

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3919]
@matmair since integration of the news-reader, marking notifications as read / unread throws an error:

![image](https://user-images.githubusercontent.com/10080325/201256969-0f153f9c-2c03-4af8-881a-785749ec5efb.png)

![image](https://user-images.githubusercontent.com/10080325/201257126-6bbc1e83-3dbe-47d1-91a6-7e1b5b7cfda4.png)

Can you look into this one please? I'm not sure what's been changed here.

If it is not in place already, some unit testing for marking notifications as "read" would be a good addition

**Comment by matmair** [comment]
@SchrodingersGat I will look into this.

**Comment by SchrodingersGat** [comment]
@matmair have you had a chance to look into this one yet?
