### ISSUE TITLE
[Bug] Background Worker Issues

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3921]
I have been trying to chase down a particularly difficult bug for a while now, and finally think I have it sorted out.

### Problem Description

If the [background worker](https://django-q.readthedocs.io/) processes too many tasks in a short space of time, subsequent tasks are handled "synchronously" (by the foreground worker / web-server) until the next scheduled "heartbeat" task. Essentially the background worker stops responding to new queued tasks for ~15 minutes.

#### Save Limit

The django-q configuration has a [save_limit](https://django-q.readthedocs.io/en/latest/configure.html#save-limit) parameter with a default value of 250. This means that once 250 "successful tasks" are stored in the database, any older successful tasks are deleted

#### Background Worker Monitoring

When the web-server tries to schedule a new background task, it first checks to see if the background worker is running. We use the "heartbeat" task to run periodically, and then we can simply see if that task has been run (within a certain time window) to determine if the worker is actually running.

However if lots of other successful tasks run, the 250 task limit overflows and the successful "heartbeat" tasks are dropped. Thus the frontend "thinks" that the worker is down (but it really isn't)

#### Bandaid Solution

The "heartbeat" task idea is already a bandaid solution, as the built-in monitoring functionality for django-q does not work properly in our situation. I have been [trying to work this out for a while](https://github.com/Koed00/django-q/issues/516) - I think it is because the django cache is not shared between processes

#### Caching

The realisation about caching not being shared raises another issue. We make use of cache to store things such as settings (user / global / plugin) - now there is a possibility that the worker and server processes may be 'out of sync' if their caches have different values! Need to look into this.

**Comment by SchrodingersGat** [comment]
@matmair might be of interest to you - especially the note about caching at the end

**Comment by matmair** [comment]
@SchrodingersGat the cache thing is a known vault with server/worker things; Celery had that problem too last time I checked.
The main problem is that separate processes can not share the same memory. Best practice to solve this is to deploy with a shared caching layer. That could be memcached or redis - I tend to deploy the second one due to better monitoring and the possibility to scale out the webserver processes to several hosts.

**Comment by matmair** [comment]
This article gives a good overview of options: https://testdriven.io/blog/django-caching/ - I generally like that site

**Comment by SchrodingersGat** [comment]
I feel like it is time to move to redis after this next release. Both for performance and to get around these caching memory issues
