### ISSUE TITLE
URL based QR code resolves to empty braces

### ISSUE THREAD

**Issue by larchen** [inventree/InvenTree#3923]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I'm trying to generate QR codes that encode the full url, but it seems that the `qr_url` variable just resolves to empty braces.

### Steps to Reproduce

I have the following template file for a part label for testing (uploaded through the admin interface)

```
{% extends "label/label_base.html" %}

{% load l10n %}
{% load barcode %}

{% block style %}

.qr {
    position: fixed;
    left: 0mm;
    top: 0mm;
    {% localize off %}
    height: {{ height }}mm;
    width: {{ height }}mm;
    {% endlocalize %}
}

.part {
    font-family: Roboto, Helvetica, sans-serif;
    display: inline;
    position: absolute;
    padding: 5px;
    {% localize off %}
    left: {{ height }}mm;
    {% endlocalize %}
    top: 2mm;
}

{% endblock %}

{% block content %}

<img class='qr' src='{% qrcode qr_url %}'>

<div class='part'>
    {{ part.full_name }}
    <br>
    <hr>
    {{ qr_data }}{{ qr_url }}
</div>

{% endblock %}
```

which generates this label

![image](https://user-images.githubusercontent.com/16676799/201493022-699f1e14-6dea-4a63-9560-95a37e1ed53b.png)

### Expected behavior

Expected `qrl_url` to resolve to the full url for the part.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.16
Commit Hash: b9de7e5
Commit Date: 2022-10-24
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/pull/3924

**Comment by larchen** [comment]
Thanks for the quick fix! Just tested and can confirm it works as expected now.
