### ISSUE TITLE
Notes content doesn't keep format, line feeds gone

### ISSUE THREAD

**Issue by matmil** [inventree/InvenTree#3932]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Latest pull of code and the notes is working but the formatting is not being preserved.

### Steps to Reproduce

Add a note with line feeds
Save a note
View the note

### Expected behavior

Should keep formatting on notes.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.90 Dev
06266b48a

**Comment by matmil** [comment]
<img width="288" alt="Screenshot 2022-11-14 at 16 19 56" src="https://user-images.githubusercontent.com/1688784/201713301-6832588b-249a-49fa-8cd3-4a1804c255f4.png">

**Comment by wolflu05** [comment]
This is actually the expected behavior of markdown.

**Comment by matmair** [comment]
Can reproduce, this is def a bug

**Comment by wolflu05** [comment]
The spec says the following, but two spaces doesn't work either. https://www.markdownguide.org/basic-syntax/#line-breaks

**Comment by matmair** [comment]
@wolflu05 a whole bunch of markdown stuff is not working; this has to be looked into further. I am currently deep into programming something else; I will take a look later
