### ISSUE TITLE
Quick Script, Ubuntu 20.04 LTS not supported

### ISSUE THREAD

**Issue by martin323232** [inventree/InvenTree#3933]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production

### Describe the problem*

Trying to install following https://docs.inventree.org/en/latest/start/installer/
Does seem that I got 20.04.05 LTS when looking at "About" screen

### Steps to Reproduce

Install Ubuntu 20.04 LTS

In terminal: wget -Nq https://raw.githubusercontent.com/InvenTree/InvenTree/master/contrib/install.sh && bash install.sh

### Relevant log output
inven@inven-ThinkCentre-M91p:~$ wget -Nq https://raw.githubusercontent.com/InvenTree/InvenTree/master/contrib/install.sh && bash install.sh
Installer for InvenTree - source: inventree/stable
Detected distribution: Ubuntu 20.04
This OS is currently not supported
please install manually using https://inventree.readthedocs.io/en/stable/start/install/
or check https://github.com/inventree/InvenTree/issues/3836 for packaging for your OS.
If you think this is a bug please file an issue at
https://github.com/inventree/InvenTree/issues/new?template=install.yaml

**Comment by martin323232** [comment]
inven@inven-ThinkCentre-M91p:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

**Comment by martin323232** [comment]
I've also tried the server version, with same result. 
Should I just go for the Docker install?
Or is there hope that this issue will get resolved?

**Comment by matmair** [comment]
@martin323232 I am working on it - this a free-time project so pls do not expect 24hrs return times

**Comment by matmair** [comment]
@martin323232 what is your installer showing on a dry run (using `bash installer.sh -d`)?

**Comment by martin323232** [comment]
@matmair 

did not mean it like that. Just wanted start using Inventree. 
Switched to Docker on ubuntu and installed it there.
I'll can give it another try on monday.

**Comment by matmair** [comment]
@martin323232 maybe try also this command, a PR merging this into master is open.
```
wget -Nq https://raw.githubusercontent.com/matmair/InvenTree/matmair/issue3933/contrib/install.sh && sudo bash install.sh master matmair
```

**Comment by matmair** [comment]
@martin323232 the fix was merged so this should work now:
```
wget -Nq https://raw.githubusercontent.com/inventree/InvenTree/master/contrib/install.sh && sudo bash install.sh master
```

**Comment by martin323232** [comment]
@matmair 

it's working now. but the documentation is not good enough for someone not used to using Linux. 
I'll switch back to using docker on windows
