### ISSUE TITLE
Minimum stock of parts on a (sub-)location

### ISSUE THREAD

**Issue by msch-alpgis** [inventree/InvenTree#3941]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I have the need to track the amount of parts on different locations. By now, we can set a minimum stock of a part globally. But what if I want to have some sublocation stocks to don't fall below their own minimum?

### Suggested solution

The stock items could have a minimum quantity. Or the location itself could have minimum quantities for certain parts.

### Describe alternatives you've considered

I can't see a way to achive this by now.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Sounds interesting

**Comment by SchrodingersGat** [comment]
@msch-alpgis the current implementation is very simple, compared to this approach. Can you suggest how the data structures to support this might work? My first impression is that this would be quite complex to implement (especially regarding edge cases).

**Comment by matmair** [comment]
@msch-alpgis the question is more about how to efficiently match this with nested locations for multiple items/nested boms. The queries have to scale as there might be a lot of items in one query. Could you provide a PR of your approach?

**Comment by SchrodingersGat** [comment]
@msch-alpgis there are a lot of higher priority tasks for us right now. If you want to see this implemented quickly, you could consider [sponsoring the feature](https://inventree.org/support.html). Otherwise, it will sit in our roadmap until a developer gives attention to it :)

**Comment by matmair** [comment]
Not stale

**Comment by matmair** [comment]
Not stale
