### ISSUE TITLE
[FR] Allow deletion of a part image from the Web interface

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#3947]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

FYI. I noticed that deleting a part image does not appear to be possible. 

Perhaps I am blind, but I do not see a delete button anywhere and at least not where I would've expected to find it (in the part image menu) :)

1. Is there a way to delete images that I am not aware of? If so, perhaps it should be added to the part images window?
2. Is the "part image" menu supposed to show ALL part images uploaded on InvenTree or only images for the related part?

### Steps to Reproduce

Add image(s) to your part. Open list of part images. There are check boxes next to each image but no delete toolbar/button. See image below

![image](https://user-images.githubusercontent.com/815886/202439475-c1a0a9ad-b102-4155-995d-7e9bbdda6619.png)

### Expected behavior

I expected a delete button/menu in the part image popup window.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: 8bcf72f
Commit Date: 2022-09-28
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by tehkillerbee** [comment]
@matmair cool, just wanted to let you know in case it had not been noticed.

**Comment by matmair** [comment]
@tehkillerbee Sorry, I thought you filed it as a bug. Do you mind adding "[FR]" to the start of the title to mark it as a Feature Request? That makes it easier to categorize it in the overview.
The functionality certainly would make sense.

**Comment by tehkillerbee** [comment]
@matmair Thanks and done. I rephrased the title slightly to make it clearer what I meant. 

Yeah, I did actually file it as a bug since I thought the toolbar was missing. But it sounds like a FR is more appropriate.
