### ISSUE TITLE
Fields get mangled by front-end forms

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3950]
There might be more issues with this - I can't see exactly why it happens though. Steps here, just in case anyone has any ideas:

1 . Enter data through API (The data here has been entered through the API originally (that was the case with the links as well, I think).
2 . After entering data, it appears as expected (" instead of &quot;")
![image](https://user-images.githubusercontent.com/1314853/202483488-e384412e-6e6b-4ab7-912d-7aeb765d57e1.png)
3. Edit screen in the GUI -> Submitted without changing anything
![image](https://user-images.githubusercontent.com/1314853/202483597-ed4a2a82-ec4c-418a-a806-ae0810f7fe86.png)
4. Now the above has changed, see the top row, right column
![image](https://user-images.githubusercontent.com/1314853/202483723-851fe263-0933-4bcc-8b4d-757da5ce0e1d.png)

_Originally posted by @miggland in https://github.com/inventree/InvenTree/issues/3864#issuecomment-1318782491_

**Comment by SchrodingersGat** [comment]
@miggland can you please provide the version you are running?

**Comment by miggland** [comment]
```
# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

```

I have not tested in the demo, there's a bit much going on at the moment.

**Comment by SchrodingersGat** [comment]
If you get a chance please check on the demo. Can you provide a string which demonstrates the issue?

**Comment by miggland** [comment]
This is very confusing..

On my main system (Ubuntu, with Firefox 107.0): I can not reproduce this issue now, with exactly the same Inventree instance and data.

On my virtual Windows 7 machine, Firefox 107.0, I get the same error - it goes wrong when the form is loaded, ie " is replaced by &quot; and then saved that way. If I explicitly change back to ", it stays there.

I can not reproduce the issue in the demo system at all at the moment..

**Comment by SchrodingersGat** [comment]
Sometimes these things are very finnicky to reproduce. If you cannot reproduce in the demo instance, maybe it has already been addressed?

**Comment by SchrodingersGat** [comment]
@miggland if you can provide more info on this, great :) I'll push it off to the next release cycle until then.

**Comment by miggland** [comment]
This issue is still present, but as you say hard to reproduce and pinpoint. Push it back, I'll add more info here when I have something relevant.
