### ISSUE TITLE
Deploy to Digital ocean

### ISSUE THREAD

**Issue by jholgate93** [inventree/InvenTree#3956]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production

### Describe the problem*

Inventree can't be deployed to docker using the link in the README.MD and also droplet can't be found in the market place

### Steps to Reproduce

Click on 'Deploy to DigitalOcean'

**Comment by matmair** [comment]
The image is currently not offered, see #3957
