### ISSUE TITLE
[FR] Purchase Order Variables 

### ISSUE THREAD

**Issue by BitterMonkey** [inventree/InvenTree#3973]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Looking for the Purchase order Variable Names for Purchase order Templates.

On the Docs page under purchase orders there are non of the Variables listed, where could i find the list of the variables.

### Suggested solution

Can we get a update to the Docs? Or where in the code can i find a list of the variables available, 

### Describe alternatives you've considered

..

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Closed due to lack of activity
