### ISSUE TITLE
Social auth https redirect url

### ISSUE THREAD

**Issue by geniesis** [inventree/InvenTree#3974]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When using InvenTree in the production docker container with Traefik as a https frontend. The Social auth redirect url for Microsoft provider is http instead of https. This creates an error as Microsoft requires https redirects when used in production. The same provider supports non-https in dev setups only.

### Steps to Reproduce

1. Setup production Inventree Docker compose
2. Add Traefik in front of Nginx as SSL frontend
3. Add/Configure Microsoft social auth provider
4. Set base url for server instance setting to have https in url
5. Attempt to login via Microsoft
6. Error is raised indicating that http redirects are not allowed

### Expected behavior

The redirect url sent to Microsoft should be https.

Allauth supports a configuration setting ACCOUNT_DEFAULT_HTTP_PROTOCOL that allows changing the default protocol used.

I have tested using this setting does work to solve my deployment setup.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by matmair** [comment]
Fixed by #3975
@geniesis thanks for the quick fix;
If you mention `Closes #3975` or `Fixes #3975` in the PR the related issue gets auto-closed.
