### ISSUE TITLE
[FR] User registration via API

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3978]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

We currently do not support user registration via API - so the frontend must be used

### Suggested solution

Steps:
- [x] Add  an API endpoint under `/api/user/register` to registering users
- [x] Add unit testing for it

### Describe alternatives you've considered

N/A

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
Ref #3901

**Comment by geniesis** [comment]
It might be valuable to add SCIM 2.0 support when developer this api endpoint, this would allow just in time provisioning with SSO providers.

**Comment by matmair** [comment]
@geniesis this FR is limited to registration via a single API endpoint - providing the same functionality via REST that is given via the current web UI.
Please open an FR if you want SCIM - that is a more involved request than a single endpoint and is an enterprise feature.

**Comment by SchrodingersGat** [comment]
@matmair any objection to me bumping this from `0.12.0` release?
