### ISSUE TITLE
[FR]Checkbox type part parameters

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#3985]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

As we discussed in the #3862 it might be useful to implement a 'checkbox' type Part Parameter Template.

I would envision it in the same way as the dropdown implemented:

Users could define two values in the admin page for the Template if the checkbox type is selected.

The parameter edit form would contain a single checkbox, and the dropdown values (depending on checkbox state) would be saved on save.

### Suggested solution

Implement it?

### Describe alternatives you've considered

Use dropdown type template with dropdown values: 0/1

### Examples of other systems

Arena PLM has such an attribute type

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
@martonmiklos how would you save this in the database? Might there be more input types in the future?

**Comment by SchrodingersGat** [comment]
Perhaps we also want some parameters which are "numeric" (and are validate appropriately)?

**Comment by martonmiklos** [comment]
> how would you save this in the database?

@matmair 
I would not change anything on the storing database side. In the admin UI we could setup values for checked/unchecked state for each attribute. Think about this feature as a constrain on attribute value.

> Might there be more input types in the future?

As @SchrodingersGat mentioned: numeric. From my side: date type attributes might make sense (something like approval date for e.g.). 
In the Arena PLM the following types present:
![kép](https://user-images.githubusercontent.com/1609182/203649551-bc750f46-d8d1-4df4-9b01-0836d178802c.png)
From this list maybe the Cost could be interesting?

**Comment by matmair** [comment]
@martonmiklos but how will InvenTree know if a dropdown or a number or a text should be shown?
Cost is already present if purchasing / selling / internal price is enabled.

**Comment by martonmiklos** [comment]
> @martonmiklos but how will InvenTree know if a dropdown or a number or a text should be shown? 

The Part parameter template would have a 'type' field which would be an enum (text/dropdown/checkbox/number/etc.)


> Cost is already present if purchasing / selling / internal price is enabled.

Yeah, but there could be different type of costs associated to the parts which could be useful to be tracked separately (as an attribute) for e.g. assembly cost. But storing cost data in the attribute brings up some questions on the rendering side too (due to the different currencies), so we can drop the plan supporting this type for now.

**Comment by matmair** [comment]
@martonmiklos an Enum sounds good. Please leave enough namespace for a lot of expansion (1000 options ought to be enough).



> Yeah, but there could be different type of costs associated to the parts which could be useful to be tracked separately (as an attribute) for e.g. assembly cost. But storing cost data in the attribute brings up some questions on the rendering side too (due to the different currencies), so we can drop the plan supporting this type for now.

I would prefer to build out the pricing system to support an arbitrary number of pricing types and algorithms. Once the caching system has proven to work under stress in more instances. I.e. plugins that can define extra pricing types and algorithms for min/max calculations. Or to enhance POs/SOs extra line items like shipments, taxes etc.

**Comment by martonmiklos** [comment]
> @martonmiklos an Enum sounds good. Please leave enough namespace for a lot of expansion (1000 options ought to be enough).
> 

What do you mean under leaving enough namespace? By looking for references in the code I was looking on the currecy field of the Company model which is a CharField. Would not be the same sufficient?

What shall we do with the #3983?
I would recommend to get it back to WIP, rework the is_dropdown field from the templates to an enum.

**Comment by matmair** [comment]
@martonmiklos


> What do you mean under leaving enough namespace?

To leave enough space in the database field. Ie. enough length for the text (setting mac_length to 2 will get you 100 enums for example).



> What shall we do with the #3983?

Sounds good to move to WIP. I think implementing the checkbox in the same PR is reasonable. The difference between the enums (on the frontend) is probably 2 LOCs.

**Comment by martonmiklos** [comment]
> @martonmiklos
> 
> > What do you mean under leaving enough namespace?
> 
> To leave enough space in the database field. Ie. enough length for the text (setting mac_length to 2 will get you 100 enums for example).

At the moment the PartParameter's data field is a CharField with max_length of 500:
https://github.com/inventree/InvenTree/blob/master/InvenTree/part/models.py#L3136

Shall we change that? I do not think that using dropdowns/checkboxes would change the amount of data to be stored in the attributes.

> 
> > What shall we do with the #3983?
> 
> Sounds good to move to WIP. I think implementing the checkbox in the same PR is reasonable. The difference between the enums (on the frontend) is probably 2 LOCs.

Alright we can roll out the dropdown and checkbox together and we can get back later to the number attribute type later.

**Comment by matmair** [comment]
@martonmiklos that should be an additional field

**Comment by martonmiklos** [comment]
> @martonmiklos that should be an additional field

You mean the numeric value of a PartParameter (if we implement it at some point)?

**Comment by matmair** [comment]
@martonmiklos the type of the parameter
