### ISSUE TITLE
Logout Redirect URL for Remote Login Configuration

### ISSUE THREAD

**Issue by maksimstojkovic** [inventree/InvenTree#3994]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Hi,

Currently I am testing the use of Inventree behind [Authelia SSO](https://github.com/authelia/authelia) with the remote/proxy login config settings, and everything seems to be working for login. However, upon trying to logout, the logout process seems to fail (i.e. the user remains logged in, rather than returning to the Authelia SSO login page).

This issue is resolved when the `LOGOUT_REDIRECT_URL` setting is updated to the appropriate Authelia logout URL.

### Steps to Reproduce

1. Setup `remote / proxy login` settings as follows in `config.yaml`:

```yaml
remote_login_enabled: True
remote_login_header: HTTP_REMOTE_USER
```

2. Login through Authelia SSO.
3. Get redirected to [Dashboard (`/index/`)](https://demo.inventree.org/index/).
4. Click Logout.
5. Get redirected to [`/accounts/logout/`](https://demo.inventree.org/accounts/logout/)
6. Click Sign Out.
7. Get redirected to [Dashboard (`/index/`)](https://demo.inventree.org/index/) while still logged in as user.

### Expected behavior

Get redirected to Authelia logout page which handles logout process, before being redirecting to Authelia login page (no longer logged in).

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 20/10/2022
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by matmair** [comment]
@maksimstojkovic this is normal behaviour when using REMOTE. In a normal enterprise scenario you would only invalidate a user session once the REMOTE is not set anymore - so invalidate in the IAM/SSO first and then invalidate the session.
I see you submitted a PR to optionally change that - seems a good way to me

If possible I would stay clear of easily spoofable methods like REMOTE and use something modern like OAuth2/OIDC or SAML - also possible with InvenTree.

**Comment by maksimstojkovic** [comment]
@matmair Thanks for the clarification, I'll have a look into those options.
