### ISSUE TITLE
[FR] 1D Barcode Search

### ISSUE THREAD

**Issue by maksimstojkovic** [inventree/InvenTree#3997]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Search for Parts by scanning a 1D barcode (e.g. a GS1 GTIN barcode in UPC and/or EAN format).

Currently the browser barcode scanner doesn't seem to detect 1D barcodes, while the android app scanner does.
Additionally, the app scanner can read existing label information encoded as a 1D barcode (e.g. `{"part":1}` encoded as a code-128 barcode).

I've tried looking through the interface and documentation for the appropriate place to designate a barcode for a part, but there doesn't seem to be one available.

### Suggested solution

Upgrade existing barcode and/or search functions to search for parts which have a designated barcode value.
Additionally, the browser barcode scanner will need 1D barcode recognition to be implemented if not already available.

Implementing this feature may require the Part model to be updated with a `barcode` field.

As this feature deviates from electrical components and leads toward general inventory management, it may make sense to add an option to the global barcode settings menu to make it optional.

### Describe alternatives you've considered

Generic barcode searching could also be added to the normal search bar (i.e. not the barcode search menu) so any information encoded as a barcode could be used as a search input.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@maksimstojkovic what version of InvenTree are you running? The upcoming `0.9.0` release supports custom barcodes for parts: https://github.com/inventree/InvenTree/pull/3640

> Currently the browser barcode scanner doesn't seem to detect 1D barcodes, while the android app scanner does.

Can confirm, the "webcam scanner" only picks up QR codes currently.

**Comment by maksimstojkovic** [comment]
@SchrodingersGat Sweet! Thanks for confirming.

I'll submit a PR shortly that aims to address this.
