### ISSUE TITLE
[FR] Enable setting API language via header

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4001]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Currently, the API response uses the user's language settings. That means the returned language needs to be set in the account first.

### Suggested solution

Add an optional header to set the language of the response.

### Describe alternatives you've considered

First call the frontend language settings, then issue the API.,

### Examples of other systems

DigiKey API requires this info in the headers for example.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
You can set the language in the header request. This is how the app does it, for example.

**Comment by matmair** [comment]
@SchrodingersGat is that working reliably for you? I have errors with it.

**Comment by SchrodingersGat** [comment]
It seems to work ok but I have not looked into it in any depth.

The API class in the app simply uses the "accept-language" header:

https://github.com/inventree/inventree-app/blob/d122a352a6b435c0017ef9b923aab781c1b6b838/lib/api.dart#L690

**Comment by matmair** [comment]
@SchrodingersGat nevermind, I used the wrong lang code
