### ISSUE TITLE
Cache "has_complete_bom_price"

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4009]
When calculating (and caching) BOM pricing, we can determine if an assembly has a "complete BOM price" (pricing available for each line in the BOM).

Store this as a boolean value, can be retrieved and used when displaying BOM data.

- An assembly must have pricing data for each line in the BOM
- Each subassembly must also have complete pricing data
- So, "has complete pricing" is only true if there is a complete "top to bottom" set of pricing data

**Comment by matmair** [comment]
@SchrodingersGat is this still valid? I think pricing is cached now?

**Comment by SchrodingersGat** [comment]
Only some parts are cached, this calculation is still made on the fly, but should be stored in the db
