### ISSUE TITLE
[FR] Example use cases (website/docs)

### ISSUE THREAD

**Issue by tombola** [inventree/InvenTree#4011]
- [X] I checked and didn't find similar feature request

## Problem

I am a potential new user/contributor and I can't quite identify if InvenTree would be a good solution for my business/client.

It looks like an amazing tool, and takes advantage of in house expertise with django, but I don't want to invest a huge amount of time investigating how we could make it work if it might turn out to be a poor fit.

### Background

I am working for/with a couple of organic producers, one (my employer) is a seed company, and the other supplies perennial herbs/vegetables.

We don't have 'parts', or build lists, but we do have suppliers, seed lots (both supplier and in house), packeting batches, labels etc, and a load of business specific workflows around germination testing, seed growing and managing stock on our website.

## Suggested solution

I would really like to see a couple of examples of contrasting businesses that use inventree. Even better it would be really useful/reassuring to see a list of example businesses that might _not_ be a good fit, eg the platform is not focussed on that type of workflow.

The example could be something like:

- business name
- sector
- features/core-workflows used\*
- extensions/plugins

I assume the best place for something like this would be on the inventree.org website?

I would be happy to chip in with an example of my own if we did decide to adopt inventree.

\* eg I don't think I have a use for BOM, so it would be good to see another example business that does not use that but clearly still finds inventree a good fit.

## Describe alternatives you've considered

I could install InvenTree locally, and explore the docs and codebase to see how far i could move the admin interface and workflows to meet our (loosely defined) business logic/workflows. 

I will in fact do a cursory investigation of this type if I can make time, but it seems likely to be the sort of task that gets really involved really quickly, and I am not sure how much time I could dedicate, especially as I would predict that I would need to do some plugin development to establish our workflows.

## Examples of other systems

This is an example of highlighting projects made on a different django platform:

https://madewithwagtail.org 

_disclaimer: i used to work for Torchbox, who develop wagtail_

## Do you want to develop this?

- [x] I want to develop this.

At least would certainly try to contribute with feedback/content/examples.

**Comment by matmair** [comment]
@tombola I would really like that. The problem I faced when trying to get this going is that most users in my circle use it for industrial production, defense or niche industries. There is a (real) fear that openly advertising the use of the tool would/could open one up to targeted probing into the security of InvenTree and then hacking of the company via it / poisoning the supply chain to get to information.

**Comment by matmair** [comment]
I think this will not gain support. Even I can not submit my usecase due to compliance guidelines. @SchrodingersGat should we close this?

@tombola I am sorry no one was interested - nobody really wants to put their company into the limelight. Maybe it is a fit for you, if you have questions feel free to reach out here or check my GitHub profile/website for more private channels.

**Comment by tombola** [comment]
Thanks for taking the time to consider my suggestion.

On balance I think without broader interest in the project I might be better off working around what we have in place.

Keep up the good work.
