### ISSUE TITLE
Submit button disappears

### ISSUE THREAD

**Issue by martin323232** [inventree/InvenTree#4023]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When clicking "Order Part" from "Part" submit button disappears.
![order_part](https://user-images.githubusercontent.com/6439801/205928283-12fdf1b8-d4d0-4efd-8d3a-161b1470b731.JPG)
[Screencast from 06. des. 2022 kl. 14.33 +0100.webm](https://user-images.githubusercontent.com/6439801/205928316-1412ec49-dad9-4574-9da2-9f9de69d9ebe.webm)

Tried in Chrome, Firefox and Edge

### Steps to Reproduce

1. Go to Part
2. Order part
3. Submit missing

### Expected behavior

Submit button to add part to PO

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by mrkylegp** [comment]
I have noticed this for label printing as well.

**Comment by SchrodingersGat** [comment]
@martin323232 thanks for reporting :)

**Comment by matmair** [comment]
@martin323232 it is hidden because no order is selected - the system does not know where the parts should be added.

**Comment by martin323232** [comment]
@SchrodingersGat Thanks, got it now
