### ISSUE TITLE
Notification Settings is blank

### ISSUE THREAD

**Issue by mrkylegp** [inventree/InvenTree#4024]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

The notifications settings pane doesn't show any content

![Screenshot 2022-12-07 200950](https://user-images.githubusercontent.com/52687659/206136700-6345fadf-1577-4195-9d49-1793114d1987.png)

### Steps to Reproduce

1. Click username
2. Click settings
3. Click Notifications (on the left)

### Expected behavior

I assume there should be a set of notification settings?

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
@mrkylegp did you recently update InvenTree from an older version?

https://docs.inventree.org/en/latest/faq/#feature-x-is-not-visible-after-update

**Comment by mrkylegp** [comment]
@SchrodingersGat Yes I did update today. I tried the cache clear and also tried visiting my inventree instance from a computer which I have never browsed on before. Same issue.

**Comment by mrkylegp** [comment]
@SchrodingersGat I do not have a plugins menu on the left like your image

![Screenshot 2022-12-08 084224](https://user-images.githubusercontent.com/52687659/206302743-1b6ec1b8-ffb2-488c-9199-591e52eed4dd.png)

**Comment by mrkylegp** [comment]
I enabled plugins in my .env and rebooted the docker instance. Also enabled CoreNotificationsPlugin and enabled email notifications. There is now the email setting under the notifications menu.

Is CoreNotificationsPlugin the same as the Inventree Notifications plugin? If so, why is the label different?

**Comment by SchrodingersGat** [comment]
> Anyway, I enabled plugins in my .env and rebooted the docker instance. Also enabled CoreNotificationsPlugin and enabled email notifications. There is now the email setting under the notifications menu.

Ah, this makes sense. I should have asked if the instance had plugins enabled.

> The documentation I saw didn't outline that I needed to enable plugins and enable an additional email plugin for that to work. Maybe I missed something?

This has been addressed in the upcoming `0.9.0` release.

> It seems CoreNotificationsPlugin the same as the Inventree Notifications plugin. How come the labelling is different on mine?

The screenshot is from [the demo server](https://demo.inventree.org) which is running latest code, not stable version.
