### ISSUE TITLE
Low stock notifications not working - email or notification bell

### ISSUE THREAD

**Issue by mrkylegp** [inventree/InvenTree#4027]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I'm not receiving any low stock notifications, either via email or via the notification bell.

I provided a video showing that I have a stock item set to minimum of 2. I remove or adjust stock to cause it to be in a low stock state, but there are no notifications at all. Am I missing something?

https://youtu.be/hQbH_tvhwQE

### Steps to Reproduce

https://youtu.be/hQbH_tvhwQE

### Expected behavior

When an item is marked as low stock, a notification is provided via the notification bell and/or email depending on the users setup & preferences.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
Typically users only receive notifications for "low stock" if they are "subscribed" to a particular part, or the category which contains the part:

![image](https://user-images.githubusercontent.com/10080325/206331673-5da3a207-5c2c-4128-b20d-e82c8b704548.png)

**Comment by mrkylegp** [comment]
@SchrodingersGat If you have a look at the video, I have already subscribed to the part.

**Comment by SchrodingersGat** [comment]
Can you check the behaviour on the demo server e.g. https://demo.inventree.org/part/69/#

**Comment by mrkylegp** [comment]
@SchrodingersGat Just checked and found that the notification worked one time but then after restocking above the minimum stock level then removing stock below the minimum level again, a notification was not triggered again. I also confirmed this on my install.

So basically, the notification is only firing once. If the item is restocked and dropped below the minimum again, there are no subsequent notifications.

**Comment by SchrodingersGat** [comment]
Yep, the notification will only fire once every 24 hours, for any individual part. So, sounds like working as expected.

**Comment by mrkylegp** [comment]
> Yep, the notification will only fire once every 24 hours, for any individual part. So, sounds like working as expected.

Ah, okay. Did I miss that somewhere in the documentation?

I'll go ahead and close this, thanks for the clarification.
