### ISSUE TITLE
[Feature] Part Stocktake

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4034]
Extend the existing "count stock" feature to be a full "stocktake" for a given part.

- Parts can exist in multiple stock items and  different locations
- No current scheme for knowing when entire part stock was last validated
- The "count stock" dialog could be adjusted to point to the "/part/stocktake/" API
- Individually update stock counts for each stock item
- Update a (new) "stocktake_date" field for the Part
- Record the stocktake user
- Expose to API (tables / etc)
- Export in BOM data

**Comment by matmair** [comment]
Would be cool to separate the feature in the API and provide read and write functionality under a dedicated route.

**Comment by SchrodingersGat** [comment]
This could also be used to track historical stocktake information for each part.
