### ISSUE TITLE
How to enable Pack Quantity?

### ISSUE THREAD

**Issue by devkdn** [inventree/InvenTree#4039]
```
# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
```

As the title suggests, I am trying to enable Pack Quantity. I see it on the demo and can also see it in the code, but I'm not familiar with Django and Python. I want to know how I can use that in my InvenTree instance.

**Comment by matmair** [comment]
@devkdn this feature is not released yet, the demo is running latest - not stable.

**Comment by devkdn** [comment]
Thank you!
