### ISSUE TITLE
[FR] Add Company to Build

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#4044]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Hi,
We use external manufacturing partners for assembling of PRBs. We have several partners and select depending on volume, availability, and other things. I found no way to add the EMS partner to a build. 
Michael 

### Suggested solution

We could either add a company field to a build or, may be even better, add a build to a purchase order. 

### Describe alternatives you've considered

Actually we put the name  to the notes section. 

### Examples of other systems

Sorry, no idea

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
@SergeoLacruz builds typically are internal manufacturing jobs. I would suggest doing a PO with the parts from the company you bought them from.

**Comment by SergeoLacruz** [comment]
As told our builds are not internal. We place build orders at EMS companies. 
These companies just offer manufacturing service. They do not sell any parts. That's why there are no manufacturing parts that I could add to the PO.  A build cannot be added to a PO.

**Comment by SergeoLacruz** [comment]
Yes, this seems very similar. Sorry for not seeing this before.
Sending material to a external manufacturing company and getting something back is a common use case here. And as said there is not much missing. I use an external stock location to keep track of the things I sent out. 
The genius reporting system allows to automatically create most of the docs the EMS partner needs. 
It was just nice if I could put the BO into a PO. Or better several of those. I can also put the BO into the free text area of a PO. But then I still cannot see where the BO went to..
