### ISSUE TITLE
[FR] Ability to reserve stock

### ISSUE THREAD

**Issue by Mimosa-oceanis** [inventree/InvenTree#4051]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I'm Building a new part with a BOM. 
A lot of parts are in stock, but some of them not enough to complete the batch build. 
And some parts are not in stock at all. 
I allocate the available stock but for the missing parts I can't generate an order, or add the parts to an already existing order in batch. And what I'm missing the most is knowing if this part is already ordered. (I can have several build using same parts). I need the part on order to be reserved for this build. **To be sure I have order everything missing.** 

### Suggested solution

Ability to reserved parts on order. Knowing all the parts for a specific build is either on stock or ordered. 

### Describe alternatives you've considered

Check manually, but not efficient, and subject to mistake. 

### Examples of other systems

Ability to reserve parts which are not is stock yet.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@Mimosa-oceanis please share the version you are running.

From the demo server, it appears that what you are asking for is already there:

![image](https://user-images.githubusercontent.com/10080325/207285172-af3f9408-9875-4ddd-a8d5-32040637528b.png)

- A button to "order" stock
- A display of how many items are "on order"

Or, perhaps I am misreading your question?

**Comment by Mimosa-oceanis** [comment]
Hi @SchrodingersGat,
I think I'm running the last stable version: 0.8.4
Or maybe I haven't found how to do it. 

Actually there is a button to order it. But I can't do it automatically, like generate an order for all missing component at once. 
And I'm missing the ability to reserve item on order for that specific build. It means if I have another build of another product but who require the same parts, I can see I have parts ordered, but not available because already assign the the first build. 

I hope I manage to be clear, not easy to explain. 
<img width="1512" alt="Capture d’écran 2022-12-13 à 10 59 24" src="https://user-images.githubusercontent.com/65179484/207287953-1bb63e4a-a24a-4380-96ad-5b87bb2358b3.png">

**Comment by SchrodingersGat** [comment]
@Mimosa-oceanis I removed your image as it revealed information about your server address :)

> But I can't do it automatically, like generate an order for all missing component at once.

Such a feature is not available, and there are a lot of edge cases. As parts can be ordered from multiple suppliers, manufacturers, and there are also potentially multiple alternative parts, it is very hard to provide an "order all at once" function. However, open to suggestions.

> And I'm missing the ability to reserve item on order for that specific build. 

This would have to be implemented separately too. Again, as there are multiple suppliers, alternatives, etc, reserving parts would need to be carefully considered.

**Comment by Mimosa-oceanis** [comment]
@SchrodingersGat 
Ah thank you I didn't notice for the server address. 

Hum I see the complexity now. Maybe we could have page with item to be ordered, so need validation and choice of supplier. And once they are ordered they disappear from that list.

But the reservation of parts not is stock (order, or other building order) would be really helpful. Because now I found it difficult to be sure I have order everything I need. Especially if I'm building multiple electronic board at the same time. I have a lot of common parts between boards and now I don't how to be sure I ordered enough parts for all my buildings order. 

The only way I found is to check individually each project and counting the number of parts needed and compare it with the purchase order. So not very easy. 
Maybe there is a better way to do it. I don't know. 

Anyway, I'm really happy with the current version and It is already really helpful. I'm just sharing some ideas to make it even better. Thanks a lot for all the job already made.

**Comment by gunstr** [comment]
@Mimosa-oceanis 
You mention "Maybe we could have page with item to be ordered". There is a section "Required for build orders" in the home page that I find very useful and maybe partly address what you are looking for.

There are some logic errors that I reported in issue #3653. As @SchrodingersGat mentioned there it's currently a quite expensive calculation, I would assume that is why it's not enabled in the demo server.

I have done a "hacky" and not fully verified fix in my local installation based on the guidance I got and although I do not trust it to 100% it's now really helpful for me to track what has to be ordered for multiple builds.

**Comment by Mimosa-oceanis** [comment]
@gunstr 
The required for build orders section seems very useful, but I couldn't understand how it is supposed to work. And I didn't found the documentation to help me. Not all the items are listed here. And if I order items, they stay in that section.

I'm not using the demo server, I'm using the last version installed on a private docker server. Maybe the difference comes also from that.

**Comment by matmair** [comment]
@Mimosa-oceanis I think that comes down to not having data that fits the schema in your instance. Only outstanding stuff (ie you have orders for it) is shown - it is possible that you do not have that in your instance.
We have not touched that section of code for a while.

**Comment by gunstr** [comment]
@Mimosa-oceanis As far as I have seen all material required for build orders (based on the BoM) not covered by the current stock are listed as "required for build orders". The issue I had and reported in #3653 was actually the other way around as parts already allocated to the build order were not deducted from the BoM quantity and thus would still be listed as required. I added the fix I have done if you would like to try. With this little modification I'm very happy with the feature.

**Comment by SchrodingersGat** [comment]
not stale
