### ISSUE TITLE
[FR] load custom template in plugins settings page

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#4073]
## Feature request description

Plugins should have the ability to define a custom html and js template which is loaded into their own settings page.

## Reference

[...] Currently I have my settings load as a custom panel on the StockIndex view. But is there an option for my plugin to add some custom html and js over here like categories and parts have? 
![image](https://user-images.githubusercontent.com/76838159/208187189-64396235-f727-46f7-9282-a7e00f89c3e8.png)

I know that there is a settings mixin which already adds some text fields to this page, but my settings are way more complex than just simple text fields or booleans.

_Originally posted by @wolflu05 in https://github.com/inventree/InvenTree/discussions/4071_

> There is no way currently to add completely custom information to the plugin settings page. It would make sense to add this as a feature, at the very least each plugin could (optionally) define a custom rendering method for its own plugin configuration tab.

_Originally posted by @SchrodingersGat in https://github.com/inventree/InvenTree/discussions/4071_

**Comment by wolflu05** [comment]
What is the current status of this issue? Afaik there is a SettingsContentMixin currently which supports custom html. Is it planned to expand this to js templates as well or should that issue be closed as completed?

**Comment by matmair** [comment]
I have no need for it and I am not sure how we would debug if the JS code works/is ever called so my interest is pretty low. Not against it in any form, just no need for it.

**Comment by wolflu05** [comment]
We could actually also use script tags inside the returned html so there is no need for an extra js template. So from my side we can close this as already implemented.

**Comment by matmair** [comment]
If you are ok with that workaround/solution I would suggest closing as not planned

**Comment by wolflu05** [comment]
The scope of this issue was actually both. Closing as already implemented.
