### ISSUE TITLE
Pricing cache not created

### ISSUE THREAD

**Issue by gunstr** [inventree/InvenTree#4074]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I have been running InvenTree without upgrading now since September (commit 5a08ef908). I liked the changes you have done recently for pricing why I upgraded to the latest master yesterday (commit e4a904e1b) yesterday but I cannot figure out how to get the pricing cache populated.

I would assume it's the task `part.tasks.check_missing_pricing` that should populate the cache and I can see in the Admin panel that it has been running. I have also set the next run a few minutes in the future several times and the task is running successfully each time. But filtering parts with "has pricing = true" I get no returns and obviously most pricing fields are empty, I also checked the database and the table `part_partpricing` is empty,

I have reverted to the old version and done the upgrade again with same result.

Any suggestions what I'm missing?

### Steps to Reproduce

1. Upgrade from the old release
2. invoke update
3. Check that `part.tasks.check_missing_pricing` has been running
4. Filter parts on  "has pricing = true"
5. Returns an empty table

### Expected behavior

Pricing cache to be populated

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: e4a904e1b
Commit Date: 2022-12-17
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: []

**Comment by SchrodingersGat** [comment]
@gunstr thanks for reporting, can confirm that this is a bug
