### ISSUE TITLE
Auto allocating stock will cause both required and optional parts being allocated

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#4085]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

It appears that using auto allocate also allocates optional parts. Is this intentional, as it seems counter intuitive.

If this is intentional, perhaps we should add it to the info header and/or have an option to enable/disable this behaviour.
![image](https://user-images.githubusercontent.com/815886/208688843-578d0e84-6583-4c80-ae00-c871846f3e38.png)

FYI I am using latest 0.10.0 dev version and just upgraded. 

### Steps to Reproduce

1. Create build order of a part with a well defined BOM, containing both required and optional parts.
![image](https://user-images.githubusercontent.com/815886/208689540-8fb84bd0-beec-427c-95dc-f6039f74617e.png)
2. Use the "Auto Allocate" button with default options selected
![image](https://user-images.githubusercontent.com/815886/208689401-56d6a2f8-ffb2-4663-9f30-927a241902c5.png)
3. Both optional and required parts are now allocated:
![image](https://user-images.githubusercontent.com/815886/208689805-6bdc2ebd-8603-4827-9c02-07c01053d327.png)

### Expected behavior

Optional parts should not be allocated automatically.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

**# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: fb34409
Commit Date: 2022-12-19
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False
**

**Comment by miggland** [comment]
This behaviour is the same on the demo server. Probably an option to include or not would be best here?

**Comment by SchrodingersGat** [comment]
@tehkillerbee this is not "intended" but it's also not "not intended" :) 

We can add an option for auto-allocating optional parts

**Comment by tehkillerbee** [comment]
@SchrodingersGat Agreed, I think your solution is better than disabling it permanently.
