### ISSUE TITLE
[BUG] Can't make storage location structural if sub storage location contains parts

### ISSUE THREAD

**Issue by bloemp** [inventree/InvenTree#4087]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

After adding a part to a sub stock location, the parent stock location no longer can be switched to structural

### Steps to Reproduce

1. Create a storage location "test1" and don't make it structural
2. Create a storage location beneath "test1" called "test2"
3. Add a part to storage location "test2"
4. Now try to make "test1" structural... if fails with message " You cannot - make this stock location structural because some stock items are already located into it!"

### Expected behavior

Storage location "test1" should be able to be changed to structural

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

InvenTree Version 	0.10.0 dev
Commit Hash	fb3440947

**Comment by bloemp** [comment]
After reporting the bug i've started searching the source code... I'm proficient in many programming languages, but python isn't one of it (yet)... but it seems that changing the following line of code maybe the solution

On line 155 of file InvenTree/InvenTree/stock/models.py change line
        if self.pk and self.structural and self.item_count > 0:
to
        if self.pk and self.structural and self.stock_item_count(False) > 0:

seems to fix this problem.
As mentioned i'm a python and inventree noob... so i'm very interested if this would be the correct solution, or why it should be solved in another way.

**Comment by SchrodingersGat** [comment]
@bloemp looks like you have successfully worked out where the error is coming from. Would you be willing to submit a PR against this?

**Comment by bloemp** [comment]
@SchrodingersGat as requested, I've made pull request #4089 containing the fix
