### ISSUE TITLE
[FR] Inverse QR Codes in labels

### ISSUE THREAD

**Issue by Kedarius** [inventree/InvenTree#4099]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Would it be possible to add the ability to print color inverted QR codes on labels? We are using Brother PT-700 label printer with black tape (and white text). However the driver does invert the colors, so the label needs to look like this:
![image](https://user-images.githubusercontent.com/352724/209022138-6eb4ddfb-79c0-4e11-a757-92d13a6a6fa4.png)
to be printed like this:
![image](https://user-images.githubusercontent.com/352724/209022331-1ed1d756-16a8-43f5-88fe-11638cdb6c3f.png)

Funny enough, the camera app on my phone (Samsung S21) does read the inverted QR code but inventree companion app does not.

### Suggested solution

I would like to be able to set the QR code generation options in the label template

### Describe alternatives you've considered

I tried using CSS filter:invert(1); on the qr class but it did nothing. Finally I swapped the default colors at /InvenTree/report/templatetags/barcode.py and I managed to get it "working".

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
You should be able to do this already. Can you check the following, and if it works, I'll update the docs.

`{% qrcode "data here" fill_color="white" back_color="black" %}`

**Comment by Kedarius** [comment]
Yes, I can confirm that this is working. Thanks a lot
