### ISSUE TITLE
[FR] Stock History Persistence

### ISSUE THREAD

**Issue by maksimstojkovic** [inventree/InvenTree#4103]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Currently it is possible to write notes when performing stock changes (i.e. add, remove, count, transfer). However, if stock ever reaches 0, at which point the stock item is deleted ("Delete on deplete" defaults to True when adding a new stock item), this history with notes is lost, even from within the admin panel.

While delete on deplete can be disabled (albeit it must be done manually every time a stock item is created and cannot be changed by default for all new stock items in the current implementation), it creates a lot of unnecessary residual stock items, especially if items can be present in multiple locations.

Hence, there is a need to aggregate stock change history into a centralised location where it can persist beyond the lifetime of individual stock items.

### Suggested solution

On the Part interface, it may be useful to have a "History" or "Stock History" tab below the existing "Stock" tab which aggregates all stock changes across all stock items for a product (including stock items that have been deleted) in reverse chronological order.

![image](https://user-images.githubusercontent.com/18454392/209260643-a0bee299-1ab8-46a4-abfe-b5f0d36987bd.png)

I haven't yet looked at how history is implemented, but my initial thoughts are that the individual stock changes/the entire history should be decoupled from stock items, and should only be cascade deleted when the product itself is deleted, rather than the stock item it corresponds to.

### Describe alternatives you've considered

Open to discussion for alternatives.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
@maksimstojkovic I personally do not see a value in this - intrested to see what other think of it.
Centralized stock history will get unreadable fast.

**Comment by maksimstojkovic** [comment]
As an aside, could this be something that could be implemented as an optional plugin, rather than a core function?

**Comment by SchrodingersGat** [comment]
@maksimstojkovic you could certainly implement it as a plugin. Might be a good way to go about it, keeps the mainline codebase clean.

For reference, there is currently work on a "stocktake" feature, which has some similarities to what you are suggesting here:

https://github.com/inventree/InvenTree/pull/4069

**Comment by Bbillyben** [comment]
> @maksimstojkovic I personally do not see a value in this - intrested to see what other think of it. Centralized stock history will get unreadable fast.

Hi @matmair, 
For my use, we have to keep track of every 'single' items (with batch number), which/when are used in what preparation, over many years. It's a regulatory obligation.

In our process, I explicitely add the check to remove 'delete on deplete' for any new item users creates.

**Comment by SchrodingersGat** [comment]
@Bbillyben ref: https://github.com/inventree/InvenTree/pull/4106

**Comment by matmair** [comment]
@Bbillyben I still do not see what benefit it brings to track every movement of stock of a part on the part itself - that will balloon quickly on a mid-size installation and be very hard to reconstruct. I think #4106 makes your use case a bit easier.

**Comment by Bbillyben** [comment]
@matmair,
Yep your right! thanks @SchrodingersGat !

That's just an example's situation where data persistent -for specific items- is mandatory! We have to keep track where, who, when for any audit by regulatory administration.

**Comment by matmair** [comment]
Interested to see what solutions get recommended / how they would be implemented.
Not sure if it will go into core/upstream but I would be willing to help move functioning code into a plugin if it gets rejected. That is a general offer for all things that won't go into core.

**Comment by SchrodingersGat** [comment]
@Bbillyben is the addition of optional configuration for "delete on deplete" enough to close out this issue for you?

**Comment by Bbillyben** [comment]
Hi @SchrodingersGat, from my side, it's quite enough !

But I don't know if it's fit with @maksimstojkovic request.

**Comment by maksimstojkovic** [comment]
@SchrodingersGat that solution works for me, so this issue can be closed.

I may look into the plugin alternative some time in the future.

**Comment by SchrodingersGat** [comment]
@maksimstojkovic feel free to ping us if you want any plugin pointers.
