### ISSUE TITLE
Barcode scanning not working after update to 0.10.0 dev

### ISSUE THREAD

**Issue by Rincewind34** [inventree/InvenTree#4105]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Linking bar codes doesn't seem to work no matter what I do. I tried different browsers, different devices all produce the same error.

On my installation just recently updated to the latest development version: I click on link bar code and the console shows this error:
```
Uncaught ReferenceError: QrScanner is not defined
    barcodeDialog en.barcode.js:271
    jQuery 7
    trigger event-handler.js:305
    _showElement modal.js:246
    _ index.js:251
    a index.js:273
    s index.js:100
    b index.js:279
    setTimeout handler*b index.js:277
    _queueCallback base-component.js:45
    _showElement modal.js:251
    show modal.js:143
    _ index.js:251
    show backdrop.js:54
    _ index.js:251
    a index.js:273
    b index.js:276
    _emulateAnimation backdrop.js:126
    show backdrop.js:53
    _showBackdrop modal.js:309
    show modal.js:143
    jQueryInterface modal.js:384
    jQuery 2
    jQueryInterface modal.js:373
    openModal en.modals.js:708
    beforeSend en.modals.js:1014
    ajax jQuery
    launchModalForm en.modals.js:1116
    inventreeDocReady inventree.js:120
    jQuery 2
[en.barcode.js:271:9](https://bbbbb.dyndns.org/static/i18n/en.barcode.js)
Uncaught ReferenceError: QrScanner is not defined
    barcodeDialog en.barcode.js:271
    jQuery 7
    trigger event-handler.js:305
    _showElement modal.js:246
    _ index.js:251
    a index.js:273
    s index.js:100
    b index.js:279
```

I can enter the bar code, but the modal does not have a submit button. When I press enter, I'm presented with the following error:
<img width="799" alt="Screenshot 2022-12-23 at 16 55 25" src="https://user-images.githubusercontent.com/13020648/209363611-02c090b8-98ec-4c10-8751-091cb92f0b6b.png">

On your demo instance, the behaviour is different. The console does not show the error and the camera starts if I click the camera icon. But when I enter the bar code manually, the modal closes immediately after I enter the first character. After that, my only option is to unlink the bar code again and I'm were I started.

### Steps to Reproduce

- Go to any part
- click on link bar code

### Expected behavior

I should be able to link a barcode.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

Your demo instance:
# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: cd2495c
Commit Date: 2022-12-22
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

My installation:
# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16

Database: mysql
Debug-Mode: False
Deployed using Docker: True
Active plugins: []

**Comment by SchrodingersGat** [comment]
Regarding the issue on your server - have you tried clearing out your browser cache? It looks like the javascript files are out of sync.

On the demo server, there is a "configurable" delay after data-entry in the barcode boxes. These entry boxes are intended to be used with USB barcode scanners, and so have a pretty short timeout by default. If you are testing by manually entering data, you'll want to increase this timeout.

![image](https://user-images.githubusercontent.com/10080325/209433416-c2891f2a-d2fb-4f49-806f-6a154cf40fed.png)

**Comment by Rincewind34** [comment]
@SchrodingersGat thank you very much for getting back to me! I already tried resetting the browser cache so I dug a little deeper.
I think this is caused by the static folder living in the inventree docker volume. Running grep results in:
`/data/inventree_data/static$ grep -lR "QrScanner" *
i18n/it.barcode.js
i18n/id.barcode.js
i18n/en.barcode.js
i18n/he.barcode.js
i18n/es.barcode.js
i18n/es_MX.barcode.js
i18n/nl.barcode.js
i18n/da.barcode.js
i18n/fa.barcode.js
i18n/pt.barcode.js
i18n/ja.barcode.js
i18n/de.barcode.js
i18n/hu.barcode.js
i18n/zh.barcode.js
i18n/ru.barcode.js
i18n/vi.barcode.js
i18n/th.barcode.js
i18n/ko.barcode.js
i18n/tr.barcode.js
i18n/pl.barcode.js
i18n/fr.barcode.js
i18n/no.barcode.js
i18n/pt_br.barcode.js
i18n/sv.barcode.js
i18n/cs.barcode.js
i18n/el.barcode.js
script/qr-scanner.min.js.map
script/qr-scanner.umd.min.js
script/qr-scanner.umd.min.js.map`

which doesn't look like the newest version of you source code.

Just to make sure I didn't mess up during the docker update, here is what I did:
`
» docker-compose down
» pull the HEAD of your Git Repo plus my small LDAP changes: https://github.com/inventree/InvenTree/compare/master...Rincewind34:InvenTree:master#diff-febf73fb8db0cab29b06e16438d535af8f6c15955ebc64f8a44d26d003f55cf0 (I'm happy to try it without my changes, but this is just some semi hardcoded LDAP add-on to the Django auth stuff)
» docker-compose run inventree-server invoke update
» docker-compose up --build -d inventree-server

MySQL and nginx are running in a separate container connected to more than just inventree, so omitted here.

**Comment by SchrodingersGat** [comment]
Do you have the static root directory exposed to your local file system as an external volume? Otherwise, when the static files are "updated" they will be overridden the next time the container launches.

**Comment by Rincewind34** [comment]
@SchrodingersGat 
this is our inventree compose file:
```
version: "3.0"

x-inventree-common: &common
  build:
    context: ../images/inventree
    target: production
  env_file:
    - inventree.env
  volumes:
    - inventree_data:/home/inventree/data
  restart: unless-stopped

services:
  inventree-server:
    <<: *common
    depends_on:
      - mysql
    expose:
      - 8000

  inventree-worker:
    <<: *common
    command: invoke worker
    depends_on:
      - inventree-server

volumes:
  inventree_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/inventree_data'
```
Other than that there is nothing else "crazy" setup with the static folder (or any other one). Should I try deleting it and wait for it to be repopulated?

**Comment by SchrodingersGat** [comment]
To confirm that the static files are being regenerated, delete the "static" directory in the external volume, and then run:

```
docker compose run inventree-server invoke static
```

This should regenerate static files into the external directory.

Might be similar to this issue:

https://docs.inventree.org/en/latest/start/docker_prod/#common-issues

**Comment by Rincewind34** [comment]
Thank you very much, this is now resolved!! Everything is working as expected. I really want to start contributing at some point but there is just so much other stuff to do that keeps getting in my way. Thanks anyway for your great work!!! Me and my team are very happy with this software.

**Comment by matmair** [comment]
@Rincewind34 is it ok if I close this as completed?

No hurries with contributing, if you need pointers feel free to ping us with @inventree/maintainer @inventree/triage

**Comment by Rincewind34** [comment]
Yes, this can be closed. Unless you want to transform it into a documentation improvement? The fact that there is a setting for the barcode reader delay really got me off guard. Maybe a small hint about that would be helpful.

**Comment by matmair** [comment]
@Rincewind34 I am currently rewriting the UI, I will put an info-bubble for the settings somewhere in the dialogue.
Thank you for the suggestion. We have a lot of settings in general, well over a hundred.

**Comment by Rincewind34** [comment]
Yeah, I noticed. I just scrolled through the settings also in the admin page :D
