### ISSUE TITLE
[FR] Add Apprise for notifications

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4126]
@matmair: I just stumbled on this package again. Have used it earlier (CLI only) for Gotify. However, it may give the possibility of having general notifications, without explicitly adding every service independently..
https://github.com/caronc/apprise

_Originally posted by @miggland in https://github.com/inventree/InvenTree/issues/4114#issuecomment-1367213231_

**Comment by matmair** [comment]
Hi there @miggland - I have released a plugin that integrates Apprise, please make note if something is not working:
https://pypi.org/project/inventree-apprise/

**Comment by miggland** [comment]
Nice, @matmair! Will install and try it out.

**Comment by miggland** [comment]
BTW, I tried it out and worked fine! Thanks for implementing.
