### ISSUE TITLE
invoke update did not receive all required positional arguments!

### ISSUE THREAD

**Issue by nelsonov** [inventree/InvenTree#4135]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Invoke update fails with message "did not receive all required positional arguments!"

### Steps to Reproduce

```
inventree@rpi07:~ $ source env/bin/activate
(env) inventree@rpi07:~ $ cd src
(env) inventree@rpi07:~/src $ git pull
Already up to date.
(env) inventree@rpi07:~/src $ git remote -v
origin  https://github.com/inventree/inventree (fetch)
origin  https://github.com/inventree/inventree (push)
(env) inventree@rpi07:~/src $ git branch -v
* master 2f7436d89 New Crowdin updates (#4132)
(env) inventree@rpi07:~/src $ invoke update
'update' did not receive all required positional arguments!
(env) inventree@rpi07:~/src $ cd ..
(env) inventree@rpi07:~ $ invoke update
Can't find any collection named 'tasks'!
```

### Expected behavior

invoke update updates database

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

Was 0.7.0 dev

Now git commit 2f7436d89

**Comment by nelsonov** [comment]
I am working from instructions here:

https://docs.inventree.org/en/0.7.1/start/update/

**Comment by matmair** [comment]
@nelsonov please check:
1) your activating the env your inventree insurance runs one
2) the directory you are executing 'inv update' in also constrains a file named 'tasks.py' (ie is the top directory of your source)

In general I would recommend switching to the package based install method, that handles updates better/with fewer steps

**Comment by nelsonov** [comment]
I am in the process of switching to the docker version, but won't I have a version conflict for the database?  I have a substantial amount of data that I don't want to lose. That's why I'm trying to do an update and migration now, so that I can have the right form.

@matmair I didn't understand what you said.  Maybe some typos?  Am I not supposed to activate the env?  If I don't, then that just produces different errors.  What directory am I supposed to be in to invoke update?

With the env deactivated:
```
inventree@rpi07:~ $ cd src
inventree@rpi07:~/src $ invoke update
'update' did not receive all required positional arguments!
inventree@rpi07:~/src $ cd ..
inventree@rpi07:~ $ invoke update
Can't find any collection named 'tasks'!
```

**Comment by nelsonov** [comment]
I have exactly the same problem if I try `invoke export-records -f data.json`.  The instructions give no indication of whether I'm supposed to have the venv activated or not and also no indication of what directory to be in.  I have hundreds of hours into the database that now exists, so I am really hoping that I can get it out of the current install and into a new docker install.

**Comment by SchrodingersGat** [comment]
What version of invoke do you have?

```
python -m invoke --version
```

**Comment by nelsonov** [comment]
```
inventree@rpi07:~ $ python --version
Python 3.7.3
inventree@rpi07:~ $ python -m invoke --version
/usr/bin/python: No module named invoke.__main__; 'invoke' is a package and cannot be directly executed                                                                                      
inventree@rpi07:~ $ invoke --version
Invoke 0.11.1
inventree@rpi07:~ $ source env/bin/activate
(env) inventree@rpi07:~ $ python -m invoke --version
/home/inventree/env/bin/python: No module named invoke
(env) inventree@rpi07:~ $ invoke --version
Invoke 0.11.1
(env) inventree@rpi07:~ $ python --version
Python 3.7.3
```

**Comment by SchrodingersGat** [comment]
@nelsonov you need invoke `1.4.0` or newer (as per the docs)

https://docs.inventree.org/en/latest/start/intro/#invoke

**Comment by nelsonov** [comment]
I used pip, both in the venv and out of it to upgrade invoke:
```
(env) inventree@rpi07:~/src $ invoke --version
Invoke 1.7.3
```

And now the command is upgrading modules and, I would assume, is going to update the database

**Comment by SchrodingersGat** [comment]
Great! I've added a note to the FAQ. If you are happy that this is now working, please close out this issue.

**Comment by nelsonov** [comment]
It is now failing and complaining about INVENTREE_SECRET_KEY, but that may be a problem I can figure out for myself.  The issue that I opened is resolved.
