### ISSUE TITLE
[FR] Update django-allauth to include openid_connect SSO

### ISSUE THREAD

**Issue by gueldenstone** [inventree/InvenTree#4139]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

With version 0.52 django-allauth supports generic oidc providers (see this [PR](https://github.com/pennersr/django-allauth/pull/3165). Inventree ships with django-allauth 0.51. I need this feature to make inventree work with our oidc provider.

### Suggested solution

 It would be great if inventree would ship with version 0.52 of django-allauth.

### Describe alternatives you've considered

My oidc provider supports a github enterprise compatible endpoint.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Nice, I've made a PR to update to 0.52.0 - https://github.com/inventree/InvenTree/pull/4141
