### ISSUE TITLE
[BUG ]PLUGIN setting only work when set in config file

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4146]
@wolflu05 I think I found the problem. Seems like the mapping only works via config file (this is how I do it currently) - fix incomming.

_Originally posted by @matmair in https://github.com/inventree/InvenTree/discussions/4123#discussioncomment-4591611_

**Comment by wolflu05** [comment]
Thank you for your investigation. Is fixing this really a breaking release? Would love to get this also working with the current stable which I'm testing against.

**Comment by matmair** [comment]
@wolflu05 I am not sure where the idea of breaking comes from - I did not label it as such.
You can always provide a config file - which I do in my CI - if you want it running on the current stable.

**Comment by wolflu05** [comment]
Breaking was a bit to hard. More like a minor change rather than a bug like you labeled it. So this won't be backported?

**Comment by matmair** [comment]
I think it is not intended that plugins can't be tested by setting an env.
Certainly was not the idea when I implemented it - therefore the `bug` label. Bugs happen and do not need to be breaking to be such. It is minor in nature, a backport was suggested in the PR.
