### ISSUE TITLE
[FR] Simplify / optimize setting loading

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4149]
We are currently loading the config.yaml every time get_setting() is called.
It would be far more efficient to initialize this on startup and then to just reuse the variable.

**Comment by matmair** [comment]
@SchrodingersGat thoughts? Could be implemented together with #3982

**Comment by SchrodingersGat** [comment]
Yes, it is not very efficient to re-load the file multiple times. It is a good idea to load once and cache.
