### ISSUE TITLE
Non-python requirements

### ISSUE THREAD

**Issue by diegoherranz** [inventree/InvenTree#415]
When trying to install InvenTree, I had to install the following package in Ubuntu: `libpq-dev`.
Does that make sense? Is there a list of system packages needed?

Thanks!

**Comment by SchrodingersGat** [comment]
Hi @diegoherranz libpq-dev is only required if you're running a postgresql database. I've just fixed this so it's not required by default.

Apart from this (and only if you're using postgresql) you should not need anything other than python and  pip.

Please let me know if you have any other issues getting it up and running.

**Comment by SchrodingersGat** [comment]
Ideally the installer script should ask the user if they want postgresql support and install the required packages if necessary

**Comment by SchrodingersGat** [comment]
Hi @diegoherranz I have now provided better documentation on how to setup with postgresql - https://inventree.readthedocs.io/en/latest/config.html - so I am going to close out this issue. Cheers!

**Comment by diegoherranz** [comment]
Sorry for the late reply. It is much clearer now in relation to postgresql. Thanks!

One more thing:
I seem to need the following sequence for a successful installation, which doesn't match the [getting started guide](https://inventree.readthedocs.io/en/latest/start.html):
```
$ make install
$ make migrate
$ make supersuser
$ python3 InvenTree/manage.py runserver
```

If I run `make supersuser` before `make migrate`, I get:

`django.db.utils.OperationalError: no such table: auth_user`

Is that correct? Does the guide needs updating?

Thanks again!

**Comment by SchrodingersGat** [comment]
Ah good catch, I have fixed this in https://github.com/inventree/InvenTree/pull/428

Now a single call to **make install** performs all the necessary steps in the correct order.

Thanks for pointing this out. Let me know if you see any other issues.

**Comment by diegoherranz** [comment]
Installation works seamlessly now. Thanks!
