### ISSUE TITLE
CI - docker workflow overwrites newer images 

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#4155]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

If the docker workflow needs a bit longer than a workflow which was started after that workflow, the docker image on docker hub will be an old image because it gets overritten by the running job on an older commit.

![image](https://user-images.githubusercontent.com/76838159/210777176-feb29432-6928-4da0-8ec6-39b9383ea66e.png)

![image](https://user-images.githubusercontent.com/76838159/210778710-9e6b59ed-42db-4a8c-b49f-d2322db1799f.png)

### Steps to Reproduce

-

### Expected behavior

There are two possibilities to fix this issue:

1. Longer running older jobs should check before a push if there was already pushed something newer
2. Newer jobs should cancel older running docker jobs

I would prefer the second fix, because pushing also can take some time where something newer was already pushed after the check.

Can you please retrigger the docker pipeline for now so I can run my test ci script to see if it works?

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

-

**Comment by matmair** [comment]
@SchrodingersGat maybe we should set [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency)?

**Comment by wolflu05** [comment]
Thank you very much. This a pretty powerful option. Didn't know this exists. Thought you would need to manually check for running jobs and cancel them.

**Comment by matmair** [comment]
@wolflu05 the syntax is quite wide, you can do a lot with it. GitHub Action grew to get a quite potent system, second only to Azure DevOps Pipelines in my opinion.

**Comment by wolflu05** [comment]
My knowledge of the github actions syntax is quite a bit deprecated, as I wasn't doing something with it the last year, where it got a major update with powerful features.

**Comment by wolflu05** [comment]
May you can just retrigger the newest job for now so that latest is the actual latest so I can test out my ci pipeline?

**Comment by matmair** [comment]
> May you can just rerun the newest docker job for now so that latest is the actual latest so I can test out my ci pipeline?

I restarted the run. Will take probably around an hour - our build times are quite long.
