### ISSUE TITLE
BOM Pricing pie charts for Variants not including Inherited Parts

### ISSUE THREAD

**Issue by Geekly** [inventree/InvenTree#4159]
Variant BOM Pricing pie chart does not seem to be including inherited parts.

Template part:
![image](https://user-images.githubusercontent.com/305681/210823260-81e4804a-dc78-4b27-87ef-4dfa53349cd3.png)

Variant part:
![image](https://user-images.githubusercontent.com/305681/210823690-77903e49-5004-4e5a-bbd3-40841d2385e7.png)

I expected pie chart for the Variant part to also include the inherited parts, but it only appears to include the non-inherited parts. Note that the BOM Pricing is calculated correctly, but the pie chart is not including the inherited parts for display.

Here's the version info for the Inventree installation (via Docker image).

![image](https://user-images.githubusercontent.com/305681/210822952-6fef017e-3dcd-4a33-b783-8c73a327c76b.png)

# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: mysql
Debug-Mode: False
Deployed using Docker: True

### Discussed in https://github.com/inventree/InvenTree/discussions/4156

<div type='discussions-op-text'>

<sup>Originally posted by **Geekly** January  5, 2023</sup>
I'm trying to view pricing for variant BOMs. I'm referring specifically to the pie chart that shows the contribution of each part in a BOM to the total price. The total under Pricing Information seems correct, it's just the pie chart that's incomplete.

Template Part BOM
- Part A (Inherited)
- Part B

The BOM Pricing pie chart for the Template Part is complete and correct. Both parts show up in the pie chart with prices.

Variant 1 (based on Template Part)
- Part A (Inherited)
- Part C

The BOM Pricing pie chart for Variant 1 is incomplete. Only the Part C shows up in the pie chart and non of the inherited parts. Obviously we want to see all of the parts. 

Does anyone have suggestions about what I could be doing wrong? Is this the right place for this post?

Thanks very much.</div>

**Comment by matmair** [comment]
@SchrodingersGat seems like a bug to me.
@Geekly thanks for the report; please try to paste the version info the next time. There should be a button to copy those in the modal. I have a script running that automatically scrapes the bug reports to get statics but they only work with text info.

**Comment by SchrodingersGat** [comment]
Hey @Geekly the pricing system has received a major overhaul in the latest release (`0.9.0`) and this issue has been addressed there. I'd suggest that you update to fix this; the changes are significant and not compatible with a backport to 0.8.x

**Comment by SchrodingersGat** [comment]
example - https://demo.inventree.org/part/81/?display=pricing
