### ISSUE TITLE
SSO SignUp with Microsoft Azure AD | Bug/Issue

### ISSUE THREAD

**Issue by 46labs-itadmin** [inventree/InvenTree#4162]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

We just did the configuration to accept Azure AD Single Sign On, the way it works is that we basically configured an Azure AD Security Group to the Azure AD Authentication for Inventree's Single Sign on.
When we want to allow Login to Inventree we first add the User in the Azure AD Security Group and that's pretty much it.

So let us assume that a user "test@domain.com" was just added as a Member to the Security Group that is bound to the Group on Azure AD.

The User goes to Inventree.domain.com and clicks on 'Microsoft Graph' under 'or use SSO'.
User is the prompted with a Microsoft Login Screen.
The User Authenticates using Microsoft Credentials.
User gets the filled-in Inventree Sign up form.
User clicks on Sign Up
User is Presented with an Internal Server Error (As per the attached screenshot)

How we are currently fixing the situation and actually allowing the user to sign in:
User Closes the Internal Server Error Tab.
Goes back to the Inventree.domain.com 
Clicks on 'Microsoft Graph' under 'or use SSO'
Microsoft Authentication is Done
User is able to Login

### Steps to Reproduce

1. The User goes to Inventree.domain.com and clicks on 'Microsoft Graph' under 'or use SSO'.
2. User is the prompted with a Microsoft Login Screen.
3. The User Authenticates using Microsoft Credentials.
4. User gets the filled-in Inventree Sign up form.
5. User clicks on Sign Up
6. User is Presented with an Internal Server Error (As per the attached screenshot)
![Error Inventree Sign Up SSO](https://user-images.githubusercontent.com/122104842/211037058-a2476f2e-c6ac-4017-ac0f-b35ea1499e9a.png)

### Expected behavior

Instead of Internal Server Error, user should get a screen saying "SSO Sign-up has been Successful" and gets redirected to the index page.

### Deployment Method

- [X] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: []

**Comment by matmair** [comment]
@46labs-itadmin thank you for the report. We will need some details to analyze.
Microsoft puts tenant ids in its Auth URLs so please make sure to remove them from logs or black the out in screenshots. You could reveal your company's identity and possibly your onmicrosoft subdomain.

Questions:
1. What installation method have you used
1a. If it was via git: what is your current git commit
1b. If it was via the package installer: do you still have your install logs?
1c. If it was via the package installer: please check your apt sources for the source used for your install
2. Please check the admin page for logged errors (eg. https://127.0.0.1/admin/error_report/error/) and report them back

**Comment by matmair** [comment]
Hi there @46labs-itadmin can we assist you in this further or should we close the issue?

**Comment by 46labs-itadmin** [comment]
Will get the above requests shortly.

**Comment by matmair** [comment]
Closing due to lack of response. Please feel free to reopen if the problem reappears/still persists.
