### ISSUE TITLE
[FR] :checkered_flag: Export BOM in CSV with alternative Part numbers

### ISSUE THREAD

**Issue by xcoder123** [inventree/InvenTree#4196]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

It would be a great feature if when we are exporting BOM in CSV to share with other people full BOM with alternative part numbers listed as well

### Suggested solution

It could be as simple as: "ALT PN 1, ALT DESC 1, ALT PN 2, ALT DESC 2" etc.

### Describe alternatives you've considered

Currently we manually enter alts

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Sounds reasonable.
The priorities of the core team are not really in this area of the code right now (see https://inventree.org/blog/2023/01/02/upcoming) but maybe someone else comes around and develops it. Should be a good starter project as the export code is rather simple.

**Comment by bloemp** [comment]
Well I saw the "starter" tag and couldn't resist ;) I've created PR #4203 that hopefully does what the OP requests (or at least is a good starting point)
