### ISSUE TITLE
[BUG] Calculation of total price is wrong with mixed currencies

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#4199]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When adding line items with different currencies, the total price calculated in the line items overview does not take into account different currencies per line.

This happens in Purchase and in Sales orders. 10 yen are only about 8 cents - 20 USD is way off the correct value.

![image](https://user-images.githubusercontent.com/1314853/211769348-c9c537dd-4ffb-4429-a619-0a13a6aa76b5.png)
![image](https://user-images.githubusercontent.com/1314853/211770368-3a091be9-27ea-4654-83ae-5114e360f0a9.png)

These were both created on the demo server. The total cost, calculated at the top of the order, is correct in both cases (10.08 USD)

### Steps to Reproduce

1. Create sales|purchase order
2. Add line items with different currencies
3. Check bottom of table summary - find wrong sum

### Expected behavior

One could argue that it makes no sense to use different currencies for each line item. I was trying to use this in a sales order to calculate a total cost of an idea, with parts purchased from different vendors, in different countries.

Regardless of which, it is currently possible to do this, and the sum is wrong. Something must be changed. Options:

1. Make the calculation take into account the currencies, as with the total cost.
2. Remove the sum from the table - better no info than wrong info, possibly on if different currencies available.
3. Make it impossible to use different currencies in line items in an order. This would require setting a currency for an order, and sticking to that.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: e730b5c
Commit Date: 2023-01-10
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by matmair** [comment]
@miggland Thanks for the report.
Seems like we will have to disable totals for now as the frontend does not know the rate.

**Comment by miggland** [comment]
I'm definitely not very good at how the frond-end works. I tried finding where that line is created, but no luck.

Can you point me to the right place, @matmair ?

**Comment by matmair** [comment]
@miggland I am also not really good with the current thing - although I am currently rebuilding it.

**Comment by bloemp** [comment]
@miggland you can disable the total price column footer of the purchase/sale order tables by commenting out the footer-formatter code:

https://github.com/inventree/InvenTree/blob/e730b5c24ce88b7b3d72d39903815359b5b66fdb/InvenTree/templates/js/translated/order.js#L2373-L2385

https://github.com/inventree/InvenTree/blob/e730b5c24ce88b7b3d72d39903815359b5b66fdb/InvenTree/templates/js/translated/order.js#L2560-L2572

https://github.com/inventree/InvenTree/blob/e730b5c24ce88b7b3d72d39903815359b5b66fdb/InvenTree/templates/js/translated/order.js#L3885-L3897

https://github.com/inventree/InvenTree/blob/e730b5c24ce88b7b3d72d39903815359b5b66fdb/InvenTree/templates/js/translated/order.js#L4377-L4388

At first glance it seems to be doing some currency conversion... but not on individual rows. Will investigate if I can get it working

**Comment by matmair** [comment]
My recommendation regarding the mixed currency total would be to use the API to get that number.

**Comment by miggland** [comment]
Good point, better not to recalculate this as it's already done somewhere.

**Comment by bloemp** [comment]
@miggland still looking to see if I'm able to fix it. Tried a few things, but I was to focused on adding data to the order lines. Having read the recommendation of @matmair, and re-thinking my strategy. I'm now thinking on adding two more fields to the api/order/so/ and api/order/po/ endpoints that represent the sub_total for the order lines and the extra lines.

Total price and sub-total prices will then all be shown in the base currency.

**Comment by matmair** [comment]
Sounds good. Please make a note of the speed of the endpoint before and after the changes, it is pretty simple to introduce slow DB queries unknowingly. The response time should not change much.
HMU if you need any pointers

**Comment by bloemp** [comment]
I've made a draft PR #4245 which is an initial solution to this problem, but it needs further refinement as for some reason the bootstrap table is firing the onPostFooter twice per table. So that's 4 times on page load.
I'm thinking to have the sub total values present in the normal GET call to the template, so I can pass them to the javascript routines without a callback to the API.
