### ISSUE TITLE
[FR] All Models should have Metadata attached

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#4202]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I  have some ideas of things I would like to implement in some plugin/using my own API scripts. However, the central models are missing the Metadata extension in several cases.

### Suggested solution

Add the Metadata plugin to the Models missing it. See PR #3895 as a reference.

* List updated *

Already present:
- [x] Company
- [x] PO
- [x] SO
- [X] Part categories
- [x] Part
- [x] Stock item
- [x] Stock location
- [x] Manufacturer part
- [x] Supplier part
- [x] Part labels
- [x] Stock item labels
- [x] Stock location labels
- [x] PO lines
- [x] PO extra lines
- [x] SO lines
- [x] SO extra lines
- [x] SO shipments
- [x] Build Orders
- [x] Build order items
- [x] BOM items
- [x] Reports BOM
- [x] Reports Build
- [x] Reports PO
- [x] Reports SO
- [x] Reports test
- [x] Part parameter template

Not present:
- [ ] Part test templates
- [ ] Part parameters
- [ ] Part category parameter templates
- [ ] BOM item substitute
- [ ] Part relateds
- [ ] Stock item test result

New models:
- [ ] Return order
- [ ] Return order lines
- [ ] Return order extra lines
- [ ] Company contacts

No action on these:
- ~~Users~~
- ~~Part pricings~~
- ~~various price breaks~~ 
- ~~various attachments~~
Input welcome - which ones make sense? Did I miss any which have had metadata models added since 0.9.2?

### Describe alternatives you've considered

Alternative is to not do this at all :)

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
I would not change the Users model, which can unintended effects in Django.
I would also prefer to not touch pricings/price breaks as we had big refactors there in the latest releases and I would like to wait for a few releases till we are sure nothing unobvious broke.

**Comment by miggland** [comment]
@matmair Makes sense, thanks for the input. I've reorganised the text above to make it a bit clearer on this, and what's already there.

**Comment by matmair** [comment]
Seems fine. If you create a PR please make sure that you reduce the number of migrations to as low as possible.

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by miggland** [comment]
@SchrodingersGat I've updated the list above according to #4410 - so there are still a few models missing.

**Comment by miggland** [comment]
There's also a few new models which did not get metadata when they were added, I've added those to the list.
