### ISSUE TITLE
[BUG] :checkered_flag: Parts not marked as 'available' after action "Return to stock"

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#4205]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

See discussion https://github.com/inventree/InvenTree/discussions/4200

Returned stock should be marked as available

### Steps to Reproduce

1. use demo server
2. Check stock of part 108, filter by available: "Blue chair": 14 pcs (https://demo.inventree.org/part/108/)
3. Open the stock item sold&shipped in SO0001: https://demo.inventree.org/stock/item/994/
4. Use "Return to stock" action on in top right menu.
5. Choose a location, eg "Room 101" (same as other 14 chairs), add note "Testing return to stock"
6. Check stock of part 108, filter by available. Expect 17 pcs -> Only 14 pcs available.

Before:
![image](https://user-images.githubusercontent.com/1314853/212007425-762c820d-f55e-46c0-92cc-001fe7d3bd83.png)

After:
![image](https://user-images.githubusercontent.com/1314853/212007679-6e035f7c-8946-4181-ab37-c680ac384658.png)

All stock items after change, without filtering:
![image](https://user-images.githubusercontent.com/1314853/212007904-5da9f2c6-6294-435b-8b47-e04b7c3ad11b.png)

### Expected behavior

Returned stock should be counted/shown as part of available stock, without extra actions.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: e730b5c
Commit Date: 2023-01-10
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by bloemp** [comment]
I've created PR #4208 in an attempt to resolve this issue. Not completely sure if I did it right...
When you return stock to the location it came from (its parent) where merging the returned stock to that stock.
Otherwise the stock is moved to the selected location.

**Comment by SchrodingersGat** [comment]
@exp if there are still outstanding issues you are concerned about, please open a new issue (you can reference back to this one)
