### ISSUE TITLE
[FR] Introduce optional physical units to parameter input

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4209]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Currently, you have to enter the value of a parameter always in the same unit, which is mostly okay - except when someone in your team uses non-SI measurement systems. Then you start calculating.

### Suggested solution

Integrate [pinet](https://github.com/hgrecco/pint) to facilitate a unit conversion. This would also enable setting metric or imperial in the user settings.

- [ ] API endpoint to convert from any unit to any
- [ ] Add switch to parameter to enable base unit saving
- [ ] Make the value of parameter optionally unit-safe
- [ ] Add dynamic input to the interface with unit-diverse input
- [ ] Opt: Detect unit from test
- [ ] Opt: Add babel to include translations of units
- [ ] Opt: Define custom units
- [ ] Opt: Add template tag to do unit transformation in reports

### Describe alternatives you've considered

N/A

### Examples of other systems

I know partskeepr could do something similar. The 'big-boy' PLMs have this integrated as well.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
still intrested

**Comment by EvilMustacheTwirl** [comment]
So there are a couple of django projects that do a lot of the base work but they seem to be gathering dust so I'm not sure if they would still work. 

https://github.com/coddingtonbear/django-measurement

https://github.com/bitlabstudio/django-units

It might be easier to just copy the currency conversion and make it a unit conversion then users can add the units and conversions themselves.

**Comment by matmair** [comment]
@EvilMustacheTwirl thank you for your input. I would prefer pinet as it is used by a lot of EEs and MEs in academia so the conversions should be right. I do not really have time for this right now so open for an FR.

The currency conversion is provided by an external dependency.

**Comment by SchrodingersGat** [comment]
@matmair I'd love to implement this for https://github.com/inventree/InvenTree/pull/4823

Parameters currently have "units" specified, but they don't really mean anything. It would be great to be able to set real physical units, say "metres" but values could be put in as `mm` or `cm` (and correctly converted for sorting / filtering)

**Comment by matmair** [comment]
Nice!
