### ISSUE TITLE
[BUG] :checkered_flag: Typo in Settings page

### ISSUE THREAD

**Issue by jtrosper** [inventree/InvenTree#4210]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Just a minor thing. There's a typo on the Settings page.

Settings -> Global Settings -> Server Configuration

"Delete **_Noficiations_** | User notifications will be deleted after specified number of days"

### Steps to Reproduce

Settings -> Global Settings -> Server Configuration -> Delete "Noficiations"

### Expected behavior

Delete Notifications

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.2
Django Version: 3.2.16
Commit Hash: 236ca36
Commit Date: 2023-01-04
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by matmair** [comment]
Thank you for the report @jtrosper ! This should be fixed in the next release.

**Comment by bloemp** [comment]
I've created a PR #4213 to close this issue
