### ISSUE TITLE
LDAP Functionality Question - Is it still working?

### ISSUE THREAD

**Issue by compumatter** [inventree/InvenTree#4215]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

This is not a problem so forgive this posting here.  I could not find a more relevant place to ask the question.

LDAP is a requirement for us.  In searching the git issues I found only one other LDAP related post.  That left me wondering if LDAP is still supported / tested / working.  I've just discovered in the docks that there is no built in LDAP but somehow it is implemented here: https://django-auth-ldap.readthedocs.io/en/latest 

Before I go down what appears to be a deep dive, I just wanted to try and get some confirmation it's functional.   

Thanks.   Jay / CompuMatter

### Steps to Reproduce

This is a request for information on LDAP functionality

**Comment by User220419** [comment]
@compumatter Did you manage to get LDAP functional? I'm quite confused how it is configured.

**Comment by compumatter** [comment]
Very regrettably no.   There is no native support for LDAP and as best I can tell there seems to be no interest in pursuing it.  It is very unfortunate as I really love the software but whatever our solution it must have LDAP support.

I did not go down the django route.  It seemed convoluted to me and the docs are extremely old relating to it.

**Comment by User220419** [comment]
That is disappointing to hear. I also require LDAP. I thought I would try keycloak to gain LDAP authentication but once I uncomment the keycloak settings in inventree config, inventree no longer starts so that option is not looking promising either. Thank you for the reply.

**Comment by matmair** [comment]
@compumatter I work in a 10k+ user IT environment completely based on MSFT as an IT Architect/Sysadmin. LDAP is a very old protocol that is breaking easily once you put it through a modern multilayer or zero trust network. Microsoft has been providing server roles for SAML/oAuth on-prem in various forms since 2003. They label LDAP as legacy in their docs.
I find it hard to agree with any of your technical points as a certified MS Identity with Win Server and Azure Identity and Access tech. Using ChatGPT for security relevant questions is frankly shocking.

If built-in LDAP is a hard requirement InvenTree is not the right software for you at this point in time. If you want a turnkey solution with LDAP I recommend one of our paid competitors.

**Comment by compumatter** [comment]
Create a new issue requesting it Maybe if they get enough feedback they'll think differently Sincerely,JayJay LeporeCompuMatterOffice: 360 299 2428Cell: 360 202 ***@***.*** you are satisfied with your service, please consider providing us a social media review at https://compumatter.com/reviews...If you are not, please let me know so I can make it betterOn Jun 6, 2023, at 2:40 AM, Matthias Mair ***@***.***> wrote:﻿
@compumatter I work in a 10k+ user IT environment completely based on MSFT as an IT Architect/Sysadmin. LDAP is a very old protocol that is breaking easily once you put it through a modern multilayer or zero trust network. Microsoft has been providing server roles for SAML/oAuth on-prem in various forms since 2003. They label LDAP as legacy in their docs.
I find it hard to agree with any of your technical points as a certified MS Identity with Win Server and Azure Identity and Access tech. Using ChatGPT for security relevant questions is frankly shocking.
If built-in LDAP is a hard requirement InvenTree is not the right software for you at this point in time. If you want a turnkey solution with LDAP I recommend one of our paid competitors.
