### ISSUE TITLE
[BUG] :checkered_flag: Quick Installer: `INVENTREE_DB_PORT` errors

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#4222]
### Describe the bug

Quick install results in multiple `ERROR Invalid number for INVENTREE_DB_PORT: sampleport` messages.

### Steps to Reproduce

1. Run command from https://docs.inventree.org/en/latest/start/installer/#quick-script
2. Observe output
3. Multiple instance of `ERROR Invalid number for INVENTREE_DB_PORT: sampleport` are showing
4. Server runs fine nonetheless

### Expected behavior

If error is false positive, it shouldn't show in the logs.

### Deployment Method

- [ ] Docker
- [ ] Bare metal
- [X] Ubuntu Package

### Version Information

``` shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

### Relevant log output
[inventree_installer.log](https://github.com/inventree/InvenTree/files/10436684/inventree_installer.log)

**Comment by matmair** [comment]
@eeintech I added a small fix. Basically, the default raised an error so I changed it to a number.

**Comment by eeintech** [comment]
Sounds good, thanks!
