### ISSUE TITLE
[BUG] :checkered_flag: Install Script. "wget: unable to resolve host address ‘gnu’"

### ISSUE THREAD

**Issue by streeriver** [inventree/InvenTree#4236]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

When running quick install script I get error 
`--2023-01-21 03:19:37--  http://gnu/linux/11.repo`
`Resolving gnu (gnu)... failed: Name or service not known.`
`wget: unable to resolve host address ‘gnu’`

### Steps to Reproduce

Deployed Debian 11 x64 droplet on Digital Ocean. 
Did `sudo apt-get update` and `sudo apt-get upgrade`.
Then ran the [quick install script](https://docs.inventree.org/en/stable/start/intro/) at the top of the page.
`wget -Nq https://raw.githubusercontent.com/InvenTree/InvenTree/master/contrib/install.sh && bash install.sh` 

Installer gets part way through then cannot resolve "gnu".

![Screenshot 2023-01-20 223506](https://user-images.githubusercontent.com/123222595/213841809-fd59a2c2-a765-423c-a8ea-d5093441faca.png)

**Comment by matmair** [comment]
Hi there @streeriver; I will try to reproduce, will take a bit.

**Comment by matmair** [comment]
@streeriver could you please run 
```bash
wget -Nq https://raw.githubusercontent.com/InvenTree/InvenTree/master/contrib/install.sh && bash install.sh --dry-run
```

**Comment by matmair** [comment]
Ok this is a confirmed bug - I can confirm on DO; fix incoming shortly

**Comment by matmair** [comment]
@streeriver I have a fix available in my fork till we can merge this - if you want.

```bash
wget -Nq https://raw.githubusercontent.com/matmair/InvenTree/matmair/issue4236/contrib/install.sh && bash install.sh
```

**Comment by streeriver** [comment]
Thank you, that worked.
