### ISSUE TITLE
[FR] Fast inventory transaction screen

### ISSUE THREAD

**Issue by kmudlemmon** [inventree/InvenTree#4238]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Ths shop I work in has R&D and regular production happening at the same time pulling from the same inventory area. As such, we have guys coming up to the stock area grabbing things all the time, and occasionally returning parts. Right now our inventory manager has a signout sheet and and excel sheet, which he updates at the end of the day usually. He then goes to each item and removes stock, a time consuming and slow process.

### Suggested solution

A multiple stock item transaction input screen, which lets the user select/search for a Stock Item , Add or Remove, quantity, and stock transaction notes. 

### Describe alternatives you've considered

The app works quite well in this respect when Stock Item barcodes are available, but I think there should be a fast way to do this natively. 

### Examples of other systems

I am not aware of any other systems with a feature like this, however I have implemented this screen in an SAP instance a few years ago.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
Hi there @kmudlemmon 
Most devs are engineers (electrical or mechanical that is) and it might show in a few UI parts. Odoo has the option for a big screen to adjust stock, it is a bit hidden though.

You could submit a PR here to add that or use a plugin to add that screen (use a [NavigationMixin](https://docs.inventree.org/en/latest/extend/plugins/navigation/) to add a link in the navigation and the [UrlMixin](https://docs.inventree.org/en/latest/extend/plugins/urls/) to add the screen itself).
