### ISSUE TITLE
[BUG] :checkered_flag: Plugin scheduled tasks: Schedule not updated

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#4239]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

The scheduling time of a task is not updated after change in the source code. 

### Steps to Reproduce

I enabled the scheduled tasks plugin from samples 
I did some slight modification to the code:
```python

def print_hello():
    now = datetime.now()
    print(now, ": Hello")  # pragma: no cover


def print_world():
    now = datetime.now()
    print(now,": World")  # pragma: no cover

class ScheduledTaskPlugin(ScheduleMixin, SettingsMixin, InvenTreePlugin):

    NAME = "ScheduledTasksPlugin"
    SLUG = "schedule"
    TITLE = "Scheduled Tasks"

    SCHEDULED_TASKS = {
          'hello': {
            'func': 'plugin.samples.integration.scheduled_task.print_hello',
            'schedule': 'I',
            'minutes': 5,
        },
        'world': {
            'func': 'plugin.samples.integration.scheduled_task.print_world',
            'schedule': 'H',
        },
    }
```
Here is what I get from the log after sorting a bit.

2023-01-20 22:50 : World
2023-01-20 23:51 : World
2023-01-21 00:50 : World
2023-01-21 01:50 : World
2023-01-21 02:50 : World
2023-01-21 04:51 : World
2023-01-21 05:50 : World
2023-01-21 06:51 : World

2023-01-20 22:50 : Hello
2023-01-20 23:36 : Hello
2023-01-21 00:20 : Hello
2023-01-21 01:05 : Hello
2023-01-21 01:50 : Hello
2023-01-21 02:36 : Hello
2023-01-21 03:20 : Hello

So Hello is executed every 45 minutes instead of five. I took a look at the database and found the 45:

![schedule](https://user-images.githubusercontent.com/10836099/213859688-73452d44-bedc-4049-81d2-f9df3bce615a.png)

The problem seems to be in ../plugin/base/integration/mixins.py
```python
  def register_tasks(self):
        """Register the tasks with the database."""
        try:
            from django_q.models import Schedule

            for key, task in self.scheduled_tasks.items():

                task_name = self.get_task_name(key)

                if Schedule.objects.filter(name=task_name).exists():
                    # Scheduled task already exists - continue!
                    continue  # pragma: no cover

                logger.info(f"Adding scheduled task '{task_name}'")

                func_name = task['func'].strip()

```
As I do not see the log message I think create is not executed because it already exists. Or do I miss something?

Michael

### Expected behavior

I would expect the scheduling times to change when I edit the source of the plugin.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

InvenTree Version 	[0.10.0 dev](https://github.com/inventree/InvenTree/releases)
Development Version
	Commit Hash	4bfc1f742
	Commit Date	2023-01-11

### Relevant log output

```shell
please see above
```

**Comment by matmair** [comment]
Dang, this is probably related to https://github.com/inventree/InvenTree/issues/2726, I will take a look.

**Comment by matmair** [comment]
Thanks for the report @SergeoLacruz

**Comment by matmair** [comment]
@SergeoLacruz how is your plugin integrated? package or just a file in /plugins . And have you reloaded the server after changing the number#ß

**Comment by SergeoLacruz** [comment]
Just file. I just edited /src/InvenTree/plugin/samples/integration/scheduled_task.py to try something. 
Yes I do a server restart but the for loop in /plugin/base/integration/mixins.py exits with continue. 
I can solve this when I disable the plugin in the admin interface and enable it again.

**Comment by matmair** [comment]
Ok I have a working fix with tests now. we basically ignored changes to existing schedules, with the path it updates them.

The activating/deactivating thing works because the schedules of deactivated plugins get deleted.

**Comment by SergeoLacruz** [comment]
Thanks for the help :-)
Will give it a try soon
