### ISSUE TITLE
Usage of Letsecrypt for free SSL Certs

### ISSUE THREAD

**Issue by tognellap** [inventree/InvenTree#4247]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

How do i have to follow the installation of LetsEncrypt to use Free SSL with the installer version of inventree.

My understanding ist that the nginx config file will be overwritten via an update and letsencrypt will use it to reference the certs in that file.

### Steps to Reproduce

I tried to follow the the tutorial below:
https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/

**Comment by matmair** [comment]
My suggestion would be to use an additional config file to handle SSL and possible redirections of all HTTP connections.

**Comment by matmair** [comment]
Closing due to lack of response. Please feel free to reopen if the problem reappears/still persists.
