### ISSUE TITLE
[BUG] Part pricing not showing

### ISSUE THREAD

**Issue by method1020** [inventree/InvenTree#4248]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When purchasing parts with sales orders and receiving them. Or adding pricing info to parts. The pricing information does not show in `Parts` > `Pricing`

More information of steps taken here: https://github.com/inventree/InvenTree/discussions/4232#discussioncomment-4742187

### Steps to Reproduce

1. Perform one of the following:
a. Purchase a part via sales order with pricing information.
b. Manually add pricing information to a part.
2. Check the Parts > Pricing tab.

### Expected behavior

* Pricing information available.
* 'Price range data is not available for this part' is not shown.

![Screenshot 2023-01-23 075841](https://user-images.githubusercontent.com/3278824/214045679-3d9fe32c-c165-4c38-ab29-38ed121f9e7a.jpg)

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0
Django Version: 3.2.16

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: []

**Comment by matmair** [comment]
Hi there @method1020! Thank you for filing the report.
Would you have time to try reproducing this on the [demo instance](inventree.org/demo)?
While you are running the current stable series I still was not able to reproduce this issue on master when creating a new part and going through the motions. Just want to make sure it is not related to instance-specific stuff to make debugging faster.

**Comment by method1020** [comment]
This is a bug in my version I think.

Steps to recreate:

1. Create a part.
2. Add supplier for part
3. Create purchase order for part, including line item for part, with pricing on line item.
4. Receive part. -- **price now shows as a purchased price in the DEMO install, but not in my install.**

**Comment by SchrodingersGat** [comment]
@method1020 thanks for reporting :) The pricing overview data are calculated by the background worker process - you'll need to confirm that the background worker is running:

Under the user dropdown menu (top right corner of the screen) select "system information":

![image](https://user-images.githubusercontent.com/10080325/214772370-a67065f3-2946-430c-9aa1-a530c2192757.png)

Can you please share a screenshot of what you see here?

**Comment by method1020** [comment]
```
Instance Name: InvenTree
Database: sqlite3
Plugin Support: Plugin support enabled
Server Status: Healthy
```

I'll try and figure out how to update everything to v0.9.2

**Comment by SchrodingersGat** [comment]
@method1020 how did you go here? Any updates?

**Comment by method1020** [comment]
No. I ran out of time to mess with it so I exported the data, installed v0.9.2, and imported. It seems to be working as expected now.

I did go from bare metal-scripted install to docker-production install.

Thank you for the support.
