### ISSUE TITLE
[BUG] Default BOM report shows incorrect part.

### ISSUE THREAD

**Issue by method1020** [inventree/InvenTree#4249]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Using the default BOM report generation is showing the wrong parts: I expected this:

![image](https://user-images.githubusercontent.com/3278824/214050481-4af14ec5-a643-4451-a7a6-24568e204f8e.png)

But the report generates this:

![image](https://user-images.githubusercontent.com/3278824/214050648-d2f4b188-b537-4029-8664-887654c32a47.png)

The quantities look correct but the parts are wrong.

### Steps to Reproduce

1. Locate an assembly.
2. Click Bill of Materials.
3. Generate a BOM report in the Bill of Materials section (using the default template).
4. See the result.

### Expected behavior

The BOM report should show the correct parts. It is showing the correct quantities but not the correct parts.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0
Django Version: 3.2.16

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: []

**Comment by matmair** [comment]
Hi there @method1020! Thanks for the report. This seems to be a problem with the default report. I am not an expert in this area myself but I am sure we will find the problem.

@SergeoLacruz do you have any insights on the BOM report or could look at it? You seem to be well acquainted with the structure. Would appreciate any insights.

**Comment by SergeoLacruz** [comment]
Hi,
The default BOM report is here:

https://github.com/inventree/InvenTree/blob/e730b5c24ce88b7b3d72d39903815359b5b66fdb/InvenTree/report/templates/report/inventree_bill_of_materials_report.html#L144-L158

The for loop refers to line.part which constantly refers to the parent. Should be line.sub_part instead. 
That refers to the BOM entry. Please refer to the example here:

https://docs.inventree.org/en/latest/report/bom/

We should correct this in the source. 

Michael

**Comment by matmair** [comment]
Thank you @SergeoLacruz !

**Comment by method1020** [comment]
Just tested with the latest template, works as expected. Thank you!
