### ISSUE TITLE
[FR] Filter 'Allocate Stock to Build'

### ISSUE THREAD

**Issue by method1020** [inventree/InvenTree#4250]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

It is difficult to quickly reference what is missing on a build besides sorting the 'Allocated' column in the Allocate Stock to Build window. (also, consumable items do not sort properly when sorting the 'Allocated' column).

### Suggested solution

It would be a nice feature to have a filter option on the Build Order > Allocate Stock to Build page to allow only showing un-allocated, or partially-allocated parts. It would be a quick reference on what is currently missing on the build.

### Describe alternatives you've considered

Sorting the Allocated column, this does not work properly with consumable parts.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
The core team is currently focusing on other areas but maybe someone else is interested in developing it.

**Comment by SchrodingersGat** [comment]
@method1020 yes this is intended for the next release, as long as someone finds time to implement it!
