### ISSUE TITLE
[FR] Attachments for Companies

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#4252]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I would like to add information about my suppliers, for example their ISO certificates, billing guidelines, etc.

### Suggested solution

The Attachment model, as it is implemented in other places, would be ideal.

### Describe alternatives you've considered

Keeping files on disk ;)

### Examples of other systems

See the following, where it was implemented for Manufacturer parts:

https://github.com/inventree/InvenTree/issues/2314
https://github.com/inventree/InvenTree/pull/2912

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Sounds reasonable @miggland! Adding attachments to a class is pretty simple, as can be seen in the PR.
