### ISSUE TITLE
How can I rename part images

### ISSUE THREAD

**Issue by Tak-MK** [inventree/InvenTree#4256]
Sorry for this quick doubt...

I can see this part of the code --> https://github.com/inventree/InvenTree/blob/master/InvenTree/part/models.py#L306
But I can't find on the UI where I can actually rename part images so it's easier to search for them.

Thanks!

**Comment by matmair** [comment]
Hi there @Tak-MK !
Please use issues for feature requests or bugs and discussions for questions. This format is not well suited for multiple answers etc. and pollutes our task lists.

You can not rename part images in the UI currently.

**Comment by Tak-MK** [comment]
Sorry! I didn't even know "Discussions" was a tab :P
I'll close this then, thanks!
