### ISSUE TITLE
Can't access Assembled item "Bill of Materials"

### ISSUE THREAD

**Issue by Mechmoth** [inventree/InvenTree#4261]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When navigating to "assembled item", the Left Menu containing "Bill of Materials" is missing. I don't see any way to view/edit bill of materials.

This first occurred when updated from previously installed version to latest version 0.9.2. Did I miss a major feature/GUI update?

Inventree was updated with the following steps:
1. docker-compose down
2. docker-compose pull
3. docker-compose run inventree-server invoke update
4. docker-compose up -d

Please see 
1. "View_Parts" - All items in view are assembled items
2. "View_ASM" - No menu on the left to navigate assembled item options

![View_Parts](https://user-images.githubusercontent.com/4116718/214796175-070feda4-bba0-4b2c-87be-0e7f4f04487a.png)
![View_ASM](https://user-images.githubusercontent.com/4116718/214796185-5c752f69-5446-4cef-b03a-9466e626f91a.png)

### Steps to Reproduce

1. Go to "Parts"
2. Go to "Subcategories"
3. Select Sub category containing Assemblies
4. Change view from "Sub Categories" to "Parts" right below "Sub Categories"
5. Select and open any part that indicates that it is an "Assembled Item" with the wrench icon
6. The left menu that should contain "Bill of Materials" does not exist

### Expected behaviour

When opening an assembled item, the menu on the left should appear and have the option to select "Bill of Materials", you should then be able to view and edit the opened assembly.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.2
Django Version: 3.2.16
Commit Hash: 236ca36
Commit Date: 2023-01-04
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
@Mechmoth are you saying that the entire left-hand "sidebar" menu is missing when viewing a Part page?

**Comment by Mechmoth** [comment]
Hi @SchrodingersGat,

That is correct, the entire menu is missing.
You have the correct menu I was referring to as per demo server image.

I had a backup of the entire HDD and booted it up with the older version (haven't checked what version i upgraded from), and the side menu was visible.

So at this stage I can't pinpoint if i have done something wrong, or it's only when upgrading from a specific version. I have updated to the latest version at least 10 times by now by following the documents, so it's not like it's completely new to me.

Thanks for your reply.

**Comment by SchrodingersGat** [comment]
@Mechmoth ok please open the developer console in your browser and check if there are any run-time javascript errors which are breaking front-end rendering?

**Comment by matmair** [comment]
@Mechmoth have you refreshed your browser cache since updating? It might be a javascript issue.

**Comment by Mechmoth** [comment]
> 

Hi @SchrodingersGat  & @matmair , the latest version HDD is back, I've cleared browser cache, cookies etc. All seems to work now. Thank you for your help, and apologies for the false concern. I'll have to manually clean Chrome regularly from now on.

Thanks for all the great work from the InvenTree team.

**Comment by Mechmoth** [comment]
If you have similar issues. Clear browser cache as recommended above, also test on different browser or PC.
