### ISSUE TITLE
Docker compose update to latest failed. 

### ISSUE THREAD

**Issue by DaveDavenport** [inventree/InvenTree#4268]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

After update inventree does not come back up.
I am using the docker files provided in this repository.

I am on the `stable` tag.

When looking at logs, it will loop over and over again.  Resulting in error:
inventree-worker  | django.db.utils.ProgrammingError: relation "part_partpricing" does not exist
inventree-worker  | LINE 1: SELECT COUNT(*) AS "__count" FROM "part_partpricing" WHERE "...

the web interface gives a bad-gateway (502) error.

### Steps to Reproduce

pull latest stable version.

*  docker-compose pull
*  docker-compose stop
*  docker-compose up --force-recreate --build -d

### Expected behaviour

Inventree getting back up and running.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

I cannot access this information anymore as it does not come up.
e759a6109d8e   inventree/inventree:stable   
        "Id": "e759a6109d8e67134895d3f2a55e7540b4a0ce9aa66365e84cf9871bf898f4d5",
"Image": "sha256:e005980cd4fcfa5376f631055bb364e541ca4de92b0f81ddcd1f103d33013bf4",
53a5c3834b12   nginx:stable                              
        "Id": "53a5c3834b12db1ff22cc0056cea43b2d7e74d08f26527b76d244a820a6efa42",
        "Image": "sha256:064bc46e6ff977b0df42de7d2c5a5fd98e3f584347436723396e76291dc6ed35",

4b5941f56988   inventree/inventree:stable
        "Id": "4b5941f569884c0872ca6a71cff9dc196080f310a5d6e475bac889a3d960b6a4",
        "Image": "sha256:e005980cd4fcfa5376f631055bb364e541ca4de92b0f81ddcd1f103d33013bf4",

I am not sure how to get clear version from the container? 

### Relevant log output

```shell
inventree-worker  |                                           ^
inventree-worker  |
inventree-worker  |
inventree-worker  | The above exception was the direct cause of the following exception:
inventree-worker  |
inventree-worker  | Traceback (most recent call last):
inventree-worker  |   File "/home/inventree/InvenTree/manage.py", line 23, in <module>
inventree-worker  |     execute_from_command_line(sys.argv)
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
inventree-worker  |     utility.execute()
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
inventree-worker  |     django.setup()
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
inventree-worker  |     apps.populate(settings.INSTALLED_APPS)
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
inventree-worker  |     app_config.ready()
inventree-worker  |   File "/home/inventree/InvenTree/part/apps.py", line 21, in ready
inventree-worker  |     self.reset_part_pricing_flags()
inventree-worker  |   File "/home/inventree/InvenTree/part/apps.py", line 55, in reset_part_pricing_flags
inventree-worker  |     if items.count() > 0:
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 412, in count
inventree-worker  |     return self.query.get_count(using=self.db)
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 528, in get_count
inventree-worker  |     number = obj.get_aggregation(using, ['__count'])['__count']
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 513, in get_aggregation
inventree-worker  |     result = compiler.execute_sql(SINGLE)
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
inventree-worker  |     cursor.execute(sql, params)
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
inventree-worker  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
inventree-worker  |     return executor(sql, params, many, context)
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
inventree-worker  |     return self.cursor.execute(sql, params)
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
inventree-worker  |     raise dj_exc_value.with_traceback(traceback) from exc_value
inventree-worker  |   File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
inventree-worker  |     return self.cursor.execute(sql, params)
inventree-worker  | django.db.utils.ProgrammingError: relation "part_partpricing" does not exist
inventree-worker  | LINE 1: SELECT COUNT(*) AS "__count" FROM "part_partpricing" WHERE "...
inventree-worker  |                                           ^
inventree-worker  |
inventree-worker  | Loading config file : /home/inventree/data/config.yaml
inventree-worker  | InvenTree translation coverage: 22%
inventree-worker  | Waiting for database...
```

**Comment by DaveDavenport** [comment]
[total_logs.txt](https://github.com/inventree/InvenTree/files/10518864/total_logs.txt)
More logs.

**Comment by SchrodingersGat** [comment]
@DaveDavenport looks like you are missing a critical step:

- [x] docker-compose pull
- [x] docker-compose stop
- [ ] **docker-compose run inventree-server invoke update**
- [x] docker-compose up -d

[see more here](https://docs.inventree.org/en/latest/faq/#errors-during-inventree-update) 

Please try this and LMK if it then works for you :)

**Comment by DaveDavenport** [comment]
Yes that worked..   I completely missed that on documentation (looking now I directly see it , not sure how I missed it before).
