### ISSUE TITLE
API Company.create() does not accept remote_image even though listed in the API

### ISSUE THREAD

**Issue by ulikoehler** [inventree/InvenTree#4273]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The InvenTree 0.9.2 /api-doc page lists `remote_image` as one of the parameters of the Company create API.

![image](https://user-images.githubusercontent.com/34971/215278824-82dbfc19-aca6-493b-a0a8-51209835c70b.png)

However, when I try to create a company with following data:
```
{'name': 'DigiKey', 'website': 'https://www.digikey.de/', 'remote_image': 'https://logodix.com/logo/1667872.jpg', 'description': '', 'is_manufacturer': False, 'is_supplier': True, 'is_customer': False, 'currency': 'EUR'}
```
I receive the following error response:
```
requests.exceptions.HTTPError: {'detail': 'Error occurred during API request', 'url': 'https://inventree-test.mydomain.com/api/company/', 'method': 'POST', 'status_code': 500, 'body': '{"error":"TypeError","error_class":"<class \'TypeError\'>","detail":"Error details can be found in the admin panel","path":"/api/company/","status_code":500}', 'headers': {'AUTHORIZATION': 'Token 6daae3817756e9c1a3603b14d9582e61f50db388'}, 'params': {'format': 'json'}, 'data': {'name': 'DigiKey', 'website': 'https://www.digikey.de/', 'remote_image': 'https://logodix.com/logo/1667872.jpg', 'description': '', 'is_manufacturer': False, 'is_supplier': True, 'is_customer': False, 'currency': 'EUR'}}
```

with the following stack trace in the admin panel:
```
Traceback (most recent call last):

File "/root/.local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/root/.local/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
return self.create(request, *args, **kwargs)

File "/home/inventree/InvenTree/InvenTree/mixins.py", line 21, in create
serializer.is_valid(raise_exception=True)

File "/root/.local/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
self._validated_data = self.run_validation(self.initial_data)

File "/home/inventree/InvenTree/InvenTree/serializers.py", line 181, in run_validation
instance = self.Meta.model(**data)

File "/root/.local/lib/python3.9/site-packages/django/db/models/base.py", line 503, in __init__
raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))

TypeError: Company() got an unexpected keyword argument 'remote_image'
```

Therefore, either the documentation is not generated correctly (i.e. `remote_image` should not actually be a parameter for the Company.create() function or the create() code does not process remote_image correctly.

### Steps to Reproduce

Run the following Python script with correct credentials:

```python
#!/usr/bin/env python3
from inventree.api import InvenTreeAPI
from inventree.company import Company

api = InvenTreeAPI("https://inventree-test.mydomain.com", username="admin", password="abc123abc")

Company.create(api, {"name": "DigiKey",
                     "currency": "EUR",
                     "remote_image": "https://logodix.com/logo/1667872.jpg"})
```

### Expected behaviour

A company with the given image URL is created.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.9.2

**Comment by SchrodingersGat** [comment]
@ulikoehler this is a (recently) known issue which has been fixed in master: https://github.com/inventree/InvenTree/pull/4264

Ref: https://github.com/inventree/inventree-python/issues/162

In stable, there is a bug where `remote_image` throws an error when creating a new part or company. You can work around this by first creating the company (via the API) and then patching `remote_image` against the newly created company
