### ISSUE TITLE
[BUG/ UI Improvement] New Part form: Input fields for supplier/manufacturer part can be filled although toggle is OFF

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4279]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When adding a new part, the form area "Supplier Options" is visible and can be filled out although the toggle switch "Create initial supplier data for this part" is not active.
In case I fail to activate the toggle, the data provided in that section of the form is ignored and no supplier parts or manufacturer parts are created - which is hard to catch, especially when adding multiple parts in a row

### Steps to Reproduce

1. Go to "Parts"
2. open "New Part" modal
3. find the "Supplier Options" section at the bottom of the form

### Expected behaviour

in order to avoid that mistake I would propose to activate/deactivate the four input fields for supplier/manufacturer part based on the toggle switch - or, even better, actually show/hide the input fields based on the toggle.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: 26f71b3
Commit Date: 2023-01-26
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: [{'name': 'IPNAutoGenerator', 'slug': 'ipnautogenerator', 'version': None}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.6.0'}]

**Comment by SchrodingersGat** [comment]
Related: https://github.com/inventree/InvenTree/issues/4266

**Comment by SchrodingersGat** [comment]
@simonkuehling thanks for adding this report - I'm currently working on a fix for #4266 so I'll ensure this gets fixed also.

**Comment by simonkuehling** [comment]
Your speed and dedication to this project are mind boggling :-) awesome!
