### ISSUE TITLE
After creating new part parameter, it cannot be found in list of parameters until page is refreshed

### ISSUE THREAD

**Issue by MR-DOS** [inventree/InvenTree#4283]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

After creating new part parameter, it cannot be found in list of parameters until page is refreshed.

### Steps to Reproduce

1. In Settings-Parts, create a new parameter.
2. Try to use the search bar to find that parameter.
3. Nothing is found.
4. Refresh the page.
5. Repeat step 2.
6. Parameter is found.

### Expected behaviour

The page should update its list of parameters when a parameter is created.

My usage - I usually have 2 tabs open, one to work with Inventree and a second to create new parameter templates when I find some parameter not existing yet. (making electronics database, now at 458 unique parameters)

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.9.2

**Comment by SchrodingersGat** [comment]
@MR-DOS do you mean this table here?

![image](https://user-images.githubusercontent.com/10080325/216168933-b78dedd7-5d23-465e-9836-a97dbce79927.png)

It appears to auto-refresh for me. Perhaps there's a javascript error message in your developer console if you could check there?

**Comment by MR-DOS** [comment]
How do I do that? :-D

**Comment by SchrodingersGat** [comment]
@MR-DOS I can't seem to reproduce that - I can create a new parameter and immediately search for it.

To look in the developer console on your browser - [read these instructions](https://balsamiq.com/support/faqs/browserconsole/)

Perhaps there's an error which is popping up here?

**Comment by MR-DOS** [comment]
Strange. I can't replicate it now, but it used to be a persistent and reproducible error.
Though I have started using the Redis profile in the meantime (if that could change the behaviour).

So, maybe I should close the issue now.
