### ISSUE TITLE
Docker builds are failling

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4287]
Docker builds have suddenly started to fail

- may be due to a recent update to [pip-tools 6.12.2](https://pypi.org/project/pip-tools/)
- may be due to a recent update to [pre-commit](https://pypi.org/project/pre-commit/)

The following line in `docker.yaml` workflow fails:

```
docker-compose run inventree-dev-server invoke setup-dev
```

Failing build: https://github.com/inventree/InvenTree/actions/runs/4059276631/jobs/6987650846

**Comment by SchrodingersGat** [comment]
@matmair any thoughts on this one?

**Comment by matmair** [comment]
@SchrodingersGat I have this happening in multiple repos right now; might be something with pre-commit - I got some update recommendations from dependency management. Will take a look.
