### ISSUE TITLE
Fork PK2InvenTree and move into org

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4288]
https://github.com/rgilham/PK2InvenTree seems to be unmaintained and broken; I think an importer from PartKeepr is quite important - should we fork and move it into the org @SchrodingersGat ?

**Comment by SchrodingersGat** [comment]
@matmair good question, I've reached out to @rgilham to see if he is still interested in maintaining it

**Comment by rgilham** [comment]
Hi guys - sorry I am intending to update just time issues. I will be looking into it soon.

**Comment by SchrodingersGat** [comment]
@rgilham great :) Please loop us in if you need, there's been a *ton* of changes to InvenTree and we'd be more than happy to help you out where we can

**Comment by matmair** [comment]
@rgilham no need to be sorry, you do not owe anyone ongoing maintenance of your code. If you need help or advice, feel free to ping me.

I think we can close this issue.

**Comment by fenugrec** [comment]
Bump; I like the suggestion of adopting this plugin. If the original author eventually does find time to work on it again he can be simply added as a member for that one repo.
I was just about ready to close down my PK instance and migrate to inventree with this, what bad timing !

**Comment by matmair** [comment]
@fenugrec there is no license file on that project as far as I can see so it can not be forked without being a constant ownership risk.

**Comment by fenugrec** [comment]
Can we reopen just to keep track of this ?

**Comment by frsteinb** [comment]
We are looking for a replacement for our old PartKeepr at our institute at TU Braunschweig. To get somewhat more familiar with InvenTree, I wanted to use PK2InvenTree – with obviously no luck. Since the Python APIs of both sides look quite easy to use, I started my own conversion tool. Feel free to take a look, but please do not expect any support.

https://gitlab.ibr.cs.tu-bs.de/steinb/partkeepr-to-inventree

**Comment by dersch81** [comment]
> We are looking for a replacement for our old PartKeepr at our institute at TU Braunschweig. To get somewhat more familiar with InvenTree, I wanted to use PK2InvenTree – with obviously no luck. Since the Python APIs of both sides look quite easy to use, I started my own conversion tool. Feel free to take a look, but please do not expect any support.
> 
> https://gitlab.ibr.cs.tu-bs.de/steinb/partkeepr-to-inventree

Thanks a lot for this!
