### ISSUE TITLE
[BUG] Image is not copied when duplicating a Part

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4302]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When duplicating a Part, the image does not get copied although the toggle is set.
The bug can be verified on the demo server as well.

### Steps to Reproduce

1. Open a Part view that has an image
2. click `duplicate Part`, check that `Copy Image` is selected
3. `Submit`

### Expected behaviour

Image should be copied

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: ce3dabe
Commit Date: 2023-02-03
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'IPNAutoGenerator', 'slug': 'ipnautogenerator', 'version': None}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.6.0'}]

**Comment by simonkuehling** [comment]
(I guess it is related to the recent changes from 4f029d4d81da610ffc766172ba4adebff8eb5830 ?)

**Comment by matmair** [comment]
Can reproduce on demo; not fully sure why though, the changes look fine from a cursory look

**Comment by simonkuehling** [comment]
@matmair For some reason I cannot reproduce this on the demo server anymore right now... I'm confused - on my local setup it still does not copy the image...

**Comment by matmair** [comment]
@simonkuehling are you on latest?

**Comment by simonkuehling** [comment]
> @simonkuehling are you on latest?

I am on latest (ce3dabedb677b44375b695934cdda452a8a0bc6c), yes.

**Comment by SchrodingersGat** [comment]
@simonkuehling looks fine on the demo server (as you say). Have you refreshed the page and restarted the server? Could be a javascript caching issue?

**Comment by matmair** [comment]
Now I can't either after ulcerating the cache. I do not think we changed anything on the frontend in that code in the last bit - interesting.
Can we close @simonkuehling ?

**Comment by simonkuehling** [comment]
Well, with a clean cache and another server restart it magically works again on my installation as well now… i guess I‘ll just take it and close…
Thanks for your time!

**Comment by matmair** [comment]
I am actually working on removing that need. With unique names for each version of JS files.
