### ISSUE TITLE
[Roadmap] background worker process

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4304]
We have been using [django-q](https://github.com/Koed00/django-q) for ages, but the project has not received any updates in a few years.

There are also some shortcomings - in particular the tasks seem to run on multiple workers - see https://github.com/inventree/InvenTree/issues/4290

Perhaps it is time to migrate to something like [celery](https://github.com/celery/celery):

- Better support (project is active)
- More comprehensive feature set
- Future proofing

I have not yet done the required reading to determine how difficult this might be, or if it would require using redis, etc.

**Comment by matmair** [comment]
@SchrodingersGat the thing I like about django q is that it does not need a broker to run. To my knowledge, we will need redis to use celery. Thus making testing and small bare metal setups harder.

**Comment by SchrodingersGat** [comment]
Indeed. I do like the simplicity of the current solution. Before switching I'd like to understand if there is a way around the current issues. The biggest one being the double execution of tasks

**Comment by SchrodingersGat** [comment]
Ref: https://github.com/Koed00/django-q/issues/633
Ref: https://github.com/Koed00/django-q/issues/577
Ref: https://github.com/Koed00/django-q/issues/566

**Comment by matmair** [comment]
@SchrodingersGat can we close this now as #5167 is merged

**Comment by SchrodingersGat** [comment]
Yes, I think we can. Sticking with django-q is more attractive now that we've found an active fork
