### ISSUE TITLE
Multi-Part Forms

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#431]
Currently the code for multi-part forms is terrible. It needs to be cleaned up and use an existing tool like django-form-wizards.

* BOM upload
* Order parts

In each of these forms, large amounts of form data need to be passed between the client and server multiple times.

**Comment by eeintech** [comment]
I was thinking... what about mixing it with [django-tables2](https://github.com/jieter/django-tables2)?
It might help to have a generic class and template to render tabular data, and that data to be passed along in the multi-step forms, generated with the [django-formtools](https://github.com/jazzband/django-formtools) package.

**Comment by SchrodingersGat** [comment]
Interesting, was not aware of this plugin!

**Comment by matmair** [comment]
@SchrodingersGat is this still active?

**Comment by SchrodingersGat** [comment]
Probably not worth keeping it open, we've  gone in a different direction for multi part forms now
