### ISSUE TITLE
[FR] Pack sizes not considered when adding stock manually

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#4310]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

See https://github.com/inventree/InvenTree/discussions/4282

When adding stock manually (not through PO), the pack size of a supplier part is not taken into account.

### Suggested solution

Pack-size should be taken into account

### Describe alternatives you've considered

Minimum: clarify which unit is used

### Do you want to develop this?

- [x] I want to develop this.

**Comment by miggland** [comment]
Fair point - I agree that the case you described is likely to occur.

Being able to choose which to use sounds like a perfect solution (but also more complicated to implement..)

Maybe a checkbox under/next to Quantity, to multiply it by pack size, or not, would solve this (and would also be compatible with the API, if sent as a flag)?

**Comment by matmair** [comment]
still relevant

**Comment by miggland** [comment]
Please assign this to me.

**Comment by miggland** [comment]
This was closed by https://github.com/inventree/InvenTree/pull/4741.
