### ISSUE TITLE
[BUG] price calculation modal uses price per packing-unit, not single-piece price

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4312]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When adding supplier parts with packing-units of more than 1 (for example length of 1000mm of steel tube), the single-unit price is correctly calculated in the `Pricing` tab. When using the price calculator modal (through the `$` icon in the top right), the prices for the full packing units are shown as price range - and calculations of multiples are way off through this, of course...

### Steps to Reproduce

Example part with pricing history:
![Bildschirmfoto vom 2023-02-07 11-08-45](https://user-images.githubusercontent.com/296454/217216687-3d8c59b9-2204-48a7-8616-21a20bf86f6c.png)

Supplier Parts for this Part:
![Bildschirmfoto vom 2023-02-07 11-09-29](https://user-images.githubusercontent.com/296454/217216882-2ae47e2f-335a-487e-8f82-6cf0c8e34fc1.png)

Pricing calculator for quantity of 1:
![Bildschirmfoto vom 2023-02-07 11-10-07](https://user-images.githubusercontent.com/296454/217217005-28340cdc-5d3b-4b99-a114-8822ac62f876.png)

Pricing calculator for multiple quantities:
![Bildschirmfoto vom 2023-02-07 11-10-18](https://user-images.githubusercontent.com/296454/217217089-639e873f-0ff5-4925-87a8-c77427dceb41.png)

### Expected behaviour

use price per single unit (in my example: per `mm`) in the calculator modal

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: ce3dabe
Commit Date: 2023-02-03
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'IPNAutoGenerator', 'slug': 'ipnautogenerator', 'version': None}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.6.0'}]

**Comment by SchrodingersGat** [comment]
@simonkuehling thanks for reporting. The pricing modal has a *lot* of other issues too and needs significant work.

**Comment by derekwolfson** [comment]
This would benefit me a ton too -- especially for raw materials (like this) and hardware.
