### ISSUE TITLE
Uncaught ReferenceError: createPart is not defined

### ISSUE THREAD

**Issue by method1020** [inventree/InvenTree#4329]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Attempting to create a new part is met with the following on console:

```
Uncaught ReferenceError: createPart is not defined
    <anonymous> http://xxx.xxx.xxx.xxx:1337/part/category/79/:925
    jQuery 9
        dispatch
        handle
        add
        De
        each
        each
        De
        on
        t
    <anonymous> http://xxx.xxx.xxx.xxx:1337/part/category/79/:924
    jQuery 13
        l
        c
        setTimeout handler*Deferred/then/a/<
        u
        fireWith
        fire
        u
        fireWith
        ready
        _
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
```

### Steps to Reproduce

Upgraded production docker from 0.9.2 to 0.10.0 using instructions in Inventree documentation.

Went to create new part in portal. Nothing happens when clicking the button.

Turned on Firefox console and saw the messages.

### Expected behaviour

Create new part.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0
Django Version: 3.2.16
Commit Hash: 0ffe786
Commit Date: 2023-02-07
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment]
@method1020 sounds like this - https://docs.inventree.org/en/latest/faq/#feature-x-is-not-visible-after-update

**Comment by SchrodingersGat** [comment]
@method1020 I am assuming that it was simply related to javascript cache - please re-open if still causing you issues.
