### ISSUE TITLE
Variants tab stopped showing up for Template Parts in latest update

### ISSUE THREAD

**Issue by diminDDL** [inventree/InvenTree#4332]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Before updating I was using the variants panel extensively when in a template part. After the update it appears to be gone.
![image](https://user-images.githubusercontent.com/25513498/218212836-94b389a8-a218-4cf3-b20f-af12cd815b50.png)

### Steps to Reproduce

1. Go to Part
2. Click template part.
3. Side panel with variants, stock and so on is gone.

### Expected behaviour

The panel would be still there or moved to another obvious location.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

It also appears that the `About InvenTree` button does not work when inside a part menu (like in the one shown in the image above.) But I managed to copy it from another menu.
```
# Version Information:
InvenTree-Version: 0.10.0
Django Version: 3.2.16
Commit Hash: 0ffe786
Commit Date: 07-02-2023
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False
```

### Relevant log output

```shell
During install I saw

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
``` 
A few times, no idea if this is relevant.
```

**Comment by matmair** [comment]
@diminDDL have you followed this: https://docs.inventree.org/en/latest/faq/#feature-x-is-not-visible-after-update ?

**Comment by diminDDL** [comment]
Yes it worked, thanks, perhaps there could be some sort of notification after an update because this was a bit obscure.
