### ISSUE TITLE
Reduce frequency of notify_low_stock_if_required task

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4337]
Currently called whenever a Part instance is saved, which can eat up a lot of CPU through database hits.

Is not necessary to call this with such high frequency. Task could run more intelligently, or be moved to a "scheduled" task.

**Comment by matmair** [comment]
@SchrodingersGat I think the feature only makes sense if you get feedback within a few minutes. Can we maybe optimize the task to reduce the database hits?

**Comment by SchrodingersGat** [comment]
Good point, we can probably look into doing it that way

**Comment by SchrodingersGat** [comment]
Closing, no interest in addressing this currently
