### ISSUE TITLE
[FR] Home assistant Add-on

### ISSUE THREAD

**Issue by DjordjeMandic** [inventree/InvenTree#4347]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

There is no Add-on for home assistant like for Grocy

### Suggested solution

Create HA Add-on which installs InvenTree

### Describe alternatives you've considered

Manual Docker install on Hass.io

### Examples of other systems

[Grocy (https://github.com/hassio-addons/addon-grocy)](https://github.com/hassio-addons/addon-grocy)

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Hi there @DjordjeMandic - we already provide [docker images](https://docs.inventree.org/en/stable/start/docker/) and install instructions. I do not really see value in building another set of images. We certainly welcome PRs but not sure if we will add another build method thats needs maintaining.
