### ISSUE TITLE
[BUG] StockItem filter "include sublocations = false" not getting applied in top-most StockLocation

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4348]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The filter parameter `include sublocations` seems to not work right now in the `/stock/` StockItems list when listing stock in the top-most StockLocation

### Steps to Reproduce

Annotated screenshot from the demo server:

![Bildschirmfoto vom 2023-02-16 10-50-38](https://user-images.githubusercontent.com/296454/219339180-d9130dd5-7450-4f8e-96f0-f354e245cddb.png)

### Expected behaviour

The filter should be applied like it is working in sublocations.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.16
Commit Hash: 45d50fc
Commit Date: 2023-02-16
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
@simonkuehling thanks for reporting this, can confirm that the bug exists
