### ISSUE TITLE
[FR] Duplicate part modal: clear IPN field if PART_ALLOW_DUPLICATE_IPN = False

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4359]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When `PART_ALLOW_DUPLICATE_IPN = False` option is set for the server, the `Duplicate Part` modal form should open with an empty `IPN` field instead of copying the original over.

### Suggested solution

Check for `PART_ALLOW_DUPLICATE_IPN = False` when generating the form data.

This should only need an additional API call to `/api/settings/global/PART_ALLOW_DUPLICATE_IPN/` in `/InvenTree/templates/js/translated/part.js` to get the configuration value and issue a `fields.ipn = ''` if needed, right?

### Describe alternatives you've considered

-

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
@simonkuehling sounds fine. There is the array `global_settings` in settings.js with all settings values,

**Comment by SchrodingersGat** [comment]
Yep all the settings are already loaded statically into a javascript file as @matmair says :)

**Comment by simonkuehling** [comment]
sweet, a quick fix is in via PR https://github.com/inventree/InvenTree/pull/4365
