### ISSUE TITLE
Unable to install plugins from settings page after update to 0.10.0

### ISSUE THREAD

**Issue by janujarerat** [inventree/InvenTree#4360]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hello,

I just updated our InvenTree version to 0.10.0 and it looks like I am now unable to install plugins from the Settings page. Clicking the Install Plugin button results in the following message:

Unhandled Error Code
Error code: 200
URL: /api/plugin/install/?context=true

This is on a production server deployed using docker.

![image](https://user-images.githubusercontent.com/54828174/219803677-4dc308a8-6d72-4b3f-a888-bdebce9d5620.png)

### Steps to Reproduce

Followed documentation to update InvenTree version in a docker installation:

- Stop running containers with `docker compose down`
- Pull latest InvenTree docker image with `docker compose pull`
- Update database with `docker compose run inventree-server invoke update`
- Restart containers with `docker compose up -d`

In terms of other plugin installations, we have the apprise-inventree plugin installed as well as the built-in plugins InvenTreeBarcode and InvenTreeCoreNotificationsPlugin. This functionality continues to work in both InvenTree versions.

### Expected behaviour

Normally, when clicking the Install Plugin button, a form appears allowing a user to specify a package name or VCS path for the plugin. I brought up our previous InvenTree 0.9.2 installation again and this functionality works. 

![image](https://user-images.githubusercontent.com/54828174/219808383-86eef6f5-f171-4b3d-abc6-e906f91709cb.png)

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.10.0

**Comment by SchrodingersGat** [comment]
@janujarerat looks like an issue with javascript cache: https://docs.inventree.org/en/latest/faq/#feature-x-is-not-visible-after-update

Please do a hard-refresh of the page, and check if it works for you

**Comment by janujarerat** [comment]
@SchrodingersGat This worked, thanks for the help!
