### ISSUE TITLE
Consuming inventory

### ISSUE THREAD

**Issue by amishHammer** [inventree/InvenTree#437]
What is the method to consume stock?  Right now it seems you can only add more stock via a purchase order/build.

**Comment by SchrodingersGat** [comment]
Hi @amishHammer there are currently three ways to reduce / consume stock;

## Build

When a build is completed, any parts that are assigned to that build are removed from stock automatically. e.g. if an assembly needs 10 2K2 resistors and the build is producing 5 units, then 50 units of the 2K2 will be removed from stock.

## Manual Removal

Items can be manually removed from stock from various views (or via the API)

![image](https://user-images.githubusercontent.com/10080325/62587035-7d50d280-b903-11e9-894f-f80e490c0e2b.png)

This reduces the stock by the selected number. A user note must also be added to this transaction.

## Stocktake

Stock can be counted manually, so the total remainder count can be adjusted in this fashion too.

**Comment by SchrodingersGat** [comment]
@amishHammer does this answer your question?
