### ISSUE TITLE
Server upgrade fails if Redis cache enabled in .env file

### ISSUE THREAD

**Issue by MR-DOS** [inventree/InvenTree#4371]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Performing upgrade from 0.9.2 to 0.10.0 fails if Redis is enabled (uncommented) in .env file. It fails because during migration, it tries to access the cache engine but fails since during upgrade, this container is not started normally.
After commenting its relevant lines in .env file, the migration completes succesfully.

### Steps to Reproduce

1. Take data from 0.9.x server
2. Enable Redis cache in .env file
3. Invoke upgrade to 0.10.0
4. Wait for it to fail

### Expected behaviour

During backup, Inventree should ignore that the cache is enabled. Or, it should start its relevant container before the migration.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

Migration from 0.9.2 to 0.10.0, official docker images.

### Relevant log output

```shell
Running InvenTree database migrations...
========================================
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/django_redis/cache.py", line 98, in _get
    return self.client.get(key, default=default, version=version, client=client)
  File "/root/.local/lib/python3.9/site-packages/django_redis/client/default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error -2 connecting to inventree-cache:6379. Name or service not known.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/root/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/inventree/InvenTree/plugin/apps.py", line 45, in ready
    registry.load_plugins()
  File "/home/inventree/InvenTree/plugin/registry.py", line 127, in load_plugins
    self._activate_plugins(full_reload=full_reload)
  File "/home/inventree/InvenTree/plugin/registry.py", line 468, in _activate_plugins
    self.activate_plugin_schedule(plugins)
  File "/home/inventree/InvenTree/plugin/registry.py", line 510, in activate_plugin_schedule
    if settings.PLUGIN_TESTING or InvenTreeSetting.get_setting('ENABLE_PLUGINS_SCHEDULE'):
  File "/home/inventree/InvenTree/common/models.py", line 427, in get_setting
    setting = cls.get_setting_object(key, **kwargs)
  File "/home/inventree/InvenTree/common/models.py", line 365, in get_setting_object
    cached_setting = cache.get(ckey)
  File "/root/.local/lib/python3.9/site-packages/django_redis/cache.py", line 91, in get
    value = self._get(key, default, version, client)
  File "/root/.local/lib/python3.9/site-packages/django_redis/cache.py", line 38, in _decorator
    raise e.__cause__
  File "/root/.local/lib/python3.9/site-packages/django_redis/client/default.py", line 258, in get
    value = client.get(key)
  File "/root/.local/lib/python3.9/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/root/.local/lib/python3.9/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/root/.local/lib/python3.9/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/root/.local/lib/python3.9/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to inventree-cache:6379. Name or service not known.
ERROR: 1
```

**Comment by SchrodingersGat** [comment]
If you made the change to the configuration file, the server expects that there is a redis container also running. I think this is fair to file under "expected behaviour", no?

To make such a change, bare minimum you'd have to pull the containers down, enable the redis container, and spool up the containers again, before running `invoke update`

**Comment by MR-DOS** [comment]
Well, during the "invoke update", it is able to start up server and database containers. Also, it's able to expect presence of cache container. And it also knows the name of the container. But it doesn't start it up, takes a long time to make backups and then fail. (I wonder how it makes the backup of database if it can't connect to Redis...)

From my point of view, it would make sense for Inventree to either start that container as well or to ignore caching completely. I would see the latter possibility as more logical since the server is running in a bare minimum mode required for backup-upgrade-migrate task. During those tasks, it is unlikely for database entries to be accessed repeatedly and massively to require caching or to benefit from using it. 
Or maybe at the start of upgrade, it could immediately try if Redis is there (it took me maybe half an hour of fiddling with starting upgrade under redis profile only to find out profiles don't work in that case).

You are probably expecting a scenario where only the Inventree container is stopped, upgraded and restarted while leaving DB+cache running. That could be a case where multiple services share the DB/cache, but not if Inventree is ran isolated from other services on that machine - in those cases most people just would perform "docker-compose down", edit the .env file for newer version and then "invoke upgrade", thus not having the Redis container running.

I'm not saying that this is some large problem. People enabling Redis probably know why they're doing it and should be able to debug the issue, but it's still kind of impractical and could jumpscare someone not expecting a stack trace during upgrade.

**Comment by matmair** [comment]
The current flow is fine in my opinion.

**Comment by SchrodingersGat** [comment]
Agreed with @matmair I think this is very much not a "standard" update procedure. And I don't see a clean way to accommodate this.

**Comment by MR-DOS** [comment]
@SchrodingersGat 
But there is still a question - how comes Inventree can make a backup of the SQL database but not run the migrations on it? Doesn't the backup also need access to the databse, thus should also reuire Redis present? (I'm just asking as someone who doesn't understand this stuff very much)

**Comment by SchrodingersGat** [comment]
There may be some subtle differences in how the backup function accesses the database - we don't do this directly, we use the django-dbbackup library

**Comment by MR-DOS** [comment]
So if there are some uncommitted changes to DB pending in Redis, django-dbbackup will ignore these and make a backup of database which is not up-to-date?

**Comment by SchrodingersGat** [comment]
Yes. and this is desirable in case the update procedure itself contains a bug. A snapshot of the database is taken *before* the update so there's a rollback point.

**Comment by matmair** [comment]
@MR-DOS Redis is only used as a read cache.

**Comment by MR-DOS** [comment]
@matmair Thanks, if it's read only, then I'm sorry for bothering you. I was just afraid there could be some data inconsistency during backup.

**Comment by matmair** [comment]
No problem, you could use redis for write-caching/pooling too - we just do not use it. The application becomes very hard to debug once you have that feature enabled and makes it hard for newbies to find errors as you need intricate knowledge of the call stack to diagnose it at that point.
