### ISSUE TITLE
[FR] Improve wording for "Inherited" option of BOM Items

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4376]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When using variants of parts with inherited BOM items, the current wording `Inherited` is confusing if it is active or passive in its meaning. Throughout the BOMs of template parts and variants is is always used to designate if a part `gets inherited` down the line, not that is `was inherited`.

Especially in the BOM table of a variant part the `Inherited` table column is actually used in both meanings:
- a newly added BOM item is marked with a badge to tell `if that line gets inherited by child variants`
- a BOM item that got inherited from a parent template/variant gets a link to the BOM `where it got inherited from`

(I am not a native English speaker, but this differentiation is even more pronounced in other languages like German - and should be clearly separated to ensure it is translatable in both ways if needed.)

### Suggested solution

I would suggest two changes:

1) change the wording from `Inherited` to `gets inherited`
2) remove the parent-BOM-link in that column of BOM items and add a grey `YES` banner instead to indicate that this item gets inherited into child BOMs. The link is doubled up in the `Actions` column anyway, which is a very good place for it I think.

Examples:
![Bildschirmfoto vom 2023-02-20 11-33-11](https://user-images.githubusercontent.com/296454/220085904-b4e0a778-ff6b-471c-af3f-56e4304f7c9b.png)
![Bildschirmfoto vom 2023-02-20 11-37-53](https://user-images.githubusercontent.com/296454/220085926-fce3e959-ba83-45e5-ad88-9d3c6e431cb5.png)

### Describe alternatives you've considered

None so far, but I'm open for other ideas any time...

### Examples of other systems

-

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
Sounds reasonable. This needs to be changed in the api and will be breaking, please remind me to mark the PR with the same labels as this issue.

**Comment by SchrodingersGat** [comment]
@simonkuehling your suggestions make sense, and I agree that the wording can be confusing here. I'd be happy to accept such changes :)

**Comment by simonkuehling** [comment]
@matmair Well, I am torn if we actually need to change the wording in the code/db/api - as far as I can tell the backend code always uses `inherited` in its `gets inherited`-meaning. Which is not wrong as a short form in itself as far as I can tell in English. As long as it is used in that specific meaning throughout the interface and translations, we should be fine to mainly change the human readable text blocks, table headers etc throughout and maybe adjust some comment- and documentation-lines.

The use as its second type of meaning `was inherited` would be removed completely if the table rendering is adjusted like I sketched above I think...

**Comment by simonkuehling** [comment]
I have submitted PR #4397 including screenshots of the changes I made - let me know what you think!
