### ISSUE TITLE
[FR] move categories and stock locations into the main menu (UI Improvement)

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4384]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

For quickly navigating a rather large parts list the quick-access menu with a list of categories (in Parts view) and stock locations (in Stock view) is already super helpful. Unfortunately you cannot make that menu stay reachable when scrolling right now - which would be another productivity boost for heavy use of the UI.

The menu currently:
![Bildschirmfoto vom 2023-02-21 13-56-41](https://user-images.githubusercontent.com/296454/220351285-9af3f24a-3397-40a2-a5cc-4610678c7474.png)

### Suggested solution

Since the main menu can be made sticky in the settings, why not move these quick-access menus there as well as drop downs?

Imagine it like this:
![image832](https://user-images.githubusercontent.com/296454/220352210-679e351c-1744-4458-8671-e0120d609cd9.png)

The breadcrumb-links next to the current quick menu (or more precisely "current path"-links) could stay as they are, just without the menu icon...

I could contribute that, in case there is support for that change. I think this could make the UI a little more accessible/consistent - but that could also just be my personal view. In other words: comments appreciated!

### Describe alternatives you've considered

.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
I like the idea, especially because it removes layout shifts. Interested in other perspectives.
