### ISSUE TITLE
[FR] Improve stock status badges for parts in forms and search results

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4385]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When creating Child Build Orders or Purchase Orders from Build Orders in the [Allocate Stock] tab, there is no sufficient indicator available which quantity of a part is available/beeing built/ordered/in demand right now.

- If stock is available, there is no info about `on order` oder `building`
- There is no info how much demand from build orders there are for this part (a number that is available in the part view through its `Allocated to Build Orders` metric)

This can quickly lead to bad planning in how many parts need to be built or ordered to serve all demands from current Build Orders.

### Suggested solution

I propose to introduce a `Demand: X` info and combine all relevant numbers into one badge. The color scheme for the badge should then be chosen based on overall "stock healthyness" (all factors considered). The content logic for the stock badge should follow these rules:

- `No stock` or `No stock available` or `Available: X/Y` --> always shown
- `Building: X` --> if beeing built right now
- `On Order: X` --> if beeing on order right now
- `Demand: X` --> if beeing in demand but not yet allocated from current Build Orders

Example
![Bildschirmfoto vom 2023-02-21 22-38-02](https://user-images.githubusercontent.com/296454/220465518-f2bfb957-0128-4e62-9c8d-e84a20342827.png)

The same badge could then also be used in the `Allocate Stock` tab in Build Orders to give a full overview/projection if stock needs to be increased by additional build orders or purchase orders, or if enough is incoming or in production already to be allocated later.

### Describe alternatives you've considered

.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
Not sure if this would not crowd the UI too much - could you mock up some examples (should be simple with the page inspection tool) and add them to the first post? I understand the need and see the added utility.

I think this one requires input from more ppl from @inventree/triage before any action is done.

**Comment by SchrodingersGat** [comment]
I agree with @matmair some example screenshots would be nice here

**Comment by matmair** [comment]
@simonkuehling you will need to ping us / inventree/triage again to get the changes reliable into our mailboxes.

**Comment by eeintech** [comment]
Looks fine to me :+1:

**Comment by matmair** [comment]
@simonkuehling interfaces are hard - I think your solution looks good. I am curios how that will look with translations

**Comment by SchrodingersGat** [comment]
I like it! Looks very neat - as long as it doesn't bloat too far horizontally

**Comment by simonkuehling** [comment]
I'm coding it up right now for a live test - but I have a question that you might be able to help me with:

It looks like I do not have access to `part.required_build_order_quantity` and `part.allocated_build_order_quantity` on the JS side right now. Also the API does not ship these values with a part request.
Do we need to extend the API for this?

**Comment by SchrodingersGat** [comment]
The "allocated" quantity is there:

![image](https://user-images.githubusercontent.com/10080325/220614415-e2cddad7-554e-4d8d-841a-e414293a0690.png)

But perhaps not the "required" quantity?

**Comment by SchrodingersGat** [comment]
Yep looks like we don't annote the "required" quantities (for build orders and sales orders) onto the Part serializer. The logic here might get a bit tricky too.

For reference, here's how we annotate the "allocated" quantity values:

https://github.com/inventree/InvenTree/blob/fa7a33dc9c8ffc753cfe26d0338a9df64d5b2129/InvenTree/part/filters.py#L100

**Comment by simonkuehling** [comment]
@SchrodingersGat you're right - only the "required" quantities is missing...

In the backend code I found
https://github.com/inventree/InvenTree/blob/fa7a33dc9c8ffc753cfe26d0338a9df64d5b2129/InvenTree/part/api.py#L686-L717

And from there I saw that `/api/part/{id}/requirements/` is an existing API endpoint which provides the value I am looking for, right?

**Comment by simonkuehling** [comment]
> And from there I saw that `/api/part/{id}/requirements/` is an existing API endpoint which provides the value I am looking for, right?

@SchrodingersGat works like a charm - this is how it is looking right now:

![Bildschirmfoto vom 2023-02-22 16-30-33](https://user-images.githubusercontent.com/296454/220671704-6ee208da-b6c2-4565-b359-15d438602dde.png)

@matmair here is the equivalent in German:

![Bildschirmfoto vom 2023-02-22 16-38-00](https://user-images.githubusercontent.com/296454/220674085-0f546f83-8d0c-44d7-9323-d7057e6aa3a3.png)

**Comment by matmair** [comment]
@simonkuehling looking good!
