### ISSUE TITLE
[FR] Sales order items export/import 

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#4390]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Handle sales orders with a lots of items.

### Suggested solution

Purchase orders have the possibility to export / import items to files.
It will be nice if sales orders have the same feature.
It can also connect SOs to POs because opens up the possibility to transfer items from one to another.

### Describe alternatives you've considered

Handle items one-by-one.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@rkalman importing will have to wait for #3101 

exporting however will be available as soon as https://github.com/inventree/InvenTree/pull/4392 is merged!

**Comment by rkalman** [comment]
Thank you Oliver!

**Comment by SchrodingersGat** [comment]
Closed as complete
