### ISSUE TITLE
[FR] API: include the PartRequirements in PartList results

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4421]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

After coding and now using the new stock badges from #4385, I see a huge productivity value in the "Stock Health" metric, that the badges use for color coding. I'd like to use that for various improvements throughout the UI, but the necessary data for calculation of it is only available as a separate API call per part to `/api/part/{id}/requirements/` right now. Which is fine for a 10 line search results, but way too many additional requests in any parts table.

### Suggested solution

If the data from the `PartRequirements` API Endpoint could somehow be annotated(?) to the `PartList` results, so they are easily accessible also in big part tables - that would be the key to the improvements I have in mind.

I'm too inexperienced with the low-level DB specifics of Django yet to know where to start - but maybe with a bit of help I could get there? Any tips or help would be highly appreciated!

@SchrodingersGat you mentioned in https://github.com/inventree/InvenTree/issues/4385#issuecomment-1439910670 that this might be tricky - so, that means it is possible, right? ;-)

### Describe alternatives you've considered

.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@simonkuehling this is a good idea, adding your improved "required" labels to the larger part tables. This way we can commonise the javascript code, as currently that is heavily duplicated.

Currently the problem is the difference between returning requirements data for a single part instance query, or returning requirements data for a list of multiple parts. This is the [N + 1 query problem](https://github.com/inventree/InvenTree/pull/4422) and I have spent a lot of time optimising various API queries to avoid this.

The existing "requirements" API only queries a single part at a time, and is far from optimal in terms of database queries:

<img width="784" alt="Screen Shot 2023-02-26 at 1 28 15 pm" src="https://user-images.githubusercontent.com/10080325/221388919-3cf2bb95-e8a1-4854-9c78-75ebdb0f7ef8.png">

<img width="823" alt="Screen Shot 2023-02-26 at 1 29 07 pm" src="https://user-images.githubusercontent.com/10080325/221388940-069b1323-7a8a-4c91-9474-20eb36e0c58b.png">

We cannot (efficiently) use this approach for the larger tables, as this would require an extra API call for each and every part in the table. The better way is to include this data in the "list" API call, but without requiring extra database hits.

Actually, some of these data are already available on the part list API:

<img width="1028" alt="Screen Shot 2023-02-26 at 1 31 07 pm" src="https://user-images.githubusercontent.com/10080325/221388980-825fb319-35e1-4641-9692-98340862464f.png">

You can see here that "allocated_to_build_order" and "allocated_to_sales_orders" data is already there.

So what we need is to add that extra data to the API serialised. I'd also suggest we turn it off by default, and pass an extra query parameter e.g. `/api/part/?requirements_data=1&allocation_data=1`

I will look into a PR to add this, there may be some other implications too. I'll tag you, and then you'll be able to update the other tables.

**Comment by SchrodingersGat** [comment]
Looking into this, the "required_for_sales_orders" query is pretty straight forward.

However due to the complexities of BOMs (substitutes, variants, etc, etc) the "required_for_build_orders" may not be possible to annotate on the entire part queryset!

**Comment by simonkuehling** [comment]
I see the complexity, for sure… does the current `required_for_build_orders()` implementation account for variants/substitutes even? If I am following the code correctly it is not, or is it?

If not, that would need to be addressed in some form or another anyway I guess (as it is used in the part details view for the „allocated to build orders“ progress bar)…

**Comment by SchrodingersGat** [comment]
Currently the `required_for_build_orders` method is *not* a complete picture - I only realise this after reviewing your request here :)

However, I am now wondering about how this "required" calculation could be easily misleading.

Say you have a sub-component `S1` which is used to make an assembly `A1`. `S1` has variants `S1.1`, `S1.2` and also there is a specified BOM substitute `S2`.

In this case, the following components would report as being "required" for the assembly: `S1` / `S1.1` / `S1.2` / `S2`. Obviously not *all* are required. So any sort of query which tallied up the number of components you are short of would be incorrect.

Any ideas how to get around this?

**Comment by simonkuehling** [comment]
> So any sort of query which tallied up the number of components you are short of would be incorrect.

@SchrodingersGat oh, I think I just understood which cases you are referring to (where parts are tallied up):
1. Template parts in parts lists (where the stock count includes variant stock right now)
2. BOM Items in Build Order --> Allocate Stock (where variants and substitutes are included in the available stock count right now)

right?

Those are two issues I wanted to propose some UI improvements for anyway - and I think there are good options to deal with that in a more explicit manner than right now, that are compatible with the current computation of `required_for_build_orders` as well.

**Comment by SchrodingersGat** [comment]
In general I think I would be happy with a general "how many *could* be used for build orders" query - but that query still needs to be developed (and is tricky)!

It would need to account for:

- "Standard" BOM item relationships
- Inherited BOM items
- BOM items which allow for variant substitutes
- BOM items which have explicit substitute parts

**Comment by simonkuehling** [comment]
@SchrodingersGat do you by chance have a database structure graph (ERD) handy for InvenTree? That would help to dive into those relations a bit deeper...

**Comment by matmair** [comment]
We do not really keep ERD graphs around but I used [this library](https://django-extensions.readthedocs.io/en/latest/graph_models.html) in the past to create graphs. Would be nice to include this for developer instances with the docs as part of https://github.com/inventree/InvenTree/issues/2493.

**Comment by matmair** [comment]
Creating a control-flow chart for how this is calculated would be very nice.

**Comment by simonkuehling** [comment]
ok, `graph_models` from django-extensions is pretty useful :+1: ... I have fitered the graphed models to `Part`, `BomItem` and `Build` for reference - i think this is all we need for the relationships we want to trace here, right?

![database_schema_graph_Part-BomItem-Build](https://user-images.githubusercontent.com/296454/222099367-ccb21914-d26f-4dc8-b39d-365e73aacc0e.png)

I'll take a good stare at it and try to draw some queries up...

**Comment by SchrodingersGat** [comment]
Take a look at https://github.com/inventree/InvenTree/blob/master/InvenTree/part/filters.py as a reference point too.

The queries become difficult when you are annotating against an entire queryset and not a single part reference. LMK how you go, I'll try to think about it also.

**Comment by simonkuehling** [comment]
that is a good reference, thanks! (I edited my last comment to add the `BomItemSubstitute` to the graph - forgot about that)

I will probably start with some pseudo-code before translating that to proper querysets...

**Comment by simonkuehling** [comment]
Ok, let's develop this step by step - let's take the list from Oliver and fill it with life:

The total quantity of parts required by open build orders calculates as a sum of these four queries:

1) "Standard" BOM item relationships
2) Inherited BOM items
3) BOM items which allow for variants of the part
4) BOM items which have explicit substitute parts

I cannot quite get a hang of Djangos annotation syntax, so I'll use raw SQL for now. Should be easy to translate later.

for 1)
```
SELECT SUM(quantity)
FROM BomItem
WHERE sub_part == current_part_pk AND part in (
    SELECT part 
    FROM Build
    WHERE completed == false
)
```
`current_part_pk` is a back-reference to the part that is processed currently - not sure how this is done in Django/Python later...

...so far correct as a starting point?

**Comment by SchrodingersGat** [comment]
You'd want `SUM(bom_item.quantity * build-quantity)` to get the total number of items required for the entire build!

**Comment by simonkuehling** [comment]
Oh, right... I fixed that with a `JOIN` and used the actual table and field names for live testing on the DB:

1) "Standard" BOM item relationships
```
SELECT SUM(build_build.quantity*part_bomitem.quantity)
FROM build_build
JOIN part_bomitem ON build_build.part_id=part_bomitem.part_id
WHERE part_bomitem.sub_part_id = current_part_pk;
```
This seems to work so far. On to the next one...

**Comment by simonkuehling** [comment]
Making progress, I have added substitutes to the query:

- [x] 1. "Standard" BOM item relationships
- [ ] 2. Inherited BOM items
- [ ] 3. BOM items which allow for variants of the part
- [x] 4. BOM items which have explicit substitute parts


```
SELECT SUM(build_build.quantity*part_bomitem.quantity)
FROM build_build
INNER JOIN part_bomitem ON build_build.part_id=part_bomitem.part_id
LEFT JOIN part_bomitemsubstitute ON part_bomitemsubstitute.bom_item_id=part_bomitem.id
WHERE part_bomitem.sub_part_id = current_part_pk OR part_bomitemsubstitute.part_id = current_part_pk;
```
next up are two recursive queries for variant and inherited parts.

**Comment by SchrodingersGat** [comment]
> next up are two recursive queries for variant and inherited parts.

They don't have to be recursive - have a look in `part/filters.py` to see how the tree based subqueries are made. It's pretty mind-bending, but very database efficient :)

**Comment by simonkuehling** [comment]
Don't the Django functions translate to db-side recursive SQL queries as well for tree traversing?
I have made some progress with queries like

```
WITH inherited_bomitems AS
	(
		WITH RECURSIVE
		    parent_parts AS
			(
				SELECT id, variant_of_id
				FROM part_part
				WHERE id = :MYPART
				
				UNION ALL
				
				SELECT c.id, c.variant_of_id
				FROM part_part AS c
				INNER JOIN parent_parts AS p ON p.variant_of_id = c.id
			)
		SELECT part_bomitem.quantity AS inherited_quantity, part_bomitem.id AS inherited_bomitem_id
		FROM parent_parts
		INNER JOIN part_bomitem ON part_bomitem.part_id=parent_parts.id
		WHERE part_bomitem.inherited = true
	)
SELECT [...]
```
Or is there another trick that is even more efficient here? 
To be honest I still have a hard time to get behind the Django way of defining those queries - that's why I am sticking to raw SQL right now...

**Comment by SchrodingersGat** [comment]
I don't believe the filters make recursive SQL queries - although I have not profiled them down to the query level.

We make use of [django-mptt](https://django-mptt.readthedocs.io/en/latest/) which allows us to do flat queries on tree-structured relationships. The models have some extra fields which are pre-computed to allow for efficient queries

**Comment by SchrodingersGat** [comment]
Not stale but needs some more thought
