### ISSUE TITLE
[FR] Change column types for "Download data" on stock table

### ISSUE THREAD

**Issue by winzkigermany** [inventree/InvenTree#4432]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

For stock lists: When using "Download data" to download an XLSX file,
the columns _Quantity_ and _purchase_price_ are not of type "float" in the exported file, and thus can't be used to do any calculations in Excel.

Also, the column _purchase_price_ contains currency symbols with the values, which makes the problem worse.
This is for all export formats, but with XLSX, and XLS, the file in effect gets unusable for further processing.

At first, I thought it's a problem with decimal separators "." (English) vs. "," (German), but it's not.

This is an example export:
[InvenTree_StockItems_28-Feb-2023-problematic.xlsx](https://github.com/inventree/InvenTree/files/10859349/InvenTree_StockItems_28-Feb-2023-problematic.xlsx)

By the way, this behaviour is inconsistent between the **stock** table export and the **parts** table export:
The **parts** table contains float values for _In stock_ and _Minimum cost_ and _Maximum cost_ just fine.

### Suggested solution

1.) Change the Quantity and _purchase_price_ columns to type **float** for XLSX and XLS when exporting those tables.
2.) Remove currency symbols in the _purchase_price_ values

### Describe alternatives you've considered

My simple workaround script -to convert the inventree XLSX stock table export files- does exactly, what I suggested as a solution. (for € and $ only):

```
#!/usr/bin/python3
# coding=utf-8
import openpyxl
import pandas as pd
import sys

filename = sys.argv[1]

df = pd.read_excel(filename, decimal=".")

# Quantity column
# set type "float"
df["Quantity"]=df["Quantity"].astype(float)

# purchase_price column
# eliminate currency symbol "€"
df["purchase_price"]=df["purchase_price"].astype(str).str.replace('€', '', regex=True)  

# eliminate currency symbol "$"
df["purchase_price"]=df["purchase_price"].astype(str).str.replace('$', '', regex=True)  

# set type "float"
df["purchase_price"]=df["purchase_price"].astype(float)

# Write excel file with default behaviour.
with pd.ExcelWriter(filename) as writer:
    df.to_excel(writer)
```

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@winzkigermany fix incoming in https://github.com/inventree/InvenTree/pull/4434

**Comment by SchrodingersGat** [comment]
e.g. 
![image](https://user-images.githubusercontent.com/10080325/222122658-4ba1c941-ed66-487c-a7f7-e49e3c769293.png)

**Comment by winzkigermany** [comment]
Thank you for the speedy fix. It works great, I verified the fix by adding the change to my version.

What about the _Quantity_ column? It's the same problem there. 
Sorry, I forgot to make _Quantity_ italic further above, so it could be misread.

**Comment by SchrodingersGat** [comment]
@winzkigermany fixed the quantity column also, and validated in excel

**Comment by winzkigermany** [comment]
@SchrodingersGat 
Verified the fix by backporting the changes to my version.
Works like a charm, thanks a lot!
