### ISSUE TITLE
Last Stocktake field is blank under parts but showing under stock

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#4448]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When viewing the list of parts the Last Stocktake field is blank, but when viewing the part/stock is showing the correct date. 

![Screenshot from 2023-03-04 08-32-58](https://user-images.githubusercontent.com/1429043/222885766-749602fd-d1ef-4261-826d-3b9bd9cf962b.png)

![Screenshot from 2023-03-04 08-33-23](https://user-images.githubusercontent.com/1429043/222885768-4f1fca29-bee4-4bd9-9e03-9d2025028819.png)

### Steps to Reproduce

1. Create part
2. Add stock to part. 
3. Click stick adjustement, count stock. 
4. Last stocktake updates to the current date. 
5. Click on parts and search for the part you created. 
6. The last stockdate is blank

### Expected behaviour

Expect last stockdate to show correct value

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.18
Commit Hash: 7aee97d63
Commit Date: 02/03/2023
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: False

**Comment by matmair** [comment]
@StormTrooper it seems to work on demo.inventree.org - can you try reproducing it there? I tested with 530470410.

**Comment by StormTrooper** [comment]
I must be doing something wrong. Replicated the issue there. 
Created 
[my-test-part](https://demo.inventree.org/part/902/)

**Comment by StormTrooper** [comment]
![Screenshot from 2023-03-04 21-31-38](https://user-images.githubusercontent.com/1429043/222929527-606912a7-c167-434a-a333-781a7e7a3c24.png)

**Comment by SchrodingersGat** [comment]
@StormTrooper this is *expected* behaviour, but it might be a bit confusing.

For a single stock item, the `last_stocktake` refers to when that particular individual stock item was last counted

For a part, the `last_stocktake` refers to when a stocktake report was most recently generated for the part.

Note that in the case where there are multiple stock items associated with a given part, the two stocktake events are not the same.

I have recently been considering whether the terminology here needs to be improved...

**Comment by StormTrooper** [comment]
Thanks for the clarification. Closing the ticket as working as expected.
