### ISSUE TITLE
[FR] Delete multiple Purchase Order Line Items via multi-select (API Endpoint needed?)

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#4449]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I am in the process of adding a mutli-select "Delete selected Line Items" function to the PurchaseOrder UI. As far as i can see right now, there is no API endpoint for
```
 DELETE /order/po-line/.* 
```
like there is for multiple BOM Items with

```
 DELETE /api/bom/.* 
```
...right?

### Suggested solution

I guess I nedd to add that endpoint for it

### Describe alternatives you've considered

.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
Check out the `BulkDeleteMixin` class which is used to achieve this:

https://github.com/inventree/InvenTree/blob/c0f405243a146597513fce6090c2fe1191e8d5fa/InvenTree/InvenTree/api.py#L68

And in particular how it is implemented, e.g. for the BomItem API

**Comment by simonkuehling** [comment]
@SchrodingersGat thanks for the tip - that made it pretty easy :+1: 
PR is submitted as #4452

**Comment by matmair** [comment]
@simonkuehling the project is not as sufisticated as it seems, just grown and on the larger size. 😇 
You have been very active in improving the project - that is very much appreciated. Thank you.
