### ISSUE TITLE
Inconsistency path for static files

### ISSUE THREAD

**Issue by Vultik** [inventree/InvenTree#4451]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [X] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem

[In the docs](https://docs.inventree.org/en/latest/start/install/#create-required-directories), it's written to create a folder for static files at `/home/inventree/static` . However, in the `config.yaml` the default path is 

![image](https://user-images.githubusercontent.com/55872753/222916898-8178925a-2802-4fd9-b5c1-616833c140c7.png)

If you uncomment theses lines, it will not match the paths suggested in the doc.
So when you run the `invoke update` command, the generates files will be stored at `/home/inventree/data/static` instead of `/home/inventree/static`.

**Suggested fix** : change the default static path in the `config_template.yml` file to `/home/inventree/static`

### Steps to Reproduce

https://docs.inventree.org/en/latest/start/install/#bare-metal-setup

**Comment by matmair** [comment]
@Vultik our docker containers use the data subdir to make mounting folders cleaner - that is where the path comes from. Docker deployment seems to be used more by new users than bare metal - which gives you the most options but also requires deeper linux knowledge than a package or docker install.

I think it can be expected from users to read what they put into their config file. @SchrodingersGat you d'accor?

**Comment by SchrodingersGat** [comment]
@Vultik the bare-metal docs provide a starting point but the directories should be located based on your requirements.

That being said, there is definitely some room for improvement in the docs. As @matmair points out, the docker setup requires a particular directory structure. But the *installer* configures the directories differently. 

Potentially the bare-metal setup guide should be closer to the documentation for our bare-metal installer...

**Comment by Vultik** [comment]
The updated docs are more clearer now .
Thanks
