### ISSUE TITLE
[Bug] Nested BOM has no arrow when using Dark/Black Theme

### ISSUE THREAD

**Issue by tehkillerbee** [inventree/InvenTree#4455]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi guys,

I noticed a small bug when viewing the BOM using the Black/dark theme.  Unlike when using the "light" theme, the triangular arrows are not displayed when using the dark theme. If you click the approximate location of it, you can expand/collapse the nested BOMs.
![Screenshot_2023-03-06_14-55-53](https://user-images.githubusercontent.com/815886/223141016-3bcdb6e8-7b2d-4a6a-b50f-744175124e3f.png)
![Screenshot_2023-03-06_15-11-33](https://user-images.githubusercontent.com/815886/223141050-a84eef6e-cee0-4d7c-bbb8-3fcb64b1748d.png)

### Steps to Reproduce

1. View a BOM containing nested items while using the Dark theme.
2. Click refresh, if necessary. "Expand" arrow icon is not displayed.

### Expected behaviour

Triangular arrows should be shown, as with the light theme, but they are not.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: fb34409
Commit Date: 2022-12-19
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
@eeintech do you think you would be able to have a look at this? You implemented these themes, right?

**Comment by eeintech** [comment]
@tehkillerbee I don't see the problem on the demo instance, the arrow shows:

## Chrome
![image](https://user-images.githubusercontent.com/4020546/223452550-26ba8d80-782d-4ad8-b746-a77dc1f573bd.png)

## Firefox
![image](https://user-images.githubusercontent.com/4020546/223452963-a5204bbf-6043-472b-8aec-78e683158c4b.png)

Which browser are you using? Can you check for any extension that would overwrite the website's CSS theme?

**Comment by tehkillerbee** [comment]
@eeintech You are right, it is not an issue when using the demo server. I should've checked this before creating an issue, sorry. 

I will try upgrading our instance and let you know if it fixes the problem.

**Comment by eeintech** [comment]
@tehkillerbee No problem, if you find the root cause I can help to fix :wink:

**Comment by tehkillerbee** [comment]
@eeintech I updated to the latest dev version and refreshed browser cache again. Then the arrows appear as expected. :)

Closing this issue

**Comment by eeintech** [comment]
Good to know @tehkillerbee, thanks for checking!
