### ISSUE TITLE
Parts table ordered by stock

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#4460]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The table displays the "in stock" quantity, but if you order it by stock then it displays items ordered by available stock, or something else, because the last page of the table is different...
So something definitely wrong with ordering/paginating here.
![Képernyőfotó 2023-03-07 - 11 53 08](https://user-images.githubusercontent.com/580623/223405785-0988c199-795b-4673-a9d5-e44b412c6ed8.png)
![Képernyőfotó 2023-03-07 - 11 53 23](https://user-images.githubusercontent.com/580623/223406303-e6bd146f-825e-46d6-8237-4d73a7a2d7ad.png)
![Képernyőfotó 2023-03-07 - 11 54 39](https://user-images.githubusercontent.com/580623/223405814-60fa111a-48fe-4721-8ed4-411907eb5c63.png)

### Steps to Reproduce

Parts/Parts, order table by clicking "Stock" in the header, select diffenrent pages.

### Expected behaviour

Display items in a right order.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

on demo server:
# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.18
Commit Hash: ba4e264
Commit Date: 2023-03-05
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
@rkalman thanks for reporting - looks like a pretty subtle difference between "total stock" and "available stock". Working on an improvement

**Comment by rkalman** [comment]
Wow, thank you Oliver!
