### ISSUE TITLE
[FR] Part history

### ISSUE THREAD

**Issue by rkalman** [inventree/InvenTree#4468]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Stock items have a history, where all changes are stored.
it would be good to have a similar tracking for the parts, where it would be visible who last modified it, when, with a comment, e.g.

### Suggested solution

Add similar functionality like the stock items have

### Describe alternatives you've considered

No alternatives.
No information about when a part was changed and why.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@rkalman this has been discussed before e.g. https://github.com/inventree/InvenTree/issues/377

An "audit log" would be a good idea, and I think the project has evolved and matured enough to warrant it.

We have discussed using something like [django-auditlog](https://django-auditlog.readthedocs.io/en/latest/) to achieve this

**Comment by rkalman** [comment]
Yes, in a multi user environment it would be a very good thing to track down all the important changes. 
Now unfortunately there is no information about who was changed a part definition and when and why.

**Comment by gooutbefree** [comment]
This feature would be very useful in a multi-user environment. Auditlog looks good.

**Comment by matmair** [comment]
We welcome PRs!

**Comment by matmair** [comment]
Still looking for a dev that wants to implement this

**Comment by SergeoLacruz** [comment]
I think there is already a history if parts are changed in the admin interface. Anyhow changes from the normal UI are not tracked.

**Comment by matmair** [comment]
The tracking in admin is a default feature of Django and not scalable. We could expand what was built for the stock model or use some community package for this.
Having a verb-based system to create an activity stream and events would be pretty helpful, it could also be used to create triggers for federated systems.

**Comment by SergeoLacruz** [comment]
I think it is still important

**Comment by SchrodingersGat** [comment]
Not stale
