### ISSUE TITLE
[Question] I cant see newly added project urls

### ISSUE THREAD

**Issue by emrecanozkok** [inventree/InvenTree#4477]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I created a new package to add a new model to the Inventree project. But the urls I defined do not work. What procedure should I follow when adding a new package?

### Steps to Reproduce

*

### Expected behaviour

*

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

*

**Comment by SchrodingersGat** [comment]
@emrecanozkok you are going to need to provide a *lot* more information here.

**Comment by matmair** [comment]
Where did you "add" a "package" and how?
Give us steps to reproduce, expected behavior, deployment method, version information. Your bug report is for all purposes empty - we can not read your mind.

**Comment by emrecanozkok** [comment]
im using pycharm, i clicked invenTree folder and added new package named "project" 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/8539564/224018117-fffcb898-1048-44e1-aad8-2cc4092adae4.png">

after that im added my urls tl urls.py
<img width="673" alt="image" src="https://user-images.githubusercontent.com/8539564/224018228-afe27530-57e9-4537-80b9-72a63924e5ba.png">

and i added project to apps section in tasks.py which in root folder

<img width="532" alt="image" src="https://user-images.githubusercontent.com/8539564/224018435-b6a12af1-7cf5-4462-a30f-ce4f5bf06cf8.png">

im using 0.10.1 version

**Comment by matmair** [comment]
@emrecanozkok please read our docs [on plugins](https://docs.inventree.org/en/latest/extend/plugins/). What you are attempting ist not how the system was designed; We do not support forks that modify core code.
InvenTree is not a django template or libary but a enduser plattform.

**Comment by emrecanozkok** [comment]
> @emrecanozkok please read our docs [on plugins](https://docs.inventree.org/en/latest/extend/plugins/). What you are attempting is not how the system was designed; We do not support forks that modify core code. InvenTree is not a django template or libary but a enduser plattform.

thank you so much for explanation
