### ISSUE TITLE
[FR] Portainer Support

### ISSUE THREAD

**Issue by LOENS2** [inventree/InvenTree#4481]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

As already stated in #2724, it would be nice to have a way to install InvenTree on Portainer without having to run commands in the bash. I don't know much about docker, this is why I use tools like Portainer. Docker is quite useful in production environments so I completely get why you'd wanna use it.

### Suggested solution

A docker compose script that allows me to run it as a Stack in Portainer, set up only by .env. Being able to run the install completely  unattended would be very useful, because I only use Docker for my production services that have to be up and running all the time. It would be great to set InvenTree up with the repo deployment option of Portainer, so the container would stay up to date. The even superior option would be to use an App Template: https://docs.portainer.io/advanced/app-templates/build .

### Describe alternatives you've considered

I don't know much about Portainer either. Is there a way to run these docker compose commands automatically? If so, that would be a good alternative.

### Examples of other systems

There are many projects that provide app templates like: Nginx, MariaDB, Jenkins. Sure, they are way bigger that InvenTree, but it would be nice to have InvenTree in that list.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Hi there @LOENS2 ! Thank you for the feedback.
I am really not a fan of supporting proprietary docker/podman wrappers in my free time so I will not implement anything specific. If someone contributes the needed changes/docs we would probably not be against merging them.

**Comment by LOENS2** [comment]
Fair enough. I don't appreciate their way of pushing costumers to their enterprise version either. For me it just was a easy way to get started with docker. I'll try for myself what I can do to get around Portainer.
