### ISSUE TITLE
Bug unable to see DropDown Menu Arrow in Darkmode 

### ISSUE THREAD

**Issue by Fluxus00** [inventree/InvenTree#4483]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When loading the sub-sub BOM of an assembly in darkmode, you are not able to see the arrow to open the loaded BOM. 

### Steps to Reproduce

1. Enable Dark Reader
2. Have an Assembly with at least one other assembly as sub-part which also contains an other assembly
3. open the BOM 
4. Try to load the BOM of the sub-sub part

### Expected behaviour

You should be able to see the arrow, which shows the extended BOM.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0 dev
Django Version: 3.2.16
Commit Hash: e730b5c24
Commit Date: 2023-01-10
Database: postgresql
Debug-Mode: True
Deployed using Docker: False
Active plugins: False

**Comment by matmair** [comment]
@Fluxus00 sounds exactly like https://github.com/inventree/InvenTree/issues/4455 - did you check the issues before submitting like instructed on top of the bug report?

**Comment by Fluxus00** [comment]
Ah sorry my bad, yes i checked it, but it seems like I need new glasses. I will close this right away.
