### ISSUE TITLE
Editing PO line item overwrites price

### ISSUE THREAD

**Issue by gooutbefree** [inventree/InvenTree#4485]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Adding a PO line item takes the price from the order. This could be useful or not.

When you edit a PO line item e.g. adjusting quantity or delivery date, the dialog takes again the price from the last order. Not the price from the existing PO line item.
If the price is not corrected again (e.g. if focused on delivery date), the price in the order is overwritten with the wrong/old one

### Steps to Reproduce

Tested also on the inventree demo server
Create a PO with a component that was ordered before
Use a new price by creating the PO line item
Edit the line item e.g. adjust date
Save
Check price in line item

### Expected behaviour

Edit dialog has to use the price from the line item

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.10.1

**Comment by SchrodingersGat** [comment]
@gooutbefree I cannot immediately replicate this - can you share some more details? Maybe a screen capture of what you are seeing?

**Comment by SchrodingersGat** [comment]
@gooutbefree thanks, I can confirm that this is a bug
