### ISSUE TITLE
Deconstruct / Unbuild a completed build

### ISSUE THREAD

**Issue by biker2000on** [inventree/InvenTree#4487]
I am trying to figure out how to deconstruct an item to reclaim the parts into inventory. Is this possible? I have not found it in the docs or by playing around with the InvenTree application.

**Comment by SchrodingersGat** [comment]
Currently this is not possible. It would be a great addition to the build order workflow, although it would require a lot of careful consideration.

For example there would have to be support for the end user to dictate (very specifically) which consumed items are to be returned to stock, and which are to be "scrapped".

**Comment by matmair** [comment]
Would be a nice thing; A bit more precise feature description would be nice to have something to work of.

**Comment by biker2000on** [comment]
My current use case is as a hobbyist beekeeper where I would "construct" a hive to take into the field. I do not use trackable parts to make this easier. When a hive has a dead-out or is no longer needed it is transferred inside and the parts become available for use in other hives as necessary. 

I imagine an implementation would look the same as a build order but in reverse. The same screens could likely be utilized: 
* I'm unsure of what industry standard naming would be. I would use: Deconstruct Order
* Allocate Stock would allow you to do the same as a build order, but in reverse. 
* Incomplete and Completed outputs instead parts moving to a whole, would be a whole moving towards parts. Probably viewable via a tree view dropdown on the whole part if trackable.
* Child Deconstruct Orders if desired could be added to take it even further apart.
* Attachments and Notes are the same as a build order. 

Hope this helps. Thanks for looking at it.

**Comment by matmair** [comment]
@biker2000on thank you for the explaination!

**Comment by biker2000on** [comment]
@matmair I may be able to take a stab at coding this feature. I read somewhere that you are in the midst of a migration to API-first and React. Should the implementation be for django templating or skip that altogether and just do the backend code and separate React frontend?

**Comment by SchrodingersGat** [comment]
@biker2000on the react rework is still a ways off. I'd concentrate first on the backend logic required to perform this process. If you can conceive a workflow, discuss with us first, before we jump into implementation.

Second step would be exposing functionality to the API.

Third is UX

**Comment by SchrodingersGat** [comment]
not stale
