### ISSUE TITLE
Migrate away from old bare metal to docker

### ISSUE THREAD

**Issue by nelsonov** [inventree/InvenTree#4504]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I have an old install in a venv, which is what I believe you call a bare metal install.  I would like to migrate to docker on a different server.  The original install and venv was python 3.7.3.  When I tried to use the invoke export-records command, it failed because it was calling python functionality that didn’t yet exist in 3.7.3.  I upgraded and updated my system to python 3.9.  However, now, of course, my venv is completely broken.  I have hundreds of hours into the data that exists now.  Is there any way I can still get at it?  I don’t even need a running inventree on the old system at this point, just some way to get the data out and into a docker install.

### Steps to Reproduce

invoke export-records

**Comment by nelsonov** [comment]
Sorry for the long delay.

It is a mysql backend.  I have dumped the database.  I have also installed python 3.7.3 in an alternate location and have the venv using that version.  The venv is working again and inventree tries to start but chokes on the ":=" operator since that was introduced after 3.7.3.  I picked a random tag, 0.6.0, and checked it out.  Now the server gets further but dies looking for columns that don't exist, so there is probably a schema mismath between 0.6.0 and whatever version I was running before upgrading.

Is there anything stored in the database that might tell me what tag or commit the database was previously running at?

In browsing through the dump file, it does have a field saying that the latest inventree version is 0.9.1, so inventree is getting far enough to have updated that field.  So, this may have wiped out previous version history.

This whole saga started when I wanted to move away from the bare metal to a docker install on a different server.  The migration instructions told me to update my existing installation to the latest version so that there wouldn't be a scheme mismatch.  This was perfectly logical.  However, the newest version of inventree (0.9.1 at that time) used the ":=" operator which invoke on Python 3.7.3 didn't understand.  Without thinking I upgraded Python and landed myself in the mess I have now.

**Comment by SchrodingersGat** [comment]
@nelsonov basically the process is outlined here: https://docs.inventree.org/en/latest/start/migrate/

1. run `invoke export-records` on your *old* installation
2. Setup a *new* installation (it is critical that this is at the same InvenTree version as the *old* one)
3. Run `invoke import-records` on the *new* installation
4. Run `invoke update` to bring your installation up to date (and critically, update your database schema and records)

**Comment by matmair** [comment]
@nelsonov we are currently targeting python 3.9 (which should be available on all current Linux and windows server os versions) - see [here](https://github.com/inventree/InvenTree/blob/d5a71b2fe8d3600b18cab24b55abca69d24456f6/CONTRIBUTING.md?plain=1#L87).

Your venv being gone is not really a problem, just update to python 3.9 or newer and generate a new venv with `python3 -m venv venv`. There is no data in the venv. The database holds the current state/version of the database so you just need to run `inv update` to get a running install again (in the venv). After that, you can export the dataset and switch to docker. Please note the current version before exporting the dataset - the docker needs to be same or higher.

@SchrodingersGat as long as the version of InvenTree is higher then the destroyed one, I do not see a reason why it should be a problem. The migration states are in the database so restoring the full dump will recreate the migration tables as well. Am I missing something?
