### ISSUE TITLE
Disable Label PDF Export or Rearrange options

### ISSUE THREAD

**Issue by codeaddicted** [inventree/InvenTree#4506]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Is there any way to disable the pdf export of labels (i have a label printer plugin installed) or at least rearrange the options so i don't always need to select the printer plugin as output when printing a label?

### Steps to Reproduce

0. try print label
1. need to select printer plugin instead of "export pdf"

**Comment by codeaddicted** [comment]
well:
![Bildschirmfoto_2023-03-18_14-49-31](https://user-images.githubusercontent.com/2549755/226110142-1e81a3f6-a567-4a66-b017-265a723f2e88.png)

**Comment by SchrodingersGat** [comment]
Yes this setting is only available in the upcoming feature release

**Comment by codeaddicted** [comment]
ok then i will wait for it thank you!
