### ISSUE TITLE
BOM API-Endpoint allows for filtering "part" but not "sub_part"

### ISSUE THREAD

**Issue by Rincewind34** [inventree/InvenTree#4507]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I'm trying to filter BOM Line items for the sub part (to find a list of all parts, that require a part X) I think I should be able to of this via
`curl -H "Content-Type: application/json" --user "NAME:PASSWORD" -X GET "BASEURL/api/bom/?sub_part=323"`
but the result seems to be all line items there are (for me 510 - same as when I would remove the filter.) I know that filtering works in general, because querying
`curl -H "Content-Type: application/json" --user "NAME:PASSWORD" -X GET "BASEURL/api/bom/?part=12"`
results in a small list of line items, that are required to build part 12.

I'm I doing something wrong? FYI: this last part filter is also not documented in my api.
<img width="818" alt="Screenshot 2023-03-19 at 14 59 52" src="https://user-images.githubusercontent.com/13020648/226181064-ab7e9cba-0694-407b-8b39-291667fd671d.png">

### Steps to Reproduce

See above

### Expected behaviour

See above

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

InvenTree Version	0.10.0 dev
API Version	85
Python Version	3.9.16
Django Version	3.2.16

**Comment by SchrodingersGat** [comment]
@Rincewind34 you want to use the `uses=<pk>` query:

i.e. 

https://demo.inventree.org/api/bom/?search=&uses=71&part_detail=true&sub_part_detail=true
