### ISSUE TITLE
Line item empty in Part Settings. Due to hide revision?

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#4509]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I've updated to the latest nightly version and run ```invoke update```

When viewing Part settings the first line is showing no text. 
I think it might be related to https://github.com/inventree/InvenTree/pull/4493

![Screenshot from 2023-03-19 22-32-35](https://user-images.githubusercontent.com/1429043/226214006-11a6954d-e843-4803-8913-a71c7f2660e5.png)

### Steps to Reproduce

1. Click on Settings
2. Click on Parts
First line is not showing any text. 

### Expected behaviour

Expect text to appear. 

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.18
Commit Hash: 4d8311682
Commit Date: 20/03/2023
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: False

### Relevant log output

```shell
Not sure if it's related but in Chrome dev tools I'm getting a 404 on 

chartjs-adapter-moment.min.js.map

DevTools failed to load source map: Could not load content for http://inventree.home:8000/static/script/chartjs-adapter-moment.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Page not found (404)
“/home/inventree/data/static/script/chartjs-adapter-moment.min.js.map” does not exist
Request Method:	GET
Request URL:	http://inventree.home:8000/static/script/chartjs-adapter-moment.min.js.map
Raised by:	django.views.static.serve


```

**Comment by SchrodingersGat** [comment]
Try refreshing the page a few times? After an update the cached templates might need refreshing..

Seems to work ok on the demo server:

![image](https://user-images.githubusercontent.com/10080325/226222067-e4183630-a7f7-48c4-a42b-441e8b61a75e.png)

**Comment by StormTrooper** [comment]
Issue fixed after I restarted the web server.
