### ISSUE TITLE
Static files not rendered on the webpage

### ISSUE THREAD

**Issue by mdotkurmi** [inventree/InvenTree#4521]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I tried to install InvenTree on my QNAP NAS TS-251+
Installation is successful, but static images are not rendered on the webpage.

I have shared the log of my inventree-proxy container.

I have tried to both setting INVENTREE_DEBUG to true and false, but it doesn't make any difference.

![Capture](https://user-images.githubusercontent.com/14815411/227173462-d885de5c-507b-4ad1-b96a-12b55507eda5.PNG)

### Steps to Reproduce

I have run the following commands with the attached files in the folder.
1. docker compose run inventree-server invoke update
2. docker compose up -d

[env.txt](https://github.com/inventree/InvenTree/files/11049560/env.txt)
[docker-compose.yml.txt](https://github.com/inventree/InvenTree/files/11049561/docker-compose.yml.txt)
[nginx.prod.conf.txt](https://github.com/inventree/InvenTree/files/11049563/nginx.prod.conf.txt)

### Relevant log output

```bash
192.168.1.110 - - [23/Mar/2023:09:47:27 +0000] "GET /static/img/favicon/favicon-16x16.png HTTP/1.1" 403 555 "http://192.168.1.112:8000/accounts/login/?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "-"
2023/03/23 09:47:27 [error] 24#24: *9 open() "/var/www/static/img/favicon/favicon-96x96.png" failed (13: Permission denied), client: 192.168.1.110, server: , request: "GET /static/img/favicon/favicon-96x96.png HTTP/1.1", host: "192.168.1.112:8000", referrer: "http://192.168.1.112:8000/accounts/login/?next=/"
192.168.1.110 - - [23/Mar/2023:09:47:27 +0000] "GET /static/img/favicon/favicon-96x96.png HTTP/1.1" 403 555 "http://192.168.1.112:8000/accounts/login/?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "-"
2023/03/23 09:47:27 [error] 24#24: *9 open() "/var/www/static/img/favicon/android-icon-192x192.png" failed (13: Permission denied), client: 192.168.1.110, server: , request: "GET /static/img/favicon/android-icon-192x192.png HTTP/1.1", host: "192.168.1.112:8000", referrer: "http://192.168.1.112:8000/accounts/login/?next=/"
192.168.1.110 - - [23/Mar/2023:09:47:27 +0000] "GET /static/img/favicon/android-icon-192x192.png HTTP/1.1" 403 555 "http://192.168.1.112:8000/accounts/login/?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "-"
```

**Comment by SchrodingersGat** [comment]
Looks like the nginx container does not have the right permissions to access those files on your local system?

**Comment by mdotkurmi** [comment]
> Looks like the nginx container does not have the right permissions to access those files on your local system?



> Looks like the nginx container does not have the right permissions to access those files on your local system?

**Comment by mdotkurmi** [comment]
But it is able to read nginx.prod.conf from the same location.
Any method to confirm it is permission issue?

**Comment by SchrodingersGat** [comment]
Honestly not sure, I'd suggest you terminal into the **nginx** container and see if there's anything at `/var/www/`

**Comment by miggland** [comment]
Have you tried using the named volume `inventree-data` instead of the path in the inventree-proxy container?

**Comment by mdotkurmi** [comment]
> Honestly not sure, I'd suggest you terminal into the **nginx** container and see if there's anything at `/var/www/`

Yes, I can see the files in '/var/www/' via the container terminal.

> Have you tried using the named volume `inventree-data` instead of the path in the inventree-proxy container?

Yes, I have tried the volume name inventree-data initially but later tried the path, that's why the docker-compose shows the path.

I think, when I run 'inventree-server invoke update', the folder inventree-data UID and GID changes to 999, which I believe the nginx user cannot access.
![image](https://user-images.githubusercontent.com/14815411/229738418-a9ade401-799c-499e-be3d-7f93c536ebad.png)

And if I change the UID or GID or permissions of the folder then the database container cannot run.

For now I have enable Debug, and removed the nginx container to make it working until I find any solution to this issue.

**Comment by SchrodingersGat** [comment]
@mdotkurmi did you end up finding a solution to this issue? I'd like to close it out :)
