### ISSUE TITLE
[FR] Ability to disable all confirmation buttons

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#4529]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

It would  be useful to be able to disable all the confirmation buttons. When making lots of changes it's pain to always have to toggle to confirm. You wouldn't click submit if you aren't sure.

![Screenshot from 2023-03-24 20-59-08](https://user-images.githubusercontent.com/1429043/227639243-11de1d8f-6daa-4d1c-929d-f2fe4dbba702.png)

### Suggested solution

Under settings have a option to disable the confirmation button so if users still want to use it they can.

### Describe alternatives you've considered

I've checked through all the settings and don't see a feature like this. 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
![grafik](https://user-images.githubusercontent.com/66015116/227652024-b454bf96-6e55-47ef-8e2b-3572327db696.png)
General Server settings.

**Comment by matmair** [comment]
Please search for old issues before making new ones: https://github.com/inventree/InvenTree/issues/3069

**Comment by StormTrooper** [comment]
Thanks, not sure how i missed this.
