### ISSUE TITLE
Pip works fine on host but gives error on docker

### ISSUE THREAD

**Issue by rohitsingal1** [inventree/InvenTree#4532]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I am trying to install inventree using docker compose on Ubuntu 22.04. 
Currently we use google DNS 8.8.8.8 and 8.8.4.4 and an nginx server on host to serve multiple webapps
While running docker compose I receive the following error for pip.

'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f10aa99c2b0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/

After adding the nameservers to /etc/resolv.conf the error changes to the one below.

Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5ea62222b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pip.

Everytime before running docker compose I do the following

docker volume rm -f inventree-production_inventree_data
snap restart docker

Docker configuration files are in my home folder /home/user/inventree and I run compose from this folder. 
The data folder is /home/user/inventree/inventree-data

running command pip /path/to/requirements.txt runs fine on host without any issues.

### Steps to Reproduce

Change your network DNS to 8.8.8.8 and 8.8.4.4
Restart network manager
Change /etc/resolv.conf and add both the nameservers
nameserver 8.8.8.8
nameserver 8.8.4.4
Restart network manager 
Copy the file docker-compose.yml, .env and nginx.prod.conf into /home/user/inventree directory
Change the values in .env values as stated in the official docker documentation
Run docker compose
docker compose run inventree-server invoke update

### Relevant log output

```bash
 ⠿ Container inventree-db  Running                                                                                                              0.0s
Loading config file : /home/inventree/data/config.yaml
File “/home/inventree/InvenTree/locale/fa/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/ru/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/fr/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/en/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/pt/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/hu/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/pl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/he/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/pt_br/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/vi/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/sv/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/ja/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/ko/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/el/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/tr/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/nl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/es/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/id/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/es_MX/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/no/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/cs/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/it/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/zh/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/sl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/da/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/th/LC_MESSAGES/django.po” is already compiled and up to date.
InvenTree translation coverage: 23%
Installing required python packages from 'requirements.txt'
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (23.0.1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f10aa99c2b0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f10aa99c5b0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f10aa99c8e0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f10aa99ca60>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/

 ⠿ Container inventree-db  Running                                                                                                              0.0s
Loading config file : /home/inventree/data/config.yaml
File “/home/inventree/InvenTree/locale/sl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/da/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/fa/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/es_MX/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/sv/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/th/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/fr/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/no/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/zh/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/he/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/vi/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/ko/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/cs/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/el/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/en/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/pt/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/it/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/pt_br/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/pl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/hu/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/ja/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/es/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/id/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/nl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/ru/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/tr/LC_MESSAGES/django.po” is already compiled and up to date.
InvenTree translation coverage: 23%
Installing required python packages from 'requirements.txt'
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (23.0.1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe0d01952b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe0d01955e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pip/
```

**Comment by matmair** [comment]
@rohitsingal1 this sounds related to your docker config. Try setting the host entry directly on the docker-compose for the server.

**Comment by rohitsingal1** [comment]
@matmair Added the below lines in my docker-compose.yml and received the same error message.

web:
            build: .
            container_name: html-container
            network_mode: "host"

Not sure if I have done the right thing. Could you guide me in this. Thanks in advance

**Comment by matmair** [comment]
@rohitsingal1 please try to explicitly set the DNS entries like:
```
web:
  container_name: html-container
  dns:
    - 1.1.1.1
    - 8.8.8.8
```

**Comment by rohitsingal1** [comment]
@matmair Added the following lines to my docker-compose.yml and still receiving the same error.

web:
        container_name: html-container
        build: .
        dns:
            - 8.8.8.8
            - 8.8.4.4
        network_mode: "host"

**Comment by matmair** [comment]
@rohitsingal1 what exact version/commit are you on? I am trying to replicate this with `master` and am not able to. Can you ping/curl pypi (eg. https://files.pythonhosted.org/packages/a2/50/7c9a275b5849e8fa0b79ce896170dc1444c271766b8acd01ee15d5d9d770/inventree-0.10.1.tar.gz) from within the container?

**Comment by rohitsingal1** [comment]
I am using the stable Prodction version of inventree and have pulled it using docker pull inventree/inventree. The version number is 0.10.1. On the host I am able to ping pypi.org and curl pypi.org. How do I ping from docker compose ?

**Comment by matmair** [comment]
@rohitsingal1 you need to check in the container itself, I strongly suspect there is some issue in the routing of your docker setup that stops access to the internet (maybe it is the DNS setup, maybe the networks, maybe the firewall on the host).
You can use `docker compose run web bash` to get a bash shell and can ping from within the container from there, see the details [here](https://docs.docker.com/engine/reference/commandline/compose_run/).

**Comment by rohitsingal1** [comment]
@matmair Thanks this is a good option now I have a bash shell to try comands but now I get the error

ping: command not found
curl: command not found

**Comment by rohitsingal1** [comment]
I have also done cat /etc/resolv.conf of docker container. The DNS does not match but I do not have an option to change since vi, nano or any other kind of editor command in unavailable.

**Comment by wolflu05** [comment]
This looks like the issue is not related to inventree for me. Have you tried spinning up a basic Debian docker image and check if ping works in there?
```bash
docker run --rm -it debian /bin/bash
```
I suspect this is related to your server configuration. Have you used docker already before inventree? And why have you installed it via snap? This would be the last option to choose from for me.

**Comment by rohitsingal1** [comment]
@matmair Finally resolved the issue. Actually your first comment was the correct solution.
I was using the network_mode: "host" under the wrong container_name.
Since my docker compose was run with the command 
`sudo docker compose run inventree-server invoke update`

the network_mode:"host" was to be added under the "inventree-server" container name.

```
inventree-server:
        container_name: inventree-server
        # If you wish to specify a particular InvenTree version, do so here
        image: inventree/inventree:${INVENTREE_TAG:-stable}
        #command: curl pypi.org
        expose:
            - 8000
        depends_on:
            - inventree-db
        env_file:
            - .env
        volumes:
            # Data volume must map to /home/inventree/data
            - inventree_data:/home/inventree/data
        **network_mode: "host"**
        restart: unless-stopped

I am really sorry I have taken so long to understand but I have just started exploring docker. 
Thanks once again @matmair 
```

**Comment by rohitsingal1** [comment]
you can check the list of dockers using the network mode using the command 
`sudo docker network ls`

I found that all my dockers were using host mode and inventree was running on bridged mode.
This was the first time I was using docker compose to run my docker. 
In order to run it under host mode just add the line `network_mode: "host"` under the container name

**Comment by matmair** [comment]
@rohitsingal1 welcome to docker - it seems easy at first and in the end, you have learned all the ins and outs of Linux networking, filesystems and system maintenance. The exact same thing happens to me at least once a year 😢.
Your setup should work now, hit us up (in a new discussion/issue) if other problems arise!
