### ISSUE TITLE
How to add new currency?

### ISSUE THREAD

**Issue by ilsicca** [inventree/InvenTree#4533]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I need to add a new currency but when I created in Admin section can't select the new currency in the price section about the part or in setting section when I want to select a default currency.

![image](https://user-images.githubusercontent.com/46833657/227831441-19ead977-0998-464f-b9ba-777d9cafd35d.png)

The new currency is not seen in the list and I don't now how create a name for it.

### Steps to Reproduce

1. Go to admin settings
2. Add new rates
3. Can't select the new rate in Prices sections or settings

### Expected behaviour

I need to add new currency in default currency and price of parts.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.10.1

**Comment by SchrodingersGat** [comment]
https://docs.inventree.org/en/latest/start/config/#supported-currencies

**Comment by ilsicca** [comment]
Pefect! Thank a lot!
