### ISSUE TITLE
[BUG] wget command in README.md is wrong

### ISSUE THREAD

**Issue by liuqun** [inventree/InvenTree#4548]
The following command of `wget` seems to be wrong on my Linux console:

https://github.com/inventree/InvenTree/blob/d0f9d0d830b993d5d4b775818b7ff18fc5d84022/README.md?plain=1#L141

I think it should be changed to
```
wget -qO install.sh  https://get.inventree.org  && bash install.sh 
```

----

On CentOS7 Linux, `wget -Oq https://get.inventree.org` will save the downloaded file as `q`

**Comment by matmair** [comment]
Hi there @liuqun . Thanks for the report. Please use the reporting templates next time, I do not get notifications for issues that do not use the templates.
Fix is incoming
