### ISSUE TITLE
[FR] API generation for C++/Qt

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#4587]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Hi folks,

I used to write tools in C++ with the Qt framework a lot and it would be handy if I could interact with the InvenTree sometimes.

Making REST calls with Qt is quite straightforward to implement "by hand", but I would like to spare (or more exactly make more future-proof) the generation of the exchanged data classes. 

When working with Django/InvenTree migrations I started to wonder that some python code must have awareness of the InvenTree/Django objects and their fields. I could write a python script which would do the same thing to generate the C++ classes. This could be ran on each InvenTree release to regenerate the API for the new releases.

I opened this FR to start some brainstorming on this topic because I think there could be some common interests with others.

### Suggested solution

-

### Describe alternatives you've considered

-

### Examples of other systems

API code generator exists for Qt for WSDL based webservices: https://github.com/KDAB/KDSoap

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
The API is not the same as the underlying model structure. But the API is self documenting (at `/api-doc/`).

FYI I use the the inventree API in a Qt application using the pythonqt bindings.

A C++ API library would be interesting but I'm certainly not going to have any time or interest to develop it.

**Comment by martonmiklos** [comment]
> But the API is self documenting (at /api-doc/).

Mhh good point. Are you aware if this api-doc output could be tricked to get json output?

**Comment by SchrodingersGat** [comment]
Not sure if it can be parsed as JSON. Maybe?

Another option is that each API endpoint also is self describing. Perform an OPTIONS request against an API endpoint to see the available fields. This is how the web interface (and the app) works, it gets all the field info from the API itself.

**Comment by matmair** [comment]
https://github.com/inventree/InvenTree/pull/4178 might help with this - that would output an OpenApi file that can be used to generate client libraries.

**Comment by martonmiklos** [comment]
Thanks guys for your great inputs! 

I found an useful library:
https://github.com/qtrest/qtrest

If I manage got gain access to the API endpoints with some parseable format I can write a code generator for this library.

**Comment by wolflu05** [comment]
Aren't there already some code generators for swagger?

**Comment by matmair** [comment]
Swagger => OpenAPI. They use the open standard (I think they partook in the development - not 100% about that though)

**Comment by SchrodingersGat** [comment]
@martonmiklos I'm going to close this one out as it's out of scope, but keep us posted if you get something working!

**Comment by martonmiklos** [comment]
Some side info for the posterity:

I got it running with the following way:

- Grab the openapi schema from the InvenTree instance from: http://inventree-instance/api/schema/
- Add the servers section:
```
servers:
    - url: http://localhost:8000
```

- Use the OpenAPI codegen to generate code: https://github.com/OpenAPITools/openapi-generator with
```
npx @openapitools/openapi-generator-cli generate -i "InvenTree\ API.yaml" -g cpp-qt-client -o /home/mm/Projektek/inventree2/qntree/gen_src --skip-validate-spec --additional-properties=cppNamespace=InvenTree --additional-properties=modelNamePrefix=""
```

The generated code will not be compile-able see: https://github.com/OpenAPITools/openapi-generator/issues/17487
I will PR it soon to fix the issue. Otherwise the methods of the classes generated for models having field called 'valid' needs to be manually fixed.

Usage wise it is quite comfy, you could use the API key in the following manner:

```
    m_apiInstance = new InvenTree::ActionApi();

    m_partApi = new InvenTree::PartApi();
    m_partApi->addHeaders("Authorization", "Token inv-d7e8312f7b53alofa290faa71708264247f0c21c11-20231228");

    connect(m_partApi, &InvenTree::PartApi::partCategoryParameters_ListSignal, this, [=](PaginatedCategoryParameterTemplateList summary) {
        qWarning() << summary.asJson();
    });
```

**Comment by SchrodingersGat** [comment]
@martonmiklos very interesting, this might be worth adding to the documentation for others to benefit from. If there are extra information fields that we need to add to the existing schema, please raise a separate issue for that!
