### ISSUE TITLE
[FR] Make adding a description optional through the settings page

### ISSUE THREAD

**Issue by standekker** [inventree/InvenTree#4588]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

In a lot of places in Inventree there is a `description` field, like in the test templates. This description, currently, cannot be left blank.  While testing Inventree I found that lots of time adding a description would not be necessary, but Inventree forces to add text in the field before being able to submit the form.

### Suggested solution

It would be great if this would be a toggle setting under the server settings. For me it can be a global toggle to enable or disable the required description through the whole Iventree, but for other people / usecase it might be nice to, per module (like tests, parts, stock etc.) define if a description is required or optional.

### Describe alternatives you've considered

I am now manually copy and pasting the name into the description field, but this is just a workaround.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by standekker** [comment]
The template left no space for this but I do want to express my gratitude for such a great and mature piece of open source software. A big thank you, I am having lots of fun with Inventree so far!

**Comment by matmair** [comment]
Hi there @standekker !
Glad you like it so far. This could _probably_ be a good first issue if you are interested in developing it. Do you have experience with Django or python? Ping me if you want to start working on this, I would be happy to point you to the relevant developer docs and where in the system changes would need to be located.

**Comment by SchrodingersGat** [comment]
@standekker thanks for your kind words. From a "business logic" perspective, there's no reason that these fields should be mandatory. If you would like to contribute this change we would certainly be receptive to it :)

**Comment by standekker** [comment]
Sounds good! I do have some Python + Django experience so I'll have a look and see if I can fix it myself and then do a PR, I think I know where the files are located but if I get stuck I'll drop a message here. Thanks for the quick response!

**Comment by standekker** [comment]
So far I have been able to identify the following locations that have a description field that is required, but ideally should be optional from a business perspective:

- Part creation modal
- Build Order creation modal
- Purchase Order creation modal
- Sales Order creation modal
- Return Order creation modal

Feel free to comment if I have missed any!

**Comment by SchrodingersGat** [comment]
Personally I'm not opposed to just removing the "required" attribute for these fields - it won't change any business logic directly. However some users may have an existing *expectation* that this field is required?

**Comment by standekker** [comment]
@wolflu05 Yeah, I thought it would be easier to just remove the required field instead of making it required, and it also seemed excessive to make it settable, as any user can choose to use the description field or not. I interpreted this reply that @SchrodingersGat also felt that way:

> @standekker thanks for your kind words. From a "business logic" perspective, there's no reason that these fields should be mandatory. If you would like to contribute this change we would certainly be receptive to it :)

I'm still open to making it settable through the settings page, I can also see the value of that. Let me know what is preferred. In any case, maybe we should hold PR #4595 until it is decided if we want it settable through the settings page or not. #4595 now only removes the field's requirement to contain data.

**Comment by matmair** [comment]
I think making it a setting would be nice but that is more work than removing it
