### ISSUE TITLE
[FR] Make default stock status settable through settings page

### ISSUE THREAD

**Issue by standekker** [inventree/InvenTree#4589]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I am testing with Inventree and noticed that the default status of a new stock item is always `OK`. For my use case, it would be great if we can set the default stock state through the settings page. For me, it would set it default `Attention Needed` so that every new stockpart can be checked at a later date.

This may be related to #2817, but as I read it #2817 request adding a new, expanded flow. I would be helped by just being able to set the default stock status through the settings page, which is why I am making the Feature Request.

### Suggested solution

Being able to set the default stock state through the settings page.

### Describe alternatives you've considered

Manually setting the stock status to something else than `OK` upon creation of stock.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
@standekker there are several things regarding status - not only for stock. The big goal is #2817 but there are also #2903 #3501 and possibly #4289. There is some logic coupled with the stock status - so we would need to decouple that. An example could be how Snipe-It [handles it](https://snipe-it.readme.io/docs/overview#status-labels).

**Comment by standekker** [comment]
Gotcha, I wasn't aware of #2903, #3501 and #4289, those also all sound promising! I have played with Snipe-It before and I do like how they handle it. Would this feature request still be something you would be willing to add (or approve if I can add it myself) or is this something that would be quickly superseded by #2817, #2903, #3501 or #4289 and thus not worth the trouble?

**Comment by matmair** [comment]
It is probably simpler and faster to fulfil this FR now and add the other things later if/once we rewrite status in general.
There is no active dev on the mentioned issues except #3501, which I am testing in prod right now.

**Comment by matmair** [comment]
Not stale

**Comment by standekker** [comment]
Not stale

**Comment by matmair** [comment]
Not stale
