### ISSUE TITLE
[FR] Allow to hide plugin settings

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#4591]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I want to build my own select component on the settings page of my plugin and handle user input validation myself (Using the settings content mixin). This is already possible thought the `get_setting` and `set_setting` methods, but the input ist still shown on the automatically generated setting page for the plugin. (related to #4546 and wolflu05/inventree-cups-plugin#1)

### Suggested solution

Add an extra `HIDE` parameter to the settings definition in the plugin and check that before rendering here: https://github.com/inventree/InvenTree/blob/0b6e2ee592b885183ee6bf5f70b94a904b0caae3/InvenTree/templates/InvenTree/settings/mixins/settings.html#L12-L14 

### Describe alternatives you've considered

*ignore that the input is still shown*

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by wolflu05** [comment]
If nobody likes to pick this up quicker than I, I'd like to develop this, but this can take a few months until I get back.

**Comment by matmair** [comment]
Hint: We have something similar for notifications, maybe that code ca be reused/generalised.

**Comment by wolflu05** [comment]
@matmair What do you mean? Sorry, Don't get the similarity to notifications?

**Comment by matmair** [comment]
Notifications have user settings, which you can hide. This tag is used to list them in the settings https://github.com/inventree/InvenTree/blob/b062accfe26c3c1c3b847ddd88b15307f5b26bf6/InvenTree/plugin/templatetags/plugin_extras.py#L79-L82
