### ISSUE TITLE
Enable to delete the parts

### ISSUE THREAD

**Issue by sasaneritik** [inventree/InvenTree#4593]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

If i click on the Parts from Navbar and click the particular part then edit and unactive it and then delete then confirm it it gives me  IntegrityError
Error details can be found in the admin panel this error i want resolve it also not deleting assembly parts from it.

### Steps to Reproduce

1.Go to Parts
2.Select the particular part
3.Go to part action button 
4.Click on the Edit Part
5.make part unactive and submit
6.click on Delete Part

### Expected behaviour

It will delete that 
particular part

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.10.0

**Comment by SchrodingersGat** [comment]
@sasaneritik this has been fixed in 0.10.1 - https://github.com/inventree/InvenTree/releases/tag/0.10.1 - please update!

**Comment by sasaneritik** [comment]
@SchrodingersGat this has been fixed in 0.10.1 - https://github.com/inventree/InvenTree/releases/tag/0.10.1 - please update! I have already update this but it still giving me that error

**Comment by SchrodingersGat** [comment]
@sasaneritik I might have been thinking of a different but similar bug. Can you please check if the same behaviour is present on the [demo server](https://demo.inventree.org) (which is running latest version)

**Comment by SchrodingersGat** [comment]
@sasaneritik ok, can you please provide the full error message (you'll be able to find it in the admin panel - https://docs.inventree.org/en/latest/settings/logs/

**Comment by sasaneritik** [comment]
insert or update on table "part_partpricing" violates foreign key constraint "part_partpricing_part_id_24e51ec7_fk_part_part_id" DETAIL: Key (part_id)=(4) is not present in table "part_part". here is the full error message
![Screenshot (187)](https://user-images.githubusercontent.com/130160158/231964000-a43e2995-e63f-44e1-844e-1f91d387119d.png)

**Comment by SchrodingersGat** [comment]
@sasaneritik ok thanks for the error report. `0.11.0` will be released soon, which has the fix for this issue

**Comment by sasaneritik** [comment]
@SchrodingersGat welcome! let mw know please whenever 0.11.0 will be released

**Comment by SchrodingersGat** [comment]
@sasaneritik check there releases, it's been out a few days now :)

**Comment by sasaneritik** [comment]
@SchrodingersGat thanks it really mean for me!

**Comment by wolflu05** [comment]
> @SchrodingersGat welcome! let mw know please whenever 0.11.0 will be released

@sasaneritik You can also subscribe to the releases of this project. Click watch and select only releases and participation.
