### ISSUE TITLE
[FR] Bluetooth QR code scanner compatibility improvement

### ISSUE THREAD

**Issue by diodenschein** [inventree/InvenTree#4608]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I would love to use a zebra DS2278 Bluetooth barcode scanner in it’s BLE mode.

But it really likes to replace the 0x22 quotation marks in the storage locations with U+201D. 

I’m not entirely sure yet who’s to blame and I wouldn’t be surprised if this problem apppears with other scanners too.

This happens in windows and ios at least.

see here 

```
QR CODE: {"stocklocation": 1} 
Scanned: {“stocklocation”: 1}
```

### Suggested solution

I wonder if it would be possible to consider them equivalent and replace them with the right character during input?

### Describe alternatives you've considered

You can set this particular model to a classic bluetooth HID mode and that works fine but consumes more energy.

I have tried a few different code pages and keyboard localizations but it seems to persistently be a problem.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
Adding a setting to the barcode plugin to replace these chars would not be too difficult. I'll have a look into this before the next release.

**Comment by wolflu05** [comment]
What about a custom replace regex setting like we could input via sed? This can actually all happen in the browser and would be extremely generic and not specific to this scanner model.

**Comment by SchrodingersGat** [comment]
This might tie in well with some of the ideas raised in https://github.com/inventree/InvenTree/pull/4336

As this config is specific to a particular scanner, it does seem to make sense to have these a "browser" settings (not user or global)

**Comment by SchrodingersGat** [comment]
@diodenschein to clarify on this one - you're talking about the web interface, yeah?

**Comment by SchrodingersGat** [comment]
This requires some further thought before implementation, so bumping from the next release cycle

**Comment by diodenschein** [comment]
Sorry I haven't responded.
Life got in the way.

I would like to look into what's going on a bit more and have forgotten what I exactly did. 

I'll test some more cases and write them down.
