### ISSUE TITLE
Uploading company_ogo.png

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4610]
Hi im new to this but i would like to use my own comapny logo on my reports.
in: https://docs.inventree.org/en/stable/report/build/
i found following code snippet:
```
{% block header_content %}
    <!-- TODO - Make the company logo asset generic -->
    <img class='logo' src="{% asset 'company_logo.png' %}" alt="logo" width="150">
```
but when addin this to my report it fails. probebly since i have no company_logo.png. where and how do i save thsi to Inventree??

**Comment by SchrodingersGat** [comment]
https://docs.inventree.org/en/stable/report/report/#report-assets

You need to upload assets via the [admin interface](https://docs.inventree.org/en/stable/settings/admin/)

**Comment by mabroens** [comment]
thank ypu, yes this solved my question. i could not find in the help how to do this.
