### ISSUE TITLE
Inventree not using the reports after 12 time upload

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4611]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi i am playing around with customizing reports. so i took a default report and started modifying this but after 12 uploads (The revision counter is 12 or higher) then it no longer takes my changes. when i rename the same report from test.html to test1.html then it outputs the report with the new markup.

i have testted this several times for buid orders (BOM reports) as well as sales invoices. and for each it was the same result.

Br Martijn

### Steps to Reproduce

1. create a template and upload
2. change the template and upload.
3. repeat step 2 over and over

### Expected behaviour

it should just load and execute

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0
Django Version: 3.2.16

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment]
Can you try restarting the server and see if the new report is loaded correctly? There have been reports of a potential cache issue with reports which I haven't been able to isolate yet. Lmk if restarting the server addresses this for you

**Comment by mabroens** [comment]
Hi Oliver,

yes restarting the PC solves the issue. i have created a feature request to add a restart service button to the user pulldown menu (upper richt corner).

we can close this one or reach out if you need my assitence for testing

**Comment by SchrodingersGat** [comment]
> yes restarting the PC solves the issue.

The entire PC or just the InvenTree application?

What proxy are you using to host / serve the static and media files?

**Comment by mabroens** [comment]
sorry here i'm over asked. i do not know what you are looking for here.
im runnig inventree on a small linux (ubuntu 20 lts) machine. 

if you want me to type in any commands feel free to pass them on an i will.

br martijn

**Comment by SchrodingersGat** [comment]
during the installation process you would have had to setup some sort of webserver to host the "static" and "media" files - which includes the uploaded report templates. Something like apache, or nginx, etc

**Comment by LavissaWoW** [comment]
@SchrodingersGat I encountered this issue myself when iterating on a report template design.
The even more funky part is that you can even be served different cached templates between refreshes.

Our production setup is bare metal on a VM
Nginx for hosting
Running InvenTree within the standard supervisor systemd service, not "supervisord" command.

To ensure I always had the freshest template loaded, I just systemctl-restarted the supervisor service after each upload.

**Comment by SchrodingersGat** [comment]
@LavissaWoW thanks for adding your report. Clearly requiring a server restart is not a good solution, we will need to look into this one further.

**Comment by matmair** [comment]
Without looking into the code, just thinking about the architecture: The rendering is happening in the Django template engine. So it should not be any external proxies. It could be that the compiled template is cached in production in the configured cache or that the process that is rendering the report is working with a precached version (specific to the worker so that behaviour might be hard to reproduce with fresh worker nodes).

The dev settings run without template caching, production has it enabled. I really think the problem is this particular area. Caching makes generation significantly faster; it would be great to keep that.

**Comment by matmair** [comment]
Here is some info on caching in Django: https://django.readthedocs.io/en/stable/topics/performance.html#the-cached-template-loader

**Comment by SchrodingersGat** [comment]
@mabroens @LavissaWoW can you please update and check that the fix provided in #4706 has indeed addressed the issue?

**Comment by mabroens** [comment]
Okay so there's definitely something between debug enabled or not.
when i switch it on my pages format is gone no longer A4 colors are gone. no comp img is loaded. when switching it back off my report is how i would think i was.
