### ISSUE TITLE
where can i find what variables i can use for a report

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4612]
Hi Sorry if this in the wrong section but did not knwo how else to place the question.

How or where can i find out what variables i have availeble for a given report?
i think you call it context but as an example i would like to print the price for a part on the invoice. but i have no idea how i can get the price: line.part.price

br Martijn

**Comment by SchrodingersGat** [comment]
@mabroens generally this information is on the docs - https://docs.inventree.org/en/latest/report/context_variables/#orders - however that section is pretty bare (needs some work)!

One of the example reports would be helpful to you, though:

https://github.com/inventree/InvenTree/blob/master/InvenTree/report/templates/report/inventree_so_report_base.html

https://github.com/inventree/InvenTree/blob/master/InvenTree/report/templates/report/inventree_return_order_report_base.html

https://github.com/inventree/InvenTree/blob/master/InvenTree/report/templates/report/inventree_po_report_base.html

If you do glean some useful information from there that you feel should be included in the documentation, please submit a pull request to improve the docs :)

**Comment by mabroens** [comment]
Hi @SchrodingersGat, 
this helped me geratly thanks i.

still it is not working for me.
If i take the inventree_so_report.html and just upload it to my instance. using the admin > reports > sales order reports.
and then try to run it from a sales order. it throws an error.
`{"error":"TemplateSyntaxError","error_class":"<class 'django.template.exceptions.TemplateSyntaxError'>","detail":"Error details can be found in the admin panel","path":"/api/report/so/6/print/","status_code":500}`

did i miss something??

**Comment by SchrodingersGat** [comment]
> Error details can be found in the admin panel

https://docs.inventree.org/en/latest/settings/logs/#reporting-errors

Please provide information on the error that is being thrown

**Comment by SchrodingersGat** [comment]
> If i take the inventree_so_report.html and just upload it to my instance. 

The example report is already installed by default - however if you are running an older version of InvenTree the template may not work! The example I posted above was from the master / latest branch

**Comment by mabroens** [comment]
as far as i know im running master latest.
```
# Version Information:
InvenTree-Version: 0.10.0
Django Version: 3.2.16


Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

```
and the logging: WOW you guys really made an great tool.
the error in the log is:

`'render_currency' received unexpected keyword argument 'currency'`
with details:
```

Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/opt/inventree/InvenTree/report/api.py", line 683, in get
return self.print(request, orders)

File "/opt/inventree/InvenTree/report/api.py", line 237, in print
doc = output.get_document()

File "/opt/inventree/env/lib/python3.8/site-packages/django_weasyprint/views.py", line 76, in get_document
string=super().rendered_content,

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
template = self.resolve_template(self.template_name)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
return select_template(template, using=self.using)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader.py", line 42, in select_template
return engine.get_template(template_name)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
return Template(self.engine.get_template(template_name), self)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
template, origin = self.find_template(template_name)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
template = loader.get_template(name, skip=skip)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loaders/cached.py", line 58, in get_template
template = super().get_template(template_name, skip)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
return Template(

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
self.nodelist = self.compile_nodelist()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
return parser.parse()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
nodelist = parser.parse()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
nodelist = parser.parse(('endblock',))

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/library.py", line 119, in compile_func
args, kwargs = parse_bits(

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/library.py", line 266, in parse_bits
raise TemplateSyntaxError(

django.template.exceptions.TemplateSyntaxError: 'render_currency' received unexpected keyword argument 'currency'

```

**Comment by SchrodingersGat** [comment]
> as far as i know im running master latest.

`InvenTree-Version: 0.10.0` - this is the 0.10.0 stable release, which is from back in Feb - https://github.com/inventree/InvenTree/releases/tag/0.10.0

The issue here is that the template you copied relies on some newer methods (which don't exist in the version you are running). Check out the report template from the linked release above, to see the differences!

**Comment by mabroens** [comment]
Hm ok
Or should i just update my version??
If so how to do so. The version windows does mentioen a newer version is avileble


Kind regards,
Martijn Broens

[signature_598193380]

t: +31 (0)<tel:+31%206%20427%20035%2002>6 427 035 02<tel:+31%206%20427%20035%2002>
e: ***@***.******@***.***>
w: www.spectrumfiftynine.com<https://www.spectrumfiftynine.com/>

________________________________
Van: Oliver ***@***.***>
Verzonden: Sunday, April 16, 2023 12:36:11 PM
Aan: inventree/InvenTree ***@***.***>
CC: Martijn Broens ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [inventree/InvenTree] where can i find what variables i can use for a report (Issue #4612)


as far as i know im running master latest.

InvenTree-Version: 0.10.0 - this is the 0.10.0 stable release, which is from back in Feb - https://github.com/inventree/InvenTree/releases/tag/0.10.0

The issue here is that the template you copied relies on some newer methods (which don't exist in the version you are running). Check out the report template from the linked release above, to see the differences!

**Comment by SchrodingersGat** [comment]
At the moment, updating won't address this as the report I linked has not been included in a stable release. You'll need to use a version of the report which works with `0.10.0`

- https://github.com/inventree/InvenTree/blob/0ffe7861aab9a35d1619f4542fbd9f13c07a6b38/InvenTree/report/templates/report/inventree_po_report.html

**Comment by mabroens** [comment]
Hi @SchrodingersGat sorry to come back to this. what are the plans for adding the form to a release that i can use on my end and what/how whould be the easiest steps to get it working on. I tried with the older version like you mentioned but was unseccessfull. And i love the tool more by the day. 

Like mentioned my InvenTreeadmin/about InvenTree page does mentionen "Update availeble"  but i have no clue how to update it (sorry not that fammiliar with lilnux, but i'll manage if i know how to).
```
# Version Information:
InvenTree-Version: 0.10.0
Django Version: 3.2.16


Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

```

Thnx Martijn

**Comment by mabroens** [comment]
if i remember correct i used the quick setup: wget -qO install.sh https://get.inventree.org && bash install.sh

**Comment by mabroens** [comment]
yes i use the quick install. found the history.

in the link you gave i also found:
### Udating InvenTree
`apt install --only-upgrade inventree `
 and just ran that command. seems like it did it. InvenTree now shows version 0.11.0
```
# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18


Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

```

Can it be that it now requies some time do what ever?? my subscribed parts are 0 used to be 10 latest parts is 10. outstanding PO is "Loading data" and when i click the **Parts** its completely empty. same for stock.
when i say completly empty i mean the screen shows: Part 103 part categories 46

Build Orders ionly shows the header
Buy > Suppliers only header etc
Stock shows Stock Items 216 and 9 locations.

could you help me out pls.

Br Martijn

**Comment by SchrodingersGat** [comment]
You may just need to refresh your browser cachce - https://docs.inventree.org/en/latest/faq/#feature-x-does-not-work-after-update

Any further questions, please open a new issue, rather than continuing this closed one on a different topic.

**Comment by mabroens** [comment]
perfect, that solved it.

thanks, should have thought about that

Br Martijn
