### ISSUE TITLE
Add restart option to admin pulldown menu

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4614]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

would it be possible to add a restart service option to the admin/user pull down maneu in te upper right corner

### Suggested solution

im writing templates and it seems like a cash issue. since after 12 uploads of a template it n longer takes the template but falls back to an older template version. restarting the pc solves this issue but i guess reatrting the service would do the same trick, just don't know how to.

### Describe alternatives you've considered

restarting the machine but that is rediculous

### Examples of other systems

no where found

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
This is a very heavy hammer for a specific (but difficult) problem. Adding a general "restart server" button is not something I want to support - it introduces a lot of security concerns and also we cannot know the specifics of any given installation.

The template cache issue does need addressing, though! I have been stumped on this one for a while now.

**Comment by mabroens** [comment]
sorry not restart server but service

**Comment by matmair** [comment]
I am not sure we can restart the service from within and adding permissions to do so externally without creating huge security problems is hard. I would caution against quick shots in this regard.
