### ISSUE TITLE
[CI] PIP workflow is broken

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4616]
Discovered in https://github.com/inventree/InvenTree/pull/4615

A recent [update to PIP](https://pypi.org/project/pip/23.1/) has broken our CI build:

```bash
 Collecting pip>=22.2 (from pip-tools==6.12.3->-r requirements-dev.txt (line 240))
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    pip>=22.2 from https://files.pythonhosted.org/packages/ae/db/a8821cdac455a1740580c92de3ed7b7f257cfdbad8b1ba8864e6abe58a08/pip-23.1-py3-none-any.whl (from pip-tools==6.12.3->-r requirements-dev.txt (line 240))

Notice:  A new release of pip is available: 22.0.4 -> 23.1
Notice:  To update, run: pip install --upgrade pip
Error: Process completed with exit code 1.
```

The `--requires-hashes` flag (which is enforced because we have hashed our pip dependencies) now appears to be more proscriptive. 

Currently the "solution" is to pin the pip version used in our CI tools to the previous version. This cannot be a "long term" solution and so we'll need to fix this properly.

**Comment by matmair** [comment]
@SchrodingersGat including the hashes is a security feature against supply-chain attacks on pypi. They are stepping up their 2fa requirements etc. so I think it would be fine to remove the hashes. Should we go ahead with that? The change is 2 lines and a regeneration.

**Comment by SchrodingersGat** [comment]
As we are pinning versions, I'd be happy with that I think. Are you able to submit this?

**Comment by matmair** [comment]
PR is submitted https://github.com/inventree/InvenTree/pull/4627
