### ISSUE TITLE
IPN uniqueness evaluation including revision

### ISSUE THREAD

**Issue by gunstr** [inventree/InvenTree#4618]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Would it be possible to include the Revision in the IPN uniqueness evaluation in the same way as for part description?

In all tables I then see revision duplicated in both the IPN and Revision column, If I understand correctly the "last used serial number" would then also be evaluated for the base number and not restart for each revision.

Sorry it there is already a setting controlling this that I have not found.

### Suggested solution

Include the Revision in the IPN uniqueness evaluation

### Describe alternatives you've considered

Currently I need to include the revision in the IPN also.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Hi there @gunstr 
It would probably be possible with some small adaptations in core code, but not with plugins currently.
You are correct that it would probably need an adaption for the serial counter. I think that could be a challenge as we allow any chars in the revision field and we would probably need a migration for that.
Thoughts @SchrodingersGat

**Comment by SchrodingersGat** [comment]
@gunstr I'm not fully sure that I'm following what you are asking for here

Currently the "PART_ALLOW_DUPLICATE_IPN" setting just allows duplicate IPNs across part, the "description" of the part is not checked as part of this?

**Comment by gunstr** [comment]
@SchrodingersGat Sorry it was a typo from my side that made this confusing. It should be "name" - not "description"... Let me try to explain:

For each new part the name has to be unique. If you add a revision multiple parts with the same name can be created. Correct?
Also (and here I'm not sure I have the complete picture) those revisions will be treated as completely separate parts with their own BoM, pricing etc. Only one exception I have found is that the serial counter will use the same number pool for all revisions - perfect!

I use IPN's and as i need them to be unique I set PART_ALLOW_DUPLICATE_IPN to false which is fine for most parts.

Some parts also have different revisions and thus I currenty have to assign a new IPN for each revision.

So my question is if it would be possible to allow one IPN for multiple revisions also when PART_ALLOW_DUPLICATE_IPN is set to false in the same way as one name can have multiple revisions?

More clear now?

**Comment by gunstr** [comment]
@matmair I [found the section in the code that validates the IPN](https://github.com/inventree/InvenTree/blob/070e2afcead7172e9436dc9b1510ff066dfa4f6e/InvenTree/part/models.py#L787) and it confirms that with PART_ALLOW_DUPLICATE_IPN set to false the same IPN cannot be used for different revisions.

I was thinking a bit more on this but I have to admit I'm a bit on deep water here. If I set  PART_ALLOW_DUPLICATE_IPN to true instead can I then create a plug-in that validates that the IPN+Revision is unique? You mentioned it's probably not possible. Is that because the validation mixin cannot be used to validate the uniqueness vs other parts so that would be a dead end? I looked at the validation plugin samples, and it seems to only act on the actual part and cannot reference other parts in the database.

**Comment by matmair** [comment]
@gunstr we do not expose the revision of the current part to the validation function so you can not validate it.

**Comment by gunstr** [comment]
@matmair Thanks, then I understand why a plugin is not an option.

**Comment by SchrodingersGat** [comment]
@gunstr @matmair I would disagree here, I think that you certainly can have a custom validation routine for the IPN which operates exactly as you require.

From the code (linked above):

https://github.com/inventree/InvenTree/blob/070e2afcead7172e9436dc9b1510ff066dfa4f6e/InvenTree/part/models.py#L574

And from the plugin code:

https://github.com/inventree/InvenTree/blob/36d17c082bcd4e22cb2174aa3f23718f49b52640/InvenTree/plugin/base/integration/mixins.py#L65

The "part" instance is passed to this function, so you have access to any attribute of the part. Writing a custom plugin here would be the correct approach IMO

**Comment by gunstr** [comment]
Thanks a lot @SchrodingersGat. I will give it a try to write a plugin in the coming days and let you know.

**Comment by gunstr** [comment]
@SchrodingersGat I have created a basic implementation for an IPN validation plugin and I can check various aspects on the IPN itself and also other attributes on the new part like that there is a revision assigned by accessing part.revision.

But I cant figure out what mixin I need to add to the plugin to be able to query all existing parts in the database to validate that the IPN+revision on unique. I believe a test similar to what you do for the name in the core code should be done, but then only for IPN+revision

https://github.com/inventree/InvenTree/blob/070e2afcead7172e9436dc9b1510ff066dfa4f6e/InvenTree/part/models.py#L797-L799

Appreciate if you can guide me in the right directions.

**Comment by SchrodingersGat** [comment]
> But I cant figure out what mixin I need to add to the plugin to be able to query all existing parts in the database to validate that 

I don't think you need to add any other mixin? You should have direct access to make the same database calls as you provided in your example above?

**Comment by gunstr** [comment]
Oh, that I did not understand.

I would assume I then at need some more import(s) on top of what you have in the IPN validation sample the be able to do a similar call as you do in the part/models code? I tried and it seems I cannot use the Part class right now, so I have obviously missed something...

https://github.com/inventree/InvenTree/blob/070e2afcead7172e9436dc9b1510ff066dfa4f6e/InvenTree/plugin/samples/integration/validation_sample.py#L3-L8

**Comment by gunstr** [comment]
I added
`from part.models import Part`
to the plugin.

With the quick testing I have done it seems to work like a charm. I can now set `PART_ALLOW_DUPLICATE_IPN to true` and the plugin will raise an error if the combination of `IPN+Revision` is already existing!

The validation method in all simplicity is only:

```
def validate_part_ipn(self, ipn: str, part):  
    if Part.objects.exclude(pk=part.pk).filter(revision=part.revision, IPN=ipn).exists():   
        raise ValidationError("Part with this IPN and Revision already exists.") 
```

**Comment by SchrodingersGat** [comment]
Glad you got it sorted with something simple :) if the plugin is public would you be willing for us to add it to the plugin samples page?

**Comment by gunstr** [comment]
Sure, I'm happy to share. I have the plugin on my local installation right now, will fix a git repo and let you know when it's done.

**Comment by walkermc20** [comment]
> 

Were you able to get this uploaded?  We're in the same boat and would love to implement something that's already complete. 💯

**Comment by gunstr** [comment]
It's a bad conscience of mine but give me a couple of days to fix it. I believe I had a bit too high ambition to clean it up and document but If you are OK with it I will just upload the code in all it's simplicity as a start. I have used it for a month now and it works perfectly fine :-)

**Comment by SchrodingersGat** [comment]
@gunstr looking forward to seeing what you've come up with :)

**Comment by gunstr** [comment]
Now the plugin is uploaded, you find it [here](https://github.com/gunstr/inventree_ipn_validator). I have only installed the plugin locally as I have never done any PIP packaging. This could be a good case for me to learn but I thought it's better not to wait until I have done that.

@walkermc20 appreciate if you can test and and let me know if it works for you also.

@SchrodingersGat However, I tried to move it out from the `src/InvenTree/plugins` directory in my installation by pointing the `plugins_plugin_dir` variable in the config file to a custom directory where I put the plugin. But when I do so it will not be found by the system. I can't really figure out what I'm doing wrong - are you aware of any common mistakes that might cause this? It's not really a problem for me to keep it inside the src tree but as you do not recommend to do so in the documentation I thought it would be better to get it working...

As a little side note I found that [the documentation](https://docs.inventree.org/en/latest/start/config/#plugin-options) refers to `plugins_plugin_dir` as the variable name while in the [config_template.yaml](https://github.com/inventree/InvenTree/blob/0c475521994346e65688e834bc4f7552b9e4b1b5/InvenTree/config_template.yaml#LL124C7-L124C7) is `plugin_dir`.

**Comment by matmair** [comment]
@gunstr cool plugin!
If you want a hint about Python packaging you can take a look [at this repo](https://github.com/matmair/inventree-apprise) or the [meta-package](https://github.com/matmair/inventree-meta-plugin) I use for packaging and creating new plugins.

**Comment by andrewwetzel23** [comment]
I am working on installing this plugin with @walkermc20 . I have placed the ``validate_ipn_unique`` directory in my ``opt/inventree/Inventree/plugins`` and have adusted my config.yaml file so that ``plugins_enabled: True``. 

Yet I am still getting an ``External plugins are not enabled for this InvenTree installation`` error on my settings/plugins page. Any advice?

**Comment by SchrodingersGat** [comment]
@andrewwetzel23 could be a few things:

- Have you restarted the server?
- Anything set in your environment variables will override the values in `config.yaml`

**Comment by andrewwetzel23** [comment]
Yes, I have restarted the server using: ``docker stop inventree-server`` and then ``docker start inventree-server``. 

Unless there is something out of the box that would overwrite those values it shouldn't be. I haven't changed to much from the boiler plate docker install.

Is there anything I need to change in the ``setup.py`` script? I saw there are function calls there that look like they may effect plugins.

**Comment by gunstr** [comment]
My installation is Bare Metal (on a VM), unfortunately I can't be of so much help on Docker. The only issue I had was that I could not move the plugin outsisde the InvenTree source code as I mentioned above.

**Comment by SchrodingersGat** [comment]
https://docs.inventree.org/en/latest/extend/plugins/install/#enable-plugin-support

**Comment by matmair** [comment]
@andrewwetzel23 that was actually already developed but is not released at the moment.

**Comment by wolflu05** [comment]
Ref: #4964

**Comment by gunstr** [comment]
@SchrodingersGat I guess this issue can be considered as resolved now and  can be closed? If you want to add a [link to the plugin](https://github.com/gunstr/inventree_ipn_validator) to the samples page please feel free to do so.

**Comment by matmair** [comment]
@gunstr we can add it to the [plugin repo](https://inventree.org/plugins) if you want.
