### ISSUE TITLE
[FR]Print multiple labels on a sheet

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#4626]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I used to print storage labels to pre-cut self-adhesive A4 pages (in 3x8 ordering).
I could print out labels with InvenTree in the necessary size, however they will be added as separate pages.
I know that it might be said that this feature should be the task of the PDF printer too, but in Okular only the CUPS provided options are set (1, 2, 4, 6, 9, and 16) which does not aligned to my needs. Som

### Suggested solution

I would add two parameters to the label templates: 
- number of rows per page
- number of columns per page
- padding in mm

### Describe alternatives you've considered

Look for some PDF readers supporting this.

### Do you want to develop this?

- [X] I want to develop this.

Here is a list of the ideas collected over the PR/issue:

- [x] Mention in the docs that fixed positioning might lead to improper positioning in the paginated labels.
- [x] Add option to eliminate adding redundant styles to each rendered label (see. item nr. 4 here: https://github.com/inventree/InvenTree/pull/4805#pullrequestreview-1444267023)
    - A) Add ability to upload the paginated template
    - B) Add option to specify "global style" per label template
- [ ] Add edgecuts marking border feature  (see. item nr. 6 here: https://github.com/inventree/InvenTree/pull/4805#pullrequestreview-1444267023)  
- [ ] Add option to skip first n label see #4929
- [ ] Add configurable border spacing, page margin etc. to support "Avery style labels" (see https://github.com/inventree/InvenTree/pull/4805#issuecomment-1567037541)

**Comment by matmair** [comment]
This sounds a lot like https://github.com/inventree/InvenTree/issues/2872

**Comment by SchrodingersGat** [comment]
I think it is different to #2872 but it **is** similar to https://github.com/inventree/InvenTree/issues/4167

This may be tackled in two ways:

1. Add the label settings you described to the label printing functionality in general
2. Write is as a plugin

I think I would prefer 2) as I expect there would be a lot of variations in how this could be implemented. I would also think this would go hand-in-hand with #4167 

Essentially, allow a plugin to receive multiple labels "in one go" and the plugin (in this instance) would print them all to a single page

**Comment by martonmiklos** [comment]
Hi folks,

I submitted a WIP PR because I would like to ask for some preliminary feedback.

Things what I am unsure about:
I basically generate raw HTML tables during label generation and inject the templated label contents into the cells:

https://github.com/martonmiklos/InvenTree/blob/add_multipage_label_print/InvenTree/label/api.py#L230

The raw HTML does not look nice in the code itself, I was wondering if I could use a template for that. (Injecting template generated HTML into a template.) 

I think I could alter the template_name here:
https://github.com/martonmiklos/InvenTree/blob/add_multipage_label_print/InvenTree/label/models.py#LL245C20-L245C20
to point my template, but how can I alter/add the template fields? Are they part of the request?

I started to add some eye candy (border settings, page size preselector) to the settings as it was discussed in the #4167 , but I do not know how could I alter the form field's order (I want to move the non-model preselect fields before the page size fields).  I read many suggestions on the internet, but none of them worked so far. At the moment I have some code here which re-alters the order:
https://github.com/martonmiklos/InvenTree/blob/add_multipage_label_print/InvenTree/label/admin.py#L27
but it does not working.

Border wise I would like to extend the combobox with a custom option which would reveal a text input where custom CSS could be entered, but it needs additional Javascript tweaking.

**Comment by matmair** [comment]
@martonmiklos you can pass additional context to the template rendering method. That would be much cleaner.
I think we should focus on the backend functions first and then get the front end going.

**Comment by martonmiklos** [comment]
> @martonmiklos you can pass additional context to the template rendering method. That would be much cleaner. I think we should focus on the backend functions first and then get the front end going.

Thanks! Creating a multipage_label

**Comment by martonmiklos** [comment]
Quick question: how should I pass template path here?

https://github.com/martonmiklos/InvenTree/blob/add_multipage_label_print/InvenTree/label/models.py#L278

I have some ideas by using the os.path.dirname(__file__) , but I guess there are some constants refering to the Inventree path.

**Comment by SchrodingersGat** [comment]
You should just be able to pass it as "multipage_label_base.html" or "label/multipage_label_base.html" due to the way that the django template lookup functions. The templates should be directly available if they are placed in the right folders

**Comment by martonmiklos** [comment]
Ah it works like a charm, thanks!

**Comment by martonmiklos** [comment]
Hi folks, 

I started to refactor the print method as @SchrodingersGat  requested to separate functions and I got confused about how to deal with the case when plugins used. Passing the paginated HTML tables in PDF and PNG would not make much sense in some cases I think. I would rather leave the multipage rendering to the plugins it self. What do you think?

**Comment by SchrodingersGat** [comment]
@martonmiklos good question, and yes it is starting to get quite complex. In your current implementation, is the "multi page printing" aspect (i.e. placing multiple separate labels onto a single page) defined by the label template itself? If so, if you *do not* paginate as per the instructions in the template (`.html`) file, aren't you effectively disregarding the instructions of the template?

I'm not sure of a great answer yet. LMK a bit more about the current state of your implementation :)

**Comment by martonmiklos** [comment]
> @martonmiklos good question, and yes it is starting to get quite complex. In your current implementation, is the "multi page printing" aspect (i.e. placing multiple separate labels onto a single page) defined by the label template itself? 

The placing multiple separate labels is defined by the label/page ration and the code, however the cell's content is rendered using the user supplied label template.

Basically this is what I do: determine the grid by the label/page geometry ratio.
Render each label into with the user uploaded template. 
Put the rendered cells into tables per page.
I render the tables into a "builtin" multi page template. (Which is responsible for the table borders styling, the page size and the margin removals.)
The in the end this HTML got rendered into PDF.

> If so, if you _do not_ paginate as per the instructions in the template (`.html`) file, aren't you effectively disregarding the instructions of the template?

Well some parts of the existing templates (absolute positioning for e.g.) will be disregarded/not utilized as they utilized in a single label printing, however I think it could be a "fair" limitation if we add a note in the documentation (what I have not done yet).

**Comment by martonmiklos** [comment]
@SchrodingersGat  let me follow the started over the another issue discussion here:

> I'm just considering how close your implementation in https://github.com/inventree/InvenTree/pull/4805 is to being "ready", and whether we ship this now with the understanding that it will later change?

From my perspective the #4805 is feature complete for merging. Yesterday I rebased to the current master and noticed that new label type (BuildItemLineLabel) appeared so some plumbing needed what I can do today.

**Comment by martonmiklos** [comment]
Hello Folks, I am Miklos's wife. Miklos managed to break both forearms, so he is not able to type. He said he would be glad if someone would be able to move this forward.

**Comment by SchrodingersGat** [comment]
> Miklos managed to break both forearms, so he is not able to type.

Oh no! @martonmiklos I hope you have a speedy recovery!

**Comment by SchrodingersGat** [comment]
Not stale
