### ISSUE TITLE
Is there a way to show more stock information on stock allocation?

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4651]
### Discussed in https://github.com/inventree/InvenTree/discussions/4650

<div type='discussions-op-text'>

<sup>Originally posted by **An40n1** April 21, 2023</sup>
I usually sort and track my parts by purchase order but it doesn't show up when allocating stock on Build Orders, is there a way of displaying it? It shows the Batch, and I could just put the purchase order on Batch but I would prefer not to duplicate information and I would save a couple steps. 

![23423423](https://user-images.githubusercontent.com/84796251/233599808-e24d5b57-d5ff-4bd8-8dbf-f9b78a1bfdd6.png)
</div>

**Comment by SchrodingersGat** [comment]
Not stale. In the [new UI](https://github.com/inventree/InvenTree/pull/5011) perhaps a hover-over approach would allow more information to be displayed here.

**Comment by walkermc20** [comment]
This would be pretty cool.

**Comment by walkermc20** [comment]
Can this be un-stale'd?  I'd really like the "hover-over for more info" approach...also the idea about selecting what info shows up on these drop-downs is genius.

**Comment by SchrodingersGat** [comment]
This will not likely receive any attention until the new ui is in fulls wing

**Comment by walkermc20** [comment]
Makes sense.  Thanks for the info.  👍

**Comment by SchrodingersGat** [comment]
Not stale, waiting for the new ui
