### ISSUE TITLE
Interface fails to show parts, orders, inventory, etc.

### ISSUE THREAD

**Issue by An40n1** [inventree/InvenTree#4654]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Iventree is failing to show the content in the app in general. Starting with the sections from the top-left menu, those can't load the items and the page seems empty:

![imagen](https://user-images.githubusercontent.com/84796251/233650873-9b9bd68f-da63-48e2-b4dd-c059fd34d494.png)

This is just an example but is the same with every other section. Despite this seems like parts are there and the database is fine as you can see here, when looking for parts or anything else, it is shown just fine:

![imagen](https://user-images.githubusercontent.com/84796251/233652100-04fa2223-2e07-4176-8794-1b3339f2abd8.png)

Also seems like its not loading part page properly as it does not show the menu in left:

![imagen](https://user-images.githubusercontent.com/84796251/233652858-c8751e58-3205-4a5c-a8a7-71c222b27c84.png)

I also just noticed that i can't open the "about inventree" windows unless i'm the settings page.

All of this started happening after updating from 0.10.1 to 0.11.0.

### Steps to Reproduce

Update from 0.10.1 to 0.11.0

Process followed:

1. 
```powershell
docker compose run inventree-server invoke update
``` 
2. 
```powershell
docker compose down
``` 
3. 
```powershell
docker compose pull
``` 
4. 
```powershell
docker compose run inventree-server invoke update
``` 
5. 
```powershell
docker compose up -d
``` 

### Expected behaviour

It, as far as i know, should look pretty much like in 0.10.1 isn't it?

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18
Commit Hash: 593a716
Commit Date: 2023-04-18
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
https://docs.inventree.org/en/latest/faq/#feature-x-does-not-work-after-update

**Comment by An40n1** [comment]
> https://docs.inventree.org/en/latest/faq/#feature-x-does-not-work-after-update

Oh, sorry I didn't see that. It worked with just ctrl+F5, thank you!
