### ISSUE TITLE
Populating demo dataset in dev sets base URL to demo.inventree.org

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#4656]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Server setting "Base URL" is set to "https://demo.inventree.org" when populating DB with demo dataset.
While not surprising given it's after all the _demo_ dataset, this is not obvious at a glance, and it produces some problematic unintentional behaviour on occasion. Any URL generated via `construct_absolute_url` will point to the demo site.
If you don't pay attention, then you'll wind up on the demo after clicking the link to a server error report. As the datasets are the same, and if you've logged into the demo recently, you might miss completely that you just moved to the online site from localhost.

### Steps to Reproduce

1. Setup a docker dev server
2. Install demo dataset on dev server using `docker compose run inventree-dev-server invoke setup-test`
3. Base URL in settings will now be "https://demo.inventree.org"

### Expected behaviour

Populating dev server with demo data should either
1. Not set base URL to demo.inventree.org
2. Warn users that base URL is now set to demo site
3. Other solution that has not occurred to me

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0 dev
Django Version: 3.2.18
Commit Hash: 9198b5239
Commit Date: 2023-04-20
Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment]
@LavissaWoW good point, and I still run into this from time to time when running a dev setup locally with the demo dataset.

**Comment by SchrodingersGat** [comment]
@LavissaWoW  @matmair I'm wondering what the "cleanest" way to implement this is. Currently the demo dataset is populated with the "demo.inventree.org" base URL which is not great for anyone using the dataset for their own testing.

My thoughts at the moment:

1. Allow base_url to be overridden by an environment variabl (and in this case, cannot be edited)
2. Fallback to the configured setting
3. If no "base_url" configured as part of 1) or 2) use the request URL itself when forming absolute URLs

Any objections to such an approach?

**Comment by matmair** [comment]
@SchrodingersGat sounds good!

**Comment by SchrodingersGat** [comment]
Thanks for the feedback, I'll submit a fix along those lines
