### ISSUE TITLE
[feature request] Add lang support for docs 

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4664]
### Body of the issue

Ref: https://github.com/inventree/inventree-docs/issues/426

**Comment by matmair** [comment]
@Xvonthe are you still in this or can we close it?

**Comment by matmair** [comment]
Closing due to lack of interest

**Comment by wolflu05** [comment]
Nowerdays there also exists _pretty_ good one click translators also included in browsers which are much better than half translated/out of date docs.
