### ISSUE TITLE
Documentation for vscode setup

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4670]
### Body of the issue

https://github.com/inventree/inventree-docs/issues/350

**Comment by wolflu05** [comment]
Where should we place that documentation?

**Comment by SchrodingersGat** [comment]
Under the setup / development space, a workflow for "setup a development environment in vscode" would make sense

**Comment by matmair** [comment]
@SchrodingersGat @wolflu05 can we close this with the devcontainer docs now being included?

**Comment by SchrodingersGat** [comment]
Yep, thought we had already closed it!
