### ISSUE TITLE
Visual overhaul 

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4674]
### Body of the issue

https://github.com/inventree/inventree-docs/issues/271

**Comment by matmair** [comment]
@SchrodingersGat is this still relevant? Seeing how beautiful/interactive other solutions can be I am even wondering if we want to switch out the framework.

**Comment by matmair** [comment]
I like docusaurus or the thing by stripe

**Comment by matmair** [comment]
https://stripe.com/blog/markdoc

**Comment by SchrodingersGat** [comment]
If we are going to change frameworks, I'd like to pick something which we can use for the website and the docs. Still keep them separate, but use the same tech stack. 

This will mean less work (learning curve) to maintain two different stacks and also allow us to maintain a more consistent visual look-and-feel

**Comment by matmair** [comment]
To add to this: unifying website and docs into one framework would be cool.

**Comment by matmair** [comment]
Still relevant

**Comment by SchrodingersGat** [comment]
I don't think there is much appetite for this any more. The docs are working well for us, we can tweak them visually but the readthedocs/mkdocs combination is functional
