### ISSUE TITLE
Solutions / How-To Section

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4676]
### Body of the issue

https://github.com/inventree/inventree-docs/issues/211

**Comment by SparkeyinVA** [comment]
Have you been able to think any more about this How-To Section?  If you are still open, I would be open to giving it a go.  I have a copy of Help-n-Doc Version: 8.2.0.286 (x64) Professional Edition.  I use it for the help section on my github.io page.

**Comment by matmair** [comment]
It is very low on the priorities list for me, feel free to tackle it. The docs are written in mkdocs and located in /docs/docs, maybe take a look at this page to see how it can be written: https://github.com/inventree/InvenTree/blob/master/docs/docs/faq.md

**Comment by SchrodingersGat** [comment]
@SparkeyinVA this would be much appreciated! W have very limited dev time, and only a small portion of that does go into documentation!

**Comment by SparkeyinVA** [comment]
@matmair @SchrodingersGat , I checked and Help-n-Doc can output a markdown document.  I will work on a few pages in in Markdown and html and share them.  If they are acceptable I will be happy to contribute what I can.

**Comment by matmair** [comment]
Still important
