### ISSUE TITLE
Purchase Order Items destination is not populated

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#4680]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Destination column is not populated in "Purchase Order Items" after "Receive Purchase Order Items" form is submitted with some destination.
Table Refresh and page reload does not help.
![изображение](https://user-images.githubusercontent.com/10057327/233792310-a3796dfe-b4e2-4551-9745-a58769101959.png)

### Steps to Reproduce

1. Create PO
2. Add line item without destination
3. Press "Issue Order" button
4. Press "Receive Line Item" button for item created at 2.
5. Select location, press Submit.

### Expected behaviour

Destination column has location selected in 5.

Actual behavior:
Destination column is empty "-".

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18
Commit Hash: 593a716c2
Commit Date: 2023-04-18
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'Part Import', 'slug': 'import', 'version': 1}]

**Comment by SchrodingersGat** [comment]
If I am reading you correctly, this is expected behaviour. The "destination" column applies to the purchase order line item, not the received stock items. If you select the destination at point of receiving, this information is *not* back-populated into the original line item. It will, however, be recorded for the incoming line item.

The correct approach is to specify the destination for the line item before receiving, and that value is used to receive the line items

**Comment by sintech** [comment]
If it is coded as you described then it is not a bug.
But in previous versions behavior for before and after receiving was the same as far as i remember.

For me it looks a little bit strange when you have to specify destination for items even before you bought (ordered) them. 
I see two usecases here: 
1. Buy additional stock of already existing item with storage location.
2. Buy completely new item, and create/select location during "Receive item" phase.

**Comment by SchrodingersGat** [comment]
> For me it looks a little bit strange when you have to specify destination for items even before you bought (ordered) them.

You don't *have* to at all. The *destination* field indicates where the items should go when received. In a company with multiple departments it is helpful to be able to communicate this information to whoever is receiving the order. But it is not required.

**Comment by sintech** [comment]
> You don't _have_ to at all. The _destination_ field indicates where the items should go when received. In a company with multiple departments it is helpful to be able to communicate this information to whoever is receiving the order. But it is not required.
Thank you. What I looked for was near, in "Received Stock" tab. ;)
