### ISSUE TITLE
completing purchase =order for  Virtual parts fails.

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4685]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Hi i have a virtual part, a SW licence that i need to purchase and sell along with a product. so i create a SW lic. 
So i create a part ProduuctX FW Lic. make it a **component, Purchaseable, Virtual and Active.** so far so good

when i look a the BOM for the product requiring this lic. i can see that since i have no stock i can not build the part. hence i create a purchase order and send it out. next i go for **received items** and mar it as cpompleted i received all  qty. 
but now im not able to proceed. the form says ....

i had to go back in the part and disable virtual to complete the order

### Suggested solution

a virtual component should either be A treated as a normal part or should not be blocking the build. or i am missiing something. if so please add this to the help file or prefereable to the text when hoovering above the virutal

### Describe alternatives you've considered

made it non virtual

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
This is probably more of a higher level discussion of what a virtual part "means", and what actions should be made available for virtual parts. Currently some actions are prohibited for parts which are marked as virtual (e.g. purchase orders) but this is not necessarily the best approach.

I'd be interested in feedback on how people use virtual parts, or would intent to use them

**Comment by mabroens** [comment]
A virtual part to me would like the comment stated before as example a SW license which I:

need to purchase and sell along with the product
do not need to purchase but still sell since i made it my self
so a virtual part for me is like a normal part except for the fact that i might not care how many i have in stock. so the BOM does not complain i can not build it.

currently i can not close the form if it has a virtual part in. then you get an error.

Br Martijn

**Comment by simonkuehling** [comment]
Just found a similar issue with virtual parts in Sales Orders: I would like to use virtual parts for non-physical items like a hourly rate for design work or a technical service fee for example. But I cannot add virtual parts as line items to a Sales Order currently.

I would agree with @mabroens on the definition that virtual parts should mainly just not have any stock management - but they can be purchasable and salable if defined as such.

@SchrodingersGat I could take a look into the changes necessary, if you share this objective...

**Comment by SchrodingersGat** [comment]
The issue there is that purchase and sales order require stock, either incoming or outgoing. So, some other considerations would then have to be made, if you want to be able to assign "stock" (which doesn't exist for a virtual part) to a sales order

**Comment by simonkuehling** [comment]
Well, I see your point... Thinking about that a bit further I realize that it might be actually beneficial for our internal processes to not use virtual parts for these items, but instead just use regular "parts/assemblies" that have a measurement unit of "hours" for example. The advantage would be that I can issue build orders for these (in the meaning of "work orders") in order to assign them to users or departments.

The "build output" is measured in hours then and can be used like physical stock items for completing a sales order.

I will give that a proper test here, so for now I suggest we can close the issue again.
