### ISSUE TITLE
[FR] Exclude inactive items from low stock

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#4688]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When looking at low stock items it would be nice to be able to exclude inactive items. 

When items are inactive I'm not concerned if they are low or out of stock

### Suggested solution

Update low stock query to exclude items that are set to inactive. If users still want to view these then you can always have a option to:
View low stoock items (Enable/Disabled) in one of the config settings. 

### Describe alternatives you've considered

Currently using a php script with a mysql statement to render a page on a remote apache server but this is not ideal.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@StormTrooper are you talking about the "home page" on in general table queries? If you are accessing this data via the API you can already limit the results with `&active=False` (for example)
