### ISSUE TITLE
move/locate/relocate database

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4690]
### Body of the issue

Hi Guys,

i could not find it so i'm asking it here.
I currently run InvenTree on a smal linux machine all local. but would like to move my database, which is growing day by day, from this pc to my NAS or a cloud server. that way i have a backup incase the drive crashes for what ever reason.

so How can i find out:
- what database am i running
- where is it currently located
- how can i move it to a diffrent location
- where are the current backups located? i know it makes a daily backup but where does it go?

br Martijn

**Comment by SchrodingersGat** [comment]
I think most of these questions are answered here:

- https://docs.inventree.org/en/latest/start/backup/
- https://docs.inventree.org/en/latest/start/migrate/

**Comment by matmair** [comment]
Please try to keep issues to actionable things like bugs (one per issue) and defined feature requests. Discussions are better suited for questions with a longer answering threads.

**Comment by matmair** [comment]
did you achieve your goal @mabroens ? Can we close this?

**Comment by mabroens** [comment]
@matmair thnks for reminding me. been to busy suing the tool :-) and other work.
i had a look at: https://docs.inventree.org/en/latest/start/backup/ which seems like what i'm llking for. Using DropBox as a backup location is ok for me.

only thing that was not clear is where i can find these configuration settings:
![image](https://github.com/inventree/InvenTree/assets/130482028/8c240e6e-16fa-4208-bb4d-0f5ea2b4b91b)


can you guid me here? i already had a look at the admin and settings page but nothing for backup except off course the interval.
![image](https://github.com/inventree/InvenTree/assets/130482028/5551d331-9b38-4c5b-827f-7f80f9df911c)


Br Martijn

**Comment by wolflu05** [comment]
You can set these options like marked as environment variables if you use docker, it's as easy as adding them to the .env file.

**Comment by mabroens** [comment]
hm but im running bare-metal. 
how do i do this then?

sorry for asking

**Comment by matmair** [comment]
You can set environment variables on linux as well. Or you could use the [config file](https://docs.inventree.org/en/latest/start/config/#configuration-file).

**Comment by mabroens** [comment]
Hi @matmair,

i am still not able to find any of the files you are refering to.
when i do an ls-al on ~/inventree i get following:
![image](https://github.com/inventree/InvenTree/assets/130482028/bfaacd80-ee55-42ea-a577-0f2c01481fdd)

so as you can see there is no `config.yaml` 

i do see some stuff mentioing docker which i find strange sine i am running bare-metal, we have verified that before.

specifically since my system is now somehow messed up an no longer working afte installing python3.9 which is required for Inventree 0.12.0 i am now no longer able to login. and we even think we need to reinstall ubuntu on our machine :-( 
so now more than before it has become vital for me to copy the backup to an external machine, then install Inventree there and open the exsisting backup.

pls assist.

Br Martijn

**Comment by mabroens** [comment]
@matmair 

with my other search i was now able to loacte the the yml file whwere the docs are referening to` config.yaml`.
it is located in `/etc/inventree/config.yaml` as mentioned in https://docs.inventree.org/en/stable/start/installer/ 
![image](https://github.com/inventree/InvenTree/assets/130482028/3182c006-4b9c-4e67-acb9-1bf81cb8556e)

hope this helps searching for others as well in the future.

in the yml file i could find:
  # --- Database settings ---
  ENGINE: sqlite3
  NAME: '/opt/inventree/data/database.sqlite3'
  USER: sampleuser
  PASSWORD: samplepassword
  HOST: samplehost
  PORT: 123456

which let me to see:
drwxrwxr-x  5 inventree inventree    4096 jul  2 21:54 .
drwxr-xr-x  5 inventree inventree    4096 jul  3 09:35 ..
drwxrwxr-x  2 inventree inventree    4096 jul  2 20:28 backup
-rw-r--r--  1 inventree inventree 6074368 jul  2 21:54 database.sqlite3
drwxrwxr-x 13 inventree inventree    4096 mei  4 13:25 media
drwxrwxr-x 18 inventree inventree    4096 jul  2 21:36 static

Now my goal was to move the backup away from the same disk as the Inventree is. prferebly to my NAS or DropBox.
the doc mention:
![image](https://github.com/inventree/InvenTree/assets/130482028/1058c55f-c098-40fd-a659-57ff55d416a0)

So now i need to change
### Backup configuration options ###
# INVENTREE_BACKUP_DIR is the local filesystem location for storing backups
backup_storage: django.core.files.storage.FileSystemStorage
**backup_dir: '/opt/inventree/data/backup'**
#backup_options:

to point to the new location correct??

Br Martijn

**Comment by SchrodingersGat** [comment]
@mabroens did you ever get this one resolved?

**Comment by mabroens** [comment]
Hi Apologies,

Could not find the time to try this out yet. i have just placed it in my agenda. for this week. will respond latest by Friday. 

Br Martijn
