### ISSUE TITLE
Connecting with CAD tool to database

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4691]
### Body of the issue

Hi All,

as a next step i would like to integrate InvenTree with my CAD tool. i know about kintree and had a look at that but i think this works diffrently.

My CAD tool (Pulsonix) can connect to any database(form) if it uses ODBC. currently i have it connected to an access dB but would like to test it agains InvenTree.

where can i find documentation on how to connect to the InvenTree dB using odbc?

Br Martijn

**Comment by SchrodingersGat** [comment]
> where can i find documentation on how to connect to the InvenTree dB using odbc?

You'd have to look pretty hard, as this feature does not yet exist ;)

It we *could* support ODBC, then we would be using it to [store KiCad data](https://github.com/inventree/InvenTree/discussions/4133) in a very similar fashion.

Our latest discussion on this involves some sort of wrapper or conversion layer to convert between ODBC and InvenTree. It would be very "dangerous" to allow an external application raw access to the database fields as ODBC does. So, a "shim" layer between ODBC apps and the Inventree database would be required. This would allow these external tools to safely access the InvenTree database.

**Comment by matmair** [comment]
Directly writing to the database is a very bad idea if you are not well aware of the underlying database structure and changes to it. It can easily corrupt your database, I would not recommend doing it for production use.

**Comment by mabroens** [comment]
Well. im not looking for writing to the db. that is InvenTree. i only need to extract MPN, description, other part parameters like voltage, dielectric etc. Stock and pricing info. thats it so it would be  read only.
InvenTree is the maintainer of the dB. CAD is the viewer only

**Comment by matmair** [comment]
ODBC is just a database connection standard; if you do not want to write into the DB and can customize how the program looks up parameters (the stuff you want is in multiple tables and needs to be joined) it should work.

**Comment by gooutbefree** [comment]
For our CAD we daily generate a special CAD-DB using the API and Python. The CAD connects with ODBC to the new, cad-specific db. Read-only. We were not good enough in sql views

A odbc-to-api plugin would be nice to simulate a db

**Comment by mabroens** [comment]
Appologies, forgot about the topic. we cose for now

**Comment by wolflu05** [comment]
#4133 is also related to this somehow. There is one user who implemented an oidc middleware for kicad, I think currently it's just a draft.
