### ISSUE TITLE
[FR] Split Address in Street, ZIP, Country

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4695]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

would it be possible to split the Address field for company such that it gets a sepperate entry for Straat, Zip, Country, this would greatly improve report making.

### Suggested solution

Add sepperate field for street, zip and country

### Describe alternatives you've considered

Add sepperate field for street, zip and country

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Any change to the company model "address" field would need to be consider backwards compatibility. I'm open to considering any PRs made here, but no urgency to develop this myself.

**Comment by mabroens** [comment]
Okay, sound fair.

Well i was thinking address could be a automated field for backward compatibility so address = {street} {zip} {Place} {Country}.
that way you leave the user the choice either they fill in the old way or use the individual fields. it could even be an Admin setting.

But it would definitely  improve reporting since the current string, for me at least, is way to large and not useable for invoicing.

**Comment by mabroens** [comment]
A virtual part to me would like the comment stated before as example a SW license which I:

1. need to purchase and sell along with the product
2. do not need to purchase but still sell since i made it my self

so a virtual part for me is like a normal part except for the fact that i might not care how many i have in stock. so the BOM does not complain i can not build it.

currently i can not close the form if it has a virtual part in. then you get an error.

Br Martijn

**Comment by matmair** [comment]
@mabroens I think the suggested migration pattern would be a bit to easy.

Did you mean to comment the second comment here? It seems misplaced.

**Comment by mabroens** [comment]
my mistake yes your right. the second if for an other topic

**Comment by LavissaWoW** [comment]
I've been mulling this one over a bit too, as the current address field doesn't really conform to any kind of mail addressing standard out in the wild. 

If you try to add your address to , i.e. a report template, you would wind up with something like:
Supplier Name Ltd
Late spring rd. 5567, 54321 City State COUNTRY

While there does not exist an official worldwide standard for writing addresses, there are at least some guildelines for breaking down these elements into components.

Line 1: Name
Line 2: Street, building etc. (Can be expanded into an optional line 3, pushing subsequent lines 1 down)
Line 3: Postal/zip, city and province
Line 4: COUNTRY (Bold, all caps)

Now, I propose moving addresses out into their own model, following something like this schema:
![image](https://user-images.githubusercontent.com/7506688/234943960-b33e37f2-e3c8-41ac-9945-5a7abba48748.png)
As a bonus, this enables the implementation of department addresses.
"Title" (optional) is the human readable name for the address entry itself.

**Company model:**
* Address field is transitioned to func pointing to str(default_address) for backward compability

**Company Address model:**
* \_\_str\_\_ returns something along the lines [line1, line2, zip, city, country].join(some_delimiter)

Migration:
1. Run a migration that creates new company_address table
2. Run a migration to add default_address to company
3. Run a migration where a RunPython operation is triggered that reads the address field of all existing company models and, if an address exists, transfers this to a new company_address as line1, with an empty title.
4. default_address of the company entity is set to the newly created company_address. 

Points to consider:
* Updating views(?)
* Updating API
* Transitioning company.address to func without triggering a delete migration prematurely 

I'd be happy to tackle this one if you'd trust me to do so.

**Comment by matmair** [comment]
The current system is not designed for shipping. The suggested solution sounds great @LavissaWoW. The model should be placed in the 'company' app IMO.

I would like to suggest a few small changes:
- Add a field primary(bool) - to show if an address is the primary one
- Add a field shipping_notes(text) - for adding notes that should be passed on to the courier
- Add a field shipping_notes_internal(text) - for adding internal info regarding this address
- Enable multiple shipping addresses per company (adding this to shipments would probably be a follow up FR)

The API could report the __str__ in place for the current address field and be appended with an additional sub-serializer with the address data.
Ping me if you want feedback; we can also discuss implementation in a draft PR.

**Comment by SchrodingersGat** [comment]
@LavissaWoW I'm happy with the suggestion you make, and the additions mentioned by @matmair

This would represent a great improvement to our ordering functionality! 

If you would like to tackle this, that's fantastic. Reach out to either myself or @matmair and we'd be more than happy to provide any assistance.

**Comment by mabroens** [comment]
@LavissaWoW I agree with your approach and sound perfect. :-)

when you say: "_While there does not exist an official worldwide standard for writing addresses, there are at least some guidelines for breaking down these elements into components._"

this is why i was thinking of providing the user/report handle to the individual fields like street and zip. that way the user can build up his/her own of representing the address on the report

**Comment by LavissaWoW** [comment]
@SchrodingersGat PR created. Feel free to mark me as assignee on this
