### ISSUE TITLE
Sales order Contact

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4707]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

when creating a sales order there's a field called **Contact** what is the idea behind this field?  when i click it i can not enter any data nor does it give me a dropdown or any.

### Suggested solution

INstruct me how to use it and where it gets its data.
but suppose you have a new contact at the customer than it would be great to be able to just type the name in there anduse that in the report

### Describe alternatives you've considered

add a list of available contacts for a company but by default a company only has one contact in InvenTree. though in reality this could be multi0ple persons

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@mabroens I have updated the docs here - https://docs.inventree.org/en/latest/order/company/#contacts
