### ISSUE TITLE
Chnage assigned serialnumbers for stock items

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4708]
### Body of the issue

Hi i was wondering is there a way to change serial numbers assigned to stock items.
i can see my stock items i can see the assigned serial number. but now i want to change these since my product was bought with only a simple serial number. but leaves with a MAC address as serial.

br martijn

**Comment by SchrodingersGat** [comment]
Click on "Edit Stock Item"

![image](https://user-images.githubusercontent.com/10080325/234816487-73e4f0f0-8951-4600-b4f9-9aac77f571fb.png)

**Comment by mabroens** [comment]
yes that solves it. thank you
