### ISSUE TITLE
removing stock item fails.

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4709]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi, I have a stock of 25 PCBA's. i am in the **Part Stock** the filter is set for In _Stock = true_ i select all or just one does not matter.
then select <Remove Stock>  <OK> but then get : **You must select at least one available stock item**

seems like a bug to me or did i miss something

Br Martijn 

### Steps to Reproduce

1. Part Stock
2. select a line
3. click Remove Stock
4. OK
5. error

### Expected behaviour

a waring that im about to remove items. do you really wish to continue

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment]
@mabroens can you provide some screenshots for context?

**Comment by mabroens** [comment]
sure.

![image](https://user-images.githubusercontent.com/130482028/235074592-455c17e8-52f7-4cd4-b97b-8e12814dc3b0.png)
hope this helps.

**Comment by SchrodingersGat** [comment]
Ah ok, so you've selected serialized items which cannot be "adjusted" in this manner.

**Comment by mabroens** [comment]
ah ok now i get it. thnks case closed
