### ISSUE TITLE
Wrong text at the selected items count at label printing

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#4717]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When selecting multiple stock locations and hit printing:
![kép](https://user-images.githubusercontent.com/1609182/234987381-078d6a02-e7b0-4033-b927-8a7c19a06be8.png)
always "%d stock items selected" is shown regardless if I print stock location labels (and by looking the code it should be the same for other non-stock items label batch printing).

### Steps to Reproduce

Go to a stock location list, select multiple locations, hit print, observe the text in the dialog.

### Expected behaviour

Use proper target wording.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

master

### Relevant log output

```shell
N/A
```

**Comment by martonmiklos** [comment]
I wanted to PR this as seemed to be a low hanging fruit to pass the items_name here:
https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/js/translated/label.js#L28

However when I looked for the selectLabel JS function usage I only found localized generated js files in the InvenTree/InvenTree/static_i18n/i18n/ folder.

For e.g. function printStockItemLabels(items) .

Could you please educate me how are these files generated, or where do I need to alter the selectLabel calls?

**Comment by martonmiklos** [comment]
.The PR is submitted, but I came across an area of optimization:

![kép](https://user-images.githubusercontent.com/1609182/235004945-950c91ea-8e8d-449c-962b-bc7f4b191f6b.png)

When printing label directly from a single stocklocation/part/stock item it does not makes any sense to display that 1 stocklocation/part/stock item selected. (We could call it misleading as nothing is selected ;) )

With the PR changes it would be quite straightforward to implement it (by not passing the singular names from the single prints). What do you think?

**Comment by SchrodingersGat** [comment]
@martonmiklos did you actually submit a PR?

**Comment by martonmiklos** [comment]
> @martonmiklos did you actually submit a PR?

Upps, I forgot to press the button ;)

**Comment by martonmiklos** [comment]
@matmair many thanks for the review and PR approval! What is your opinion on the removing this message when printing directly from an item (see my post above)?

**Comment by matmair** [comment]
I would let it stay there for the sake of consistency.
