### ISSUE TITLE
Worker timeout on inventree-server and timeout of nginx frontend

### ISSUE THREAD

**Issue by gjherrmann** [inventree/InvenTree#4718]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I am attempting to install on an Armbian aarch64 5.15.93-rockchip64 computer that has several other docker images already installed.  

When I try to connect via a web browser, I get a error "504 Gateway Time-out" and when I examine the logs, it appears that there is a timeout at the inventree-server

> 2023/04/28 03:21:45 [error] 21#21: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.109, server: , request: "GET / HTTP/1.1", upstream: "http://172.27.0.3:8000/", host: "192.168.1.20:1337"

The server has errors with the worker timing out with the process terminating due to signal 9

The worker is able to connect to the database, but has a number of errors around "label_stockitemlabel"
django.db.utils.ProgrammingError: relation "label_stockitemlabel" does 

> not exist
> LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...

Finally, examining the database, there are a number of errors that see to arise 

> 2023-04-28 03:40:08.971 UTC [49] ERROR:  relation "common_inventreesetting" does not exist at character 112
> 2023-04-28 03:40:08.971 UTC [49] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
> 2023-04-28 03:40:09.806 UTC [50] ERROR:  relation "common_inventreesetting" does not exist at character 112
> 2023-04-28 03:40:09.806 UTC [50] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
> 2023-04-28 03:40:09.866 UTC [51] ERROR:  relation "common_inventreesetting" does not exist at character 112
> 2023-04-28 03:40:09.866 UTC [51] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1

I have removed and re-run the entire docker compose, with the same result.  At the moment, I am not sure if the issue is something I did in the install or if something isn't quite configured correctly.  I have not been able to connect for even the first time and haven't really been able to run inventree fully for the first time. Any help would be appreciated.  

### Steps to Reproduce

0. git pull https://github.com/inventree/InvenTree.git
1. cd InvenTree/docker/production
2. edit .env to have the path to the ext_volume, database user, and database password, and the compose project name to be "inventree-stable"
3. docker compose up
4. docker logs inventree-server
5. observe the worker timeout

### Relevant log output

```bash
File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "label_stockitemlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...
                               ^
[2023-04-28 03:20:54 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "label_stockitemlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...
                               ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/inventree/InvenTree/InvenTree/wsgi.py", line 15, in <module>
    application = get_wsgi_application()  # pragma: no cover
  File "/root/.local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/inventree/InvenTree/label/apps.py", line 41, in ready
    self.create_labels()  # pragma: no cover
  File "/home/inventree/InvenTree/label/apps.py", line 53, in create_labels
    self.create_labels_category(
  File "/home/inventree/InvenTree/label/apps.py", line 130, in create_labels_category
    self.create_template_label(model, src_dir, ref_name, label)
  File "/home/inventree/InvenTree/label/apps.py", line 166, in create_template_label
    if model.objects.filter(label=filename).exists():
  File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 808, in exists
    return self.query.has_results(using=self.db)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 561, in has_results
    return compiler.has_results()
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1145, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "label_stockitemlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...
                               ^
[2023-04-28 03:20:55 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:9)
[2023-04-28 03:20:55 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:10)
[2023-04-28 03:20:55 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:11)
[2023-04-28 03:20:55 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:12)
[2023-04-28 03:20:55 +0000] [8] [WARNING] Worker with pid 9 was terminated due to signal 6
[2023-04-28 03:20:55 +0000] [8] [WARNING] Worker with pid 11 was terminated due to signal 9
[2023-04-28 03:20:55 +0000] [8] [WARNING] Worker with pid 12 was terminated due to signal 9
[2023-04-28 03:20:55 +0000] [8] [WARNING] Worker with pid 10 was terminated due to signal 9
[2023-04-28 03:21:26 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:113)
[2023-04-28 03:21:26 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:114)
[2023-04-28 03:21:26 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:115)
[2023-04-28 03:21:26 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:116)
[2023-04-28 03:21:27 +0000] [8] [WARNING] Worker with pid 113 was terminated due to signal 9
[2023-04-28 03:21:27 +0000] [8] [WARNING] Worker with pid 114 was terminated due to signal 9
[2023-04-28 03:21:27 +0000] [8] [WARNING] Worker with pid 115 was terminated due to signal 9
[2023-04-28 03:21:27 +0000] [8] [WARNING] Worker with pid 116 was terminated due to signal 9
```

**Comment by SchrodingersGat** [comment]
Most likely you have not run the "invoke update" command to perform database migrations:

https://docs.inventree.org/en/latest/faq/#errors-during-inventree-update

**Comment by gjherrmann** [comment]
Reinstalling everything and running the invoke update resolved the database issues for the first run.
So, the modified install is now:

1. git pull
2. mkdir for persistent data
3. cd to InvenTree/docker/production
4. edit .env to ext_volume, admin user(pw and email), db user and password)
5. docker compose pull
6. docker compose up -d inventree-db
7. docker compose run inventree-server invoke update
8. docker compose up -d


However, I am still getting issues on the communication between the proxy, server, and worker.

1) connection is timing out in communication between the proxy and the server:
> /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
> /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
> 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
> /docker-entrypoint.sh: Configuration complete; ready for start up
> 2023/04/28 20:13:57 [notice] 1#1: using the "epoll" event method
> 2023/04/28 20:13:57 [notice] 1#1: nginx/1.24.0
> 2023/04/28 20:13:57 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
> 2023/04/28 20:13:57 [notice] 1#1: OS: Linux 5.15.93-rockchip64
> 2023/04/28 20:13:57 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
> 2023/04/28 20:13:57 [notice] 1#1: start worker processes
> 2023/04/28 20:13:57 [notice] 1#1: start worker process 21
> 2023/04/28 20:13:57 [notice] 1#1: start worker process 22
> 2023/04/28 20:13:57 [notice] 1#1: start worker process 23
> 2023/04/28 20:13:57 [notice] 1#1: start worker process 24
> 2023/04/28 20:16:12 [error] 21#21: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.109, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.4:8000/", host: "192.168.1.20:1337"
> 192.168.1.109 - - [28/Apr/2023:20:16:12 +0000] "GET / HTTP/1.1" 504 569 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
> 192.168.1.109 - - [28/Apr/2023:20:17:12 +0000] "GET /favicon.ico HTTP/1.1" 504 569 "http://192.168.1.20:1337/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
> 2023/04/28 20:17:12 [error] 21#21: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.109, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.21.0.4:8000/favicon.ico", host: "192.168.1.20:1337", referrer: "http://192.168.1.20:1337/"
> 192.168.1.109 - - [28/Apr/2023:20:17:18 +0000] "GET / HTTP/1.1" 504 167 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0" "-"
> 2023/04/28 20:17:18 [error] 22#22: *4 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.109, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.4:8000/", host: "192.168.1.20:1337"
> 192.168.1.109 - - [28/Apr/2023:20:17:18 +0000] "GET /favicon.ico HTTP/1.1" 499 0 "http://192.168.1.20:1337/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0" "-"


2) On the server, the worker pid is timing out and terminating
> [2023-04-28 20:15:00 +0000] [9] [WARNING] Worker with pid 118 was terminated due to signal 9
> [2023-04-28 20:15:00 +0000] [9] [WARNING] Worker with pid 116 was terminated due to signal 9
> [2023-04-28 20:15:00 +0000] [9] [WARNING] Worker with pid 117 was terminated due to signal 9
> [2023-04-28 20:15:00 +0000] [9] [WARNING] Worker with pid 115 was terminated due to signal 9
> [2023-04-28 20:15:30 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:221)
> [2023-04-28 20:15:30 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:222)
> [2023-04-28 20:15:30 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:223)
> [2023-04-28 20:15:30 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:224)
> [2023-04-28 20:15:32 +0000] [9] [WARNING] Worker with pid 223 was terminated due to signal 9
> [2023-04-28 20:15:32 +0000] [9] [WARNING] Worker with pid 222 was terminated due to signal 9
> [2023-04-28 20:15:32 +0000] [9] [WARNING] Worker with pid 224 was terminated due to signal 9
> [2023-04-28 20:15:32 +0000] [9] [WARNING] Worker with pid 221 was terminated due to signal 9
> [2023-04-28 20:16:02 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:326)
> [2023-04-28 20:16:02 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:327)
> [2023-04-28 20:16:02 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:328)
> [2023-04-28 20:16:02 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:329)
> [2023-04-28 20:16:03 +0000] [9] [WARNING] Worker with pid 329 was terminated due to signal 9
> [2023-04-28 20:16:03 +0000] [9] [WARNING] Worker with pid 326 was terminated due to signal 9
> [2023-04-28 20:16:03 +0000] [9] [WARNING] Worker with pid 327 was terminated due to signal 9
> [2023-04-28 20:16:03 +0000] [9] [WARNING] Worker with pid 328 was terminated due to signal 9
> [2023-04-28 20:16:33 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:434)
> [2023-04-28 20:16:33 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:435)
> [2023-04-28 20:16:33 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:436)
> [2023-04-28 20:16:33 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:437)
> [2023-04-28 20:16:34 +0000] [9] [WARNING] Worker with pid 434 was terminated due to signal 9
> [2023-04-28 20:16:34 +0000] [9] [WARNING] Worker with pid 436 was terminated due to signal 9
> [2023-04-28 20:16:34 +0000] [9] [WARNING] Worker with pid 437 was terminated due to signal 9
> [2023-04-28 20:16:35 +0000] [9] [WARNING] Worker with pid 435 was terminated due to signal 9
> [2023-04-28 20:17:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:548)
> [2023-04-28 20:17:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:549)
> [2023-04-28 20:17:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:550)
> [2023-04-28 20:17:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:551)
> [2023-04-28 20:17:06 +0000] [9] [WARNING] Worker with pid 548 was terminated due to signal 9
> [2023-04-28 20:17:06 +0000] [9] [WARNING] Worker with pid 551 was terminated due to signal 9
> [2023-04-28 20:17:06 +0000] [9] [WARNING] Worker with pid 549 was terminated due to signal 9
> [2023-04-28 20:17:06 +0000] [9] [WARNING] Worker with pid 550 was terminated due to signal 9
> [2023-04-28 20:17:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:664)
> [2023-04-28 20:17:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:665)
> [2023-04-28 20:17:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:666)
> [2023-04-28 20:17:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:667)
> [2023-04-28 20:17:37 +0000] [9] [WARNING] Worker with pid 665 was terminated due to signal 9
> [2023-04-28 20:17:37 +0000] [9] [WARNING] Worker with pid 667 was terminated due to signal 9
> [2023-04-28 20:17:37 +0000] [9] [WARNING] Worker with pid 664 was terminated due to signal 9
> [2023-04-28 20:17:37 +0000] [9] [WARNING] Worker with pid 666 was terminated due to signal 9
> [2023-04-28 20:18:08 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:778)
> [2023-04-28 20:18:08 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:779)
> [2023-04-28 20:18:08 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:780)
> [2023-04-28 20:18:08 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:781)
> [2023-04-28 20:18:09 +0000] [9] [WARNING] Worker with pid 780 was terminated due to signal 9
> [2023-04-28 20:18:09 +0000] [9] [WARNING] Worker with pid 779 was terminated due to signal 9
> [2023-04-28 20:18:09 +0000] [9] [WARNING] Worker with pid 781 was terminated due to signal 9
> [2023-04-28 20:18:09 +0000] [9] [WARNING] Worker with pid 778 was terminated due to signal 9
> [2023-04-28 20:18:39 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:892)
> [2023-04-28 20:18:39 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:893)
> [2023-04-28 20:18:39 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:894)
> [2023-04-28 20:18:39 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:895)
> [2023-04-28 20:18:40 +0000] [9] [WARNING] Worker with pid 895 was terminated due to signal 9
> [2023-04-28 20:18:40 +0000] [9] [WARNING] Worker with pid 894 was terminated due to signal 9
> [2023-04-28 20:18:40 +0000] [9] [WARNING] Worker with pid 892 was terminated due to signal 9
> [2023-04-28 20:18:40 +0000] [9] [WARNING] Worker with pid 893 was terminated due to signal 9
> [2023-04-28 20:19:11 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1007)
> [2023-04-28 20:19:11 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1008)
> [2023-04-28 20:19:11 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1009)
> [2023-04-28 20:19:11 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1010)
> [2023-04-28 20:19:12 +0000] [9] [WARNING] Worker with pid 1009 was terminated due to signal 9
> [2023-04-28 20:19:12 +0000] [9] [WARNING] Worker with pid 1010 was terminated due to signal 9
> [2023-04-28 20:19:12 +0000] [9] [WARNING] Worker with pid 1007 was terminated due to signal 9
> [2023-04-28 20:19:12 +0000] [9] [WARNING] Worker with pid 1008 was terminated due to signal 9
> [2023-04-28 20:19:42 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1123)
> [2023-04-28 20:19:42 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1124)
> [2023-04-28 20:19:42 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1125)
> [2023-04-28 20:19:42 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1126)
> [2023-04-28 20:19:43 +0000] [9] [WARNING] Worker with pid 1123 was terminated due to signal 9
> [2023-04-28 20:19:43 +0000] [9] [WARNING] Worker with pid 1124 was terminated due to signal 9
> [2023-04-28 20:19:43 +0000] [9] [WARNING] Worker with pid 1126 was terminated due to signal 9
> [2023-04-28 20:19:43 +0000] [9] [WARNING] Worker with pid 1125 was terminated due to signal 9
> [2023-04-28 20:20:13 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1237)
> [2023-04-28 20:20:13 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1238)
> [2023-04-28 20:20:13 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1239)
> [2023-04-28 20:20:13 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1240)
> [2023-04-28 20:20:14 +0000] [9] [WARNING] Worker with pid 1240 was terminated due to signal 9
> [2023-04-28 20:20:14 +0000] [9] [WARNING] Worker with pid 1238 was terminated due to signal 9
> [2023-04-28 20:20:14 +0000] [9] [WARNING] Worker with pid 1239 was terminated due to signal 9
> [2023-04-28 20:20:14 +0000] [9] [WARNING] Worker with pid 1237 was terminated due to signal 9
> [2023-04-28 20:20:45 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1351)
> [2023-04-28 20:20:45 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1352)
> [2023-04-28 20:20:45 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1353)
> [2023-04-28 20:20:45 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1354)
> [2023-04-28 20:20:46 +0000] [9] [WARNING] Worker with pid 1351 was terminated due to signal 9
> [2023-04-28 20:20:46 +0000] [9] [WARNING] Worker with pid 1352 was terminated due to signal 9
> [2023-04-28 20:20:46 +0000] [9] [WARNING] Worker with pid 1353 was terminated due to signal 9
> [2023-04-28 20:20:46 +0000] [9] [WARNING] Worker with pid 1354 was terminated due to signal 9
> [2023-04-28 20:21:16 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1467)
> [2023-04-28 20:21:16 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1468)
> [2023-04-28 20:21:16 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1469)
> [2023-04-28 20:21:16 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:1470)
> [2023-04-28 20:21:17 +0000] [9] [WARNING] Worker with pid 1468 was terminated due to signal 9
> [2023-04-28 20:21:17 +0000] [9] [WARNING] Worker with pid 1469 was terminated due to signal 9
> [2023-04-28 20:21:17 +0000] [9] [WARNING] Worker with pid 1467 was terminated due to signal 9
> [2023-04-28 20:21:17 +0000] [9] [WARNING] Worker with pid 1470 was terminated due to signal 9

**Comment by SchrodingersGat** [comment]
You might be running low on system resources? Either the host pc, or your docker might be ram or cpu limited? Can you monitor your system resources use during boot?

**Comment by gjherrmann** [comment]
looking at docker stats, the server is currently using a lot of the cpu % at the moment, anywhere from 230% up to 260%.  even with restarts.  
![Screenshot 2023-04-29 165335](https://user-images.githubusercontent.com/4349813/235327328-3c1847f6-bfd4-4783-9594-0e2a68b1d4e0.png)

**Comment by gjherrmann** [comment]
when looking at top on the host computer, the computer is pretty consistently maxxing out at 85% of cpu, with the drops in cpu usage likely are the termination of the worker processes.

**Comment by SchrodingersGat** [comment]
What version of InvenTree are you running?

**Comment by gjherrmann** [comment]
My impulse answer is whatever is currently bundled in the production docker image - I haven't altered anything from the docker install.

Connecting to the server instance and running `invoke --version` I find that this returns 
`Invoke 2.0.0`

**Comment by matmair** [comment]
That does not help a bit.
Please provide the docker image hash or the environment variable 'INVENTREE_COMMIT_HASH' - which is exposed on your docker container itself.

**Comment by gjherrmann** [comment]
Ah, I can get that for you as well.
docker ID `sha256:626010c61f1730fee797ef6f77605d3cdba3bedc35c7c6ab48fb15b2ada554e6`
`ENV INVENTREE_COMMIT_HASH=593a716`

**Comment by matmair** [comment]
I have tried reproducing this on multiple low-end docker hosts now. I think the problem lies somewhere else than performance.

@gjherrmann
1) Xan you try if the behavior changes with plugins en/disabled in the config.yaml?
2) Can you check if docker is allowed to read and write on the mounted dir?
3) Is there anything else in the server logs then timeout kills?

**Comment by gjherrmann** [comment]
I reinstalled inventree and have the following results.
1. I edited the config.yaml inside the server instance at /home/inventree/data/ to allow for plugins (the .env file for docker compose was also edited with the line INVENTREE_PLUGINS_ENABLED=True) then restarted inventree-server to the same behavior
2. The edits above persisted after restarting and was done inside the docker inventree-server container.  Also created a couple of txt files in the persistent storage and these are still present.  Installing vim and mlocate did not persist after restarting, which is expected.
3. In addition to the worker timeout, there are now some pip errors
```
[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
fatal: not a git repository (or any of the parent directories): .git
[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```

I have attached docker logs from the server, worker, and proxy containers.  I changed the log level to DEBUG and nothing else has presented.  Are there different logs that you would like to see or other system version information that might help?

[_inventree-server.txt](https://github.com/inventree/InvenTree/files/11437121/_inventree-server.txt)
[_inventree-worker.txt](https://github.com/inventree/InvenTree/files/11437122/_inventree-worker.txt)
[_inventree-proxy.txt](https://github.com/inventree/InvenTree/files/11437123/_inventree-proxy.txt)

**Comment by gjherrmann** [comment]
As I was playing around with things today, I installed the debian package procps and watched top.
What I noticed was that, at regular intervals, it appears that each gunicorn worker spawned a pip process that maximized the consumed large amounts of the available cpu resources.  Just to double check, when I run 

```
python3 -m pip list
```

I get the following list of extra python packages that were installed in addition to those installed via requirements.txt
```
cli-helpers                     2.3.0
click                           8.1.3
configobj                       5.0.8
invoke                          2.0.0
mariadb                         1.0.11
mysqlclient                     2.1.1
pendulum                        2.1.2
pgcli                           3.5.0
pgspecial                       2.1.0
pip                             23.1
prompt-toolkit                  3.0.38
psycopg                         3.1.8
psycopg2                        2.9.6
Pygments                        2.15.0
pytzdata                        2020.1
setproctitle                    1.3.2
setuptools                      65.6.3
tabulate                        0.9.0
wheel                           0.40.0
```
I don't actually expect this to be a useful list.  The only other major difference between the requirements and the pip installed files that I noticed was that the requirements wanted `typing-extensions` and the pip list showed `typing_extensions`.  I haven't played around enough in python to know off the top of my head if calling this package with a dash versus underscore makes a difference.

**Comment by matmair** [comment]
@gjherrmann that is normal and part of the update cycle. It is curious that it saturated the cpu though.

**Comment by thefakewater** [comment]
I have the same issue

**Comment by thefakewater** [comment]
To fix it I had to shutdown the other containers running

**Comment by SchrodingersGat** [comment]
> To fix it I had to shutdown the other containers running

Can you expand on this @thefakewater - what containers?
