### ISSUE TITLE
"Install Plugin" via GUI fails to add plugin to plugins.txt correctly for first plugin

### ISSUE THREAD

**Issue by jannick-gb** [inventree/InvenTree#4719]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When trying to install a plugin via the GUI function "Install Plugin" without any prior installed plugins, the plugin is appended to the first line of the plugins.txt.

As the first line is already populated with `# InvenTree Plugins (uses PIP framework to install)` the result is e.g. `# InvenTree Plugins (uses PIP framework to install)inventree-zebra-plugin@git+https://github.com/SergeoLacruz/inventree-zebra-plugin  # Installed 2023-04-28 06:55:40.146423+00:00 by xyz` thus ignoring the plugin in a docker env restart because of the `#`.

Subsequently installed plugins are correctly placed in an empty line of the plugins.txt.

### Steps to Reproduce

1. Have a fresh install without installed plugins.
2. Go to "Settings" > "Plugin Settings" > "Plugins" > "Install Plugin"
3. Fill "Package Name" with `inventree-zebra-plugin`
4. Fill "Source URL" with `git+https://github.com/SergeoLacruz/inventree-zebra-plugin`
5. "Submit"
6. Check plugins.txt file

### Expected behaviour

The installed plugin should be added below the comment such that it actually will be parsed by the plugin management.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18
Commit Hash: 593a716
Commit Date: 2023-04-18
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by matmair** [comment]
Thanks for the report; looking into it
