### ISSUE TITLE
Add manufacturer and MPN as filter columns to Bill Of Matterial overview

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4720]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I would like to have additional fields available in the part > BOM view and be able to filter on these. that way its easier to filter on them

### Suggested solution

please add Manuf, MPN, Supplier, SKU to them though the last 2 might be more tricky i guess

### Describe alternatives you've considered

?

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@mabroens this may be difficult or impractical to achieve. BOMs link to internal parts, which have zero-to-many link to MPN (manufacturer part) and SKU (supplier part). Manufacturer Parts and Supplier parts are "linked" to internal parts but there may be multiple (or zero) linked parts.

**Comment by matmair** [comment]
I think this would not fit in the way that parts, supplier parts and manufacturers parts work in InvenTree; I would close this as not planned
