### ISSUE TITLE
[Bug] Model Metadata Issues

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4723]
As part of documentation for https://github.com/inventree/InvenTree/issues/4665 - noticed that the metadata implementation is somewhat broken when updating via the API. 

The metadata field is a JSONField which supports multiple data types (string / int / dict / array / etc)

However the methods `get_metadata` and `set_metadata` assume that the `metadata` field is a dict - and cause failures if this is not the case.

**Comment by SchrodingersGat** [comment]
My suggestion would be that we enforce the metadata to be a dict object to support key:value pairs and validate that `type(metadata) is dict` whenever the model is saved

**Comment by matmair** [comment]
Sounds good 👌
