### ISSUE TITLE
using part images

### ISSUE THREAD

**Issue by DS1705** [inventree/InvenTree#4726]
if i use the image link like this sometimes i get an unauthorized response sometimes i get the image
`<img src="http://172.27.6.4:8000/media/part_images/part_9_image.png/" style="width:50px">`
does someone know why this is? how to fix this?

**Comment by SchrodingersGat** [comment]
@DS1705 you are going to have to supply some more context than this.

- How are you hosting your InvenTree server?
- What is the exact response / error message?
- Where are you writing the code to access the image?

**Comment by DS1705** [comment]
i host inventree bare metal
this is the code to create the link
```
def getpartimage(part):
    if part.image == None:
        return api.base_url[:-1]+"/static/img/blank_image.thumbnail.png"
    return api.base_url[:-1] + part.image
```
this is the error i get
![image](https://user-images.githubusercontent.com/57893168/235308052-34dc6f77-6c77-4591-a3b4-3a348764ff01.png)

**Comment by SchrodingersGat** [comment]
Pretty straight forward then - [you need to login](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)

**Comment by matmair** [comment]
@DS1705 please use issue templates
