### ISSUE TITLE
[FR] Remove Gitpod integration

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4729]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Gitpod and Codespaces provide similar feature sets but Gitpod requires an extra file and changes PRs.

### Suggested solution

REmove gitpod integration; I switched quite a time ago and I am not aware of many other users.

### Describe alternatives you've considered

We can leave it there; it is not doing much harm

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
Thoughts @SchrodingersGat ?

**Comment by wolflu05** [comment]
You're using codespaces? I think I remember a conversation with you where you said codespaces is no Option due to costs? But aren't we get 50h for free per month?

**Comment by matmair** [comment]
The billing/counting for public repos changed so I switched.

**Comment by SchrodingersGat** [comment]
Happy to switch, I don't think it has been getting any use anyway

**Comment by matmair** [comment]
PR is in
