### ISSUE TITLE
[FR] Replace markuplint with djlint

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4730]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

We currently rely on markuplint - a node-based linter for html - for linting django templates. This means we are requiring a whole lot of js packages just for linting.Django

### Suggested solution

There is a tool built for django templates specifically called [djlint](https://www.djlint.com/docs/integrations/). We could replace the node dependencies with it and merge the HTML step with the pre-commit step.Django

### Describe alternatives you've considered

The current way works.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
Thoughts @SchrodingersGat?

**Comment by SchrodingersGat** [comment]
Does it also support JavaScript linting? We use jslint for that currently I believe

**Comment by matmair** [comment]
I think that should be done in a second step; the diff for the templates alone is big enough
