### ISSUE TITLE
Printing labels

### ISSUE THREAD

**Issue by DS1705** [inventree/InvenTree#4745]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

if try to print a label i get an error. i tried printing with python interface and from the web interface with following plugins:
Sample Label Printer
Cups Label Printer

this is the code i used for printing with the python interface
it worked before like this
`def printl(stock:StockItem):
    stocklabel= LabelStock(api,pk=2)
    print(stocklabel.name)
    stock.printlabel(label=stocklabel,plugin='cups',args={})
   
stocks=StockItem.list(api)       
print(stocks[0].getPart().name)
printl(stocks[0])` 

### Steps to Reproduce

i run the code or go to the stock page and print a label

### Expected behaviour

i expected to print a label

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.18
Commit Hash: 3d4b64d03
Commit Date: 2023-03-29
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'Label Printer', 'slug': 'samplelabel', 'version': '0.2'}, {'name': 'CupsLabels', 'slug': 'cups', 'version': '0.1.0'}]

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/dieter/inventree-api/inventreeInterface.py", line 212, in <module>
    printl(stocks[0])       
  File "/home/dieter/inventree-api/inventreeInterface.py", line 208, in printl
    stock.printlabel(label=stocklabel,plugin='cups',args={})
  File "/home/dieter/env/lib/python3.8/site-packages/inventree/label.py", line 45, in printlabel
    return self._api.get(URL, params=params)
  File "/home/dieter/env/lib/python3.8/site-packages/inventree/api.py", line 496, in get
    response = self.request(url, method='get', **kwargs)
  File "/home/dieter/env/lib/python3.8/site-packages/inventree/api.py", line 344, in request
    raise requests.exceptions.HTTPError(detail)
requests.exceptions.HTTPError: {'detail': 'Error occurred during API request', 'url': 'http://172.27.6.4:8000/api/label/stock/2/print/', 'method': 'GET', 'status_code': 500, 'body': '{"error":"AttributeError","error_class":"<class \'AttributeError\'>","detail":"\'SafeString\' object has no attribute \'get_document\'","path":"/api/label/stock/2/print/","status_code":500}', 'headers': {'AUTHORIZATION': 'Token '}, 'params': {'items[]': 61, 'plugin': 'cups'}}
```

**Comment by matmair** [comment]
@DS1705 there should be an error in your admin panel - please provide that if you think this is a server error.

**Comment by matmair** [comment]
Also please redact your token from the error log above and delete the old version

**Comment by DS1705** [comment]
this is the error from the admin panel
Change Error
Error object (51)
[HISTORY](http://172.27.6.4:8000/admin/error_report/error/51/history/)

Type:
AttributeError
Path:
/api/label/stock/2/print/
Info:
'SafeString' object has no attribute 'get_document'
When:
May 1, 2023, 8:43 p.m.
Data:
Traceback (most recent call last):

File "/home/dieter/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/dieter/src/InvenTree/label/api.py", line 152, in get
return self.print(request, self.get_items())

File "/home/dieter/src/InvenTree/label/api.py", line 237, in print
pdf = output.get_document().write_pdf()

AttributeError: 'SafeString' object has no attribute 'get_document'

**Comment by matmair** [comment]
@SchrodingersGat any idea how this could happen?

**Comment by SchrodingersGat** [comment]
@DS1705 have you recently updated your InvenTree installation?

**Comment by DS1705** [comment]
no i installed inventree from my fork and have not synced my fork yet

**Comment by SchrodingersGat** [comment]
- Does the printing plugin work when activated via the web interface (and not your custom API code)?
- Does label printing work direct to PDF (and not to the plugin)?

**Comment by DS1705** [comment]
i can export to pdf but not to the two plugins from the web interface

**Comment by SchrodingersGat** [comment]
Thanks, looks to be an issue with label printing via plugins

**Comment by DS1705** [comment]
do you know when i can print again?

**Comment by SchrodingersGat** [comment]
Do you have "debug mode" enabled for reports?

https://docs.inventree.org/en/latest/report/report/#debug-mode

This may cause some issues with printing via plugin. If you turn that off, it should work
