### ISSUE TITLE
Set "Delete on deplete" to off by default

### ISSUE THREAD

**Issue by IsThisNameGoodEnough** [inventree/InvenTree#475]
Fist off, really impressed with what's been done so far!  I've been playing with InvenTree for a little while now, and it looks like a great option for a small business.

Onto one of the issues/questions I have.  It looks like the default nature for new stock is to have the stock item deleted when it reaches zero, and I don't see a way to change this.  Perhaps a setting in the admin section, or an attribute that can set on the part level?

Side note, would be great if the wiki for InvenTree here on github was enabled so people could start fleshing out usage documentation.

**Comment by SchrodingersGat** [comment]
Thanks, I'm really glad you like it!

I think that having the ability to change the default behavior of "delete_on_deplete" is a good idea. I will have to consider how best to implement it. I do like both suggestions (admin level / part level) - perhaps both options could be considered somehow.

With regards to documentation - I know that is where the project is really lacking currently. I do have some user documentation at https://inventree.github.io/

Is this the kind of thing you mean? What do you see as the advantage of having a Wiki here too?

**Comment by IsThisNameGoodEnough** [comment]
Yes, I saw the documentation at https://inventree.github.io but it really doesn't convey the scope of the project or how best to use it.  The value of moving documentation over to a wiki is that the community can help flesh it out.  I for one would be up to help add content.

My guess is that InvenTree would get more exposure if it was better shown what it can do, as it really fills a void for SMB inventory.

**Comment by SchrodingersGat** [comment]
> My guess is that InvenTree would get more exposure if it was better shown what it can do, as it really fills a void for SMB inventory.

Yes, absolutely. I really need to improve the quality of the user documentation, for sure.

**Comment by IsThisNameGoodEnough** [comment]
I'm willing to take a stab at fleshing out the user documentation.  What's the best format/process to get it to you?

**Comment by eeintech** [comment]
@IsThisNameGoodEnough The "delete on deplete" check box now exists!

![image](https://user-images.githubusercontent.com/4020546/95808787-dae46a00-0cd2-11eb-9e92-887cec636f0c.png)

If you are still thrilled to write some docs, we've made the setup "much" easier for contributors as it only requires Python to be installed on your system 😃 
Check out the new repository: https://github.com/inventree/inventree-docs

And the new documentation website can be found here now: https://inventree.readthedocs.io/

If you have any question, let us know 😉

**Comment by SchrodingersGat** [comment]
@IsThisNameGoodEnough I'm going to close this issue out, as it's gone "stale". Please feel free to comment here again if you have any further thoughts.

**Comment by SchrodingersGat** [comment]
@mrkylegp no, this was not implemented. I'd suggest opening a new issue (referencing this one) if you'd like to discuss this.
