### ISSUE TITLE
SQL Database "fine" -- but Inventree will not load it

### ISSUE THREAD

**Issue by derekwolfson** [inventree/InvenTree#4759]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I went to delete an inactive item from a pending PO and boom -- inventree exploded.

I can access the postgresql database from docker terminal -- but the docker compose command to setup the server does not work. 

It looks like this mostly 
--- 
pg_dump: error: Dumping the contents of table "django_q_ormq" failed: PQgetResult() failed.
pg_dump: error: Error message from server: ERROR:  could not open file "base/16384/18913": Input/output error
---

The command changes pretty often. 

I have daily backups -- but it didn't trigger yet today.  I can restore to a yesterday but I've been working feverishly getting our system up and running so it'd be a considerable amount of lost work.

Any tips or tricks?  I hate bringing this up as an issue as it is probably idiosyncratic -- but oof -- this is a big facepalm moment.

Seems an issue with pg_dump missing files...

### Steps to Reproduce

make item inactive
delete from PO
and cry...

Could not reproduce on test server.

### Expected behaviour

Just not this...

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

Can't get it -- was running latest stable version

### Relevant log output

```shell
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump --dbname=postgresql://XXX:YYY@inventree-db:5432/inventree --format=custom
pg_dump: error: Dumping the contents of table "django_q_ormq" failed: PQgetResult() failed.
pg_dump: error: Error message from server: ERROR:  could not open file "base/16384/18913": Input/output error
pg_dump: error: The command was: COPY public.django_q_ormq (id, key, payload, lock) TO stdout;
```

**Comment by derekwolfson** [comment]
Hey there -- honestly -- I was updating lots of parts and supplier parts -- but that was all done -- I was simply making POs and realized I had the wrong piece of hardware in one and went to delete it and *poof*.

The server was stuck in a loop -- I tried to run --invoke backup-- from the server before going further but it wouldn't take.  At that point -- I removed the container and volume and tried to start fresh with the local file.

Honestly -- I wouldn't even post an issue for something like this -- but the task I was doing seemed so innocuous that I thought this might have more to do with the Inventree docker sequence than the database.

It appears the fidelity of the database is in tact -- but I'm guessing there's missing files somewhere -- given the error of `pgdump`.

I'll look for ways to "fix" `pgdump` today on stack exchange etc -- but I'm guessing working directly with the database might make inventree break in other ways.

I'll do some more digging -- but definitely frusterating.

I'll get in the habit of doing manual backups more often now on heavy work days -- but man -- it wasn't like I was doing any heavy lifting -- just normal adding parts, etc.

**Comment by derekwolfson** [comment]
I went back to the originally failing database -- and got this...
```
2023-05-05 08:21:34 2023-05-05 15:21:34.893 UTC [27] LOG:  database system was shut down at 2023-05-05 15:13:50 UTC
2023-05-05 08:21:34 2023-05-05 15:21:34.906 UTC [27] LOG:  invalid primary checkpoint record
2023-05-05 08:21:34 2023-05-05 15:21:34.906 UTC [27] PANIC:  could not locate a valid checkpoint record
2023-05-05 08:21:34 2023-05-05 15:21:34.915 UTC [1] LOG:  startup process (PID 27) was terminated by signal 6: Aborted
2023-05-05 08:21:34 2023-05-05 15:21:34.915 UTC [1] LOG:  aborting startup due to startup process failure
2023-05-05 08:21:34 2023-05-05 15:21:34.919 UTC [1] LOG:  database system is shut down
```

I think [https://stackoverflow.com/questions/48197579/docker-postgres-invalid-primary-checkpoint-record](url) is going to be helpful...

**Comment by derekwolfson** [comment]
I've been staring at this all day -- it seems the key is to run `pg_resetwal` but you cannot do it in the terminal because we're signed in as root by default. 

I've tried signing in as `-u 1000` but then I cannot run it because it needs to be run by the superuser who started the database. 

This is way above my understanding of docker/sql -- so any help here would be greatly appreciated.

I've no idea why this broke so catastrophically -- but I know the data is in there so it would be great to uncover it and reindex.

**Comment by derekwolfson** [comment]
`su postgresql` was the trick.  Then I could run `pg_resetwal` -- still had some issues -- so rewound a Dropbox folder that holds my persistent binded volume -- and tried it again and it worked.  

I'm guessing this happened because of Dropbox -- so I'm going to move my persistently binded volume out of Dropbox and find a way to "push" it to Dropbox periodically...

Sorry for mucking up the software issues -- but this legitimately was like 200 man hours of work that was gonna be gone if we didn't recover... 

Whether Dropbox was the problem or not -- I'll do some digging -- but without the high frequency backups from Dropbox -- we would have been SOL.

Time for a baguette and some wine.

**Comment by derekwolfson** [comment]
Maybe I should have read this before hosting directly to Dropbox...

Oh well -- we're over the hump now -- and I learned a lot about how this works under the hood -- so I'm glad about that.

**Comment by matmair** [comment]
@derekwolfson you are storing your live binary postgres data on Dropbox? That is very very much a no-no. Postgres (nearly all DBMS) writes temporary transaction logs to the disk. That is why most databases need the kind of iops they do. Please do not do that if you ever write to the database. That will brick your database server - has nothing to do with InvenTree but the database system itself. You are lucky the „backup“ worked. Hosting you binary data on Dropbox is not a backup. Verified backups (ie. you regularly verify backups can be used to recreate a running instance) should be the only thing that counts. Especially if you spend that amount of time on your instance.

The only database that can work this way I know is SQLite. And even there you need to turn of the WAL.

**Comment by derekwolfson** [comment]
Yeah I know it now — and I realize I got lucky to be able to recover it.

Was a total nightmare.

I’ll just start pushing backups to Dropbox using the tools recommended by
the devs.
