### ISSUE TITLE
Report ignore currency symbol when printing

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4762]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Hi is there a way to not print the currency symbol on a report?
currently i use:
```
<td>{% render_currency line.price  decimal_places=2 currency=order.customer.currency%}</td>
<td>{% render_currency line.total_line_price  decimal_places=2 currency=order.customer.currency%}</td>
```

which print nicly the US$ infron tof the price but unfortunatly als comusumes space on the lines.
so i'd like to not print this currency unit per line but only at the bottom of the sales report 

### Suggested solution

good question. is this possible?

### Describe alternatives you've considered

could not come up with one so foar for testing

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
You can see in the `render_currency` method that the `include_symbol` argument can be set to False to hide the symbol:

https://github.com/inventree/InvenTree/blob/7793b3505d1dc4b6983bcc3c7efe8915dbc6150c/InvenTree/InvenTree/helpers.py#L1142
