### ISSUE TITLE
Sales Reports VAT

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4763]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Currently the customers/suppliers/manufacturers do not have a field indicating the VAT number nor VAT %. could this be added 
and can we then use it in the sales report?

### Suggested solution

add 2 additional field to customer details: VAT.Nr and VAT %.
add order.customer.vat to be used in rendering reports.

### Describe alternatives you've considered

?

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by miggland** [comment]
Adding a VAT number for the customer is straightforward - it's just a number, and doesn't have any immediate implications. I put it in the description field for companies, but that's just because I thought it was handy.

VAT-% and so on is definitely more complicated. Not only will it depend on customers, it might depend on what you are selling as well, ie be different per sales order line.

Customers, sales orders, sales order lines all have metadata activated. I would suggest this is something that could be put in the metadata fields, by a plugin.

**Comment by mabroens** [comment]
Sounds good thank you.
we need to print the VAT number on the invoices.

as for the VAT per part. true. this would actually imply that a part gets a VAT% since depending on the good these might very.
but also the customers/suppliers/manufacturer have a VAT%. typically when selling within the same country you need to charge VAT. but under some circumstance the buyer might be free from VAT. but whenever sending to other countries thats when we do not need add VAT and hence the VAT% could be 0 i guess.

Customer setting would in my case overwrite the part.vat.

**Comment by miggland** [comment]
The point is that it's very hard to get this right, in general. What you describe is valid in the EU - what about outside? If VAT functionality is a part of the core, it needs to be use-able for all cases.

A plugin is much more flexible, and can be used by those who require it / adapted to fit local regulations.

**Comment by matmair** [comment]
InvenTree does not include proper business accounting functionality. So I would really question if it makes sense to create full invoices from it.

@SchrodingersGat I think we should discuss putting this on the roadmap. It suggests that we will - at some point - implement tax support. From my experience with this area I can tell you 2 things:
1) Getting it right every time is very hard
2) Getting it wrong makes your life as a business and individually very hard

Although we are MIT licensed and do not have any warranty to fear I think including even adding a percentage puts us in an ethical liability to get it right. Without anyone with proper tax/accounting knowledge on the core team, we should stay away from taxes or proper accounting as far as possible IMO.

**Comment by SchrodingersGat** [comment]
@matmair I would tend to agree - we either get it perfect of explicity don't do it. My preference would strongly be to allow easy ingress / egress of order data to other systems which support finance / accounting operations, and focus on the stock management side.

I have recently been discussing this topic with regard to GST in Australia. Implementing a generic system which works "everywhere" would be exceptionally difficult.

**Comment by mabroens** [comment]
Hi All,

for now i just created two templates one fo export (excl VAT) and one including VAT.

closing this issue
