### ISSUE TITLE
Stock value non-zero for deleted stock

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#4764]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

In the stock list, stock which is depleted still shows a stock value.

It seems, however, that the value is not added to the total line of the table (correctly).

The purchase price shows the correct value, but the purchase price is not multiplied by the correct value (0), but by 1.

See example:
![image](https://user-images.githubusercontent.com/1314853/236453617-d4034488-f370-4dd0-bea7-fe150f06770f.png)

### Steps to Reproduce

1. Mark stock to not be depleted on delete.
2. Deplete stock
3. Check table

### Expected behaviour

When nothing is in stock, the value should be zero.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18
Commit Hash: 593a716
Commit Date: 2023-04-18
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'AutoPrintLabelPlugin', 'slug': 'autoprint', 'version': '0.0.1'}, {'name': 'CustomPagerPlugin', 'slug': 'cpager', 'version': '0.1.2'}, {'name': 'Print Labels to file', 'slug': 'printlabeltofile', 'version': '0.0.1'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.6.0'}]

**Comment by SchrodingersGat** [comment]
@miggland thanks for reporting :)
