### ISSUE TITLE
New Sales Order button does not work in Company view

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#4776]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

As in title.

### Steps to Reproduce

1. Click menu: Sell -> Customers
2. Click on any company
3. Select "Sales Orders" tab.
4. Click on "New Sales Order"

### Expected behaviour

New Sales Order form should be opened with pre-filled customer.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18
Commit Hash: 593a716c2
Commit Date: 2023-04-18
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'Part Import', 'slug': 'import', 'version': 1}]

**Comment by matmair** [comment]
@sintech have you checked https://docs.inventree.org/en/latest/faq/#feature-x-does-not-work-after-update ?

**Comment by sintech** [comment]
It was the first thing I tried, also https://demo.inventree.org behave the same way.
