### ISSUE TITLE
how to add customer.contact.name to a report

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4777]
### Body of the issue

Hi while creating a report i would like to add, for a sales order or RMA, the contact name or contact email to the report but how can i access that context variable.
while going over https://docs.inventree.org/en/stable/report/context_variables/#orders contect variables is was not successful in finding how to.

I know a customer has contactpersons and contactpersons have name, phone number, email etc. but how you access these and where could i have found the information?
i tried with: {{ customer.contact.email }}

also it would be nice if dor debugging you could print all variables from a context. for example {%print customer.contact} would give a lilst of all variables that can be used in the report

please advice
Br Martijn

**Comment by SchrodingersGat** [comment]
The *contact* is associated with the order, so something like:

```html
{% raw %}
{% if order.contact %}
Contact: {{ order.contact.name }} - {{ order.contact.email }}
{% endif %}
{% endraw %}
```
