### ISSUE TITLE
Report save according to nameing scheme

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4779]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Is there a way to automatically save a report according to its naming scheme?

### Suggested solution

Currently reports are stored internally according a naming scheme. But when generating the report is is saved according the name given in the admin panel. Can we somehow save the report with the report number SO_123

### Describe alternatives you've considered

We already know the order name use that to save it as pdf??

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Yes, this is possible - https://docs.inventree.org/en/latest/report/report/#filename-pattern

**Comment by mabroens** [comment]
@SchrodingersGat ,

thanks for the response but it seems not working for me.
i entered following in the system panel:
![image](https://user-images.githubusercontent.com/130482028/236631479-4b8c0b25-0273-426b-a764-33a090979aed.png)

but that also results in the sales report being saved as:
S59_I{(ref_04d}}.pdf

did i miss something?

**Comment by SchrodingersGat** [comment]
That's completely the wrong setting. As specified in the link above you need to adjust the "filename pattern" for each specific report in the admin interface.
