### ISSUE TITLE
Maths Operations assign to variables and print seems not to work

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4785]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi,

i was testing with the Math Operation. by just copying the examples from:
`https://docs.inventree.org/en/latest/report/helpers/`

Goal of my exercise was to eventually multiply a constant with line.quantity and play some with results from formulas and assign to variables.
my code is not that much:
```
{% extends "report/inventree_order_report_base.html" %}

{% load i18n %}
{% load report %}
{% load barcode %}
{% load inventree_extras %}
{% load markdownify %}

add_2numbers: {% add 1 3 %} <!-- Add two numbers together -->
Subtract_3_from_4:{% subtract 4 3 %} <!-- Subtract 3 from 4 -->
Multiply_two_numbers:{% multiply 1.2 3.4 %} <!-- Multiply two numbers -->
Divide_10_by_2:{% divide 10 2 %} <!-- Divide 10 by 2 -->

{% for line in order.lines %}
	Total: {% multiply line.purchase_price line.quantity %}<br>
{% endfor %}

{% block page_content %}
	<div>0: {{ customer.name }}</div>
	<div>1: { Total }</div>
	<div>2: {{ add_2numbers }}</div>
	<div>3: Subtract_3_from_4 </div>
	<div>4: {{ Multiply_two_numbers }}</div>
	<div>5: {{ Divide_10_by_2 }}</div>
{% endblock %}
```
but the result is not as i expected it to be.
![image](https://user-images.githubusercontent.com/130482028/236637821-68d0cb83-767f-45bd-800b-82052a16277e.png)

what am i missing or is this a bug in 0.11.0
Br Martijn

### Steps to Reproduce

create a sales order
upload above script
run it

### Expected behaviour

output from calculations
and or constants 

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment]
@mabroens I'm not sure where you got the idea that it would work like that 😛 

You cannot assign variables within the template in that fashion. In the last line when you try to access the `{{ Divide_10_by_2 }}` variable - that variable literally does not exist. 

If you want to assign a variable for later use, it *can* be done under certain circumstances but you'd need to look into the [django templating language](https://docs.djangoproject.com/en/4.2/ref/templates/language/).

For example you could do something like

```
{% multiply 3 5 as myvar %}
Result: {{ myvar }}
```

**Comment by derekwolfson** [comment]
Related to this -- why doesn't each line item have a total price associated with it as in the GUI? 

I get that we can calculate this using a django template -- but seems cleaner to include it so we can call directly via `{line.total_price}`

**Comment by mabroens** [comment]
Thx your hint helped and again learned some more.
Got it working now
