### ISSUE TITLE
Setting purchase price to 0 messes up pricing calulation in stocktake

### ISSUE THREAD

**Issue by winzkigermany** [inventree/InvenTree#4791]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Imagine, there are two stock entries for the same part. Currency does not matter, so I use €
One entry is: 100 parts for 0€
The other is: 200 parts for 1€

In a stocktake, this results in 300 parts, and a value of 300€
**instead of 300 parts, and a value of 200€**

Why is that? My best guess:
`if entry.purchase_price:` is false, so `has_pricing` never gets TRUE, hence `if not has_pricing:` is entered.
There, `pricing.overall_min` or `pricing.overall_max` is assigned as the price for the part, et voilà: wrong price, instead of 0€

InvenTree/part/tasks.py, around line 178, in perform_stocktake:

```
        # Update price range values
        if entry.purchase_price:
            # If purchase price is available, use that
            try:
                pp = convert_money(entry.purchase_price, base_currency) * entry.quantity
                total_cost_min += pp
                total_cost_max += pp
                has_pricing = True
            except MissingRate:
                logger.warning(f"MissingRate exception occured converting {entry.purchase_price} to {base_currency}")

        if not has_pricing:
            # Fall back to the part pricing data
            p_min = pricing.overall_min or pricing.overall_max
            p_max = pricing.overall_max or pricing.overall_min

            if p_min or p_max:
                try:
                    total_cost_min += convert_money(p_min, base_currency) * entry.quantity
                    total_cost_max += convert_money(p_max, base_currency) * entry.quantity
                except MissingRate:
                    logger.warning(f"MissingRate exception occurred converting {p_min}:{p_max} to {base_currency}")
```

### Steps to Reproduce

Create two stock entries with different amounts of parts, and give a purchase price of 0€ to one stock item, and 100€ to the other stock item.
Then create a stocktake.
The amount of both parts is correct, but the value(sum of prices) is not. 

### Expected behaviour

When a part has a purchase price of 0€, those 0€ should be reflected in stocktakes.
The part should not be priced with the price of the other stock item of the same part.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.1
Django Version: 3.2.18

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

**Comment by SchrodingersGat** [comment]
Does it make sense to allow for a purchase price of zero? I can see how this edge case would get through, but is it something which makes sense to allow?

**Comment by winzkigermany** [comment]
My 2 cents:
I can see that an additional flag "has been set" will have more implications further down for sure.
In my case, a "value needs to be != 0.0000" would be fine, too.

As a workaround, users *could* probably set a value of 0.0001 instead of 0.0 ... unless they're handling millions of parts, and need them to be 0.0€
