### ISSUE TITLE
[FR] Hosting Custom Django Tag/Filters on Binded Volume?

### ISSUE THREAD

**Issue by derekwolfson** [inventree/InvenTree#4793]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I'm learning about Django as I start building reports I want some fields besides the pre-defined context variables -- and I know just enough to be dangerous, I think.

For example -- I want to create a "subtotal" in a purchase order report -- which calculates the entire order value net of  extra line items (which are shipping and tax for me) -- I tried something like this inside the report .html file: 
```
{% add 0 0 as subtotal %}
{% for line in lines.all and other_lines.all%}
	{% add line.total_line_price subtotal as subtotal %}
...
{% endfor %}
```
besides not creating an iterative subtotal -- all the stackexchange stuff I see is this is the _wrong_ way to Django anyways: don't calculate anything on the fly -- just create templates/tags that are defined in ``templatetags`` directory upstream of the relevant ```models.py```.  It makes sense to me -- this is a simple python object to create.

The problem I'm running into is -- this directory is _part and parcel_ of the source -- so editing directly isn't a good solution.  I'm guessing the *right* way to do this is via the Docker Compose file but I do not know how.

I *think* I found the relevant place to tell django  to look for new tags/templates here: 
https://github.com/inventree/InvenTree/blob/57502a1ad8c051ba7eeb0c11eee146af12ba9db1/InvenTree/InvenTree/settings.py#L311-L341

But I'm at a complete loss on how to add some "user defined templates/tag" to this directory without directly editing the source code.

I would really value more flexibility to the reports-- but given that Django doesn't want you to do variable creation outside of the template file -- I think it would be nice if there was a directory (or directories) where we could store these on the binded volume and have them automagically map into the relevant source code accordingly.

### Suggested solution

N/A

### Describe alternatives you've considered

Probably a lot of complex `{% django stuff %}`

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by derekwolfson** [comment]
Silly me -- I didn't see the [ReportMixin class ](https://docs.inventree.org/en/latest/extend/plugins/report/) which is exactly what I want....

Might be worth expanding the documentation to: 

>  Extending with Plugins[¶](https://docs.inventree.org/en/latest/report/report/#extending-with-plugins)
>
>The [ReportMixin plugin class](https://docs.inventree.org/en/latest/extend/plugins/report/) allows reporting functionality to be extended with custom features.

To something that says a bit more about user-defined Django tags/filters and variable creation.

I've read that "mixin" statement a few times -- and only now that I know what I am looking for did it even click.

**Comment by SchrodingersGat** [comment]
@derekwolfson the ReportMixin class is quite new so please raise an issue if something doesn't work right or you have any questions!

**Comment by matmair** [comment]
I would start by reading all plugin pages in the docs and getting familiar with all the mixins we offer. I think most of the stuff you could need should be there.
If you implement an AppMixin you can register your own template tags - that will probably help with creating very custom plugins. As for the usage of SQL: You should not directly use or access SQL as a bunch of stuff can go wrong there. Django exposes a function Python API to interact with objects.
If you want to develop your own stuff, it could be beneficial to get familiar with Django itself. We tend to follow their best practices (where we are aware). [This](https://docs.djangoproject.com/en/4.2/intro/tutorial01/) is a great tutorial by them. It gives a good overview of the framework. The AppMixin allows you to introduce your own Django apps so everything shown there could be used.

**Comment by derekwolfson** [comment]
Sweet. There’s a lot of great info in here.

I think the learning curve might be a bit steep — but once I figure out one
variable/tag — it should scale pretty quickly.
