### ISSUE TITLE
[FR] Add delivery date to shipment

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#4794]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I would like to keep track of when shipments are delivered, not only when they are shipped.

### Suggested solution

Add a 'delivery date' field to shipments, similar to the shipment date.

This field does not have to have any logic attached to it, it should be:
1. shown in the shipment overview
2. possible to filter shipments in the API which are delivered/not delivered (just like shipped)

### Describe alternatives you've considered

Placing the delivery date in metadata, but that doesn't allow easy filtering of the list of shipped/not-delivered.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
Seems like a reasonable addition to me, even without any additional business logic
