### ISSUE TITLE
After receiving line items in PO, page has to be refreshed to show received stock

### ISSUE THREAD

**Issue by MR-DOS** [inventree/InvenTree#4797]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When line items are received in Purchase Order, switching to Received Stock shows nothing. A refresh of the page is required.
Tested on current official 0.11.0 docker image.

### Steps to Reproduce

Create purchase order with at least 1 Line item.
Release the order.
Receive the item.
Look into Received stock pane.

### Expected behaviour

Page should autorefresh its contents or indicate that user should do so manually.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18
Commit Hash: 593a716
Commit Date: 2023-04-18
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment]
@MR-DOS seems to work as expected on my end. Receiving items against the order refreshes the "received items" table. Have you tested on the demo server?

**Comment by MR-DOS** [comment]
Checked on demo server, does the same.
![image](https://github.com/inventree/InvenTree/assets/29711626/5d60424c-7761-4f5f-bb19-221a785fb2f1)
![image](https://github.com/inventree/InvenTree/assets/29711626/0885be6a-2a19-44f1-9e6e-6dbca2ecf245)

**Comment by SchrodingersGat** [comment]
When you say a manual refresh of the page is needed - does a refresh of the "received items" table (not the whole page) work also?

**Comment by MR-DOS** [comment]
Oh, there's a button for that. Didn't see that. OK, that's one solution. But would it be possible to trigger the refresh also on confirmation of the received items automatically?

**Comment by SchrodingersGat** [comment]
@MR-DOS very possible, and (at least on my local installation) it *does* do exactly that. Still trying to work out why it's not on yours

**Comment by MR-DOS** [comment]
Tested on current Firefox and Chrome. Firefox with uBlock turned on, Chrome with both on/off. The page reloads correctly after closing the order, but not after confirming receipt of items in all these 3 cases.

**Comment by SchrodingersGat** [comment]
@MR-DOS can you check in the developer console in your browser to see if there are any javascript errors?

I've just tried on the demo server and it works as expected for me:

1. Receive items against purchase order
2. Select "received stock" tab (without reloading page)
3. Received stock items are visible in stock table

**Comment by SchrodingersGat** [comment]
This will be addressed in our UI refactor (in progress).
