### ISSUE TITLE
NOT NULL constraint failed: stock_stockitem.quantity

### ISSUE THREAD

**Issue by brendanross** [inventree/InvenTree#48]
When trying to create an stock item, the quantity can not be set as it is marked read only. I may be missing something, but shouldn't that field be able to be set when creating the item since it cannot be set to NULL?

I changed it to so it could be set as a workaround for now. Let me know if I'm overlooking something.

**Comment by cymonx** [comment]
please give me all table structure.

**Comment by SchrodingersGat** [comment]
@brendanross not quite sure what you mean here - is it "read only" in the admin interface?
