### ISSUE TITLE
Show "Batch" page

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#480]
Display all stock items for a given "batch" code.

- May be all together
- May have been split into multiple locations
- May be installed in other parts ("Build")
- May be sold to customers

This should be a separate page, rather than just a stock "filter" because not all items are necessarily "in stock"

**Comment by SchrodingersGat** [comment]
This may be as simple as showing a "track" page for parts that are trackable

**Comment by IsThisNameGoodEnough** [comment]
Lots of value on this one!  This would be very helpful if a particular batch of parts needs to be recalled/investigated.  Perhaps an export function to csv/xls/etc as well (would be helpful if you need to document corrective actions for a CAPA).

**Comment by SchrodingersGat** [comment]
@IsThisNameGoodEnough the latest updates now provide the ability to export a list of Parts (under a PartCategory) or Stock (under a StockLocation).

I'll have to work on how to integrate the "batch" view.. But I agree it is very useful
