### ISSUE TITLE
Permission denied for mkdir: /home/inventree/data/static

### ISSUE THREAD

**Issue by AlexPerni** [inventree/InvenTree#4802]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I've followed the install guide for docker production and after I run "docker compose run inventree-server invoke update" I get the error message "mkdir: cannot create directory '/home/inventree/data/static': Permission denied"
I am running the command as super user. Also all the other containers I've run so far, I never had this issue. So I'm a bit puzzled. 
Due to this error the container "inventree-production-inventree-server-run-099234e15f89" exits with an error. 

General solution from google did not work for me. But I am also still learning how to use docker correctly. 
Any help would be appreciated. 

### Steps to Reproduce

1. download production directory from the repo with .env, docker-compose.yml and nginx.prod.conf files
2. configure only the .env file with external volume (/mnt/nas/DB/InvenTree/) etc.
3. switch to su
4. run command "docker compose run inventree-server invoke update"

### Relevant log output

```bash
root@porty:/home/porty/Downloads/InvenTree# docker compose run inventree-server invoke update
[+] Running 2/2
 ✔ Network inventree-production_default  Created  0.2s
 ✔ Container inventree-db                Created  0.9s
[+] Running 1/1
 ✔ Container inventree-db  Started  0.6s
Creating directory /home/inventree/data/static
mkdir: cannot create directory ‘/home/inventree/data/static’: Permission denied
```

**Comment by matmair** [comment]
hi there @AlexPerni 
have you checked if  your docker user has full rights on`/mnt/nas/DB/InvenTree/` ? Maybe try to create a file 
`
su docker -c "nano /mnt/nas/DB/InvenTree/test.txt"
`

**Comment by AlexPerni** [comment]
Hi @matmair 
that was it! Foolish beginners fault, I did not test if I can do anything on the external mounted storage. 
Fixed it, thank you very much :)

**Comment by matmair** [comment]
Typical problem; even after 10 years sysadmin'ing I still run into it sometime.

**Comment by SchrodingersGat** [comment]
We should add this to the FAQ
