### ISSUE TITLE
Issue display data after migration to 0.11.0

### ISSUE THREAD

**Issue by icvdok** [inventree/InvenTree#4807]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Data not available on gui after migration to 0.11.0 version.

After the migration from V0.10.1 to 0.11.0 the gui doesn0t show the data (Parts, Stock, PO, etc.)
Data are successfully migrated and available because i can access to them via search.

Something wrong during the update or I' missing some new config available with the new version?

In the meantime, I've back on the previous version.

I'm not a superexpert therefore any help is welcome.

Thanks

### Steps to Reproduce

Setup on docker
Command launched according to the manual, no significant errors during the upgrade except a bunch of these:

**_fatal: not a git repository (or any of the parent directories): .git_**

After the migration, all dockers have started and are up and running as usual.

### Relevant log output

```bash
[+] Running 4/4
 ⠿ Container inventree-db      Running                                                                                           0.0s
 ⠿ Container inventree-server  Started                                                                                              1.3s
 ⠿ Container inventree-proxy   Started                                                                                              2.6s
 ⠿ Container inventree-worker  Started                                                                                              2.6s
```

**Comment by SchrodingersGat** [comment]
Have you tried a hard-refresh of your browser cache? - https://docs.inventree.org/en/latest/faq/#feature-x-does-not-work-after-update

**Comment by icvdok** [comment]
I'll check thanks

**Comment by icvdok** [comment]
It was the cache to clean :-), i feel stupid. Thanks again for the support.
