### ISSUE TITLE
[Bug] Unit testing for notifications takes excessive amount of time

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4821]
During testing for https://github.com/inventree/InvenTree/pull/4817 I discovered that some of the unit tests (in particular related to notifications) take a *very* long time to execute. It also appears that calling notifications can cause the plugin system to reload multiple times (which is very time consuming).

In this example we'll use the following unit test as an example:

```
build.test_build.BuildTest.test_overdue_notification
```

Running *just* this test shows that it takes ~90 seconds to run:

![image](https://github.com/inventree/InvenTree/assets/10080325/a48efecf-be00-4fc4-8376-9f544d861d54)

The culprit is the method `build.tasks.check_overdue_build_orders` which I have instrumented as follows:

![image](https://github.com/inventree/InvenTree/assets/10080325/da713317-24aa-4102-bc64-58d3d5b68fd4)

And processing the output of this profile:

![image](https://github.com/inventree/InvenTree/assets/10080325/99ed991b-a76b-4506-9d15-89c1b77fd1c7)
![image](https://github.com/inventree/InvenTree/assets/10080325/10799891-4d75-495b-a43b-d23d5efbc26e)

Looking further we can see that it is taking a *lot* of time to load / unload plugins (which it should *not* be doing here!)

![image](https://github.com/inventree/InvenTree/assets/10080325/ad39f574-5a7d-448a-80ef-e885d172e7dd)

Profiling data attached below:

[profile.txt](https://github.com/inventree/InvenTree/files/11473769/profile.txt)

@matmair this may be related to your recent plugin changes - can you take a look when you have some time? 

This is likely one of the large causes of long CI tests, and also is probably happening in production code too.

**Comment by matmair** [comment]
@SchrodingersGat the timings for tests did not really change in azure devops so maybe this has been going on for longer; there should not be an additional reload - I will look into it

**Comment by SchrodingersGat** [comment]
Cheers, LMK what you find!

**Comment by matmair** [comment]
@SchrodingersGat I have not really found a reason yet. Concentrating on #3261 / #4857 rn. Should I move this forward?

**Comment by SchrodingersGat** [comment]
Not urgent, whenever you have time 🙏

**Comment by SchrodingersGat** [comment]
@matmair have you had any further thoughts on this one? Ideally I'd like to get the testing framework sped up a lot before we release 0.12.0

**Comment by SchrodingersGat** [comment]
Will be closed by https://github.com/inventree/InvenTree/pull/5087
