### ISSUE TITLE
[Feature] Define different "types" for parameters

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4835]
Ref: https://github.com/inventree/InvenTree/pull/4823
Ref: https://github.com/inventree/InvenTree/pull/3983

Add distinct parameter types:

- String
- Numeric
- Boolean

Also allow for "choices" input which defines allowable values

**Comment by matmair** [comment]
Ref: https://github.com/inventree/InvenTree/issues/3985
Ref: https://github.com/inventree/InvenTree/issues/3862
