### ISSUE TITLE
PanelMixin get_custom_panels not getting called for part list view

### ISSUE THREAD

**Issue by IvoLealMCS** [inventree/InvenTree#4838]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I want to add a custom part import panel, for that I'm trying to use the PanelMixin for my plugin.
But I realized the part list view "http://inventree_server/part/" ignores the plugin and doesn't call the get_custom_panels method.

### Steps to Reproduce

create plugin with PanelMixin that always returns a test panel.
open part list, the panel doesn't show

### Expected behaviour

The panel should show

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.10.0
Django Version: 3.2.16

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'EMEImport', 'slug': 'emeimport', 'version': '0.0.1'}]

**Comment by SchrodingersGat** [comment]
@IvoLealMCS you'll need to provide more information here - do you have a link to your plugin or a snippet of code? Otherwise not much we can help with

**Comment by wolflu05** [comment]
I think this is a feature request because the InvenTreePluginViewMixin is missing on the PartIndex view.

**Comment by SchrodingersGat** [comment]
@wolflu05 ah, I see. I guess that makes sense to add that mixin then :)

**Comment by IvoLealMCS** [comment]
> @IvoLealMCS you'll need to provide more information here - do you have a link to your plugin or a snippet of code? Otherwise not much we can help with

Here you have it:
`
from plugin import InvenTreePlugin
from plugin.mixins import PanelMixin

from part.views import CategoryDetail


class ImportPlugin(PanelMixin, InvenTreePlugin):
    NAME = "ImportTest"
    DESCRIPTION = "Test"
    VERSION = "0.0.1"

    def get_custom_panels(self, view, request):
        with open('/etc/inventree/custom_log.txt', 'a') as f:
            f.write(str(type(view))+'\n')
        panels = []
        if isinstance(view, CategoryDetail):
            panels.append({
                'title': 'Test',
                'icon': 'fa-file-upload'
            })
        return panels
`

But either way I believe @wolflu05 undertood my issue correctly, and if so, sorry for the incorrect category, I believed it was a bug because in the remaing views it works
