### ISSUE TITLE
Properties with spaces in label templates

### ISSUE THREAD

**Issue by clj** [inventree/InvenTree#4839]
### Body of the issue

The [documentation on properties in labels](https://github.com/inventree/InvenTree/blob/4785f465e8bfef8cd262fefe9ec33b927da6a57e/docs/docs/report/labels.md?plain=1#L309) shows how to print a parameter using the dot syntax, e.g.:

```
{{ parameters.length }}
```

It isn't clear how I would print a parameter that has a space in its name though, like "Rated Power" or the like. Django doesn't seem to like the syntax:

```
{{ parameters["Rated Power"] }}
```

Is there already something that would make this work? and if so could it be added to the docs? Thanks!

**Comment by SchrodingersGat** [comment]
See https://docs.inventree.org/en/latest/report/helpers/#data-structure-access :)
