### ISSUE TITLE
Part parameter title in modal

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#4847]
Editing part parameters does not display parameter name/details/units/etc in pop-up modal. Getting distracted can lead to forgetting what parameter you're editing. 

I suggest modifying parameter API calls to include parameter template information for display purposes. 

I'm thinking of tackling this as soon as I finish my current feature

**Comment by SchrodingersGat** [comment]
@LavissaWoW that'd be great. We have something similar for the "Supplier Part" dialog which works great:

![image](https://github.com/inventree/InvenTree/assets/10080325/0fece552-4012-40ed-ad4f-d3ddb866d60f)

LMK if you want any pointers on where to look in the code!

**Comment by LavissaWoW** [comment]
@SchrodingersGat Looks like this came in via the recent work on parameters.
![image](https://github.com/inventree/InvenTree/assets/7506688/874c88f8-d926-4f60-a79a-e2d667ddcaf6)

I'm happy with this, in general. Could probably make some UX tweaks here and there, but the benefit wouldn't outweigh the effort to customise the form.

**Comment by SchrodingersGat** [comment]
@LavissaWoW fair enough, happy to close this issue out then?

**Comment by LavissaWoW** [comment]
@SchrodingersGat Yup.
Issue resolved
