### ISSUE TITLE
print reports are broken on v0.11.1

### ISSUE THREAD

**Issue by papgrap** [inventree/InvenTree#4856]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hello

I updated to inventree version 0.11.1 and now my PDF reports don't work anymore. I tried with the builtin reports and I get the same error:

```
Traceback (most recent call last):

File ".. /InvenTree/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File ".. /InvenTree/InvenTree/report/api.py", line 263, in get
return self.print(request, items)

File ".. /InvenTree/InvenTree/report/api.py", line 228, in print
doc = output.get_document()

File ".. /InvenTree/venv/lib/python3.10/site-packages/django_weasyprint/views.py", line 80, in get_document
return html.render(

TypeError: HTML.render() got multiple values for argument 'font_config'
```

I also tested in report-debug-mode and there I don't get any errors.
Can you reproduce this bug or is this somehow related to my setup?

### Steps to Reproduce

1. Use Inventree version 0.11.1
2. Open a build and print Inventree build order report

### Expected behaviour

I expected my nice PDF reports.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.1
Django Version: 3.2.18
Commit Hash: e21a75066
Commit Date: 2023-05-19
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'AutoAdjustIpn', 'slug': 'autoadjustipn', 'version': None}, {'name': 'DeliveryPlugin', 'slug': 'deliveryplugin', 'version': '1.0.2'}, {'name': 'IpnFinder', 'slug': 'ipnfinder', 'version': '1.0.1'}]

**Comment by SchrodingersGat** [comment]
@papgrap I'm assuming you ran `invoke update` as part of your migration process?

What OS / version are you running? Might be related to some of your system packages?
