### ISSUE TITLE
Rejection process for Orders

### ISSUE THREAD

**Issue by IsThisNameGoodEnough** [inventree/InvenTree#486]
Hope you don't mind the issue submissions.

Currently there is no clean way I've seen to deal with damaged / out of spec parts when they're received.  My current approach is to create a "rejected" location and receive parts to that location, then perform a stock out for the rejected parts and record the rejection reason in the stock out notes.

It would be great to have a reject button similar to the receive button on the purchase order page, which would combine the processes laid out above (or setup new database tables instead of treating it as normal stock).

**Comment by SchrodingersGat** [comment]
What do you mean by a "stock out" in this context?

**Comment by IsThisNameGoodEnough** [comment]
Using the "Take from stock" button on the Stock Items Detail page.

![tempsnip](https://user-images.githubusercontent.com/55004464/64530106-573f9900-d2da-11e9-903b-74a02f45a3bc.png)

**Comment by SchrodingersGat** [comment]
Ah, gotcha. Each stock item has a "STATUS" field which could be used to signify that stock has been rejected? Would that be sufficient for your use case?

**Comment by IsThisNameGoodEnough** [comment]
I think that could work, but it looks like inventory is still counted for stock that have a status field other than OK.  If only the status field is used to denote and the quantity of rejected stock isn't removed (via a "take from stock" or similar process) it could cause issues with builds, inventory planning, etc.

I think a good rejection process could be something like:
1. Press "Reject Items" button on purchase order page.
2. Have a pop-up "Reject parts" page similar to the current receive parts page.  User will choose location and qty to reject. (user can setup a "quarantine" location or similar for this).  Page also allows the user to include an optional "reason for rejection" note.
3. InvenTree uses the same process as receiving a part, with the following exceptions:
  3A. The status field is marked as "Rejected"
  3B. The stock description is a concatenation of the statement "Rejected X items against order 'YYYY': " and the reason for rejection note the user entered in step 2.
4. Any stock with status fields other than OK cannot be selected for builds and do not count towards stock qty of the part, although you can still see the stock row (see image below for example).

![tempsnip](https://user-images.githubusercontent.com/55004464/64629711-b4624a00-d3c1-11e9-9a78-aa085fd1d594.png)

This would allow users to mark items as rejected with reasons (e.g. "dimension XYZ out of spec"), quarantine the part, and at a later date remove the stock via the "take from stock" process while including a disposition note (e.g. scrapped, returned to vendor, etc).  While the parts are still on-site they won't be included in counting/builds/etc.
