### ISSUE TITLE
apt-key deprecated

### ISSUE THREAD

**Issue by c0fe** [inventree/InvenTree#4866]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Installation is done on bare metal Debian Bullseye distro. It threw an error saying that `apt-key` is deprecated. Are there plans to update this?

`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).`

### Steps to Reproduce

Install inventree using repo with the installation instructions posted:

https://docs.inventree.org/en/latest/start/installer/

**Comment by matmair** [comment]
Hi there @c0fe. Using apt-key is the recommended way of our packaging tool, therefore we use it.
As long as the official recommendation by the tool is not changing we are unlikely to change as there is no reassurance other ways might not break.

**Comment by matmair** [comment]
@c0fe we are using `pkgr` / https://packager.io/ for hosting. You can see our build dashboard [here](https://packager.io/gh/inventree/InvenTree). The suggested instal instructions are listed [here](https://packager.io/gh/inventree/InvenTree/builds/492/install/debian-11) for example (Note: this is for the master (unstable) branch. Do not use this in production)
