### ISSUE TITLE
Add update automation

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4869]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Whenever i want to update Inventree (Bare metal from easy setup) i struggle with this. particularly since im not confident enough with Linux.

I know i'm running on Ubuntu 20.04.6. 
would it be possible to add a script that:
- pulls the latest from git, 
- Creates backups
- stops all what is required, 
- updates it all 
- starts it again

this would make life so much easier for me and others that do not master linux.

i have read the docs on https://docs.inventree.org/en/0.7.6/start/update/
but :
![image](https://github.com/inventree/InvenTree/assets/130482028/eba506f9-1381-4fe1-96a8-88df79135d89)

doe snot help me sorry for that

### Suggested solution

provide a script that:
- pulls the latest from git, 
- Creates backups
- stops all what is required, 
- updates it all 
- starts it again

### Describe alternatives you've considered

think this is the best alternative

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Several points @mabroens
* you are linking a year-old version of the docs
* it is not clear what setup you use; we have: bare metal developer, bare metal production, package installer and several docker versions
* bare metal is meant for ppl proficient in Linux administration - see the explicit [warning](https://docs.inventree.org/en/stable/start/install/)
![grafik](https://github.com/inventree/InvenTree/assets/66015116/4438ff7c-ca42-4950-938e-033648a17ae0) We can't really teach every new user how to administer a server. Either docker or the package distributions are suitable for that user group
* the package-based installs (used by the [installer](https://docs.inventree.org/en/stable/start/installer/) or installed [by hand](https://docs.inventree.org/en/stable/start/installer/#manual-install)) auto-update with the OS - doing all required steps - I do not see any value in having 2 separate places that we need to keep updated

**Comment by mabroens** [comment]
@matmair thanks for the response and agree if there is a version that supports this than it should be fine.
you mention: 
"the package-based installs (used by the [installer](https://docs.inventree.org/en/stable/start/installer/) or installed [by hand](https://docs.inventree.org/en/stable/start/installer/#manual-install)) auto-update with the OS - doing all required steps - I do not see any value in having 2 separate places that we need to keep updated"
i went to this installer link and i believe thats what i did. 
![image](https://github.com/inventree/InvenTree/assets/130482028/b336ebf0-282a-4fc8-8425-a5148e69c5a6)

can you please verify this for me:
# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18


Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

according to your writing and if i'm right, and i can not believe i went any other direction installing InvenTree, but again please confirm or tell me how i can find out or even better make sure i switch to the automated flow.

Thanks in advance Martijn

**Comment by matmair** [comment]
@mabroens we can not verify it based on the version information. There is a PR for that but I did not get around to implementing that up to now.
Please run the following in a shell as a privileged user `inventree config` - what is the return?

**Comment by mabroens** [comment]
@matmair here is the response
```
sudo su
inventree config
APP_GROUP=inventree
APP_HOME=/opt/inventree
APP_NAME=inventree
APP_RUNNER_CLI=systemctl
APP_RUNNER_TYPE=systemd
APP_SAFE_NAME=inventree
APP_USER=inventree
APP_WIZARDS=
FORWARDED_ALLOW_IPS=*
GUNICORN_CMD_ARGS=--access-logfile -
HOME=/home/inventree
INVENTREE_CONFIG_FILE=/etc/inventree/config.yaml
LANG=en_US.UTF-8
OLDPWD=/
ORIGINAL_PWD=/home/spectrum
PATH=/opt/inventree/.heroku/python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/sbin
PORT=6000
PWD=/opt/inventree
PYTHONHASHSEED=random
PYTHONPATH=/opt/inventree
PYTHONUNBUFFERED=true
ROOT_PATH=/
SHLVL=0
```

**Comment by matmair** [comment]
@mabroens it seems like you used the single-line installer.
Using git to update is neither required nor recommended with this method. Your InvenTree will update with system updates (for Ubuntu that would be running `sudo apt update && sudo apt upgrade`) once a new version is released to stable.

**Comment by mabroens** [comment]
thanx. that helps.

i ran the `sudo apt update && sudo apt upgrade` but after that and reboot the info box still mentions update availeble:
![image](https://github.com/inventree/InvenTree/assets/130482028/e6cf7b09-8329-4789-aec4-be3dd2eb78c1)

is that expected?

**Comment by matmair** [comment]
We were made aware of an issue with automation on the stable packaging channel yesterday, I will ping you once the point-releases are up up there too.

**Comment by mabroens** [comment]
ok thx for updating me on this. i will just sit this one out for the auto update i'm now aware it should do it automatically so wait for it :-) thx.

pls ping me once the point-releases are up up there
 
br martijn

**Comment by matmair** [comment]
@mabroens running the updates should work now. Please report back if you find time!

**Comment by mabroens** [comment]
@matmair thanks for pinging me. 
i ran `sudo apt update && sudo apt upgrade` as **root** and now its upgraded to **[0.11.2]**

thanks and confirmed :-)

**Comment by matmair** [comment]
Nice; so can we close this as not planned or completed?

**Comment by mabroens** [comment]
Yes, we certainly can works like a charm. perhaps it would be a good idea to mention this in with the installation steps that updates will be pushed automatically when running  `sudo apt update && sudo apt upgrade` this would avoid further questions i hope.

many thanks Br MArtijn

**Comment by matmair** [comment]
That is the default behaviour for Debian/Ubuntu (and most other Linux distros) but I will look for a place that fits this information
