### ISSUE TITLE
HTML support in markdown fields

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4877]
Markdown fields do not currently allow any HTML tags.

This means that (for example) you cannot specify the size of an image, or use raw html (which would be useful).

To achieve this we will need to "relax" our approach to stripping out HTML tags, so needs to be very carefully considered

**Comment by matmair** [comment]
@SchrodingersGat this has great potential to cause XSS (and friends) issues - maybe we should add some testing for these issues as a QC step?
