### ISSUE TITLE
Sales order assigning serial number add selection box

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4887]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Feature request

Hi,

currently when creating a sales order you have the chance to allocate stock and/or assign serial numbers for trackable parts.

**Question 1:**
when i select allocate stock i get the option to select a stock item:
![image](https://github.com/inventree/InvenTree/assets/130482028/ccabb0c5-9b5f-48da-803e-07c8c337a2d8)

i assume this is to select the stock item in question, and in this case also the serial number. then why is there a qty option? or what is the idea behind this?

**Question 2:**
when i go for the `allocate serial numbers`:
![image](https://github.com/inventree/InvenTree/assets/130482028/1f3a9c82-6338-4e2f-9306-60dba98a8650)

![image](https://github.com/inventree/InvenTree/assets/130482028/3e75ffe8-4c4b-4df5-a3a3-3b235780ba7c)

would it be possible to provide a list of available serial numbers like shown with the `allocate stock` ? and than with checkboxes that way you can in one go select multiple serial numbers and allocate them to the order.

makes it way more convenient and it seems like part of the feature is already availeble

Br Martijn

### Suggested solution

reuse the allocate stock popup.
add checkboxes or allow selection of multiple serial numbers in one go

### Describe alternatives you've considered

see above

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
> then why is there a qty option? or what is the idea behind this?

You might want to allocate a group of stock items (quantity > 1) to a sales order line. Not all sold items are tracked by SN

> would it be possible to provide a list of available serial numbers like shown with the allocate stock ? and than with checkboxes that way you can in one go select multiple serial numbers and allocate them to the order.

Potentially, this data should all be accessible by the API. The hard part would be implementing the UX code

**Comment by SparkeyinVA** [comment]
I would like to second this request.  While the process for allocation and moving of stock is wonderful as is for untracked items (no serial number) when doing the same process in Inventree for items which are tracked (with serial numbers) it can become very tedious.  

For example if I need to allocate a box of 100 tracked items to a shipment on a sales order, I must select the item and the sales order 100 times.  

If there was a process where multiple tracked items could be selected for a process it would help.

**Comment by SchrodingersGat** [comment]
@SparkeyinVA you can specify serial numbers by range e.g. `100-134, 150, 160, 199+` in the dialog box - is this what you are looking for?

**Comment by matmair** [comment]
@SparkeyinVA ranges will not work with items that are using elements that we use to assign numbers. those are mainly `-`, `,`, `+` - read more about them [in the docs](https://docs.inventree.org/en/latest/stock/tracking/#generating-serial-numbers).

**Comment by mabroens** [comment]
@matmair thx for the hint. I had a look an its helpful. 
In my case the serial numbers are represented by MAC addresses. Obviously removing the : form the mac and convert to a hex number but it will be a very large one. 

Also since we have our own mac ramge the first aa:bb:cc:dd is fixed so we could treat that as a batch code and have the rest as a hex serial. 

Could that work?

**Comment by matmair** [comment]
It could.
The best way would be to create a plugin that implements the [Validation Mixin](https://docs.inventree.org/en/0.9.1/extend/plugins/validation/#serial-number-sorting) for your serial number format.

**Comment by SchrodingersGat** [comment]
my 2 cents - if this is not solved with a custom plugin, perhaps the new UI could support "multi select" dropdowns. Would that go some way towards providing the functionality you are looking for?

**Comment by mabroens** [comment]
@SchrodingersGat ,
i would go for the new UI. what you need is partially exsisting for allocate stock. i understand its not that straight foreward but..
Br martijn

**Comment by walkermc20** [comment]
> my 2 cents - if this is not solved with a custom plugin, perhaps the new UI could support "multi select" dropdowns. Would that go some way towards providing the functionality you are looking for?

Yep, should work fine with a multi-select dropdown.  As long as I can see which serial number / batch number I'm delivering to the customer, I'm good to go.  As long as we're dreaming of cool stuff, knowing how many they ordered and how many I've selected (i.e. - 7/37 selected) would be good.

**Comment by SchrodingersGat** [comment]
With the new user interface, implementing these features should be much easier. Additionally, it should be easier for other developers to contribute too :)

**Comment by walkermc20** [comment]
Not stale.  Want this in the new user interface please!

Michael Walker

**Comment by SchrodingersGat** [comment]
not stale

**Comment by hvraven** [comment]
not stale, please reopen

**Comment by mabroens** [comment]
agree please do not close.

**Comment by mabroens** [comment]
Hi Team, is there any progress on this topic?
Just now again i was facing the issue: create a SO. add 2 items, need to select the Serial number but the system does not take it:
![image](https://github.com/inventree/InvenTree/assets/130482028/f9f8e5eb-edb6-444c-b834-360d068935f2)

though stock says:
![image](https://github.com/inventree/InvenTree/assets/130482028/f383d7a9-e14b-42af-a928-0cb9a5b9cac5)


so what am i doing wrong. this would not have happened if the available stock would have been a pulldown or select list.

Alternative benefit when having a list to pick from is that one could also just type in/select the serialnumber and the rest of the attributes would follow.
example: go to you stock pick one out search by serial from within the SO. and voila all data is there.

**Comment by SchrodingersGat** [comment]
> so what am i doing wrong.

The serial numbers are case sensitive..

**Comment by mabroens** [comment]
yeah sorry just found that out as well. need to correct that in my db than.
thnx
