### ISSUE TITLE
[FR] Use parameters in name template

### ISSUE THREAD

**Issue by IvoLealMCS** [inventree/InvenTree#4888]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

For the system I'm implemeting there is a lot of data for a part, I used parameters to add this data to each part.
I want to be able to reference the parameter value in the "Part Name Display Format".

Is this possible? If yes, how?

### Suggested solution

Allow acess to paramters in the template system something like part.parameters.<paremeter name> 

### Describe alternatives you've considered

Don't know

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
> I want to be able to reference the parameter value in the "Part Name Display Format".

Sorry @IvoLealMCS I'm not sure I fully understand what you are asking here. Can you expand on this a bit?

**Comment by IvoLealMCS** [comment]
Sorry, I Will try to explain it better.
In the settings webpage, in server settings > parts.
There is a setting called "Part Name Display Format" which the value is a template for creating the part name display. 
In it i can access part.revision, part.IPN, etc.

What I'm asking is:
Is it possible to use values from part parameters in this template? Is yes, how?

**Comment by matmair** [comment]
Not currently but an easy change, working on it right now.

**Comment by SchrodingersGat** [comment]
> Not currently but an easy change, working on it right now.

"part name display" format is used to display part names in the API, so be careful that your implementation does not run multiple queries on the DB or API access will be hit

**Comment by matmair** [comment]
Ok, we do not need anything new. Something like this works (but has a slight effect on the performance as 1 lookup is added per part):
```{{ part.parameters.filter(template__name='Color').first().data}} {{ part.name }}```

@SchrodingersGat are we married to 200 chars for the template field?

**Comment by IvoLealMCS** [comment]
Looking at that, is the parameters a django queryset in this situation? So all the queryset API is available?

**Comment by matmair** [comment]
Yes! Actually, you can use all functions exposed in Django for the part instance. I always forget about that part. Proceed with a bit of caution: The more sophisticated/database heavy your part name definition is the longer the calculation takes. This can have a noticeable impact on API performance.

**Comment by wolflu05** [comment]
Doesn't Django's mechanism use joines under the hood? Or is this something like the n+1 problem?

**Comment by matmair** [comment]
The calls are made per part within a function so that does not work in this case; here is the code that does it. https://github.com/inventree/InvenTree/blob/433ea4d0ded6018c81bc210d1a73206a3c85ee28/InvenTree/part/models.py#L736-L743

**Comment by SchrodingersGat** [comment]
You could *maybe* consider adding a `prefetch_related('templates')` to the API queryset, which should reduce the query complexity from O(n) to O(1) - but would need testing

**Comment by matmair** [comment]
@IvoLealMCS have you tried the solution? Is it performing well enough for you and can we close it?

**Comment by IvoLealMCS** [comment]
Yes, It is working. But still have a small amount of parts, so no idea on the performance impact. I'm fetching 2 parameters.
