### ISSUE TITLE
Missing alt tags in templates

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#4890]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

My PR QC checks failed with:
https://github.com/inventree/InvenTree/actions/runs/5072715583/jobs/9110794538

I have not touched those templates, so I do not know how did they failed for me now (as I see the latest master commits passed QA).

If this is really an issue I can fix it with a PR quite easily.

### Steps to Reproduce

-

### Expected behaviour

-

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

master

### Relevant log output

```shell
https://github.com/inventree/InvenTree/actions/runs/5072715583/jobs/9110794538
```

**Comment by matmair** [comment]
@martonmiklos are you sure this was not caused by the version bump in the linting tool?

**Comment by martonmiklos** [comment]
> @martonmiklos are you sure this was not caused by the version bump in the linting tool?

Dah, you have the point, I reverted that accidental change and we will see if the QC will pass.

**Comment by matmair** [comment]
Bumping versions on the linting tools often leads to "interesting" behaviour. Those actions should always be a separate PR - we had a hard time diagnosing issues like that before.

**Comment by martonmiklos** [comment]
> Bumping versions on the linting tools often leads to "interesting" behaviour. Those actions should always be a separate PR - we had a hard time diagnosing issues like that before.

Yes I apologize for committing it "blindly". How should we deal with this lint upgrade? I could send a PR which bumps the version and fixes the issues if you would like to.

**Comment by matmair** [comment]
That would be a good approach. I normally need 3-4 full CI runs to get all issues with linking updates so don‘t be discouraged.

**Comment by SchrodingersGat** [comment]
@matmair can this be closed out?
