### ISSUE TITLE
Report footer seems not fixed to position hence not always printing same content/location

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4893]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi guys,

i was playing with a SO report that has a company logo, invoice details, line details and, finally a footer with again a logo and some text. but it seems like the footer is not always printed at the same position/offset.

I was wondering if thers any way that i can upload my template to the online test environment to see if it reports the same there?
currently i could not access the site administration 

below i have added screenshots of the result including my template. could you pls advice why the footer is not printed correctly

thx Martijn

### Steps to Reproduce

1. Upload attached template
[InvoiceTemplate_Export.html.txt](https://github.com/inventree/InvenTree/files/11561760/InvoiceTemplate_Export.html.txt)
I have added background red to the footer to make it more clear.

2. create a SO with multiple line items such that it exceeds one page.
3. print so report
4. see the deltas
![image](https://github.com/inventree/InvenTree/assets/130482028/f3e3a516-affe-45bc-a6d5-3f0a00f190d8)
 
The red areas should be 
a) at the same offset from the lower left corner of the page. 
b) be from same size with same number of line
c) not overlap wit the lines

### Expected behaviour

i would expect the footer to always be consistent from size and position.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment]
@mabroens you might run into issues if your footer content is taller than the allocated footer margin size.

Check out the way that the page is defined [here](https://github.com/inventree/InvenTree/blob/master/InvenTree/report/templates/report/inventree_report_base.html)

Also the [weasyprint docs](https://doc.courtbouillon.org/weasyprint/v52.5/tips-tricks.html#include-header-and-footer-of-arbitrary-complexity-in-a-pdf) might help

**Comment by miggland** [comment]
You could consider using page-margins, which are not supported by most browsers but work in Weasyprint.

https://www.quackit.com/css/at-rules/what_is_a_page-margin_box_in_css.cfm
https://printcss.net/articles/page-margin-boxes

**Comment by mabroens** [comment]
Hi All,
still strugling to get the template correct.

here's an example of what the pdf looks like:
![image](https://github.com/inventree/InvenTree/assets/130482028/0518e049-736a-421d-bb42-3383e680a0f5)

as we can see on page 1 the fotter just goes over the invoice line
while on page 2 its lower but still not at the position where i had visioned it.

the text page x of y is always atethe same position though.

i'm using following settings:

{% block page_margin %}
	margin-left: 20mm;
	margin-right: 15mm;
	margin-top: 40mm;
	margin-bottom: 45mm;
{% endblock %}

.footer {
	background: red;
    
    color: #545454;
    font-size: 10px;
	
	bottom: 40mm;
	left: 0mm;
	position: fixed;
	width: 100%;
	margin-bottom: -30mm;
}
.footer img {
    width: 100%;
    max-width: 100%;
}
.footer div {
    line-height: 16px;
    padding: 10px 30px 30px;
}

{% block footer_content %}
    <div class="footer">
		<img src="{% asset 'footer.jpg' %}" >
        <div>
            Address VAT COC <br>
            Bank details
        </div>
    </div>
{% endblock %}


I have also tried placing my data in the {% block bottom_center %} but also that fails.

is there anyone willing to have a look at my template and fix it?
and i'm fine with the template beeing used as template later on.

Br Martijn

**Comment by mabroens** [comment]
Hi all, we finally managed to get the layout like we wanted.
thanks for the help.

**Comment by SchrodingersGat** [comment]
> Hi all, we finally managed to get the layout like we wanted.

Nice, glad to hear it! Are you able to provide some contribution to the reporting documentation that might help others who are facing the same issue?

**Comment by mabroens** [comment]
@SchrodingersGat yes i'd like to contribute here. and will also make my temlate availeble.
will do so in the comming weeks

Br Martijn
