### ISSUE TITLE
Theme improvements

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4897]
Bootstrap offers a built-in "dark mode" which is worth looking into:

https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode

Might simplify (and improve) the user interface between light mode and dark mode.

Also is it worth considering removing "custom themes"?

**Comment by matmair** [comment]
Not sure how much css/styles would need to be rewritten but cool feature.

> Also is it worth considering removing "custom themes"?

I am not sure about taking away functionality. Maybe we can push it into a really simple mix-in? When the plugin is enabled the provided file is loaded if not then not? Would remove all the selection logic.

I would be interested in @eeintech's take on this

**Comment by wolflu05** [comment]
I like the idea of shipping themes via plugins.

**Comment by SchrodingersGat** [comment]
> I like the idea of shipping themes via plugins.

Me too, this is a good idea

**Comment by eeintech** [comment]
The current "Dark Reader" mode CSS comes from the same name browser extension: https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh
In the past, I had chosen it over others as it did a really good job at converting bright websites into dark mode.
Bootstrap built-in dark mode would have definitely been simpler option but not available at the time...

Theme management via plugin is fine, but having core light/dark modes would still make the InvenTree setup much faster and lean for those who don't want to bring in plugins.

**Comment by SchrodingersGat** [comment]
I'm going to shelve this until the new bootstrap (5.3) is out - the current alpha dark mode support is pretty limited

**Comment by SchrodingersGat** [comment]
Closing this, we'll get this for "free" with the React/mantine updates.
