### ISSUE TITLE
Shipping items from sales order fails due to typo

### ISSUE THREAD

**Issue by jelgersma** [inventree/InvenTree#4906]
https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/js/translated/sales_order.js#L399

Should be completeSalesOrderShipment instead of completeSalseOrderShipment, now gives the error "cant find variable completeSalseOrderShipment"

I know creating a PR would be the way to go, but im on mobile atm.

**Comment by martonmiklos** [comment]
> I know creating a PR would be the way to go, but im on mobile atm.

Here you go: #4908
