### ISSUE TITLE
Reduce size of docker image

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4924]
InvenTree docker image is quite large, and could *probably* be reduced significantly in size.

But, requires someone to look at it closely...

**Comment by wolflu05** [comment]
Analyzed the image. Looks like we have lots of *unnecessary* dependencies for runtime which we could remove or use multi stage build to copy only the needed files.

![image](https://github.com/inventree/InvenTree/assets/76838159/1a6518ea-7491-468c-a72e-ffede30d8dd3)

Is there any reason why we don't use alpine images, they are a lot smaller?

**Comment by SchrodingersGat** [comment]
We were previously using alpine, but moved away from it to use the current base image. 

IIRC there were some dependencies in the alpine image which broke InvenTree for a while so we switched over. Also some articles I read at the time seemed to indicate that [alpine was not the best choice](https://pythonspeed.com/articles/alpine-docker-python/) - ref https://github.com/inventree/InvenTree/issues/3029

Regarding multi-stage builds - this looks like a good idea. Do you want to take a look at this?

**Comment by SchrodingersGat** [comment]
@wolflu05  did you want to take a crack at this one?

**Comment by wolflu05** [comment]
Sorry forgot to answer here. Yeah, I can try it, but don't expect any activity in the next weeks, won't have time for it. So if anybody else want to tackle this, go ahead.
