### ISSUE TITLE
Label Printing Plugin Updates

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4926]
Once https://github.com/inventree/InvenTree/pull/4805 is merged:

- Allow plugins to return `pdf` objects rather than offload to external printer
- Add "multipage" plugin plugin examples
- Background rendering for long-running pdf printing?

**Comment by matmair** [comment]
Still valid

**Comment by SchrodingersGat** [comment]
still valid

**Comment by SchrodingersGat** [comment]
The label printing plugins have been thusly updated
