### ISSUE TITLE
[FR] Using globally unique identifiers for most of objects.

### ISSUE THREAD

**Issue by roman-dvorak** [inventree/InvenTree#4931]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

The current solution is that each object in the InvenTree system has ID (primary key) in form of number, which is incremental. Due to, the ID (for example) `id=1` is used in many tables. It would be better if the ID were replaced with a globally unique code that would only appear once in the entire database and all other instances of the InvenTree installation.

This aims to solve situations where, for example, one item (label) comes in touch with a different InvenTree instance, which would then consider it as a different item. Due to the architecture of the tool and the use of Django models, there is not much danger of IDs (database links) being mistakenly swapped due to a programming error.

These U-IDs could then be displayed on all reports to make it easy to trace back to the original source. The disadvantage is that all QR/barcodes will be significantly larger in terms of data and complexity.

This approach of handling with codes also creates possibilities for semi-automatic transfer of items between instances (companies) that uses InvenTree.

### Suggested solution

In the first phase, I would propose adding the generation of unique objects to selected items through inventree mixins. Due to use of Django and PostgreSQL database, it seems useful to use UUIDs, as they are natively supported.

[wiki](https://en.wikipedia.org/wiki/Universally_unique_identifier)
[Django support](https://books.agiliq.com/projects/django-orm-cookbook/en/latest/uuid.html)
[Postgress support](https://www.postgresql.org/docs/current/datatype-uuid.html)

Then (after implementing 1st phase), it is should be considering using these identifiers as primary keys, which would mean replacing (minimally add support) all the links.

I cant quantify the impact on the system/database performance when using UUIDs as primary keys. I think this step can be decided after implementation of UUIDs as a second unique code in the database and are somehow used within the system - being referenced, printed on labels, ...

### Describe alternatives you've considered

 I don't have an alternative for that. It is very general solution. 

### Examples of other systems

A similar system is used in the [OpenIntranet](https://github.com/UniversalScientificTechnologies/OpenIntranet) storage system, where this approach seems to be very successful and efficient. This eliminates the possibility change/confusion of identifiers.

OpenIntranet uses the MongoDB NoSQL database, which natively supports [ObjectID](https://www.mongodb.com/docs/manual/reference/method/ObjectId/) identifiers. Subsequently, these ObjectID objects are used for all component/item/position identifications throughout the system.

### Do you want to develop this?
I'm not decided yet.

**Comment by SchrodingersGat** [comment]
@roman-dvorak this is reasonable, and thanks for your well-reasoned discussion here.

Currently we support two distinct types of barcodes to be associated with a database object:

- Simple "JSON" data such as `{"part": 3}` as you have seen
- Association with external barcode (i.e. assign an incoming barcode to a stock item as received from a supplier)

An additional barcode type (UUID) would need to be able to work alongside these existing types. This is fine, we have a plugin system for recognizing different barcodes and can just extend this.

**Comment by wolflu05** [comment]
#5208 is related

**Comment by SchrodingersGat** [comment]
not stale

**Comment by SchrodingersGat** [comment]
not stale
