### ISSUE TITLE
[BUG] Error in display of SVG when creating reports - Weasyprint will need to be upgraded

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#4936]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When creating a report with an SVG embedded in it via a link, there is a display error. It's our logo, and half of it is missing.

When I run Weasyprint 59.0 with the same source code on a different computer, the PDF looks like it should.

I believe this is caused by a bug in Weasyprint )https://github.com/Kozea/WeasyPrint/issues/1864), which has been fixed in version 59.0.

At the moment, we can not update the version of Weasyprint to 59.0 because of an incompatibility with `django-weasyprint`, as described here: 
https://github.com/fdemmer/django-weasyprint/issues/71

Until [this PR](https://github.com/fdemmer/django-weasyprint/pull/70) is merged in `django-weasyprint`, weasyprint can not be updated. For now, there is not InvenTree can do.

Workarounds:
- Do no use <use ..:> tags in SVG
- Convert SVG to another format, eg PNG

### Steps to Reproduce

1. Make SVG with `<use ...>` tags
2. Use SVG in report template, eg with:
```
@top-left {
                width : 100%;
                height : 17mm;
                background-image: url("Logo.svg");
}
```
3. Create a report in InvenTree
4. Look for parts of SVG with `<use ...> ` in the PDF vain

### Expected behaviour

Same as with 59.0

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

Current master has:
`weasyprint==54.3`

Bug remains with
`weasyprint==58.0`

**Comment by matmair** [comment]
Thanks for the report! We are pinned to 54.3 due to problems between django-weasyprint and newer weasyprint that popped up.

How much of an impact has this error? I personally do not use svgs that are affected but sounds like something pretty severe. Do you have any idea how widely used `use` is?
From a quick glance at django-weasyprint it seems like a monkey patch would be pretty simple/small.

**Comment by miggland** [comment]
In my limited understanding, `use` is probably applied more often than necessary by drawing programs.

The impact is big if the SVG is affected, but since there is a workaround, it can be handled. Since there seems to be a fix on the way for `django-weasyprint`, I would wait for that and then check if the other problems are solved.

The issues with merging PDF pages should be fixed in the newest Weasyprint. The "good reason to update" may be this issue with SVGs.

Relevant issues, for reference:
https://github.com/inventree/InvenTree/issues/3607
https://github.com/inventree/InvenTree/issues/3528

**Comment by miggland** [comment]
Still relevant, but the required PR is not merged yet (not much happening in `django-weasyprint`?

**Comment by miggland** [comment]
The relevant PR is now merged. Unclear when the updated version will be released.

**Comment by SchrodingersGat** [comment]
not stale
