### ISSUE TITLE
[FR] Include preact with static

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4937]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Currently, every plugin needs to include their own version of preact and htm.

### Suggested solution

Include https://esm.sh/htm/preact/standalone as a static file.

### Describe alternatives you've considered

Vanilla js works, preact feels more intuitive.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
@inventree/triage opinions? 👍 / 👎

**Comment by SchrodingersGat** [comment]
@matmair is preact a viable alternative to react for our purposes?

Also, if a plugin requires preact, can't it just load it from a CDN? It'll be cached anyway right?

**Comment by matmair** [comment]
@SchrodingersGat for inserting small interactive elements into the UI yes. It works very nicely with the current setup. See Lukas bulk plugin for example.

The problem I am running into is the following: the new inventree-kom2 plugin will include preact and htm; Lukas plugin also includes those files - this leads to potential overloading of the namespace (with panels for example). Making things unstable.

**Comment by matmair** [comment]
Closing in favour of #5011
