### ISSUE TITLE
[FR] Switch from pure git to dulwich

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4942]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

The calling of external processes via subprocess is creating problems with logs.

### Suggested solution

Switch to using https://github.com/jelmer/dulwich - a pure Python version

### Describe alternatives you've considered

There is also GitPython - which still requires git on the system.

### Examples of other systems

netbox uses this lib

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
Interesting project! Hopefully works to solve the logs issues
