### ISSUE TITLE
[FR] Feature flags

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#4965]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

We currently can not ship multiple versions of a feature / new versions of a UI as there is no selection features.

### Suggested solution

Add feature flags - possibly https://github.com/cfpb/django-flags/

### Describe alternatives you've considered

We could use settings, dedicated ff sound like a more stable solution

### Examples of other systems

GitHub uses ff a lot - https://github.blog/2021-04-27-ship-code-faster-safer-feature-flags/

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@matmair looks perfect. We'd need to manually add guards to various points in "new" code based on these feature flags, but there's probably no getting around that anyway.

Let's assume we go forward with this - and add a "Experimental Features" tab in the settings window.

Should we implement this first for our react branch?

**Comment by SchrodingersGat** [comment]
Additionally should we add a new `feature` issue label, which is "more important" than the `enhancement` one? I'm in favour of that, to discriminate between "flashy new never before seen feature" and "enhancement to an existing feature or workflow". Will also give more visibility in the release notes.

**Comment by matmair** [comment]
@SchrodingersGat I think there will not be too much need for backend flagging - mainly if behaviour for existing code/APIs changes.
My plan is to implement the feature flagging feature (including a settings page for it) and then merge that into react branch.

A new label costs nothing so why not.

**Comment by SchrodingersGat** [comment]
Sounds good to me :)
