### ISSUE TITLE
[FR] Batch label print of selected items from the BOM &/or Build Order page

### ISSUE THREAD

**Issue by damien-ls** [inventree/InvenTree#4970]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Once a build order is generated, typically for a SMT operation, materials needs to be taken from the stock and sent to the SMT factory.

The parts needs to be taken from the stock, packaged into a bag and the package needs to be labeled with the IPN, Stock Location, Quantity per unit, Quantity total, Description, QR Code 

The person picking from the stock can use the label to also find the part, put them in bags and put the label on it.

### Suggested solution

Add a "Print Labels for selected items" button on the Build Order -> Allocate Stock page to print a label for the selected items containing:
Internal Part ID, Stock Location, Quantity per unit, Reference, Quantity total, Description, QR Code

The printed labels can be then given to the person picking the parts from the stock, acting as a picking list by itself.

### Describe alternatives you've considered

Similar could be done on the BOM page, but the total quantity required and references would be missing.

### Examples of other systems

This is an important feature for using this system for manufacturing in general

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@damien-ls to clarify here - you are talking about the "allocated" items themselves, not the "created" outputs of the build order?

**Comment by damien-ls** [comment]
@SchrodingersGat correct, the output already have this functionality

**Comment by SchrodingersGat** [comment]
The current UI makes this complicated to select the individual stock items, as they are broken down by "part". I'll have a look into it but it might take a bit of a back seat as we have a number of other big projects on currently

**Comment by damien-ls** [comment]
@SchrodingersGat My understanding is that this button would be located there (still not fully familiar with inventree)

![1685959036360](https://github.com/inventree/InvenTree/assets/14539722/1c8e6a61-99ac-45e4-aa91-f7f0dd1f5072)

we are happy to contribute ($) for that as it is for us a critical need to use Inventree.

**Comment by SchrodingersGat** [comment]
> we are happy to contribute ($) for that as it is for us a critical need to use Inventree.

If you want to shoot me an email at `support@inventree.org` let's have a chat and see what we can work out :)

**Comment by SchrodingersGat** [comment]
@damien-ls this is dependent on https://github.com/inventree/InvenTree/pull/4855 which should be merged in soon :)

**Comment by damien-ls** [comment]
Hi Oliver,

You should have received the 500$ form Avalon.

Cheers
