### ISSUE TITLE
Restoring from backups/new install with old data

### ISSUE THREAD

**Issue by snorkrat** [inventree/InvenTree#4981]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I have had an issue where I need to restore data from an old Inventree instance to a new one.  (The VM I was hosting on was hacked, but I had off site daily backups of the docker persistent storage). I now have a completely new docker install on a new machine, with access to the old Inventree persistent storage/files.

The data I have available is the Inventree docker persistent storage volumes, namely the data and nginx folders with the complete subfolder structure, including the backup, media, pgdb, and static folders.

The backup folder includes a backup from yesterday, 5th June 2023 - I would ideally like to either restore this file, or use the data that already exists in the static, media and pgdb folders.

I also have the exact same compose and .env files that I was using.

### Steps to Reproduce

I thought it might be a simple case of placing the existing data and nginx folders in my new setup, and running the container but this gave DB errors such as:

```
ERROR:  relation "common_inventreesetting" does not exist at character 112
inventree-db        | 2023-06-06 20:32:53.153 BST [104] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
```
I then tried the same thing (placing the old data and nginx folders and contents in place), but ran `docker compose run inventree-server invoke update` first.  The webui loads, and I can log in, but after 30 seconds or so the webui is inaccessible and the docker logs show things like:

```
INFO Process-1:2 processing [item-sixteen-oklahoma-mississippi]
inventree-db        | 2023-06-06 20:38:15.163 BST [267] ERROR:  duplicate key value violates unique constraint "common_inventreesetting_key_key"
inventree-db        | 2023-06-06 20:38:15.163 BST [267] DETAIL:  Key (key)=(INVENTREE_DELETE_TASKS_DAYS) already exists.
inventree-db        | 2023-06-06 20:38:15.163 BST [267] STATEMENT:  INSERT INTO "common_inventreesetting" ("value", "key") VALUES ('30', 'INVENTREE_DELETE_TASKS_DAYS') RETURNING "common_inventreesetting"."id"
inventree-worker    | 19:38:15 [Q] INFO Process-1:3 processing [quebec-cup-triple-shade]
inventree-worker    | 19:38:15 [Q] INFO Process-1:4 processing [triple-potato-apart-nuts]
inventree-worker    | 19:38:15 [Q] INFO Process-1:1 processing [september-jig-north-sad]
inventree-worker    | 19:38:15 [Q] INFO Process-1:1 processing [happy-georgia-artist-tennis]
inventree-worker    | 19:38:15 [Q] INFO Process-1:1 processing [florida-zebra-carbon-california]
inventree-worker    | 19:38:15 [Q] INFO Processed [potato-friend-spaghetti-finch]
inventree-worker    | /root/.local/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1358: RuntimeWarning: DateTimeField PartPricing.updated received a naive datetime (2023-05-07 00:00:00) while time zone support is active.
inventree-worker    |   warnings.warn("DateTimeField %s.%s received a naive datetime "
inventree-worker    | 19:38:15 [Q] INFO Processed [robin-equal-sodium-berlin]

```

I tried setting up a new instance, which launches fine, moving a previous backup to the backup folder, and then restoring using `invoke restore`.  When using invoke restore I get the following:

```
Restoring InvenTree database...
Finding latest backup
Restoring backup for database 'default' and server 'None'
Restoring: default-020e32190ef7-2023-06-05-145606.psql.bin.gz
Restore tempfile created: 455.3 KiB
Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/root/.local/lib/python3.9/site-packages/dbbackup/management/commands/dbrestore.py", line 68, in handle
    self._restore_backup()
  File "/root/.local/lib/python3.9/site-packages/dbbackup/management/commands/dbrestore.py", line 118, in _restore_backup
    self.connector.restore_dump(input_file)
  File "/root/.local/lib/python3.9/site-packages/dbbackup/db/base.py", line 105, in restore_dump
    return self._restore_dump(dump)
  File "/root/.local/lib/python3.9/site-packages/dbbackup/db/postgresql.py", line 124, in _restore_dump
    stdout, stderr = self.run_command(cmd, stdin=dump, env=self.restore_env)
  File "/root/.local/lib/python3.9/site-packages/dbbackup/db/base.py", line 171, in run_command
    raise exceptions.CommandConnectorError(
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_restore --dbname=postgresql://**REDACTED USERNAME**:**REDACTED PASSWORD**@inventree-db:5432/inventree --single-transaction --clean 
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3623; 2606 16617 CONSTRAINT users_owner users_owner_pkey **REDACTED USERNAME**
pg_restore: error: could not execute query: ERROR:  cannot drop constraint users_owner_pkey on table public.users_owner because other objects depend on it
DETAIL:  constraint order_returnorder_responsible_id_19db2f48_fk_users_owner_id on table public.order_returnorder depends on index public.users_owner_pkey
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
Command was: ALTER TABLE ONLY public.users_owner DROP CONSTRAINT users_owner_pkey;
```
I feel like this could work if I could do what it says: `HINT:  Use DROP ... CASCADE to drop the dependent objects too.` but I'm unsure what to do.

Is there a way that I can restore my data, and if so would you be able to provide a step by step guide?  If you need me to provide more information regarding each of ways I tried to help debug the issue I can certainly do that.  I didn't want to keep trying things incase I was restoring the wrong way!

Thanks in advance for the help!

**Comment by snorkrat** [comment]
Yes the compromised account has gave me quite the headache!

I'm not exactly sure what I did differently following your steps, perhaps the `invoke migrate`, however it's all restored and working great now.  Thanks so much for the help!

PS: the `invoke check` was giving me this error:
```
Loading config file : /home/inventree/data/config.yaml
No idea what 'check' is!
```
but even without that it's all good.

Thanks again!

**Comment by snorkrat** [comment]
I should say one more thing for anybody else who comes across this:  inside the pgdb folder I had to manually create a bunch of folders as when starting the db I was getting complaints in the docker logs about missing folders.  I suspect this may only be the case when starting the db on it's own without the other containers.

The folders inside pgdb I had to manually create were:

- pg_commit_ts
- pg_logical/snapshots
- pg_logical/mappings
- pg_notify
- pg_replslot
- pg_snapshots
- pg_tblspc
- pg_twophase

**Comment by matmair** [comment]
Great! Reach out if something is not behaving well. You should be golden after 24hrs.
