### ISSUE TITLE
[FR] Install Stock Item Batch Install

### ISSUE THREAD

**Issue by damien-ls** [inventree/InvenTree#4986]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Some tracked stock items may requires hundreds of installed parts, in our case PCBs.

Currently it has to be done 1 by 1, making the functionality unusable if large amount of parts are installed. (In our case, it's hundreds)

### Suggested solution

User would scan the stock item serial  into which sub part are installed.

User then scan all the parts serial 1 by 1, without any required input (for instance 200 parts).

Scanned Parts are added in a list. It does not add duplicates.

When all parts are scanned, the user check the list, has the ability to edit the list like delete items, add items.

The user then confirm and the part are installed

### Describe alternatives you've considered

This might be an app implementation

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by damien-ls** [comment]
@SchrodingersGat That particular example was through a stock item page -> Install Stock Item.

To enable barcode functionality across the board, the primary thing to keep in mind is how to allow batch handling through scanning in general with minimum user input, and how to prevent user errors. 

The same concept can be applied to
- Attach parts to a location, you scan the location then scan 100 items and validate.
- Attach a location to another location, scan the parent location (a room) then scan 20 shelves and validate.
- Send spare parts to a client, enter the client / machine ID, scan 20 parts and validate.

etc...

**Comment by SchrodingersGat** [comment]
@damien-ls have a look at how we currently handle this in the web interface, to scan multiple stock items into a specific location. The approach you have laid out above in 1) is pretty much how we do this already.

**Comment by damien-ls** [comment]
@SchrodingersGat does it also exists for installing items ? (did not find how)

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat does it also exists for installing items ? (did not find how)

No, that feature does not exist yet.

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by SchrodingersGat** [comment]
not stale

**Comment by SchrodingersGat** [comment]
not stale
