### ISSUE TITLE
[FR] Merge new stock item if existing sublocation already has part.

### ISSUE THREAD

**Issue by pyrotech78** [inventree/InvenTree#4989]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I am currently using this to track items in our tech bag. 

The most useful feature is the "Stock Tracking Information" as it lets everyone know from the notes on when and where the part was used. 

When you add "New Stock Item" and add the same part again, whether the item is depleted or has items, it creates a duplicate of the part and doesn't add it to the existing part in your sublocation you chose. The problem is now the part will be duplicated and with its own tracking information. 

Merging the parts will delete the history of the item.

![Screenshot 2023-06-07 095407](https://github.com/inventree/InvenTree/assets/135863498/890668f5-348c-48ff-9318-714f415a6e82)

### Suggested solution

* Dont allow item to be added if  item has the same exact information. (from when creating new stock item)

### Describe alternatives you've considered

* If item already exist in sublocation, show a popup saying something like "Item already exist in sublocation, are you sure you would like to add it? ( will create a separate item)"  

*If item has the same exact information (from when creating new stock item) merge item with the existing one. Stock tracking info will say that is was manually added.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@pyrotech78 I see what you are going for here, I guess the question is how you determine what the "same exact information" means?

**Comment by pyrotech78** [comment]
Thank you for your reply,

It will be when you go an create a new stock item for that location. The information you input when adding that item.

Purchase Price
Status*
Supplier Part
Etc...


If all information matches an existing item to either merge or just not allow it and have to edit existing item.
