### ISSUE TITLE
Issue with partially complete BOs and cancelled BOs

### ISSUE THREAD

**Issue by SebBorbely** [inventree/InvenTree#4995]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When working with a Build Order the BO output is created when on output is completed but the BOM parts are only subtracted when the BO is competed. This can cause issues with un-allocating from partially complete BOs or when cancelling partially complete BOs.

### Steps to Reproduce

Create BO

![Capture12](https://github.com/inventree/InvenTree/assets/99136411/36ff2632-6c7e-4590-89b2-166badbc9986)
Allocate to this build order

![Capture13](https://github.com/inventree/InvenTree/assets/99136411/6d27d4eb-1014-48af-a0e7-62f24b42286b)
Create output to build order

![Capture3](https://github.com/inventree/InvenTree/assets/99136411/3576217d-7c7b-45a5-a151-a1833a5da619)
Complete output

![Capture4](https://github.com/inventree/InvenTree/assets/99136411/6d791724-c1ff-4976-b492-92cd0acc5e23)

At this point there is one of the output in stock and still two being built and the part 'Test1' shows 3 allocated and 1 in free stock.

![Capture8](https://github.com/inventree/InvenTree/assets/99136411/e40d0916-418f-4f6c-8cb3-215e53105403)
![Capture5](https://github.com/inventree/InvenTree/assets/99136411/ac7c8083-368d-4ec4-9f3b-d9a004752f85)

At this point I can unallocated part 'Test1' from the build with no issue. This frees up the 3 allocated parts so there are now 4 in stock while still showing that there is 1 completed output part which should have consumed those 3 parts. Like this I have now duplicated my stock as I have the completed assembly and the sub parts available still.

![Capture7](https://github.com/inventree/InvenTree/assets/99136411/d3511fc0-c35e-4c05-8f8c-f9b4cdc6386a)
![Capture6](https://github.com/inventree/InvenTree/assets/99136411/e1bc6213-c9fc-4292-ac6e-bb200a30becd)
![Capture9](https://github.com/inventree/InvenTree/assets/99136411/3cc4e52b-5eb4-4b70-8ac6-d1e94ea61f82)

Alternatively if I complete an output then cancel the BO I also end up with the same situation where I have the output and the parts still available to use.

### Expected behaviour

Unless there is a reason for it not to work like this, in my mind when an output is complete on a BO that would consume the parts there and then. Stock is consumed as the output assembly is added.  At this point the used stock cannot be un-allocated from the BO. Shown by maybe greying out the used allocated parts

![Capture14](https://github.com/inventree/InvenTree/assets/99136411/4747d298-b687-4842-b7c9-e3bdfe5caa00)

Or decreasing the allocated parts as shown 

![Capture15](https://github.com/inventree/InvenTree/assets/99136411/a8f3e0d4-e8e3-4464-8b06-7fe00b58eda4)

Not sure if either of these is a viable solution but I think there needs to be a way of preventing un-allocation and indicating this some way to the user. Leaving the visual allocation indicator as is but only allowing to un-allocate the unused parts might be confusing as without understanding why its not allowing it, they might think its a bug.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

Not sure if it counts as docker or what but I'm using the DigitalOcean one click install.

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18

Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@SebBorbely I understand the thought process here. Deciding when to mark stock as consumed is a difficult question. With the recent [changes to the build order process](https://github.com/inventree/InvenTree/pull/4855), we may have some more flexibility here in terms of marking stock as "consumed" part-way through the build.
