### ISSUE TITLE
2FA (QR code) when dark mode enabled

### ISSUE THREAD

**Issue by jelgersma** [inventree/InvenTree#4998]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

2FA QR code can't be scanned due to gray background when dark mode is enabled for the user.

### Steps to Reproduce

1. Login as user (U) and enable dark mode for your account
2. Login as admin (A) on another device or incognito
3. Enforce 2FA for users in Inventree (Settings > Login > Enforce MFA)
4. Watch U struggle to scan the QR code because the background is gray all the while A is laughing

### Expected behaviour

White background for QR code eventhough dark mode is enabled

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

Inventree version [0.11.2](https://github.com/inventree/InvenTree/releases)
Python Version | 3.9.16
Django Version | 3.2.18

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@jelgersma a screenshot would be handy here :)

**Comment by jelgersma** [comment]
![2023-06-08 13 56 24](https://github.com/inventree/InvenTree/assets/2895744/de4f164b-c413-44da-9e88-1999f47ca077)

User is using Android Pixel 7 Pro and can't scan the QR when the background is gray (note: on my iphone it just works). When changing the background color to white (through dev console) it works for his phone too. As a fallback I told the user to get a better phone :grimacing:

**Comment by SchrodingersGat** [comment]
@jelgersma fix incoming. You might not have to ship better phones to everyone!
