### ISSUE TITLE
Fix broken docker build

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#4999]
Docker build is borked, needs fixing before next release.

https://github.com/inventree/InvenTree/pull/4997#issuecomment-1582513974

```[tasklist]
### Tasks
- [x] Check previous versions
- [x] https://github.com/inventree/InvenTree/actions/runs/5210537105/jobs/9405692470
```

**Comment by matmair** [comment]
@SchrodingersGat I will watch the runs and restart them in the line of PRs

**Comment by matmair** [comment]
Actually looking at the things you linked: The runs did not fail, they were stopped due to concurrency rules

**Comment by matmair** [comment]
See:
* https://github.com/inventree/InvenTree/actions/runs/5210537105/jobs/9405692470
* https://github.com/inventree/InvenTree/actions/runs/5210674654/jobs/9402043420
* https://github.com/inventree/InvenTree/actions/runs/5210919131/jobs/9403505957

**Comment by matmair** [comment]
This seems to be a known issue https://github.com/orgs/community/discussions/8336
@SchrodingersGat should we shut off concurrency-checks for now? I can create a PR for it

**Comment by matmair** [comment]
@SchrodingersGat it seems like the failed docker builds were just cancelled runs - I have submitted a PR that would remove concurrency:
- pro: no failed runs because of cancellation
- con: unneeded builds (ie burning energy for nothing)
