### ISSUE TITLE
add shelve id

### ISSUE THREAD

**Issue by Philipboy881** [inventree/InvenTree#5013]
maby this is a nice function so you can put an id your shelve,
if you have multiple shelves in a storage room, you can find the item more easly

**Comment by LavissaWoW** [comment]
Seconding what @SchrodingersGat says.
I've got our stock configured hierarchically by Room->Shelf->Box. The structure of having Room be the "base", with "Shelf" locations under it, and "Box" locations under this again lets you keep somewhat unique names, even if every box is just called 1,2,3,4 etc. By structuring your locations like this, you will get breadcrumbs like "Room1/Shelf3/Box2".

A small workaround I'm personally doing is giving all box locations a description string that allows me to search for the whole name when assigning locations.

Say you have Room-001/Shelf-A4/Box-3
When looking up storage, you will not get any "Shelf-A4" as hits if you've marked it as structural. 
But if you include "Shelf-A4" in the location description, it will be searchable.
