### ISSUE TITLE
[FR/P-UI] New admin UI

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#5016]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

The current admin (global settings) UI is using HTML templates. This means you can not use all admin features headless and the UI needs to be fully rendered on the server side before being shown.

### Suggested solution

Switch to new UI #5011

### Describe alternatives you've considered

N/A

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
I will use this as a first PR to show the capabilities of the new UI.

**Comment by wolflu05** [comment]
Good idea to start this, but I am not sure if the admin ui would be a good thing for the start. I just think we should build something users daily would use. The admin ui is something that gets not used very often. Or was that your thinking so that we can experiment with something that's not used so much?

**Comment by matmair** [comment]
@wolflu05 there is nearly nothing in the daily UI that does not require fast rewrites of the modal and forms interfaces - which is 20+ files.
The admin UI is pretty much standalone so the idea is to get fast results that can be discussed. And add the missing admin APIs.

**Comment by SchrodingersGat** [comment]
@matmair do you mean the "django admin" page (which we use mostly out-of-the-box) or our "settings" page (which is user facing)?

**Comment by matmair** [comment]
@SchrodingersGat our settings page

**Comment by matmair** [comment]
Regarding this I ran into the first interesting question: do we define where settings go on the backend (ie making it pluggable and frontend version independent) or is that done in the frontend? Thoughts @inventree/triage?

**Comment by matmair** [comment]
I mean in terms of categories. Ie a category security with 3 settings, reporting with 20 settings etc. So a mapping where settings should be rendered. Because that is contingent on the server version.
The general URLs and layout will need to be done in react.

**Comment by SchrodingersGat** [comment]
Oh right, yeah I think the categories have to be specified by the server and then rendered out by the front-end

**Comment by matmair** [comment]
Closed by #5679
