### ISSUE TITLE
Improve Unit Test Time

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5024]
Current suite of unit tests takes an *excessive* amount of time (over an hour on some hardware).

We need to dedicate some time to working out where the inefficiencies are, and how we can trim this down significantly.

**Comment by wolflu05** [comment]
#5005 was a try on that, but it's not really working. Would need some further analysis.

**Comment by SchrodingersGat** [comment]
@wolflu05 it's a tough nut to crack

**Comment by LavissaWoW** [comment]
Migration tests definitely use up a lot of time, with around a minute per piece. As a starter, it's not a bad place to start.
I see you've done some initial work on this in your PR. Perhaps separate migration tests into its own container run that can run in parallell with the rest of testing? Can we potentially only trigger them under certain conditions?

It's probably not an easy feat, ofc. But several migration tests run on very specific migration states (from mig1 to mig2).
In that case, they really only need to run when the migrations in their app are updated?

**Comment by SchrodingersGat** [comment]
Closing this one out, recent changes to our CI suite have improved this a *lot*
