### ISSUE TITLE
units parameters

### ISSUE THREAD

**Issue by DS1705** [inventree/InvenTree#5033]
### Body of the issue

is there a way to print the units of the parameters in the labels. behind the value i want the unit to print but don't know how
`<p class="text">
        {% if parameters.voltage %}
            {{parameters.voltage}}
        {% endif %}
    </p>`

**Comment by SchrodingersGat** [comment]
@DS1705 sorry I thought there was an easy way to do this, turns out there was not. So, now after https://github.com/inventree/InvenTree/pull/5055 has been merged, you can actually do this:

https://docs.inventree.org/en/latest/report/labels/part_labels/#parameter-data
