### ISSUE TITLE
[FR] Block Build Orders until Tests are completed

### ISSUE THREAD

**Issue by MartinLoeper** [inventree/InvenTree#5037]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I would like to block a build order from being completed until all of its required tests are completed.

### Suggested solution

Check if any tests are missing before allowing build order to be marked completed and items being shipped to customer.

### Describe alternatives you've considered

We could make this an option in the settings: "Would you like tests to be mandatory for completing build orders?"

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Nice idea. I'd suggest that this applies to each individual *Build Output*, which has the associated tests, and not the *Build Order* itself.

This way, each build output can only be completed when the required tests have been performed.

And it could be (as you say) linked to a global setting

**Comment by SchrodingersGat** [comment]
Not stale, just need someone to implement

**Comment by SchrodingersGat** [comment]
not stale

**Comment by martonmiklos** [comment]
Hi there!

I have the willingness to implement it. Adding a global setting is clear, but let's do some discussion on the "all required tests passed" criteria.

We have test templates assigned to parts which could be set as required, the decision should be made based only on the required test template results right?

In the case if multiple test results assigned to a specific stock item' specific required test template then I would do the decision on the latest (in time) result's status.

**Comment by SchrodingersGat** [comment]
@MartinLoeper happy for you to look at this one - my only thought is that the build process may be very "bespoke" for certain companies processes. Maybe we want to consider exposing any such implementation to the plugin system - allowing the implementation to be "tweaked" for a given setup?

**Comment by martonmiklos** [comment]
> my only thought is that the build process may be very "bespoke" for certain companies processes

I think if the required flag is set on a specific test it would be straightforward to  interpret it as a "test is required to pass" for build output completion criteria. But if you would mind writing an use case where this is not the case then it would help me to understand it better. 

Retesting wise I am aware of some cases where it is forbidden or different process follows (see.: HiPot section here https://github.com/inventree/InvenTree/issues/2817#issuecomment-1100833023), but I think that it is going to be covered if we implement the Build workflows.

**Comment by SchrodingersGat** [comment]
What we could do, very simply, is enforce "required tests" to be passing before a particular build output can be marked as "complete". This will in turn prevent the build from being completed (as it cannot be completed with incomplete build outputs).

**Comment by martonmiklos** [comment]
Not stale
