### ISSUE TITLE
[FR] Allow "recovery" of consumed stock items from a build

### ISSUE THREAD

**Issue by mattbnz** [inventree/InvenTree#5068]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Following the recent stock tracking changes stock item records for untracked stock consumed by build orders are retained in the database but marked as unavailable by setting the consumed_by_id field to the build order that they were used in - and associated stocktracking entries are created with additional metadata as well. This is great.

Let's say however that a built item is returned/scrapped/reworked and as a result some of the components that were used to build it are "recovered" from the item and returned to stock able to be re-used in a future build.

Currently I cannot find any supported method to record this in the database without resorting to manual SQL queries.

It's desirable to be able to "recover" the original stock items to stock, rather than simply creating new items for the recovered parts to enable traceability of the parts across their previous uses and back to the purchase order. 

### Suggested solution

Add an API/UI functionality to "recover" a stock item that is currently marked as consumed back into stock - this is conceptually a parallel to the "uninstall" action that is possible with tracked/installable items, but would work on untracked stock items instead. 

Achieving it requires just two things to happen afaict:
1) Add a stocktracking entry (with a new tracking_type code) to record the recovery of the parts
2) NULL out the consumed_by_id field on the stock entry itself. 

A further extension would be to allow the "split" functionality to also occur on the stockitem to handle the case where the build order consumed more stock than is being recovered (e.g. stock for 3 units was built/consumed, but only parts from 1 unit are being recovered). 

### Describe alternatives you've considered

The main issue I see with the proposal is that while we retain history of the use in the build in the stocktracking table - I think the parts won't show up in the "consumed items" view of the build itself anymore as that references via the consumed_by field, not the stocktracking table... In a way that's correct, because the items are not consumed by the build any more, but it does mean that there is no way from the build to see all the stockitems that were originally used, which some may find desirable? To do that however, would require making the build look up the stocktracking table, and/or some further duplicatino of stockitem records which seems more complicated.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@mattbnz nice idea - you might want to read through the latest comments in https://github.com/inventree/InvenTree/issues/2624 also
