### ISSUE TITLE
[setup] custom https port via nginx does not work on baremetal inventree

### ISSUE THREAD

**Issue by T0jan** [inventree/InvenTree#5080]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

hi once more,

as recommended by the documentation of gunicorn and also InvenTree itself I am currently working on putting my server behind an nginx instance. This worked for `http` access but as soon as I want to use `https` the connection goes into an weird read-only state. if you have a session running it is still possible to see all elements visible for this user but every time you try to change something a notification about insufficient user rights appears. if you try to log-out or log-in you get:
 ```
Authentication Failure
You have been logged out from InvenTree.
```

I am a beginner with nginx so I am aware that this could be an configuration issue however it feels weird for me that http works completely and https has this weird behavior. 

I based my nginx config on the one from the docker example and with some modifications to my local ports and circumstances it worked at least for http. However I have a slight weird port configuration as my server is currently only accessible via port 8000 so I set the port inventree is listening on to 8080 and nginx to 8000.

### Steps to Reproduce

1. have an barematel install mirroring the one from the inventree documentation
2. configure nginx with the docker template, (un-)comment the https specific lines ([nginx.conf.zip](https://github.com/inventree/InvenTree/files/11801846/nginx.conf.zip))
3. set nginx listening port to 8000 and inventree/gunicorn to 8080 (or any other available port)
4. start inventree and nginx
5. try accessing the server

### Expected behaviour

The server should be accessible via nginx https the same way it is via nginx http.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0 dev
Django Version: 3.2.18

Database: postgresql
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
have you verified it doe not work with port 443?

**Comment by T0jan** [comment]
@matmair I just tested it and with port 443 it works, even with no other port open for http. After a bit of research I discovered that apparently nginx supports ssl only over 443 so if you need multiple https ports on the same server you need to get a bit creative. 

So mostly an nginx problem the only suggestion I would have here is to add a note somewhere that points to this nginx behavior to help other starters to avoid this pitfall

**Comment by matmair** [comment]
I mean you can route to another port but it is a bit more work than changing out the target port and involves advanced config concepts.

We can mention it but the question is where. I would like to keep the main docs simple as it is very long as it is.

**Comment by T0jan** [comment]
@matmair I wouldn't add it to the main docs either. I think a small comment in the nginx config examples should be enough as this anyway would be the starting point for most working with it.

**Comment by matmair** [comment]
@T0jan agree
Do you have a useful link that you would suggest for further info?

**Comment by T0jan** [comment]
@matmair there is sadly no clear description (or at least I didn't found some) that states that only port 443 works. most just say one should use a reverse proxy in nginx if a different port is used but don't explain in detail why. maybe just point to the official documentation for at least examples? https://docs.nginx.com/nginx/admin-guide/security-controls/terminating-ssl-http/

**Comment by SchrodingersGat** [comment]
@T0jan I'm playing catch up here - are you suggesting that *our* documentation needs an update?

**Comment by SchrodingersGat** [comment]
Ok, happy to close this out then?

**Comment by T0jan** [comment]
I mean there was no comment added yet or did I missed that?

**Comment by SchrodingersGat** [comment]
Sorry, didn't link the PR - https://github.com/inventree/InvenTree/pull/5243 - LMK If you are happy with this

**Comment by T0jan** [comment]
looks good to me 👍
