### ISSUE TITLE
Issue loading plugins from external directory

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5081]
When loading a plugin from the "plugins" directory (either "internal" or "external"), it can take upwards of 60 seconds to actually load the plugin. This can cause the worker to timeout (and thus not actually start the server at all).

Ref: https://github.com/inventree/InvenTree/discussions/5066

I have narrowed down the problem to the `get_git_log` function:

https://github.com/inventree/InvenTree/blob/66ec82d4d123fc75cb55b62a89a5829b0d637604/InvenTree/plugin/helpers.py#LL112C1-L112C1

When loading from an external directory, this code spends an *eternity* walking directories:

![image](https://github.com/inventree/InvenTree/assets/10080325/8074c808-e200-4e01-b2ec-f7cc087b83d9)

Either this needs to be optimized, or removed.

**Comment by matmair** [comment]
It is indeed the walker settings, I am going to test out how much we can strip down the walk to still have the required depth of discovery.

**Comment by SchrodingersGat** [comment]
@matmair FYI this seems to be a performance hit even loading from local code. removing this function reduces plugin time almost down to zero

**Comment by SchrodingersGat** [comment]
@matmair have you had a chance to look into this yet? This is currently the only issue remaining for our 0.12.0 release :)

**Comment by matmair** [comment]
I think I have a solution but it seems a bit complex for the problem
