### ISSUE TITLE
Low stock page shows template part regardless of variation stock levels

### ISSUE THREAD

**Issue by 1337joe** [inventree/InvenTree#5096]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The "Low Stock" page lists template items that have a minimum stock value set even when the variants of that template meet the requested stock levels.

### Use Case:
I have an item with multiple variants representing different revisions of an item. Only the newest revision will be produced but older revisions are still kept for filling orders and I want to track what revision was used to fill orders in case problems crop up.

I want to make sure I always have 5 in stock across all revisions. This is tracked well by the template but setting a minimum stock on the template makes that part always show up on the "Low Stock" page.

### Steps to Reproduce

1. Create a template part "Temp" and set the minimum stock to 5.
2. Create a variant part "Var" based on the above template and don't set a minimum stock.
3. Add 10 units of stock to "Var".
4. The "Low Stock" page will now list "Temp" but will list its stock as 10, which is above the minimum stock value.

### Expected behaviour

If I set a `Minimum Stock` value on a template part and that part has variants that are in stock (individually or collectively) I expect the template part to track as being in stock.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.3
Django Version: 3.2.18
Commit Hash: 1c4362c
Commit Date: 2023-06-05
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@1337joe thanks for bringing this up - fix in #5102
