### ISSUE TITLE
Plugin URL not accessible when logged out

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#5112]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I've got a situation here where I need to get a token without using the Inventree's standard URL.

KiCad will eventually define one root URL which points to a plugin which provides endpoints for data exchange. Those are fixed and can't change.

In my plugin I tried to duplicate the /api/user/token/ url but when accessing it, it redirects me to the proper one which kinda makes sense but I can't have that in this case unfortunately. Is there a way to set a decorator of some sort to make that URL accessible without redirection?

All I need is a second URL which I can call to authenticate.

### Steps to Reproduce

none

### Expected behaviour

get a token

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0 dev
Django Version: 3.2.19
Commit Hash: 951eb04
Commit Date: 2023-06-28
Commit Branch: run-locally
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Platform: Windows-10-10.0.22621-SP0
Installer: GIT

Active plugins: [{'name': 'KiCadLibraryPlugin', 'slug': 'kicad', 'version': '0.0.1'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
This is not available as standard, and introducing such changes would be potentially problematic as it is linked with the auth system.

@afkiwers I'll discuss this one with you in person :)

**Comment by matmair** [comment]
Is this still required or did you clear this in person @SchrodingersGat?

**Comment by afkiwers** [comment]
It could still need such an option to provide an automatic authentication mechanism for my KiCad rest api proposal but at the moment it looks like they want to be provided with a token only rather than getting on created automatically through basic auth.

**Comment by SchrodingersGat** [comment]
@afkiwers are you happy to close this out?

**Comment by afkiwers** [comment]
Yep
