### ISSUE TITLE
[FR] "Expand All" option in Bill of Materials view

### ISSUE THREAD

**Issue by omerk** [inventree/InvenTree#5116]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

In top-level assemblies with many parts that might have their own child BOMs, expanding the tree requires a lot of manual clicking. What's worse, and I suspect this might be a bug, is that expanding a single line item just collapses the entire tree.

Here's an example:

![inventree-expand-bom](https://github.com/inventree/InvenTree/assets/9847/95f924aa-e45c-4962-a760-4c05baa756eb)

I believe this was actually implemented for some table views (#3068) but missing for the BOM view?

### Suggested solution

Adding an "Expand All" button that recursively expands the entire BOM would save users a lot of clicks.

### Describe alternatives you've considered

Unless I am mistaken, there is currently no alternative to manually expanding all items?

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Expanding all levels of BOM Items could introduce significant lag into the system - which is why currently BOMs are loaded a single level at a time. However a button which has to be clicked by the user to do this might not be too bad.

> What's worse, and I suspect this might be a bug, is that expanding a single line item just collapses the entire tree.

Agreed this is a bug / unintended behaviour.

Would you be willing to submit a PR to address this?

**Comment by omerk** [comment]
Just commenting to keep this issue open.

I'm afraid I won't be able to send a PR as I currently do not have the time to familiarise myself with Django/Python web apps. Will revisit when I have a bit more time and if this issue is still open.

**Comment by SchrodingersGat** [comment]
Not stale, but I think we should focus on bringing this to the new react interface
