### ISSUE TITLE
How to import new parts ?

### ISSUE THREAD

**Issue by rohitsingal1** [inventree/InvenTree#5126]
I have 900+ parts to import which are variants of differnt parent parts. I aready have the data in an excel format. I created 2-3 parts to generate an export template for the "parts" under admin section.
When I use the admin panel --> Part --> Parts and select Import and supply the file in the required format I get the error "SupplierPart matching query does not exist". Company.models.SupplierPart.DoesNotExist.

How do I add parts using import (excel, csv etc) ? I cannot add them manually one by one as there are 900 parts.

**Comment by SchrodingersGat** [comment]
> "SupplierPart matching query does not exist". Company.models.SupplierPart.DoesNotExist.

This most likely means you have specified a value for the "default supplier" field when importing parts - you cannot import a record which references a row in a separate table, which itself does not already exist.

If you clean up your dataset, you should be able to import via the admin importer.

Another alternative is to use the [python api](https://github.com/inventree/inventree-python) but this requires some custom scripting.

**Comment by rohitsingal1** [comment]
Still receiving the same error. 
I am sharing my CSV file content below.
I have uploaded the file directly and I have uploaded after deleting the "Default Supplier ID" but the error remains the same.
I am using the admin importer to import the data. None of the parts mentioned here exist and are being imported for the first time.
Find the error below.

> 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\admin\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\admin\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Part ID | Part Name | Part Description | IPN | Revision | Keywords | Link | Units | Notes | Category ID | Category Name | Default Location ID | Default Supplier ID | Variant Of | Minimum Stock | Active | Assembly | Component | Purchaseable | Salable | Template | Trackable | Virtual | Suppliers | In Stock | On Order | Used In | Allocated | Building | Minimum Cost | Maximum Cost | default_expiry | creation_date | creation_user | responsible | last_stocktake | base_cost | multiple
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
55 | CM1017_1051_Red_$P |   |   |   |   |   | Pieces |   | 1 | Salwars | 4 |   |   | 0 | 1 | 0 | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |   |   | 0 | 01/07/2023 | 1 |   |   | 0 | 1
56 | CM1017_1051_Red-30 |   |   |   |   |   | Pieces |   | 1 | Salwars | 4 | 3 | 55 | 0 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |   |   | 0 | 01/07/2023 | 1 |   |   | 0 | 1
57 | CM1017_1051_Green_$P |   |   |   |   |   | Pieces |   | 1 | Salwars | 4 |   |   | 0 | 1 | 0 | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |   |   | 0 | 01/07/2023 | 1 |   |   | 0 | 1
58 | CM1017_1051_Green-26 |   |   |   |   |   | Pieces |   | 1 | Salwars | 4 | 3 | 57 | 0 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |   |   | 0 | 01/07/2023 | 1 |   |   | 0 | 1
59 | CM1017_1051_Green-28 |   |   |   |   |   | Pieces |   | 1 | Salwars | 4 | 3 | 57 | 0 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |   |   | 0 | 01/07/2023 | 1 |   |   | 0 | 1
60 | CM1017_1051_Green-30 |   |   |   |   |   | Pieces |   | 1 | Salwars | 4 | 3 | 57 | 0 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |   |   | 0 | 01/07/2023 | 1 |   |   | 0 | 1
61 | CM1017_1051_Green-32 |   |   |   |   |   | Pieces |   | 1 | Salwars | 4 | 3 | 57 | 0 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |   |   | 0 | 01/07/2023 | 1 |   |   | 0 | 1
62 | CM1017_1051_Green-34 |   |   |   |   |   | Pieces |   | 1 | Salwars | 4 | 3 | 57 | 0 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |   |   | 0 | 01/07/2023 | 1 |   |   | 0 | 1
63 | CM1017_1051_Green-36 |   |   |   |   |   | Pieces |   | 1 | Salwars | 4 | 3 | 57 | 0 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |   |   | 0 | 01/07/2023 | 1 |   |   | 0 | 1



</body>

</html>

> Errors
> 
>     Line number: 2 - Part matching query does not exist.
>     56, CM1017_1051_Red-30, , , , , , Pieces, , 1, Salwars, 4, , 55, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, , , 0, 01/07/2023, 1, , , 0, 1
> 
>     Traceback (most recent call last):
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 658, in import_row
>     self.import_obj(instance, row, dry_run)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 512, in import_obj
>     self.import_field(field, obj, data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 495, in import_field
>     field.save(obj, data, is_m2m)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/fields.py", line 110, in save
>     cleaned = self.clean(data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/fields.py", line 66, in clean
>     value = self.widget.clean(value, row=data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/widgets.py", line 396, in clean
>     return self.get_queryset(value, row, *args, **kwargs).get(**{self.field: val})
>     File "/opt/inventree/env/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
>     raise self.model.DoesNotExist(
>     part.models.Part.DoesNotExist: Part matching query does not exist.
>     Line number: 4 - Part matching query does not exist.
>     58, CM1017_1051_Green-26, , , , , , Pieces, , 1, Salwars, 4, , 57, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, , , 0, 01/07/2023, 1, , , 0, 1
> 
>     Traceback (most recent call last):
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 658, in import_row
>     self.import_obj(instance, row, dry_run)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 512, in import_obj
>     self.import_field(field, obj, data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 495, in import_field
>     field.save(obj, data, is_m2m)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/fields.py", line 110, in save
>     cleaned = self.clean(data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/fields.py", line 66, in clean
>     value = self.widget.clean(value, row=data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/widgets.py", line 396, in clean
>     return self.get_queryset(value, row, *args, **kwargs).get(**{self.field: val})
>     File "/opt/inventree/env/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
>     raise self.model.DoesNotExist(
>     part.models.Part.DoesNotExist: Part matching query does not exist.
>     Line number: 5 - Part matching query does not exist.
>     59, CM1017_1051_Green-28, , , , , , Pieces, , 1, Salwars, 4, , 57, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, , , 0, 01/07/2023, 1, , , 0, 1
> 
>     Traceback (most recent call last):
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 658, in import_row
>     self.import_obj(instance, row, dry_run)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 512, in import_obj
>     self.import_field(field, obj, data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 495, in import_field
>     field.save(obj, data, is_m2m)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/fields.py", line 110, in save
>     cleaned = self.clean(data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/fields.py", line 66, in clean
>     value = self.widget.clean(value, row=data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/widgets.py", line 396, in clean
>     return self.get_queryset(value, row, *args, **kwargs).get(**{self.field: val})
>     File "/opt/inventree/env/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
>     raise self.model.DoesNotExist(
>     part.models.Part.DoesNotExist: Part matching query does not exist

**Comment by SchrodingersGat** [comment]
You have to delete the values in the "Part ID" field. If a value is provided, it tries to find the matching part and *update* the existing record. Delete the value, and it will *create* a new record instead.

**Comment by rohitsingal1** [comment]
Then how will I define the "Variant of" field without a part ID ?

**Comment by rohitsingal1** [comment]
Still the same error

> Errors
> 
>     Line number: 2 - SupplierPart matching query does not exist.
>     , CM1017_1051_Red-30, , , , , , Pieces, , 1, Salwars, 4, 3, , 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, , , 0, 01/07/2023, 1, , , 0, 1
> 
>     Traceback (most recent call last):
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 658, in import_row
>     self.import_obj(instance, row, dry_run)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 512, in import_obj
>     self.import_field(field, obj, data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 495, in import_field
>     field.save(obj, data, is_m2m)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/fields.py", line 110, in save
>     cleaned = self.clean(data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/fields.py", line 66, in clean
>     value = self.widget.clean(value, row=data)
>     File "/opt/inventree/env/lib/python3.10/site-packages/import_export/widgets.py", line 396, in clean
>     return self.get_queryset(value, row, *args, **kwargs).get(**{self.field: val})
>     File "/opt/inventree/env/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
>     raise self.model.DoesNotExist(
>     company.models.SupplierPart.DoesNotExist: SupplierPart matching query does not exist.

**Comment by rohitsingal1** [comment]
> Either:
> 
>     1. Import template parts first, then variant parts second
> 
>     2. Remove "variant of" data, import parts, then _update_ parts with variant_of data once records are imported
> 
> 
> Records must be imported as a single atomic operation - they _cannot_ reference each other before they exist in the database.

Thanks this sorted out lot of things. Let me generate all the template parts first and then using the template part ID will create the Parts as variants. Just now successfully imported the parent template.

**Comment by matmair** [comment]
@rohitsingal1 were you successful?

**Comment by SchrodingersGat** [comment]
Closing this one out, @rohitsingal1 comment again if you did not get it sorted out
