### ISSUE TITLE
Can't login after installing

### ISSUE THREAD

**Issue by solarmax1** [inventree/InvenTree#5128]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I installed InvenTree using the Quick Script and I'm unable to log in.  

I'm running Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-73-generic x86_64) and installed InvenTree 0.12.0 using the Quick Script installer.  It completed without an error.  From a different machine, I can see the web-based Sign In screen, but it does not like any username/password combination that I have tried.

Initially the admin_user, admin_email, and admin_password entries in the /etc/inventree/config.yaml file were empty, so edited the file and filled out these fields.  I shut the machine down and rebooted, However, it made no difference.  

I looked through the documentation and I cannot find if there is supposed to be a default username and password.  

There was no /etc/inventree/admin_password file, so I created one and entered a password in it.  This password does not seem to work either.

I've tried multiple things to try to get this to work over the past few weeks, but I'm out of ideas.  Is there any guidance you can provide on how to get in?

### Steps to Reproduce

1. Install Ubuntu 20.04.6 LTS
2. login to Linux using SSH
3. Install InvenTree using Quick Script
4. Reboot the machine
5.  Try to sign in from a different machine with the URL http://inventree/accounts/login/
6. Try different combinations of Usernames and Passwords

**Comment by matmair** [comment]
There are no default logins. Creating an admin_password file will do nothing - that is something that is generated by InvenTree, not consumed.

You can add a superuser dynamically with `inventree run cli superuser`.

**Comment by KC0D** [comment]
Thanks for the response.  This is the response I got:
pi@Inventree:/inventree$ sudo inventree run cli superuser
/opt/inventree/vendor/pkgr/processes/cli: 2: exec: .: Permission denied

**Comment by matmair** [comment]
@KC0D have you tried running the command without sudo?

**Comment by KC0D** [comment]
Yes I did.  I ran with sudo because when I try it without sudp, I get this message:

pi@Inventree:~$ inventree run cli superuser
Error: You must be executing as the user 'inventree' or with root privileges to launch commands.
Either log in as 'inventree', root, use sudo, or add sudo privileges for running inventree with your current user.

I also tried logging in as super user and ran the command and got the "Permission denied" message just like I did with sudo.

**Comment by matmair** [comment]
@KC0D seems like there is a problem with Ubuntu - I am working on an upstream patch. You can patch it now with this command:
```
sudo cat <<EOT > /opt/inventree/vendor/pkgr/processes/cli
#!/bin/sh
. env/bin/activate &&  exec env/bin/python -m invoke $@
EOT
```

then repeat `inventree run cli superuser`

**Comment by KC0D** [comment]
Hi Matthias,

I made the modification as you described, then ran "inventree run cli superuser".  It still wants this to run under sudo.  I did that, and this time it made it further:

pi@Inventree:/opt/inventree$ sudo inventree run cli superuser
[sudo] password for pi:

InvenTree - inventree.org
The Open-Source Inventory Management System

Installation paths:
Base        /opt/inventree
Config      /etc/inventree/config.yaml
Media       /opt/inventree/data/media
Static      /opt/inventree/data/static

Versions:
Python      3.8.10
Django      3.2.19
InvenTree   0.12.0
API         127

Commit hash:None
Commit date:None

You are probably running the package installer / single-line installer. Please mentioned that in any bug reports!

Use '--list' for a list of available commands
Use '--help' for help on a specific command

I'm not sure this worked.  I was expecting a prompt  for a username/password, or some info that said that superuser was created and what the superuser name/password is.

**Comment by matmair** [comment]
@KC0D are you sure you ran the whole command? This looks like the output for `inventree run cli`

**Comment by KC0D** [comment]
Sorry, that is what I sent by accident.  I tried several things and copied the wrong one.  The results are the same though:

pi@Inventree:~$ sudo inventree run cli superuser

InvenTree - inventree.org
The Open-Source Inventory Management System


Installation paths:
Base        /opt/inventree
Config      /etc/inventree/config.yaml
Media       /opt/inventree/data/media
Static      /opt/inventree/data/static

Versions:
Python      3.8.10
Django      3.2.19
InvenTree   0.12.0
API         127

Commit hash:None
Commit date:None

You are probably running the package installer / single-line installer. Please mentioned that in any bug reports!

Use '--list' for a list of available commands
Use '--help' for help on a specific command
