### ISSUE TITLE
Missing InvenTree/InvenTree/static/admin

### ISSUE THREAD

**Issue by morio** [inventree/InvenTree#5130]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Missing css and javascript for admin page in the GitHub repository.
I copied InvenTree/InvenTree/static to /var/www using nginx as a reverse proxy and hosting the static and media files.
The main page looks fine, the issue is when I go to the admin page, it is all non-formatted html. I checked the repo and it is missing the static/admin directory. 
As the image show all the static/admin files are missing
![image](https://github.com/inventree/InvenTree/assets/352201/2fa35cdb-192d-4f9c-a36d-4a2c619eddd4)

I checked with the inventree demo site and those files exist 
Proof of the javascript file
![image](https://github.com/inventree/InvenTree/assets/352201/878346b5-2f42-4124-a341-d9268df15103)
Proof of the css files
![image](https://github.com/inventree/InvenTree/assets/352201/cfe5bfa0-1e3c-47d3-9dd4-c0936d50bd6e)

And I doubled checked the GitHub repository and the whole admin directory is missing
![image](https://github.com/inventree/InvenTree/assets/352201/25aae587-b8e2-4658-a694-2ee90e10deb1)

I also did a find for the missing css files and they didn't show up in any directory in the git project.

I guess for now I could copy the files from the demo site, but it would be nice if they were included in the repository.

### Steps to Reproduce

clone 0.12.0 into src 
bash# find ./src | grep base.css

no results are returned

**Comment by SchrodingersGat** [comment]
Did you run `invoke static` before copying the requried files? Some of those are generated only when running the command.

**Comment by morio** [comment]
Thanks!
I didn't see it in the instructions for bare metal production docs
https://docs.inventree.org/en/latest/start/bare_prod/
