### ISSUE TITLE
Internal Server Error when opening any Sales/Build or Purchase order

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#5131]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi Team,

after updating my ubuntu machin  am now at rev 0.12.0. great job addinthe adres field option thank you so much.
but unfortunatly i am now running into an isseu when i try to Build order / Sales Ordr or Purchase orders. 
i can see all my orders but when clicking an order i get an error screen.
![image](https://github.com/inventree/InvenTree/assets/130482028/7f8f9741-4f61-4e57-88ed-458113aaf50c)

log file attached below

### Steps to Reproduce

1. Goto sales order
2. click on nay sales order 
3. i get the error
4. 

### Expected behaviour

not this

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0
Django Version: 3.2.19
Commit Hash: 1d18b487
Commit Date: None
Commit Branch: master
stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.29
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Change Error
Error object (138)
[HISTORY](http://172.17.40.21/admin/error_report/error/138/history/)

Type:
AttributeError
Path:
http://172.17.40.21/order/sales-order/10/
Info:
'str' object has no attribute 'removesuffix'
When:
July 2, 2023, 6:34 p.m.
Data:
Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
response = response.render()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
self.content = self.rendered_content

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
return template.render(context, self._request)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 170, in render
return self._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/library.py", line 192, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in status_label
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/tags.py", line 14, in <dictcomp>
state = {cls.tag(): cls for cls in inheritors(StatusCode)}.get(typ, None)

File "/opt/inventree/InvenTree/generic/states/states.py", line 108, in tag
ref_name = cls.__name__.removesuffix('Status')

AttributeError: 'str' object has no attribute 'removesuffix'
```

**Comment by wolflu05** [comment]
Hello @mabroens ,

the `str.removesuffix` function is only available in python 3.9+ which is also the min version you need to run InvenTree. From your log I can see you run python 3.8, so you need to update your python version to fix that issue.

**Comment by mabroens** [comment]
Hello @wolflu05 ,

thanks for the hint.
I have installed pyhthon 3.9 and alsa ran as python was still set for 3.8 
`sudo apt install python-is-python3`
then restarted my ubuntu.
but now it seems like nothing is working, i now get **`502 Bad Gateway`**

will try more tomorrow but if you have any hints please.

**Comment by SchrodingersGat** [comment]
@mabroens you'll want to look at the server logs to determine what is going on. No doubt updating your python version means that all your library references are broken

**Comment by mabroens** [comment]
@SchrodingersGat ,
thank you for the feedback, but sorry to ask where can i find 'the server logs' you are refering to? do you mean logfiles from ubuntuu or from inventree?

```
~/inventree$ ls -al
total 348
drwxr-xr-x 13 root     root       4096 apr  7 09:08 .
drwxr-xr-x 23 spectrum spectrum   4096 jul  3 10:49 ..
drwxr-xr-x  2 root     root       4096 apr  7 09:08 ci
drwxr-xr-x  4 root     root       4096 apr  7 09:08 contrib
-rw-r--r--  1 root     root       8071 apr  7 09:08 CONTRIBUTING.md
-rw-r--r--  1 root     root        257 apr  7 09:08 crowdin.yml
drwxr-xr-x  2 root     root       4096 apr  7 09:08 deploy
drwxr-xr-x  2 root     root       4096 apr  7 09:08 .devcontainer
drwxr-xr-x  2 root     root       4096 apr  7 09:08 .devops
drwxr-xr-x  3 root     root       4096 apr  7 09:08 docker
-rw-r--r--  1 root     root       2472 apr  7 09:08 docker-compose.yml
-rw-r--r--  1 root     root        553 apr  7 09:08 docker.dev.env
-rw-r--r--  1 root     root       4664 apr  7 09:08 Dockerfile
-rw-r--r--  1 root     root        404 apr  7 09:08 .eslintrc.yml
drwxr-xr-x  8 root     root       4096 apr  7 09:08 .git
-rw-r--r--  1 root     root        118 apr  7 09:08 .gitattributes
drwxr-xr-x  5 root     root       4096 apr  7 09:08 .github
-rw-r--r--  1 root     root       1397 apr  7 09:08 .gitignore
-rw-r--r--  1 root     root       1354 apr  7 09:08 .gitpod.yml
drwxr-xr-x  3 root     root       4096 apr  7 09:08 images
drwxr-xr-x 17 root     root       4096 apr  7 09:08 InvenTree
-rw-r--r--  1 root     root       1071 apr  7 09:08 LICENSE
-rw-r--r--  1 root     root        119 apr  7 09:08 package.json
-rw-r--r--  1 root     root     149310 apr  7 09:08 package-lock.json
-rw-r--r--  1 root     root        916 apr  7 09:08 .pkgr.yml
-rw-r--r--  1 root     root       1205 apr  7 09:08 .pre-commit-config.yaml
-rw-r--r--  1 root     root        194 apr  7 09:08 Procfile
-rw-r--r--  1 root     root       7726 apr  7 09:08 README.md
-rw-r--r--  1 root     root        746 apr  7 09:08 RELEASE.md
-rw-r--r--  1 root     root        936 apr  7 09:08 requirements-dev.in
-rw-r--r--  1 root     root      23082 apr  7 09:08 requirements-dev.txt
-rw-r--r--  1 root     root       3177 apr  7 09:08 requirements.in
-rw-r--r--  1 root     root       5966 apr  7 09:08 requirements.txt
-rw-r--r--  1 root     root         14 apr  7 09:08 runtime.txt
-rw-r--r--  1 root     root        790 apr  7 09:08 SECURITY.md
-rw-r--r--  1 root     root       1047 apr  7 09:08 setup.cfg
-rw-r--r--  1 root     root      17973 apr  7 09:08 tasks.py
drwxr-xr-x  2 root     root       4096 apr  7 09:08 .vscode
```

**Comment by SchrodingersGat** [comment]
From whatever service is giving you the 502:

- Do you have a proxy server running in front of InvenTree?
- What URL are you trying to access?
- What are the connection logs from your browser?

**Comment by mabroens** [comment]
Im connecting to local host:
![image](https://github.com/inventree/InvenTree/assets/130482028/a1a7a709-ce33-485a-8240-e500fc068519)

not running a proxy server
but the same happens when i connect from an othe machine to the IP of that machine (Which btw is how i alway connected to InvenTree)

![image](https://github.com/inventree/InvenTree/assets/130482028/eb9283e3-e8c0-4686-b46f-79e7636a2846)

does this help you?
Br Martijn

**Comment by SchrodingersGat** [comment]
Ok, so probably the web server is not running, and nginx is not able to connect you to the server.

First port of call - check the nginx logs to see if there is any useful information there.

Second, @matmair can you advise on how to view inventree logs when installed via pkg?

**Comment by mabroens** [comment]
Brief update. mu Yubuntu was still at 20.01lts and since it appeared somethig was horebly broken i decide to upgrade to 22.04.

this did me bring closer to home. i.e. i no longer get the ngnix error but now the 127.0.0.1 reports `Unable to connect. an error occurd during the connection to 127.0.0.1`

seems to me like InvenTree is not starting its web server??
but perhaps we knwo more once we know where the InvenTree log files are located?

Br Martijn

**Comment by matmair** [comment]
Depends on your log level/where the error is if anything is logged for this error. Check `inventree logs` to see if anything was logged.
I think that your install is not "horribly broken", there is no need for large changes in the environment - that will make debugging just harder for us.
If you have already upgraded your os you will need to uninstall the inventree package and run the installer again (your settings and data remain) through this if you use the package installer. 22.03 and 20.01 have different packaging sources and 22.04 needs several extra packages for inventree to run.
If you touch your Python version/the mapping (which `python-is-python3` does) you will have to repair your env. Let's check first if uninstalling and running the quick install again fixes it - then we will try to check the env.

**Comment by mabroens** [comment]
@matmair thnx that sounds hopefull. 

when i look in  /opt/inventree/log -> /var/log/inventree
ls -al
drwxrwxr-x  2 inventree inventree  4096 jul  5 00:00 .
drwxrwxr-x 17 root      syslog     4096 jul  5 00:00 ..
-rw-r--r--  1 inventree inventree     0 apr  9 00:00 setup_2023-04-07_09_01_45.log
-rw-r--r--  1 inventree inventree 66727 apr  9 00:00 setup_2023-04-07_09_01_45.log.1
-rw-r--r--  1 inventree inventree     0 apr 27 00:00 setup_2023-04-25_15_30_41.log
-rw-r--r--  1 inventree inventree 41051 apr 27 00:00 setup_2023-04-25_15_30_41.log.1
-rw-r--r--  1 inventree inventree     0 mei 27 00:00 setup_2023-05-25_21_00_40.log
-rw-r--r--  1 inventree inventree 25335 mei 27 00:00 setup_2023-05-25_21_00_40.log.1
-rw-r--r--  1 inventree inventree     0 jul  4 00:00 setup_2023-07-02_20_27_31.log
-rw-r--r--  1 inventree inventree 41338 jul  4 00:00 setup_2023-07-02_20_27_31.log.1
-rw-r--r--  1 root      root          0 jul  5 00:00 setup_2023-07-03_09_09_36.log
-rw-r--r--  1 root      root       2144 jul  5 00:00 setup_2023-07-03_09_09_36.log.1


so the most recent log is the one from the 3d.

[setup_2023-07-03_09_09_36.log.1.log](https://github.com/inventree/InvenTree/files/11954525/setup_2023-07-03_09_09_36.log.1.log)

hope this help you or els epoint me to the file we are looking for.


wrt to reinstalling InvenTree.
invoking the install again is mostlikly again:
`wget -qO install.sh https://get.inventree.org && bash install.sh`

but removing it... how do o do this?

**Comment by mabroens** [comment]
Hi All,

sorry to ask but any hints how to proceed?
@matmair did the above help you in anyway?

If its safe to remove Inventree and reinstall that i'm fine with that as long as i get it operational again.

I do think that the update mechanism need some updating to avoid this for others. somethings about a dependency check or automatically install the required pyhton version.

**Comment by matmair** [comment]
You can uninstall inventree with `apt remove inventree` like any other package on debian/ubuntu https://linuxhint.com/uninstall-package-ubuntu/. It is safe to uninstall and install again - which is why i suggested it.

We are happy to review PRs regarding improvements. There are hosted offerings of InvenTree for ppl. without sysadmin knowledge, I recommend those for users relying on InvenTree for their buisness.

**Comment by mabroens** [comment]
@matmair thanks for confirming and that solved the issue.

Uninstall was not succesfful though as there was no Inventree installed it reported. but just running `wget -qO install.sh https://get.inventree.org && bash install.sh` solved it and made it work again.

many thanks.
