### ISSUE TITLE
Custom units get mangled improperly

### ISSUE THREAD

**Issue by MR-DOS** [inventree/InvenTree#5135]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi, the new feature for parsing custom units may have some internal bugs regarding capitalization - for example it changes MOhm (megaohm) to mohm (milliohm). In fact it seems to decapitalize all units which may break the meaning of some units. In the end, it causes major damage to parameter units.

Also, it changes % into "percent". Why?

![image](https://github.com/inventree/InvenTree/assets/29711626/93040c59-5d3f-424a-99a0-c858016ee4e5)
![image](https://github.com/inventree/InvenTree/assets/29711626/17bfc9f9-8209-4ef2-b262-84c97e5bd056)

### Steps to Reproduce

1. Make parameters with units which have a different meaning according to capitalization in 0.11.0 (mRad as milliRad for radiation / mrad as milliradian, MOhm vs mOhm (6 decades away), Nm versus nm (newtonmetre vs. nanometre).
2. Update to 0.12.0 and watch update log.

### Expected behaviour

The custom unit feature shall not change capitalization as units are case sensitive.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0
Django Version: 3.2.19
Commit Hash: 1d18b48
Commit Date: 2023-06-30

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-4.19.0-17-amd64-x86_64-with-glibc2.36
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Running migrations:
  Applying InvenTree.0002_auto_20230630_0441... OK
  Applying common.0017_notesimage... OK
  Applying common.0018_projectcode... OK
  Applying common.0019_projectcode_metadata... OK
  Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying taggit.0003_taggeditem_add_unique_index... OK
  Applying taggit.0004_alter_taggeditem_content_type_alter_taggeditem_tag... OK
  Applying taggit.0005_auto_20220424_2025... OK
  Applying stock.0097_alter_stockitem_notes... OK
  Applying stock.0098_auto_20230427_2033... OK
  Applying stock.0099_alter_stockitem_status... OK
  Applying stock.0100_auto_20230515_0004... OK
  Applying build.0042_alter_build_notes... OK
  Applying stock.0100_stockitem_consumed_by... OK
  Applying stock.0101_stockitemtestresult_metadata... OK
  Applying part.0105_alter_part_notes... OK
  Applying part.0106_part_tags... OK
  Applying part.0107_alter_part_tags... OK
  Applying part.0108_auto_20230516_1334... OK
  Applying part.0109_auto_20230517_1048...warning: Could not find unit match for nV/sqrt(Hz)
warning: Could not find unit match for pA/sqrt(Hz)
warning: Could not find unit match for nV/sqrt(Hz)
warning: Could not find unit match for - W/°C
warning: Could not find unit match for uVpp
Found unit match: Ohm -> ohm
warning: Could not find unit match for dBc
Found unit match: MOhm -> mohm
warning: Could not find unit match for mv/dB
warning: Could not find unit match for dBV
warning: Could not find unit match for MSa/s
warning: Could not find unit match for dBc
warning: Could not find unit match for LSB
warning: Could not find unit match for LSB
Found unit match: % FSR -> % fsr
Found unit match: % FSR -> % fsr
warning: Could not find unit match for dBc/Hz
warning: Could not find unit match for dBc/Hz
warning: Could not find unit match for dBc/Hz
warning: Could not find unit match for mVpp
Found unit match: Ohm -> ohm
warning: Could not find unit match for Million
warning: Could not find unit match for -
warning: Could not find unit match for -
warning: Could not find unit match for V-us
warning: Could not find unit match for -
warning: Could not find unit match for 10^-6/mT
Found unit match: Ohm.m -> ohm.m
warning: Could not find unit match for -
Updated units for 469 parameter templates
 - Converted 23 units
 - Found 15 invalid units:
   - - W/°C
   - uVpp
   - LSB
   - Million
   - pA/sqrt(Hz)
   - V-us
   - nV/sqrt(Hz)
   - -
   - 10^-6/mT
   - dBc
   - mv/dB
   - MSa/s
   - dBV
   - dBc/Hz
   - mVpp
Updated 14828 parameter values
 OK
  Applying build.0043_buildline... OK
  Applying build.0044_auto_20230528_1410... OK
  Applying build.0045_builditem_build_line... OK
  Applying build.0046_auto_20230606_1033... OK
  Applying build.0047_auto_20230606_1058... OK
  Applying build.0048_build_project_code... OK
  Applying part.0110_alter_part_units... OK
  Applying part.0111_auto_20230521_1350...Warning: Invalid units for part 'Part object (468)': triplets (3pcs)
Updated units for 20 parts
Found 1 invalid units:
 - triplets (3pcs)
 OK
  Applying company.0056_alter_company_notes... OK
  Applying company.0057_auto_20230427_2033... OK
  Applying company.0058_auto_20230515_0004... OK
  Applying company.0059_supplierpart_pack_units... OK
  Applying company.0060_auto_20230519_0344...Updated 1554 supplier part units
 OK
  Applying company.0061_remove_supplierpart_pack_size... OK
  Applying company.0062_contact_metadata... OK
  Applying company.0063_auto_20230502_1956... OK
  Applying company.0064_move_address_field_to_address_model... OK
  Applying company.0065_remove_company_address... OK
  Applying company.0066_auto_20230616_2059... OK
  Applying flags.0012_replace_migrations_for_wagtail_independence... OK
  Applying flags.0013_add_required_field... OK
  Applying label.0010_buildlinelabel... OK
  Applying label.0011_auto_20230623_2158... OK
  Applying order.0091_auto_20230419_0037... OK
  Applying order.0092_auto_20230419_0250... OK
  Applying order.0093_auto_20230426_0248... OK
  Applying order.0094_auto_20230514_2331... OK
  Applying order.0095_salesordershipment_delivery_date... OK
  Applying order.0096_alter_returnorderlineitem_outcome... OK
  Applying order.0097_auto_20230529_0107... OK
  Applying part.0112_auto_20230525_1606...Added field checkbox to model partparametertemplate
Added field choices to model partparametertemplate
 OK
  Applying part.0113_auto_20230531_1205... OK
  Applying plugin.0006_pluginconfig_metadata... OK
  Applying stock.0102_alter_stockitem_status... OK
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Operations to perform:
  Synchronize unmigrated apps: allauth, allauth_2fa, corsheaders, crispy_forms, dbbackup, dj_rest_auth, django_cleanup, django_filters, django_ical, django_otp, djmoney, drf_spectacular, formtools, generic, import_export, maintenance_mode, markdownify, messages, mptt, registration, rest_framework, staticfiles
  Apply all migrations: InvenTree, account, admin, auth, authtoken, build, common, company, contenttypes, django_q, error_report, exchange, flags, label, order, otp_static, otp_totp, part, plugin, report, sites, socialaccount, stock, taggit, user_sessions, users
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
System check identified no issues (1 silenced).
```

**Comment by SchrodingersGat** [comment]
@MR-DOS we moved to using [pint](https://pint.readthedocs.io/en/stable/) for physical part / parameter units in 0.12.0. Your migration here does show some units which are not directly supported and require some careful considration.

> In fact it seems to decapitalize all units which may break the meaning of some units.

It only decapitalizes units when it cannot find a direct match:

![image](https://github.com/inventree/InvenTree/assets/10080325/a103c6bd-888e-47fb-a572-1cc964c66cb1)

For example, `Ohm` is not considered a valid unit in pint, while `ohm` is the correct version.

However, it appears that converting the lower case version is too naive - prefixes are not considered, for example:

![image](https://github.com/inventree/InvenTree/assets/10080325/d1c38594-b356-4bd6-81e5-7d48917b1c4e)

Open to suggestions how we can make this conversion process more comprehensive

**Comment by MR-DOS** [comment]
If it's possible to have Mohm and mohm at the same time, that's OK for me, though not ideal.
What I still find a problem is that it changes % to percent and decapitalizes units which it does not like (e.g. % FSR to % fsr [full scale range]).

**Comment by SchrodingersGat** [comment]
@MR-DOS it should only convert to lower case if there is a matching lower-case unit. Not if there are no matches. Do you have any examples of it converting to lower case, even though there is no match?

**Comment by MR-DOS** [comment]
Probably not, my mistake.
Since it checks online for proper units when editing parameters, I'm OK with this solution as a user, though there may be some warning during migration that people should check units in InvenTree instances migrated from <=0.11.0.
