### ISSUE TITLE
Some FontAwesome icons broken by string truncating

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#5137]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Some specific FA-icons have broken sometime between 0.11.0 and 0.12.0.
The example I've located is on BOMs.

### Steps to Reproduce

https://demo.inventree.org/part/101/?display=bom

### Expected behaviour

The generated HTML string for this icon is:
```html
0
    <span class='icon-badge fas fa-times-circle icon-red float-right' title='No Stock Available'>
        
    </span>
```

This is then passed to
https://github.com/inventree/InvenTree/blob/2e7c86ff92b20c271943451ea249504d7628e36b/InvenTree/templates/js/translated/helpers.js#L401

which in turn triggers 

https://github.com/inventree/InvenTree/blob/2e7c86ff92b20c271943451ea249504d7628e36b/InvenTree/templates/js/translated/helpers.js#L116

The returned string then looks like:

```html
0
    <span class='icon-badge fas fa-times-circle... title='No Stock Available'>
        
    </span>
```

Totally breaking in-browser:

```html
<!-- <span class="icon-badge fas fa-times-circle... title=" no="" stock="" available'="">
        
    </span> -->
```

### Deployment Method

- [X] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0 dev
Django Version: 3.2.19
Commit Hash: 07cb147
Commit Date: 2023-06-26
Commit Branch: docker-docs
Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by LavissaWoW** [comment]
I was considering if it was as easy a fix as just rexex-removingthe HTML tags to determine if the string was too long, but that would break any HTML-based formatting with tags etc. So throwing it up here for opinions :)

**Comment by matmair** [comment]
@LavissaWoW can you provide a screenshot? I do not really see the broken icon on demo.

**Comment by LavissaWoW** [comment]
@matmair 
![image](https://github.com/inventree/InvenTree/assets/7506688/2fdc428c-7b98-4bdd-9331-b85bdde66b0e)

**Comment by SchrodingersGat** [comment]
The `shortenString` function should only  be applied to raw-text, not to the formatted html. Wherever this is happening, break out the inner text, shorten that first, and then wrap it in the html

**Comment by LavissaWoW** [comment]
As it stands, `shortenString` is used within `renderLink`, and the latter gets passed anything that's regarded as a link.
In this case, `<span>` tags to generate FA icons that someone wants to be a link.
