### ISSUE TITLE
Changing prefix of parameter's unit leads to wrong value displayed in part view

### ISSUE THREAD

**Issue by spike77453** [inventree/InvenTree#5148]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

After creating a new part with a parameter, the value is correctly display in the part parameter view (`/part/<n>/`, select Parameters) when hovering the mouse of the parameter value.

Here's an example of a 33 pF capacitor created with a parameter "Capacitance" which has a unit of "farad" correctly showing `3.3e-11 F`:

![Screenshot_20230704_044709](https://github.com/inventree/InvenTree/assets/25122064/4627a0aa-19e6-447c-9cba-783f839d1edb)

If one changes the prefix of the parameter (i.e. the multiple or submultiple of the unit) in `Settings -> Part Parameter -> Part Parameter Templates`, the value of the part is still calculated based on the previous prefix.

Here's the same 33pF capacitor after changing the unit of the parameter "Capacity" from "F" to "mF":

![Screenshot_20230704_044828](https://github.com/inventree/InvenTree/assets/25122064/d72a0172-46d6-4c18-bbf1-3ffb10bdbc6b)

This should be either `3.3e-8 mF` or `3.3e-11 F` since the value hasn't changed (i.e. it's still 33 pF).

The issue is not reproducible on https://demo.inventree.org. Here, the value is correctly shown as `3.3e-8 mF`.

![Screenshot_20230704_052854](https://github.com/inventree/InvenTree/assets/25122064/b1c1a319-824c-4d71-b879-10b1380998f5)

### Steps to Reproduce

0. Create parameter "Capacitance" with unit "F"
1. Create new part
2. Add parameter "Capacitance" with value 33 pF to part
3. Change unit of Capacitance from "F" to "mF"

### Expected behaviour

Either `3.3e-8 mF` or `3.3e-11 F` .

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.19
Commit Hash: 3ea5a36
Commit Date: 2023-07-04
Commit Branch: master
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-6.3.8-200.fc38.x86_64-x86_64-with-glibc2.37
Installer: GIT

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
When you update the "units" of a parameter template, the parameters are scheduled for update (it may take some time to update them all).

Each part parameter keeps two copies of data. The "raw" input (e.g. "33 pF") and the "native" value (e.g. "33e-12"). The "native" values get re-calculated when you update the parameter template, but this does not happen instantaneously. You should find that the values are updated after ~ 30 seconds?

**Comment by spike77453** [comment]
> The "native" values get re-calculated when you update the parameter template, but this does not happen instantaneously. You should find that the values are updated after ~ 30 seconds?

Gave it over a minute between changes but unfortunately the value is never updated. I've check `part_partparameter.data_numeric` in the mysql database and it stays `0.000000000033`.

**Comment by SchrodingersGat** [comment]
Is the background worker process running?

![image](https://github.com/inventree/InvenTree/assets/10080325/89eb1425-c565-4565-a21d-2885ad6ef8eb)

Check "server status" in the "system information" window

**Comment by spike77453** [comment]
D'OH! Thanks for you help and sorry for wasting your time.
