### ISSUE TITLE
Build Completion

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5157]
Completing a build order (particularly one with a large number of lines) takes a *long time* to complete. This is especially the case after the recent change whereby stock items are *consumed* by the build order.

This process can severely "block" the web interface - potentially timing out.

We *could* push some of the post-processing off to the background worker, such as the various housekeeping functions which mark stock as "consumed" etc.

**Comment by SchrodingersGat** [comment]
Not stale. Could be addressed with the new interface refactor

**Comment by SchrodingersGat** [comment]
Still important

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by NerosKi** [comment]
@SchrodingersGat This issue still seems to be relevant. On a build order of 200 items it takes over a minute to complete just 10.

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/pull/12361 was recently merged which provides a huge overhaul and performance improvement. 

It will be available in the upcoming 1.5.0 release
