### ISSUE TITLE
[FR] Add substitute details to BOM export

### ISSUE THREAD

**Issue by mredp-evos** [inventree/InvenTree#5179]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When exporting a BOM (.xlsx) with substitute parts it only includes the substitute part name and description. As these are not necessarily unique fields, it would be helpful to also include the IPN.

Additionally, when sharing the Bill of Materials with an external manufacturer. They need to know the parts manufactuer and supplier details. So, adding these additional columns would also help.

### Suggested solution

Add the following columns to the BOM export:

- Substitute IPN
- Substitute Manufacturer
- Substitute MPN
- Substitute Supplier
- Substitute SKU

As there may be multiple manufacturers and suppliers, they should follow the same structure as Inventree uses for the standard parts. So, for example:
- Substitute_Part1_Manufacturer_0
- Substitute_Part1_Manufacturer_1
- Substitute_Part2_Manufacturer_0
- etc.

### Describe alternatives you've considered

Instead of using Substitute parts, I can list multiple manufactures under each standard part. But this causes other issues for example, if the standard part is used in multiple products then that enforces that the substitutes are allowed in all products. This defeats the purpose of having BOM specific substitutes. 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by mredp-evos** [comment]
This might need its own issue as it is not related to substitute parts. But it is related to BOM export.
There is no part revision column in the BOM export. So it means you cannot track each BOM item back to the exact part.

**Comment by hugozijlmans** [comment]
> I have another addition to this issue which is not related to substitute parts but it is still related to BOM export.
> 
> The issue issue is that there is no part revision column in the BOM export. So it means you cannot track each BOM item back to the exact part.

Although I do not have an opinion on the original [FR] above, I stipulate the fact that it's very unfortunate that in the export for BOM the 'Part IPN' is exported but not the 'Part Revision'. I agree with @mredp-evos that when using this export for 3rd party manufacturing or internal BOM (whatever the use) the actual part cannot be traced in a BOM export.

**Comment by SchrodingersGat** [comment]
Not stale.

@hugozijlmans @mredp-evos would either of you be willing to submit a PR for these requested additions?

**Comment by hugozijlmans** [comment]
Hi @SchrodingersGat, I'd like to but don't know exactly how to. I have a work around solution just append the revision in the IPN. However that than completely omits the revision feature inentionally in there. So if it's not too much trouble adding it to the (BOM) export, which I can imagine, then I would very much like to.

**Comment by SchrodingersGat** [comment]
>  I'd like to but don't know exactly how to. 

Happy to help! Where do you need pointers? Finding the place in code to change? Or making a PR (pull request) to GitHub?

**Comment by hugozijlmans** [comment]
I can give it a go first. Ok let me try in a branch this week.

**Comment by hugozijlmans** [comment]
It's not so easy getting started from scratch. I've completed the steps for Quickstart and Setup DevTools from https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md. Is there some documentation I'm missing on where to find stuff?

**Comment by SchrodingersGat** [comment]
Have you checked out the [devcontainer docs](https://docs.inventree.org/en/latest/develop/devcontainer/)?

**Comment by matmair** [comment]
@hugozijlmans are you still intrested in this?

**Comment by mredpath2** [comment]
I have started to implement this, as per the original post the following data will be added to the BOM export:

- Substitute IPN
- Substitute Manufacturer
- Substitute MPN
- Substitute Supplier
- Substitute SKU

I think IPN should always be exported if "Include Substitute Parts" is selected. However, the manufacturer and supplier fields could be implemented in one of the following ways.

1. Always include manufacturer and supplier data if "Include Substitute Parts" is selected.
2. Only include manufacturer/supplier data if "Include Substitute Parts" and "Include Manufacturer/Supplier Data" is checked.
3. Add a separate options "Include Substitute Part Manufacturer Data" and "Include Substitute Part Supplier Data"

Is there a preference on how this is implemented @SchrodingersGat @matmair ?

I think while having more customization can be good. I would think in most cases you would always want it included so option 1 might be good enough. But shouldn't be difficult to do option 2 or 3 either I just don't want to clutter the UI.

**Comment by hugozijlmans** [comment]
Hi @mredpath2 thanks for thinking about my suggestion. I think it will be a valueable thing to add because of Change Control for BOM.
