### ISSUE TITLE
Build order with tracked items in the BoM cannot be completed

### ISSUE THREAD

**Issue by gunstr** [inventree/InvenTree#5195]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I had the same problem as was fixed in #5127 and just upgraded to the latest master. After that the BO looks all good:

![Screenshot 2023-07-06 195007](https://github.com/inventree/InvenTree/assets/41468206/ace31e47-d7c9-407e-a4a2-a8827e1900e5)

But when I try to compelete the BO that dialog anyway looks like this:

![Screenshot 2023-07-06 201940](https://github.com/inventree/InvenTree/assets/41468206/78a4f7e1-f51f-4181-bf49-23f589d23dd5)

All untracked and tracked parts in the BoM are allocated and the build output is completed, I managed to reproduce this problem on the Demo Server as decribed below.
 

### Steps to Reproduce

1. Create a tracked part with one tracked and one untracked part in the BoM
2. Open a BO for a few pieces
3. Allocate the untracked parts
4. Create build output and allocate the tracked parts. I do not assign serial numbers to the final parts, only a batch code - do not know if that matters...
5. Complete the outputs
6. The BO does now look OK and is ready to be marked as completed, no warnings
7. Click `complete BO` and in that dialog also in the Demo server looks like this:

![Screenshot 2023-07-06 210321](https://github.com/inventree/InvenTree/assets/41468206/b3473924-dec2-438b-a861-95060d20a980)

### Expected behaviour

Also BO's with tracked items should be possible to complete.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.20
Commit Hash: 4b40fe5
Commit Date: 2023-07-06
Commit Branch: master
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.31
Installer: GIT

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'ValidateUniqueIPN', 'slug': 'ipn_validator', 'version': '0.1'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.6.1'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@gunstr thanks for reporting, this is a bug, fix incoming :)

**Comment by gunstr** [comment]
@SchrodingersGat Thanks a lot, the fix solved the problem!
