### ISSUE TITLE
Bug: part attachments can not be deleted via GUI

### ISSUE THREAD

**Issue by mvnmgrx** [inventree/InvenTree#5216]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The delete button (![grafik](https://github.com/inventree/InvenTree/assets/99667992/cd41fd85-5b66-4402-92ab-8b4a1534e34b)) for a part attachment does no longer work after update to latest version.

### Steps to Reproduce

1. Select a part
2. Go to `Attachments` page
4. Upload an attachment
5. Click on the trashbin symbol to delete it
6. Nothing happens

### Expected behaviour

A modal pops up asking me if i really want to delete the part attachment

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

InvenTree v0.12.0

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

### Relevant log output

```shell
No relevant logs found
```

**Comment by SchrodingersGat** [comment]
@mvnmgrx thanks for reporting - see https://github.com/inventree/InvenTree/pull/5219
