### ISSUE TITLE
RuntimeWarning "[...]*.updated received naive datetime [...]"

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#5223]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Going through the logs on my production server, I find the occasional RuntimeWarning

`/home/inventree/env/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1358: RuntimeWarning: DateTimeField StockItem.updated received a naive datetime (2023-06-10 00:00:00) while time zone support is active.`

Same has occurred with `NotificationEntry.updated`

### Steps to Reproduce

Sadly not able to reliably reproduce this error

### Expected behaviour

It appears as if some `updated` timestamps are stored without TZ info.
Perhaps storing in ISO 8601 format would be better?
Not sure how these timestamps operate atm

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0
Django Version: 3.2.19
Commit Hash: 1d18b48
Commit Date: 2023-06-30
Commit Branch: stable
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.35
Installer: GIT

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by wolflu05** [comment]
I already experienced this issue the last days while developing, but didn't spend much attention at it. Now I did some checks. This must have something todo with some external dependency. I stepped back to commit 0c0e61432d2d4d44deb2c7d089e14217c448dad6 and still get this error.

**Comment by SchrodingersGat** [comment]
It has been there for a *while*. The CI logs used to be filled with this, which I mostly managed to get rid of (I thought it was completely gone).

If you work out where it is coming from, great :)

**Comment by SchrodingersGat** [comment]
@LavissaWoW did you ever get anywhere with this?

**Comment by LavissaWoW** [comment]
@SchrodingersGat I haven't gotten to attempting to brute-force (Read: clicking all kinds of links in a browser until the message pops) the errors yet due to being off on holidays and such :) Aiming to look into this soon.

**Comment by LavissaWoW** [comment]
@SchrodingersGat 
Using the devcontainer, you can see what requests are triggering these. 
In short, it seems to be caused by dates manually defined with Moment leading to the creation of a Model object that contains no TZ info. What I don't understand is why a new StockItem instance gets created when the resulting query returns no objects, and there are no existing StockItems with their `.updated` value set to this specific time.

The offending query parameters are these:

https://github.com/inventree/InvenTree/blob/a9d5b247022fec12d2d068cc7afc38618629c63b/InvenTree/templates/InvenTree/index.html#L113

Looking at P-UI, it seems that this notation has been cut. Instead of going a month back, it's now just fetching the last 10.
So these messages might disappear when migrating to P-UI

**Comment by SchrodingersGat** [comment]
> In short, it seems to be caused by dates manually defined with Moment leading to the creation of a Model object that contains no TZ info

So you are saying that creating a new stock item (with "bad" timestamp) is the cause here?

> What I don't understand is why a new StockItem instance gets created when the resulting query returns no objects

Can you expand on this? Not quite sure what you mean here

**Comment by LavissaWoW** [comment]
```
[22/Nov/2023 22:18:53] "GET /api/part/?search=&offset=0&limit=25&starred=true&active=true&category_detail=true HTTP/1.1" 200 1387
/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1358: RuntimeWarning: DateTimeField StockItem.updated received a naive datetime (2023-10-22 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
[22/Nov/2023 22:18:54] "GET /api/stock/?search=&offset=0&limit=25&in_stock=true&part_detail=true&ordering=-updated&updated_after=2023-10-22&location_detail=true HTTP/1.1" 200 52
```

This is the chain of log messages. As you can see, the runtime error is clearly referring to the get request below itself. The thing is, though. In the test dataset, no individual StockItem was last updated at 2023-10-22 00:00:00.
I naddition, not a single StockItem was updated the last month, so in the Dashboard, the table contains no elements.

So... If:
1. the resulting query returns an empty queryset
2. No StockItems were updated at that given time

Why are we getting an error from Django's internal Model __init__? That would imply that the code is creating an in-memory StockItem (Not present in the DB) using the date provided in the GET request.

**Comment by LavissaWoW** [comment]
> So you are saying that creating a new stock item (with "bad" timestamp) is the cause here?

I know I've seen somewhere something about timezones in the code or UI. But Django definitely considers timezones to be active.
So when a date containing no TZ info (Like 2023-10-11 00:00:00), Django throws a fit, because it doesn't know for sure if the date given was UTC or some arbitrary Timezone.

My own personal preference, on the server side, all dates should be either Linux Epoch or ISO 8601 formatted. But I'm not entirely sure what exactly is crating these ghost objects, so time format might not be the root issue.

**Comment by SchrodingersGat** [comment]
@LavissaWoW see the proposed fix in https://github.com/inventree/InvenTree/pull/5970
