### ISSUE TITLE
Protected settings not working

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#5227]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

While working on #5224 I discovered, that the initial implementation of protected settings (#2339) doesn't work correctly (anymore). You can still see the protected settings values in the plugin settings page and they aren't redacted. 

### Steps to Reproduce

1. create a plugin with protected settings
2. goto the plugins settings page and set a value
3. reload settings page and see the NOT redacted values

### Expected behaviour

protected settings should be redacted with `***`.

### Deployment Method

- [X] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.20
Commit Hash: c30190e
Commit Date: 2023-07-11
Commit Branch: feature/required-settings
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-5.15.49-linuxkit-pr-x86_64-with-glibc2.31
Installer: GIT

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Thanks @wolflu05 - fix incoming in https://github.com/inventree/InvenTree/pull/5229
