### ISSUE TITLE
Error Logs not working

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5230]
It would appear that the server error logs are no longer working correctly.

If an error occurs, a notification will be sent to the staff users, but the error does not exist in the database:

![image](https://github.com/inventree/InvenTree/assets/10080325/ef226a56-0c6e-402a-a326-5fe9f43b540c)
![image](https://github.com/inventree/InvenTree/assets/10080325/5b85ba5e-6ad2-4bee-b22e-6359c618df99)
![image](https://github.com/inventree/InvenTree/assets/10080325/5d00ae9e-d162-4a6f-b882-c6366f65173f)

This happens for "naturally occuring" errors, and also if you create one manually:

```python
from error_report.models import Error()
Error.objects.create()
```

The fact that the pk values are incrementing would suggest that the errors are actually being created? Additionally the "after_error_logged" hook is being called (to notify the users). So, it would seem that for some reason the errors are being subsequently deleted from the database.

@matmair have you seen this?

**Comment by SchrodingersGat** [comment]
Further investigation: The errors *are there* but not visible in the admin page:

```python
>>> Error.objects.count()
33
>>> Error.objects.last()
<Error: Error object (67)>
```

Going to `http://inventree.in.currawongeng.com.au/admin/error_report/error/67/` yields:

![image](https://github.com/inventree/InvenTree/assets/10080325/178a50f9-5f4c-4d75-9d3c-16197b5a13bf)

And the "error report" admin page is empty:

![image](https://github.com/inventree/InvenTree/assets/10080325/7c7dd04a-2c6f-47f9-93f4-69f2492898e5)

**Comment by matmair** [comment]
Interesting - I will try to debug

**Comment by matmair** [comment]
Seems to work on current master - could you provide more information on the version and deployment method?

**Comment by SchrodingersGat** [comment]
- Current master
- Docker (development)

**Comment by SchrodingersGat** [comment]
Ok, this one is on me. I have multiple setups running, and the error-report link was using the wrong base url. So the admin page was actually for a completely different install! Oops
