### ISSUE TITLE
Packing List support

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#5232]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Hi team, as i am progressing with my report templates for invoices (will upload this later once 100% sattified) i thought it was time to look again at creating a Packing List or pick list including serialnumbers for stock items.

i had a look at https://github.com/inventree/InvenTree/issues/62  where matmair provided me a link to [packing lists](https://docs.inventree.org/en/stable/report/pack/).  but unfortunatly this results in: 
![image](https://github.com/inventree/InvenTree/assets/130482028/8aaaa6dc-cf71-4760-827b-8ba6e4750857)

for version 0.11.0 it shows:
![image](https://github.com/inventree/InvenTree/assets/130482028/589af031-de87-45e1-96a1-74d61df92c70)

and in https://github.com/inventree/InvenTree/pull/748 
i noticed:
![image](https://github.com/inventree/InvenTree/assets/130482028/a79714f8-a26b-410e-89d2-24b4ab57d3f0)

is there anything left from previous work (not finisched) that i can take as starting point. then later when i am done i can upldoad it and you can post the template again.

I also had a look at: https://docs.inventree.org/en/0.6.0/report/context_variables/#stockitem which let me to a inventree_test_report_base.html (https://github.com/inventree/InvenTree/blob/master/InvenTree/report/templates/report/inventree_test_report_base.html)
which is the only thing i could find referencing serial numbers.

so tried following:
```
 {% for line in lines.all %}
<tr>
<td>
	<div class='thumb-container'>
		<img src='{% part_image line.part %}' class='part-thumb'>
	</div>
</td>
<td>
	<div class='part-text'>
		{% if line.part.revision %} 
				<strong>{{ line.part.IPN }} {{line.part.revision}}-Sample</strong>
		{% else %} 
				<strong>{{ line.part.name }}</strong>
		{% endif %}
		<br><br>
		{{ line.part.description }}
		</div>
</td>
{% if stock_item.is_serialized %}
	<td>{% trans "Serial Number" %}: {{ stock_item.serial }}</td>
{% else %}
	<td>{% trans "Quantity" %}: {% decimal stock_item.quantity %}</td>
{% endif %}

<td></td>
<td></td>
</tr>
    {% endfor %}

```
but that did not work for me.

Br Martijn

### Suggested solution

provide me some hint or older doc that could be reused

### Describe alternatives you've considered

see code snipped above

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by mabroens** [comment]
forgot to mention, in my example i have one line item but qty is 50 so in my ideal case i would want to print all 50 serail numbers.
so i thought of iterating over items
{% for line in lines.all %}
    {% for part in lines.part %}
        {{ part.item.serial }}
something like that

**Comment by matmair** [comment]
Pick lists were moved in the docs [to here](https://docs.inventree.org/en/stable/report/bom/?h=pick+list#pick-list).

**Comment by mabroens** [comment]
Hi, sorry to come back on this topic. but I'm still struggling to get this to work.
Goal create a shipping list including Serial Numbers. i would like this report to be with every shipment i make.
in this case i have 100 boards that will be in one shipment and the serial numbers should be printed on the report.

could somebody help me getting this to work. i can figure out how to get to the serial numbers: here's the code snippet that i have.

 ```
{% for line in lines.all %}
	<tr>
		<td>
			<div class='thumb-container'>
				<img src='{% part_image line.part %}' class='part-thumb'>
			</div>
		</td>
		<td>
			<div class='part-text'>
				{% if line.part.revision %} 
				  <strong>{{ line.part.IPN }} {{line.part.revision}}-Sample</strong>
				{% else %} 
				  <strong>{{ line.part.name }}</strong>
				{% endif %}
				<br><br>
				{{ line.part.description }}
		  </div>
		</td>
		<td> {% decimal line.quantity %} </td>
		<td> {% decimal line.allocated_quantity %} </td>
		<td> {% decimal line.unallocated_quantity %} </td>
	</tr>
	
	{% if line.allocated_quantity %}
		<tr class="serial-numbers">
			<td colspan='5'><strong> SerialNumbers:</strong></td>
		</tr>
		<tr>
			<td></td>
			<td colspan='2'> </td>
		</tr>
		
	{% endif %}
{% endfor %}

```

**Comment by SchrodingersGat** [comment]
For each [SalesOrderLineItem](https://github.com/inventree/InvenTree/blob/7d5ff1d5bdb35b66c340378f7828dc419320e2c4/InvenTree/order/models.py#L1278) instance there are multiple [SalesOrderAllocation](https://github.com/inventree/InvenTree/blob/7d5ff1d5bdb35b66c340378f7828dc419320e2c4/InvenTree/order/models.py#L1568) instances which link stock items to a sales order line.

So you could do something like:

```html
{% for line in lines %}
{% for allocation in line.allocations %}
{% with item as allocation.item %}
Item: {{ item.serial }}
Part: {{ item.part.name }}
{% endwith %}
{% endfor %}
{% endfor %}
```

**Comment by mabroens** [comment]
Thanks for the example.
i tried it but i get:
```
 {
    "error": [
        "Report printing failed"
    ],
    "detail": [
        "'RelatedManager' object is not iterable"
    ],
    "path": [
        "/api/report/so/9/print/"
    ]
}
```
with following code:
```
{% for line in lines.all %}
	<tr>
		<td>
			<div class='thumb-container'>
				<img src='{% part_image line.part %}' class='part-thumb'>
			</div>
		</td>
		<td>
			<div class='part-text'>
				{% if line.part.revision %} 
				  <strong>{{ line.part.IPN }} {{line.part.revision}}-Sample</strong>
				{% else %} 
				  <strong>{{ line.part.name }}</strong>
				{% endif %}
				<br><br>
				{{ line.part.description }}
		  </div>
		</td>
		<td> {% decimal line.quantity %} </td>
		<td> {% decimal line.allocated_quantity %} </td>
		<td> {% decimal line.unallocated_quantity %} </td>
	</tr>

	{% for allocation in line.allocations %}
		{% with item as allocation.item %}
			Sn: {{ item.serial }}
		{% endwith %}
	{% endfor %}
{% endfor %}
```
any suggestions?

**Comment by mabroens** [comment]
Thx that already no longer gives an error but also not the list of macs.
[S59_Shipment.html.txt](https://github.com/inventree/InvenTree/files/12464836/S59_Shipment.html.txt)

and the generated output.
![image](https://github.com/inventree/InvenTree/assets/130482028/cbf4cbea-e323-4690-aa98-cbf73b128f88)

so we can see there are 100 identical items 
![image](https://github.com/inventree/InvenTree/assets/130482028/7b777f65-c801-4a50-a43f-38078db34a25)

any further suggestions?

**Comment by mabroens** [comment]
ok brief update found that with this it now at least itterates over the 100 items.
but the serial number nor Part_name are printed.

```
{% for allocation in line.allocations.all %}
  {% with item as allocation.stock_item %}
    sn. : {{ item.serial }}
    Part: {{ item.part.name }}
  {% endwith %}
{% endfor %}
```

**Comment by SchrodingersGat** [comment]
I think it should be:

`{% with item as allocation.item %}` 

instead of

`{% with item as allocation.stock_item %}`

**Comment by mabroens** [comment]
I have tried that already:

```
{% extends "report/inventree_order_report_base.html" %}

{% load i18n %}
{% load report %}
{% load barcode %}
{% load inventree_extras %}
{% load markdownify %}

{% block bottom_right %}
	content: counter(page) " of " counter(pages);
{% endblock %}



{% block page_content %}

	{% for line in lines.all %}
	
		Part:  {{ line.part.name }}	<br>	
		Descr: {{ line.part.description }}<br>
		Allocated Qty: {{ line.allocated_quantity }}<br>
		{% if line.allocated_quantity > 1 %}
			Qtys: {% decimal line.quantity %}<br>
		{% else %}
			Qty : one<br>
		{% endif %}
		<br>
		SerialNr.: <br>
		{% for allocation in line.allocations.all %}
			{% with item as allocation.item %}
				{{ item.serial }} | 
			{% endwith %}
		{% endfor %}
	{% endfor %}

{% endblock %}

```
with this as output:
![image](https://github.com/inventree/InvenTree/assets/130482028/2d3a0deb-524f-4c15-9d27-d513c1d7d7c4)

so it iterates over all 100 instances. but it does not print any of its serials

**Comment by SchrodingersGat** [comment]
My bad,

```{% with item as allocation.item %}```

should be

```{% with allocation.item as item %}```

**Comment by mabroens** [comment]
@SchrodingersGat ,
many thanks for the support now it works and yes i should have noticed this one myself aswell.
