### ISSUE TITLE
[FR] Allow BOM entries that don't exist yet

### ISSUE THREAD

**Issue by formatc1702** [inventree/InvenTree#5233]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When importing a BOM, it is currently a strict requirement that all items in the BOM already exist in the Inventree database.

This prevents users from populating the database in a top-down way, i.e. by first creating the top level assembly, importing its BOM, and then creating the child components afterwards. This is especially valuable when dealing with mechanical assemblies that can be multiple layers deep.

Example:
It is more important (at least in the beginning) to be able to store the BOM info of my top-level assembly, than it is to have every single screw, washer and nut created as individual parts. Maybe I don't take detailed stock of these smaller components, or perhaps the diversity of screws and nuts is too big to create individual part entries for each (at least right now), but this should not block me from managing the high-level BOMs first.

### Suggested solution

It would be desirable to have the ability to deal with "unknown"/"nonexistent" items in a BOM, either permanently (if for whatever reason these entries are not considered relevant enough to manage in Inventree) or temporarily (e.g. populating the database top-down as described above).

This would allow storing meaningful data on top-level assemblies, and allowing to create assembly hierarchies top-down without having to fill the database bottom-up first.

Proposal:
Allow rows in the BOM that simply do not link to any other part in the database.

- Upon BOM import, fill out the description or part name field from the imported BOM
- Mark all Inventree-specific fields (e.g. `available`, `can build`, ...) with `unknown`, `-`, `?` or similar
- Mark the row with a special icon to indicate that it is not referencing an existing part in the DB

The cherry on top would be to provide a button next to rows of these "unknwon" components to quickly create them afterwards, and autofilling the description or part name field with the contents of the imported BOM.

Mockup (see row 5):

![image](https://github.com/inventree/InvenTree/assets/2447251/9b2237d9-7e40-470c-a315-4d3302aec5e7)

The same workflow could apply when using the `+ Add BOM item` button. The `Sub-part` field should not require selecting from the dropdown of existing parts, but allow for simple text entry as well.

### Describe alternatives you've considered

No alternative comes to mind, please advise :-)

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
InvenTree is designed with the part as the central component, implementing this would certainly not be as easy as it sounds. There is a lot of buisness logic around BOMs and they all expect that a BOM consists of parts with attributes.

**Comment by wolflu05** [comment]
With the react frontend we could add a button to the bom that opens a part create popup, than you could create it and then it's auto choosen by the bom.

**Comment by SchrodingersGat** [comment]
The first requirement would be to allow BomItem objects to have null values for the "sub_part" field. This should be done as its own PR to ensure that all the business logic is updated correctly and checked.

From there, it would be reasonably straight forward to import a BOM (with description / etc) and create a part from that data.

**Comment by SergeoLacruz** [comment]
This might be useful in the given example. For electronic designs i would like to disable it. We keep the lib in Inventree strictly in sync with DS-CR. If there is a part in the BOM that does not show up in Inventree it is definitely a bug in the lib. So I am happy if Inventree complains about it.

**Comment by method1020** [comment]
This feature would be a huge time saver for us. Even just the popup idea.

I am often running into instances where I need to import a BOM and it is hard to even see what parts are missing as they don't show up as named if they dont' exist in the database.

**Comment by matmair** [comment]
The required development effort is substantial as effects in core business logic are wide-reaching (pricing, BOs, BOM validation, importing, stock management). As long as no one takes ownership of the change and figures out all the edge cases I do not see this going anywhere.

**Comment by SchrodingersGat** [comment]
Not stale
