### ISSUE TITLE
Stock counting up when completing a build

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#5234]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi Team,

hope i'm wrong but i just completed a build order which has a BOM with allocated parts.
but after doing so i look at the current stock for one of the components and notice that instead of decreasing the stock with 15 it con incremented.

![image](https://github.com/inventree/InvenTree/assets/130482028/f2c23f89-330d-40c6-b265-9a012593fe92)

is this correct? i would have expected 180-15-15=150 not 210

Br Martijn

### Steps to Reproduce

create build order
watch stock total
allocat stock
complete build order
watch stock total, should be lower

### Expected behaviour

see above

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0
Django Version: 3.2.19
Commit Hash: 1d18b487
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Because you are not filtering the table to show only "in stock" items, you are also seeing the items which are actually consumed by the build order.

**Comment by mabroens** [comment]
Ah, ye sthat was the trick.
and nw i also understand the feature here.

default you can see all so including where it went and that just sums up.
thnks @SchrodingersGat
