### ISSUE TITLE
SalesOrder status 'Complete ' missing

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#5254]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi I believe i followed al steps for the sales order.
1) create sales order
2) allocate stock
3) ship order (Status changed to shipped) 
4) press Complete order
but its status remains shipped.
![image](https://github.com/inventree/InvenTree/assets/130482028/af05314c-44bb-4d91-86ca-a7f4fa3ad44e)

so i wen t in the admin for the sales order and noticed that the complet is not in the list
![image](https://github.com/inventree/InvenTree/assets/130482028/d946c30f-8d25-4579-823a-2ff8c6a25037)

BTW this is on Rev 0.12.0

did i miss something?

for your information i would like to use the completed status to indicate the ordr has been delivered/ and invoicing can take action.

also noticed that the docs for 0.12.1 is missing shipped
![image](https://github.com/inventree/InvenTree/assets/130482028/9a378931-8597-4b2e-8405-2b83132330b0)

Br Martijn

### Steps to Reproduce

see above

### Expected behaviour

i would expect the status to be present in the dropdown list. and i wold expect the button to remain ther 
![image](https://github.com/inventree/InvenTree/assets/130482028/37ab0688-ba7b-490a-af68-be49994bf775)
until the status is complete

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0
Django Version: 3.2.19
Commit Hash: 1d18b487
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@mabroens looks like a discrepancy between the docs and the code. I'll look into this

**Comment by mabroens** [comment]
@SchrodingersGat, 

but than still the issue remains right? in the application the `complete `status is missing.
![image](https://github.com/inventree/InvenTree/assets/130482028/5dcfe877-b1a4-42e6-ab8a-2dd29180956d)

and in the admin for the order:
![image](https://github.com/inventree/InvenTree/assets/130482028/4ed0e6a6-e116-4535-b1d6-4e100e0eb0c9)


or am i missing something??

**Comment by SchrodingersGat** [comment]
@mabroens here "Shipped" means that the order is complete. There is no "Complete" status
