### ISSUE TITLE
[BUG] Not possible to use units not understood by pint

### ISSUE THREAD

**Issue by MR-DOS** [inventree/InvenTree#5265]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

It is impossible to define custom units, Inventree rejects them.
It is impossible to assign a value to a parameter using a unit which is not recognized.
This means that users are forced to not use any unit in parameters which use non-recognized units.
Parameter adding form doesn't show parameter description, so it's not possible to write the custom unit in description and have it visible when adding a parameter to a part.

For example mVpp, uVpp [peak to peak voltage], W/°C [thermal resistance, also denoted as W/K often], LSB [used with ADCs, DACs, least significant bit], pA/sqrt(Hz) [current noise in opamps, is it now possible to use UTF-8 characters?], V.us [saturation of transformers], nV/sqrt(Hz) [voltage noise of opamps], - [to denote unitless parameters, a.u. may also sometimes be used], 10^-6/mT [for magnetics], dBc [deciBels of carrier, used in RF], MSa/s [sampling rate], dBV [decibelvolts], dBc/Hz [used for phase noise measurements in RF].
Most of these units are actually quite commonplace, not obscure, nonsense or non-physical.
![image](https://github.com/inventree/InvenTree/assets/29711626/bd3fda84-db9e-4669-bd33-c419bac2b82a)

Also, Inventree currently converts % to percent which is more difficult to recognize visually. Already mentioned in #5135.
![image](https://github.com/inventree/InvenTree/assets/29711626/031b1a55-c839-4174-8dd1-ee0052a25c76)

Some units may get decapitalized for some reason - for example % FSR to % fsr. Already mentioned in #5135.
![image](https://github.com/inventree/InvenTree/assets/29711626/b65c5d7a-1d65-4831-87b4-7e3ae647d19e)

Ohms get sometimes decapitalized, sometimes not if used in compound units. Already mentioned in #5135.
![image](https://github.com/inventree/InvenTree/assets/29711626/5aed4c40-9f5e-4edb-a90b-2fde9d21cc45)

Currently, this new feature has made me unable to add new parts (unless I delete units), at least in several categories such as: switching power supplies, linear regulators, voltage references, any components where temperature under load is important (nearly anything), DACs, ADCs, opamps, comparators,instrumentation amplifiers, magnetics and almost anything common with RF. Which is quite unpleasant at the moment.

### Steps to Reproduce

Described in bug description - non-recognized but valid units may not be assigned to parameter templates and parameters with non-recognized unit in parameter templates cannot be entered at all.

### Expected behaviour

There could be a possibility to enter non-recognized units to parameter templates (maybe have a checkbox to disable the unit checking/conversions for a given parameter template).
For parameters with non-recognized units (of for templates with the checkbox checked), it would be more useful to disallow entering a value along with unit, only value should be allowed (so no recalculation is triggered).

Maybe an easier way would be to add a checkbox to a parameter template that it's actually a "arbitrary text" value even though it has unit.

Also, could parameter decription be shown when adding a parameter? This could help for some parameter templates where user is not sure which one to choose for a certain value (happens sometimes in electronics).

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0
Django Version: 3.2.19
Commit Hash: 1d18b48
Commit Date: 2023-06-30

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-4.19.0-17-amd64-x86_64-with-glibc2.36
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
Hi there @MR-DOS this is a known limitation with an open FR https://github.com/inventree/InvenTree/issues/4840
If you do not set a unit you can input whatever - see examples below
![grafik](https://github.com/inventree/InvenTree/assets/66015116/82222c6c-3ede-41bc-b9fa-e9da1c695265)
![grafik](https://github.com/inventree/InvenTree/assets/66015116/6c14a99f-ed8b-4782-bd6f-0807d6942e4e)

**Comment by SchrodingersGat** [comment]
In addition to the comment by @matmair above - there is a WIP to implement custom units - https://github.com/inventree/InvenTree/pull/5268

**Comment by SchrodingersGat** [comment]
#5268 has now been merged into master - please check it out and LMK how it looks for you

**Comment by MR-DOS** [comment]
> #5268 has now been merged into master - please check it out and LMK how it looks for you

Sadly, I lack the magic powers to try out something which has not been rolled out to Docker, sorry for that. But if it gets into Demo site, I will surely check it out.

**Comment by wolflu05** [comment]
@MR-DOS it should be already on docker hub, the `:latest` image tracks the master branch, so it should be already automatically deployed to the demo site.

**Comment by SchrodingersGat** [comment]
Yep, ready at a demo site near you

**Comment by MR-DOS** [comment]
The Demo site doesn't allow me to enter custom unit. Am I doing something wrong?
![image](https://github.com/inventree/InvenTree/assets/29711626/8065b715-a99f-4eeb-a2cf-b180715285be)

**Comment by SchrodingersGat** [comment]
You have to define your custom unit before you can use it in a parameter

**Comment by MR-DOS** [comment]
Yes, it does work. Though when adding the parameter, it shows the non-fancy internal name instead of the "symbol". Or maybe I understand the usage of the symbol symbol incorrectly?
Otherwise, this solution is great.
![image](https://github.com/inventree/InvenTree/assets/29711626/e8ab30ba-a492-4160-aab4-5aff26d4626a)
![image](https://github.com/inventree/InvenTree/assets/29711626/e2a89bae-0dbd-4010-af0f-eee241f6de23)
![image](https://github.com/inventree/InvenTree/assets/29711626/dc5f6ca4-1479-4ae9-bef5-110d0f05b2c4)

**Comment by matmair** [comment]
@MR-DOS can we close this issue then?

**Comment by SchrodingersGat** [comment]
@MR-DOS yes you have to use the "name" of the unit, that is a limitation of the system. Glad you got it working :) LMK if you come across any other issues.

**Comment by MR-DOS** [comment]
@matmair Yep.
@SchrodingersGat What is the use of the symbol then, if it doesn't appear anywhere else?

**Comment by SchrodingersGat** [comment]
@MR-DOS honestly I was hoping to get it to work as you expected, but have not been able to work out how yet. Maybe it can be done?
