### ISSUE TITLE
[BUG] Bill of Material - Price invalide when a sub-BOM is open

### ISSUE THREAD

**Issue by RichiSeitz** [inventree/InvenTree#5286]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When you have a BOM you can find the sum of all prices at the very end. This price is correct but when you open a sub-BOM in this BOM you can see all the parts includes one by one and also the prices for each part separate. Know you have the fail at the sum of all prices, because you add the prices for each part to the price of the sub-BOM where the parts are located. For example: You have a product which is build with Pos1. Plug (1€) and Pos2. Wires (BOM) (2€) you have the correct price of 3€. When you let flip open the "Wires-BOM" you have Pos1. Plug (1€), Pos2. Wires (BOM) (2€), Pos.2.1 Wire1 (1€) and Pos.2.2 Wire2 (1€) so your complete price is now 5€ (1+2+1+1) 

### Steps to Reproduce

see describtion 

### Expected behaviour

show us the correct price in all cases, please

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.2
Django Version: 3.2.18
Commit Hash: 4868194
Commit Date: 2023-05-25
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
@#can you reproduce this on the demo site? If not this might be an issue that is already fixed. Please provide steps for reproduce that demonstrate the supposed bug on the demo site

**Comment by RichiSeitz** [comment]
Yes I can reproduce the issue on the demo site.

**Comment by RichiSeitz** [comment]
Hello, yes the problem is still important. The problem is just existing and for me an essential part of the software. It would be nice, if you could fix this bug, please.

**Comment by JambonLeVrai** [comment]
I can confirm this is happening with the last version

**Comment by SchrodingersGat** [comment]
This would be a great starter issue for anyone who wants to jump in - in the BOM table, the total pricing is calculated as part of the pricing row footer:

https://github.com/inventree/InvenTree/blob/814322e512c348cb62fa1ea853078ddfa1cb41fb/InvenTree/templates/js/translated/bom.js#L1097

This function needs to be adjusted to only add prices which point to the top-level items in the table (ignore any sub items)
