### ISSUE TITLE
Reuse Part Image - Select Part Image - Does Not Show Images, Only Checkboxes 

### ISSUE THREAD

**Issue by imager2019** [inventree/InvenTree#5292]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When adding an existing image to a Part, the option only displays check boxes and no images.

![image](https://github.com/inventree/InvenTree/assets/49574724/6aebf117-0c1e-4c49-8e5a-d1470cd678bc)

### Steps to Reproduce

Go to Parts
Select any existing part
From the Part Image, use the "Select From Existing Images" option
Only check boxes will be displayed, no graphics
![image](https://github.com/inventree/InvenTree/assets/49574724/6b80ee65-59e2-4c19-8b08-f406e948913c)

### Expected behaviour

Would expect to see existing images that have already been uploaded to the system.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.12.1

Issue cannot be reproduced on demo site.

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
- Have you recently updated?
- Have you tried a [hard-refresh of the page](https://docs.inventree.org/en/latest/faq/#feature-x-does-not-work-after-update)
- Can you show the "console" window from the developer tab of your browser

**Comment by imager2019** [comment]
Good evening.. I read your note and went ahead and moved from Chrome to Microsoft Edge and it is working as intended.

Went back into Chrome and cleared "Cookies and other site data" along with "Cached images and files" and that cleared it up. 

Thanks for pointing me in that direction - we can mark the issue as non-existent...

Appreciate the help..
