### ISSUE TITLE
API/ P UI generic forms

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#5295]
We need a way to define generic forms that can be used at various places in inventree:
- Settings (integration with `InvenTreeBaseSetting`)
- Label printing drivers (and later machines - #4824) should be able to provide inputs on the printing dialog
- ...

To do so we would need some reusable logic in the generics package. This is somehow a bit similar to the state we already have there. I'd like to use this issue for proposing a few things how this process could look like and what I already thought so we can discuss this before one of us implements it. What is you opinion on this @SchrodingersGat , is that something you also have in mind? I created this issue as discussion base.

---
```py
from generic.forms import ReactForm, FormField, SubField
from common.settings import InvenTreeSettingsForm

class ZebraLabelPrinterOptionsForm(ReactForm):
    def get_orientation_choices(self, *, label):
        return [...]  # returns orientation choices based on the label field on which it depends

    label = FormField(...)
    orientation = FormField(type="choices", name="orientation", description=_("Paper orientation"), required=True, depends_on=["label"], get_choices=get_orientation_choices)
    
    color_mode = FormField(type="bool", ...)

    another_cool_field = SubField(name="another_cool_field", fields=[
        FormField(name="abc")
    ])

class ZebraLabelPrinterOptionsDetailForm(ReactFormDetailAPI):
    form = UserSettingsForm

class ZebraLabelPrinterOptionsForm(ReactFormAPI):
    form = UserSettingsForm

urls = [
    path("<key:slug>/", ZebraLabelPrinterOptionsDetailForm.as_view()),
    re_path(r"^.*$", ZebraLabelPrinterOptionsForm.as_view()),
]


# alternative, automatically creates the required form fields based on the InvenTreeUserSetting definition, but works the same
class UserSettingsForm(InvenTreeSettingsForm):
    class Meta:
        model = InvenTreeUserSetting

```
#### Single form field:
- Note: query params are the values of the fields they depend on
- `GET [...]/<field_name>` Gets a single form field
- `POST [...]/<field_name>` Posts a single form field
- `PATCH [...]/<field_name>` Patches a single form field
- `PUT [...]/<field_name>` Patches a single form field

#### List form fields:
- `GET [...]/` Lists all form fields
- `POST [...]/` Posts a form with all fields
- `PATCH [...]/` Patches a form with all fields
- `PUT [...]/` Puts a form with all fields

And then on react we could just do something like this:
```tsx
const ZebraLabelPrintingForm = () => {
    const formSubmitHandler = useCallback((data) => {
        console.log("Form was submitted with data", data)
    }, [])
    return (
        <div>
            <ReactForm url="[...]/" onSubmit={formSubmitHandler}>
        </div>
    )
}
```
Which automatically renders out the complete form as described with the python class by:
1. Making an API call to `GET [...]/` which lists out all settings
2. iterates over the settings and renders the correct mantine components
3. uses the useForm hook from mantine to handle form state
4. handles form submitting

**Comment by SchrodingersGat** [comment]
My gut feel here is that the plugin interface (e.g. for printing) should be generic, so the front end (via react) constructs the form dynamically with information provided by the API.

This is the way that the current forms architecture works

**Comment by wolflu05** [comment]
> My gut feel here is that the plugin interface (e.g. for printing) should be generic, so the front end (via react) constructs the form dynamically with information provided by the API.

Sorry if it wasn't clear, using label printing was just an example to show the capabilities of my imaginated api. Definitely this will not be used in that way.

**Comment by wolflu05** [comment]
Maybe could you quickly write down what you roughly have in mind?

**Comment by matmair** [comment]
We already have a Rest API for settings; that should not be broken if possible

**Comment by SchrodingersGat** [comment]
@wolflu05 check out [forms.js](https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/js/translated/forms.js) for our current implementation of modal forms. My refactor into react would re-implement much of this functionality (hopefully in a cleaner way). It is in two stages:

## 1. Generic Modal Form Component

Construct a generic modal form component which allows the field definitions to be passed to the component constructor. Handles things like:

- Defining field types
- Labels / help_text / placeholder / etc
- Validation error messages
- Buttons, progress bars, spinners

## 2. API Driven Forms

Leverages the form Component to render a form which is created dynamically from an API endpoint. The InvenTree API provides all the required information via an `OPTIONS` request to each endpoint.

**Comment by wolflu05** [comment]
And do you have any plans for adding some generic interface to expose the required APIs and form definitions for the dynamic forms? That's the thing I described above and what I need. In addition I would also need dependent options, and suboptions. Would your implementation also cover all of that, or do you only want to focus on the react side?

**Comment by SchrodingersGat** [comment]
> And do you have any plans for adding some generic interface to expose the required APIs and form definitions for the dynamic forms? 

Yes, this will be covered by point 2.

I think it will make a lot more sense once I start implementing!

**Comment by wolflu05** [comment]
Ok, then do it and I'll wait

**Comment by wolflu05** [comment]
@SchrodingersGat you said you are currently implementing the forms api. Initially while creating this issue I imagined the API forms something like [this](https://github.com/wolflu05/inventree-bulk-plugin/blob/4a718d22faa2b956b0ccc2e803635da5cbf7c3dc/inventree_bulk_plugin/bulkcreate_objects.py#L249-L344). This is an example of my plugin where I use the definition to bulk generate a lot more complex structure than just a the fields for stock locations or part categories. This fields definition is used to only define the fields on the backend and the frontend then automatically fetches them. Something like this could be easily extended to also create the dependent fields, groups and much more proposed in this issue. This would also enables us to have a standard of fields definition that can also be implemented by the mobile app, so adding of some new fields for e.g. a date fields doesn't require any changes in the app, and the app is also compatible with old software versions, but also with the current development version.

**Comment by SchrodingersGat** [comment]
As @matmair says here, the current work is focused on recreating / refactoring what we currently have, in react.

As an output of this work we will have an extensible front-end component set which can be augmented / extended as required. 

But for now, just looking to reimplement the functionality that we already have.

**Comment by SchrodingersGat** [comment]
@wolflu05 perform an `OPTIONS` request to `/api/part/` (you can do this in `DEBUG` mode using the DRF web viewer):

This will give you a full set of fields which are available at that endpoint.

This is generated in `./InvenTree/metadata.py`

**Comment by wolflu05** [comment]
Thank you for the hints, I'm currently playing a bit with a custom serializer field and it works pretty good to solve the dependent sub fields. DRF serializer fields actually how I imagined the API while creating this issue, but I was not aware of that most of this stuff is already built into DRF, and that they are a lot more powerful than my previously proposed PR. I'll try to submit a first draft including printing options in the next days/weeks.

**Comment by wolflu05** [comment]
This was already covered by the OPTIONS forms. #5837/#5924 added the `dependent field` and full `nested object` field support which I was describing above. So this can be close now.
