### ISSUE TITLE
[FR] Method, later an API, for moving an outer storage container between locations  

### ISSUE THREAD

**Issue by eriklundh** [inventree/InvenTree#5297]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I would like to be able to pick up an big container, with a number of smaller parts containers and bags inside, and move the outer container to another room. 
I plan to do this by a wireless barcode scanner, which I will interface with Inventree.
I am thinking of a mechanism where I first scan the outer container's barcode and then do a "check in" of it to a new storage location by barcode. All sublocations should be updated.
I can manage the logic and code for my particular use case, I just need to understand the implications of updating all the paths.  Is there some registry of storage paths, or is the storage path stored with each part?  I have not found any database schema. 

### Suggested solution

I would like Inventree to gracefully handle relocation of a storage unit at any level. This is a common use case for a multiroom electronics lab or shared workspace, e g makerspace.
Priorities:
1. An answer on the implications of, and best practice for, (bulk?) changings paths.
2. An API that implements the preferred way to move an outer container, thus altering a lot of storage paths.
3. UI for doing this operation at the outer container level.  

### Describe alternatives you've considered

Altering the database myself.  I run the docker dev setup right now, but I would like the move container to work on all supported databases.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
Sounds interesting in general. A word of warning: directly messing with the database can be problematic. Wrap your action in an [atomic block](https://docs.djangoproject.com/en/4.2/topics/db/transactions/#django.db.transaction.atomic) to limit operations while keeping all the ORM benefits. Paths are constructed on the fly, they are consisting of nested StockLocation objects.

There are similar, maybe duplicate issues on the books for a while now, especially #2058 comes to mind.
I personally do not have bandwidth or interest for this but maybe someone else is intrested.

**Comment by SchrodingersGat** [comment]
@eriklundh this functionality is already supported. For example in the app, when viewing a particular stock location, you can select "transfer stock location" and use the barcode scanner to "move" it into another location.

We do not have the barcode side of things implemented in the web interface currently, but the code (and API) is there

**Comment by eriklundh** [comment]
Great!
Then I can work out the logic for my use case with a handheld barcode scanner, and hopefully over time make it general enough to be useful as a contribution.  I have some thoughts about how to make it as frictionless as possible with bar codes, "easier than not" to keep location up to date, when you - like me - often move around outer storage units. 
Thank you for a the great work you put into Inventree!
(I have reached a major pain point right now, and need to get better organized)

**Comment by SchrodingersGat** [comment]
@eriklundh our barcode support could definitely be much better, and I think would make the software so much more user friendly! 

We are currently in the middle of a major UI refactor, moving to react for the web front-end, so any barcode stuff you want to add in will be best done when that is ready for contributions :)

**Comment by wolflu05** [comment]
I need this myself and like to implement this. @eriklundh have you started development already?

**Comment by eriklundh** [comment]
No, not yet.
FYI: I am currently spending all my spare time on replacing all doors and
windows on the main house of my old family farm. Has to be done before the
late autumn cold hits the south of Sweden. It is just me and my wife, no
extra help.
I don not expect to have serious time to spend on InvenTree until late
October.
/Erik

**Comment by SchrodingersGat** [comment]
So we are all on the same page - if I am reading this correctly, what is proposed here is to implement the required barcode functionality in the web interface, yeah? The API framework should all be in place already.

**Comment by wolflu05** [comment]
There is already an API to move locations around? Didn't saw that. Then I only need to implement a simple form in the web Interface for handeling this. Using barcodes was not really my priority, I wanted to build the api. Also for categories to move one or more nodes with its sub tree to another parent.

**Comment by SchrodingersGat** [comment]
@wolflu05 I still feel like I am missing something here, but this seems simple to implement. Each location has a "parent" location. To "move" a location, simply change the parent for that location.

e.g.

```
PUT
URL = /api/stock/location/1/
DATA = {
  'parent': 3,
}
```

**Comment by wolflu05** [comment]
Locations are a MPTT models to represent the tree, I don't think we can mess around on our self with that, because there need to be the lft, rght, path string, level fields be updated on db. And there is this [`move_to`](https://django-mptt.readthedocs.io/en/latest/models.html#move-to-target-position-first-child) utility function from `Django-mptt`, so I think we should use that.

**Comment by wolflu05** [comment]
In addition, if such a dedicated route exist, one could later also implement tracking of those movements like proposed in #2058

**Comment by SchrodingersGat** [comment]
@wolflu05 you can *already* change the parent location for a location, using the API... The MPTT tree updates are performed automatically!

Look at the "edit location" function on any stock location - see that you can change the location parent? That is all that is required to move a location tree around.

**Comment by SchrodingersGat** [comment]
> In addition, if such a dedicated route exist, one could later also implement tracking of those movements like proposed in #2058

Location tracking would be a good addition - and could be implemented into the current code without a new API endpoint. Much like we do for stock item updates.

**Comment by wolflu05** [comment]
> Look at the "edit location" function on any stock location - see that you can change the location parent? That is all that is required to move a location tree around.

I See, works like expected, didn't knew this was already possible. Then only the issue title is misleading.

> Location tracking would be a good addition - and could be implemented into the current code without a new API endpoint. Much like we do for stock item updates.

Yeah, makes sense too, sorry for confusion, but tracking is not what I need currently, just got in that in mind So everything I need works already.

**Comment by eriklundh** [comment]
A clarification:
The approach to barcode scanning that I sketched “on a napkin” would have a
server process talking to InvenTree APIs. The server process would then use
MQTT to talk to small interface devices, based on ESP32 (typically a bridge
to an Bluetooth barcode reader) or Raspberry Pi. One ESP32 reads barcodes.
A Raspberry pi drives a big wall display.  Another Pi interfaces with a
label printer, etc. I have done similar setups with different devices and
mixed interface hardware in the past. So far MQTT has been useful to tie
things together. It is also easy to do “pipes and filters”-style
programming that is harder if you just interface with APIs.

Some later ESP32s can also be used to detect presence in a certain room, an
inexpensive albeit coarse indoor positioning, helping the forgetful user
that forget to scan the correct room barcode when placing a container.

/Erik

**Comment by matmair** [comment]
@eriklundh So on the InvenTree side, we are only talking about some UI changes?
