### ISSUE TITLE
[bug] installed items are no longer shown in stock views

### ISSUE THREAD

**Issue by T0jan** [inventree/InvenTree#5303]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi,

after updating from the 0.12.x branch to the master branch today I noticed that installed stock items can no longer be found via the stock view. It seems like the filter to not show installed items is permanently set and the user can't change it.

![image](https://github.com/inventree/InvenTree/assets/22519396/b525848d-db93-4495-a3d9-91be6a8510c9)

As you can see I have no filters set, the table claims 11 items are being shown with only eight actually visible, the four missing SNs 1, 5, 9 and 10 being installed in other stock items.

I also tried if it only affects SNs which ave been installed prior to the server update but I can tell that this is not the case.

### Steps to Reproduce

1. update server from 0.12.x to master
2. check stock item lists with installed items

### Expected behaviour

all stock items should be shown when no filter is set.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.20
Commit Hash: 3bea809
Commit Date: 2023-07-05
Commit Branch: master
Database: postgresql
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.35
Installer: GIT

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.
- see https://demo.inventree.org/part/87/

**Comment by SchrodingersGat** [comment]
@T0jan thanks for reporting, this was a pretty weird edge case
