### ISSUE TITLE
[FR]Allow selecting multiple rows in tables when shift is pressed

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#5332]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

It would be useful to set the data-multiple-select-row attribute on the selectable tables to being able to select multiple rows by holding the shift key.

### Suggested solution

Set data-multiple-select-row on the selectable tables:
https://examples.bootstrap-table.com/#options/multiple-select-row.html

### Describe alternatives you've considered

-

### Examples of other systems

-

### Do you want to develop this?

- [X] I want to develop this.

**Comment by martonmiklos** [comment]
I am not an expert on these frontend things, will react bring it's own UI toolkit i.e. going to replace bootstrap things?

**Comment by wolflu05** [comment]
Yes, the react ui won't be made with bootstrap and bs-table, instead we use mantine and mantine-datatable (ref: #5218 ). Maybe its a good idea to consider then.

**Comment by martonmiklos** [comment]
> Yes, the react ui won't be made with bootstrap and bs-table, instead we use mantine and mantine-datatable (ref: #5218 ). Maybe its a good idea to consider then.

Thanks for the info! The mantine-datatable looks to be supporting the feature I wanted OOTB, with some side effects: it also selecting the text of the rows (at least with Firefox).

Is there any estimation how far is the react UI change?

**Comment by SchrodingersGat** [comment]
> Is there any estimation how far is the react UI change?

Target is by the end of the year, earlier if we get more development support, later if the scope creeps away from us!

**Comment by martonmiklos** [comment]
The problem with the [bootstrap multi select ](https://examples.bootstrap-table.com/#options/multiple-select-row.html)is the fact that it changes the current behavior: the Ctrl key must be pressed to being able to make multiple selection and right now the multiple selection is allowed without that. The mentioned Mantine datatable does what I suggested.
