### ISSUE TITLE
Invoke Backup - Fails

### ISSUE THREAD

**Issue by imager2019** [inventree/InvenTree#5334]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

On a fresh install on Debian 11, using the Quick Script installer. The invoke backup fails with 

FileNotFoundError: INVENTREE_STATIC_ROOT not specified

### Steps to Reproduce

On a fresh install on Debian 11, using the Quick Script installer after issuing:
```
cd /opt/inventree
source ./env/bin/activate
```

I attempt to force a backup using: `invoke backup`

I receive the following, with the error at the end of the output window:
```
(env) root@debian:/opt/inventree# invoke backup
Backing up InvenTree database...
load version from file
Traceback (most recent call last):
  File "/opt/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/opt/inventree/env/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/inventree/InvenTree/InvenTree/settings.py", line 116, in <module>
    STATIC_ROOT = config.get_static_dir()
  File "/opt/inventree/InvenTree/InvenTree/config.py", line 230, in get_static_dir
    raise FileNotFoundError('INVENTREE_STATIC_ROOT not specified')
FileNotFoundError: INVENTREE_STATIC_ROOT not specified
```

The `config.yaml` file (from `/etc/inventree`)  (attached below and named config.yaml.txt) indicates that the static_route is set.

[config.yaml.txt](https://github.com/inventree/InvenTree/files/12152651/config.yaml.txt)

The system also has a second `config.yaml` located in `/opt/inventree/InvenTree` which is locked and I have not attempted to edit this. Is it necessary to edit the second `config.yaml` file?

I have confirmed that the `backup, media, static` folders are located in `/opt/inventree/data` along with the database (`database_sqlite3`).

Is there a setting/feature I have forgot to enable?

### Expected behaviour

Looking for backup process to not show errors and complete backup

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.1
Django Version: 3.2.19
Commit Hash: 93b44ad8
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.10.0-23-amd64-x86_64-with-glibc2.31
Installer: PKG
Target: debian:11
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@imager2019 thanks for reporting. I cannot reproduce the issue here, but I am not running with the same setup as you (windows / docker). Your config file looks OK as far as I can see.

@matmair any thoughts on this one?

**Comment by matmair** [comment]
The used commands will not work. The quick installer installs the package, which comes with its own environment and that follows the Debian path conventions. The settings are in /etc. Run your command with `inventree run cli` and not with invoke - that will set up your environment correctly.

**Comment by imager2019** [comment]
I did in fact use the quick installer on Debian 11.
Could you clarify where I should execute the` inventree run cli` from? I have tried:

from **/opt/inventree**
```
inventree@debian:~$ cd /opt/inventree
inventree@debian:/opt/inventree$ inventree run cli
/opt/inventree/vendor/pkgr/processes/cli: 2: exec: .: Permission denied
inventree@debian:/opt/inventree$ su
Password: 
root@debian:/opt/inventree# inventree run cli
/opt/inventree/vendor/pkgr/processes/cli: 2: exec: .: Permission denied
root@debian:/opt/inventree# inventree run cli backup
/opt/inventree/vendor/pkgr/processes/cli: 2: exec: .: Permission denied
root@debian:/opt/inventree# source ./env/bin/activate
(env) root@debian:/opt/inventree# inventree run cli
/opt/inventree/vendor/pkgr/processes/cli: 2: exec: .: Permission denied
(env) root@debian:/opt/inventree# inventree run cli backup
/opt/inventree/vendor/pkgr/processes/cli: 2: exec: .: Permission denied
(env) root@debian:/opt/inventree# 
```

and also
from **/etc/**
```
inventree@debian:/etc$ inventree run cli
/opt/inventree/vendor/pkgr/processes/cli: 2: exec: .: Permission denied
inventree@debian:/etc$ su
Password: 
root@debian:/etc# inventree run cli
/opt/inventree/vendor/pkgr/processes/cli: 2: exec: .: Permission denied
root@debian:/etc# inventree run cli backup
/opt/inventree/vendor/pkgr/processes/cli: 2: exec: .: Permission denied
```

each time, receiving the Permission Denied note. I did use the su command also.

Is there a different syntax to be used?

john

**Comment by imager2019** [comment]
@SchrodingersGat / @matmair 
Could you clarify where `inventree run cli` should be executed from? As you can see from the above note, I have tried a couple of places with the Permission Denied response.

Thanks..

**Comment by SchrodingersGat** [comment]
@imager2019 can you run it from a local directory where you have permissions (e.g. your home directory)? Sorry @matmair has way more knowledge about the installer than I do

**Comment by imager2019** [comment]
I have tried running it from the Home directory and several other locations. Tried running as SU as well, same result with `Permission denied`.
To clarify, I am using Debian 11, installed with with single-line installer, and trying to run using Terminal from the various directories.

I am open to any ideas and thoughts - if you need to spend extra time on this 1-to-1, let me know and I can make myself available as needed. Suspect that I would not be the only one experiencing this.

john

**Comment by SchrodingersGat** [comment]
@imager2019 it looks like this has been fixed in master in #5204 

So, I'm submitting a backport of this patch to stable, for next release.

**Comment by imager2019** [comment]
Excellent - that is good news. I will watch for the next release and give it a try.
Thanks..

**Comment by imager2019** [comment]
@SchrodingersGat - Do you know if the current release has the fixes applied? I am interested in giving a fresh install another try and just want to see if things should be patched now?

john

**Comment by SchrodingersGat** [comment]
@imager2019 I believe that the fixes have been applied - please report back :)

**Comment by SchrodingersGat** [comment]
@imager2019 this is the same issue as the other discussion
