### ISSUE TITLE
[P-UI] Static Image Files

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5337]
The InvenTree logo does not load correctly on platform UI on the demo site:

![image](https://github.com/inventree/InvenTree/assets/10080325/675c194b-f48e-40b4-90d8-39707291f213)

The source URL is incorrect:

![image](https://github.com/inventree/InvenTree/assets/10080325/171375c8-c1ee-46bb-b0ac-beaf200d9936)

It should be `/static/web/assets/...` (note the "/static/web/" prefix)

**Comment by SchrodingersGat** [comment]
Same behaviour when serving files locally (although it works as expected for the `yarn dev` server)

**Comment by matmair** [comment]
Interesting, I will have a look

**Comment by matmair** [comment]
A fix is incoming as part of #5344
