### ISSUE TITLE
When duplicating parts, BOM items of the same part get lost

### ISSUE THREAD

**Issue by JustusRijke** [inventree/InvenTree#5341]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Some assembly parts I use have multiple BOM items of the same part. E.g.,  1 meter of cable A to use for connecting X to Y, 2 meter of cable A to use for connecting Y to Z.

When duplicating such a part, only one of these items gets copied. The rest is lost.

### Steps to Reproduce

1. Create a new part with part attribute "Assembly" enabled.
1. Add a BOM item to the Bill of Materials. Any part will do. Add a note to the part, e.g., "Foo".
1. Repeat, but use a different text for the note, e.g., "Bar". The BOM now contains 2 items of the same part, as expected.
1. Duplicate the part. Now the issue becomes visible: the BOM only contains 1 item ("Foo").

### Expected behaviour

The BOM should be copied completely.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

Demo Server 0.13.0 dev

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@JustusRijke thanks for reporting - fix incoming in https://github.com/inventree/InvenTree/pull/5347
