### ISSUE TITLE
Move and count same time

### ISSUE THREAD

**Issue by Marbles87** [inventree/InvenTree#535]
Please provide a function to allow adjusting the stock count while moving location.

Image shows trying to adjust part count while moving. 

Note that it will not allow you to add parts while moving and it will leave excess parts behind if recounting to less then shown.

![Capture](https://user-images.githubusercontent.com/48982658/64937921-783a5800-d89f-11e9-98c8-db6f91b1682d.PNG)

**Comment by eeintech** [comment]
@Marbles87 I'm not understanding the problem you requesting a fix for, why would you'd like to move more parts than what the current stock is?

If you want to add stock, use the corresponding menu option:

![image](https://user-images.githubusercontent.com/4020546/96171065-02f9e600-0eea-11eb-838b-00eb97c090be.png)

Then move the stock accordingly.

Also, have you tried a newer version of InvenTree? Do you still have issue transferring stock between locations?

**Comment by SchrodingersGat** [comment]
This issue is pretty stale, happy for @Marbles87 to provide further input but I'll close it out for now.
