### ISSUE TITLE
[FR] SW Licence and BOM

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#5356]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Hi i could not find any other matching item.

In my products we sometimes require a SW lic to be solled along the product. hence i have added it to the BOM. this is not a stock item but we need to keep track of them and pay royalties at the end of each quarter. so it would be nice if we could keep track on the amount of licences sold.

is there any way to do this or could something like this be implemented

### Suggested solution

allow a part to be part of a bom and have no stock but still be able to sell the product. 
I have also been playing with purchase order. an thought of keeping the order open for a quarter and make partial deliveries or something but not sure if that would work.

### Describe alternatives you've considered

see above. made the part a consumable but i have no idea how i can track it per quarter or what ever other periode

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by mabroens** [comment]
as a note i have also played with the Virtual part, as i think this is what i am looking for.
![image](https://github.com/inventree/InvenTree/assets/130482028/aa822276-483b-4ae1-9e46-58e7da27c3c1)

but i could not close the order when using virtual parts. perhaps this type of item requires more eplanation in the docs??

**Comment by SchrodingersGat** [comment]
I don't think that the "no stock" is consistent with "keep track of number sold". It sounds like you need to keep stock, perhaps tracked based on serial number?

**Comment by matmair** [comment]
Tallying up usage after a certain period sounds more like the job of a plugin IMO. @mabroens would that be a solution or can you be more specific on what (usage flow, how the part type would act in certain situations) you would want to see implemented to close this FR?
