### ISSUE TITLE
Label printer plugins do not work without BLOCKING_PRINT = True

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#5367]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The Zebra label printer plugin did not work any more. The function print_label is not executed. I get an error message:

WARNING: '<function print_label at 0x7fe333c57400>' not started due to <class 'django.template.response.ContentNotRenderedError'>

The sample label printer plugin behaves the same. 
I had a look at the inventree source and found that adding BLOCKING_PRINT = True solves the problem. BLOCKING_PRINT = False results in the same error. 

### Steps to Reproduce

Activate the label printer plugin
Print a label
See error message in log

### Expected behaviour

Label should print

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

InvenTree Version 	[0.13.0 dev](https://github.com/inventree/InvenTree/releases)
Development Version
	Commit Hash	b89a120
	Commit Date	2023-07-28
	Commit Branch	master

Ubuntu 22.4 LTS

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 455
Saving setting 'InvenTreeSetting:LABEL_DPI' to cache
WARNING: '<function print_label at 0x7fe333c57400>' not started due to <class 'django.template.response.ContentNotRenderedError'>
[28/Jul/2023 19:55:58] "GET /api/label/part/3/print/?part=1425&plugin=zebra HTTP/1.1" 200 48
[28/Jul/2023 19:56:10] "GET /api/notifications/?read=false HTTP/1.1" 200 1173
```

**Comment by SchrodingersGat** [comment]
@SergeoLacruz thanks for reporting - fix in https://github.com/inventree/InvenTree/pull/5371
