### ISSUE TITLE
add on order to BOM overview

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#5369]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Hi Would it be possible to add the on order collumn to the BOM overview.

currently i us ethe BOM overview to determine what is missing to build a certain amount of PCBA's but currently it only shows what is in stock but it would be nice if we could also immidiatly see how many are in order, that way you know a) they are or are not yet ordered and B) yes i can build the desired amount once the parts are in.

### Suggested solution

as suggested add a column showing how amny are on order

### Describe alternatives you've considered

none

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
The BOM table currently does show the "on order" quantity - as a hover icon and not a separate column:

![image](https://github.com/inventree/InvenTree/assets/10080325/8d0851bb-8c18-4586-a0e3-4406be50dc96)

Have you seen this?

**Comment by mabroens** [comment]
Thx for pointing out and no i had not seen the popup. i was aware of the basket so i knew they where on order but not how many.

i think this could work. thx
