### ISSUE TITLE
[FR] Alert on allocation page that trackable items are allocated at build outputs steps

### ISSUE THREAD

**Issue by cpattersonic2** [inventree/InvenTree#5391]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Low priority (but hopefully easy) user interface request

It took us a while to dig up how to make the build orders with trackable (serialized) parts work. When we went to allocation parts page the trackable item was missing, and we had no idea why or how to get it to appear. We finally found it when we created the outputs of the build, then "surprise!" we got a cool new drop down. It makes sense this is the only way to order and attach trackable parts to trackable parts, but it was not obvious when this step would be done.

### Suggested solution

I would suggest a red text alert warning on the top of the parts allocation page when trackable parts are used saying "Trackable BOM items will be selected/assigned on the "Outputs" page.

### Describe alternatives you've considered

Any sort of hit to the user about when the trackable items will be assigned would work, really just a hint to where to look in the documentation would be good.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@cpattersonic2 makes sense from a user experience POV. Would you be willing to submit a PR for this?

**Comment by SchrodingersGat** [comment]
Not stale, but will wait for the new user interface
