### ISSUE TITLE
[FR] Naming / Labelling Stock Items

### ISSUE THREAD

**Issue by KeyCompTheater** [inventree/InvenTree#5392]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I'm having trouble distinguishing between stock items, even though it is very obvious in while I'm building the hardware, Inventree makes it kind of hard.

### Suggested solution

This all concerns working with serialised stock. Apart from the actual serial number, QR and barcode, I'd like to be able to name/label my stock items (e.g. my Main Mac, or Backup Mac) to distinguish them more easily e.g. while allocating stock items to a sales order or while installing other serialised stock items into an incomplete build output.

The labelling or naming would not be unique. It's not meant to be. But very often, I find my hardware being labeled for others to see what purpose it will serve in my larger system (e.g. a rack containing a main and a backup Mac - or a rack going to serve for a special department or purpose).

Instead of just showing "#123456" as the stock item name in tables and drop-downs, we'd be showing "MyLabelName (#123456)" if a label is set. If none is set, the rendering stays works same as it always has. Same goes for uncomplete build outputs. The creation wizard should contain a similar input field for the new label/name like the serial numbers input field.

### Describe alternatives you've considered

I can't think of any.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@KeyCompTheater you could use the "batch code" attribute for this purpose, no?

**Comment by KeyCompTheater** [comment]
@SchrodingersGat I gave it a try, but it really isn't doing what I want (apart from of course not being a batch code). The batch code is not taking into account when displaying the stock item anywhere. Also, when creating build outputs, it doesn't seem like accepting the comma separator to set different batch codes for the e.g. three stock items I'm creating like it works with the serial number.

**Comment by matmair** [comment]
This shouldn't pose problems regarding backwards compatibility if done right so why not. Happy to review a PR.

Here are a few pointers on a possible solution:
- new model field for name (I would give a long length to enable more complex situations), null- and blankable
- extend serializer with name - serialised number if no name is set, else name
- switch UI to use the new name field
