### ISSUE TITLE
issue with selecting location and show Rows bug?

### ISSUE THREAD

**Issue by Marbles87** [inventree/InvenTree#540]
While trying to select all parts that are located in the elab location only. I am provided with multiple parts in different sub locations from the elab location. 

It also reverts back to showing 25 items after asking to show 100 before the refresh. Is it possible to show all listings instead of 100 as max items?  with an option to lock it?

**Comment by SchrodingersGat** [comment]
See:
https://github.com/inventree/InvenTree/issues/544

https://github.com/inventree/InvenTree/issues/543
