### ISSUE TITLE
Plugin configuration values are limited to 200 chars, which is not enough for apprise

### ISSUE THREAD

**Issue by hvraven** [inventree/InvenTree#5400]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I ran into a problem while configuring inventree-apprise, where the required configuration field is not long enough (reported at the plugin here: https://github.com/matmair/inventree-apprise/issues/1). In short the MS Teams integration requires a long URI with several tokens which does not fit into the 200 chars limit of the configuration field.

### Steps to Reproduce

Add `inventree-apprise` and attempt to configure a MS Teams plugin by setting `NOTIFICATION_APPRISE_URL` using a URI longer than 200 chars. The value will be cut at 200 chars, rendering the config invalid.

### Expected behaviour

the string will fit into the config value

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.12.3 with inventree-apprise 1.0

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by wolflu05** [comment]
The following line would need to be changed to allow more than 200 chars. https://github.com/inventree/InvenTree/blob/54e0e47c6ae98ac920f4496e65b12b3551c89d93/InvenTree/common/models.py#L585
