### ISSUE TITLE
Feature request: find/add parts using the octopart api

### ISSUE THREAD

**Issue by Snevzor** [inventree/InvenTree#541]
Hi,

I found this neat project on the Kicad forum and tried it instantly.
What holds me back from using it in a medium sized company is the part entry stuff.
It is a lot of manual work (even with the batch import/edit) and errors can be made. Also the price information can be old.

Octopart has a nice API: https://octopart.com/api/home
Adding a part would be much easier as all the information (including prices from multiple distributors, a picture and possibly Kicad library parts) can be fetched automatically. I'm starting to dream now but perhaps email notifications can be sent when stocks at distributors get low for instance.

**Comment by SchrodingersGat** [comment]
Hey @Snevzor it's a great idea, but unfortunately the Octopart API terms of service do not allow caching of any downloaded data (i.e. you cannot store it in a database). I have actually reached out to the Octopart support and specifically asked about this.

I would love to know how to support this but not violate their TOS

**Comment by Snevzor** [comment]
Oh that's a pity. I've briefly searched for some alternative but none seem to live up to what Octopart has to offer.

**Comment by SchrodingersGat** [comment]
I think that the individual supplier APIs are worth looking at (e.g. Digikey / Mouser / etc) but this obviously would require a lot more work, and a careful analysis of the TOS of each API

**Comment by eeintech** [comment]
@Snevzor I have responded to your other issue: https://github.com/inventree/InvenTree/issues/566
I definitely think you should have a look at [Ki-nTree](https://github.com/sparkmicro/Ki-nTree/) :smile:

**Comment by SchrodingersGat** [comment]
@eeintech I've added Ki-nTree to the list of third-party InvenTree integrations!

Congrats, you've single-handedly doubled the length of the list 👍

**Comment by eeintech** [comment]
@SchrodingersGat Nice, thanks! Hopefully it lives up to the hype!

**Comment by eeintech** [comment]
OP is not active: @SchrodingersGat I think we should close this issue

**Comment by SchrodingersGat** [comment]
I will close it out for now. In the future I'd like to see such integrations, but it needs to be carefully considered.

**Comment by ndbroadbent** [comment]
If anyone else finds this comment - https://github.com/inventree/InvenTree/issues/541#issuecomment-677961649

Here's the new link for the third-party InvenTree integrations page in the docs: https://inventree.readthedocs.io/en/latest/extend/plugins/

**Comment by orzechow** [comment]
I came across this issue and wondered and realized that Octopart (and it's API) now belongs to Altium and is running as Nexar API.
Unfortunately, the [Terms of Use](https://nexar.com/api/legal) are still not allowing this use case 😞 

> 1. License Grant.
> [...]
> 1.2. Restrictions.
> [...] you shall not, and shall not permit others, including your Authorized Users to [...] 
> (v) self-host any content including but not limited to datasheets and images; 
> (vi) use the Nexar API to cache and/or store data for more than twenty-four (24) hours;

**Comment by eeintech** [comment]
@orzechow Not surprising, better stick with APIs from the suppliers themselves and avoid data aggregators, even if it's more work.
