### ISSUE TITLE
Purchase History Graph not displaying

### ISSUE THREAD

**Issue by Elitearcanist** [inventree/InvenTree#5418]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When viewing pricing for a given part the purchase history section's graph does not display the bars properly. All the other pricing graphs appear fine but all the purchase history graph stay blank. The labels for each record are made on the graph but the values are non-existent.
Here are 3 examples from the demo site:
![image](https://github.com/inventree/InvenTree/assets/41604209/58fa6ac5-664f-46b3-b24c-4c11e4ce1d63)
![image](https://github.com/inventree/InvenTree/assets/41604209/5e8a8c02-d059-404e-831a-6f71f507d914)
![image](https://github.com/inventree/InvenTree/assets/41604209/b58bcdf5-c8aa-4985-8bab-3de3404b9a79)

And one from the site I am working on
![image](https://github.com/inventree/InvenTree/assets/41604209/8ee6ea66-5092-465a-b823-81481fc454a5)

### Steps to Reproduce

1. Go to any part with purchase order history
2. Look at pricing
3. Purchase history appears blank

### Expected behaviour

I expect the graph to display properly. The bars should be non-zero and display past cost information

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.2
Django Version: 3.2.19
Commit Hash: 1d51b2a
Commit Date: 2023-07-25

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-4.18.0-477.10.1.el8_8.x86_64-x86_64-with-glibc2.36
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'AVL Demo', 'slug': 'companyavldemo', 'version': '0.1.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@Elitearcanist thanks for reporting :)
