### ISSUE TITLE
[FR] Part Attachments with "Class" or "Kind" property to categorize them

### ISSUE THREAD

**Issue by Petrox** [inventree/InvenTree#5429]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Manufacturing a part that is made of 100 other parts.
Each component could have it's own cut-out drawings for example.
Producing a list of files that has to be cut is tedious one-by-one.

### Suggested solution

In my use-case it would be very efficient to have the 100 subparts listed and after choosing "cutout" from a dropdown (that has elements made from the unique categories the parts have attachments) I could click download and maybe a zip file with files like:
"
PARTNUMBERXXX_cutout_5pcs.PDF
PARTNUMBERYYY_cutout_3pcs.PDF
"
so that it could be sent to the relevant personnel or supplier or manufacturer for lasercutting.

### Describe alternatives you've considered

We could use keywords in filenames and create a script that uses API or direct db access to pick the files required, but this feature might be useful for others too.

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/5429">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/5429/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/5429/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@Petrox this behaviour sounds quite bespoke, would be a good use-case for a [custom plugin](https://docs.inventree.org/en/latest/extend/plugins/)

**Comment by Petrox** [comment]
I agree this is not a musthave feature, but anyone doing manufacturing of multiple items with many subcomponents might need to group similar steps in technology together. (all 3dprinting all welding all cutting could be done in parallel on different machines, but each machine needs a well prepared batch).

This is a workaround to the fact that the stable version doesn't really support manufacturing plans, processes, so preparing food with a current stable release is limited to mixing all the components together in a bowl and there you have the part ready.

The proposal does not solve the lack of storing the technology documentation with the parts, but increases workflow 500% assuming the staff knows how to build the parts based on prepared plans and design files.

Nevertheless I accept your comment that this could be a plugin in the future. Feel free to close this if it is not of interest to the main project.

**Comment by SchrodingersGat** [comment]
We do have some plans (no timeline yet) for significant improvements to our MES capability: https://github.com/inventree/InvenTree/issues/4826

With regard to your suggestions / requirements here, I think that a plugin which collates all of these manufacturing files on the "Build Order" page would be reasonably straight-forward to implement. The particular file are uploaded against individual parts, and the build order pages collects these files as required, for each part needed to make the assembly

**Comment by matmair** [comment]
This sounds very specific and probably costly to maintain to me - should be a plugin.

**Comment by Petrox** [comment]
I've been thinking about this and the solution might be to use keywords
(tags).

1. Attachments could have tags as core feature. (All entities could have
tags)
2. A plugin could help tagging the attachments based on filenames and file
contents mabye. (Type:document or Type:cad are easy to add, even metadata
could be processed)

3. Download attachments having specific tags in a given mfg order could be
done by same plugin too.

 But I also accept if this is far down the road amd addresses a niche need.
Feel free to ignore.

 (Tagging everything and search by tag is a good core feature still.)

**Comment by matmair** [comment]
Looking into this again https://polar.sh/inventree/InvenTree/issues/5703
