### ISSUE TITLE
Database export to json issue

### ISSUE THREAD

**Issue by templeofhead** [inventree/InvenTree#5460]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hello. I've installed Inventree quite awhile ago, and its running fine (version is 0.11), but when i'm trying to export database into json using the command `invoke export-records -f data.json` it fails with output: 
```
Exporting database records to file '/opt/inventree/data.json'
CommandError: Unable to serialize database: no such table: build_build
```
My current setup is Ubuntu 22.04 with python 3.8, database is sqlite. I do understand that i'm most likely doing something wrong. Any help/advice would be much appreciated.

### Steps to Reproduce

cd /opt/inventree
source env/bin/activate
invoke export-records -f data.json

### Relevant log output

```bash
Exporting database records to file '/opt/inventree/data.json'
CommandError: Unable to serialize database: no such table: build_build
```

**Comment by SchrodingersGat** [comment]
@templeofhead have you recently performed any updates or changes to your system?

**Comment by templeofhead** [comment]
No, i haven't, system state is exactly the same as it was when i installed inventree, no updates.

**Comment by SchrodingersGat** [comment]
This may be a pathing issue, if you are using a file-system db (sqlite). Where is your database file actually stored?

**Comment by templeofhead** [comment]
Its in opt/inventree/data

**Comment by SchrodingersGat** [comment]
Do any of the other `invoke` commands run?

For example, what is the output of:

```
invoke migrate
```

**Comment by templeofhead** [comment]
Here's the output:
```
(env) ***@inventree:/opt/inventree$ sudo invoke migrate
[sudo] password for ***:
Running InvenTree database migrations...
========================================
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    import django  # noqa: F401
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```
Also, i get the same output if i try to export db outside of venv.

**Comment by SchrodingersGat** [comment]
Did you activate the correct venv before running `invoke migrate`? You should not see a "no module named django" error.

**Comment by templeofhead** [comment]
I go into /opt/inventree and use `source env/bin/activate`, is this correct?

**Comment by SchrodingersGat** [comment]
@matmair any thoughts on this? Is `/opt/inventree/env` the correct virtual environment location?

**Comment by matmair** [comment]
@SchrodingersGat theoretically yes. But for packaged installer you need some configs etc. in the environment - therefore the correct command is `inventree run cli` instead of `invoke`.

**Comment by SchrodingersGat** [comment]
@templeofhead please try again using `inventree run cli` instead of `invoke` (as detailed above by matmair)

**Comment by templeofhead** [comment]
No import issues were present, everything went smooth. Closing the issue, thanks for the assist :)
