### ISSUE TITLE
[FR] Using of trackable items in build

### ISSUE THREAD

**Issue by AlxrMironovOldAcc** [inventree/InvenTree#5463]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

We are a small company, who have end-to-end producing line of low-quantity devices. 
Device contains several PCBs and connecting items + HUD.
Device is high configurable by customer, so there are many variants of PCBs and complete assembly. 

We trying to track every board by serial number, complete assembly has its own serial number too. Before, the serials is assigned by hands and was tracked in *.xls and now with inventree. 

But there is a problem. You cant use trackable items in trackable item build in inventree. They are displayed as avaliable, but not listed in allocation.

This behaviour is reproducable in DEMO, so IDK if it's a bug or a missing feature, because i understand that implementation of this feature may consume significant amount of time.

Steps to reproduce:
1) Create a template item "Mainboard"
2) Create a variant of "Mainboard" with name "Mainboard Rev:A"
3) Make "Mainboard Rev:A" trackable
4) Add stock item for "Mainboard Rev:A" with any serial
5) Create a variant of "Mainboard" with name "Mainboard Rev:A"
6) Add stock item for "Mainboard Rev:B" without serial (cause it is not trackable)
7) Create item "Device"
8) Make "Device" buildable
8) Make "Device" trackable
9) Add BOM to "Device" with "Mainboard" template.
10) Create build order for "Device"
11) Try to allocate "Mainboard Rev:A" for build order. You not able to do it, only "Mainboard Rev:B". If you remove all stock from "Mainboard Rev:B" - you cant allocate any "Mainboard" item to "Device"

### Suggested solution

Trackable items is allocatable in trackable and buildable items.

Buildable item contains additional submenu with table what contains links to trackable stock items, what used in build.

Trackable stock item, what used in build, contains link to trackable buildable item stock. 

### Describe alternatives you've considered

Sorry, i dont know. 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Please read https://github.com/inventree/InvenTree/issues/5391 https://github.com/inventree/InvenTree/issues/3915

**Comment by AlxrMironovOldAcc** [comment]
I have found some inconsistence, template item must be trackable for trackable allocation. If variants is trackable and template is not - part is displayed at "default" allocation list. So you cant allocate it. (cause all stock is trackable and not allowed for "default" allocation.)

Idk is it a minor bug or planned behaviour, just reporting.

**Comment by AlxrMironovOldAcc** [comment]
I have found some inconsistence, template item must be trackable for trackable allocation. If variants is trackable and template is not - part is displayed at "default" allocation list. So you cant allocate it. (cause all stock is trackable and not allowed for "default" allocation.)

**Comment by matmair** [comment]
Yes, that is planned behaviour. All functional restrictions that you want to use need to be active in the template part.
