### ISSUE TITLE
Show transaction history for user

### ISSUE THREAD

**Issue by Marbles87** [inventree/InvenTree#547]
Add a page that displays all the historical actions performed by the current user (or for any user).

- Stock transaction history
- Part history
- etc etc

**Comment by eeintech** [comment]
@Marbles87 This is an interesting idea, it would take some consideration to implement... Maybe the [django-simple-history](https://github.com/jazzband/django-simple-history) library could help? What do you think @SchrodingersGat, should we take a crack at it?

**Comment by SchrodingersGat** [comment]
django-simple-history looks like a good candidate for this feature. We would need to consider what models need history tracked, and how exactly that works for complex data operations.

For example, when a build is completed and subsequently new stock items are created, this is a multi-faceted step that might not be able to be "tracked" with such a simple approach?

I'm not sure. Research needed!

**Comment by eeintech** [comment]
Sounds good, not sure either. I find it very compelling (transparency is dear to me) so I may give it a shot soon and report!

**Comment by eeintech** [comment]
@SchrodingersGat 

> For example, when a build is completed and subsequently new stock items are created, this is a multi-faceted step that might not be able to be "tracked" with such a simple approach?

In that case, the historical table would need to be enabled for stock items. If each stock item has a link to the build they originated from, there can be tracked against that build.

**Comment by eeintech** [comment]
Related to #537 #377

**Comment by matmair** [comment]
@SchrodingersGat is this still on the roadmap or `wontfix`?

**Comment by SchrodingersGat** [comment]
I think the scope requirements for this are pretty prohibitive, and it hasn't received much user attention.
