### ISSUE TITLE
error in the URL of `Confirm Your E-mail Address` E-Mail

### ISSUE THREAD

**Issue by ChristianSchindler** [inventree/InvenTree#5470]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

With the newest Stabel docker version 0.12.6 the email has the following format:
```
Hello from Test InvenTree!

You're receiving this e-mail because user Test has given your e-mail address to register an account on https://inventory.test.de/.

To confirm this is correct, go to https://inventory.test.de/https://inventory.test.de/api/auth/registration/account-confirm-email/Mw:1qYvtS:BSko65HFRUGoIuobm49V54t8s_hpwWTlOArebc94SA4/

Thank you for using Test InvenTree!
https://inventory.test.de/
```
The only changes are the URL and name.
The problem is the duplication of  https://inventory.test.de/ in the verification URL. 
This was not the case with 0.12.3 (prior docker version)
likely related to #5333 (this is fixed)

### Steps to Reproduce

1. Install the version 0.12.6 in docker
2. setup email
3. send verification email

### Expected behaviour

```
Hello from Test InvenTree!

You're receiving this e-mail because user Test has given your e-mail address to register an account on https://inventory.test.de/.

To confirm this is correct, go to https://inventory.test.de/api/auth/registration/account-confirm-email/Mw:1qYvtS:BSko65HFRUGoIuobm49V54t8s_hpwWTlOArebc94SA4/

Thank you for using Test InvenTree!
https://inventory.test.de/
```

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

image: docker.io/inventree/inventree:0.12.6

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@ChristianSchindler thanks for reporting - fix incoming in https://github.com/inventree/InvenTree/pull/5472
