### ISSUE TITLE
[FR] Support creating reading initial superuser account password from file

### ISSUE THREAD

**Issue by Gigahawk** [inventree/InvenTree#5471]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I am running the docker-compose project on [NixOS](https://nixos.org/) through [Arion](https://docs.hercules-ci.com/arion/).

I am managing all of my secrets/passwords through [agenix](https://github.com/ryantm/agenix), which writes files containing the decrypted passwords to a specific path on the system (with appropriate permissions).
Due to the way Nix works, it is not safe to read the password file directly into the Arion config (Arion will generate a docker-compose.yaml file which will be readable to all users).

Instead, the recommended way for applications to ingest secrets is for them to be read at runtime.

### Suggested solution

I would like an option like `INVENTREE_ADMIN_PASSWORD_FILE` to be added to `add_user_on_startup()` which will read the contents of a file containing the password (mapped as a volume in the generated docker-compose.yaml)

### Describe alternatives you've considered

I could of course just forgo this feature and set up the superuser account manually, but part of the appeal of NixOS is the ability to bootstrap and configure the entire system with just a few commands

### Examples of other systems

From the [agenix readme](https://github.com/ryantm/agenix/blob/91220a701d0bf8055547620baa765b36d885db7a/README.md), shows the suggested way to access the secret (in this case defining linux user accounts)
```
{
  users.users.user1 = {
    isNormalUser = true;
    passwordFile = config.age.secrets.secret1.path;
  };
}
```

Instead of directly accessing a file, some NixOS modules instead take a generic shell command which prints the password to stdout, which gets run at the programs runtime:
```
  programs.msmtp = {
    enable = true;
    accounts.default = {
      auth = true;
      tls = true;
      tls_starttls = true;
      tls_trust_file = "/etc/ssl/certs/ca-bundle.crt";
      tls_certcheck = true;
      host = "smtp.office365.com";
      port = 587;
      from = "asdf@outlook.com";
      user = "asdf@outlook.com";
      passwordeval = "cat ${config.age.secrets.alert-outlook.path}";
    };
  };
```

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@Gigahawk can you not set this up as an environment variable?

**Comment by matmair** [comment]
Sounds interesting. I think you already found the correct part of the code - ping us if you need help implementing it.

From experience there can be some issues with reading from secrets files - please make sure that it fails gracefully and logs (not using print but longer.error so that all the logging drivers work).

**Comment by matmair** [comment]
@Gigahawk you selected that you want to develop this - schools I assign you?

**Comment by Gigahawk** [comment]
@matmair  yea thats fine

**Comment by matmair** [comment]
@Gigahawk still interested? Would be great to support NixOS better

**Comment by matmair** [comment]
I had some discussions with users and they pressed that this is blocking for real world usage of inventree with nixos; I will implement the suggestion by @Gigahawk in the next few days
