### ISSUE TITLE
Issue with Allocated parts counter

### ISSUE THREAD

**Issue by templeofhead** [inventree/InvenTree#5477]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hello. Recently i've updated my inventree packaged install from 0.11 to 0.12.3 and when i was done with the update, i went to check if everything was present and found an interesting thing: in the build order tab, when i open\create new build order, the spinner after allocated parts keeps spinning indefinitely instead of showing how many of the parts total isnt allocated.
It was working on 0.11 alright, but not on the newer version.

Same behaviour was present when i exported database and imported it on the fresh vm, same is as with updating current installation. Screenshot is below, for reference.
![spinner](https://github.com/inventree/InvenTree/assets/142637610/46c1b584-48ff-4196-84de-340937d229a8)

### Steps to Reproduce

1. Either update from older version or export database and import into the new one.
2. Open "build order" tab, navigate to "build order details"
3. In the details submenu, the loading spinner that indicates the amount of allocated parts keeps spinning as if loading of parts amount is in the loop.

### Expected behaviour

After brief loading (amount of allocatable parts arent that big) the counter should display the actual amount (from 0 to 20)

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.3
Django Version: 3.2.19
Commit Hash: 1f3a49b1
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by wolflu05** [comment]
Have you checked https://docs.inventree.org/en/latest/faq/?h=work#feature-x-does-not-work-after-update

**Comment by templeofhead** [comment]
Yeah, i did hard refresh, multiple browsers as well - didn't work.

**Comment by wolflu05** [comment]
Have you also checked the browser console if there is any log or errors? Also the network tab?

**Comment by SchrodingersGat** [comment]
@templeofhead I think that this is a bug due to the way that the required data is loaded. This might not get addressed before our move to react (see https://github.com/inventree/InvenTree/issues/5212)

**Comment by templeofhead** [comment]
If its just some script bug and not the db problem, and it wouldnt impede anything on the long run (at least until you alleviate it in future versions) think i can be considered a minor inconvenience.
