### ISSUE TITLE
Trackable stock item value displayed as "BOM price range" instead of real price.

### ISSUE THREAD

**Issue by AlxrMironovOldAcc** [inventree/InvenTree#5481]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

If you build trackable item with BOM what include optional items or items with "price range", the result trackable stock item would have "price range" what equals BOM price range, instead "true" build cost. 

So you really have no way to get know real cost, only manual calculation. 
PS: as micro [FR] its been cool to see build cost in trackable stock item page, currently only the "purchase" cost is presented. 

### Steps to Reproduce

1. Create BOM for trackable item, with sub-items what have price range
2. Add optional sub-item
3. Build trackable item without optional sub-item

### Expected behaviour

True cost (consumed stock cost + installed optional items cost) will display in Part->Stock->Trackable item line->Stock value cell.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.3
Django Version: 3.2.19
Commit Hash: 1f3a49b1
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/5481">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/5481/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/5481/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@AlxrMironovOldAcc so you are expecting that the true "cost to build" of the output would be the sum of costs of all inputs, right?

This is not something that currently takes place - build output costs are not actually calculated. So, this would be a great addition.

Would you be willing to contribute towards or sponsor such a feature?

**Comment by AlxrMironovOldAcc** [comment]
I think it is not right for me as a hirable personel to sponsor this. But i think, i can try to contribute later, im not a python developer so this can take some time.

**Comment by SchrodingersGat** [comment]
Not stale, this would be a good feature to have

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by SchrodingersGat** [comment]
Extending the "real cost" tracking of a stock item would be a good improvement. Adding the "fund" tag to this issue, so hopefully it can receive some attention from users who may want to sponsor it.

**Comment by alxrMironov** [comment]
@SchrodingersGat ok, maybe im try to ask headquaters about funding. The question - how much?

**Comment by SchrodingersGat** [comment]
To implement this properly will require some significant work - I would estimate 10 to 15 hours minimum. If you are looking to fund the entire issue, that's great, but the more funds contributed towards it, the greater attention it can receive!

**Comment by SchrodingersGat** [comment]
@alxrMironov please reach out to me at `support@inventree.org` if you want to discuss further :)
