### ISSUE TITLE
Build order AND Purchase Order

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#5482]
### Body of the issue

Hi team,

i need some guidence.

We use Inventree to keep track of stock for both parts and finisched products. this means all bom items that we deliver for manufacturing to our assemblyhouse are tracked using inventree and once the assembled PCBA's come back we close the order and add them including their serialnumbers (in our case MAC adresses) to the stock.

but what is the best way to do this. currently i create a Purchase order for 125 PCBA's and create a Build order for 125 pcs(to keep track of our parts count). once they come in i have now closed both order but now i our stock was not incremented by 125 but with 250 (125 for PO and 125 for BO) actually thats obvious but did not think about this :-(

![image](https://github.com/inventree/InvenTree/assets/130482028/3ab14b93-68b5-434c-a480-43c9bab47f2a)

Question how can i now best lower stock with 125 pcs. i guess i need to do a stock take on the first 4 rows. or is there a better way to get this resolved??

I know ther have been question on linking Build and purchase orders what is the status on this i guess that would have solved this issue??

Br Martijn

**Comment by matmair** [comment]
This sounds like an internal workflow/consultation problem, not a bug.

**Comment by SchrodingersGat** [comment]
@mabroens it does sound like this issue would be functionally "solved" by https://github.com/inventree/InvenTree/issues/1071 - but not much progress on that as yet. There are some interesting ideas in that thread regarding how others have approached this "double handling" issue.

In terms of consolidating the stock you have on hand currently - you could simply perform a stocktake to reduce or remove the extra / duplicate stock items.

**Comment by mabroens** [comment]
@SchrodingersGat yes agree. lets close this one.
