### ISSUE TITLE
Edit Password for Admin user

### ISSUE THREAD

**Issue by 70A5** [inventree/InvenTree#5484]
How do I change the password for the admin user? I edited the environment variables. But no luck.

**Comment by matmair** [comment]
You can not change the password of an already existing (admin) user with env variables. This can be done from the admin page (/admin) -> Users -> {username} -> Change password and save. You need a valid admin login for this to work.

Also please either use the templates when opening issues or post in discussions for questions.

**Comment by 70A5** [comment]
Ok, how do I get to the location to change the password? I can't seem to get into the system at all. The docs say that the admin has a generated password that can be found somewhere. I changed that password on that location but no luck.

**Comment by matmair** [comment]
We can't help you with the provided information. We need to know which version you have, how you installed it, what OS you have etc.
Could you please link where it says in the official docs that the admin has a generated password? This is not a stock feature of InvenTree and might be part of a third-party distribution.

**Comment by 70A5** [comment]
Thanks for the quick replies, the installation method I used is the barebones one. Here's the link to the [docs](https://docs.inventree.org/en/latest/start/installer/#external-calls).

**Admin User**

By default, an admin user is automatically generated with username admin, mail admin@example.com and a dynamic password that is saved to /etc/inventree/admin_password. These values can be customised with the environment variables INVENTREE_ADMIN_USER, INVENTREE_ADMIN_EMAIL and INVENTREE_ADMIN_PASSWORD. To stop the automatic generation of an admin user, generate an empty file needs to be placed at /etc/inventree/admin_password.

**Comment by 70A5** [comment]
@matmair Have you seen my reply yet? I'm not getting any progress.

**Comment by 70A5** [comment]
This problem is still active

**Comment by SchrodingersGat** [comment]
@70A5 you can set new passwords via the Django admin interface - https://docs.inventree.org/en/stable/settings/admin/
