### ISSUE TITLE
Partcategory TSV Import slow or crashes causing NGINX 504 Gateway timeout response

### ISSUE THREAD

**Issue by Petrox** [inventree/InvenTree#5490]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When uploading some 1700 rows into Partcategory from TSV (sampe file contains a duplicate category name under the same parent, so one error should appear)

![image](https://github.com/inventree/InvenTree/assets/3036509/7d131ae0-6e68-4a32-bb2a-e90d8b26fa7a)

### Steps to Reproduce

Admin -> Partcategory -> Import -> Select file -> Format TSV -> Submit

### Expected behaviour

Since the sampe file has two lines (id 1046 and 1316) with duplicate name under same parent, there should be two error messages, but otherwise the full list should appear and wait for a confirmation.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.12.6 

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by Petrox** [comment]
Example file:

https://gist.githubusercontent.com/Petrox/8ee7f254f51fc71bb03bed9a3e44dec6/raw/319d52380cea01116a77ef11cdcfd01ac61de52d/inventreehungarianpartcategories.tsv

**Comment by SchrodingersGat** [comment]
@Petrox this is one of the known issues with the current importer process. We are working on a complete overhaul here to provide a much more efficient importing process which does not cause the front-end worker / nginx to timeout.

You can see an overview here: https://github.com/inventree/InvenTree/pull/5125

Until that refactor is completed, large import files may continue to cause this issue

**Comment by Petrox** [comment]
Ok, not fatal, I just sorted it an split in 4 pieces in the end.
