### ISSUE TITLE
Updating Inventree by following documentation yields error "No idea what '--no-frontend' is!" when invoking database update

### ISSUE THREAD

**Issue by standekker** [inventree/InvenTree#5492]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When updating our Inventree to the latest version (I do not know which version we had before, IIRC we were running on something like 0.12.2) I followed the documentation for a docker installation update [as per documentation](https://docs.inventree.org/en/latest/start/docker_prod/#updating-inventree).

When I arrived at the "Update Database" section, I ran the following command as stated in the documentation:

`docker compose run inventree-server invoke update --no-frontend`

But this yields the following error:
```
Loading config file : /home/inventree/data/config.yaml
No idea what '--no-frontend' is!
```

And then quits. I then tried to re-run the command without the `--no-frontend` flag and that seems to work fine.

### Steps to Reproduce

I have not been able yet to verify if there are steps to reproduce it reliably.

### Expected behaviour

Database update.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

System was probably on 0.12.2 before and I was updating it to 0.12.6.

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@standekker looks like you are installing the stable version but running from the "latest" docs. 

Try this instead and LMK how you go: https://docs.inventree.org/en/stable/start/docker_prod/#update-images

**Comment by standekker** [comment]
Ah yes my bad, that works!

I don't know how I ended up on the latest version documentation instead of the stable version. Thanks!

**Comment by standekker** [comment]
Closing.
