### ISSUE TITLE
Single line install script installs old version (0.12.3)

### ISSUE THREAD

**Issue by timmyhadwen** [inventree/InvenTree#5499]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi All,

I have installed Inventree this week but have noticed that the install script (and thus the apt repository) both point to 0.12.3. Im wondering if this is intended or if this has been missed in the latest releases.

Otherwise everything is great, really enjoying it and looking forward to getting into the API to integrate with our other processes. Great work guys!

Cheers
Tim

### Steps to Reproduce

1. Install via single line installer
2. Notice version is 0.12.3 and UI says update available
3. Attempt to update via Apt
4. Cry

### Expected behaviour

Expect the latest stable via Apt

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

0.12.3

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@timmyhadwen sorry for the delay, @matmair is the go-to on the installer and he's currently away. Have you had any further luck with this?

**Comment by matmair** [comment]
@timmyhadwen the latest available version of the stable package is 0.12.3 currently

**Comment by matmair** [comment]
Our stable CI seems to be breaking; I need to investigate that

**Comment by SchrodingersGat** [comment]
Something happened with our docker builds too - 0.12.4 is missing from docker hub.

@matmair do you know if the packager is up and running again?

**Comment by matmair** [comment]
@SchrodingersGat it did not trigger, I had to do it by hand - 0.12.7 is released now.

**Comment by matmair** [comment]
Should work now again

**Comment by timmyhadwen** [comment]
Thanks heaps :) Working great now!
