### ISSUE TITLE
Adding exchange rates

### ISSUE THREAD

**Issue by Abitkun** [inventree/InvenTree#5507]
### Body of the issue

Hello everyone, I would like to raise a concern regarding the addition of exchange rates. For example, I'm trying to add PH currency in my Inventree but whenever we update the currency, it is suddenly gone. I hope this will be resolved as soon as possible thanks! Godbless

**Comment by SchrodingersGat** [comment]
@Abitkun 

> or example, I'm trying to add PH currency in my Inventree but whenever we update the currency, it is suddenly gone. 

- How are you "adding" the currency in?
- Please expand on what you mean by "gone"

**Comment by Abitkun** [comment]
@SchrodingersGat 

Hello! Actually, my colleague tried to change one of the default currencies, and when we tried to update the currency it went back to where it was.

**Comment by SchrodingersGat** [comment]
> Actually, my colleague tried to change one of the default currencies, and when we tried to update the currency it went back to where it was.

Sorry, there is not sufficient information here for me to work with. Please provide the exact sequence of steps you are following, and what you are seeing.

**Comment by Abitkun** [comment]
@SchrodingersGat is there a way to add currency in Inventree?

![image](https://github.com/inventree/InvenTree/assets/144098256/f94435b7-43ba-4004-9221-9b853d889674)

**Comment by SchrodingersGat** [comment]
Yes, supported currencies must be added in the configuration file:

https://docs.inventree.org/en/stable/start/config/#supported-currencies
