### ISSUE TITLE
Parts Parameter Units

### ISSUE THREAD

**Issue by Abitkun** [inventree/InvenTree#5508]
### Body of the issue

Hello everyone, Can someone tell me what's the reason why units from parameters when we create one, there's an error "Invalid Physical Units" like Can we input any words we want there? Thanks!

**Comment by SchrodingersGat** [comment]
- https://docs.inventree.org/en/latest/concepts/units/
- https://docs.inventree.org/en/latest/part/parameter/#parameter-units

What version of InvenTree are you using? The "physical units" support has been recently added and there have been some tweaks around it

**Comment by Abitkun** [comment]
![image](https://github.com/inventree/InvenTree/assets/144098256/7c53ad54-9f47-4acf-b960-90f5869f9b9d)

Hello @SchrodingersGat, here you go. Thanks for replying!

**Comment by SchrodingersGat** [comment]
@Abitkun ok thanks - in that case can you show me what units you are trying to create, and the error message you receive?

**Comment by Abitkun** [comment]
![image](https://github.com/inventree/InvenTree/assets/144098256/e1f219ce-4bde-4eea-8621-81a190c4d009)

@SchrodingersGat Thanks man. Please see image. Also, I can't find Physical Units tab in the settings panel.

**Comment by SchrodingersGat** [comment]
Right, this is a limitation of the current stable version (0.12.x) - you cannot add in custom units which are not "valid" (real SI units).

Upcoming 0.13.x will (has) solved this. When this releases you'll be able to add custom units and also units which are not "valid". Until then, you'll have to leave that field empty

**Comment by Abitkun** [comment]
@SchrodingersGat I see, thank you so much! Looking forward to the new version.

**Comment by SchrodingersGat** [comment]
@Abitkun we are hoping to release *soon* - there are a few major PRs still outstanding :)
