### ISSUE TITLE
Receiving order and allocating line items 

### ISSUE THREAD

**Issue by Marbles87** [inventree/InvenTree#551]
When Receiving orders please add following feature in the purchase order feature page.

- Add an options to allocate different items to different locations.
- Add a field/column to show what the component was ordered for and where to place it.
- Be able to back track the Po to find where parts were sent in case of misplacement and back orders

Is it possible to have some type of filter system to to be able to set item locations easier?

Not sure how to word this buuuuttt!

If ordering items for multiple parts. Have it referenced showing what item it was ordered for. so for the person closing the Purchase order in InvenTree knows where to place them.

![Capture4](https://user-images.githubusercontent.com/48982658/65402520-403c9300-de12-11e9-9150-ff41596cd12a.PNG)

**Comment by Marbles87** [comment]
please provide a new status in the "purchase order details" to allow a new status from pending to received then to "Allocation"? to provide a stop gap to allow a palm from one person to another. When item is received the purchase officer can then check for all line items then pass on packages to intended rooms where they can then be further allocated to final destination (BINS, build kits).

![Capture5](https://user-images.githubusercontent.com/48982658/65573935-5cc20200-dfaf-11e9-8e39-7addd8820ab4.jpg)

**Comment by eeintech** [comment]
@SchrodingersGat What are your general thoughts for entering parts from purchase orders?
I think what @Marbles87 hinted at sounds like a fair request, just wondering what you think.

**Comment by SchrodingersGat** [comment]
An "Intended location" column would certainly be a handy addition - and could default to the "default location" for the particular part.

I've opened a new issue for adding the ability to track down stock items received against a certain purchase order

**Comment by eeintech** [comment]
Looks like you were quick to jump on this, nice. Should we close this issue then?

**Comment by SchrodingersGat** [comment]
I think leave open until we have implemented a "receive location" for a purchase order line item. I have a few ideas how to implement this, might be able to look at it today.

**Comment by Kedarius** [comment]
What is the status on this? I was wondering if it would be possible to assign parts from a purchase order to a location. Just simple select items and click set to different location...

**Comment by SchrodingersGat** [comment]
@Kedarius no further development on this one yet...
