### ISSUE TITLE
Upload BOM with few lines with same Part ID cause lost of all, except one.

### ISSUE THREAD

**Issue by AlxrMironovOldAcc** [inventree/InvenTree#5510]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

BOM allow to have few lines with same Part (Pard ID) but different Ref\Notes and quantity.

When importing from file, seems only first string will be uploaded, all another will denied. 

### Steps to Reproduce

1. Create file with two lines with same Part ID
2. Import it as BOM

### Expected behaviour

Two lines presented in BOM after import.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.3
Django Version: 3.2.19
Commit Hash: 1f3a49b1
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
Can reproduce, should be addressed in #3101

**Comment by SchrodingersGat** [comment]
@AlxrMironovOldAcc can you share a simple file which reproduces this? Please ensure that any IP or PII data is removed.

**Comment by alxrMironov** [comment]
> Can reproduce, should be addressed in #3101

I cant reproduce it in demo (seems 13.0 fixed?), but i still well reproduce it on my own server.

**Comment by SchrodingersGat** [comment]
Are you still running `0.12.3`?

**Comment by alxrMironov** [comment]
> Are you still running `0.12.3`?

We switched with pain from 12.1 to 12.7 =) I reproduce it on 12.7
If you needed for diag, i can give you a privileged account.

**Comment by SchrodingersGat** [comment]
Looks like this has already been "fixed" in https://github.com/inventree/InvenTree/pull/5698

As this is not strictly a "bug" it will be available in the upcoming `0.13.0` release (within the next month)
