### ISSUE TITLE
[FR] Automatically print label when creating stock item

### ISSUE THREAD

**Issue by murray484** [inventree/InvenTree#5514]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Often I am adding parts / stock items to my inventory in bulk.  It takes several steps to create a stock item, navigate to it's page, select the label / printer, print the label, and then go back to the item creation screen for the next item.

### Suggested solution

Add an option to the create modal to print the label automatically to the default printer.  Perhaps we could also add a default label field to simplify this.

I imagine it could look something like this (using stock items as an example):
![image](https://github.com/inventree/InvenTree/assets/6455740/dd2fce3c-0e80-4e86-a70a-9f504da38ed7)

### Describe alternatives you've considered

Suck it up and do it manually :)

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@murray484 this would be a good use-case for a plugin. Register for the  "stockitem.created" event, and print the label. I would rather not push this into general functionality
