### ISSUE TITLE
Installation via Docker behind reverseproxy

### ISSUE THREAD

**Issue by liszca** [inventree/InvenTree#5533]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

First, I think it is not a bug but me doing something wrong.

When using Inventree as Admin everything is fine.

Adding a user with only view permissions sometimes gives "Permission Denied" after hammering F5 in the Browser it works.

When I setup Inventree I didn't manage to get it to work on port 80. But with another external Reverseproxy to port 1337 it is working so I am not using port 80. Withing the ".env" file I could switch it away from port 80?

### Steps to Reproduce

0. Open https://service.example.com/index/
1. Page shows incomplete see screenshot:
![image](https://github.com/inventree/InvenTree/assets/32976532/33ee6f99-8d19-4091-bdf5-e5c8910ae312)
2. After hitting F5 like crazy things can look different:
![image](https://github.com/inventree/InvenTree/assets/32976532/3f810d76-9f2c-4a78-9e6b-fa927edf1b8e)

### Relevant log output

```bash
how to collect logs?
```

**Comment by SchrodingersGat** [comment]
Can you explain a bit more how you have your reverse proxy setup?

**Comment by liszca** [comment]
Infront of the nginx provided in the docker-compose file is another nginx (LXC-Container) as a reverseproxy with TLS.

Its configuration looks as follows:
```
  location / {
    proxy_pass http://192.168.178.193:1337;
    #proxy_pass http://192.168.178.193:80;
    proxy_set_header    Host              $http_host;
    proxy_set_header    X-Forwarded-Proto $scheme;
    proxy_set_header    X-Real-IP         $remote_addr;
    proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header    X-Original-URI    $request_uri;
    proxy_set_header    Upgrade           $http_upgrade;
    proxy_hide_header   Upgrade;
  }
```

**Comment by liszca** [comment]
Infront of the nginx provided in the docker-compose file is another nginx (LXC-Container) as a reverseproxy with TLS.

Its configuration looks as follows:
```
  location / {
    proxy_pass http://192.168.178.193:1337;
    #proxy_pass http://192.168.178.193:80;
    proxy_set_header    Host              $http_host;
    proxy_set_header    X-Forwarded-Proto $scheme;
    proxy_set_header    X-Real-IP         $remote_addr;
    proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header    X-Original-URI    $request_uri;
    proxy_set_header    Upgrade           $http_upgrade;
    proxy_hide_header   Upgrade;
  }
```

**Comment by liszca** [comment]
not clear what caused the Problem on my side, but I am sure it is NOT an application problem.

**Comment by SchrodingersGat** [comment]
sysadmin is always tricky :)
