### ISSUE TITLE
Pricing of splitted stockitem incorrect.

### ISSUE THREAD

**Issue by HannesMorre** [inventree/InvenTree#5540]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

It appears that when a stock item is split from the parent item, the purchase price is set to 0. Because of this, the purchase pricing history of the associated part (part Y) has a range from 0 to X. This results in bom pricing of parts which include part Y to be inaccurate.

### Steps to Reproduce

1. Create a purchase order of a specific part X with a price.
2. Receive the stock item Z of this purchase order.
3. Create another part Y which is an assembly and include part X.
4. Create a build order of part Y that uses less then the full quantity of stock item Z.
5. Complete the build order.

Now you will see that a new stock item A is created by splitting it from stock item Z. Stock item A will now have a purchase price of 0 instead of the original purchase pricing.

### Expected behaviour

The purchase price of splitted stock items should be either empty or the same as the parent stock item, but not 0. Otherwise this pricing breaks bom pricing of other parts.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.12.1

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@HannesMorre I have not been able to reproduce this. Can you replicate this on the demo server? Or potentially make a screen recording running through the required steps?

**Comment by HannesMorre** [comment]
I found out what was wrong. Apparently the parent stock item also had an incorrect purchase price of 0.
My bad.
