### ISSUE TITLE
Changing part BOM does not cause "Build order BOM" to change.

### ISSUE THREAD

**Issue by AlxrMironovOldAcc** [inventree/InvenTree#5541]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

If you changing BOM it is not changing in active build orders, you need to cancel build order and create new one. 

### Steps to Reproduce

1. Create a part with BOM
2. Create a build order
3. Change part BOM

### Expected behaviour

Build orders BOM is same as parts BOM.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.3
Django Version: 3.2.19
Commit Hash: 1f3a49b1
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@AlxrMironovOldAcc fix incoming in https://github.com/inventree/InvenTree/pull/5542
