### ISSUE TITLE
When adding a part from the supplier part's page to an invoice, it doesn't set a unit  price in the invoice

### ISSUE THREAD

**Issue by lazyarse** [inventree/InvenTree#5548]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

This is on the demo server at demo.inventree.org

In Supplier / A part # / Supplier Part Orders / Order Part.

When clicking Order Part and setting the part and quantity, no price is transferred across to the purchase order, unlike a manual add line item that does set an initial price

### Steps to Reproduce

see above

### Expected behaviour

The unit price should be calculated dependent on quantity and available price breaks.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

0.13.0 dev

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@lazyarse thanks for reporting this. There are a few little "quality of life" things here which could be implemented better in the frontend. Please note that we are currently working to [refactor the entire frontend in react](https://github.com/inventree/InvenTree/issues/5212) - so this might be better addressed once that is done, as the frontend capabilities will be much improved.

**Comment by lazyarse** [comment]
Thanks, I'm new to inventree and have found it to be the closest to what I want!
