### ISSUE TITLE
[FR] Generate UUID barcodes on part / location create

### ISSUE THREAD

**Issue by lazyarse** [inventree/InvenTree#5549]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When creating a location or part, it'd be nice to have an internal barcode generated. This could be serial, serial with a pattern e.g. P[0-9]{6,6}, UUID, etc (settings to choose the type / format would be nice).

I know you can 'link' a barcode to a location, but that means the user has to think of a barcode value, instead of one just being created and if you're creating locations, existing barcodes don't always exist.

Related to #2058

### Suggested solution

Add the ability on the create form for locations and parts to have a barcode which will allow searching on. Add settings to define barcode type for parts, for locations, and whatever other entities. I think the existing barcode actions should have an 'add barcode' option as well incase the user wishes to add one at a later date.

### Describe alternatives you've considered

None

### Examples of other systems

I'm pretty sure odoo auto creates barcodes for most items that are generated, including PO/SOs.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@lazyarse InvenTree already supports [native barcodes](https://docs.inventree.org/en/stable/barcodes/internal/) which sounds like exactly what you are looking for. Many people already use this, in conjunction with the mobile app.

Additionally you can assign an [external barcode](https://docs.inventree.org/en/stable/barcodes/external/) to an item, location, etc

Further, we support [custom barcode functionality](https://docs.inventree.org/en/stable/barcodes/custom/) via plugins.
