### ISSUE TITLE
[FR] Let user define date for received order items

### ISSUE THREAD

**Issue by lippoliv** [inventree/InvenTree#5560]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

If I don't user InvenTree daily, I end up with wrong information. It happens clearly when I "receive a order item". I just can classify the item, but cannot overrule when I received it.

So if I even for one day forget to directly open the package and update InvenTree, I have wrong data.

### Suggested solution

Let the user, at least optionally, overrule the receipt date of order items. On automatic order close, adapt the date.

### Describe alternatives you've considered

Manual updates in the database (at least this is what I do now) -.-

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@lippoliv so you want to be able to adjust the "date received" for stock items received against a purchase order?

**Comment by lippoliv** [comment]
Yes :)

**Comment by SchrodingersGat** [comment]
Not stale. Needs someone to take responsibility though :)
