### ISSUE TITLE
[FR] Storage location types

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#5561]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I have different types of boxes and 1. want to keep track of what containers I have and 2. display the same icon for the same box even if I update it at one place without messing with the db directly.

### Suggested solution

Add a storage location type table (like Parameter templates) where bins, bags, boxes, drawers, shelves, cases, toolboxes can be created with their properties like name, description, icon (and in the future maybe also an image or size can be added?). Then each location is optionally related to a storage location type. These types then can be edited in settings. And if the type contains an icon, the storage location uses that.

Actually in the end I also like to deprecate the location icon field and make it readonly, but I'm not sure how migration could look like. Maybe a script which groups by icon and creates location types according to that which get assigned to the locations. 

### Describe alternatives you've considered

Use sql queries to update the icons on all parts, but this is not a really easy solution for non programmers.

### Examples of other systems

/

### Do you want to develop this?

- [X] I want to develop this.

**Comment by wolflu05** [comment]
@SchrodingersGat exactly

**Comment by matmair** [comment]
I think having the option to set/override icons without having to create a `StockLocationType` entry will still have value (identifying every shelf by a different symbol for example) so if that is possible I'd appreciate it.

**Comment by wolflu05** [comment]
Ok, maybe I can also make a setting for that to force location types.
