### ISSUE TITLE
[FR] Restructure code

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#5578]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

We currently have frontend and backend structured differently and the name InvenTree is used multiple times. If you clone InvenTree any you set up bare metal manually you end up with this path: `/home/inventree/InvenTree/InvenTree/InvenTree/version.py`.

### Suggested solution

Reshuffle the code organisation, rename the `InvenTree` Django app and move everything possible into clearly documented (in CONTRIBUTING) folders.

My suggested structure would be something like this:
```
InvenTree/
├─ .github/
│  ├─ actions/
│  ├─ workflows/
│  ├─ scripts/
├─ .vscode/
├─ src/
│  ├─ backend/
│  │  ├─ requirements.txt
│  │  ├─ src/
│  │  │  ├─ core/
│  │  │  │  ├─ version.py
│  │  │  ├─ common/
│  │  │  ├─ order/
│  │  │  ├─ part/
│  │  ├─ manage.py
│  ├─ frontend/
│  │  ├─ src/
│  │  │  ├─ main.tsx
│  │  ├─ package.json
├─ contrib/
│  ├─ deploy/
│  ├─ docker/
│  │  ├─ Dockerfile
│  │  ├─ docker-compose.yml
├─ docs/
├─ assets/
│  ├─ images/
│  │  ├─ LOGO
├─ tasks.py
├─ README.md
```

### Describe alternatives you've considered

Moving some of the deploy stuff out of the way and adding docs alone would also be a bg win IMO.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by wolflu05** [comment]
This is a good idea to simplify things, but we need to make sure that the plugin system still works with the current import paths.

**Comment by matmair** [comment]
All documented paths are safe, they were structured that way. Imports from `InvenTree` will need a rewrite, that is kind of the point. Monkey patching that would run into a lot of problems because there are multiple namespaces/modules named InvenTree.

**Comment by SchrodingersGat** [comment]
This has been bothering me for ages, I support such a change. It would obviously need a lot of testing :)

**Comment by matmair** [comment]
I can make a PR that shows the effects. I have already tested this for all the docker stuff and know that keeps working. Other things should be straight forward - but breaking to 1) forks and 2) plugins. I think a fat warning in the release notes should be enough for 2) and think 1) can be neglected as I know of none that are signifincant.

**Comment by matmair** [comment]
Here is the docker test: https://github.com/matmair/InvenTree/tree/docker-cleanup

**Comment by matmair** [comment]
My suggestion would be a multi-PR change:
1. move all files except things that touch InvenTree import internals (ci, docker, Django as a whole, misc files) - with symlinks in place to the new locations for bare metal setups
2. make the breaking Django app name change
3. remove symlinks when we release 1.0

Does this sound good @inventree/triage ?
