### ISSUE TITLE
Cannot replace primary address

### ISSUE THREAD

**Issue by lippoliv** [inventree/InvenTree#5587]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

A customer can have 1 primary address. So if you define a new one, you need to confirm, that the other(s) will be replaced. But if you confirm that and save, you will get an error, that an primary address already exists.

### Steps to Reproduce

1. Create company
2. Add primary address
3. Save
4. Add another primary address
5. Confirm that the current primary address will be replaced
6. Save

![Xnip2023-09-21_11-17-46](https://github.com/inventree/InvenTree/assets/2561859/d138502a-faad-42dd-93e5-ebe4f8527148)
![Xnip2023-09-21_11-18-06](https://github.com/inventree/InvenTree/assets/2561859/ae062773-f1d9-49ab-bcef-ba9b5eb319cc)
![Xnip2023-09-21_11-18-21](https://github.com/inventree/InvenTree/assets/2561859/aa0c8599-97f2-4c3e-9eb3-597d70494f96)
![Xnip2023-09-21_11-18-34](https://github.com/inventree/InvenTree/assets/2561859/398a5ba9-4d08-45a2-abc9-2d997ac6e878)

### Expected behaviour

Since I confirmed, that current primary address is replaced, I expect that I can save the form.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.12.7

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@lippoliv thanks for reporting - fix incoming
