### ISSUE TITLE
Slow and often Bad gateway 502, 503 with the Digital Ocean One-Click Install

### ISSUE THREAD

**Issue by mittkkoo** [inventree/InvenTree#5589]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I deployed Inventree through the [DigitalOcean One-Click Install](https://inventree.org/digitalocean) with the cheapest server offered at Digital Ocean. See version information. I don't have much data in inventree, only 350 parts and a few images.

The problem is that sometimes Inventree is very slow and often it throws back errors like Bad Gateway 502 or 503 or other server errors. This happens in the browser as well as with the Android app. If this is a known issue, is the installation thorugh docker compose the better choice?

### Steps to Reproduce

1. Install inventree through the Digital Ocean 1-click-install with the cheapest server available
2. Do something in inventree and observe how it is slow and bad gateway errors appear

### Expected behaviour

I expect inventree to run without bad gateway errors.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0
Django Version: 3.2.18

Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

1 GB Memory / 1 Intel vCPU / 25 GB Disk / FRA1 

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
Your server does not have enough resources, probably RAM.

**Comment by mittkkoo** [comment]
I resized the server to 2GB and 2 CPUs and now it works fine. Thank you for the hint! I'm still surprised that some simple queries in a database would need so much resources. As the database was empty this was not the case, but 350 items is still nothing.

**Comment by lippoliv** [comment]
When it's "slow", can you chack background jobs queue in the admin panel please, is it a lot of queued jobs (like for me #5594)?
