### ISSUE TITLE
Minimum stock form validation requires an integer

### ISSUE THREAD

**Issue by adamgreig** [inventree/InvenTree#5596]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

If a part has a unit of measure, e.g. `m`, then stock can be tracked as a real number, e.g. `0.7 [m]`. However the minimum stock field only validates if an integer is provided. In some cases stock is only considered low when below 0.5, but it's not currently possible to put a non-integer into the minimum stock field.

### Steps to Reproduce

1. Create or edit part with non-empty unit of measure
2. Attempt to set minimum quantity to a non-integer value such as 0.5
3. Submit form
4. Form validation error is returned

### Expected behaviour

Non-integer minimum stock levels are accepted and cause "low stock" alerts when stock falls below that level.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

Git 6563b4c4134df6fc3ee9886437d4213738bc2af2

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@adamgreig the "minimum_stock" field is an integer field, so it makes sense that the form throws an error here.

However, it should probably be not limited to integer values, this concept went away from "part quantity" quite some time ago. I'll look into this for you.

**Comment by SchrodingersGat** [comment]
Fix incoming in https://github.com/inventree/InvenTree/pull/5609

Note that as this is not a critical bug and the fix involves a change to the database schema, this will not be back-ported to the current stable branch

**Comment by adamgreig** [comment]
Thank you, I appreciate the quick response!
