### ISSUE TITLE
[FR] Allow part templates to be base of supplier parts

### ISSUE THREAD

**Issue by lippoliv** [inventree/InvenTree#5601]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

We work with printing companys to produce some post cards or flyers, stuff like that. When adding a new product, I have a lot of work to do, since I need to create a new producer part, but in fact all post cards are the same.

Just the supplier part then isn't since now theres some graphics printed on the paper.

### Suggested solution

I would like to be allowed to select a product template as base part for the producer and then later select the producer part with the specific variant of my parts.

### Describe alternatives you've considered

-

### Examples of other systems

-

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
I am not sure I fully understand what you mean by 'producer'. We have supplier and manufacturer parts - both need a part as a anchor for allocation, BOMs and more. Can you restate your request using official language as used in the UI and docs?

**Comment by lippoliv** [comment]
OK I retry:

1. Create a `Part` (Part 1) as a Template
2. Create another `Part` (Part 2) as a variant for that Template
3. Create another `Part` (Part 3) as a variant for that Template
4. Create a `Company` (Company 1) which is Supplier and Manifacturer
5. In "Company 1", create a "Manifacturer Part" with Part 1 as "Base Part" (Manifacturer Part 1)
6. In "Company 1", create a "Supplier Part" with Part 2 as "Base Part" and the above created"Manifacturer Part 1"

<img width="1059" alt="image" src="https://github.com/inventree/InvenTree/assets/2561859/d1053a28-0592-4fdb-98ba-b69d6f114c1f">

My FR is, that this should / could be allowed.

**Comment by lippoliv** [comment]
I just saw that Manufacturer Part is optional lol So maybe for the items I have it's not relevant to maintain, hence priority of this FR reduced for me.
