### ISSUE TITLE
loadPluginTable not defined - after update

### ISSUE THREAD

**Issue by mredp-evos** [inventree/InvenTree#5643]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I just did two things:

- Installed the KiCad Inventree Plugin
- Updated Inventree to the latest using docker pull (Then running the invoke command)

Everything appears to work, but when I go to the settings page I don't see any content render. I see the error "loadPluginTable not defined" error when I view the web console. See image attached.

If I recall correctly the issue didn't happen immediately after installing the plugin, but after I did the update. I went from 11.3 to 12.7.

![image](https://github.com/inventree/InvenTree/assets/92128855/0fa0d33a-bcbc-4d7e-ae34-3ee13920c150)

### Steps to Reproduce

1. Install KiCad plugin on version 11.3
2. Update to version 12.7 using docker pull

### Expected behaviour

Not able to access the settings page. See an error message in the web console.

`loadPluginTable not defined`

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

Started at 11.3 -> updated to 12.7

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
@mredp-evos please use the proper version information text. It is provided in the upper right corner of the page in the `About InvenTree` dialog. There is a copy information button that copies everything we need into your clipboard.

**Comment by matmair** [comment]
I can not reproduce this on the demo instance, please try [this step](https://docs.inventree.org/en/stable/faq/#feature-x-does-not-work-after-update) from our FAQ to confirm it is a bug and not a caching problem.

**Comment by mredp-evos** [comment]
Hi @matmair Thank you it must have been a caching problem.
