### ISSUE TITLE
Update Images - remind user which path to use before running update

### ISSUE THREAD

**Issue by tomse** [inventree/InvenTree#5655]
### Body of the issue

Yesterday I was going to update the docker images, while docker isn't unknown to me, I still have a lot to learn.

I had issues which I did manage to find and resolve.

It would be nice to have a reminder in which path to be in when running the update commands. 
having followed the installation guide it would be in: "InvenTree/production/docker"
and not in "InvenTree" like I did and couldn't get it to work

[https://docs.inventree.org/en/stable/start/docker_prod/#update-images](https://docs.inventree.org/en/stable/start/docker_prod/#update-images)

**Comment by SchrodingersGat** [comment]
@tomse from the page you linked:

> .This tutorial assumes you are working from the ./docker/production directory. If this is not the case, ensure that these required files are all located in your working directory.

Note that you do not need to download InvenTree source code at all, to install via docker:

![image](https://github.com/inventree/InvenTree/assets/10080325/bccbd5f8-c718-4408-be4a-4b288a3f5e14)

**Comment by tomse** [comment]
thank you, I know it is written in the early stages of the page - under installation.

When you are a newbie like me, and already have an installation running, and just want to update, you skip reading the installation section, and go directly to the update section, and start following the steps there.

| Note that you do not need to download InvenTree source code at all, to install via docker:

I just thought it easier to git clone the project, rather than fetch each of the 3 files on a headless machine,
(github is not single file friendly using fetch/wget - or I just haven't figured it out yet).
