### ISSUE TITLE
Feature request: SnapEDA api

### ISSUE THREAD

**Issue by Snevzor** [inventree/InvenTree#566]
Related to #541, where we briefly discussed the Octopart API.

There are 2 issues where I work. When adding a new component to the design we need to check and make sure:

- We have the cad libs
- We have it in stock and if not we have to buy it

It happens a lot that these actions are not executed together and most likely you will be looking for the same part for different reasons on different occasions. What a waste of time?

What about SnapEDA api (or others)? This would make it easier to add a component but at the same sime Kicad or Eagle libs could be downloaded whilst adding the part. This would solve the 2 issues in one step. In an ideal world there would be even an option to choose a git repo to store all the libs in so a simple fetch will make the new libs that were added using InvenTree available in your cad soft.

I cannot seem to find the SnapEDA TOS though...

**Comment by eeintech** [comment]
@Snevzor I have tried to get a hold on SnapEDA's API for a tool I developed: https://github.com/sparkmicro/Ki-nTree/
However, they're quite picky on the projects they would support. I actually made a case that InvenTree was used by hundreds of people and they still consider it as "very early stage" project.

I've also considered also using Octopart's API but their older API was lacking features for filtering requests and now they have a pretty harsh limit of 500 requests a month for the free version. Digikey's API on the other hand is almost entirely free (limited to 1000 request **a day**) and there already was a Python API (https://github.com/peeter123/digikey-api).

The combination of KiCad and InvenTree is clearly a winner if one can set them up properly, which was my intention making Ki-nTree. However, InvenTree should never hold KiCad or Eagle libraries, it can merely point to them if needed.

**Comment by eeintech** [comment]
@Snevzor What are your thoughts on my previous comment?

**Comment by eeintech** [comment]
SnapEDA API's isn't made public yet (the main request of the OP), I would suggest to close this issue for the time being @SchrodingersGat

**Comment by Snevzor** [comment]
Thanks @eeintech for investigating. I will surely give Ki-nTree a go on my next project! Nice work!

**Comment by SchrodingersGat** [comment]
@Snevzor best bet would be to look at the [Python API](https://github.com/inventree/inventree-python) and try to link this up with SnapEDA. If you come up with a solution please let me know and I'll add it to the [Third Party Tools](https://inventree.readthedocs.io/en/latest/extend/integrate/) page 👍
