### ISSUE TITLE
[FR] Part External Links should open in new window

### ISSUE THREAD

**Issue by Limb** [inventree/InvenTree#5669]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Currently External Links open in the existing window, making you lose your current position in inventree unless you use the browser back button. It would be more helpful if these opened in a new window so you can browse the external link, close it, and be back where you were in inventree.

### Suggested solution

Add ```target="_blank"``` to the anchor tag for external links.

### Describe alternatives you've considered

Leaving it as is?

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
https://developer.chrome.com/docs/lighthouse/best-practices/external-anchors-use-rel-noopener/
