### ISSUE TITLE
Stock Location

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#567]
I have 14 of the 64 drawer cabinet.  I have them labeled C-01 and each drawer labeled 01-64
How do I enter this into InvenTree?  It will not let me assign drawer 01 to multiple cabinets.

**Comment by SchrodingersGat** [comment]
Hey @lookme2 currently there is a requirement that the name for each StockLocation is unique (so this is not currently possible)

**Comment by a7hybnj2** [comment]
@lookme2 I see how this could be very helpful. Any inventory system is made up of locations that have sub locations that may repeat.

Shelf A: Box 1, Box 2, Box 3, Box 4
Shelf B: Box 1, Box 2, Box 3, Box 4

if you cannot repeat Box 1, ect then you have to have UUIDs for every storage location which makes finding things much harder.

I would vote for unique first level but 2nd levels could repeat.

**Comment by SchrodingersGat** [comment]
Turns out this was actually pretty easy to implement. This has now been implemented in https://github.com/inventree/InvenTree/pull/631

**Comment by lookme2** [comment]
Thanks!
