### ISSUE TITLE
Part variant BOM pricing way too high

### ISSUE THREAD

**Issue by kronok** [inventree/InvenTree#5683]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

While trying to create a "pack of 9" by creating a BOM, I ran into a nasty bug.

I have a $0.30 part that inventree calculates as worth $6,863,037,736,488.3 if I use it as a BOM item in a variant of itself.

I opened up Inventree's official demo and easily re-created it. (If it hasn't deleted itself, it's part 913 and 914 as of right now, but I'll show how to reproduce it)

### Steps to Reproduce

1. Create a new part (we'll call it Main Part). Make sure it can be used as a template.
2. Add internal pricing to the part. I used $0.30 in my test. (it just needs any sort of pricing, whether it's internal or wherever)
3. Create a variant of 'Main Part'.
4. Add a BOM to it and use 'Main Part' with a quantity of 9.
5. It should instantly go haywire with the max pricing of the BOM.
6. Each time you refresh the pricing, it should go higher until the database can't handle that high of a number.

### Expected behaviour

Expected the BOM price to be $0.30 x 9 = $2.70 instead of $6,863,037,736,488.3

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.22
Commit Hash: 6f2dca7
Commit Date: 2023-10-09

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-82-generic-x86_64-with
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Ok, that's an interesting case. The BOM for the variant includes the parent part - and so each time the "variant price" is calculated, it looks at the bill of materials, which includes the template part. The pricing for the template part includes the calculation of pricing for all variant parts. So, the variant price is 9x template price which is 1x the variant price.

Essentially we have created for ourselves a nice little infinite loop.

**Comment by SchrodingersGat** [comment]
Thinking about it some more, the most robust solution would be to prohibit a BOM item from containing items which are either children or ancestors of the assembly.

This would mean that your "pack" would need to be a *different* part (not a variant). But it is the simplest approach which avoids a lot of potential edge cases.

**Comment by SchrodingersGat** [comment]
@matmair @wolflu05 I'd like to get a fix for this into `0.13.0`. Any thoughts on the idea of preventing BOMs from containing variants of the target part?

I'd also like to consider how we would stop this infinite loop in pricing calculations too. As each pricing calculation is considered "separately" it is hard to detect loops like this

**Comment by matmair** [comment]
I think the logical problems arising from BOMs containing itself alone are enough reason to not allow this; I would just close down this possibility and check the tree on BOM changes if the item itself is in the tree in either direction.
