### ISSUE TITLE
Changing Quantity to decimal field 

### ISSUE THREAD

**Issue by Zenbiz** [inventree/InvenTree#569]
Issue: tests not passing when changing PositiveIntegerField to DecimalField on quantity variables within models.py. 

Pretty new to Django here..Looks like you've been using this system for whole parts (ie you can buy a 1/2 a transistor). I tried changing the following quantity fields to decimals and I'm getting errors when I run tests. I'm wondering how difficult it would be to change the following:

**Before:**     
`quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)]`)

**After:**   
`quantity = models.DecimalField(max_digits=11, decimal_places=8, validators=[MinValueValidator(0)], default=1.0)`

![image](https://user-images.githubusercontent.com/36719631/67036691-4b18d980-f0d9-11e9-953a-127059dfcd10.png)

Reason I ask is I'm buying some products by weight. So when using Inventree I can't convert oz<->grams and lbs<->liters  without using decimals for the quantity variable. 

Product is awesome though thanks for all the work! I'm using this for a lab setup potentially. I wouldn't mind working on this project and using it for my hobby lab and contributing to the documentation ;) 

![image](https://user-images.githubusercontent.com/36719631/67037174-3ee14c00-f0da-11e9-9888-eb959201c762.png)

**Comment by SchrodingersGat** [comment]
Hey @Zenbiz thanks for the feedback - I'm super excited that you like the project!

I've just returned from holiday, sorry for the delay on responding to this. 

I would like to move to a DecimalField for the 'quantity' - up until now I have managed without 'partial' quantities but I can now see the need for it. I'll have a look at the unit testing issues, but there are also some other considerations that need to be made...

I would absolutely love some contributions to the documentation if you have time - it's really lacking at the moment!

**Comment by SchrodingersGat** [comment]
Hi @Zenbiz I have implemented this now. Please update to latest version and see if it is all working for you! (I may have missed an edge case in my testing).

Also, I'd be very keen to hear back from you regarding the documentation side of things :)
