### ISSUE TITLE
[FR] Add Tags for Attachments

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#5691]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Currently I can only add text comments. If let's say someone wants to add a datasheet, they could put a comment like Datasheet, DATASHEET, dAtAScHeEt, datasheet etc.

### Suggested solution

It would be good if there could be predefined tags for uploads rather than just a comment. This would sunify the comments a bit.

![image](https://github.com/inventree/InvenTree/assets/42826581/bca235f6-9c51-4dcf-83da-3efa5060b99a)

### Describe alternatives you've considered

none

### Examples of other systems

none

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Duplicated issue of https://github.com/inventree/InvenTree/issues/5429 perhaps?

**Comment by SchrodingersGat** [comment]
Closing as duplicate issue
