### ISSUE TITLE
[FR] Adding Swiss francs as currency

### ISSUE THREAD

**Issue by nikolai2111** [inventree/InvenTree#5694]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I didn't found Swiss francs (CHF) in the drop-down menu, where I could select the currency. I Swiss, so I would be very happy when you cloud add it.

### Suggested solution

Add Swiss francs (CHF) to the currency drop-down menu. I sadly could only found the [Wiki](https://en.m.wikipedia.org/wiki/Swiss_franc) about it.

### Describe alternatives you've considered

There is no alternative.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by wolflu05** [comment]
Hey @nikolai2111 ,

Mostly all currencies are already supported, but not enabled by default. You need to enable chf first using either the config file or environment variables as described in our [docs](https://docs.inventree.org/en/latest/start/config/#supported-currencies).

**Comment by SchrodingersGat** [comment]
You can also find more here - https://docs.inventree.org/en/latest/settings/currency/
