### ISSUE TITLE
[PUI] How to download attachments and reports

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5697]
Related issues:

- https://github.com/inventree/InvenTree/pull/5696
- https://github.com/inventree/InvenTree/issues/5048

The new user interface will be driven entirely by the API. Thus, downloading files (like attachments, reports, etc) no longer relies on session cookies.

so, how do we provide "file download" for the user? Note that any media files served / hosted by InvenTree require user authentication (e.g. via auth token).

So, we need a way to fetch the file and present to the user for download, via the web client. 

Many of the ways I have found are very clunky, requiring first downloading the file to browser RAM, and then making a hidden button and "clicking" the button (in software). Or, similar tricks using hidden web forms.

Surely there is a better way? Any suggestions how we can cleanly do this via the API, without any of these hacks tricks?

**Comment by wolflu05** [comment]
Also related #5531

**Comment by matmair** [comment]
I do not really see why it is not working with basic links; I will investigate tonight.
If required I think we should change the backend for this so we can just link to a download endpoint instead of having to work around in the frontend with it.
Maybe [this](https://stackoverflow.com/a/56763856/17860466) is a solution?

**Comment by SchrodingersGat** [comment]
@matmair as far as I can tell, it is because the browser does not have a session cookie. Have a look at the request headers when you download a file in the current UI, vs the react UI.

Here is the request to do a "simple download" of the file in the new UI, which only has login via token auth - no browser session auth:

<img width="796" alt="Screenshot 2023-10-16 at 7 11 25 pm" src="https://github.com/inventree/InvenTree/assets/10080325/fb45c480-88ac-4305-b08a-b7b017de6b7c">

This is the same reason that I have been working on [this PR for images](https://github.com/inventree/InvenTree/pull/5696)

One option I have considered:

1. At login, request a "session cookie" from the server
2. Save the cookie to the session
3. Any "media file links" can then be downloaded without any extra issues

**Comment by SchrodingersGat** [comment]
> If required I think we should change the backend for this so we can just link to a download endpoint instead of having to work around in the frontend with it.

I would prefer this too - the required changes to the frontend would be prohibitive

**Comment by SchrodingersGat** [comment]
> I think adding a session token should be a (somewhat) easy feat.

I hope so! I have not yet found any good examples of this

**Comment by matmair** [comment]
I have done something similar in the past - we need to argument the token endpoint to instantiate a session/log the user in and set the session token in the response. I will tackle it once #5582 is done; that is getting to the finishing line
