### ISSUE TITLE
[Docker] Place translation stats file in external volume

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5716]
I see, that might explain why it is working over there.

Sounds logical to me to just expose the file to the `data` volume like the other precompiled assets... right?

_Originally posted by @simonkuehling in https://github.com/inventree/InvenTree/issues/5214#issuecomment-1697426648_

**Comment by SchrodingersGat** [comment]
See extended notes in #5214

**Comment by SchrodingersGat** [comment]
While reviewing this one I have discovered two things:

1. The translation stats do not account for the react frontend translations 
2. The new "platform" frontend does not use the translation stats

@matmair @wolflu05 is this feature worth pursuing? Or should we eliminate it? I have a WIP to fix the above issues, but wondering if it is worth it

**Comment by matmair** [comment]
I found them handy in CUI but not sure if they are really worth it. Removing them would reduce complexity

**Comment by SchrodingersGat** [comment]
I'll leave the script in place (in case we need to use it again) but remove the integrations

**Comment by SchrodingersGat** [comment]
In fact, let's close this *after* we have removed CUI, as it will be pretty much useless after that

**Comment by matmair** [comment]
@SchrodingersGat I would prefer if we target this after 0.17.x to reduce possible issues

**Comment by SchrodingersGat** [comment]
Agreed
