### ISSUE TITLE
[FR] Add "dominant foreground and background color" to config.yml

### ISSUE THREAD

**Issue by Petrox** [inventree/InvenTree#5720]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Any company introducing inventree should have at least one production and one training/staging/dev environment set up.

These instances could have some customizations (eg. login screen background, title in the middle of main page).

The mobile app can also handle multiple inventree instances, which is nice.

But the end user (a random employee of the company) might still work in the wrong system and create real data in testing or worse they could damage the production system with chaotic amount of noise (eg 2000 new stocklocations) or delete some real information, parts or stockitems for example.

### Suggested solution

Introduce a "dominant foreground" and "dominant background" color setting.
The general design of the webside does not need to change, just make sure the instance name is written in the top-center of the screen with this color pair.

Also the mobile app could query these properties and colorize the UI headers according to the specific instance settings.

Then it is intuitive for the end user employee that "we try things in the yellow only and do real work in the blue system only".

### Describe alternatives you've considered

In theory this can be done on the mobile app side, but it's a better idea to store these colors in the main backend then let all clients (including the web ui) use the same specific colors.

### Examples of other systems

I had the same implemented in multiple custom software and some test systems even had diagonally striped backgrounds and people liked it and made no serious mistakes after the introduction of this simple feature.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by Petrox** [comment]
Yes, I did that already.

The feature request is about "colorize/identify an instance globally, even
through different APIs including the mobile app, so users don't mix up
multiple instances"

(I could have opened an issue there, but the color settings should be in
config.yml in inventree and then a new issue will "appear" at the
mobileapprepo)

**Comment by SchrodingersGat** [comment]
THis could be solved by the currently available theming support

**Comment by SchrodingersGat** [comment]
Not going to fix - new UI will offer some level of customisation
