### ISSUE TITLE
[PUI] Expose all language options

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5729]
Currently language options for the react/platform interface are artificially limited. We need to expose all of the locale options

**Comment by matmair** [comment]
@SchrodingersGat we do not really have translations for the new UI but I will add all currently supported languages in a PR.

**Comment by SchrodingersGat** [comment]
Not yet, but they are exposed on crowdin yeah?

**Comment by matmair** [comment]
Yes, I am currently prototyping a task to add new languages and will push the diff after that.
