### ISSUE TITLE
[PUI] Auto-build frontend on update

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5732]
Ref: https://github.com/inventree/InvenTree/pull/5568

Once the react frontend is "good enough" to ship, we will make the "breaking" change to the update procedure which automatically builds the react frontend

**Comment by matmair** [comment]
@SchrodingersGat should we maybe shift this to 0.15.0 or do you still want to ship this with 0.14.0?

**Comment by SchrodingersGat** [comment]
I'm happy to bump it, so that we have some time to build confidence in the process

**Comment by matmair** [comment]
@SchrodingersGat we are now shipping the frontend ready-to-go on docker and packaged installs - can we close this?

**Comment by SchrodingersGat** [comment]
I believe this can be closed out, yet :)
