### ISSUE TITLE
Unable to make backup link of './opt/inventree/Inventree/script/translation_stats.py` before installation. Operation is not permitted

### ISSUE THREAD

**Issue by CodingPupper3033** [inventree/InvenTree#5739]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [X] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hey, I'm attempting to update my Inventree instance using the command found in the documentation (`sudo apt install --only-upgrade inventree`), and it fails to apply the update. The first error encountered is `Unable to make backup link of './opt/inventree/Inventree/script/translation_stats.py` before installation. Operation is not permitted`, at the end of the update, the error is: `sub-process /usr/bin/dpkg returned an error code (1)`

### Steps to Reproduce

1. run `sudo apt install --only-upgrade inventree`

**Comment by CodingPupper3033** [comment]
I'm trying to update from version 0.12.1 to the latest version

**Comment by SchrodingersGat** [comment]
@CodingPupper3033 is there any more error information available?

**Comment by CodingPupper3033** [comment]
Those were the only lines that specifically said error or warning. I can try outputting the terminal to a file if you would like

**Comment by CodingPupper3033** [comment]
Everything else seemed to have worked, though (but not applied as the version in about inventree hadn't changed)

**Comment by CodingPupper3033** [comment]
I believe this should be the output from running the command. However, this is after rerunning the command, so it may have updated some parts

[upgrade-log.txt](https://github.com/inventree/InvenTree/files/12969282/upgrade-log.txt)

**Comment by SchrodingersGat** [comment]
@matmair any thoughts on a permission error writing to `/opt/inventree/InvenTree/script/translation_stats.py`?

**Comment by matmair** [comment]
Bare metal development and package installer are not compatible. @CodingPupper3033 do you have bare metal development or package/single line installer?

**Comment by CodingPupper3033** [comment]
My apologies; the issue was on my end.

For the record, here's what went wrong.

I have InvenTree running on Ubuntu in a VM. However, I have the main InvenTree source root on my computer and share the folder with the VM. I do this so I can code using my main computer and already set up IDE and run the server in a very similar environment to our production server.

I brought the source code back to the VM and the installer script worked without issue. Thank you for your help!
