### ISSUE TITLE
Dependencies issue with python-coveralls

### ISSUE THREAD

**Issue by nickoe** [inventree/InvenTree#574]
I tried to clone inventree and hit `make install` on archlinux. I got an issue with pip installing the dependencies. I then tried to make a Docker file based on python:3. It also failed, to reproduce I did:

```
FROM python:3
ADD . /inventree
RUN cd /inventree && make install
```

The error logs is:
```
ERROR: python-coveralls 2.9.1 has requirement coverage==4.0.3, but you'll have coverage 4.5.4 which is incompatible.
```
I am testing with `v0.0.7-24-g54855da`.

**Comment by SchrodingersGat** [comment]
HI @nickoe if you change line 16-17 of `requirements.txt` to:

```
coverage==4.0.3                 # Unit test coverage
python-coveralls==2.9.1         # Coveralls linking (for Travis)
```

is the problem fixed?

I really need to make a python virtual-env setup for this, the requirements file has grown pretty big now...

**Comment by nickoe** [comment]
Yes, setting `coverage==4.0.3` works.

So we need a specific version of coveralls?

I am no expert here, but I would have expected latest versions of everything to be ok on master.

**Comment by SchrodingersGat** [comment]
It is an interdependency issue between coveralls and python-coverage. I have not personally picked those specific versions for my own preference, but due to requirements of other packages. It's annoying, but at least the requirements.txt takes care of it.

**Comment by nickoe** [comment]
Ok, thank you.
