### ISSUE TITLE
Documentation for new barcode scanning functionality

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5747]
Once https://github.com/inventree/InvenTree/pull/5509/ is merged, documentation around the new functionality is required.

**Comment by SchrodingersGat** [comment]
@30350n :)

**Comment by 30350n** [comment]
Actually, I've already added a small section to the Custom Barcode docs [here](https://github.com/inventree/InvenTree/pull/5509/files#diff-0f326fbc7daa97ea50a1fbf86a8a3da2c17d3b7c8f36c4f9f9c28d776dcdfdbd).

**Comment by wolflu05** [comment]
I guess @SchrodingersGat means to document the new Mixin in the extend section too.

**Comment by 30350n** [comment]
Ah okay, yeah I guess that makes sense. I'm honestly not sure about the current bit of documenation I've added too. The new functionality kind of fits into both the External Barcodes and Custom Barcodes categories.

Looking at the External Barcodes docs, I guess this functionality should atleast be mentioned there, as atleast for the now supported suppliers, it kind of makes manually adding the barcodes unnecessary.

**Comment by SchrodingersGat** [comment]
The docs should include also "user" functionality - I would suggest we wait until the features are added to the user interface. Additionally some notes on how to use the features in the mobile app, with some screenshots and examples
