### ISSUE TITLE
[PUI] Remove custom themes

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5754]
Current support for "custom themes" will be removed when we make the switch to the new react UI

**Comment by matmair** [comment]
@SchrodingersGat what is the action item here? Remove the backend function?

**Comment by SchrodingersGat** [comment]
Yes, basically all the current theming support, once we remove the existing UI code

**Comment by wolflu05** [comment]
But we could still sync the theme for one user, I mean there is still a dark and light mode?

**Comment by SchrodingersGat** [comment]
@wolflu05 yes that is still there, this is just a reminder to cull the old code once we switch

**Comment by matmair** [comment]
Will be needed after PUI is GA

**Comment by matmair** [comment]
This is addressed in #8384

**Comment by SchrodingersGat** [comment]
Duplicate of https://github.com/inventree/InvenTree/pull/8384
