### ISSUE TITLE
[PUI] Check user permission when viewing pages

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5755]
User might not have "view" permission for a given page.

If not, redirect away, or show error message?

**Comment by matmair** [comment]
I would run a permission check and if it is a missing permission show an error, else log out (user might be unauthenticated).

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by matmair** [comment]
@SchrodingersGat we now have permission tests in PUI - is this still valid?

**Comment by SchrodingersGat** [comment]
Yes this is still valid - we do not currently check if a user has the required permissions to view any particular page in PUI.
