### ISSUE TITLE
[Question] Shortcoming of current token implementation

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5762]
The *new* token implementation does not re-issue duplicate tokens via the API, which causes a subtle problem.

If a user has multiple browsers open, which all request a token with the same "key" (such as "inventree-web-app") then the server will invalidate the existing token that matches that key, and create a new one. Essentially, only one browser will have a valid token at any one time.

In a similar fashion the mobile app would run into the same problem if the same user has the app installed on multiple devices

#### Potential Solutions

1 - Allow multiple tokens to share the same "name" (do not invalidate old ones when a new one is generated)
2 - Make the names more "unique" somehow?

2 does not seem foolproof and will run into problems at some stage.

I think 1) - remove the `unique_together` requirement on `[user, name]`?

**Comment by matmair** [comment]
I think using more unique names (ie including useragent or device name) would be beneficial but I do not see an inherent value in unique names
