### ISSUE TITLE
Do not delete stock items

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#578]
If a stock item is 'removed' do not actually delete it, simply mark it as "deleted" but preserve it (and its history). Deleted stock should not be visible to the user (unless they explicitly look for it).

**Comment by eeintech** [comment]
@SchrodingersGat Isn't this the same as marking stock "depleted" but disabling the setting to delete it when depleted?

**Comment by SchrodingersGat** [comment]
I think you're right! I'll close this one out, it has been on the back burner for quite a while now and as you say I think it has been addressed already.
