### ISSUE TITLE
[FR] Assign Stock to Contract

### ISSUE THREAD

**Issue by Elitearcanist** [inventree/InvenTree#5792]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Sometimes a stock item taken into the company but is legally owned or controlled by another organization or contract. Currently there isn't a clear way of marking that a stock item is part of a larger contract that might have regulations or needs to be better controlled.

### Suggested solution

Add a system (perhaps similar to the already existing assigned customer system) to mark a stock item to a company or contract (could even just be a custom tag). Stock items would display this information in the list view table and individual item properties.

### Describe alternatives you've considered

The assigned customer system kind of accomplishes this. It is limited to customers and salable parts. The proposed system would make a new feature that would be more universal.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@Elitearcanist it sounds like some pretty complex changes would be needed to "fully" implement this - we have had similar requests in the past for "loaning" stock out (e.g. to external companies)
