### ISSUE TITLE
[Plugin] Plugin loader does not find packaged plugin in "plugins" dir

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5827]
If you download a "packaged" plugin, (e.g. [inventree-brother-plugin](https://github.com/inventree/inventree-brother-plugin/)) and place it in the external "plugins" dir, it will not be found by the plugin walker.

This is because the actual plugin code is in a second-level directory.

Enabling the plugin to be "found" if it is downloaded and placed here would be useful for:

- Plugin development: Simply dump the code into the plugins dir, edit, changes are reloaded by the server
- User experience: If users can easily drag plugins into this directory, better than trying to explain why it won't work in this case

### Approaches?

- Allow these directories to be walked one level deeper when looking for modules?
- Another approach?

**Comment by matmair** [comment]
Walking deeper could lead to a slower discovery process but should not have an impact on normal operations. Note that plugins are traditionally only rediscovered on a full/forced reload.

**Comment by SchrodingersGat** [comment]
Not stale. can avoid this by using "pip install -e" but not for simple discovery
