### ISSUE TITLE
Get Cannot find module error

### ISSUE THREAD

**Issue by MohammadSamandar** [inventree/InvenTree#5829]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [x] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

when i want deploy with dockerfile i get this error:

### Steps to Reproduce

[liara-logs.txt](https://github.com/inventree/InvenTree/files/13224511/liara-logs.txt)

### Relevant log output

```bash
src/router.tsx(31,21): error TS2307: Cannot find module './pages/build/BuildIndex' or its corresponding type declarations.

src/router.tsx(34,21): error TS2307: Cannot find module './pages/build/BuildDetail' or its corresponding type declarations.

[91merror Command failed with exit code 2.
[0m
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The command '/bin/sh -c cd ${INVENTREE_HOME}/InvenTree && inv frontend-compile' returned a non-zero code: 2
```

**Comment by SchrodingersGat** [comment]
- Are you using a custom docker compose setup? Or our "standard" one?
- `inventree:stable` or `inventree:latest`?

**Comment by wolflu05** [comment]
A gh sha would be helpful, try `docker image inspect your/image:tag` you're using and see if there is an gh sha referenced.

**Comment by MohammadSamandar** [comment]
> * Are you using a custom docker compose setup? Or our "standard" one?
> * `inventree:stable` or `inventree:latest`?

I use a PaaS cloud service and I just need to upload the folder containing Dockerfile to this PaaS.

**Comment by matmair** [comment]
I do not think this will work, you need the source code to build the image.

**Comment by MohammadSamandar** [comment]
> I do not think this will work, you need the source code to build the image.

I talked to the support of the cloud platform and they said that the problem is with your code and there are other people who use this platform well.

**Comment by SchrodingersGat** [comment]
> I just need to upload the folder containing Dockerfile to this PaaS.

InvenTree will not work with just a docker file. You will at minimum need:

- Other running containers with database / proxy / etc
- A docker-compose file (or similar) to control these
- Knowledge of what this entails

**Comment by matmair** [comment]
InvenTree is not designed to run as a single image or be built without the source code available. It will not work - based on the info you have given.
Please provide more information about the platform and what you are trying to do or close this issue.
