### ISSUE TITLE
[FR] use integers at purchase order export if unit is pieces

### ISSUE THREAD

**Issue by T0jan** [inventree/InvenTree#5832]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

hi,

We try to use the InvenTree purchase orders to track our purchases at different suppliers and in general this works very well but there is one problem if you want to get the data into the suppliers systems: they sometimes only allow integers as quantity and will just reject any other kind as value even if it is a .0 float. Most notable interface where we noticed it was the bom-import tool of Digi-Key if we used the unmodified purchase order export list.

### Suggested solution

In case the quantity unit is `pieces` the export should use integer values instead of floats as it is very unlikely that you can use/order half or quarter pieces of anything.

### Describe alternatives you've considered

If it is needed to also reflect decimal values for cases I am not aware of it could be also an idea to allow the use of supplier based export templates which define which values, formats and maybe even columns are needed for the data transfer.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@T0jan I think that [this old issue](https://github.com/inventree/InvenTree/issues/2778) would potentially be a cleaner implementation

**Comment by T0jan** [comment]
@SchrodingersGat cleaner yes, but also more restrictive. I can imagine that there are use cases where one wants to track half, quarter, etc. pieces. E.g. to remind someone that only half a cake is left in the fridge :smile:

**Comment by T0jan** [comment]
just noticed I am to focused on CSV. if you do an XLS or XLSX export the quantity will be an integer by default. so yeah there is a bit inconsistency in how pieces are handled in the export, but at least our problem with the data transfer is solved for now.
