### ISSUE TITLE
Update failed to fetch https://dl.packager.io/srv/inventree/InvenTree/...

### ISSUE THREAD

**Issue by mittkkoo** [inventree/InvenTree#5838]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [X] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

What's wrong with dl.packager.io?

```
root@inventree0110onubuntu2004-s-1vcpu-1gb-intel-fra1-01:~# apt install --only-upgrade inventree
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  inventree
1 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
Need to get 109 MB of archives.
After this operation, 4096 B disk space will be freed.
Err:1 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/ubuntu 20.04/main amd64 inventree amd64 0.12.8-1698354157.a7487ff8.focal
  500  Internal Server Error [IP: 178.63.71.248 443]
E: Failed to fetch https://dl.packager.io/srv/inventree/InvenTree/downloads/219670?token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkbC5wYWNrYWdlci5pbyIsInN1YiI6In........LocXoDhjlGw1m9XS--dPP7mzp2vY  500  Internal Server Error [IP: 178.63.71.248 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Here a very similar issue with another tool. Maybe have something in common, related to packager.io: https://community.zammad.org/t/zammad-update-500-internal-server-error-apt-upgrade/12523/20

### Steps to Reproduce

1. Try to update inventree as [described in the docs](https://docs.inventree.org/en/stable/start/installer/#updating-inventree)

**Comment by SchrodingersGat** [comment]
Server might just be down, have you tried again?

**Comment by matmair** [comment]
Seems like a more general problem with the platform, I see a lot of these errors in my works SIEM.

**Comment by matmair** [comment]
@mittkkoo try to run `apt update && apt install inventree`

**Comment by matmair** [comment]
As far as I can tell the problem should be fixed now, my personal instances are updating without problems.

**Comment by wolflu05** [comment]
I guess this is related to the [Cloudflare outage](https://www.cloudflarestatus.com). Doing a whois request to `packager.io` reveals they point to Cloudflare. So this issue may also depend on your location?
