### ISSUE TITLE
Issue with Pack Quanty Values

### ISSUE THREAD

**Issue by bberg115** [inventree/InvenTree#5850]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The "pack quantity" paramter for Supplier Parts is no longer working. This was working on our internal Inventree before we updated to 12.8 from 11.0. We are unable to see existing pack quanties nor add pack quantities to new supplier parts. This appears on all data that shows pack quantites - part supplier page, purchase orders, and stock tables.

Examples:

1. In the edit window for a supplier part - "pack_size" is listed under the Packaging parameter.
2. In the part supplier table, it shows "undefined" in the column for "Pack Quantity".

See screen shots below. 
![chrome_UXqER0SpCJ](https://github.com/inventree/InvenTree/assets/17869135/689fcc55-06ad-4255-b94b-66fde2f88e45)
![chrome_wilqdKfwiB](https://github.com/inventree/InvenTree/assets/17869135/b66acfe4-a38c-4efb-bb54-5045099b790f)

### Steps to Reproduce

1. Go to a part
2. Click on suppliers
3. Look at column "Pack Quantity" in Part Suppliers table

### Expected behaviour

Should show pack quanities and be able to add them to new parts.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

12.8

The demo site does not appear to have this issue.

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
No relevant errors in error_reports
```

**Comment by SchrodingersGat** [comment]
This may simply be that your [browser cache is not updated](https://docs.inventree.org/en/stable/faq/#feature-x-does-not-work-after-update), and is using old javascript. Try doing a hard refresh of your browser to ensure you are getting the new javascript files

**Comment by bberg115** [comment]
Thanks, that was the issue!

Sorry, this was seen by multiple users so I assumed it was server side.
