### ISSUE TITLE
Price range for part not calculated (after unknown actions with db)

### ISSUE THREAD

**Issue by alxrMironov** [inventree/InvenTree#5853]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Part have a stock with purchase price.
Internal prices is disabled (all two options).
Stock pricing is enabled.

Price range value for part is not calculated. The "-" is displayed. BOM based on part is calculated partially with "! incomplete" message.

Many parts are affected, but not all. 

### Steps to Reproduce

There is no way to reproduce this.

We had issues this summer while attempting to update to 12.x version.
Also we had issues with migration from SQLite to postgreSQL.
I suspect that this might have happened during DB migration long time ago... Nobody did check this, due to zero errors after the migration.

### Expected behaviour

Price range depends on stock price.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.7
Django Version: 3.2.19
Commit Hash: 6563b4c4
Commit Date: None
Commit Branch: 0.12.x
stable
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
In the pricing view you can manually select "update pricing" - does this result in the part pricing being updated correctly?

**Comment by alxrMironov** [comment]
> In the pricing view you can manually select "update pricing" - does this result in the part pricing being updated correctly?

Nope. Pricing->Refresh doesnt work.

**Comment by SchrodingersGat** [comment]
Can you please provide a screenshot of your "pricing settings" screen, as well as potentially some screenshots detailing the problem. Please redact any sensitive data

**Comment by alxrMironov** [comment]
> Can you please provide a screenshot of your "pricing settings" screen, as well as potentially some screenshots detailing the problem. Please redact any sensitive data

https://imgur.com/KdSBUUf

**Comment by SchrodingersGat** [comment]
And a screenshot of the "pricing" screen for a sample of affected parts?

**Comment by alxrMironov** [comment]
> And a screenshot of the "pricing" screen for a sample of affected parts?

https://imgur.com/DxpttG3
https://imgur.com/NwSU7tQ
https://imgur.com/vm5AyuZ

Hope it helps.

**Comment by SchrodingersGat** [comment]
> Part have a stock with purchase price.

Ok, so the purchase pricing only works if the stock items are linked to a purchase order. As your stock items are not linked to a purchase order, the "purchase price" field does not get calculated..

Probably an oversight in the code - that stock items with a price but without a linked purchase should be included in pricing too. But, for now, that's why it is not workin

**Comment by SchrodingersGat** [comment]
@Mimosa-oceanis please check the values of the settings shown below:

![image](https://github.com/inventree/InvenTree/assets/10080325/6df891b5-838f-4366-9aeb-bb31e51c107a)

**Comment by Mimosa-oceanis** [comment]
> @Mimosa-oceanis please check the values of the settings shown below:
> 
> ![image](https://private-user-images.githubusercontent.com/10080325/286463026-6df891b5-838f-4366-9aeb-bb31e51c107a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTM3NjYsIm5iZiI6MTcwMTM1MzQ2NiwicGF0aCI6Ii8xMDA4MDMyNS8yODY0NjMwMjYtNmRmODkxYjUtODM4Zi00MzY2LTlhZWItYmIzMWU1MWMxMDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE0MTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTEwMWM5ZTQ3YWJmNjg1ZDZiMDdkNTk0NTJkNzdkOWE3MGZhZTBhNTBiODA5MGQzMDg5YTllMGVlMDA1NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBoPtSs-mpIaa6HYF2wYGTAr5-UFGL2YaZlfH_gDNyU)

@SchrodingersGat thank you. It was effectively the problem. 
Sorry for that. 

Best regards

**Comment by matmair** [comment]
@Mimosa-oceanis @alxrMironov can we close this or is this still un-adressed?

**Comment by alxrMironov** [comment]
> @Mimosa-oceanis @alxrMironov can we close this or is this still un-adressed?

As far as i know it is not. So still actual.

**Comment by alxrMironov** [comment]
Ok, im double checked it now. 

> Ok, so the purchase pricing only works if the stock items are linked to a purchase order.

Its not. Today im create PO for some items, what previously was "inserted by hand" and still havent price in BOM and in price range.

**Comment by alxrMironov** [comment]
![image](https://github.com/inventree/InvenTree/assets/95591555/6227a554-28f9-4a36-84d5-6ef3c74db261)

**Comment by alxrMironov** [comment]
> @alxrMironov if you click on the "pricing" tab for that part and then press "recalculate pricing" does anything happen?

We have found the issue - we have custom currency "Russian rubble" and exchange API is dead (we have 12.7). So i think update will fix this.

**Comment by SchrodingersGat** [comment]
@alxrMironov happy to close this issue then?

**Comment by alxrMironov** [comment]
> @alxrMironov happy to close this issue then?

The issue is still exists after update to 13.3
The exchange plugin sync seem not to fire. 
![image](https://github.com/inventree/InvenTree/assets/95591555/e035fa70-583c-4112-b0b2-8df340c05554)

**Comment by alxrMironov** [comment]
Ahh. We have found the issue. RUB is missing in frankfurt app =)

**Comment by SchrodingersGat** [comment]
@alxrMironov ok, that's unexpected :) So we probably have to:

- Provide a way of handling the case where a particular currency is not supported by the exchange
- Implement a different exchange plugin (if you have access to a currency exchange which supports RUB)
- Allow manual adjustments of exchange rates on the server

**Comment by alxrMironov** [comment]
> @alxrMironov ok, that's unexpected :) So we probably have to:
> 
> * Provide a way of handling the case where a particular currency is not supported by the exchange
> * Implement a different exchange plugin (if you have access to a currency exchange which supports RUB)
> * Allow manual adjustments of exchange rates on the server

Manual adjustments seems to be already implemented. But you cant create new exchange rate.
For i just made a dirty hack in plugin to create USD\RUB exchange.
