### ISSUE TITLE
Purchase Order Report Documentation - Supplier Part Info

### ISSUE THREAD

**Issue by bberg115** [inventree/InvenTree#5893]
### Body of the issue

The current documentation lists "part" twice for Purchase Order Reports. I tried "line.supplierpart", "line.supplier_part", and "line.supplier.part" without any success.

Source: "Lines" table https://github.com/inventree/InvenTree/blob/master/docs/docs/report/purchase_order.md

<html>
<body>
<h4 tabindex="-1" id="user-content-lines" dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 16px; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(203, 218, 230); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(10, 14, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a class="heading-link" href="https://github.com/inventree/InvenTree/blob/master/docs/docs/report/purchase_order.md#lines" style="box-sizing: border-box; color: unset; background-color: transparent; text-decoration: none; text-underline-offset: 0.2rem;">Lines<svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg></a></h4><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(203, 218, 230); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(10, 14, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Each line item have sub variables, as follows:</p>

Variable | Description
-- | --
...| ...
part | The supplier part to be ordered
part | The supplierpart object that the build references

</body>
</html>

**Comment by SchrodingersGat** [comment]
@bberg115 it looks like the docs are not quite correct. Please confirm that the following should work:

```html
{% raw %}
{% for line in lines %}
SKU: {{ line.part.SKU }}
Part Name: {{ line.part.part.name }}
{% endfor %}
{% endraw %}
```

You can reference [this example report](https://github.com/inventree/InvenTree/blob/master/InvenTree/report/templates/report/inventree_po_report_base.html)

**Comment by bberg115** [comment]
Perfect. That worked.

**Comment by SchrodingersGat** [comment]
Thanks @bberg115  - I'll fix the errors in the documentation
