### ISSUE TITLE
Supervisor doesn't start automatically on boot

### ISSUE THREAD

**Issue by FireDeveloper** [inventree/InvenTree#5903]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [X] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Dear devs,
I am trying the bare metal installation on ubuntu server 20.04 with MySQL db and debug True.
Everything works fine up to step with "sudo supervisord". (I can log in, add parts, etc...) and supervisor is functional at :9001
My only issue is that Supervisor doesn't automatically start on system reboot.
Here is my supervisord.conf [supervisord.txt](https://github.com/inventree/InvenTree/files/13328008/supervisord.txt)
Is some other steps that I have to do to register automatically startup?

### Steps to Reproduce

Followed this steps https://docs.inventree.org/en/stable/start/install/
And this https://docs.inventree.org/en/stable/start/bare_prod/

**Comment by SchrodingersGat** [comment]
Something [like this](https://medium.com/@mohammedhammoud/how-to-automatically-start-supervisor-on-boot-350aeccf5f7a) perhaps?

**Comment by SchrodingersGat** [comment]
@FireDeveloper glad you got it working :)
