### ISSUE TITLE
Allocated stock appears twice in the stock item search

### ISSUE THREAD

**Issue by HannesMorre** [inventree/InvenTree#5915]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When a stock item is partially allocated to 2 different build orders, they appear twice in the stock item search list if the filter for "is allocated" is set to true.
![image](https://github.com/inventree/InvenTree/assets/71696745/9e5663dc-e9ec-49a9-bb3a-f8a266be5572)

### Steps to Reproduce

1. Create a stock item
2. Create 2 build orders of that include the part of which you created a stock item
3. Assign half of the stock item to each build order
4. Go to stock
5. Go to stock items
6. Apply the filters "in stock = true" and "is allocated = true"

### Expected behaviour

I expect to only see each stock item once in this list OR if they are shown multiple times (for each build order it is assigned to) also show the build order it is assigned to in this list.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.7
Django Version: 3.2.19
Commit Hash: 6563b4c
Commit Date: 2023-09-16

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.4.0-165-generic-x86_64-with-glibc2.36
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@HannesMorre thanks for reporting. A pretty simple fix, surprised that this has gone unnoticed for so long!
