### ISSUE TITLE
[FR] Larger extension of "Default location" functionality

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#5928]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

You can mark any part with a default location p.t.

However, there is no connection from a location to see which items have their default set to it.
There is no way to choose to transfer a stock item to its default location.
There is no way to easily add a newly arrived stock item to its default location from a Purchase Order

### Suggested solution

Integrate the concept of default locations more thoroughly throughout the Stock experience.
If a part has a default location, allow for any stock item to be transferred to this location with a simple click.
Allow all PO's to be added to the default location of the Part upon reception if a box has been ticked
Possible more ways to use default locations to smooth out workflows.

### Describe alternatives you've considered

Opening tabs
Checking default locs
Typing out what you just read

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@LavissaWoW this all seems reasonable. Given our focus on the new react interface, and that this will require a lot of user interface work, I'd like to see this implemented for the new UI

**Comment by LavissaWoW** [comment]
@SchrodingersGat I agree. I'm happy to work with P-UI for Frontend improvements.
However. I haven't looked a tremendous amount into the dual existence of C and P UI, so: How do I activate the current React codebase on any given installation?

**Comment by SchrodingersGat** [comment]
@LavissaWoW the easy way to get started with the new frontend is:

1. Setup an [InvenTree devcontainer](https://docs.inventree.org/en/stable/develop/devcontainer/)
2. Run the server
3. In a new terminal, type `invoke frontend-dev` - this will run a development server for the frontend

**Comment by LavissaWoW** [comment]
@SchrodingersGat This was a real headscratcher...
I've made sure to run `invoke frontend-compile`, but I'm just served with an eternally loading white entry page.
Site title is InvenTree, skeleton code def shows I'm getting served the initial React code before any loading is performed.

If I leave it idle for long enough, the main Server process spits out this: 

```
Created new API token for user 'admin' (name='inventree-web-app')
[21/Nov/2023 20:19:23] "GET /api/user/token/?name=inventree-web-app HTTP/1.1" 200 114
Background worker check failed
Email backend not configured
InvenTree system health checks failed
[21/Nov/2023 20:19:30] "GET /api/ HTTP/1.1" 200 1145
[21/Nov/2023 20:19:31] "GET /api/generic/status/ HTTP/1.1" 200 5851
Background worker check failed
Email backend not configured
InvenTree system health checks failed
[21/Nov/2023 20:19:32] "GET /api/ HTTP/1.1" 200 1145
[21/Nov/2023 20:19:32] "GET /api/generic/status/ HTTP/1.1" 200 5851
Background worker check failed
Email backend not configured
InvenTree system health checks failed
[21/Nov/2023 20:19:33] "GET /api/ HTTP/1.1" 200 1145
[21/Nov/2023 20:19:33] "GET /api/generic/status/ HTTP/1.1" 200 5851
Background worker check failed
Email backend not configured
InvenTree system health checks failed
[21/Nov/2023 20:19:34] "GET /api/ HTTP/1.1" 200 1145
[21/Nov/2023 20:19:35] "GET /api/generic/status/ HTTP/1.1" 200 5851
```
Then the login page finally loads.

For every login attempt, it looks like one worker process is started and promptly terminated .
Client side I'm served these two:

Login failed
Error fetching token from server.

Login failed
Check your input and try again.

In case it matters:
```
InvenTree - inventree.org
The Open-Source Inventory Management System


Installation paths:
Base        /workspaces/InvenTree
Config      /workspaces/InvenTree/dev/config.yaml
Media       /workspaces/InvenTree/dev/media
Static      /workspaces/InvenTree/dev/static

Versions:
Python      3.10.10
Django      3.2.23
InvenTree   0.13.0 dev
API         152
Node        v20.9.0
Yarn        1.22.19

Commit hash:dabd95d
Commit date:2023-11-21
```

**Comment by matmair** [comment]
@LavissaWoW you need a running backend server additionally to the frontend server

**Comment by wolflu05** [comment]
Can you please also share
1. what URLs you open in the browser
2. how the server list in the frontend is configured (click on the server icon on the login page, then edit)

**Comment by LavissaWoW** [comment]
@matmair I'm running via the devcontainer "run and debug" tab, with the "Inventree Server" target. Then I separately ran `invoke frontend-dev` from a separate terminal. As the classic UI on port 8000 seems to work, I would presume the backend is running as expected.

@wolflu05 http://localhost:8000 and http://localhost:5173, and ditto the same using 127.0.0.1.
Info from login page: 
```
http://127.0.0.1:5173/
Version: 0.13.0 dev
API:152
Name: InvenTree Demo Server
State: worker (4), plugins (9)
```

**Comment by wolflu05** [comment]
Do you see any errors in the browser console?

**Comment by wolflu05** [comment]
The entry page for PUI should be at http://localhost:5173/platform/

**Comment by LavissaWoW** [comment]
No messages in the console.
The root path redirects to `platform/login` so that's not the issue

Upon an attempted login, the backend server gives this terminal ouptut:
```
Created new API token for user 'admin' (name='inventree-web-app')
[21/Nov/2023 20:45:23] "GET /api/user/token/?name=inventree-web-app HTTP/1.1" 200 114
```

The frontend gives me these in-GUI: 

````
Login failed
Error fetching token from server.
```

```
Login failed
Check your input and try again.
```

**Comment by LavissaWoW** [comment]
Oh, and as I keep forgetting to include...
Having `invoke frontend-dev` running is absolutely MAXing CPU usage on the devcontainer.
The container has a constant CPU usage of about 700+%/800%, so it's constantly stressing my CPU to its max.

**Comment by wolflu05** [comment]
On which platform do you run your dev container? WSL?

**Comment by wolflu05** [comment]
What do you see in the network tab happening?

**Comment by LavissaWoW** [comment]
Yeah, it's being run through WSL. The whole Docker experience on Windows relies on WSL afaik.
My system itself is 5-6 years old, Old though it is, its still a top-end i7 for it's time with 32 GB of RAM. 
Now. WSL has decided to occupy all my remaining RAM for itself (happnes sometimes), but Docker Desktop proudly proclaims it's only using 1.52GB/15.24GB it has allocated to itself. So even tho it sucks up my RAM atm, it has given itself plenty to do anything it needs.

Where it just didn't load anything else than skeleton code for TS React earlier, after a few restarts, it actually loads the login page. Albeit extremely slow. Takes about 30 secs to load all components according to the network graphing on Dev Tools.

Login attempts seem to not return a response from the backend to the frontend.

**Comment by matmair** [comment]
Sounds like a windows/node issue. I had very bad file system performance with windows before I switched to Debian/macos

**Comment by wolflu05** [comment]
Try changing the host to :8000 in the host list (where you saw the plugin and worker in red/green). Then there is no proxying of the requests from vite to the Django backend. 

I would also try disabling polling for vite, this could drastically reduce your cpu load. You find this option in the vite config file. By default that is enabled if it detects WSL, because there is no fs watch. The cost then would be that you don't have hot reloadong anymore, but if you have such performance problems, this could help.

**Comment by LavissaWoW** [comment]
There we go. Seems the FS polling was absolutely killing any and all communication and performance.
Now, my CPU is old, of course. But obv. the FS polling is sucking some intense juice using WSL.

Fun fact: I wanted to check if I had 8000 or 5173 in the host list, So I went ot log out. I'm not allowed to log out now, hahaha. 

```
Logout successful
See you soon.

Already logged in
Found an existing login - using it to log you in.
```

**Comment by SchrodingersGat** [comment]
> Fun fact: I wanted to check if I had 8000 or 5173 in the host list, So I went to log out. I'm not allowed to log out now, hahaha.

I have noticed this sometimes too - can you please grab some screenshots / logs and raise a new issue about this?

**Comment by SchrodingersGat** [comment]
@LavissaWoW based on the above, do you think that our documentation for frontend dev using the devcontainer is sufficient, or needs some tweaking?

**Comment by LavissaWoW** [comment]
@SchrodingersGat  There's def things that could be clarified. I'll read back the docs and check logs after getting a good night's sleep :)

**Comment by LavissaWoW** [comment]
The devcontainer docs are reasonably well set up to where you can get a devcontainer up and running.
What I don't see though is information telling the user they still need to run `invoke update/install` and `invoke setup-test --dev`/`invoke setup-dev` to get a properly working dev setup. This might be wise to add, or link to the general setup page.

With regards to frontend dev, I can't really find any documentation at all.
I pieced it together by viewing `tasks.py` and finding the `invoke frontend-compile` task.
My suggestion would be to add a temporary(?) docs page under development going through the steps needed to get the Frontend dev server up and running. Maybe also some warninga about Windows, WSL and polling etc. 

I can create a PR for this and write down some info based on what I had to research because the docs didn't say.
Or if someone else wants to do a write-up of the frontend dev info, let me know.

**Comment by SchrodingersGat** [comment]
> I can create a PR for this and write down some info based on what I had to research because the docs didn't say.

@LavissaWoW that would be *greatly* appreciated. The docs for frontend dev are almost non-existent so please feel free to add a new page for that!

**Comment by LavissaWoW** [comment]
Not stale
