### ISSUE TITLE
[FR] Allow week number to be used in auto batch generation

### ISSUE THREAD

**Issue by lfg-seth** [inventree/InvenTree#5933]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I want to auto generate batch codes with the year and week number. (Common in manufacturing). For example, today would be 2023-46. 

I would like to develop this and think I know how. I just need to be pointed in the right direction. 

### Suggested solution

In the backend where the {{year}} is replaced with the actual year, add a "week" or "weeknumber" option that will replace with the week number. 

```python
# Shamelessly stolen from chat gpt
from datetime import datetime
current_date = datetime.now()
current_week_number = current_date.isocalendar()[1]
current_week_number
#46
```

### Describe alternatives you've considered

This could also be done by writing a custom validation mixin I think? But that seems like a lot of work for a one off, especially when others might benefit from this too. 

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
We are just passing in values to a context so this should be a 1-2 LoC change. I think we would be happy to merge the suggested function.

https://github.com/inventree/InvenTree/blob/a0841088aec8422771c6b273e03b3573fc14fc10/InvenTree/stock/models.py#L301-L308

**Comment by SchrodingersGat** [comment]
@lfg-seth would you be able to submit a PR to implement this?
