### ISSUE TITLE
"Default Location" of a category not propagated to parts inside the category

### ISSUE THREAD

**Issue by mjktfw** [inventree/InvenTree#5938]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The optional "Default Location" parameter filled in when creating new categories, is not propagated to parts in this category. No matter whether the part is newly created, or we assign it to the category afterward.
Contratry, the "Default Location" for a part, is properly transferred to newly created stock items.

The same behavior can be reproduced using web interface or admin panel (both import and manual entry)

It might be, that I'm somehow misunderstanding the "default location" concept here, however I did not find any reference in Inventree docs.

### Steps to Reproduce

1. Create a "New Location"
2. Create "New Category" and fill-in the location.
3. Create "New Part" under the category. The default location for a part is not set.
4.  Creat a stock item of the part. It is not assigned to any location

### Expected behaviour

The newly created parts should have "Default Location" prefilled based on the "Default location" for the category.
Same logic might be applied for new subcategories.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

InvenTree-Version: 0.12.8
Django Version: 3.2.19
Commit Hash: a7487ff
Commit Date: 2023-10-03

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-13-amd64-x86_64-with-glibc2.36
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
As far as I am aware we never had this functionality, this seems to be a feature request. Thoughts @inventree/triage @inventree/maintainer ?

**Comment by SchrodingersGat** [comment]
What I would suggest (as a new feature) is to extend the current implementation of how a "default location" is determined for a part.

1. If the *part* instance specifies a default location, use that
2. If the *category* of the part specifies a default location, use that
3. Walk up the *category tree* for the part, and look for the first specified default location

The *default location* value should not be copied from the category to the part - this would cause a lot of issues if the part is moved to a different category or if the category values change. Rather it should be calculated when required.

**Comment by mjktfw** [comment]
> As far as I am aware we never had this functionality, this seems to be a feature request

Then it seems to be only partially implemented or presented in a bit misleading manner, as the field inside a category creation form is commented as:
> Default location for parts in this category

The category will then have "Default Location" property, which is not further propagated. So now should I assume this is just a hint for a user?

> The default location value should not be copied from the category to the part
I second that. Especially as the part might also inherit from another part on duplication, or from a part template as a variant. 
Currently, in order to achieve similiar effect, for each category I create dummy part templates, with a default location already set.

**Comment by LavissaWoW** [comment]
I've been thinking of interweaving the "default location" fields closer with the user experience for a while now, and I'm about to start working on a few improvements to the system in #5928 

 I could just as well address this too if there are and concrete ideas for it.

**Comment by SchrodingersGat** [comment]
@LavissaWoW that's great, hit me up if you need any assistance.

One thing to keep in mind - if we traverse up the category tree to determine the "default location" (for a part which does not have one explicitly set) we will need a pretty complex queryset annotation do make that perform efficiently.

**Comment by LavissaWoW** [comment]
@SchrodingersGat My thoughts here would be to do it like any given Stock Item created from a Part page.
Basically, in the creation modal, the default location will be preset. This preset comes from the category or parents, depending.

The only frontend work required in such an implementation is to update the creation modal if the category is changed. (Issuing a new API call, and repopulating form fields accordingly)

The user will then be able to see that the default location has been filled, and can then choose to override this. 

Would this work for you, @mjktfw ?

**Comment by SchrodingersGat** [comment]
@LavissaWoW handling this in the front-end forms would work. We would need a method of "traversing" up a part category tree to find the correct default location, and this method must be available to the API.

**Comment by mjktfw** [comment]
> Would this work for you, @mjktfw ?
Surely will do, thanks a lot. 

Regarding the frontend, I guess this would require to update the form and hoc, as we're assigning a part to a category in the same form we choose its location

**Comment by LavissaWoW** [comment]
Not stale

**Comment by LavissaWoW** [comment]
@mjktfw Here's what I'm planning:
For any given part, if the `default_location` is `null`, the part's category tree will be traversed until a `default_location` is found. 
This is what will be sent to the frontend. The part itself however still has `null` as its `default_location`. 

This enables the ability to choose a new location for the category, and have all parts under that category use that location if they don't have one defined themselves. 

To put it into pseudocode:
```
if not part.default_location:
  render part.traverse_category_tree use first default_location != null
```
Visually, it will look like any part with this setup "has" a default_location, but it's actually just inserted during runtime when fetching the object from the server.
