### ISSUE TITLE
[Review] "full_name" for Part

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5942]
After some simple profiling, I have found that the `full_name` Part field adds a significant overhead to the API. Even though it does not require many database hits, the rendering function for `full_name` does take a significant chunk of time to execute - and this time accumulates with the number of parts in the query.

### Query Results

Using the demo dataset, performed the following queries: 

| Query | Without `full_name` | With `full_name` |
| --- | --- | ---|
| `/api/part/?format=json` | 1.91s |  > 30 seconds |
| `/api/part/?format=json&limit=100` |  620ms | 1.34s |
| `/api/part/?format=json&limit=10` | 230ms | 350ms |

Note that in both cases the number of actual database hits was the same.

Clearly this needs to be optimized.

The original intent for `full_name` was to solve a specific problem on my end - it would be interesting to know how this field is *actually* being used. Perhaps removing this field is an option? (Although this would touch a *lot* of code. A cleaner option would be to improve the rendering efficiency)

**Comment by matmair** [comment]
If I see it correctly there is a Template instantiation every time - maybe this can be solved by caching/reusing the Template?

We could write the full_name to the cache for example.

**Comment by SchrodingersGat** [comment]
I think that caching the template caches the *compiled* template - including the contents? So for a list query set this does not help us...

Digging deeper, the default "part name" implementation uses the following template string:

```
{% raw %}
{{ part.IPN if part.IPN }}{{ ' | ' if part.IPN }}{{ part.name }}{{ ' | ' if part.revision }}{{ part.revision if part.revision }}
{% endraw %}
```

This takes around `5ms` to render.

If we used a simpler approach:

```python
entries = [self.IPN, self.name, self.revision]
return ' | '.join([e for e in entries if e])
```

This takes around `2us` to render.

I think that templates are just... slow?

I would propose that we consider replacing the "templated" implementation with a more pythonic approach, and then potentially expose this to the plugin system if people want more customisation?

**Comment by wolflu05** [comment]
Maybe we need to improve the templating. I use jinja2 for my bulk plugin and hadn't any performance issues. What about trying that? The syntax is very similar, but if the template is compiled it is pretty fast.
```py
from jinja2 import Environment
import time

env = Environment(variable_start_string="{{", variable_end_string="}}")

def test(reps):
    t = env.from_string('{{a}} | {{b if b else ""}} part') # this compiles the template into a python function which takes the context as an argument and that's why it is pretty fast
    start = time.time()
    for i, x in enumerate(range(reps)):
        x = t.render(a=i, b=x)
        # print(x)
    end = time.time()
    return (end-start)/reps

print(test(100000)) # 9.491140842437743e-06 = 9.49us
```

**Comment by SchrodingersGat** [comment]
@wolflu05 thanks for the tip - I'll check that out
