### ISSUE TITLE
[FR] Audit log / audit trail

### ISSUE THREAD

**Issue by Phoenixian** [inventree/InvenTree#5945]
### Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find a similar feature request

### Problem statement

This feature request is related to this post #5932 
Inventree does not have an audit trail for tracking user actions.

### Suggested solution

For the purposes of monitoring and control, particularly in a professional environment, each action of a user should be traced: addition to stock, deletion to stock, addition of a reference, new order, receipt of order, etc. I am aware of the important work, but this could be added by priority, in particular on the addition or deletion to stock for an initial follow-up.

### Describe alternatives you've considered

This feature is absent now, so I have no alternative.

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/5945">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/5945/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/5945/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@Phoenixian thanks for raising the issue. This would be a fantastic addition to the project - and also a *lot* of work.

Potentially this would work well as a plugin - a lot of users who are looking for a "lightweight" setup might not want this behaviour

**Comment by miggland** [comment]
Possibly related: https://github.com/jazzband/django-auditlog
