### ISSUE TITLE
Django 3.X Upgrade

### ISSUE THREAD

**Issue by Zeigren** [inventree/InvenTree#595]
Now that Django 3.0 has been officially [released](https://www.djangoproject.com/weblog/2019/dec/02/django-3-released/) is there any plan to upgrade from 2.2?

**Comment by SchrodingersGat** [comment]
There are a couple of required python modules that have not been upgraded yet, meaning that there are some incompatibilities. I tried updating to Django 3.0 but without success - until these other packages are also updated.
