### ISSUE TITLE
Inventree 0.12.9 Docker image missing

### ISSUE THREAD

**Issue by hvraven** [inventree/InvenTree#5951]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Just wanted to update an existing installation and had to find out that the latest release 0.12.9 did not make it to the Docker hub. Would be great if it could be added.

### Steps to Reproduce

docker pull inventree/inventree:0.12.9

### Expected behaviour

I get an image

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.12.9

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@hvraven thanks for reporting - looks like the docker build broke.. I will see if I can get a miminal fix in and release

**Comment by SchrodingersGat** [comment]
Closing this - `0.12.9` is skipped but replaced by `0.12.10`
