### ISSUE TITLE
Inventree Demo - Login Issues

### ISSUE THREAD

**Issue by bberg115** [inventree/InvenTree#5964]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Appears the both "allaccess" and "engineer" accounts are not setup correctly. I cannot login with the provided usernames/passwords from the demo.html.

https://inventree.org/demo.html

### Steps to Reproduce

1. Visit demo.html
2. Select login on allaccess or engineer (or type info on login page of demo site)

### Expected behaviour

To be able to login, like reader and engineer accounts

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

[0.13.0 dev](https://github.com/inventree/InvenTree/releases)

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by bberg115** [comment]
![chrome_bzP4vCgge2](https://github.com/inventree/InvenTree/assets/17869135/b08f3027-63f0-4227-bb53-e06a66d065ce)

**Comment by SchrodingersGat** [comment]
@bberg115 looks like those user accounts have been deleted. They will be restored when the dataset resets within the 24hr period
