### ISSUE TITLE
BOM Price Range Multiplying

### ISSUE THREAD

**Issue by bberg115** [inventree/InvenTree#5965]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The total "price range" of a BOM is increasing everytime you expand a subassembly. It appears that the subassembly is being double counted when you click the "Load BOM for subassembly" button.

This is consistent across multiple BOMs but cannot be reproduced on the DEMO.

![image](https://github.com/inventree/InvenTree/assets/17869135/d6566d6b-a5a6-4120-8782-3579606817b8)

Item M1-00036 is expanded and the $2.3 is added to the total price range at the bottom.
![image](https://github.com/inventree/InvenTree/assets/17869135/2b0ba19c-e3d5-4f9c-8ea4-8b69e5d0b55b)

### Steps to Reproduce

1. Open part with BOM that is nested with >1 depth
2. Note price range of BOM-1
3. Expand child BOM-A
4. Note increase in price range of BOM-1

### Expected behaviour

Pricing should not change.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

0.12.8

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@bberg115 thanks for reporting - this issue has actually already been closed in https://github.com/inventree/InvenTree/pull/5721

This fix will be available in the upcoming `0.13.0` release :)

**Comment by bberg115** [comment]
Sorry, I didn't see that. Thanks!
