### ISSUE TITLE
[QUESTION] Links in part stock table for "Part" link to part, "Stock" link to stock item

### ISSUE THREAD

**Issue by Alex9779** [inventree/InvenTree#5967]
This has been very confusing for me when I started working with InvenTree a few weeks ago.

If you are in a part and look at the stock you have a table with "Part Stock" but the links in the very first column named "Part" link to the part again which is somehow correct if you consider the title but also not expected.
Same for the global list of "Stock items".

Is that intentional?

IMHO it is a bit misleading, in both cases I am watchiing a list of "Stock Items" and I click the for me main entry of that list and land on something different.

**Comment by SchrodingersGat** [comment]
To clarify - you would expect that in a table of stock items, clicking on the link takes you to the *stock item* and not the parent *part*?

For reference, this is the approach in the new UI: 

![image](https://github.com/inventree/InvenTree/assets/10080325/4345c1c2-8df8-488d-a5b1-546c540e16aa)

![image](https://github.com/inventree/InvenTree/assets/10080325/51401c4f-5e40-45f3-b877-f683699c90a8)

**Comment by Alex9779** [comment]
> To clarify - you would expect that in a table of stock items, clicking on the link takes you to the _stock item_ and not the parent _part_?

Yes that's it. As I said the heading of the table collides with that because it indicates "Part" so that's why I asked if that is intentional.
But looking at the stock list of a part this makes no sense IMHO because you look at the part and if you click in the table of stock items you get to the part again, nothing changes...

**Comment by Alex9779** [comment]
So in the new UI you wanna say it is what I expect, you click a line and get to the stock item?

**Comment by wolflu05** [comment]
I was initially also confused by this. But yes, in PUI it is like you requests, you can check it out already at https://demo.inventree.org/platform

**Comment by Alex9779** [comment]
Cool thanks, so I am closing and wait for the new UI to be released...
