### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by mtrazakhan** [inventree/InvenTree#597]
I am learning django and I clone this https://github.com/inventree/InvenTree  project from github and trying to add new app as user management and want to show on header but having issue in routing. Can anyone tell me how can I do this.

**Comment by mtrazakhan** [comment]
I Created a new module user management with current setup and tried to add 
Add tab in left navigation named with user management.  
List Page for users with required fields  are :
In top of the page add user button
Sr No
Full Name
Email
Mobile number
Role
Edit
Action (Note : block/unblock the user account
     3. Create form for add users.
     4. Send random password to email of user after create any user.
     5. Each user can able to login on same panel with there provided credential.
     6. Use JWT token instead of session. 

But having issue with routing how can I add user management app on navbar

**Comment by SchrodingersGat** [comment]
Hi @mtrazakhan I'm not 100% sure what you're looking for here. Are you needing to know how to link to your new page from the main page?

Do you have a branch on github that I could look at?
