### ISSUE TITLE
Trailing zeros disappear

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#598]
I think the following screen shots make it pretty clear what is happening.

511 == 511

<img width="889" alt="Screen Shot 2020-01-01 at 17 34 23" src="https://user-images.githubusercontent.com/36831279/71648646-f39c0a00-2cd4-11ea-8526-eeb9cffa916d.png">

51 != 510

<img width="898" alt="Screen Shot 2020-01-01 at 17 34 46" src="https://user-images.githubusercontent.com/36831279/71648647-f39c0a00-2cd4-11ea-9c59-91cad657be62.png">

I accidentally filed this bug in 'inventree.github.io' first and moved  it to here once I realized.

**Comment by SchrodingersGat** [comment]
Thanks for pointing this out @a7hybnj2 - fixed in https://github.com/inventree/InvenTree/pull/601

**Comment by a7hybnj2** [comment]
@SchrodingersGat Thanks! And so quickly! I will update ASAP. Did you have a chance to see #599? When I can receive a full order then this will be %100 my solution going forward for inventory.
