### ISSUE TITLE
LDAP is in the docs but it's not released yet

### ISSUE THREAD

**Issue by mechanarchy** [inventree/InvenTree#5998]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

LDAP support (#5226) is available in the [public documentation](https://docs.inventree.org/en/latest/start/advanced/#ldap), but it's only in the `master` branch and not in any of the released Docker image tags. I am specifically targeting 0.12.10, which I initially thought would support LDAP as it was tagged after the LDAP PR was merged; but no.

I don't have time right at the moment to update the docs, but at the very least if it can indicate it's an unreleased feature that should hopefully stop other people having the same confusion.

### Steps to Reproduce

1. Follow the Docker Production installation steps
2. Follow the LDAP setup instructions
3. Wonder why nothing works

**Comment by mechanarchy** [comment]
Actually I think this kind of issue will be more easily solved in the version-specific documentation support in https://github.com/inventree/inventree-website/pull/177

**Comment by matmair** [comment]
You are linking to latest docs, the feature is available in latest.  There is a version indicator on the right hand side of the docs.

**Comment by mechanarchy** [comment]
Ah, my apologies! Thanks @matmair.

**Comment by matmair** [comment]
No problem, the indicator is pretty small on mobile devices.
