### ISSUE TITLE
[FR] Parametric Part Name generation based on part category

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#6007]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

A lot of parts within electronics, but also mechanical stuff like fasteners tend to be named based on their specifiations.

A general capacitor would earn its name based on capacitance, type , footprint, and so on.
And in general, that's what you wind up doing. The part's name is a mirror of its attributes.
As names are only generated based on part model fields, you have to write out the part name anyway.

### Suggested solution

Implement a feature that allows for any given category to compose part names based on its parameters. 

In such a solution, on part creation, the part name will not be writable, The part category holds a boolean activate/deactivate and a pattern string. Thus of the category has this feature active, you are not allowed to independently name your part.

Given this system, you can utilize part parameters to define a name. The format is defined on the category, replacing the normal part name generation. The string for a capacitor (based on the demo dataset) would then be: "C_{capacitance}_{footprint}"

### Describe alternatives you've considered

The alternative is as the system currently is. If the parameter is integral to the part, you have to both define the parameter AND write it out in the part name. This makes part names and/or parameters prone to errors where these are considered to be identical.

A typo of a capacitor's capacitance on the part name will not show up in the parameter table, thus making the part's name not match up with its sorting in the table.

### Examples of other systems

Many online stores already use this type of part naming in their frontend. 

### Do you want to develop this?

- [X] I want to develop this.

**Comment by LavissaWoW** [comment]
This is some ways down my list, given my other two features atm.
but I wanted to get the feature written down and get some feedback.

**Comment by SchrodingersGat** [comment]
@LavissaWoW I think I understand what you are going for here. To me this feels like a great feature for a plugin, as it is a pretty narrow scope. It could be achieved quite easily with a plugin which renames the part based on a category parameter when the part parameters change

**Comment by LavissaWoW** [comment]
Fair point. I could envision it in core, but I agree the scope is narrow. Only applying to certain types of electronic components, and standardised fasteners like screws, nuts, etc, etc.

Maybe this'll be my first toe-dipping into plugin development :)
