### ISSUE TITLE
[Bug/PUI] Table filters are ignored when initially loading a page URL

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#6009]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Tables are initially loaded with `null` as `pk` within PUI.
I've run this test on Part and Stock Item, and they both load an unfiltered table for their respective models.

### Steps to Reproduce

Based on the demo dataset

1. Make sure you have the "Parts" panel selected
2. Access http://localhost:5173/platform/part/category/13 (or your local version of this. category PK 13 at least)
3. This category has 57 items. but the total will be listed as 414.
4. Refresh, and it'll list it as 57.

I added this debug print to Stock Locations (/stock/location/7):
`console.log("Location:", location, "id:", id)`, and this is the output on hitting F5:

![image](https://github.com/inventree/InvenTree/assets/7506688/69bc4b42-f24d-4e97-8b0d-a928233c1adb)

The code passes `location.pk`, and that doesn't become available until after the first render of the table.

### Expected behaviour

API filters should be added on first load, not second. 

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

0.13.0 master commit f0f72a8742781495628ed09dfcf288061ff22071

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Thanks for reporting. Probably an issue with the hooks when loading the table. Do you want to look into this one?

**Comment by LavissaWoW** [comment]
@SchrodingersGat Yeah, I can have a look and find a fix.

**Comment by LavissaWoW** [comment]
Hmm.

So, what's going on initially is that 

```js
params={{
  location: location.pk ?? null
}}
```
is populating no `null`, as 

```js
<PanelGroup pageKey="stocklocation" panels={locationPanels} />
```
is read before the `useInstance` resolves. 
This makes `InvenTreeTable` send an API request with no category/location/etc parameter in the request.
As made evident by the following log entry when accessing `/stock/location/7`: 
`[30/Nov/2023 19:18:51] "GET /api/stock/?part_detail=true&location_detail=true&supplier_part_detail=true&limit=25&offset=0 HTTP/1.1" 200 32476`
So the resulting table populates using the entire unfiltered list of whatever the table displays. 
I don't have to elaborate what a large performance hit this can have on large InvenTree instances.

Unfortunately, even though InvenTreeTable gets an updated `pk` when the `useInstance` Promise resolves, it doesn't initiate an update of the table to the API. For this, you have ot toggle between the tabs on your given page. Thankfully, this allowed us to detect this bug.

I think a fix will have to involve passing the `instanceQuery` state all the way into `InvenTreeTable` to enable re-rendering on updating this. Adding a PR to illustrate my idea.

**Comment by SchrodingersGat** [comment]
@LavissaWoW has this issue been sufficiently addressed now?

**Comment by LavissaWoW** [comment]
@SchrodingersGat Yes. Link to the PR wasn't properly set up, I guess.
