### ISSUE TITLE
Inserting serial numbers is getting slower when having high number of stock items

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#6013]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I tried to migrate our 5 years of historical production data into the InvenTree with a python script using the InvenTree API.  I started to ran into sort of performance issues after inserting ~67K stock items (took a couple of day) what I thought worth to investigate before moving forward. A single request for creating a stock item with a single serial takes ~3s to complete now. It was not so slow at the beginning if I remember correctly, but now it started to be a bottleneck. 
(I am running InvenTree with MySQL on a notebook with reasonable performance (8th gen i9))

As a first idea I added some timing measurement here:
https://github.com/martonmiklos/InvenTree/blob/stockitem_save_performance_tracking/InvenTree/stock/models.py#L478

Which results the following for a single StockItem + serial insert:
```
Validate unique: 13.355768998735584 ms
Clean: 0.7472590077668428 ms
Update serial: 0.5881280085304752 ms
Super save: 837.7136269991752 ms
Validate unique: 15.880550010479055 ms
Clean: 0.6893499958096072 ms
Update serial: 0.5778909981017932 ms
Field update: 0.9629400010453537 ms
Super save: 624.8631559865316 ms
Tracking info: 1.3864210050087422 ms

```
The first thing what was strange for me that the StockItem::save got called twice from the API call
Here:
https://github.com/inventree/InvenTree/blob/master/InvenTree/stock/api.py#L898

And here:
https://github.com/inventree/InvenTree/blob/master/InvenTree/stock/api.py#L905

i do not have in depth knowledge on debugging such a problems with django+python (and maybe MySQL) so any hint/tip what I can look into/try would be welcome.

### Steps to Reproduce

-

### Expected behaviour

Adding a single serial number should be reasonably fast regardless to the stock item count in the system :)

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

Latest master

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
-
```

**Comment by wolflu05** [comment]
My assumption is that this is related to how MPTT handles tree objects. Because if you insert one element into a nested set datastructure, you need to increment the lft and rght values in all other stock items depending if they are only on the left or right. And because of that a nested set is not very performant for inserting. It would be good, if MPTT would offer some way of bulk inserting so that the increment task needs to be done only once and then a view nodes can be inserted. But other than that I have no idea how to fix that performance issue. 

I would be really interested in @SchrodingersGat experience with stock items on large instances, mine is not that big.

**Comment by martonmiklos** [comment]
Well I have managed to enable the SQL logging and yes quite a lot of SQL query got executed when doing a single serial number insertion:
https://pastebin.com/a4d6UKZj

**Comment by SchrodingersGat** [comment]
@martonmiklos you could try using a profiling tool (such as [cProfile.runctx](https://docs.python.org/3/library/profile.html#profile.runctx) ) to work out which parts of the code are taking up the most amount of time on one of these long-running requests. From there, we can dig down into the SQL that is being executed. But first we should find the higher level functions which are *calling* the SQL

**Comment by SchrodingersGat** [comment]
Using cProfile, it looks like the main culprit may be the `notify_low_stock_if_required` method. When a new stock item is created, we offload a call to notify low stock (after checking if this is required). This takes up a *lot* of time when there are many stock items in the database. Commenting out this method speeds up insertion significantly. Might be a good place to start :)

**Comment by SchrodingersGat** [comment]
Closed by https://github.com/inventree/InvenTree/pull/6051
