### ISSUE TITLE
Suggestion: Add 'qty' column to 'remove stock'

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#602]
I suggest adding a "quantity" column to the "remove stock" dialog.

When you click on a stock item, in my case it was one that had sub items. And use the option to 'remove stock' you get the following dialog.

<img width="1209" alt="Screen Shot 2020-01-02 at 11 12 34" src="https://user-images.githubusercontent.com/36831279/71677499-fe948000-2d50-11ea-91c5-3e9699e0f1ff.png">

It would be much easier to see next to each stock item the qty it has. If you enter a value that is outside the parameter you do get the following:

<img width="1200" alt="Screen Shot 2020-01-02 at 11 17 06" src="https://user-images.githubusercontent.com/36831279/71677696-7c588b80-2d51-11ea-9c68-62b5219761a9.png">

**Comment by SchrodingersGat** [comment]
Good suggestion - implemented in https://github.com/inventree/InvenTree/pull/604

**Comment by a7hybnj2** [comment]
@SchrodingersGat Thanks. I really want to start using this for primary but #599 is still hanging me up. Can you look at that?
