### ISSUE TITLE
[PUI] API urls need to be specified at two places

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#6025]
In my opinion the idea behind this function is good, but the issue with it is, that if adding an api path, I basically have to go to two different files and add something on two places. That slows down the quick development.  As the apiEndpoint function is just a huge switch case prefabricated building, why not just use an object with `key: url` and type the function accordingly. And then to allow strings, we add a second function that allows strings which gets called by the function which only allows ApiPaths. Because we cannot union `string` with choices. E.g. something like this:

```ts
export const API_PATHS = {
  "api-plugin-settings": "plugins/:plugin/settings/",
  // ...
}
export type API_PATH_TYPE = keyof typeof API_PATHS;

export function apiGenericUrl(path: string; ...) {
  // do  like before, but without the apiEndpoint call
} 

export function apiUrl(path: API_PATH_TYPE, ...args) {
  return apiGenericUrl(API_PATHS[path], ...args)
}
```

That way we would 
1. only need to change something at one place
2. only need to import the `apiUrl` function
3. have the possibility to use raw strings without mixing them

_Originally posted by @wolflu05 in https://github.com/inventree/InvenTree/issues/6012#issuecomment-1835614867_

**Comment by SchrodingersGat** [comment]
The split was (on my part) originally implemented to fix a circular import issue - separation of the functions was an easy way to get this working reliably. If you want to submit a PR to address this in the way you think it should be done, I'm happy to review :)

**Comment by LavissaWoW** [comment]
I've noticed that accessing the `api-doc` triggers a LOT of warnings about duplicate API endpoints.
From what I gather, it doesn't seem to like that the API paths are defined both as `endpoint/{id}/.*` and `endpoint/.*` saying these are identical in their natures. I was planning to have a look at it, but I wouldn't be surprised if this might be related.

**Comment by matmair** [comment]
@wolflu05 I think this was addressed now?

**Comment by wolflu05** [comment]
Yes, that's fixed. Thanks for the reminder.
