### ISSUE TITLE
Can not install on debian 12

### ISSUE THREAD

**Issue by tnemrap** [inventree/InvenTree#6036]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Installing InvenTree
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package inventree

sudo apt-get install inventree -y does not find any package.

### Steps to Reproduce

Install on debian 12

### Relevant log output

```bash
### Installer for InvenTree - source: inventree/stable
### Detected distribution: Debian GNU/Linux 12
### Installing required packages for download
### Getting and adding key
### Adding package source
### Updating package lists
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:4 http://security.debian.org/debian-security bookworm-security/non-free-firmware Sources [796 B]
Get:5 http://security.debian.org/debian-security bookworm-security/main Sources [62.4 kB]
Get:6 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [106 kB]
Get:7 http://security.debian.org/debian-security bookworm-security/main Translation-en [64.1 kB]
Get:8 http://security.debian.org/debian-security bookworm-security/non-free-firmware amd64 Packages [688 B]
Get:9 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing InRelease [12.5 kB]
Get:10 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing/main amd64 Packages [10.4 kB]
Get:11 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 12 InRelease [1,852 B]
Fetched 359 kB in 1s (240 kB/s)
Reading package lists... Done
### Setting installer args
### Installing InvenTree
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package inventree
root@astrid:/home/mike# wget -qO install.sh https://get.inventree.org && bash install.sh
### Installer for InvenTree - source: inventree/stable
### Detected distribution: Debian GNU/Linux 12
### Installing required packages for download
### Getting and adding key
### Adding package source
### Updating package lists
Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 https://openhab.jfrog.io/artifactory/openhab-linuxpkg testing InRelease
Get:5 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 12 InRelease [1,852 B]
Fetched 1,852 B in 2s (1,154 B/s)
Reading package lists... Done
### Setting installer args
### Installing InvenTree
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package inventree
```

**Comment by SchrodingersGat** [comment]
@tnemrap thanks for reporting. It looks like the packager builds are broken specifically for debian-12. Not sure why we were not getting notifications for this. Will have to look into this.

**Comment by SchrodingersGat** [comment]
Also we do not support debian-12 for "stable" release yet - that will be available in `0.13.x` release

**Comment by matmair** [comment]
That is sadly a bit hard @SchrodingersGat ; the packaging mechanism relies on build packs that contain a lot of code themselves - it is hard to tell where the error appears.
In this case it seems like multiple things are broken at the same time (python install and SSL).

A quick fix might be to adjust the one-line installer to recommend the repo for Debian 11 when 12 is detected. I have run the current master branch package running on multiple CIS-hardened Debian 12 test machines without problems.

**Comment by SchrodingersGat** [comment]
Is there a way to run the packager process locally for debug / development?

**Comment by matmair** [comment]
Not that I am aware off

**Comment by SchrodingersGat** [comment]
Moving to the next minor release

**Comment by SANCLA** [comment]
Getting the same error for Debian 11
Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-26-amd64
Architecture: x86-64



```
### Updating package lists
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://mirror.nl.leaseweb.net/debian bullseye InRelease
Hit:3 http://mirror.nl.leaseweb.net/debian bullseye-updates InRelease
Get:4 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 InRelease [1,857 B]
Err:4 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B6D583CCBD33EEB8
Reading package lists... Done
W: GPG error: https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B6D583CCBD33EEB8
E: The repository 'https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by SANCLA** [comment]
Fixed by editing /etc/apt/sources.list.d/inventree.list
removing "[signed-by=/etc/apt/trusted.gpg.d/pkgr-inventree.gpg]"

`#deb [signed-by=/etc/apt/trusted.gpg.d/pkgr-inventree.gpg] https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 main`

**Comment by samumatic** [comment]
@SANCLA what do you mean by just removing the `signed-by=...`? I have the same problem, but neither editing the file itself and then re-running the installer, nor editing the script installer and removing the `[signed-by=/etc/apt/trusted.gpg.d/pkgr-inventree.gpg]` from `deb [signed-by=/etc/apt/trusted.gpg.d/pkgr-inventree.gpg] https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11` main makes it look like this: `deb https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 main` will fix the bug.

**Comment by firebat81** [comment]
@SANCLA @SchrodingersGat 
Just came here to say that manually installing `gnupg` with the code 'sudo apt-get install gnupg' prior to running the installer resolves this issue on a Debian 11 LXC on Proxmox 8.1

**Comment by tnemrap** [comment]
I still get this for debian 12

**Comment by SANCLA** [comment]
Try Part-DBOp 18 jul 2024 om 01:27 heeft Michael Parment ***@***.***> het volgende geschreven:﻿
I still get this for debian 12

**Comment by tnemrap** [comment]
> Try Part-DB

sudo apt install Part-DB.
E: Unable to locate package Part-DB.

**Comment by matmair** [comment]
@tnemrap are you running the current installer or just `apt update`?

Part-DB have their own [issue tracker](https://github.com/Part-DB/Part-DB-server/issues) + Jan and team are pretty responsive so please try to find an answer there.

**Comment by tnemrap** [comment]
> @tnemrap are you running the current installer or just `apt update`?
> 
> Part-DB have their own [issue tracker](https://github.com/Part-DB/Part-DB-server/issues) + Jan and team are pretty responsive so please try to find an answer there.

Sorry thought @SANCLA mentioned another way of installing InvenTree, but he meant to use another product.
My problem is that i can not install InvenTree on debian 12 with recommended installer.

**Comment by matmair** [comment]
@tnemrap I think I have found the issue, fix incoming

**Comment by MrShippeR** [comment]
Solution - you can add repository manualy before running install.sh

Code to insert:
`wget -qO- https://dl.packager.io/srv/inventree/InvenTree/key | sudo apt-key add -
sudo wget -O /etc/apt/sources.list.d/inventree.list \
  https://dl.packager.io/srv/inventree/InvenTree/master/installer/debian/11.repo`

After that
`sudo apt-get update `
and you should be okay.

source of solution: https://packager.io/gh/inventree/InvenTree/builds/2394/install/debian-11
