### ISSUE TITLE
[FR] Custom panels for plugin settings

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#6042]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I would want to render a more complicated panel like possible with custom panels

### Suggested solution

It would be good if it could support the same interface as the custom panels

### Describe alternatives you've considered

None

### Examples of other systems

None

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Allowing templated views and javascript would be very handy here

**Comment by afkiwers** [comment]
@SchrodingersGat Totally agree

**Comment by wolflu05** [comment]
I think for the current ui this will not be that hard. But I think we should focus on the new platform ui. There we need to find a solution at all for plugins to provide custom views that get shown in panels, admin center, plugin drawer, ... and to be in style with the rest of the InvenTree theme without much code duplication.

**Comment by afkiwers** [comment]
KiCad 8 will be released in January, if their schedule can be trusted, and http libs will be officially supported. InvenTree is so far the only system supporting that, at least as far as I know.

However, KiCad devs are not keen on having an update feature inside KiCad which means lots of manual data entry on the InvenTree side.

I am currently working on a custom panel for my InvenTree_KiCad plugin that allows users to essentially export a bom from previous or new KiCad projects and reimport them into InvenTree which would then add the missing data automatically such as footprints, symbols, datasheet and so on. It's a workaround to get people started and to make InvenTree even more interesting.

So I think it would be beneficial for both sides if it's available as soon as possible. I'm still trying to find my way around InvenTree's code base and would need a fair bit of time to understand the business logic of that part. Otherwise I would have done it already.

**Comment by afkiwers** [comment]
I looked into that already, hence the FR.

I probably should have mentioned that in the beginning, sorry about that.

Problem with that mixin is that it doesn't allow to add a template file which makes more complicated views not really feasible.

**Comment by wolflu05** [comment]
You could implement your own template loading/rendering logic using the Django templates if you need that since that's a python function that should return html.

**Comment by afkiwers** [comment]
@wolflu05 thanks, I will definitely give that a go!
