### ISSUE TITLE
Installer does not start worker process

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6044]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

When installing via the simple installer, the "background worker" is not started as a systemd process.

### Steps to Reproduce

1. Run [inventree installer](https://docs.inventree.org/en/latest/start/installer/)
2. Start server `inventree restart`
3. Worker process is not started

### Relevant log output

`systemctl status inventree-web`

```
inventree-web.service
     Loaded: loaded (/etc/systemd/system/inventree-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-12-06 12:55:35 AEDT; 2h 16min ago
   Main PID: 1096 (sleep)
      Tasks: 1 (limit: 7107)
     Memory: 160.0K
     CGroup: /system.slice/inventree-web.service
             └─1096 /bin/sleep infinity
```

`systemctl status inventree-worker`

```
Unit inventree-worker.service could not be found.
```

**Comment by aKn1ghtOut** [comment]
+1
Could not figure out how to start it

**Comment by SchrodingersGat** [comment]
@aKn1ghtOut when you are running inventree, does it report that the background worker process is running,.or not?

**Comment by aKn1ghtOut** [comment]
> @aKn1ghtOut when you are running inventree, does it report that the background worker process is running,.or not?

No. Running inventree restart doesn't print anything.
Don't think the installer printed anything either. Will report back after running that again.
Running on Ubuntu 22.04. Just adding deadsnakes repo to a fresh install and running the script.

**Comment by SchrodingersGat** [comment]
I am fairly sure that this was just an issue on my end, closing it out.
