### ISSUE TITLE
[PUI] Table data caching causes old data to flash on-screen

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#6053]
It seems that Table views are cached between uses in a given React session.
Accessing a table on a detail view, then the same table on a different detail view, will cause the data of the old detail view to briefly flash on-screen before the new API call has completed.

To reproduce (with the demo dataset):
1. Open BO-0015 (platform/build/15)
2. Open "Completed Outputs" panel
3. Go back to "Details" panel
4. Go to Build Index (platform/build)
5. Go to  BO-0016 (platform/build/16)
6. Open "Completed Outputs" panel
7. You'll see a brief flash of 3x Green Chair in the table.

To verify this was indeed old data, and not some new API fetch, I performed steps 1-5, and promptly terminated the React Server. Then I did step 6, and the same behaviour was observed.

_Originally posted by @LavissaWoW in https://github.com/inventree/InvenTree/issues/6014#issuecomment-1841910194_

**Comment by SchrodingersGat** [comment]
@LavissaWoW I think that this issue may have been resolved from other refactoring - can you please check and confirm?

**Comment by LavissaWoW** [comment]
@SchrodingersGat Looks great on 3410534f29055f1b7e5bccaf602c8562deb776a2.
Table doesn't display previous elements before applying a loadingOverlay. 

I attempted the same order of operations as I described above, and didn't see old data.

**Comment by SchrodingersGat** [comment]
@LavissaWoW great, I'll close this out then :)
