### ISSUE TITLE
Getting "http: invalid Host header" on "invoke update"

### ISSUE THREAD

**Issue by slavikme** [inventree/InvenTree#6061]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Following the docker installation guide, I'm stuck on the first command run
```
docker compose run inventree-server invoke update
```
It throws my a weird error:
```
$ sudo docker compose run inventree-server invoke update
[+] Running 2/0
 ✔ Volume "inventree-production_inventree_data"   Created                   0.0s 
 ✔ Container inventree-production-inventree-db-1  Created                   0.1s 
[+] Running 1/1
 ✔ Container inventree-production-inventree-db-1  Started                   0.5s 
http: invalid Host header
```
Any seggestions?

```
$ docker compose version
Docker Compose version v2.17.2
```

### Steps to Reproduce

1. run `sudo docker compose run inventree-server invoke update`

### Relevant log output

```bash
No log output
```

**Comment by SchrodingersGat** [comment]
Could be a docker hub server issue? Have you tried again later?

**Comment by slavikme** [comment]
> Could be a docker hub server issue? Have you tried again later?

I have tried so many times with so many changes, for hours.
Worth to mention, that `docker compose up` works (except that later it fails to query tables, because the db is not initiated).
The problem occurs when specifically running `docker compose run inventree-server invoke update`.
I do have some experience with docker, but I don't even have a clue how to debug such case. Any idea?

**Comment by wolflu05** [comment]
You could run the tasks `invoke update` runs individually and try to narrow down the problem. You can find the tasks [here](https://github.com/inventree/InvenTree/blob/5d42fb3f88e16d3df95f93507d23655ecc621b28/tasks.py#L323).

**Comment by slavikme** [comment]
Solved it!

It appears that there was a race condition between two dockers installed on the same system (ubuntu apt and snap).
Removed the other and now it works! 🙌

Thanks @wolflu05 for your support :)
