### ISSUE TITLE
[FR] fontawesome Quality of Live improvements

### ISSUE THREAD

**Issue by philipp2310** [inventree/InvenTree#6064]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

At the moment you have to type the full icon name and save it to see if you did a mistake

### Suggested solution

1) Show a preview of the currently entered icon next to the input field
2) Allow pasting of the font awesome website -> regex from`<i class="fas fa-store"></i>` to `fas fa-store`

### Describe alternatives you've considered

Of course it would be awesome if there was even suggestions while you type, but that is another level of complexity

### Examples of other systems

I used roughly the following code for this in another project on input:
```[JavaScript]
icon(input) {
  // fallback if empty
  if (input === '' || input === undefined)
    return 'fas fa-box' 
  const regex = /<i class="(.*)"><\/i>/
  const matches = regex.exec(input)
  if (matches) {
    return matches[1]
  }
  // if it is not copied - keep input
  return input
}
``` 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by wolflu05** [comment]
This would be an easy addition, but in long term, I would like to have something like explained here. And as we are currently already rewriting the frontend to use react, I think this wouldn't be to hard to develop, but it was not my priority.

**Comment by SchrodingersGat** [comment]
@philipp2310 as we are currently [pushing to move the entire frontend to react](https://github.com/inventree/InvenTree/issues/5212) then this will not receive attention from the core devs. If you want to implement this yourself and push a PR, I'd look at it, but better would be to look at how this could be implemented in the new interface :)

**Comment by wolflu05** [comment]
I just realized, I forgot to add the link I was referring to in my last post. But here it is: https://github.com/inventree/InvenTree/issues/5354#issuecomment-1728421390 

Basically what I thought would be good is a button where you can click on and then an popup opens where you can select and search for you icon and set it via a click. That would be good, so that we also have some kind of standard set of icons around every platform (pui, cui, mobile app and the python script)

**Comment by matmair** [comment]
I think this will be addressed by @LavissaWoW . Although we are switching away from Fontawesome
