### ISSUE TITLE
News Feed task doesn't work behind proxy, impacting performance

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#6071]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The `update_news_feed` task attempts to fetch the RSS/Atom feed once daily. This, however, doesn't work behind a proxy server.

The result is that these tasks occupy workers all the time, and never complete.
Each worker is terminated roughly every 90 seconds due to this.

### Steps to Reproduce

1. Put the InvenTree backend on a network unable to reach `INVENTREE_NEWS_URL`
2. Trigger the task
3. Task will lead to continuous timeout termination of workers

### Expected behaviour

Task should finish with no new News entries added if URL is unreachable.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.12.10

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@LavissaWoW we have been discussing removing the news feed entirely - it is very rarely updated anyway. Happy to run with an interim fix until we make that change though. 

In this case do you know what is blocking? Is it simply a connection timeout to the remote server?

**Comment by LavissaWoW** [comment]
@SchrodingersGat My guess is a network timeout. My prod instance sits behind a proxy, and from what I see, feedparser doesn't really account for timeouts when trying to use it for requests as well.

I can't really mess a whole lot around and experiment with my prod server, so not too much done on that front. Looking at the feedparser package though, it seems that the intended use of it is only parsing returned data from I.e the requests library. Not running the request itself. Saw some discussions on their GH page about removing the ability for it to do HTTP request by itself.

On my prod, I've deleted that task schedule from my admin view as a workaround. But I suppose that can pop back into existence after a reboot.

**Comment by SchrodingersGat** [comment]
@LavissaWoW do you see the same problem in the `check_for_updates` task?

**Comment by LavissaWoW** [comment]
![image](https://github.com/inventree/InvenTree/assets/7506688/6fb28de1-3411-4ba6-b5e9-2d12189d7b75)

Only the news_feed is problematic here, And I think the issue lies in how it's implemented. 
As I mentioned above, the maintainer for the `feedparser` package has stated that the ability to do requests with the library _will_ be deprecated in due time.

Move the requests call out of feedparser, and the requests library should handle timeouts etc and cause the task to at least finish, even though it didn'treach the target URL.

So, in essence, something like this:
```python
    # Fetch and parse feed
    try:
        req = requests.get(settings.INVENTREE_NEWS_URL)
        d = feedparser.parse(req)
    except Exception as entry:  # pragma: no cover
        logger.warning('update_news_feed: Error parsing the newsfeed', entry)
        return
```

This simple change will cause the task to properly catch` requests.exceptions.RequestException`s

PS: Deleting the scheduled task doesn't work. The task is simply re-added to "scheduled tasks" on a daily basis.

**Comment by wolflu05** [comment]
What about to also just ignoring the newsfeed feature if the url is empty, which can be used for such cases?

**Comment by SchrodingersGat** [comment]
@LavissaWoW if you can submit a PR with your suggested change, that would be great :)
