### ISSUE TITLE
Part images and files are left out of migration data

### ISSUE THREAD

**Issue by readmodifywrite** [inventree/InvenTree#6074]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Part images (from media/part_images and media/part_files - at the very least) are not included in the database migration.

I attempted to manually copy these folders over to the new database (which also included fixing permissions on the files).  Unfortunately, the entire system is now broken.  nginx is reporting 502 bad gateway.

Questions:
- Is it possible to do a *full* database migration, including all images, attachments, and files?
- How do I do that?  The migration documentation does not seem to cover this.
- Should I just copy the entire volume instead?
- What is the migration tooling actually for (since I am clearly doing the wrong thing here)?

### Steps to Reproduce

Do a database migration.

### Expected behaviour

I would expect the entire database to transfer.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.12.10

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Loading config file : /home/inventree/data/config.yaml
Deleting all data from InvenTree database...
Importing database records from '/home/inventree/data/export.json'
Installed 1515 object(s) from 1 fixture(s)
Data import completed
Rebuilding Part objects
Rebuilding PartCategory objects
Rebuilding StockItem objects
Rebuilding StockLocation objects
Rebuilding Build objects
Warning: Image file 'part_images/1_thumbnail.jpeg' is missing
Warning: Image file 'part_images/2_thumbnail.jpeg' is missing
Warning: Image file 'part_images/3_thumbnail.jpeg' is missing
Warning: Image file 'part_images/4_thumbnail.jpeg' is missing
Warning: Image file 'part_images/5_thumbnail.jpeg' is missing
Warning: Image file 'part_images/6_thumbnail.jpeg' is missing
Warning: Image file 'part_images/8_thumbnail.jpeg' is missing
Warning: Image file 'part_images/9_thumbnail.jpeg' is missing
Warning: Image file 'part_images/10_thumbnail.jpeg' is missing
Warning: Image file 'part_images/11_thumbnail.jpeg' is missing
Warning: Image file 'part_images/12_thumbnail.jpeg' is missing
Warning: Image file 'part_images/13_thumbnail.jpeg' is missing
Warning: Image file 'part_images/14_thumbnail.jpeg' is missing
Warning: Image file 'part_images/15_thumbnail.jpeg' is missing
Warning: Image file 'part_images/16_thumbnail.jpeg' is missing
Warning: Image file 'part_images/17_thumbnail.jpeg' is missing
Warning: Image file 'part_images/18_thumbnail.jpeg' is missing
Warning: Image file 'part_images/19_thumbnail.jpeg' is missing
Warning: Image file 'part_images/20_thumbnail.jpeg' is missing
Warning: Image file 'part_images/21_thumbnail.jpeg' is missing
Warning: Image file 'part_images/22_thumbnail.jpeg' is missing
Warning: Image file 'part_images/23_thumbnail.jpeg' is missing
Warning: Image file 'part_images/25_thumbnail.jpeg' is missing
Warning: Image file 'part_images/26_thumbnail.jpeg' is missing
Warning: Image file 'part_images/27_thumbnail.jpeg' is missing
Warning: Image file 'part_images/28_thumbnail.jpeg' is missing
Warning: Image file 'part_images/29_thumbnail.jpeg' is missing
Warning: Image file 'part_images/30_thumbnail.jpeg' is missing
Warning: Image file 'part_images/31_thumbnail.jpeg' is missing
Warning: Image file 'part_images/32_thumbnail.jpeg' is missing
Warning: Image file 'part_images/33_thumbnail.jpeg' is missing
Warning: Image file 'part_images/34_thumbnail.jpeg' is missing
Warning: Image file 'part_images/35_thumbnail.jpeg' is missing
Warning: Image file 'part_images/36_thumbnail.jpeg' is missing
Warning: Image file 'part_images/37_thumbnail.jpeg' is missing
Warning: Image file 'part_images/38_thumbnail.jpeg' is missing
Warning: Image file 'part_images/39_thumbnail.jpeg' is missing
Warning: Image file 'part_images/40_thumbnail.jpeg' is missing
Warning: Image file 'part_images/41_thumbnail.jpeg' is missing
Warning: Image file 'part_images/42_thumbnail.jpeg' is missing
Warning: Image file 'part_images/43_thumbnail.jpeg' is missing
Warning: Image file 'part_images/44_thumbnail.jpeg' is missing
Warning: Image file 'part_images/45_thumbnail.jpeg' is missing
Warning: Image file 'part_images/2023-12-04_15-50.png' is missing
Warning: Image file 'part_images/47_thumbnail.jpeg' is missing
Warning: Image file 'part_images/48_thumbnail.jpeg' is missing
```

**Comment by readmodifywrite** [comment]
I've also tried to do a backup and restore.  Unfortunately this does not appear to work across server instances.  You'll get tons of errors from Postgres about missing user accounts and files.


What I'm trying to do is move my Inventree database (including the media files!) to another server.  It is currently on a test server that cannot be accessed externally.  What I'd like to do is move Inventree over to another server that has an external IP so other people on my team can access it.  I want to do this without having to recreate the entire database by hand.

The migration process doesn't do this.  Manually moving the files over by hand doesn't do this.  The backup/restore process doesn't do this.  Is what I'm trying to do possible?

**Comment by readmodifywrite** [comment]
I'm attempting a normal migration again, but with the media files copied out of the backup archive.  This gets us to here:

`[+] Creating 1/0
 ✔ Container inventree-db  Running                                                                               0.0s 
Loading config file : /home/inventree/data/config.yaml
Exporting database records to file '/home/inventree/data.json'
[...........................................................................]
Running data post-processing step...
Data export completed
`

What's interesting here is that data.json doesn't go anywhere.  It's not on the host filesystem at all.  It doesn't look like this location is mapped into the docker volume.  I'd recommend updating either the command itself to better interact with the host, or maybe change the docker configs to map the volume.

**Comment by readmodifywrite** [comment]
OK here's how you do this:

First, set up the new server with an empty database.

Second, export your data.  Make sure you use the commands for docker, since everything happens within the container and your volume mount:
`docker compose run inventree-server invoke export-records -f /home/inventree/data/export.json`

Copy export.json to the same volume location on your target server.

Third, copy the media folder from the old server to the new server.  Copy *only* the media folder.  You can't just copy the entire thing, it will break and you'll have to start over.

Fourth, run the import.  This is the exact same command as before, but with import-records:
`docker compose run inventree-server invoke import-records -f /home/inventree/data/export.json`


I'd recommend at least updating the migration docs to explain how to copy the media files over.  Even better to have the export/import tooling do that for you.  This was frankly much, much harder than it needed to be (running on a remote server in docker makes this more frustrating).  But it *is* possible.

**Comment by SchrodingersGat** [comment]
@readmodifywrite thanks for getting back with your detailed update. Would you be able to submit a PR with the relevant updates to the documentation?

I agree with your process - that the *media* files (and only the media files) need to be transferred into the location before re-launching the database. Looks like you got it all figured out well :)

**Comment by SchrodingersGat** [comment]
@readmodifywrite were you happy to submit a PR to update the documentation around this process?
