### ISSUE TITLE
[FR] Rownumber in BOM

### ISSUE THREAD

**Issue by tnemrap** [inventree/InvenTree#6075]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When i pick the bom into a pickbox ( box with 25 smal slots) i want to have a number on the row in bom so i know what slot it should be in.

### Suggested solution

add a editable field in BOM called row number or pickslot.

### Describe alternatives you've considered

I print the bom and use a pen to write down slotnumber.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
This sounds like a very niche use case that would not make sense for most users.

We offer extensive customisation options via [plugins](https://docs.inventree.org/en/stable/extend/plugins/) and adding arbitrary data to most models [via metadata](https://docs.inventree.org/en/stable/api/metadata/?).

**Comment by SchrodingersGat** [comment]
@tnemrap there is also the "notes" and "reference" and "description" field on each BOMItem which could certainly host this data

**Comment by tnemrap** [comment]
I try to see if i can use description, Reference is already for PCB placement.
