### ISSUE TITLE
Remove a part permanently

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#608]
I found where you can edit a part and make it !active but is there a way to remove it altogether?
I for instance made a:
<img width="1984" alt="Screen Shot 2020-01-05 at 11 57 07 PM" src="https://user-images.githubusercontent.com/36831279/71796239-c83c5680-3017-11ea-8167-e23dc23b419c.png">
Test part that I don't need or want anymore.

**Comment by SchrodingersGat** [comment]
Once a part is marked as **not active** then a delete button will be available on the part details page:

![image](https://user-images.githubusercontent.com/10080325/71807576-b910e380-30bf-11ea-9146-7a713feaef7b.png)


Also, you can manually delete any records via the admin interface
