### ISSUE TITLE
[PUI] Issues with panel routing

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6090]
- Ref: https://github.com/inventree/InvenTree/pull/6088
- Ref: https://github.com/inventree/InvenTree/pull/6078

The current panel implementation re-writes the URL when the panel changes. This causes a number of subtle issues related to routing and instance queries.

### URL Rewrite Issue

Click on the "parts" tab:

![image](https://github.com/inventree/InvenTree/assets/10080325/e71309e9-63ce-4dac-b418-be046789ef16)

Note that the URL (which should be `/platform/part/category/`) has been re-written to `/platform/part/category/parts/parts`:

![image](https://github.com/inventree/InvenTree/assets/10080325/3a384475-907e-4530-9b09-dced9892c988)

The URL rewrite has effectively made "parts" the "ID" for the selected category which causes the following query to be made (from `useInstance` hook):

![image](https://github.com/inventree/InvenTree/assets/10080325/11c91044-9349-4d3e-8885-c8cb909a1f63)

This is really querying *all* parts from the server, which takes a very long time:

![image](https://github.com/inventree/InvenTree/assets/10080325/603a4d23-651b-442f-a876-fa06511780c0)

Part of the issue here is that we need a separate `PartIndex` page, rather than re-routing via the router:

![image](https://github.com/inventree/InvenTree/assets/10080325/5b51eaf4-40e4-424e-97f3-5f6f4ed6b6f8)

### URL Duplication

The panel URL rewriter causes *two* subdirectories to be added to the URL:

![image](https://github.com/inventree/InvenTree/assets/10080325/df0cfd79-abcd-4eaa-876a-931710ea5358)

### Potential Clashes

The approach of rewriting the URL will cause issues related to clashing URLs. This is already demonstrated above (`/part/category/parts`) but there are plenty of potential cases where we need to be able to differentiate between an actual "sub path" and a "panel path").

A different approach is needed here. Personally I think that a `/URL/path/like/this/` should *always* indicate explicit routing and the "content" of the page (in this case the panels) should be handled separately so there is no chance of conflict.

Perhaps we could use the `#` anchor to specify the panel name?

**Comment by SchrodingersGat** [comment]
@wolflu05 hopefully this is more informative as to where the issues are. Let me know what you think!

**Comment by LavissaWoW** [comment]
Looking past the codewise problems here, looking at this from both SEO and a UX point of view.

The URL ` /platform/part/category/parts/parts/` is very confusing. 
I think it's a good idea to have the URL reflect the current panel, as it allows for deterministic links, something missing in CUI. 
But how it works out atm isn't very good.

**Comment by SchrodingersGat** [comment]
I am happy to continue with putting the panels into the URL as long as the issues outlined above are addressed. Can we explicitly put an optional panel name param into the router?

e.g. something like

`/part/:id/:panel*/`

**Comment by SchrodingersGat** [comment]
@wolflu05 do you have any time to input on this? I'd like to address these two issues and move forward, but as you implemented this I'd certainly like to hear your thoughts before moving forward

**Comment by wolflu05** [comment]
Sorry for my late response. Just moving the router definitions from the `PanelGroup` component to the `router.tsx` would only help to have the router definition at one place, but would require a lot of duplicate work. And additionally this would still require us to do some rerouting to open the last used panel if no panel is in the url. Where I do not see a simple solution then.

What about having the index page explicitly in the url by using `/part/category/index/parts`. 
This has the advantage, that a part id parameter does not clash with a panel name parameter like if the index page would be just without an id in the path segments:

Before:
- `/part/category/parts` (index page that shows all parts)
- `/part/category/1/parts` (parts that are in category 1)

Using index in the route:
- `/part/category/index/parts` (index page that shows all parts)
- `/part/category/1/parts` (parts that are in category 1)

We could do that by checking if the id parameter is a number and if not set it as undefined. That way `id===undefined` means the index page:

<details><summary>Possible implementation</summary>

```patch
diff --git a/src/frontend/src/pages/part/CategoryDetail.tsx b/src/frontend/src/pages/part/CategoryDetail.tsx
index 30f63b6ba..345d06bf9 100644
--- a/src/frontend/src/pages/part/CategoryDetail.tsx
+++ b/src/frontend/src/pages/part/CategoryDetail.tsx
@@ -23,7 +23,8 @@ import { useInstance } from '../../hooks/UseInstance';
  * Note: If no category ID is supplied, this acts as the top-level part category page
  */
 export default function CategoryDetail({}: {}) {
-  const { id } = useParams();
+  const { id: _id } = useParams();
+  const id = useMemo(() => !isNaN(parseInt(_id || "")) ? _id : undefined, [_id]);
 
   const [treeOpen, setTreeOpen] = useState(false);
 
@@ -33,6 +34,7 @@ export default function CategoryDetail({}: {}) {
     instanceQuery
   } = useInstance({
     endpoint: ApiPaths.category_list,
+    hasPrimaryKey: true,
     pk: id,
     params: {
       path_detail: true
diff --git a/src/frontend/src/router.tsx b/src/frontend/src/router.tsx
index 45713dbe3..96636816f 100644
--- a/src/frontend/src/router.tsx
+++ b/src/frontend/src/router.tsx
@@ -119,7 +119,7 @@ export const routes = (
         <Route path="user/*" element={<UserSettings />} />
       </Route>
       <Route path="part/">
-        <Route index element={<Navigate to="category/" />} />
+        <Route index element={<Navigate to="category/index/" />} />
         <Route path="category/:id?/*" element={<CategoryDetail />} />
         <Route path=":id/*" element={<PartDetail />} />
       </Route>
```

</details> 

Please let me know what you thing about that fix or if you have a better idea.

**Comment by matmair** [comment]
Seems reasonable and simple @wolflu05

**Comment by wolflu05** [comment]
What do you mean with duplication? The parts/parts thing? That should be fixed with my patch by using index/parts

**Comment by SchrodingersGat** [comment]
> What do you mean with duplication? The parts/parts thing? That should be fixed with my patch by using index/parts

I can confirm that the patch has fixed the duplication issue too!

**Comment by wolflu05** [comment]
The issue was that navigating to `/part/category` caused to already render the panel group which now tries to navigate to `parts/` because that's the first/last used panel. But since there is no id in the path segment, the panel name now got the id, and now there is still no panel name in the path, so it redirected a second time to the last used panel. 

However adding an explicit index segment in the path now only redirects the wanted one time to the correct panel.

Really sorry that I haven't seen this issue while implementing.
