### ISSUE TITLE
Export data from bare metal installation results in error

### ISSUE THREAD

**Issue by Alex9779** [inventree/InvenTree#6110]
### Deployment Method

- [x] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

As far as I can remember I followed the guide to install bare metal.
To make this a little easier to manage for me I decided to migrate to a Docker installation.
So I wanted to migrate the data but I get an error.
My bare metal container runs Debian 11 as recommended.

### Steps to Reproduce

I do the following:
`cd /opt/inventree`, then `source env/bin/activate` and `inventree run invoke export-records -f data.json`.
But this results in an error:
`python3: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory`

I think this has something to do with Python versions because active is 3.9.2 and that lib seems to be 3.10.
Searching the lib with find revelas it at `./.heroku/python/lib/libpython3.10.so.1.0`but obviously the above command does not find it or is unable to use it.

Any idea how I can get the data to import it to a new Docker stack?

**Comment by SchrodingersGat** [comment]
When you install via the installer, it comes with a special command to run `invoke` from within the right context. Try:

```bash
inventree run cli export-records -f data.json
```

**Comment by Alex9779** [comment]
tried that also but this just returns an empty line and nothing happens...

**Comment by LavissaWoW** [comment]
Given it's a bare metal installation, try skipping the "InvenTree run" parts of the command. If you've ran the 'source *somedir*' command on the relevant CLI, then as long as you're in the same directory as the tasks.py file, the invoke command should in theory suffice.

**Comment by SchrodingersGat** [comment]
@Alex9779 the "empty line" bug was fixed in https://github.com/inventree/InvenTree/pull/6049 but may not be fixed for your install.

To get the `inventree run cli` method to work, edit the following file:

`/opt/inventree/vendor/pkgr/processes/cli`

And change the command to:

```bash
echo "" | echo "" && . env/bin/activate && invoke
```

**Comment by Alex9779** [comment]
@LavissaWoW treid that but even I think I activated the env and everythinig the command then wants all the variables for paths at first, setting them as env variables works so far that I can run "config" but not the export because this then needs the database info and this was a dead end for me because setting "ENGINE" as env variable did not work out...

@SchrodingersGat kk, sorry I have really no idea any more how I installed, the installer script was in /root but I think I messed up somehow. Tried what you wrote but then I just got the config in return calling `inventree run cli export-records -f data.json`.
Change it to:
`echo "" | echo "" && . env/bin/activate && invoke $@`
And then I worked I think, at least I got the files so trying to restore it...

**Comment by Alex9779** [comment]
Export worked with adjusted command but I still have problems with my new instance, can't get the bulk plugin working even not in a bare docker container installation but this is some other topic...

Thanks for the help...
