### ISSUE TITLE
[FR] Provide setup keys for two-factor authentication alongside QR codes

### ISSUE THREAD

**Issue by HammyHavoc** [inventree/InvenTree#6132]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Two-factor auth is obviously very important, but not all devices have cameras. Most services that offer 2FA via QR codes also offer keys you can manually copy to set up your 2FA.

### Suggested solution

Add the setup code for manual usage alongside the QR code.

### Describe alternatives you've considered

This is pretty standard, not having it is unusual.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@HammyHavoc thanks for raising this issue. Looks like there are a few 2FA issues we need to sort out

**Comment by matmair** [comment]
Still important

**Comment by wolflu05** [comment]
Still important
