### ISSUE TITLE
Email confirmation key missing domain

### ISSUE THREAD

**Issue by HammyHavoc** [inventree/InvenTree#6133]
### Deployment Method

- [ ] Installer
- [X] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

The URL in the email to confirm an address consists of `/accounts/confirm-email/` followed by the key, but it isn't prefixed by the base URL.

### Steps to Reproduce

1. Send an email confirmation.

**Comment by SchrodingersGat** [comment]
@HammyHavoc did you find a solution?

**Comment by HammyHavoc** [comment]
Yes! :- ) Seems that for whatever reason, `base_url` in `config.yaml` wasn't respected and wasn't visible in `/settings` ("No value set"), so added it via the Server Settings page, and worked like a charm.

**Comment by HammyHavoc** [comment]
If it's useful, my `base_url` in `config.yaml` was set as `base_url: 'https://inventree.mydomain.suffix'`.

**Comment by SchrodingersGat** [comment]
Ok, I will reopen this to determine why the setting in the config file was not being respected

**Comment by SchrodingersGat** [comment]
Ok, can confirm that the "base_url" config setting is not being "respected" as one might expect. This is a real issue

**Comment by HammyHavoc** [comment]
> Ok, can confirm that the "base_url" config setting is not being "respected" as one might expect. This is a real issue

Just wanted to say I appreciate you and what you do and give to the world in both solutions, and your own time and energy. I hope you have the greatest year yet. 🖖 You're awesome.

Looking forward to getting more involved with contributing to Inventree however I can too.

**Comment by SchrodingersGat** [comment]
@HammyHavoc FYI - see the updates in https://github.com/inventree/InvenTree/pull/6390

The issue on your end is that it should be called `site_url` (and not `base_url`) in the settings file :)
