### ISSUE TITLE
`received a naive datetime while time zone support is active.`

### ISSUE THREAD

**Issue by HammyHavoc** [inventree/InvenTree#6134]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I get an error in my log when starting the container. Not sure how to correct it.

### Steps to Reproduce

1. Start the container.

### Relevant log output

```bash
ython version 3.10.13 - /usr/local/bin/python3
/root/.local/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1358: RuntimeWarning: DateTimeField PartPricing.updated received a naive datetime (2023-11-25 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/root/.local/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField NotesImage.date received a naive datetime (2023-09-26 06:55:06.646529) while time zone support is active.
```

**Comment by matmair** [comment]
sounds like #5223; hard to say without a full bug report/version stump

**Comment by SchrodingersGat** [comment]
Probably a similar fix. If you can work out which API request it correlates to that would be very helpful.
