### ISSUE TITLE
install.sh now bails with depends: python3.9

### ISSUE THREAD

**Issue by AlfBaz** [inventree/InvenTree#6139]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

To prevent messing up my actual server I test new versions on a vm running a fresh ubuntu server 22.04.3 install
I then disable the cloud init stuff and run the wget one liner
wget -qO install.sh https://get.inventree.org
followed by
sudo bash install.sh

This has worked every time up until recently where the script now ends with

The following packages have unmet dependencies:
 inventree : Depends: python3.9 but it is not installable
             Depends: python3.9-venv but it is not installable
             Depends: python3.9-dev but it is not installable
E: Unable to correct problems, you have held broken packages.

By the way no difference if I apt auto remove, apt update or apt upgrade prior to running install.sh

### Steps to Reproduce

1. On windows 10, start vmware workstation 15 and select Create New Virtual Machine.
2. I select "ubunut-22.04.3-live-server-amd64.iso" as the installer disc and proceed to boot and install the server OS on the VM
3. I then disable cloud-init as outlined here https://gist.github.com/zoilomora/f862f76335f5f53644a1b8e55fe98320 Having said that I have also tried it without disabling cloud-init and there's no change in outcome
4. I run the one liner install command from my home directory but with a few extra steps
5. wget -qO  install.sh https://get.inventree.org
6. bash install.sh --version (returns 2.0)
7. sudo bash install.sh

### Relevant log output

```bash
### Installer for InvenTree - source: inventree/stable
### Detected distribution: Ubuntu 22.04
### Installing required packages for download
Selecting previously unselected package apt-transport-https.
(Reading database ... 73912 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.4.11_all.deb ...
Unpacking apt-transport-https (2.4.11) ...
Setting up apt-transport-https (2.4.11) ...
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
### Installing libssl1.1
deb http://security.ubuntu.com/ubuntu focal-security main
Hit:1 http://au.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://au.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:3 http://au.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,640 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [405 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [13.2 kB]
Fetched 3,402 kB in 4s (798 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  eatmydata libeatmydata1 python-babel-localedata python3-babel python3-certifi python3-jinja2 python3-json-pointer
  python3-jsonpatch python3-jsonschema python3-markupsafe python3-pyrsistent python3-requests python3-tz
  python3-urllib3
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libssl1.1
0 upgraded, 1 newly installed, 0 to remove and 44 not upgraded.
Need to get 1,321 kB of archives.
After this operation, 4,126 kB of additional disk space will be used.
Get:1 http://security.ubuntu.com/ubuntu focal-security/main amd64 libssl1.1 amd64 1.1.1f-1ubuntu2.20 [1,321 kB]
Fetched 1,321 kB in 3s (498 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libssl1.1:amd64.
(Reading database ... 73916 files and directories currently installed.)
Preparing to unpack .../libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1f-1ubuntu2.20) ...
Setting up libssl1.1:amd64 (1.1.1f-1ubuntu2.20) ...
Processing triggers for libc-bin (2.35-0ubuntu3.5) ...
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
### Getting and adding key
### Adding package source
### Updating package lists
Hit:1 http://au.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://au.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://au.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:5 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/ubuntu 20.04 InRelease [1,863 B]
Get:6 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/ubuntu 20.04/main amd64 Packages [2,741 B]
Fetched 4,604 B in 2s (2,309 B/s)
Reading package lists... Done
### Setting installer args
### Installing InvenTree
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 inventree : Depends: python3.9 but it is not installable
             Depends: python3.9-venv but it is not installable
             Depends: python3.9-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by AlfBaz** [comment]
OK, so I did a little more digging and the problem seems to be with the latest version which according to `apt show` is
0.13.0-1702638825.301afaa9.focal.

I can recreate the problem by simply typing 
`sudo apt install inventree`
or more specifically
`sudo apt install inventree=0.13.0-1702638825.301afaa9.focal`
To which I get...
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 inventree : Depends: python3.9 but it is not installable
             Depends: python3.9-venv but it is not installable
             Depends: python3.9-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
```

if, however I try
`sudo apt install inventree=0.12.8-1698964278.a7487ff8.focal`
all is well
So it looks as though what ever mechanism is employed in the latest install insists on python 3.9?


Oddly enough in my "production" machine the about yeilds
```
# Version Information:
InvenTree-Version: 0.12.8
Django Version: 3.2.19
Commit Hash: a7487ff8
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]
```
which shows python version 3.10.12 which for some reason isn't copied into the clipboard when you click "copy version information"

**Comment by AlfBaz** [comment]
Never mind.
I just found out you guys actually did this on purpose with PR Packages - force python 3.9 #5206 
I knew the officially supported OS was 20.04 but the doc's Python Requirements said 3.9 and newer so...

Anyway, time to learn docker

**Comment by AlfBaz** [comment]
Never mind.
I just found out you guys actually did this on purpose with PR Packages - force python 3.9 https://github.com/inventree/InvenTree/pull/5206
I knew the officially supported OS was 20.04 but the doc's Python Requirements said 3.9 and newer so...

Anyway, time to learn docker

**Comment by bhotrock** [comment]
Just to comment:  It seems that #5206 was meant to force 3.9 rather than allowing install on 3.8.  However, like @AlfBaz, my 0.12.8 install is running fine with Python 3.10.  And because I'm on 3.10, I also can't update to version 0.13.  Is there a way to modify this so an installer based installation can update via apt to version 0.13?
