### ISSUE TITLE
InvenTree App URL in About not displayed correctly

### ISSUE THREAD

**Issue by rezafouladian** [inventree/InvenTree#6140]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The link to the mobile app in About is displayed and linked as `('https://docs.inventree.org/en/0.13.0/app/app',)`.
I updated from 0.12.7 to 0.13.0, and the link was fine in 0.12.7.

### Steps to Reproduce

1. Select About InvenTree from the top right user menu
2. The link is not displayed properly and cannot be followed by clicking on it

<img width="976" alt="Screenshot 2023-12-28 at 4 30 49 AM" src="https://github.com/inventree/InvenTree/assets/9205977/408d94cc-ed3d-493f-a414-66ab9363293a">

### Expected behaviour

On 0.12.7:

<img width="976" alt="Screenshot 2023-12-28 at 4 30 38 AM" src="https://github.com/inventree/InvenTree/assets/9205977/aac28ee4-a4fd-45a6-b16b-3bbf573f4c9b">

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0
Django Version: 3.2.23
Commit Hash: 301afaa9
Commit Date: None
Commit Branch: master
stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-162-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by alimurtaza026** [comment]
Assign me.  I am working on it

**Comment by SchrodingersGat** [comment]
@rezafouladian are you still looking into this one?

**Comment by matmair** [comment]
I would have the solution but very happy to let someone else solve it
