### ISSUE TITLE
[FR] Enhancing BoM exporting with subassemblies by splitting subassemblies on other sheets

### ISSUE THREAD

**Issue by JambonLeVrai** [inventree/InvenTree#6147]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When exporting a BoM including subassemblies, the resulting BoM is completely flattened when selecting level 0 and might make the file a bit tough to read.

### Suggested solution

When exporting to .xlsx or .xls, an option could be added to put the BoMs of the subassemblies on other sheets. For csv files, the subassembly BoMs could simply be exported as multiple files zipped. 
This makes the files more readable, and makes it better for being printed out : all subassemblies can be printed independently to perform real-life stock allocation.

### Describe alternatives you've considered

This could also be done with a simple "post-prod" python script, that reads a csv file and splits the subassemblies to other files, or perform the splitting in .xls / .xlsx sheets.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@JambonLeVrai I am not sure if we can export to sub-sheets with our existing tech stack. Of course exporting multiple sub files for each sub assembly is already possible (although manual and time consuming).
Exporting all files as a single archive would be achievable but could potentially take some time for the server to format and zip. This will require some further though
