### ISSUE TITLE
Automatic Rounding

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#615]
Is it possible to make the price automatically round instead of saying "only use 5 decimal digits" or whatever the warning is. I am fine with only 5 places but it takes me longer to manually round and I am sure there is an easy rounding function that can be implemented.

**Comment by SchrodingersGat** [comment]
@a7hybnj2 can you please provide an example of where you are running into this issue?

**Comment by a7hybnj2** [comment]
I think...I was copying and pasting price per part data from, lcsc into the supplier cost fields. Lcsc provided the price out to more decimal places than InvenTree would accept.

**Comment by SchrodingersGat** [comment]
Aha, I see - should be fixed in https://github.com/inventree/InvenTree/pull/669
