### ISSUE TITLE
APT Update to 0.13 fails with requirement for Python 3.9, when system uses 3.10

### ISSUE THREAD

**Issue by bhotrock** [inventree/InvenTree#6154]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

As very well documented in issue #6139, (closed by the submitter), the requirements for python3.9, python3.9-venv, and python3.9-dev prohibit using the command:  apt install --only-upgrade inventree on systems that are running python3.10, such as Ubuntu 22.04.   It seems to ME that if a system running 0.12.8 works okay with python3.10, then we should be able to upgrade to 0.13.  However, I'm not a programmer.  :-)  I'm wondering if the requirement for python3.9 was to avoid installation on python3.8 systems, or if it was intended to also avoid python3.10.

### Steps to Reproduce

0.  Running Inventree 0.12.8, originally installed using the Installer Script, on Ubuntu 22.04 with python3.10.
1.  Attempted update to Inventree to version 0.13 using  `apt install --only-update inventree` which had been used successfully to update to 0.12.8.
2. Update was not possible due to dependencies for python3.9

### Relevant log output

```bash
apt install --only-upgrade inventree
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 inventree : Depends: python3.9 but it is not installable
             Depends: python3.9-venv but it is not installable
             Depends: python3.9-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by SchrodingersGat** [comment]
It seems like the `.pkgr.yml` file is the culprit here, forcing `3.9`. Currently `3.9` to `3.11` are "known good".

@matmair is there a path forward here to loosen the python version requirements for the installer?

**Comment by matmair** [comment]
I am unaware of built-in tooling for this. A common solution would be to release different packages for different python versions.
The "problem" is that the generic package (ex [python3-venv](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=python3-venv&searchon=names)) is pointing to Python 3.8 on Ubuntu 20.04 LTS - so it would fail in the setup steps.

**Comment by erikpt** [comment]
I've never built a packager deployment myself, but I'm having the same issue as op. After a bunch of reading about packager, could this be fixed with a yaml array for the python dependency?

replace
```
python3.9
python3.9-venv
python3.9-dev
```

with
```
"python3.9 | python3.10 | python3.11"
"python3.9-venv | python3.10-venv | python3.11-venv"
"python3.9-dev | python3.10-dev | python3.11-dev"
```

Source: dependencies section on this page: https://doc.packager.io/documentation/customizing-the-build/
