### ISSUE TITLE
Error importing Purchase Order CSV file.  Metadata must be a python dict object

### ISSUE THREAD

**Issue by bhotrock** [inventree/InvenTree#6155]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I checked for similar issues and did find #5322, but the fix of #5349 doesn't seem to have fixed my issue.

When attempting to import a CSV file for Purchase Orders, I'm getting the same error that is referenced in #5322 and #5348.  I have attempted with both the double bracket: ` {} ` as well as leaving this field empty (nothing between the commas in the CSV file).  I have checked my `admin.py` and it includes the code that was added in #5349 as shown here:
```
                row[idx] = val

        return row

    def get_fields(self, **kwargs):
        """Return fields, with some common exclusions"""

        fields = super().get_fields(**kwargs)

        fields_to_exclude = [
            'metadata',
            'lft', 'rght', 'tree_id', 'level',
        ]

        return [f for f in fields if f.column_name not in fields_to_exclude]


class CustomRateAdmin(RateAdmin):
```
Here's a screenshot of the error:
![Screen Shot 2024-01-03 at 1 07 34 PM](https://github.com/inventree/InvenTree/assets/19352294/ce9f840f-e548-41c5-b612-cd123a0f6e8e)

### Steps to Reproduce

1. Create CSV file to import Purchase Orders, based on an exported CSV file.
2. Attempt to import the CSV file.
3. Receive error about metadata field.

### Expected behaviour

I would expect that the file would be imported without an error.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

Python Version 	3.10.12
# Version Information:
InvenTree-Version: 0.12.8
Django Version: 3.2.19
Commit Hash: a7487ff8
Commit Date: None
Commit Branch: stable
Database: mysql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.35
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by bhotrock** [comment]
@SchrodingersGat  Thanks for the quick fix.  I'll try to test the new file today.

**Comment by bhotrock** [comment]
@SchrodingersGat I just wanted to confirm that this solved our issue.  Imports working fine now.  Thank you so much!

**Comment by SchrodingersGat** [comment]
Awesome, thanks for confirming the fix 😃
