### ISSUE TITLE
Question: Importing Data with Creation Dates

### ISSUE THREAD

**Issue by jacobfelknor** [inventree/InvenTree#6159]
I have a relatively simple question, but one that is really important to my use case. I've spent some time writing import scripts to bring data over from a legacy system into InvenTree. I'm doing so via Python using InvenTree's API to create objects.

However, when importing Purchase Order information, I noticed there is no documented way to create a Purchase Order with a custom creation date. It obviously would be ideal if I could preserve dates during my import, both for POs and other types of objects. Is there a recommended way of doing so?

I'm using the internal API documentation at `/api-doc/#tag/order/operation/order_po_.*_create`

Thank you in advance

**Comment by martonmiklos** [comment]
By strictly looking on the code all orders (including the purchase orders) has a creation_date field.
In the [save logic it looks like there is care taken](https://github.com/inventree/InvenTree/blob/master/InvenTree/order/models.py#L194) to use the passed values, so I would recommend to set that field before the API call.

**Comment by jacobfelknor** [comment]
How could I set it _before_ the API call? I'm using [the python module documented here](https://docs.inventree.org/en/latest/api/python/python/)

I did try passing a field called `creation_date` with the API call with no luck. Something like

```python
from inventree.purchase_order import PurchaseOrder

INVENTREE_API_URL = "http://localhost:8000"
INVENTREE_API_USERNAME = ""
INVENTREE_API_PASSWORD = ""
API = InvenTreeAPI(INVENTREE_API_URL, username=INVENTREE_API_USERNAME, password=INVENTREE_API_PASSWORD)

po_data = {
    "reference": "PO-12345"
    "supplier": "1276",
    "target_date": "2024-01-21", # this works!
    "creation_date": "2022-10-28" # matching format used for target date
}

PurchaseOrder.create(API, data)
```

**Comment by martonmiklos** [comment]
You are right, sorry the creation_date is not exposed via the serializer.

I have changed this in my fork so you can test it:
https://github.com/martonmiklos/InvenTree/tree/allow_order_creation_date_edit_via_api

I am unsure if this is the right way to handle it, so I would like to hear @SchrodingersGat opinion on it.

**Comment by SchrodingersGat** [comment]
We could expose this to the API, and also to the data import framework. I see no issues with this. Anyone want to tackle this one?

**Comment by martonmiklos** [comment]
I will sort it out.
