### ISSUE TITLE
Geewhiz metrics

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#617]
This is just for fluff but could possible be useful somehow.

Add an area similar to `Part Categories ##` and `Stock Locations ##` to give you total # of parts in inventory. Maybe add some other metrics in there like least/most expensive part, most used part, most purchased part, ect.

My primary interest was in total parts in inventory so I could say I stock ## parts.

**Comment by SchrodingersGat** [comment]
What if it were an option in the main drop-down menu in the top-right corner which shows database stats. It is only called when required but can include a lot of varied stats as required.

**Comment by a7hybnj2** [comment]
Sounds perfect!
Jan 19, 2020, 05:25 by notifications@github.com:

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/73607425-fd819780-4609-11ea-83bf-ac4f810c3e0b.png)

![image](https://user-images.githubusercontent.com/10080325/73607431-070aff80-460a-11ea-8c2e-ff030ddea07c.png)

**Comment by a7hybnj2** [comment]
Perfect. If I think of any additional metrics that could be useful I will let you know.
