### ISSUE TITLE
[FR] Destination of a BO automatically set to default location

### ISSUE THREAD

**Issue by JambonLeVrai** [inventree/InvenTree#6174]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Whenever creating a new build order and selecting the part to build, the destination location of the build order is not set to the default location of the built part.

### Suggested solution

I would expect that when selecting a part that has a default location, the destination of the build order is automatically set to the default location

### Describe alternatives you've considered

This can simply be done manually, but makes more room for a mistake

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@JambonLeVrai sorry for the delay on this one - finally have a fix incoming in https://github.com/inventree/InvenTree/pull/7160
