### ISSUE TITLE
Export cascading BOM

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#619]
Currently a BOM export is flat (only show top-level BOM items).

However it would be useful to include sub-assembly information in the BOM

Make this a selectable option?

**Comment by sihawken** [comment]
This would be a fantastic addition to InvenTree. Definitely something I'd really like to have. 

I'm currently working for a start-up. We do a lot of prototyping, 3D printing, etc. and we've been using InvenTree to organize all of our part numbers and generate the bill of materials for manufacturing.  It's been great, super easy to use and to organize the information. 

A multi-level BOM is something I really, really am aching for. Especially for the engineering team looking at different projects, and at a glance seeing what the project contains with the relevant information. This would make finding the information much more efficient.

**Comment by SchrodingersGat** [comment]
@sihawken - see https://github.com/inventree/InvenTree/pull/641
