### ISSUE TITLE
PackingList / BuildList

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#62]
When shipping or building items, it can be helpful to print out a list of all the items, with a picture, description, quantity.

Then shipping peoples can easily check off each item as they go.

**Comment by SchrodingersGat** [comment]
This packing list can be generated from:

* Purchase Order
* Sales Order / Customer Order
* Internal Stock Movement

**Comment by mabroens** [comment]
Hi @SchrodingersGat ,

i have started using Inventree 2 weeks agoo and LOVE it. its great i have been able to upload my parts to the db using the inventree-digikey python app. works :-) 
but now that i have all my stock in and i have cretaed a build order for an external assembly house (I design PCB's) i also need to ship certain parts from my lab to them. therfore i would like to create a packinglist for the items that i'm shipping (or hand carry) to the assembly house. how can i create this packinglist?

you mentioned tha this is possible from: This packing list can be generated from:

> Purchase Order
> Sales Order / Customer Order
> Internal Stock Movement

but i cant figure out how to.
please advice.
Br Martijn

**Comment by matmair** [comment]
You need to create a report template. Read more in the docs about [reports](https://docs.inventree.org/en/stable/report/report/) and [packing lists](https://docs.inventree.org/en/stable/report/pack/). This is an advanced topic.
Please do not reuse old, closed issues.

**Comment by SchrodingersGat** [comment]
@mabroens the report documentation as linked by matmair above should contain all you need. Otherwise please open a new issue or discussion
