### ISSUE TITLE
[PUI] Enable 2FA for new interface

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6200]
Need to enable 2FA functionality via the API, and implement for:

- React interface
- Mobile app
- etc

In addition to implementing 2FA support via API endpoints, need to setup the user interface elements for the new platform UI

**Comment by matmair** [comment]
@SchrodingersGat I think 2FA is probably the easiest to do just in the web UI and then used via webviews in the app. Thah way OIDC would also be easy.

**Comment by SchrodingersGat** [comment]
Fixed in #6368

**Comment by matmair** [comment]
@SchrodingersGat are you sure this was fixed?

**Comment by SchrodingersGat** [comment]
@matmair you're right, I was thinking SSO.. Too much going on.

**Comment by matmair** [comment]
@SchrodingersGat are you on board to split this into 2 issues:
1) (this) Add 2fa to PUI
2) Add 2fa APIs ( I would wait for the REST release of django-allauth for that)

**Comment by SchrodingersGat** [comment]
Yep, on board
