### ISSUE TITLE
Import of Purchase order line items fails due to Destination issue

### ISSUE THREAD

**Issue by bhotrock** [inventree/InvenTree#6201]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When trying to import Purchase Order Line Items, I get a validation error of:  Cannot assign "'11'": "PurchaseOrderLineItem.destination" must be a "StockLocation" instance.

I assumed that the correct data for the "Destination" field should be the "Location ID" from an export of StockLocations.  That appears to be the data value that is stored in the destination_id field order_purchaseorderlineitem table in the database.  I've tried it as just a number, as a number inside quotes, and also as the text of the Location Name.   

I've also tried to leave it blank but that fails with the error:  Cannot assign "'null'": "PurchaseOrderLineItem.destination" must be a "StockLocation" instance.  However, I have one entry in the destination_id field that has a NULL value.

When I export the existing Purchase order line items, the output shows the text name of the location.  I've tried to import a line with that exact copy of the text (both with and without quotes) and that doesn't work either.

It appears to me that there's some sort of error with the validator.  Or maybe I just don't know what the correct data should be.  

<img width="310" alt="Screen Shot 2024-01-10 at 3 40 32 PM" src="https://github.com/inventree/InvenTree/assets/19352294/3fde9830-ac93-4b67-820c-5138bc8eb05a">

### Steps to Reproduce

1.  Create CSV file with data for Purchase order line items
2. Set value of the "destination" field to the location_id of the stock locations
3. Attempt to import
4. Receive validation error

### Expected behaviour

I would expect the data to import without errors.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.8
Django Version: 3.2.19
Commit Hash: a7487ff8
Commit Date: None
Commit Branch: stable
Database: mysql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.35
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@bhotrock thanks for reporting

**Comment by bhotrock** [comment]
@SchrodingersGat  Thanks for the quick fix!  I can confirm that the import is now successful.
Have a great day!
