### ISSUE TITLE
Add 'Notes' to the available tabs within a part

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#621]
Add a tab called "Notes" and make it just a big editable text box maybe with markdown rendering. This would be an easy place to make notes of anything associated with that part or build.

**Comment by SchrodingersGat** [comment]
Great idea - see https://github.com/inventree/InvenTree/pull/626

**Comment by SchrodingersGat** [comment]
This has now been implemented - please let me know what you think!

**Comment by a7hybnj2** [comment]
I will give it a go on Monday. Its just ‘git pull’ & ‘make update’ right? I don’t think ‘make backup’ worked the last time I tried but I guess I should start with that.

**Comment by SchrodingersGat** [comment]
Yes, just follow the instructions here - https://inventree.readthedocs.io/en/latest/update.html

Note that if it fails at the `make backup` step, then change line 10 of *Makefile*  from:

`update: backup install migrate static`

to

`update: install migrate static`

I'll have to get around to looking into the backup issues for you.

**Comment by a7hybnj2** [comment]
@SchrodingersGat I just had a second so I ssh'ed into my box and pulled and `make update` and got the following errors. I will be back physically at the computer on Monday and can try to fix anything.

```
root@InvenTree:~/InvenTree # make update
cd InvenTree && python3 manage.py dbbackup
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'markdownx'
*** Error code 1

Stop.
make: stopped in /root/InvenTree
root@InvenTree:~/InvenTree # 
```

**Comment by chschlue** [comment]
`make update` doesn't pull markdownx and markdownify. Manually installing does the trick for me.

**Comment by a7hybnj2** [comment]
I’ll give it a try. Guess need to add that to the requirements for install now.

Feb 2, 2020, 00:10 by notifications@github.com:

**Comment by SchrodingersGat** [comment]
Ah, it would appear that the 'backup' command expects all required packages to be installed. 

Run `make install` to ensure the packages are up to date, then run `make update`.

I'll tweak the makefile slightly to make this a bit simpler.

**Comment by a7hybnj2** [comment]
Just pulled and `make update` and it pulled dependencies and it all seems to be working.

# Notes are great!
