### ISSUE TITLE
Single picture for multiple components

### ISSUE THREAD

**Issue by nchokoev** [inventree/InvenTree#622]
It looks like I cannot choose a component picture from already uploaded pictures for other components.
Use case is when, for example, I have multiple resistors. They all have one picture, but are essentially different components. I don't want to upload one and the same photo for each entry, but rather use a already uploaded one.

**Comment by a7hybnj2** [comment]
Beat me to suggesting the same thing.

**Comment by SchrodingersGat** [comment]
It is a good idea. I'm not sure how the existing images should be presented to the user for selection. Maybe a "select from existing images" button which brings up a window that has a grid of existing part images? These images could be sorted by "most popular" so resistors / caps would be at the top

**Comment by Zeigren** [comment]
This would be great for things like attachments too. I was looking at [django-filebrowser](https://github.com/sehmaschine/django-filebrowser), although it's aimed at doing this in the admin panel.

**Comment by SchrodingersGat** [comment]
See https://github.com/inventree/InvenTree/pull/639
