### ISSUE TITLE
"undefined" in Tooltip for Info about Pack Quantity

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#6224]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The tooltip in purchase order tables regarding pack quantities currently have an `undefined` value in it, probably a typo or something minor in the code:

![IMG_0096](https://github.com/inventree/InvenTree/assets/296454/76ed9bf1-3cc3-4cd6-a7b9-17a33214dae5)

### Steps to Reproduce

1. go to https://demo.inventree.org/part/896/?display=part-suppliers#
2. hover over the blue [i] badge to display its tooltip

### Expected behaviour

display the value as intended

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

Current version at demo.inventree.org:

# Version Information:
InvenTree-Version: 0.14.0 dev
Django Version: 3.2.23
Commit Hash: b8369fb
Commit Date: 12-01-2024

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-89-generic-x86_64-with
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@simonkuehling thanks for reporting. Should be an easy fix
