### ISSUE TITLE
Component picture from a camera

### ISSUE THREAD

**Issue by nchokoev** [inventree/InvenTree#623]
Is there a way to add a photo for a component from a camera directly?
Ideally, I'd like to take a picture and add a description in a single web page. This will help me add many components easily without having to take pictures separately and upload them...

**Comment by SchrodingersGat** [comment]
Do you mean from a webcam which the browser could use directly? I like this idea, it would require learning how the browser can access the webcam, take a photo, and make it available for upload... Currently I have no idea how such a thing would be accomplished.

**Comment by nchokoev** [comment]
Yes, that's exactly what I mean. It will be very useful especially for use from a mobile phone to enter parts faster...

**Comment by rrakso** [comment]
Hi!
As I mentioned earlier, I'd like to have an API endpoint for images upload.
I was trying to make it own, but I don't know how to use django (I'm newbie
haha)

czw., 30 sty 2020 o 11:28 nchokoev <notifications@github.com> napisał(a):

**Comment by excitedbox** [comment]
I know there are webcam libraries to do this but haven`t looked into how to implement it. You could also pull images from digikey etc. pretty easily for some parts.

**Comment by a7hybnj2** [comment]
@excitedbox Yes, I hinted at pulling from suppliers sites in my issue #614 . I would still be happy with just 2 browsers open side by side where you could drag and drop between them.

If you for instance open this:
https://i.ytimg.com/vi/g86iBXzqK2g/maxresdefault.jpg
you can drag it to the upload box here:
https://imgur.com/upload?beta
and easily post it without having to download or do any in between steps.

**Comment by excitedbox** [comment]
Yes. you could also drag and drop to copy the image location and let the server copy the image directly. Easy to do using curl in php so it should be just as easy with python.

**Comment by eeintech** [comment]
I believe this can be done with a third-party program which can capture the image from the webcam/camera and upload it to InvenTree using the Python interface: https://github.com/inventree/inventree-python

Would be fun to see anyone taking a crack at it 😃

**Comment by sintech** [comment]
Pretty simple workaround for this issue is to use smartphone to make a picture.
1. Install addon for your PC/MAC browser to generate QR code with link url to part info page.
2. Scan code on smartphone, use link url to open the same page on mobile browser.
3. Touch "Upload Part Image", select image from gallery or make new image from camera.
4. Profit

It would be even easier if part info page has QR code with current url only.
BTW, what was the idea behind current QR code containing json with: server info; part name, id and url; inventree version?

**Comment by SchrodingersGat** [comment]
@sintech the upcoming mobile app will support all these features

> BTW, what was the idea behind current QR code containing json with: server info; part name, id and url; inventree version?

The latest InvenTree version uses a much simpler QR code scheme which does not contain all this extra data. The extra data is all available by the API anyhow

**Comment by a7hybnj2** [comment]
@SchrodingersGat 
> ... the upcoming mobile app will support all these features
> 
Sorry to hijack but is there somewhere I can find a status on the mobile app? I don't see a repo for it.

**Comment by lettore** [comment]
Uploading images taken with the App is working but I can see them only on the browser interface, in the App I see a ! mark only. It's quite difficult to debug because I get no errors.

**Comment by SchrodingersGat** [comment]
@lettore what version of the app are you using?

**Comment by SchrodingersGat** [comment]
@lettore what about images uploaded via the web interface? Can you see those images in the app? Or are *all* images not displaying in the app?

**Comment by lettore** [comment]
All images are not displaying, my app version is 0.4.3 build 25 and server version 0.5.0 pre

**Comment by SchrodingersGat** [comment]
Check out the fix in #1938
