### ISSUE TITLE
Allow unallocation of one part

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#624]
So, I don't know if this is how it is susposed to work but I had a 'build' setup with my exact part needs. I ended up ruining a few chips during the process so when I went to 'complete build' I thought I would reallocate that part to include those broken chips. I did not find a way to remove the one allocation and clicking the allocate button did not allow me to change my data.

If there is a different way to account for buggered parts then let me know. If not then it would be super helpful if you could account for them afterwards.

**Comment by SchrodingersGat** [comment]
At any time (before the build is marked as "complete") you can edit the allocated parts as below:

![image](https://user-images.githubusercontent.com/10080325/74278155-dd21ad80-4d6c-11ea-8029-748dd08a2625.png)

![image](https://user-images.githubusercontent.com/10080325/74278182-e9a60600-4d6c-11ea-834a-620215d63098.png)

![image](https://user-images.githubusercontent.com/10080325/74278200-f4609b00-4d6c-11ea-9132-bcd270494b77.png)

![image](https://user-images.githubusercontent.com/10080325/74278226-ff1b3000-4d6c-11ea-89b9-4066909fc9a3.png)

**Comment by SchrodingersGat** [comment]
Does this answer sufficiently? :)

**Comment by a7hybnj2** [comment]
@SchrodingersGat OH! The additional when you click on the part name was not intuitive. I did not know that functionality was there. I thought those part links would have linked you to the part page so, I never clicked on them. Yes this works for me but maybe one of those arrows that turns 90˚ when you click it should be added.

**Comment by SchrodingersGat** [comment]
Yes this Build page is probably the one that needs the most work in terms of UX - it is the most complicated concept I think. Any additions welcome :)
