### ISSUE TITLE
Dark Reader - Theme - Black text on dark background

### ISSUE THREAD

**Issue by tomse** [inventree/InvenTree#6241]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Found a spot where the text is black in the "dark reader" theme.

### Steps to Reproduce

Enable "dark reader" theme. (Problem page: Select Stock Location)
goto part -> stock -> new stock item -> press the "open selection" button in the "Stock Location"

![image](https://github.com/inventree/InvenTree/assets/1444539/483321e5-cf9c-42ef-b4a6-41d46b13e67a)

### Expected behaviour

Text should be light gray - same as the rest of the site.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.13

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
Not stale
