### ISSUE TITLE
Change default currency doesn't recalculate values

### ISSUE THREAD

**Issue by tomse** [inventree/InvenTree#6242]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Changing default currency doesn't recalculate values for existing parts

### Steps to Reproduce

go to show parts, 
look at the price range of the parts
![image](https://github.com/inventree/InvenTree/assets/1444539/7ad0b8e8-ace3-4378-881e-548edb1921d2)

change default currency in username -> settings -> pricing -> default currency

check the price range of the parts again

![image](https://github.com/inventree/InvenTree/assets/1444539/835b7872-6509-4b3d-acf4-c4c3704dd49f)

### Expected behaviour

price for the circled item should be around DKK 180. but both EURO and DKK says ~24  (exchange rate between EURO and DKK is about 7.5)

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

13.1

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
When you change the base currency, the pricing for all parts is not immediately updated. The part pricing is re-calculated periodically.

You should be able to manually recalculate the pricing for a single part by selecting the "refresh pricing" button for a particular part - does this work?

**Comment by SchrodingersGat** [comment]
Also, here is a PR to schedule pricing updates when base currency is changed - https://github.com/inventree/InvenTree/pull/6243

**Comment by tomse** [comment]
thank you :-D
