### ISSUE TITLE
Docker logs error: Undefined Table after install

### ISSUE THREAD

**Issue by garykuipers** [inventree/InvenTree#6249]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [X] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Docker logs error: Undefined Table

psycopg2.errors.UndefinedTable: relation "label_partlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_partlabel" WHERE "label_partla...
                               ^

### Steps to Reproduce

Install Inventree with Docker
Let docker run
try to connect on port 1337, you will get a 502 error
look at docker ps, you will find :
inventree/inventree:stable   "/bin/sh ./init.sh i…"   41 hours ago   Up 1 second                     8000/tcp                                inventree-production_inventree-worker_1
continual restarts

### Relevant log output

```bash
CONTAINER ID   IMAGE                        COMMAND                  CREATED        STATUS                          PORTS                                   NAMES
a26d369456c0   nginx:stable                 "/docker-entrypoint.…"   41 hours ago   Up 41 hours                     0.0.0.0:1337->80/tcp, :::1337->80/tcp   inventree-production_inventree-proxy_1
1c112bd3fbf9   inventree/inventree:stable   "/bin/sh ./init.sh i…"   41 hours ago   Up 1 second                     8000/tcp                                inventree-production_inventree-worker_1
ceab0ac827fb   inventree/inventree:stable   "/bin/sh ./init.sh /…"   41 hours ago   Restarting (1) 15 seconds ago                                           inventree-production_inventree-server_1
0d246450a24c   postgres:13                  "docker-entrypoint.s…"   41 hours ago   Up 41 hours                     5432/tcp                                inventree-production_inventree-db_1



Failed to create label 'QR and text'
Failed to query label for 'label/inventree/part/part_label.html' - you should run 'invoke update' first!
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "label_partlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_partlabel" WHERE "label_partla...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inventree/InvenTree/label/apps.py", line 187, in create_template_label
    if model.objects.filter(label=filename).exists():
  File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 808, in exists
    return self.query.has_results(using=self.db)
  File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 561, in has_results
    return compiler.has_results()
  File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1145, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/root/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "label_partlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_partlabel" WHERE "label_partla...
```

**Comment by matmair** [comment]
have you run `inv update`?

**Comment by garykuipers** [comment]
Thanks for writting me back.

searching Inventre "inv udpate" brings up one entry which points to a github error

(why is there no docuemntattion about this??)

Anyway: looking at that I see this instructions in that post that say to do this.

postgres@ssaass:/home/inventree$ ls
InvenTree  data
postgres@ssaass:/home/inventree$ cd InvenTree/
postgres@ssaass:/home/inventree/InvenTree$ ls
CONTRIBUTING.md  InvenTree  Procfile   RELEASE.md   backportrc.json  contrib	  deploy  docker-compose.yml  docs    package-lock.json  pyproject.toml   requirements-dev.in	requirements.in   runtime.txt  tasks.py
Dockerfile	 LICENSE    README.md  SECURITY.md  ci		     crowdin.yml  docker  docker.dev.env      images  package.json	 readthedocs.yml  requirements-dev.txt	requirements.txt  src	       yarn.lock
postgres@ssaass:/home/inventree/InvenTree$ inv update
Command 'inv' not found, but can be installed with:
apt install python3-invoke
Please ask your administrator.
postgres@ssaass:/home/inventree/InvenTree$ 


So:
inventree@ssaass:~$ inv update
Command 'inv' not found, but can be installed with:
sudo apt install python3-invoke
inventree@ssaass:~$ sudo apt install python3-invoke
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
... yada yada yada
Running kernel seems to be up-to-date.

Restarting services... I selected them all not knowing which=service was needed by inv update
 /etc/needrestart/restart.d/dbus.service
 systemctl restart getty@tty1.service networkd-dispatcher.service NetworkManager.service systemd-logind.service unattended-upgrades.service wpa_supplicant.service

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
inventree@ssaass:~$ inv update
Can't find any collection named 'tasks'!
inventree@ssaass:~$ 

Not clear what this does.

Since it has to do with the database I tried (from the inventree user):
 sudo su postgres
postgres@ssaass:/home/inventree$ psql
psql (14.10 (Ubuntu 14.10-1.pgdg20.04+1))
Type "help" for help.

postgres=# \l

(there we no databases other than the ones I've installed for other projects)

Should I assume that the docker install script does not install the inventree database?

**Comment by SchrodingersGat** [comment]
[As per the documentation](https://docs.inventree.org/en/stable/start/docker_prod/#initial-database-setup):

```
![image](https://github.com/inventree/InvenTree/assets/10080325/746db5a0-e8c6-4d18-bc24-d8a52a82318f)
```
