### ISSUE TITLE
[FR]  Add INR (Indian national rupee ) as currency  with symbol   ⟨₹⟩ 

### ISSUE THREAD

**Issue by ajay01994** [inventree/InvenTree#6252]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

i was facing issue  with storing inventry data as there is no support for INR local currency 

### Suggested solution

 request to pls add symbol and currency info

### Describe alternatives you've considered

maybe doing myself

### Examples of other systems

lot of open source finance related software  eg crater invoice 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
This can be done by enabling the `INR` currency in your settings file:

https://docs.inventree.org/en/stable/start/config/#supported-currencies
