### ISSUE TITLE
Raspbery pi4 instalation problems

### ISSUE THREAD

**Issue by Tolomaj** [inventree/InvenTree#6260]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hi i tried install inventree on raspbery pi 4 but without success.
I tried the installer at first but system is not supported. (Raspbian).
Same story with installation via docker.

Then i tried install as bare metall to ***'/opt/inventree'***

I install python requirements and created a PostgreSQL database without any big issues.

But i can't find config.yaml.
And when i try run `invoke update` i got error: `Can't find any collection named 'tasks'!`
also ***/home/InvenTree*** is not created.

Have you any experience with installing inventree on raspberry? 
Or any helpful recommendation?

### Steps to Reproduce

Try install inventree on raspberry in /opt/inventree directory.
Step by step by manual : https://docs.inventree.org/en/stable/start/install/

**Comment by Tolomaj** [comment]
Sorry for my mistake.
I find out that **_/home/InvenTree_** is not generated and in my case its folder **_/opt/inventree_**.

This find solve the `can't find any collection named 'tasks'!` problem. 
But now i have another problem.
After typing `invoke update` i got wall of text error:

```
Traceback (most recent call last):
  File "/usr/bin/invoke", line 11, in <module>
    load_entry_point('invoke==1.4.1', 'console_scripts', 'invoke')()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/lib/python3/dist-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/inventree/src/tasks.py", line 386, in <module>
    def update(c, skip_backup=False, frontend: bool = False, no_frontend: bool = False):
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 338, in inner
    obj = klass(
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 76, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
  File "/usr/lib/python3.9/inspect.py", line 1122, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them
```

Have you any idea what can this error cause ?

**Comment by wolflu05** [comment]
This should be due to the invoke version, see #6170 .

**Comment by Tolomaj** [comment]
wery mutch thaks. it whas old invoke

**Comment by wolflu05** [comment]
Jagst a Note: you said that you also don't got it to work with docker. Installing raspberry pi os 64 bit should work with the arm64 image on dockerhub.

**Comment by Tolomaj** [comment]
Yeah. I didn't go deeper to docker when i see the first error:

 ``` 
>o@raspberrypi:~ $ sudo docker pull inventree/inventree

Using default tag: latest
latest: Pulling from inventree/inventree
no matching manifest for linux/arm/v8 in the manifest list entries
```
But this is first time i working with docker so probably it is error on my side.

**Comment by wolflu05** [comment]
I understand, docker can look quite difficult on the first place, and might not always be the right solution, but glad that you got it working with a bare metal installation. 

Just to check out if interested, what version of raspberry pi is have you installed? The normal version or the 64 bit?

**Comment by SchrodingersGat** [comment]
@Tolomaj are you happy for us to close out this issue?

**Comment by Tolomaj** [comment]
@wolflu05 This is version of raspbery pi 4 that i run:
(i don't know in which number you are interested)

```
o@raspberrypi:~ $ hostnamectl
   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: 25070aeb79f44c94a7f7bcc85e4ba968
           Boot ID: 8b5de79ff5cc479687a0cfdebb6ba7d1
  Operating System: Raspbian GNU/Linux 11 (bullseye)
            Kernel: Linux 6.1.21-v8+
      Architecture: arm64

o@raspberrypi:~ $ uname -m
aarch64

```

**Comment by wolflu05** [comment]
`aarch64`/`arm64` sounds good, the docker image should work there normally, not not sure why you got that error.
