### ISSUE TITLE
[Enhancement] BOM price formatting

### ISSUE THREAD

**Issue by chschlue** [inventree/InvenTree#627]
BOM price column looks confusing atm, especially the first line below made my jaw drop for a moment (until I realised the exponent is just 2.)
![inventree-pricing](https://user-images.githubusercontent.com/40901018/73603813-e0a48000-4587-11ea-86ca-a5653208c52c.png)
How do fixed decimals and possibly min-mean-max sub-columns sound?
Better ideas are welcome, of course.

**Comment by SchrodingersGat** [comment]
I think this has now been fixed as a part of the improvements made in https://github.com/inventree/InvenTree/pull/642

In the future I may move to a min/max column - I think the BOM pricing idea needs some other improvements too. Thanks for pointing this out, I hadn't seen it display in scientific notation before!
