### ISSUE TITLE
[PUI] Recent auth updates have broken API in debug mode

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6290]
- Ref: https://github.com/inventree/InvenTree/pull/6287
- Ref: https://github.com/inventree/InvenTree/pull/6284

After applying these changes, PUI API access no longer works (at least with the development server in debug mode):

### UI Screenshot

![image](https://github.com/inventree/InvenTree/assets/10080325/a6649152-6ee0-45d2-b9a3-58deeb2db7d0)

### JS Console

![image](https://github.com/inventree/InvenTree/assets/10080325/2569a774-71b0-44d9-bdc2-1edfe3a4db9a)

@matmair can you review, based on the changed you made in the referenced PRs?

**Comment by matmair** [comment]
Seems like your CORS headers are set up wrong on your setup, I can not reproduce. Do you have explicit CORS settings in config.yaml?

**Comment by SchrodingersGat** [comment]
No, this is on two separate dev setups with stock config. It works OK in a private browsing session - seems that it is being "polluted" by a logged in CUI session
