### ISSUE TITLE
Question: Allocate Stock to Build

### ISSUE THREAD

**Issue by caiovernaglia** [inventree/InvenTree#6295]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

It isn't a bug, but a question.
There's any way to not allow a Stock Item to be allocated to multiples build orders?

Let's imagine that I have a part that is package as a reel and I have multiples reels of this part. When I allocate that part to a build order, on the Part Stock I can see a flag indicating "Stock item has been partially allocated" but, if I place another build order, while allocating the parts, I have no indication that this Stock item is already allocated.

The problem is, if I have two or more pick and places, I can allocated the same reel to multiples machines wich is impossible.

### Steps to Reproduce

1. Go to  "Allocate Stock" in Build Order
2. Defining the Stock Item (no info if that Stock Item is already allocated to another build)
![Captura de tela 2024-01-19 161734](https://github.com/inventree/InvenTree/assets/24217191/c4107312-a546-4215-82db-d4177de3bf68)

### Expected behaviour

A warning flag saying that Stock Item is already beem allocated to another BO.

Maybe some checkbox in "New Stock Item" saying that this stock item cannot be allocated to multiples BO.
I think that we should manually define that because, if a part is not a reel, I can allocate to multiples BO.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.2
Django Version: 3.2.23
Commit Hash: ddd65cf
Commit Date: 17/01/2024

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Currently this check is not implemented, but it would theoretical to implement it.
