### ISSUE TITLE
[FR] Improve Docker deployment 

### ISSUE THREAD

**Issue by ChristianSchindler** [inventree/InvenTree#6303]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I want to suggest to simply the deployment of Docker.

1) I would like that you only need no longer a `Server` and `worker` but only use 1
2) invoke updates of the db when you start a newer version of the container and updates are done 
3) many include also Nginx 

### Suggested solution

For the first two make a script with first checks if we are in first created, update or reboot and run `invoke update ` then start both process 

### Describe alternatives you've considered

Implent it directly in the docker file but this makes it more complex 

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
I am not sure how scalable and reliable the system would be with the suggested changes, after all we have deployments with 100k+ items and hundreds of background tasks a minute so this is certainly something that would need extensive validation with power users.

2. Would be a no for me - invoke updates does more than just DB updates and only running those can lead to problems (we have automigrations as an option in the config file but it presents problems form time to time and is off by default). Running a full update cycle can take minutes on larger deployments - probably leading to a lot of confusion if InvenTree suddenly just isn't comming up
3. I do not understand this point, could you expand this a bit?

**Comment by matmair** [comment]
1. I do not think we will support this approach
2. invoke update has to be run after every upgrade - this is essential for a functioning instance. I do not see a value in this beeing controlable
3. We do not ship a static file hoster (the debug server is not designed to handle this) so a webserver is a must

**Comment by ChristianSchindler** [comment]
If we run `invoke update` on every update it makes even more sense to automate it because then it is less likely to get user errors

**Comment by SchrodingersGat** [comment]
@ChristianSchindler I am happy to consider a PR which can run `invoke update` on container start, if it needs to be updated - but I am not keen to change the overall construct of the container services (i.e. combining two containers into one).

**Comment by ChristianSchindler** [comment]
@SchrodingersGat I think also that this is the most important part. What happens when the worker is running and `invoke update` simultaneously? Does this crash something?
