### ISSUE TITLE
[React] New markdown editor

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6306]
For fields that support markdown (like "notes") we currenly use easymde.

However it looks like mdx-editor would be a better choice - https://github.com/mdx-editor/editor

It supports mode advanced editing features (including image resizing) and a better, more "modern" look and feel. Better react support too.

**Comment by matmair** [comment]
Something more modular (enableing mentions and inline links linke GitHub has) like tiptap might also be intresting

**Comment by wolflu05** [comment]
I like that there is a WYSIWYG and diff editor, but still a source editor. But we need to consider that change well, because there are some special markdown flavors involved that maybe people will use and break later if we migrate to something else.
