### ISSUE TITLE
Exporting a Stock table does not include the "Stock value" column

### ISSUE THREAD

**Issue by JambonLeVrai** [inventree/InvenTree#6321]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The "Stock value" column, which is displayed when displaying the stock, is not exported when performing an export.

### Steps to Reproduce

1. Navigate to stock menu
2. Click Download table data and download the data in any format
3. Open and check the exported file

### Expected behaviour

I would expect this column to be exported along with the rest. It seems pretty straightforward, since the export function exports pretty much all the info displayed on the table of the inventree frontend, that it would also export this column. 
The "stock value" also includes some valuable information that cannot be obtained from the other columns, since it gives a value to a stock item even if it is not tied to a purchase order (and therefore does not have a purchase price) or if it is an assembly (where the value is computed from the components of the assembly).

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.3
Django Version: 3.2.23
Commit Hash: e81349e
Commit Date: 22/01/2024

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-91-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/6321">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/6321/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/6321/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@JambonLeVrai can you please provide an example screenshot of the data you are looking to export here? I'm not sure exactly what you're asking for

**Comment by JambonLeVrai** [comment]
On the image, the column I am talking about is the one I framed in red :
![image](https://github.com/inventree/InvenTree/assets/6325304/ca6b77de-5768-492a-9b93-d10464af833e)
And whenever the stock is exported (here I took .xlsx as an example) we get all those columns :
![image](https://github.com/inventree/InvenTree/assets/6325304/18298524-cf83-4d9b-8b00-9b87f46a3fbc)
Where the stock value column is missing. In this example, on the second line there is no purchase price, because the stock wasn't tied to a purchase order, but is still valued thanks to the other pricings available in the database ; this is the information I would like to keep when exporting the stock.

**Comment by SchrodingersGat** [comment]
@JambonLeVrai I see what you are saying. This could be added in to the export feature. Would you be willing to sponsor this? There are a lot of other features on our development schedule :)

**Comment by JackFGS** [comment]
Not Stale

**Comment by SchrodingersGat** [comment]
This is now implemented in #6911
