### ISSUE TITLE
Camera icon not shown on barcode pop-up

### ISSUE THREAD

**Issue by coratron** [inventree/InvenTree#6336]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The camera icon is missing on the Barcode pop-up menu, which means I am unable to use the webcam to scan.

### Steps to Reproduce

- My webcam works on the browsers - tested
- I have created a part just in case this was a pre-requisite
- Barcode Support and Barcode Webcam Support are both enabled under Settings>Barcode Support

1. Open the Barcode pop-up from the top bar
2. The camera icon is missing on the far right (see picture below)
![image](https://github.com/inventree/InvenTree/assets/33310086/ad5aeca9-0d13-4d65-bc38-9344ee5785e5)

### Expected behaviour

I'd expect the camera icon to be present and to give me access to the webcam to scan Barcodes as shown on the documentation page.
![image](https://github.com/inventree/InvenTree/assets/33310086/a40dd3a9-a635-4b5c-80ce-7e282799be6d)

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.4
Django Version: 3.2.23
Commit Hash: 6a66be3
Commit Date: 2024-01-24

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-17-amd64-x86_64-with
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can't reproduce this bug on the demo site. After having the pop-up open for several seconds the browser requests permission to access the webcam, after granting it, the icon appears. Perhaps a docker-specific problem?

**Comment by coratron** [comment]
Maybe related but it seems different:
https://github.com/inventree/InvenTree/issues/4105

**Comment by wolflu05** [comment]
Can you test this with a private (incognito) tab? Maybe you have already set the camera permissions to deny for that site. And also this shouldn't be related to docker, that's just the browser.

**Comment by coratron** [comment]
Thanks for your prompt reply, @wolflu05 . I have tested in incognito mode, with the same result - the icon is still missing. This was mostly expected as I normally use Firefox for everything and the same result was observed on Chrome as well.

**Comment by coratron** [comment]
@wolflu05 , OK I have just found the culprit:
`Uncaught (in promise) Camera access is only supported in secure context like https or localhost.`
I am running Inventree on a home server, local network.

**Comment by wolflu05** [comment]
Oh right, that could also be the case. That means you have to setup https certificates on your server so that the browser know the environment is safe.

**Comment by coratron** [comment]
@wolflu05 yes, I think that's what I would have to do. I purchased the App anyway so I will be using that as it's much more convenient and works great on the local network.

**Comment by matmair** [comment]
@coratron do you consider this solved or can we assist in getting this corrected in your setup?

**Comment by Con30** [comment]
While not the best security practices, if you are on a trusted network you can add the URL to the list of trusted URLs via Chrome's flags: [Chrome ]( chrome://flags/#unsafely-treat-insecure-origin-as-secure )

**Comment by coratron** [comment]
@matmair I think we can close this issue. Thanks @Con30 , I am aware of the different approaches to solve this problem now that I know what the issue was. We can close this, it will hopefully help some other users.
