### ISSUE TITLE
Slow docker build times on master

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#6344]
## Problem

We are currently occuring around 2.5 hours of build times on docker. This makes integrated CI/CD workflows like canary deployments very lon running - not ideal for fast paced development

## Possible solutions

I played around with this [on my fork](https://github.com/matmair/InvenTree/tree/docker-tests) and here are some possible solutions:
1. Split the build and push action per plattform (amd64, arm64) (via a matrix build) -> Faster availability of the images that are already done
2. Create a custom Pypi index with all the missing wheels (like sentry for example) -> Wheel builds are one of the mayor hold ups
3. Switch to python 3.11 or 3.12 for the image (breaking!) -> better availabilty of new wheels, performance improvements
4. Use Arm-based builders (either GitHubs MacOS machines, 3rd party machines or self-hosted runners on our sponsor DigitalOcean)

**Comment by kgantchev** [comment]
> Use Arm-based builders (either GitHubs MacOS machines, 3rd party machines or self-hosted runners on our sponsor DigitalOcean)

Hi @matmair 

I apologize if I'm intruding here, but if you're considering MacOS runners, may I suggest giving [FlyCI](https://flyci.net) a try? We offer MacOS M1 and M2 runners that are faster than GitHub's. For public repos, we offer 500 mins/month of free M1 usage (4 vCPUs, 7 GB RAM, 28 GB storage).

We're a startup that just launched our public Beta, so you're able to experiment with all of our runners for free until we enable billing (within a few weeks). After that, the standard free tier applies.

Do you think this might be a good option for InvenTree? 

Web: [flyci.net](https://flyci.net/) | Twitter: [flyciapp](https://twitter.com/flyciapp) | LinkedIn: [FlyCI](https://linkedin.com/company/flyci) | Discord: [FlyCI](https://discord.gg/JyCjh439da)

**Comment by matmair** [comment]
I will test it, we might need to optimize the pipeline to cut down on cycles enough to only need 500 cycles

**Comment by matmair** [comment]
@wolflu05 I would be intrested in your view of this as you already proofed to be knowledgeable with your work on docker/infrastructure things

**Comment by wolflu05** [comment]
@matmair I think all your possible solutions make sense, but we should start with the easier ones. Bumping the python versions also makes sense due to the performance improvements which came with python 3.11. And if there are more wheels for arm64 available, we could use them. One other thing we could do is using the gh actions cache for wheels caching, that woudnt require us to host some extra infrastructure (We could even try out caching docker image layers, but the gh actions cache is limited to 10GB/repo in the free variant, so we would have to first check if that would exceed that size.).

**Comment by matmair** [comment]
@kgantchev we have reviewed your offering and discussed it among devs. TBH there is far to less info about your company, your security / trust setup and track record online to use you for a critical application like CI/CD. Thank you for the generous offer though.

**Comment by kgantchev** [comment]
@matmair no problem. I understand your concern. We recently launched our startup so we haven't had enough time to provide all of that information. I presume your team is interested in knowing our security certificates. I'll circle back around when all of that information is available (if that's OK with you).

**Comment by matmair** [comment]
My main concern is with infrastructure attestation and visibility into security proesses/culture (Trust center with ISO 27001 or SOC2, visible security staff and following standards like security.txt). Feel free to ping me here - options are good for a competetive market.

**Comment by kgantchev** [comment]
@matmair will do! Thanks for sharing the info.
