### ISSUE TITLE
Installation issue "no collection found named 'tasks' "

### ISSUE THREAD

**Issue by JigarJoshi04** [inventree/InvenTree#6346]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

When we tried to run the installer script, it worked.
Installation was competed.
Later on while running `invoke server`
we get an error saying "no collection found named 'tasks' "

### Steps to Reproduce

Just run the script and run invoke server

### Relevant log output

```bash
no collection found named 'tasks'
```

**Comment by JigarJoshi04** [comment]
https://github.com/Atharva-H regarding the same issue we discussed over call :)

**Comment by matmair** [comment]
@JigarJoshi04 if you are using package installer you need to use `inventree run invoke` instead of `invoke`.

**Comment by JigarJoshi04** [comment]
This worked for me.
Closing this issue.

Thanks @matmair for help.
