### ISSUE TITLE
Specifying NULL in related queries through OpenAPI generated bindings

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#6347]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I have started to use some generated code from the OpenAPI descriptor in C++/Qt and came across a limitation which caused me some issues.

There are filter fields for certain API calls, where filters made on relations, like the parent field of the build's:
![kép](https://github.com/inventree/InvenTree/assets/1609182/f0cb64c2-0ff2-431e-9db7-9be180d0a374)

The generated API's build_List method will have a `    * @param[in]  parent qint32 [optional]` argument which could be only specified as 0 due to the C++ typing.

However this request is going to rejected by the InvenTree as parent with pk 0 not found. 
If I pass an empty string manually as the filter value then the API works as expected, however the generated API does not allow to do so due to the nature of the typed environment. 

Is it something what you would be open to fix on the InvenTree side (handle '0' as NULL in the related filters), or shall I focus on implementing some workaround into the generated API code?

### Steps to Reproduce

-

### Expected behaviour

-

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

master

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

### Relevant log output

```shell
-
```

**Comment by matmair** [comment]
I think handeling 0 as Null in the backend is a bad pattern, the client should send correct calls.

**Comment by martonmiklos** [comment]
> I think handeling 0 as Null in the backend is a bad pattern, the client should send correct calls.

Alright then I need to tinker with the openapitools-codegen as the parameters are nullable in the schema.

**Comment by martonmiklos** [comment]
Cross reference to the openapi-codegen issue in the case if someone runs into the same trouble:
[17756](https://github.com/OpenAPITools/openapi-generator/issues/17756)
