### ISSUE TITLE
[FR]Add servers section to the OpenAPI schema

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#6350]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

As I mentioned in the #4587 some of the openapi-codegen generators (Qt/C++ client generator for sure) expects the servers section to be present in the schema descriptor yaml file, because they generating the API endpoints to the code.

The InvenTree generated schema lacks it so it has to be manually extended before generating code.

### Suggested solution

It would be straightforward to add the servers section into the SPECTACULAR_SETTINGS in the [settings.py](https://github.com/inventree/InvenTree/blob/master/InvenTree/InvenTree/settings.py#L489), however I have no idea how can I 'smuggle' the re the base url. 

### Describe alternatives you've considered

Adding manually.

### Examples of other systems

-

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
There is an active PR for openApi generation, maybe feedback regarding the schema should be placed there: https://github.com/inventree/InvenTree/pull/6319

**Comment by SchrodingersGat** [comment]
@martonmiklos you are asking for the ability to have the local instance base URL in the servers section? as in, when you run `invoke schema` locally, the "server" will include *your* server URL?

**Comment by martonmiklos** [comment]
@SchrodingersGat well I was not aware of the local `invoke server` command I have used the /schema/ endpoint so far. It would be good if via that endpoint the servers section would be filled with the same url base through what I downloading the schema.

**Comment by SchrodingersGat** [comment]
Check out this PR - https://github.com/inventree/InvenTree/pull/6463 - I have made a change which allows this to be filled out, *if* you have a globally defined SITE URL

**Comment by SchrodingersGat** [comment]
Closed by #6463
