### ISSUE TITLE
Unable to add stock when 'Tackable' option is set.

### ISSUE THREAD

**Issue by keitarusm** [inventree/InvenTree#636]
When the 'Trackable' option is set on the Part page, I am unable to add stock through either the part page stock tab with the 'new stock item' button or through the Stock view 'new stock item' button. 

Leaving the serial number field blank causes the attempt to fail silently. Adding a serial number like '1' for example, cause the attempt to give an error 500, and the stock item will be present upon page refresh.

> TypeError at /stock/item/new Object of type Part is not JSON serializable Request Method: POST Request URL: http://10.10.10.186:8000/stock/item/new Django Version: 2.2.9 Python Executable: /home/pi/WRTapps/TEMPinventory/inventree-env/bin/python3 Python Version: 3.7.3 Python Path: ['/home/pi/WRTapps/TEMPinventory/inventree/InvenTree', '/home/pi/WRTapps/TEMPinventory/inventree-env/bin', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages', '/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/odf', '/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/odf', '/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/odf', '/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/odf', '/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/odf', '/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/odf', '/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/odf'] Server time: Wed, 5 Feb 2020 19:22:59 +0000 Installed Applications: ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'common.apps.CommonConfig', 'part.apps.PartConfig', 'stock.apps.StockConfig', 'company.apps.CompanyConfig', 'build.apps.BuildConfig', 'order.apps.OrderConfig', 'django_filters', 'dbbackup', 'rest_framework', 'rest_framework.authtoken', 'corsheaders', 'crispy_forms', 'import_export', 'django_cleanup', 'qr_code', 'mptt', 'markdownx', 'markdownify'] Installed Middleware: ['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'corsheaders.middleware.CorsMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'InvenTree.middleware.AuthRequiredMiddleware', 'InvenTree.middleware.QueryCountMiddleware'] Traceback: File "/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner 34. response = get_response(request) File "/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response 115. response = self.process_exception_by_middleware(e, request) File "/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response 113. response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/django/views/generic/base.py" in view 71. return self.dispatch(request, *args, **kwargs) File "/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/django/views/generic/base.py" in dispatch 97. return handler(request, *args, **kwargs) File "/home/pi/WRTapps/TEMPinventory/inventree/InvenTree/stock/views.py" in post 929. return self.renderJsonResponse(request, form, data=data) File "/home/pi/WRTapps/TEMPinventory/inventree/InvenTree/InvenTree/views.py" in renderJsonResponse 186. return JsonResponse(data, safe=False) File "/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/django/http/response.py" in __init__ 558. data = json.dumps(data, cls=encoder, **json_dumps_params) File "/usr/lib/python3.7/json/__init__.py" in dumps 238. **kw).encode(obj) File "/usr/lib/python3.7/json/encoder.py" in encode 199. chunks = self.iterencode(o, _one_shot=True) File "/usr/lib/python3.7/json/encoder.py" in iterencode 257. return _iterencode(o, 0) File "/home/pi/WRTapps/TEMPinventory/inventree-env/lib/python3.7/site-packages/django/core/serializers/json.py" in default 104. return super().default(o) File "/usr/lib/python3.7/json/encoder.py" in default 179. raise TypeError(f'Object of type {o.__class__.__name__} ' Exception Type: TypeError at /stock/item/new Exception Value: Object of type Part is not JSON serializable Request information: USER: admin GET: No GET data POST: csrfmiddlewaretoken = 'BWduzBDDDkRb0LpDXZogP3dXshSqLt7DAypDlvwDJa7pnpCVelL90y7YMU43qzOd' part = '2' supplier_part = '' location = '1' quantity = '1' batch = '' serial_numbers = '1' delete_on_deplete = 'False' status = '10' notes = '' URL = '' FILES: No FILES data COOKIES: tabstyle = 'html-tab' csrftoken = 'SZ9dFJsojXMpNHQT9QukTUJqttUsgXN8RBlmrDlopN2Dal3bqcRd4pDrN665V3uI' sessionid = 'lqpohv7vu1pq9w8n8f5xda8pt94lsazn' META: CONTENT_LENGTH = '1348' CONTENT_TYPE = 'multipart/form-data; boundary=----WebKitFormBoundarySVgDnqtpGRCZTXaX' CSRF_COOKIE = 'SZ9dFJsojXMpNHQT9QukTUJqttUsgXN8RBlmrDlopN2Dal3bqcRd4pDrN665V3uI' CSRF_COOKIE_USED = True HTTP_ACCEPT = '*/*' HTTP_ACCEPT_ENCODING = 'gzip, deflate' HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.9' HTTP_CONNECTION = 'keep-alive' HTTP_COOKIE = 'tabstyle=html-tab; csrftoken=SZ9dFJsojXMpNHQT9QukTUJqttUsgXN8RBlmrDlopN2Dal3bqcRd4pDrN665V3uI; sessionid=lqpohv7vu1pq9w8n8f5xda8pt94lsazn' HTTP_DNT = '1' HTTP_HOST = '10.10.10.186:8000' HTTP_ORIGIN = 'http://10.10.10.186:8000' HTTP_REFERER = 'http://10.10.10.186:8000/part/2/stock' HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36' HTTP_X_REQUESTED_WITH = 'XMLHttpRequest' PATH_INFO = '/stock/item/new' QUERY_STRING = '' RAW_URI = '/stock/item/new' REMOTE_ADDR = '10.10.10.166' REMOTE_PORT = '51875' REQUEST_METHOD = 'POST' SCRIPT_NAME = '' SERVER_NAME = '10.10.10.186' SERVER_PORT = '8000' SERVER_PROTOCOL = 'HTTP/1.1' SERVER_SOFTWARE = 'gunicorn/20.0.4' gunicorn.socket = wsgi.errors = wsgi.file_wrapper = '' wsgi.input = wsgi.input_terminated = True wsgi.multiprocess = True wsgi.multithread = False wsgi.run_once = False wsgi.url_scheme = 'http' wsgi.version = '(1, 0)' Settings: Using settings module InvenTree.settings ABSOLUTE_URL_OVERRIDES = {} ADMINS = [] ALLOWED_HOSTS = ['*'] APPEND_SLASH = True AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend'] AUTH_PASSWORD_VALIDATORS = '********************' AUTH_USER_MODEL = 'auth.User' BASE_DIR = '/home/pi/WRTapps/TEMPinventory/inventree/InvenTree' CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}, 'qr-code': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 'LOCATION': 'qr-code-cache', 'TIMEOUT': 3600}} CACHE_MIDDLEWARE_ALIAS = 'default' CACHE_MIDDLEWARE_KEY_PREFIX = '********************' CACHE_MIDDLEWARE_SECONDS = 600 CONFIG = {'database': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': '../inventree_default_db.sqlite3', 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'OPTIONS': {}, 'TIME_ZONE': None, 'USER': '', 'PASSWORD': '********************', 'HOST': '', 'PORT': '', 'TEST': {'CHARSET': None, 'COLLATION': None, 'NAME': None, 'MIRROR': None}}, 'language': 'en-us', 'debug': True, 'allowed_hosts': ['*'], 'cors': {'allow_all': True}, 'media_root': '/home/pi/WRTapps/TEMPinventory/inventree_media', 'static_root': '/home/pi/WRTapps/TEMPinventory/inventree_static', 'log_queries': True, 'backup_dir': '/home/pi/WRTapps/TEMPinventory/inventree-backups/'} CORS_ORIGIN_ALLOW_ALL = True CORS_URLS_REGEX = '^/api/.*$' CRISPY_TEMPLATE_PACK = 'bootstrap' CSRF_COOKIE_AGE = 31449600 CSRF_COOKIE_DOMAIN = None CSRF_COOKIE_HTTPONLY = False CSRF_COOKIE_NAME = 'csrftoken' CSRF_COOKIE_PATH = '/' CSRF_COOKIE_SAMESITE = 'Lax' CSRF_COOKIE_SECURE = False CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure' CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN' CSRF_TRUSTED_ORIGINS = [] CSRF_USE_SESSIONS = False DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': '../inventree_default_db.sqlite3', 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'OPTIONS': {}, 'TIME_ZONE': None, 'USER': '', 'PASSWORD': '********************', 'HOST': '', 'PORT': '', 'TEST': {'CHARSET': None, 'COLLATION': None, 'NAME': None, 'MIRROR': None}}} DATABASE_ROUTERS = [] DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440 DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000 DATETIME_FORMAT = 'N j, Y, P' DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%Y', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M', '%m/%d/%y'] DATE_FORMAT = 'N j, Y' DATE_INPUT_FORMATS = ['%Y-%m-%d'] DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage' DBBACKUP_STORAGE_OPTIONS = {'location': '/home/pi/WRTapps/TEMPinventory/inventree-backups/'} DEBUG = True DEBUG_PROPAGATE_EXCEPTIONS = False DECIMAL_SEPARATOR = '.' DEFAULT_CHARSET = 'utf-8' DEFAULT_CONTENT_TYPE = 'text/html' DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter' DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage' DEFAULT_FROM_EMAIL = 'webmaster@localhost' DEFAULT_INDEX_TABLESPACE = '' DEFAULT_TABLESPACE = '' DISALLOWED_USER_AGENTS = [] EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' EMAIL_HOST = 'localhost' EMAIL_HOST_PASSWORD = '********************' EMAIL_HOST_USER = '' EMAIL_PORT = 25 EMAIL_SSL_CERTFILE = None EMAIL_SSL_KEYFILE = '********************' EMAIL_SUBJECT_PREFIX = '[Django] ' EMAIL_TIMEOUT = None EMAIL_USE_LOCALTIME = False EMAIL_USE_SSL = False EMAIL_USE_TLS = False EXTRA_URL_SCHEMES = [] FILE_CHARSET = 'utf-8' FILE_UPLOAD_DIRECTORY_PERMISSIONS = None FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler'] FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440 FILE_UPLOAD_PERMISSIONS = None FILE_UPLOAD_TEMP_DIR = None FIRST_DAY_OF_WEEK = 0 FIXTURE_DIRS = [] FORCE_SCRIPT_NAME = None FORMAT_MODULE_PATH = None FORM_RENDERER = 'django.forms.renderers.DjangoTemplates' IGNORABLE_404_URLS = [] IMPORT_EXPORT_USE_TRANSACTIONS = True INSTALLED_APPS = ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'common.apps.CommonConfig', 'part.apps.PartConfig', 'stock.apps.StockConfig', 'company.apps.CompanyConfig', 'build.apps.BuildConfig', 'order.apps.OrderConfig', 'django_filters', 'dbbackup', 'rest_framework', 'rest_framework.authtoken', 'corsheaders', 'crispy_forms', 'import_export', 'django_cleanup', 'qr_code', 'mptt', 'markdownx', 'markdownify'] INTERNAL_IPS = [] LANGUAGES = [('en', 'English'), ('de', 'German'), ('fr', 'French'), ('pk', 'Polish')] LANGUAGES_BIDI = ['he', 'ar', 'fa', 'ur'] LANGUAGE_CODE = 'en-us' LANGUAGE_COOKIE_AGE = None LANGUAGE_COOKIE_DOMAIN = None LANGUAGE_COOKIE_NAME = 'django_language' LANGUAGE_COOKIE_PATH = '/' LOCALE_PATHS = "('/home/pi/WRTapps/TEMPinventory/inventree/InvenTree/locale/',)" LOGGING = {'version': 1, 'disable_existing_loggers': False, 'handlers': {'console': {'level': 'DEBUG', 'class': 'logging.StreamHandler'}}} LOGGING_CONFIG = 'logging.config.dictConfig' LOGIN_REDIRECT_URL = '/accounts/profile/' LOGIN_URL = '/accounts/login/' LOGOUT_REDIRECT_URL = None MANAGERS = [] MARKDOWNIFY_BLEACH = True MARKDOWNIFY_WHITELIST_ATTRS = ['href', 'src', 'alt'] MARKDOWNIFY_WHITELIST_TAGS = ['a', 'abbr', 'b', 'blockquote', 'em', 'h1', 'h2', 'h3', 'i', 'img', 'li', 'ol', 'p', 'strong', 'ul'] MARKDOWNX_MEDIA_PATH = 'markdownx/2020/02/05' MEDIA_ROOT = '/home/pi/WRTapps/TEMPinventory/inventree_media' MEDIA_URL = '/media/' MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage' MIDDLEWARE = ['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'corsheaders.middleware.CorsMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'InvenTree.middleware.AuthRequiredMiddleware', 'InvenTree.middleware.QueryCountMiddleware'] MIGRATION_MODULES = {} MONTH_DAY_FORMAT = 'F j' NUMBER_GROUPING = 0 PASSWORD_HASHERS = '********************' PASSWORD_RESET_TIMEOUT_DAYS = '********************' PREPEND_WWW = False QR_CODE_CACHE_ALIAS = 'qr-code' REST_FRAMEWORK = {'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler', 'DATETIME_FORMAT': '%Y-%m-%d %H:%M', 'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.BasicAuthentication', 'rest_framework.authentication.SessionAuthentication', 'rest_framework.authentication.TokenAuthentication'), 'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'} ROOT_URLCONF = 'InvenTree.urls' SECRET_KEY = '********************' SECURE_BROWSER_XSS_FILTER = False SECURE_CONTENT_TYPE_NOSNIFF = False SECURE_HSTS_INCLUDE_SUBDOMAINS = False SECURE_HSTS_PRELOAD = False SECURE_HSTS_SECONDS = 0 SECURE_PROXY_SSL_HEADER = None SECURE_REDIRECT_EXEMPT = [] SECURE_SSL_HOST = None SECURE_SSL_REDIRECT = False SERVER_EMAIL = 'root@localhost' SESSION_CACHE_ALIAS = 'default' SESSION_COOKIE_AGE = 1209600 SESSION_COOKIE_DOMAIN = None SESSION_COOKIE_HTTPONLY = True SESSION_COOKIE_NAME = 'sessionid' SESSION_COOKIE_PATH = '/' SESSION_COOKIE_SAMESITE = 'Lax' SESSION_COOKIE_SECURE = False SESSION_ENGINE = 'django.contrib.sessions.backends.db' SESSION_EXPIRE_AT_BROWSER_CLOSE = False SESSION_FILE_PATH = None SESSION_SAVE_EVERY_REQUEST = False SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer' SETTINGS_MODULE = 'InvenTree.settings' SHORT_DATETIME_FORMAT = 'm/d/Y P' SHORT_DATE_FORMAT = 'm/d/Y' SIGNING_BACKEND = 'django.core.signing.TimestampSigner' SILENCED_SYSTEM_CHECKS = [] STATICFILES_DIRS = ['/home/pi/WRTapps/TEMPinventory/inventree/InvenTree/InvenTree/static'] STATICFILES_FINDERS = ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder'] STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage' STATIC_ROOT = '/home/pi/WRTapps/TEMPinventory/inventree_static' STATIC_URL = '/static/' TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': ['/home/pi/WRTapps/TEMPinventory/inventree/InvenTree/templates'], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}] TEST_NON_SERIALIZED_APPS = [] TEST_RUNNER = 'django.test.runner.DiscoverRunner' THOUSAND_SEPARATOR = ',' TIME_FORMAT = 'P' TIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M'] TIME_ZONE = 'UTC' USE_I18N = True USE_L10N = True USE_THOUSAND_SEPARATOR = False USE_TZ = True USE_X_FORWARDED_HOST = False USE_X_FORWARDED_PORT = False WSGI_APPLICATION = 'InvenTree.wsgi.application' X_FRAME_OPTIONS = 'SAMEORIGIN' YEAR_MONTH_FORMAT = 'F Y' You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by SchrodingersGat** [comment]
Ok I am able to replicate this

**Case 1 - Create Stock Item without S/N**
- No error message
- No stock created

**Case 2 - Create Stock Item with S/N**
- Error message as above
- Stock items ARE created

I will look into this ASAP, it's pretty critical! Thanks for reporting.

**Comment by a7hybnj2** [comment]
I don't want to hijack but can you explain what the trackable option does? I looked in the user docs and did not see it called out. If you have it 'trackable by serial number' what parameters does that change?

**Comment by SchrodingersGat** [comment]
@a7hybnj2 it does need to be documented better. A "trackable" part means that you can assign a serial number, and keep track of individual stockitems, rather than just bulk item quantities.

e.g. a laptop is serial-tracked, but the capacitors on the motherboard are not... If that makes sense.

Eventually this concept will be expanded such that tracked items are unable to be deleted, and you can keep track of these special items even if they are installed into another item, for example.

**Comment by keitarusm** [comment]
Thanks for looking at this. This functionality is really important to me down the line. InvenTree as a whole is a beautiful product. I can't wait to see where it goes.

**Comment by SchrodingersGat** [comment]
This should be fixed now - please confirm :)
