### ISSUE TITLE
WSL Docker Development "invoke install" : ValueError("Function has keyword-only parameters or annotations"

### ISSUE THREAD

**Issue by chouvaevandrei** [inventree/InvenTree#6361]
### Deployment Method

- [ ] Installer
- [X] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hi,

I'm trying to install Inventree Docker Development environment, using Debian in WSL on aWindows 10 machine.

But I get this message.

`sudo docker compose run inventree-dev-server invoke install
[+] Building 0.0s (0/0)                                                                                                      docker:default
[+] Creating 1/0
 ✔ Container inventree-inventree-dev-db-1  Running                                                                                     0.0s
[+] Building 0.0s (0/0)                                                                                                      docker:default
Creating directory
Copying config file to /home/inventree/data/config.yaml
Running first time setup for python environment
Requirement already satisfied: pip in ./data/env/lib/python3.9/site-packages (22.0.4)
Collecting pip
  Downloading pip-23.3.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 8.5 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./data/env/lib/python3.9/site-packages (58.1.0)
Collecting setuptools
  Downloading setuptools-69.0.3-py3-none-any.whl (819 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.5/819.5 KB 8.8 MB/s eta 0:00:00
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-23.3.2 setuptools-69.0.3
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/local/lib/python3.9/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/local/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/local/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/inventree/tasks.py", line 387, in <module>
    def update(
  File "/usr/local/lib/python3.9/site-packages/invoke/tasks.py", line 357, in inner
    obj = klass(
  File "/usr/local/lib/python3.9/site-packages/invoke/tasks.py", line 76, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/local/lib/python3.9/site-packages/invoke/tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/local/lib/python3.9/site-packages/invoke/tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
  File "/usr/local/lib/python3.9/inspect.py", line 1122, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them`

I saw that the same problem occured for someone else (issue [#6170)](https://github.com/inventree/InvenTree/issues/6170) on a Production installation, that was caused by an out of date Invoke. However mine is up to date.

I've searched several days and even tried to recompile Python (didn't knew if it was usefull or not) to /usr/local/lib directory, but it didn't help.

Have I missed something ?

Thanks in advance :)

### Steps to Reproduce

0. New Install of Debian in WSL
1. Then follow Quickstart for the Docker Dev installation, with just the two first commands.

**Comment by SchrodingersGat** [comment]
Hmm, that's intersesting. Can you run the following command to double check your invoke version?

```bash
docker compose run inventree-dev-server pip show invoke
```

**Comment by chouvaevandrei** [comment]
Well that's akward ^^'.

```
bob@P3520:~/InvenTree$ sudo docker compose run inventree-dev-server pip show invoke
[+] Building 0.0s (0/0)                                                                                                      docker:default
[+] Creating 1/0
 ✔ Container inventree-inventree-dev-db-1  Running                                                                                     0.0s
[+] Building 0.0s (0/0)                                                                                                      docker:default
Creating directory
Loading config file : /home/inventree/data/config.yaml
Using Python virtual environment: /home/inventree/data/env
Name: invoke
Version: 1.7.1
Summary: Pythonic task execution
Home-page: https://pyinvoke.org
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: BSD
Location: /usr/local/lib/python3.9/site-packages
Requires:
Required-by:
```

I think I've been updating the systems overall pip invoke package...

Anywho, your command made me think to update the invoke package through :
```
docker compose run inventree-dev-server pip install invoke --upgrade
```

... and it worked !

Issue resolved, but still it has to be done before continuing the installation.

Sorry for the incovenience.
