### ISSUE TITLE
[FR] Farnell or Element14 Support

### ISSUE THREAD

**Issue by arkajyotidas** [inventree/InvenTree#6366]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Are there any plans to implement Farnell or Element14 as a supplier?

### Suggested solution

Just like lCSC or Digikey or Mouser.

### Describe alternatives you've considered

N/A

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/6366">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/6366/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/6366/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
No plans, but we would support a PR to implement this.
