### ISSUE TITLE
Translations [RU] approvement

### ISSUE THREAD

**Issue by alxrMironov** [inventree/InvenTree#6378]
I has filled the RU translations, some of them has a false-positive "conflict warning" due to multiplie sequential change i think.
Seems they need to be approved somehow or idk...

Also, can i apply it to previous inventree versions or how they are must be applied at all? 

PS "i have no doubts" about my english quality, but still have ability to translate some technical termins. My current staff needs them dramatically.

**Comment by SchrodingersGat** [comment]
@alxrMironov have you been translating over at [our Crowdin page](https://crowdin.com/project/inventree) as per [the documentation](https://inventree.org/contribute.html#translate)? Or have you been making the changes locally to your codebase.

I suspect the latter - the RU translation on Crowdin is sitting at ~ 30%:

<img width="687" alt="image" src="https://github.com/inventree/InvenTree/assets/10080325/e4c7f161-c93a-48dd-bb94-ad28a93e8282">

It is preferred to translate over at crowdin - you will need a free account. This will prevent conflicts too.

> Also, can i apply it to previous inventree versions or how they are must be applied at all?

The translations only keep track with the *latest* ("master") branch of InvenTree - it would be way too hard to track translations for multiple branches. So, any translations are available at the next release cycle.

**Comment by matmair** [comment]
@SchrodingersGat i am currently approving the things without ci warnings

**Comment by alxrMironov** [comment]
> have you been translating over at [our Crowdin page](https://crowdin.com/project/inventree)
Yes.
>  the RU translation on Crowdin is sitting at ~ 30%:
Yes, thats probably due im translate the app_en.arb only.

**Comment by SchrodingersGat** [comment]
Ah, ok, for the app, I see! :)

**Comment by alxrMironov** [comment]
> @SchrodingersGat i am currently approving the things without ci warnings

About the warning aroung "stock item", there is no unambiguous direct translation of this to RU. Before, "stock item" was translated differently in different cases (it still have near-same meaning, but differs in small cases, im not a linguist, cant say another), that way had a lack of consistency. You really cant teach people a terminology, what changes from page to page.

So i unite "складской товар", "товар на складе", "единица хранения" to "складская позиция" (the most direct and still meaning translation).
That cause the next warning
![image](https://github.com/inventree/InvenTree/assets/95591555/56cf937c-2184-4dc7-8734-e464b72e726d)

**Comment by alxrMironov** [comment]
> Ah, ok, for the app, I see! :)

Ahhh it is for an APP! Ok, there will be a long night for me...

**Comment by matmair** [comment]
@alxrMironov would you be up to take up provereading russian translation? You clearly know more of it than Oliver or I

**Comment by alxrMironov** [comment]
> @alxrMironov would you be up to take up provereading russian translation? You clearly know more of it than Oliver or I

Ok. Im try. Hope there is a way to rollback, if another russian users will not so happy for that changes.

**Comment by matmair** [comment]
There is - history is kept for all sugested translations and there is even a voting mechanism. But without anyone else stepping up for this language I think there will no conflict

**Comment by SchrodingersGat** [comment]
Closing this issue - has been resolved over on Crowdin
