### ISSUE TITLE
[FR] Show total quantity in BOM

### ISSUE THREAD

**Issue by MyRetroStore** [inventree/InvenTree#6386]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When viewing a BOM it would be handly if the total quantity of all components is displayed at the bottom. This is useful when manually adding in a BOM and you want to compare the number added to a know value. 

### Suggested solution

![image](https://github.com/inventree/InvenTree/assets/149300137/d56c1b99-d596-4a40-b9a6-50681ac9c9e4)

### Describe alternatives you've considered

None

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@MyRetroStore we used to have this feature - however it was very confusing if the parts in the BOM have different units.

i.e. `3m of wire` + `2mL of glue` + `3 connectors`

Happy to discuss ideas for how to implement this cleanly

**Comment by MyRetroStore** [comment]
I can see in that case it will be very confusing. What about a option to enable/disable the count?

**Comment by matmair** [comment]
I do not see how that option would resolve the problem with the different units.
