### ISSUE TITLE
[Roadmap] Improve Data Export Functionality

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6389]
The data export functionality (i.e. exporting datasets to a file such as `.csv` or `.xlsx`) is currently very inefficient, to the point where it causes session timeout when exporting more than a few hundred records.

#### django-import-export

We use [django-import-export](https://django-import-export.readthedocs.io/en/latest/) to export records - however this has not been optimized and makes a *LOT* of database hits. In particular, it does not do any of the clever query annotations which we have implemented for the API. So, we have the ability to extract lots of records *quickly* (via queryset annotation) but django-import-export does not make use of this.

We can refactor the export process to use our optimized API serializers, and use this data for file export.

This has the *huge* advantage that the exported file data would then exactly match the data exported via the API - currently there is a discrepancy between the two export formats

#### Background Worker

We can also potentially offload the export process to the background worker thread. This would allow for longer running processes that do not get prematurely killed by short connection timeouts from the frontend worker...

#### related issues

- https://github.com/inventree/InvenTree/issues/6376
- https://github.com/inventree/InvenTree/issues/2568
- https://github.com/inventree/InvenTree/issues/5571
- https://github.com/inventree/InvenTree/pull/5125

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/6389">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/6389/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/6389/pledge.svg">
</picture>
</a>

**Comment by matmair** [comment]
@SchrodingersGat is this in relation to https://github.com/inventree/InvenTree/pull/5125?

**Comment by SchrodingersGat** [comment]
@matmair yes, thanks, I have updated the related issues list now.
