### ISSUE TITLE
[PUI] SSO is not working in dev mode

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#6392]
One edge case where it can fail (minor, but took me a while to work out):

1. Run the `frontend-dev` server at `localhost:5173/platform`
2. Login via SSO from `localhost:5173`
3. The server after login redirects to `localhost:8000/platform` (not `localhost:5173/platform`)

This can cause some strange issues with the dev server. However if you start from `localhost:8000/platform` it works *ok*.

_Originally posted by @SchrodingersGat in https://github.com/inventree/InvenTree/issues/6333#issuecomment-1922767517_

**Comment by matmair** [comment]
To address this we will need to add config settings that amend both CORS and influence the callback logic.

@SchrodingersGat this only affects modern auth (SSO, magic link) login methods in debug. Should we document the behaviour or introduce mentioned changes?

**Comment by SchrodingersGat** [comment]
I think a warning (in the `devcontainer` docs) would be sufficient here. I am not super concerned about this.
