### ISSUE TITLE
Add Invoice

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#64]
Parts shipped out against invoice
Invoice against CustomerOrder

**Comment by miggland** [comment]
I've thought about this also - and come to the conclusion that the information is all there.

From the user side, there are loads of different reports which contain similar information:
- purchase order
- packing list
- proforma invoice
- order confirmation
- invoice
- checklists for warehouse
- ....

You could continue the list for sales/build orders. Would a way to go be to allow different types of user-defined reports for each type of order (or Model) - ie let the user choose to generate a packing list or invoice from a SO/PO/BO? This would save InvenTree having to include a specific option for each one..

The way I would go about it with the existing functions is to use the python API, and generate the reports in Latex (works great for the POs so far).

**Comment by matmair** [comment]
@miggland we have a report framework based on jinja / html - I would suggest using that.
https://inventree.readthedocs.io/en/latest/report/report/

**Comment by matmair** [comment]
It is more dev oriented right now ref: https://github.com/inventree/InvenTree/issues/2777

**Comment by SchrodingersGat** [comment]
An invoice report can be generated by the user if desired. Other than that, this is pushing too far into the financial / accounting space, out of scope.
