### ISSUE TITLE
Single-Line Installer Failure with Debian 11 --> Public Key is not Available

### ISSUE THREAD

**Issue by imager2019** [inventree/InvenTree#6416]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Attempting new installation using single-line installation on Debian 11. After starting install, receive notification of failure:
**The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B6D583CCBD33EEB8**

### Steps to Reproduce

Installed after setting root (su root)

### Expected behaviour

Expected install to complete

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

n/a

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
inventree@debian-inventree:~$ su root
Password: 
root@debian-inventree:/home/inventree# wget -qO install.sh https://get.inventree.org && bash install.sh
### Installer for InvenTree - source: inventree/stable
### Detected distribution: Debian GNU/Linux 11
### Installing required packages for download
### Getting and adding key
install.sh: line 123: curl: command not found
gpg: no valid OpenPGP data found.
### Adding package source
### Updating package lists
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease 
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Get:4 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 InRelease [1,857 B]
Err:4 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B6D583CCBD33EEB8
Reading package lists... Done
W: GPG error: https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B6D583CCBD33EEB8
E: The repository 'https://dl.packager.io/srv/deb/inventree/InvenTree/stable/debian 11 InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@debian-inventree:/home/inventree#
```

**Comment by Nudelsalad** [comment]
Hi @imager2019, is curl installed on your system? 
`install.sh: line 123: curl: command not found`

Script tries to curl the gpg key 
`curl -fsSL https://dl.packager.io/srv/$publisher/InvenTree/key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/pkgr-inventree.gpg > /dev/null`

Maybe add curl to the required packages installation in script @SchrodingersGat ?

**Comment by imager2019** [comment]
I noticed that as message as well. I have limited navigation and usage skills with Linux. In previous test installs that I performed, I did not need to do anything extra.

I found a note on adding in curl using the following commands
```
		sudo apt update && sudo apt upgrade	
		sudo apt install curl
```
That has allowed me to complete the install now, so I am good. 
Thanks...
