### ISSUE TITLE
Parts remain allocate to a completed sales order after a return order and back to stock.

### ISSUE THREAD

**Issue by Mimosa-oceanis** [inventree/InvenTree#6431]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi all, thanks for your amazing job, 
Here is the situation. 
I have some **serialized** parts which has been assigned to a sale order for a client. Sales is done and shipment completed. 
then the parts were returned to our facility so, after creating a return order, assigned to parts, complete the return order and assigned the parts back to stock.
Now I need to assign this part to a new sale order, but the part is currently locked as it is still assign to the first sale order. Even if it is now back to my stock.

### Steps to Reproduce

1. assigne a serialized part to a sale order
2. complete shipment and sail order
3. create a return order for this part
4. complete the return order and return the item back to stock
5. change the status of the part to "ok" as it is in "quarantine"
6. create a new sale order and try to allocate the part. 
7. check in stock and see that this specific part is still allocate to the first sale order created. 

### Expected behaviour

Once bake to stock, we should keep in the history this part was shipped and returned, but it should be available again to a new order. 

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.5
Django Version: 3.2.23
Commit Hash: 0804ecf
Commit Date: 2024-02-05

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-4.19.0-25-cloud-amd64-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Related issue: https://github.com/inventree/InvenTree/issues/4590

**Comment by Mimosa-oceanis** [comment]
I have another comment, but might need a new bug or feature request. 
For items not serialized it is not possible to assign them to a return order. It would be nice to be able to assign the same way we can do it in the sale order. Also when the client have more than one of the same item we cannot return to stock only part of them. Either all of them or none. Being able to use the return order to return a certain number of not serialized item would be a great plus. 

Thanks again for your great job.

**Comment by Mimosa-oceanis** [comment]
@SchrodingersGat It seems this is not a problem anymore. 
I had the issue with a previous version of inventree. I Updated to the last version and the issue was still here. But probably because I did the return order before the update. I had to do a new return order with the new version and everything seems ok. Sorry for that. You can probably close this issue.

**Comment by SchrodingersGat** [comment]
Thanks for reporting back @Mimosa-oceanis
