### ISSUE TITLE
URL https://get.inventree.org is down

### ISSUE THREAD

**Issue by saosangmo** [inventree/InvenTree#6433]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I get nothing when run `wget -qO install.sh https://get.inventree.org && bash install.sh`

### Steps to Reproduce

I also get blank page try to access this address with Chrome. 

### Relevant log output

```bash
nothing
```

**Comment by matmair** [comment]
@SchrodingersGat something in the DNS setup changed recently?

**Comment by matmair** [comment]
@saosangmo thank you for the report, we will look into it. For now, you can use `https://raw.githubusercontent.com/inventree/InvenTree/stable/contrib/install.sh` instead - get.inventree.org is just a redirect to that

**Comment by SchrodingersGat** [comment]
@saosangmo thanks for reporting - looking into it :)

**Comment by SchrodingersGat** [comment]
Back up now :)

**Comment by XanderLuciano** [comment]
FYI, I am getting an SSL error for the subdomain again.

**Comment by samumatic** [comment]
Yes for me too, maybe reopen it?

**Comment by matmair** [comment]
This issue was closed over a month ago, please open a new issue

**Comment by SchrodingersGat** [comment]
@XanderLuciano @saosangmo problem has been fixed, `get.inventree.org` is back up again
