### ISSUE TITLE
[FR] Sales Order Additional Status

### ISSUE THREAD

**Issue by altispeedkschmidt** [inventree/InvenTree#6434]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

The issue I am running into is that when using the sales order function in the program there is no status to differentiate between a "shipped" sales order and a "Complete" sales order. As it stands when you hit the "Ship Items" button in the program it dose not change the status to "Shipped" it keeps the status of  "In Progress" until after you have then hit "Complete Order" 

The workflow I am trying to accomplish is the following.

![image](https://github.com/inventree/InvenTree/assets/120754288/e9f45862-9673-446a-8533-3dd0e5590f59)

### Suggested solution

Add an additional status for "Completed" to the sales orders function in Inventree.

### Describe alternatives you've considered

Currently if I want to see if an order has been shipped but not marked as completed I have to open each individual sales order instead of at a glance being able to see the status of all orders at one glance from one page.

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/6434">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/6434/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/6434/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@altispeedkschmidt this makes sense, and would be a good addition. Should not be too difficult to implement.

Given our current development workload, would you be willing to implement this yourself, or provide a small amount of sponsorship to see it prioritized?

**Comment by tsimonq2** [comment]
I'll take this from the Altispeed side, feel free to assign the issue to me.

Thanks!

**Comment by altispeedkschmidt** [comment]
@SchrodingersGat I have spoken with @tsimonq2 one of our software developers at Altispeed Technologies and he has offered to take on this project and commit a pull request with the features described in this feature request.

**Comment by SchrodingersGat** [comment]
Awesome, looking forward to it :)
