### ISSUE TITLE
Transfering stock changes status

### ISSUE THREAD

**Issue by medo64** [inventree/InvenTree#6442]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

If I have damaged items in stock, using "Transfer stock" to move them to a new location changes their status to "OK"

### Steps to Reproduce

1. Start with part containing stock in "Damaged" status.
2. Use "Transfer stock" to move it to the new location.

### Expected behaviour

I would expect stock to stay in "damaged" status instead of reverting to "OK".

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.4
Django Version: 3.2.23
Commit Hash: 6a66be3
Commit Date: 2024-01-24

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.6.7-0-lts-x86_64-with
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@medo64 thanks for reporting this - I can confirm that this is indeed a bug!
