### ISSUE TITLE
User without superuser rights can remove installed items in trackable part, but cant install it.

### ISSUE THREAD

**Issue by alxrMironov** [inventree/InvenTree#6476]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

User without superuser rights can remove installed items in trackable part, but cant install it.

### Steps to Reproduce

A1. Create user witout superuser checkbox
A2. Try to install item in trackable part (you cant)
B1. Create user witout superuser checkbox
B2. Try to remove item in trackable part (you do)

### Expected behaviour

Staff must be able to do it, without superuser rights or even without stock add\remove rights (only change).

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.3
Django Version: 3.2.23
Commit Hash: e81349e7
Commit Date: None
Commit Branch: stable
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@alxrMironov I have not been able to reproduce this. Can you improve your example, perhaps use some parts / users from the demo server as an example?

**Comment by alxrMironov** [comment]
> @alxrMironov I have not been able to reproduce this. Can you improve your example, perhaps use some parts / users from the demo server as an example?

Can reproduce in demo. 
Login as engineer and able to remove installed items from serialized.
But cant install another one.
