### ISSUE TITLE
Documentation for develop a plugin 

### ISSUE THREAD

**Issue by progressify** [inventree/InvenTree#648]
Hi
If I want to develop a plugin, where i can find the docs and guidelines? 
Ty

**Comment by SchrodingersGat** [comment]
Hey @progressify can you provide some more details on what sort of plugin you are trying to make? There may be some documentation addressing this, otherwise I can try and assist (and potentially the documentation can be created as required...)

**Comment by progressify** [comment]
I want to develop a plugin for synchronizing the product of the inventory with eBay and Prestashop and I must extend some models for storing new information about the synchronization

**Comment by SchrodingersGat** [comment]
There are a few options here:

First, you could use an external script (see https://github.com/inventree/inventree-python for how to access InvenTree using Python)

The "Part" object already has a list of customizable key:value parameter pairs. You could for example make a new parameter called "ebay_status" or whatever..

![image](https://user-images.githubusercontent.com/10080325/74924981-8c264f00-5427-11ea-9cac-9f920bcf60cf.png)

There is no official "plugin" system at this stage - although in the future I do wish to address this, but it is not yet available or even planned.

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/pull/722

This PR is now starting the progress towards a proper Pythonic "plugin" interface

**Comment by SchrodingersGat** [comment]
There are now multiple methods you could try:

- Plugin system - https://inventree.github.io/docs/extend/plugins
- API - https://inventree.github.io/docs/extend/api
- Python - https://inventree.github.io/docs/extend/python

Please let me know if there is any further info you need to get started.
