### ISSUE TITLE
Auto-increment order references

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#65]
When creating a new purchase order, set the default value to the "next highest" order

(whatever that is?)

- Maybe have the ability to set a prefix for different types of orders
- PO
- CSO
- INVOICE

**Comment by a7hybnj2** [comment]
I don't know if this is relevant to this issue but... It would be nice when using the 'purchase order - order part' area that if there is only 1 open supplier PO that carries that part that it defaults to that value. Would make adding things to PO much faster.
