### ISSUE TITLE
mariadb 10.3 and django 2.2.9: make migrate issues

### ISSUE THREAD

**Issue by Chrescht** [inventree/InvenTree#650]
Dear all,

I am having trouble setting up mariadb 10.3 with inventree.
I created a database and user:
```
CREATE DATABASE inventree;
CREATE USER 'ivt'@'localhost' IDENTIFIED BY 'mypassword'; 
GRANT ALL PRIVILEGES ON inventree.* TO 'ivt'@'localhost';
FLUSH PRIVILEGES;
```
And modified `config.yaml` accordingly.
But `make migrate` is giving me:
jango.db.utils.ProgrammingError: (1146, "Table 'inventree.common_inventreesetting' doesn't exist")

What am I missing?

**Comment by Zeigren** [comment]
See #647

**Comment by Chrescht** [comment]
I confirm the make migrate runs fine now in 10.3.22-MariaDB and django 2.2.9.
