### ISSUE TITLE
Add "ON HOLD" status to orders

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6504]
A new "status" flag for orders (build, sales, purchase, return) which allows them to be marked as "on hold".

Not closed out, but designated as not currently active (perhaps waiting for input)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/6504">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/6504/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/6504/pledge.svg">
</picture>
</a>

**Comment by matmair** [comment]
@SchrodingersGat would this flag stop changes from occuring?

**Comment by SchrodingersGat** [comment]
We would have to consider the allowed state transitions here. Have not yet fully thought it through

**Comment by mabroens** [comment]
Hi,

would it also be possible to add In Test and Internal to the status for parts?
I currently use Quarentine to identify if a parts is in test. so in my case Boards come in, then they are added to the stock but. they can only be sold once availeble. and prior to getting this order i run an intake test for each board. hence this status would be nice.

**Comment by SchrodingersGat** [comment]
I would like to implement this soon, as I have a need for it. There are two potential ways to implement this, and I'd like some feedback on how we would like to see it done.

### Option A: New Status Code

Add a new "ON_HOLD" status code to each type of order. This means that the order must transition to a new "ON_HOLD" state, which is very visible and the order cannot be "in progress" and "on hold" at the same time.

This would require careful consideration of state transitions for each order, but is probably (IMO) the more robust approach

### Option B: Separate Field

Add a separate "ON HOLD" boolean field to the Order model, which is a simpler approach. However this is potentially confusing if the "on hold" flag is set for an order which is "complete" or "cancelled" etc.

---------------------------------

Thoughts?

**Comment by mabroens** [comment]
I would prefer option A as its more clear in its state. But in the end the importance for me is that we can simply filter them out in the overview


Met vriendelijke groet/ With kind regards,
Martijn Broens

**Comment by matmair** [comment]
Without a full definition of the transitions and business logic behind them it is hard to tell which would be suited better but probably option A
