### ISSUE TITLE
Status Text on Custom Label

### ISSUE THREAD

**Issue by horbix28** [inventree/InvenTree#6506]
Hello together,
I got the following variable in my custom label: `item.status`.
But i only get numerica value, e.x: `10`

How do i display `OK`, `Attention needed`, `Damaged`?

Thx a lot :D

**Comment by SergeoLacruz** [comment]
Hi,
I do not think this is a bug. Status codes are numeric values. All codes a are defined here:
InvenTree/InvenTree/status_codes.py

**Comment by wolflu05** [comment]
Can you try `item.status.name` or maybe casting it to a string?

**Comment by horbix28** [comment]
@wolflu05 unfortunately `.name` does not work.
@SergeoLacruz I didn't submitted this as bug, so I thought it should be okay.
I already saw it defined there, however, I don't get how to access this status name.

**Comment by SergeoLacruz** [comment]
I found it. It is `item.status_label`

**Comment by horbix28** [comment]
Thank you @SergeoLacruz. Now it works like it should.
Should be added here https://docs.inventree.org/en/latest/report/context_variables/#stockitem
