### ISSUE TITLE
Allocate stock items to build orders that do not work with decimals

### ISSUE THREAD

**Issue by nikolai2111** [inventree/InvenTree#6508]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Ich kann die Spule nicht zuordnen, wenn sie nur ein Teil einer ganzen Spule ist. Das Filament wird in kg erfasst und 0,3149 bedeutet, dass noch 314,9 g auf der Spule sind.

Wie Sie auf dem Bild sehen können, erscheint die Meldung "Form error exist", wenn ich Nr. 2 auswähle, und wenn ich Nr. 1 auswähle, funktioniert es und das Garn wird zugewiesen.

-----------------

I can't assign the coil if it's just a part of a whole coil. The filament is recorded in kg and 0.3149 means that there are 314.9 g left on the spool.

As you can see in the picture, when I select 2, the message "Form error exists" appears, and when I select 1, it works and the yarn is assigned.

-----------------
![grafik](https://github.com/inventree/InvenTree/assets/10119322/19d4b049-c2e7-48fc-bdc4-5e047d067947)

The bug is reproduced below on the demo page:
![grafik](https://github.com/inventree/InvenTree/assets/10119322/2fe5bdad-f7f6-4f43-9dff-99f0057485c4)

### Steps to Reproduce

I don't know if this is a specific bug. I had the problem when I did the following:

1. Create a stock of a part where x is 1 > x > 0.
2. Try to allocate it in a build order

### Expected behaviour

I assume that if it works, the fracture will be allocated and then used.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

![grafik](https://github.com/inventree/InvenTree/assets/10119322/4430a46b-3bb5-4198-8e5d-9052d7af4fb2)

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

### Relevant log output

```shell
I don't know how to produce the log output.
```

**Comment by SchrodingersGat** [comment]
The "form error" is not being displayed here. Can you open up the developer tab in your browser and see what error message is returned when you hit "Submit" button?

**Comment by nikolai2111** [comment]
Do you mean the console output when you press F12 in Firefox?

![grafik](https://github.com/inventree/InvenTree/assets/10119322/edda50d6-1f38-4b7f-b2ae-e8281c6bf959)

**Comment by SchrodingersGat** [comment]
@nikolai2111 if you change to the "network" tab, you should be able to see the response from the server, with the actual error message.

**Comment by nikolai2111** [comment]
Like this one?
![grafik](https://github.com/inventree/InvenTree/assets/10119322/3306ec11-2b4c-43e7-a46e-d8a2acffae04)

**Comment by SchrodingersGat** [comment]
@nikolai2111 ok, that's a good start - can you also show the `POST` data in that request, to check what data is being *sent* to the server?

**Comment by nikolai2111** [comment]
Do you mean this?
![grafik](https://github.com/inventree/InvenTree/assets/10119322/022dc727-166b-45e5-90e9-56142466f70a)

**Comment by SchrodingersGat** [comment]
@nikolai2111 thanks :)

**Comment by SchrodingersGat** [comment]
@nikolai2111 ok fix incoming in https://github.com/inventree/InvenTree/pull/6532 - this was a pretty subtle bug!

**Comment by nikolai2111** [comment]
Thanks!

Is there any indication of when the release will be published?

**Comment by wolflu05** [comment]
0.13.6 was just released, that should contain the backpot with that fix.

**Comment by nikolai2111** [comment]
You guys are awesome fast!
