### ISSUE TITLE
xlsx Part Image Import

### ISSUE THREAD

**Issue by mitchellmoss** [inventree/InvenTree#6511]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi, when I bulk import via xlsx the 'part image' is being ignored and imports as blank. The export is pulling thumbnail images locations, but only those set via webUI. Existing part image is imported, but new 'Part Image' locations do not import and show as blank in import comformation. 

here is my Part Image file location format: 

part_images/RP1925609_0823_TRILITE_30lb_GREY_1.png

### Steps to Reproduce

1. under Part / Parts / export as xlsx via Admin Interface
2. Importing Part / Parts / import as xlsx

### Expected behaviour

Part Image files location should be imported 

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.5
Django Version: 3.2.23
Commit Hash: 0804ecf
Commit Date: 2024-02-05
Commit Branch: stable
Database: postgresql
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-5.15.0-94-generic-x86_64-with-glibc2.35
Installer: GIT

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@mitchellmoss this is likely due to the `readonly=True` attribute set here:

https://github.com/inventree/InvenTree/blob/0f51127adfd97c842b2b9e39edb887d2b9d74710/InvenTree/part/admin.py#L60

Can you locally test what happens if you remove this `readonly=True`?

**Comment by mitchellmoss** [comment]
@SchrodingersGat  thank you. Yes I will give it a try.

**Comment by mitchellmoss** [comment]
@SchrodingersGat that worked. Thanks for the help.

**Comment by SchrodingersGat** [comment]
Thanks for confirming. Incoming fix here - https://github.com/inventree/InvenTree/pull/6513
