### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#652]
I have been adding parts to InvenTree.  I use Molex connectors often and I think it would be nice to be able to link two or more parts together.  Like for example the Molex connector with the crimp pin.

**Comment by a7hybnj2** [comment]
Yea, a “related part”, “associated part” would be nice. I think you could do this in the short term by putting it in the notes or if you wanted to mess with it you could have a “crimped molex” part that is a build of the conn + pins parts

**Comment by eeintech** [comment]
@lookme2 @a7hybnj2 In pursuit of this feature, I've created #1048 

Please take a look and let me know if that looks like what you expected.

**Comment by lookme2** [comment]
@eeintech this looks great.  I'll try to pull that down and give it a try sometime this week.

**Comment by sintech** [comment]
Static linking is good, but what about dynamic(automatic) linking?

For example 74-series ICs of different types have the same logic inside: 7400, 73LS00, 74ALS00, 74HC00. It would be nice if all variants of 74*00 were displayed as variant of each other.
Another example: in Russia we have variants of 74-series under different name 7400=К155ЛА3, 74LS00=К555ЛА3, etc.

I'm thinking about dynamic links based on regexp or match table.
Does that make sense?

**Comment by eeintech** [comment]
@sintech For your example I suggest you use Part "Variants", [see documentation](https://inventree.readthedocs.io/en/latest/part/template/).

If you want to automate variant creation, I suggest you take a look into the [API](https://inventree.readthedocs.io/en/latest/extend/api/) and/or the [Python Interface](https://inventree.readthedocs.io/en/latest/extend/python/).
I do believe the logic driving "links" between parts should reside outside of InvenTree.

**Comment by eeintech** [comment]
@lookme2 Were you able to try it? Any feedback?

**Comment by lookme2** [comment]
@eeintech sorry I have not.  I've been very busy the last couple of weeks.  I'll try to take a look by the end of the week.

**Comment by lookme2** [comment]
@eeintech I did a git pull this morning and I don't see the related parts tab.  Is there something I need to setup for that?

**Comment by eeintech** [comment]
@lookme2 Which branch did you pull?

**Comment by lookme2** [comment]
The Master branch

**Comment by eeintech** [comment]
@lookme2 Ha it's not in master yet.

Try this:
```
$ git remote add eeintech https://github.com/eeintech/InvenTree.git
$ git fetch eeintech
$ git checkout -b related_parts
$ git pull eeintech related_parts
```

**Comment by lookme2** [comment]
@eeintech I had a chance to look at this over the weekend.  Very nice.  Thanks!!!

**Comment by eeintech** [comment]
@lookme2 Glad to hear! I'll ask @SchrodingersGat to review and merge :+1:
