### ISSUE TITLE
[FR] Ki365 Support

### ISSUE THREAD

**Issue by OfficialKris** [inventree/InvenTree#6520]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

From my limited research into the topic, there seems to be no cohesive, well-supported way to integrate with KiCad. This includes syncing library, part data, and BOM/assembly data. Topic #4133 shows the support for this feature.

### Suggested solution

Ki365 is a new project which has the potential to integrate functionality InvenTree has previously been reluctant to support. I suggest the development of either a plug-in or middle layer which sits between InvenTree’s internal database and external applications to sync data between programs. This would allow Inventree to remain program agnostic while keeping OSS programs synced with the data they need.

### Describe alternatives you've considered

None

### Examples of other systems

Professional solutions have all these programs under one name and use proprietary implementations of APIs.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
We have full support for KiCad integration - see https://inventree.org/blog/2023/09/26/kicad
I am currently looking into integration with Ki365 but see some architectural challenges that I want to solve on the InvenTree side - see https://gitlab.com/ki365/ki-365/-/issues/16#note_1720323476

**Comment by OfficialKris** [comment]
Shoot, I can’t believe I missed that. Thank you for pointing that out. It seems that inventree_kicad only has support for read only part metadata. Is there a solution for BOM/assembly data? I wish I had more experience with InvenTree and KiCad but have been using other softwares.

The KiCad CLI is receiving improvements across the board which would make using Actions running KiCad commands to Ki365 then to InvenTree seem like a very robust solution. Of course Ki365 would need to be developed to make use of that pipeline.

**Comment by matmair** [comment]
I would rather not rely on a pretty new platform to develop this important functionality but have this handled in our ecosystem.

**Comment by SchrodingersGat** [comment]
@afkiwers is the developer behind the inventree-kicad-plugin - which is receiving a *lot* of support and interest from the community.

**Comment by afkiwers** [comment]
@OfficialKris my plugin can easily support both; the KiCad core team didn't like that though. Hence not yet implemented.

Check out https://dev-docs.kicad.org/en/apis-and-binding/http-libraries/ to see how to query my api endpoints. 

I'd be happy to implement any upstream features using those existing endpoints.

**Comment by matmair** [comment]
Still important
