### ISSUE TITLE
[PUI] Part Category Tree leaf nodes display as branch nodes

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#6525]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

"Pin headers" doesn't have any children, but still render the folder arrow
![image](https://github.com/inventree/InvenTree/assets/7506688/58909b34-6703-4af5-98a5-f0683fdac8f0)

### Steps to Reproduce

1. Open the category tree and look at the structure as above

### Expected behaviour

Categories without children should have an object structure such that they're defined as leavfs by `react-tree`

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

Master as of 20.02.24

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
It also seems like open parent leaves are not marked

**Comment by SchrodingersGat** [comment]
@LavissaWoW fixed in https://github.com/inventree/InvenTree/pull/6581. Also addresses the "open nodes" icon issues
