### ISSUE TITLE
Add links to the new ui in the old ui like `try this out in the new ui` @wolflu05

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#6554]

**Comment by SchrodingersGat** [comment]
Placing an element at least on the login screen would be a good idea!

And perhaps in the home screen / dashboard?

**Comment by matmair** [comment]
Should I add a setting to control this "promotion" of the new interface?

**Comment by SchrodingersGat** [comment]
Yeah, likely some users would want to disable it. But, it would pay us to increase visibility of the new UI
