### ISSUE TITLE
Media file serving suddenly stopped working

### ISSUE THREAD

**Issue by 30350n** [inventree/InvenTree#6555]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [X] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hey! I've been trying to test a fix, so I updated my production server to master yesterday (I know, I know, I shouldn't do that 😅 ).

Anyways, it's sitting at [`6e713b1`](https://github.com/InvenTree/InvenTree/tree/6e713b15ae532bf475d75bdb9c603c0bdc34a705) now and everything seems to be working, except for my media file serving which certainly stopped working.

The issue seems to stem from the `/auth` endpoint.

From the nginx error log:

`2024/02/22 15:41:30 [error] 18703#0: *222 auth request unexpected status: 302 while sending to client, client: <IP>, server: <HOST_URL>, request: "GET /media/company_images/company_113_img.thumbnail.png HTTP/1.1", host: "<HOST_URL>", referrer: "https://<HOST_URL>/index/"`

From the InvenTree log:

`[pid: 7443|app: 0|req: 127/1276] <IP> () {60 vars in 1080 bytes} [Thu Feb 22 15:41:30 2024] GET /media/company_images/company_113_img.thumbnail.png => generated 0 bytes in 47 msecs (HTTP/1.1 302) 10 headers in 349 bytes (1 switches on core 0)`

If I remove the `auth_request /auth;` part from the `/media` location in my nginx config, it's working again.

### Steps to Reproduce

-

**Comment by matmair** [comment]
Can not immediately reproduce this on master; Can you try to log out, remove the cookies and check if the behaviour still occurs?

**Comment by 30350n** [comment]
Yep, tried it in a private window, same thing.

**Comment by 30350n** [comment]
My nginx config is more or less the same as the docker one provided here btw, only real difference is that I'm using uwsgi instead of gunicorn. It was working before though and I didn't touch it for ages.

**Comment by SchrodingersGat** [comment]
> If I remove the auth_request /auth; part from the /media location in my nginx config, it's working again.

This change is essentially removing any authentication checks from media file access.

For some reason the `/auth` endpoint is returning 302.

What response do you get from the server if you navigate your browser to `<server>/auth/`?

**Comment by 30350n** [comment]
Well if I remove the `internal;` part so I can actually reach it I get the `302`, which looking into it seems to be the core of the problem. According to the [nginx `auth_request` code breakdown](https://www.nginx.com/resources/wiki/extending/examples/auth_request/):

> If the response code is between 200 and 300 then the auth is approved.

**Comment by SchrodingersGat** [comment]
> Well if I remove the internal; part so I can actually reach it I get the 302

Ok, so why is the endpoint returning `302`? Can you look at the headers being sent by your browser, and the response being returned? The `/auth` endpoint should just return an empty `200` response to indicate that you are an authenticated user

**Comment by 30350n** [comment]
![image](https://github.com/inventree/InvenTree/assets/34186858/97ad39a2-f338-4740-a6e3-8bc4cb0fb144)

Ah I thought the 302 might be intended somehow, the auth system did get touched recently didn't it?

**Comment by 30350n** [comment]
Request Cookie is: `csrftoken=<TOKEN>; sessionid=<SESSION_ID>` (might have redacted too much here).

**Comment by 30350n** [comment]
Not sure, but I think I don't actually see the `/auth` requests in the inventree log. That's not good, right?

**Comment by 30350n** [comment]
Hmmm I'm also getting a 302 if I'm not logged in. Could be an nginx thing I guess 😕

**Comment by SchrodingersGat** [comment]
@30350n the demo server (which runs on the "standard" nginx config file) is hosting media files correctly. Are you certain you have not changed something else?

**Comment by 30350n** [comment]
Relatively, yeah. (Currently in the process of installing caddy, let's see how that works out ^^)

**Comment by 30350n** [comment]
The [`caddy-snake` project](https://github.com/mliezun/caddy-snake) might be interesting in regard to further simplifying the server setup (#6551). Though I'm currently running into [another issue](https://github.com/mliezun/caddy-snake/issues/4) setting it up.

**Comment by matmair** [comment]
Not to shade that project but this seems to be very new (16 Feb 2024); not sure we should replace gunicorn with such an unknown player for the default production.

**Comment by 30350n** [comment]
Probably not, but it's still interesting. + This is really not a lot of code and really only providing the WSGI interface for caddy to work with.

**Comment by 30350n** [comment]
Okay so the issue seems to have been related to `uwsgi` after all. The problem was that I was passing using `uwsgi pass` and communicating via a unix socket with it. So any requests to `/auth` were passed to `/auth` as is instead of **`/auth/`** with your `reverse_proxy` setup: https://github.com/inventree/InvenTree/blob/2df0fd8a673cd9980c2b305dd6d5a74a8da77b34/docker/nginx.dev.conf#L59

Thus because of the `APPEND_SLASH` setting, Django returns a 301.

**Comment by 30350n** [comment]
Okay I did the reasonable switch to gunicorn now and am using it together with caddy as a reverse proxy. Seems to be working fine for now!
