### ISSUE TITLE
[FR] make temp number untill issued

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#6557]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Assume you need to create a quote for something. You make an SO and the system will assign a number to it. SOxxx and the next order SO is incremented. Now assume you have 4 SO's and the 3rd is being confirmed, meaning the customer agrees to continue. In my case only then I press `Issue Order`. now the problem is that for example SO3 is now in process and SO1 is also approved. This means SO 2 is missing in line. Now I know the tool is not an accounting tool but since the numbers do not lineup anymore (1 and 3 ok, 2 cancelled and 4 still pending) my accountant is not happy with this and unfortunately neither is the government. 
Would it be possible to make the numbers more flexible as in generating a number depending on the status (like pending/in progress/shipped). Once not Pending the SO number is assigned and fixed.

### Suggested solution

add a dependency on status=not pending. or perhaps ad a next step Invoicing to the flow.

### Describe alternatives you've considered

type the whole template over in word or excell and invoice fro there which is what i do now but Inventree is so much nicer :-)

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
InvenTree is not a accounting tool and it is not striving to be.
You should not issue invoices from it, that will create problems downline (accountants, audits, bookkeeping). If I were you I would connect it to my invoicing/payment solutions via a plugin and append the sales orders as an attachment with  „internal order“ written on there somewhere.

Reference number are one of the minor problems you will encounter if you try to use InvenTree for accounting. Our whole money conversion system is real-time course based. This will fail you in every reasonable audit.

**Comment by SchrodingersGat** [comment]
The "next available reference" is just a suggestion - there is no requirement to *use* that. You could even have a custom plugin which auto-fills this with something like "SO-xxxx-pending" and then can be edited later?

**Comment by mabroens** [comment]
Hi Guys,
fair points and understood.  i'll see if i can export the content of the SO somehow to my invoicing tool.

again thxs for thinking with me.
Br Martijn
