### ISSUE TITLE
part ownership and lending

### ISSUE THREAD

**Issue by Chrescht** [inventree/InvenTree#656]
One way to use InvenTree is to share parts among a group of people (friends, ..).
This means a part 
- has to have ownership,
- can be lent to a user, with a start and end date

Is somebody else interested in this?

**Comment by a7hybnj2** [comment]
I don’t currently need this but could foresee it being useful in the future.

Would the “lent to a user” need an inventree account or would they just be added as a “client/supplier/contact”?

**Comment by Chrescht** [comment]
> 
> 
> I don’t currently need this but could foresee it being useful in the future.
> 
> Would the “lent to a user” need an inventree account or would they just be added as a “client/supplier/contact”?

They need an InvenTree account since they can also add they own stuff, be parts owner, and lend parts.

**Comment by chschlue** [comment]
I don't really get the "lend" part.
Isn't lending parts akin to lending firewood?

**Comment by a7hybnj2** [comment]
@chschlue I think its more for if you track things like your multimeters and dso and whatnots. As an asset management system.

**Comment by SchrodingersGat** [comment]
You could pretty easily hack this in by creating a StockLocation tree like:

``Stock/Friends/Bob`` which then contains all the things that Bob has selfishly never returned to you. This also allows automated history tracking of when something was transferred to Bob. The ``Stock/Friends`` location would then show all the items you have lent out.

**Comment by Chrescht** [comment]
> You could pretty easily hack this in by creating a StockLocation tree like:
> 
> `Stock/Friends/Bob` which then contains all the things that Bob has selfishly never returned to you. This also allows automated history tracking of when something was transferred to Bob. The `Stock/Friends` location would then show all the items you have lent out.
> 
> i.e. if you instead encode a "who" as a "where" you should get all the features you are looking for, without scope-creeping the software :)

This is one way it could work, but I was more thinking about a shared stock management, where some stuff is owned by me, some by my friend Bob. So Stock/Friends/Bob doesn't really work unless we have the parts tagged with an owner.

Then there are _parts_ like firewood as @chschlue pointed out, these are _commonly owned_ or have _no owner_, just a location, an can be consumed. Nails, screws, and paint are more examples.

**Comment by SchrodingersGat** [comment]
Ok, what if in addition to having a "virtual" location like "lent to friends", each Part can have an (optional) "owner" field. In a factory or business context this would be the person responsible for that part, for example.

I am very keen to *not* add single-use features which address a very slim problem but otherwise just add complexity. Maybe an "owner" field is simple (and useful) enough to be worthwhile...

@Chrescht  what do you think about that

**Comment by Chrescht** [comment]
> Ok, what if in addition to having a "virtual" location like "lent to friends", each Part can have an (optional) "owner" field. In a factory or business context this would be the person responsible for that part, for example.
> 
> I am very keen to _not_ add single-use features which address a very slim problem but otherwise just add complexity. Maybe an "owner" field is simple (and useful) enough to be worthwhile...
> 
> @Chrescht what do you think about that

Sounds great, I agree to keep it simple.

**Comment by eeintech** [comment]
@SchrodingersGat I think ownership of parts, stock, build, purchase and sales order could be a nice addition to InvenTree, it may well be combined with the new permission-based system where specific objects assigned to users gives them more permissions than others. I'm thinking of a simple case scenario like: "John" created this sales order therefore "John" gets permission to update it, "Tim" won't have the option to update it until "John" passes ownership to him or "Tim" is added to list of owners.

Have you already thought into the actual implementation or want me to check our options based on your comments above?

**Comment by SchrodingersGat** [comment]
@eeintech I can see that "ownership" as you suggest here could be useful, but I have not given it much thought in particular.

One related suggestion I have received is the ability to "loan" or "rent" stock items out. This was in particular for an A/V company which has a lot of equipment that is sent out to different music festivals. This feature request included such things as a booking calendar, etc.

I can see this being a great set of features to add - but have not yet made any effort to investigate how it would actually be implemented.

**Comment by eeintech** [comment]
@SchrodingersGat Sounds good, I also only gave 5-10 minutes of reflexion myself but found the idea compelling, if well implemented. I do not have this on my "absolutely" needed list though 😄 

Just a thought but what about having a simple "idea box" or "future features list" with requests needing more than just a couple hours of reflexion/work and use-case attached (like the one you mentioned). This could be stored in the docs like [the build future features](https://inventree.readthedocs.io/en/latest/build/build/#future-features) but on its own page. 
With more and more requests coming in, we may have a better view of what InvenTree most demanded features are and manage priorities accordingly.

**Comment by SchrodingersGat** [comment]
A "future features" list sounds like a great addition to the documentation! Under the "extend" directory would probably be a good place for it.

**Comment by eeintech** [comment]
Great, I'll keep track of all those "extensive" feature requests there.

**Comment by eeintech** [comment]
I started a list a while ago: https://github.com/inventree/inventree-docs/pull/26/files#diff-f005532afd58081f31152965122861a522abc1aff04ab65f76bb457ef325bd85

But it was tough to keep up with the rapid progress... so I think @SchrodingersGat decided it wasn't worth keeping at the moment.
I would be keen to see some kind of plan for the future release but I guess at this early stage, it is difficult to convey the "biggest" gaps and features other than listening to proposals made into issues here.

**Comment by matmair** [comment]
@eeintech some kind of indication what should be prioritised by people how want to help would be nice - there is the "help wanted" tag but those are 4 issues right now and I do not want to take away all of those in case somebody wants to help.

**Comment by SchrodingersGat** [comment]
I've re-added the "upcoming features" page, I was thinking about doing that anyway :) we'll just have to ensure we keep it updated.

As for tags, I think the "help wanted" tag is appropriate to use in these cases

**Comment by eeintech** [comment]
@SchrodingersGat In case you need help for triage and labelling, I'm sure @matmair and I could give you a hand.
Given InvenTree repo is under the InvenTree organization, seems like GH provides a different levels of permission:
https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level

The "Triage" one would let us add labels. Also we can officially ask you to review our PRs 😃

**Comment by eeintech** [comment]
Focusing back on the OP, as InvenTree does not aim to become an assets management platform, the scope of the "lending" option should only apply to external interactions (eg. customers) as proposed in #1946 

The ownership idea has already been implemented in #1155 and further improvements/fixes.
