### ISSUE TITLE
No SSO providers have been configured

### ISSUE THREAD

**Issue by jefffhaynes** [inventree/InvenTree#6560]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Despite configuring microsoft SSO, login shows no SSO providers have been configured.

### Steps to Reproduce

Here is the relevant config section:

```
authentication_backends:
  - 'django.contrib.auth.backends.ModelBackend'
  - 'allauth.account.auth_backends.AuthenticationBackend'

#  Custom middleware, sometimes needed alongside an authentication backend change.
middleware:
  - 'django.middleware.security.SecurityMiddleware'
  - 'x_forwarded_for.middleware.XForwardedForMiddleware'
  - 'django.contrib.sessions.middleware.SessionMiddleware'
  - 'django.middleware.locale.LocaleMiddleware'
  - 'django.middleware.common.CommonMiddleware'
  - 'django.middleware.csrf.CsrfViewMiddleware'
  - 'allauth.account.middleware.AccountMiddleware'
  - 'corsheaders.middleware.CorsMiddleware'
  - 'django.contrib.auth.middleware.AuthenticationMiddleware'
  - 'InvenTree.middleware.InvenTreeRemoteUserMiddleware'
  - 'django_otp.middleware.OTPMiddleware'
  - 'django.contrib.messages.middleware.MessageMiddleware'
  - 'django.middleware.clickjacking.XFrameOptionsMiddleware'
  - 'InvenTree.middleware.AuthRequiredMiddleware'
 ```

Here is the SSO app config:

![image](https://github.com/inventree/InvenTree/assets/9734727/4a2622ed-b4e2-495d-aaa0-334f11aeebf4)

SSO is also enabled in settings.

### Expected behaviour

Microsoft SSO available at login.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.13.5

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Nothing weird in the logs from what I can see.
```

**Comment by SchrodingersGat** [comment]
Was there a reason for enabling custom middleware? This is usually only a *very advanced* option.. And should not be done for standard SSO.

**Comment by jefffhaynes** [comment]
I saw others doing similar things but I have removed that now with the same result.

**Comment by jefffhaynes** [comment]
Sorry, I omitted the SSO config from my original.  Now I just have this:

```
# Add SSO login-backends (see examples below)
social_backends:
   - 'allauth.socialaccount.providers.microsoft'

# Add specific settings for social account providers (if required)
social_providers:
  microsoft:
    TENANT: '<tenant id>'
```

I removed the authentication backends but same result.  I believe this is what I started with and started adding the backend/middleware config based on other examples I was able to find.

**Comment by jefffhaynes** [comment]
Not clear if TENANT is supposed to be tenant id or literally 'organizations' but I get the same result in either case.

**Comment by SchrodingersGat** [comment]
Can you try changing the name of the provider configuration from "inventree" to "microsoft"?

**Comment by jefffhaynes** [comment]
Sorry, same result.  I should say that it is possible that I've somehow configured the microsoft tenant wrong although I'm not seeing any errors in the log that suggest that.

**Comment by jefffhaynes** [comment]
I'm starting to wonder if it's related to the site url.  I tried playing around with it and now I'm getting this error in the logs:

```
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist
```

**Comment by jefffhaynes** [comment]
Unfortunately now I can't get back in to fix it...

**Comment by jefffhaynes** [comment]
Alright, after an hour of trying to get back into the site I think I'm calling it for now.

**Comment by jefffhaynes** [comment]
This did end up being an issue with the django sites.  There appears to be some bug related to management of the site list (e.g. I think it is possible to break db constraints by editing the list).  I had to edit the db to get everything back to normal but then the site correctly resolved and the SSO became available.

**Comment by SchrodingersGat** [comment]
@jefffhaynes I'm interested to know what the sites issue is - can you provide some more information here? Did you have multiple sites setup, or just a single site?
