### ISSUE TITLE
Updating from 0.12.3 to latest version

### ISSUE THREAD

**Issue by kimizumi1** [inventree/InvenTree#6563]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I have Inventree installed via installer.
I've tried to update Inventree by stopping Inventree (systemctl stop inventree) and then running:
`apt install --only-upgrade inventree`

but that leads to:
`The following packages have unmet dependencies:
 inventree : Depends: python3.9 but it is not installable
             Depends: python3.9-venv but it is not installable
             Depends: python3.9-dev but it is not installable
E: Unable to correct problems, you have held broken packages.`

I tried to install python3.9 but Inventree doesn't start after that.

Then I tried also running:
`inventree run invoke update`
but :
`sh: 1: exec: invoke: not found`

Nothing seems to work for updating the version

### Steps to Reproduce

1. re-running the commands won't work

### Expected behaviour

Can't update to latest version due to commands failing

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

InvenTree Version	0.12.3
API Version		127
Python Version		3.10.12
Django Version		3.2.19

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
if you modify your system's python install you will have to re-setup InvenTree as the virtual environment that InvenTree depends upon will be damaged.

**Comment by eeintech** [comment]
@matmair When do you think the Ubuntu package can be fixed and not require `python3.9` to be installed?

**Comment by matmair** [comment]
No idea. I do not consider this a bug and I am not working on it

**Comment by eeintech** [comment]
Ok, too bad I won't be able to checkout 0.13.x anytime soon 😢

**Comment by LavissaWoW** [comment]
Just tossing this out:
Could a workaround be to do a `sudo apt-mark hold package-name` for each of the relevant deps?
The backside here ofc being that I don't know if you can downgrade.

**Comment by eeintech** [comment]
> Just tossing this out: Could a workaround be to do a `sudo apt-mark hold package-name` for each of the relevant deps? The backside here ofc being that I don't know if you can downgrade if you already went past what InvenTree needs

I'm not sure what would that achieve? It will still need the dependencies to be installed (eg. Python 3.9)

**Comment by LavissaWoW** [comment]
> I'm not sure what would that achieve? It will still need the dependencies to be installed (eg. Python 3.9)

Well, as I said. I don't know if you can downgrade if already upgraded.
I just remember doing this exact thing for an old Ruby on Rails project I'm hosting at work. Ruby versions a few years back was an "it's complicated" issue. I froze the Ruby version, and the project still runs on Ruby 2.5.3 today, even with the IT department regularly updating the server.

**Comment by cnschu** [comment]
sorry if i missed it, what is the solution or workaround for this bug?

**Comment by eeintech** [comment]
@cnschu No workaround as of now, but there was a fix to the packager proposed in #6154 like you pointed out, let's hope for the best!

**Comment by matmair** [comment]
The linked packaging job (in the PR) is installable

**Comment by eeintech** [comment]
Following the instructions here work for me: https://packager.io/gh/inventree/InvenTree/builds/1509/install/ubuntu-20.04
However it installs `master` (eg. `0.14.dev`) and not the latest stable release, FYI.

**Comment by matmair** [comment]
@eeintech the build was of master; it should now install stable normally when using the stable path
