### ISSUE TITLE
Docker compose complete behind nginx reverse proxy SSL

### ISSUE THREAD

**Issue by MrShippeR** [inventree/InvenTree#6565]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hello devs,
first it's not issue, it's question about deploymend because I didn't find source in whole documentation even github issues.

Please could you give me template file which should I insert into /etc/nginx/sites-available/something.example.com ?

I would like to deploy applications as is from docker-compose for production. Before all this to have other Nginx proxy, which obtain Let's encrypt certificate. There will be 2 nginx because of top level nginx deciding of domain name for app and  deploying SSL certificate for webpage.

### Steps to Reproduce

When I use my proxy-default.conf which I am using normally for other docker containers to obtain Let's encrypt certificate, it doesn't work property. Works good when page is viewed on http port 80, but when i use command `certbot --nginx` and receive certificate, then use choice redirect all trafic to https, result showing without CSS, JS and images.

Content of my /etc/nginx/sites-available/inventree.example.com before certbox --nginx:

```
server {
    listen 80;
    server_name inventree.example.com;

    location / {
        proxy_pass         http://0.0.0.0:1337;
        proxy_redirect     off;
        proxy_read_timeout 300s;
        client_max_body_size 0;
        proxy_buffering off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by SchrodingersGat** [comment]
@MrShippeR I would suggest that you look at this PR - https://github.com/inventree/InvenTree/pull/6551 - we are looking to move our recommended docker setup to use the [Caddy](https://caddyserver.com/) reverse proxy. 

This will provide a much simpler setup, as well as ssl "out of the box"

**Comment by MrShippeR** [comment]
Thank you, I will try Caddy server. 
My config with Nginx get worked when i obtained cert for domain. I had to host other website and when I switched back to host Inventree and cleared browser cache, it started working.
