### ISSUE TITLE
SalesOrder print Suppplier Reference

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#6568]
### Body of the issue

Hi Tream,

i would lke to print the Suplier Order Reference
![image](https://github.com/inventree/InvenTree/assets/130482028/21645d14-5c15-4db8-8fb9-d22eb44f9a9e)

i tried with:
```
<tr>			
   <td valign="top">{% trans "Your refrence:" %} </td>
   <td valign="top">{{ Supplier.Reference }} </td>
   <td colspan='3'></td>
</tr>

```
Which does not print the reference. did i miss something?
coud you please provide instructuions or the proper code snippet to do so.

I find it very hard to find documentation on how to do this 

Br Martijn

**Comment by LavissaWoW** [comment]
For SalesOrder, there's no `supplier_reference`. There is however a `customer_reference`.

For SO, the field is accessible via `order.customer_reference`
For PO, the field is accessible via `order.supplier_reference`

**Comment by LavissaWoW** [comment]
I actually just somewhat handled the same case you discussed with invoicing. Although my case is to generate invoices for internal projects to pay for stock they use.

All accounting is outside InvenTree,but I built a simple report template that lists all SO line items, total sum and a 15% warehousing fee. This is then sent to accounting to perform the internal cost reallocation.

**Comment by mabroens** [comment]
Hi @LavissaWoW , yes that was what i was looking for thank you. i stupid enough my SO had this `order.customer_reference` already in and i had a type in my PO template. but now its solved. thanks you

Br Martijn
