### ISSUE TITLE
[FR] Alter behaviour of some bulk API calls

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#6570]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Working with Stock API endpoints, there are 2 types of bulk actions:
1. Endpoints accepting a sub-serializer
2. Endpoints accepting only an array of PKs

Working with data in PUI, this presents a little data display dilemma.
Alternative 1 allows me to use complete objects for data rendering.
Alternative 2 doesn't allow for this, and would require custom rendering functions with re-fetching of data from the API. 

The current workflow goes like this:
- Get array of objects from `table.selectedRecords`
- Map objects to API form `tableField`
- Render objects using above field, allowing for removing records in-form

### Suggested solution

Implement sub-serializers for PK-only endpoints.

### Describe alternatives you've considered

Rendering the records in a `preForm` table. However, this differs from other endpoints and won't be editable after opening the form window.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by LavissaWoW** [comment]
Example of data display for endpoint with sub-serializer:
![image](https://github.com/inventree/InvenTree/assets/7506688/0583eaba-fc6e-4379-80b2-841449577d56)

`api/stock/transfer/` takes an array of objects in its `items` slot. This enables rendering data to piggyback on the form field.
`api/stock/change_status/` only takes an array of PKs/ints. Rendering data and form data cannot co-exist on the same field here.

**Comment by matmair** [comment]
@LavissaWoW do you have a list of affected routes?

**Comment by LavissaWoW** [comment]
@matmair the status change endpoint. And all endpoints that use the BulkDeleteMixin.

**Comment by SchrodingersGat** [comment]
@LavissaWoW so the suggested change here is *only* for the `change_status` endpoint?

**Comment by LavissaWoW** [comment]
@SchrodingersGat no, it would be for the BulkDeleteMixin too 🙈

**Comment by LavissaWoW** [comment]
```bash
x@DESKTOP-J1HJERS:~/InvenTree/InvenTree$ grep -rn BulkDeleteMixin
InvenTree/api.py:228:class BulkDeleteMixin:
InvenTree/api.py:305:class ListCreateDestroyAPIView(BulkDeleteMixin, ListCreateAPI):
common/api.py:25:from InvenTree.api import BulkDeleteMixin, MetadataView
common/api.py:352:class NotificationList(NotificationMessageMixin, BulkDeleteMixin, ListAPI):
common/api.py:411:class NewsFeedEntryList(NewsFeedMixin, BulkDeleteMixin, ListAPI):
common/api.py:502:class ErrorMessageList(BulkDeleteMixin, ListAPI):
common/api.py:548:class PendingTaskList(BulkDeleteMixin, ListAPI):
common/api.py:577:class FailedTaskList(BulkDeleteMixin, ListAPI):

x@DESKTOP-J1HJERS:~/InvenTree/InvenTree$ grep -rn ListCreateDestroyAPIView
order/api.py:26:    ListCreateDestroyAPIView,
order/api.py:497:    PurchaseOrderLineItemMixin, APIDownloadMixin, ListCreateDestroyAPIView
order/api.py:631:class SalesOrderAttachmentList(AttachmentMixin, ListCreateDestroyAPIView):
order/api.py:1099:class PurchaseOrderAttachmentList(AttachmentMixin, ListCreateDestroyAPIView):
order/api.py:1365:class ReturnOrderAttachmentList(AttachmentMixin, ListCreateDestroyAPIView):
part/api.py:23:    ListCreateDestroyAPIView,
part/api.py:400:class PartAttachmentList(AttachmentMixin, ListCreateDestroyAPIView):
part/api.py:1851:class BomList(BomMixin, ListCreateDestroyAPIView):
company/api.py:9:from InvenTree.api import AttachmentMixin, ListCreateDestroyAPIView, MetadataView
company/api.py:84:class CompanyAttachmentList(AttachmentMixin, ListCreateDestroyAPIView):
company/api.py:100:class ContactList(ListCreateDestroyAPIView):
company/api.py:124:class AddressList(ListCreateDestroyAPIView):
company/api.py:159:class ManufacturerPartList(ListCreateDestroyAPIView):
company/api.py:217:class ManufacturerPartAttachmentList(AttachmentMixin, ListCreateDestroyAPIView):
company/api.py:251:class ManufacturerPartParameterList(ListCreateDestroyAPIView):
company/api.py:315:class SupplierPartList(ListCreateDestroyAPIView):
stock/api.py:29:    ListCreateDestroyAPIView,
stock/api.py:803:class StockList(APIDownloadMixin, ListCreateDestroyAPIView):
stock/api.py:1193:class StockAttachmentList(AttachmentMixin, ListCreateDestroyAPIView):
stock/api.py:1286:class StockItemTestResultList(StockItemTestResultMixin, ListCreateDestroyAPIView):
InvenTree/api.py:305:class ListCreateDestroyAPIView(BulkDeleteMixin, ListCreateAPI):
build/api.py:13:from InvenTree.api import AttachmentMixin, APIDownloadMixin, ListCreateDestroyAPIView, MetadataView
build/api.py:569:class BuildAttachmentList(AttachmentMixin, ListCreateDestroyAPIView):
```

**Comment by matmair** [comment]
That is a lot of endpoints, any changes here need to be tested and weighed - especially regarding render and database access performance

**Comment by SchrodingersGat** [comment]
The `bulk delete` endpoints are a special case, I think. Can we handle those separately?

How many endpoints do you wish to change - *excluding the bulk delete ones*?

**Comment by LavissaWoW** [comment]
Closing out this, as the change won't be necessary.
