### ISSUE TITLE
Buildorder (un)allocated stock

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#6576]
### Body of the issue

Hi Team,

I'm creating a picklist in whicn i'd like to print req qty per pcb, total req (Qty*Qtyperppcb) availeble tock allocated and unallocate stock.
Hers my code snip.:

```
{% for line in bom_items.all %}
<tr>
	<!-- <td>{{ line.manufacturer.name }}</td> -->
	<td>{{ line.sub_part.name }}</td>
	<td>{{ line.reference }}</td>
	{% multiply line.quantity build.quantity as ReqQty %}
	<td>{% decimal ReqQty %}</td>
	<td>{% decimal line.available_quantity %}</td>
	<td>{% decimal line.allocated_quantity %}</td>
	<td></td>
	<td>{% decimal line.unallocated_quantity %}</td>
</tr>

{% endfor %}
```
problem only my calculation is working meaning: `line.available_quantity`, `line.allocated_quantity` and  `line.available_quantity` are not.
what am i doing wrong?

Br Martijn

**Comment by mabroens** [comment]
Hi @LavissaWoW 

thanks for the feedback that already got me most. i had already seen this page but looked at it the wrong way.

I now get this
![image](https://github.com/inventree/InvenTree/assets/130482028/c992a236-134d-4c88-b18b-6777a1c7c817)
but would also like to print the qty available in stock.

```
{% for line in line_items.all %}
			<tr>
				<td>{{ line.part.name }}</td>
				<td>{{ line.bom_item.reference }}</td>
				<td>{% decimal line.quantity %}</td>
				<td>{% decimal line.bom_item.available %}</td>
				<td>{% decimal line.allocated_quantity %}</td>
				<td></td>
				<td>{% decimal line.unallocated_quantity %}</td>
			</tr>

		{% endfor %}
```

how would i add that to the report?
`<td>{% decimal line.bom_item.available %}</td>` is not working obviously

**Comment by mabroens** [comment]
that did not work but `<td>{% decimal line.part.available_stock %}</td>` does.

where and how could i have found this myself? i feel stupid having to ask these things as they feel like simpel solutions

**Comment by LavissaWoW** [comment]
If something in a report context is said to be an instance of something, you will generally have access to all the data in the item's serializer. In your instance here, a part. You can either look at the serializer code to see what's available, or simply perform an API call and look at what is returned. Anything that the API returns for a part, you will have access to via the `line.part` variable.

**Comment by wolflu05** [comment]
If you have to write a lot of reports, you could also spin up a devcontainer und use the debugger feature inside the template.

**Comment by mabroens** [comment]
@wolflu05  'the debugger feature'?? sound awesome and like something that could help me.

How can i enable this where can i find more information on how to do so?

**Comment by wolflu05** [comment]
Here are some [docs](https://docs.inventree.org/en/latest/develop/devcontainer/#prerequisites) around how to setup a devcontainer. Then try running inventree via the debugger and then upload your template and you should be able to locate it at `dev/media/report_templates/....`. Then simply press before the line number to add a break point and on next render of your template it should pause there and you should be able to see the context available.
![image](https://github.com/inventree/InvenTree/assets/76838159/4afcefdd-e453-45b8-975c-ed7a293d5721)
