### ISSUE TITLE
Consumed Stock wrong

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#6577]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi Team,

I have made a build order. and its completed but now i see that somehow, i must have done something wrong (Multiple entries per IPN), the consumed stock is wrong.

In my case i made the build order for 20 PCB's.
first received 2 for validation and then received the remaining 18.
but i can now se ethat the consumed stock is verry verry wierd:
![image](https://github.com/inventree/InvenTree/assets/130482028/2b8ddfaa-20a3-4f5a-accf-345fc8002ddd)

what is the best way to revert this? and what could i have done wrong?

### Steps to Reproduce

no idea sorry

### Expected behaviour

.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.3
Django Version: 3.2.19
Commit Hash: 1f3a49b1
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@mabroens you will have to provide much more information  here for us to be able to assist.

For starters:

- Can you share the BOM for the assembled part?
- How much stock of each part shown here did you *expect* to allocate to the build order?

**Comment by mabroens** [comment]
@SchrodingersGat i just found something else thats wierd.
i went to this product in the bom search for a specific bead and it should then return only on line but as you can see it returns 2 line one thats not even matching
![image](https://github.com/inventree/InvenTree/assets/130482028/df02cfd8-c2bc-4ed9-8a72-63bc9551646d)

might this have something to do with the isseue

**Comment by SchrodingersGat** [comment]
In the *consumed stock* for the build order - do all of the consumed items point to the *same* build order?

**Comment by mabroens** [comment]
yes all point to the same BO

**Comment by SchrodingersGat** [comment]
@mabroens I would think that perhaps there has been a user input error on the build order, and these items actually have been allocated against it. Unless you have some evidence that there is a repeatable bug, I do not think there is much to go on here.

In terms of "fixing" the stock, you can use the admin interface to edit each individual stock item, and clear the `consumed_by` field - this will unallocate it from the build order and put it back into stock.

**Comment by mabroens** [comment]
Ok yeas i think I did something wrong but no idea what. 

Ill try to correct stock via the admin page. Thx for the support

**Comment by mabroens** [comment]
We can close this issue

Thanks for the support
