### ISSUE TITLE
Overwrite existing files?

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#659]
I just went up update after not using the software for a while and I got a 
```
MEDIA_ROOT: /root/InvenTree/inventree_media

You have requested to collect static files at the destination
location as specified in your settings:

    /root/InvenTree/inventree_static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: 
```
I was unsure what exactly was changed and what I should pick. I snapshot the jail running my InventreeServer so I just rolled it back but would like to upgrade soon.

**Comment by SchrodingersGat** [comment]
That static files are (for e.g.) scripts / css / static images etc - the only files that will be stored at STATIC_ROOT will be generated by InvenTree and should be fairly safe to overwrite.

No "user files" live here

**Comment by a7hybnj2** [comment]
Perfect! Thanks!
