### ISSUE TITLE
Input Chinese characters at Unit field reported an error

### ISSUE THREAD

**Issue by weizhangny** [inventree/InvenTree#6596]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

In old version  0.11 doesn't report an issue; the new version reported an error after system migration.
I have found a workaround method - In administrator mode, add a physical unit for the international characters - both name and symbol need be the Chinese unit name.

### Steps to Reproduce

1. Go to “Add new part"
2. Input Chinese characters "个“ at field "Unit"
3. Click submit

### Expected behaviour

measurement unit error

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.13.5

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
> I have found a workaround method - In administrator mode, add a physical unit for the international characters - both name and symbol need be the Chinese unit name.

This is probably what you are going to have to do - create custom physical units as needed. InvenTree already provides a way to add custom units on top of the [pint conversion library](https://pint.readthedocs.io/en/stable/) (which as far as I can tell, does not support multi-lingual support).

So, I would suggest that you add these custom units as required.

**Comment by weizhangny** [comment]
The workaround (add physical unit) is not stable. Now when I edit a part, the unit measurement appear again. I suggest that reopen this issue. 
Probably just after I modified/added the physical unit, the part edit/add seems to work; after some days, it wouldn't work any more.

**Comment by SchrodingersGat** [comment]
@weizhangny can you please provide some more information about your latest comment. Some scr
eenshots and examples would be really helpful.

**Comment by weizhangny** [comment]
Just after I added a new custom physical unit, the error was not generated. After a while, the unit error came up consistantly.

**Comment by weizhangny** [comment]
![inventree-create-part-with-unit-error](https://github.com/inventree/InvenTree/assets/74438069/d86050a8-74d2-4c48-bc6a-038b738f6e63)
![inventree-custom-physical-unit](https://github.com/inventree/InvenTree/assets/74438069/4ff4a98d-e121-436c-90c0-c0327804ad87)

**Comment by SchrodingersGat** [comment]
Have you tried updating to the latest version? This seems to work ok in `0.14.x`:

![image](https://github.com/inventree/InvenTree/assets/10080325/5587d60b-092e-4f37-a7dc-062f6a0b4981)
