### ISSUE TITLE
BOM Revision

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#660]
I have a part with a BOM.  I built the prototype and now have to revision the BOM.  Is there a way of doing that with out modifying the current BOM?  Or is there a way to revision the current part?

**Comment by SchrodingersGat** [comment]
> Or is there a way to revision the current part?

Sure is!

![image](https://user-images.githubusercontent.com/10080325/75925928-aba88780-5ebd-11ea-9e90-328b9876683e.png)

![image](https://user-images.githubusercontent.com/10080325/75925983-c3800b80-5ebd-11ea-9ee0-8449e1f37be4.png)

**Comment by lookme2** [comment]
@SchrodingersGat I should have know that.  Got it thanks!
