### ISSUE TITLE
[Docker] dynamic shared libraries for mariadb (and others) are missing in the 0.14.0 build

### ISSUE THREAD

**Issue by shapirus** [inventree/InvenTree#6625]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

```
inventree-server_1  | Traceback (most recent call last):
inventree-server_1  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
inventree-server_1  |     import MySQLdb as Database
inventree-server_1  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/__init__.py", line 17, in <module>
inventree-server_1  |     from . import _mysql
inventree-server_1  | ImportError: Error loading shared library libmariadb.so.3: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/MySQLdb/_mysql.cpython-311-i386-linux-musl.so)
```

### Steps to Reproduce

Try to use the 0.14.0 docker image.

### Expected behaviour

All must work.

The root cause of the issue is the following change:

https://github.com/inventree/InvenTree/compare/0.13.6..0.14.0#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L64-L69

It removed the installation of *runtime* libraries in the base image. It was moved to install_build_packages.sh, but when it's done there, they only stay in the prebuild image and don't make it to the later stages.

Runtime libraries need to be installed in the base image.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.14.0

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Thanks for letting us know. This will be fixed as part of https://github.com/inventree/InvenTree/pull/6621
