### ISSUE TITLE
 /home/inventree/data/config.yaml missing during update

### ISSUE THREAD

**Issue by icvdok** [inventree/InvenTree#6627]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Config file missing during update procedure

### Steps to Reproduce

Run docker compose run inventree-server invoke update during first setup or update. 

### Relevant log output

```bash
haservice@ss-00:/dockerconfig/inventree_origlionet_acc$ docker compose run inventree-server invoke update
[+] Creating 2/1
 ✔ Network acc_net_inventree   Created                                                                                                                          0.1s
 ✔ Container acc_inventree-db  Created                                                                                                                          0.0s
[+] Running 1/1
 ✔ Container acc_inventree-db  Started                                                                                                                          0.3s
Loading config file : /home/inventree/data/config.yaml
./init.sh: exec: line 56: invoke: not found
```

**Comment by SchrodingersGat** [comment]
See https://github.com/inventree/InvenTree/pull/6621 - we will a patch out for this soon. Sorry for the inconvenience!
