### ISSUE TITLE
Creating Build | Part is not showing In Dropdown 

### ISSUE THREAD

**Issue by smvaibhav** [inventree/InvenTree#663]
Part is not showing at the time of Creating Build
![image](https://user-images.githubusercontent.com/46482387/76601137-4e9c7980-652e-11ea-8b6f-8414e236bd03.png)

**Comment by SchrodingersGat** [comment]
HI @smvaibhav - the "Part" drop-down here will only show parts which are marked as "assembly".

![image](https://user-images.githubusercontent.com/10080325/76698781-f5357580-66fa-11ea-88e7-743ae649de56.png)

Make sure you have the "Assembly" option enabled for any part you wish to build

**Comment by SchrodingersGat** [comment]
@smvaibhav does this address your issue? Cheers
