### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by ECCOsea** [inventree/InvenTree#6632]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

https://inventree.org/demo

returns HTTP ERROR 502

### Steps to Reproduce

Just visit https://demo.inventree.org/

### Expected behaviour

Just open demo

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

no info

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@ECCOsea thanks for reporting - we are currently working out some issues with our docker image - https://github.com/inventree/InvenTree/pull/6621

Will be fixed shortyl

**Comment by SchrodingersGat** [comment]
@ECCOsea demo is back up again :)
