### ISSUE TITLE
Docker compose setup doesnt recognize .env variables

### ISSUE THREAD

**Issue by VanCalsterFinn** [inventree/InvenTree#6636]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hi! I am trying to setup an Inventree instance. I followed the newer method which requires only 3 files: docker-compose, .env, caddyfile. When running the command "docker compose run --rm inventree-server invoke update" i get an error that says the some of the variables in the .env file are not set. Sometimes it only complains about "INVENTREE_DB_USER" not being set. When at other times it also says the "INVENTREE_EXT_VOLUME" variable is not set. 

### Steps to Reproduce

0. I made a directory called "InventreeSource" on my Desktop
1. I downloaded the docker-compose.yml, .env and caddyfile from the official inventree github
2. I dragged the 3 files into the InventreeSource folder
3. Renaming the env file to ".env" because the dot was lost in downloading
4. I opened a command prompt in my InventreeSource folder and ran the command "docker compose run --rm inventree-server invoke update"
5. I get the error that says the .env variables are not set

### Relevant log output

```bash
time="2024-03-04T12:57:42+01:00" level=warning msg="The \"INVENTREE_EXT_VOLUME\" variable is not set. Defaulting to a blank string."
time="2024-03-04T12:57:42+01:00" level=warning msg="The \"INVENTREE_EXT_VOLUME\" variable is not set. Defaulting to a blank string."
time="2024-03-04T12:57:42+01:00" level=warning msg="The \"INVENTREE_EXT_VOLUME\" variable is not set. Defaulting to a blank string."
time="2024-03-04T12:57:42+01:00" level=warning msg="The \"INVENTREE_EXT_VOLUME\" variable is not set. Defaulting to a blank string."
time="2024-03-04T12:57:42+01:00" level=warning msg="The \"INVENTREE_EXT_VOLUME\" variable is not set. Defaulting to a blank string."
error while interpolating services.inventree-db.environment.[]: required variable INVENTREE_DB_USER is missing a value: You must provide the 'INVENTREE_DB_USER' variable in the .env file
```

**Comment by matmair** [comment]
Where did you download the files (link)? And are you sure the docker process is allowed to access and sees the .env file?

**Comment by SchrodingersGat** [comment]
Can you also please share the current contents of the `.env` file?
