### ISSUE TITLE
Purchase order doesn't find all components - and uses wrong currency

### ISSUE THREAD

**Issue by tomse** [inventree/InvenTree#6647]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

So I'm trying out a purchase order and import a .csv - all the components are added beforehand. 
Some components are shown in step 3 of the import, and some are not - red circles in the screenshots.

(should I make a new bug report for the currency?)
My currency default is Danish Kr., but for this supplier I've chosen USD. (see yellow circles)
How can I make a selection that everything should be in USD? having 20+ different components is tedious to change.

![image](https://github.com/inventree/InvenTree/assets/1444539/a8171c5c-1eb1-436a-b4f3-7e1a1f5a3427)

Here you can see one of the individual parts that aren't to find for the same supplier partnumber (column selection naming would be nice if they also are the same as Step 2 in the csv import).
![image](https://github.com/inventree/InvenTree/assets/1444539/489ebb18-1269-45de-881a-7e62ca6595ee)

### Steps to Reproduce

Make an order, make sure all the components have been added beforehand.
Get a CSV with your order and upload it.

### Expected behaviour

all the missing component fields should be filled out.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

[0.13.5]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by tomse** [comment]
[LCSC_Exported.csv](https://github.com/inventree/InvenTree/files/14502269/LCSC_Exported.csv)

Attached is my CSV file

**Comment by SchrodingersGat** [comment]
> (should I make a new bug report for the currency?)
> My currency default is Danish Kr., but for this supplier I've chosen USD. (see yellow circles)
> How can I make a selection that everything should be in USD? having 20+ different components is tedious to change.

Please raise a new issue for this. The importer for purchase order items does not currently support switching currency AFAIK. So this would need to be implemented

**Comment by SchrodingersGat** [comment]
Regarding this issue - For line number 4, in the drop-down menu can you find and select the `c131154` component?

**Comment by tomse** [comment]
> Regarding this issue - For line number 4, in the drop-down menu can you find and select the `c131154` component?

unfortunately no

![image](https://github.com/inventree/InvenTree/assets/1444539/9e6679d1-8fee-4609-a93a-617f880723ab)

![image](https://github.com/inventree/InvenTree/assets/1444539/03725458-b658-42f1-8cce-6066c19e952c)

**Comment by SchrodingersGat** [comment]
> unfortunately no

That's very weird then. Can you find the supplier part in the global search drop-down (magnifying glass icon in the top right of the screen)?

**Comment by tomse** [comment]
very weird indeed..

yes, I can also find it in "Parts" search/filter box

here is a partial search for "c13"
![image](https://github.com/inventree/InvenTree/assets/1444539/66eec69b-a054-4df0-9028-62237150763e)

The components have all been added using kintree (don't know if that helps).

I'm really at a loss here.. I've been trying to see any differences between a found component and unfound component.

Running in docker, are there any logs I can look in to supply more data?

**Comment by SchrodingersGat** [comment]
@tomse I cannot think of any more tests to run for this. It is very strange.

In the "import" window, when you type something (e.g. "C13") into the drop-down menu, can you show the API request and response data? This is available in the "developer" tab in your browser

**Comment by tomse** [comment]
@SchrodingersGat  I hope the following screenshots are what you're requesting

by import window I'm understanding this one?
![image](https://github.com/inventree/InvenTree/assets/1444539/89bb5fdc-b55b-4258-b7a0-6d887b098482)


![image](https://github.com/inventree/InvenTree/assets/1444539/924404a2-8370-4b93-a765-d1d327c1e656)

![image](https://github.com/inventree/InvenTree/assets/1444539/aaf8c9f8-8821-42a1-8da3-f83cfaed1142)


![image](https://github.com/inventree/InvenTree/assets/1444539/a7209180-eb66-49ca-bd29-34e093e480f7)


![image](https://github.com/inventree/InvenTree/assets/1444539/af309f82-d74d-4ed8-bc71-b658ac914f15)

**Comment by SchrodingersGat** [comment]
@tomse no that's just for notification fetching. You'll need to capture while you are typing into the box. It should send a search query with the text you type, back to the server

**Comment by tomse** [comment]
@SchrodingersGat I'm not sure if I'm doing this correctly
Using firefox:
Step 3 in uploading csv.

Web Developer Tools
* Network (is the only place I can find request/response)

"ALL" seems messy - specially under Response where I get a truncated html output with 40k lines 
![image](https://github.com/inventree/InvenTree/assets/1444539/fb85216d-bebe-406c-931f-2c1fa622baf6)

**Comment by tomse** [comment]
I'm doing something wrong.. sorry.. web dev tools is not something I'm fluent in.. not even 1%
I cleared "something" and now the request/response are empty, even after reloading the page.
it would probably be best that you describe in better detail what I need to do, I'm ok in switching browser is that is your preference

I do get this filter output in another window, but it doesn't matter if I select request/response, it shows the same


![image](https://github.com/inventree/InvenTree/assets/1444539/985ed295-65d9-48f5-b37a-964156bfae33)

**Comment by wolflu05** [comment]
What @SchrodingersGat meant was doinging the following with the Select input where you have the issues (this was using chrome, but should work with firefox too):

https://github.com/inventree/InvenTree/assets/76838159/8dfe46e0-9ca3-4e68-8588-7bdcf2f920e0

**Comment by tomse** [comment]
what am I doing wrong? (make note I expect we are in the step 3 of uploading the csv rather than  adding a new part)

https://github.com/inventree/InvenTree/assets/1444539/5059d298-1d32-45bd-9ea5-e3b73ea79f57

**Comment by SchrodingersGat** [comment]
@tomse that looks correct. What request data is being sent?

- URL
- Headers
- Parameters

It looks like the response is empty. For the response:

- What is the return code?
- Headers

**Comment by SchrodingersGat** [comment]
@tomse huh, looking into the code it appears that this import method does not make use of the API. The options for each drop-down are pre-rendered on the server...

This is all going to be totally refactored as part of our [roadmap to fix the import/export interface](https://github.com/inventree/InvenTree/issues/6389). Perhaps you would be willing to sponsor this feature?

**Comment by tomse** [comment]
@SchrodingersGat done :-)

**Comment by SchrodingersGat** [comment]
@tomse thanks! In the mean time, you could also use the [admin import functionality](https://docs.inventree.org/en/stable/settings/import/) to get your data into the system? This one edge case  is very strange.

**Comment by tomse** [comment]
strange didn't get a notification other than the bot.. should we keep the issue open ?

**Comment by SchrodingersGat** [comment]
@tomse I will keep it open as it is referenced by a PR which will address it: https://github.com/inventree/InvenTree/pull/6911

**Comment by SchrodingersGat** [comment]
This has now been addressed in #6911
