### ISSUE TITLE
[PUI]Form Select default value disappears after opening dropdown

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#6654]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Any form field using `react-select` that has a default value set will have that value visually erased if the dropdown menu is oened and closed without selecting anything new (I.e. clicking outside the dropdown)

Interestingly, the value is retained if you actively select an entry in the dropdown after loading.

### Steps to Reproduce

![chrome_RetHp05DvL](https://github.com/inventree/InvenTree/assets/7506688/f67f3150-26f6-47c1-b1ad-94dc75648d0a)

### Expected behaviour

The default value of the field should be retained

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

0.14.0 dev

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@LavissaWoW this is caused by a simple caching issue. Fix incoming!
