### ISSUE TITLE
After upgrade to 14.1, "Instant" login but few permissions

### ISSUE THREAD

**Issue by chl33** [inventree/InvenTree#6655]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I upgraded to 0.14.1.  I'm running via a Docker-compose "stack" in Portainer.  I did what I have done before: set the  `command` field for the server container in the docker-compose file to be "invoke upgrade", disabled `restart`, then started the system.  After the upgrade completed, I removed the `command` field from the docker-compose file and started the system again.

I was not asked to login to my inventree session afterward and I am able to browse the parts tree, but I get permission errors when I try to search and when I tried to transfer a part location.  I logged out, then pressed the "login" button.  Instead of being prompted for username and password, I immediately appeared logged-in again in  the regular web interface, but have the same lack of permissions.

I previously tried to update to 0.14.0, but this failed  to update due to the lack of "invoke" in that Docker image.  So I went back to 0.13.6 for a couple days.  I didn't try anything after that which would have tested permissions before I tried going to 0.14.1, however.

### Steps to Reproduce

Upgrade from 0.13.6 to 0.14.1 via the docker-compose method I described above(??)

### Expected behaviour

Be prompted to login, with a username and password.  Then have permissions to search and move parts.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.14.1
Django Version: 4.2.10
Commit Hash: df0bb34
Commit Date: 2024-03-05

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-94-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by LavissaWoW** [comment]
Add your InvenTree server URI to `trusted_origins` in your `config.yaml`
0.14.x bumped Django to 4.x, and Django 4.x has much stricter CORS requirements that Django 3.x

**Comment by LavissaWoW** [comment]
Have a read through https://inventree.org/blog/2024/03/02/0.14.0 to fully learn what 0.14 brings

**Comment by chl33** [comment]
Thank you!!!  I added this to my `config.yaml` (took a couple tries to get the format right), and now things work for me again!
```
trusted_origins:
 - 'https://{my-server}'
```
