### ISSUE TITLE
DOCKER CADDYFILE ISSUE

### ISSUE THREAD

**Issue by arkajyotidas** [inventree/InvenTree#6658]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Switching to caddy from NGINX is causing trouble, 
My inventree docker instance runs on a local LAN server with multiple other apps. I access the Inventree instance through the server's IP address and the port, which is ok. Since I use a static IP from my ISP I was able to forward my port of the router and access the instance, but now after switching to Caddy, it is not possible anymore. Also, this is causing the mobile app to fail to connect via mobile internet.

### Steps to Reproduce

SET THE INVENTREE PORT VIA ENV
INSTALL VIA DOCKER 
FORWARD PORT OF THE ROUTER TO INVENTREE PORT
TRY TO CONNECT THROUGH MOBILE APP OR ACCESS THE INVENTREE INSTANCE THROUGH FQDN 

### Expected behaviour

N/A

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

14.00

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@arkajyotidas you will have to provide some more information here. Did you have some custom settings in your nginx configuration file? These will no doubt have to be replicated to your caddyfile.

Also, some  sort of log / error message / etc will be required at minimum.

**Comment by arkajyotidas** [comment]
server {

    # Listen for connection on (internal) port 80
    listen 80;

    real_ip_header proxy_protocol;

    location / {

        proxy_set_header      Host              $http_host;
        proxy_set_header      X-Forwarded-By    $server_addr:$server_port;
        proxy_set_header      X-Forwarded-For   $remote_addr;
        proxy_set_header      X-Forwarded-Proto $scheme;
        proxy_set_header      X-Real-IP         $remote_addr;
        proxy_set_header      CLIENT_IP         $remote_addr;

        proxy_pass_request_headers on;

        proxy_redirect off;

        client_max_body_size 100M;

        proxy_buffering off;
        proxy_request_buffering off;

        # Do not touch this unless you have a specific reason - this and the docker-compose need to match
        proxy_pass http://inventree-server:8000;
    }

    # Redirect any requests for static files
    location /static/ {
        alias /var/www/static/;
        autoindex on;

        # Caching settings
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }

    # Redirect any requests for media files
    location /media/ {
        alias /var/www/media/;

        # Media files require user authentication
        auth_request /auth;

        # Content header to force download
        add_header Content-disposition "attachment";
    }

    # Use the 'user' API endpoint for auth
    location /auth {
        internal;

        proxy_pass http://inventree-server:8000/auth/;

        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }

}

my ngnix  configuration file

**Comment by arkajyotidas** [comment]
(log_common) {
    log {
        output file /var/log/caddy/{args.0}.access.log
    }
}
{
	auto_https off
}
# Change the host to your domain (this will serve at inventree.localhost)
{$INVENTREE_SITE_URL:192.168.0.11} {
    import log_common inventree

    encode gzip

    request_body {
        max_size 100MB
    }

    handle_path /static/* {
        root * /var/www/static
        file_server
    }

    handle_path /media/* {
        forward_auth {$INVENTREE_SERVER:"http://inventree-server:8000"} {
            uri /auth/
        }
        root * /var/www/media
        file_server
    }

    reverse_proxy {$INVENTREE_SERVER:"http://inventree-server:8000"}
}
my caddy config file

**Comment by SchrodingersGat** [comment]
@arkajyotidas please provide some information about the actual errors you are seeing here

**Comment by arkajyotidas** [comment]
try to visit the site using network.arkajyotidas.net:1337 you will see SSL protocol error
