### ISSUE TITLE
CORS issues for static / media files behind proxy

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6663]
While investigating issues related to https://github.com/inventree/InvenTree/pull/6399 I stumbled across an existing issue which may need addressing.

When serving media and static files behind a proxy (e.g. Caddy as per our docker setup), and requesting from a different host (i.e. a CORS request) the files are not served - due to failed CORS checks.

The `/api/` requests are honoured - these are handled by django and our configured CORS whitelist / etc.

However the `/static/` and `/media/` endpoints *do not observe* these allowed CORS hosts:

```
    handle_path /static/* {
        root * /var/www/static
        file_server
    }

    handle_path /media/* {
        forward_auth {$INVENTREE_SERVER:"http://inventree-server:8000"} {
            uri /auth/
        }
        root * /var/www/media
        file_server
    }
```

To demonstrate this, spool up the local vite server and point to the demo server: `https://demo.inventree.org`:

![image](https://github.com/inventree/InvenTree/assets/10080325/1513224d-2ab3-4665-b7c7-0a61da7ecb4d)

![image](https://github.com/inventree/InvenTree/assets/10080325/7a58a0db-8027-45dc-8a2a-88f4c4b8d228)

@matmair @wolflu05 any idea how to tackle this? https://github.com/inventree/InvenTree/pull/6662 fixes the issue with static files in *development* mode, but not behind the proxy.

Ideally the best solution here would be to forward the cors headers from our server, based on the configured CORS whitelist values. Not sure if that is possible using Caddy?

Second idea might be to adjust the caddy configuration file itself, to explicitly set which origins are valid? Again, not sure if this is possible and it has the disadvantage of requiring double input of data. Ideally, would like it all to run from our existing config file or env variables.

**Comment by SchrodingersGat** [comment]
Some useful references:

- https://kalnytskyi.com/posts/setup-cors-caddy-2/
- https://gist.github.com/ryanburnette/d13575c9ced201e73f8169d3a793c1a3
- https://enable-cors.org/server_caddy2.html

**Comment by matmair** [comment]
Not sure we can use config.yaml, env should work
