### ISSUE TITLE
[FR] Add Customer name to Part Stock overview

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#6666]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

currently the Part Stock overview only shows the status of a part and if its shipped. but it would be nice if we coula also show the customer to whome it was shipped. that helps whenever you need to find out who has a specific board with a specific version.

### Suggested solution

add option to show the customer name under `Location`

### Describe alternatives you've considered

could not ye find any

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Could certainly be added but very low priority for me

**Comment by SchrodingersGat** [comment]
@mabroens can you show a screenshot of what you mean?

**Comment by mabroens** [comment]
![image](https://github.com/inventree/InvenTree/assets/130482028/08806e57-46e2-4c16-9df3-a97bcc55170f)
does this help?

The goal would be to see which customer not only Shipped to customer.

and as for the Status field this also shows my request for having more states

and im running:
# Version Information:
InvenTree-Version: 0.12.3
Django Version: 3.2.19
Commit Hash: 1f3a49b1
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment]
@mabroens yes that does make it clearer. This is a good candidate for the new user interface - it will not make sense to spend the effort required to implement it in the current one
