### ISSUE TITLE
Blank page on fresh install

### ISSUE THREAD

**Issue by jacky4566** [inventree/InvenTree#6667]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

After performing a fresh OS install, running the docker container. 
I am left with a blank white page. 
Trying to set Site URL to plain localhost for intranet viewing. IE. Putting `http://inventree.192.168.42.14` into a browser results in a google search.  Not recognized as a value URL. 

### Steps to Reproduce

1. Fresh install of Ubuntu 23.04 on Proxmox Container
2. Create inventree-data directory
3. Pull pre-build `image docker pull inventree/inventree`
5. Change ENV file `INVENTREE_SITE_URL="http://localhost""`
6. Change Caddy File `{$INVENTREE_SITE_URL:localhost}`
7. Run docker setup `docker compose run --rm inventree-server invoke update`
8. Start Containers `docker compose up -d`

### Relevant log output
From SSH on local machine
```bash
inventree@InvenTree:~$ curl -v http://192.168.42.14/
*   Trying 192.168.42.14:80...
* Connected to 192.168.42.14 (192.168.42.14) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.42.14
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Caddy
< Date: Sat, 09 Mar 2024 15:38:39 GMT
< Content-Length: 0
<
* Connection #0 to host 192.168.42.14 left intact
inventree@InvenTree:~$
```

**Comment by arkajyotidas** [comment]
Are you using a different machine on lan to host docker?

**Comment by SchrodingersGat** [comment]
`http://inventree.192.168.42.14` is not a valid host URL. Can you share your `.env` and `Caddfile` contents? (redact any sensitive information)

**Comment by jacky4566** [comment]
_http://inventree.192.168.42.14 is not a valid host URL._ This is where i am confused. Using the default value of _inventree.localhost_ , how are we supposed to access the site?

`
# Caddyfile for Inventree
# The following environment variables may be used:
# - INVENTREE_SITE_URL: The upstream URL of the Inventree site (default: inventree.localhost)
# - INVENTREE_SERVER: The internal URL of the Inventree container (default: http://inventree-server:8000)

(log_common) {
    log {
        output file /var/log/caddy/{args.0}.access.log
    }
}

# Change the host to your domain (this will serve at localhost)
{$INVENTREE_SITE_URL:localhost} {
    import log_common inventree

    encode gzip

    request_body {
        max_size 100MB
    }

    handle_path /static/* {
        root * /var/www/static
        file_server
    }

    handle_path /media/* {
        forward_auth {$INVENTREE_SERVER:"http://inventree-server:8000"} {
            uri /auth/
        }
        root * /var/www/media
        file_server
    }

    reverse_proxy {$INVENTREE_SERVER:"http://inventree-server:8000"}
}
`

`
# InvenTree environment variables for docker compose deployment

# Specify the location of the external data volume
# By default, placed in local directory 'inventree-data'
INVENTREE_EXT_VOLUME=./inventree-data

# Ensure debug is false for a production setup
INVENTREE_DEBUG=False
INVENTREE_LOG_LEVEL=WARNING

# InvenTree admin account details
# Un-comment (and complete) these lines to auto-create an admin acount
#INVENTREE_ADMIN_USER=
#INVENTREE_ADMIN_PASSWORD=
#INVENTREE_ADMIN_EMAIL=

# Database configuration options
INVENTREE_DB_ENGINE=postgresql
INVENTREE_DB_NAME=inventree
INVENTREE_DB_HOST=inventree-db
INVENTREE_DB_PORT=5432

# Database credentials - These should be changed from the default values!
INVENTREE_DB_USER=pguser
INVENTREE_DB_PASSWORD=pgpassword

# Redis cache setup (disabled by default)
# Un-comment the following lines to enable Redis cache
# Note that you will also have to run docker-compose with the --profile redis command
# Refer to settings.py for other cache options
#INVENTREE_CACHE_HOST=inventree-cache
#INVENTREE_CACHE_PORT=6379

# Options for gunicorn server
INVENTREE_GUNICORN_TIMEOUT=90

# Enable custom plugins?
INVENTREE_PLUGINS_ENABLED=True

# Run migrations automatically?
INVENTREE_AUTO_UPDATE=True

# Image tag that should be used
INVENTREE_TAG=stable

# Site URL - update this to match your host (and update the Caddyfile too!)
INVENTREE_SITE_URL="http://localhost"

COMPOSE_PROJECT_NAME=inventree
`

**Comment by arkajyotidas** [comment]
Set INVENTREE_SITE_URL="http://192.168.42.14" in .env file
Remove ":localhost" from $INVENTREE_SITE_URL:localhost in caddyfile.

**Comment by matmair** [comment]
localhost points to your local machine and is only accessible on the local machine. If you want to use the machine on the internet either pass a valid DNS name (that points to the servers IP) or an IP to site URL. TLS issuance will not work on IP's so use HTTP in that case.

**Comment by jacky4566** [comment]
> Set INVENTREE_SITE_URL="http://192.168.42.14" in .env file Remove ":localhost" from $INVENTREE_SITE_URL:localhost in caddyfile.

This was the answer, I can get in on my LAN now. 

Thank you very much for the support.

**Comment by SchrodingersGat** [comment]
@jacky4566 glad you got it working. We might look into making the documentation a little clearer around this

**Comment by Knochi** [comment]
> Set INVENTREE_SITE_URL="http://192.168.42.14" in .env file Remove ":localhost" from $INVENTREE_SITE_URL:localhost in caddyfile.

So what should then be in this line?

default:` {$INVENTREE_SITE_URL:inventree.localhost} {`

and then ` {$INVENTREE_SITE_URL:} {` ???
