### ISSUE TITLE
Authentication Failure over https

### ISSUE THREAD

**Issue by nikolai2111** [inventree/InvenTree#6670]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Today I updated to the new release, unfortunately inventree only works over the unencrypted `http:`, it doesn't matter if I connect over the local network or from the outside through a cloudflare tunnel.

When I connect via `http:` I get the following errors. And I can't log out or do anything.

Edit 1: I tried to restart docker and also the whole VM it's running on. 

![grafik](https://github.com/inventree/InvenTree/assets/10119322/ae749f77-8f21-44ba-b539-bef97db98732)
![grafik](https://github.com/inventree/InvenTree/assets/10119322/f191b817-12a5-4d92-8791-d472c4a9529e)

### Steps to Reproduce

I don't know if it's that easy to reproduce external.

### Expected behaviour

It should work as normal, like before the update.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.14.1
Django Version: 4.2.10
Commit Hash: df0bb34
Commit Date: 2024-03-05

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-100-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'InvenTreeBulkPlugin', 'slug': 'inventree-bulk-plugin', 'version': '1.2.3'}, {'name': 'ApprisePlugin', 'slug': 'apprise', 'version': '1.1'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by G-Pereira** [comment]
I have the same error while accessing inventree through a reverse proxy, my setup:
HTTPS -> nginx proxy -> HTTP -> inventree-proxy
and:
INVENTREE_SITE_URL="https://inventory.lcdporto.org"

**Comment by SchrodingersGat** [comment]
@nikolai2111 @G-Pereira please read the [site access section](https://docs.inventree.org/en/stable/start/config/#server-access) in the docs.

If you are running behind another proxy, likely what is happening is that the proxy headers do not match the condfigured `ALLOWED_HOSTS`. We recently updated to django 4.2 (read the [breaking changes section](https://inventree.org/blog/2024/03/02/0.14.0)) which tightens up site access requirements.

If you look at the `inventree-server` and `inventree-proxy` logs in your setup, you should be able to see some error messages related to the access attempts - please post those here!

You should also try enabling the `INVENTREE_USE_X_FORWARDED_HOST` and `INVENTREE_USE_X_FORWARDED_PORT` settings. If this does not work, add the proxy host and upstream host to your `INVENTREE_ALLOWED_HOSTS` config.

**Comment by G-Pereira** [comment]
Thank you. I'll check it later today and confirm the fix

**Comment by nikolai2111** [comment]
I did not know where to find these logs, so I tried your suggestion. And it seems that enabling the `INVENTREE_USE_X_FORWARDED_HOST` and `INVENTREE_USE_X_FORWARDED_PORT` settings does not work for my setup.

But I have set up the `INVENTREE_SITE_URL` correctly as described in the following line of the documentation. Then InvenTree will work like a charm for me again.
https://github.com/inventree/InvenTree/blob/a613a7b9fcf5acad124213599ac20220764a84d3/docs/docs/start/config.md?plain=1#L76

The problem is solved for me, I forgot to set the `INVENTREE_SITE_URL` correctly. We can leave the issue open, maybe @G-Pereira has another problem or can post the logs here.

**Comment by matmair** [comment]
@G-Pereira did this help you?

**Comment by matmair** [comment]
@nikolai2111 for docker you can find the logs by running `docker compose logs` in the same directory as your docker-compose.yaml is placed.

**Comment by SchrodingersGat** [comment]
You can also specify which container to inspect, e.g.

```
docker compose logs inventree-server
```

**Comment by G-Pereira** [comment]
Since I have a reverse proxy pointing to Caddy using HTTP I had to do a more intricate config to get it working. So in my .env I now have:
```
INVENTREE_SITE_URL="http://inventory.lcdporto.org"
INVENTREE_TRUSTED_ORIGINS="https://inventory.lcdporto.org"
```
