### ISSUE TITLE
Database migrations failed while updating to 0.14.1

### ISSUE THREAD

**Issue by templeofhead** [inventree/InvenTree#6684]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hello. While updating from 0.13.3 to 0.14.1 i've encountered a weird issue, which i can't work around of. The update process went fine until the DB migration, which has failed with the error i'm attaching below. I'm fully aware that the issue might be specific to my installation. My config is: ubuntu 20.04, python3.9, postgres 14. I had to revert the inventree server from a backup since it's a production unit, though if need arise - i will break it again :). Thanks in advance.

### Steps to Reproduce

apt update --only-upgrade inventree
wait until DB migrations kick in
get an error

### Relevant log output

```bash
# inv update| Running migrations:
# inv update|   Applying machine.0001_initial... OK
# inv update|   Applying part.0120_parttesttemplate_key... OK
# inv update|   Applying part.0121_auto_20240207_0344...Traceback (most recent call last):
# inv update|   File "/opt/inventree/InvenTree/manage.py", line 24, in <module>
# inv update|     main()
# inv update|   File "/opt/inventree/InvenTree/manage.py", line 20, in main
# inv update|     execute_from_command_line(sys.argv)
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
# inv update|     utility.execute()
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
# inv update|     self.fetch_command(subcommand).run_from_argv(self.argv)
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
# inv update|     self.execute(*args, **cmd_options)
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
# inv update|     output = self.handle(*args, **options)
# inv update|   File "/opt/inventree/InvenTree/InvenTree/management/commands/runmigrations.py", line 18, in handle
# inv update|     check_for_migrations(force=True, reload_registry=False)
# inv update|   File "/opt/inventree/InvenTree/InvenTree/tasks.py", line 694, in check_for_migrations
# inv update|     call_command('migrate', interactive=False)
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 194, in call_command
# inv update|     return command.execute(*args, **defaults)
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
# inv update|     output = self.handle(*args, **options)
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/base.py", line 106, in wrapper
# inv update|     res = handle_func(*args, **kwargs)
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 356, in handle
# inv update|     post_migrate_state = executor.migrate(
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
# inv update|     state = self._migrate_all_forwards(
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
# inv update|     state = self.apply_migration(
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
# inv update|     state = migration.apply(state, schema_editor)
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/db/migrations/migration.py", line 132, in apply
# inv update|     operation.database_forwards(
# inv update|   File "/opt/inventree/env/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
# inv update|     self.code(from_state.apps, schema_editor)
# inv update|   File "/opt/inventree/InvenTree/part/migrations/0121_auto_20240207_0344.py", line 14, in set_key
# inv update|     template.key = InvenTree.helpers.generateTestKey(str(template.test_name).strip())
# inv update|   File "/opt/inventree/InvenTree/InvenTree/helpers.py", line 94, in generateTestKey
# inv update|     if key[0].isdigit():
# inv update| IndexError: string index out of range
```

**Comment by SchrodingersGat** [comment]
@templeofhead it looks like there is a bug which occurs if you have a `PartTestTemplate` instance which will generate a "key" with zero length.

As the "key" only uses alpha-numeric characters, perhaps you have a `PartTestTemplate` instance with an odd name? Can you look at that? If you can, please let me know the names of the templates you have configured. Or at least any which have "strange" names.

Also, there is a PR incoming to address this too, but I would like to work out from your instance where the error is coming from.

https://github.com/inventree/InvenTree/pull/6685

**Comment by templeofhead** [comment]
Where should i look for it exactly?

**Comment by SchrodingersGat** [comment]
A quick way would be to look at the "admin" site under "Part test templates":

![image](https://github.com/inventree/InvenTree/assets/10080325/2cbf670f-73f4-4095-8a14-ff54bfe3069c)
![image](https://github.com/inventree/InvenTree/assets/10080325/dfa125a8-7912-4024-ad80-b74d9a27a658)

**Comment by templeofhead** [comment]
There you go.
![image](https://github.com/inventree/InvenTree/assets/142637610/d34afd24-5022-41d3-8437-bf7c99d7b3f9)

**Comment by SchrodingersGat** [comment]
> Собранный щит

@templeofhead yep, looks like non-latin chars are rejected. Will update the patch to fix this. bit of an oversight!

**Comment by templeofhead** [comment]
Should i try renaming it and updating again or wait for the patch?

**Comment by templeofhead** [comment]
Roger. How would i know that the patch is out? I understand it will be terribly inconvenient, also brash, to ask you to dm me about it :)

**Comment by SchrodingersGat** [comment]
As this is a pretty serious bug in terms of migrations, I'll issue a new release once https://github.com/inventree/InvenTree/pull/6685 is merged in. I'll ping back on this issue after that

**Comment by templeofhead** [comment]
Thanks a lot for the help, looking forward for the patch. Have a good $(time of day) :)

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/releases/tag/0.14.2

Installer and docker builds will take a couple of hours to be ready

**Comment by matmair** [comment]
The package, installer and docker for this are now released to stable channels @templeofhead
