### ISSUE TITLE
[FR] disable the "must be on BOM" restriction

### ISSUE THREAD

**Issue by aep** [inventree/InvenTree#6695]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

i'm using inventree to track servers and components in it.
it's a bit inconvenient to edit the BOM to include all possible components, like all 14 different drive types.

### Suggested solution

would be nice to have an option to disable the "must be on BOM" restriction

### Describe alternatives you've considered

we're currently just adding every possible component to the bom

### Examples of other systems

a DCIM or asset managment could do it i guess, but those don't really work well for when you build things yourself

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/6695">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/6695/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/6695/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@aep implementation incoming in https://github.com/inventree/InvenTree/pull/6719

**Comment by SchrodingersGat** [comment]
Thank you @SchrodingersGat for contributing to close this issue! ⭐

The rewards from this issue, totalling $50, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
