### ISSUE TITLE
[PUI] Make "footer" (buttons etc) stick to the bottom of the modal (no scroll)

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6696]
> Make "footer" (buttons etc) stick to the bottom of the modal (no scroll)

Big +1 on this, the ability to click "submit" without having to scroll to the bottom is a killer advantage of the old UI vs. the new UI currently

Also, I know the old UI also handles "enter" as a modal form submission. This behavior also should be kept / added to the new UI.

This is a task I'm interested in submitting a PR for.

EDIT: Related Issue: https://github.com/orgs/mantinedev/discussions/1141

_Originally posted by @XanderLuciano in https://github.com/inventree/InvenTree/issues/5354#issuecomment-1993793221_

**Comment by SchrodingersGat** [comment]
@XanderLuciano :)

**Comment by XanderLuciano** [comment]
Heck yeah, I got it covered :)
