### ISSUE TITLE
Allocate from multi source doesn't add

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#670]
When doing a build and you have to allocate parts from 2 stock locations they don't add up to complete the allocation.
<img width="763" alt="Screen Shot 2020-03-18 at 10 09 01 AM" src="https://user-images.githubusercontent.com/36831279/76969312-9b9e9800-6900-11ea-9db9-5c644485c3b8.png">

**Comment by a7hybnj2** [comment]
Haha, I just looked! I think they are adding but the 2nd allocation is being used as a decimal. Whoops.

**Comment by SchrodingersGat** [comment]
That was a weird one! Javascript lets you add strings and numbers interchangeably, with no guarantee that you'll like the results ;)
