### ISSUE TITLE
Problems upgrading docker env from 0.13.6 to 0.14.2

### ISSUE THREAD

**Issue by Alex9779** [inventree/InvenTree#6702]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I have issues updating my env from 0.13.6 to 0.14.2.
I tried it several times now.
If I do it with the 0.13.6 docker-compose environment and just pull the new images and run "invoke upgrade" in the server container it first seems to work but I get authorization error messages when I try to do certain things, when I then clear my authorization cookie to log in again I am not able to.
If I update my .env and compose files to the new versions using Caddy I am not able to acces the server but everything seems fine, no real error messages.
Actually Caddy is making me some troubles because I run everything already behind a reverse HAProxy using HTTPS, Caddy in the default config tries to get a cert but is not able to. I deactivated the auto HTTPS, I tried default entries for server and also my real server name but nothing works.

Is there an upgrade path for docker env from 0.13.6 to 0.14.2? What do I have to change and what not?

### Steps to Reproduce

---

**Comment by SchrodingersGat** [comment]
> because I run everything already behind a reverse HAProxy using HTTPS,

This is likely the issue. Check out the "breaking changes" section in the 0.14.0 release notes:

- https://inventree.org/blog/2024/03/02/0.14.0
- https://github.com/inventree/InvenTree/releases/tag/0.14.0

Site access has become more "locked down" in django 4.

You will need to read these docs to configure - https://docs.inventree.org/en/stable/start/config/#server-access

> but I get authorization error messages when I try to do certain things, when I then clear my authorization cookie to log in again I am not able to.

What error messages are you getting?

**Comment by Alex9779** [comment]
> What error messages are you getting?

Can't tell for sure at the moment, will update when I do the next try if it happens again...

Thanks for the links, I missed the  blog entry completely...

Still I am not absolutely sure how to handle the Caddy stuff, I used Caddy in a different project but there all the automation it provides was useful, not in this particular case so.
I think for the moment I'll stick with Nginx and try to get the other problems sorted...

**Comment by Alex9779** [comment]
Ok got it working with Nginx still, played with the CORS settings and site URL and now it seems to work.
Post-poning the switch to Caddy...
