### ISSUE TITLE
[PUI] Report editor not rendering error message correctly

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6705]
When template rendering throws an error, the error is not displayed as expected. Instead it just shows `[object Blob]`

![image](https://github.com/inventree/InvenTree/assets/10080325/74b2b89e-a462-45e5-b36a-916991cf72c6)

@wolflu05 any thoughts on this one? I have tried to fix but no luck.

**Comment by wolflu05** [comment]
Could that be related to something with caddy or some other changes on the backend?

**Comment by wolflu05** [comment]
@SchrodingersGat I have found the issue, PR is incoming.
