### ISSUE TITLE
[PUI] Details Field Text Length

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6715]
Text in a "details field" should clip, but a very long value causes rendering issues:

![image](https://github.com/inventree/InvenTree/assets/10080325/e79007a5-2a66-4eb0-8289-17adf353b3df)

@wolflu05 @LavissaWoW any thoughts on this one?

**Comment by wolflu05** [comment]
Maybe we should cut that, and add some kind of accordion component to show the full text on click?

**Comment by SchrodingersGat** [comment]
That sounds suitable, I think

**Comment by wolflu05** [comment]
Or isn't there a backend restriction? If it's not too long, we may could also simply show all by like breaking?

**Comment by XanderLuciano** [comment]
I think we could wrap that data in a [`<Spoiler>`](https://mantine.dev/core/spoiler/) to clip the text, but allow expansion if desired

**Comment by SchrodingersGat** [comment]
It looks like `<Spoiler>` is based on height, really what we want is to break the text into multiple lines so it does not exceed the table width. I think this can be achieved with some simple CSS?

**Comment by LavissaWoW** [comment]
@SchrodingersGat I Actually tinkered with something like this just yesterday. You can define a max width, and instead of pixels, use `ch` for characters. Additionally, this can be used with the CSS `clamp(min, optimal, max)` function

**Comment by wolflu05** [comment]
https://stackoverflow.com/questions/499137/how-can-i-force-a-long-string-without-any-blank-to-be-wrapped this may be useful
