### ISSUE TITLE
Parts sold

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#672]
I see there is a way to have a supplier be marked as a customer but, how do I sell that customer things? Do I make up a PO or what?

**Comment by SchrodingersGat** [comment]
Great question. Currently the concept of "Purchase Orders" is not implemented, but definitely is something that is on the horizon.

Parts will be tracked against individual customers, and also support concepts such as "product returns" etc.

I just have had not had the bandwidth to look at implementing this yet.

**Comment by a7hybnj2** [comment]
Great to hear it’s somewhere on the horizon. I would find it very helpful.

**Comment by a7hybnj2** [comment]
Would be nice if there could be a difference in prices for sales and orders. For instance if I buy 5000 resistors for .10 each but I sell them for .12 each would be cool if it could calculate that.
