### ISSUE TITLE
Import error on "invoke update" with 0.14.2

### ISSUE THREAD

**Issue by RealNagus** [inventree/InvenTree#6729]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [X] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I upgraded my Inventree installation from 0.13.0 to the most recent release 0.14.2 and hit a small issue when running `invoke update`. 
When invoke tries to install the plugins it imports the `get_plugin_file()` function from `Inventree/Inventree/config.py`. For some reason the Django imports on the top of the file fail, although Django is installed in the virtual environment (which is activated of course). A full logfile of the output is attached. I'm not familiar with invoke, my guess is it's not actually using the environment?

When the imports are disabled the task runs just fine, but of course a later step will fail. A properly timed re-enabling between these two points will finish the update just fine, though.

[invoke_update_log.txt](https://github.com/inventree/InvenTree/files/14624631/invoke_update_log.txt)

### Steps to Reproduce

1. Setup and activate a new virtual environment.
2. Install a fresh Inventree 0.13.0 instance (I used MySQL backend)
3. After `invoke update` finishes, update source to 0.14.2 (`git checkout 0.14.2`)
4. Run `invoke update` again.
5. It fails right after installing the packages from requirements.txt

### Relevant log output

```bash
File "/home/nagilum/tmp/inventree/InvenTree/tasks.py", line 213, in plugins
    from InvenTree.InvenTree.config import get_plugin_file
  File "/home/nagilum/tmp/inventree/InvenTree/InvenTree/InvenTree/config.py", line 13, in <module>
    from django.core.files.base import ContentFile
ModuleNotFoundError: No module named 'django'
```

**Comment by SchrodingersGat** [comment]
@RealNagus this may indicate a problem with your virtual environment setup - have you setup a [python virtual environment](https://docs.inventree.org/en/stable/start/intro/#virtual-environment)?

Please provide the output of the following commands

```
which invoke
```

```
invoke --version
```

```
invoke version
```

```
python3 -m invoke version
```

**Comment by RealNagus** [comment]
Yes, I created a fresh virtual environment to verify the behavior on a second machine (Debian 12, Python 3.11.2).

Here's the output from the commands. 

```
which 
/home/nagilum/tmp/inventree/InvenTree/.venv/bin/python
```
```
which invoke
/usr/bin/invoke
```
```
invoke --version
Invoke 2.0.0
```
```
invoke version
Traceback (most recent call last):
  File "/usr/bin/invoke", line 33, in <module>
    sys.exit(load_entry_point('invoke==2.0.0', 'console_scripts', 'invoke')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 380, in run
    self.execute()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 565, in execute
    executor.execute(*self.tasks)
  File "/usr/lib/python3/dist-packages/invoke/executor.py", line 127, in execute
    result = call.task(*args, **call.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 115, in __call__
    result = self.body(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nagilum/tmp/inventree/InvenTree/tasks.py", line 940, in version
    import InvenTree.InvenTree.version as InvenTreeVersion
  File "/home/nagilum/tmp/inventree/InvenTree/InvenTree/InvenTree/version.py", line 14, in <module>
    import django
ModuleNotFoundError: No module named 'django'
```
```
python -m invoke version
/home/nagilum/tmp/inventree/InvenTree/.venv/bin/python: No module named invoke
```

Looks like `/usr/bin/invoke` is to blame here. If I uninstall the Debian version and add it manually via `pip` to the virtual environment everything works smoothly. Sorry for the troubles.

**Comment by SchrodingersGat** [comment]
@RealNagus glad we could help :)

**Comment by niclash** [comment]
I had the same problem, and would be good if that is added to the documentation at https://docs.inventree.org/en/stable/start/install/#initialize-database. I have submitted a PR.
