### ISSUE TITLE
[Enhancement] POs can't have attachments?

### ISSUE THREAD

**Issue by maholli** [inventree/InvenTree#673]
Hey @SchrodingersGat- thank you for all your hard work on this tool! I LOVE it.

I generated a PO today and noticed I couldn't attach anything like receipts, correspondence, etc... to the PO. This seems general enough that it shouldn't need to be implemented on a per-user basis by editing the database config.

**Comment by SchrodingersGat** [comment]
Attachments for POs is a great idea - I'll have a look into this one
