### ISSUE TITLE
Optional SITE_URL setting and CSRF_TRUSTED_ORIGINS

### ISSUE THREAD

**Issue by RealNagus** [inventree/InvenTree#6730]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

This is more of a question than an actual bug report. Maybe I'm just missing something.
I had a 0.13.0 release version of Inventree running for a while and just upgraded to 0.14.2. Right after upgrading I was unable to login/logout or POST anything due to CSRF errors from Django. 
In my initial install I didn't specify a SITE_URL, only the base URL in the web interface settings. Adding a site URL to my config.yaml quickly fixed the issue. I'm not sure why the old version ran just fine.

From what I see in the source the CSRF_TRUSTED_ORIGINS is set to the trusted_origins settings and, if defined, the site_url. Shouldn't one of these settings be made mandatory when installing/running Inventree, so the CSRF protections are working as intended?

### Steps to Reproduce

Unset trusted_origins and site_url settings before starting the server. 

### Expected behaviour

Starting the server should fail if CSRF_TRUSTED_ORIGINS is empty, like it fails for example when static_root is not set.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

The issue appeared when upgrading from 0.13.0 to 0.14.2. 

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Forbidden (Origin checking failed - https://... does not match any trusted origins.): /accounts/login/
[16/Mar/2024 17:23:34] "POST /accounts/login/ HTTP/1.1" 403 6948
```

**Comment by SchrodingersGat** [comment]
> I'm not sure why the old version ran just fine.

Because `0.13.x` ran on Django `3.x` - we have now updated to django `4.2` which has much stricter site access controls.

> Shouldn't one of these settings be made mandatory when installing/running Inventree, so the CSRF protections are working as intended?

You are probably right. Exiting early with a helpful error message if one of the required parameters is not set would be better.
