### ISSUE TITLE
[Testing] Event triggers disabled during tests

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#6734]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Writing tests for the IPN plugin, I didn't get it to run on create and save events.
Doing some digging, I found the culprit. When running tests, all table events are disabled by default.

### Steps to Reproduce

https://github.com/inventree/InvenTree/blob/7905c556cf2ca7afb0b7e4c80033d4993338ae22/InvenTree/plugin/base/event/events.py#L119-L122

### Expected behaviour

Perhaps we should allow events if you explicitly set `settings.PLUGIN_TESTING_EVENTS = True`?

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

0.15.0-dev

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@LavissaWoW I'm happy with the suggested solution of adding a configurable setting. However it is not solely related to plugins so maybe `TEST_TABLE_EVENTS`?
