### ISSUE TITLE
[Enhancement] Add "On Order" flag to Part Status 

### ISSUE THREAD

**Issue by maholli** [inventree/InvenTree#674]
Similar to the "No Stock" flag for Part Status:
![image](https://user-images.githubusercontent.com/29153441/77239496-be4ade00-6b98-11ea-923f-7c6811c55006.png)

There should be an "On Order" flag for Parts that have an On Order quantity >0:
![image](https://user-images.githubusercontent.com/29153441/77239511-e4707e00-6b98-11ea-9cbe-018cb47d2dba.png)

I'd make the flag blue-ish to visually correlate to PO "Placed" status:
![image](https://user-images.githubusercontent.com/29153441/77239528-08cc5a80-6b99-11ea-8daa-b1e07bfa8ad9.png)

**Comment by SchrodingersGat** [comment]
Hi @maholli can you please mock-up a "screenshot" of where this on-order flag might be placed?

**Comment by maholli** [comment]
@SchrodingersGat I'm envisioning it something like this:
(from that Parts tab)
![image](https://user-images.githubusercontent.com/29153441/77575584-fd2aad80-6e90-11ea-945f-529a2cc41e71.png)

Obviously not critical, but would nice to have :)

**Comment by a7hybnj2** [comment]
I like it
