### ISSUE TITLE
ContentType model is throwing error with OPTIONS calls

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#6755]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

OPTIONS calls try to call model.get_api_url() - which is not implemented on Django's build in model ContentType

### Steps to Reproduce

1. Create an APIView that has a serializer that references ContentType
2. Nake an OPTIONS call to that endpoint

### Expected behaviour

Provide either an API endpoint or do not fail similar to the built-in User model

### Deployment Method

- [X] Docker
- [X] Bare metal

### Version Information

InvenTree-Version: 0.15.0 dev
Django Version: 4.2.10
Commit Hash: b49e06e
Commit Date: 2024-03-19
Commit Branch: deploy
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Platform: macOS-14.3.1-arm64-arm-64bit
Installer: GIT

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
AttributeError

type object 'ContentType' has no attribute 'get_api_url'
```

**Comment by SchrodingersGat** [comment]
@matmair does this apply to the main code base or a plugin? Can you provide an example we can test against?

**Comment by matmair** [comment]
This applies to usage in plugins - we seem to not reference ContentType in any serializer. I will create a PR that fixes this and include a very minimal testing case for a few build-ins (ContentType, User, Group).

I am curious if we should also expose Sites and Permissions to the API for superusers.
