### ISSUE TITLE
Time zone error.

### ISSUE THREAD

**Issue by CFox243** [inventree/InvenTree#6768]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

.env

INVENTREE_TIMEZONE=CST

error:
raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting: CST

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
iv tried CST,CDT,UTC-6,UTC−06:00
all throw the error. what am i doing wrong

### Steps to Reproduce

change .env settings try to run
sudo docker compose run --rm inventree-server invoke update

error pops up.

### Relevant log output

```bash
File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 260, in __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting: CST
```

**Comment by matmair** [comment]
The TZ identifier for CST is "US/Central" - as seen in the second column of the wikipedia you linked

**Comment by CFox243** [comment]
🤦🤦
ughs was thinking abbreviations....
thank you

**Comment by matmair** [comment]
This is common pitfall wit python tz, happens to all of us

**Comment by zly20129** [comment]
> The TZ identifier for CST is "US/Central" - as seen in the second column of the wikipedia you linked

Hmm, i define INVENTREE_TIMEZONE=US/Centra in .env, but it is not work.
However, if i replace to UTC, it work.
I try to define CST\UTC+8\UTC+08 or Asia/Shanghai, nothing can run it work.

**Comment by zly20129** [comment]
> This is common pitfall wit python tz, happens to all of us

I try to add """ to text, such as INVENTREE_TIMEZONE="US/Centra".
This does not provide any substantial assistance.
