### ISSUE TITLE
Completing Build Outputs without enough allocated stock on Build Orders

### ISSUE THREAD

**Issue by bberg115** [inventree/InvenTree#6810]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When completing the Incomplete Output and NOT selecting "Complete outputs if stock has not been fully allocated" - a user can close out an incomplete build output even without any parts allocated. I confirmed this bug exists even if some, but not enough, parts are allocated. However, it does not appear to happen when a serialized (unique) items is on the BOM..

### Steps to Reproduce

1. Create build order for qty X
2. Create build incomplete output for anything between 1 and X
3. Complete output without checking "Complete outputs if stock has not been fully allocated"

![chrome_XuHOPY2ZEW](https://github.com/inventree/InvenTree/assets/17869135/b0e3a4cd-7845-4a05-9187-ca737ec5f1b1)

![chrome_0MMPuxb8Pr](https://github.com/inventree/InvenTree/assets/17869135/fc2776ee-a879-40ca-aada-32b9c04967c7)

![chrome_Gq8XNq7vhE](https://github.com/inventree/InvenTree/assets/17869135/609e5644-5617-4a6e-84ee-473b076bc6bb)

### Expected behaviour

I would expect this to NOT create a "completed output" and stay incomplete. 

**Edit: we realized that "Completed Outputs" go to stock before the BO is completed and is messing up stock.**

However, Inventree does NOT allow for you to close the Build Order without checking the "Accept that stock items have not been fully allocated to this build order" after clicking Complete Build.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

13.6

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by LavissaWoW** [comment]
I've ssen something oddly similar to this myself. A colleague made a BO, added outputs, then cancelled it withput completing said outputs. Stock was still subtracted from all BOM items.

**Comment by SchrodingersGat** [comment]
> Stock was still subtracted from all BOM items.

@LavissaWoW this is likely because your colleague had selected the "subtract allocated stock" option when cancelling the build order. 

> I would expect this to NOT create a "completed output" and stay incomplete.

@bberg115 when you "complete" a build output, this action is separate to consuming the stock required to produce the build output. Stock is "consumed" then the build order (not the build output) is marked as complete.

Ref: https://docs.inventree.org/en/stable/build/allocate/

**Comment by bberg115** [comment]
Thanks for the reply. Per your link:

> Untracked stock items are consumed against the build order, once the order is completed.

However, the stock items are consumed after allocation.

Here's a better example that I just did on the demo servo.

1. Create BO
2. Allocate untracked stock
3. Cancel order - Making sure to NOT consume stock.

The untracked stock is no longer available, but per the link - they should not have been consumed since I never completed the order. Am I missunderstanding this?

Here are some screen shots.

![image](https://github.com/inventree/InvenTree/assets/17869135/82ac6dc1-a1f1-466c-abf3-14d4f4e10338)
![PowerToys_bIWJZ54ipx](https://github.com/inventree/InvenTree/assets/17869135/e116f65d-8a92-4c2a-8358-616237b36cee)
![PowerToys_b0ey3is5M6](https://github.com/inventree/InvenTree/assets/17869135/ec0f2b20-ae6f-4739-bf78-4f9671cfef63)
![PowerToys_2SzbsI5bJB](https://github.com/inventree/InvenTree/assets/17869135/c3b05f48-fa4a-4318-b9d7-d219a7a01438)

**Comment by bberg115** [comment]
Thanks for the reply. Per your link:

Untracked stock items are consumed against the build order, once the order is completed.

I have also verified that the stock is replaced when canceled.

However, the comment about completing BO with unallocated and incomplete is still not possible. I do not desire this feature, but  it looks like it should be a viable option per the screenshot below.
![image](https://github.com/inventree/InvenTree/assets/17869135/9aed49aa-88e0-48de-a872-596944ce969f)
