### ISSUE TITLE
Making the Packaging field editable at different stages

### ISSUE THREAD

**Issue by bmalatest** [inventree/InvenTree#6840]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

The packaging field and notes fields are very useful for quickly finding parts and ensuring that when sending parts to an assembly house that we can send the most suitable packaging (i.e., reel over cut tape, tray over bulk, etc.)

### Suggested solution

We would like to make the Packaging field and Notes field visible and editable at the time of receiving each line item. We would also like to make this field visible when allocating stock to a build (similar to the way Batch is visible, while still ensuring Batch is visible)

### Describe alternatives you've considered

No alternative available.

### Examples of other systems

We previously used PartKeepr which had a similar field that was editable per part and was displayed in the project report which was used for selecting which physical part we wanted to use.

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/6840">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/6840/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/6840/pledge.svg">
</picture>
</a>

**Comment by matmair** [comment]
Certainly a possible change but for me personal not a priority as we keep packaging information in pat/stock metadata. Maybe another dev here is intrested in implementing it.

**Comment by SchrodingersGat** [comment]
Requires https://github.com/inventree/InvenTree/issues/7205 to be implemented first
