### ISSUE TITLE
Download Image: Connection error: HTTPSConnectionPool

### ISSUE THREAD

**Issue by 15ah35** [inventree/InvenTree#6875]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

![image](https://github.com/inventree/InvenTree/assets/17753799/a6775ea1-6794-4849-8be3-61d512b6b8b4)

**The server where docker is installed is behind a network PROXY**

I get this error when using link to image feature:

Form errors exist
Remote Image*
https://resource.fs.com/mall/products/800x800/22318.H.jpg
URL of remote image file
Connection error: HTTPSConnectionPool(host='resource.fs.com', port=443): Max retries exceeded with url: /mall/products/800x800/22318.H.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))

### Steps to Reproduce

1. Click on download image from url
2. input url
3. click submit

### Expected behaviour

For the image to be successfully downloaded from the URL

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.15.0 dev
Django Version: 4.2.11
Commit Hash: ae83a10
Commit Date: Mar 26 2024

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-4.18.0-305.25.1.el8_4.x86_64-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
This seems like an SSL error by the external server. Please try to reproduce this on the demo server

**Comment by matmair** [comment]
@15ah35 can you still reproduce this? I would like to close this if not.

**Comment by 15ah35** [comment]
The 'Download from URL' setting is disabled on the demo server by default, and I cannot access the server settings to enable it. So, I am not able to test on the demo server.

**Comment by matmair** [comment]
Can you reproduce it on your server? I can not on mine

**Comment by 15ah35** [comment]
Yes I can. Same issue. My server is behind a proxy.

**Comment by matmair** [comment]
If your proxy is replacing the normal cert chain and your custom CA cert is not available in the certificate storage of the container it will not work.

**Comment by wolflu05** [comment]
Maybe you can try on your server to download the image via curl through the proxy. If that fails too, that's not an issue with InvenTree, but your server/proxy setup.

**Comment by 15ah35** [comment]
Curl download with proxy is successful, but InvenTree download fails.

**Comment by SchrodingersGat** [comment]
Do you provide your proxy information to curl? Or does it work it out somehow?

**Comment by 15ah35** [comment]
I provide my proxy info to curl

**Comment by SchrodingersGat** [comment]
Right. So, there you go then. We would need to add an option for supplying proxy information to InvenTree. Presumably other requests (such as version checks) are failing too in your instance.

If you would like the dev team to provide priority implementation to this you can fund the issue - otherwise I do not think that this will leap to the top of the pile.
