### ISSUE TITLE
API schema generation is not stable between dev enviroments

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#6882]
With the recent problems, I discovered that the API schema generation is highly unstable between dev and CI environments.

Main problems:
- plugin URLs are included by default
- the local currency config influences descriptions/enums
- server endpoints changes

I think at least 1 and 2 should be changed by default to make comparisons simpler

_Originally posted by @matmair in https://github.com/inventree/InvenTree/issues/6836#issuecomment-2023123850_

**Comment by matmair** [comment]
Thoughts @SchrodingersGat

**Comment by SchrodingersGat** [comment]
### Plugins

Plugin URLs should be disabled by default. Maybe we can add a flag to the invoke task to include these? But (at least for the public schema) these should be excluded.

### Currency

Would you be opposed to moving currency support out of the "sysadmin setup" - and into the database backed settings? I would like to allow this to be adjusted "at run time" anyway, so maybe this would also solve this issue.

### Server Host

Can we maybe add an option to the schema generation task to pass a URL? That way we can hard-code it for the public schema generation

**Comment by matmair** [comment]
This all sounds reasonable. This has no urgency, I will tackle it once the 0.15.x roadmap is done from my side. Maybe this is someone else wants to tackle (partly) in the meantime

**Comment by matmair** [comment]
@SchrodingersGat what default currencies do we want to have included in the schema? The current default is below; we could cut it to 3 or 4 (for example AUD, CNY, EUR, USD) IMO. What is your view on this? I already have to touch the code anyway to make it stable.

```
            * `AUD` - Australian Dollar
            * `CAD` - Canadian Dollar
            * `CNY` - Chinese Yuan
            * `EUR` - Euro
            * `GBP` - British Pound
            * `JPY` - Japanese Yen
            * `NZD` - New Zealand Dollar
            * `USD` - US Dollar
 ```

**Comment by SchrodingersGat** [comment]
I'm happy to reduce the "default" config setting, (AUD/CNY/EUR/USD) makes sense
