### ISSUE TITLE
Batch Code from Build Order not pre-populated in New Build Output Form

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#6886]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When creating a Build Order, I can set a Batch Code in the form - which I thought is intended to be used to pre-populate the form for creating new Incomplete Build Outputs (is it?).

The batch code is not carried into the build output form right now. Is this a bug, or do I misunderstand the "Batch Code" field for a Build Order?

### Steps to Reproduce

1) Add a `Batch Code` to a Build Order:
![24-03-28 15-15-35 0107](https://github.com/inventree/InvenTree/assets/296454/0b62f4fb-711d-4a42-8651-e5f019fed653)

2) Create a new Build Output in that Build Order:
![24-03-28 15-15-37 0108](https://github.com/inventree/InvenTree/assets/296454/196ab6fa-7bdb-4db6-9130-e56ec6962998)

### Expected behaviour

I would expect that the batch code would be populated in the build output form.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.15.0 dev
Django Version: 4.2.10
Commit Hash: c827133
Commit Date: 2024-03-18

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-rpi7-rpi-v8-aarch64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'IPNAutoGenerator', 'slug': 'ipnautogenerator', 'version': None}, {'name': 'OrderNotesTemplates', 'slug': 'ordernotestemplates', 'version': None}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.9.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@simonkuehling this value should be brought through when generating the new build output, yes.

**Comment by SchrodingersGat** [comment]
This is closed in https://github.com/inventree/InvenTree/pull/7000

Note: Only implemented in the *new* interface (React / PUI)
