### ISSUE TITLE
The Subscribe and Unsubscribe button is glitched!

### ISSUE THREAD

**Issue by E-Hain** [inventree/InvenTree#6894]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Clicking the subscribe button on any part/category to subscribe pops up the notification "You have unsubscribed to notifications for this item" even when there was no prior subscription. This same notification pops up when unsubscribing to any part/category "You have unsubscribed to notifications for this item" which is normal however it does not actually unsubscribe. A quick refresh of the page and it will show that you are subscribed again. I have not tested if this is only frontend visual error or if it has actually unsubscribed in the backend. This error can be reproduced in the Demo Inventree website.

### Steps to Reproduce

1. Click Subscribe for any part/category
2. First error appears "You have unsubscribed to notifications for this item"
3. Part will successfully subscribe
4. Click Unsubscribe button for any part/category (part seemingly successfully unsubscribes)
5. Refresh the page
6. Second error appears (still subscribed)

### Expected behaviour

I expect when I click subscribe for it to show that I have subscribed. I also expect when I click unsubscribe for it to actually unsubscribe

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.14.2
Django Version: 4.2.10
Commit Hash: b807e47
Commit Date: Mar 13 2024

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.5.0-26-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

### Relevant log output

```shell
No Relevant Log Output
```

**Comment by SchrodingersGat** [comment]
@E-Hain thanks for reporting - fix should be incoming in https://github.com/inventree/InvenTree/pull/6910
