### ISSUE TITLE
[Docker] Custom docker container for Caddy proxy

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6920]
Currently the docker setup requires a [custom caddy config file](https://docs.inventree.org/en/stable/start/docker_install/#required-files) which must be copied into the running [caddy container](https://hub.docker.com/_/caddy).

However we could simplify this by building our own proxy container which we then push to dockerhub / ghcr

This would reduce the number of required files

**Comment by SchrodingersGat** [comment]
While a custom caddyfile container might make complex / custom deployments harder, users can always revert to their own custom container in such cases. In general this should make setup simpler. A good target for 1.0.0

**Comment by wolflu05** [comment]
That will only work with named volumes, but then we need to instruct people to not change that named volume to a bind mount, but people will do that, ...

**Comment by matmair** [comment]
Wouldn’t the server not work anymore at that point?

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/inventree-caddy

**Comment by wolflu05** [comment]
> Wouldn’t the server not work anymore at that point?

I do not really understand what you mean by this.

**Comment by SchrodingersGat** [comment]
Image is now live - https://hub.docker.com/r/inventree/inventree-caddy/tags

I am currently testing , and will push a simplified docker setup if it works well

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/pull/8538

**Comment by SchrodingersGat** [comment]
Closing, see https://github.com/inventree/InvenTree/pull/8538
