### ISSUE TITLE
Resize / Rescale images

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#693]
When images are uploaded to the server, they should be automatically scaled down if they are too large.

For example part thumbnails do not need to be huge!

This could speed up server requests significantly.

Make a new ImageField class which enforces scaling when the image is uploaded.

**Comment by a7hybnj2** [comment]
Would this keep the original file also? That way requests could be fast with the thumbnails but the original available for reference if needed...?

**Comment by SchrodingersGat** [comment]
Yes, absolutely. I'm looking at using https://github.com/codingjoe/django-stdimage
