### ISSUE TITLE
docker installation guide outdated

### ISSUE THREAD

**Issue by alvaroalvarezih** [inventree/InvenTree#6952]
### Body of the issue

Dear all,

I installed inventree through docker few months ago, and I have no issues with the setup (on my notes it was just reported "follow the webpage instructions"), however, I have to perform a new setup from scractch, and it seems that the guidelines provided at https://docs.inventree.org/en/latest/start/docker_install/#before-you-start are completely out of date.
Mainly in the links to the github code. 
![Captura](https://github.com/inventree/InvenTree/assets/117641569/d224348d-f455-4a23-8b15-3977aacb2b91)
returned: 
![image](https://github.com/inventree/InvenTree/assets/117641569/90d28296-099c-43fc-8d7d-8cb9f2516eaa)
I found those files @ https://github.com/inventree/InvenTree/tree/master/contrib/container, and copying them to the local folder, allow me to continue with the setup.
Thanks for verifying it!

**Comment by SchrodingersGat** [comment]
@alvaroalvarezih thanks for reporting - fix is incoming in https://github.com/inventree/InvenTree/pull/6954
