### ISSUE TITLE
Exportable Allocate Stock to Build Table Data

### ISSUE THREAD

**Issue by bmalatest** [inventree/InvenTree#6955]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

We currently need to manually copy and paste the line items in the Allocate Stock section of a Build Order to get the data in the table in a useful format.

### Suggested solution

 We would like to be able to export the table data to a csv or other format as that information (part name, quantity needed, qty available, etc.) are used when we are submitting RFQs to our suppliers to purchase the required stock. 

### Describe alternatives you've considered

All options are manual copy and paste and that section of Inventree is the only method we can pull the information we need.

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/6955">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/6955/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/6955/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@bmalatest I would expose this as part of https://github.com/inventree/InvenTree/pull/6911 which is a complete overhaul of how we do data import / export.

**Comment by bmalatest** [comment]
this is still important for us but I know this requires a complete overhaul that is being worked on

**Comment by SchrodingersGat** [comment]
@bmalatest please note that this has now been implemented as part of https://github.com/inventree/InvenTree/pull/6911

![image](https://github.com/inventree/InvenTree/assets/10080325/70bd3955-37bb-49f7-9aed-396e4ed75b82)
