### ISSUE TITLE
Consumed Stock Table Data

### ISSUE THREAD

**Issue by bmalatest** [inventree/InvenTree#6956]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Under consumed stock within a build order, we would like to be able to export the table with all displayed fields in the default configuration with the addition of the Stock Supplier Part that was consumed

### Suggested solution

We would like to be able to export the table data to a csv or other format as that information is used for our own tracking purposes for traceability.

### Describe alternatives you've considered

None available (manual copy and paste only)

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/6956">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/6956/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/6956/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@bmalatest I would expose this as part of https://github.com/inventree/InvenTree/issues/3101 (which is being addressed in  https://github.com/inventree/InvenTree/pull/6911). This is a complete overhaul of how we do data import / export.

**Comment by bmalatest** [comment]
The export will allow us to export everything that is displayed but it shows the Part, which is helpful, but we would ideally also have the Supplier Part exported.

Example, if we have a build that calls for an 10k ohm 0402 resistor, and there were many stock options for this part, but we select RMCF0402FT10K0, we would like to know that this specific part is being used.

There is a work around, although cumbersome, where we would use the information contained in the Batch Field for us to search it but that is somewhat tedious.

**Comment by SchrodingersGat** [comment]
So, you are looking for the supplier part SKU to be included in the exported dataset

**Comment by SchrodingersGat** [comment]
@bmalatest fix incoming in https://github.com/inventree/InvenTree/pull/7418 which adds "SKU" to exported dataset
