### ISSUE TITLE
Admin panel BOM Item import requires Reference, Notes to be set (not null)

### ISSUE THREAD

**Issue by LastEdit** [inventree/InvenTree#6957]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Importing a 'BOM Item' table by way of the admin panel produces an error of `null value in column "reference" of relation "part_bomitem" violates not-null constraint` when there is no data in the certain columns. The 'Reference' and 'Note' column was tried, others may exist. The reference in this case being the BOM item reference.

This does not occur when manually editing a BOM Item in the admin panel, it saves and allows a blank field. It also does not occur on the Upload Bill of Materials section of the Parts section of the main site when uploading a single BOM.

It seems to be related to the `Reference` and `Notes` variables not changing to `''` by way of `CONVERT_NULL_FIELDS` on import. The table template was taken from the export, which exports capitalized column names for those fields. `CONVERT_NULL_FIELDS` looks like it is looking for lower case fields. `reference` appears in other datasets such as sales order and build order, which seem to contain exclusively lower case column names on export.

Not sure if it is related to the export template being off or the import functions being off.

### Steps to Reproduce

1. Go to the import page of the BOM Item section on admin page (site:port/admin/part/bomitem/import/)
2. Import table with empty 'Reference' or 'Note' column
3. Click submit and wait for error.

### Expected behaviour

Go to verify import screen to approve import

Should import as `reference: ''` and not `reference: None`

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

Devcontainer dd889e8

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@LastEdit thanks for reporting the bug. I have a fix incoming - https://github.com/inventree/InvenTree/pull/6962
