### ISSUE TITLE
Switch coverage tracking provider?

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#6966]
We are experiencing some weird behaviour around the UI with coveralls and there is some doubt about how active they still work on their infra/coverage uploaders. Their behaviour around flags/carryforward and closing flags is also causing problems

CodeCov would be a known, open-source (ish?) competitor by Sentry, which we already use without any problems. I would propose to test-drive CodeCov parallel to Coveralls and decide if it is better after a few weeks/months. Especially regarding the disrubtions the usage of DeepSource caused. Thoughts @inventree/triage @inventree/maintainer ?

**Comment by SchrodingersGat** [comment]
@matmair should we remove coveralls integration now, so we can close this?

**Comment by matmair** [comment]
@SchrodingersGat I would like to wait a bit to make sure it really works the way we want to; backfilling coveralls would be very hard
