### ISSUE TITLE
Showing IPN under part view if IPN is removed from 'Part Name Display Format'

### ISSUE THREAD

**Issue by JacobEFO** [inventree/InvenTree#6971]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I don't know if this is a bug per se, but I have a use case, where I in the part overview don't care showing the IPN as a part of the part name and have thus removed it so my Part Name Display Format is set to `{{ part.name }}`.

When you do so and view a part, you cannot see the part IPN. See for instance the overview:
<img width="1052" alt="image" src="https://github.com/inventree/InvenTree/assets/22648097/320f4c66-0db7-47c0-8887-09846490a03f">

Then you see the following when you've navigated to the part:
<img width="1433" alt="image" src="https://github.com/inventree/InvenTree/assets/22648097/44062df6-decb-4d6e-871f-345f9fabfd3b">

Is there any way to have IPN show up just below the `description` of the part? Alternatively that would be an excellent feature request.

### Steps to Reproduce

1. Go to `Settings`
2. Go to `Parts`
3. Change `Part Name Display Format` to not include `part.IPN`
4. Go to some part that has an affiliated `IPN`

### Expected behaviour

Inventree is likely designed exactly for this behavior, and thus I wouldn't classify the desire as expected behavior.

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.14.4
Django Version: 4.2.11
Commit Hash: 35fc954
Commit Date: 2024-03-22

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.6.12-linuxkit-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'KiCadLibraryPlugin', 'slug': 'kicad-library-plugin', 'version': '1.4.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
If you select the "show part details" button (as shown in your screenshot above) then the IPN will be visible:

![image](https://github.com/inventree/InvenTree/assets/10080325/23291c90-e49d-4047-9d70-0629fda251f8)

**Comment by matmair** [comment]
@JacobEFO Can we close this?
