### ISSUE TITLE
Follow the po files movement on Crowdin

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#7004]
### Body of the issue

I poked now on Crowdin and seen a lot of untranslated strings, however I remembered that the translation progress was quite higher last time. 

It looks that the django.po file is duplicated on crowdin to follow the recent source code restructuring:
![kép](https://github.com/inventree/InvenTree/assets/1609182/90dc170f-aafb-44ac-9fa5-75e43f30377c)

Would it be possible to merge these two po files on crowding automatically?

**Comment by SchrodingersGat** [comment]
Hmm, good question. We really need to deal with this! I'll reach out to the Crowdin support and see if they have any suggestions.

**Comment by matmair** [comment]
@SchrodingersGat there is an option to do this in the backend; let's talk offline about this

**Comment by SchrodingersGat** [comment]
@martonmiklos happy to report that this has been fixed now. Thanks for reporting!
