### ISSUE TITLE
[PUI] Focus on form fields

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7005]
When opening a new form modal, I would like to be able to specify the field to focus on by default. If no field is specified, focus on the first visible field.

It looks like this should be possible with [react-form-hook setFocus](https://react-hook-form.com/docs/useform/setfocus) but I cannot get it working.

@wolflu05 do you have any insights here?

**Comment by wolflu05** [comment]
We need to directly pass the ref to the input instead of destructuring it first (we have to do that for all form field types ignorer for it to work correctly):

```diff
          <TextInput
             {...reducedDefinition}
-            ref={ref}
+            ref={field.ref}
             id={fieldId}
             type={definition.field_type}
```

Then we can utilize the `setFocus` method to set focus after the initial render.
