### ISSUE TITLE
JS translation syntax error (stock-badge in search window)

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#7011]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

the stock/availability-badge icon in the quick-search window seems to have a syntax error in form of a space in the `%}` bracket in

https://github.com/inventree/InvenTree/blob/f4d748ebed95ed204f02688b325c6a665e041287/src/backend/InvenTree/templates/js/translated/model_renderers.js#L221

I have no time for a PR right now - maybe someone wants to pick this up occasionally? Thanks!

### Steps to Reproduce

![Bildschirmfoto vom 2024-04-12 13-57-47](https://github.com/inventree/InvenTree/assets/296454/a3226091-2fa4-486d-924c-c1397a3b72f3)

### Expected behaviour

correctly translated badge text...

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.0 dev
Django Version: 4.2.10
Commit Hash: c827133
Commit Date: 2024-03-18

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-rpi7-rpi-v8-aarch64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'IPNAutoGenerator', 'slug': 'ipnautogenerator', 'version': None}, {'name': 'OrderNotesTemplates', 'slug': 'ordernotestemplates', 'version': None}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.9.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
Thank you for the report @simonkuehling - fix in #7013
