### ISSUE TITLE
[FR] Add the ability to either enter ones own User-Agent strings, or define some generic ones, for the thubnail from link feature to work on certain websites.

### ISSUE THREAD

**Issue by diminDDL** [inventree/InvenTree#7012]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

The feature for adding images from URLs is very useful. However, increasingly websites check for a user agent string before serving any content at all. Because of this you can get a 403 error even though the link opens perfectly fine in your web browser. Example of an LCSC image link and trying to fetch it below:
```python
>>> import requests
>>> url = "https://assets.lcsc.com/images/lcsc/900x900/20221228_Advanced-Monolithic-Systems-AMS1117-3-3_C6186_front.jpg"
>>> r = requests.get(url)
>>> print(r.status_code)
403
>>> headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 uacq'}
>>> r = requests.get(url, headers=headers)
>>> print(r.status_code)
200
>>> 
```

### Suggested solution

Either provide a field in the admin panel to add your own User-Agent/header strings, or include a generic one in the requests that are being issued to fetch the image. (With guidance from the developers on where the logic for this is implemented I can likely be able to add this myself in a short PR).

### Describe alternatives you've considered

One could set up their own script that would fetch the image and present it on the local network for InvenTree to download, but that is not an optimal solution. Also providing User-Agent headers is a good idea in general. In the above test, I can even replace the headers to `headers = {'User-Agent':'InvenTree'}` and it still works for most places.

### Examples of other systems

For example messaging services like Telegram or Discord, as well as tools like wget all fetch the image correctly (embedding/downloading it without any issues). 

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
This is already present in InvenTree, please check the existing settings before requesting features.
