### ISSUE TITLE
Native print support for QR codes

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#709]
Add ability (in the web interface) to print a QR code directly to a label maker / sticker printer.
This might be as simple as passing the QR code to the computer's printer interface and the user selects the printer. Not sure.

- https://github.com/inventree/InvenTree/issues/708
- https://github.com/inventree/InvenTree/issues/677

**Comment by maholli** [comment]
For what it's worth, I use a [Brother PTD600](https://www.amazon.com/Brother-PC-Connectable-PTD600-High-Resolution-Printing/dp/B00OCEKCB2) to print barcodes and labels over USB. Tape widths range from 9mm to (I think) 24mm. Big enough for me to put QR labels on things.

**Comment by a7hybnj2** [comment]
I have a pt-p700 which I like but the software only generates qr codes which does need a pretty wide tape. I would like micro-qr or data-matrix so I could use the smaller tapes.

Maybe I just need to try to print from a different application.

**Comment by rco3** [comment]
I'm fond of my Dymo LabelWriter 450

**Comment by SchrodingersGat** [comment]
support for printing of custom labels is now implemented - #906
