### ISSUE TITLE
[FR] Increase Length of URL limit on import

### ISSUE THREAD

**Issue by motusRP** [inventree/InvenTree#7118]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

See [Discussion 7078](https://github.com/inventree/InvenTree/discussions/7078)

### Suggested solution

Possible options:
- Increase length of URL limit to something greater than 200 (Maybe 300?).
- Make the maximum length adjustable in the Admin settings somewhere.
- Remove the limit and replace it with content validation that validates and then accepts the link regardless of length if it is valid.

### Describe alternatives you've considered

Not much I can do here... If the supplier's or manufacturer's website requires a link longer than 200 characters to link to the part on their site, then the limit isn't high enough.  The only other option would be to run our own URL shortening service and manually shorten any link that's too long on a one-off basis.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
I think extending this is not too problematic. I think 2000 chars should be enough for now, I will submit a patch later tonight.
