### ISSUE TITLE
[FR] Ukrainian language support

### ISSUE THREAD

**Issue by ybilopolov** [inventree/InvenTree#7123]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Would be great to have Ukrainian translation for the app.

### Suggested solution

Author would willingly commit into the process of translation, however Ukrainian is not even listed in the list of languages, available for translation in crowdin.

### Describe alternatives you've considered

There is no clear alternative for potential non-English-speaking Ukrainian users.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
We do not support ukrainian currently as there are no translators for it. I have enabled support on [our translation](https://crowdin.com/project/inventree/uk) platform, please head over there and submit your translations.
