### ISSUE TITLE
Update from v14.2 to v14.3/14.4/14.5

### ISSUE THREAD

**Issue by imager2019** [inventree/InvenTree#7128]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Have version 0.14.2 running with install from Quick Script on Ubuntu 20.04.
Attempting to update from v14.2 to latest version using command  inventree run cli update

Process begins and runs for about two minutes and returns back to prompt with many processes completed.

Upon checking status of Inventree (from About), continues to report version 0.14.2 is running and that it is Up to Date.

### Steps to Reproduce

From Terminal
Enter Su along with password
Enter inventree run cli update

### Relevant log output

```bash
# Version Information:
InvenTree-Version: 0.14.2
Django Version: 4.2.10
Commit Hash: b807e476
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-105-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]
```

**Comment by matmair** [comment]
With package install you only need to run `apt update inventree` to get the newest version that is available on your environment. Maybe the package update is held back by ubunutu?

**Comment by matmair** [comment]
Seems like the package was not build for ubuntu, I have started the CI by hand

**Comment by imager2019** [comment]
Hello. Not sure I understand what you are requesting to do the update.  When I attempt   `apt update inventree`  , I receive the response `The update command takes no arguments`

I believe the command mentioned before for the updates was to run  `inventree run cli update`
And this where the update appears to run, but still stuck on v14.2

Is there a different set of command I should be running to do the update? For backups, I enter the command `inventree run cli update` and backups seem to run fine.

Ideas?

**Comment by matmair** [comment]
Sorry, wrong command `apt upgrade inventree` is the right one. Running the CLI upgrade script (inventree run cli update) is done automatically when the source changes.

**Comment by imager2019** [comment]
Perfect - that worked. System successfully upgraded to v14.5 from v14.2

**Comment by imager2019** [comment]
All working.
Final solution to upgrade from v14.2 to v14.5 with one-line installed version: `apt upgrade inventree`
