### ISSUE TITLE
Unable to allocate stock

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#7137]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

After Cancelling a build order
![image](https://github.com/inventree/InvenTree/assets/130482028/66edd0b4-06a9-438f-b38e-c91479c68b21)

![image](https://github.com/inventree/InvenTree/assets/130482028/ef75962d-3235-432b-bb67-84aac0dc057a)

im not able to allocate stock a new build order:
![image](https://github.com/inventree/InvenTree/assets/130482028/c07dde24-1987-4b87-8c81-3b5fb701f896)

but if i understand correct: than i still have 1377 pcs availeble and require 1125 more. but for some reason i can not allocate them.

coudl you please advice what t check .

and its for many parts not this single item.

### Steps to Reproduce

![image](https://github.com/inventree/InvenTree/assets/130482028/66edd0b4-06a9-438f-b38e-c91479c68b21)

![image](https://github.com/inventree/InvenTree/assets/130482028/ef75962d-3235-432b-bb67-84aac0dc057a)

![image](https://github.com/inventree/InvenTree/assets/130482028/c07dde24-1987-4b87-8c81-3b5fb701f896)

### Expected behaviour

i would expect the 2799 pcs to be availeble:
![image](https://github.com/inventree/InvenTree/assets/130482028/7fc81c50-36ba-4a16-ad4f-f4df0d0326f3)

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.14.5
Django Version: 4.2.11
Commit Hash: b32f081a
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-6.5.0-28-generic-x86_64-with-glibc2.35
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by mabroens** [comment]
To add to this: when i select a part and go for Build ORder Allocations, that page keeps loading data and never finishes.

**Comment by SchrodingersGat** [comment]
@mabroens if I am understanding what you are saying:

![image](https://github.com/inventree/InvenTree/assets/10080325/e0c0248d-e0e3-4be9-a8fb-b3891741aa48)

Selecting "Remove Allocated Stock" when cancelling a build order will actually *remove* that quantity of stock and it will be consumed by the build order. Thus, it will not be available any longer. So, I think that this is simply what has happened here - the quantity of stock has been consumed by the build order during cancellation.

**Comment by SchrodingersGat** [comment]
> To add to this: when i select a part and go for Build ORder Allocations, that page keeps loading data and never finishes.

Can you reproduce this on the demo server?

**Comment by mabroens** [comment]
@SchrodingersGat ai. yes that is what i did but not how i thought it would work.
any way using admin or whatever to revert this?

**Comment by SchrodingersGat** [comment]
You can go to the build order and for each "consumed stock item" you will need to open the admin view and set the "consumed_by" field to null. That *should* be enough to bring those stock items back into the system

**Comment by mabroens** [comment]
Okay but consumed stock is empty:
![image](https://github.com/inventree/InvenTree/assets/130482028/6b327e60-0591-4913-a9b7-019eca674634)

or am i looking at the wrong location??

**Comment by mabroens** [comment]
Also for each part that was in in these buildorders i see:
![image](https://github.com/inventree/InvenTree/assets/130482028/717dbe10-d267-407b-94b5-8d6837287133)

and Build Order Allocations stays on loading: 
![image](https://github.com/inventree/InvenTree/assets/130482028/1f05aec9-e0a4-42ca-87bb-f842421ab66b)

**Comment by SchrodingersGat** [comment]
> and Build Order Allocations stays on loading:

Can you open up the developer console in your browser, and in the "console" tab you will probably see an error message there?

**Comment by mabroens** [comment]
![image](https://github.com/inventree/InvenTree/assets/130482028/c20359d5-0b90-47e8-a811-5b9b63a696f0)
 this what your looking for?

**Comment by SchrodingersGat** [comment]
@mabroens thanks, that was helpful. Bug fix incoming in https://github.com/inventree/InvenTree/pull/7153 which *should* handle most of the issues raised here...

**Comment by mabroens** [comment]
> Okay but consumed stock is empty: ![image](https://private-user-images.githubusercontent.com/130482028/327399840-6b327e60-0591-4913-a9b7-019eca674634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MzExODcsIm5iZiI6MTcxNDgzMDg4NywicGF0aCI6Ii8xMzA0ODIwMjgvMzI3Mzk5ODQwLTZiMzI3ZTYwLTA1OTEtNDkxMy1hOWI3LTAxOWVjYTY3NDYzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxMzU0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDdlNjBkZTUzNzYwZWE2NTllMTk0YmJmYTM0YWM3ZWQ4ODBiNGZmNzdmZDU2ZjZhNGFlMDk0NjZmNmQ2ZTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oy0JeC7QpUwU8cl7ZvbdmGjgfHRVKIkWQh1HZMqWuho)
> 
> or am i looking at the wrong location??

@SchrodingersGat  was this the right location or should i wait for a fix??

**Comment by SchrodingersGat** [comment]
@mabroens found some further issues - https://github.com/inventree/InvenTree/pull/7178
