### ISSUE TITLE
[FR]Allow uploading images by pasting their URL

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#7146]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When I creating parts I usually go out and hunt an image for the part on the internet. 
The current workflow:
- download that image to /tmp 
- browse it in the InvenTree UI

The latest step could need some time if I have multiple images downloaded.

### Suggested solution

Add a lineedit input to the image upload dialog, or handle the paste events and if they start with http:// or https://.
If link provided through either way then automatically download the image and use that.

### Describe alternatives you've considered

Downloading and uploading the images to InvenTree manually.

### Examples of other systems

Google photos search is a good example how it is done.

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@martonmiklos this feature is already available. You need to enable this option:

![image](https://github.com/inventree/InvenTree/assets/10080325/5e0ac50e-90b9-4954-8717-323038f2cab9)

And then:

![image](https://github.com/inventree/InvenTree/assets/10080325/192e5c4f-3c47-4bea-9f9c-c74e00dc023f)

![image](https://github.com/inventree/InvenTree/assets/10080325/6d5d2dc5-01cd-4d73-bb1d-8cdc9825451a)

**Comment by martonmiklos** [comment]
> @martonmiklos this feature is already available. You need to enable this option:
> 

Thanks! Next time I will take a look on the settings not just the existing issues 😆
