### ISSUE TITLE
Stock Level (from Remove Stock option) Displays Stock #

### ISSUE THREAD

**Issue by imager2019** [inventree/InvenTree#7149]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

From the Stock menu option and selecting the item(s) and Remove Stock option. The Stock level displays a # sign
However, some other products (noticed today with a new recently added item), displays the correct stock level.
![stock-level-issue](https://github.com/inventree/InvenTree/assets/49574724/2031b25f-54b2-4346-a782-d66293c0b349)

### Steps to Reproduce

From Stock menu option
Select item(s)
Select Remove Stock option
Display will show items along with current stock levels, or # if it cannot display

### Expected behaviour

Expected to have stock level displayed.

Some products (seems to be newer added items) have the correct stock level displayed.

### Deployment Method

- [ ] Docker
- [X] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.14.5
Django Version: 4.2.11
Commit Hash: b32f081a
Commit Date: None
Commit Branch: stable
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-105-generic-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@imager2019 thanks for reporting - fix incoming in https://github.com/inventree/InvenTree/pull/7150

**Comment by imager2019** [comment]
Had the opportunity to update to v0.15.4 and the same issue is still there. Old stock entries still show # while new entries show correct stock levels.
Version Information as of now:

==============
# Version Information:
InvenTree-Version: 0.15.4
Django Version: 4.2.12



Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-107-generic-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

**Comment by SchrodingersGat** [comment]
Have you done a hard refresh of your browser to ensure that the old cached javascript files are removed?

**Comment by imager2019** [comment]
Did the hard refresh on the browser and this has solved the issue. Working as intended on my side now.. Thanks..
