### ISSUE TITLE
[FR] Consume full supplier parts

### ISSUE THREAD

**Issue by DanielDango** [inventree/InvenTree#7155]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I would like to consume full stock items but still keep track of the actual packaging size. 
I have variants of parts that can be supplied in different amounts of different sized packs. The total stock is modeled accurately by using pack quantities. When removing stock I would like to conveniently extract an entire package. 

_For example: 
Water can be either 6 * 1.5 l, 12 * 0.7 l or 12 * 1 l.
When taking a single (one) bottle of water, I want to remove exactly one from the corresponding variants stock._

### Suggested solution

Implement a separate field where you can consume full supplier parts instead of the tracked unit. 
This could also be a feature that is toggled persistent and somewhere central. Like switching between free (any amount) and restricted (full parts) to avoid clutter in the UI.

Even better: Split Supplier Part Units into unit and minimal consumable unit-> "Supplier Part has 42 unit in pieces of 0.1 unit" 
This could allow minimal consumable units to be set. When removing stock, the amount can be set in multiples of the minimal consumable unit. 
The default minimal consumable unit (empty) should probably mean that stock can be subtracted without restrictions.

### Describe alternatives you've considered

My current way of doing this is by keeping track of bottles instead of contents. This means I can not easily check how much stock is actually left. 
_Taking the numbers from my example, if I set my minimum stock to 10 I might be down to 7 l or still have 15 l remaining. This means on average I will have more buffer stock than actually needed._
A viable alternative would be to keep proper track of the physical units instead. However when taking a smallest unit I need to enter the actual physical amount which takes far more time / concentration especially for larger quantities of stock removed.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
I suppose this might be possible - the *StockItem* object retains information about the *SupplierPart* it is linked to, so the "pack quantity" data is available. This would likely require a fair bit of user interface work too.

@DanielDango would you be interested in developing this?

**Comment by DanielDango** [comment]
I have no prior experience with ui work and it would probably take a while to get worked in. To be honest I am not to keen on putting in that time right now.
