### ISSUE TITLE
Lack of IPv6 support

### ISSUE THREAD

**Issue by elspru** [inventree/InvenTree#7175]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

inventree-server only listens on ipv4 because guinicorn is -b 0.0.0.0:8000
and I use a reverse proxy caddy on a cheap VPS and host my actual services at home to cut down on VPS costs. 
for it to listen on ipv6 it needs to be:
CMD gunicorn -c ./gunicorn.conf.py InvenTree.wsgi -b [::]:8000 --chdir ./InvenTree
But yeah I did that and then realized that you don't just use your Caddyfile for SSL but also for static file hosting, 
and caddy is just like so hyper SSL that it wont do like regular http. 

So I needed to replace the caddy proxy with nginx

    inventree-proxy:
        container_name: inventree-proxy
        image: nginx:alpine
        restart: always
        command: /bin/sh -c "mkdir -p /var/log/nginx && nginx -g 'daemon off;'"
        depends_on:
            - inventree-server
        expose:
          - 80
            #ports:
            #    - ${INVENTREE_WEB_PORT:-80}:80
            # Uncomment the next line if you need to enable HTTPS on this server
            # - 443:443
        env_file:
            - .env
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z
        networks:
          default:
          proxy:
            ipv6_address: "$CPREFIX:ea09:a92b"

and put in an nginx.conf
    inventree-proxy:
        container_name: inventree-proxy
        image: nginx:alpine
        restart: always
        command: /bin/sh -c "mkdir -p /var/log/nginx && nginx -g 'daemon off;'"
        depends_on:
            - inventree-server
        expose:
          - 80
            #ports:
            #    - ${INVENTREE_WEB_PORT:-80}:80
            # Uncomment the next line if you need to enable HTTPS on this server
            # - 443:443
        env_file:
            - .env
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_EXT_VOLUME}:/var/log:z
            - ${INVENTREE_EXT_VOLUME}:/data:z
            - ${INVENTREE_EXT_VOLUME}:/config:z
        networks:
          default:
          proxy:
            ipv6_address: "$CPREFIX:ea09:a92b"

### Steps to Reproduce

curl the ipv6 address of the invertree server and it rejects it

### Expected behaviour

that I can setup my own simple caddy proxy on the vps host, and that invetree will be a well behaved simple http app like pretty much everyone else makes. 

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

used the stable version

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
logs shmogs it works now with my mods
```

**Comment by matmair** [comment]
1. caddy support http fine if configured by passing a http site url instead of https
2. Thank you for your pointing out how well behaved apps work - I look forward to your PR making inventree well behaved

**Comment by elspru** [comment]
Well I couldn't get caddy to return anything from a curl request when it was setup even with http.

but yeah now I'm having a strange issue where I've defined the parts, and the locations. but when I try to add new stock, it says it can't find any parts, so I'm not able to add any stock.

what I'm getting from my log is:
2602:fcd3:102:a884::e7f3 - - [07/May/2024:10:59:46 +0000] "GET /api/part/?virtual=false&offset=0&limit=25 HTTP/1.0" 200 52 "https://lwat.liberit.ca/stock/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
2602:fcd3:102:a884::e7f3 - - [07/May/2024:10:59:48 +0000] "GET /api/part/?virtual=false&offset=0&limit=25 HTTP/1.0" 200 52 "https://lwat.liberit.ca/stock/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"[Screenshot 2024-05-07 at 07-04-04 InvenTree Stock.png][Screenshot 2024-05-07 at 07-04-28 InvenTree Stock Location - 1138 3rd Ave West_West Greenhouse_Top Bench_Tray 1 -.png][Screenshot 2024-05-07 at 07-03-42 InvenTree Part List.png]

please help I donno what to do.
can't really use it if I can't add stock.
is this is a common issue or could it be related to the proxying somehow?

--

Andrii (Logan) Zvorygin,
Lyis Food Forestry https://lyis.caGlobal Distributist https://distributist.org
LiberIT Liberty Information Technology Services http://liberit.ca

We All are One Being https://1being.org
Encrypted email key fingerprint: BABA 36D9 8956 A9EA 0C5E ([pubkey](https://keys.openpgp.org/vks/v1/by-fingerprint/67190E17BEE5026A01CFBABA36D98956A9EA0C5E))
I am a piece of dust, on a planet, in a vast cosmos, within One Infinite Creation.
If you don't like receiving emails from me, please respond to this email with "Unsubscribe" as the first word of the email.
As I found you, I leave you glorying in the love and in the light of the One Infinite Creator. Go forth therefore rejoicing in the Power and in the Peace of the One Infinite Creator.

**Comment by elspru** [comment]
whoops sorry it seems I was making subcategories instead of parts
sorry about that. got it all sorted out.
have a great day!

--

Andrii (Logan) Zvorygin,
Lyis Food Forestry https://lyis.caGlobal Distributist https://distributist.org
LiberIT Liberty Information Technology Services http://liberit.ca

We All are One Being https://1being.org
Encrypted email key fingerprint: BABA 36D9 8956 A9EA 0C5E ([pubkey](https://keys.openpgp.org/vks/v1/by-fingerprint/67190E17BEE5026A01CFBABA36D98956A9EA0C5E))
I am a piece of dust, on a planet, in a vast cosmos, within One Infinite Creation.
If you don't like receiving emails from me, please respond to this email with "Unsubscribe" as the first word of the email.
As I found you, I leave you glorying in the love and in the light of the One Infinite Creator. Go forth therefore rejoicing in the Power and in the Peace of the One Infinite Creator.
