### ISSUE TITLE
Stock Status prevents stock transfers

### ISSUE THREAD

**Issue by LastEdit** [inventree/InvenTree#7188]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

After changing the stock status of a stock item to one of the non-available types, it prevents transfer of location of that stock item.

[Status types](https://docs.inventree.org/en/stable/stock/status/#stock-status)

### Steps to Reproduce

1. Change stock status to Destroyed, Lost, Rejected, Quarantined.
2. Try to transfer stock to another location.
3. Get error (Form errors exist StockItem cannot be moved as it is not in stock)

### Expected behaviour

I would expect the availability status of a stock item for sale/builds to not affect the ability to transfer locations of that item.

I would expect to be able to move stock in the Rejected or Quarantined status since they are still physical stock.

I would imagine Destroyed or Lost stock should be able to be moved out of a location for stock take purposes.

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.14.5
Django Version: 4.2.11
Commit Hash: b32f081
Commit Date: 2024-04-18

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-105-generic-x86_64-with
Installer: DOC

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
This behaviour is intended IMO

**Comment by SchrodingersGat** [comment]
I have just noticed this recently actually. You cannot move a "quarantined" or "destroyed" stock item between locations, which is super annoying. I think that this should be possible.

This is somewhat related to the [custom stock status](https://github.com/inventree/InvenTree/issues/4289) issue, although I think that is much more complex and nuanced issue.

For this one, I think it would be sufficient to allow transfer of "out of stock" items - even if it is behind a configurable setting. It was on my list of tasks to look into this, I think that is a sufficiently low-hanging fruit.

**Comment by SchrodingersGat** [comment]
@LastEdit see https://github.com/inventree/InvenTree/pull/7194

**Comment by LastEdit** [comment]
@SchrodingersGat Thank you for looking into this and the quick resolution
