### ISSUE TITLE
Unable to create the Incomplete output in Build Order

### ISSUE THREAD

**Issue by Jaishankar872** [inventree/InvenTree#7192]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Unable to create the new build output. while click the incomplete output option site through error as Bad request 400

### Steps to Reproduce

1. Click the Build in top 
2. Select the Build Order
3. Just click the Incomplete output

![image](https://github.com/inventree/InvenTree/assets/45547294/af6ff32e-9913-4ddd-a8ed-ae4eb0c17ef0)

### Expected behaviour

Unable to understand

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.14.5
Django Version: 4.2.11
Commit Hash: b32f081
Commit Date: Apr 18 2024

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.5.0-28-generic-x86_64-with
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
172.18.0.1 - - [09/May/2024:15:25:55 +0000] "GET /api/notifications/?read=false HTTP/1.0" 200 2 "https://-----------/build/2/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0"
Bad Request: /api/part/test-template/
```

**Comment by SchrodingersGat** [comment]
If you look in the "network" tab of the developer console in your browser, you should be able to see what the actual error message is for the `400` request. This will be very helpful in working out what is going on here.

**Comment by Jaishankar872** [comment]
Below refer below the logs from web browser 

![image](https://github.com/inventree/InvenTree/assets/45547294/8b73efe5-686b-45fb-9c5b-eab209595351)
 
![image](https://github.com/inventree/InvenTree/assets/45547294/acd135ac-9c0e-4570-881c-6c934b955fa7)

**Comment by SchrodingersGat** [comment]
@Jaishankar872 thanks, but I do need to see the "Response" tab as shown here:

![image](https://github.com/inventree/InvenTree/assets/10080325/01323b57-b0a6-4d80-9c7b-aeffced84280)

Please blank out any sensitive information that may be returned there.

**Comment by Jaishankar872** [comment]
"Response" tab 

![image](https://github.com/inventree/InvenTree/assets/45547294/a7b3b9bf-16bc-4928-a8c6-efecd7498ea2)

**Comment by SchrodingersGat** [comment]
Ok, thanks. And what data was in the "request" tab?

**Comment by Jaishankar872** [comment]
Nothing in request tab

![image](https://github.com/inventree/InvenTree/assets/45547294/79ea2f1f-bca0-49a3-9aae-d2b0e4fddc06)

**Comment by SchrodingersGat** [comment]
Ok..

If you navigate to `/part/365/` - is this part marked as "trackable"?

**Comment by Jaishankar872** [comment]
No, It is not marked as trackable
![image](https://github.com/inventree/InvenTree/assets/45547294/6bd150b8-477d-4e9f-9a97-4514f25f0a1a)

**Comment by SchrodingersGat** [comment]
Ok, then that is why the request is failing - it is trying to receive test results for a non-trackable part.

Fix incoming in https://github.com/inventree/InvenTree/pull/7196

**Comment by Jaishankar872** [comment]
Yes, It is working now.
Thanks for your support !!!!!!!!!!
