### ISSUE TITLE
[FR] Searching for PN with only alphanumeric characters

### ISSUE THREAD

**Issue by LastEdit** [inventree/InvenTree#7199]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Allow searching PNs (IPN,Mfg,Supplier) with only alphanumeric characters, ignoring things like `- / \ _ " " ,` etc. 

This would allow for a simpler user interface when typing in PNs that have those characters or when supplier/mfg PNs don't have consistent use of those symbols. 

### Suggested solution

Specifically for PNs, add additional db columns with stripped PNs and search against new columns. Have search remove characters before making query.

### Describe alternatives you've considered

Search against the original database and automatically place regex between all characters in PN query so unknown to user. Such as `[^a-zA-Z0-9_]*`, but potential database performance hit.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@LastEdit regex search is already an available option:

![image](https://github.com/inventree/InvenTree/assets/10080325/7d624c59-62ae-4d92-8f1e-2034e83aa027)

And there's a drop-down option in the new interface:

![image](https://github.com/inventree/InvenTree/assets/10080325/5dfb7a02-eece-4c60-90f9-056eb9d44f66)

**Comment by LastEdit** [comment]
@SchrodingersGat Doesn't regex search require the user to input the expression manually into the search bar? I was looking for a more behind the scenes ability to ignore the specific characters during search.

**Comment by SchrodingersGat** [comment]
I do not want to make the regex search support any more complex than it already is - if you want to use regex, which is already supported, then go for it! But I think any further complications will make the experience more difficult for everyone.

**Comment by matmair** [comment]
I am with @SchrodingersGat on this one - making the regex search more complex ought to introduce bugs again. Additionally, regex opens up a whole class of security headaches against which the current implementation was tested but new stuff would have to be checked again.
