### ISSUE TITLE
Data importing

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#72]
- csv / excel / etc
- For each import, also provide downloadable 'template' which can be filled in
- "Guess" at fields if there is a discrepancy

**Comment by james-currawong** [comment]
In the case of BOM import, automatically (with user confirmation) do one of the following for each line:

- Match existing part
- Ask user to specify part (if ambiguous)
- Create new part

**Comment by SchrodingersGat** [comment]
BOM import implemented in https://github.com/inventree/InvenTree/pull/411
