### ISSUE TITLE
Stock Count Calculation

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#723]
Something isn't calculating correctly with stock counts. When I see and item in a list it has one stock count but when you click on that item a different stock count is displayed.

<img width="359" alt="Screen Shot 2020-04-13 at 5 19 11 PM" src="https://user-images.githubusercontent.com/36831279/79162315-0f6e7c00-7dab-11ea-8d88-e351c5c7a91b.png">
<img width="1336" alt="Screen Shot 2020-04-13 at 5 19 03 PM" src="https://user-images.githubusercontent.com/36831279/79162320-10071280-7dab-11ea-972c-23ef00935ad4.png">

These are the same part just viewing the count from different locations. One is 7k+ and the other is 3k+.

<img width="1198" alt="Screen Shot 2020-04-13 at 5 22 18 PM" src="https://user-images.githubusercontent.com/36831279/79162479-59576200-7dab-11ea-9848-58c4da55253d.png">

**Comment by SchrodingersGat** [comment]
This is a strange one. Can you confirm which number is correct?

**Comment by a7hybnj2** [comment]
The 3k value is the correct one.

**Comment by SchrodingersGat** [comment]
Ok, turned out that was a very deep rabbit hold to get lost in. However the problem should be fixed now. Please confirm that it works on your end!

**Comment by a7hybnj2** [comment]
Great! I was just about to update and test but then I saw #743. I will keep an eye on #743 and as soon as I get the go ahead I will update and check it.

**Comment by a7hybnj2** [comment]
@SchrodingersGat just updated and it is displaying the correct quantity for my parts. Yip! Did you change the parts stock tab? I feel like it used to provide more information without clicking on it.

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat just updated and it is displaying the correct quantity for my parts. Yip! Did you change the parts stock tab? I feel like it used to provide more information without clicking on it.

I do not think I changed the stock tab - can you share a screenshot to show what you mean?
