### ISSUE TITLE
Add `copy version information` button

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#725]
Add a button to the `InvenTree Version Information` window that copies all important data to the paste buffer for easier supplying that info on bug reports/issues. Or, format that window where it can be copied and pasted because when I do it now it looks like this:
```

  | Instance Name | 1e8f50a4e38e49969ec510f2f5dc91c1
-- | -- | --
 

```

<img width="1151" alt="Screen Shot 2020-04-13 at 5 26 31 PM" src="https://user-images.githubusercontent.com/36831279/79162833-f0241e80-7dab-11ea-808d-56ebf23d4e28.png">

the screen shot is what was selected when I hit copy.

**Comment by SchrodingersGat** [comment]
Nice idea. It would a perfect one to contribute if you were able to :)

**Comment by a7hybnj2** [comment]
Maybe I will take a look. I poked around the code before and was completely lost.

**Comment by SchrodingersGat** [comment]
The about dialog is handled here:

https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/about.html

If there are any other contributions you want to make, and you want me to point you in the right direction, please let me know. I'd be more than happy to assist.

**Comment by SchrodingersGat** [comment]
@a7hybnj2 did you want me to assign this to you?

**Comment by eeintech** [comment]
May be related to https://github.com/inventree/InvenTree/issues/997

**Comment by matmair** [comment]
@SchrodingersGat @eeintech I finished the work on this, should be maybe add something about the deployment method?

**Comment by SchrodingersGat** [comment]
> should be maybe add something about the deployment method?

What exactly do you mean here?

**Comment by matmair** [comment]
> 
> 
> > should be maybe add something about the deployment method?
> 
> What exactly do you mean here?

If the installation uses docker (and if it is in development or production) or is setup manually. Maybe also if MySQL is used - that sometimes causes problems with search / filtering.

**Comment by SchrodingersGat** [comment]
Ah I see, yes that is a good idea. How can you determine at run-time if docker is being used?

I would like to see, as additions to the "System Information" dialog:

- Database backend
- Is the server running in debug mode?
- running in docker or bare-metal? (If this can be determined)

**Comment by SchrodingersGat** [comment]
See https://github.com/inventree/InvenTree/pull/1583

I have added database engine and debug mode

**Comment by matmair** [comment]
I will think about how do detect docker, maybe an enviroment-variable set in the docker-file and read by the settings.py?
