### ISSUE TITLE
Plugin settings do not work

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#7254]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The settings of all plugins result in error messages like

No Response
No response from the InvenTree server
URL: /api/plugins/settings/suppliercart/MOUSER_PK/

Error 404: Resource Not Found
The requested resource could not be located on the server
URL: /api/plugins/settings/inventreelabel/DEBUG/

### Steps to Reproduce

Go to settings->plugins
Tra to change a setting

### Expected behaviour

As in the past :-)

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

0.16.0 dev
351701e
ubunto 2204

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

### Relevant log output

```shell
[17/May/2024 07:31:07] "GET /api/notifications/?read=false HTTP/1.1" 200 2
Not Found: /api/plugins/settings/zebra/CONNECTION/
Not Found: /api/plugins/settings/zebra/CONNECTION/
[17/May/2024 07:31:14] "GET /api/plugins/settings/zebra/CONNECTION/ HTTP/1.1" 404 110
```

**Comment by matmair** [comment]
Could this be partially because of https://github.com/inventree/InvenTree/pull/7224

**Comment by SchrodingersGat** [comment]
@SergeoLacruz thanks for reporting, can confirm that this is a bug, caused by #7224
