### ISSUE TITLE
Version shown as 0.15.2 but apt shows 0.15.1

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#7269]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I've got 0.15.1 installed and did a ```apt dist-upgrade``` today. 

```Unpacking inventree (0.15.1-1716160500.af3cf62b.focal) over (0.15.1-1715729109.be3b22ce.focal)```

So a later version of 0.15.1 was installed however if I do a About Inventree it shows 0.15.2 is installed.

### Steps to Reproduce

1. Upgrade to latest apt package  ```sudo apt dist-upgrade```

### Expected behaviour

Latest tag is 0.15.1 so version should show 0.15.1 instead of 0.15.2

### Deployment Method

- [ ] Docker
- [X] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.2
Django Version: 4.2.12

Database: mysql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-182-generic-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
user@inventree-clone:~$ sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
Get more security updates through Ubuntu Pro with 'esm-apps' enabled:
  libpython3.9-minimal libpython3.9-stdlib libpython3.9 python3.9
  python3.9-dev python3.9-minimal libpython3.9-dev python3.9-venv
Learn more about Ubuntu Pro at https://ubuntu.com/pro
The following packages will be upgraded:
  inventree
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 64.5 MB of archives.
After this operation, 4,096 B disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 https://dl.packager.io/srv/deb/inventree/InvenTree/0.15.x/ubuntu 20.04/main amd64 inventree amd64 0.15.1-1716160500.af3cf62b.focal [64.5 MB]
Fetched 64.5 MB in 6s (10.5 MB/s)
(Reading database ... 89097 files and directories currently installed.)
Preparing to unpack .../inventree_0.15.1-1716160500.af3cf62b.focal_amd64.deb ...
Unpacking inventree (0.15.1-1716160500.af3cf62b.focal) over (0.15.1-1715729109.be3b22ce.focal) ...
Setting up inventree (0.15.1-1716160500.af3cf62b.focal) ...
# Setting base environment variables
# Using existing config file: /etc/inventree/config.yaml
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/opt/inventree/.github/requirements.txt'
/opt/inventree/contrib/packager.io/functions.sh: line 96: jc: command not found
# Collected environment variables:
#    INVENTREE_MEDIA_ROOT=
#    INVENTREE_STATIC_ROOT=
#    INVENTREE_BACKUP_DIR=
#    INVENTREE_PLUGINS_ENABLED=
#    INVENTREE_PLUGIN_FILE=
#    INVENTREE_SECRET_KEY_FILE=
#    INVENTREE_DB_ENGINE=
#    INVENTREE_DB_NAME=
#    INVENTREE_DB_USER=
#    INVENTREE_DB_HOST=
#    INVENTREE_DB_PORT=
# Getting the IP address of the server via web service
IP address is 86.142.8.50
# Setting up python environment
Requirement already satisfied: invoke in ./env/lib/python3.9/site-packages (2.2.0)
Requirement already satisfied: wheel in ./env/lib/python3.9/site-packages (0.43.0)
# Stopping nginx
# Setting up nginx to /etc/nginx/sites-enabled/inventree.conf
# Starting nginx
# (Re)creating init scripts
Nothing to do.
Nothing to do.
# Enabling InvenTree on boot
# Admin data already exists - skipping
# Stopping InvenTree
# Updating InvenTree
```

**Comment by SchrodingersGat** [comment]
Our latest release is [0.15.1](https://github.com/inventree/InvenTree/releases/tag/0.15.1) so I am not sure why the installer has built against 0.15.2 - @matmair any ideas on this?

**Comment by StormTrooper** [comment]
Another update this morning which has fixed the issue. Back to 0.15.1

```
Unpacking inventree (0.15.1-1716272465.be3b22ce.focal) over (0.15.1-1716160500.af3cf62b.focal) ...
Setting up inventree (0.15.1-1716272465.be3b22ce.focal) ...
```

**Comment by matmair** [comment]
I have re-triggered all builds so that might have fixed it

**Comment by matmair** [comment]
So we can close this @StormTrooper ?
