### ISSUE TITLE
pip errors when running `make install`

### ISSUE THREAD

**Issue by rrakso** [inventree/InvenTree#728]
Hi! I have some errors when trying to install InvenTree on _fresh ubuntu 18.04_ instalation.
The first one is
`error: invalid command 'bdist_wheel'`
to fix it I ran
`pip install wheel`

Second one is
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
to fix it I need to run
`sudo apt install g++`, but then I got 
`fatal error: Python.h: No such file or directory`
so I need to install **python3-dev** packgage
`sudo apt install python3-dev`

I hope this help someone! :smile:

**Comment by SchrodingersGat** [comment]
Thanks for this - I will make sure the documentation is updated to match!
