### ISSUE TITLE
Stockitems can be overallocated

### ISSUE THREAD

**Issue by HannesMorre** [inventree/InvenTree#7285]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

It is possible to allocate a single stock item twice on the same build order when that part appears twice in the BOM. This messes up the available stock numbers and even more when the BOM is changed.

![image](https://github.com/inventree/InvenTree/assets/71696745/b1ebf62a-5394-4995-8168-5f210c08e196)

If this happens and the BOM is changed to merge the 2 lines of the same part, then the build order changes and the stock that was allocated to the line in the BOM that is now deleted is allocated to "None" instead, thus it cannot be unallocated.

### Steps to Reproduce

1. create a "component" part
2. create an "assembly" part
3. add a stock item for the component part
4. add the component part to the BOM of the assembly part twice
5. create a build order for teh assembly part
6. click on "allocate stock" to open the stock allocation panel for all build lines
7. allocate the same stock item to both build lines

### Expected behaviour

do not allow to overallocate a stock item 

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [X] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.14.4
Django Version: 4.2.11
Commit Hash: 35fc954
Commit Date: 2024-03-22

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.4.0-167-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'SupplierCart', 'slug': 'suppliercart', 'version': '0.4.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@HannesMorre looking into this it appears that both these issues have been addressed in version 0.15.x

Can you please try to update and see if the problem persists, or otherwise see if you can reproduce the issue on the demo server
