### ISSUE TITLE
[PUI] Date Input Rendering Issue

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7289]
Noticed an issue with date input field rendering in PUI:

![image](https://github.com/inventree/InvenTree/assets/10080325/78d48dbd-6b5c-4055-8d1a-7c4b6de04033)

**Comment by SchrodingersGat** [comment]
This seems to have been fixed now

**Comment by wolflu05** [comment]
Yes, I have fixed that with one of my last PRs. The Stylesheet for the date package was missing when migrating to mantine v7

**Comment by SchrodingersGat** [comment]
Awesome, thanks for that @wolflu05
