### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by HamzaF-m** [inventree/InvenTree#7304]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

getting 502 bad gateway, I'm not quite sure why but its happening ever since the OS got updated, please let me know on how i can resolve this

### Steps to Reproduce

N/A

### Expected behaviour

N/A

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

not quite sure what Inventree version i have 

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Do you have any log files from the installation process?

You might be having similar issues to these people:

- https://github.com/inventree/InvenTree/issues/6349
- https://github.com/inventree/InvenTree/issues/7246

**Comment by SchrodingersGat** [comment]
Ref: https://github.com/inventree/InvenTree/discussions/7336

**Comment by matmair** [comment]
@HamzaF-m can you confirm this was resolved by the latest update?

**Comment by HamzaF-m** [comment]
Yes, This issue has been resolved, I was able to fix this by updating the repo, also i had to make a little change in the config file of both Inventree and ngnix, the local host value i.e. 127.0.0.1.
