### ISSUE TITLE
[PUI] Implement status change buttons for orders

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7306]
- Ref: https://github.com/inventree/InvenTree/pull/7305
- Order detail pages currently do not let user change status of order

### Build Order

- Complete
- Cancel order

### Purchase Order

- Receive items
- Complete order
- Cancel order

### Sales Order

- Ship items
- Mark as shipped
- Mark as complete
- Cancel order

### Return Order

- Receive items
- Complete order
- Cancel order

**Comment by LavissaWoW** [comment]
@SchrodingersGat State transitions coming with #6989
