### ISSUE TITLE
502 bad gateway (somehwat different issues than others have raised)

### ISSUE THREAD

**Issue by xkalamity** [inventree/InvenTree#7326]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I'm incredibly new to this linux thing, but ran the install script and seemed to have no issues. however I get a 502 bad gateway when i go to the local host page. followed along with issue 7246, I uncommented the site_url in the /etc/inventree/config.yaml file (see below). I checked the web-service-1 log and got the below issue. System has been restarted as well post-yaml change. I realize there's lots of others dealing with this issue so hopefully my situation can provide some clarity

### Steps to Reproduce

"#"Base URL for the InvenTree server
"#"Use the environment variable INVENTREE_SITE_URL
site_url: 'http://localhost:8000'

### Relevant log output

```bash
May 23 14:24:08 SRVOTTINVTREE systemd[1]: Started inventree-web-1.service.
May 23 14:24:10 SRVOTTINVTREE inventree-web-1.service[939]: Python version 3.9.5 - /opt/inventree/env/bin/python3.9
May 23 14:24:10 SRVOTTINVTREE inventree-web-1.service[939]: 2024-05-23 14:24:10,827 ERROR No CSRF_TRUSTED_ORIGINS specified. Please provide a list of trusted origins, or specify INVENTREE_SITE_URL
May 23 14:24:10 SRVOTTINVTREE systemd[1]: inventree-web-1.service: Main process exited, code=exited, status=255/EXCEPTION
May 23 14:24:10 SRVOTTINVTREE systemd[1]: inventree-web-1.service: Failed with result 'exit-code'.
May 23 14:24:11 SRVOTTINVTREE systemd[1]: inventree-web-1.service: Scheduled restart job, restart counter is at 1.
```

**Comment by SchrodingersGat** [comment]
Ref: https://github.com/inventree/InvenTree/discussions/7336

**Comment by SchrodingersGat** [comment]
@xkalamity thanks for reporting. we are looking into this and hope to have a resolution for everyone soon

**Comment by SchrodingersGat** [comment]
@xkalamity from your logs it looks like the `INVENTREE_SITE_URL` is not actually being set. How are you specifying this value?

**Comment by xkalamity** [comment]
@SchrodingersGat 

I am using the config.yaml file, and using the default localhost address given in the config.

**Comment by SchrodingersGat** [comment]
> I am using the config.yaml file,

Can you clarify the exact location of the file you are editing?

Also please note that we have just releaesd an update to hopefully fix the installer issues. Please try reinstalling / updating the setup

**Comment by SchrodingersGat** [comment]
@xkalamity awesome thanks for letting us know.
