### ISSUE TITLE
[FR] Build orders linking to multiple Sales Order Reference

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#7334]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

as a user i would like to be able to link a single Build Order with multiple Sales Orders.
suppose you sell 15 products to 5 customers but, ther's no stock. then i'd like to create a build order for 15 or more products but link them to the 5 sales orders. currently this can only be one.
![image](https://github.com/inventree/InvenTree/assets/130482028/fa9b4ddc-267e-44ba-a33e-f6d41604cd56)

### Suggested solution

ad ability to select multiple sales orders. or from the sales order link to the build/buy order.
![image](https://github.com/inventree/InvenTree/assets/130482028/50dcff14-292c-4cfd-ad6a-2e8ca3334fe0)
 which probably is easier to implement.

### Describe alternatives you've considered

none currently

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Implementing this would be somewhat difficult given the current data structure, and the workflow for making new stock (via a build order) would be vastly complicated if it could be created / updated from multiple sales orders simultaneously.

I would suggest that if you need to add more quantity to a build order, the "to build" quantity can be adjusted after it is created.

And the "notes" field can be filled with any data linking to multiple sales orders if required...

Any further custom functionality I think would be a good target for a custom plugin, but not core functionality.
