### ISSUE TITLE
[PUI] BOM Validation

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7358]
Implement BOM validation features to the PUI interface:

- Display if a BOM is invalid (not validated)
- Add UI elememnts to validate
- Display which BOM lines are validated
- Filter by validated / invalidated lines

**Comment by mredpath2** [comment]
Not sure if this should be a separate issue. But I would like to see BOM items be invalidated if the manufacturer or supplier data changes.

The motivation for this is when the same part is used in multiple BOMs, it is easy to update the manufacturer details to satisfy one assembly but this should invalidate the other parts that also depend on that BOM item. Especially when working with other people and you aren't aware of the changes happening under the hood.

I would be happy to have a go at implementing this if you agree with this logic.

**Comment by SchrodingersGat** [comment]
@mredpath2 the scope for this issue is just to re-implement existing functionality to the new interface.

For new ideas, specifically around BOM versioning, refer to [this issue](https://github.com/inventree/InvenTree/issues/5028).

Happy to discuss, and sounds like a good idea. I would like to expose this functionality to the plugin system to allow custom logic that is not tied to core InvenTree code.

**Comment by SchrodingersGat** [comment]
This has now been implemented
