### ISSUE TITLE
Unable to change Pack Quantity for part

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#7363]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

i was trying to change the default pack quantity an/or packaging for a part using `Edit Supplier Part`
![image](https://github.com/inventree/InvenTree/assets/130482028/f99f8289-31a3-4e8d-8574-772567e533ac)

but the form errors exist:
![image](https://github.com/inventree/InvenTree/assets/130482028/3931ef8c-ec9e-42c9-9d1d-62cf962de460)

clearing Packaging doe snot help or making qty empty or 1 also fails

### Steps to Reproduce

go edit supplier part
change Pack Quantity 

### Expected behaviour

to take the new value

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.2
Django Version: 4.2.12

Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-6.5.0-35-generic-x86_64-with-glibc2.35
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@mabroens do you have a custom unit set for the "part" which this "SupplierPart" is linked to?
