### ISSUE TITLE
ADD  next stock item status 

### ISSUE THREAD

**Issue by czkapitan2** [inventree/InvenTree#7372]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Hi guys , we just try to use Inventree as spare part  stock management system for our training devices,  According to our operation we have spares  we mount to device . We created 2 locations for each training  device  ( one for stock and one for device itself )  but when we move the item  from stock location to device , the number of "OK" stock item is logically the same because  from Invetnree point of view  the item was just moved from location to location in one stock.  We try to set "mounted"  part as "LOST" but still in device loaction and numbers of  OK parts decreased . SO this solution woudlk be nice - is it possible to add "MOUNTED "  status of item ? and is  it possible to do not count this item as stock OK part ?       

### Suggested solution

 is it possible to add "MOUNTED "  status of item ? and is  it possible to do not count this item as stock OK part ?       

### Describe alternatives you've considered

As another solution would be implementation of special locations , which locations that would not count towards inventory.   It would be possible to browse them, but not count them to parts/item witch  OK status in stock.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by wolflu05** [comment]
Hi @czkapitan2 , adding lots of different status codes requested by users for their niche use would accumulate a long list where nobody knows what status code means what and should be used for what. Some users event don't need such statues and adding this would clutter the list.
But there is already a feature request for custom stock statuses where users can say count or not count each status as stock. (#4289). If that is implemented, I think your particular use case can be easily covered.

**Comment by czkapitan2** [comment]
Yes - thank you very much @wolflu05 for direction. I agree - this should be   "clear" solution of my problem . Thank you for info !!!! I will continue  with disussion on ISSUE #4289 . Have a nice day .
