### ISSUE TITLE
[Installer] Add python version option at runtime

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7377]
- Currently python version can be set with an environment variable
- Should we expose it as a runtime flag for the installer?
- Similar to `SOURCE` and `PUBLISHER` flags
- Ref: https://github.com/inventree/InvenTree/issues/7375

**Comment by matmair** [comment]
Simply adding support to pass anything will not ensure it works. Multiple footguns would need fixing:
- re-running the installer with a different python version will bork your instance in interesting  and unpredictable ways (not fully sure why, pinning was a reliable fix)
- customised environment installs (not in requirements or plugins) will need to transfer with updates to keep instances running - this is the main reason it is fixed right now
- some sort of validation that the passed version is actually accessible on the OS and supported by InvenTree would be needed

**Comment by matmair** [comment]
This keeps coming up - I will patch the installer to just stop if the configured/detected python version is not found
