### ISSUE TITLE
Adding INR currency gives 502 Bad Gateway error

### ISSUE THREAD

**Issue by masteradit** [inventree/InvenTree#7384]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When I added INR in the`INVENTREE_CURRENCIES` list and restarted the server, it started giving 502 Bad Gateway.

### Steps to Reproduce

1. Install Inventree using the installer.
2. Run `inventree config:set INVENTREE_CURRENCIES=INR`.
3. Run `systemctl restart inventree`.
4. Open Inventree.

### Expected behaviour

It should restart the server and when the user goes to Settings -> Pricing -> Default currency, INR should be an option.

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [X] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.3
Django Version: 4.2.12

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by masteradit** [comment]
I figured out the solution:
1. Install Inventree using the installer.
2. Run `inventree config:set INVENTREE_CURRENCIES=INR`.
3. Run `systemctl restart inventree`.
4. Run `inventree run invoke update`.
5. Open Inventree.

So, after running the update command, it worked.
Is this the correct way to do this or am I doing something wrong.

**Comment by SchrodingersGat** [comment]
You will have to look at the logs output for the server. The 502 error shows that the server is not running.

**Comment by czkapitan2** [comment]
I joined this community recently - and after some Inventree testing, I also discovered the need for "special" locations that would not count towards the overall store .  Now we solve this by marking the item as "LOST" but this means 2 steps when moving between locations :  1st step move, 2nd step mark as LOST  ....:-)  I'll try to "throw" funds into polar.sh ( unfortunately it's not only up to me:-) )

**Comment by matmair** [comment]
@masteradit can we close this?

**Comment by masteradit** [comment]
> @masteradit can we close this?

I haven't deployed Inventree after that, but I guess we can close the issue now as the PR has been merged.

Thanks a lot @SchrodingersGat @matmair!
