### ISSUE TITLE
[FR] Stock Item ID on Label

### ISSUE THREAD

**Issue by timmyhadwen** [inventree/InvenTree#7399]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When looking for stock items in a warehouse it is useful to be able to look for a specific stock item to take from (ie when allocated to a build or sales order). In this case it is difficult to find.

### Suggested solution

Is it possible to:
A. Add stock item ids to the label templates (same as what is in the url)
B. Add stock item ids to the stock item links somewhere (we currently look for these in the url). It would be great to see a stock item ID + quantity everywhere we currently just get a quantity and a link to the stock item. This would make picking much easier!

### Describe alternatives you've considered

We currently use the URL and phone to scan the QR code to find the right stock item

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
You can access the "ID" of the stock item using `{{ item.pk }}`

**Comment by matmair** [comment]
@timmyhadwen ja we close this?

**Comment by timmyhadwen** [comment]
Closed :)
