### ISSUE TITLE
Logo Redesign

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#741]
Could be cleaner! The open box tabs get lost especially when small.

**Comment by a7hybnj2** [comment]
I don't know if this is something on my end but I have my instance of InvenTree bookmarked in my **Firefox** bookmark toolbar and the icon/logo looks generic...

<img width="98" alt="Screen Shot 2020-04-27 at 9 19 46 PM" src="https://user-images.githubusercontent.com/36831279/80436334-e979c900-88cc-11ea-9c80-2f89f09418ac.png">

**Comment by SchrodingersGat** [comment]
Might be something on your end - works on firefox for me?
