### ISSUE TITLE
Lists last supplier part when using Order parts under parts action in main Parts page

### ISSUE THREAD

**Issue by LastEdit** [inventree/InvenTree#7411]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

On the Main parts page, when selecting multiple parts and using the order parts action, the supplier parts listed in the dropdown will always be from the last part listed. 
I don't think there are any other pages that allow multiple parts to be selected to order. The individual part page is single and the build order list only allows single part order.
I feel like the multiple part order would be useful for the build order section so I am bringing this bug up in case it is ever implemented there.

### Steps to Reproduce

1. Select multiple parts on main Parts page
2. Select Part Action -> Order parts
3. Select drop down on supplier part on any but the last part
4. Will only see last parts supplier information

### Expected behaviour

Able to select supplier part

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.3
Django Version: 4.2.12
Commit Hash: d4d9aa9
Commit Date: 2024-05-27

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-107-generic-x86_64-with
Installer: DOC

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by LastEdit** [comment]
I just noticed ordering multiple stock items is accessible on the main stock page as well through the stock actions menu.

**Comment by SchrodingersGat** [comment]
@LastEdit can you perhaps share some screenshots here? I'm not fully understanding what the issue is

**Comment by LastEdit** [comment]
Sorry if the wording is confusing. Here are some screenshots.
![Screenshot 2024-06-08 012125](https://github.com/inventree/InvenTree/assets/145784724/853bfd50-878f-42aa-801f-a0dbddec844d)
![Screenshot 2024-06-08 012209](https://github.com/inventree/InvenTree/assets/145784724/b7b564da-5fc7-40e6-b5a3-39821664f3f8)
![Screenshot 2024-06-08 012330](https://github.com/inventree/InvenTree/assets/145784724/6d8b2b7e-aaf4-431c-819a-40cf80f3eb45)
![Screenshot 2024-06-08 012416](https://github.com/inventree/InvenTree/assets/145784724/ec3fa68c-0b1b-4b59-9d3e-5a14023ae324)

**Comment by SchrodingersGat** [comment]
Ah ok, thanks yes those images are helpful.
