### ISSUE TITLE
Backups not occurring as per daily schedule

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#7415]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

On the system interface I've set the backups to occur every 1 day, but when looking at a listing of the backup files, it's only occurring every second day. 

Automatic Backup enabled and Auto Backup Interval = 1

The odd thing is the task is running daily.
```[fix-apart-ohio-march InvenTree.tasks.run_backup	InvenTree.tasks.run_backup	InvenTree	June 7, 2024, 11:33 a.m.	June 7, 2024, 11:33 a.m.	4.197163```

But there are no backup files generated today. 

### Steps to Reproduce

Setup backups to daily and check backup files

### Expected behaviour

Expect backup to happen daily. 

### Deployment Method

- [ ] Docker
- [X] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.3
Django Version: 4.2.12

Database: mysql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-182-generic-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'KiCadLibraryPlugin', 'slug': 'kicad-library-plugin', 'version': '1.4.1'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
-rw-r--r-- 1 inventree inventree 108093242 May 29 12:33 inventree-server-2024-05-29-113323.tar.gz
-rw-r--r-- 1 inventree inventree 108093242 May 31 12:33 inventree-server-2024-05-31-113308.tar.gz
-rw-r--r-- 1 inventree inventree 108093242 Jun  2 12:33 inventree-server-2024-06-02-113323.tar.gz
-rw-r--r-- 1 inventree inventree 108513264 Jun  4 12:33 inventree-server-2024-06-04-113327.tar.gz
-rw-r--r-- 1 inventree inventree 108440239 Jun  6 12:33 inventree-server-2024-06-06-113315.tar.gz
```

**Comment by matmair** [comment]
This seems to be valid, I can reproduce it on some instances (I do not really use the default backup solution)
