### ISSUE TITLE
Search field in Allocate Stock to Build does not search part IPN

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#7434]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When I enter something in the search field of the Allocate Stock to Build the IPN in the column Required part is not searched. Only the name part is searched.  If I go to the BOM panel of a part, the IPN part is searched.

Part Name Display Format is  	
{{ part.IPN if part.IPN }}{{ ' | ' if part.IPN }}{{ part.name }}{{ ' | ' if part.revision }}{{ part.revision if part.revision }} 

### Steps to Reproduce

Go to a Build order -> Allocated Stock
Enter something in Search

### Expected behaviour

Part name and IPN should be searched

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

[0.16.0 dev](
Commit Hash	ab2e838
Commit Date	2024-06-12
Commit Branch	master

Ubuntu 22.04
Postgree

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@SergeoLacruz can you please provide a screenshot of exactly where you are entering this value (and expecting it to search by IPN)?

**Comment by SergeoLacruz** [comment]
Allocated parts view without search
![tb1](https://github.com/inventree/InvenTree/assets/10836099/449ec459-79a6-4fbf-9f49-af6f8fa245fc)

With search for 002
![tb2](https://github.com/inventree/InvenTree/assets/10836099/c17cc670-79a5-4d02-8bc1-b9b8ffcceacc)

**Comment by SchrodingersGat** [comment]
@SergeoLacruz pretty simple fix - incoming in https://github.com/inventree/InvenTree/pull/7442
