### ISSUE TITLE
Stock Item Ownership on items with no owner

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#7446]
### Body of the issue

I think we have a mismatch here. the documentation says:
![tb1](https://github.com/inventree/InvenTree/assets/10836099/3d6d9a60-99e8-47d6-ab85-ad029689fe97)
but 
https://github.com/inventree/InvenTree/blob/2d234e283111188d70d32676f606203675e9740e/src/backend/InvenTree/stock/models.py#L990
returns True in that case. In my setup I need to add am owner to all stock items to avoid the editing possibility. Which one  is the
intended behavior?  I can change either doc or code.

**Comment by SchrodingersGat** [comment]
The "stock ownership" permission functionality probably needs a larger scale review. I do not use this feature myself and am unsure how it is being used in practice.

Any changes to the `check_ownership` method (and similar methods) will result in some far-reaching consequences so we need to carefully consider it.

It sounds like you *do* use this feature? Can you provide some context on what changes you would like to see here, and your motivations?

**Comment by SergeoLacruz** [comment]
There is no need to change the code. There is just a mismatch with the documentation. Changing the doc is fine.
We do not use the feature yet but plan the following use case:
Normal developers have view access to all parts and stock items. However populated boards are a special case. 
They have serial numbers and the developers need write access because they need to add remarks to the notes field like
"repaired. replaces U343". They need to add pictures and error reports. 
Anyhow they should  not have write access to other components. 
With the existing system I can create a user group for a project. I  add all developers who are working on the project to
that group and set the owner of all populated boards related to that project to the group. 
Additional I add a dummy owner to anything else. This is needed remove the editing feature.

I know the stock ownership feature is a hack that just hides certain buttons. It is not ideal but OK for the moment.
 
In an ideal case each stock item has its own access rules, user groups are related to projects, handling of 
beta testers, ...... long wish list :-)

**Comment by SchrodingersGat** [comment]
@SergeoLacruz if you want to submit a PR to adjust the documentation accordingly, I'd support that!

**Comment by matmair** [comment]
A general refactor of the permissions would certainly be interesting... maybe we should create an epic collecting all issues regarding that and defining the user stories we want to have considered

**Comment by SchrodingersGat** [comment]
Yep, I think an epic would be a good idea. I've got no horse in this race but would be interested to see how the feature is being used.

**Comment by SergeoLacruz** [comment]
I think we can close this because the docs have been aligned with #7474
