### ISSUE TITLE
Subscribed part notification bug

### ISSUE THREAD

**Issue by E-Hain** [inventree/InvenTree#7448]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When subscribed to a part and/or part category and stock reaches its minimum threshold or lower, a notification is not given.

### Steps to Reproduce

1. Set minimum stock for a part
2. Subscribe to part or part category
3. Remove stock at or below minimum threshold
4. No notification is given (Bug occurs)

### Expected behaviour

1. Set minimum stock for a part
2. Subscribe to part or part category
3. Remove stock at or below minimum threshold
4. Receive notification

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.3
Django Version: 4.2.12
Commit Hash: d4d9aa9
Commit Date: May 27 2024

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.8.0-35-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Nothing Relevant
```

**Comment by SchrodingersGat** [comment]
@E-Hain can you please check if you can reproduce this on the demo server? I am not seeing this issue on my dev setup.

**Comment by E-Hain** [comment]
Yes, I have tried to get a notification to pop up on the demo site, and no notification pops up. It does show up in the low stock section in the main menu area.

**Comment by SchrodingersGat** [comment]
Strange, it works locally on my dev setup but on the demo server does appear to be not working. Will have to look into this.

**Comment by SchrodingersGat** [comment]
@E-Hain if you find any further info here, or want to dig into it yourself, it would be greatly appreciated!

**Comment by SchrodingersGat** [comment]
I have a running system which exhibits this behaviour now, running on [latest master commit](https://github.com/inventree/InvenTree/commit/6be6c4b42f38aaf3a086e8bf4864ed5b18218efa).

Some interesting points:

- If you edit a part, both the `notify_low_stock_if_required` and `notify_low_stock` background processes are correctly called and run
- However, no notification is generated
- If you manually call `notify_low_stock` (from the admin shell for e.g.), the notification *is* actually generated
