### ISSUE TITLE
[FR] Part Categories got harder to navigate

### ISSUE THREAD

**Issue by eimparas** [inventree/InvenTree#7485]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

i Have structured my inventory based based on a general part group 
eg: 
```
-Voltage regulators
--Positive 
---78xx
---LDO
``` 
etc. 

Im not so sure at witch version this happend cause this is more like a "when you need it" thing,  i notised that when going to the part or stock Subcategories menu i had all the "tree" on the same list and i had to set a filter 
![image](https://github.com/inventree/InvenTree/assets/20401903/be077964-d30e-468b-9760-a51a30e22d0b)
that wasnt needed before . 

### Suggested solution

Revert back to doing the oposite . If someone wants everything listed like this : 
![image](https://github.com/inventree/InvenTree/assets/20401903/e01581cf-591f-45f4-a175-3309abe009db)

 have it be a filter 

### Describe alternatives you've considered

You could also have it be a option in the config if the user want by default 
![image](https://github.com/inventree/InvenTree/assets/20401903/fb433018-0506-4129-a5cd-6652e0833f3f)
the `Include Parameters` Option be `True` or `false`

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@eimparas any development in this area will focus on the new react interface. You can view the progress here: https://demo.inventree.org/platform

**Comment by eimparas** [comment]
@SchrodingersGat  Yes i understand , but the same behavor seems to happen in the demo 
![image](https://github.com/inventree/InvenTree/assets/20401903/66b70216-4961-4503-b2fb-f0d85abc911a)

But help me clear this up , did this behavor change indeed in some version or it was like a Mandela effect of some short?

**Comment by wolflu05** [comment]
I think this is a regression introduced with #6536 . (Found this by git bisect, that its working a commit prior to that (a310437dc71ae08af30c8079532e425bc1838c7d) and the first bad commit is 0bfbd45cece8ae7e68b077d61438b70c26ab5a12)

**Comment by SchrodingersGat** [comment]
Ok, I think I misunderstood the issue here. So, you are saying that now by default, sub-categories are included in the results, but previously they were not included by default?

**Comment by wolflu05** [comment]
Exactly

**Comment by eimparas** [comment]
> Ok, I think I misunderstood the issue here. So, you are saying that now by default, sub-categories are included in the results, but previously they were not included by default?

Yes, thats what im saing . 

having  sub-categories  included in the categories  list makes it quite confusing imho

**Comment by wolflu05** [comment]
> As far as I can tell this is only the case for the "top level" part category.

You are right, but I think this is definitely a regression should be changed for the "top level" category.
