### ISSUE TITLE
"Identify" Action Plugin

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#749]
Add a plugin to support "identification" (e.g. of StockItems)

## Use Case

- User presses "Identify this stock item" in the app
- Server is connected to LED strip controller
- LED lights up (part of a grid) to show the location of the stock item

**Comment by SchrodingersGat** [comment]
@jamescurrawong

**Comment by matmair** [comment]
@SchrodingersGat do you know if anyone worked on this?

**Comment by SchrodingersGat** [comment]
No I don't believe so. It was an idea that @jnewlands and I discussed that would be potentially useful, but never actually went anywhere.

I'd probably like to re-think the whole "actions" plugin system first, after the current feature pushes are done.
