### ISSUE TITLE
Change what part details are visible in Parts tab

### ISSUE THREAD

**Issue by Basilisvirus** [inventree/InvenTree#7495]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When I want to pick a resistor to solder, the first thing I want to see is where this resistor is placed in my lab.  
So I am at the Parts tab looking at the resistor that I want to pick up and I see the IPN, Revision, Description, Units, Category, Stock, Price range, Link etc. But none of these matters to me when I am prototyping.

I would like to have the option to choose what part details I see on the parts tab. I would like to see first the Default Location and MPN.

![image](https://github.com/inventree/InvenTree/assets/18421898/e7c69b59-7c37-4d29-8538-288aec6b38f8)

### Suggested solution

I want to have a way to change what details I see at the parts tab/ tab columns. And say I select to see the Part, Default Location and MPN. After I log out and in again, I want this setting to remain the same. I dont want to set my view again. I always want to see the Part, Default location and MPN when I log in until I change it again.

### Describe alternatives you've considered

Alternative for you to implement or alternative way/ workaround for me?  

A workaround for me would be to use the Parameters tab and make my own MPN and  Default location column. 

![image](https://github.com/inventree/InvenTree/assets/18421898/377fec7e-bc98-4bf6-9123-d8eedfa4ac09)

So I would have to re-invent the already existing MPN input field and Default locations features.

### Examples of other systems

Partkeepr allows you to edit the colums.
![image](https://github.com/inventree/InvenTree/assets/18421898/44f171dc-a213-49fc-8f4a-763be2fcd07d)

but I dont have that installed to show more details.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by Basilisvirus** [comment]
Its weird that I couldnt find similar feature request because this should be a very desirable feature. Maybe I just didnt find the already existing feature request.

**Comment by SchrodingersGat** [comment]
@Basilisvirus I'm not quite sure what you are missing here - the available data columns are selectable - they can be turned on / off and this selection is "sticky" (at least for the browser session). Are the column selections not persisting for you?

**Comment by SchrodingersGat** [comment]
The column selector is on the top-right of the screeen:

![image](https://github.com/inventree/InvenTree/assets/10080325/f972a9c9-03a6-42fd-9970-0a20ed4471fb)

**Comment by Basilisvirus** [comment]
Right, I admit my mind skipped that!

Still, I do not see the option for MPN and Default location which are what I want to see on the columns.

So I would change the feature request a little bit to emphasize on those two. MPN and Default location. Otherwise I can make it as a new feature request. 
Let me know.

**Comment by wolflu05** [comment]
Displaying the Mpn in a parts list is not possible, because each part could have more than one MP, so each part could have multiple MPNs.

**Comment by Basilisvirus** [comment]
> Displaying the Mpn in a parts list is not possible, because each part could have more than one MP, so each part could have multiple MPNs.

All right. Default location then, at least.

**Comment by Basilisvirus** [comment]
Got it.

> > All right. Default location then, at least.
> 
> Yes, that would work.

Great, I made a feature request to be more specific for this:

https://github.com/inventree/InvenTree/issues/7539

So you can decide to close this issue and track the other one.
Thanks.
