### ISSUE TITLE
Update "PurchaseOrder" rendering

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#750]
New SalesOrder rendering has a progress-bar display for displaying quantity vs quantity allocated. A similar approach could be used for display quantity vs quantity received

**Comment by andyseracuse** [comment]
Hello!  I'd like to work on this.

**Comment by SchrodingersGat** [comment]
Hi @andyseracuse thanks for stepping up! I've actually just fixed this in https://github.com/inventree/InvenTree/pull/748 (see image below).


![image](https://user-images.githubusercontent.com/10080325/80169974-39853100-862a-11ea-81cf-aa82df9400a8.png)

If there is another one you want to take a look at instead?... Any contributions would be awesome! Thanks again.

**Comment by andyseracuse** [comment]
okay!  thanks anyway.
