### ISSUE TITLE
Allocate Stock Item with Serial Number results in "Form error exist"

### ISSUE THREAD

**Issue by PrintINGU** [inventree/InvenTree#7510]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

If you try to allocate a tracked stock item in a build order it results in a error message "Form error exist". If you do the same with a non tracked item there will be no problem. 

The following screenshots are from the DEMO site. But the error output is exactly the same.

Build Order: 
![Inventree_DEMO_Build_Order](https://github.com/inventree/InvenTree/assets/76585523/65120028-c8ca-4551-9866-e06318d8802e)

Allocate Stock item to Build Order:
![Inventree_DEMO_Allocate_to_Build_Order](https://github.com/inventree/InvenTree/assets/76585523/149a44d3-d64e-4a0d-a162-841364fdf357)

F12 Network Debug Output:
![Inventree_DEMO_Debug_Output](https://github.com/inventree/InvenTree/assets/76585523/54863b47-61aa-4d46-abd3-506d9e9b427e)

Further F12 Debug:
![Inventree_DEMO_Debug_Output2](https://github.com/inventree/InvenTree/assets/76585523/4595481b-7d0a-4c8c-8ee2-3565fd16e207)

### Steps to Reproduce

1. Create or open a build order
2. Select a tracked BOM item and klick the "Allocate Stock" button
3. (if necessary) select Stock Item with Serial Number and klick the "Submit" button
4. Output: "Form error exist"

Same output if you select a Source Location.

### Expected behaviour

1. Create or open a build order
2. Select a trackend BOM item and klick the "Allocate Stock" button
3. (if necessary) select Stock Item with Serial Number and klick the "Submit" button
4. Item is allocated

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.4
Django Version: 4.2.12
Commit Hash: fa1a9da
Commit Date: 2024-06-16

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.149-1-pve-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Tracked items must be allocated against individual build outputs:

https://docs.inventree.org/en/stable/build/allocate/#untracked-vs-tracked-stock

I'll look into the obtuse error message, not sure why that is happening.

**Comment by SchrodingersGat** [comment]
This has been addressed in recent improvements to the build order / stock allocation interface
