### ISSUE TITLE
Order part default value is `-0`

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#752]
## Descripting
Not a huge bug/issue but would require less clicks if fixed. When you double click it just selects the 0 so if there is the `-` sign you have to triple click to select the whole line.

## Steps to reproduce
1. Go to a part
1. Select the `purchase order` tab
1. Hit `order part`
1. Observe that the qty is set to `-0`

## Screenshots
<img width="235" alt="Screen Shot 2020-04-23 at 11 36 31 AM" src="https://user-images.githubusercontent.com/36831279/80119686-05d9d680-8558-11ea-99f8-dcf1d5b719fe.png">

## Version Information
<img width="1027" alt="Screen Shot 2020-04-23 at 11 46 30 AM" src="https://user-images.githubusercontent.com/36831279/80119745-18eca680-8558-11ea-827c-04b94ee634d7.png">

**Comment by SchrodingersGat** [comment]
What browser are you using?

**Comment by a7hybnj2** [comment]
Firefox

**Comment by eeintech** [comment]
I stumble upon the same issue and I believe it is due to the `quantity_to_order` property of the `Part` model:
```
	@property
	def quantity_to_order(self):
		""" Return the quantity needing to be ordered for this part. """

		required = -1 * self.net_stock
		return max(required, 0)
```
So that replacing:
```required = -1 * self.net_stock```
with:
```required = self.net_stock```
solves it.

Not sure what good it brings to multiply the `net_stock` by -1.
