### ISSUE TITLE
[FR] multi-line notes with markdown support in supplier parts

### ISSUE THREAD

**Issue by bgrant85** [inventree/InvenTree#7522]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I have a need to write notes that are attached to a supplier part.  I think that feature exists but it doesn't accommodate notes with many lines.  Ideally it would support markdown, and the notes would  show up in the table of suppliers for the associated parts in a way that the last few lines are visible, and when the supplier part is pulled up, all the notes are visible in a fairly large screen, with scrolling if necessary.

### Suggested solution

Expand the supplier notes feature to support large (infinite) number of lines and markdown.  Adjust its presentation on the associated part page and the actual supplier part page so that the large number of lines show up in a convenient readable way  (line breaks show up as expected in all views), and is editable, at least from the supplier part page.

### Describe alternatives you've considered

NA

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/7522">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/7522/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/7522/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@bgrant85 certainly we could add this feature in - although there are a lot of competing priorities. If you want to sponsor this feature (via the "fund this issue" button above) we can push it to the top of the stack

**Comment by matmair** [comment]
@wolflu05 I think you implemented this recently?

**Comment by wolflu05** [comment]
Yes, this sounds like #7667.

**Comment by SchrodingersGat** [comment]
Closed as complete
