### ISSUE TITLE
Ability to import parts with a chosen part id that is not currently in use

### ISSUE THREAD

**Issue by realstudent01** [inventree/InvenTree#7524]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I want to import parts from a spreadsheet, and I have already assigned unique IDs to them. I want to use these unique IDs as their part id in InvenTree so that if I ever need to update them, I can reimport and the new things will populate to the correct place. Currently, the documentation says that to add a new part, import it with part id blank and the next part id will be assigned to it.

### Suggested solution

So the solution would be to make it search for existing part ids (as it already does). If one is not found (currently it throws an error) then insert a new part with the not found part id and the other information in the row being imported.

### Describe alternatives you've considered

An alternative would be to give back a list of generated Part Ids in the order that they are assigned so that they can be inserted into the file type that was used for the import, but this seems less ideal.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by realstudent01** [comment]
I could also help to make this happen, but I would need a bit of guidance/help with starting.

**Comment by SchrodingersGat** [comment]
That is not compatible with how the database works - the database backend assigns unique IDs and we cannot pass our own ID values to it. The "ID" value must be blank for new items being imported.

Note that there is currently a large project to completely overhaul the data import framework: https://github.com/inventree/InvenTree/pull/6911

**Comment by matmair** [comment]
IMO this is not planned - can we close this?

**Comment by SchrodingersGat** [comment]
Closing, this will not be supported.
