### ISSUE TITLE
Ability to edit and add the fields when importing parts in Admin view

### ISSUE THREAD

**Issue by realstudent01** [inventree/InvenTree#7525]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I want to import parts from a spreadsheet, but I want to add more categories than are currently available in the options of "part id, part name, part description, IPN, etc".

### Suggested solution

I assume this could be doable with an additional section in the admin view to control part fields for import/export. If a new part field is added, then that field should be set to null or false or something like that for all existing parts in the database. If a field is removed, then that field should be deleted from all existing parts.

### Describe alternatives you've considered

These options could also be easily exposed in the source code instead of in the admin view.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
See comment in https://github.com/inventree/InvenTree/issues/7524

**Comment by SchrodingersGat** [comment]
Closing this, as the "import" workflow in the django admin view will be removed entirely in favour of the new import process.
