### ISSUE TITLE
Add translatable names for database columns

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#753]
The database column names are used to generate field titles for HTML forms. However these are not passed through the translation layer.

So, for each database model field, a `verbose_name` parameter must be added.

## TODO

For each `models.py` file, look through each Model class and ensure that each field is has a translatable `verbose_name` parameter. Remember to prepend with `_` to translate it.

e.g.

![image](https://user-images.githubusercontent.com/10080325/80280189-ed2f1380-8745-11ea-976d-2a10bf13afe5.png)

**Comment by ikassim9** [comment]
Hi so we are adding verbose_name to each class in the models.py. My question is what comes after verbose_name?

**Comment by SchrodingersGat** [comment]
The `verbose_name` parameter is simply a translatable version of the name of the field. The `_` function allows the name of the field to be translated so that forms can be displayed in different languages.

**Comment by matmair** [comment]
hey @SchrodingersGat is this still current? a quick check shows that almost all models have the verbose field.

Also if it is still relevant - do you also want to have help_texts added or just keep it like it is?

**Comment by SchrodingersGat** [comment]
I have not checked in a while but I think there are still some fields that need translating, both `verbose_name` and `help_text`.

**Comment by matmair** [comment]
Just a heads-up, I am actively working on that, I am currently going through every file in the system, and it might take a while.
The branch I am working on that is https://github.com/matmair/InvenTree/tree/translation_improv

**Comment by matmair** [comment]
@SchrodingersGat I would recommend closing this issue, I think I got all models / forms
