### ISSUE TITLE
How to change INVENTREE_SITE_URL under wsl

### ISSUE THREAD

**Issue by Basilisvirus** [inventree/InvenTree#7530]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I have a Inventree setup running on my wsl configuration. I can access Inventree via `http://localhost/` on the host PC but I have a hard time making it work for the rest of the devices that are connected to the same wifi (locally).

I have already checked two similar issues on github ([here ](https://github.com/inventree/InvenTree/discussions/7402)and [here](https://github.com/inventree/InvenTree/discussions/7308)) but none of them seem to use wsl and they installed their Inventree using docker (if I understod the issues correctly). 

Now, I understand that I need to change the `INVENTREE_SITE_URL `var under `/opt/inventree/contrib/container/.env` to the ip of the host device. 

Inside wsl I see:

```
root@Zen:~# netstat -tulnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      118/systemd-resolve
tcp        0      0 10.255.255.254:53       0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:6000            0.0.0.0:*               LISTEN      188/python3.10
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      382/nginx: master p
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -
udp        0      0 127.0.0.53:53           0.0.0.0:*                           118/systemd-resolve
udp        0      0 10.255.255.254:53       0.0.0.0:*                           -
udp6       0      0 ::1:323                 :::*                                -
```
Where I suppose I have to set the INVENTREE_SITE_URL="127.0.0.1:323"
At that point, I have questions:
1. What is the format to set the INVENTREE_SITE_URL variable? Which one of the below is acceptable:
a) INVENTREE_SITE_URL=127.0.0.1:323
b) INVENTREE_SITE_URL=https://127.0.0.1:323
c) INVENTREE_SITE_URL="https://127.0.0.1:323"

Judging from the default INVENTREE_SITE_URL="http://inventree.localhost" I should always use the `""` and the `http://`.

2. Do I need to use the 8000 port anywhere when defining the ip?

I also tried:
INVENTREE_SITE_URL="127.0.0.1" (Do I have to define the :8000 port here?)
and tried: INVENTREE_SITE_URL="192.168.2.5" which is the IP address of my windows (where the wsl runs at):

```
PS C:\Users\Vasilis> ipconfig

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : station
   IPv6 Address. . . . . . . . . . . : ---
   Temporary IPv6 Address. . . . . . : ---
   Link-local IPv6 Address . . . . . : ---
   IPv4 Address. . . . . . . . . . . : 192.168.2.5
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::1%4
                                       192.168.2.1
```
 Every time I changed the INVENTREE_SITE_URL I restarted the inventree by using `inventree restart`, the host pc could always connect to the inventree website via `http://localhost/` but the other devices in the same wifi network would not connect. I believe there is something wrong when using the wsl, windows might be blocking something. But I always work with firewall completely disabled, windows defender disabled and defender's files are also deleted from my hard drive so its not blocking anything.

### Steps to Reproduce

1. Use windows 11
2. install wsl by: opening up cmd, type `wsl --install` (and after installation its possible `wsl --update` might be needed.
3. Upon running wsl for the first time it will install Ubuntu. If prompted, install Ubuntu 22.04.4 LTS, as newer versions wont be supported.
4. In wsl/Ubuntu, run `sudo apt-get update` and `sudo apt-get upgrade` to update the ubuntu system.
5. Check your python version. If it starts from 3.10 for example, create this variable as such: `export SETUP_PYTHON=python3.10`
6. Use the automated script to install inventree: `sudo wget -qO install.sh https://get.inventree.org && sudo bash install.sh`
7. Inventree should be available under `http://localhost/`
8. Uncomment `/etc/inventree/config.yaml` for username/password
9. Change `INVENTREE_SITE_URL `var under `/opt/inventree/contrib/container/.env` to a) WSL's IP, b) windows's IP. After every change, do `inventree restart`.
10. Try to connect to the inventree ip addressed used at `INVENTREE_SITE_URL ` with a device connected to the same wifi as host pc and fail.

### Relevant log output

```bash
where do I get the logs?
```

**Comment by SchrodingersGat** [comment]
Running behind WSL in this manner means that the IP address is obscured. 

I'm not 100% sure that this will work but what I would suggest is:

1. Set your `INVENTREE_SITE_URL` to the external IP of the server (`http://192.168.8.1`)
2. Configure your WSL install to forward ports - https://jwstanly.com/blog/article/Port+Forwarding+WSL+2+to+Your+LAN/

**Comment by Basilisvirus** [comment]
It worked.
according to the article/link you posted I forwarded these ports using the command:

`netsh interface portproxy add v4tov4 listenport=443 listenaddress=0.0.0.0 connectport=443 connectaddress=172.28.221.133`

for all these ports:

![image](https://github.com/inventree/InvenTree/assets/18421898/7129f24a-274e-4bcd-bc1e-c2b85bdb9651)

I think only port 80 is needed? But from what I saw in the issues here and from the .env/config files of the inventree installation I forwarded the rest of the ports as well. 

And then in the .env file I changed the ip to what you suggested:

![image](https://github.com/inventree/InvenTree/assets/18421898/117b0610-e741-48a8-adf5-a96c24b7ef68)

I then restarted windows.

And then I can connect to the server/host pc from other devices using the ip address of the server/host pc (that windows see aka `192.168.1.17` seen below):

```
PS C:\Users\Vasilis> ipconfig

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : home
   IPv6 Address. . . . . . . . . . . : --
   Temporary IPv6 Address. . . . . . : --
   Link-local IPv6 Address . . . . . : f--
   IPv4 Address. . . . . . . . . . . : 192.168.1.17
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::1%4
                                       192.168.1.1
```

So thanks.
I just have one question.
How did you know that the external IP of my server is http://192.168.8.1 ? It was not on any of the exported IPs that I posted here. Is it a standard ip that wsl makes?

**Comment by SchrodingersGat** [comment]
Glad that you got it working!

> How did you know that the external IP of my server is http://192.168.8.1/ ?

Uh, that's very odd. I was sure you had typed it somewhere, but looking back through your original message it is not there. I must have mistyped "192.168.2.1", perhaps.

**Comment by Basilisvirus** [comment]
I can connect from other devices even if I let the INVENTREE_SITE_URL to its default:
`INVENTREE_SITE_URL="http://inventree.localhost"`
I also changed to to my external IP and I can still connect from other devices:
`INVENTREE_SITE_URL=http://192.168.2.1`
I always use window's ipv4 to connect from other devices and it connects. The INVENTREE_SITE_URL variable doesn't seem to do anything. Let me know if you manage to confirm and demystify it, but I guess you would have to use Windows and WSL.

You can close the issue though, the default issue I has is resolved.
