### ISSUE TITLE
[FR] User permissions

### ISSUE THREAD

**Issue by bharathmanvas** [inventree/InvenTree#7533]
Currently there is two options. But iam looking for the more options for user permission like read-only, admin and super admin.
```[tasklist]
### Tasks
```

**Comment by SchrodingersGat** [comment]
> Currently there is two options.

Can you please expand on this. Not sure what the issue is that you are raising.

**Comment by bharathmanvas** [comment]
Hi @SchrodingersGat ,

urrently, InvenTree user management provides three options for user roles: superuser, staff, and active. While these roles cover basic user management needs, there is a requirement for more granular permissions to manage teams across different locations effectively. Specifically, there is a need for:

Read-Only Access to Inventory Products: Users with this permission should only be able to view the inventory products without the ability to edit any details.

Stock-Only Access: Users with this permission should be able to add items to the inventory stock section but should not have access to other sections or editing capabilities.

**Comment by matmair** [comment]
1) we support that: you can set up fine grained permissions with groups. Roles are just faster as the user gets access to everything with one click
2) use the feature request template if you have a feature request. We have to ask all the questions in the template anyway

**Comment by SchrodingersGat** [comment]
https://docs.inventree.org/en/stable/settings/permissions/
