### ISSUE TITLE
Build - Available/Allocated parts not refreshed when auto allocating

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#7537]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When creating a build, if you use "auto allocate" and clic submit, the available and allocated values are not refreshed on the screen. You have to click F5/refrsh on the browser to get the update. 

This was working a month ago or so. 

### Steps to Reproduce

1. On demo site, create new build order. 
2. Select part:  Test Board 1
3. Set Quantity to some random number: 10 in my case. 
4. Submit
5. On Build order, click "auto allocate"
6. Click confirm/submit

### Expected behaviour

The allocated field should automatically update after sumitting. 

### Deployment Method

- [ ] Docker
- [X] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.4
Django Version: 4.2.12

Database: mysql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-182-generic-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'KiCadLibraryPlugin', 'slug': 'kicad-library-plugin', 'version': '1.4.1'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by StormTrooper** [comment]
This issue is still occuring

**Comment by SchrodingersGat** [comment]
This has been fixed in the new user interface, and as it is not a critical bug it will not be updated in the old UI. Thus I will close this out.
