### ISSUE TITLE
[FR] Add Default Location at the available data columns

### ISSUE THREAD

**Issue by Basilisvirus** [inventree/InvenTree#7539]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When I am doing a prototyping for a PCB, when I want to solder a 10k resistor, I want to just search for 10k, and the first thing I want to see is the "Default location" of the parts list that show up in the results and go to pick it up.

Right now, when I look for a part, what I can see first on the columns is stuff like description, units, price range, IPN.   
![image](https://github.com/inventree/InvenTree/assets/18421898/27858ef3-6a22-4928-bd2d-35fd168b3aad)  
These are not irrelevant to the R&D process. The most important information for R&D that is missing here is  "Default location" (storage location) so that I can go and pick that part while I solder components on the PCB.

### Suggested solution

When I am at the parts category, I would like to see the "Default location" at the columns. 
So I would like to have the option to show/hide the "Default location" for the columns.

![image](https://github.com/inventree/InvenTree/assets/18421898/b118fefd-cb4e-4c8f-8240-4e4c86bdaa85)

### Describe alternatives you've considered

An alternative for me:
Would be that I will assign the Default location to the IPN column instead. Like this:  
![image](https://github.com/inventree/InvenTree/assets/18421898/1042264d-2e73-44a3-877b-d07d4ede5f57)
But this is not the "official" place to store the storage location so it might not be future-proof for features that might come up in the future that include the Default location. For example there is a plug in that creates many storage locations at once so I dont have to type all the available storage locations. And I wont be able to use that if I use the IPN instead.

An alternative solution (for you to implement):
I dont know, you already have the Defaut location, the easiest thing I think, would be to just put it on the columns. 
What if you made a different field called "Storage location", which I think is more appropriate (Because "Default location" indicates that the location might have changed from the default). And then make this "Storage location" visible on the columns. 
But I think this alternative would take more work to implement.

### Examples of other systems

In parkeepr they show the Storage location at the columns:

![image](https://github.com/inventree/InvenTree/assets/18421898/e7d07572-153f-412a-9ff6-37b9a1fec7eb)

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/7539">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/7539/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/7539/pledge.svg">
</picture>
</a>

**Comment by Basilisvirus** [comment]
The added column of the Location, will it be search-able be default? If not, I would like to have that (maybe by opening a new feature request)

**Comment by SchrodingersGat** [comment]
@Basilisvirus this has been closed in https://github.com/inventree/InvenTree/pull/7587
