### ISSUE TITLE
Duplicate MPN not allowed

### ISSUE THREAD

**Issue by binxuli** [inventree/InvenTree#7551]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When duplicating a part and giving the same MPN, an error occurs saying the MPN already exists and the duplicating process cannot proceed. By skipping the MPN however, one can duplicate the part and edit the MPN afterwards, and no error occurs. 

### Steps to Reproduce

1. go to a active part 
2. click "duplicate part" 
3. type in the same MPN in the duplicate window 
4. error message: "MPN already exists". 
5. skip the manufacturer and MPN while duplicating and duplicate the part 
6. click "edit part" 
7. type in the same MPN you wanted to type in anyway 
8. MPN will be accepted

### Expected behaviour

1. go to a active part 
2. click "duplicate part" 
3. type in the same MPN in the duplicate window 
4. part will get duplicated with the same MPN

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

<html>
<body>

0.15.4
--

</body>
</html>[0.15.4](https://github.com/inventree/InvenTree/releases)

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@binxuli can you provide some screenshots of this behaviour? In particular I  want to know from what screens you are duplicating the part, etc.

**Comment by binxuli** [comment]
> @binxuli can you provide some screenshots of this behaviour? In particular I want to know from what screens you are duplicating the part, etc.

Here is a screenshot of the error message, the part I'm duplicating from has the same MPN.
![screenshot](https://github.com/inventree/InvenTree/assets/139081942/835e12db-4f15-49a6-b1b4-a9699320b79d)

**Comment by matmair** [comment]
@binxuli from your description it sounds like you skipped entering the manufacturer in 7.

We enforce manufacturer and MPN to be a unique combination

**Comment by binxuli** [comment]
> @binxuli from your description it sounds like you skipped entering the manufacturer in 7.
> 
> We enforce manufacturer and MPN to be a unique combination
> 
> Edit: The provided version info is also not helping. Please paste the info you get from "copy version information"

Hello @matmair,
thank you for your reply, I did enter the manufacturer, as shown in the screenshot. 
In my opinion, the manufacturer and the MPN doesn't have to be a unique combination, with our workflow as an example: we always require two versions of the same part to represent two quality standards, they would be logged as different versions but it is the identical part, if the manufacturer and the MPN is a unique combination for the entire storage, this process would not be possible. 
For now it is still possible because as I described, it works when adding the Manufacturer and the MPN after duplicating the part, it seems more like an inconsistency with these two options, so I submitted this as a bug.

And here's the correct version info: 
# Version Information:
InvenTree-Version: 0.15.4
Django Version: 4.2.12
Commit Hash: fa1a9da
Commit Date: 2024-06-16

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-21-amd64-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'IPNGenerator', 'slug': 'ipngen', 'version': '0.1'}]
