### ISSUE TITLE
[PUI] All users can access system settings

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#7552]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

By navigating directly to the URL, all users can access system settings.
They do not, however, have any rights to change these settings.
I discovered this accidentally when writing some PUI tests

![image](https://github.com/inventree/InvenTree/assets/7506688/f296bbf1-5949-4686-b890-54898e79c90a)

### Steps to Reproduce

1. log in with any non-superuser
2. go to: baseUrl/platorm/settings/system/purchaseorders

### Expected behaviour

Should redirect unauthorised users to some default page, or trigger a access denied page.

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

0.16 dev

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by LavissaWoW** [comment]
Hmmkay...
Shouldn't then all settings be read-only/buttons disabled on the page for users not authorised to perform changes?
To me it just seems like something that only leads to confusion on the user's end.
"Why am I allowed to click this only to get a message saying I wasn't alloed to click it?"

**Comment by matmair** [comment]
https://github.com/inventree/InvenTree/issues/5755

**Comment by LavissaWoW** [comment]
Ooouh :)

**Comment by LavissaWoW** [comment]
Can be handled by #5755
