### ISSUE TITLE
Add option to "delete stock items" when deleting a stock location

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#757]
Currently when deleting a StockLocation the contained StockItem objects are automatically moved up a level.

Two new things need to be added:

1. Provide the user an option to either move the StockItems up a level (default) or delete them. This option should also provide a warning about what stock items are going to be deleted. Also consider whether a separate option should be provided as to what to do with sub-locations

2. When deleting a stock location, and moving contained parts "upward" ensure that each StockItem is given a new tracking note

**Comment by eeintech** [comment]
@SchrodingersGat What did you decide on in #2736 ?

**Comment by SchrodingersGat** [comment]
@eeintech this one is a separate issue.

Consider the case where you have a hierarchy of stock locations A -> B -> C -> D , and location "C" has 10 items in it.

If you were to delete C, the following happens:

1. The 10 stock items are now located in "B" (the "parent" location for C)
2. The parent of D is now B
3. The hierarchy is now A -> B -> D

However, the user may have actually wished to delete C *and everything in it*. Currently this is not easy to do - you would have to delete each child location and stock item individually.

**Comment by luwol03** [comment]
I was also searching for something like this and ended up with a little scripted version. Just wanted to post that here if somebody else needs it until this feature is implemented.

```py
from inventree.api import InvenTreeAPI
from inventree.stock import StockLocation

SERVER_ADDRESS = ''
MY_USERNAME = ''
MY_PASSWORD = ''

api = InvenTreeAPI(SERVER_ADDRESS, username=MY_USERNAME, password=MY_PASSWORD)

def delete_recursively(location: StockLocation):
    print(location.pathstring)
    for sub_loc in location.getChildLocations():
        delete_recursively(sub_loc)
    location.delete()

delete_recursively(StockLocation(api, pk=306))
```

But this method has a big downside, its very slow. I guess this is caused by the logic which checks if it has Childs and tries to move them up.

**Comment by matmair** [comment]
Thank you @luwol03 ! This should really be part of the general API.

**Comment by SchrodingersGat** [comment]
@luwol03 looks like this feature is coming into the UI as well : https://github.com/inventree/InvenTree/issues/3384

> But this method has a big downside, its very slow

Yep, multiple API certainly add up! That's why we added a `BulkDeleteMixin` so that *some* items can be deleted all at once. 

https://github.com/inventree/InvenTree/blob/703731ec4d60f39864379ff89c0c90e23d9cb837/InvenTree/InvenTree/api.py#L59

This also has another **huge** advantage: If one of the delete operations fails, all the others are rolled back.

You can do a search on the codebase to find which API endpoints implement the `BulkDeleteMixin`

We should port this feature to the [python bindings](https://github.com/inventree/inventree-python) so it can be used there.

**Comment by SchrodingersGat** [comment]
Ref: https://github.com/inventree/inventree-python/pull/130

**Comment by SchrodingersGat** [comment]
@martonmiklos :)

**Comment by eeintech** [comment]
@SchrodingersGat  Nice job :)

**Comment by martonmiklos** [comment]
Hi folks!

I started to work on this and get a bit stuck again with the unit testing implementation.

My code lives here:
https://github.com/martonmiklos/InvenTree/tree/fix_757

In the test I try to delete a created StockLocation via API:
```
url = reverse('api-location-detail', kwargs={'pk': stock_location_to_delete.id})
...
response = self.delete(
                url,
                params,
                #expected_code=204,
            )

```
My requests fails with 403 with the response content:

```
(env) mm@mm-precision:~/Projektek/inventree/src$ python3 InvenTree/manage.py test --keepdb  stock.test_api.StockLocationTest.test_stock_location_delete
Using existing test database for alias 'default'...
System check identified no issues (1 silenced).
/api/stock/location/164/
Forbidden: /api/stock/location/164/
{"detail":"You do not have permission to perform this action."}<Response status_code=403, "application/json">
```
Would you mind to take a look on it and help to find the reason of this?
Many thanks in advance!

**Comment by matmair** [comment]
@martonmiklos seems like the user you are using does not have the right permissions

**Comment by SchrodingersGat** [comment]
In the testing framework you can use the `self.assignRole` method to give the test environment the right permissions for the API.

e.g. `self.assignRole('stock.change')`

Search through the code base for examples of this

**Comment by SchrodingersGat** [comment]
Closed in https://github.com/inventree/InvenTree/pull/3926
