### ISSUE TITLE
Improve "Auto-Allocation" process

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#758]
- Allow user to "adjust" the automated allocation by adjusting item quantity, and removing rows via a checkbox

- Add similar functionality for automatically allocating lines against a Purchase Order

- For each line which cannot be "automatically" allocated, instead of omitting, provide a drop-down menu populated with possible options.

- The form then becomes "Allocate" not "Auto Allocate" and allows the user to allocate items in a single step

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/80359297-fa244200-88c0-11ea-874d-170154155fe3.png)

This is the screen that should be cleaned up!

**Comment by a7hybnj2** [comment]
I don't know if this is related but since the linked issue was closed I thought I would re-reference it. https://github.com/inventree/InvenTree/issues/761#issuecomment-620335675

Tell me if I should create a dedicated issue for it since it is in the BOM and not build.

**Comment by eeintech** [comment]
@SchrodingersGat In the case that part stock is spread among different location, the "Auto Allocate" method fails to propose at least one of them. At a minimum requirement, it should propose the stock for the `default_location` set for that part if that stock exists.
