### ISSUE TITLE
[FR] Parameter Choices 5000 char limit is a problem

### ISSUE THREAD

**Issue by reid-p** [inventree/InvenTree#7583]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I'd like to have the choice list exceed the current 5000 character limit to allow for an arbitrary length list of options.
I have a use case for the selection of over 1000 options.

### Suggested solution

Parameter choices could be saved to another table instead of a comma separated string.
Drop down should be searchable by the user. 
Using something like: https://www.w3schools.com/howto/howto_js_filter_dropdown.asp

### Describe alternatives you've considered

Can't find and alternative within the current framework

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/7583">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/7583/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/7583/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@reid-p with that many options, mapping it to another table makes sense. Would you be willing to either implement this, or fund development?

**Comment by matmair** [comment]
Removing the limit is not an option from a security standpoint.

**Comment by reid-p** [comment]
@SchrodingersGat 
I could possibly implement this, but it'd probably take me a while to get up to speed with the code base.
Funding the development is also a possibility.

@matmair 
 What's the security implication with having a longer list?
Isn't it the same as an array of parts or any other item?

**Comment by SchrodingersGat** [comment]
> Funding the development is also a possibility.

@reid-p I'd be happy to take a look at this, the "fund this issue" button at the top of this issue would be the best way to support it!

**Comment by matmair** [comment]
Arbitrary length text fields that get parsed (processing of the choices) can be used easily for resource exhaustion or as part of a denial of service attack

**Comment by SchrodingersGat** [comment]
This has now been addressed with the addition of the "Selection List" concept for parameters values
