### ISSUE TITLE
Show quantity when adding to BOM

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#760]
I am building a BOM and I have a few parts like 1µF caps where there are multiple entries for different manufactures even thought they would be considered interchangeable. It would be nice to have the quantity displayed next to the add item to bom sub-part so that you can pick which one actually has parts in stock.

I think this touches on an issue of is there a way to have a generic heading like 1µF 0805 Caps and have multiple children fill it?

**Comment by SchrodingersGat** [comment]
I'm not quite sure what you mean here, can you perhaps add some more detail, or a screenshot?

**Comment by a7hybnj2** [comment]
<img width="1184" alt="Screen Shot 2020-04-27 at 9 16 44 PM" src="https://user-images.githubusercontent.com/36831279/80436148-73756200-88cc-11ea-8747-52dd5e6fbda9.png">

To the right of where it reads `chip` you could provide additional item information to help narrow down picking a part. Like quantity.

**Comment by SchrodingersGat** [comment]
Ah ok I understand. That might take some thought to work out the best way to implement. But I like the idea. In general the modal forms need to include a lot more context data! Cheers
