### ISSUE TITLE
[BUG] Searching items using barcode doesn't show correct items due a language convertion

### ISSUE THREAD

**Issue by Dark-V** [inventree/InvenTree#7605]
Can't find any pinned issue with template for bug reporting.
Also didn't find any similar issue.

# Issue:
QR is contain a json format text, that used in searching gui, and issue here if user does have multiple language installed on machine.
For example in my case, it was a russian and english(US), output data depented on selected language in win 11 ringht now.
If english, it working correctly like {"stockitem": 2}
but if is not english, in my case russian it will be like "ХЭыещслшеуьЭЖ 408Ъ"

I didnt found any info how to select only english languages on barcode scanner by using windows, only info that some barcode scanners have a ability select language type using HID (not sure, but most of all use that argument like a 0x00 in lang field)

# Expected:
- Use a neutral type for barcode format, like numbers, if need using a diff types (like a part, stockitem and etc) use a basic math for that, like adding a number in end of order.
- or create a convertional based on selected settings 

# Version Information:
InvenTree-Version: 0.15.4
Django Version: 4.2.12
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

**Comment by matmair** [comment]
We are literally using GitHubs build-in template function https://github.com/inventree/InvenTree/issues/new/choose

This sounds like an issue with your hardware, changing the decoding of the barcode will not help that

**Comment by Dark-V** [comment]
also, i guess, need mentention that, if i'm using external barcode, it will be working correctly on scanning. 
(talking about a Barcode Identifier | db868021329e8f99daaab1ce8e6eb6fb)
it's fix my issue, but it's too hard for using, coz i need mannualy create all external barcodes in my format, if there was a settings like a auto-generation, it will be fix fully my issue, but not sure about others langauges

**Comment by Dark-V** [comment]
> We are literally using GitHubs build-in template function https://github.com/inventree/InvenTree/issues/new/choose
> 
> This sounds like an issue with your hardware, changing the decoding of the barcode will not help that

oh, gotha, i just used a [Report Bug](https://github.com/inventree/InvenTree/issues/new?template=bug_report.md&title=[BUG]) from a readme

**Comment by SchrodingersGat** [comment]
@Dark-V are you saying that:

1. the barcode data (as generated by InvenTree) is being displayed in a different language?
2. The barcode *scanner* is translating the barcode data at the point of scan?

I have tried to reproduce 1) but the barcode data is always in english, no matter the selected language

**Comment by Dark-V** [comment]
@SchrodingersGat 
> @Dark-V are you saying that:
> 
> 1. the barcode data (as generated by InvenTree) is being displayed in a different language?
> 2. The barcode _scanner_ is translating the barcode data at the point of scan?
> 
> I have tried to reproduce 1) but the barcode data is always in english, no matter the selected language

1.  No, tried to use my phone for scanning, qr-code always on english
2. Look like, yes. I guess the issue really in my scanner, but i can't find any info how to set language format type. It's also look like it's correctly reading qr-code data, but is translating the barcode data at the point of entering data, due a how a HID drivers works. 
But i can't understang why it's correctly working for a external barcodes (maybe coz it's using a numbers, instead of english text?)

**Comment by SchrodingersGat** [comment]
Ok, if the barcode scanner is translating the data, there's not much we can do about that really. We have a separate open issue for  a different barcode format - https://github.com/inventree/InvenTree/issues/6612 - which *may* help here. But, I would suggest finding out some more about your scanner.

**Comment by Dark-V** [comment]
So, in my case a found a special barcode that force set language to a english, got this from support.. So, i guess issue is closed for me, for my mertech cl-2210 
![image](https://github.com/inventree/InvenTree/assets/58254635/187e23fc-efc1-4540-ad71-3fe45e92bf2b)

**Comment by SchrodingersGat** [comment]
@Dark-V glad to hear you found a solution :)
