### ISSUE TITLE
Auto Allocate Build Bug

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#761]
Okay... So, I have a part that gets built. I processed one build for 25 but I needed to do another 60. I completed the first build for 25 but when I started another build for the 60 I hit the "auto allocate" button hoping it would take care of most of the parts like it did for the 25 build. I did not.

<img width="1190" alt="Screen Shot 2020-04-27 at 5 49 46 PM" src="https://user-images.githubusercontent.com/36831279/80424437-ba089380-88af-11ea-92e4-29048efc85da.png">

I double checked that most of the parts just had one stock location and enough and should/could be auto allocated. Only 3 of the 20 or so parts had multiple stock locations to choose from. I am guessing this has something to having done the 25 builds just prior but I don't know.

<img width="1172" alt="Screen Shot 2020-04-27 at 5 52 54 PM" src="https://user-images.githubusercontent.com/36831279/80424534-f1774000-88af-11ea-9f9f-558d9e9daced.png">

**Comment by SchrodingersGat** [comment]
Auto-allocation is going to be improved significantly - https://github.com/inventree/InvenTree/issues/758

But I have found and fixes this bug (I think) - https://github.com/inventree/InvenTree/pull/763

**Comment by a7hybnj2** [comment]
I just did a `git pull` and the problem is worse...

This is a screenshot of my BOM tab. Everyone of those parts has stock.

<img width="730" alt="Screen Shot 2020-04-27 at 10 14 12 PM" src="https://user-images.githubusercontent.com/36831279/80439397-71af9c80-88d4-11ea-9650-31a532c7439f.png">

Also when you click on the hyperlinked part in the BOM it takes you to the build and not to the parts page.

**Comment by SchrodingersGat** [comment]
I think that the BOM display issue is a separate bug - see https://github.com/inventree/InvenTree/pull/767 for the fix - please let me know if it fixes it on your end.
