### ISSUE TITLE
Stock Item Import - Maximum Number of Rows

### ISSUE THREAD

**Issue by bmalatest** [inventree/InvenTree#7624]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The maximum number of rows you can import for stock items is set to 1,000. This is undesirable for multiple reasons but also made more undesirable by the fact that when exporting Stock Items it will automatically export the total number of Stock Items not just those selected.

### Steps to Reproduce

Go to admin panel. Click on Stock Items under the Stock heading. Click on Export. Select format as .csv, and Submit. 
Go back to Stock Items and click on Import. Select the file exported above.

### Expected behaviour

You are able to import the stock items.
Actual outcome is that you receive an error for maximum number of rows exceeding 1,000

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

￼
InvenTree Version	0.16.0 dev
Commit Hash	9fea03a
Commit Date	2024-07-10
InvenTree Documentation	https://docs.inventree.org/en/latest
API Version	217
Python Version	3.11.3
Django Version	4.2.13

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
I am not able to access the admin panel on the demo site
```

**Comment by SchrodingersGat** [comment]
This is a known limitation and one of the driving factors behind the current work to improve the data import process:

- https://github.com/inventree/InvenTree/issues/3101

Note that a major part of this has now been completed in this PR - https://github.com/inventree/InvenTree/pull/6911

Notably, in the new interface, you can navigate to the "admin" section and perform data import there, without the row-count restriction.

Here, you can manage data import sessions (and even come back to them later on, partially complete):

![image](https://github.com/user-attachments/assets/15784859-2825-4f0d-9544-067580436069)

Please try this out on your system and let me know how it goes. This approach is new, and is *much better* than the previous implementation, but there may be some bugs or  issues still.

**Comment by SchrodingersGat** [comment]
Note also that there is another PR to support BOM import using the new approach: https://github.com/inventree/InvenTree/pull/7635

**Comment by bmalatest** [comment]
It looks like there is still a limitation even in the new interface on:
Server Version | 0.16.0 dev
API Version | 217

Specifically trying to import more than 1000 rows for Stock Item (note that I have not tried others such as Parts or Supplier Parts)

**Comment by SchrodingersGat** [comment]
The limitation in the new approach should be `5000` rows. 

![image](https://github.com/user-attachments/assets/ca2a9f57-a77b-4d2a-9d05-9c6a74ba44fd)

Honestly any more than that is going to be very cumbersome to import all at once. I'd suggest breaking the dataset into smaller chunks anyhow.

**Comment by bmalatest** [comment]
Absolutely, I agree and that would definitely work. Thank you!
