### ISSUE TITLE
Docker Installation

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#7633]
I just upgraded my Ubuntu OS from 22.04 to 24.04. The Docker Installation guide has a note that says, "The latest Ubuntu 24.04 LTS is not yet supported. Docker Desktop will fail to start." When will this be taken care of?
--Thanks Larry

**Comment by SchrodingersGat** [comment]
> The Docker Installation guide has a note that says, "The latest Ubuntu 24.04 LTS is not yet supported. Docker Desktop will fail to start."

Do you mean the InvenTree setup guide for docker, or the official docker setup guide itself?

**Comment by LarryJoy** [comment]
So here is how I get to the information: Starting at Docs > Install > Docker > docker installation guide > official installation guide > Docker Desktop for Linux > Ubuntu > Under "Prerequisites" is the Note. It looks like this is the official docker setup guide.

    On Friday, July 12, 2024 at 04:44:40 AM EDT, Oliver ***@***.***> wrote:  



The Docker Installation guide has a note that says, "The latest Ubuntu 24.04 LTS is not yet supported. Docker Desktop will fail to start."


Do you mean the InvenTree setup guide for docker, or the official docker setup guide itself?

**Comment by SchrodingersGat** [comment]
Right, that's in the hands of the ubuntu / docker teams. No idea when that might be supported, and outside the scope of InvenTree for sure!

**Comment by wolflu05** [comment]
Note that you don't need docker "desktop" to use inventree in a production setup with inventree. You only need the docker engine, which should work just fine with ubuntu 24.04 (taken from https://docs.docker.com/engine/install/ubuntu/#os-requirements)

**Comment by SchrodingersGat** [comment]
@wolflu05 good point. Command line docker should be just fine

**Comment by LarryJoy** [comment]
Oliver,I seem to have muddled through downloading the Docker Engine as I get the following message: "Hello from Docker! This message shows that your installation appears to be working correctly."Next I executed "sudo docker pull inventree/inventree." and got "Status: Downloaded newer image for inventree/inventree:latest."Now how do I log into the program? I don't see any instructions to enter on the command line.
    On Friday, July 12, 2024 at 06:24:24 PM EDT, Oliver ***@***.***> wrote:  


@wolflu05 good point. Command line docker should be just fine
