### ISSUE TITLE
[FR] Unused leftover System Settings, CUI only settings and PUI

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#7639]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

The system settings contain a long list of settings, where some actually don't have any effect anymore, and some only for CUI.

E.g the `LABEL_ENABLE` and `REPORT_ENABLE` settings are just defined in the settings model, and available in the system settings in PUI/CUI, but are not referenced anywhere else in the code.

And some settings like e.g. `PART_SHOW_RELATED`, `INVENTREE_REQUIRE_CONFIRM`, `INVENTREE_TREE_DEPTH`, `BARCODE_ENABLE`, `BARCODE_INPUT_DELAY` are UI only settings which are only referenced by CUI. So we should maybe delete this setting if CUI is removed and not needed anymore or re-integrate it into PUI too if reasonable.

### Suggested solution

We should go through the list and check if they are all really used, and remove unused settings to do not confuse people with settings that have no effect.

And also the question for many of these settings: Do we still need all of those when we drop CUI? Having a lot of settings is great on one hand as users can really customize there instance, but having too much settings may also lead to such leftovers and just complicate things where we lost track of what all can be customized.

### Describe alternatives you've considered

/

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
Agreed that there are a bunch of settings we should drop once we move to PUI.

**Comment by SchrodingersGat** [comment]
Still important

**Comment by SchrodingersGat** [comment]
Still important and will be closed out for 1.0.0
