### ISSUE TITLE
Getting Internal Server Error when exporting parts list

### ISSUE THREAD

**Issue by mikeabiz** [inventree/InvenTree#7650]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Trying to export a list of around 1550+ parts.  Whereas before it was working fine, now I am getting an internal server error.
![errors5](https://github.com/user-attachments/assets/a33e8806-c6e2-4e55-a4d4-378c5d9515cc)
![errors4](https://github.com/user-attachments/assets/da044a6b-5b2e-4b70-8a06-1305f1aaf0ae)
![errors3](https://github.com/user-attachments/assets/aef1f4bb-8ab2-4f9f-8a55-b1a9ebf1a9a4)
![errors2](https://github.com/user-attachments/assets/4e004dbd-cc3b-43d5-b230-319bfee2a5ba)
![errors](https://github.com/user-attachments/assets/17405281-1341-4b22-b317-7973f2653628)

Previously working, a couple of additions to the parts and now cannot export.   Error logs on Inventree also posted.
[Part-2024-07-14 (1).csv](https://github.com/user-attachments/files/16221624/Part-2024-07-14.1.csv)

This is my last successful part export

### Steps to Reproduce

Go to admin
Go to Parts
Go to Export

### Expected behaviour

CSV would be generated

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.4
Django Version: 4.2.12

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.10.0-30-amd64-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@mikeabiz this is likely due to the larger dataset taking a while to encode and export. This is an issue that we have addressed in https://github.com/inventree/InvenTree/pull/6911 with a fully refactored import / export workflow. This will be available in the next minor release (`0.16.0`)
