### ISSUE TITLE
Stock count with allocation flags

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#768]
Is there a way to make it so a part that is allocated displays the no-stock or low-stock flags? I know that isn't a 'good' idea but this is just getting the thought train rolling.

Ex. If I have a build with all 1000 of my 10K_0805 resistors are going to be used. I don't see that anywhere that I should need more.

Maybe instead of no-stock or low-stock it should be a different flag for `Will be exhausted if you finish the build. Evaluate this for your next general parts order if you need to buy more`

**Comment by eeintech** [comment]
@a7hybnj2 I would suggest for you to [update your InvenTree instance](https://inventree.readthedocs.io/en/latest/start/update/) and check out the new Index page, it shows a table called "Require Stock to Complete Build" which gather which parts stocks are too low to be able to reach a full build output:

![image](https://user-images.githubusercontent.com/4020546/95806425-40355c80-0ccd-11eb-8b2d-4ec04cc20945.png)

Would that help you to some extent?
