### ISSUE TITLE
Unassigned barcode opens supplier item

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7690]
### Discussed in https://github.com/inventree/InvenTree/discussions/7646

<div type='discussions-op-text'>

<sup>Originally posted by **dieselburner** July 14, 2024</sup>
I have faced rather weird issue and don't know how to fix this. I received my order from Mouser and while scanning received items one by one I have found out some of these gives error about "existing barcode". Surprisingly, scanning barcodes on these few problematic items via Android opens "supplier item", and it's the correct one. I checked the database records, and these supplier items does not have barcode fields set.
So... I assume the system somehow checks the barcode, even if it's not assigned to anything yet, and if it corresponds to supplier item, just reports with error it's already in the system.
I of course can generate my own barcode label to these received items with misbehaving barcodes, but curious if this barcode supplier check can somehow be turned off?

Just to avoid unnecessary questions: the behavior is the same if I configure Mouser barcode plugin to point to Mouser supplier, or not.

Thanks.</div>

**Comment by SchrodingersGat** [comment]
@30350n do you have any input / insight on this one? This probably is related to the extensive supplier barcode support you added

**Comment by 30350n** [comment]
That largely sounds like expected behavior. Barcode plugins should not be checked when trying to assign a barcode though. This was adressed by me in #6162.

So either that got messed up, or @dieselburner actually already (unknowingly) assigned the barcode in question (for example via the `Scan Received Items` functionality).

**Comment by SchrodingersGat** [comment]
@dieselburner please refer to the comments by @30350n above - any chance it could be a workflow issue?

**Comment by dieselburner** [comment]
@30350n Nope, I believe I didn't messed up, since this was a fresh delivery of components, which were never scanned before. This might be related to the issue I posted earlier: https://github.com/inventree/InvenTree/issues/7637
Also, as I wrote:
> I checked the database records, and these supplier items does not have barcode fields set.

**Comment by 30350n** [comment]
If you use the `Scan Received Items` functionality, the scanned barcode will be automatically assigned to the created stock item.

I also checked again and the code from #6162 is still intact.

**Comment by dieselburner** [comment]
@30350n, don't trying to be impolite, but did you went through the issue which I mentioned?

**Comment by 30350n** [comment]
Yeah, looks like you are scanning two different barcodes. If you look at the actual barcode data, it doesn't match at all.

**Comment by dieselburner** [comment]
Yes, the logs I provided are around two different barcodes, which doesn't exist in the database.

**Comment by matmair** [comment]
There is more technical info at https://github.com/inventree/InvenTree/issues/7637 so I think it would be good to address #7637 before checking if this one is still relevant

**Comment by SchrodingersGat** [comment]
Note: The admin interface now shows a history of scanned barcodes - so that would be a great starting point for additional information.

Ref: https://github.com/inventree/InvenTree/pull/8150

**Comment by dieselburner** [comment]
Thanks for pinging this. Today is my first day of unemployment 🎉, so I will dive into this topic again, this week perhaps. I've already collected whole bunch of empty component bags to play around.

**Comment by SchrodingersGat** [comment]
@dieselburner I'm going to close this issue out, but if you do end up discovering something please feel free to ping me again. Best of luck with your unemployment
