### ISSUE TITLE
Check out quantity that is less than tracked unit.. E. g. we are selling textile retail by yard but sometimes can be sold for half a yard

### ISSUE THREAD

**Issue by mikeabiz** [inventree/InvenTree#7713]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

We cannot close orderd that are not whole numbers

### Suggested solution

System can accept different package or variants of it

### Describe alternatives you've considered

as stated

### Do you want to develop this?

- [ ] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/7713">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/7713/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/7713/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@mikeabiz please provide more detail here, there's not much to go on. What sort of order? Sales order ? Purchase Order?

**Comment by mikeabiz** [comment]
Hi Oliver,

Sorry, I meant Sales Order.

We are selling textile by rolls and per yard and sometimes client requests
a per half yard order.  Wanted to understand if this can be done.

Best regards,

**Comment by SchrodingersGat** [comment]
Ok, and what error message are you getting when you try to allocate a quantity of less than 1 to the sales order?

**Comment by mikeabiz** [comment]
Hi Oliver,

Thanks for your email.

Please see below:

[image: image.png]

[image: image.png]
[image: image.png]

We cannot complete the SO transaction.

Thanks.

Best regards,

Mike

**Comment by SchrodingersGat** [comment]
@mikeabiz those images have not embedded correctly, sorry!

**Comment by mikeabiz** [comment]
Hi Oliver,

Please see attached.

Best regards,

Mike

**Comment by matmair** [comment]
@mikeabiz you need to upload the files within Github.com via the link provided in the footer of the mails. Attachments do not get transferred.

**Comment by mikeabiz** [comment]
HI.  Thanks for the help but managed to circumvent the issue.  Please close
the request.
