### ISSUE TITLE
The time zone setting instructions in the document are very unclear. We strongly recommend the production team to improve the document!

### ISSUE THREAD

**Issue by zly20129** [inventree/InvenTree#7726]
### Body of the issue

In the document, there is only a short section of instructions for setting the time zone INVENTREE_TIMEZONE, which roughly tells users to check Wikipedia. However, there is no format explanation at all, which makes it very unfriendly for non professional enthusiasts.
For example, in Chinese Mainland, setting the CST time zone is not allowed. You must use Asia/Shanghai to set the time zone, and there are strict requirements for the format. You must add a single quotation mark to make the server run correctly.
There is no explanation of the format in the document, which has taken me a lot of detours and is very exhausting. You can refer to my written record of stepping into pitfalls, the link is as follows.
https://github.com/inventree/InvenTree/discussions/7725

**Comment by matmair** [comment]
There is a link to the table with the correct identifiers in the column "tz identifiers" directly above the value in the config file. I am not sure how this can be documented clearler.
https://github.com/inventree/InvenTree/blob/b10a20d1ef6140f84cb0853a36e98cee50d2090b/src/backend/InvenTree/config_template.yaml#L44-L48

CST is not an international timezone but an often-used abbreviation for multiple time zones in Asia and the Americas. Timezones are standardised by IANA and that is what we also use.
Formatting for all values has to follow either bash or yaml formatting rules depending on the used config method. These are system defaults in POSIX style OSes that we adhere to.

**Comment by zly20129** [comment]
> There is a link to the table with the correct identifiers in the column "tz identifiers" directly above the value in the config file. I am not sure how this can be documented clearler.
> 
> https://github.com/inventree/InvenTree/blob/b10a20d1ef6140f84cb0853a36e98cee50d2090b/src/backend/InvenTree/config_template.yaml#L44-L48
> 
> CST is not an international timezone but an often-used abbreviation for multiple time zones in Asia and the Americas. Timezones are standardised by IANA and that is what we also use. Formatting for all values has to follow either bash or yaml formatting rules depending on the used config method. These are system defaults in POSIX style OSes that we adhere to.

Regarding the configuration documentation, I read it carefully.
But neither the config docs nor the web docs, I didn't find any relevant examples or such instructions, which I think is not very friendly for non-professional developers, so I would like to suggest adding some examples to illustrate this part.
I myself, for example, rarely develop OS-related software, specializing in industrial control, and I really encountered too many difficulties in debugging the InvenTree system.
Including today, I encountered a label printing can not support the Chinese problem, with a number of ways to find no solution, I intend to submit another problem later.

**Comment by matmair** [comment]
You are welcome to submit PRs that add the information you deem to be missing.

**Comment by zly20129** [comment]
> You are welcome to submit PRs that add the information you deem to be missing.

Okay, I'll add some help content and then submit an MR request after I've solved all the problems I've had so far.

Thank you very much for your help, I will be submitting a new question later and would like to ask you to continue guiding me.

**Comment by zly20129** [comment]
> You are welcome to submit PRs that add the information you deem to be missing.

By the way, I would also like to ask where the web-doc document can be submitted for MR requests?

**Comment by SchrodingersGat** [comment]
@zly20129 the documentation for InvenTree is in this repository too, located in the "docs/" directory

**Comment by zly20129** [comment]
> @zly20129 the documentation for InvenTree is in this repository too, located in the "docs/" directory

Okay, thank you. After I finish exploring the project, I will try to add some explanations, but after the translation, I am currently working hard to help complete the remaining Chinese translation of the project.
