### ISSUE TITLE
Suggest adding a Chinese translation to the document.

### ISSUE THREAD

**Issue by zly20129** [inventree/InvenTree#7728]
### Discussed in https://github.com/inventree/InvenTree/discussions/7727

<div type='discussions-op-text'>

<sup>Originally posted by **zly20129** July 24, 2024</sup>
Since translation support can be added to the server, can translation also be added to the help document?
This is not limited to Chinese, but can also add multiple languages to help people read documents faster and understand various functions.</div>

**Comment by matmair** [comment]
We, as a project, do not demonstrate the bandwidth to keep the UI translations fully up to date, so adding doc translations seems unreasonable at this point.
The language of the project internals is English and I think that is the only way that makes sense currently. Thoughts @SchrodingersGat ?

**Comment by zly20129** [comment]
> We, as a project, do not demonstrate the bandwidth to keep the UI translations fully up to date, so adding doc translations seems unreasonable at this point. The language of the project internals is English and I think that is the only way that makes sense currently. Thoughts @SchrodingersGat ?

Thank you very much for the clarification, but I still expect that multilingual support for documentation pages will be added in the future, and I'd be more than happy to provide some help in translating the documentation.

**Comment by SchrodingersGat** [comment]
As @matmair says, the project pages (i.e. what is hosted here on GitHub) is English only. 

Our [project documentation](https://docs.inventree.org) could *theoretically* be translated but currently is English only, and would require significant effort to add different languages to. This would have to be driven and managed by particular project contributors to manage the translations. At this stage, no one has stepped up to take the lead on this.

**Comment by zly20129** [comment]
> As @matmair says, the project pages (i.e. what is hosted here on GitHub) is English only.
> 
> Our [project documentation](https://docs.inventree.org) could _theoretically_ be translated but currently is English only, and would require significant effort to add different languages to. This would have to be driven and managed by particular project contributors to manage the translations. At this stage, no one has stepped up to take the lead on this.

Haha, I'll hope a big brother to show up!

My English is not very good and it took me a super long time to learn the documentation completely, it's really too hard.
