### ISSUE TITLE
CentOS Stream support for InvenTree

### ISSUE THREAD

**Issue by 15885566436** [inventree/InvenTree#7782]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [X] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

安装不了 InvenTree 

### Steps to Reproduce

[root@localhost ~]# wget -qO install.sh https://get.inventree.org && bash install.sh
### Distribution not supported
This OS is currently not supported.
Please install manually using https://docs.inventree.org/en/stable/start/install/
or check https://github.com/inventree/InvenTree/issues/3836 for packaging for your OS.
If you think this is a bug please file an issue at
https://github.com/inventree/InvenTree/issues/new?template=install.yaml
[root@localhost ~]# 

### Relevant log output

```bash
[root@localhost ~]# wget -qO install.sh https://get.inventree.org && bash install.sh
### Installer for InvenTree - source: inventree/stable
### Detected distribution: CentOS Stream 8
### Distribution not supported
This OS is currently not supported.
Please install manually using https://docs.inventree.org/en/stable/start/install/
or check https://github.com/inventree/InvenTree/issues/3836 for packaging for your OS.
If you think this is a bug please file an issue at
https://github.com/inventree/InvenTree/issues/new?template=install.yaml
[root@localhost ~]#
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/7782">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/7782/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/7782/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
@15885566436 please only submit issues to our GitHub in English - this is the only common language of the development team and issues submitted in other languages may not be addressed.

Regarding CentOS support: Currently our installer supports Debian / Ubuntu - as per our documentation:

https://docs.inventree.org/en/stable/start/installer/#installer

If you would like to see CentOS support, perhaps you have the ability to provide an update to our installer to support this OS? Or, you may be willing to sponsor this issue so that one of our developers can look into this.

**Comment by matmair** [comment]
We are not packaging for RPM now, only the Debian-based OS family is supported.

**Comment by 15885566436** [comment]
Oh, I see, thank you.
&nbsp;


weibuan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Matthias ***@***.***&gt;; 
发送时间: 2024年8月1日(星期四) 下午2:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [inventree/InvenTree] 安装 InvenTree 报错 (Issue #7782)















我们现在没有为RPM打包，只支持基于Debian的OS系列。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.***&gt;
