### ISSUE TITLE
[FR]Hierarchial test templates?

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#7804]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

We make some badge engineered products what we handle as different parts in InvenTree.
The parts are technically the same so they have the same tests (test templates).
If we improve the test result visualization then it would be great if there would be a possibility to  have statistics per test template which would include all results from all product variations. 

### Suggested solution

Changing part - test template assignment from one to many to many to many (decouple the templates from parts).
I know this could be a lot of work.

Making some relation between the test templates.

I brought this up for discussion purposes to see if there is anyone walking in the same boot, or there is a recommended workaround what did not came into my mind,

### Describe alternatives you've considered

Workarounding it with BoM tricks: adding the same subassembly to each customer parts.
There are some corner cases where this is problematic: different cable lengths, connectors, etc.

### Examples of other systems

-

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
Perhaps I am not underestanding correctly, but test templates are already "inherited" by part variants.

That is, if you define a "template" part, and define some test templates for that part, those templates are available for any part which is a "variant" of the template.
