### ISSUE TITLE
[FR]Add link to the filtered stock items under the in stock and in production badges

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#7805]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

We have these two nice and shiny badges in the PUI:
![kép](https://github.com/user-attachments/assets/787f7d8b-aa5a-4e63-bef7-e993e9342ea7)
which could be made more useful if they could be clickable and would redirect to the stock view filtered by the production/stock state. 

### Suggested solution

I am poking around similar (changing of the tables filtering without user intervention), if I sort that out I am fairly sure I can implement it.

The question is how to handle the case if filtering is already setup on the stock list:
- Clear the setup filters and set the in stock/in production filters
- Merge the in stock/in production to the filter setup.

@matmair , @SchrodingersGat what do you think about this?

### Describe alternatives you've considered

this field cannot left empty ;)

### Examples of other systems

-

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
I do not think it makes sense to have those buttons clickable. It is not obvious from the location of those buttons what that click would do.

However, in the table shown in your image, you could click on the "Status" column to filter by a given status type. While this is not *currently* possible it is definitely on the road map - and could use some help for sure.

This is related to the discussion over here - https://github.com/inventree/InvenTree/discussions/7806#discussioncomment-10235017
