### ISSUE TITLE
Chinese translation file merging

### ISSUE THREAD

**Issue by simple51** [inventree/InvenTree#7814]
### Body of the issue

Upload the complete Chinese translation file
![Uploading Snipaste_2024-08-06_09-24-37.jpg…]()

**Comment by SchrodingersGat** [comment]
@simple51 your image has not come through here.

Note that for any translation efforts, refer to our [crowdin page](https://crowdin.com/project/inventree)

**Comment by matmair** [comment]
@SchrodingersGat can we close this?
