### ISSUE TITLE
Missing API endpoint

### ISSUE THREAD

**Issue by Con30** [inventree/InvenTree#7818]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

From version 0.15.7 to 0.16.0 the API endpoint GET /api/part/attachment/ is missing

### Steps to Reproduce

View documentation or /api-doc/ to see that /api/part/attachment no longer exists

### Expected behaviour

/api/part/attachment exists

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.0 dev
Django Version: 4.2.14
Commit Hash: 6937b3a
Commit Date: 2024-08-05
Commit Branch: master
Database: postgresql
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
Installer: GIT

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
Here are the current API docs https://demo.inventree.org/api-doc/#tag/attachment
