### ISSUE TITLE
E: Unable to locate package inventree

### ISSUE THREAD

**Issue by iamkittykat** [inventree/InvenTree#7857]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I've got this error while trying to install it with the downloader.(it says that it doesn't work on arm64)

### Steps to Reproduce

1. Run the installer,
![image](https://github.com/user-attachments/assets/02dd7832-6789-4c9a-8c25-5491f827a0b3)

### Expected behaviour

It should install the package.

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

N/A

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
### Installer for InvenTree - source: inventree/stable
### Detected distribution: Ubuntu 20.04
### Installing required packages for download
### Getting and adding key
### Adding package source
### Updating package lists
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Get:5 https://dl.packager.io/srv/deb/inventree/InvenTree/stable/ubuntu 20.04 InRelease [1863 B]
Fetched 1863 B in 2s (1137 B/s)    
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://dl.packager.io/srv/deb/inventree/InvenTree/stable/ubuntu 20.04 InRelease' doesn't support architecture 'arm64'
### Setting installer args
### Installing InvenTree
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package inventree
```

**Comment by matmair** [comment]
We do not support arm64 architecture - as stated by the error

**Comment by Gasman2014** [comment]
Is there a list of supported architecture / hardware requirements? I'm considering this to replace PartKeepr but would like to run it on a stand alone SBC - which I suspect is not an uncommon plan for hobbyist/small companies. I want something small and cheap - I hit the same error as @iamkittykat when installing on a Pi but it was not until I got to this stage that it was apparent that it was unsupported - even though I run PartKeepr on the same hardware. It would save some pain and annoyance to discover this ahead of the hard stop. I'm not complaining about the limitation - just not knowing about it. A obvious minimum hardware spec would be helpful.
