### ISSUE TITLE
Is there a list of known units?

### ISSUE THREAD

**Issue by LiarOnce** [inventree/InvenTree#7858]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I was hoping to add "box" as a custom unit and got an error.
I think it's a custom unit but I can't add it.

### Steps to Reproduce

1. Go to Settings page
2. Go to Physical Units
3. Add a Unit
4. Name is `Box`, Definition is `box`
5. Definition got an error: `'box' is not defined in the unit registry`

### Expected behaviour

Successfully added this unit

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.17.0 dev
Django Version: 4.2.14

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-6.1.0-23-amd64-x86_64-with-glibc2.36
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by tristanle22** [comment]
So if I want to add a new unit "box", its definition has to be one of the known units?

**Comment by SchrodingersGat** [comment]
You can create custom units - https://docs.inventree.org/en/stable/concepts/units/?h=units#custom-units

**Comment by tristanle22** [comment]
I got it now! Just have to provide the definition based on an existing unit in the UnitRegistry. For example, to create the "box" unit, I put "count" as definition.
