### ISSUE TITLE
[FR] Improve page titles for PUI

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7869]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Currently the page title only shows the instance name, and does not reflect the content of the current view.

This means that the "history" tab in the browser is not very useful:

![image](https://github.com/user-attachments/assets/7cc229f3-4893-4dee-8f9b-947781c0b5b8)

### Suggested solution

- Display information on the current "route" in the page title

### Describe alternatives you've considered

N/A

### Examples of other systems

N/A

### Do you want to develop this?

- [X] I want to develop this.

**Comment by ATLAS2246** [comment]
I'd like to try this as a learning task, is that ok?

**Comment by SchrodingersGat** [comment]
@ATLAS2246 absolutely :) your contribution would be warmly welcomed

**Comment by SchrodingersGat** [comment]
@ATLAS2246 did you ever get anywhere with this?
