### ISSUE TITLE
The results of the crowdin translation are not synchronized into the github file

### ISSUE THREAD

**Issue by skyyearxp** [inventree/InvenTree#7873]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

chinese translation show 99% complete, but demo app or github main branch file not show the translation result.

for example:
words: Customer Reference
https://crowdin.com/editor/inventree/216/en-zhcn?view=comfortable&filter=basic&value=0#q=Customer%20Reference 
https://github.com/inventree/InvenTree/blob/master/src/backend/InvenTree/locale/zh_Hans/LC_MESSAGES/django.po

### Steps to Reproduce

another example:
words: "Revision"
https://crowdin.com/editor/inventree/216/en-zhcn?view=comfortable&filter=basic&value=0#q=%22Revision%22
https://github.com/inventree/InvenTree/blob/master/src/backend/InvenTree/locale/zh_Hans/LC_MESSAGES/django.po

### Expected behaviour

the approved translation in crowdin can be apply into github file

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

docker stable version install. but the github main branch file also missing the translation result.

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
There seems to be a mismatch between language codes in the pipeline. Using the zh language code should work as a break gap while we figure this out.

**Comment by SchrodingersGat** [comment]
It looks like for "chinese simplified":

- Crowdin uses `zh`
- Django uses `zh_hans`

I think that we can get Crowdin to remap the output for a single language - I'll give that a go and see if it works

**Comment by matmair** [comment]
@SchrodingersGat I have already fixed the mapping - PR incoming

**Comment by SchrodingersGat** [comment]
@matmair I am not sure that a simple merge will be sufficient here - the incoming translation files from crowdin need to be "remapped". I *think* that I am close to getting this working as expected.

**Comment by SchrodingersGat** [comment]
@skyyearxp thanks for raising this - we have worked out why this is happening and issued a fix. 

You should see updates to the `master` and `0.16.x` branches soon :)

**Comment by skyyearxp** [comment]
thanks, i have seen the updates. Can I manually apply django.po to the stable version in docker? I have copied the django.po into the docker through the docker cp. Do I still need to execute the compilation instructions? thanks.
