### ISSUE TITLE
[FR] Asking for multi choices at Component and Assembly features

### ISSUE THREAD

**Issue by vhminhquan** [inventree/InvenTree#7890]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Hi guys,
First of all, i would like to say thank you about your project. It is extremely helpful.
When using it in my circumstances, i have realized that "Component" and "Assembly" features just allow 1 choice ( Parts can be used as sub-components // Parts can be assembled from other components ).
At my case, for example : A hard drive can be related to more than 2 or 3 4 5 different devices ( E.X : server A , storage B ).
So it would be a huge help if you could allow these features to be selected more than 1.
Thank you!

### Suggested solution

allow multi-choices at Component and Assembly

### Describe alternatives you've considered

Hi guys,
First of all, i would like to say thank you about your project. It is extremely helpful.
When using it in my circumstances, i have realized that "Component" and "Assembly" features just allow 1 choice ( Parts can be used as sub-components // Parts can be assembled from other components ).
At my case, for example : A hard drive can be related to more than 2 or 3 4 5 different devices ( E.X : server A , storage B ).
So it would be a huge help if you could allow these features to be selected more than 1.
Thank you!

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
You can use parts in as many assemblies as you want
