### ISSUE TITLE
Price showing as "None" when trying to import price information via part import

### ISSUE THREAD

**Issue by realstudent01** [inventree/InvenTree#7896]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

On the admin page, when importing parts if the Minimum and/or Maximum Cost fields have data in the csv file that data does not get attached to the part and in InvenTree.

### Steps to Reproduce

1. Export parts from admin page
2. Edit the exported CSV to remove most parts
3. Add data for the Minimum Cost and Maximum Cost columns
4. Import the file from the parts admin page
5. The columns appear as None

### Expected behaviour

The columns should show the numerical data from the file being imported

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

0.15.7

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Can't reproduce on demo site because I can't get to the part admin page
```

**Comment by SchrodingersGat** [comment]
This is because the pricing information is in a different table in the database, so the pricing data has to be imported separately (after the part data).

**Comment by realstudent01** [comment]
Is it possible for an importing CSV option to be added similar to how there is for parts and parameters?

Also, can this CSV import feature be added for creating part relationships?

**Comment by matmair** [comment]
This type of import is being removed entirely, I do not think we should spend time on it. See https://github.com/inventree/InvenTree/pull/6911

**Comment by realstudent01** [comment]
What will be the method for importing large numbers of parts and parameters at once once it is changed to this? Right now it's very inconvenient to have to click multiple buttons to add each part when they are stored in mass in a CSV.
