### ISSUE TITLE
[Qestion] Manual translation update 

### ISSUE THREAD

**Issue by Dark-V** [inventree/InvenTree#7968]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I have issue with russian translation, i added it by crowdin and trying to update with chatgpt help (due no knowledge with how translition works), after i copied a files from crowdin (messages.go and smth else), trying to local build, but after updated and restart in inventree i didnt found any my translation. 

### Suggested solution

in my case, update a crowdin, export trans files, build, restart, got new translition.

### Describe alternatives you've considered

-

### Examples of other systems

it's also look like, all russian translition avaible at new UI, but doesnt update at old version. (i can't use new UI, due it's not in release, and is not good working with QR codes for stock managment only)

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
A manual ingestion of translations is not part of our workflow design, I would not recommend it.
