### ISSUE TITLE
Invalid block tag 'transa' in "settings/parts"

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#797]
When loading: http://localhost:8000/settings/part

I get this error:
```
Request Method: | GET
-- | --
http://localhost:8000/settings/part
3.0.5
TemplateSyntaxError
Invalid block tag on line 9: 'transa', expected 'endblock'. Did you forget to register or load this tag?
```

I just pulled fresh code from github:
![image](https://user-images.githubusercontent.com/4020546/81590967-466f8780-9381-11ea-8011-cde2f14b1e00.png)

Is it better to stick to the last release?

**Comment by SchrodingersGat** [comment]
Hey thanks for raising this. Generally speaking you should be good to run off latest `master` commit, you shouldn't need to stick to the release versions. I try not to introduce *known* broken things into master ;)
