### ISSUE TITLE
[FR] Hide parts in child categories

### ISSUE THREAD

**Issue by realstudent01** [inventree/InvenTree#7970]
When inside a category with subcategories, when viewing the parts tab it displays parts in the current category and parts in the child categories by default. I think it would be great to offer the tree structure option that is provided when looking at the main categories page. Or only show parts when you're in the subcategory in which they are housed.

**Comment by matmair** [comment]
Please use the [feature request template](https://github.com/inventree/InvenTree/issues/new?assignees=&labels=enhancement%2Ctriage%3Anot-checked&projects=&template=feature_request.yaml&title=%5BFR%5D+title) for requests.

This is also already implemented
![grafik](https://github.com/user-attachments/assets/449b2602-7665-49be-abed-60d57f86b954)
![grafik](https://github.com/user-attachments/assets/a4f0066c-ffa8-4965-bc36-b6279bb68770)
