### ISSUE TITLE
[PUI] Markdown Horizontal Dividers in Notes not parsed correctly in platform UI

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#7973]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

We used a lot of horizontal dividers (three dashes like ```---```) in the notes field throughout inventree. In the new platform UI those seem to not be escaped correctly as the rendered notes text field cut off everything after the first of these horizontal dividers. 

### Steps to Reproduce

1. in the old UI add a line with three dashes like ```---``` to a notes field with more text before and after this line
2. view the note in the new UI
3. only text from before the divider is rendered (both in ```view``` and in ```edit``` mode)

### Expected behaviour

properly parse/escape three dashes to account for legacy content in the database from before the PUI upgrade

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.17.0 dev
Django Version: 4.2.15
Commit Hash: 5515e07
Commit Date: 2024-08-20

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-rpi7-rpi-v8-aarch64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'IPNAutoGenerator', 'slug': 'ipnautogenerator', 'version': None}, {'name': 'OrderNotesTemplates', 'slug': 'ordernotestemplates', 'version': None}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.9.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
Can reproduce - thank you for the report @simonkuehling !

**Comment by SchrodingersGat** [comment]
I have raised a question on the MDXEditor repo as the behaviour in unexpected - https://github.com/mdx-editor/editor/issues/572
