### ISSUE TITLE
Custom Stock Status cannot be set from Stock Actions

### ISSUE THREAD

**Issue by gunstr** [inventree/InvenTree#7990]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

A configured custom stock status such as "TestState" is not visible in the drop down list in the StockAction modal.

I can set the TestState on an item from the Edit Stock Item modal but I noticed that if then TestState is selected as a filter to the Stock Item list no itmes are visble. I do not know if this is related or maybe it should be a separate issue?

### Steps to Reproduce

This test is done on the Demo site only, I have not installed PUI locally yet.

1. Create a Custom Stock status
2. Open the Stock Items list, click Stock Actions and select Change Stock Status

![image](https://github.com/user-attachments/assets/04c3d97e-0fc8-4e65-9168-3d747bb78b67)

3. In the Status dropdown the TestState option is not visible

![image](https://github.com/user-attachments/assets/8812dfc8-9063-48a2-aa27-25842f2cc9dc)

### Expected behaviour

It should be possible to set custom stock status also from the Stock Action modal

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [X] Other - added info in Steps to Reproduce

### Version Information

InvenTree-Version: 0.17.0 dev
Django Version: 4.2.15
Commit Hash: 6951748
Commit Date: 2024-08-25
Commit Branch: null
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-100-generic-x86_64-with
Installer: DOC
nullActive plugins: false

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@gunstr thanks for reporting, we will have to look into this

**Comment by matmair** [comment]
@SchrodingersGat can we move this to 1.0?

**Comment by SchrodingersGat** [comment]
@matmair sure, it requires a bit more attention and I would like to get the new release out.

**Comment by gunstr** [comment]
@SchrodingersGat @matmair is your recommendation not to use the cusom states at all until you have worket this trough a bit more?

**Comment by SchrodingersGat** [comment]
@gunstr I think that for this particular issue, you can manually adjust the stock status per stock item, rather than as a group?

**Comment by gunstr** [comment]
@SchrodingersGat Yes, for the UI related issues that is probably OK. I have seen your discussion on the implementation in general and got a bit worried that updating all current stock items with custom states at this stage might be waste of time - but maybe that would not be the case...

As you might remember from previous discussions I pach my local installations for each upgrde with more relevant status names and I'm really looking forward to skip that and use the custom states instead. A few limitations in the UI is OK as long as there are work arounds.

**Comment by SchrodingersGat** [comment]
@gunstr yes that does sound like a separate issue - please create a new one with as much information as you cna provide

**Comment by SchrodingersGat** [comment]
@gunstr this has now been resolved in https://github.com/inventree/InvenTree/pull/8438 which will be in the next major release

**Comment by gunstr** [comment]
Thanks a lot @SchrodingersGat  I appreciate all your work and look forward to start to use the custom status featute after the next release.
