### ISSUE TITLE
Expansion on "template part" implementation

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#801]
Currently parts can be "templates" which mean that other parts are "variants" of the template. Stock of the variants are counted towards stock of the template.

This should be expanded so that parts can be related in a "tree" structure, with arbitrary depths of variants / etc.

Stock for any part is then the sum of all parts underneath it. Using the existing MPTT structure this is pretty cheap to compute.

The real advantage comes with adding this concept to the build / bom / order models. For example, if you add a part to a BOM, then when it comes time to assign stock for a build, then stock for any part UNDER the selected BOM line can be chosen!

Same goes for orders, when assiging stock items.

Validation of serial numbers should also observe the "tree" structure - a serial number must be unique across the entire tree. 

The purpose of a "template" part is then to indicate that the given part (at any point in the tree, really) cannot have stock or be assigned to an order / build / etc etc

**Comment by rco3** [comment]
I'm starting to believe that my understanding of the purpose and usage of the Template / Variant system is incorrect.  

The use of terms 'Template' and 'Variant' suggest to me that there is a skeleton of a part description, the Template, and that instances of parts ('Variants') can be generated by varying additional part parameters.  Example: if I have a template for #8-32 316SS Philips Round Head screws, I could then create a Part (as a Variant from that Template) with the length added to Keywords (and perhaps a Parameter), to generate a #8-32 x 1/2" 316SS Philips Round Head screw.  I would then be able to go to McMaster-Carr, find a screw that fit these needs, and create a SupplierPart for that part.  That SupplierPart would be assigned to the new Part I created, the #8-32 x 1/2" 316SS Philips Round Head screw, and then when the new Stock arrived from McMaster I could enter that as a new Stock Item.

However, this understanding / usage pattern is at odds with the suggestion that any part which is a Variant of my #8-32 316SS Philips Round Head screw Template can be used as Stock for that Template Part. Clearly, either a 1/4" or a 3" version of that screw are unlikely to be a suitable replacement.  So, the way I've understood the use of Templates and Variants doesn't fit with that idea.

The implication of all Variant parts being usable as Stock for the parent Template is that they all have similar characteristics, and thus are likely to be competing vendors' versions of the same 'part'.  This feels like a structure to allow for multiple vendors to supply parts which can be used in the same application.  But, that already exists - you can already assign multiple SupplierParts to a single Part.  So... what am I missing?

**Comment by chschlue** [comment]
I thought it was supposed to be used like
```
category cap -> cat 0603 -> cat x7r -> template 100n 25V -> variants (the yageo and the kemet one) -> supplier parts (mouser and digikey part numbers for each)
```

**Comment by rco3** [comment]
That seems a logical way to do it.  That puts a more or less 1-to-1 correspondence between Part Variant and MPN.  However, Manufacturer and MPN are attributes of a SupplierPart, not a Part.  How do I distinguish each Variant of that Template as being a Yageo, or a Kemet?

Seems like, in that usage, the Template should have PartParameters of 'Capacitance = 100n Farads' and 'Voltage = 25 Volts' set, and each Variant should inherit those same parameters and values.

**Comment by chschlue** [comment]
We probably have it both wrong and should wait for the Word of God @SchrodingersGat :)

**Comment by rco3** [comment]
I've been preparing some stone tablets...

**Comment by SchrodingersGat** [comment]
Ok, sorry for the delay on a response here guys. This may be a difficult concept for me to convey easily, but here goes!

Eventually this will all make it into the documentation...

Perhaps the easiest way to explain this is to explain how I use this in practice at my company.

We have a product we make and sell, let's called it a "Widget". However, customers do not order a "Widget" - they instead order a "variant" of the widget which depends on their particular specifications.

For example, they may wish to select:

- Power rating
- Enclosure style
- Supplied connectors
- etc etc

So, we have a template part called "Widget", and variants of this part called "Widget-01", "Widget-02", "Widget-03" (etc)

However instead of being explicitly named "Widget-01", the variant field is set to "01" and the name field is still "Widget" (like the parent template part).

So, what advantage does the template concept confer? Templates (and their variants) have some unique properties which are advantageous for certain use cases:

## Serial Numbering

Serial numbers must be unique across an entire template-tree - this means that any "variants" under a template part must have unique serial numbers, so you cannot have Widget-01 #001 and Widget-02 #001

## Testing

Unit test templates that are defined for a template part "flow down" to variant parts, so you can make a template part which has some test templates defined, they apply to any variants

## BOM

Templates allow some flexibility in BOM assignment. Let's say you have an assembly that requires 1xWidget in the Bill of Materials. As Widget-01 is strictly a variant of Widget, it can be used in the BOM. But it does not work the other way (Widget cannot be substituted for Widget-01)

(*Note: This BOM substitution feature is not actually implemented yet*)

## Contrast to Supplier Parts

Supplier Parts and Variants are strictly different things. Supplier parts link external supplier SKUs to an internal Part object. A purchaseable part can have multiple (or none) supplier part links.

However, Templates / Variants are more for managing internal parts definitions.


Does this make sense? I hope this feature is useful, I have tried to make it generic. However it was developed to meet an internal requirement at our company.

**Comment by SchrodingersGat** [comment]
This has now been implemented (for quite some time)
