### ISSUE TITLE
[FR]Simplify displayed part name if IPN and part name equals

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#8011]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

With the default part name template the part names looks the following in the case if the IPN and the part name equals:
![kép](https://github.com/user-attachments/assets/959f029d-e801-4faa-bf9d-bf26068b46d2)
which is kind of weird.

### Suggested solution

Changing the value of the PART_NAME_FORMAT from the default:
```
{{ part.IPN if part.IPN }}{{ ' | ' if part.IPN }}{{ part.name }}{{ ' | ' if part.revision }}{{ part.revision if part.revision }}
```
to 
```
{{ part.IPN if part.IPN and part.name != part.IPN}}{{ ' | ' if part.IPN and part.name != part.IPN}}{{ part.name }}{{ ' | ' if part.revision }}{{ part.revision if part.revision }}
```

I think it would be useful to change the default value, and the fallback would also be useful to change:
https://github.com/inventree/InvenTree/blob/master/src/backend/InvenTree/part/helpers.py#L76

### Describe alternatives you've considered

Using different IPN and part name ;)

### Examples of other systems

-

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
I am against changing the default, you can already set it up the way you like with the provided mechansim.

**Comment by SchrodingersGat** [comment]
Agreed, I think this makes the default "more" complicated.
