### ISSUE TITLE
Typo in template "Isueue Build"

### ISSUE THREAD

**Issue by Petrox** [inventree/InvenTree#8049]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

While working on HU translation typo found:

Identifier (Key): Isueue Build
Context: #: build/templates/build/build_base.html:87

### Steps to Reproduce

While working on HU translation typo found:

Identifier (Key): Isueue Build
Context: #: build/templates/build/build_base.html:87

### Expected behaviour

Issue Build

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

master

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
Thanks for the report @Petrox, it will be corrected shortly.
