### ISSUE TITLE
Install Problem On My Ubuntu 22.04 OS

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#8060]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Often times there are error messages when downloading and installing pieces of InvenTree and there is nobody to talk to about the situation, to give direction as what to do to alleviate the situation. For instance I have Docker loaded but I don't know if it is in the correct place. I am willing to make a one-time donation to InvenTree if someone would work with me one-on-one so I can get InvenTree running. I am not a programmer myself and so I would need explicit terminal commands to carry out.

### Steps to Reproduce

0. I am trying to follow the instructions as given in the Deployment section for the Docker method. 1. Whoever I work with I will carry out their instructions and report back the results I get. Would need to start from scratch.

**Comment by timmyhadwen** [comment]
@LarryJoy Let me know what issues you're having? We run docker Inventree on 22.04 so I might be able to help :)

**Comment by LarryJoy** [comment]
I have Docker (and I think it's called Docker-editor, or something like that) installed. I have InvenTree downloaded. Trying to follow the instructions in the documentation just doesn't work. I need step by step (terminal commands) instructions that I can implement, and when something doesn't work I need to be able to report back to someone that can get me going on the right path. If you'll stick with me I will follow the information as I understand it and report the results, good or bad, back to you. I guess I wouldn't have to give you the good report only the bad stuff when I run across it. I will try again tomorrow to set it up.

**Comment by LarryJoy** [comment]
Further: By default, Docker Desktop is installed at /opt/docker-desktop. NO! It is not there.

**Comment by SchrodingersGat** [comment]
@LarryJoy as a starting point to get docker engine installed, the following tutorial should work: 

- https://docs.docker.com/engine/install/ubuntu/

**Comment by LarryJoy** [comment]
I think I have downloaded/installed everything I need. My problem now is when I go to http://inventree.localhost it goes to the Apache2 screen instead of to InvenTree. So, what do I check and what do I do? I guess I can follow your link, follow the instructions to remove files, and then install the files again. I guess I would try that unless someone can give me directions to resolve the Apache2/InvenTree conflict. Thank you.

**Comment by SchrodingersGat** [comment]
> I think I have downloaded/installed everything I need. My problem now is when I go to http://inventree.localhost/ it goes to the Apache2 screen instead of to InvenTree

This would likely indicate that you have an apache server which is already running, and taking control of your web port (80).

So you can either:

1) Disable the apache server 
2) host InvenTree on a different port.

I would think 2) is simpler at this stage. You can try adding `INVENTREE_WEB_PORT=1337` in your `.env` file, and then reloading the InvenTree server. Then, nominally you should be able to see your InvenTree server at `inventree.localhost:1337` in your browser

**Comment by LarryJoy** [comment]
Hello, InvenTree is up ad running for me for a couple of months now. I got my answers from JustAnswer for which I paid for. I would have paid someone at InvenTree but nobody would work with me one-on-one.
