### ISSUE TITLE
[BUG/FR?] decimal separator inconsistencies between English/German localisations

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#8067]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

when running the interface in ```German```, I can input decimal numbers with both colons ```,```or dots ```.``` as decimal separator. Using the interface in ```English``` only dots are recognized (colons are stripped).

We use InvenTree in English translation usually, but often copy&paste pricing and other information from german websites/shops and need to adjust each entry manually when doing so.

### Steps to Reproduce

1. add a price break like to a supplier part with either a colon or a dot as decimal separator (like ```1.35``` and ```1,35```)
2. save

### Expected behaviour

Not sure if the German behavior is a bug or a feature - but it is certainly very helpful. Would there be downsides to also allow both separators in other languages including English as well?

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

Development Version
InvenTree Version	
[0.17.0 dev](https://github.com/inventree/InvenTree/releases)
Commit Hash	
f144158
Commit Date	
2024-09-03
Commit Branch	
API Version	
[249](http://192.168.177.12/api-doc/)
Python Version	
3.11.9
Django Version	
[4.2.15](https://www.djangoproject.com/)

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
The input methods follow the convention for the language as set by JS intl framework. For German that allows inputs in both ways, for English not. While I understand your point as a German-speaking person myself, I do not think it makes sense to introduce extra complexity in this area.
German is at 90%+ translation - is there a reason you use English instead?

**Comment by simonkuehling** [comment]
The main reason for us to use English is that the process relevant keywords throughout the app are somewhat more concise than the german translation (but we are in lack of better translations to suggest at the moment) - like for example "Stock Item" vs "Lagerartikel". "Lagerartikel" does have the connotation of "an article that is usually in stock" as a common use in onlineshops etc. Also, it is easier to keep internal development ideas and bug reports matching the original english terms that way - there is less that gets lost/confused when talking about those topics...

We will keep thinking about the translation and are happy to post suggestions if we happen to find improvements to the wording at any time!

But i totally see that this is a very individual "problem" for us and not really relevant for the general user - so I'm fine to close this...

**Comment by wolflu05** [comment]
I'm using the English version myself as a German. Maybe we can separate the settings for number/date style and user interface language.
