### ISSUE TITLE
Image File Upload button click opens both the image and the upload modal on top of each other

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#8068]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

In the PUI I cannot upload image files for parts etc at the moment. when hovering the image and clicking the "Upload new image" icon, it seems to issue the "view image in large" and the "upload new file" windows/modals both on top of each other.

### Steps to Reproduce

1. hover over image
![grafik](https://github.com/user-attachments/assets/b64b7376-836e-4ee7-8211-25dc716c79b4)

2. click "upload new image" icon
![grafik](https://github.com/user-attachments/assets/e418ddbe-e501-48d6-896e-b90d2a809e09)

3. hit ESC to close the image and reveal the upload screen behind it
![grafik](https://github.com/user-attachments/assets/394fc397-22ea-4138-9e8f-65bd2d95cfb5)

### Expected behaviour

only the file upload screen should display

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

InvenTree Version	
[0.17.0 dev](https://github.com/inventree/InvenTree/releases)
Commit Hash	
f144158
Commit Date	
2024-09-03
Commit Branch	
API Version	
[249](http://192.168.177.12/api-doc/)
Python Version	
3.11.9
Django Version	
[4.2.15](https://www.djangoproject.com/)

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@simonkuehling thanks for reporting, fix incoming in https://github.com/inventree/InvenTree/pull/8071
