### ISSUE TITLE
Add "empty" line to Purchase Order and Sales Order

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#807]
Might want to add a line item against something not in the database. This could be simply because the item has not been entered, or because it requires a line for "consulting fee" or something non tangible.

**Comment by eeintech** [comment]
@SchrodingersGat I think this was added in the past few months and I just tested it, empty lines accepted :+1:

**Comment by eeintech** [comment]
Oops correction, it only works for Purchase orders, not sales orders

**Comment by SchrodingersGat** [comment]
@eeintech oh, good point.
