### ISSUE TITLE
[FR] display links as clickable in table views (links for line items of POs etc)

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#8070]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

when adding links to supplier parts, those links were previously rendered as clickable html links in table views like purchase order line items etc. In the PUI interface, the whole table row now has the same link action (which is generally very consistent and appreciated compared to the old interface) - but especially in PO line items it is very useful to be able to directly click on those links when assembling a shopping cart for purchasing parts

![grafik](https://github.com/user-attachments/assets/cf15fd1c-3d83-4ac2-b28a-53c2fd84adde)

### Suggested solution

table fields containing URLs should be excluded from the current "boundary box link" and the URLs should be rendered as ```<a href...>```html links instead like this:

![grafik](https://github.com/user-attachments/assets/f43ab2cc-40cb-4d32-a2ae-60f51abfd8e7)

### Describe alternatives you've considered

Depending on UI consistency considerations this could instead be implemented with a small icon next to the URL as a "action button" - but I think a traditional link with the classic underline should be conventionally recognized by users

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@simonkuehling thanks, this is a simple fix, we already the column rendering functions in place - https://github.com/inventree/InvenTree/pull/8072
