### ISSUE TITLE
[FR] time tracking of stock items 

### ISSUE THREAD

**Issue by UPIlobra07** [inventree/InvenTree#8074]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I need to determine whether my products have expired and whether any of my tools require calibration. 
Tracking all of this takes a significant amount of time and can lead to issues.

### Suggested solution

Adding an expiration date field that can be updated,
 along with sending notifications or emails prior to the expiration date,
 would help resolve the problem.

### Describe alternatives you've considered

n/a

### Examples of other systems

i don't know 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@UPIlobra07 this feature is already available, although disabled by default. Please read the documentation here: https://docs.inventree.org/en/stable/stock/expiry/
