### ISSUE TITLE
BOM items are not listed

### ISSUE THREAD

**Issue by kozmotronik** [inventree/InvenTree#8078]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The BOM list items for the parts is empty since yesterday. See the screenshot please.

![inventree_bom_list_problem_20240905_090119](https://github.com/user-attachments/assets/58c0ea2e-0122-4bb3-b64f-b0ad0b8caccb)

As you can see there are actually 30 rows of BOM items assigned to this part. However none of them are listed somehow.
The bad part is that I don't know how this happened hence can't provide any steps to reproduce unless you give me some tips to do it.

I've tried refreshing the page both with **`F5`** and  **`CTRL + F5`** with no avail. Then I went to the admin panel to check whether the BOM items are still exist, I see them in there.

I also tried to add a new BOM item to see if it will be shown in the list, but it did not either.

Why something like this would happen? What should I do?

### Steps to Reproduce

Not sure how this happened...

### Expected behaviour

The BOM items of the part to be listed.

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.1
Django Version: 4.2.15
Commit Hash: 4c15e5c
Commit Date: 2024-08-30

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.8.0-40-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'IPNGenerator', 'slug': 'ipngen', 'version': '0.1'}, {'name': 'KiCadLibraryPlugin', 'slug': 'kicad-library-plugin', 'version': '1.4.3'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@JustusRijke have you tried refreshing the cache on your browser?

https://docs.inventree.org/en/latest/faq/#feature-x-does-not-work-after-update

**Comment by SchrodingersGat** [comment]
@kozmotronik can you please open the developer console in your browser and share (screenshots please) what the "requests" or "network" tab shows when you try to reload that table? i.e. by pressing the "reload data" button:

![image](https://github.com/user-attachments/assets/03b2ed1d-307f-4ea9-bd93-4a761ca57fd3)

**Comment by kozmotronik** [comment]
Sure, here it is:

![inventree-network-requests](https://github.com/user-attachments/assets/ec63e1db-6b45-4b7a-90fc-837070ef27a8)

By the way, I logged in to InvenTree from Vivaldi browser, the BOM list appeared in it. The browser that I am having problem with is the KDE's Falkon browser. I use it because it is lightweight and fast. But if it is not compatible I can ditch it from using for InvenTree.

What do you advice me?

**Comment by kozmotronik** [comment]
Oh my! It turns out that it is a browser specific caching issue. `CTRL +F5` does not seem to work in Falkon browser. So I cleared the cache from the settings and restarted the browser then boom! The BOM items returned.

I'd like to apologize for consuming of your valuable time for this insignificant browser specific issue. Excuse me please and thank you.

**Comment by SchrodingersGat** [comment]
@kozmotronik thanks for getting back with the outcome. Glad to hear that you got it sorted!
