### ISSUE TITLE
Website not loading in Singapore

### ISSUE THREAD

**Issue by BorampetBhavani** [inventree/InvenTree#8087]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

In india , its working fine but in singapore ,the same website is not loading. Our inventree is hosted on google cloud platform.

### Steps to Reproduce

I am using vm instance , google cloud shell

### Expected behaviour

It should load 

### Deployment Method

- [ ] Docker
- [X] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

15.3 version

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@BorampetBhavani more likely an issue with your cloud hosting platform than with InvenTree. 

![image](https://github.com/user-attachments/assets/2e5ace73-4439-40a0-9fb8-60bf270360e7)

Are you really saying that the demo site does not load in Singapore?

**Comment by matmair** [comment]
This sounds like a local deployment problem
