### ISSUE TITLE
Admin Center Part Data Import Issue

### ISSUE THREAD

**Issue by Austex-AaronCraig** [inventree/InvenTree#8094]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I Cannot find a way to bulk import part data into Inventree, using the new or old UI. Stuck on the processing data screen and selecting an individual item or selecting multiple items then importing does nothing.
![image](https://github.com/user-attachments/assets/46311214-9455-4853-9af4-55f90f3e9cbd)

### Steps to Reproduce

1. Go to New UI
2. Go to Admin Center -> Data Import
3. Begin part data import
4. Match fields.

### Expected behaviour

I suppose it should import the data.

### Deployment Method

- [ ] Docker
- [X] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

InvenTree Version | 0.16.1
API Version | 232
Python Version | 3.10.12
Django Version | 4.2.15

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
If you select the rows (via the checkboxes on the left) does the "import rows" button become active on the top left, above the table?

**Comment by Austex-AaronCraig** [comment]
When I do, it does go green however you can click that button and nothing really happens, no imports or anything, import stays at 0/998
![image](https://github.com/user-attachments/assets/0bc1311a-3f39-4617-bbb4-02191f74f550)

**Comment by Austex-AaronCraig** [comment]
Also using the part import in the classic admin center throws this error, tried UTF-8 and ANSI encoding to see if its to do with that and cannot get it to work.


Line number: 1 - [<class 'decimal.ConversionSyntax'>]
10-359-1252, Test Point 20 Nipple W/- Metal CapX1/8 BSPP Male 10-359-1252, , , , , , , , , , , , , , 2, , , , , , , , , , , , , , , 12.28, , , , , , , Aaron, , , ,
Traceback (most recent call last):
File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 778, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 399, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "/opt/inventree/env/lib/python3.10/site-packages/import_export/resources.py", line 392, in get_instance
return instance_loader.get_instance(row)
File "/opt/inventree/env/lib/python3.10/site-packages/import_export/instance_loaders.py", line 29, in get_instance
params[field.attribute] = field.clean(row)
File "/opt/inventree/env/lib/python3.10/site-packages/import_export/fields.py", line 86, in clean
value = self.widget.clean(value, row=data, **kwargs)
File "/opt/inventree/env/lib/python3.10/site-packages/import_export/widgets.py", line 99, in clean
return int(Decimal(value))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by 15ah35** [comment]
I have the same issue

**Comment by SchrodingersGat** [comment]
@Austex-AaronCraig @15ah35 we are not actively working on the "import_export" tool any longer - instead we are focusing on the new user interface which has a muhc more streamlined import process.

As such, if you want to provide a fix for the errors as listed above I'll merge it in, but I do not have any time to look into it

**Comment by 15ah35** [comment]
This error is occurring in the new user interface…

**Comment by SchrodingersGat** [comment]
@15ah35 I meant for the "class admin" error that @Austex-AaronCraig reported above.

Can either of you provide a sample data file that you are seeing errors with?

Additionally, a screen recording / video of the issue would be helpful too here so I can see the sequence of events. Or even a series of screenshots.

**Comment by Austex-AaronCraig** [comment]
@SchrodingersGat Sorry for the late reply, I was on holiday.

The issue was with the part number, found out that you can only have a number in the part number column, no letters or any other characters in the part number column. Once I changed the part number column to only have numbers the new interface mass import worked a charm.

I would want to have a prompt to check and tell the user that you can't have characters in your part numbers with inventree, or update the database to support more than numerical characters in it. 

This specific issue can be closed now as I can mass import parts with the new interface but would like to see a warning if users try to add a part number with characters instead of no prompt at all going forward.

**Comment by SchrodingersGat** [comment]
Not sure what you mean by part numbers not having non numerical characters - can you please provide a sample file that I can test with?

**Comment by SchrodingersGat** [comment]
Any working sample files which I can use to test this? The importer has been working well on my end. @Austex-AaronCraig

**Comment by matmair** [comment]
@SchrodingersGat do we consider this a valid bug report and do we want to keep it on the 0.17.0 backlog or move it to the 1.0 bucket?
