### ISSUE TITLE
[FR] Make Parameters Editable in Parametric Part View

### ISSUE THREAD

**Issue by realstudent01** [inventree/InvenTree#8109]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

In the Parameters tab when viewing parts in a subcategory, I would like to be able to double click on a cell (or select it in some way) and edit the value in that cell.

### Suggested solution

When the cell is double clicked open the same function as when the edit button is pressed on the parameter when viewing the part parameters only.

### Describe alternatives you've considered

Anything that makes it easier/require less clicks to change the parameters of a part.

### Examples of other systems

This would make it closer to how it is done in Excel.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@realstudent01 have you tried the new user interface (i.e. at `/platform/`) - in this interface, the functionality you are asking for has already been implemented. Please check that out.
