### ISSUE TITLE
[FR] Adding a test result manually should allow date and time to be chosen from a picker menu

### ISSUE THREAD

**Issue by calumblair** [inventree/InvenTree#8112]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

When I want to add a new test for a build, I have to enter start and finish times by entering ISO datetime format `YYYY-MM-DDTHH:mm` manually
![image](https://github.com/user-attachments/assets/232286c7-666c-4ae7-9d0e-d5543c7c7b77)

### Suggested solution

Inventree uses date pickers elsewhere, e.g. in the admin panel; can we add a date and time picker for these form items? 

### Describe alternatives you've considered

Alternatively we can continue entering timestamps manually which is error-prone 

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@calumblair this is implented in the new user interface, which uses a much more modern UI framework. Back porting this to the old UI will be difficult and probably not supported.
