### ISSUE TITLE
[FR] Sales order templates

### ISSUE THREAD

**Issue by ATLAS2246** [inventree/InvenTree#8116]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Where I am using Inventree just had an event where we had to create and issue a large number of sales orders with the same line items with only a few variations

### Suggested solution

A template for sales orders where a group of line items are added automatically to the sales order

### Describe alternatives you've considered

At the moment we are just manaully adding every line item by hand but this is very slow

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@ATLAS2246 we currently have the option to "duplicate" a sales order - but this only duplicates the order details, not the line items.

Perhaps a clean solution here would be to allow the user to also duplicate the line items from an existing order?

**Comment by ATLAS2246** [comment]
that would probably work extremely well, id just set up a template order that doesnt get completed and use that
