### ISSUE TITLE
Pricing format under Purchase order

### ISSUE THREAD

**Issue by MIOsystems** [inventree/InvenTree#8117]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The pricing in the total field in a purchase order did not follow the regional settings of the browser.

Browser: Firefox

### Steps to Reproduce

Set browser/OS to Dutch regional settings. Open purchase order with a total above 1000 units
![Pricing format](https://github.com/user-attachments/assets/d75c771e-51eb-4f3f-923b-12940c38121c)

### Expected behaviour

Same pricing format as other fields

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.2
Django Version: 4.2.15
Commit Hash: 065aca4
Commit Date: 2024-09-10

Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Platform: Linux-4.4.302+-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
None. Demo site outs an Internal Server Error
```

**Comment by SchrodingersGat** [comment]
Hi @MIOsystems thanks for raising the issue. Note that in the screenshot you posted, the "table" is rendered in the frontend (client browser) while the "total cost" is rendered in the server (backend).

Our *new* user interface (which is almost ready) is entirely rendered on the client side and so there will be no such inconsistency. So, I'll close this out, we won't be making trivial patches back to the legacy user interface.

**Comment by MIOsystems** [comment]
Clear. 
We are very pleased with the functionality of Inventree and sponsored it already by installing the app (not effectively used). The GUI is already very good we thing. Maybe not the tread to give feedback here, but now you mentioned it for the new GUI design. Users that have a practical use of software never like changes. Hope it is very customizable such that it can adapt very likely to the current design and mainly the layout. Most of us engineers like technical, clean, overview design that is very responsive. Instead of fading screens and buttons or bulky fonts and div's. I use the dashboard a lot specially the low stock overview. The new dashboard is no compare to the previous one. I known it is still under development but as seen from 0.16.2 this it not useful for us at the moment.

![image](https://github.com/user-attachments/assets/48db5447-48ba-477f-a025-784467dac00b)

**Comment by SchrodingersGat** [comment]
@MIOsystems the dashboard is still under heavy development, and any contributions to the new interface would be very welcome! There is only a very small handful of people actively working on it which causes a big bottleneck. If you have ideas / suggestions (or even better, can contribute code or design) that would be greatly appreciated.

**Comment by MIOsystems** [comment]
Although I'm a programmer, my time is too precious to give away for this project. But i will help you by reviewing the software. Is there a special channel for the new interface?

**Comment by SchrodingersGat** [comment]
@MIOsystems if you find any [issues](https://github.com/inventree/InvenTree/issues), or want to [discuss](https://github.com/inventree/InvenTree/discussions) the new interface, the GitHub platform here is the best place.
