### ISSUE TITLE
Report setting for Inline PDF not working

### ISSUE THREAD

**Issue by LastEdit** [inventree/InvenTree#8144]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

I had enabled the user->report setting for inline report and label display and it was working previously. Recently I noticed it has starting downloading the files instead of showing in the browser from the server.

Happened on Firefox 129, 130

### Steps to Reproduce

Enable inline setting.
Generate report/label.
PDF gets downloaded

### Expected behaviour

Display PDF directly from server.

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.1
Django Version: 4.2.15
Commit Hash: 4c15e5c
Commit Date: 2024-08-30

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@LastEdit this is likely because we have changed the way that reports are generated. The report is saved on the server (in the `/media/` directory) before download. This in turn means that the proxy server configuration is forcing a "download" attribute on the download file (if you are using our proxy server setup)

**Comment by SchrodingersGat** [comment]
@LastEdit our default behaviour (via the Caddyfile) is to be very conservative from a security POV. The danger is that an uploaded file may execute a script in the browser

**Comment by LastEdit** [comment]
Since the issue is caused by the default proxy configuration, and could be remedied by changing that configuration, I will close the issue.
