### ISSUE TITLE
print location report does not work properly

### ISSUE THREAD

**Issue by Philipboy881** [inventree/InvenTree#8156]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

when i want to print stok location reports on the new ui this does open the dialog but i get an "Invalid Return Code Server returned status 0" error in the right botom. when i press print.

on the old ui it just works when the print reports is enabled in the server settings.

cannot reproduce on demo because cannot login on the new ui

### Steps to Reproduce

got to stock -> stock locations -> select a sub location
after this the print button will be visible and select print report in the dropdown.

### Expected behaviour

i expect an document instead of error code (i do not know if it is already implemented becas the new ui is new).

### Deployment Method

- [ ] Docker
- [x] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.1
Django Version: 4.2.15

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-196-generic-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'Zebra', 'slug': 'zebra', 'version': '0.5.2'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
It might be timing out. How long does the "print" operation take to complete on the old UI?

**Comment by SchrodingersGat** [comment]
Upcoming version `0.17.0` has already an increased timeout for these actions. I am backporting that to `0.16.x` here - https://github.com/inventree/InvenTree/pull/8187
