### ISSUE TITLE
Main Sign On Screen

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#8160]
### Body of the issue

I finally got the Docker method of InvenTree installed, with much consternation and help from an expert. The http://localhost:8000 link in my FireFox browser works and I get to the initial sign on screen. Now it wants a name and a password. What name and what password? I tried the GitHub name and password, my Ubuntu name and password, and several others, but nothing worked. Please supply information and maybe make it a bit clearer as to what name and what password. Thanks.

**Comment by ATLAS2246** [comment]
Did you define the admin user in the .env file or through the `docker compose run inventree-server invoke superuser` command. in the .env file there should be 3 lines which say:

INVENTREE_ADMIN_USER=
INVENTREE_ADMIN_PASSWORD=
INVENTREE_ADMIN_EMAIL=

you need to put detailes in there, hopefully that helps

**Comment by LarryJoy** [comment]
Thank you. I went to my .env file and found those lines, entered the info, and now everything is working. Regards.
