### ISSUE TITLE
Sorting line items

### ISSUE THREAD

**Issue by Flare0** [inventree/InvenTree#8164]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Sorting Required part or part column in build, purchase and sales order sort by name instead of full name.
If reference column contain numbers sorting is not sequential for build and purchase orders. Works for sales orders.

![Image](https://github.com/user-attachments/assets/0e4e0b6c-765f-4b8e-b9c7-c98485b466fe) ![Image](https://github.com/user-attachments/assets/138ae65c-3f8e-4a2b-9ed1-53da9bcb23a9)

### Steps to Reproduce

1. Go to Line Items
2. Press header to sort column

### Expected behaviour

Expect sorting to be like in a BOM.
Sorting part column sort by full name and sorting reference is sequential.

![Image](https://github.com/user-attachments/assets/77f0f503-0067-4065-8955-2a597c9def77) ![Image](https://github.com/user-attachments/assets/aa108e81-5787-4bce-98f6-8519e1fc9134)

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.2
Django Version: 4.2.15
Commit Hash: 065aca4
Commit Date: 2024-09-10

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.2.16-20-pve-x86_64-with
Installer: DOC

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

**Comment by Flare0** [comment]
After looking more at the sorting behavior at other pages too (Parts, Stock items, supplied parts etc.), it seems like BOM is the only place using full name for sorting, pretty much everywhere else it's by name.
So maybe sort by name is the intended behavior?

**Comment by SchrodingersGat** [comment]
@Flare0 yes the part column always sorts by name. You can also sort by `IPN` separately (if that column is available in the table). We cannot do a database sort directly off `full_name` as it is a dynamically constructed field.

**Comment by Flare0** [comment]
@SchrodingersGat I understand, I just assumed it was full name for the BOM, as it is sorted in that order. Must be by IPN there then?
Anyways my main concern was actually the reference field.
The reference field is sorted the same way for BOM and Sales order and another way in Build, and purchase order.
As it is now, I can't find a way to sort a BOM and the line items in a build order the same way.

**Comment by SchrodingersGat** [comment]
Ah right, so the the "reference" field in the BOM model is not numerically sorted in the same way as the "reference" field for orders
