### ISSUE TITLE
[FR] Backup rotation (DBBACKUP_CLEANUP_KEEP configuration)

### ISSUE THREAD

**Issue by Silex** [inventree/InvenTree#8165]
### Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find a similar feature request

### Problem statement

Hello,

I'm trying to configure `DBBACKUP_CLEANUP_KEEP` (https://django-dbbackup.readthedocs.io/en/2.5.0/configuration.html) so it remembers 6 months of backups before deleting the old backups.

I enabled daily backups in the interface by following https://docs.inventree.org/en/latest/start/backup, but I could not find how to tweak `DBBACKUP_CLEANUP_KEEP`

I guess I should modify `INVENTREE_BACKUP_OPTIONS` but I can't figure how to use the dict format.

### Suggested solution

Show an example in the doc.

### Describe alternatives you've considered

Using cron & logrotate.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
The dict format is easier to specify in the config file, as you can just use yaml!
