### ISSUE TITLE
Fix spelling mistake in Docker installation documentation

### ISSUE THREAD

**Issue by jacobburrell** [inventree/InvenTree#8178]
### Body of the issue

**Description:**

There is a small spelling mistake on the Docker installation page of the documentation. The sentence currently reads:

"This tutorial assumes you are working from a direction where all of these files are located."

The word "direction" should be corrected to "directory" for accuracy.

**Location:**
Link to the page: [Docker Installation - Inventree Documentation](https://docs.inventree.org/en/stable/start/docker_install/#required-files)

**Proposed Correction:**

Change the sentence to (without emphasis):

"This tutorial assumes you are working from a **directory** where all of these files are located."

Thank you for addressing this!

**Comment by SchrodingersGat** [comment]
Thanks, fix incoming in https://github.com/inventree/InvenTree/pull/8181
