### ISSUE TITLE
Server Restart Required.

### ISSUE THREAD

**Issue by BorampetBhavani** [inventree/InvenTree#8188]
### Deployment Method

- [x] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

 Server Restart Required
A configuration option has been changed which requires a server restart.

### Steps to Reproduce

Inventree is hosted on Google cloud as VM.

### Relevant log output

Still the error persists even after trying "sudo systemctl restart inventree" and "sudo systemctl restart nginx". Ans my inventree is hosted on google cloud.I recently upgraded it to latest version .

**Comment by SchrodingersGat** [comment]
Please provide complete version information for your InvenTree installation

**Comment by BorampetBhavani** [comment]
Inventree version is 16.2

**Comment by matmair** [comment]
Please provide the full version information as it is available in the server info modal (there is also a copy button there)
