### ISSUE TITLE
Purchase Order add new filter

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#820]
Seems that I can only have one filter for the purchase order view.  When I click the "+" nothing happens.  Running in a VM with Ubuntu 18.04, FireFox 76.01.

InvenTree version 0.1.1 pre

Frankie

**Comment by SchrodingersGat** [comment]
Yes, there's only one filter available for the order table - "Order Status". This is expected behaviour

**Comment by lookme2** [comment]
Ok thanks!
