### ISSUE TITLE
Multiple order bug?

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#822]
So if I setup a part as Order Multiple of 100.  Then add qty of 1 of that part to a purchase order.  I then receive that 1 item should my stock not show that I have 100 pieces?  If so it's not working.

**Comment by SchrodingersGat** [comment]
This feature is not actually implemented yet. But the idea is that if you set an order-multiple, it restricts the quantity you can buy. For example, if a certain part is bought in a pack of 12, you can only order 12 / 24 / 36 / 48 / etc.

**Comment by lookme2** [comment]
I see.  Ok thanks.
