### ISSUE TITLE
Prevent HTML Encoding in QR Code Payload for Part Data

### ISSUE THREAD

**Issue by skydiablo** [inventree/InvenTree#8251]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Currently, when generating a QR code for a part, the resulting payload is HTML-encoded, which affects the output format. For example, instead of generating a plain text JSON payload like this:

```
{"part": 1}
```

the payload is encoded as:

```
{&quot;part&quot;: 1}
```

This encoding causes unnecessary transformations, especially when parsing the data from the QR code. It would be more useful if the QR code generator produced the payload in plain text format without HTML-encoding special characters such as " and &.

### Steps to Reproduce

Go to a part in InvenTree.
Generate a QR code for that part.
Scan the QR code and check the payload. It will be HTML-encoded (e.g., {&quot;part&quot;: 1}).

### Expected behaviour

The payload should not be HTML-encoded and should instead output raw JSON data, like:

```
{"part": 1}
```

### Deployment Method

- [ ] Docker
- [ ] Package
- [x] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

0.16.4

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

**Comment by skydiablo** [comment]
so, i have checked this, i think the default escaping is the problem. this fix it, just patch this [line](https://github.com/inventree/InvenTree/blob/198a39a33cf304c8682c41cea958c39d6bc1420c/src/backend/InvenTree/part/templates/part/part_base.html#L461) from

```
            '{{ part.barcode }}',
```
to
```
            '{{ part.barcode|safe }}',
```

regards, volker.

**Comment by SchrodingersGat** [comment]
@skydiablo so, it is only in the displayed text that the error is occurring, not the actual generated barcode itself?

**Comment by skydiablo** [comment]
no, the payload of the QR-code itself is escaped, see above, there is a PR to fix this issue for the payload
