### ISSUE TITLE
'Tag' management

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#83]
Parts (or 'things' in general?) should have custom tags

**Comment by SchrodingersGat** [comment]
Ability to filter by tags. Filter against multiple tags too.

**Comment by SchrodingersGat** [comment]
Get list of existing tags via JSON. Probably something like "SELECT text FROM tags GROUP by text" or whatever the Django equivalent of that is.

**Comment by eeintech** [comment]
@SchrodingersGat Is this "tag" system still a wish?

**Comment by SchrodingersGat** [comment]
Tags here is probably an extension of "keywords" which already exist for the `Part` model. Probably this could be extended, allowing searching / filtering by keyword tags.

**Comment by matmair** [comment]
@SchrodingersGat  General question: do you want to use 'dumb' keywords - so just text that gets searched - or a more elaborate system with a model for the keywords and foreign keys to them?

I did a bit research into tag-packages and the following seem to be interesting:
- [django tagulos](https://github.com/radiac/django-tagulous) - is the full package: autocompletion, slug generation and trees for tags
- [django sitecat](https://github.com/idlesign/django-sitecats) - adds nice editing elements
- [django taggit ](https://github.com/jazzband/django-taggit) seems to be a reasonable light variant

**Comment by SchrodingersGat** [comment]
Shelving this one until someone clamours for it (and ideally develops it)

**Comment by matmair** [comment]
@SchrodingersGat would that be of interest for you?

**Comment by matmair** [comment]
I need something like this for next steps of #3791 so I will contribute it

**Comment by matmair** [comment]
I will use https://django-taggit.readthedocs.io/en/latest/
