### ISSUE TITLE
Parts and stock tabs do not show complete information after updating

### ISSUE THREAD

**Issue by Jamespcman** [inventree/InvenTree#8304]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Parts and stock tabs do not show complete information after updating to 16.5

### Steps to Reproduce

Main website click on upper parts tab or stock tab do display proper information, which was there before update the bill tab by and Cell or probably working

### Expected behaviour

On the PC, through the web browser, the parts and stock categories are not fully functioning as they were before the update I have tried deleting the cash multiple times Everything else seems to be functional except for those two sections.

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

16.5

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Try this first - https://docs.inventree.org/en/stable/faq/#feature-x-does-not-work-after-update

Otherwise, please provide some screenshots. It is hard to know exactly what you mean

**Comment by QuadratClown** [comment]
I have the same Issue. My parts/stock pages look like this:
![Image](https://github.com/user-attachments/assets/5a9fd034-8461-4ace-9a49-8cbb82f36e5d)

Additionally, clicking on "edit" on a selected stock location does nothing
![Image](https://github.com/user-attachments/assets/40754096-5f58-4ff0-8b0f-e53cadf7eae5)

**Comment by QuadratClown** [comment]
Nvm, was able to fix this by migrating the database via `docker compose run --rm inventree-server invoke update` and reloading the browser cache 👍
