### ISSUE TITLE
[BUG/FR?] Default Label Printer setting not recognized in PUI

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#8313]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Just noticed that currently the user-specific default label printer selection is not working (or not yet implemented?) in the PUI:

<img src="https://github.com/user-attachments/assets/946afde7-06dd-4986-9463-50f7d9818a76" width="70%" height="70%">

Setting in ```Account Settings``` is:

<img src="https://github.com/user-attachments/assets/6b46f5d1-09d9-4feb-9538-ef25068dd175" width="70%" height="70%">

### Steps to Reproduce

1. Install a label printer (e.g. via ``ìnventree-brother-plugin```)
2. open a part or stockitem and click ```print label``

### Expected behaviour

have the Printing Plugin dropdown preselected as configured

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

InvenTree Version	
[0.17.0 dev](https://github.com/inventree/InvenTree/releases)
Commit Hash	
17bf7bb
Commit Date	
2024-10-18
Commit Branch	
API Version	
[269](http://192.168.177.12/api-doc/)
Python Version	
3.11.9
Django Version	
[4.2.16](https://www.djangoproject.com/)

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@simonkuehling would you be willing to look into this one? I think this has simply not been implemented yet.

**Comment by simonkuehling** [comment]
@SchrodingersGat ah ok - I can try to do so, sure... My first guess would be to look at https://github.com/inventree/InvenTree/blob/master/src/frontend/src/components/buttons/PrintingActions.tsx, right?

How should I access the user settings correctly here - like this?
```
import { useUserSettingsState } from '../../states/SettingsState';
const userSettings = useUserSettingsState();

default_printer = userSettings.getSetting('LABEL_DEFAULT_PRINTER')
```

**Comment by SchrodingersGat** [comment]
That looks right to me! Happy to review a PR :)

**Comment by SergeoLacruz** [comment]
Also in the classical UI the default label printer is not set any more in 0.16.5. It worked fine in 0.15.1. 
Is this the same reason?
Also the template selection in the form is not prefilled any longer.

**Comment by simonkuehling** [comment]
@SergeoLacruz from my understanding the current project focus is pretty much 100% on the new UI - but don't take my word for it... 

Regarding template selection, I can confirm that this also needs to be solved in platform UI - so I opened a new issue for that at https://github.com/inventree/InvenTree/issues/8347
