### ISSUE TITLE
[FR/PUI] Allow scanning on main page with wedge/keyboard

### ISSUE THREAD

**Issue by F9Alejandro** [inventree/InvenTree#8323]
### Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find a similar feature request

### Problem statement

When clicking on "Open QR code scanner" you are presented with the ability to select a camera. However not all environments allow usage of webcams or cameras; instead they use scanners or scan guns to input data, which is currently not possible with the current version of inventree 0.16.5

![Image](https://github.com/user-attachments/assets/9367082d-7d15-4a42-a30d-1bb0d9dc4ea1)

### Suggested solution

A selectable option to change to barcode scanning with a scanner or wedge. Where the modal changes to show a text field and on enter it will submit show relevant information and reselect the text box to continue scanning.

### Describe alternatives you've considered

Instead of using a modal use a page instead where continuous scanning is possible without causing potential issues with the modal running out of space or extensive scrolling.

### Examples of other systems

CUI has this capability currently. It should be possible to make this change relatively easily.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
The new scanning page (can be found in the navigation pane or in the command pallet with cmd + k) supports continuous scanning and text-based input.

**Comment by SchrodingersGat** [comment]
Not stale!
