### ISSUE TITLE
Full hierarchy in 'Default Location' dropdown not presented to user

### ISSUE THREAD

**Issue by chris-thorn** [inventree/InvenTree#8350]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

When choosing a default stock location for a part or category, the hierarchy of stock locations is not visible in Platform UI whereas it was in Classic UI.

Based on the hierarchical way in which stock locations can be set up in InvenTree, I set up all my stock locations with the location itself _not_ including details of its parent locations.

For example, I have two stock locations with the name "B01", but one is a child of Drawer Unit 1 and one is a child of Drawer Unit 2. This has always worked well in Classic UI due to the way that the full location hierarchy is always visible.

![Image](https://github.com/user-attachments/assets/5ba2c60f-522b-45e6-829a-5f4df430fd9b)

In Platform UI, the hierarchy is hidden, and I am presented with two apparently identical options of "B01" or "B01", with no additional information to help me decide which one I need to select.

![Image](https://github.com/user-attachments/assets/a8b8c359-8d8b-4ef9-b0e3-ac88e06096f6)

I have tried to illustrate the differences in behaviour in this short clip. First, the expected behaviour in Classic UI, followed by the new behaviour in Platform UI.

https://github.com/user-attachments/assets/5945129b-43d2-4292-9bfb-72f971afa480

### Steps to Reproduce

1. Add a new part category
2. Select the **Default Location** dropdown box
3. Begin to type the name of a location
4. In Platform UI, filtered results of search may be indistinguishable from one another.

### Expected behaviour

The hierarchy of stock locations is presented to the user as it is in Classic UI.

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.5
Django Version: 4.2.15
Commit Hash: 6e37f0c
Commit Date: 2024-10-07

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.10.0-27-amd64-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.9.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Chris, it looks like the form rendering for a "location" has not been fully implemented (or is differently implemented) in the new interface. I've added this to the next release milestone so it doesn't get forgotten.

This should be a pretty simple fix - is it something that you are interested in contributing to?

**Comment by SchrodingersGat** [comment]
We renamed that command to `invoke dev.frontend-server`. Looks like the docs are out of date, I'll issue a PR to fix that!
