### ISSUE TITLE
Is not permitted to add/modify comment in attachment in part

### ISSUE THREAD

**Issue by simoneamadori** [inventree/InvenTree#8354]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

When trying to modify the comment of an attachment in part I get this error:
![Image](https://github.com/user-attachments/assets/35c783cd-8696-4984-af33-e882228b0301)
also is not permitted to delete the attachment it tell me that is prohibited (the user is admin)

### Steps to Reproduce

1. go to attachments in a selected part
2. press edit
3. add a comment
4. press submit

### Expected behaviour

Pressing submit should apply the updated data

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.5
Django Version: 4.2.15
Commit Hash: 6e37f0c
Commit Date: 2024-10-07

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-124-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'KiCadLibraryPlugin', 'slug': 'kicad-library-plugin', 'version': '1.4.3'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
- What "type" of attachment are you trying to upload? e.g. against a "part" or "build order" (etc)
- Have you recently performed an update from an older version?
- Can you share the actual data being transmitted to the server when you hit the "Submit" button? (This is available via the developer console in your browser)

**Comment by simoneamadori** [comment]
The problem is only on the modifying / delete, when creating it create it correctly.

- The attachment is referred to a part:

![Image](https://github.com/user-attachments/assets/3c155c4b-1f77-4b9c-bd38-ba40d2759b89)

- I've always updated regularly
- for the data you intend from the console?:

The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
240/:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
jquery_3.3.1_jquery.min.js:2 
        
        
       PATCH http://192.168.10.18:1337/api/attachment/240/ 400 (Bad Request)
send @ jquery_3.3.1_jquery.min.js:2
ajax @ jquery_3.3.1_jquery.min.js:2
inventreePut @ en.api.js:151
submitFormData @ en.forms.js:970
(anonymous) @ en.forms.js:725
dispatch @ jquery_3.3.1_jquery.min.js:2
y.handle @ jquery_3.3.1_jquery.min.js:2

**Comment by simoneamadori** [comment]
Here the screenshot:
![Image](https://github.com/user-attachments/assets/61489c51-3825-4087-a115-cfa54c6a10be)
![Image](https://github.com/user-attachments/assets/81c81379-05e9-44b3-baf5-53f76251283a)

**Comment by SchrodingersGat** [comment]
That's.. very odd then.

Can you look at the admin view for that particular attachment (and post a screenshot if you can):

It should be at: http://192.168.10.18:1337/admin/common/attachment/240/change/

In particular, what does the "model_type" and "model_id" fields say?

![Image](https://github.com/user-attachments/assets/880c1715-b872-4809-9915-53ea33dd1cf4)

**Comment by simoneamadori** [comment]
Here the screenshot:
![Image](https://github.com/user-attachments/assets/ffbfc2a9-c678-4f57-a638-83049e8f4050)

Indeed is very peculiar this problem...

**Comment by simoneamadori** [comment]
If it can help,  trying with the new platform interface I can change the comment or deleting without problem

**Comment by SchrodingersGat** [comment]
Fix incoming in https://github.com/inventree/InvenTree/pull/8362

Looks like this has been already fixed in latest, but the patch did not get backported correctly

**Comment by simoneamadori** [comment]
Thanks!

**Comment by matmair** [comment]
@simoneamadori can you confirm this was fixed? Can we close this?

**Comment by SergeoLacruz** [comment]
I had the same issue. It is fine after update. Thanks for the quick fix.

**Comment by simoneamadori** [comment]
> [@simoneamadori](https://github.com/simoneamadori) can you confirm this was fixed? Can we close this?

I confirm that it works correctly
