### ISSUE TITLE
Getting Internal Server Error when generating parts list from Admin

### ISSUE THREAD

**Issue by mikeabiz** [inventree/InvenTree#8358]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

I have installed the 16.0 development version and have been running it.  Tried to generate a parts list for around 1k parts but have been getting an internal server error.

My hardware specs is an Intel Celeron on a J1900 motherboard with 8 GB RAM and 256 GB SSD

### Steps to Reproduce

Go to admin
Go to parts
Select Export
Select CSV file![Image](https://github.com/user-attachments/assets/da9955f1-f28d-46c6-b7d6-df17b2d18068)
![Image](https://github.com/user-attachments/assets/1c594766-afb4-4e28-ae28-8f7672922846)
![Image](https://github.com/user-attachments/assets/1820cadf-cb98-4cca-a071-9457cea4eecb)
![Image](https://github.com/user-attachments/assets/187aa17c-ff2b-4406-b6d6-800d1eccb76a)
![Image](https://github.com/user-attachments/assets/636a1066-524d-4861-bd06-565923086d4f)

### Expected behaviour

Parts list will be generated

### Deployment Method

- [ ] Docker
- [ ] Package
- [x] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.0 dev
Django Version: 4.2.14

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.10.0-31-amd64-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
This looks to be an identical issue to https://github.com/inventree/InvenTree/issues/7650

Basically, the "old" library we use for exporting is inefficient - and will be removed after our next release.

You can export via the "download data" button in the part table - and this should be a lot quicker, and prevent the proxy server from timing-out the request

**Comment by mikeabiz** [comment]
Thanks.  Have been able to complete the download.
