### ISSUE TITLE
[UI] Remove old  PUI settings

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#8368]
- Once CUI code is removed, delete all old settings which are no longer referenced
- e.g. the home page / dashboard is now fully controlled by the front-end
- There are many settings which are only used in the (legacy) templated UI code

**Comment by wolflu05** [comment]
Related, and maybe also a duplicate of #7639

**Comment by SchrodingersGat** [comment]
Thanks, it is a duplicate. There are too many open issues!! I'll close this one out.
