### ISSUE TITLE
[FR] Return order for non-serializable (trackable) items

### ISSUE THREAD

**Issue by baltuonis** [inventree/InvenTree#8372]
### Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find a similar feature request

### Problem statement

We are using InvenTree to manage our small non-profit book warehouse. So far it served us a lot and we love how nifty it is.

We are trying to register Return Orders for books that get returned from our sellers/book fairs.
Unfortunately Return Orders only allow serialized (trackable) parts to be returned.
We ship dozens of books weekly so it is not practical to serialize (track) them.

### Suggested solution

Is there a way to return non-serialized (non trackable) parts?

### Describe alternatives you've considered

Modify the code ourselves?
Is there a simple/non-destructive way to modify the code for behavior this to work?
We have invested in this system and it would be tedious to migrate.

### Do you want to develop this?

- [x] I want to develop this.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/8372">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/8372/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/8372/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
The return order was focused on "serialized" items to allow full traceability of items. If you have a method of discriminating between individual stock items (other than the serial number) then I have no *idealistic* objection to removing this limitation

I would probably suggest controlling this via a configurable setting, so that the behaviour could be configured.

Would you be willing to contribute some funding to this issue? It should not take a significant amount of time to implement this.

**Comment by baltuonis** [comment]
Hey @SchrodingersGat , Thanks for quick response!


1. I'm not very familiar with InvenTree internals, but as a KISS suggestion - could it just return the item(s) to the stock without location set?
2. Ideally for our use-case it: would allow setting returned amount and destination location.
3. I agree on configurable setting. I see how a lot of users won't be comfortable with this loose returns tracking.
4. I'm helping a volunteer organisation to modernize their processes so this is entirely on me. How much $$$ would make a worthy contribution? And how long could it take to implement? (weeks? months?)

**Comment by baltuonis** [comment]
@SchrodingersGat  
Had some time so I sat down and added this feature as a separate section. Could you please review?

P.S. Cudos for devcontainers. Deploying this locally was a Breeze.

![Image](https://github.com/user-attachments/assets/13b1ca1d-576d-4235-a3e9-36098d18799b)
