### ISSUE TITLE
SSO brocken with 0.16.6

### ISSUE THREAD

**Issue by ChristianSchindler** [inventree/InvenTree#8374]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

After updating to 0.16.6 SSO with GitLab did not work any longer: 

![Image](https://github.com/user-attachments/assets/6b378092-f5c8-4b5e-9bb4-bd18ec15821e)

![Image](https://github.com/user-attachments/assets/914a0bd5-8c52-41ce-b1d3-3909231300f7) 

I tested it with 0.16.5 and there it does work (also when rolling back to 0.16.5)

I do not even go to the SSO provider and I get a 403 at `https://****/accounts/gitlab/login/?process=login&next=/`

I did try to log in with my backup user, and in the old GUI, it does not work, but on the new one (/platform/login), it does work.

On the new GUI SSO dos also does not work

### Steps to Reproduce

- Create a SSO provieder in  0.16.5
- update to 0.16.6
- login with SSO

### Expected behaviour

I can log in

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

Update from 0.16.5 to 0.16.6

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by ChristianSchindler** [comment]
on 0.16.5 also SSO does not work and goes to (/platform/null) so this my be 2 different problems 

![Image](https://github.com/user-attachments/assets/a0b26040-cba1-46dc-8e97-ed9e6604dca5)

**Comment by SchrodingersGat** [comment]
@ChristianSchindler you'll need to provide some more information here. In particular, can you provide some of the network logs between your browser and the server during the login process?

Also, have you just recently updated to the new version? And what version were you running previously, before the update?

**Comment by ChristianSchindler** [comment]
I did my update `0.15.8` -> `0.16.6` because the SSO did not work. I then tested on `0.16.5`, and there it does work.

But I tested it on 0.16.5 and there it works and the logs are as follows regarding SSO:

![Image](https://github.com/user-attachments/assets/bae30f1e-e993-4d33-897e-052f310025b0)

on the first time of 0.16.6 (with cash):

![Image](https://github.com/user-attachments/assets/4b22fa7d-31e6-49c9-9021-1017d5c41ee4)

on 0.16.6 (without cash):
![Image](https://github.com/user-attachments/assets/6c51dc6d-9f22-4206-a8bf-a745e3215973)

**Comment by SchrodingersGat** [comment]
Can you share the actual response data from the 301 and 403 entries? Please redact any sensitive information first

**Comment by ssewell** [comment]
I'm getting the same issue in a Docker Compose instance of Inventree, but I'm not using SSO. Attempting to log in results in an error message in the logs of: `inventree-server  | Forbidden (CSRF cookie not set.): /accounts/login/`

I've confirmed this same issue is present if I attempt to log in via a reverse proxy or directly on the application server itself, so it doesn't appear to be an issue with INVENTREE_TRUSTED_ORIGINS or INVENTREE_CORS_ORIGIN_WHITELIST values at first glance.

Here's the raw response headers I get back when attempting to authenticate:
```
HTTP/1.1 403 Forbidden
Content-Encoding: gzip
Content-Language: en
Content-Type: text/html; charset=utf-8
Cross-Origin-Opener-Policy: same-origin
Date: Mon, 28 Oct 2024 22:04:53 GMT
Referrer-Policy: same-origin
Server: Caddy
Server: gunicorn
Vary: Accept-Language, Cookie
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Content-Length: 1740
```

**Comment by SchrodingersGat** [comment]
I have identified an issue in 0.16.6 release which I am patching now - https://github.com/inventree/InvenTree/pull/8390

There should be a new version out pretty soon to fix this.

**Comment by SchrodingersGat** [comment]
Closed in https://github.com/inventree/InvenTree/pull/8390

**Comment by SchrodingersGat** [comment]
I have just made a 0.16.7 release - https://github.com/inventree/InvenTree/releases/tag/0.16.7 - please note that there are *breaking changes* here and you will potentially need to make a slight tweak to your InvenTree configuration.

Note: the docker image will take a few hours to be uploaded, so wait to see when that is available on our [dockerhub page](https://hub.docker.com/r/inventree/inventree/tags)
