### ISSUE TITLE
Cannot switch to PUI - `None` shown in browser

### ISSUE THREAD

**Issue by Keybored02** [inventree/InvenTree#8393]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

When prompted to switch to PUI during login, if link is clicked no UI is loaded.![Image](https://github.com/user-attachments/assets/27f3ddf3-fa47-4073-9764-a044d04318ec)
This is not affected by the browser or machine accessing it. It happens with inventree.localhost too, with and without SSL certification.
No error report is shown in the admin console. Unsure where the log files are located with DEBUG disabled. 

### Steps to Reproduce

1. From the login screen, click the link to PUI switch.

### Expected behaviour

The UI is switched from CUI to PUI, as in the demo. A new login page appears.

### Deployment Method

- [ ] Docker
- [x] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.17.0 dev
Django Version: 4.2.14

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.10.0-33-amd64-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'KiCadLibraryPlugin', 'slug': 'kicad-library-plugin', 'version': '1.4.3'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

13:32:35 server inventree-web-1.service[2275]: Manifest file not found
Oct 29 13:32:35 server inventree-web-1.service[2275]: 192.168.1.15 - - [29/Oct/2024:12:32:35 +0000] "GET /platform HTTP/1.0" 200 401 "http://192.168.1.96/accounts/login/?next=/" "Mozilla/5.0 >
Oct 29 13:32:35 server inventree-web-1.service[2281]: 192.168.1.15 - - [29/Oct/2024:12:32:35 +0000] "GET /favicon.ico HTTP/1.0" 302 0 "http://192.168.1.96/platform" "Mozilla/5.0 (Windows NT 1>
Oct 29 13:32:35 server inventree-web-1.service[2274]: 192.168.1.15 - - [29/Oct/2024:12:32:35 +0000] "GET /accounts/login/?next=/favicon.ico HTTP/1.0" 200 8517 "http://192.168.1.96/platform" ">
lines 980-1002/1002 (END)

**Comment by SchrodingersGat** [comment]
You may not have compiled the frontend code when updating - this may be skipped depending on your setup.

Run the following command:

```
invoke update --frontend
```

And then restart the server. LMK if you see the frontend code then

**Comment by Keybored02** [comment]
Hi, thanks for the fast response. 

Unfortunately it didn't work. `invoke update` does run without errors, but the issue remains the same.

I also tried stopping the service inventree before invoking, still no luck. 

Maybe a general update would benefit it? 

I used the provided installer for the initial setup btw.

**Comment by SchrodingersGat** [comment]
Does the web browser provide any error / warning information in the console?

**Comment by Keybored02** [comment]
No, there's only a generic warning regarding COOP headers being ignored due to the fact that I don't use HTTPS. This message is common to both CUI and PUI, and it doesn't seem to have any impact.

**Comment by matmair** [comment]
@Keybored02 can you please provide the full log from `invoke update --frontend` ?

**Comment by Keybored02** [comment]
Sure, full console log here https://pastebin.com/2BP3fWMS 

syslog https://pastebin.com/DkP0eSKm

Let me know if you need anything else (and possibly the path to get it, it's all a bit dispersed)

**Comment by SchrodingersGat** [comment]
If the console log is a complete trace of the command requested by @matmair  then this shows a problem - the `install` command has failed part way through:

![Image](https://github.com/user-attachments/assets/d96f4b2b-55dc-476f-a738-c652ac41e124)


This means that the process has not continued - and copied across the required static files to render the frontend. Additionally there are other crucial steps that would have been bypassed also

**Comment by Keybored02** [comment]
You're right that might be the issue. I'm not sure whether bypassing or manually uninstalling it would be an option?

**Comment by matmair** [comment]
@Keybored02 pleawe try running `sudo inventree run cli update --uv`

**Comment by Keybored02** [comment]
Here it is https://pastebin.com/tsaM6k8s (issue still persists)

**Comment by matmair** [comment]
Are you running a development version?

**Comment by Keybored02** [comment]
Yes, [0.17.0 dev]. The default from the installation script.

**Comment by matmair** [comment]
The installer script defaults to the stable channel. Dev builds do not come with a frontend so this is to be expected.

**Comment by Keybored02** [comment]
Sorry, isn't the production installer script separated for the developer setup? I didn't use the latter ofc: https://docs.inventree.org/en/latest/start/installer/ 

I'll try to replicate it on a clean machine.

**Comment by Keybored02** [comment]
Started am install on a fresh VM and it did in fact default to stable and version 0.16.8. No idea what went wrong here, as i used the same steps as before.
Any suggested way to rollback? I definitely can do a backup and reinstall, but would it be backwards compatible?

**Comment by matmair** [comment]
We do not guarantee backwards migrations so waiting is probably for the best. Just running the installer script should be enough to migrate to stable.

**Comment by SchrodingersGat** [comment]
@Keybored02 glad you got it working :)
