### ISSUE TITLE
Alternate Part

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#841]
Do we have a way to handle alternate parts on a BOM?

**Comment by SchrodingersGat** [comment]
@lookme2 not currently, although there are some ways to work around. What exactly are you imagining here?

**Comment by lookme2** [comment]
I'm not really sure.  May you could add the Alt part# as a Qty of 0.  Just a thought.

**Comment by eeintech** [comment]
@lookme2 @SchrodingersGat 
In my experience with BoMs, alternate parts are extra columns with manufacturer data, for instance:
| Name | IPN | Designator | Quantity |  Manufacturer A |  MPN A |  Manufacturer B | MPN B |
|---|---|---|---|---|---|---|---|
| RES 10K OHM 5% 1/10W 0603 | RES-000039-00 | R1, R2  | 2 | KOA Speer Electronics, Inc. | RK73B1JTTD103J | Panasonic Electronic Components | ERJ-3GEYJ103V |

CMs usually understand the liberty to use whichever manufacturer part is easier for them to source.
What do you guys think?
