### ISSUE TITLE
Environmental variable formatting (e.g. INVENTREE_TRUSTED_ORIGINS).

### ISSUE THREAD

**Issue by mjktfw** [inventree/InvenTree#8410]
### Describe the bug*

This issue has been reported due to my miscoception about the proper formatting of env variables.

Inventree's documentions refers to django documentation in terms of `INVENTREE_TRUSTED_ORIGINS` variable.
For django the variable format is a list, while for .env file it should be just a comma-separated list of URLs.

I improperly assumed, that this is a proper formatting:
`INVENTREE_TRUSTED_ORIGINS=['https://inventree.example.com:8443','https://stock.example.com:8443']` 

While it should look like this:
`INVENTREE_TRUSTED_ORIGINS='https://inventree.example.com:8443,https://stock.example.com:8443'` 

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

InvenTree-Version: 0.17.0 dev
Django Version: 4.2.16
Commit Hash: cc6a2f4
Commit Date: 2024-11-02

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-25-amd64-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@mjktfw thanks for the report! Would you be able to make a PR to adjust the documentation accordingly?

The file in question is here - https://github.com/inventree/InvenTree/blob/master/docs/docs/start/config.md

**Comment by SchrodingersGat** [comment]
Docs incoming in https://github.com/inventree/InvenTree/pull/8499
