### ISSUE TITLE
Printing report option from part table

### ISSUE THREAD

**Issue by Vimalbhimani2000** [inventree/InvenTree#8425]
![Image](https://github.com/user-attachments/assets/4853b894-d854-44c6-8a77-e3c91a0a5433)
![Image](https://github.com/user-attachments/assets/c587401e-2a6b-497f-9cca-d4f052c04fb3)
### Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find a similar feature request

### Problem statement

If print features is available in part menu in part table with stock it good for use , also possible add printing report option in home menu for total pending SO And others , thanks add image please check

### Suggested solution

In my use case want to know each parts how many stocks with batch detail in print 

### Describe alternatives you've considered

No haven’t idea

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@Vimalbhimani2000 sorry, I'm not quite sure what you are asking for here. Can you please add some more context? Perhaps some screenshots / mockups of what you are looking for

**Comment by Vimalbhimani2000** [comment]
> [@Vimalbhimani2000](https://github.com/Vimalbhimani2000) sorry, I'm not quite sure what you are asking for here. Can you please add some more context? Perhaps some screenshots / mockups of what you are looking for

![Image](https://github.com/user-attachments/assets/7a1bf157-7ff6-442e-b310-53236b56512d)
![Image](https://github.com/user-attachments/assets/6672a1c6-b046-4bbc-a14a-485cb34adfc3)

 Please check image
Required printing report button if possible

**Comment by SchrodingersGat** [comment]
Ah, ok. That functionality is all provided in the [new user interface](https://github.com/inventree/InvenTree/issues/5212) which we are working hard to finalize. As such, any minor tweaks to the existing (legacy) UI will not be given much attention by the core dev team.

If you want to submit a patch to fix this, I'll be happy to review. But our main focus is getting the new user interface across the line.
