### ISSUE TITLE
Invalid Operation

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#847]
Hello Oliver,
I put some parts into the Parts and did a BOM. I must have done something wrong because when I click on the BOM P/N that I set up it doesn't take me to the BOM any more, I get the following:
Request Method: | GET
-- | --
http://127.0.0.1:8000/part/3/
3.0.5
InvalidOperation
[<class 'decimal.DivisionUndefined'>]
/home/larry/InvenTree-master/inventree/InvenTree/part/models.py in can_build, line 647
/home/larry/InvenTree-master/inventree/inventree-env/bin/python
3.6.9
['/home/larry/InvenTree-master/inventree/InvenTree',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages',  '/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/odf',  '/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/odf',  '/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/odf',  '/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/odf',  '/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/odf',  '/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/odf',  '/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/odf']
Sun, 31 May 2020 20:16:48 +0000

This is not all of the report, but I think it will do. I think it's saying that there was an attempt at division by zero, but what do I know? How to overcome this?
--Thanks, Larry

**Comment by SchrodingersGat** [comment]
Looking through the code, this seems like it could only occur if a BOM item has a "quantity" field set to zero. Is this the case for any of the lines in the BOM?

In any case I have issued a fix for this issue - https://github.com/inventree/InvenTree/pull/850

Please grab the updated version - you can see the [updating instructions here](https://inventree.github.io/docs/start/update).

I believe that this code change should fix the issue you are seeing.

**Comment by LarryJoy** [comment]
Oliver,
Your update worked, I was able to get into the BOM. Yes, there were two items that had a quantity of 0 (zero), but they were both marked as Virtual parts and I think I left the quantity blank as they are drawings/documents and the ref des used is "REF#" as they are references.

Also, when opening this BOM there is a statement at the top that reads "The BOM for 10077 | ASSY PL does not have complete pricing information". The listing for the two items has "No pricing available" and this is true as they are drawings. Is this going to interfere with a COGS calculation?
--Larry
