### ISSUE TITLE
How to Enter Categories and Subcategories?

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#848]
I am confused as to what to enter where. I want to set up a parent category of Capacitors with Subcategories of Axial leaded and Radial leaded. The entry screen has Parent, Name, and Description. I don't understand what is meant by Description when you have the Category (and Subcategory) that is descriptive. Please indicate what I should enter.
--Thanks, Larry

**Comment by SchrodingersGat** [comment]
The description is simply a place to add some descriptive text regarding the part category. The latest update to InvenTree makes this text optional - so you do not have to enter anything.
