### ISSUE TITLE
Can't login anymore with the original UI

### ISSUE THREAD

**Issue by Mimosa-oceanis** [inventree/InvenTree#8485]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

We have updated from 0.16.1 to 0.16.7 and from that moment it is not possible to login on the original UI. It works with the new Platform UI. 
We tried with 0.16.8 and not working either. 

### Steps to Reproduce

Update to 0.16.7
Logout
Try to login...

### Expected behaviour

The expected behavior is to be able to login on the original UI.

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

<h5 class="m_8a5d1357 mantine-Title-root" data-order="5" style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px; font-weight: var(--title-fw); font-size: var(--title-fz); line-height: var(--title-lh); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">Version Information</h5><div class="m_4081bf90 mantine-Group-root" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; display: flex; flex-direction: row; flex-wrap: var(--group-wrap, wrap); justify-content: var(--group-justify, flex-start); align-items: var(--group-align, center); gap: var(--group-gap, var(--mantine-spacing-md)); caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;"><p class="mantine-focus-auto m_b6d8b162 mantine-Text-root" style="box-sizing: border-box; text-decoration: none; font-size: var(--text-fz, var(--mantine-font-size-md)); line-height: var(--text-lh, var(--mantine-line-height-md)); font-weight: 400; margin: 0px; padding: 0px; color: var(--text-color);">Your InvenTree version status is</p><div class="m_347db0ec mantine-Badge-root" style="box-sizing: border-box; --badge-height-xs: calc(1rem * var(--mantine-scale)); --badge-height-sm: calc(1.125rem * var(--mantine-scale)); --badge-height-md: calc(1.25rem * var(--mantine-scale)); --badge-height-lg: calc(1.625rem * var(--mantine-scale)); --badge-height-xl: calc(2rem * var(--mantine-scale)); --badge-fz-xs: calc(.5625rem * var(--mantine-scale)); --badge-fz-sm: calc(.625rem * var(--mantine-scale)); --badge-fz-md: calc(.6875rem * var(--mantine-scale)); --badge-fz-lg: calc(.8125rem * var(--mantine-scale)); --badge-fz-xl: calc(1rem * var(--mantine-scale)); --badge-padding-x-xs: calc(.375rem * var(--mantine-scale)); --badge-padding-x-sm: calc(.5rem * var(--mantine-scale)); --badge-padding-x-md: calc(.625rem * var(--mantine-scale)); --badge-padding-x-lg: calc(.75rem * var(--mantine-scale)); --badge-padding-x-xl: calc(1rem * var(--mantine-scale)); --badge-height: var(--badge-height-md); --badge-fz: var(--badge-fz-md); --badge-padding-x: var(--badge-padding-x-md); --badge-radius: calc(62.5rem * var(--mantine-scale)); --badge-lh: calc(var(--badge-height) - calc(.125rem * var(--mantine-scale))); --badge-color: var(--mantine-color-white); --badge-bg: var(--mantine-color-green-filled); --badge-bd: calc(0.0625rem * var(--mantine-scale)) solid transparent; font-size: var(--badge-fz); border-radius: var(--badge-radius); height: var(--badge-height); line-height: var(--badge-lh); text-decoration: none; padding: 0 var(--badge-padding-x); display: inline-flex; align-items: center; justify-content: center; width: fit-content; text-transform: uppercase; font-weight: 700; letter-spacing: calc(.015625rem * var(--mantine-scale)); cursor: inherit; text-overflow: ellipsis; overflow: hidden; color: var(--badge-color); background: var(--badge-bg); border: var(--badge-bd);"><span class="m_5add502a mantine-Badge-label" style="box-sizing: border-box; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">UP TO DATE</span></div></div>
InvenTree Version | 0.16.8
-- | --
Commit Hash | f23d405
Commit Date | 2024-11-07
Commit Branch |  
API Version | 232
Python Version | 3.11.9
Django Version | 4.2.15

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Version Information
Your InvenTree version status is
UP TO DATE
InvenTree Version	
[0.16.8](https://github.com/inventree/InvenTree/releases)
Commit Hash	
f23d405
Commit Date	
2024-11-07
Commit Branch	
API Version	
[232](http://34.65.2.157/api-doc/)
Python Version	
3.11.9
Django Version	
[4.2.15](https://www.djangoproject.com/)
Links
InvenTree Documentation	
https://docs.inventree.org/en/0.16.8
View Code on GitHub	
https://github.com/InvenTree/InvenTree/
Credits	
https://docs.inventree.org/en/latest/credits/
Mobile App	
https://docs.inventree.org/app/
Submit Bug Report	
https://github.com/InvenTree/InvenTree/issues

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by matmair** [comment]
Sounds like https://github.com/inventree/InvenTree/pull/8390#issue-2619731965

**Comment by SchrodingersGat** [comment]
@Mimosa-oceanis please read the release notes for  [0.16.7](https://github.com/inventree/InvenTree/releases/tag/0.16.7) - there is a breaking change / bug fix which requires a change to a config parameter for existing installations

**Comment by matmair** [comment]
@Mimosa-oceanis did this help?

**Comment by Mimosa-oceanis** [comment]
@matmair No it didn't helped. We rolled back to 0.16.1 and we will upgrade gradually on a second instance before deploying our production one.

**Comment by matmair** [comment]
We won't be able to help without further information about the error and crucially logs from the server

**Comment by Mimosa-oceanis** [comment]
> We won't be able to help without further information about the error and crucially logs from the server

@nuffer you can put some info about the issue here.
