### ISSUE TITLE
Getting error while invoke setup-test

### ISSUE THREAD

**Issue by lathigarachetan** [inventree/InvenTree#8488]
### Deployment Method

- [x] Installer
- [ ] Docker Development
- [x] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Installing/Running invenTree through the docker deployment guide. I am able to run all require docker images and getting login page as well with localhost / Machine IP. 
But getting error while try to install test user and data using below command.

Command run : docker compose run --rm inventree-server invoke setup-test -i

Error after above command executed : 

django.db.utils.IntegrityError: Problem installing fixture '/home/inventree/inventree-demo-dataset/inventree_data.json.data.json': Could not load order.SalesOrderAllocation(pk=91): null value in column "shipment_id" of relation "order_salesorderallocation" violates not-null constraint
DETAIL:  Failing row contains (91, 1.00000, 1286, 27, null).
ERROR: 1

It would be great help if anyone help to fix / solve the above issue.

### Steps to Reproduce

0. Run invenTree images (proxy, server, worker, db, cache) using URL : https://docs.inventree.org/en/latest/start/docker_install/#before-you-start
1. Check if getting Login screen using localhost or Machine IP
2. Run below command to setup test data.
docker compose run --rm inventree-server invoke setup-test -i
3. Check if the data inserted or error in insert data (for me i am getting error as mention in "Describe the problem")

### Relevant log output

```bash
Error after above command executed : 

django.db.utils.IntegrityError: Problem installing fixture '/home/inventree/inventree-demo-dataset/inventree_data.json.data.json': Could not load order.SalesOrderAllocation(pk=91): null value in column "shipment_id" of relation "order_salesorderallocation" violates not-null constraint
DETAIL:  Failing row contains (91, 1.00000, 1286, 27, null).
ERROR: 1
```

**Comment by SchrodingersGat** [comment]
Likely you have unapplied database schema migrations. 

Run `invoke migrate` first - and then run `invoke setup-test`

**Comment by SchrodingersGat** [comment]
Also, please provide version information?

**Comment by lathigarachetan** [comment]
> Likely you have unapplied database schema migrations.
> 
> Run `invoke migrate` first - and then run `invoke setup-test`

@SchrodingersGat, Thanks for prompt reply.

Getting same error after execute invoke migrate first and then invoke setup-test command.

invoke migrate : 
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.

invoke setup-test : 

django.db.utils.IntegrityError: Problem installing fixture '/home/inventree/inventree-demo-dataset/inventree_data.json.data.json': Could not load order.SalesOrderAllocation(pk=91): null value in column "shipment_id" of relation "order_salesorderallocation" violates not-null constraint
DETAIL:  Failing row contains (91, 1.00000, 1286, 27, null).
ERROR: 1

**Comment by lathigarachetan** [comment]
> Also, please provide version information? The demo dataset may be ahead of your installed version.

I am using "inventree:stable" docker image, Please find screenshot below.

![Image](https://github.com/user-attachments/assets/76932d97-bc49-438f-954b-f1985225831b)

**Comment by SchrodingersGat** [comment]
@lathigarachetan I have now fixed the demo dataset - please try again it should work now.

Ref: https://github.com/inventree/demo-dataset/pull/84
