### ISSUE TITLE
More Input and Questions

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#849]
• Under **InvenTree - Intuitive Inventory Management**
**How it Works**
1st paragrapyh, 2nd line "...via a web brower..." "brower" should be "browser".
• Under **Part**
**Part Category**
The example shown for "Passives" needs to be larger so it is readable.
• How to sort Parts numerically according to my IPN assigned?
• How to get a printout of Parts?
--Thanks, Larry

**Comment by SchrodingersGat** [comment]
Thanks for the heads up on another typo.

> How to sort Parts numerically according to my IPN assigned?

This is a good idea, I have now added an "IPN" column to the part display table which allows ordering by IPN: https://github.com/inventree/InvenTree/pull/855

You can grab the updated code to use this feature

> How to get a printout of Parts?

A part printout feature is not yet available

**Comment by LarryJoy** [comment]
Please add an IPN column to the "Stock" table also.
--Larry
