### ISSUE TITLE
No Parts Shown in List View

### ISSUE THREAD

**Issue by rco3** [inventree/InvenTree#851]
Two systems (one home, one work) on which testing and development copies of Inventree are running; both Raspberry Pi running Raspbian.  In both cases (different datasets entirely), I have recently updated the Inventree install to the latest update (c1da4d5 just now here at home, 7c7055c at work yesterday) and have updated Raspbian to latest.  

In both systems, the Part list views simply do not appear.  I see a count of parts in a Category, but when I select that category no Parts are listed.  They are all visible through the admin interface, so I know that they are there.  I cannot see any problem with the parts themselves.

To update Inventree, I have followed the following steps:

```
sudo systemctl stop gunicorn
git pull origin master
make update
sudo systemctl start gunicorn
```

Have I missed a step? Done something incorrectly?

**Comment by SchrodingersGat** [comment]
What filters do you have setup for the part display table?

![Uploading image.png…]()

**Comment by rco3** [comment]
Thanks for response.

1. Didn't realize that there WERE filters for that table; guess I don't have enough parts to have needed them yet.  
2. AFAIK, haven't set any.
3. I don't see any filters next to the trashcan.  I do see the filter icon and the trashcan icon.  Neither of them do anything when pressed.

<img width="773" alt="MissingParts_SS" src="https://user-images.githubusercontent.com/63524655/83752393-79323600-a636-11ea-846b-68d85879cc27.png">

**Comment by rco3** [comment]
SOrry, didn't mean to close the issue.  Wrong button.

**Comment by rco3** [comment]
Update: I saw no immediate effect from either of the two filter buttons.  With no apparent filters assigned, I saw no parts in any category.

After pressing both the Filter button and the Trash button and seeing no results, I responded accordingly above.  A few minutes later, I was continuing to poke around, and noticed that I was now seeing parts in their Categories.  I wasn't seeing Parts in subcategories, but now when I press the Filter button I am offered various filters which I can apply.  Something has changed, apparently as a result of attempting to add or remove filters.  Could it be that the list filter was somehow set or initialized to a non-valid state?

I'll try to repeat this again at work, see what state the list filters are in and what happens when I try to interact with them.

**Comment by rco3** [comment]
Just updated the second system at work.  Same process: stop server, update from origin, make update, start server.  This system does not show parts, and does not show any icons for filtering.  I can navigate directly to a part detail page (assuming I know the pk), and I can view all parts in the admin interface.

**Comment by lookme2** [comment]
Look below the Part Categories table.  This is what mine looks like.
![Annotation 2020-06-04 085731](https://user-images.githubusercontent.com/11365211/83766153-a89a7000-a641-11ea-97c9-2f5913171d11.png)

**Comment by rco3** [comment]
Thanks, lookme2.  As you can (hopefully) see in the screenshot I posted from the install at home, those buttons are present.  So, I now know what to look for.  However, in the installation at the office (just updated to same version), I don't have those buttons.  They simply aren't there.  

![MissingFilterButtons](https://user-images.githubusercontent.com/63524655/83772335-447fa800-a651-11ea-9270-eb8ab4b16432.png)


I'm stumped.

**Comment by lookme2** [comment]
That is strange.  I am running V 0.1.1.  Have you tried 0.1.1?

**Comment by rco3** [comment]
I updated both installations to the very most recent version immediately before posting, commit c1da4d5.

**Comment by SchrodingersGat** [comment]
Ok, the fact that your buttons are missing probably means that the javascript code that renders the tables is going wrong.

Can you open "developer mode" in your browser (If you are running firefox, this is `Ctrl+Shift+I`) and you can see if the javascript is throwing any errors.

## Network Activity

First step, see what the page is requesting from the server. Navigate to the "network" tab, and filter traffic by "XHR":

![image](https://user-images.githubusercontent.com/10080325/83827273-3c8f3900-a721-11ea-8907-ebfbabff381c.png)

Refresh the page (`Ctrl+R`) and you should see an API request like follows:

![image](https://user-images.githubusercontent.com/10080325/83827300-4add5500-a721-11ea-82f2-7ddaeeaf5a93.png)

Which returns status code 200:

![image](https://user-images.githubusercontent.com/10080325/83827357-78c29980-a721-11ea-80a8-1b1954b37f91.png)

## Script Console

Select the `Console` tab:

![image](https://user-images.githubusercontent.com/10080325/83827373-8e37c380-a721-11ea-92d4-6247866a6f82.png)

If the javascript code is failing, you will see error messages here (in red)

Please let me know what happens when you try this!

**Comment by rco3** [comment]
Will check today when I'm at that location.  Thanks.

**Comment by rco3** [comment]
Opened in Firefox, loading /part/category/2/, I get:


```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 2
jQuery.Deferred exception: query is undefined loadPartTable@http://192.168.168.31/static/script/inventree/part.js:95:9
@http://192.168.168.31/part/category/2/:614:18
l@http://192.168.168.31/static/script/jquery_3.3.1_jquery.min.js:2:29375
a/</c<@http://192.168.168.31/static/script/jquery_3.3.1_jquery.min.js:2:29677
 undefined jquery_3.3.1_jquery.min.js:2:30930
TypeError: query is undefined
part.js:95:9
Source map error: Error: request failed with status 404
Resource URL: http://192.168.168.31/static/css/bootstrap_3.3.7_css_bootstrap.min.css
Source Map URL: bootstrap.min.css.map
```

Should I just blow this away and reinstall fresh?  I can cache my config.yaml and drop it in to the new install, should go pretty quick.

**Comment by SchrodingersGat** [comment]
Try running, from the ./inventree directory:

`make update`
`make static`

And see if you still get the same errors...

**Comment by rco3** [comment]
make static.  No, haven't done that.  

Thanks, I'll try that Monday.

**Comment by rco3** [comment]
OK, problem cropped up again in the home install.  Few other weirdnesses going on. Can't see any test results, either.

Some of this behavior is now browser-specific.  Safari is showing filter buttons, but they do nothing.  However, in the console I see that there are complaints about:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap-table.css.map, line 0)
[Error] SyntaxError: Unexpected token '?'
	(anonymous function) (table_filters.js:65)
[Warning] jQuery.Deferred exception: Can't find variable: getAvailableTableFilters (2) (jquery_3.3.1_jquery.min.js, line 2)
getFilterSettings — filters.js:148
getFilterOptionValue — filters.js:389
setupFilterList — filters.js:273
loadPartTable — part.js:91
(anonymous function) — 14:634
l — jquery_3.3.1_jquery.min.js:2:29381
(anonymous function) — jquery_3.3.1_jquery.min.js:2:29679
undefined
[Error] ReferenceError: Can't find variable: getAvailableTableFilters
	(anonymous function) (jquery_3.3.1_jquery.min.js:2:31048)`

**Comment by rco3** [comment]
Monday AM: system I'm testing/dev with at the office.

```
sudo systemctl stop gunicorn
git pull origin master
make update
make static
sudo systemctl restart nginx
sudo systemctl start gunicorn
```

After this update (0.1.1pre commit b2c302cb) and restart, I have no observable issues with part visibility or with part filters not working, using either Safari or Firefox.

Thanks all for the help.

**Comment by SchrodingersGat** [comment]
Glad that it's working for you again. Sounds like (for some reason) the static files got out of sync with the server, so it was requesting old versions of the files, or something? Very strange. I'll certainly keep my  eye out for similar issues in the future.
