### ISSUE TITLE
Ability to add machine config (easily)

### ISSUE THREAD

**Issue by gid204** [inventree/InvenTree#8510]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

I've found a few concurrent things, which I believe may be issues/bugs.

In the original admin UI, when adding a machine there's no way to actually add (type in) the machine settings:
![Image](https://github.com/user-attachments/assets/17f0119c-5df2-4e54-8ba4-1d4940a90520)

In the new Platform UI I am able to modify these fields but they often will just not appear and require me to spam the refresh button for a few minutes until they show up. When they do show up the setting I am editing will often just spin.

Settings not showing:
![Image](https://github.com/user-attachments/assets/bde66153-3648-4128-90f9-4a2015ec5fcd)

Spam refresh to get the settings to show:
![Image](https://github.com/user-attachments/assets/18935552-d63e-40e4-9a77-91c50c944e5f)

Try to modify settings and it just spins:
![Image](https://github.com/user-attachments/assets/e70a61a0-f290-4ad9-8768-873e219aacfb)

I have a sneaky suspicion (without evidence) that the Cups Driver plugin is freaking out and either crashing/timing out as I try to edit the settings.

### Original UI 
1. Admin menu > Machine configs > Add Machine Config
2. From here you can add the name, type and driver but can't edit any settings.

### New Platform UI
1. Go to: Admin centre > Machines > "+" button to add machine.
2. Type in name, type and driver and press submit
3. Machine settings should then present for editing (without disappearing).

### Expected behaviour

Upon adding a machine either via the new or old UI, I should be able to enter the machine settings without them disappearing.

If I can help do further tests or if this should be raised in the Cups Driver Plugin issues page please let me know :)

### Deployment Method

- [ ] Docker
- [ ] Package
- [x] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.16.3
Django Version: 4.2.15

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-200-generic-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'CupsLabelPrinterDriver', 'slug': 'cups-driver', 'version': '1.0.0'}, {'name': 'IPNGenerator', 'slug': 'ipngen', 'version': '0.1'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by SchrodingersGat** [comment]
@wolflu05 any thoughts on this one?

**Comment by wolflu05** [comment]
> original admin UI

This is not ment for manually adding things. The Admin Center from PUI is the right place.

> Missing DRIVER settings: PRINTER
> In the new Platform UI I am able to modify these fields but they often will just not appear and require me to spam the refresh button for a few minutes until they show up. When they do show up the setting I am editing will often just spin.

Thats exactly why you shouldn't use the django admin UI to manage machines. I suggest deleting that broken machine and add a new one via the Admin Center. 

> I have a sneaky suspicion (without evidence) that the Cups Driver plugin is freaking out and either crashing/timing out as I try to edit the settings.
> If I can help do further tests or if this should be raised in the Cups Driver Plugin issues page please let me know :)

Yes, that's more related to the cups driver plugin. That can happen if you enter a wrong host/port/user/password. The plugin then tries to connect to the cups server and load all available printers. If these values are wrong, the plugin cannot connect, resulting in the connection closes due to a timeout issue. And due to the nature of the pycups library (the only I could find for python) the thread is blocked until it timed out. I have already planned to restructure the plugin by creating a second docker image with a simple http API which handles the cups connection so that the main inventree process is not blocked, and the installation process is much simpler than needing to build a custom image which contains the cups headers, but unfortunately I had no time, yet.

Hope that helps.

**Comment by matmair** [comment]
@wolflu05 I am left unsure if this is a bug or a FR - what is your opinion?

On another note: If you can break stuff when adding machines in the admin - should we remove that option? I can PR that.

**Comment by wolflu05** [comment]
I am not sure, if there is anything related to inventree core in this issue at all, so I suggest closing this issue, and if there pop up any issues with my inventree-cups-plugin after reading my above comment, feel free to open an issue there. 

> On another note: If you can break stuff when adding machines in the admin - should we remove that option? I can PR that.

But can't we do that with all other admin things in django admin too? If some does something there, he should be knowing what he is doing. But no strong objection there, if you feel that confuses people feel free to remove it.

**Comment by matmair** [comment]
tbh most of the django admin is a foot gun - we should discuss locking it down/removing most apps from it

**Comment by gid204** [comment]
@wolflu05 Sorry can you clarify what the Django admin UI is?
> Thats exactly why you shouldn't use the django admin UI to manage machines. I suggest deleting that broken machine and add a new one via the Admin Center.

I was adding and modifying machine settings here:
![Image](https://github.com/user-attachments/assets/8056f396-a04b-4479-be20-577c25f292a1)
