### ISSUE TITLE
Make stock location report to include the out of stock items

### ISSUE THREAD

**Issue by templeofhead** [inventree/InvenTree#8545]
### Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find a similar feature request

### Problem statement

Hello! I'm currently working on a stock location report template, based on the default template that comes with the inventree, and i found myself struggling with making said template to include the out of stock (zero quantity) items to the rendered table. 

### Suggested solution

So far, the template loops through `stock_items.all` and i was thinking, should i maybe make it somehow to loop through parts and not the stock, yet i have no clue how to do so. If you could help me resolve this issue, or point me in the right direction, i would appreciate that a lot.

### Describe alternatives you've considered

I've been through docs, had a gander at the API (with my limited knowledge of coding i might've overlooked something though) to no avail. While the stock location report is extremely useful for verifying and correcting the physical stock amounts, the only alternative that i see so far is to print the report, count the stock items, and if something that isnt included in the report is found - mark it down manually and include into the inventree database later, which is arduous and confusing for the employee that would execute said stock verification.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@templeofhead if I am understanding you correctly, you should be able to something like the following to access each `Part` instance

```html
{% raw %}
{% for item in stock_items.all %}
Part: {{ item.part }}
{% endraw %}
```

**Comment by templeofhead** [comment]
It still loops through the stock items, like i had before, and pretty much returns everything as it were. What do i need (i think) is to loop through all the parts, not just the stock (i understand that it contradicts with the idea of "stock location report" but bear with me for a little while, i'll explain) since its needed sorely for physical stock counting and amount verification purposes.

**Comment by SchrodingersGat** [comment]
So you don't want to limit just to the available stock items in the selected category, but also some subset of the available parts in the database?

**Comment by templeofhead** [comment]
Yes, precisely! The idea is to make a list of everything that is stored in the warehouse, parse through it (physically i mean), compare with the list of items that is in the database (inventree) and verify the amounts.

**Comment by SchrodingersGat** [comment]
So, I think you are probably coming at it from the wrong angle. If you print a report for a given "location" - it will return any *items* in that location.

However, if you made a report template against a specific part *Category* you could iterate over all parts in that category - and then over each stock item for each of those parts, if you wanted

**Comment by templeofhead** [comment]
Yeah, you're right, about the wrong angle. What about making a report against all the parts that is in the database, is this possible? Gategories are good, but at the end of the day i would need to count the whole warehouse anyway, so this option is needed as well.

**Comment by SchrodingersGat** [comment]
@templeofhead not currently, although I am looking into how this might be possible.

You can always extend reporting functionality using a plugin to add the extra context you need:

https://docs.inventree.org/en/stable/report/templates/#extending-with-plugins

**Comment by templeofhead** [comment]
Thank you for the info, i'll have a look into the plugin. Also, should we keep this issue open incase you find something that works?

**Comment by SchrodingersGat** [comment]
@templeofhead yes let's keep open for now

**Comment by templeofhead** [comment]
While it's impossible to iterate through all the parts, could you advice me how to iterate through categories at least? I think i can use those as a substitute still.

**Comment by templeofhead** [comment]
You've mentioned that i should have part category available in the report context, could you elaborate on this some more? How do i know if i have or haven't? I can post the code of the current template too, if it's of any help.

**Comment by SchrodingersGat** [comment]
You can see what context variables are available by default, for each report type, here:

https://docs.inventree.org/en/latest/report/context_variables/#template-types

**Comment by matmair** [comment]
@templeofhead do I read this correctly that you are going to use a template - ie. we can close this FR?

**Comment by templeofhead** [comment]
I'm pretty much done with it, and even if i'm not - i have the general idea of how it works now. So yeah, feel free to close it :)
