### ISSUE TITLE
[FR] Make filter or status for consumed parts.

### ISSUE THREAD

**Issue by alxrMironov** [inventree/InvenTree#8552]
### Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find a similar feature request

### Problem statement

Serialized parts, what been consumed by build order cant be easy filtered out. 

Example: 
I have part "PC" with serial number and  part "Mainboard", serialized too.
So, after building and selling a few PCs, if im trying to search mainboads by OK status (or any other), i will have consumed mainboards in search results.
There is also checkbox "Is Available", but it filters out quarantined\lost and other statuses.

### Suggested solution

So, we need special status for consumed parts or checkbox field.

### Describe alternatives you've considered

.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
@alxrMironov adding in such a filter would be pretty simple - would you like to submit a PR for this? I would be happy to point you to the places in code where it would need to be implemeted

**Comment by alxrMironov** [comment]
> [@alxrMironov](https://github.com/alxrMironov) adding in such a filter would be pretty simple - would you like to submit a PR for this? I would be happy to point you to the places in code where it would need to be implemeted

I'd like, but im embedded programmer, not web, i have near zero knowleges about websites architecture and ecosystem.

**Comment by templeofhead** [comment]
Can't say this is my area of expertise as well.

**Comment by SchrodingersGat** [comment]
> I'd like, but im embedded programmer

Me too ;) that's no excuse :)
