### ISSUE TITLE
Serial numbers: integer only?

### ISSUE THREAD

**Issue by rco3** [inventree/InvenTree#860]
Many of the parts I'll be using in assemblies include a factory-assigned serial number.  For a variety of obvious reasons I'd like to use that SN for tracking stock if present.  Currently the web interface, at least, rejects serial numbers that are non-integer.  I assume that this is to ease auto-generation of SNs; perhaps either option can be supported?

**Comment by SchrodingersGat** [comment]
Yes currently only integer values are supported. To change this would require changing the field-type in the database, and also a lot of the validation code would need to change.

It would be possible to implement this, though. I'll add it to the pile ;)

**Comment by bcc** [comment]
Too simple, it turns out - works fine on sqlite, but not postgres. I've refactored a bit so it's now DB independent, a bit cleaner and fixed some issues I found while doing some more testing. I've tried pretty hard to retain the existing behaviour for int-only serials, and I think this all works now, but I'll be testing with some real data over the next day or so.

**Comment by erkutalakus** [comment]
I guess, something with version 0.3.0 broke this non-integer serial number support. It gives an error at the stock item detail page, for the stock items, which has non-integer serial numbers. The exception I got is here (belongs to v0.4.2 though):

```
Environment:


Request Method: GET
Request URL: http://some_deployment/stock/item/48/

Django Version: 3.2.4
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'InvenTree.apps.InvenTreeConfig',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup.apps.CleanupConfig',
 'mptt',
 'markdownx',
 'markdownify',
 'django_admin_shell',
 'djmoney',
 'djmoney.contrib.exchange',
 'error_report',
 'django_q',
 'formtools']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware',
 'error_report.middleware.ExceptionProcessor']



Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/inventree/InvenTree/stock/views.py", line 127, in get
    return super().get(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/home/inventree/InvenTree/stock/views.py", line 95, in get_context_data
    serial_elem = {int(a.serial): a for a in self.object.part.stock_items.all() if a.serialized}
  File "/home/inventree/InvenTree/stock/views.py", line 95, in <dictcomp>
    serial_elem = {int(a.serial): a for a in self.object.part.stock_items.all() if a.serialized}

Exception Type: ValueError at /stock/item/48/
Exception Value: invalid literal for int() with base 10: 'C06442406JTFT9TAK'
```

**Comment by eeintech** [comment]
@erkutalakus It sounds like you have a SKU/MPN in your serial number field of your stock item 48, try to correct this?

**Comment by SchrodingersGat** [comment]
@erkutalakus definitely looks like a regression here

**Comment by damien-ls** [comment]
On The extension of this, having a header on serial numbers like "SN12345" and on all other "numbers" that can be printed into barcode allows more efficient search in database and enables batch scanning / processing.

It allows people in an organization to know whether a label refers to a serial number or some other forms of ID.

It allows the app/system to have awareness the canned item is a barcode,  reducing user input / improving DB search of the part. 

To the extension, same could apply for other form of ID, even if the QR code may give context, it would simplify the label as the ID itself contains what is the ID about.

Example:
Serial Number "SN1234"
Location ID: "LOC1234"
Part ID: "PRT1234"
etc...

This allows to develop context awareness barcode scanning system, simplifies user input and simplifies batch scanning, improve database searches, etc.. and enables lean manufacturing and will enable the development of more functionalities.

**Comment by SchrodingersGat** [comment]
@damien-ls this is a pretty old issue. We now have the [Validation Plugin System](https://docs.inventree.org/en/latest/extend/plugins/validation/) which allows users to write their own validation requirements for things like serial numbers etc.

If you have any specific questions about developing a custom validation plugin, please open a new issue :)
