### ISSUE TITLE
[PUI] IPN missing in search

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#8601]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Searching in the old interface shows the IPN and the mart name:

![Image](https://github.com/user-attachments/assets/2d2884bd-9c0c-4fc0-b71d-b6846f21a416)

In the new interface the IPN is missing:
![Image](https://github.com/user-attachments/assets/2cd6394f-8fff-466c-bece-df72d43f0443)

### Steps to Reproduce

1. click search button
2. enter search string

### Expected behaviour

IPN should be shown

### Deployment Method

- [ ] Docker
- [ ] Package
- [x] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

0.17.0.dev
c734741
2024-11-24

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by turist79** [comment]
Hi mate,

it works for me:

![Image](https://github.com/user-attachments/assets/49b2a97e-f9c4-4476-9879-1fc69e343fe6)

Did you check the Search settings in options, probably something misconfigured there?

PS: i expected it to be Whole word serach option but strange enough it does not do what i expected - ie setting it to true does not prevent partial search :)

**Comment by SergeoLacruz** [comment]
I made an update just now. Still the same result. I did not find a corresponding search setting:
![Image](https://github.com/user-attachments/assets/1333295f-7468-4c03-8fba-28a79b09a378)

During update I got this massage:

InvenTree database migrations completed
Updating frontend...
Downloading frontend...
Current frontend information for commit is not available - this is expected in some cases
ERROR: Cannot find any workflow runs for current SHA
Python version 3.10.12 - /usr/bin/python3
Adding plugin sample static content

**Comment by SchrodingersGat** [comment]
@SergeoLacruz if you are running from `0.17.0 dev` version then the UI is not correctly up to date. The search table should look like this:

![Image](https://github.com/user-attachments/assets/c3f29489-5b9f-453b-aec3-d8f3222a8f2a)

So, I think that the user-interface files are not being downloaded properly - so probably this error is factoring in:

```
ERROR: Cannot find any workflow runs for current SHA
```

Can you please share the entire log for the update process?

**Comment by SergeoLacruz** [comment]
Here it comes:

[log.txt](https://github.com/user-attachments/files/17969213/log.txt)

It's a bare metal setup on Ubuntu 22.04. 
Your picture does not show the problem because 1553WBDK from the demo dataset does not have an IPN.

**Comment by matmair** [comment]
It seems lke you are running bare metal. In this case you will have to build the frontend yourself by running `invoke int.frontend-build`. This requires node to be presend on the system

**Comment by SergeoLacruz** [comment]
I remember...
We discussed this already. 
I former times I needed to download the frontend manually.

**Comment by wolflu05** [comment]
You can still download the frontend manually, but only if you run on a sha on official master and not some custom modified version. Or you use a tagged version, then the download should happen automatically.

**Comment by SergeoLacruz** [comment]
```
michael@Tree:~/src$ invoke int.frontend-build
Building frontend
yarn run v1.22.22
$ tsc && vite build --emptyOutDir
src/App.tsx(1,29): error TS2307: Cannot find module '@tanstack/react-query' or its corresponding type declarations.
src/App.tsx(2,19): error TS2307: Cannot find module 'axios' or its corresponding type declarations.
src/components/Boundary.tsx(1,19): error TS2307: Cannot find module '@lingui/macro' or its corresponding type declarations.
...
```
Several hundred errors. 
This seems to be an endless story. Giving up...

**Comment by matmair** [comment]
@SergeoLacruz this error means the required packages are not there; `invoke int.frontend-compile` will set up everything

**Comment by SergeoLacruz** [comment]
Victory :-)
On Ubuntu 22.04 There are some more things to do:

install npm
install tsx using npm
install yarn
install node-typescript

For nodejs upgrade package info because the latest on 22.04 is 12:

curl -sL https://deb.nodesource.com/setup_20.x | sudo bash -
sudo apt-get install nodejs 

invoke int.frontend-install
invoke int.frontend-trans
invoke int.frontend-build

got some warnings like 

▲ [WARNING] Unexpected "(" [css-syntax-error]

    <stdin>:91:2:
      91 │   (max-width: 48em) {
         ╵   ^

Finally the new UI works es expected and the IPN is there :-) Thanks to all for the help. 
I will add a paragraph to the docs soon.
