### ISSUE TITLE
Custom Stock Status filter does not work

### ISSUE THREAD

**Issue by gunstr** [inventree/InvenTree#8612]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

With reference to #7990 

When a Custom State is assigned to a Stock Item and also selected as a filter no items are being displayed in a Stock Item list.

### Steps to Reproduce

This has only been reproduced on the Demo system

1. Create a Custom Status like this (Is this correct?)
![Image](https://github.com/user-attachments/assets/44e56497-f152-4e1a-9fde-8497e4f33181)
2. Assign the Custom Status to a Stock Item for a part where there are a couple of Stock Items (I used the first part 1551ABK in the demo database)
3. Show a list of stock items (all or the stock for the 1551ABK part
4. Set a Status filter, the Custom State can be selected there
5. The list of Stock Items is blank
6. If th filter instead is set to "OK" (the base Status that the Custom Status is assiciated to), then Stock items with the OK status is visible as well as the items with the Custom Status

So it seems that the list is filterd based on the "Base Status" rather then the Custom Status.

### Expected behaviour

Custom Status should be used as filter

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [x] Other - added info in Steps to Reproduce

### Version Information

InvenTree-Version: 0.17.0 dev
Django Version: 4.2.16
Commit Hash: 7a3ceb9
Commit Date: 2024-11-30
Commit Branch: null
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-100-generic-x86_64-with
Installer: DOC
nullActive plugins: false

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by gunstr** [comment]
@matmair how do you mean I should do that? In the filter selection list I can only see "Status" and when I select that the "TestStatus" I created is in the list. So what am I doing wrong?

![Image](https://github.com/user-attachments/assets/fe57b9bd-03b6-4f3f-81b0-0efe788a935c)

**Comment by SchrodingersGat** [comment]
I would expect that the "custom stock status" values would appear here.

This will be rectified in https://github.com/inventree/InvenTree/pull/8438

**Comment by gunstr** [comment]
@SchrodingersGat Not sure I fully understand what you mean, but to further clarify what I see as the issue:

The starting point is a part with one of the stock item assigned with a "custom stock status", TestState in this case.

![Image](https://github.com/user-attachments/assets/f2104e9a-3d7d-4036-85e1-b70b48f1e75d)

The "custom stock status" TestState is populated and selectable in the Status filter value drop down as in the screenshot in my previous comment, so far as expected.

![Image](https://github.com/user-attachments/assets/879f0f35-8d34-41b2-9179-1d1f6620bfc4)

But with that filter applied the list of stock items is empty, I would expect the stock item with "TestState" status to be visible.

![Image](https://github.com/user-attachments/assets/1a4ef206-5e9d-49dd-924d-28d95df22370)

**Comment by SchrodingersGat** [comment]
@gunstr this has now been resolved in https://github.com/inventree/InvenTree/pull/8438 which will be in the next major release

**Comment by gunstr** [comment]
Thanks a lot @SchrodingersGat  I appreciate all your work and look forward to start to use the custom status featute after the next release.
