### ISSUE TITLE
Dev Container

### ISSUE THREAD

**Issue by ttftw** [inventree/InvenTree#8656]
### Deployment Method

- [ ] Installer
- [x] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

When I walk through the dev container process, postCreateCommand.sh fails trying to install files. The last line looks like the script is trying to run `invoke dev.frontend-install` but it doesn't think that function exists.

Also, when the dev container is installing, VS Code shows a notification saying "Could not find Biome in your dependencies. Either add the @biomejs/biome package to your dependencies, or download the Biome binary."

When the container starts, this is the output:

```
Running the postCreateCommand from devcontainer.json...

[15502 ms] Start: Run in container: /bin/sh -c .devcontainer/postCreateCommand.sh
Error: [Errno 1] Operation not permitted: '/home/inventree/dev/venv/bin/Activate.ps1'
.devcontainer/postCreateCommand.sh: line 8: /home/inventree/dev/venv/bin/activate: No such file or directory
Updating InvenTree installation...
Installing required python packages from '/home/inventree/src/backend/requirements.txt'
Requirement already satisfied: pip in /usr/lib/python3.11/site-packages (23.1.2)
Collecting pip
  Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 5.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3.11/site-packages (75.6.0)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/bin/pip'
Consider using the `--user` option or check the permissions.

ERROR: InvenTree command failed: 'pip3 install --no-cache-dir --disable-pip-version-check -U pip setuptools'
- Refer to the error messages in the log above for more information
```

Then continues and gets here:

```
Successfully built django-querycount django-slowtests
Installing collected packages: django-querycount, distlib, zipp, tomli, pyproject-hooks, pycparser, platformdirs, pip, nodeenv, isort, identify, filelock, django-test-migrations, django, coverage, cli
ck, charset-normalizer, cfgv, virtualenv, importlib-metadata, django-slowtests, django-admin-shell, cffi, build, pre-commit, pip-tools, cryptography, pdfminer-six
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/querycount'
Consider using the `--user` option or check the permissions.

ERROR: InvenTree command failed: 'pip3 install -U --require-hashes -r src/backend/requirements-dev.txt'
- Refer to the error messages in the log above for more information
No idea what 'dev.frontend-install' is!
```

### Steps to Reproduce

I'm following the steps in the `docs/docs/develop/devcontainer.md` guide. Step 4 is where the errors happen. When I open a terminal, it does activate the virtual environment, but I am not able to run the server. I get a `ModuleNotFoundError: No module named 'django'`

1. Clone the repository (If you want to submit changes fork it and use the url to your fork in the next step)
   ```bash
   git clone https://github.com/inventree/InvenTree.git
   ```
2. Open vscode, navigate to the extensions sidebar and search for `ms-vscode-remote.remote-containers`. Click on install.
3. Open the cloned folder from above by clicking on `file > open folder`
4. vscode should now ask you if you'd like to reopen this folder in a devcontainer. Click `Reopen in Container`. If it does not ask you, open the command palette (<kbd>CTRL/CMD</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) and search for `Reopen in Container`. This can take a few minutes until the image is downloaded, build and setup with all dependencies.

### Relevant log output

```bash

```

**Comment by SchrodingersGat** [comment]
```
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/bin/pip'
```

This error is the cause of your problems. There is a permission error for your devcontainer. Maybe @wolflu05 has some pointers here, but otherwise a good start would be googling permission issues for vscode

**Comment by ttftw** [comment]
@SchrodingersGat This message is coming from inside the container (I'm assuming, since I'm on a Windows PC and don't have /usr/bin). InvenTree configures the dev container and I'm trying to use it as-configured. When I Google the issue, there are solutions that come up (which includes doing what the error suggests, running with --user option), but I would assume the dev container would without me needing to make modifications to the process. I don't see anything that comes up specific about vs code dev containers with this issue.


I'm more concerned with how the script starts with an immediate error:

```
[15502 ms] Start: Run in container: /bin/sh -c .devcontainer/postCreateCommand.sh
Error: [Errno 1] Operation not permitted: '/home/inventree/dev/venv/bin/Activate.ps1'
.devcontainer/postCreateCommand.sh: line 8: /home/inventree/dev/venv/bin/activate: No such file or directory
```

I don't know why it's trying to do anything with a ps1 file since the container is Linux and I'm not sure why there is this error on line 8:
`.devcontainer/postCreateCommand.sh: line 8: /home/inventree/dev/venv/bin/activate: No such file or directory`. This happens before any of these other errors and might be the source of the other problems.

**Comment by wolflu05** [comment]
> Maybe @wolflu05 has some pointers here, but otherwise a good start would be googling permission issues for vscode

Sorry, I never had this error and no idea why it's happening. And unfortunately I'm not using the dev container anymore since a year or so.

> No idea what 'dev.frontend-install' is!

@SchrodingersGat  This might be related due to the grouping of tasks and then I think we ungrouped the frontend-install or moved it into another group but forgot to change the devconainer script?
