### ISSUE TITLE
'No module named django' when inventree is installed with the installer

### ISSUE THREAD

**Issue by wkigenyi** [inventree/InvenTree#8665]
### Deployment Method

- [x] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I run the installer `wget -qO- https://dl.packager.io/srv/inventree/InvenTree/key | sudo apt-key add -` and it run successfully but when I run the command inventree run invoke version I get the error 'MethodNotFoundError: No module named django'. Is there a step I missed ?

### Steps to Reproduce

1. On a Ubuntu 20.04 machine run wget -qO- https://dl.packager.io/srv/inventree/InvenTree/key | sudo apt-key add -
2. Run the command inventree run invoke version
3. The command fails 
4. Read through the generated message

### Relevant log output

```bash
Traceback (most recent call last):
  File "/opt/inventree/env/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/opt/inventree/env/lib/python3.9/site-packages/invoke/program.py", line 398, in run
    self.execute()
  File "/opt/inventree/env/lib/python3.9/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/opt/inventree/env/lib/python3.9/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)
  File "/opt/inventree/env/lib/python3.9/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
  File "/opt/inventree/tasks.py", line 1090, in version
    import src.backend.InvenTree.InvenTree.version as InvenTreeVersion
  File "/opt/inventree/src/backend/InvenTree/InvenTree/version.py", line 15, in <module>
    import django
ModuleNotFoundError: No module named 'django'
```

**Comment by matmair** [comment]
@wkigenyi if that is all commands you have run you are missing a few. You will need at least the following:

```bash
wget -qO- https://dl.packager.io/srv/inventree/InvenTree/key | sudo apt-key add -
sudo wget -O /etc/apt/sources.list.d/inventree.list \
  https://dl.packager.io/srv/inventree/InvenTree/stable/installer/ubuntu/20.04.repo
sudo apt-get update
sudo apt-get install inventree
```

Where did you get those steps? Do we have old docs somewhere?

**Comment by wkigenyi** [comment]
@matmair thanks for the response. I was following this:
https://docs.inventree.org/en/stable/start/installer/#installer
Surely I missed the other steps. I assumed additional steps that you have mentioned here are only necessary if you are not using the installer. I will remember to do that correctly next time.
Do you think it is a good idea to show these steps under a title **"Additional steps"**?

**Comment by matmair** [comment]
The first line you used is not for the installer.

The installer needs this one step: https://docs.inventree.org/en/stable/start/installer/#quick-script

The manual steps are all listed here: https://docs.inventree.org/en/stable/start/installer/#manual-install

**Comment by wkigenyi** [comment]
Thanks @matmair

**Comment by SchrodingersGat** [comment]
@wkigenyi did you end up getting it working then?

**Comment by wkigenyi** [comment]
I used the Digital Ocean deployment link and it worked. Thanks.
