### ISSUE TITLE
Make Update FAILed

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#869]
I am guessing I need to pip some things but I thought you should know so you can add it to dependencies.
```
cd InvenTree && python3 manage.py makemigrations
InvenTree running in DEBUG mode
MEDIA_ROOT: /root/InvenTree/inventree_media
STATIC_ROOT: /root/InvenTree/inventree_static
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': Shared object "libcairo.so" not found, required by "python3"
cannot load library 'libcairo.2.dylib': Shared object "libcairo.2.dylib" not found, required by "python3"
cannot load library 'libcairo-2.dll': Shared object "libcairo-2.dll" not found, required by "python3"
You may require some further system packages to be installed.
*** Error code 1

Stop.
```

**Comment by SchrodingersGat** [comment]
There are some new system-level requirements - make sure they are all installed before running `make update`

https://inventree.github.io/docs/start/install#requirements

**Comment by a7hybnj2** [comment]
Wow! Thanks for the fast reply. I will try to figure out how to install those on my bsd server that I rarely use. I think I can portsnap them.

Looks like you have been making TONS of updates I don't think I will even recognize it when I finally update. I hope I can figure out how to make use of all the new features.

**Comment by a7hybnj2** [comment]
@SchrodingersGat Will I need to do anything special since I am updating vs installing? Or just get those packages installed and 'make update' like normal?

**Comment by SchrodingersGat** [comment]
Once you install those system packages, you should just be able to run `make update` and everything should work. LMK how you go :)

**Comment by a7hybnj2** [comment]
sheesh, that was fun. I am on a freeBSD system which I am not super familiar with. I just built cairo and pango from source which took seemingly forever. But, everything appears to be working now.

Thanks!
