### ISSUE TITLE
[PUI] Image upload fails/succeeds silently.

### ISSUE THREAD

**Issue by sur5r** [inventree/InvenTree#8691]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

When uploading an image for a part as AVIF, the preview renders sucessfully. Pressing submit, however, does nothing visible.
In the backgrund, a JSON error is returned:

```json
{"image":["Upload a valid image. The file you uploaded was either not an image or a corrupted image."]}
```

Selecting a PNG instead works silently, but the overlay stays open. No user feedback as well.

### Steps to Reproduce

1. Go to a place where you can upload an image, e.g. a part
2. Select an image from disk
3. Click Submit
4. Nothing happens

### Expected behaviour

On successful image upload, the overlay should close and the part page should show the new image without refresh
On failed upload, an error message should be shown.

### Deployment Method

- [ ] Docker
- [ ] Package
- [x] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

InvenTree-Version: 0.18.0 dev
Django Version: 4.2.17
Commit Hash: ff69cf6
Commit Date: 2024-12-17
Commit Branch: master
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-6.1.0-13-cloud-amd64-x86_64-with-glibc2.36
Installer: GIT
nullActive plugins: [{"name":"InvenTreeBarcode","slug":"inventreebarcode","version":"2.1.0"},{"name":"InvenTreeCoreNotificationsPlugin","slug":"inventreecorenotificationsplugin","version":"1.0.0"},{"name":"InvenTreeCurrencyExchange","slug":"inventreecurrencyexchange","version":"1.0.0"},{"name":"InvenTreeLabel","slug":"inventreelabel","version":"1.1.0"},{"name":"InvenTreeLabelMachine","slug":"inventreelabelmachine","version":"1.0.0"},{"name":"InvenTreeLabelSheet","slug":"inventreelabelsheet","version":"1.0.0"},{"name":"DigiKeyPlugin","slug":"digikeyplugin","version":"1.0.0"},{"name":"LCSCPlugin","slug":"lcscplugin","version":"1.0.0"},{"name":"MouserPlugin","slug":"mouserplugin","version":"1.0.0"},{"name":"TMEPlugin","slug":"tmeplugin","version":"1.0.0"},{"name":"Brother Labels","slug":"brother","version":"1.0.0"}]

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by SchrodingersGat** [comment]
@sur5r thanks for reporting - fix incoming in https://github.com/inventree/InvenTree/pull/8700
