### ISSUE TITLE
[PUI] Editing a purchase order line item breaks table entry

### ISSUE THREAD

**Issue by sur5r** [inventree/InvenTree#8693]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

When editing the line reference of a purchase order item, some columns are empty. A manual refresh is required.

For the screenshot below, I changed the line reference from 003 to 099.

![Image](https://github.com/user-attachments/assets/f7699dfc-f206-4936-93ef-d5e1ece3c2b9)

After refreshing the table, contents is correct:

![Image](https://github.com/user-attachments/assets/89deedb3-c0f7-4059-a427-350c7fcad474)

### Steps to Reproduce

1. Go to a purchase order
2. Change line item reference of an item
3. Observe the table content to be incomplete

### Expected behaviour

Table is updated/refreshed correctly.

### Deployment Method

- [ ] Docker
- [ ] Package
- [x] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

InvenTree-Version: 0.18.0 dev
Django Version: 4.2.17
Commit Hash: ff69cf6
Commit Date: 2024-12-17
Commit Branch: master
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-6.1.0-13-cloud-amd64-x86_64-with-glibc2.36
Installer: GIT
nullActive plugins: [{"name":"InvenTreeBarcode","slug":"inventreebarcode","version":"2.1.0"},{"name":"InvenTreeCoreNotificationsPlugin","slug":"inventreecorenotificationsplugin","version":"1.0.0"},{"name":"InvenTreeCurrencyExchange","slug":"inventreecurrencyexchange","version":"1.0.0"},{"name":"InvenTreeLabel","slug":"inventreelabel","version":"1.1.0"},{"name":"InvenTreeLabelMachine","slug":"inventreelabelmachine","version":"1.0.0"},{"name":"InvenTreeLabelSheet","slug":"inventreelabelsheet","version":"1.0.0"},{"name":"DigiKeyPlugin","slug":"digikeyplugin","version":"1.0.0"},{"name":"LCSCPlugin","slug":"lcscplugin","version":"1.0.0"},{"name":"MouserPlugin","slug":"mouserplugin","version":"1.0.0"},{"name":"TMEPlugin","slug":"tmeplugin","version":"1.0.0"},{"name":"Brother Labels","slug":"brother","version":"1.0.0"}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by SchrodingersGat** [comment]
@sur5r thanks for reporting this - fix incoming in https://github.com/inventree/InvenTree/pull/8698
