### ISSUE TITLE
Barcode Scan Page error (in Firefox 133.0.3)

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#8703]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

With the current version 0.18.0-dev I get a rendering error when opening the barcode scanning page in Firefox 133.0.3 ("https://<INVENTREE-URL>/platform/scan") after selecting a webcam - not sure what to make of those console tracebacks right now or where to dig deeper here, but happy to debug this further...
Using the webcam for Google Meet and such does work in Firefox - so I assume it is not a general issue with webcam use in my browser - also in Chromium the scanning works just fine with InvenTree

![Image](https://github.com/user-attachments/assets/1037f796-f77c-498e-92a6-b958eceb774c)

### Steps to Reproduce

1. open <INVENTREE-URL>/platform/scan
2. select one of the webcam options in the drop down (i have two on my machine)
3. error is shown

### Expected behaviour

rendering the webcam view correctly

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

InvenTree-Version: 0.18.0 dev
Django Version: 4.2.17
Commit Hash: 4569fd2
Commit Date: 2024-12-18
Commit Branch: null
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-rpi7-rpi-v8-aarch64-with
Installer: DOC
nullActive plugins: [{"name":"InvenTreeBarcode","slug":"inventreebarcode","version":"2.1.0"},{"name":"InvenTreeCoreNotificationsPlugin","slug":"inventreecorenotificationsplugin","version":"1.0.0"},{"name":"InvenTreeCurrencyExchange","slug":"inventreecurrencyexchange","version":"1.0.0"},{"name":"InvenTreeLabel","slug":"inventreelabel","version":"1.1.0"},{"name":"InvenTreeLabelMachine","slug":"inventreelabelmachine","version":"1.0.0"},{"name":"InvenTreeLabelSheet","slug":"inventreelabelsheet","version":"1.0.0"},{"name":"DigiKeyPlugin","slug":"digikeyplugin","version":"1.0.0"},{"name":"LCSCPlugin","slug":"lcscplugin","version":"1.0.0"},{"name":"MouserPlugin","slug":"mouserplugin","version":"1.0.0"},{"name":"TMEPlugin","slug":"tmeplugin","version":"1.0.0"},{"name":"IPNAutoGenerator","slug":"ipnautogenerator","version":null},{"name":"OrderNotesTemplates","slug":"ordernotestemplates","version":null},{"name":"Brother Labels","slug":"brother","version":"1.0.0"}]

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Error: [@mantine/core] Duplicate options are not supported. Option with value "53onDl+GhFMrnGfsqvd+OzFV1s9oosASHSPnjUDbguo=" was provided more than once
    g3 https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:127
    BA https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:127
    s0 https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:60
    uh https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    hx https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    dx https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    WI https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    hu https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    Sh https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    lx https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    k https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:47
    z https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:47
    EventHandlerNonNull* https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:47
    <anonymous> https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:47
[vendor-BWg2Hufi.js:127:574](https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js)
Uncaught Error: [@mantine/core] Duplicate options are not supported. Option with value "53onDl+GhFMrnGfsqvd+OzFV1s9oosASHSPnjUDbguo=" was provided more than once
    g3 https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:127
    BA https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:127
    s0 https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:60
    uh https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    hx https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    dx https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    WI https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    hu https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    Sh https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    lx https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:62
    k https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:47
    z https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:47
    EventHandlerNonNull* https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:47
    <anonymous> https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js:47
[vendor-BWg2Hufi.js:127:140012](https://inventree<URL_REMOVED>/static/web/assets/vendor-BWg2Hufi.js)

```

**Comment by matmair** [comment]
@simonkuehling this was fixed recently; please feedback if #8732 did not adress your concerns
