### ISSUE TITLE
Link to 'Add Supplier' overlay from 'Add Supplier Part' overlay

### ISSUE THREAD

**Issue by rco3** [inventree/InvenTree#872]
In the process of adding an existing inventory into Inventree, I am often finding that not only do I not yet have this part in my database but I don't have the Manufacturer either.  I then have to stop the 'Create New Supplier Part' process, add that Manufacturer, and then restart the 'Create New Supplier Part' process.  I can, of course, go back and add it later... but that's a convoluted workflow. 

Priority: low.  If there is an easy way to link to the "Create new Supplier" dialog from the 'Create New Supplier Part' dialog, that would allow the user to add a new Manufacturer in time to include it with the new Supplier Part. Also supports interactive consumption of DataMatrix fields #865

...unless there's a way already there and I just don't see it?

**Comment by SchrodingersGat** [comment]
Can you show me a screenshot of which dialog you are talking about here?

**Comment by rco3** [comment]
Apologies.  

Start from New Stock Item button on Stock page. Overlay popover entitled "Create new Stock Item" appears.  Second pulldown is Supplier Part; there is a button above and to the right for "New Supplier Part".  Click this button, and another popover sits above the first one; it is entitled "Create new Supplier Part".  In order to successfully create this New Supplier Part, a Supplier is required.  However, there is NOT a button for "New Supplier" to bring up a Create New Supplier dialog / popover.  To add that new supplier, it is necessary to cancel all the way out of this New Stock Item process, add the supplier, and then start the New Stock Item process all over.

![AddNewSupplierScreenShot](https://user-images.githubusercontent.com/63524655/85329574-c6b8fa80-b4a0-11ea-89e3-5041297d3795.jpg)

**Comment by SchrodingersGat** [comment]
Ah, gotcha. Currently the secondary dialogs cannot have sub-dialogs attached. It's a two-level limit. There's an outstanding issue to add tertiary dialogs but that will take some effort. Sorry, this one won't be available yet.

**Comment by rco3** [comment]
Understood.  Makes sense. Thanks for looking at it.
