### ISSUE TITLE
Can't get SSL working

### ISSUE THREAD

**Issue by chadleylyell** [inventree/InvenTree#8733]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [x] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

For the love of all, can someone PLEASE tell me where the correct html files are so I can point the Nginx configuration file to the web server. Right now it's pointed to: "/var/www/html" which only has the default new install Ngnix webpage. I have tried searching for "index.html" only to find these and changing the config file to some of these just give me a empty page. *In log output*

### Steps to Reproduce

.

### Relevant log output

```bash
root@inventree:/# find index.html
find: ‘index.html’: No such file or directory
root@inventree:/# sudo find / -name "*index.html*"
/home/inventree/.cache/uv/archive-v0/d_AvkVUgqt7Le26g7m8wT/setuptools/tests/indexes/test_links_priority/simple/foobar/index.html
/home/inventree/.cache/uv/archive-v0/iBI6yU-o6OxiOOSbp1GE5/rest_framework/templates/rest_framework/docs/index.html
/home/inventree/.cache/uv/archive-v0/IYw57ureZIOaZpWqFhDhS/allauth/templates/mfa/recovery_codes/index.html
/home/inventree/.cache/uv/archive-v0/IYw57ureZIOaZpWqFhDhS/allauth/templates/mfa/index.html
/home/inventree/.cache/uv/archive-v0/HfZ0FZCUU57xA3TZsziGU/django/contrib/admindocs/templates/admin_doc/view_index.html
/home/inventree/.cache/uv/archive-v0/HfZ0FZCUU57xA3TZsziGU/django/contrib/admindocs/templates/admin_doc/model_index.html
/home/inventree/.cache/uv/archive-v0/HfZ0FZCUU57xA3TZsziGU/django/contrib/admindocs/templates/admin_doc/template_tag_index.html
/home/inventree/.cache/uv/archive-v0/HfZ0FZCUU57xA3TZsziGU/django/contrib/admindocs/templates/admin_doc/index.html
/home/inventree/.cache/uv/archive-v0/HfZ0FZCUU57xA3TZsziGU/django/contrib/admindocs/templates/admin_doc/template_filter_index.html
/home/inventree/.cache/uv/archive-v0/HfZ0FZCUU57xA3TZsziGU/django/contrib/admin/templates/admin/app_index.html
/home/inventree/.cache/uv/archive-v0/HfZ0FZCUU57xA3TZsziGU/django/contrib/admin/templates/admin/index.html
/home/inventree/.cache/uv/archive-v0/gn_I26if5_MGeGXjWH7vK/setuptools/tests/indexes/test_links_priority/simple/foobar/index.html
/home/inventree/.cache/uv/sdists-v6/pypi/django-allauth/0.63.3/xL_DF9jIKFz8EHaZuFbWz/src/build/lib/allauth/templates/mfa/recovery_codes/index.html
/home/inventree/.cache/uv/sdists-v6/pypi/django-allauth/0.63.3/xL_DF9jIKFz8EHaZuFbWz/src/build/lib/allauth/templates/mfa/index.html
/home/inventree/.cache/uv/sdists-v6/pypi/django-allauth/0.63.3/xL_DF9jIKFz8EHaZuFbWz/src/allauth/templates/mfa/recovery_codes/index.html
/home/inventree/.cache/uv/sdists-v6/pypi/django-allauth/0.63.3/xL_DF9jIKFz8EHaZuFbWz/src/allauth/templates/mfa/index.html
/home/inventree/.cache/uv/sdists-v6/pypi/dj-rest-auth/6.0.0/s1L3gfi0mqGXnQxiMFfjy/src/demo/react-spa/public/index.html
/opt/inventree/src/backend/InvenTree/build/templates/build/index.html
/opt/inventree/src/backend/InvenTree/templates/InvenTree/index.html
/opt/inventree/src/backend/InvenTree/InvenTree/static/treegrid/index.html
/opt/inventree/src/backend/InvenTree/InvenTree/static/script/jquery-ui/index.html
/opt/inventree/src/backend/InvenTree/company/templates/company/index.html
/opt/inventree/src/backend/InvenTree/web/templates/web/index.html
/opt/inventree/src/backend/InvenTree/web/static/web/index.html
/opt/inventree/src/frontend/index.html
/opt/inventree/data/static/treegrid/index.html
/opt/inventree/data/static/script/jquery-ui/index.html
/opt/inventree/data/static/web/index.html
/opt/inventree/env/lib/python3.9/site-packages/django/contrib/admindocs/templates/admin_doc/view_index.html
/opt/inventree/env/lib/python3.9/site-packages/django/contrib/admindocs/templates/admin_doc/model_index.html
/opt/inventree/env/lib/python3.9/site-packages/django/contrib/admindocs/templates/admin_doc/template_tag_index.html
/opt/inventree/env/lib/python3.9/site-packages/django/contrib/admindocs/templates/admin_doc/index.html
/opt/inventree/env/lib/python3.9/site-packages/django/contrib/admindocs/templates/admin_doc/template_filter_index.html
/opt/inventree/env/lib/python3.9/site-packages/django/contrib/admin/templates/admin/app_index.html
/opt/inventree/env/lib/python3.9/site-packages/django/contrib/admin/templates/admin/index.html
/opt/inventree/env/lib/python3.9/site-packages/allauth/templates/mfa/recovery_codes/index.html
/opt/inventree/env/lib/python3.9/site-packages/allauth/templates/mfa/index.html
/opt/inventree/env/lib/python3.9/site-packages/setuptools/tests/indexes/test_links_priority/simple/foobar/index.html
/opt/inventree/env/lib/python3.9/site-packages/rest_framework/templates/rest_framework/docs/index.html
/usr/lib/python3/dist-packages/twisted/python/_pydoctortemplates/index.html
/usr/share/doc/libexpat1-dev/expat.html/index.html
/usr/share/doc/shared-mime-info/shared-mime-info-spec.html/index.html
/usr/share/doc/info/html/index.html
/usr/share/doc/gdisk/index.html
/usr/share/doc/adduser/examples/adduser.local.conf.examples/skel.other/index.html
/usr/share/doc/python3/python-policy.html/index.html
/usr/share/nginx/html/index.html
```

**Comment by chadleylyell** [comment]
Here is the contents of my config file with some redacted info:
'/etc/nginx/sites-available/[REDACTED].me'

`
##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
    listen 80;
    listen [::]:80;

    server_name [REDACTED].me www.[REDACTED].me;

    # Redirect HTTP to HTTPS
    return 301 https://$host$request_uri;

}

server {
    # SSL configuration
    listen 443 ssl;
    listen [::]:443 ssl;

    # Path to SSL certificate and private key
    ssl_certificate /etc/letsencrypt/live/[REDACTED].me/fullchain.pem;   
    ssl_certificate_key /etc/letsencrypt/live/[REDACTED].me/privkey.pem;

    root /opt/inventree/src/frontend/;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name [REDACTED] www.[REDACTED].me;

    location / {
        try_files $uri $uri/ =404;
    }
}  
`

**Comment by chadleylyell** [comment]
I am sick of wasting my time on this. I created a new droplet and I'll restart my 8+ hours of adding my parts into the system. I believe that someone needs to created a guide on how to implement ssl using letsencrypt since the "automatic" part of it doesn't work. :)

`Finally, it provides a [Let's Encrypt](https://letsencrypt.org/) endpoint for automatic SSL certificate generation and renewal.`
https://docs.inventree.org/en/latest/start/processes/#proxy-server

**Comment by matmair** [comment]
Please fill out the `steps to reproduce` section if you want help, this is not reproducible.

**Comment by chadleylyell** [comment]
> Please fill out the `steps to reproduce` section if you want help, this is not reproducible.

I worked on this for so many hours last night that I couldn't even begin to tell you where I went wrong. Can you just please link me to something telling me how to use letsencrypt with the digital ocean image to link it with my domain?

**Comment by chadleylyell** [comment]
Also, since the "Site URL is locked by configuration" I ran this command `sudo inventree config:set INVENTREE_SITE_URL=https://[REDACTED].me` on the new server that I generated and https still doesn't work, even though the docs say that "The [Caddy](https://docs.inventree.org/en/latest/start/docker/#ssl-certificates) container will automatically generate SSL certificates for your domain."

**Comment by matmair** [comment]
The docs you are referring to are for official inventree install methods. As noted on the website the digital ocean image is by the community - it does not follow the official docs.

The image uses nginx, not caddy, and has no automatic SSL support.

**Comment by SchrodingersGat** [comment]
@chadleylyell if you want to follow the official docker setup guide, with Caddy / SSL support, then this blog post might be a good starting point.

https://inventree.org/blog/2024/03/13/docker

Please note that system administration of a public facing web server is *complex* and not within the scope of the InvenTree software. We cannot, and will not, be able to provide comprehensive documentation or support for this, beyond how to get an InvenTree server up and running.

**Comment by chadleylyell** [comment]
@SchrodingersGat Honestly at this point, I don't really care for SSL anymore as this is literally just hosting stuff for my electrical engineering part stock.
