### ISSUE TITLE
Not able to see the login page after running the command docker compose up -d successfully

### ISSUE THREAD

**Issue by nitume00** [inventree/InvenTree#8736]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [x] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

<img width="377" alt="Image" src="https://github.com/user-attachments/assets/e0286fa3-5816-4528-8167-58431974b0b6" />
<img width="684" alt="Image" src="https://github.com/user-attachments/assets/4c0eb259-180c-4a33-a5f7-bd434f1409a7" />

### Steps to Reproduce

just follow the docker installation instructions.

### Relevant log output

```bash

```

**Comment by nitume00** [comment]
# Site URL - update this to match your host
INVENTREE_SITE_URL="http://inventree.localhost"

COMPOSE_PROJECT_NAME=inventree

**Comment by SchrodingersGat** [comment]
@nitume00 this is because you have an nginx service capturing all traffic to "localhost". The InvenTree docker setup uses Caddy as the proxy server, not nginx.

You should halt the nginx process running on your machine, and then the InvenTree server should be visible.

**Comment by nitume00** [comment]
@SchrodingersGat  is Caddy  is the only option as proxy server or we can go with nginx also

**Comment by SchrodingersGat** [comment]
@nitume00 you can change to nginx if you want - however our documentation and setup guides are based around Caddy.

Have a look in the `docker-compose.yml` file - you can see that there is a placeholder for a nginx proxy. You will need you substitute our [example nginx configuration file](https://github.com/inventree/InvenTree/blob/master/contrib/container/nginx.conf) too.

Please note though: If you are seeing a nginx page, that is *not* being served by our docker container. That is running somewhere else on your machine

**Comment by SchrodingersGat** [comment]
@nitume00 I'm going to close this out, the issue here lies with your local machine having a separate nginx service running.
