### ISSUE TITLE
Zebra label printer does not work

### ISSUE THREAD

**Issue by Philipboy881** [inventree/InvenTree#8740]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

I upgraded from inventree version v16.1 to v17.0
On 16.1 everything worked fine.
On 17.0 the printer does not work annymore

### Steps to Reproduce

Print an label on anny item and it does not give a label at the printer
But the printer will show it has an output job and finishes it, but no label wil come out.

### Expected behaviour

Print a label

### Deployment Method

- [ ] Docker
- [ ] Package
- [x] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.17.0
Django Version: 4.2.17

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-204-generic-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'Zebra', 'slug': 'zebra', 'version': '0.7.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by SchrodingersGat** [comment]
@SergeoLacruz maintains the [zebra printer plugin](https://github.com/SergeoLacruz/inventree-zebra-plugin)

**Comment by SergeoLacruz** [comment]
Any message from the printer driver in the logs? 
Network or USB printer?
Please check the printer settings. Perhaps something got lost during the update.

**Comment by Philipboy881** [comment]
These are the settings between different versions (v16.1 and 17.0).

And I die not get Anny error. Or is there a place where I can check for error log's?
At least the admin page / error does not give anything.

But do I need to post this issue at the zebra label printer plugin in github?

![Screenshot_2024-12-23-23-33-56-09_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/b0947a9c-cb3d-46b5-bc63-2754ba4aefdf)

![Screenshot_2024-12-23-23-39-23-61_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/1fe78061-22cf-4466-9386-c92ee240c02b)

**Comment by SergeoLacruz** [comment]
If there are errors, they should be visible in the InvenTree log. 
I think you do not use a ZPL template because this is new to 0.7.0.
The settings seem to be OK. You use a network printer. In our setup the printer sometimes looses the connection, for whatever reason, and needs to be reset by switching off for a few seconds. Can you reach the printers WEB UI? 
If the printer is online and still does not print have a look here:
https://github.com/SergeoLacruz/inventree-zebra-plugin/blob/dd8bfaa23c7b9d3cdb1718436af05d261517e024/inventree_zebra/zebra_plugin.py#L150C7-L153C27
Uncomment these lines and have a look at the file that is sent out to the printer.

**Comment by Philipboy881** [comment]
These are the settings between different versions (v16.1 and 17.0).

And I die not get Anny error. Or is there a place where I can check for error log's?
At least the admin page / error does not give anything.

But do I need to post this issue at the zebra label printer plugin in github?

![Screenshot_2024-12-23-23-33-56-09_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/b0947a9c-cb3d-46b5-bc63-2754ba4aefdf)

![Screenshot_2024-12-23-23-39-23-61_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/1fe78061-22cf-4466-9386-c92ee240c02b)

    
I did not use zpl commands.

I did use this:
`{% extends "label/label_base.html" %}

{% load l10n i18n barcode %}

{% block style %}

@page {
    size: 70mm 32mm; /* Dit definieert de grootte van de pagina */
    margin: 0mm; /* Standaard marge rondom de pagina */
}

.label-container {
    display: block;
    width: 100%;
    height: 100%;
    padding: 2mm;
    box-sizing: border-box;
    overflow: hidden; /* Zorg ervoor dat inhoud niet buiten de container valt */
}

.header {
    width: calc(100% - 4mm);
    height: 3mm;
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 10pt;
    font-weight: bold;
    box-sizing: border-box;
	padding-bottom: 5mm;
    line-height: 3mm;
}

.content {
    display: flex;
    flex-direction: row;
    height: 32mm; /* Verminderd om overloop aan de onderkant te voorkomen */
    width: 100%;
	overflow: hidden;
}

.left-column, .right-column {
    display: flex;
	border-top: 1px solid black;
    align-items: flex-start; /* Verplaatst de QR-code omhoog */
    padding: 0;
    box-sizing: border-box;
	height:22mm;
}

.left-column {  
    width: 30%;
	justify-content: center;
    border-right: 1px solid black;
    padding-right: 2mm; /* Voegt wat ruimte toe aan de rechterkant van de linker kolom */
}

.right-column {
    width: 70%;
    display: block; 
    justify-content: left; /* Zorgt ervoor dat de inhoud bovenaan begint */
    padding-top: 1mm;
    padding-left: 1mm;
    box-sizing: border-box; /* Houdt rekening met padding in de totale breedte */
}

.qr {
    height: 20mm;
    width: 20mm;
    object-fit: contain; /* Zorg ervoor dat de afbeelding correct wordt geschaald */
    position: relative; /* Nodig voor z-index */
    z-index: 10; /* Zorg ervoor dat de QR-code boven andere elementen ligt */
	display: block;
	box-sizing: border-box;
	margin-top: 1mm;
}

.path {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 6pt;
    text-align: left;
	white-space: normal;
    width: 100%;
    overflow-wrap: break-word;
    line-height: 1.2;
    overflow: hidden;
}

.bold-label {
    font-weight: bold;
}


{% endblock style %}

{% block content %}

<div class="label-container">
    
    <div class="header">
        {% if part.name %}
		{{ part.name }}
		{% endif %}
    </div>

    <div class="content">
        
		<div class="left-column">
			<img class='qr' alt="{% trans 'QR Code' %}" src='{% qrcode qr_data %}'>
        </div>
		
		<div class="right-column">
            
			<div class="path">
				{% if part.IPN %}
				<span class="bold-label">IPN: </span> {{ part.IPN }}
				{% endif %}
            </div>
			
			{% if part.default_supplier %}
			<div class="path">
				<span class="bold-label">SKU: </span> {{ part.default_supplier.supplier.name }} | {{ part.default_supplier.SKU }}
            </div>
			
			<div class="path">
				<span class="bold-label">MPN: </span> {{ part.default_supplier.manufacturer_string }}
            </div>
			{% endif %}
		
			<div class="path">
				{% if part.description %}
				<span class="bold-label">Omschrijving: </span> {{ part.description }}
				{% endif %}
            </div>
        
		</div>
    </div>

</div>

{% endblock content %}
`

I did make an new label template with the following example from the zebra label GitHub:
`
{% autoescape off %} ^FT30,25^A0N,18,22^FDIPN^FS ^FT150,30^FB100,1,,C,,^A0N,24,32^FDACME^FS ^FT320,25^A0N,18,22^FD{{ item.pk }}^FS ^FT100,70^FB200,2,,C,,^A0N,18,22^FD{{ part.name }}^FS ^FT100,100^FB200,1,,C,,^A0N,18,22^FD{{ part.manufacturer_parts.first.manufacturer.name }}^FS ^FT30,150^FB340,1,,C,,^A0N,30,40^FD{{ part.IPN }}^FS ^FT20,210^FB360,3,,L,,^A0N,18,22^FD{{ part.description }}^FS ^FT15,110^BQ,2,3^FDQA,{{ part.IPN }}^FS ^FT310,130^BQ,2,3^FDQA,{{ qr_data }}^FS {% endautoescape %}
`

But still no label from the printer
I use a gk420t printer with the labels being 70*32
I did not have connection problems with the printer, I can connect to the homepage and I can ping the device from the server. Also it adds an item to the job log.

Is it possible there is an item I forgot to enable to print zpl commands directly ?

Many Thanks for the fast response

**Comment by Philipboy881** [comment]
I have taken the printer to the location where the Inventree is hosted and put it on the same network. Changed the ip of the device in the printer settings and I was trying to print. It did print a label with the correct information.

I put it back on the original location changed the ip address back to the adress it now has on the location and now it does not print anything anymore.

The server can ping the device. The device is in an other part of the country and connected via VPN tunnel to the server.

But still strange because 16.1 Inventree did work and 17.0 not. Could there be an limitation in communication between networks ?

**Comment by SergeoLacruz** [comment]
I meanwhile copied your html template into my setup and it works OK. There is no problem with your labels. 
I do not think that InvenTree 17 is the problem. The code that controls the printer is in the printer driver:

https://github.com/SergeoLacruz/inventree-zebra-plugin/blob/dd8bfaa23c7b9d3cdb1718436af05d261517e024/inventree_zebra/zebra_plugin.py#L164C1-L174C92

There was no change here for a long time. It can be you are running a different python version and the behavior of the socket
library has changed. Or the VPN now blocks certain traffic.

**Comment by SergeoLacruz** [comment]
Discussion will be continued here:
https://github.com/SergeoLacruz/inventree-zebra-plugin/issues/9

**Comment by SchrodingersGat** [comment]
Thanks @SergeoLacruz

**Comment by SergeoLacruz** [comment]
Just to inform. This was a socket timeout error because of ZPL file size and slow connection.
