### ISSUE TITLE
Sales order doesnt capture *Parts

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#876]
![image](https://user-images.githubusercontent.com/31635566/85393284-69cb4c00-b555-11ea-8427-655a080eb203.png)
![image](https://user-images.githubusercontent.com/31635566/85393352-836c9380-b555-11ea-9d77-3323c0287d74.png)
Hello I couldnt add new item to sales order *Part section doesnt catch parts which i created in case of purchasing. Would you please advice me if i do something wrong or is there any lacking code to catch parts in the *Part field.

**Comment by SchrodingersGat** [comment]
Hi @neco1982 - for parts to appear in the SalesOrder form, the parts must be marked as "Salable":

![image](https://user-images.githubusercontent.com/10080325/85943719-333a6a80-b975-11ea-8f7d-a2c879d82543.png)

- Parts which are marked as "Purchaseable" can be added to purchase orders
- Parts which are marked as "Salable" can be added to sales orders
