### ISSUE TITLE
can't set any password

### ISSUE THREAD

**Issue by ineselhajahmed11** [inventree/InvenTree#8760]
### Deployment Method

- [x] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

When I try to change the admin password via the interface, when I click on set password i get Not implemented
This feature is not yet implemented, is this a plugin error ?? what to do to fix this error <img width="955" alt="Image" src="https://github.com/user-attachments/assets/0f881cd7-f890-4966-afc5-fa2deeab095c" />

### Steps to Reproduce

navigate to user settings
click on set password

### Relevant log output

```bash
Not implemented
This feature is not yet implemented
```

**Comment by SchrodingersGat** [comment]
Setting user password via the new interface has not been implemented yet - that is a target for `1.0.0` release
