### ISSUE TITLE
configuration file misconfiguration for bare metal nginx setup

### ISSUE THREAD

**Issue by matmay** [inventree/InvenTree#8761]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [x] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Did a fresh bare metal installation using the installation script in a debian 11 lxc on proxmox and would always get logged out when refreshing, would not be able to download any media or display the pictures. Also old GUI would not work, login button was just dead.

citing from /etc/inventree/config.yaml
```
# Cookie settings (nominally the default settings should be fine)
#cookie:
#  secure: false
#  samesite: false
```

these three lines need to be commented out to fix this, as we are not using ssl.

took me a night to figure this out.

### Steps to Reproduce

in proxmox pve shell  create debian 11 lxc 
`bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/vm/debian-vm.sh)"`
in debian lxc
`wget -qO install.sh https://get.inventree.org && bash install.sh`

copy media and import database from old installation to have some media to download
`inventree run invoke import-records -c -f data.json`

### Relevant log output

```bash

```

**Comment by SchrodingersGat** [comment]
@matmay thanks for reporting this. I am trying to work out where the discrepancy is occurring. Can you please test what happens when you configure the settings like this:

```yaml
cookie:
    secure: true
    samesite: false
```
