### ISSUE TITLE
Mention need to copy media folder in documentation

### ISSUE THREAD

**Issue by matmay** [inventree/InvenTree#8764]
### Body of the issue

[https://docs.inventree.org/en/stable/start/migrate/](https://docs.inventree.org/en/stable/start/migrate/ ) should mention that the media folder has to be copied as well to the new system. I guess it should be done before importing the database and ownership has to be correct.

**Comment by SchrodingersGat** [comment]
@matmay good point. Do you want to submit a PR for this?
