### ISSUE TITLE
Starred parts disappear from part list

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#877]
I've noticed that when a part is "starred" (click on the "Star" icon), the part disappears from the part list (`Parts` tab).
The starred part only appears under "Starred Parts" on the Index page.

Is this the desired behavior? If it is, can an option be added to include "starred" parts in the part list?

Version info (on latest commit):
```
  | InvenTree Version | 0.1.1 pre
  | Django Version | 3.0.7
  | Commit Hash | 8ac23c08
  | Commit Date | 2020-06-22
  | InvenTree Documentation | https://inventree.github.io
  | View Code on GitHub | https://github.com/InvenTree/InvenTree/
  | Submit Bug Report | https://github.com/InvenTree/InvenTree/issues
```

**Comment by SchrodingersGat** [comment]
Twas a bug! Fixed :)
