### ISSUE TITLE
[CI] Automate database snapshots

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#8774]
Ref: https://github.com/inventree/InvenTree/pull/8773

The "database snapshot" idea has not recevied any attention in a while (and is now out of date).

The idea here is that we keep snapshots of a test database at various points in the project history, and then we ensure that we can always cleanly migrate from those snapshots to the "latest" version.

However these snapshots are made manually and I have not rememebered to do it for a while.

Ideally, we can automate this such that:

- The "latest" snapshot is updated whenever a schema change is made to the code
- A new "release" snapshot is automatically uploaded when we make a release

**Comment by matmair** [comment]
I'm not sure it makes sense to have too many of these snapshots, we already check the full run-through of migrations on every change. Having them manually created reduces the number naturally

**Comment by SchrodingersGat** [comment]
@matmair that's a reasonable point, maybe this is overkill anyway. Just a thought I had when I noticed it was out of date.

I'll leave this up as a thinking point for now,
