### ISSUE TITLE
FR: Add Link Barcode to stock locations

### ISSUE THREAD

**Issue by gab696** [inventree/InvenTree#8792]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Some buttons are missing from the new UI Platform

- QRcode relink for locations
- parts grid view
- locations tree view

### Steps to Reproduce

QR CODE relink :
1. Go to "Stock"
2. Go to "Stock Locations"
3. Open a location item
4. Click on "Barcode Actions" icon
5. Here only "View Barcode" - "Scan in stock items" - Scan in containers" is available.
6. On the old UI "Link Barcode" is available

TREE VIEW and GRID VIEW buttons are also missing from the new UI

### Expected behaviour

Theses buttons are available on the old UI and very usefull.

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

InvenTree Version | 0.17.1

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

### Relevant log output

```shell

```

**Comment by matmair** [comment]
Hi there @gab696 !
Plattform UI is a complemtly new UI, some functionality was not transferred and maybe will not. What exactly do you mean be TREEVIEW and GRIDVIEW? Pease add reproducible steps and screenshots of what you are missing and why it is important if you want it discussed for re-implementation

**Comment by SchrodingersGat** [comment]
@gab696 fix incoming for this in https://github.com/inventree/InvenTree/pull/8802 

Please open a new issue for any other bugs, as this one will be closed out when #8802 is merged
