### ISSUE TITLE
Broken API doc url

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#881]
[In the doc](https://inventree.github.io/docs/extend/api), it says to access `api-doc/` but it redirects to `index/`.

I did `make docs` and still no luck.

**Comment by SchrodingersGat** [comment]
It should work as you posted - I just confirmed this on my install:

e.g. if the server is `http://localhost:8000/` then the docs are `http://localhost:8000/api-doc/`

(Don't forget the trailing slash, it is required!)

**Comment by eeintech** [comment]
Ouch you are right, I was missing the trailing slash, grrr. Sorry for the trouble, I'll close the ticket :)
