### ISSUE TITLE
do you have a discord server or a way to chat

### ISSUE THREAD

**Issue by JunkyardCat** [inventree/InvenTree#885]
Not exactly a bug or issue but do you happen to have a server or an easier way to chat? If not are you plannjng on creating one?

**Comment by SchrodingersGat** [comment]
No, I do not have that (and no plan to make one). Given the project size at the moment I'd rather keep all discussion centralized here.

**Comment by lobra07** [comment]
i advice of a discord server this will let people talk to each other and help them setup the program to be able to use it 
you just set  it up and people will connect there self

**Comment by matmair** [comment]
Discord is a great time sink that forces you to repeat the information again and again - all while being not searchable by search engines. Additionally, you need moderators to keep the users safe from spam/phishing – I do not see how that makes sense from a maintainer view

From: lobra07 ***@***.***>
Reply to: inventree/InvenTree ***@***.***>
Date: Wednesday, 3. January 2024 at 19:39
To: inventree/InvenTree ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [inventree/InvenTree] do you have a discord server or a way to chat (#885)


i advice of a discord server this will let people talk to each other and help them setup the program to be able to use it
you just set it up and people will connect there self

**Comment by lobra07** [comment]
understandable  now
