### ISSUE TITLE
Build Function Does Not Work

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#893]
I just did a build at a quantity of 1 for a BOM of mine. There is now a quantity of 1 for this part/assembly in my finished goods box according to InvenTree. That is good and correct. However, I checked the quantities of the (sub)parts that made up this assembly and InvenTree did not subtract the number of parts used. What is going on?
--Regards, Larry

**Comment by SchrodingersGat** [comment]
Hi Larry,

Did you assign the sub-parts to the build before completing the build? This is a manual process - you have to specify which sub-parts are going to be used to make the new part. If that step is completed, then the sub-parts will be subtracted from stock.

If you have not assigned parts to the build, the build will be completed without actually taking any sub-parts out of stock.

**Comment by LarryJoy** [comment]
Yes Oliver,
I assigned all sub-parts in my BOM. There are something like 67 sub-parts including drawings/documents that are virtual parts and have a quantity of zero (0).
--Larry

**Comment by SchrodingersGat** [comment]
I've tried to replicate the issue on my end but the quantities are being properly removed from the sub-parts. Can you provide some further information or some screenshots of the issues?

**Comment by LarryJoy** [comment]
Oliver,
Might the following be the problem? At the top of the BOM there are two statements:
• In yellow background is "The BOM for 10017-6KIT | Top ASSY Audio Interface II | 10017E does not have complete pricing information".
• In what appears to be a red background is "The BOM for 10017-6KIT | Top ASSY Audio Interface II | 10017E has not been validated".
--Larry

**Comment by eeintech** [comment]
I just tested this too with an unvalidated BOM. While the stock item for the sub-parts is updated, the stock number in the Parts tab view is not:

![image](https://user-images.githubusercontent.com/4020546/92118102-a28c6a80-edbb-11ea-9808-568e51cbfb25.png)

![image](https://user-images.githubusercontent.com/4020546/92117968-7e308e00-edbb-11ea-8478-88fe053f9eca.png)

![image](https://user-images.githubusercontent.com/4020546/92118295-eaab8d00-edbb-11ea-8b11-f63ca1ffa33b.png)

@SchrodingersGat See last screenshot, that's the only issue I could find.

**Comment by SchrodingersGat** [comment]
@LarryJoy I think that the incorrect reported stock in the screenshot above is caused by a different bug that I just fixed - https://github.com/inventree/InvenTree/pull/965

Please update to the latest code and let me know if the issue has been fixed - thanks!

**Comment by LarryJoy** [comment]
Oliver,
In the screenshot above I was not the one who reported this, it was "eeintech". However, I did try to update to the latest code and got terrible results. My crib sheet of instructions to update InvenTree is as follows:
• Run from "~/InvenTree-master/inventree" (root directory)
1. Stop InvenTree Server (Ctrl-C), if running.
2. Update Source Code 'git pull origin master'.
3. Perform DataBase Migrations 'make update'.
4. Restart Server.
The 'git pull origin master' step seemed to work, many lines of code.
When I did 'make update' I got "make: *** No rule to make target 'update'. STOP."
I don't know what the problem is as this has worked for previous updates.
I can't get into the InvenTree program now as the following is what I get:
(inventree-env) larry@larry-MS-7693:~/InvenTree-master/inventree/InvenTree$ python manage.py runserver 127.0.0.1:8000
InvenTree running in DEBUG mode
MEDIA_ROOT: /home/larry/InvenTree-master/inventree/inventree_media
STATIC_ROOT: /home/larry/InvenTree-master/inventree/inventree_static
2020-09-07 14:15:28,489 DEBUG Using selector: EpollSelector
InvenTree running in DEBUG mode
MEDIA_ROOT: /home/larry/InvenTree-master/inventree/inventree_media
STATIC_ROOT: /home/larry/InvenTree-master/inventree/inventree_static
2020-09-07 14:15:29,190 DEBUG Using selector: EpollSelector
Watching for file changes with StatReloader
2020-09-07 14:15:29,496 INFO Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/larry/InvenTree-master/inventree/InvenTree/label/models.py", line 11, in <module>
    from blabel import LabelWriter
ModuleNotFoundError: No module named 'blabel'

What is going on?
--Larry

**Comment by SchrodingersGat** [comment]
@LarryJoy the install system has been updated to use `invoke` rather than `make`.

- It is more configurable and powerful
- Inventree now only has a requirement to install python for easier install on windows

So please run the following commands:

`pip install invoke`

and then

`invoke update`

## References

https://inventree.github.io/docs/start/install#invoke
https://inventree.github.io/docs/start/update

**Comment by LarryJoy** [comment]
Oliver, I run Ubuntu 18.04 LTS and here are my entries and responses:
larry@larry-MS-7693:~$ pip install invoke
Command 'pip' not found, but can be installed with:
sudo apt install python-pip---***This I did***
Then at my entry of 'invoke update' I got "Command 'invoke' not found, but can be installed with:"
'sudo apt install python-invoke'
'sudo apt install python3-invoke'---***Which should I use?***
--Larry

**Comment by eeintech** [comment]
@LarryJoy I think you missing to run the `pip install invoke` once more after you ran `sudo apt install python-pip`.
Also make sure you've created a Python virtual environment first.

**Comment by LarryJoy** [comment]
Sorry for being dense and not understanding. I am not a programmer or software engineer and I need explicit instructions. The reason I mentioned that I use Ubuntu 18.04 LTS is to let you know the OS I am using--not Windows or Mac. I know Python exits and that is it. Just how do I check for a Python virtual environment (it may already exist), how do I create a Python virtual environment, and where should it exist (directory/path)? I liken your instruction, "Also make sure you've created a Python virtual environment first" to telling someone to change a tire on your car without telling them where the spare tire is, where the lug wrench is, and where the jack is.

I read over the reference <https://inventree.github.io/docs/start/update> and it has slightly different instructions in that these terminal commands should be done at the root directory level, which for me is ~/InvenTree-master/inventree. Again, I need explicit instructions and in proper order.
--Thank you and regards, Larry

**Comment by eeintech** [comment]
@LarryJoy I do understand the difficulty of starting with python, however @SchrodingersGat wrote a very comprehensive `Getting Started` page that if you follow step-by-step should lead you to a successful result: https://inventree.github.io/docs/start/install

I'd advise you to restart from scratch:
- backup any work
- remove all files from current folder (or create a fresh folder)

Python virtual environment are used to isolate any project dependencies from the rest of your system. It will basically create some sort of "container" environment for the InvenTree application and won't mess with other python applications you may have running on your system. Make sure to not oversee this step from the installation guide: https://inventree.github.io/docs/start/install#python-virtual-environment

If you still have difficulties, please point to the step in the installation guide which did not succeed on your machine and send the error details your are getting.

**Comment by SchrodingersGat** [comment]
Continues in https://github.com/inventree/InvenTree/issues/989
