### ISSUE TITLE
Supplier List and Manufacturer List

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#894]
These two lists are not in alphabetical order, making it difficult to pick the one I need. Can these two lists be put in alpha numeric order?
--Larry

**Comment by SchrodingersGat** [comment]
Do you mean this list here:

![image](https://user-images.githubusercontent.com/10080325/89693752-bf678680-d952-11ea-9959-208857e2d3bb.png)

This *is* listed alphabetically by default. Or is it a different supplier listing you mean?

**Comment by LarryJoy** [comment]
When I add a new part the first item to input is the supplier. When I click on "New Supplier" my supplier list is not in alphabetical order. Same thing for inputting the manufacturer for a new part, my list of manufacturers is not in alphabetical order.
--Larry

**Comment by SchrodingersGat** [comment]
Ah OK i see what you mean, should be fixed in #896
