### ISSUE TITLE
Include test results in stock grid and filters

### ISSUE THREAD

**Issue by Kedarius** [inventree/InvenTree#917]
It would be great if user would be able to show test results in the stock grid and be able to filter by them. For example filter: all items with all tests passed or items with failed specific test(s),.....

**Comment by SchrodingersGat** [comment]
Similar to https://github.com/inventree/InvenTree/issues/821

**Comment by eeintech** [comment]
@Kedarius Would #821 meet your requirement?

**Comment by eeintech** [comment]
@SchrodingersGat I would close and keep #821 as reference

**Comment by SchrodingersGat** [comment]
Duplicate of #821
