### ISSUE TITLE
Create new Stock item form: selecting "Base Part" won't refresh "Supplier Part" list

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#920]
Base part selected:
![image](https://user-images.githubusercontent.com/4020546/90819501-ae752880-e2f5-11ea-8225-024f62850849.png)

"Submit" button clicked:
![image](https://user-images.githubusercontent.com/4020546/90819768-00b64980-e2f6-11ea-953d-d032f6dcdad0.png)

Maybe a 2-step form?
1. Select base part, stock location, etc.
2. Select supplier part

**Comment by SchrodingersGat** [comment]
This is potentially a difficult one to solve. Currently these modal forms are served "once", and then re-computed every time the form is submitted.

What would be nice is to have some sort of AJAX layer in the middle, where certain fields can be marked as "dynamic" (i.e. updating these fields causes other fields to be updated also). Ideally this would be reasonably abstract so it does not have to be "hacked" into each case where it is useful.

There some documentation on how the forms work [here](https://inventree.readthedocs.io/en/latest/forms.html) - this would be a good starting point. 

It feels like this would be a job for some front-end javascript code which is called whenever a tagged field is updated

**Comment by eeintech** [comment]
Thanks for getting back on this, sounds like a good challenge. I'm not so familiar with JS so I hope someone can pick it up!

**Comment by SchrodingersGat** [comment]
Someone did!

**Comment by eeintech** [comment]
Haha who better than @SchrodingersGat!
