### ISSUE TITLE
/api-doc/ Missing docs for customer CRUD operations

### ISSUE THREAD

**Issue by amishHammer** [inventree/InvenTree#922]
There is no documentation in the /api-doc/ interface for creating a customer so right now it is impossible to sync a sales order via the API As you first have to create the customer.

**Comment by SchrodingersGat** [comment]
A "customer" is just a Company that has the `is_customer` field set to True. So you use the Company API endpoint to create a Customer:

![image](https://user-images.githubusercontent.com/10080325/90855182-4e988380-e3c2-11ea-83f7-b27661d86d63.png)

**Comment by amishHammer** [comment]
I think you need to put some information here that tells people that the customer field references the company objects.

![image](https://user-images.githubusercontent.com/971788/91583497-ec3a0880-e916-11ea-845d-ef25f5948f92.png)
