### ISSUE TITLE
issue with importing from a CSV file containing parts

### ISSUE THREAD

**Issue by zinka** [inventree/InvenTree#951]
Hi ... I followed the installation instruction provided on the documentation page and am able to run development version of inventree on my localhost. All features (like parts, categories, etc) are working fine except I am unable to import multiple parts using csv file. I created one part manually to export a "template", and used it to upload a few other parts. However, I am always seeing the message "Import finished, with 0 new and 0 updated Parts." (in the uploading csv file I have changed ID and IPN to create a new dummy part). Am I missing something? My "staff status" is enabled in the admin area.

**Comment by SchrodingersGat** [comment]
What version of InvenTree are you running? (You can see this in the drop-down menu in the top right-hand corner).

Also, when you upload a file, and hit "submit" (see below) does it show a preview of the new data that will be imported?

![image](https://user-images.githubusercontent.com/10080325/91994160-9bdd0380-ed79-11ea-9565-d904444c6fb2.png)

e.g. when I try to upload a .xlsx file (which contains invalid data, as shown in red) the following preview screen is displayed:

![image](https://user-images.githubusercontent.com/10080325/91994253-c16a0d00-ed79-11ea-932e-91ef814a174b.png)

**Comment by zinka** [comment]
I am using "0.1.3 pre" with "2020-09-01" as the commit date. My OS is Lubuntu 20.04. This is the screenshot of the downloaded csv file which I used as template

![csv_file](https://user-images.githubusercontent.com/380465/91997589-e2216b00-ed57-11ea-977c-44cbb2817cc4.jpg)

I have added one dummy part in the last row ensuring ID and IPN are unique. When I uploaded (after removing first row containing part parameters) this file the following screen appears:

![screen05](https://user-images.githubusercontent.com/380465/91998109-77246400-ed58-11ea-9d6f-bfef1ead14c4.jpg)

By the way, when I tried to do the same using xlsx file, Inventree is hanging as shown below:

![screen07](https://user-images.githubusercontent.com/380465/91998497-ea2dda80-ed58-11ea-881a-77d2dcf974d3.jpg)

**Comment by SchrodingersGat** [comment]
## Red Errors

There are a couple of "errors" indicated by the red squares. What do they say when you mouse-over?

## ID Field

To add a "new" entry you actually have to leave the ID field blank, not create a new ID.

**Comment by zinka** [comment]
Hi ... I reinstalled inventree with the latest master branch (commit hash 11b75132). Also, I didn't populate ID column as you suggested. Now, the import feature is working. Thank you very much for this great piece of software. I could see that you are working hard fixing bugs, implementing new features, etc. If any help is needed in the documentation part, please let me know.

Red Errors: those are not errors. I was just highlighting those fields in excel software.

**Comment by SchrodingersGat** [comment]
Ah, great! Glad to hear that it's working for you now :)

> If any help is needed in the documentation part, please let me know.

Documentation help would be *greatly* appreciated. Documentation repo is https://github.com/inventree/inventree.github.io
