### ISSUE TITLE
Report templates should have templated filenames

### ISSUE THREAD

**Issue by jnewlands** [inventree/InvenTree#958]
For example:

`{{part.IPN}} SN{{stock_item.serial}} acceptance report.pdf`

**Comment by matmair** [comment]
@jnewlands still interested in this?

**Comment by SchrodingersGat** [comment]
This has actually been implemented already:

https://github.com/inventree/InvenTree/blob/120870712ae9c0fd22200ffd51e19b9efaee6be6/InvenTree/report/models.py#L289
