### ISSUE TITLE
Generating a test report should automatically attach a copy against the stock item

### ISSUE THREAD

**Issue by jnewlands** [inventree/InvenTree#960]
Perhaps this could be optional. Mainly for traceability purposes.

**Comment by matmair** [comment]
Sounds nice but could create a lot of files. Maybe we need to create a dashboard for that.

**Comment by SchrodingersGat** [comment]
This might be a good candidate for a plugin. Will close out for now, this has been hanging around for a while and I know that @jnewlands is no longer interested in it.

**Comment by SchrodingersGat** [comment]
This has actually come up as a requirement again, will implement for `0.8.0` as an optional feature (default=disabled)
