### ISSUE TITLE
[BUG] Part deletion is hidden behind another div

### ISSUE THREAD

**Issue by tionebrr** [inventree/InvenTree#967]
![image](https://user-images.githubusercontent.com/8854321/92330292-105fbd00-f06e-11ea-99d9-dcd260a34825.png)

**Comment by SchrodingersGat** [comment]
I've been playing around with the CSS trying to get it to display, without much success so far.

**Comment by eeintech** [comment]
@SchrodingersGat What about adding `padding-bottom: 60px;` to:
```
.media-body {
    padding-top: 10px;
    padding-bottom: 60px;
    overflow: visible;
}
```

It does create a bit more spacing between top and bottom part detail elements but does show the delete menu entry:

![image](https://user-images.githubusercontent.com/4020546/92419129-22566400-f131-11ea-80e8-ecd84c825683.png)

**Comment by SchrodingersGat** [comment]
I would like to find a solution which:

a) Does not increase padding
b) Allows the dropdown menu items to appear "over" other content

Just extending the padding means that when another menu item is added, the problem resurfaces. I'm sure there is a good CSS solution to this.

**Comment by eeintech** [comment]
@SchrodingersGat What did you go with?

**Comment by SchrodingersGat** [comment]
One of the higher-level css elements had `overflow: hidden;` set which was preventing the menu from displaying properly
