### ISSUE TITLE
[BUG] Part activation toggle button is reversed

### ISSUE THREAD

**Issue by tionebrr** [inventree/InvenTree#968]
After toggling the Active toggle, the button is acting weird and reversed.

![image](https://user-images.githubusercontent.com/8854321/92330372-9ed43e80-f06e-11ea-97b5-4735ee9b3c39.png)

**Comment by SchrodingersGat** [comment]
Huh that's odd.

a) When you toggle the button, does the page reload?
b) When you manually reload the page, does the button work as expected?

**Comment by tionebrr** [comment]
a. IIRC, the page reload when I toggle the button.
b. The button is still inverted after a reload.

I didn't tried on Chrome and have other problems on other ERP soft with firefox.

**Comment by SchrodingersGat** [comment]
So just to clarify, what browser were you testing this with?

**Comment by tionebrr** [comment]
Firefox.
Will edit above to clarify.

**Comment by SchrodingersGat** [comment]
Ok, worked it out! That was a pretty strange  one... the browser was trying to autocomplete the checkbox...

**Comment by tionebrr** [comment]
Oh yeah, that might have been nasty. 
Thanks for the good work 👍
