### ISSUE TITLE
Is it possible to change main css?

### ISSUE THREAD

**Issue by Kedarius** [inventree/InvenTree#969]
I've created little more darker CSS. Is it possible to somehow use it via config or some settings so it will not conflict on upgrade?
If anyone is interested:
[inventree-darker.zip](https://github.com/inventree/InvenTree/files/5182314/inventree-darker.zip)

**Comment by SchrodingersGat** [comment]
I kinda like that! I would like to be able to support "theming" via custom CSS, with perhaps some "inbuilt" themes too. I'd have to look into some potential approaches to allowing this as a configurable setting. Or if you can suggest a way, or anyone else wants to weigh in?

**Comment by Kedarius** [comment]
I did try to look into it a little but my knowledge of django framework is limited. I would find best option to have config setting which CSS file to use. Then you could include more CSS files in your repository and system administrator could choose which one to use.

**Comment by eeintech** [comment]
I had the same thought not long ago, I do prefer darker themes too.
I thought of giving it a shot, still in the process: https://github.com/eeintech/InvenTree/tree/color_themes

![image](https://user-images.githubusercontent.com/4020546/92415206-7a836b00-f11d-11ea-977b-89eac021fb72.png)

![image](https://user-images.githubusercontent.com/4020546/92415194-6e97a900-f11d-11ea-848e-5b7fbb052df5.png)

I would like the color theme setting to be available to any user, not only the admin. But in what I have now, when the theme changes it is changed for all users, I would make it a "per user" change in my next step.

**Comment by Kedarius** [comment]
Thank you, it looks great. For me it would be sufficient to have system wide setting but setting per user is fantastic. The reason why I needed this and why I created the darker CSS is to make Inventree more usable in "less comfortable" workplaces not to make it look nicer.  

By "less comfortable" workplace I mean worktables with tools, soldering station, hotair, lamps, etc where the screen is somewhere on the side, the mouse is buried somewhere deep under cables, etc....

**Comment by eeintech** [comment]
@Kedarius Sounds good to me, I don't think it would hurt to get some color customization :smile: 

In my latest effort, I added a complete dark mode: #970 

Which will probably be my default if @SchrodingersGat is on-board!
