### ISSUE TITLE
can not install InvenTree on a web hosting account?

### ISSUE THREAD

**Issue by humansoft** [inventree/InvenTree#97]
Hi, everybody.
I am trying to install InveTree on my web server.
I have now installed Python version 3.6.5.
However, because I am a beginner, I am looking for a detailed step-by-step guide to installing Invetree, but I have not been able to find it.
I looked for a manual on how to install it here, but it was just a vague description.
So I need step by step instructions.
For example, can not install InvenTree on a web hosting account?
Can you help me a little bit?
Thank you.

**Comment by SchrodingersGat** [comment]
Inventree is still very much a work in progress - such instructions are not available yet. Hopefully soon!
