### ISSUE TITLE
Acceptable values for tests

### ISSUE THREAD

**Issue by jnewlands** [inventree/InvenTree#971]
At the moment the determination of whether a test is pass/fail is a switch in the 'add test result' dialog. But can easily see a use case for specifying the acceptable value in the part and evaluating pass/fail (perhaps overridable) at the point of adding test data.

- A part might require different configurations for each variant part
- Two tests might be linked (firmware version and firmware checksum) against a table of acceptable releases

**Comment by matmair** [comment]
@jnewlands any work on this? I will close this for now. Feel free to reopen if this is still of interest. If you can spare 5 minutes I would appreciate if you could open a new issue and fill out the feature request template.
