### ISSUE TITLE
CreateBomItem form is slow

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#979]
Takes *ages* to load the CreateBomItem form

- perhaps the background calculations are taking too long?
- look at the BOM recursion calculation?

**Comment by eeintech** [comment]
@SchrodingersGat I don't have this problem, neither with SQLite or PostGreSQL databases, the form loads and shows rather quickly...

**Comment by SchrodingersGat** [comment]
@eeintech good to hear it's responsive on your end. Might be something about my particular setup, I have some pretty deep level BOMs with *lots* of parts...

**Comment by eeintech** [comment]
@SchrodingersGat Gotcha, hopefully you can figure this out 😄
