### ISSUE TITLE
Listing BOM items fails to load

### ISSUE THREAD

**Issue by wolffam** [inventree/InvenTree#983]
I have a single layer BOM (1 component under 1 assembly) that is failing to load.  Looks like some recursive call that never returns out.  Any help with this one?  I'm not even sure where I would start the debugging as I don't understand how the bootstrap table treegrid is getting used.

<img width="1433" alt="Screen Shot 2020-09-18 at 10 54 52 AM" src="https://user-images.githubusercontent.com/11801197/93629608-70732f00-f99d-11ea-8a39-f29ab264bb3b.png">

**Comment by SchrodingersGat** [comment]
Can you show me what is happening in the "network" tab of the developer interface. Is the table making multiple API requests?

**Comment by SchrodingersGat** [comment]
It doesn't appear that the page is requesting too much data from the server. Only one XHR query is being sent (which is as expected for a flat BOM).

Can you please find the entry that looks like `?part=`&...`

![image](https://user-images.githubusercontent.com/10080325/93668976-d5c93c00-fad3-11ea-824d-ac09c499492b.png)

and show what the response content is? It should look like JSON data

Cheers

**Comment by wolffam** [comment]
The JSON looks normal and as expected to me:
`[{"pk": 1, "part": 1, "sub_part": 2, "sub_part_detail": {"pk": 2, "IPN": null, "name": "component", "revision": null, "full_name": "component", "description": "component description", "thumbnail": "/static/img/blank_image.thumbnail.png", "active": true, "assembly": false, "is_template": false, "purchaseable": false, "salable": false, "stock": 3.0, "trackable": true, "virtual": false}, "quantity": 1.0, "reference": "", "price_range": null, "overage": "", "note": "", "validated": true}]`

**Comment by SchrodingersGat** [comment]
And what version of InvenTree are you running?

![image](https://user-images.githubusercontent.com/10080325/93690074-c8ce3c00-fb17-11ea-9955-2990d5bfb3c7.png)

![image](https://user-images.githubusercontent.com/10080325/93690081-d4216780-fb17-11ea-9078-a4809079f710.png)

![image](https://user-images.githubusercontent.com/10080325/93690084-daafdf00-fb17-11ea-81c3-0eaf1b213d2d.png)

**Comment by wolffam** [comment]
<img width="842" alt="Screen Shot 2020-09-19 at 3 06 42 PM" src="https://user-images.githubusercontent.com/11801197/93690144-c91ff600-fa89-11ea-930e-540ed2af566b.png">

**Comment by wolffam** [comment]
Hmm I can't seem reproduce the issue.  I'll reopen if I can repro
