### ISSUE TITLE
Search and filter by non-integer serial

### ISSUE THREAD

**Issue by Kedarius** [inventree/InvenTree#985]
It would be nice if the "main search" option on the toolbar did work with non-integer serials. Also it would be great to have a filter to match the serial number, not only GTE and LTE.

**Comment by SchrodingersGat** [comment]
Ref: https://github.com/inventree/InvenTree/issues/899

**Comment by Kedarius** [comment]
Just a note: the search using serial number is working in the search field near the stock table. I tried to look into it but my experience  with Django is very small and I was not able to find the code/query for the search at all :-(

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/pull/986 now lets you filter tables by exact serial number match, also

**Comment by Kedarius** [comment]
Wow, that was fast.... And it is working great, thank you

**Comment by SchrodingersGat** [comment]
The main search bar (top right) now lets you search for stock (and you can search by serial number and/or batch code, too)
