### ISSUE TITLE
Build Function Still Does Not Work

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#989]
As far as I know I carried out your instructions to get and install Python and updated InvenTree to the latest revision. I then created a BOM for a 3-item assembly, which I validated. Here is the screenshot.
![image](https://user-images.githubusercontent.com/18520951/93686543-e56d6400-fa84-11ea-944c-7fcdcdd49db4.png)

I then went to the Build Orders tab and entered the information to build one and where to put the finished good. Here is the screenshot.
![Build](https://user-images.githubusercontent.com/18520951/93687462-3df42f80-fa8c-11ea-8af1-0737dd4232c7.png)

The build did not subtract the subparts used from inventory as the following three screeshots of the three items (subparts) shows.
![Case](https://user-images.githubusercontent.com/18520951/93687610-e7d3bc00-fa8c-11ea-8922-85e6746cca19.png)
![FrontPanel](https://user-images.githubusercontent.com/18520951/93687617-f91cc880-fa8c-11ea-8b98-466f61ce4155.png)
![RearPanel](https://user-images.githubusercontent.com/18520951/93687628-076ae480-fa8d-11ea-83d9-d67b97c6d3a6.png)

The following screenshot is the Details tab for the Rear Panel to show the selections of the right side criteria of Virtual, etc.
![FPdetails](https://user-images.githubusercontent.com/18520951/93687687-852ef000-fa8d-11ea-9dd9-968aeb548ee6.png)
The questions I have are:
• What do I need to do to get the build function to work properly so it will remove subpart stock quantity used?
• There is cost associated with the parts I used but this is because I was able to put pricing breakdown information previously when I was able to get to the price breakdown screen, but now I can't get to it. How do I get to the part price breakdown screen?
--Larry

**Comment by wolffam** [comment]
Hi Larry,
When you created a new build, did you "allocate" the subparts before completing the build?

**Comment by LarryJoy** [comment]
I was wondering about the "Allocation" tab, but when I went to the documentation it said "To Do". Tell me how it works and what I need to do. If each subpart needs to be "allocated" individually that is going to be a lot of manual work and would, of course, grow with the number of different parts on a BOM.
--Larry

**Comment by wolffam** [comment]
Play around with it a little bit.  You can use "Auto Allocate" which should do what you what.  As long as your subparts are not trackable, all of the subparts should allocated.  Once you have all the subparts allocated, then you can complete the build and the stock should be adjusted

**Comment by LarryJoy** [comment]
wolffam, Again, sorry to be so dense, I need a little more instruction. I don't see anywhere the "Auto Allocate" function. Do I do this in the assembly I am trying to build or do I have to go to each subpart in the BOM? Here is a screenshot of one of my subpart's "Allocated" tab from my BOM:
![image](https://user-images.githubusercontent.com/18520951/93716978-c3d1b280-fb40-11ea-8041-f7ef07359b26.png)
I don't see any functionality here of any kind. Please explain.

**Comment by wolffam** [comment]
Assuming you have at least 2 Parts (1 a subpart/component and 1 an assembly) and have updated the assembly's BOM (in the Part tab)....then you can perform the following:

1. Go to the **Build** tab and hit **New Build Order**
2. Choose your assembly part for **Part** and finish that form
3. Find the **Allocated Parts** button circled in red in the screenshot below
<img width="700" alt="Screen Shot 2020-09-20 at 10 34 16 AM" src="https://user-images.githubusercontent.com/11801197/93717807-07222600-fb2d-11ea-8107-81c9d515eb68.png">
4. You can allocated parts using **Auto Allocate** (if your subparts are not serialized/trackable) or use the green plus to allocate manually.  See the screenshot for locations of those buttons
<img width="700" alt="Screen Shot 2020-09-20 at 10 34 59 AM" src="https://user-images.githubusercontent.com/11801197/93717821-1acd8c80-fb2d-11ea-80de-3b8f1af5b2b4.png">
5. Once fully allocated, it should look like the screenshot below.  You can hit the **Complete Build** button and that should adjust the stock as you are expecting.
<img width="1408" alt="Screen Shot 2020-09-20 at 10 37 44 AM" src="https://user-images.githubusercontent.com/11801197/93717918-9cbdb580-fb2d-11ea-84bd-2d4fba8203cb.png">

In general, I figured most of this out by playing around with the system.  Set up some mock parts (assemblies and components) and play around with things.  This project seems to still be in its beginnings so the official documentation can't really be set in stone since it would most likely change from month to month.

**Comment by LarryJoy** [comment]
Wolffam, It didn't work! Here is the screenshot when I picked on "Auto Allocate":
![image](https://user-images.githubusercontent.com/18520951/93722240-5c792a00-fb63-11ea-87bd-5324b261f9ec.png)
It says can not allocate because there are none in stock (my interpretation)? That is an incorrect statement, there are 9 pcs of each of the three subparts (items) in stock. What is going on? And what does it mean by "Stock items are selected for automatic allocation if there is only a single stock item available"? What? That sounds like you have to reduce the stock quantity to one in order for it to work, but that wouldn't be right. I tried picking on the green "+" for each of the three subparts and got the same thing.
--Larry

**Comment by SchrodingersGat** [comment]
Hi Larry,

> And what does it mean by "Stock items are selected for automatic allocation if there is only a single stock item available"?

Auto-allocation is intended to reduce the burden of manually assigning stock to a build. If (**and only if**) there is a single stock item available for a part required for a build, the auto-allocation algorithm knows that it can assign *that* stock item. 

However if there are multiple stock items available, it does not *guess* which one to assign - that is up to the user to manually assign.

So if you are seeing the message above it means that (most likely) you have multiple stock items available for each part and so the system is not suggesting any of them for auto-allocation.

Does this make sense? Do you have multiple stock items available for your parts?

**Comment by wolffam** [comment]
And if that's the case, you'll need to manually allocate them (with the green plus button on the right side)

**Comment by LarryJoy** [comment]
Thank you for the explanation. But no, there are not multiple suppliers or multiple stock items. All three of my subparts (items) are single sourced. And as I mentioned in my previous comment that I tried the green "+" to manually allocate the three parts and I got the same message back for all three parts to the effect that there were none available?
--Larry

**Comment by SchrodingersGat** [comment]
That's odd. Can you share a screenshot of the detail view of one of these single-sourced stock items?

**Comment by LarryJoy** [comment]
Here you go.
![image](https://user-images.githubusercontent.com/18520951/93723308-92baa780-fb6b-11ea-8917-9fc04b640ff6.png)
--Larry

**Comment by SchrodingersGat** [comment]
Can you also show me what is on the Stock tab?

![image](https://user-images.githubusercontent.com/10080325/93723368-5fb2fb00-fbe1-11ea-9722-2daaf1aa6121.png)

**Comment by LarryJoy** [comment]
Here you go.
![image](https://user-images.githubusercontent.com/18520951/93723451-a286bb80-fb6c-11ea-9fb8-8ed1e50c9bd4.png)
--Larry

**Comment by SchrodingersGat** [comment]
That all looks good.

One final thing - can you show me what version of InvenTree you are running?

![image](https://user-images.githubusercontent.com/10080325/93723499-4fe7e680-fbe2-11ea-8e13-e48ada653641.png)

![image](https://user-images.githubusercontent.com/10080325/93723508-58d8b800-fbe2-11ea-8f3b-2685d0518ee1.png)

**Comment by SchrodingersGat** [comment]
The build / allocation process is working for me on the latest code version, I wonder what could be going on here

**Comment by SchrodingersGat** [comment]
For reference this is what the allocation page looks like on a sample build (for me)

![image](https://user-images.githubusercontent.com/10080325/93723549-aa814280-fbe2-11ea-9caf-f6ecbcbb9536.png)

**Comment by LarryJoy** [comment]
Version of InvenTree:
![image](https://user-images.githubusercontent.com/18520951/93725282-fd73df00-fb7b-11ea-84e8-73be0bdaf3d4.png)
--Larry

**Comment by SchrodingersGat** [comment]
Ok, thanks. That's a relatively recent commit - and I do not see any glaring differences between that point and the latest code that should be causing the problems...

**Comment by SchrodingersGat** [comment]
Can you please click on the link shown below:

![image](https://user-images.githubusercontent.com/10080325/93725400-541c0000-fbf2-11ea-8c24-7738a210ea2b.png)

And screen-shot the detail view of the actual stock item itself

Thanks

**Comment by LarryJoy** [comment]
Again, here is the screenshot you asked for:
![image](https://user-images.githubusercontent.com/18520951/93726137-34e58a00-fb82-11ea-806d-ae74bd4be2e8.png)
--Larry

**Comment by SchrodingersGat** [comment]
@LarryJoy I have another theory which we have not explored yet.

> I then went to the Build Orders tab and entered the information to build one and where to put the finished good. Here is the screenshot.

`where to put the finished good`

I think you *might* have accidentally set the "source" location for the parts not the "destination".

Can you please provide a screenshot of the build detail page as exampled below:

![image](https://user-images.githubusercontent.com/10080325/93871407-f383e480-fd11-11ea-9511-f3cd8be94be2.png)

**Comment by LarryJoy** [comment]
Oliver,
Here is what I get at the Build Orders tab:
![image](https://user-images.githubusercontent.com/18520951/93883105-1d57ef80-fcaf-11ea-9faf-76e73b92935e.png)
Here is what I get for the "Complete" build:
![image](https://user-images.githubusercontent.com/18520951/93883838-1a113380-fcb0-11ea-87a4-5c598fd54a8c.png)
And here is what I get for the "Cancelled" build:
![image](https://user-images.githubusercontent.com/18520951/93884224-9dcb2000-fcb0-11ea-9713-cca8a7099cf1.png)
I see that the "Stock Source" entry is different between the two, but as I recall I got the same result in that the subparts quantities were not reduced. I guess I interpreted "Stock Source" to be where are the subparts coming from when the question really is where is the finished assembly going to be stocked. I don't know why the second build is cancelled other than there was something that came up that I didn't know how to answer and therefore I backed out of the build.
--Larry

**Comment by SchrodingersGat** [comment]
Try allocating items to a new build without a location in "stock source". I think this should be the problem.

**Comment by LarryJoy** [comment]
Okay Oliver,
That worked. I left the "Source Location" blank and continued. At the "Parent Build?" "Parent build to which this build is allocated" I left blank as this assembly stands on its own. I did the "Auto Allocate" and "Confirm" and then the "Now Allocated" column showed "1/1", instead of "0/1", for all three subparts. I clicked on the wrenches icon that says "Complete build". The assembly was "built" and showed a "BOM price", which was the sum of the subparts costs.

I checked the three parts and indeed the number in stock had been reduced by one for each of the three parts. Here is what I got for one of the subparts:
![image](https://user-images.githubusercontent.com/18520951/94301508-aa61a980-ff38-11ea-8cc6-093af955aed3.png)
All three subpaarts I got the same thing. I didn't quite understand the three lines with Stock of "9 (2 items)", then "8", and then "1". I guess this is how you keep track.

And now this brings on the question of how do you get to the price breakdown screen? I have another BOM that I want to do a build but one of the statements at the top of the BOM says "no pricing available". Again, going to the part stock screen there is no way of getting to the pricing screen, whereas before I was able to click on the part and the pricing screen would show up. The BOM function is getting the cost from somewhere, but I can't get to the somewhere.
--Larry

**Comment by eeintech** [comment]
@LarryJoy Looks like this issue can be closed, would you do me a favor and close it?

If you have any other issue using InvenTree, feel free to open a new one.

**Comment by LarryJoy** [comment]
This issue can now be closed. I only hope that when I attempt another build I can answer the questions correctly or in the one case to leave it blank.
--Larry
