### ISSUE TITLE
Add "copy to clipboard" button to table cells

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#997]
Like DigiKey, for example, add a button (which is only visible when you hover over a table cell) which copies the cell contents into the clipboard.

**Comment by cdplayer** [comment]
assistive info:
https://w3c.github.io/clipboard-apis/
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

https://clipboardjs.com/ 3kGZIPd library.

https://www.iconfinder.com/icons/326595/content_duplicate_copy_icon
https://thenounproject.com/term/copy-to-clipboard/3548032/
![image](https://user-images.githubusercontent.com/184022/96974287-5c05f180-155c-11eb-8938-cc0d23ef6e88.png)

**Comment by matmair** [comment]
I hacked this feature in 2 pages by hand
- a table
- a detail-page

and I find it makes using the table quite distracting as the button to copy always fades in.
My solution would be to add the copy function - using the great js library @cdplayer suggested - only to the detail-pages (see mock-up below - would be adjusted to fit the style)
@SchrodingersGat What is your opinion on that? Is this thing still relevant?

![grafik](https://user-images.githubusercontent.com/66015116/117555002-b0397480-b05b-11eb-85f1-e4945ad21eb6.png)

**Comment by matmair** [comment]
@SchrodingersGat should we close this now?

**Comment by matmair** [comment]
@SchrodingersGat do you consider this done or should additional functionality be implemented?

**Comment by SchrodingersGat** [comment]
Thanks for reminding me! Happy to close this one out now.
